--PSP_PSTUB_DDITEM
delete from PSPADM.PSP_PSTUB_DDITEM
where PSTUB_DDITEM_SEQ in (
    select PSTUB_DDITEM_SEQ from MCHOUBEY.PSP_PSTUB_DDITEM_TEMP_PSP_25432
);
commit;

--PSP_PSTUB_MSG
delete from PSPADM.PSP_PSTUB_MSG
where PSTUB_MSG_SEQ in (
    select PSTUB_MSG_SEQ from MCHOUBEY.PSP_PSTUB_MSG_TEMP_PSP_25432
);
commit;

--PSP_PSTUB_PAID_TIMEOFF_ITEM
delete from PSPADM.PSP_PSTUB_PAID_TIMEOFF_ITEM
where PSTUB_PAID_TIMEOFF_ITEM_SEQ in (
    select PSTUB_PAID_TIMEOFF_ITEM_SEQ from MCHOUBEY.PSP_PSTUB_PAID_TIMEOFF_ITEM_TEMP_PSP_25432
);
commit;

--PSP_PSTUB_PAY_ITEM
delete from PSPADM.PSP_PSTUB_PAY_ITEM
where PSTUB_PAY_ITEM_SEQ in (
    select PSTUB_PAY_ITEM_SEQ from MCHOUBEY.PSP_PSTUB_PAY_ITEM_TEMP_PSP_25432
);
commit;

--PSP_PAYSTUB
delete from PSPADM.PSP_PAYSTUB
where PAYSTUB_SEQ in (
    select PAYSTUB_SEQ from MCHOUBEY.PSP_PAYSTUB_TEMP_PSP_25432
);
commit;

--PSP_EFTPS_PAYMENT_DETAIL
delete from PSPADM.PSP_EFTPS_PAYMENT_DETAIL
where EFTPS_PAYMENT_DETAIL_SEQ in (
    select EFTPS_PAYMENT_DETAIL_SEQ from MCHOUBEY.PSP_EFTPS_PAYMENT_DETAIL_TEMP_PSP_25432
);
commit;

--PSP_VOIDED_CHECK
delete from PSPADM.PSP_VOIDED_CHECK
where VOIDED_CHECK_SEQ in (
    select VOIDED_CHECK_SEQ from MCHOUBEY.PSP_VOIDED_CHECK_TEMP_PSP_25432
);
commit;

--PSP_FSET_FILING_DETAIL
delete from PSPADM.PSP_FSET_FILING_DETAIL
where FSET_FILING_DETAIL_SEQ in (
    select FSET_FILING_DETAIL_SEQ from MCHOUBEY.PSP_FSET_FILING_DETAIL_TEMP_PSP_25432
);
commit;

--PSP_QBDT_TRANSACTION_INFO
delete from PSPADM.PSP_QBDT_TRANSACTION_INFO
where QBDT_TRANSACTION_INFO_SEQ in (
    select QBDT_TRANSACTION_INFO_SEQ from MCHOUBEY.PSP_QBDT_TRANSACTION_INFO_TEMP_PSP_25432
);
commit;

--PSP_QBDT_PAYLINE_INFO
delete from PSPADM.PSP_QBDT_PAYLINE_INFO
where QBDT_PAYLINE_INFO_SEQ in (
    select QBDT_PAYLINE_INFO_SEQ from MCHOUBEY.PSP_QBDT_PAYLINE_INFO_TEMP_PSP_25432
);
commit;

--PSP_FINANCIAL_TRANS_STATE
delete from PSPADM.PSP_FINANCIAL_TRANS_STATE
where FINANCIAL_TRANS_STATE_SEQ in (
    select FINANCIAL_TRANS_STATE_SEQ from MCHOUBEY.PSP_FINANCIAL_TRANS_STATE_TEMP_PSP_25432
);
commit;

--PSP_TAX_PAYMENT_ON_HOLD_REASON
delete from PSPADM.PSP_TAX_PAYMENT_ON_HOLD_REASON
where TAX_PAYMENT_ON_HOLD_REASON_SEQ in (
    select TAX_PAYMENT_ON_HOLD_REASON_SEQ from MCHOUBEY.PSP_TAX_PAYMENT_ON_HOLD_REASON_TEMP_PSP_25432
);
commit;

--PSP_TRANSACTION_OFFLOAD_BATCH
delete from PSPADM.PSP_TRANSACTION_OFFLOAD_BATCH
where TRANSACTION_OFFLOAD_BATCH_SEQ in (
    select TRANSACTION_OFFLOAD_BATCH_SEQ from MCHOUBEY.PSP_TRANSACTION_OFFLOAD_BATCH_TEMP_PSP_25432
);
commit;