SELECT /*+PARALLEL(16) */ count(EDI_PAYMENT_DETAIL_SEQ)
FROM PSP_EDI_PAYMENT_DETAIL epd,
     PSP_MONEY_MOVEMENT_TRANSACTION mmt
WHERE epd.MONEY_MOVEMENT_TRANSACTION_FK = mmt.MONEY_MOVEMENT_TRANSACTION_SEQ
  AND epd.COMPANY_FK is not null
  and epd.COMPANY_FK = mmt.COMPANY_FK
  and epd.EDI_PAYMENT_DETAIL_SEQ in
      (SELECT EDI_PAYMENT_DETAIL_SEQ FROM SKUMAR71.PSP_EDI_PAYMENT_DETAIL_TEMP);