
package com.intuit.ias.notification.pub.wsdl;

import javax.xml.ws.WebFault;
import com.intuit.ias.common.xsd.ErrorDataType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "Error", targetNamespace = "http://www.intuit.com/ias/common/xsd")
public class Fault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ErrorDataType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public Fault(String message, ErrorDataType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public Fault(String message, ErrorDataType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.intuit.ias.common.xsd.ErrorDataType
     */
    public ErrorDataType getFaultInfo() {
        return faultInfo;
    }

}
