
package com.intuit.ias.notification.pub.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import com.intuit.ias.common.xsd.HeaderDataType;
import com.intuit.ias.notification.pub.xsd.SendRequest;
import com.intuit.ias.notification.pub.xsd.SendResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "NotificationPort", targetNamespace = "http://www.intuit.com/ias/notification/pub/wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.intuit.ias.notification.pub.xsd.ObjectFactory.class,
    com.intuit.ias.common.xsd.ObjectFactory.class
})
public interface NotificationPort {


    /**
     * 
     * @param body
     * @param header
     * @return
     *     returns com.intuit.ias.notification.pub.xsd.SendResponse
     * @throws Fault
     */
    @WebMethod(operationName = "Send", action = "Send")
    @WebResult(name = "SendResponse", targetNamespace = "http://www.intuit.com/ias/notification/pub/xsd", partName = "body")
    public SendResponse send(
        @WebParam(name = "Header", targetNamespace = "http://www.intuit.com/ias/common/xsd", header = true, mode = WebParam.Mode.INOUT, partName = "header")
        Holder<HeaderDataType> header,
        @WebParam(name = "SendRequest", targetNamespace = "http://www.intuit.com/ias/notification/pub/xsd", partName = "body")
        SendRequest body)
        throws Fault
    ;

}
