
package com.intuit.ias.notification.pub.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "NotificationService", targetNamespace = "http://www.intuit.com/ias/notification/pub/wsdl", wsdlLocation = "file:/D:/dev/PSP/main/Gateways/Email/schema/notification.wsdl")
public class NotificationService
    extends Service
{

    private final static URL NOTIFICATIONSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.intuit.ias.notification.pub.wsdl.NotificationService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.intuit.ias.notification.pub.wsdl.NotificationService.class.getResource(".");
            url = new URL(baseUrl, "file:/D:/dev/PSP/main/Gateways/Email/schema/notification.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/dev/PSP/main/Gateways/Email/schema/notification.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        NOTIFICATIONSERVICE_WSDL_LOCATION = url;
    }

    public NotificationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NotificationService() {
        super(NOTIFICATIONSERVICE_WSDL_LOCATION, new QName("http://www.intuit.com/ias/notification/pub/wsdl", "NotificationService"));
    }

    /**
     * 
     * @return
     *     returns NotificationPort
     */
    @WebEndpoint(name = "NotificationPort")
    public NotificationPort getNotificationPort() {
        return super.getPort(new QName("http://www.intuit.com/ias/notification/pub/wsdl", "NotificationPort"), NotificationPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NotificationPort
     */
    @WebEndpoint(name = "NotificationPort")
    public NotificationPort getNotificationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.intuit.com/ias/notification/pub/wsdl", "NotificationPort"), NotificationPort.class, features);
    }

}
