DROP TABLE IF EXISTS TEMP_PSP_BANK_ACCOUNT CASCADE;

--------------------------------------------------------
-- Create temp table                                  --
--------------------------------------------------------

CREATE TABLE TEMP_PSP_BANK_ACCOUNT (LIKE PSP_BANK_ACCOUNT INCLUDING ALL) ;

--------------------------------------------------------
-- Adding new account_number_enc values               --
--------------------------------------------------------
-- DECODE(FN_GET_ENV(),'PROD',<account_number encrypted with prod key>,<account_number encrypted with preprod key>)
-- EXAMPLE :
-- DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACGNpcGt6Tzc3R4poiFDNR0O5TO6txAnbZJ/P2waC+ynBDw==','2gIAAAASAQAEAAAAAgIACHVGWHhPQldQ/T59B2ceS5Ys8QleT2aXlnW7/p0Y3OKPgg==')

--------------------------------------------------------
-- Insert into temp table                             --
--------------------------------------------------------

INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID ) VALUES (
'a5263743-7cf0-42fc-b164-25ea68315756',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Checking', 'Checking', 'JP MORGAN CHASE', '111000614', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACGNpcGt6Tzc3R4poiFDNR0O5TO6txAnbZJ/P2waC+ynBDw==' ELSE '2gIAAAASAQAEAAAAAgIACHVGWHhPQldQ/T59B2ceS5Ys8QleT2aXlnW7/p0Y3OKPgg==' END), NULL, NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID ) VALUES (
'a62f39f9-3aab-48ac-ace7-3ab8f700abb9',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Checking', 'Checking', 'JP MORGAN CHASE', '111000614', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACDRWdXlrSlNp5X831lieXNtaHeCnLlqGmdX8Lx2dkBxnmw==' ELSE '2gIAAAASAQAEAAAAAgIACHFSdC92VHE34xJAzEH/lJ4GsLv+iGLSkSuEC0wEYQKknQ==' END), NULL, NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID ) VALUES (
'89057491-baf0-49dd-bbda-a5c5eff5a7d9',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Checking', 'Checking', 'JP MORGAN CHASE', '111000614', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACFJHUUZCcm1WO80E63rpH7WVlmquGddIlGiJM7e5fF0HBA==' ELSE '2gIAAAASAQAEAAAAAgIACC9EdVN5N0gxipZ+YW3sLiyhou1nKg4S7fs2CFOWSD1bOw==' END), NULL, NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID ) VALUES (
'3b76af25-eb67-4409-a559-225a85eee4b9',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Checking', 'Checking', 'JP MORGAN CHASE', '111000614', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACCtsREJVL2Rs291ek1Yh8RZrPknAJsYFmpjahmAKhFF/qg==' ELSE '2gIAAAASAQAEAAAAAgIACFZFbUFtdHhtgwaZ9heigTh9ltV4g8O79zp8yALSrwRg8w==' END), NULL, NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID ) VALUES (
'3b76af25-eb68-4409-a559-225a85eee4b9',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Checking', 'Checking', 'JP MORGAN CHASE', '021000021', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACGdUU0ZFaGtmB3w2i31OVeVf/TsRDF8XOGrX1j/hoNB54w==' ELSE '2gIAAAASAQAEAAAAAgIACEpKVVVYVlowy6hdJa/y/aMKpGGNB9Cp2yyJSofi083vGg==' END), NULL, NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID ) VALUES (
'3b76af25-eb69-4409-a559-225a85eee4b9',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Checking', 'Checking', 'JP MORGAN CHASE', '021309379', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACDdXWkcxeUlFbLBELNmRp4LpIsF9/8qkwxTVWufj6RtM0g==' ELSE '2gIAAAASAQAEAAAAAgIACDNPeEZlcW5H2rLthBswWGyTmbIvJAhBiIPVH+d8kxLFOg==' END), NULL, NULL,'System')
;

-----------------------------------------------------------------------------------------------------------------
-- Inserting bank accounts for ACH Payments
-- *** DO NOT MAKE CHANGES TO BANK ACCOUNTS!  Create new bank accounts and new PaymentTemplateBankAccounts ***
-----------------------------------------------------------------------------------------------------------------

INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157567',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '091000022', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACHdtUTZKRXB28AjtAPL2RAU+ZTARATZEFYtYX2i/Q9mBvO9UUA==' ELSE '2gIAAAASAQAEAAAAAgIACDBJM3F0bUZUgn3C1UEdk82w7Li73QIm4f4reTAIOFsakpT19g==' END), NULL, NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157568',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '091000022', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACDZEQXd1L3Yyh6aSGqj50JWfLqDNpKWgKJMgeuGxAxJuj9MSCA==' ELSE '2gIAAAASAQAEAAAAAgIACE00REZubXVn/6GCoIFoEy65bbWw5dE+P0uiuQqwQ/kL7jic/w==' END), NULL, NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157569',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '052001633', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACGoyVHg5NnlGBSlW3cTkCz5TOxhy1bGPhvQ78vmQtb6W1C4=' ELSE '2gIAAAASAQAEAAAAAgIACGRHZjhDc2JNP3+el76TEPrEoQtSdzXUIHBOts2JsXanrdY=' END), NULL, NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315756a',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'Citi Bank', '021000089', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACCtIdlVCZGZRVkw1kNA/LcKQuzsLhTvKKS2BZXFBudQl' ELSE '2gIAAAASAQAEAAAAAgIACG10RFFVdFVrR2MsheNyqm56VhkqqM39OtTNpeu2gx91' END), NULL, NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315756b',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '031100209', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACEtaSXZNNnNsJ3SX0Js4gd2Y2ZKXPJMCWsf/tEFKTH8v' ELSE '2gIAAAASAQAEAAAAAgIACEhLeENMTG1Iv0UDkdNSCPs7PFm4FPZd9wNjk8XiMXVf' END), NULL, NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315756e',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '021052053', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACElwWnk4ejM0Y8PDzXoFkMtBUCdY7fSAfZ3IH5BQr8Lx' ELSE '2gIAAAASAQAEAAAAAgIACHpNRHBNemdW61e04sqd27vSlWjTePv7vHavvbS6aD5/' END), NULL, NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315756f',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '021052053', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACHJ2dXBHVUd2KEbrcGXR2HtEriPYOQqihFsA4Q2GWOoG' ELSE '2gIAAAASAQAEAAAAAgIACEI5aUprRzJKw4i3BbWMxrmo6KaB9FceSneUMlwSNdnf' END), NULL, NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'33e4fff0-3595-4d66-9150-06ddb79c2f60',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'US BANK', '021052053', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACGdGYUkzMEorSjWxnvsi1i92VeIhaVEBXxNC+n68o1fm' ELSE '2gIAAAASAQAEAAAAAgIACHFzdEhSa0pp5FLkSqwtQvj5x4I01jEOuAZx2U+9U5yj' END), NULL, NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157571',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '065400137', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACFFGRzFtMnBTD4X/DY+DmvN+1GsVsNIWwJ5cSiwTgvlVGn8=' ELSE '2gIAAAASAQAEAAAAAgIACHFndmMxRW1Oikvc4opm1ti/rnFMmr0EsRrpoaSxNgNz5gU=' END), NULL, NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157573',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '082000073', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACEM0aHQ1Y0hVMSKNm10FQbyIxQ197nxB446ALg+eXOt5M8g=' ELSE '2gIAAAASAQAEAAAAAgIACE41MXVYNGtmYEvVyPvmnzNl/oDuMOkEi7oQY5tlEor5Vjg=' END), NULL, NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157575',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '102001017', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACDZFZDRkYytaBYbr60WKNRDP6EtqDIQAknajJD+7GJPQwAQ=' ELSE '2gIAAAASAQAEAAAAAgIACFFDRlpKdjBoBnNaq9TiRIuHKcTXXC6+3LEx0R9sJ5Btz8Y=' END), NULL, NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ,VERSION,CREATED_DATE,MODIFIED_DATE,ACCOUNT_TYPE_CD,A_C_H_ACCOUNT_TYPE_CD,BANK_NAME,ROUTING_NUMBER,ACCOUNT_NUMBER_ENC,EFFECTIVE_DATE,EXPIRATION_DATE,CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157577',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking','Checking','JP MORGAN CHASE','121000248', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACEtFZ29wcmIzspKWJqoSW1iRQ8sxvSJglKXDorL4ErUAnPw=' ELSE '2gIAAAASAQAEAAAAAgIACDM5Z2o3YndP6UNLn49Qdl3he1WsGcWMylZa/LnE9GEcq9g=' END), NULL,NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157578',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '071109338', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACEJEeCtxMUU0oQ/d8utq5Nx2ot5z5TxGilRMV8Dlfg==' ELSE '2gIAAAASAQAEAAAAAgIACHJ0MWE5RG11Sn7OVYEdadQPKlKs5emYccLVBU/S9Q==' END), NULL, NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157579',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '123206707', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACFJVUjYzdmU4957CEgD+u22vIKCHCntOsvJRuDLqE2QliIQ=' ELSE '2gIAAAASAQAEAAAAAgIACHZaQ1pOajRO7lZ3VzBILBAlKL5D4CcsJ+nJKZoZ3Ec94To=' END), NULL, NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315757a',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '043000096', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACCtaSm1iQ1F0Z32W0okENbu0XXjbOp+yd8DoyBn9o0btCQY=' ELSE '2gIAAAASAQAEAAAAAgIACG1HRG1XaENmJPFbmASqTWYbUPxtvk3JO3T/GVSGaT2m4m0=' END), NULL, NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315757b',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '021000021', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACFBRVWlTLzVPgSXN5uAAgb5rLlHh3xkQYMHK/YGSxOAlnQ==' ELSE '2gIAAAASAQAEAAAAAgIACHFqWTZWQUpmabCsNMpnT8ZWvkxhosMQLbuCBh/SMGOKKA==' END), NULL, NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315757c',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '021000021', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACHl2Tm9KUjJN8uD9zCpB9CNP4Pa2WNff8tFt4B3JdlSTTw==' ELSE '2gIAAAASAQAEAAAAAgIACE0rZmFqQ3Jy8twjUFmI7LL1JXmGTCKcLT7STpxUx2tdBQ==' END), NULL, NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'e0a70827-e95d-4684-b857-11ea7d0d6dd2',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '121000248', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACFlVZ0E2V3VD2mcdVzXkxtLFfyjUJPtDyWJsLegSc+hM/Es=' ELSE '2gIAAAASAQAEAAAAAgIACDFGT25CeWxnfiWo4WUdvh0QrpW/qAO4VLUzxs64d54VCew=' END), NULL, NULL,'System')
;
Insert into TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ,VERSION,CREATED_DATE,MODIFIED_DATE,ACCOUNT_TYPE_CD,A_C_H_ACCOUNT_TYPE_CD,BANK_NAME,ROUTING_NUMBER,ACCOUNT_NUMBER_ENC,EFFECTIVE_DATE,EXPIRATION_DATE,CREATOR_ID) values (
'e0a70827-e95d-4684-b857-11ea7d0d6dd3',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking','Checking','JP MORGAN CHASE','121000248', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACC9FSGxPemRzIQgePoX+B8bznQz8h4UnLThWML3b0iQdSPU=' ELSE '2gIAAAASAQAEAAAAAgIACEs1OTZYdlZmTRubUDvR8vrcDjNNQoTHJIM4pJOTZFS53ZA=' END), NULL,NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315757d',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '061000227', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACHgrWmFicWZBkM7CqLGS9gC7HIEbAi89H7nEP4rwjf4jsuX1iaA=' ELSE '2gIAAAASAQAEAAAAAgIACHgxNHVxd2N33enwaBQ268+yEp/BLwOdHFwiIziHKn1ffj8IsR0=' END), NULL, NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315757e',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '121000248', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACHdHOW1PRWxxxALDfh2366rgbWlgSkr6CArZcCrbZiMLdAs=' ELSE '2gIAAAASAQAEAAAAAgIACFBiajlENFQ2jbZM1a3/ODm6CeXuflL5zwPCpG1tlJWRm20=' END), NULL, NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315757f',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '011000206', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACFpHUGVjN1J5zYaJsQXYo/jBsWkor7Xku6gzvIa2z+Rauw==' ELSE '2gIAAAASAQAEAAAAAgIACGlWMVpIZ2t3GXT6PFMP4+vNAcZXy6qzaRZsd4ul/vD6Ig==' END), NULL, NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157580',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '011000138', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACHRJZTJwNGEzoWEDcWRDw/fYT+1JVrEEUjQ4VHi5oSjNjDaLOg==' ELSE '2gIAAAASAQAEAAAAAgIACFduZzJ3dThKhKUK2xq89JZYaTVTZUn36YCppX23nODWJMO+Yw==' END), NULL, NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157581',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '086507174', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACDNVeGIzWUdXhXs8a8BJ4/JtYgspUleOUZKrJ+xPBco=' ELSE '2gIAAAASAQAEAAAAAgIACDI1VjBGUlJRk45GDw8rvTa4d+9cdUSHPDb2e2ZkAiI=' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157582',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '072000326', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACEZlTW1TMTFGoB5o7PiPF4Z0R+qjVEDxnW+trG6NREs=' ELSE '2gIAAAASAQAEAAAAAgIACFArc0xycVBM+uvwtmWzTq/boz8E+TG0toa3qxdGzjQ=' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'e0a70827-e95d-4684-b857-11ea7d0d6dd1',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '072000326', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACFhaRGxlbVVKgcFFEmI2jxDp/8N7auqJvKwRiXlJggNoyw==' ELSE '2gIAAAASAQAEAAAAAgIACGtkdWxvWThFMlfn88RtPEFFqq4LWFKWZv+VW/ERd8Bs8Q==' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157583',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '075000022', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACEU3SytabkRhgfdqsI3NxaRhKC429DTL1OA9leWZgsXI3g==' ELSE '2gIAAAASAQAEAAAAAgIACDdVbHUzUUUvKVR41aixdS56Lya7u+7i35PvwHskM8I7ng==' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157584',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '075000022', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACFg2UWVmMFBMKIpZhSulI5AbUUfTqtw8G1gtBEohb+ialw==' ELSE '2gIAAAASAQAEAAAAAgIACGdTaExibFhoMYNo2RouvtIMA7LKb1xbntl0FGKKwS0atQ==' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157585',1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '121000248', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACDVFQlEzYWFjdvrf1uZ1bdGLH9eV8Evu3kEBgEyrejEjgUEtZ28=' ELSE '2gIAAAASAQAEAAAAAgIACFhuNEFaSjVQt6cwyNRb4TVk9wuukpLM/lwEtosmv5CLA2ZYD50=' END), NULL, CURRENT_TIMESTAMP, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157586',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '053000196', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACHhZcUhqRURzgNP9gl5fPTQycG6d/AQniTo+0Vh/yI007EtZpQ==' ELSE '2gIAAAASAQAEAAAAAgIACE5PUmF5SWNIcEJ9MgLDRJswhOdbSQ/CHRaGBngVjKZQYo91JA==' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157587',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '053207766', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACDhyNTA1dGxxrkO0AwxEeJ5R1GBgXYH5uebrqVEQ3Y1pHVmdzkw=' ELSE '2gIAAAASAQAEAAAAAgIACEtlWU5jZXVk1VHydcvW1TfXzU0e8paxrusbr6tfPPY6Zbky7Gg=' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157588',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '051000020', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACEF4YjE4RlY0WglV2bhWIaByUAHvOfwFEagDH83zfy2amg==' ELSE '2gIAAAASAQAEAAAAAgIACFdaem9IcDdnB8JkC+VMkCR2afkpD6+1Tsbk2u45Vk197A==' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157589',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '041001039', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACFQvLzNrc2g3fomaD7T6yVRGSe749jcEiVsL4uQJb+J9gN9/mg==' ELSE '2gIAAAASAQAEAAAAAgIACDJGOUtEZW5l+rVDKs49AWN5iCZyrOVKTVJ6ae5REpGfhzcH4w==' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315758a',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '122101706', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACFNwWlJZT2FOfwWaG6Nw9W68vizD0mXsRrqD9O0bZbDkkg==' ELSE '2gIAAAASAQAEAAAAAgIACExIbFRZTTIzNgfJN1eW12pxHQvCY1G7JplEdGv0eGbWzQ==' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315758b',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '122101706', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACEI4N0kyU0ZRYUeOUDuCCMbLd/I+VTD2x/g8JzDIS6Nm6pTDxA==' ELSE '2gIAAAASAQAEAAAAAgIACHdWQ3pyMkYz0xSDOPcRJOeBe7PGpL3ejXdax8KOblAcMAo68g==' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315758c',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '113000609', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACEM2QTZwMldZHABSC1EfrizQ2uWNXe1IlHI5274yNVnglFcv' ELSE '2gIAAAASAQAEAAAAAgIACHIySGdTVitYv6kXnpRgRdcWoTP8Apxt9+mey6XDxwjVOeIZ' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315758d',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '103000648', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACFZOTU1ta3VrHPHHPm3cKCwdlFoXDGV4tZBgluQYFAON9Q==' ELSE '2gIAAAASAQAEAAAAAgIACG9Zbzh2TGdpo/4RqmqPA0m3EYa+Nxh+H+Q7DQAFhaTCIw==' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315758e',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '062001186', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACGFMMktLUm9iSxh/00cPhUkxefSGby5dihoHnlts+Jv0' ELSE '2gIAAAASAQAEAAAAAgIACEhkNmhQelhjFB2d8bbanjsGbrwhzmeoWa0yvTbYXeoQ' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315758f',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '062000019', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACEgwcDI3b3ZmUiiY2eOQ8Q1lZ7TxhfH4zUlmBTvnD8XZ' ELSE '2gIAAAASAQAEAAAAAgIACGpTM2htdG5zOshmRfb3j2VcTHPG1BJ5hNdBRxov+6VB' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157590',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '083000137', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACEJkQnQ5K0NK+ubXrkmpeg3q3Q5a9B7kL0jFPNdEFwbgYQ==' ELSE '2gIAAAASAQAEAAAAAgIACElSTytRQXh2NQjPFF9VTveYdKX0Z4EDbu0bKzaKIlzxXg==' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157591',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '011900445', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACFFqL1NpSXNmsTh+zAmnpN8N0+jdkrKQ9nX2TQdIcHFC' ELSE '2gIAAAASAQAEAAAAAgIACEdFRGJ1bjdyZaZ7BsuaLqLQpqfoB+BrZQUejDwfJ+QT' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157592',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '121000248', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACHVIbWVwV1R1zB//8N79d4fV0mX8hV3NXslDtLndwJANhCE=' ELSE '2gIAAAASAQAEAAAAAgIACHlJbmNkd1V3Gje/fLZYGhNGc8/j/c3naCXx5ks//128YqI=' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157593',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '121000248', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACHVIbWVwV1R1zB//8N79d4fV0mX8hV3NXslDtLndwJANhCE=' ELSE '2gIAAAASAQAEAAAAAgIACHlJbmNkd1V3Gje/fLZYGhNGc8/j/c3naCXx5ks//128YqI=' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157594',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '021052053', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACG9mTjFNZ1B2qknAFmKaNC3xD5OQhjXBSYOhUFVPQRiw' ELSE '2gIAAAASAQAEAAAAAgIACHQxUTNXbXUwyXlSBh1ZgQcvh2BkVLjP1mFvv5jXGPJL' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157595',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '021052053', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACHQyZDVyaXdjpuw0Ceng3MnCyXv/oIPS2/QDEjBzsRrF' ELSE '2gIAAAASAQAEAAAAAgIACHVVUW5hK3Vy5bTwD3Ao/P3dQGnSWjEV5AKYfb0LYIgH' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157596',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '121301015', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACGRJbkplNHdy5VOMxLYyFdu8DEVRa5Dc1Db9CXUOySEv' ELSE '2gIAAAASAQAEAAAAAgIACDVOb1NiMHN5ghp7kP3mPz7lpReWmS0Aj/JvM50rKjv6' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157597',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '073000228', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACFdHalFwZThMSexPVw/v1WRBXPymsumhBhNpQHisWCq7Mfk=' ELSE '2gIAAAASAQAEAAAAAgIACDRuQ3VjRmQvcTbkJ6OX1GpIQhaUENyqqZarBCxkiPPBSTQ=' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157598',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '121000248', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACEs4NGRITWhWrdTAenYhAwKcYop2WcbgYEohxkCwgnedjxE=' ELSE '2gIAAAASAQAEAAAAAgIACFdwVi9oaHBnJbmuEZj/Pj89NwNm0kYlxqjphartdSUF9S4=' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157599',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '011600033', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACGZ3SEN2VmY3gFWqnlWAyaQjK2m/Sh5I+lIQVvX4aZKJ1zQ=' ELSE '2gIAAAASAQAEAAAAAgIACDcwSnNRR252bd6THn2s2awtqFdw+qsWSlR+mg3vF+/YZR4=' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315759a',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '121000248', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACFY2b0FJWktaMyv/ALxwBWsnL7rViU+9dftzWCjnE+OhTCY=' ELSE '2gIAAAASAQAEAAAAAgIACDF5SXM4QnJZ3aOscekFhX3HKNV1YaWJctjIsUWoQY4VtsU=' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315759b',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '121000248', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACDhPaWNrK3BjtwIeKTnZXSHKYB23NM1O8anj6Yn4LjFKZ0I=' ELSE '2gIAAAASAQAEAAAAAgIACEJ2UjZOTWtDvIx6359Q8lPTVGLJfm6JiJLB0t2meojxyiA=' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315759c',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '101101154', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACEtoVkZEcDZIdfqQ/kgpKz0uIhNwMH121b5/2Pnw5Weah/E=' ELSE '2gIAAAASAQAEAAAAAgIACCt4bEM3QTRXmWHFsX+2s6HR5imIZd97l6vtO9kAsolN/a0=' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315759d',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '101000695', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACGZrTHZEU0gwQOulzoBEK7jsh2EmnqWV5y2GLkV0eZhsBv0=' ELSE '2gIAAAASAQAEAAAAAgIACFJibU9HblhOqR3dJsPvyzHUjJh1Ste8ie3L9CF72fFLJKQ=' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315759e',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '211170101', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACEZxR3VkM3Rn6PFeIPkbyOB/RHeCn79ku55yfkkxsJrJGQs=' ELSE '2gIAAAASAQAEAAAAAgIACDI4ZGtNeVlSbJ1AdncIxAyGpPyzU/rw5MDWUaGTCUD6ia8=' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315759f',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '092900383', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACFc2WUYxV0ZvQuXBTxXAuD6Qzf/HpxcAu18z8y7gE5jNdWdmqyPTQw==' ELSE '2gIAAAASAQAEAAAAAgIACDVGTFZ6V25v4mAKdc/7zvBNB6bjtIiR6dEaIxZjHdTQJBMPDmEfSg==' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea831575a0',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'WELLS FARGO', '121000248', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACDd0dlpBRjZY1VEcOWkvG6Qf8bN1A2CE/XtE58sp4nqtGn//FWicqLB/' ELSE '2gIAAAASAQAEAAAAAgIACHlNVk5yVDB6awa6PxY1Q6xImYlRPSsuHBuoOO5zcMieT9si80gOqSRO' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea831575a1',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '091300285', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACFhhSWxNQkVGXN2JcQGMW/19VqIq5tn+61+ZQScKZ0s=' ELSE '2gIAAAASAQAEAAAAAgIACDBBeWw0ZXN2LeASv9XTWSyERSsnZQkwiU2fN0upvLc=' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea831575a2',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '091300285', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACE9xR2d6RXovrl735KJm39AogE4YkyaxjoWu4Ly7Mg==' ELSE '2gIAAAASAQAEAAAAAgIACHJmcThFRGtBEH4CA9RUn1HmNa22LaV3hRvgwUdD8Q==' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea831575a3',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '031000037', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACC84SmNjVG01Fnn/+OsuIWf/l9dTnknpTY0Rp3t/bUI=' ELSE '2gIAAAASAQAEAAAAAgIACDFNS3RwRWk0JWLJ+OP5WaQTiE9BSmbzrdfSqZ/aW5o=' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea831575a4',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '063100277', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACCs3Umd1OGFBa+m6zUtUPpbN4z64Etc0ygGITApBNEBoV/k=' ELSE '2gIAAAASAQAEAAAAAgIACC9nM3FBNFNvgh/56+V+ipD4xqLaC8oRT0x8J1Y7cNFKR/M=' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea831575a5',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '121000248', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACEQraW16enBCUevbWBgfEQ2+b4lLIT5dsFc6Rvw3ygHet038rTI=' ELSE '2gIAAAASAQAEAAAAAgIACERkMmcyQXEyD7nwVaeYQBqeUlQlfj7XRlMrT18S0TQhJTUx1mU=' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea831575a6',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '051904634', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACE5oenFERVNz/i6e7YhehESZnzDYteMNYq6wKgleOKlm' ELSE '2gIAAAASAQAEAAAAAgIACEwxUWRUUE5XuZsAOuViIfEKwLuVe3zenF2nF3kbBinA' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea831575a7',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '064000020', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACEtKNjljNkF4D3hewJwErekGnanpYDh7PWuy9fbE7iIulVZTDw==' ELSE '2gIAAAASAQAEAAAAAgIACDIySUVsNDhDuHpxHwwa+SI/IifBrfcJ/q/TaOFEsWxOoSp5BA==' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea831575a8',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'BANK ONE', '065400137', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACDFoVFRNbUprAFHgc5+XJn1WR1Jqb7LyDAFBN4kYV325eg==' ELSE '2gIAAAASAQAEAAAAAgIACHRxdmg1ckd2nvGiBKOcBc3PJqGkJHcDfulnS8WIThEJ0w==' END), NULL, NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea831575a9',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'Regions', '065305436', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACFZCVk14RkY2158jcL4KZ/Naeb3Ndz8DCeh+1kkd9/gO6wI=' ELSE '2gIAAAASAQAEAAAAAgIACFRodmx6TEw0wwqKir2ZwE2EwnX15SCOpJP6T7Hxx005VgI=' END), NULL, NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'e0a70827-e95d-4684-b857-11ea7d0d6dc8',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'PNC Bank', '043000096', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACHViTS9Mcjhk3PiwEptr/JxD/Ytdym8zdB3ENYN8yEgjcmA=' ELSE '2gIAAAASAQAEAAAAAgIACEpQMTRXNUZ1jKquGq0e1S72vXpU5qQWdMPh2bPSpX9ELDI=' END), NULL, NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'e0a70827-e95d-4684-b857-11ea7d0d6dc9',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'Bank of America', '021052053', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACEMzcnVsQnVsRtoFXk4Tlpnmh2u/DpmRIDJ/4VsbZEpe' ELSE '2gIAAAASAQAEAAAAAgIACFB0WkJIRjZ1ClayMoNSFz70VqOPulBHXSgEGRGVsggN' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'e0a70827-e95d-4684-b857-11ea7d0d6dd0',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'Bank of America', '121000248', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACEFncmp3eklPDs/03Y9qIvQtrk7lYaci9gNMSlV2zWXGjvt3bR2NPMWK' ELSE '2gIAAAASAQAEAAAAAgIACHJjMHBBL0owkwsjIBovsmkUxFocdoN1iga7B42gGlrHTXILWo8+g1Z1' END), NULL, NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea831575ff',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'US BANK', '123103729', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACDJLZUpMT2N0p31/zLod8NTna8ej0dsvYg9iDrYqJZeu6cpcsg==' ELSE '2gIAAAASAQAEAAAAAgIACEg4Z2tYaDIrweYTnC2/n7N0cJ9xDuA52se6QdM/QHNHHhQowQ==' END), NULL, NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157600',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'UNION BANK', '122000496', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACFJTc2dqd2h3zOuG7LxIG3GK8jQxiPiNq0Tf0PLpcT0UaSI=' ELSE '2gIAAAASAQAEAAAAAgIACGt6V2hXbG95KijfhczI3xvnd5B/6M5Gfa8KBa/bslPmJnI=' END), NULL, NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157601',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'WELLS FARGO BANK', '121000248', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACFlPZlZ3R1ErVgz9rgdEBaJ7Z/HFEsdDHXtgVqB5YbhfJtg=' ELSE '2gIAAAASAQAEAAAAAgIACExhSTVHR1hxJkp5nqbKZu0wQti0WiqxXEPY4ziXrB4yXbY=' END), NULL, NULL,'System')
;
Insert into TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ,VERSION,CREATED_DATE,MODIFIED_DATE,ACCOUNT_TYPE_CD,A_C_H_ACCOUNT_TYPE_CD,BANK_NAME,ROUTING_NUMBER,ACCOUNT_NUMBER_ENC,EFFECTIVE_DATE,EXPIRATION_DATE,CREATOR_ID) values (
'33b17266-6d6d-4dfb-83cd-93511f52c1f1',0,CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking','Checking','JP MORGAN CHASE','111000614', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACExsTy9kZ25ZO5iOY7UpVAM5uvCD4lG7v+EBbXARDqMdnzfV' ELSE '2gIAAAASAQAEAAAAAgIACDFrS09hTHBPBwQwGzef53WAciJw0qjJiJpvDDt/7RHNhUyp' END),null,null,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'347cccb9-8d41-4bd4-9a1e-a20401b20909',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'CHITTENDEN', '011600062', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACGhpMDdSTithV4Zx8QS3F9W/Pp2I+Q2pecLuBHnczhwC' ELSE '2gIAAAASAQAEAAAAAgIACEw5UG5uWmZT6Q7gmiPrkmA6yD8a9T3WH1h8ZcgUsUDS' END), NULL, NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852d71d0303',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'BB&T', '061113415', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACExML05HdjNN5YZW+grz6cng//4hacSy4tJ+cO3SlLmm2VnHGms=' ELSE '2gIAAAASAQAEAAAAAgIACG04OE45MUQxQ5Ia4bIAaMS75+SKgXaO34YAerAzjayHWuH8Vgc=' END), NULL, NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-c164-25ea8315756a',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'Wells Fargo', '121000248', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACGNBWndJckhUOEUZr9djeaGFcJZX7fz8rTv9lVVZKlH47X0=' ELSE '2gIAAAASAQAEAAAAAgIACGMvcTJtWGpG9im09Gqf6i5OoijuWB6/95YlHfG/VFbmTms=' END), NULL, NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-c164-25ea83157592',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'CITIBANK NA', '031100209', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACGE4V2c2V3RMgGDxlsV0AN/XlOrYmw5CIAItvC9shoC8' ELSE '2gIAAAASAQAEAAAAAgIACGtONmYrVzN3OA7FaBOSvO9G/IsNuNPvomDqOwqyGm6r' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-c164-25ea83157593',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'CITIBANK NA', '031100209', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACGE4V2c2V3RMgGDxlsV0AN/XlOrYmw5CIAItvC9shoC8' ELSE '2gIAAAASAQAEAAAAAgIACGtONmYrVzN3OA7FaBOSvO9G/IsNuNPvomDqOwqyGm6r' END), NULL, NULL, 'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852e71d0303',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'People''s United Bank', '221172186', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAQIACEFlNUxYZWMwZmovJI6YHQQlp8eR3rhEH6d0GBauG1uqeWg=' ELSE '2gIAAAASAQAEAAAAAgIACDB4MXJYMS84ah5ePed00bXUWeWaY8oIsbLCWulvXOSx35o=' END), NULL, NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852e71d0313',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'US Bank NA', '123000848', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAgIACFJjL2dIL0xYeTXIRc7yj1oTeVBXXXIuaTq1gy8xL0ThWykjkw==' ELSE '2gIAAAASAQAEAAAAAgIACFQ2RWlrN1J2NbVIrb6bXytpe04k84wwP6qbM8ykjL0yyNSryw==' END), NULL, NULL,'System')
;
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b264-25ea8325759d',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'US BANK', '101000187', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAgIACDIzRGFoR3NnZBoBsQs+N73YYquvybosRhnY5b6fOd6Yuv50qA==' ELSE '2gIAAAASAQAEAAAAAgIACEVuMTJRcDZCsCyOq5+3IcZ2lDcxqpwAIWwTBAfAxlhsL3jY7Q==' END), NULL, NULL, 'System')
;
--PSP-17711
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852e71d0319',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'US Bank', '092900383', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAgIACFVYU3RUUVdnoMhYZXXJun90I1mHwripyhpndT02hascHJ4HOw==' ELSE '2gIAAAASAQAEAAAAAgIACG5JK0RwYWNBhki5h8saxvBmyG4uYubpwDbTVsyCs2ZNzPWAhg==' END), NULL, NULL,'System')
;
--PSP-18543
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852e71d0320',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'Bank of America', '011000206', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAwIACHhGSjlWYjVCcczknaR9D0FMbKZn/wA9rinrdUiPFcpZeQ==' ELSE '2gIAAAASAQAEAAAAAwIACDl4RVFJdy9yETJdN3r69h8yTimB44kVlXWmCSmVwNuavw==' END), NULL, NULL,'System')
;
--PSP-19068
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852e71d0323',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'US Bank National Association OR', '123206707', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAwIACEpKWmZXYWdRAkqXehl6xg0+TyAmJ9EDpqxLy6hV6ldPWm0' ELSE '2gIAAAASAQAEAAAAAwIACFU2RVQvVWpJxpWTsBMx+5ALqokKZdaHFLbkTieUdDlawTU' END), NULL, NULL,'System')
;
--PSP-18895
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852e71d0321',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'Synovus', '061100606', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAAAwIACHVYelVjVmVU5FQBgtTSA6POWP3uYmgrAP0JydmbGxyj4YA=' ELSE '2gIAAAASAQAEAAAAAwIACHI2d3VtRFBh/yvOCtT5L2VGy0bsZBBILXHOUHRPOs6FZLs=' END), NULL, NULL,'System')
;
--PSP-19894
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852e71d0324',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '021409169', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAABAIACGFUODM2OUxhiI0rVS5qwQGOu9wwy6RpmZ9+GipwvQ==' ELSE '2gIAAAASAQAEAAAABAIACGdMclF6K2cwzVJKm37sJFl099sqB2ESl/RM+43pRw==' END), NULL, NULL, 'System')
;
--PSP-19946
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852e71d0326',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'MO Employment Security', '086500634', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAABAIACDhPLzNVOWZpZxIr6gUaIdULA3/oqA6hySnslxmYPCk=' ELSE '2gIAAAASAQAEAAAABAIACGkyMVhEWXN1IKW4Sl04t9g4tX1H35Jk9YVjG4lwpIM=' END), NULL, NULL, 'System')
;
--PSP-20226
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852e71d0327',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'Bank of America', '011900254', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAABAIACGQrZW02ZXpXCOqK4ULEKJTt6OI8m9zqngRwo1bWBkBBx38FyhgOnZ+H' ELSE '2gIAAAASAQAEAAAABAIACG0xQTcyVjUySF4W4mDxOG4Fcon9tfqbxnx0pdAn+VNuR9etpYxY+1dl' END), NULL, NULL, 'System')
;
---PSP-20860
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852e71d0328',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'Wells Fargo', '121000248', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAABAIACGVWK0ZzNGFmCMzZ8mJOCYdG9357+62KegwttBH9vKxLbtSAjvWto/Oj' ELSE '2gIAAAASAQAEAAAABAIACDZNdnM2L0pjc0FGubiv/gzgrolqPb4zZD7Ga9B+yBJzHm8MDD1wyWrm' END), NULL, NULL, 'System')
;
---PSP-20938
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852e71d0329',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'JP MORGAN CHASE', '121000248', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAABAIACFY0NlVmTjd5XmD5GHqh0Zo+jxO+Y19/t9Bv8Vejrp6TsK4=' ELSE '2gIAAAASAQAEAAAABAIACGhudlc2NDZYSCt9nJjwmx6l2uUyo6XrBdUbA3U7WG/cnlM=' END), NULL, NULL, 'System')
;
---PSP-22429
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852e71d0330',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'PNC', '083000108', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAABgUACDl2SDQ1NVZKBSIWaorJgesn9eom2W7gGioR8IxHangeOF8=' ELSE '2gIAAAASAQAEAAAABgUACEFOTjZGVjg0DQJGq5ihsdkvRBLq/sySHQR1L5a2JUYWV7g=' END), NULL, NULL, 'System')
;
-- PSP-23405
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852e71d0332',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'Bank of America N.A.', '011900254', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAABwUACGdwVitqeFQrINX3Q3jDXy4X+hIx/TQFyfrTjaZVDb23Crz23w==' ELSE'2gIAAAASAQAEAAAABwUACEdSVEt3Qmpv3Rhtp1+0ehGR5XdmeTWa1eNBxbAHNuVdcNrAjA==' END), NULL, NULL, 'System')
;
--PSP-24126
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852e71d0331',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'WELLS FARGO', '121000248', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAABwUACDNRMW9QV1VZnrdnCbVd2iyhKpfolaiGSGGn88KD0ndfjpk=' ELSE '2gIAAAASAQAEAAAABwUACDNKVnoxdmdwH3HeoLoyWCKmHr2t610MPpMAmgzDjKHT4aU=' END), NULL, NULL,'System')
;
--PSP-24938
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852e71d0333',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'Key Bank', '021052053', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAACAUACC9VUkJFemFpocmKvUm9YzBRVeF9TK+eGhZ1Ui/Svuxb' ELSE '2gIAAAASAQAEAAAABwUACHZ2ME1oUXFW27h8w3CahfJ6JoYMgy5uw+4+FJhLnJ53' END), NULL, NULL,'System')
;
--PSP-25221
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852e71d0338',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'US BANK', '021052053', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAACAUACDcrUXpod3FBviLv50f9gsyCYealInpPgQXNGM39H3Gn' ELSE '2gIAAAASAQAEAAAACAUACENCQzhOdlRNSn4ahTGtx52MXc+NGp7s+ZW/O+a5hPWW' END), NULL, NULL,'System')
;
--PSP-25540
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852e71d0456',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'US Bank', '122235821', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAACQUACFpvUURSSTU1k49yCh52RW7UgBBUMAHp5ydVRXY/SLEF5bTvaw==' ELSE '2gIAAAASAQAEAAAACAUACGhXN3ZWOWhIuMb0IXGGubz+o2huen/WcdXFMeMp9rfEf/nWEw==' END), NULL, NULL,'System')
;
--PSP-27235
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852e71d0486',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'US Bank', '123000848', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAACQUACGV0aHBmYmN0/3RQwR9AvjDAZBnQfDtkt+h8wHSVgKQ2rgC/kA==' ELSE '2gIAAAASAQAEAAAACQUACEJRVDlwRVRt2KcsuecZjCJGT2a1einOD/x+Xq4ZokwwmB3sOA==' END), NULL, NULL,'System')
;
--PSP-26526
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-9832-8188-1852e71d0456',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'BB&T', '051503394', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAACQUACHM2c2pTelRzm7C65vawEwzcFRL6UjtluqzoO8aX69jQIlQ=' ELSE '2gIAAAASAQAEAAAACQUACEpIdWs5ckVoRysRqJvSn6ztzxFGkDSLrLIkKw9nOBrh1xI=' END), NULL, NULL,'System')
;
--PSP-29017
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b168-25ea83157576',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'Checking', 'Checking', 'US Bank', '021052053', (CASE WHEN FN_GET_ENV() = 'PROD' THEN '2gIAAAASAQAEAAAACgUACGJqM2FFbUtmvVyu7+M4WwzPu/cXY4HWVP5ANbFnD7eh' ELSE '2gIAAAASAQAEAAAACQUACGpUcTl3MnVPkFiNKaKg11K74HTxtR95TB/+NRYmieEf' END), NULL, NULL,'System')
;
--------------------------------------------------------
-- Sychronize temp table and real table by            --
-- inserting, deleting, and updating as necessary     --
--------------------------------------------------------

INSERT INTO PSP_BANK_ACCOUNT
   (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE,CREATOR_ID )
SELECT
    BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE,CREATOR_ID
FROM
   TEMP_PSP_BANK_ACCOUNT tt
WHERE
   tt.BANK_ACCOUNT_SEQ NOT IN (SELECT BANK_ACCOUNT_SEQ FROM PSP_BANK_ACCOUNT)

;

UPDATE PSP_BANK_ACCOUNT rt
SET ( VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE, EXPIRATION_DATE, CREATOR_ID) =
(SELECT  tt.VERSION, tt.CREATED_DATE, tt.MODIFIED_DATE, tt.ACCOUNT_TYPE_CD, tt.A_C_H_ACCOUNT_TYPE_CD, tt.BANK_NAME, tt.ROUTING_NUMBER, tt.ACCOUNT_NUMBER_ENC, tt.EFFECTIVE_DATE, tt.EXPIRATION_DATE,tt.CREATOR_ID
FROM TEMP_PSP_BANK_ACCOUNT tt WHERE tt.BANK_ACCOUNT_SEQ = rt.BANK_ACCOUNT_SEQ)
WHERE rt.BANK_ACCOUNT_SEQ IN (SELECT BANK_ACCOUNT_SEQ FROM TEMP_PSP_BANK_ACCOUNT)
;



--------------------------------------------------------
-- Drop temp table                                  --
--------------------------------------------------------
DROP TABLE TEMP_PSP_BANK_ACCOUNT

;
COMMIT;


