spool adv_companyinfo_datafix.log
set lines 1000
set echo on
create table kpopat.companyinfo_adv_bkp_c10 as select * from qbo_data.companyinfo_1@SPM_C10_UW2 where company_id in (select company_id from kpopat.all_companyinfo_dupe_del_adv where cluster_id = 10) and nvl(companyinfo_1.sample_company,-1) <> 1 ;
select count(1) from kpopat.companyinfo_adv_bkp_c10 ;
delete qbo_data.companyinfo_1@SPM_C10_UW2 where company_id in (select company_id from kpopat.all_companyinfo_dupe_del_adv where cluster_id = 10) and nvl(companyinfo_1.sample_company,-1) <> 1;
commit ;
create table kpopat.companyinfo_adv_bkp_c11 as select * from qbo_data.companyinfo_1@SPM_C11_UW2 where company_id in (select company_id from kpopat.all_companyinfo_dupe_del_adv where cluster_id = 11) and nvl(companyinfo_1.sample_company,-1) <> 1 ;
select count(1) from kpopat.companyinfo_adv_bkp_c11 ;
delete qbo_data.companyinfo_1@SPM_C11_UW2 where company_id in (select company_id from kpopat.all_companyinfo_dupe_del_adv where cluster_id = 11) and nvl(companyinfo_1.sample_company,-1) <> 1;
commit ;
create table kpopat.companyinfo_adv_bkp_c12 as select * from qbo_data.companyinfo_1@SPM_C12_UW2 where company_id in (select company_id from kpopat.all_companyinfo_dupe_del_adv where cluster_id = 12) and nvl(companyinfo_1.sample_company,-1) <> 1 ;
select count(1) from kpopat.companyinfo_adv_bkp_c12 ;
delete qbo_data.companyinfo_1@SPM_C12_UW2 where company_id in (select company_id from kpopat.all_companyinfo_dupe_del_adv where cluster_id = 12) and nvl(companyinfo_1.sample_company,-1) <> 1;
commit ;
create table kpopat.companyinfo_adv_bkp_c22 as select * from qbo_data.companyinfo_1@SPM_C22_UW2 where company_id in (select company_id from kpopat.all_companyinfo_dupe_del_adv where cluster_id = 22) and nvl(companyinfo_1.sample_company,-1) <> 1 ;
select count(1) from kpopat.companyinfo_adv_bkp_c22 ;
delete qbo_data.companyinfo_1@SPM_C22_UW2 where company_id in (select company_id from kpopat.all_companyinfo_dupe_del_adv where cluster_id = 22) and nvl(companyinfo_1.sample_company,-1) <> 1;
commit ;
create table kpopat.companyinfo_adv_bkp_c24 as select * from qbo_data.companyinfo_1@SPM_C24_UW2 where company_id in (select company_id from kpopat.all_companyinfo_dupe_del_adv where cluster_id = 24) and nvl(companyinfo_1.sample_company,-1) <> 1 ;
select count(1) from kpopat.companyinfo_adv_bkp_c24 ;
delete qbo_data.companyinfo_1@SPM_C24_UW2 where company_id in (select company_id from kpopat.all_companyinfo_dupe_del_adv where cluster_id = 24) and nvl(companyinfo_1.sample_company,-1) <> 1;
commit ;
create table kpopat.companyinfo_adv_bkp_c25 as select * from qbo_data.companyinfo_1@SPM_C25_UW2 where company_id in (select company_id from kpopat.all_companyinfo_dupe_del_adv where cluster_id = 25) and nvl(companyinfo_1.sample_company,-1) <> 1 ;
select count(1) from kpopat.companyinfo_adv_bkp_c25 ;
delete qbo_data.companyinfo_1@SPM_C25_UW2 where company_id in (select company_id from kpopat.all_companyinfo_dupe_del_adv where cluster_id = 25) and nvl(companyinfo_1.sample_company,-1) <> 1;
commit ;
create table kpopat.companyinfo_adv_bkp_c26 as select * from qbo_data.companyinfo_1@SPM_C26_UW2 where company_id in (select company_id from kpopat.all_companyinfo_dupe_del_adv where cluster_id = 26) and nvl(companyinfo_1.sample_company,-1) <> 1 ;
select count(1) from kpopat.companyinfo_adv_bkp_c26 ;
delete qbo_data.companyinfo_1@SPM_C26_UW2 where company_id in (select company_id from kpopat.all_companyinfo_dupe_del_adv where cluster_id = 26) and nvl(companyinfo_1.sample_company,-1) <> 1;
commit ;
create table kpopat.companyinfo_adv_bkp_c27 as select * from qbo_data.companyinfo_1@SPM_C27_UW2 where company_id in (select company_id from kpopat.all_companyinfo_dupe_del_adv where cluster_id = 27) and nvl(companyinfo_1.sample_company,-1) <> 1 ;
select count(1) from kpopat.companyinfo_adv_bkp_c27 ;
delete qbo_data.companyinfo_1@SPM_C27_UW2 where company_id in (select company_id from kpopat.all_companyinfo_dupe_del_adv where cluster_id = 27) and nvl(companyinfo_1.sample_company,-1) <> 1;
commit ;
create table kpopat.companyinfo_adv_bkp_c28 as select * from qbo_data.companyinfo_1@SPM_C28_UW2 where company_id in (select company_id from kpopat.all_companyinfo_dupe_del_adv where cluster_id = 28) and nvl(companyinfo_1.sample_company,-1) <> 1 ;
select count(1) from kpopat.companyinfo_adv_bkp_c28 ;
delete qbo_data.companyinfo_1@SPM_C28_UW2 where company_id in (select company_id from kpopat.all_companyinfo_dupe_del_adv where cluster_id = 28) and nvl(companyinfo_1.sample_company,-1) <> 1;
commit ;
create table kpopat.companyinfo_adv_bkp_c29 as select * from qbo_data.companyinfo_1@SPM_C29_UW2 where company_id in (select company_id from kpopat.all_companyinfo_dupe_del_adv where cluster_id = 29) and nvl(companyinfo_1.sample_company,-1) <> 1 ;
select count(1) from kpopat.companyinfo_adv_bkp_c29 ;
delete qbo_data.companyinfo_1@SPM_C29_UW2 where company_id in (select company_id from kpopat.all_companyinfo_dupe_del_adv where cluster_id = 29) and nvl(companyinfo_1.sample_company,-1) <> 1;
commit ;
create table kpopat.companyinfo_adv_bkp_c30 as select * from qbo_data.companyinfo_1@SPM_C30_UW2 where company_id in (select company_id from kpopat.all_companyinfo_dupe_del_adv where cluster_id = 30) and nvl(companyinfo_1.sample_company,-1) <> 1 ;
select count(1) from kpopat.companyinfo_adv_bkp_c30 ;
delete qbo_data.companyinfo_1@SPM_C30_UW2 where company_id in (select company_id from kpopat.all_companyinfo_dupe_del_adv where cluster_id = 30) and nvl(companyinfo_1.sample_company,-1) <> 1;
commit ;
create table kpopat.companyinfo_adv_bkp_c31 as select * from qbo_data.companyinfo_1@SPM_C31_UW2 where company_id in (select company_id from kpopat.all_companyinfo_dupe_del_adv where cluster_id = 31) and nvl(companyinfo_1.sample_company,-1) <> 1 ;
select count(1) from kpopat.companyinfo_adv_bkp_c31 ;
delete qbo_data.companyinfo_1@SPM_C31_UW2 where company_id in (select company_id from kpopat.all_companyinfo_dupe_del_adv where cluster_id = 31) and nvl(companyinfo_1.sample_company,-1) <> 1;
commit ;
create table kpopat.companyinfo_adv_bkp_c32 as select * from qbo_data.companyinfo_1@SPM_C32_UW2 where company_id in (select company_id from kpopat.all_companyinfo_dupe_del_adv where cluster_id = 32) and nvl(companyinfo_1.sample_company,-1) <> 1 ;
select count(1) from kpopat.companyinfo_adv_bkp_c32 ;
delete qbo_data.companyinfo_1@SPM_C32_UW2 where company_id in (select company_id from kpopat.all_companyinfo_dupe_del_adv where cluster_id = 32) and nvl(companyinfo_1.sample_company,-1) <> 1;
commit ;
create table kpopat.companyinfo_adv_bkp_c36 as select * from qbo_data.companyinfo_1@SPM_C36_UW2 where company_id in (select company_id from kpopat.all_companyinfo_dupe_del_adv where cluster_id = 36) and nvl(companyinfo_1.sample_company,-1) <> 1 ;
select count(1) from kpopat.companyinfo_adv_bkp_c36 ;
delete qbo_data.companyinfo_1@SPM_C36_UW2 where company_id in (select company_id from kpopat.all_companyinfo_dupe_del_adv where cluster_id = 36) and nvl(companyinfo_1.sample_company,-1) <> 1;
commit ;
create table kpopat.companyinfo_adv_bkp_c39 as select * from qbo_data.companyinfo_1@SPM_C39_UW2 where company_id in (select company_id from kpopat.all_companyinfo_dupe_del_adv where cluster_id = 39) and nvl(companyinfo_1.sample_company,-1) <> 1 ;
select count(1) from kpopat.companyinfo_adv_bkp_c39 ;
delete qbo_data.companyinfo_1@SPM_C39_UW2 where company_id in (select company_id from kpopat.all_companyinfo_dupe_del_adv where cluster_id = 39) and nvl(companyinfo_1.sample_company,-1) <> 1;
commit ;
spool off
