\timing
set search_path=pspadm;
SELECT CURRENT_TIMESTAMP;
select 'creating index on psp_entitlement_message' as status ;
create index psp_entitlement_message_u1_2012 on pspadm.psp_entitlement_message_2012  USING BTREE (token ASC);
create index psp_entitlement_message_u1_2013 on pspadm.psp_entitlement_message_2013  USING BTREE (token ASC);
create index psp_entitlement_message_u1_2014 on pspadm.psp_entitlement_message_2014  USING BTREE (token ASC);
create index psp_entitlement_message_u1_2015 on pspadm.psp_entitlement_message_2015  USING BTREE (token ASC);
create index psp_entitlement_message_u1_2016 on pspadm.psp_entitlement_message_2016  USING BTREE (token ASC);
create index psp_entitlement_message_u1_2017 on pspadm.psp_entitlement_message_2017  USING BTREE (token ASC);
create index psp_entitlement_message_u1_2018 on pspadm.psp_entitlement_message_2018  USING BTREE (token ASC);
create index psp_entitlement_message_u1_2019 on pspadm.psp_entitlement_message_2019  USING BTREE (token ASC);
create index psp_entitlement_message_u1_2020 on pspadm.psp_entitlement_message_2020  USING BTREE (token ASC);
create index psp_entitlement_message_u1_2021 on pspadm.psp_entitlement_message_2021  USING BTREE (token ASC);
create index psp_entitlement_message_u1_2022 on pspadm.psp_entitlement_message_2022  USING BTREE (token ASC);
create index psp_entitlement_message_u1_2023 on pspadm.psp_entitlement_message_2023  USING BTREE (token ASC);
create index psp_entitlement_msg_lcno_eofcd_2012 on pspadm.psp_entitlement_message_2012  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index psp_entitlement_msg_lcno_eofcd_2013 on pspadm.psp_entitlement_message_2013  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index psp_entitlement_msg_lcno_eofcd_2014 on pspadm.psp_entitlement_message_2014  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index psp_entitlement_msg_lcno_eofcd_2015 on pspadm.psp_entitlement_message_2015  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index psp_entitlement_msg_lcno_eofcd_2016 on pspadm.psp_entitlement_message_2016  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index psp_entitlement_msg_lcno_eofcd_2017 on pspadm.psp_entitlement_message_2017  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index psp_entitlement_msg_lcno_eofcd_2018 on pspadm.psp_entitlement_message_2018  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index psp_entitlement_msg_lcno_eofcd_2019 on pspadm.psp_entitlement_message_2019  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index psp_entitlement_msg_lcno_eofcd_2020 on pspadm.psp_entitlement_message_2020  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index psp_entitlement_msg_lcno_eofcd_2021 on pspadm.psp_entitlement_message_2021  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index psp_entitlement_msg_lcno_eofcd_2022 on pspadm.psp_entitlement_message_2022  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index psp_entitlement_msg_lcno_eofcd_2023 on pspadm.psp_entitlement_message_2023  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index psp_entitlement_msg_msgts_er_2012 on pspadm.psp_entitlement_message_2012  USING BTREE (message_timestamp ASC,event_reason ASC);
create index psp_entitlement_msg_msgts_er_2013 on pspadm.psp_entitlement_message_2013  USING BTREE (message_timestamp ASC,event_reason ASC);
create index psp_entitlement_msg_msgts_er_2014 on pspadm.psp_entitlement_message_2014  USING BTREE (message_timestamp ASC,event_reason ASC);
create index psp_entitlement_msg_msgts_er_2015 on pspadm.psp_entitlement_message_2015  USING BTREE (message_timestamp ASC,event_reason ASC);
create index psp_entitlement_msg_msgts_er_2016 on pspadm.psp_entitlement_message_2016  USING BTREE (message_timestamp ASC,event_reason ASC);
create index psp_entitlement_msg_msgts_er_2017 on pspadm.psp_entitlement_message_2017  USING BTREE (message_timestamp ASC,event_reason ASC);
create index psp_entitlement_msg_msgts_er_2018 on pspadm.psp_entitlement_message_2018  USING BTREE (message_timestamp ASC,event_reason ASC);
create index psp_entitlement_msg_msgts_er_2019 on pspadm.psp_entitlement_message_2019  USING BTREE (message_timestamp ASC,event_reason ASC);
create index psp_entitlement_msg_msgts_er_2020 on pspadm.psp_entitlement_message_2020  USING BTREE (message_timestamp ASC,event_reason ASC);
create index psp_entitlement_msg_msgts_er_2021 on pspadm.psp_entitlement_message_2021  USING BTREE (message_timestamp ASC,event_reason ASC);
create index psp_entitlement_msg_msgts_er_2022 on pspadm.psp_entitlement_message_2022  USING BTREE (message_timestamp ASC,event_reason ASC);
create index psp_entitlement_msg_msgts_er_2023 on pspadm.psp_entitlement_message_2023  USING BTREE (message_timestamp ASC,event_reason ASC);
create index psp_entitlement_msg_orno_lcno_2012 on pspadm.psp_entitlement_message_2012  USING BTREE (order_number ASC,license_number ASC);
create index psp_entitlement_msg_orno_lcno_2013 on pspadm.psp_entitlement_message_2013  USING BTREE (order_number ASC,license_number ASC);
create index psp_entitlement_msg_orno_lcno_2014 on pspadm.psp_entitlement_message_2014  USING BTREE (order_number ASC,license_number ASC);
create index psp_entitlement_msg_orno_lcno_2015 on pspadm.psp_entitlement_message_2015  USING BTREE (order_number ASC,license_number ASC);
create index psp_entitlement_msg_orno_lcno_2016 on pspadm.psp_entitlement_message_2016  USING BTREE (order_number ASC,license_number ASC);
create index psp_entitlement_msg_orno_lcno_2017 on pspadm.psp_entitlement_message_2017  USING BTREE (order_number ASC,license_number ASC);
create index psp_entitlement_msg_orno_lcno_2018 on pspadm.psp_entitlement_message_2018  USING BTREE (order_number ASC,license_number ASC);
create index psp_entitlement_msg_orno_lcno_2019 on pspadm.psp_entitlement_message_2019  USING BTREE (order_number ASC,license_number ASC);
create index psp_entitlement_msg_orno_lcno_2020 on pspadm.psp_entitlement_message_2020  USING BTREE (order_number ASC,license_number ASC);
create index psp_entitlement_msg_orno_lcno_2021 on pspadm.psp_entitlement_message_2021  USING BTREE (order_number ASC,license_number ASC);
create index psp_entitlement_msg_orno_lcno_2022 on pspadm.psp_entitlement_message_2022  USING BTREE (order_number ASC,license_number ASC);
create index psp_entitlement_msg_orno_lcno_2023 on pspadm.psp_entitlement_message_2023  USING BTREE (order_number ASC,license_number ASC);
select  'psp_entitlement_message completed' as status;
SELECT CURRENT_TIMESTAMP;

select 'creating index on psp_paycheck_usage' as status;
create index psp_paycheck_usage_fk1_2012 on pspadm.psp_paycheck_usage_2012  USING BTREE (company_fk ASC);
create index psp_paycheck_usage_fk1_2013 on pspadm.psp_paycheck_usage_2013  USING BTREE (company_fk ASC);
create index psp_paycheck_usage_fk1_2014 on pspadm.psp_paycheck_usage_2014  USING BTREE (company_fk ASC);
create index psp_paycheck_usage_fk1_2015 on pspadm.psp_paycheck_usage_2015  USING BTREE (company_fk ASC);
create index psp_paycheck_usage_fk1_2016 on pspadm.psp_paycheck_usage_2016  USING BTREE (company_fk ASC);
create index psp_paycheck_usage_fk1_2017 on pspadm.psp_paycheck_usage_2017  USING BTREE (company_fk ASC);
create index psp_paycheck_usage_fk1_2018 on pspadm.psp_paycheck_usage_2018  USING BTREE (company_fk ASC);
create index psp_paycheck_usage_fk1_2019 on pspadm.psp_paycheck_usage_2019  USING BTREE (company_fk ASC);
create index psp_paycheck_usage_fk1_2020 on pspadm.psp_paycheck_usage_2020  USING BTREE (company_fk ASC);
create index psp_paycheck_usage_fk1_2021 on pspadm.psp_paycheck_usage_2021  USING BTREE (company_fk ASC);
create index psp_paycheck_usage_fk1_2022 on pspadm.psp_paycheck_usage_2022  USING BTREE (company_fk ASC);
create index psp_paycheck_usage_fk1_2023 on pspadm.psp_paycheck_usage_2023  USING BTREE (company_fk ASC);
create index psp_paycheck_usage_nu1_2012 on pspadm.psp_paycheck_usage_2012  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_nu1_2013 on pspadm.psp_paycheck_usage_2013  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_nu1_2014 on pspadm.psp_paycheck_usage_2014  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_nu1_2015 on pspadm.psp_paycheck_usage_2015  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_nu1_2016 on pspadm.psp_paycheck_usage_2016  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_nu1_2017 on pspadm.psp_paycheck_usage_2017  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_nu1_2018 on pspadm.psp_paycheck_usage_2018  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_nu1_2019 on pspadm.psp_paycheck_usage_2019  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_nu1_2020 on pspadm.psp_paycheck_usage_2020  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_nu1_2021 on pspadm.psp_paycheck_usage_2021  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_nu1_2022 on pspadm.psp_paycheck_usage_2022  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_nu1_2023 on pspadm.psp_paycheck_usage_2023  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2012 on pspadm.psp_paycheck_usage_2012  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2013 on pspadm.psp_paycheck_usage_2013  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2014 on pspadm.psp_paycheck_usage_2014  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2015 on pspadm.psp_paycheck_usage_2015  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2016 on pspadm.psp_paycheck_usage_2016  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2017 on pspadm.psp_paycheck_usage_2017  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2018 on pspadm.psp_paycheck_usage_2018  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2019 on pspadm.psp_paycheck_usage_2019  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2020 on pspadm.psp_paycheck_usage_2020  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2021 on pspadm.psp_paycheck_usage_2021  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2022 on pspadm.psp_paycheck_usage_2022  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2023 on pspadm.psp_paycheck_usage_2023  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheckusage_fk1_2012 on pspadm.psp_paycheck_usage_2012  USING BTREE (bill_fk ASC);
create index psp_paycheckusage_fk1_2013 on pspadm.psp_paycheck_usage_2013  USING BTREE (bill_fk ASC);
create index psp_paycheckusage_fk1_2014 on pspadm.psp_paycheck_usage_2014  USING BTREE (bill_fk ASC);
create index psp_paycheckusage_fk1_2015 on pspadm.psp_paycheck_usage_2015  USING BTREE (bill_fk ASC);
create index psp_paycheckusage_fk1_2016 on pspadm.psp_paycheck_usage_2016  USING BTREE (bill_fk ASC);
create index psp_paycheckusage_fk1_2017 on pspadm.psp_paycheck_usage_2017  USING BTREE (bill_fk ASC);
create index psp_paycheckusage_fk1_2018 on pspadm.psp_paycheck_usage_2018  USING BTREE (bill_fk ASC);
create index psp_paycheckusage_fk1_2019 on pspadm.psp_paycheck_usage_2019  USING BTREE (bill_fk ASC);
create index psp_paycheckusage_fk1_2020 on pspadm.psp_paycheck_usage_2020  USING BTREE (bill_fk ASC);
create index psp_paycheckusage_fk1_2021 on pspadm.psp_paycheck_usage_2021  USING BTREE (bill_fk ASC);
create index psp_paycheckusage_fk1_2022 on pspadm.psp_paycheck_usage_2022  USING BTREE (bill_fk ASC);
create index psp_paycheckusage_fk1_2023 on pspadm.psp_paycheck_usage_2023  USING BTREE (bill_fk ASC);
create index psp_paycheckusage_fk2_2012 on pspadm.psp_paycheck_usage_2012  USING BTREE (employee_usage_fk ASC);
create index psp_paycheckusage_fk2_2013 on pspadm.psp_paycheck_usage_2013  USING BTREE (employee_usage_fk ASC);
create index psp_paycheckusage_fk2_2014 on pspadm.psp_paycheck_usage_2014  USING BTREE (employee_usage_fk ASC);
create index psp_paycheckusage_fk2_2015 on pspadm.psp_paycheck_usage_2015  USING BTREE (employee_usage_fk ASC);
create index psp_paycheckusage_fk2_2016 on pspadm.psp_paycheck_usage_2016  USING BTREE (employee_usage_fk ASC);
create index psp_paycheckusage_fk2_2017 on pspadm.psp_paycheck_usage_2017  USING BTREE (employee_usage_fk ASC);
create index psp_paycheckusage_fk2_2018 on pspadm.psp_paycheck_usage_2018  USING BTREE (employee_usage_fk ASC);
create index psp_paycheckusage_fk2_2019 on pspadm.psp_paycheck_usage_2019  USING BTREE (employee_usage_fk ASC);
create index psp_paycheckusage_fk2_2020 on pspadm.psp_paycheck_usage_2020  USING BTREE (employee_usage_fk ASC);
create index psp_paycheckusage_fk2_2021 on pspadm.psp_paycheck_usage_2021  USING BTREE (employee_usage_fk ASC);
create index psp_paycheckusage_fk2_2022 on pspadm.psp_paycheck_usage_2022  USING BTREE (employee_usage_fk ASC);
create index psp_paycheckusage_fk2_2023 on pspadm.psp_paycheck_usage_2023  USING BTREE (employee_usage_fk ASC);
select  'psp_paycheck_usage completed'  as status;
SELECT CURRENT_TIMESTAMP;

select 'creating index on psp_entity_update' as status;
create index idx_entityupdate_crdate_m112022 on pspadm.psp_entity_update_m112022 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m122022 on pspadm.psp_entity_update_m122022 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m012023 on pspadm.psp_entity_update_m012023 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m022023 on pspadm.psp_entity_update_m022023 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m032023 on pspadm.psp_entity_update_m032023 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m042023 on pspadm.psp_entity_update_m042023 USING BTREE (created_date ASC);
select  'psp_entity_update completed' as status;
SELECT CURRENT_TIMESTAMP;

--indexes on modified_date column
--Range Partition tables

create index concurrently idx_ent_msg_mod_date_2012 on pspadm.psp_entitlement_message_2012  USING BTREE (modified_date);
create index concurrently idx_ent_msg_mod_date_2013 on pspadm.psp_entitlement_message_2013  USING BTREE (modified_date);
create index concurrently idx_ent_msg_mod_date_2014 on pspadm.psp_entitlement_message_2014  USING BTREE (modified_date);
create index concurrently idx_ent_msg_mod_date_2015 on pspadm.psp_entitlement_message_2015  USING BTREE (modified_date);
create index concurrently idx_ent_msg_mod_date_2016 on pspadm.psp_entitlement_message_2016  USING BTREE (modified_date);
create index concurrently idx_ent_msg_mod_date_2017 on pspadm.psp_entitlement_message_2017  USING BTREE (modified_date);
create index concurrently idx_ent_msg_mod_date_2018 on pspadm.psp_entitlement_message_2018  USING BTREE (modified_date);
create index concurrently idx_ent_msg_mod_date_2019 on pspadm.psp_entitlement_message_2019  USING BTREE (modified_date);
create index concurrently idx_ent_msg_mod_date_2020 on pspadm.psp_entitlement_message_2020  USING BTREE (modified_date);
create index concurrently idx_ent_msg_mod_date_2021 on pspadm.psp_entitlement_message_2021  USING BTREE (modified_date);
create index concurrently idx_ent_msg_mod_date_2022 on pspadm.psp_entitlement_message_2022  USING BTREE (modified_date);
create index concurrently idx_ent_msg_mod_date_2023 on pspadm.psp_entitlement_message_2023  USING BTREE (modified_date);
create index concurrently idx_ent_msg_mod_date_2024 on pspadm.psp_entitlement_message_2024  USING BTREE (modified_date);
create index concurrently idx_ent_msg_mod_date_2025 on pspadm.psp_entitlement_message_2025  USING BTREE (modified_date);
create index concurrently idx_ent_msg_mod_date_2026 on pspadm.psp_entitlement_message_2026  USING BTREE (modified_date);


create index concurrently idx_pchk_usg_mod_date_2012 on pspadm.psp_paycheck_usage_2012  USING BTREE (modified_date);
create index concurrently idx_pchk_usg_mod_date_2013 on pspadm.psp_paycheck_usage_2013  USING BTREE (modified_date);
create index concurrently idx_pchk_usg_mod_date_2014 on pspadm.psp_paycheck_usage_2014  USING BTREE (modified_date);
create index concurrently idx_pchk_usg_mod_date_2015 on pspadm.psp_paycheck_usage_2015  USING BTREE (modified_date);
create index concurrently idx_pchk_usg_mod_date_2016 on pspadm.psp_paycheck_usage_2016  USING BTREE (modified_date);
create index concurrently idx_pchk_usg_mod_date_2017 on pspadm.psp_paycheck_usage_2017  USING BTREE (modified_date);
create index concurrently idx_pchk_usg_mod_date_2018 on pspadm.psp_paycheck_usage_2018  USING BTREE (modified_date);
create index concurrently idx_pchk_usg_mod_date_2019 on pspadm.psp_paycheck_usage_2019  USING BTREE (modified_date);
create index concurrently idx_pchk_usg_mod_date_2020 on pspadm.psp_paycheck_usage_2020  USING BTREE (modified_date);
create index concurrently idx_pchk_usg_mod_date_2021 on pspadm.psp_paycheck_usage_2021  USING BTREE (modified_date);
create index concurrently idx_pchk_usg_mod_date_2022 on pspadm.psp_paycheck_usage_2022  USING BTREE (modified_date);
create index concurrently idx_pchk_usg_mod_date_2023 on pspadm.psp_paycheck_usage_2023  USING BTREE (modified_date);
create index concurrently idx_pchk_usg_mod_date_2024 on pspadm.psp_paycheck_usage_2024  USING BTREE (modified_date);
create index concurrently idx_pchk_usg_mod_date_2025 on pspadm.psp_paycheck_usage_2025  USING BTREE (modified_date);
create index concurrently idx_pchk_usg_mod_date_2026 on pspadm.psp_paycheck_usage_2026  USING BTREE (modified_date);


create index concurrently idx_ent_upd_mod_date_m112022 on pspadm.psp_entity_update_m112022 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m122022 on pspadm.psp_entity_update_m122022 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m012023 on pspadm.psp_entity_update_m012023 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m022023 on pspadm.psp_entity_update_m022023 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m032023 on pspadm.psp_entity_update_m032023 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m042023 on pspadm.psp_entity_update_m042023 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m052023 on pspadm.psp_entity_update_m052023 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m062023 on pspadm.psp_entity_update_m062023 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m072023 on pspadm.psp_entity_update_m072023 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m082023 on pspadm.psp_entity_update_m082023 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m092023 on pspadm.psp_entity_update_m092023 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m102023 on pspadm.psp_entity_update_m102023 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m112023 on pspadm.psp_entity_update_m112023 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m122023 on pspadm.psp_entity_update_m122023 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m012024 on pspadm.psp_entity_update_m012024 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m022024 on pspadm.psp_entity_update_m022024 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m032024 on pspadm.psp_entity_update_m032024 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m042024 on pspadm.psp_entity_update_m042024 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m052024 on pspadm.psp_entity_update_m052024 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m062024 on pspadm.psp_entity_update_m062024 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m072024 on pspadm.psp_entity_update_m072024 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m082024 on pspadm.psp_entity_update_m082024 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m092024 on pspadm.psp_entity_update_m092024 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m102024 on pspadm.psp_entity_update_m102024 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m112024 on pspadm.psp_entity_update_m112024 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m122024 on pspadm.psp_entity_update_m122024 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m012025 on pspadm.psp_entity_update_m012025 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m022025 on pspadm.psp_entity_update_m022025 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m032025 on pspadm.psp_entity_update_m032025 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m042025 on pspadm.psp_entity_update_m042025 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m052025 on pspadm.psp_entity_update_m052025 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m062025 on pspadm.psp_entity_update_m062025 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m072025 on pspadm.psp_entity_update_m072025 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m082025 on pspadm.psp_entity_update_m082025 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m092025 on pspadm.psp_entity_update_m092025 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m102025 on pspadm.psp_entity_update_m102025 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m112025 on pspadm.psp_entity_update_m112025 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m122025 on pspadm.psp_entity_update_m122025 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m012026 on pspadm.psp_entity_update_m012026 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m022026 on pspadm.psp_entity_update_m022026 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m032026 on pspadm.psp_entity_update_m032026 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m042026 on pspadm.psp_entity_update_m042026 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m052026 on pspadm.psp_entity_update_m052026 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m062026 on pspadm.psp_entity_update_m062026 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m072026 on pspadm.psp_entity_update_m072026 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m082026 on pspadm.psp_entity_update_m082026 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m092026 on pspadm.psp_entity_update_m092026 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m102026 on pspadm.psp_entity_update_m102026 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m112026 on pspadm.psp_entity_update_m112026 USING BTREE (modified_date);
create index concurrently idx_ent_upd_mod_date_m122026 on pspadm.psp_entity_update_m122026 USING BTREE (modified_date);

