spool Disable_Triggers.log

ALTER TRIGGER PSPADM.TR_UPD_INTUIT_TAX_BANK_ACCT DISABLE;
ALTER TRIGGER PSPADM.TR_UPD_DD_LIMITS DISABLE;
ALTER TRIGGER PSPADM.TR_UPD_COMPANY_EVNT_TIMESTAMP DISABLE;
ALTER TRIGGER PSPADM.TR_UPD_COMPANY_EVENT_TIMESTAMP DISABLE;
ALTER TRIGGER PSPADM.PSP_TAX_PENALTY_INTEREST_AT DISABLE;
ALTER TRIGGER PSPADM.PSP_TAX_CS_INFO_AT DISABLE;
ALTER TRIGGER PSPADM.PSP_QUICKBOOKS_INFO_AT DISABLE;
ALTER TRIGGER PSPADM.PSP_MONEY_MVMT_TRANS_AT DISABLE;
ALTER TRIGGER PSPADM.PSP_INDIVIDUAL_AT DISABLE;
ALTER TRIGGER PSPADM.PSP_ENTITY_CHANGE_AT DISABLE;
ALTER TRIGGER PSPADM.PSP_EMPLOYEE_AT DISABLE;
ALTER TRIGGER PSPADM.PSP_DDCOMPANY_SERVICE_INFO_AT DISABLE;
ALTER TRIGGER PSPADM.PSP_CONTACT_AT DISABLE;
ALTER TRIGGER PSPADM.PSP_COMPANY_SERVICE_AT DISABLE;
ALTER TRIGGER PSPADM.PSP_COMPANY_PAYROLL_ITEM_AT DISABLE;
ALTER TRIGGER PSPADM.PSP_COMPANY_OFFER_AT DISABLE;
ALTER TRIGGER PSPADM.PSP_COMPANY_LAW_AT DISABLE;
ALTER TRIGGER PSPADM.PSP_COMPANY_BANK_ACCOUNT_AT DISABLE;
ALTER TRIGGER PSPADM.PSP_COMPANY_AT DISABLE;
ALTER TRIGGER PSPADM.PSP_COMPANY_AGENCY_AT DISABLE;
ALTER TRIGGER PSPADM.PSP_CMPNYAGENCY_PMTTPLT_AT DISABLE;
ALTER TRIGGER PSPADM.PSP_CMPMTMPLT_PMTMTD_AT DISABLE;
ALTER TRIGGER PSPADM.PSP_BPCOMPANY_SERVICE_INFO_AT DISABLE;
ALTER TRIGGER PSPADM.PSP_ADDRESS_AT DISABLE;


spool off;