# $Id: Makefile,v 1.4 2007/12/06 01:42:55 rgsage Exp $
#
include $(QBNBASE)/build/rules/base.mak
include $(QBNBASE)/build/rules/salsa.mak

all:: $(DIRS) pre

pre::

JAVA_PACKAGE = com/intuit/payroll/agency/api

JAVA_SRC = \
		IAgency.java \
		ICredentialData.java \
		ICredentialFormFooter.java \
		ICredentialFormHeader.java \
		ICredentialFormInputField.java \
		ICredentialFormLogin.java \
		IEnrollmentGroup.java \
		IFormFilingFrequency.java \
		IFormInfo.java \
		IFormRulesInfo.java \
		IFormSubmitMethod.java \
		IFormTemplateGroup.java \
		IJurisdiction.java \
		IPaymentFrequency.java \
		IPaymentMethodRule.java \
		IPaymentPeriod.java \
		IPaymentPeriodRequest.java \
		IPaymentReason.java \
		IRulesFormTemplate.java \
		IRulesInfo.java \
		IRulesList.java \
		IRulesPaymentTemplate.java \
		ISubmitMethod.java \
		NoResultsFoundException.java \
		PaymentPeriodRequestType.java \
		UserFrequencyType.java \
		ReleaseStatus.java \
		RoundingType.java \
		ReconciliationFrequencyType.java \
		RulesObjectBroker.java

include $(QBNBASE)/build/rules/java.mak



