\timing
set search_path to ibobadm;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m082018_from_cris;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m082018_from_psp;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m082018_from_qbdt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m082018_from_null;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m092018_from_ews;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m092018_from_cris;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m092018_from_as400;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m092018_from_psp;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m092018_from_dflt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m092018_from_qbdt;
SELECT pg_sleep(60);
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m092018_from_null;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m102018_from_ews;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m102018_from_as400;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m102018_from_dflt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m102018_from_qbdt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m102018_from_cris;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m102018_from_psp;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m112018_from_cris;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m102018_from_null;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m112018_from_as400;
SELECT pg_sleep(60);
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m112018_from_ews;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m112018_from_qbdt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m112018_from_null;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m112018_from_dflt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m112018_from_psp;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m122018_from_dflt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m122018_from_as400;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m122018_from_cris;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m122018_from_ews;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m122018_from_qbdt;
SELECT pg_sleep(60);
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m122018_from_psp;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m122018_from_null;
vacuum (analyze, verbose)  awsdms_control_table.awsdms_history;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m042022_from_psp;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m042022_from_cris;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m052022_from_cris;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m042022_from_dflt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m042022_from_as400;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m052022_from_dflt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m052022_from_null;
SELECT pg_sleep(60);
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m052022_from_as400;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m042022_from_qbdt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m052022_from_qbdt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m042022_from_null;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m052022_from_ews;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m042022_from_ews;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m082022_from_qbdt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m052022_from_psp;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m062022_from_dflt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m082022_from_as400;
