\timing
set search_path to ibobadm;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m062022_from_as400;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m072022_from_psp;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m072022_from_dflt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m082022_from_dflt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m082022_from_ews;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m082022_from_null;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m082022_from_psp;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m062022_from_cris;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m062022_from_null;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m062022_from_qbdt;
SELECT pg_sleep(60);
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m072022_from_cris;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m062022_from_ews;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m072022_from_ews;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m072022_from_qbdt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m062022_from_psp;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m112022_from_qbdt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m072022_from_as400;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m072022_from_null;
vacuum (analyze, verbose)  mchoubey.psp_sst_backup;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m082022_from_cris;
SELECT pg_sleep(60);
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m112022_from_ews;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m112022_from_psp;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m042018_from_ews;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m092014_from_cris;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m062018_from_ews;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m052018_from_cris;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m072018_from_cris;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m082018_from_dflt;
vacuum (analyze, verbose)  perfstat.pg_stat_activity_sample_p2022_12_19;
vacuum (analyze, verbose)  perfstat.pg_stat_statements_hist_p2022_12_19;
SELECT pg_sleep(60);
vacuum (analyze, verbose)  perfstat.pg_stat_all_indexes_hist_p2022_12_19;
vacuum (analyze, verbose)  perfstat.pg_stat_all_tables_hist_p2022_12_19;
vacuum (analyze, verbose)  perfstat.pg_stat_activity_hist_p2022_12_19;
vacuum (analyze, verbose)  perfstat.pg_stat_database_hist_p2022_12_19;
vacuum (analyze, verbose)  perfstat.dba_plans_hist_p2022_12_19;
vacuum (analyze, verbose)  perfstat.snap_p2022_12_19;
vacuum (analyze, verbose)  perfstat.pg_stat_activity_sample_p2022_12_20;
vacuum (analyze, verbose)  perfstat.dba_plans_hist_p2022_12_20;
vacuum (analyze, verbose)  perfstat.pg_stat_all_tables_hist_p2022_12_20;
vacuum (analyze, verbose)  perfstat.pg_stat_all_indexes_hist_p2022_12_20;
SELECT pg_sleep(60);
vacuum (analyze, verbose)  perfstat.pg_stat_statements_hist_p2022_12_20;
vacuum (analyze, verbose)  perfstat.pg_stat_database_hist_p2022_12_20;
vacuum (analyze, verbose)  perfstat.snap_p2022_12_20;
vacuum (analyze, verbose)  perfstat.pg_stat_activity_hist_p2022_12_20;
vacuum (analyze, verbose)  perfstat.pg_stat_activity_sample_p2022_12_21;
vacuum (analyze, verbose)  perfstat.snap_p2022_12_21;
vacuum (analyze, verbose)  perfstat.pg_stat_activity_hist_p2022_12_21;
vacuum (analyze, verbose)  perfstat.pg_stat_database_hist_p2022_12_21;
vacuum (analyze, verbose)  perfstat.pg_stat_statements_hist_p2022_12_21;
vacuum (analyze, verbose)  perfstat.pg_stat_all_indexes_hist_p2022_12_21;
SELECT pg_sleep(60);
vacuum (analyze, verbose)  perfstat.dba_plans_hist_p2022_12_21;
vacuum (analyze, verbose)  perfstat.pg_stat_all_tables_hist_p2022_12_21;
vacuum (analyze, verbose)  pg_statistic;
vacuum (analyze, verbose)  perfstat.pg_stat_activity_sample_p2022_12_22;
vacuum (analyze, verbose)  perfstat.pg_stat_all_indexes_hist_p2022_12_22;
vacuum (analyze, verbose)  perfstat.pg_stat_all_tables_hist_p2022_12_22;
vacuum (analyze, verbose)  perfstat.dba_plans_hist_p2022_12_22;
vacuum (analyze, verbose)  perfstat.pg_stat_database_hist_p2022_12_22;
vacuum (analyze, verbose)  perfstat.snap_p2022_12_22;
vacuum (analyze, verbose)  perfstat.pg_stat_statements_hist_p2022_12_22;
vacuum (analyze, verbose)  perfstat.pg_stat_activity_hist_p2022_12_22;
