\timing
set search_path to ibobadm;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042016_from_psp ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052017_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052012_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052016_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112013_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022015_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022017_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042015_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102019_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032015_from_cris ;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102021_from_as400 ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042017_from_as400 ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052020_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042015_from_qbdt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122009_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072019_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072010_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072019_from_psp ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122009_from_null ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112019_from_ews ;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122020_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042017_from_qbdt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082012_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082012_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082015_from_psp ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082015_from_null ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082015_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092021_from_qbdt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022021_from_as400 ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102017_from_as400 ;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062012_from_as400 ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112017_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122021_from_qbdt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052015_from_psp ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122021_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042010_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022020_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062012_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062017_from_psp ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032012_from_ews ;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022017_from_psp ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122015_from_null ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012012_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072012_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072015_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072015_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122020_from_qbdt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122016_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022012_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012015_from_dflt ;

