DROP TABLE IF EXISTS TEMP_PSP_AUTH_ROLE CASCADE;

--------------------------------------------------------
-- Create temp table                                  --
--------------------------------------------------------

CREATE TABLE TEMP_PSP_AUTH_ROLE (LIKE PSP_AUTH_ROLE INCLUDING ALL) ;

--------------------------------------------------------
-- Insert into temp table                             --
--------------------------------------------------------

INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK, CREATOR_ID)
VALUES ('23de8b0f-e437-35a1-a474-773de5778341', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'QBOE-IOPRep','QBOE-IOP Rep','QBOE-IOP Rep','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('54de8b0e-434d-a5e1-7e41-4435dea1c3d3', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'QBOE-IOPSeniorRep','QBOE-IOP Senior Rep',
'QBOE-IOP Senior Rep','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('830343df-4421-f4d1-5181-5d3d46a3135d', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'QBOE-IOPTeamLead','QBOE-IOP Team Lead',
'QBOE-IOP Team Lead','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('682d2a01-e3a1-d326-f452-f3a5dea1cd15', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'QBOE-IOPProductSpecialist','QBOE-IOP Product Specialist',
'QBOE-IOP Product Specialist','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('21a435de-d356-f352-f31d-552d4a5c3b3e', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'FRGRep','FRG Rep','FRG Rep','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('8391f43e-f3d3-3de1-4728-772d7341edc1', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'FRGSupervisor','FRG Supervisor','FRG Supervisor','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('1d42d34e-f3dd-ed24-3d42-6625d4672123', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'FRGManager','FRG Manager','FRG Manager','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('14de8b0e-434d-15e1-7d45-4d55dea1d21e', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'RMRep','RM Rep','RM Rep','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('13d48bcd-4d38-a532-7a42-4d4ddea11e23', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'RMSupervisor','RM Supervisor','RM Supervisor','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('a4de8b03-4341-ad23-7e47-423d3a4c13e6', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'RMManager','RM Manager','RM Manager','DDUI','System')
;

INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('635e8b0e-43f4-a631-5341-56d6a5327852', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'Accounting','Accounting','Accounting','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('635e8b0e-43f4-a631-5341-56d6a5327853', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'AccountingManager','Accounting Manager','Accounting Manager','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('23de845f-a1a3-f3e1-7e34-3d4ea672c37a', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'DesktopCareAgent','Desktop Care Agent','Desktop Care Agent','DDUI','System')

;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('134e8b0d-434d-f331-7345-f463dea1c1da', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'DesktopCareManager','Desktop Care Manager','Desktop Care Manager','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('83de8b3e-d35d-f4e1-a461-d565dea1c352', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'DirectDepositTierIII','Tier III - DIY/DD','Tier III - DIY/DD (Direct Deposit Tier III Offshore)','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('83de8b3e-d35d-f4e1-a461-d565dea1a911', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'PSSRepOnshore','SD - Full Service Agent','SD - Full Service Agent (PS&S Rep Onshore)','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('83de8b3e-d35d-f4e1-a461-d565dea1a912', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'PSSActivationsChat','SD - Activations Agent','SD - Activations Agent (PS&S & Activations Chat)','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('83de8b3e-d35d-f4e1-a461-d565dea1a915', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'KnowledgeAdvisor','Knowledge Advisor','Knowledge Advisor','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('83de8b3e-d35d-f4e1-a461-d565dea1a916', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'PPS','PPS Agent','PPS','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('83de8b3e-d35d-f4e1-a461-d565dea1a917', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'PPSManager','PPS Manager','PPS Manager','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('83de8b3e-d35d-f4e1-a461-d565dea1a918', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'PPSRAF','PPS RAF/Enrollment','PPS RAF/Enrollment','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('83de8b3e-d35d-f4e1-a461-d565dea1a919', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'PPSManualLedger','PPS Manual Ledger','PPS Manual Ledger','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('83de8b3e-d35d-f4e1-a461-d565dea1a920', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'PPSManualLedgerAdmin','PPS Manual Ledger Admin','PPS Manual Ledger Admin','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('83de8b3e-d35d-f4e1-a461-d565dea1a91a', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'PPSPayments','PPS Payments','PPS Payments','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('83de8b3e-d35d-f4e1-a461-d565dea1a91b', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'PPSTierIII','PPS Tier III','PPS Tier III','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('67de8bde-f35d-d4e1-c461-d3562a41242e', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'DirectDepositSME','SD - DIY/DD Supervisor/Lead','SD - DIY/DD Supervisor/Lead (Direct Deposit SME)','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('64de8b0f-334d-a5e3-7e45-4d46dea1c3d9', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'Admin','Admin','Admin','AUTH','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('a5263743-7cf0-42fc-b164-25ea68315761', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'HelpDesk','Help Desk','Help Desk','AUTH','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('a5263743-7cf0-42fc-b164-25ea68315767', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'DataCustodian','Data Custodian','Data Custodian','AUTH','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('635e8b0e-43f4-a631-5341-56d6a5327854', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'ReadOnly','Read Only','Read Only','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('695e8b0e-43f4-a631-5341-88d6a5327112', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'PSOAgent','PSO Agent','PSO Agent','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('685e8b0e-43f4-a631-5341-77d6a5327234', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'POA','POA','POA','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('675e8b0e-43f4-a631-5341-66d6a5327356', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'Operator','Operator','Operator','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('69999999-43f4-a631-5341-66d6a5327356', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'NoAccess','No Access','No Access','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('675e8b0e-43f4-a631-5341-68d6a5327356', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'DesktopCareLead','Desktop Care Lead','Desktop Care Lead','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('675e8b0e-43f4-a631-5341-69d6a5327356', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'ActivationsTierIII','Tier III - Full Service','Tier III - Full Service (PS&S & Activations Tier III)','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('675e8b0e-43f4-a631-5341-6bd6a5327356', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'WOTCTaxRep','WOTC Tax Rep','WOTC Tax Rep','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('675e8b0e-43f4-a631-5341-6cd6a5327356', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'PrintQueueAgent','Print Queue Agent','Print Queue Agent','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('675e8b0e-43f4-a631-5341-6dd6a5327356', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'CheckDistributionAgent','Check Distribution Agent','Check Distribution Agent','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('675e8b0e-43f4-a631-5341-6ed6a5327356', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'EngineeringReadOnly','Engineering Read Only','Engineering Read Only','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('675e8b0e-43f4-a631-5341-6fd6a5327356', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'CS-RMRep','CS-RM Rep','CS-RM Rep','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('134e8b0d-434d-f331-7345-f463dea1beef', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'PPSCancellations', 'PPS Cancellations', 'PPS Cancellations', 'DDUI', 'System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('134e8b0d-434d-f331-a345-f463dea1beef', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'CCTAgent', 'PPS Customer Correction Team', 'PPS Customer Correction Team', 'DDUI', 'System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('134e8b0d-434d-f331-a345-f463dea2beef', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'PPSEntity', 'PPS - Entity', 'PPS - Entity', 'DDUI', 'System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('134e8b0d-434d-f331-a345-f463dea3beef', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'PPSAccountMaintenance', 'PPS - Acct Maintenance', 'PPS - Acct Maintenance', 'DDUI', 'System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('134e8b0d-434d-f331-a345-f463dea4beef', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'SalesAgent', 'Sales Agent', 'Sales Agent', 'DDUI', 'System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('134e8b0d-434d-f331-a345-f463dea5beef', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'SalesManager', 'Sales Manager', 'Sales Manager', 'DDUI', 'System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('134e8b0d-434d-f331-a345-f463dea6beef', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'MarketingOps', 'Marketing Ops', 'Marketing Ops', 'DDUI', 'System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('635e8b0e-43f4-a631-5341-56d6a5327959', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'PPSSUIAgent','PPS SUI Agent','PPS SUI Agent','DDUI','System')
;


INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('635e8b0e-43f4-a631-5341-56d6a5327856', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'AccountingRM','AccountingRM','AccountingRM','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('635e8b0e-43f4-a631-5341-56d6a5322456', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'EngineeringAdmin','Engineering Admin','Engineering Admin','DDUI','System')
;

INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('635e8b2e-43f4-a631-5341-56d6a5322456', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'OrderControl','Order Control','Order Control','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('635e8b5e-43f4-a631-5341-56d6a5322456', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'AssistedDataSteward','Assisted Data Steward','Assisted Data Steward','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('635e8b7e-43f4-a631-5341-56d6a5322456', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'IFSP','IFSP','IFSP Agent','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('635e8b8e-43f4-a631-5341-56d6a5322456', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'DISAgent','DIS Agent','Role for DIS backend processes','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('635e8b8e-43f4-a631-5341-56d6a5322457', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'PPSNoticeAgent','PPS Notice Agent','PPS Notice Agent','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('635e8b8e-43f4-a631-5341-56d6a5322458', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'DirectDepositManagerSME','Direct Deposit Manager SME','Direct Deposit Manager SME','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('635e8b8e-43f4-a631-5341-56d6a5322459', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'RTBAdmin','RTB Admin','RTB Admin','DDUI','System')
;
INSERT INTO TEMP_PSP_AUTH_ROLE ( AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
VALUES ('635e8b8e-43f4-a631-5341-56d6a5322159', 0, LOCALTIMESTAMP, LOCALTIMESTAMP, 'RTBAutomationAdmin','RTB Automation Admin','RTB Automation Admin','DDUI','System')
;




--------------------------------------------------------
-- Sychronize temp table and real table by            --
-- inserting, deleting, and updating as necessary     --
--------------------------------------------------------

INSERT INTO PSP_AUTH_ROLE
   (AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID)
SELECT
    AUTH_ROLE_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID,NAME,DESCRIPTION, AUTH_DOMAIN_FK,CREATOR_ID
FROM
   TEMP_PSP_AUTH_ROLE tt
WHERE
   tt.AUTH_ROLE_SEQ NOT IN (SELECT AUTH_ROLE_SEQ FROM PSP_AUTH_ROLE)

;

DELETE FROM PSP_AUTHROLE_OPERATION_ASSOC
WHERE AUTH_ROLE_FK NOT IN (SELECT AUTH_ROLE_SEQ FROM TEMP_PSP_AUTH_ROLE)
;

DELETE FROM PSP_ROLE_SUB_STATUS
WHERE AUTH_ROLE_FK NOT IN (SELECT AUTH_ROLE_SEQ FROM TEMP_PSP_AUTH_ROLE)
;
DELETE FROM PSP_AUTH_ROLE
WHERE AUTH_ROLE_SEQ NOT IN (SELECT AUTH_ROLE_SEQ FROM TEMP_PSP_AUTH_ROLE) AND CREATOR_ID = 'System'
;

UPDATE PSP_AUTH_ROLE rt
SET (VERSION, CREATED_DATE, MODIFIED_DATE, ROLE_ID, NAME, DESCRIPTION, AUTH_DOMAIN_FK, CREATOR_ID) =
(SELECT tt.VERSION, tt.CREATED_DATE, tt.MODIFIED_DATE, tt.ROLE_ID,tt.NAME,tt.DESCRIPTION, tt.AUTH_DOMAIN_FK,tt.CREATOR_ID
 FROM TEMP_PSP_AUTH_ROLE tt WHERE tt.AUTH_ROLE_SEQ = rt.AUTH_ROLE_SEQ)
WHERE rt.AUTH_ROLE_SEQ IN (SELECT AUTH_ROLE_SEQ FROM TEMP_PSP_AUTH_ROLE) AND CREATOR_ID = 'System' 
;

--------------------------------------------------------
-- Drop temp table                                  --
--------------------------------------------------------
DROP TABLE TEMP_PSP_AUTH_ROLE

;
COMMIT
