DROP TABLE IF EXISTS TEMP_PSP_INTUIT_BANK_ACCOUNT CASCADE

;

--------------------------------------------------------
-- Create temp table                                  --
--------------------------------------------------------
CREATE TABLE TEMP_PSP_INTUIT_BANK_ACCOUNT (LIKE PSP_INTUIT_BANK_ACCOUNT INCLUDING ALL)

;

--------------------------------------------------------
-- Insert into temp table                             --
--------------------------------------------------------

INSERT INTO TEMP_PSP_INTUIT_BANK_ACCOUNT ( INTUIT_BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE,  BANK_ACCOUNT_FK, DESCRIPTION, EFF_DTTM,EXP_DTTM ) VALUES ( 
'a5263743-7cf0-42fc-b164-25ea68315756',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'a5263743-7cf0-42fc-b164-25ea68315756', 'INTUIT FEE', NULL, NULL)
; 
INSERT INTO TEMP_PSP_INTUIT_BANK_ACCOUNT ( INTUIT_BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE,  BANK_ACCOUNT_FK, DESCRIPTION, EFF_DTTM,EXP_DTTM ) VALUES ( 
'a62f39f9-3aab-48ac-ace7-3ab8f700abb9',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'a62f39f9-3aab-48ac-ace7-3ab8f700abb9', 'INTUIT EE RETURN', NULL, NULL)
;
INSERT INTO TEMP_PSP_INTUIT_BANK_ACCOUNT ( INTUIT_BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE,  BANK_ACCOUNT_FK, DESCRIPTION, EFF_DTTM,EXP_DTTM ) VALUES ( 
'89057491-baf0-49dd-bbda-a5c5eff5a7d9',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '89057491-baf0-49dd-bbda-a5c5eff5a7d9', 'INTUIT ER RETURN', NULL, NULL)
;
INSERT INTO TEMP_PSP_INTUIT_BANK_ACCOUNT ( INTUIT_BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE,  BANK_ACCOUNT_FK, DESCRIPTION, EFF_DTTM,EXP_DTTM ) VALUES ( 
'3b76af25-eb67-4409-a559-225a85eee4b9',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '3b76af25-eb67-4409-a559-225a85eee4b9', 'INTUIT DD', NULL, NULL)
;
INSERT INTO TEMP_PSP_INTUIT_BANK_ACCOUNT ( INTUIT_BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE,  BANK_ACCOUNT_FK, DESCRIPTION, EFF_DTTM,EXP_DTTM ) VALUES ( 
'3b76af25-eb68-4409-a559-225a85eee4b9',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '3b76af25-eb68-4409-a559-225a85eee4b9', 'INTUIT TAX', NULL, NULL)
;
INSERT INTO TEMP_PSP_INTUIT_BANK_ACCOUNT ( INTUIT_BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE,  BANK_ACCOUNT_FK, DESCRIPTION, EFF_DTTM,EXP_DTTM ) VALUES (
'3b76af25-eb69-4409-a559-225a85eee4b9',0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '3b76af25-eb69-4409-a559-225a85eee4b9', 'INTUIT CHECK', NULL, NULL)
;

--------------------------------------------------------
-- Sychronize temp table and real table by            --
-- inserting, deleting, and updating as necessary     --
--------------------------------------------------------

INSERT INTO PSP_INTUIT_BANK_ACCOUNT
   (INTUIT_BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE,  BANK_ACCOUNT_FK, DESCRIPTION, EFF_DTTM,EXP_DTTM  )
SELECT 
    INTUIT_BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE,  BANK_ACCOUNT_FK, DESCRIPTION, EFF_DTTM,EXP_DTTM 
FROM 
   TEMP_PSP_INTUIT_BANK_ACCOUNT tt 
WHERE 
   tt.INTUIT_BANK_ACCOUNT_SEQ NOT IN (SELECT INTUIT_BANK_ACCOUNT_SEQ FROM PSP_INTUIT_BANK_ACCOUNT)

;

DELETE FROM PSP_INTUIT_BANK_ACCOUNT
WHERE INTUIT_BANK_ACCOUNT_SEQ NOT IN (SELECT INTUIT_BANK_ACCOUNT_SEQ FROM TEMP_PSP_INTUIT_BANK_ACCOUNT) 

;

UPDATE PSP_INTUIT_BANK_ACCOUNT rt
SET ( VERSION, CREATED_DATE, MODIFIED_DATE,  BANK_ACCOUNT_FK, DESCRIPTION, EFF_DTTM, EXP_DTTM ) =
(SELECT tt.VERSION,  tt.CREATED_DATE,  tt.MODIFIED_DATE,  tt.BANK_ACCOUNT_FK, tt.DESCRIPTION, tt.EFF_DTTM, tt.EXP_DTTM
 FROM TEMP_PSP_INTUIT_BANK_ACCOUNT tt WHERE tt.INTUIT_BANK_ACCOUNT_SEQ = rt.INTUIT_BANK_ACCOUNT_SEQ)
;



--------------------------------------------------------
-- Drop temp table                                  --
--------------------------------------------------------
DROP TABLE TEMP_PSP_INTUIT_BANK_ACCOUNT

;
COMMIT
 

 
