set echo on timiming on feedback on
spool CREATE_LOCAL_INDEXEX_ON_STAGING_HASH

exec rdsadmin.rdsadmin_dbms_scheduler.disable('SYS.CLEANUP_ONLINE_IND_BUILD');

CREATE INDEX PSPADM.IDX_FT_SETLLEMENT_DATE ON PSPADM.PSP_FINANCIAL_TRANSACTION (SETTLEMENT_DATE) local online parallel (degree 8) TABLESPACE PSP_IDX01;
CREATE INDEX PSPADM.IDX_PAYCHECK_SPLIT_CR_DATE ON PSPADM.PSP_PAYCHECK_SPLIT (CREATED_DATE) local online parallel (degree 8) TABLESPACE PSP_IDX03;
alter index PSPADM.IDX_FT_SETLLEMENT_DATE NOPARALLEL;
alter index IDX_PAYCHECK_SPLIT_CR_DATE NOPARALLEL;

exec rdsadmin.rdsadmin_dbms_scheduler.enable('SYS.CLEANUP_ONLINE_IND_BUILD');
spool off
