\timing
set search_path to ibobadm;

vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042024_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052024_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052024_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042024_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052024_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062024_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062024_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052024_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062024_from_ews;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062024_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052024_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052024_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062024_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062024_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062024_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072024_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082024_from_cris;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082024_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072024_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082024_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072024_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072024_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072024_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072024_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072024_from_as400;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082024_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082024_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082024_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092024_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092024_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092024_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092024_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092024_from_as400;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082024_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092024_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112024_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102024_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102024_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102024_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102024_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102024_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102024_from_ews;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102024_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092024_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112024_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122024_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112024_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112024_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112024_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122024_from_as400;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122024_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112024_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122024_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122024_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112024_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012023_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122024_from_psp;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122024_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012023_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012023_from_psp;
vacuum (analyze, verbose) partman.template_perfstat_pg_stat_all_tables_hist;
vacuum (analyze, verbose) partman.part_config;
vacuum (analyze, verbose) partman.template_perfstat_pg_stat_activity_sample;
vacuum (analyze, verbose) perfstat.pg_stat_activity_hist_default;
vacuum (analyze, verbose) partman.part_config_sub;
SELECT pg_sleep(60);
vacuum (analyze, verbose) partman.template_perfstat_pg_stat_activity_hist;
vacuum (analyze, verbose) partman.template_perfstat_pg_stat_statements_hist;
vacuum (analyze, verbose) partman.template_perfstat_snap;
vacuum (analyze, verbose) partman.template_perfstat_dba_plans_hist;
vacuum (analyze, verbose) perfstat.dba_plans_hist_default;
vacuum (analyze, verbose) perfstat.pg_stat_activity_sample_default;
SELECT pg_sleep(60);
vacuum (analyze, verbose) perfstat.pg_stat_all_indexes_hist_default;
vacuum (analyze, verbose) perfstat.pg_stat_all_tables_hist_default;
vacuum (analyze, verbose) perfstat.snap_default;
vacuum (analyze, verbose) partman.custom_time_partitions;
vacuum (analyze, verbose) partman.template_perfstat_pg_stat_database_hist;
vacuum (analyze, verbose) perfstat.pg_stat_statements_hist_default;
vacuum (analyze, verbose) perfstat.pg_stat_database_hist_default;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022011_from_qbdt;
vacuum (analyze, verbose) partman.template_perfstat_pg_stat_all_indexes_hist;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022011_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032011_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032011_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032011_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022011_from_cris;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032011_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022011_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032011_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012011_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012011_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012011_from_dflt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022011_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012011_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012011_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012011_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032011_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012011_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022011_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092011_from_qbdt;

