\timing

vacuum (analyze, verbose) ibobadm.table_b;
vacuum (analyze, verbose) perfstat.pg_stat_activity_sample_p2023_05_20;
vacuum (analyze, verbose) perfstat.pg_stat_activity_hist_p2023_05_20;
vacuum (analyze, verbose) perfstat.pg_stat_statements_hist_p2023_05_20;
vacuum (analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_05_20;
vacuum (analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_05_20;
vacuum (analyze, verbose) perfstat.dba_plans_hist_p2023_05_20;
vacuum (analyze, verbose) perfstat.pg_stat_activity_sample_p2023_05_21;
vacuum (analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_05_21;
vacuum (analyze, verbose) perfstat.pg_stat_activity_hist_p2023_05_21;
vacuum (analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_05_21;
vacuum (analyze, verbose) perfstat.pg_stat_statements_hist_p2023_05_21;
vacuum (analyze, verbose) perfstat.dba_plans_hist_p2023_05_21;
vacuum (analyze, verbose) perfstat.pg_stat_activity_sample_p2023_05_22;
vacuum (analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_05_22;
vacuum (analyze, verbose) perfstat.dba_plans_hist_p2023_05_22;
SELECT pg_sleep(60);
vacuum (analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_05_22;
vacuum (analyze, verbose) perfstat.pg_stat_activity_hist_p2023_05_22;
vacuum (analyze, verbose) perfstat.pg_stat_statements_hist_p2023_05_22;
vacuum (analyze, verbose) perfstat.pg_stat_activity_sample_p2023_05_23;
vacuum (analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_05_23;
vacuum (analyze, verbose) perfstat.pg_stat_statements_hist_p2023_05_23;
vacuum (analyze, verbose) perfstat.pg_stat_activity_hist_p2023_05_23;
vacuum (analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_05_23;
vacuum (analyze, verbose) perfstat.dba_plans_hist_p2023_05_23;
vacuum (analyze, verbose) pg_subscription_rel;
vacuum (analyze, verbose) pg_publication_rel;
vacuum (analyze, verbose) pg_transform;
vacuum (analyze, verbose) pg_language;
SELECT pg_sleep(60);
vacuum (analyze, verbose) pg_largeobject_metadata;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052012_from_dflt;
vacuum (analyze, verbose) pg_shseclabel;
vacuum (analyze, verbose) pg_partitioned_table;
vacuum (analyze, verbose) pg_user_mapping;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062010_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032019_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012010_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032010_from_dflt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082019_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102021_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062010_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012019_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042010_from_null;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012019_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022019_from_ews;
vacuum (analyze, verbose) information_schema.sql_features;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092021_from_dflt;
vacuum (analyze, verbose) information_schema.sql_implementation_info;
vacuum (analyze, verbose) information_schema.sql_parts;
vacuum (analyze, verbose) pg_operator;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112019_from_dflt;
vacuum (analyze, verbose) pg_opfamily;
vacuum (analyze, verbose) pg_opclass;
vacuum (analyze, verbose) pg_am;
vacuum (analyze, verbose) pg_aggregate;
vacuum (analyze, verbose) pg_statistic_ext;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022010_from_dflt;
vacuum (analyze, verbose) information_schema.sql_sizing;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012010_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022015_from_dflt;
vacuum (analyze, verbose) pg_trigger;
vacuum (analyze, verbose) pg_rewrite;
vacuum (analyze, verbose) pg_event_trigger;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072010_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032020_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012021_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022020_from_dflt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092012_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052016_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062010_from_dflt;
vacuum (analyze, verbose) pg_type;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012016_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092013_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012012_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072021_from_null;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062013_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022021_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052021_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012013_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022012_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012013_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052021_from_as400;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012015_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012013_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012013_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012013_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012017_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032012_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012021_from_ews;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082019_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012017_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052020_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062019_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012019_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082019_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022020_from_null;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082017_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102015_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052020_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102009_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122010_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042010_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122009_from_dflt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032019_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062019_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092009_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042020_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082009_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042019_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122017_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122009_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102010_from_null;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072009_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052010_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092009_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052020_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082010_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112009_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052015_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122009_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022017_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112009_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102009_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042019_from_null
SELECT pg_sleep(60);;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022019_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082020_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092019_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112017_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052020_from_as400;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082013_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012016_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092017_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052019_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042012_from_dflt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042021_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072012_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122016_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012021_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062015_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092013_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032015_from_qbdt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012015_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032021_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052016_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012016_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022021_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032012_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082021_from_as400;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082013_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082017_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062020_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062020_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062020_from_qbdt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062020_from_as400;
vacuum (analyze, verbose) perfstat.pg_stat_activity_sample_p2023_05_24;
vacuum (analyze, verbose) perfstat.dba_plans_hist_p2023_05_24;
vacuum (analyze, verbose) perfstat.pg_stat_activity_hist_p2023_05_24;
vacuum (analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_05_24;
vacuum (analyze, verbose) perfstat.pg_stat_statements_hist_p2023_05_24;
SELECT pg_sleep(60);
vacuum (analyze, verbose) perfstat.snap_p2023_05_24;
vacuum (analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_05_24;
vacuum (analyze, verbose) perfstat.pg_stat_database_hist_p2023_05_24;
vacuum (analyze, verbose) perfstat.pg_stat_activity_sample_p2023_05_25;
vacuum (analyze, verbose) perfstat.snap_p2023_05_25;
vacuum (analyze, verbose) perfstat.pg_stat_database_hist_p2023_05_25;
vacuum (analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_05_25;
vacuum (analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_05_25;
vacuum (analyze, verbose) perfstat.dba_plans_hist_p2023_05_25;
vacuum (analyze, verbose) perfstat.pg_stat_activity_hist_p2023_05_25;
vacuum (analyze, verbose) perfstat.pg_stat_statements_hist_p2023_05_25;
vacuum (analyze, verbose) perfstat.pg_stat_activity_sample_p2023_05_26;
vacuum (analyze, verbose) perfstat.snap_p2023_05_26;
vacuum (analyze, verbose) perfstat.dba_plans_hist_p2023_05_26;
vacuum (analyze, verbose) perfstat.pg_stat_activity_hist_p2023_05_26;
vacuum (analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_05_26;
vacuum (analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_05_26;
vacuum (analyze, verbose) perfstat.pg_stat_statements_hist_p2023_05_26;
vacuum (analyze, verbose) perfstat.pg_stat_database_hist_p2023_05_26;
vacuum (analyze, verbose) perfstat.pg_stat_activity_sample_p2023_05_27;
vacuum (analyze, verbose) perfstat.dba_plans_hist_p2023_05_27;
vacuum (analyze, verbose) perfstat.pg_stat_database_hist_p2023_05_27;
vacuum (analyze, verbose) perfstat.pg_stat_activity_hist_p2023_05_27;
vacuum (analyze, verbose) perfstat.snap_p2023_05_27;
vacuum (analyze, verbose) perfstat.pg_stat_statements_hist_p2023_05_27;
vacuum (analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_05_27;
vacuum (analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_05_27;
vacuum (analyze, verbose) pg_attribute;
vacuum (analyze, verbose) pg_class;
