\timing
set search_path to ibobadm;
vacuum (analyze, verbose) pg_partitioned_table ;
vacuum (analyze, verbose) pg_transform ;
vacuum (analyze, verbose) pg_attrdef ;
vacuum (analyze, verbose) pg_sequence ;
vacuum (analyze, verbose) pg_constraint ;
vacuum (analyze, verbose) pg_publication ;
vacuum (analyze, verbose) information_schema.sql_parts ;
vacuum (analyze, verbose) pg_publication_rel ;
vacuum (analyze, verbose) information_schema.sql_implementation_info ;
vacuum (analyze, verbose) pg_subscription_rel ;
vacuum (analyze, verbose) pg_type ;
vacuum (analyze, verbose) pg_user_mapping ;
vacuum (analyze, verbose) information_schema.sql_sizing ;
vacuum (analyze, verbose) information_schema.sql_features ;
vacuum (analyze, verbose) pg_range ;
vacuum (analyze, verbose) pg_subscription ;
vacuum (analyze, verbose) pg_proc ;
vacuum (analyze, verbose) pg_collation ;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062010_from_null ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022010_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012019_from_as400 ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012019_from_null ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062010_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012010_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022019_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112019_from_dflt ;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_hcm401k_company_qbdt_pitem ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022019_from_as400 ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022020_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032019_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032010_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_hcm401k_company_policy ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082019_from_as400 ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062010_from_as400 ;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042010_from_null ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022019_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_sap_method_call ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092021_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122017_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012010_from_as400 ;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052020_from_psp ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092012_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052016_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062012_from_psp ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052021_from_qbdt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022015_from_dflt ;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102021_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012021_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052012_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092015_from_dflt ;
