\timing
set search_path to ibobadm;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052013_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052013_from_psp ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062016_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042012_from_null ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022021_from_psp ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112015_from_null ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052021_from_null ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102015_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062013_from_null ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092016_from_cris ;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062021_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022016_from_qbdt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092019_from_qbdt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092021_from_as400 ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062020_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112019_from_qbdt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032017_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112010_from_null ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062020_from_null ;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092020_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082012_from_psp ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102019_from_null ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082012_from_null ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122017_from_null ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062016_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072015_from_null ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082013_from_as400 ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032012_from_as400 ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112015_from_psp ;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032013_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062015_from_psp ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062016_from_qbdt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062017_from_as400 ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062017_from_null ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062017_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012016_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092020_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122010_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032013_from_qbdt ;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112010_from_psp ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122019_from_null ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102009_from_null ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082009_from_psp ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072010_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102019_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112019_from_null ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012010_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052010_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032019_from_qbdt ;

