\timing

vacuum (analyze, verbose) perfstat.dba_plans_hist_p2023_03_15;;
vacuum (analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_03_15;
vacuum (analyze, verbose) perfstat.pg_stat_activity_hist_p2023_03_15;
vacuum (analyze, verbose) perfstat.pg_stat_statements_hist_p2023_03_15;
vacuum (analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_03_15;
vacuum (analyze, verbose) perfstat.pg_stat_activity_sample_p2023_03_16;
vacuum (analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_03_16;
vacuum (analyze, verbose) perfstat.pg_stat_activity_hist_p2023_03_16;
SELECT pg_sleep(60);
vacuum (analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_03_16;
vacuum (analyze, verbose) perfstat.pg_stat_statements_hist_p2023_03_16;
vacuum (analyze, verbose) perfstat.dba_plans_hist_p2023_03_16;
vacuum (analyze, verbose) perfstat.pg_stat_activity_sample_p2023_03_17;
vacuum (analyze, verbose) perfstat.pg_stat_statements_hist_p2023_03_17;
vacuum (analyze, verbose) perfstat.dba_plans_hist_p2023_03_17;
vacuum (analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_03_17;
vacuum (analyze, verbose) perfstat.pg_stat_activity_hist_p2023_03_17;
SELECT pg_sleep(60);
vacuum (analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_03_17;
vacuum (analyze, verbose) perfstat.pg_stat_activity_sample_p2023_03_18;
vacuum (analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_03_18;
vacuum (analyze, verbose) perfstat.pg_stat_activity_hist_p2023_03_18;
vacuum (analyze, verbose) perfstat.pg_stat_statements_hist_p2023_03_18;
vacuum (analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_03_18;
vacuum (analyze, verbose) perfstat.dba_plans_hist_p2023_03_18;
SELECT pg_sleep(60);
vacuum (analyze, verbose) perfstat.pg_stat_activity_sample_p2023_03_19;
vacuum (analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_03_19;
vacuum (analyze, verbose) perfstat.dba_plans_hist_p2023_03_19;
vacuum (analyze, verbose) perfstat.pg_stat_statements_hist_p2023_03_19;
vacuum (analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_03_19;
vacuum (analyze, verbose) perfstat.pg_stat_activity_hist_p2023_03_19;
vacuum (analyze, verbose) perfstat.pg_stat_activity_sample_p2023_03_20;
vacuum (analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_03_20;
vacuum (analyze, verbose) perfstat.dba_plans_hist_p2023_03_20;
SELECT pg_sleep(60);
vacuum (analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_03_20;
vacuum (analyze, verbose) perfstat.pg_stat_activity_hist_p2023_03_20;
vacuum (analyze, verbose) perfstat.pg_stat_statements_hist_p2023_03_20;
vacuum (analyze, verbose) perfstat.pg_stat_activity_sample_p2023_03_21;
vacuum (analyze, verbose) perfstat.dba_plans_hist_p2023_03_21;
vacuum (analyze, verbose) perfstat.pg_stat_statements_hist_p2023_03_21;
vacuum (analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_03_21;
vacuum (analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_03_21;
vacuum (analyze, verbose) perfstat.pg_stat_activity_hist_p2023_03_21;
vacuum (analyze, verbose) perfstat.pg_stat_activity_sample_p2023_03_22;
vacuum (analyze, verbose) perfstat.pg_stat_statements_hist_p2023_03_22;
vacuum (analyze, verbose) perfstat.pg_stat_activity_hist_p2023_03_22;
SELECT pg_sleep(60);
vacuum (analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_03_22;
vacuum (analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_03_22;
vacuum (analyze, verbose) perfstat.dba_plans_hist_p2023_03_22;
vacuum (analyze, verbose) perfstat.pg_stat_activity_sample_p2023_03_23;
vacuum (analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_03_23;
vacuum (analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_03_23;
vacuum (analyze, verbose) perfstat.pg_stat_activity_hist_p2023_03_23;
vacuum (analyze, verbose) perfstat.pg_stat_statements_hist_p2023_03_23;
vacuum (analyze, verbose) perfstat.dba_plans_hist_p2023_03_23;
vacuum (analyze, verbose) perfstat.pg_stat_activity_sample_p2023_03_24;
vacuum (analyze, verbose) perfstat.pg_stat_statements_hist_p2023_03_24;
vacuum (analyze, verbose) perfstat.dba_plans_hist_p2023_03_24;
SELECT pg_sleep(60);
vacuum (analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_03_24;
vacuum (analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_03_24;
vacuum (analyze, verbose) perfstat.pg_stat_activity_hist_p2023_03_24;
vacuum (analyze, verbose) perfstat.pg_stat_activity_sample_p2023_03_25;
vacuum (analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_03_25;
vacuum (analyze, verbose) perfstat.pg_stat_statements_hist_p2023_03_25;
vacuum (analyze, verbose) perfstat.pg_stat_activity_hist_p2023_03_25;
vacuum (analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_03_25;
vacuum (analyze, verbose) perfstat.dba_plans_hist_p2023_03_25;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022023_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022023_from_ews;
SELECT pg_sleep(60);
vacuum (analyze, verbose) pg_class;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022023_from_psp;
vacuum (analyze, verbose) pg_attribute;
vacuum (analyze, verbose) pg_type;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122022_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122022_from_ews;
vacuum (analyze, verbose) pg_statistic_ext_data;
vacuum (analyze, verbose) pg_authid;
SELECT pg_sleep(60);
vacuum (analyze, verbose) pg_amop;
vacuum (analyze, verbose) awsdms_control_table.awsdms_apply_exceptions;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122022_from_psp;
vacuum (analyze, verbose) pg_description;
vacuum (analyze, verbose) ibobadm.table_b;
vacuum (analyze, verbose) pg_foreign_table;
vacuum (analyze, verbose) apg_plan_mgmt.plans;
vacuum (analyze, verbose) ibobadm.test2;
vacuum (analyze, verbose) ibobadm.test3;
vacuum (analyze, verbose) pg_cast;
vacuum (analyze, verbose) pg_enum;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122017_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022019_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062012_from_psp;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092015_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052021_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022019_from_dflt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) pg_namespace;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052020_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062010_from_null;
vacuum (analyze, verbose) pg_auth_members;
vacuum (analyze, verbose) pg_proc;
vacuum (analyze, verbose) pg_attrdef;
vacuum (analyze, verbose) pg_publication;
vacuum (analyze, verbose) pg_sequence;
