\timing


vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112020_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112020_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102019_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122019_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122019_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122020_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092015_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122019_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082016_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042012_from_psp;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012021_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032013_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012021_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032016_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012015_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022016_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042012_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052012_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082020_from_psp;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112021_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112020_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072017_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102010_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052015_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012010_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072013_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012013_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022017_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042017_from_cris;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042012_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022013_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092013_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072015_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022021_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072015_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072017_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052015_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052013_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092010_from_as400;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112009_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062012_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092010_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072017_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072017_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092010_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092010_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092010_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082020_from_null;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102010_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102010_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092020_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102020_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112019_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012019_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102020_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072017_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012010_from_qbdt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082019_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012019_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102021_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092013_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072017_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072019_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052017_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072017_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012019_from_psp;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012010_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112010_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012020_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022010_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082017_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082016_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092016_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082017_from_cris;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082017_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082016_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112016_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112016_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112021_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072016_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032021_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022019_from_qbdt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032021_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012015_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112017_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092021_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052017_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082019_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122017_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112017_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112010_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032019_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022010_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022010_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042021_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012017_from_ews;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012017_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102013_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092010_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052016_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112012_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122013_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022020_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012012_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122016_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122016_from_cris;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102017_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112021_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102021_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072013_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102013_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042021_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102015_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082017_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122016_from_as400;

