\timing


vacuum (full, analyze, verbose) partman.template_perfstat_pg_stat_all_tables_hist;
vacuum (full, analyze, verbose) partman.template_perfstat_snap;
vacuum (full, analyze, verbose) partman.template_perfstat_pg_stat_statements_hist;
vacuum (full, analyze, verbose) partman.template_perfstat_pg_stat_activity_sample;
vacuum (full, analyze, verbose) partman.template_perfstat_dba_plans_hist;
vacuum (full, analyze, verbose) partman.template_perfstat_pg_stat_activity_hist;
vacuum (full, analyze, verbose) partman.template_perfstat_pg_stat_database_hist;
vacuum (full, analyze, verbose) partman.template_perfstat_pg_stat_all_indexes_hist;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012011_from_dflt;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_04_25;
SELECT pg_sleep(60);
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_04_25;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_04_25;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_04_25;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_04_25;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_04_25;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_04_26;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_04_26;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_04_26;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_04_26;
SELECT pg_sleep(60);
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_04_26;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_04_26;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_04_27;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_04_27;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_04_27;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_04_27;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_04_27;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_04_27;
SELECT pg_sleep(60);
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_04_28;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_04_28;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_04_28;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_04_28;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_04_28;
vacuum (analyze, verbose) pg_statistic;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_04_28;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_04_29;
SELECT pg_sleep(60);
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_04_29;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_04_29;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_04_29;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_04_29;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_04_29;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_04_30;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_04_30;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_04_30;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_04_30;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_04_30;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_04_30;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_05_01;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_05_01;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_05_01;
SELECT pg_sleep(60);
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_05_01;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_05_01;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_05_01;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_05_02;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_05_02;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_05_02;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_05_02;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_05_02;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_05_02;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_05_03;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_05_03;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_05_03;
SELECT pg_sleep(60);
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_05_03;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_05_03;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_05_03;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062023_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062023_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062023_from_psp;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_05_04;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_05_04;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_05_04;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_05_04;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_05_04;
SELECT pg_sleep(60);
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_05_04;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_05_05;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_05_05;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_05_05;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_05_05;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_05_05;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_05_05;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_05_06;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_05_06;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_05_06;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_05_06;
SELECT pg_sleep(60);
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_05_07;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_05_07;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_05_06;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_05_06;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_05_07;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_05_07;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_05_07;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_05_07;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_05_08;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_05_08;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_05_08;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_05_08;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_05_08;
SELECT pg_sleep(60);
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_05_08;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_05_09;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_05_09;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_05_10;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_05_10;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_05_09;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_05_09;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_05_09;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_05_10;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_05_09;
SELECT pg_sleep(60);
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_05_10;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_05_10;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_05_11;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_05_10;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_05_11;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_05_11;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_05_11;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_05_11;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_05_11;
SELECT pg_sleep(60);
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_05_12;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_05_12;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_05_12;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_05_12;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_05_12;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_05_12;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_05_13;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_05_13;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_05_13;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_05_13;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_05_13;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_05_13;
SELECT pg_sleep(60);
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_05_14;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_05_14;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_05_14;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_05_14;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_05_14;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_05_14;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_05_15;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_05_15;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_05_15;
SELECT pg_sleep(60);
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_05_15;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_05_16;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_05_15;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_05_15;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_05_16;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_05_16;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_05_16;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_05_16;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_05_16;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_05_17;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_05_17;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_05_17;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_05_17;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_05_17;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_05_17;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_05_18;
vacuum (analyze, verbose) pg_inherits;
SELECT pg_sleep(60);
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_05_18;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_05_18;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_05_18;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_05_18;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_05_18;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042023_from_psp;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_03_13;
vacuum (full, analyze, verbose) perfstat.snap_p2023_03_13;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_03_13;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_03_13;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_03_13;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_03_13;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_03_13;
vacuum (full, analyze, verbose) perfstat.snap_p2023_03_14;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_03_14;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_03_14;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_03_14;
vacuum (full, analyze, verbose) perfstat.snap_p2023_03_18;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_03_16;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_03_14;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_03_14;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_03_17;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_03_15;
vacuum (full, analyze, verbose) perfstat.snap_p2023_03_17;
vacuum (full, analyze, verbose) perfstat.snap_p2023_03_16;
SELECT pg_sleep(60);
vacuum (full, analyze, verbose) perfstat.snap_p2023_03_15;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_03_14;
vacuum (full, analyze, verbose) perfstat.snap_p2023_03_24;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_03_24;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_03_20;
vacuum (full, analyze, verbose) perfstat.snap_p2023_03_21;
vacuum (full, analyze, verbose) perfstat.snap_p2023_03_20;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_05_19;
vacuum (full, analyze, verbose) perfstat.snap_p2023_03_25;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_03_19;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_03_25;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_03_21;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_03_22;
vacuum (full, analyze, verbose) perfstat.snap_p2023_03_22;
vacuum (full, analyze, verbose) perfstat.snap_p2023_03_19;
SELECT pg_sleep(60);
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_03_23;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_03_18;
vacuum (full, analyze, verbose) perfstat.snap_p2023_03_23;
vacuum (full, analyze, verbose) perfstat.snap_p2023_05_19;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_05_19;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_05_19;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_05_19;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_05_19;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_05_19;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_05_19;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_03_15;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_03_15;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_03_15;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_03_15;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_03_16;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_03_15;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_03_16;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_03_16;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_03_16;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_03_16;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022023_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022023_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022023_from_psp;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122022_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122022_from_ews;
vacuum (analyze, verbose) pg_amop;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122022_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122017_from_dflt;
vacuum (analyze, verbose) pg_foreign_table;
vacuum (analyze, verbose) pg_enum;
vacuum (analyze, verbose) pg_statistic_ext_data;
vacuum (analyze, verbose) awsdms_control_table.awsdms_apply_exceptions;
vacuum (analyze, verbose) pg_authid;
vacuum (analyze, verbose) pg_cast;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062012_from_psp;
vacuum (analyze, verbose) test2;
vacuum (analyze, verbose) test3;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022019_from_as400;
vacuum (analyze, verbose) apg_plan_mgmt.plans;
vacuum (analyze, verbose) pg_description;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052021_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092015_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022019_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052020_from_psp;
vacuum (analyze, verbose) pg_attrdef;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062010_from_null;
vacuum (analyze, verbose) pg_sequence;
vacuum (analyze, verbose) pg_namespace;
vacuum (analyze, verbose) pg_auth_members;
vacuum (analyze, verbose) pg_proc;
vacuum (analyze, verbose) pg_publication;
vacuum (full, analyze, verbose) perfstat.snap_p2023_05_20;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_05_20;
vacuum (full, analyze, verbose) perfstat.snap_p2023_05_21;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_05_21;
vacuum (full, analyze, verbose) perfstat.snap_p2023_05_22;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_05_22;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_05_23;
vacuum (full, analyze, verbose) perfstat.snap_p2023_05_23;
SELECT pg_sleep(60);
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_03_17;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_03_17;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_03_17;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_03_17;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_03_18;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_03_17;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_03_18;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_03_18;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_03_18;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_03_18;
vacuum (analyze, verbose) pg_ts_template;
vacuum (analyze, verbose) pg_default_acl;
vacuum (analyze, verbose) pg_ts_config_map;
vacuum (analyze, verbose) pg_ts_config;
vacuum (analyze, verbose) pg_shdescription;
vacuum (analyze, verbose) pg_tablespace;
vacuum (analyze, verbose) pg_db_role_setting;
vacuum (analyze, verbose) pg_database;
vacuum (analyze, verbose) pg_conversion;
vacuum (analyze, verbose) pg_ts_dict;
vacuum (analyze, verbose) pg_ts_parser;
vacuum (analyze, verbose) pg_extension;
vacuum (analyze, verbose) pg_amproc;
vacuum (analyze, verbose) pg_foreign_data_wrapper;
vacuum (analyze, verbose) pg_foreign_server;
vacuum (analyze, verbose) pg_policy;
vacuum (analyze, verbose) pg_replication_origin;
vacuum (analyze, verbose) pg_init_privs;
vacuum (analyze, verbose) pg_seclabel;
vacuum (analyze, verbose) pg_collation;
SELECT pg_sleep(60);
vacuum (analyze, verbose) pg_range;
vacuum (analyze, verbose) pg_subscription;
vacuum (analyze, verbose) table_b;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_05_20;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_05_20;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_05_20;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_05_20;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_05_20;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_05_20;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_05_21;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_05_21;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_05_21;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_05_21;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_05_21;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_05_21;
SELECT pg_sleep(60);
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_05_22;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_05_22;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_05_22;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_05_23;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_05_22;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_05_22;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_05_22;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_05_23;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_05_23;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_05_23;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_05_23;
vacuum (analyze, verbose) pg_language;
vacuum (analyze, verbose) pg_subscription_rel;
vacuum (analyze, verbose) pg_publication_rel;
vacuum (analyze, verbose) pg_transform;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_05_23;
vacuum (analyze, verbose) pg_shseclabel;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052012_from_dflt;
vacuum (analyze, verbose) pg_user_mapping;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062010_from_ews;
vacuum (analyze, verbose) pg_partitioned_table;
vacuum (analyze, verbose) pg_largeobject_metadata;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012010_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032010_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032019_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082019_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012019_from_as400;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062010_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102021_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042010_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022019_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012019_from_null;
vacuum (analyze, verbose) information_schema.sql_features;
vacuum (analyze, verbose) pg_operator;
SELECT pg_sleep(60);
vacuum (analyze, verbose) information_schema.sql_parts;
vacuum (analyze, verbose) information_schema.sql_implementation_info;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092021_from_dflt;
vacuum (analyze, verbose) pg_am;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022010_from_dflt;
vacuum (analyze, verbose) pg_opclass;
vacuum (analyze, verbose) pg_statistic_ext;
vacuum (analyze, verbose) pg_aggregate;
vacuum (analyze, verbose) information_schema.sql_sizing;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112019_from_dflt;
vacuum (analyze, verbose) pg_opfamily;
vacuum (analyze, verbose) pg_trigger;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072010_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032020_from_qbdt;
vacuum (analyze, verbose) pg_event_trigger;
vacuum (analyze, verbose) pg_rewrite;
