\timing
set search_path to ibobadm;

vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082018_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082018_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082018_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082018_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092018_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092018_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092018_from_as400;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092018_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092018_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092018_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102018_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092018_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102018_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102018_from_dflt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102018_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102018_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102018_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112018_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102018_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112018_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112018_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112018_from_qbdt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112018_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112018_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112018_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122018_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122018_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122018_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122018_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122018_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122018_from_psp;
SELECT pg_sleep(60);
vacuum (analyze, verbose) awsdms_control_table.awsdms_history;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122018_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042022_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052022_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042022_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052022_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052022_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042022_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042022_from_as400;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042022_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052022_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052022_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042022_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052022_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042022_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082022_from_qbdt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052022_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062022_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082022_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072022_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062022_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082022_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072022_from_dflt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082022_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082022_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062022_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062022_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082022_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062022_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062022_from_ews;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072022_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072022_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072022_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062022_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112022_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072022_from_null;
SELECT pg_sleep(60);
vacuum (analyze, verbose) mchoubey.psp_sst_backup;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072022_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082022_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112022_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112022_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042018_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062018_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092014_from_cris;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082018_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072018_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052018_from_cris;
vacuum (analyze, verbose) perfstat.pg_stat_activity_sample_p2023_02_21;
vacuum (analyze, verbose) perfstat.pg_stat_statements_hist_p2023_02_21;
vacuum (analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_02_21;
SELECT pg_sleep(60);
vacuum (analyze, verbose) perfstat.pg_stat_activity_hist_p2023_02_21;
vacuum (analyze, verbose) perfstat.pg_stat_database_hist_p2023_02_21;
vacuum (analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_02_21;
vacuum (analyze, verbose) perfstat.snap_p2023_02_21;
vacuum (analyze, verbose) perfstat.dba_plans_hist_p2023_02_21;
SELECT pg_sleep(60);
vacuum (analyze, verbose) public.plans_copy;
vacuum (analyze, verbose) perfstat.pg_stat_activity_sample_p2023_02_22;
vacuum (analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_02_22;
vacuum (analyze, verbose) perfstat.pg_stat_database_hist_p2023_02_22;
vacuum (analyze, verbose) perfstat.pg_stat_activity_hist_p2023_02_22;
vacuum (analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_02_22;
vacuum (analyze, verbose) perfstat.snap_p2023_02_22;
vacuum (analyze, verbose) perfstat.dba_plans_hist_p2023_02_22;
vacuum (analyze, verbose) perfstat.pg_stat_statements_hist_p2023_02_22
