\timing
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082015_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102016_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022015_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082021_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092012_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022015_from_null;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112009_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022017_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022010_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092012_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022021_from_cris;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102013_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042017_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112012_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112016_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022020_from_ews;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012019_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022010_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102020_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112017_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122017_from_qbdt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112013_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042013_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052012_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032013_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052016_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122020_from_as400;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122020_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012021_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122016_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012015_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102017_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082020_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062012_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102012_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112010_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082020_from_qbdt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082021_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092020_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022012_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072015_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092009_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072015_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082009_from_ews;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072019_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082009_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022017_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092020_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072012_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012012_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122009_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052010_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042015_from_psp;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082020_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072019_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122015_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112020_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082020_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052017_from_qbdt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082019_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052015_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042020_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042010_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052013_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042016_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012017_from_cris;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022020_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032015_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052010_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092013_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092016_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032017_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052015_from_dflt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062020_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042017_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092013_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092016_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052021_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042015_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102016_from_cris;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032013_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102016_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102017_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042021_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102017_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032010_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052021_from_psp;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032010_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042017_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032017_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022015_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052013_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032017_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032010_from_qbdt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112016_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112016_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112017_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122012_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122021_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022015_from_qbdt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122010_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062017_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032012_from_ews;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_06_15;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_06_16;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052015_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122021_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122021_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122019_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062012_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122020_from_qbdt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102019_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112017_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022021_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022012_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102017_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062012_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042010_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012020_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102020_from_qbdt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012012_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092015_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102012_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092016_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082012_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092012_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092016_from_psp;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082015_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112012_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032021_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082021_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102020_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122020_from_dflt;
