\timing
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022024_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022024_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012024_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012024_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122023_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042024_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012024_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022024_from_psp;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012024_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022024_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012024_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022024_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032024_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032024_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042024_from_ews;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032024_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042024_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042024_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062024_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052024_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032024_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052024_from_null;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042024_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032024_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052024_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052024_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032024_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062024_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072024_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052024_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062024_from_psp;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042024_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052024_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042024_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072024_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072024_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072024_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062024_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062024_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062024_from_dflt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082024_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052024_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072024_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082024_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092024_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072024_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072024_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082024_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062024_from_null;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092024_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102024_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112024_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092024_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082024_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082024_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082024_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082024_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092024_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092024_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092024_from_qbdt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102024_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102024_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112024_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092024_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102024_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102024_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112024_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102024_from_psp;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112024_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112024_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102024_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122024_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012023_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122024_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122024_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122024_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012023_from_qbdt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112024_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122024_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122024_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112024_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012023_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122024_from_qbdt;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_default;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022011_from_qbdt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) partman.part_config;
vacuum (analyze, verbose) partman.part_config_sub;
vacuum (analyze, verbose) partman.custom_time_partitions;
vacuum (full, analyze, verbose) perfstat.snap_default;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_default;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_default;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_default;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_default;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_default;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_default;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032011_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012011_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022011_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022011_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012011_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032011_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032011_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012011_from_dflt
SELECT pg_sleep(60);;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012011_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032011_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022011_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032011_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012011_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022011_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012011_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032011_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012011_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022011_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092011_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012014_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052011_from_qbdt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022011_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052011_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052011_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062011_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052011_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062011_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022014_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022014_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022014_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092011_from_ews;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072011_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092011_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092011_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092011_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092011_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092011_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072011_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012014_from_psp;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032011_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012014_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102011_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012014_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042011_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042011_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042011_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042011_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012014_from_dflt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012014_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042011_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052011_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062011_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052011_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052011_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062011_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022014_from_cris;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062011_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072011_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072011_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072011_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062011_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082011_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022014_from_dflt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062011_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022014_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072011_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082011_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082011_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082011_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022014_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082011_from_qbdt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082011_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102011_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032014_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082011_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072011_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102011_from_ews;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032014_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012014_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102011_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102011_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042011_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032014_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032014_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032014_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042011_from_as400;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102011_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102011_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032014_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032014_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012018_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012018_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012018_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112011_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122011_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112011_from_dflt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122011_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012018_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112011_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012018_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112011_from_cris;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_06_17;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112011_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112011_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012018_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112011_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012018_from_qbdt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122011_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122011_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122011_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052014_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122011_from_cris;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052014_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122011_from_ews;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_04_23;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_04_23;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_04_23;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_04_23;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_04_23;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_04_23;
vacuum (full, analyze, verbose) perfstat.snap_p2023_04_23;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_04_24;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_04_23;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_04_24;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_04_24;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_04_24;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_04_24;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_04_24;
vacuum (full, analyze, verbose) perfstat.snap_p2023_04_24;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_04_24;
vacuum (full, analyze, verbose) perfstat.snap_p2023_04_25;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_04_25;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052014_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052014_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042014_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042014_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052014_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052014_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052014_from_psp;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042014_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042014_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042014_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042014_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022018_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042014_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022018_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022018_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022018_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022018_from_dflt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022018_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022018_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082014_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082014_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072014_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072014_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082014_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062014_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082014_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082014_from_dflt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072014_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062014_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082014_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072014_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072014_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062014_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062014_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082014_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062014_from_null;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072014_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062014_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072014_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032018_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062014_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032018_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032018_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032018_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092014_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102014_from_psp;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032018_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032018_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092014_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102014_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032018_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102014_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102014_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102014_from_cris;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102014_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092014_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102014_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042018_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092014_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092014_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042018_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112014_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112014_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042018_from_qbdt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112014_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042018_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112014_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042018_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122014_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122014_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122014_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112014_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112014_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052018_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122014_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122014_from_dflt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052018_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122014_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052018_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052018_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052018_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062018_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072018_from_qbdt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072018_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062018_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062018_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062018_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062018_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072018_from_psp;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082018_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072018_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072018_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112014_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072018_from_as400;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052018_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062018_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092014_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122014_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042018_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082018_from_as400;
vacuum (full, analyze, verbose) perfstat.snap_p2023_04_26;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_04_26;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082018_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082018_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082018_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082018_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092018_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092018_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092018_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092018_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092018_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102018_from_ews;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102018_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092018_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092018_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102018_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102018_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112018_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102018_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102018_from_psp;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112018_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102018_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112018_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112018_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112018_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112018_from_dflt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122018_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112018_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122018_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122018_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122018_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122018_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122018_from_psp;
vacuum (analyze, verbose) awsdms_control_table.awsdms_history;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042022_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052022_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052022_from_cris;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042022_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122018_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042022_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052022_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042022_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042022_from_dflt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052022_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052022_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052022_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042022_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042022_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082022_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052022_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072022_from_psp;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082022_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062022_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082022_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062022_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082022_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062022_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062022_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072022_from_dflt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082022_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082022_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062022_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062022_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072022_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072022_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072022_from_cris;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062022_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112022_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072022_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112022_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082022_from_cris;
vacuum (analyze, verbose) mchoubey.psp_sst_backup;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072022_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112022_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042018_from_ews;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062018_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072018_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052018_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092014_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082018_from_dflt;
vacuum (analyze, verbose) public.plans_copy;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_04_27;
vacuum (full, analyze, verbose) perfstat.snap_p2023_04_27;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_04_22;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_04_22;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_04_22;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_04_22;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_04_22;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_04_22;
vacuum (full, analyze, verbose) perfstat.host_stat_hist;
vacuum (full, analyze, verbose) perfstat.snap_p2023_04_28;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_04_28;
vacuum (full, analyze, verbose) perfstat.snap_p2023_04_29;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_04_29;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_04_30;
SELECT pg_sleep(60);
vacuum (full, analyze, verbose) perfstat.snap_p2023_04_30;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_05_01;
vacuum (full, analyze, verbose) perfstat.snap_p2023_05_01;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_05_02;
vacuum (full, analyze, verbose) perfstat.snap_p2023_05_02;
vacuum (full, analyze, verbose) perfstat.snap_p2023_05_03;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_05_03;
vacuum (full, analyze, verbose) perfstat.snap_p2023_05_04;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_05_04;
vacuum (full, analyze, verbose) perfstat.snap_p2023_05_05;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_05_05;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_05_06;
vacuum (full, analyze, verbose) perfstat.snap_p2023_05_06;
vacuum (full, analyze, verbose) perfstat.snap_p2023_05_07;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_05_07;
vacuum (full, analyze, verbose) perfstat.snap_p2023_05_08;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_05_08;
vacuum (full, analyze, verbose) perfstat.snap_p2023_05_09;
SELECT pg_sleep(60);
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_05_09;
vacuum (full, analyze, verbose) perfstat.snap_p2023_05_10;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_05_10;
vacuum (full, analyze, verbose) perfstat.snap_p2023_05_11;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_05_11;
vacuum (full, analyze, verbose) perfstat.snap_p2023_05_12;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_05_12;
vacuum (full, analyze, verbose) perfstat.snap_p2023_05_13;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_05_13;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_05_14;
vacuum (full, analyze, verbose) perfstat.snap_p2023_05_14;
vacuum (full, analyze, verbose) perfstat.snap_p2023_05_15;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_05_15;
vacuum (full, analyze, verbose) perfstat.snap_p2023_05_16;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_05_16;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_05_17;
vacuum (full, analyze, verbose) perfstat.snap_p2023_05_17;
vacuum (full, analyze, verbose) perfstat.snap_p2023_05_18;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042023_from_qbdt;
vacuum (full, analyze, verbose) perfstat.pg_stat_database_hist_p2023_05_18;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042023_from_ews;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_06_18;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_06_19;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_06_20;
SELECT pg_sleep(60);
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_06_21;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_06_22;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_06_23;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_06_24;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_06_25;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_06_26;
