\timing
set search_path to ibobadm;
vacuum (analyze, verbose)  pg_depend ;
vacuum (analyze, verbose)  pg_index ;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m122022_from_qbdt ;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m122022_from_ews ;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m122022_from_psp ;
SELECT pg_sleep(60);
vacuum (analyze, verbose)  apg_plan_mgmt.plans ;
vacuum (analyze, verbose)  awsdms_control_table.awsdms_apply_exceptions ;
vacuum (analyze, verbose)  ibobadm.test3 ;
vacuum (analyze, verbose)  ibobadm.table_b ;
vacuum (analyze, verbose)  ibobadm.test2 ;
vacuum (analyze, verbose)  pg_description ;
vacuum (analyze, verbose)  pg_foreign_table ;
vacuum (analyze, verbose)  pg_authid ;
vacuum (analyze, verbose)  pg_statistic_ext_data ;
vacuum (analyze, verbose)  pg_amop ;
SELECT pg_sleep(60);
vacuum (analyze, verbose)  pg_amproc ;
vacuum (analyze, verbose)  pg_language ;
vacuum (analyze, verbose)  pg_largeobject_metadata ;
vacuum (analyze, verbose)  pg_operator ;
vacuum (analyze, verbose)  pg_opfamily ;
vacuum (analyze, verbose)  pg_opclass ;
vacuum (analyze, verbose)  pg_am ;
vacuum (analyze, verbose)  pg_aggregate ;
vacuum (analyze, verbose)  pg_statistic_ext ;
vacuum (analyze, verbose)  pg_rewrite ;
vacuum (analyze, verbose)  pg_trigger ;
SELECT pg_sleep(60);
vacuum (analyze, verbose)  pg_event_trigger ;
vacuum (analyze, verbose)  pg_cast ;
vacuum (analyze, verbose)  pg_enum ;
vacuum (analyze, verbose)  pg_namespace ;
vacuum (analyze, verbose)  pg_conversion ;
vacuum (analyze, verbose)  pg_database ;
vacuum (analyze, verbose)  pg_db_role_setting ;
vacuum (analyze, verbose)  pg_tablespace ;
vacuum (analyze, verbose)  pg_auth_members ;
vacuum (analyze, verbose)  pg_shdescription ;
vacuum (analyze, verbose)  pg_ts_config ;
SELECT pg_sleep(60);
vacuum (analyze, verbose)  pg_ts_config_map ;
vacuum (analyze, verbose)  pg_ts_dict ;
vacuum (analyze, verbose)  pg_ts_parser ;
vacuum (analyze, verbose)  pg_ts_template ;
vacuum (analyze, verbose)  pg_extension ;
vacuum (analyze, verbose)  pg_foreign_data_wrapper ;
vacuum (analyze, verbose)  pg_foreign_server ;
vacuum (analyze, verbose)  pg_policy ;
vacuum (analyze, verbose)  pg_replication_origin ;
vacuum (analyze, verbose)  pg_default_acl ;
vacuum (analyze, verbose)  pg_init_privs ;
vacuum (analyze, verbose)  pg_seclabel ;
vacuum (analyze, verbose)  pg_shseclabel ;
