\timing


vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_09_28;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_09_29;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_09_30;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_10_01;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_10_02;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_10_03;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_10_04;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_10_05;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_sample_p2023_10_06;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052016_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102015_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032022_from_qbdt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022022_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012022_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022022_from_qbdt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012022_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032022_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022022_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012022_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032022_from_psp;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102022_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092022_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102022_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092022_from_ews;
vacuum (analyze, verbose) ibobadm.psp_sap_method_call;
vacuum (analyze, verbose) pg_largeobject;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102022_from_psp;
vacuum (analyze, verbose) ibobadm.psp_hcm401k_company_qbdt_pitem;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092022_from_psp;
vacuum (analyze, verbose) ibobadm.psp_hcm401k_employee_deduction;
vacuum (analyze, verbose) public.awsdms_ddl_audit;
vacuum (analyze, verbose) pg_shdepend;
vacuum (analyze, verbose) awsdms_control_table.awsdms_status;
vacuum (analyze, verbose) ibobadm.psp_hcm401k_company_policy;
vacuum (analyze, verbose) ibobadm.psp_qbdt_request_info;
vacuum (analyze, verbose) awsdms_control_table.awsdms_suspended_tables;
vacuum (analyze, verbose) awsdms_control_table.awsdms_full_load_exceptions;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052023_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052023_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052023_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032023_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032023_from_ews;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032023_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022023_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012023_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012023_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032023_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022023_from_cris;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022023_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032023_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072023_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022023_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062023_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052023_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032023_from_cris;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072023_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082023_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042023_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012023_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032023_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042023_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042023_from_null;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052023_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062023_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062023_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072023_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042023_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012023_from_dflt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102023_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062023_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052023_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082023_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112023_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092023_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082023_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112023_from_as400;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072023_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052023_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102023_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102023_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092023_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102023_from_as400;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012024_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092023_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082023_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112023_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092023_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122023_from_dflt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012024_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122023_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022024_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022024_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032024_from_as400;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122023_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112023_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032024_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122023_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022024_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022024_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042024_from_null;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012024_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022024_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032024_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012024_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012024_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022024_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062024_from_ews;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032024_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012024_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012024_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022024_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052024_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042024_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042024_from_as400;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032024_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042024_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052024_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052024_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072024_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062024_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052024_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032024_from_null;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052024_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062024_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032024_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042024_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052024_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042024_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072024_from_as400;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072024_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062024_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062024_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072024_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042024_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062024_from_cris;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062024_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082024_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072024_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072024_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092024_from_psp;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072024_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082024_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052024_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082024_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112024_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082024_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092024_from_qbdt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102024_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092024_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092024_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092024_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082024_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102024_from_null;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082024_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092024_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082024_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102024_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092024_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112024_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112024_from_as400;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012023_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122024_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102024_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112024_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102024_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102024_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102024_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112024_from_dflt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122024_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012023_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122024_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122024_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112024_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122024_from_cris;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012023_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122024_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112024_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022011_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032011_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122024_from_qbdt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) partman.custom_time_partitions;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022011_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012011_from_cris;
vacuum (analyze, verbose) partman.part_config;
vacuum (analyze, verbose) partman.part_config_sub;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012011_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022011_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032011_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032011_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012011_from_ews;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012011_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022011_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022011_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032011_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032011_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012011_from_as400;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032011_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022011_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012011_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092011_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012014_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052011_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022011_from_as400;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062011_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052011_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062011_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022014_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052011_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052011_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022014_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072011_from_as400;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022014_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012014_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092011_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072011_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092011_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012014_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102011_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092011_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092011_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092011_from_as400;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092011_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012014_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042011_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042011_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032011_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042011_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042011_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042011_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012014_from_dflt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052011_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012014_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052011_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052011_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062011_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022014_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062011_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062011_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072011_from_ews;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072011_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082011_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072011_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022014_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082011_from_as400;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062011_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082011_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072011_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062011_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022014_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082011_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082011_from_qbdt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022014_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102011_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082011_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032014_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072011_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082011_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102011_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042011_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012014_from_as400;
