\timing

vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082023_from_ews;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082023_from_qbdt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082023_from_psp;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_06_01;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_06_01;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_06_01;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_06_01;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_06_01;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_06_02;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_06_02;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_06_02;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_06_02;
SELECT pg_sleep(60);
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_06_02;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_06_03;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_06_03;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_06_03;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_06_03;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_06_03;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_06_04;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_06_04;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_06_04;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_06_05;
SELECT pg_sleep(60);
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_06_05;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_06_04;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_06_04;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_06_05;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_06_05;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_06_05;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_06_06;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_06_06;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_06_06;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_06_06;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_06_07;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_06_06;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_06_07;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_06_07;
SELECT pg_sleep(60);
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_06_07;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_06_07;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_06_08;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_06_08;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_06_08;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_06_08;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_06_08;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_06_09;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_06_09;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_06_09;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_06_09;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_06_09;
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_06_10;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_06_10;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_06_10;
SELECT pg_sleep(60);
vacuum (full, analyze, verbose) perfstat.pg_stat_statements_hist_p2023_06_11;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_06_11;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_06_10;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_indexes_hist_p2023_06_11;
vacuum (full, analyze, verbose) perfstat.pg_stat_activity_hist_p2023_06_10;
vacuum (full, analyze, verbose) perfstat.pg_stat_all_tables_hist_p2023_06_11;
vacuum (full, analyze, verbose) perfstat.dba_plans_hist_p2023_06_11;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072023_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072023_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072023_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052013_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052015_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082015_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112012_from_psp;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062013_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102013_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042013_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042015_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042015_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032012_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062013_from_ews;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112017_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112015_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062017_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082013_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092015_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032013_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032015_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092017_from_null;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082021_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112009_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012013_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122015_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112015_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022013_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062013_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042016_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012012_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062013_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102020_from_cris;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092019_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112019_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032020_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052019_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102020_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072019_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052019_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052019_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042019_from_cris;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072009_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072020_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062010_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062021_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042013_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062021_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062021_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032013_from_null;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052012_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122015_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012021_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072010_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082015_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062015_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062021_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092017_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072010_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072020_from_psp;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072020_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082015_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072009_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092019_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072020_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072010_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092015_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022013_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072020_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062015_from_null;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092017_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062013_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042013_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102009_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072012_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042013_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072012_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022017_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072012_from_ews;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082010_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062015_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072012_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062016_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062016_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072016_from_psp;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072021_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082010_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122019_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122010_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122010_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062015_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032019_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082009_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092019_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042020_from_null;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032020_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032020_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022016_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032020_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092019_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062016_from_as400;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032021_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072021_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092015_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062019_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022016_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022015_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102012_from_null;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052013_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052013_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022016_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092016_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022021_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062013_from_null;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062016_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102015_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042012_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022016_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112015_from_null;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052021_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062021_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092019_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112019_from_qbdt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062020_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062016_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102019_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082012_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082012_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092021_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032017_from_dflt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112010_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062020_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112015_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122017_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092020_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062015_from_psp;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032013_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062016_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072015_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082013_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032012_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012016_from_ews;
