\timing
set search_path to ibobadm;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m092023_from_as400;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m092023_from_cris;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m092023_from_dflt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m092023_from_ews;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m092023_from_null;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m092023_from_psp;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m092023_from_qbdt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m102023_from_as400;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m102023_from_cris;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m102023_from_dflt;
SELECT pg_sleep(60);
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m102023_from_ews;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m102023_from_null;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m102023_from_psp;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m102023_from_qbdt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m112023_from_as400;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m112023_from_cris;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m112023_from_dflt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m112023_from_ews;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m112023_from_null;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m112023_from_psp;
SELECT pg_sleep(60);
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m112023_from_qbdt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m122023_from_as400;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m122023_from_cris;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m122023_from_dflt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m122023_from_ews;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m122023_from_null;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m122023_from_psp;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m122023_from_qbdt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m012024_from_as400;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m012024_from_cris;
SELECT pg_sleep(60);
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m012024_from_dflt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m012024_from_ews;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m012024_from_null;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m012024_from_psp;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m012024_from_qbdt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m022024_from_as400;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m022024_from_cris;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m022024_from_dflt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m022024_from_ews;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m022024_from_null;
SELECT pg_sleep(60);
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m022024_from_psp;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m022024_from_qbdt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m032024_from_as400;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m032024_from_cris;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m032024_from_dflt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m032024_from_ews;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m032024_from_null;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m032024_from_psp;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m032024_from_qbdt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m042024_from_as400;
