\timing
set search_path to ibobadm;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122017_from_as400 ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032015_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092017_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052019_from_null ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092020_from_qbdt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022020_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092021_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042020_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052017_from_psp ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092021_from_null ;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072015_from_qbdt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082016_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022012_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072012_from_as400 ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032017_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082016_from_qbdt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022013_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082013_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032015_from_psp ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122009_from_qbdt ;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102009_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062017_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052017_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112009_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062019_from_psp ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062019_from_qbdt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012010_from_null ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102010_from_as400 ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092010_from_qbdt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112021_from_psp ;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022021_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122013_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032015_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052010_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112020_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072009_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072009_from_null ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052012_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042016_from_as400 ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122013_from_as400 ;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012017_from_as400 ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052012_from_psp ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082016_from_psp ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122015_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042012_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112013_from_null ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062012_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122012_from_null ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032012_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102012_from_ews ;

