DROP TABLE IF EXISTS TEMP_LEDGER_ACCOUNT_ACTION CASCADE

;
--------------------------------------------------------
-- Create temp table                                  --
--------------------------------------------------------
CREATE TABLE TEMP_LEDGER_ACCOUNT_ACTION (LIKE PSP_LEDGER_ACCOUNT_ACTION INCLUDING ALL)
;

--------------------------------------------------------
-- Insert into temp table                             --
--------------------------------------------------------

INSERT INTO TEMP_LEDGER_ACCOUNT_ACTION ( LEDGER_ACCOUNT_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACTION_EVENT_FK, LEDGER_ACCOUNT_FK, CREDIT_DEBIT_INDICATOR)
VALUES ('35aa8b0f-a89d-46d9-a474-60e3bb5e4481', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'BadDebtWriteOff','ERReturnReceivable', 'Debit')
;
INSERT INTO TEMP_LEDGER_ACCOUNT_ACTION ( LEDGER_ACCOUNT_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACTION_EVENT_FK, LEDGER_ACCOUNT_FK, CREDIT_DEBIT_INDICATOR)
VALUES ('35aa8b0f-a89d-46d9-a484-60e3bb5e4581', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'BadDebtWriteOffEEReturn','EEReturnLiablility', 'Debit')
;
INSERT INTO TEMP_LEDGER_ACCOUNT_ACTION ( LEDGER_ACCOUNT_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACTION_EVENT_FK, LEDGER_ACCOUNT_FK, CREDIT_DEBIT_INDICATOR)
VALUES ('50812626-78b4-43f8-99fa-00016ae800ec', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,  'BadDebtRecover','BadDebt', 'Debit')
;
INSERT INTO TEMP_LEDGER_ACCOUNT_ACTION ( LEDGER_ACCOUNT_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACTION_EVENT_FK, LEDGER_ACCOUNT_FK, CREDIT_DEBIT_INDICATOR)
VALUES ('985d0ef7-937a-45c4-a561-275f4fe6f1f5', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,  'EEReturnTransfer','EEReturnLiablility', 'Credit')
;
INSERT INTO TEMP_LEDGER_ACCOUNT_ACTION ( LEDGER_ACCOUNT_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACTION_EVENT_FK, LEDGER_ACCOUNT_FK, CREDIT_DEBIT_INDICATOR)
VALUES ('aac2f372-c6ad-47a7-a67c-3a492405f04c', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,  'FeeTransfer','ERReturnReceivable', 'Credit')
;
INSERT INTO TEMP_LEDGER_ACCOUNT_ACTION ( LEDGER_ACCOUNT_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACTION_EVENT_FK, LEDGER_ACCOUNT_FK, CREDIT_DEBIT_INDICATOR)
VALUES ('3db69376-7c6a-4dc0-bf52-e02aae664a67', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,  'Intuit5DayReturnTransfer','DDCurrentLiability', 'Credit')
;
INSERT INTO TEMP_LEDGER_ACCOUNT_ACTION ( LEDGER_ACCOUNT_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACTION_EVENT_FK, LEDGER_ACCOUNT_FK, CREDIT_DEBIT_INDICATOR)
VALUES ('cfff81fb-e7ca-4443-a00d-713ef880bc9e', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,  'DDRefund','DDCurrentLiability', 'Credit')
;
INSERT INTO TEMP_LEDGER_ACCOUNT_ACTION ( LEDGER_ACCOUNT_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACTION_EVENT_FK, LEDGER_ACCOUNT_FK, CREDIT_DEBIT_INDICATOR)
VALUES ('0055072f-ba32-4fbc-868f-54b7370162ef', 0,CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,  'ERReturnRefund','ERReturnReceivable', 'Credit')
;
INSERT INTO TEMP_LEDGER_ACCOUNT_ACTION ( LEDGER_ACCOUNT_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACTION_EVENT_FK, LEDGER_ACCOUNT_FK, CREDIT_DEBIT_INDICATOR)
VALUES ('93e25d84-5e6a-403a-9760-196ed324613e', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,  'EEReturnRefund','EEReturnLiablility', 'Credit')
;
INSERT INTO TEMP_LEDGER_ACCOUNT_ACTION ( LEDGER_ACCOUNT_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACTION_EVENT_FK, LEDGER_ACCOUNT_FK, CREDIT_DEBIT_INDICATOR)
VALUES ('93e25d84-5e6a-403a-9760-196ed324625a', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,  'VoidPayrollTaxPayment','TaxCurrentCash', 'Debit')
;
INSERT INTO TEMP_LEDGER_ACCOUNT_ACTION ( LEDGER_ACCOUNT_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACTION_EVENT_FK, LEDGER_ACCOUNT_FK, CREDIT_DEBIT_INDICATOR)
VALUES ('93e25d84-5e6a-503a-9760-196ed324625a', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,  'ApplyERPayableToBalanceDue','ERReturnReceivable', 'Debit')
;
--------------------------------------------------------
-- Sychronize temp table and real table by            --
-- inserting, deleting, and updating as necessary     --
--------------------------------------------------------

INSERT INTO PSP_LEDGER_ACCOUNT_ACTION
   (LEDGER_ACCOUNT_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACTION_EVENT_FK, LEDGER_ACCOUNT_FK, CREDIT_DEBIT_INDICATOR)
SELECT 
   LEDGER_ACCOUNT_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACTION_EVENT_FK, LEDGER_ACCOUNT_FK, CREDIT_DEBIT_INDICATOR
FROM 
   TEMP_LEDGER_ACCOUNT_ACTION tlaa
WHERE 
    (tlaa.ACTION_EVENT_FK)  NOT IN (SELECT ACTION_EVENT_FK FROM PSP_LEDGER_ACCOUNT_ACTION)

;

DELETE FROM PSP_LEDGER_ACCOUNT_ACTION
WHERE  (ACTION_EVENT_FK)  NOT IN (SELECT ACTION_EVENT_FK FROM TEMP_LEDGER_ACCOUNT_ACTION)


;

UPDATE PSP_LEDGER_ACCOUNT_ACTION laa
SET (VERSION, CREATED_DATE, MODIFIED_DATE, ACTION_EVENT_FK, LEDGER_ACCOUNT_FK, CREDIT_DEBIT_INDICATOR) =
(SELECT  tlaa. VERSION, tlaa.CREATED_DATE, tlaa.MODIFIED_DATE, tlaa.ACTION_EVENT_FK, tlaa.LEDGER_ACCOUNT_FK, tlaa.CREDIT_DEBIT_INDICATOR
 FROM TEMP_LEDGER_ACCOUNT_ACTION tlaa WHERE 
                                   tlaa.ACTION_EVENT_FK = laa.ACTION_EVENT_FK )
;



--------------------------------------------------------
-- Drop temp table                                  --
--------------------------------------------------------
DROP TABLE TEMP_LEDGER_ACCOUNT_ACTION

;
COMMIT
 

