CREATE OR REPLACE FUNCTION FN_TR_UPD_COMPANY_EVENT_TIMESTAMP()
    RETURNS TRIGGER
    AS $$
BEGIN
    IF (NEW.EVENT_TYPE_CD <> 'Strike') THEN
        NEW.EVENT_TIME_STAMP := OLD.EVENT_TIME_STAMP;
END IF;
RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER TR_UPD_COMPANY_EVENT_TIMESTAMP
    BEFORE UPDATE ON PSP_COMPANY_EVENT
    FOR EACH ROW EXECUTE FUNCTION FN_TR_UPD_COMPANY_EVENT_TIMESTAMP();
