CREATE TABLE FLUX_ACTION (PK NUMBER NOT NULL PRIMARY KEY, CLAZZ VARCHAR(200) NOT NULL, FLOW_CHART NUMBER NOT NULL, NAME VARCHAR(200) NOT NULL, STARTING_POINT NUMBER NOT NULL, JOIN_POINT NUMBER NOT NULL, TRANSACTION_BREAK NUMBER NOT NULL, TIMEOUT_TIMEXP VARCHAR(200), SUB_FLOW_CHART NUMBER, PRE_SCRIPT_LANG VARCHAR(200), POST_SCRIPT_LANG VARCHAR(200), PRE_SCRIPT CLOB, POST_SCRIPT CLOB, SKIPPABLE NUMBER NOT NULL);
CREATE TABLE FLUX_AUDIT_TRAIL (PK NUMBER NOT NULL PRIMARY KEY, ENGINE VARCHAR(200) NOT NULL, USERNAME VARCHAR(200), GROUPNAME VARCHAR(200), NAMESPACE VARCHAR(200), EVENT VARCHAR(200), CREATION DATE, MESSAGE CLOB, ACTION_NAME VARCHAR(200), FK_RUN_HISTORY_PK NUMBER);
CREATE TABLE FLUX_AUDIT_TRL_TGR(PK NUMBER PRIMARY KEY, ENGINE VARCHAR(200), USERNAME VARCHAR(200), GROUPNAME VARCHAR(200), NAMESPACE VARCHAR(200), EVENT VARCHAR(200) NOT NULL, MESSAGE VARCHAR(200), ACTION_NAME VARCHAR(200), ACTION_PK NUMBER, EVENT_PK NUMBER, LAST_EVENT_PK NUMBER);
CREATE TABLE FLUX_BIZ_PROCESS (PK NUMBER NOT NULL PRIMARY KEY, FK_FLOW_CHART_PK NUMBER NOT NULL UNIQUE, TEMPLATE_NAME VARCHAR(200), CREATION DATE NOT NULL);
CREATE TABLE FLUX_BIZ_PROCESS_T (PK NUMBER NOT NULL PRIMARY KEY, PARTICIPANT VARCHAR(200) NOT NULL, CLAIMER VARCHAR(200), WAIT_FOR_ALL NUMBER NOT NULL, CONFIRMED NUMBER NOT NULL);
CREATE TABLE FLUX_BIZ_PROC_CONF (PK NUMBER NOT NULL PRIMARY KEY, BIZ_PROCESS_T NUMBER NOT NULL, PARTICIPANT VARCHAR(200) NOT NULL, CONFIRMATION_TYPE VARCHAR(200), EXT_PARTICIPANT NUMBER NOT NULL);
CREATE TABLE FLUX_BIZ_PROC_OWNR (PK NUMBER NOT NULL PRIMARY KEY, FK_FLOW_CHART_PK NUMBER NOT NULL, NAME VARCHAR(200) NOT NULL);
CREATE TABLE FLUX_CALLSTACK (PK NUMBER NOT NULL PRIMARY KEY, FK_READY_CALLER_PK NUMBER NOT NULL, FK_READY_CALLEE_PK NUMBER NOT NULL, IS_PRIMARY NUMBER NOT NULL);
CREATE TABLE FLUX_CHKPT (PK NUMBER NOT NULL PRIMARY KEY, FLOW NUMBER, FLOW_CHART NUMBER, MESSAGE_DEFINITION NUMBER NOT NULL, PUBLISHER NUMBER NOT NULL);
CREATE TABLE FLUX_CLUSTER (PK NUMBER NOT NULL PRIMARY KEY, ENGINE_INSTANCE NUMBER NOT NULL, CURRENT_STATE VARCHAR(200) NOT NULL, HEARTBEAT NUMBER NOT NULL, NAME VARCHAR(200) NOT NULL, HOST VARCHAR(200), BIND_NAME VARCHAR(200), PORT NUMBER NOT NULL);
CREATE TABLE FLUX_CLUSTER_NAME(ID VARCHAR(200) NOT NULL PRIMARY KEY, NAME VARCHAR(200));
CREATE TABLE FLUX_BAG_ITEM (PK NUMBER NOT NULL PRIMARY KEY, BAG_ID NUMBER NOT NULL, ELEMENT_POSITION NUMBER);
CREATE TABLE FLUX_ERROR_RESULT (PK NUMBER NOT NULL PRIMARY KEY, MESSAGE CLOB, CLAZZ VARCHAR(200) NOT NULL, THROWING_ACTION VARCHAR(200) NOT NULL, STACK_TRACE CLOB, EXCEPTION_OBJECT BLOB);
CREATE TABLE FLUX_FLOW (PK NUMBER NOT NULL PRIMARY KEY, TARGET_ACTION NUMBER NOT NULL, SOURCE_ACTION NUMBER NOT NULL, CONDITION VARCHAR(200));
CREATE TABLE FLUX_FLOW_CHART (PK NUMBER NOT NULL PRIMARY KEY, NAME VARCHAR(200) NOT NULL, SEAL NUMBER NOT NULL, RUN_AS_USER VARCHAR(200), LISTENER_CLASSPATH VARCHAR(200), RUN_AS_USER_SOURCE NUMBER NOT NULL, IS_TEMPLATE NUMBER NOT NULL, DEADLINE_TS DATE, DEADLINE_TIMEXP VARCHAR(200), DEADLINE_WINDOW DATE, DEADLINE_WINDOW_TE VARCHAR(200), DEADLINE_STATUS NUMBER, CREATION NUMBER NOT NULL, UNIQUE(NAME));
CREATE TABLE FLUX_FLOW_CONTEXT (PK NUMBER NOT NULL PRIMARY KEY);
CREATE TABLE FLUX_GROUP (PK NUMBER NOT NULL PRIMARY KEY, NAME VARCHAR(200) NOT NULL UNIQUE, EXPIRATION DATE);
CREATE TABLE FLUX_JBIG_DECIMAL (PK NUMBER NOT NULL PRIMARY KEY, VALUE NUMERIC(9, 2));
CREATE TABLE FLUX_JBOOLEAN (PK NUMBER NOT NULL PRIMARY KEY, VALUE NUMBER);
CREATE TABLE FLUX_JBYTE_ARRAY (PK NUMBER NOT NULL PRIMARY KEY, VALUE BLOB);
CREATE TABLE FLUX_JDATE (PK NUMBER NOT NULL PRIMARY KEY, VALUE DATE);
CREATE TABLE FLUX_JDOUBLE (PK NUMBER NOT NULL PRIMARY KEY, VALUE DOUBLE PRECISION);
CREATE TABLE FLUX_JFLOAT (PK NUMBER NOT NULL PRIMARY KEY, VALUE FLOAT);
CREATE TABLE FLUX_JINTEGER (PK NUMBER NOT NULL PRIMARY KEY, VALUE NUMBER);
CREATE TABLE FLUX_JLONG (PK NUMBER NOT NULL PRIMARY KEY, VALUE NUMBER);
CREATE TABLE FLUX_JOINING (PK NUMBER NOT NULL PRIMARY KEY, FLOW NUMBER NOT NULL, READY NUMBER NOT NULL, QUEUE NUMBER NOT NULL, FIRED NUMBER NOT NULL);
CREATE TABLE FLUX_JSHORT (PK NUMBER NOT NULL PRIMARY KEY, VALUE NUMBER);
CREATE TABLE FLUX_JSTRING (PK NUMBER NOT NULL PRIMARY KEY, VALUE CLOB);
CREATE TABLE FLUX_JTIME (PK NUMBER NOT NULL PRIMARY KEY, VALUE DATE);
CREATE TABLE FLUX_JTIMESTAMP (PK NUMBER NOT NULL PRIMARY KEY, VALUE DATE);
CREATE TABLE FLUX_LOCK (PK NUMBER NOT NULL PRIMARY KEY, FK_USER_PK NUMBER NOT NULL, FK_USR_ROL_GRP_PK NUMBER NOT NULL UNIQUE, TYPE NUMBER NOT NULL, CREATION DATE NOT NULL);
CREATE TABLE FLUX_LOGGING (PK NUMBER NOT NULL PRIMARY KEY, ENGINE VARCHAR(200) NOT NULL, USERNAME VARCHAR(200), GROUPNAME VARCHAR(200), NAMESPACE VARCHAR(200), LOGGER_TYPE VARCHAR(200), LOGGING_LEVEL VARCHAR(200), CREATION DATE, MESSAGE CLOB);
CREATE TABLE FLUX_MESSAGE_TGR (PK NUMBER NOT NULL PRIMARY KEY, PUBLISHER NUMBER NOT NULL, LAST_MESSAGE NUMBER, CURRENT_MESSAGE NUMBER, FILTER VARCHAR(200));
CREATE TABLE FLUX_META_BAG (PK NUMBER NOT NULL PRIMARY KEY, BAG_ID NUMBER NOT NULL, BAG_CLASS VARCHAR(200) NOT NULL, COMPARATOR_CLASS VARCHAR(200));
CREATE TABLE FLUX_MEZZAGE (PK NUMBER NOT NULL PRIMARY KEY, BODY NUMBER NOT NULL, PROPERTIES NUMBER NOT NULL, PUBLISH_DATE NUMBER NOT NULL, PUBLISHER NUMBER NOT NULL, PRIORITY NUMBER NOT NULL);
CREATE TABLE FLUX_PERMISSION (PK NUMBER NOT NULL PRIMARY KEY, FK_USER_OR_ROLE_PK NUMBER NOT NULL, TYPE NUMBER NOT NULL, CLASSNAME VARCHAR(200), NAME VARCHAR(200), ACTIONS VARCHAR(200), VARIABLE_NAME VARCHAR(200), VARIABLE_TYPE VARCHAR(10), ACTION_NAME VARCHAR(200));
CREATE TABLE FLUX_PK (PK NUMBER NOT NULL PRIMARY KEY, NEXT_PK NUMBER NOT NULL);
CREATE TABLE FLUX_PUBLISHER (PK NUMBER NOT NULL PRIMARY KEY, NAME VARCHAR(200) NOT NULL, STYLE VARCHAR(200) NOT NULL, PAUSED VARCHAR(200) NOT NULL, MAX_MESSAGES NUMBER NOT NULL, EXPIRATION_TIMEXP VARCHAR(200), UNIQUE(NAME));
CREATE TABLE FLUX_READY (PK NUMBER NOT NULL PRIMARY KEY, NAMESPACE VARCHAR(200) NOT NULL, FLOW_CHART_NAME VARCHAR(200) NOT NULL, ACTION NUMBER NOT NULL, EXPEDITED NUMBER NOT NULL, FLOW_CONTEXT NUMBER NOT NULL, HEARTBEAT NUMBER NOT NULL, INSTANCE NUMBER, INTERRUPTED NUMBER, SEAL NUMBER, SUPER_STATE VARCHAR(200) NOT NULL, STATE VARCHAR(200) NOT NULL, RESUME_ACTION NUMBER, RESUME_FLOW_CNTXT NUMBER, FAILED_ERROR NUMBER, EXECUTION_TIME NUMBER, TIMEOUT DATE, ORIGINAL_PRIORITY NUMBER, EFFECTIVE_PRIORITY NUMBER, LAST_PRTY_CHANGE NUMBER, PRIORITY_SOURCE NUMBER NOT NULL, ERROR_ACTION NUMBER, STATUS VARCHAR(200));
CREATE TABLE FLUX_REPOSITORY (PK NUMBER NOT NULL PRIMARY KEY, NAMESPACE VARCHAR(200) NOT NULL UNIQUE, CONTENT CLOB NOT NULL, DESCRIPTION CLOB, OWNER NUMBER, CREATION DATE NOT NULL, LAST_MODIFIED DATE NOT NULL, TYPE NUMBER NOT NULL);
CREATE TABLE FLUX_ROLE (PK NUMBER NOT NULL PRIMARY KEY, NAME VARCHAR(200) NOT NULL, GROUP_FK NUMBER NOT NULL);
CREATE TABLE FLUX_RUN_AVERAGE (NAMESPACE VARCHAR(200) NOT NULL, START_TIMESTAMP NUMBER NOT NULL, END_TIMESTAMP NUMBER NOT NULL, AVERAGE_RUN_TIME NUMBER NOT NULL, AVERAGE_WAIT_TIME NUMBER NOT NULL, FIRING_COUNT NUMBER NOT NULL, LAST_MODIFIED DATE NOT NULL, UNIQUE(NAMESPACE));
CREATE TABLE FLUX_RUN_HISTORY (PK NUMBER NOT NULL PRIMARY KEY, NAMESPACE VARCHAR(200) NOT NULL, ACTION_NAME VARCHAR(200), ENTER_TIMESTAMP NUMBER NOT NULL, START_TIMESTAMP NUMBER NOT NULL, EXIT_TIMESTAMP NUMBER NOT NULL, LAST_MODIFIED DATE NOT NULL, SUCCESS_STATUS NUMBER NOT NULL, PREMATURE NUMBER NOT NULL);
CREATE TABLE FLUX_DATA_MAP (PK NUMBER NOT NULL PRIMARY KEY, ACTION NUMBER, FLOW NUMBER, SOURCE_NAME VARCHAR(200) NOT NULL, SOURCE_TYPE NUMBER NOT NULL, TARGET_NAME VARCHAR(200) NOT NULL, TARGET_TYPE NUMBER NOT NULL);
CREATE TABLE FLUX_SIGNAL (PK NUMBER NOT NULL PRIMARY KEY, MONITOR NUMBER, RAISE NUMBER, CLEAR NUMBER, RAISED NUMBER, NAME VARCHAR(200) NOT NULL);
CREATE TABLE FLUX_TIMER_TRIGGER (PK NUMBER NOT NULL PRIMARY KEY, LATE_TIME_WINDOW VARCHAR(200), SCHEDULED_T_DATE NUMBER NOT NULL, END_DATE NUMBER NOT NULL, END_TIME_EXP VARCHAR(200), TOTAL_COUNT NUMBER NOT NULL, REMAINING_COUNT NUMBER NOT NULL, ACTUAL_T_DATE NUMBER NOT NULL, ABSTRACT_TIMEXP NUMBER, MAKEUP_FIRING NUMBER NOT NULL);
CREATE TABLE FLUX_USER (PK NUMBER NOT NULL PRIMARY KEY, USERNAME VARCHAR(200) NOT NULL UNIQUE, PASSWORD VARCHAR(200) NOT NULL, DISPLAY_NAME VARCHAR(200), GROUP_FK NUMBER NOT NULL);
CREATE TABLE FLUX_USER_ROLE_REL (PK NUMBER NOT NULL PRIMARY KEY, FK_USER_PK NUMBER NOT NULL, FK_ROLE_PK NUMBER NOT NULL);
CREATE TABLE FLUX_USR_SUPR_REL (PK NUMBER NOT NULL PRIMARY KEY, FK_USER_PK NUMBER NOT NULL, FK_ROLE_PK NUMBER, FK_USER_OR_ROLE_PK NUMBER NOT NULL, TYPE NUMBER NOT NULL);
CREATE TABLE FLUX_VARIABLE (PK NUMBER NOT NULL PRIMARY KEY, OWNER NUMBER, TYPE VARCHAR(200) NOT NULL, NAME VARCHAR(200), USER_VARIABLE NUMBER NOT NULL);

CREATE SEQUENCE FLUX_AUDIT_TRAIL_SEQ;
CREATE SEQUENCE FLUX_LOGGING_SEQ;
CREATE SEQUENCE FLUX_RUN_HISTORY_SEQ;
CREATE SEQUENCE FLUX_REPOSITORY_SEQ;

CREATE INDEX FLUX_AUDIT_TRAIL1 ON FLUX_AUDIT_TRAIL(CREATION);
CREATE INDEX FLUX_AUDIT_TRAIL2 ON FLUX_AUDIT_TRAIL(NAMESPACE);
CREATE INDEX FLUX_AUDIT_TRAIL3 ON FLUX_AUDIT_TRAIL(ACTION_NAME);
CREATE INDEX FLUX_AUDIT_TRAIL4 on FLUX_AUDIT_TRAIL(EVENT);
CREATE INDEX FLUX_AUDIT_TRAIL5 on FLUX_AUDIT_TRAIL(USERNAME);
CREATE INDEX FLUX_AUDIT_TRAIL6 on FLUX_AUDIT_TRAIL(GROUPNAME);

CREATE INDEX FLUX_AUDIT_TGR1 ON FLUX_AUDIT_TRL_TGR(ENGINE);
CREATE INDEX FLUX_AUDIT_TGR2 ON FLUX_AUDIT_TRL_TGR(NAMESPACE);
CREATE INDEX FLUX_AUDIT_TGR3 ON FLUX_AUDIT_TRL_TGR(ACTION_NAME);
CREATE INDEX FLUX_AUDIT_TGR4 on FLUX_AUDIT_TRL_TGR(EVENT);
CREATE INDEX FLUX_AUDIT_TGR5 on FLUX_AUDIT_TRL_TGR(USERNAME);
CREATE INDEX FLUX_AUDIT_TGR6 on FLUX_AUDIT_TRL_TGR(GROUPNAME);
CREATE INDEX FLUX_AUDIT_TGR7 on FLUX_AUDIT_TRL_TGR(MESSAGE);
CREATE INDEX FLUX_AUDIT_TGR8 on FLUX_AUDIT_TRL_TGR(ACTION_PK);
CREATE INDEX FLUX_AUDIT_TGR9 on FLUX_AUDIT_TRL_TGR(EVENT_PK);
CREATE INDEX FLUX_AUDIT_TGR10 on FLUX_AUDIT_TRL_TGR(LAST_EVENT_PK);

CREATE INDEX FLUX_RUN_AVERAGE1 ON FLUX_RUN_AVERAGE(LAST_MODIFIED);
CREATE INDEX FLUX_RUN_HISTORY1 ON FLUX_RUN_HISTORY(LAST_MODIFIED);
CREATE INDEX FLUX_RUN_HISTORY2 ON FLUX_RUN_HISTORY(NAMESPACE);

CREATE INDEX FLUX_READY1 ON FLUX_READY(ACTION);
CREATE INDEX FLUX_READY2 ON FLUX_READY(SEAL);
CREATE INDEX FLUX_READY3 ON FLUX_READY(STATE);
CREATE INDEX FLUX_READY4 ON FLUX_READY(HEARTBEAT);
CREATE INDEX FLUX_READY5 ON FLUX_READY(FLOW_CHART_NAME);
CREATE INDEX FLUX_READY6 ON FLUX_READY(EXECUTION_TIME);
CREATE INDEX FLUX_READY7 ON FLUX_READY(TIMEOUT);

CREATE INDEX FLUX_SIGNAL1 ON FLUX_SIGNAL(RAISED);
CREATE INDEX FLUX_SIGNAL2 ON FLUX_SIGNAL(NAME);

CREATE INDEX FLUX_VARIABLE1 ON FLUX_VARIABLE(OWNER);
CREATE INDEX FLUX_VARIABLE2 ON FLUX_VARIABLE(USER_VARIABLE);
CREATE INDEX FLUX_VARIABLE3 ON FLUX_VARIABLE(NAME);

CREATE INDEX FLUX_PUBLISHER1 ON FLUX_PUBLISHER(STYLE);

CREATE INDEX FLUX_MESSAGE_TGR1 ON FLUX_MESSAGE_TGR(PUBLISHER);
CREATE INDEX FLUX_MESSAGE_TGR2 ON FLUX_MESSAGE_TGR(LAST_MESSAGE);
CREATE INDEX FLUX_MESSAGE_TGR3 ON FLUX_MESSAGE_TGR(CURRENT_MESSAGE);

CREATE INDEX FLUX_MEZZAGE1 ON FLUX_MEZZAGE(PUBLISHER);

CREATE INDEX FLUX_ACTION1 ON FLUX_ACTION(FLOW_CHART);

CREATE INDEX FLUX_FLOW1 ON FLUX_FLOW(SOURCE_ACTION);
CREATE INDEX FLUX_FLOW2 ON FLUX_FLOW(TARGET_ACTION);

CREATE INDEX FLUX_FLOW_CHART1 ON FLUX_FLOW_CHART(SEAL);
CREATE INDEX FLUX_FLOW_CHART2 ON FLUX_FLOW_CHART(CREATION);

CREATE INDEX FLUX_META_BAG1 ON FLUX_META_BAG(BAG_ID);

CREATE INDEX FLUX_BAG_ITEM1 ON FLUX_BAG_ITEM(BAG_ID);

CREATE INDEX FLUX_CHKPT1 ON FLUX_CHKPT(PUBLISHER);
CREATE INDEX FLUX_CHKPT2 ON FLUX_CHKPT(FLOW_CHART);
CREATE INDEX FLUX_CHKPT3 ON FLUX_CHKPT(FLOW);

CREATE INDEX FLUX_ROLE1 ON FLUX_ROLE(NAME);

CREATE INDEX FLUX_USR_ROL_RELATION1 ON FLUX_USER_ROLE_REL(FK_USER_PK);
CREATE INDEX FLUX_USR_ROL_RELATION2 ON FLUX_USER_ROLE_REL(FK_ROLE_PK);

CREATE INDEX FLUX_LOCK1 ON FLUX_LOCK(FK_USER_PK);
CREATE INDEX FLUX_LOCK3 ON FLUX_LOCK(CREATION);

CREATE INDEX FLUX_LOGGING1 on FLUX_LOGGING(CREATION);
CREATE INDEX FLUX_LOGGING2 on FLUX_LOGGING(NAMESPACE);
CREATE INDEX FLUX_LOGGING3 on FLUX_LOGGING(USERNAME);
CREATE INDEX FLUX_LOGGING4 on FLUX_LOGGING(GROUPNAME);
CREATE INDEX FLUX_LOGGING5 on FLUX_LOGGING(ENGINE);
CREATE INDEX FLUX_LOGGING6 on FLUX_LOGGING(LOGGER_TYPE);
CREATE INDEX FLUX_LOGGING7 on FLUX_LOGGING(LOGGING_LEVEL);

CREATE INDEX FLUX_JOINING1 ON FLUX_JOINING(READY);
CREATE INDEX FLUX_JOINING2 ON FLUX_JOINING(FLOW);

exit