
DECLARE OfferingSequence VARCHAR2(100);
BEGIN
select PO.OFFERING_SEQ into OfferingSequence from PSP_OFFERING PO where PO.OFFERING_CODE = 'SYMFY14';
update PSP_COMPANY_OFFERING PCO set PCO.OFFERING_FK = OfferingSequence where PCO.COMPANY_OFFERING_SEQ in (SELECT PSP_COMPANY_OFFERING.COMPANY_OFFERING_SEQ
FROM PSP_COMPANY 
JOIN PSP_ENTITLEMENT_UNIT ENT_UNIT ON PSP_COMPANY.COMPANY_SEQ = ENT_UNIT.COMPANY_FK 
JOIN PSP_ENTITLEMENT ENT ON ENT_UNIT.ENTITLEMENT_FK = ENT.ENTITLEMENT_SEQ 
JOIN PSP_ENTITLEMENT_CODE ENT_CODE ON (ENT.ENTITLEMENT_CODE_FK = ENT_CODE.ENTITLEMENT_CODE_SEQ and ENT_CODE.IS_PRIMARY = 1)
JOIN PSP_ENTITLEMENT_CODE_OFFERING ENT_CODE_OFFERING ON ( ENT_CODE_OFFERING.ENTITLEMENT_CODE_FK = ENT.ENTITLEMENT_CODE_FK AND ENT_CODE_OFFERING.IS_DEFAULT = 1 AND ENT_CODE_OFFERING.PRICE_TYPE = PSP_COMPANY.PRICE_TYPE )
INNER JOIN PSP_COMPANY_SERVICE ASSISTED_SVC 
ON PSP_COMPANY.COMPANY_SEQ = ASSISTED_SVC.COMPANY_FK
AND ASSISTED_SVC.SERVICE_FK = 'Tax'
AND ASSISTED_SVC.STATUS_CD IN ('ActiveCurrent','PendingFirstPayroll') 
JOIN PSP_COMPANY_OFFERING on PSP_COMPANY_OFFERING.COMPANY_FK = PSP_COMPANY.COMPANY_SEQ
JOIN PSP_OFFERING CUR_OFFERING ON ( CUR_OFFERING.OFFERING_SEQ = PSP_COMPANY_OFFERING.OFFERING_FK AND CUR_OFFERING.NAME = 'USAGE-BILLING') 
JOIN PSP_OFFERING OLD_OFFERING ON ENT_CODE_OFFERING.OFFERING_FK = OLD_OFFERING.OFFERING_SEQ);
commit;

dbms_output.put_line('Number of Rows Updated For Offering update usage billing:: PSP_COMPANY_OFFERING : ' ||  SQL%ROWCOUNT);
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE ('Error : ' || SQLERRM);
END;

