set timing on echo on feedback on trimspool on
spool get_count_tables

SELECT /*+PARALLEL(1,8) */ count(*) FROM PSPADM.PSP_PAYROLL_RUN;
SELECT /*+PARALLEL(1,8) */ count(*) FROM PSPADM.PSP_FINANCIAL_TRANSACTION;
SELECT /*+PARALLEL(1,8) */ count(*) FROM PSPADM.PSP_MONEY_MOVEMENT_TRANSACTION;
SELECT /*+PARALLEL(1,8) */ count(*) FROM PSPADM.PSP_ENTRY_DETAIL_RECORD;
SELECT /*+PARALLEL(1,8) */ count(*) FROM PSPADM.PSP_PAYCHECK;
SELECT /*+PARALLEL(1,8) */ count(*) FROM PSPADM.PSP_PAYCHECK_SPLIT;

SELECT /*+PARALLEL(1,8) */ max(created_date) FROM PSPADM.PSP_PAYROLL_RUN; 
SELECT /*+PARALLEL(1,8) */ max(created_date) FROM PSPADM.PSP_FINANCIAL_TRANSACTION; 
SELECT /*+PARALLEL(1,8) */ max(created_date) FROM PSPADM.PSP_MONEY_MOVEMENT_TRANSACTION; 
SELECT /*+PARALLEL(1,8) */ max(created_date) FROM PSPADM.PSP_ENTRY_DETAIL_RECORD; 
SELECT /*+PARALLEL(1,8) */ max(created_date) FROM PSPADM.PSP_PAYCHECK; 
SELECT /*+PARALLEL(1,8) */ max(created_date) FROM PSPADM.PSP_PAYCHECK_SPLIT; 

spool off
