UPDATE PSP_SYSTEM_PARAMETER
SET SYSTEM_PARAMETER_ORG = NULL
WHERE SYSTEM_PARAMETER_ORG = 'PROD FIX'
AND SYSTEM_PARAMETER_DESCRIPTION = 'Emergency fix';

PROMPT this should update 32 rows



UPDATE PSP_SYSTEM_PARAMETER
SET SYSTEM_PARAMETER_VALUE = NULL
WHERE SYSTEM_PARAMETER_CODE = 'SYSTEM_PARAMETER_CACHE_VOLATILE_KEYS'

PROMPT should update 1 row
PROMPT commit manually if number of rows match
