// Generated by DB Solo ${version} on ${date} at ${time}
package ${generator.getPackage()};

import org.hibernate.cfg.Configuration;
import org.hibernate.cfg.AnnotationConfiguration;
import org.hibernate.SessionFactory;
import org.hibernate.Session;
import org.hibernate.HibernateException;
import org.hibernate.Hibernate;

import java.util.Date;
import java.util.Properties;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Arrays;
import java.math.BigDecimal;
import java.math.BigInteger;

import java.sql.Blob;
import java.sql.Clob;

import org.dom4j.Element;
import org.dom4j.tree.DefaultElement;
import org.dom4j.util.NodeComparator;

<#list generator.getEnumsWithPackage() as enum>
  <#if generator.hasPackage(enum) && generator.getPackage(enum) != generator.getPackage()>
    import ${enum};
  </#if>
</#list>


public class HibernateUtil
{
  private static final SessionFactory sessionFactory;
  private static final ThreadLocal session = new ThreadLocal();

  static
  {
    try
    {
      Properties props = new Properties();

      props.setProperty("hibernate.connection.driver_class", "${generator.getDriverClass()}");
      props.setProperty("hibernate.connection.url", "${generator.getFilledURL()}");
      props.setProperty("hibernate.connection.username", "${generator.getUsername()}");
      props.setProperty("hibernate.connection.password", "${generator.getPassword()}");
      props.setProperty("hibernate.dialect", "${generator.getDialect()}");
      props.setProperty("hibernate.connection.pool_size", "1");
      props.setProperty("hibernate.current_session_context_class", "thread");
      props.setProperty("hibernate.cache.provider_class", "org.hibernate.cache.NoCacheProvider");
      props.setProperty("hibernate.show_sql", "${generator.showHibernateSql()}");

      Configuration cfg = new AnnotationConfiguration()
<#foreach entity in generator.getJunitClasses()>
                              .addAnnotatedClass(${entity}.class)
</#foreach>
                              .setProperties(props);
      sessionFactory = cfg.buildSessionFactory();
    }
    catch(Throwable ex)
    {
      throw new ExceptionInInitializerError(ex);
    }
  }

  public static Session getNewSession() throws HibernateException
  {
    return sessionFactory.openSession();
  }

  public static Session currentSession() throws HibernateException
  {
    Session s = (Session) session.get();

    if(s == null)
    {
      s = sessionFactory.openSession();
      session.set(s);
    }

    return s;
  }

  public static void closeSession() throws HibernateException
  {
    Session s = (Session) session.get();
    session.set(null);
    if(s != null)
      s.close();
  }

  //
  // Comparison
  //

  public static boolean equals(Element e1, Element e2) throws Exception
  {
    NodeComparator comp = new NodeComparator();

    return comp.compare(e1, e2) == 0;
  }

  public static boolean equals(Blob b1, Blob b2) throws Exception
  {
    return b1.length() == b2.length();
  }

  public static boolean equals(Clob c1, Clob c2) throws Exception
  {
    return c1.length() == c2.length();
  }

  //
  // Methods for generating random values
  //

  public static Blob random_Blob()
  {
     return Hibernate.createBlob(random_byteArray(5000));
  }

  public static Clob random_Clob()
  {
      return Hibernate.createClob(random_String(5000));
  }

  public static boolean random_boolean()
  {
    return random_short() % 2 == 1;
  }

  public static Boolean random_Boolean()
  {
    return random_boolean() ? Boolean.TRUE : Boolean.FALSE;
  }

  public static byte random_byte()
  {
    return (byte) (Math.random() * Byte.MAX_VALUE);
  }

  public static Byte random_Byte()
  {
    return new Byte(random_byte());
  }

  public static byte[] random_byteArray() { return random_byteArray(1); }
  public static byte[] random_byteArray(int len)
  {
    byte[] ret = new byte[len];

    for(int i = 0; i < len; i++)
      ret[i] = random_byte();

    return ret;
  }

  public static short random_short()
  {
    return (short) (Math.random() * Short.MAX_VALUE);
  }

  public static Short random_Short()
  {
    return new Short(random_short());
  }

  public static int random_int()
  {
    return (int) (Math.random() * Integer.MAX_VALUE);
  }

  public static Integer random_Integer()
  {
    return new Integer(random_int());
  }

  public static long random_long()
  {
    return (long) (Math.random() * Long.MAX_VALUE);
  }

  public static Long random_Long()
  {
    return new Long(random_long());
  }

  public static float random_float()
  {
    return (float) random_int();
  }

  public static double random_double()
  {
    return (double) random_int();
  }

  public static Double random_Double()
  {
    return new Double(random_double());
  }

  public static BigInteger random_BigInteger()
  {
    return new BigInteger(random_long() + "");
  }

  public static BigDecimal random_BigDecimal()
  {
    return new BigDecimal(random_Double());
  }

  public static Date random_Date()
  {
    Calendar now = new GregorianCalendar();

    now.add(Calendar.DAY_OF_MONTH, random_int() % 1000);
    now.add(Calendar.HOUR, random_int() % 1000);
    now.add(Calendar.MINUTE, random_int() % 1000);
    now.add(Calendar.SECOND, random_int() % 1000);
    now.set(Calendar.MILLISECOND, 0);

    return now.getTime();
  }

  public static String random_XMLString()
  {
    String elem = random_String(10);

    return "<" + elem + "/>";
  }

  public static String random_String()
  {
    return random_String(1);
  }

  public static String random_String(int len)
  {
    StringBuffer buf = new StringBuffer();

    for(int i = 0; i < len; i++)
    {
      char temp = (char) ('a' + (random_int() % 26));

      buf.append(temp);
    }
    return buf.toString();
  }

  public static Element random_Element()
  {
     return new DefaultElement(random_String());
  }

<#list generator.getEnums() as enum>
  public static ${enum} random_${enum}()
  {
    int index = random_int();

    return ${enum}.values()[index % ${enum}.values().length];
  }
</#list>
}

