// Generated by DB Solo ${version} on ${date} at ${time}
package ${generator.getPackage()};

<#assign temp>

public class ${klass.getName()}Test extends TestCase {

  public void testSelect() {
     List all = selectAll();

     for(int i = 0; i < all.size(); i++) {
       ${klass.getName()} temp = (${klass.getName()}) all.get(i);

       <#if klass.isSubClass() >
           assertNotNull(temp.${klass.getSuperClassPrimaryKeyField().getterMethod()}());
       <#else>
           assertNotNull(temp.${klass.getPrimaryKeyField().getterMethod()}());
       </#if>
     }
  }

  public void testInsert() {
    try
    {
      beginTran();
      int before = selectAll().size();
      ${klass.getName()} obj = insert();
      int after = selectAll().size();

      assertNotNull(obj);
      assertTrue(after == before + 1);
      commit();
    } catch(Exception e) {
      e.printStackTrace();
      rollback();
      assertFalse(true);
    }
  }

  public void testDelete() {
    try
    {
      beginTran();
      ${klass.getName()} obj = insert();
      int before = selectAll().size(), after;

      session().delete(obj);
      after = selectAll().size();
      assertTrue(after == before - 1);
      commit();
    } catch(Exception e) {
      e.printStackTrace();
      rollback();
      assertFalse(true);
    }
  }

  public void testUpdate() {
    try
    {
      // insert
      beginTran();
      ${klass.getName()} obj = insert();
      commit();

      // update
<#foreach field in klass.getFields()>
    <#if generator.updatableField(field) >
         <#if field.isComponent() == false>
             ${field.getJavaType()} temp${field.getName()} = HibernateUtil.random_${generator.methodNameForRandom(field)}();
         <#else>
             ${field.getJavaType()} temp${field.getName()} = random_${generator.methodNameForRandom(field)}();
         </#if>
    </#if>
</#foreach>

<#foreach field in klass.getFields()>
    <#if generator.updatableField(field) >
      obj.${field.setterMethod()}(temp${field.getName()});
    </#if>
</#foreach>
      beginTran();
      session().save(obj);
      commit();
      closeSession();

      // verify results
      beginTran();
<#if klass.isSubClass() >
      obj = (${klass.getName()}) session().get(${klass.getName()}.class, obj.${klass.getSuperClassPrimaryKeyField().getterMethod()}());
<#else>
      obj = (${klass.getName()}) session().get(${klass.getName()}.class, obj.${klass.getPrimaryKeyField().getterMethod()}());
</#if>

<#foreach field in klass.getFields()>
  <#if generator.updatableField(field) >
      ${generator.getAssertEquals(field)};
  </#if>
</#foreach>

      commit();
    } catch(Exception e) {
      e.printStackTrace();
      rollback();
      assertFalse(true);
    }
  }

  protected static ${klass.getName()} insert() {
    ${klass.getName()} obj = new ${klass.getName()}();
<#if generator.insertablePrimaryKey(klass) && klass.getPrimaryKeyField().isComponent() >
     <#if klass.isSubClass() >
       ${klass.getSuperClassPrimaryKeyField().getJavaType()} id = new ${klass.getSuperClassPrimaryKeyField().getJavaType()}();

       <#foreach field in klass.getSuperClassPrimaryKeyField().getComponent().getFields() >
           id.${field.setterMethod()}(HibernateUtil.random_${generator.methodNameForRandom(field)}());
       </#foreach>

       obj.${klass.getSuperClassPrimaryKeyField().setterMethod()}(id);
     <#else>
       ${klass.getPrimaryKeyField().getJavaType()} id = new ${klass.getPrimaryKeyField().getJavaType()}();

       <#foreach field in klass.getPrimaryKeyField().getComponent().getFields() >
           id.${field.setterMethod()}(HibernateUtil.random_${generator.methodNameForRandom(field)}());
       </#foreach>

       obj.${klass.getPrimaryKeyField().setterMethod()}(id);
     </#if>
<#else>

</#if>
<#foreach field in klass.getOwnAndDerivedFields()>
     <#if field.isForeignKey() >
       <#if generator.generateInsertForForeignKey(field) >
         <#if field.isSelfRef() >
             obj.${field.setterMethod()}(obj);
         <#else>
              obj.${field.setterMethod()}(${field.getJavaType()}Test.insert());
         </#if>
       </#if>
     <#elseif field.isPrimaryKey() == false >
        <#if field.isComponent() == false>
            <#if field.isDiscriminatorField() >
               obj.${field.setterMethod()}(${klass.getDiscriminatorValue()});
            <#else>
               obj.${field.setterMethod()}(HibernateUtil.random_${generator.methodNameForRandom(field)}());
            </#if>
         <#else>
             obj.${field.setterMethod()}(random_${generator.methodNameForRandom(field)}());
        </#if>
     <#elseif generator.insertablePrimaryKey(klass)>
        <#if klass.getPrimaryKeyField().isComponent() == false>
             obj.${field.setterMethod()}(HibernateUtil.random_${generator.methodNameForRandom(field)}());
        </#if>
     </#if>
</#foreach>
    session().save(obj);

    return obj;
  }

<#list klass.getOwnAndDerivedEmbeddedComponents() as comp>
  <#if comp.isEmbedded() >
  private static ${comp.getName()} random_${comp.getName()}()
  {
     ${comp.getName()} obj = new ${comp.getName()}();

     <#foreach field in comp.getFields()>
        obj.${field.setterMethod()}(HibernateUtil.random_${generator.methodNameForRandom(field)}());
     </#foreach>

     return obj;
  }
  </#if>
</#list>

  private static List selectAll() { return session().createQuery("from ${klass.getName()}").list(); }
  private static Session session() { return HibernateUtil.currentSession(); }
  private static void beginTran() { HibernateUtil.currentSession().beginTransaction(); }
  private static void commit() { HibernateUtil.currentSession().getTransaction().commit(); }
  private static void rollback() { HibernateUtil.currentSession().getTransaction().rollback(); }
  private static void closeSession() { HibernateUtil.closeSession(); }
}

</#assign>

import java.util.List;
import junit.framework.TestCase;
import org.hibernate.Session;

<#list klass.getImports() as import>
  import ${import};
</#list>
<#list klass.getStaticImports() as import>
  import static ${import};
</#list>

${temp}

