# Properties file for EFTPS Bulk Acknowledgment Splitter

inputDir    = /qsys.lib/zeftpslib.lib/eftpstx.file
errorDir    = /ftplib/eftps/error
renoDir     = /qsys.lib/zeftpslib.lib/eftpsin.file
sandiegoDir = /ftplib/eftps/sd
log4jPropertiesFilePath=/app/eftps/config/log4j.properties
