//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.15 at 04:47:04 PM PST 
//


package com.intuit.sbd.payroll.psp.adapters.qbdtws.payroll.dtos;

import com.intuit.sbd.payroll.psp.adapters.qbdtws.marshalling.ToUpperStringAdapter;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


@XmlJavaTypeAdapter(type = String.class, value = ToUpperStringAdapter.class)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QBAddress", propOrder = {
    "addressLine1",
    "addressLine2",
    "addressLine3",
    "city",
    "state",
    "country",
    "zipCode",
    "zipCodeExtension"
})
public class QBAddress {
    @XmlJavaTypeAdapter(type = String.class, value = ToUpperStringAdapter.class)
    @XmlElement(name = "AddressLine1", required = true)
    protected String addressLine1;
    @XmlJavaTypeAdapter(type = String.class, value = ToUpperStringAdapter.class)
    @XmlElement(name = "AddressLine2")
    protected String addressLine2;
    @XmlJavaTypeAdapter(type = String.class, value = ToUpperStringAdapter.class)
    @XmlElement(name = "AddressLine3")
    protected String addressLine3;
    @XmlJavaTypeAdapter(type = String.class, value = ToUpperStringAdapter.class)
    @XmlElement(name = "City", required = true)
    protected String city;
    @XmlJavaTypeAdapter(type = String.class, value = ToUpperStringAdapter.class)
    @XmlElement(name = "State", required = true)
    protected String state;
    @XmlJavaTypeAdapter(type = String.class, value = ToUpperStringAdapter.class)
    @XmlElement(name = "Country")
    protected String country;
    @XmlElement(name = "ZipCode", required = true)
    @XmlJavaTypeAdapter(type = String.class, value = ToUpperStringAdapter.class)
    protected String zipCode;
    @XmlJavaTypeAdapter(type = String.class, value = ToUpperStringAdapter.class)
    @XmlElement(name = "ZipCodeExtension")
    protected String zipCodeExtension;

    /**
     * Gets the value of the addressLine1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine1() {
        return addressLine1;
    }

    /**
     * Sets the value of the addressLine1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine1(String value) {
        this.addressLine1 = value;
    }

    /**
     * Gets the value of the addressLine2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine2() {
        return addressLine2;
    }

    /**
     * Sets the value of the addressLine2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine2(String value) {
        this.addressLine2 = value;
    }

    /**
     * Gets the value of the addressLine3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine3() {
        return addressLine3;
    }

    /**
     * Sets the value of the addressLine3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine3(String value) {
        this.addressLine3 = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the zipCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZipCode() {
        if (zipCode != null && zipCode.length() > 5) {
            setZipCodeExtension(zipCode.substring(5, zipCode.length()));
            zipCode = zipCode.substring(0, 5);
        }
        return zipCode;
    }

    /**
     * Sets the value of the zipCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZipCode(String value) {
        this.zipCode = value;
    }

    /**
     * Gets the value of the zipCodeExtension property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZipCodeExtension() {
        if (zipCode != null && zipCode.length() > 5) {
            setZipCodeExtension(zipCode.substring(5, zipCode.length()));
            zipCode = zipCode.substring(0, 5);
        }
        return zipCodeExtension;
    }

    /**
     * Sets the value of the zipCodeExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZipCodeExtension(String value) {
        this.zipCodeExtension = value;
    }

}
