//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.15 at 04:47:04 PM PST 
//


package com.intuit.sbd.payroll.psp.adapters.qbdtws.payroll.dtos;

import com.intuit.sbd.payroll.psp.adapters.qbdtws.marshalling.ToUpperStringAdapter;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


@XmlJavaTypeAdapter(type = String.class, value = ToUpperStringAdapter.class)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QBCompany", propOrder = {
    "sourceCompanyId",
    "legalAddress",
    "legalName",
    "fein",
    "QBVersion",
    "taxTableId",
    "applicationId",
    "bankAccount"
})
public class QBCompany {

    @XmlElement(name = "SourceCompanyId", required = true)
    protected String sourceCompanyId;
    @XmlElement(name = "LegalAddress", required = true)
    protected QBAddress legalAddress;

    @XmlJavaTypeAdapter(type = String.class, value = ToUpperStringAdapter.class)
    @XmlElement(name = "LegalName", required = true)
    protected String legalName;
    
    @XmlElement(name = "Fein", required = true)
    protected String fein;
    @XmlElement(name = "QBVersion", required = true, nillable = false)
    protected String QBVersion;
    @XmlElement(name = "TaxTableId", required = true, nillable = false)
    protected String taxTableId;
    @XmlElement(name = "ApplicationId", required = true, nillable = false)
    protected String applicationId;
    @XmlElement(name = "BankAccount", required = false)
    protected QBBankAccount bankAccount;

    public String getSourceCompanyId() {
        return sourceCompanyId;
    }

    public void setSourceCompanyId(String sourceCompanyId) {
        this.sourceCompanyId = sourceCompanyId;
    }

    public QBAddress getLegalAddress() {
        return legalAddress;
    }

    public void setLegalAddress(QBAddress legalAddress) {
        this.legalAddress = legalAddress;
    }

    public String getLegalName() {
        return legalName;
    }

    public void setLegalName(String legalName) {
        this.legalName = legalName;
    }

    public String getFein() {
        return fein;
    }

    public void setFein(String fein) {
        this.fein = fein;
    }

    public String getQBVersion() {
        return QBVersion;
    }

    public void setQBVersion(String QBVersion) {
        this.QBVersion = QBVersion;
    }

    public String getTaxTableId() {
        return taxTableId;
    }

    public void setTaxTableId(String taxTableId) {
        this.taxTableId = taxTableId;
    }

    public String getApplicationId() {
        return applicationId;
    }

    public void setApplicationId(String applicationId) {
        this.applicationId = applicationId;
    }

    public QBBankAccount getBankAccount() {
        return bankAccount;
    }

    public void setBankAccount(QBBankAccount bankAccount) {
        this.bankAccount = bankAccount;
    }
}
