//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.27 at 09:25:31 PM PST 
//


package com.intuit.sbd.payroll.psp.adapters.qbdtws.payroll.dtos;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for QBDirectDepositItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QBDirectDepositItem">
 *   &lt;complexContent>
 *     &lt;extension base="{http://dtos.payroll.qbdtws.adapters.psp.payroll.sbd.intuit.com}QBPaycheckLineItemBase">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Current" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="PayrollItemId" type="{http://www.w3.org/2001/XMLSchema}ID" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QBDirectDepositItem", propOrder = {
    "name",
    "current",
    "payrollItemId",
    "bankRoutingNumber",
    "bankAccountNumber",
    "bankAccountName",
    "bankAccountType"
})
public class QBDirectDepositItem
{
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Current", required = true)
    protected BigDecimal current;
    @XmlElement(name = "PayrollItemId")
    protected String payrollItemId;
    @XmlElement(name = "BankRoutingNumber")
    protected String bankRoutingNumber;
    @XmlElement(name = "BankAccountNumber")
    protected String bankAccountNumber;
    @XmlElement(name = "BankAccountNane")
    protected String bankAccountName;
    @XmlElement(name = "BankAccountType")
    protected QBBankAccountTypeEnum bankAccountType;


    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the current property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCurrent() {
        return current;
    }

    /**
     * Sets the value of the current property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCurrent(BigDecimal value) {
        this.current = value;
    }

    /**
     * Gets the value of the payrollItemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayrollItemId() {
        return payrollItemId;
    }

    /**
     * Sets the value of the payrollItemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayrollItemId(String value) {
        this.payrollItemId = value;
    }

    public String getBankRoutingNumber() {
        return bankRoutingNumber;
    }

    public void setBankRoutingNumber(String bankRoutingNumber) {
        this.bankRoutingNumber = bankRoutingNumber;
    }

    public String getBankAccountNumber() {
        return bankAccountNumber;
    }

    public void setBankAccountNumber(String bankAccountNumber) {
        this.bankAccountNumber = bankAccountNumber;
    }

    public String getBankAccountName() {
        return bankAccountName;
    }

    public void setBankAccountName(String bankAccountName) {
        this.bankAccountName = bankAccountName;
    }

    public QBBankAccountTypeEnum getBankAccountType() {
        return bankAccountType;
    }

    public void setBankAccountType(QBBankAccountTypeEnum bankAccountType) {
        this.bankAccountType = bankAccountType;
    }
}
