//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.15 at 04:47:04 PM PST 
//


package com.intuit.sbd.payroll.psp.adapters.qbdtws.payroll.dtos;

import javax.xml.bind.annotation.*;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QBEmployee", propOrder = {
    "sourceCompanyId",
    "sourceEmployeeId",
    "ofxEmployeeId",
    "isActive",
    "firstName",
    "lastName",
    "middleName",
    "socialSecurityNumber",
    "suffix",
    "phoneNumber",
    "emailAddress",
    "birthDate",
    "hireDate",
    "terminationDate",
    "isStatutory",
    "hasRetirementPlan",
    "hasThirdPartySickPay",
    "liveAddress",
    "workState",
    "fedFilingStatus",
    "fedAllowances",
    "stateFilingStatus",
    "stateAllowances",
    "isHighlyCompensatedEmployee",
    "isFamilyMember",
    "ownerPercent",
    "paySchedule"
})
public class QBEmployee {

    @XmlElement(name = "SourceCompanyId", required = true)
    protected String sourceCompanyId;
    @XmlElement(name = "SourceEmployeeId", required = true)
    protected String sourceEmployeeId;
    @XmlElement(name = "OFXEmployeeID", required = false)
    protected String ofxEmployeeId;
    @XmlElement(name = "IsActive")
    protected boolean isActive;
    @XmlElement(name = "FirstName")
    protected String firstName;
    @XmlElement(name = "LastName")
    protected String lastName;
    @XmlElement(name = "MiddleName")
    protected String middleName;
    @XmlElement(name = "SocialSecurityNumber")
    protected String socialSecurityNumber;
    @XmlElement(name = "Suffix")
    protected String suffix;
    @XmlElement(name = "PhoneNumber")
    protected String phoneNumber;
    @XmlElement(name = "EmailAddress")
    protected String emailAddress;
    @XmlElement(name = "BirthDate")
    protected QBDate birthDate;
    @XmlElement(name = "HireDate")
    protected QBDate hireDate;
    @XmlElement(name = "TerminationDate")
    protected QBDate terminationDate;
    @XmlElement(name = "IsStatutory")
    protected Boolean isStatutory;
    @XmlElement(name = "HasRetirementPlan")
    protected Boolean hasRetirementPlan;
    @XmlElement(name = "HasThirdPartySickPay")
    protected Boolean hasThirdPartySickPay;
    @XmlElement(name = "LiveAddress")
    protected QBAddress liveAddress;
    @XmlElement(name = "WorkState")
    protected String workState;
    @XmlElement(name = "FedFilingStatus")
    protected QBFilingStatusEnum fedFilingStatus;
    @XmlElement(name = "FedAllowances")
    protected Integer fedAllowances;
    @XmlElement(name = "StateFilingStatus")
    protected QBFilingStatusEnum stateFilingStatus;
    @XmlElement(name = "StateAllowances")
    protected Integer stateAllowances;
    @XmlElement(name = "IsHighlyCompensatedEmployee")
    protected Boolean isHighlyCompensatedEmployee;
    @XmlElement(name = "IsFamilyMember")
    protected Boolean isFamilyMember;
    @XmlElement(name = "OwnerPercent")
    protected Double ownerPercent;
    @XmlElement(name = "PaySchedule")
    protected QBPayScheduleEnum paySchedule;

    public String getSourceCompanyId() {
        return sourceCompanyId;
    }

    public void setSourceCompanyId(String sourceCompanyId) {
        this.sourceCompanyId = sourceCompanyId;
    }

    public String getSourceEmployeeId() {
        return sourceEmployeeId;
    }

    public void setSourceEmployeeId(String sourceEmployeeId) {
        this.sourceEmployeeId = sourceEmployeeId;
    }

    public String getOfxEmployeeId() {
        return ofxEmployeeId;
    }

    public void setOfxEmployeeId(String ofxEmployeeId) {
        this.ofxEmployeeId = ofxEmployeeId;
    }

    public boolean isActive() {
        return isActive;
    }

    public void setActive(boolean active) {
        isActive = active;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getMiddleName() {
        return middleName;
    }

    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    public String getSocialSecurityNumber() {
        return socialSecurityNumber;
    }

    public void setSocialSecurityNumber(String socialSecurityNumber) {
        this.socialSecurityNumber = socialSecurityNumber;
    }

    public String getSuffix() {
        return suffix;
    }

    public void setSuffix(String suffix) {
        this.suffix = suffix;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getEmailAddress() {
        return emailAddress;
    }

    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    public QBDate getBirthDate() {
        return birthDate;
    }

    public void setBirthDate(QBDate birthDate) {
        this.birthDate = birthDate;
    }

    public QBDate getHireDate() {
        return hireDate;
    }

    public void setHireDate(QBDate hireDate) {
        this.hireDate = hireDate;
    }

    public QBDate getTerminationDate() {
        return terminationDate;
    }

    public void setTerminationDate(QBDate terminationDate) {
        this.terminationDate = terminationDate;
    }

    public Boolean isStatutory() {
        return isStatutory;
    }

    public void setStatutory(Boolean statutory) {
        isStatutory = statutory;
    }

    public Boolean getHasRetirementPlan() {
        return hasRetirementPlan;
    }

    public void setHasRetirementPlan(Boolean hasRetirementPlan) {
        this.hasRetirementPlan = hasRetirementPlan;
    }

    public Boolean getHasThirdPartySickPay() {
        return hasThirdPartySickPay;
    }

    public void setHasThirdPartySickPay(Boolean hasThirdPartySickPay) {
        this.hasThirdPartySickPay = hasThirdPartySickPay;
    }

    public QBAddress getLiveAddress() {
        return liveAddress;
    }

    public void setLiveAddress(QBAddress liveAddress) {
        this.liveAddress = liveAddress;
    }

    public String getWorkState() {
        return workState;
    }

    public void setWorkState(String workState) {
        this.workState = workState;
    }

    public QBFilingStatusEnum getFedFilingStatus() {
        return fedFilingStatus;
    }

    public void setFedFilingStatus(QBFilingStatusEnum fedFilingStatus) {
        this.fedFilingStatus = fedFilingStatus;
    }

    public Integer getFedAllowances() {
        return fedAllowances;
    }

    public void setFedAllowances(Integer fedAllowances) {
        this.fedAllowances = fedAllowances;
    }

    public QBFilingStatusEnum getStateFilingStatus() {
        return stateFilingStatus;
    }

    public void setStateFilingStatus(QBFilingStatusEnum stateFilingStatus) {
        this.stateFilingStatus = stateFilingStatus;
    }

    public Integer getStateAllowances() {
        return stateAllowances;
    }

    public void setStateAllowances(Integer stateAllowances) {
        this.stateAllowances = stateAllowances;
    }

    public Boolean isHighlyCompensatedEmployee() {
        return isHighlyCompensatedEmployee;
    }

    public void setHighlyCompensatedEmployee(Boolean highlyCompensatedEmployee) {
        isHighlyCompensatedEmployee = highlyCompensatedEmployee;
    }

    public Boolean isFamilyMember() {
        return isFamilyMember;
    }

    public void setFamilyMember(Boolean familyMember) {
        isFamilyMember = familyMember;
    }

    public Double getOwnerPercent() {
        return ownerPercent;
    }

    public void setOwnerPercent(Double ownerPercent) {
        this.ownerPercent = ownerPercent;
    }

    public QBPayScheduleEnum getPaySchedule() {
        return paySchedule;
    }

    public void setPaySchedule(QBPayScheduleEnum paySchedule) {
        this.paySchedule = paySchedule;
    }

    @XmlTransient
    public String getFullName() {
        String firstName = getFirstName() != null ? getFirstName() + " " : "";
        String middleName = getMiddleName() != null ? getMiddleName() + " " : "";
        String lastName = getLastName() != null ? getLastName() : "";
        return firstName + middleName + lastName;
    }

    /**
     * Return the OFX employee identifier if it exists, otherwise
     * return the internal, native QBDT identifier for an employee.
     * Customers who are not on Assisted will only have the native identifier
     * available.
     *  
     * @return ofxEmployeeId if not null, otherwise sourceEmployeeId
     */
    @XmlTransient
    public String getPspEmployeeId() {
        if (isOFXEmployee())
            return getOfxEmployeeId();
        return getSourceEmployeeId();
    }

    @XmlTransient
    public boolean isOFXEmployee() {
        return getOfxEmployeeId() != null && !getOfxEmployeeId().equals("0");
    }


    @Override
    public String toString() {
        return "QBEmployee{" +
                "sourceCompanyId='" + sourceCompanyId + '\'' +
                ", sourceEmployeeId='" + sourceEmployeeId + '\'' +
                ", isActive=" + isActive +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", middleName='" + middleName + '\'' +
                ", socialSecurityNumber='" + socialSecurityNumber + '\'' +
                ", suffix='" + suffix + '\'' +
                ", phoneNumber='" + phoneNumber + '\'' +
                ", emailAddress='" + emailAddress + '\'' +
                ", birthDate=" + birthDate +
                ", hireDate=" + hireDate +
                ", terminationDate=" + terminationDate +
                ", isStatutory=" + isStatutory +
                ", hasRetirementPlan=" + hasRetirementPlan +
                ", hasThirdPartySickPay=" + hasThirdPartySickPay +
                ", liveAddress=" + liveAddress +
                ", workState='" + workState + '\'' +
                ", fedFilingStatus=" + fedFilingStatus +
                ", fedAllowances=" + fedAllowances +
                ", stateFilingStatus=" + stateFilingStatus +
                ", stateAllowances=" + stateAllowances +
                ", isHighlyCompensatedEmployee=" + isHighlyCompensatedEmployee +
                ", isFamilyMember=" + isFamilyMember +
                ", ownerPercent=" + ownerPercent +
                ", paySchedule=" + paySchedule +
                '}';
    }
}
