//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.15 at 04:47:04 PM PST 
//


package com.intuit.sbd.payroll.psp.adapters.qbdtws.payroll.dtos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QBFilingStatusEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="QBFilingStatusEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Single"/>
 *     &lt;enumeration value="MarriedFilingJointly"/>
 *     &lt;enumeration value="MarriedFilingSeparately"/>
 *     &lt;enumeration value="HeadofHousehold"/>
 *     &lt;enumeration value="QualifyingWidowWithDependentChild"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "QBFilingStatusEnum")
@XmlEnum
public enum QBFilingStatusEnum {

    @XmlEnumValue("Single")
    SINGLE("Single"),
    @XmlEnumValue("MarriedFilingJointly")
    MARRIED_FILING_JOINTLY("MarriedFilingJointly"),
    @XmlEnumValue("MarriedFilingSeparately")
    MARRIED_FILING_SEPARATELY("MarriedFilingSeparately"),
    @XmlEnumValue("HeadofHousehold")
    HEADOF_HOUSEHOLD("HeadofHousehold"),
    @XmlEnumValue("QualifyingWidowWithDependentChild")
    QUALIFYING_WIDOW_WITH_DEPENDENT_CHILD("QualifyingWidowWithDependentChild"),
    @XmlEnumValue("Unknown")
    UNKNOWN("UNKNOWN");
    private final String value;

    QBFilingStatusEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static QBFilingStatusEnum fromValue(String v) {
        for (QBFilingStatusEnum c: QBFilingStatusEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
