//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.27 at 09:25:31 PM PST 
//


package com.intuit.sbd.payroll.psp.adapters.qbdtws.payroll.dtos;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QBPaycheckLineTaxCompanyItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QBPaycheckLineTaxCompanyItem">
 *   &lt;complexContent>
 *     &lt;extension base="{http://dtos.payroll.qbdtws.adapters.psp.payroll.sbd.intuit.com}QBPaycheckLineItem">
 *       &lt;sequence>
 *         &lt;element name="WageBase" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="IncomeSubjectToTax" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QBPaycheckLineTaxCompanyItem", propOrder = {
    "wageBase",
    "incomeSubjectToTax"
})
public class QBPaycheckLineTaxCompanyItem
    extends QBPaycheckLineItem
{

    @XmlElement(name = "WageBase", required = true)
    protected BigDecimal wageBase;
    @XmlElement(name = "IncomeSubjectToTax", required = true)
    protected BigDecimal incomeSubjectToTax;

    /**
     * Gets the value of the wageBase property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWageBase() {
        return wageBase;
    }

    /**
     * Sets the value of the wageBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWageBase(BigDecimal value) {
        this.wageBase = value;
    }

    /**
     * Gets the value of the incomeSubjectToTax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIncomeSubjectToTax() {
        return incomeSubjectToTax;
    }

    /**
     * Sets the value of the incomeSubjectToTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIncomeSubjectToTax(BigDecimal value) {
        this.incomeSubjectToTax = value;
    }

}
