//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.15 at 04:47:04 PM PST 
//


package com.intuit.sbd.payroll.psp.adapters.qbdtws.payroll.dtos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QBPayScheduleEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="QBPayScheduleEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Daily"/>
 *     &lt;enumeration value="Weekly"/>
 *     &lt;enumeration value="BiWeekly"/>
 *     &lt;enumeration value="SemiMonthly"/>
 *     &lt;enumeration value="Monthly"/>
 *     &lt;enumeration value="Quarterly"/>
 *     &lt;enumeration value="SemiAnnual"/>
 *     &lt;enumeration value="Annual"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "QBPayScheduleEnum")
@XmlEnum
public enum QBPayScheduleEnum {

    @XmlEnumValue("Daily")
    DAILY("Daily"),
    @XmlEnumValue("Weekly")
    WEEKLY("Weekly"),
    @XmlEnumValue("BiWeekly")
    BI_WEEKLY("BiWeekly"),
    @XmlEnumValue("Monthly")
    MONTHLY("Monthly"),
    @XmlEnumValue("SemiMonthly")
    SEMI_MONTHLY("SemiMonthly"),
    @XmlEnumValue("Quarterly")
    QUARTERLY("Quarterly"),
    @XmlEnumValue("SemiAnnual")
    SEMIANNUAL("SemiAnnual"),
    @XmlEnumValue("Annual")
    ANNUAL("Annual"),
    @XmlEnumValue("Other")
    OTHER("Other");

    private final String value;

    QBPayScheduleEnum() {
        this("");
    }

    QBPayScheduleEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static QBPayScheduleEnum fromValue(String v) {
        for (QBPayScheduleEnum c: QBPayScheduleEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
