//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.27 at 09:25:31 PM PST 
//


package com.intuit.sbd.payroll.psp.adapters.qbdtws.payroll.dtos;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QBPaycheckLineItem", propOrder = {
    "name",
    "current",
    "ytd",
    "payrollItemId"
})
@XmlSeeAlso({
    QBEarningItem.class,
    QBPaycheckLineTaxCompanyItem.class,
    QBPaycheckLineTaxItem.class
})
public class QBPaycheckLineItem
{
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Current", required = true, nillable = false)
    protected BigDecimal current;
    @XmlElement(name = "YTD", required = true, nillable = false)
    protected BigDecimal ytd;
    @XmlElement(name = "PayrollItemId")
    protected String payrollItemId;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the current property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCurrent() {
        return current;
    }

    /**
     * Sets the value of the current property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCurrent(BigDecimal value) {
        this.current = value;
    }

    /**
     * Gets the value of the ytd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getYTD() {
        return ytd;
    }

    /**
     * Sets the value of the ytd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setYTD(BigDecimal value) {
        this.ytd = value;
    }

    /**
     * Gets the value of the payrollItemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayrollItemId() {
        return payrollItemId;
    }

    /**
     * Sets the value of the payrollItemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayrollItemId(String value) {
        this.payrollItemId = value;
    }

}
