//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.27 at 09:25:31 PM PST 
//


package com.intuit.sbd.payroll.psp.adapters.qbdtws.payroll.dtos;

import com.intuit.sbd.payroll.psp.domain.PayrollItemCode;

import javax.xml.bind.annotation.*;


/**
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QBPayrollItem", propOrder = {
        "id",
        "ofxPayrollId",
        "name",
        "payrollItemCategory",
        "taxTrackingTypeId",
        "payrollItemTypeId",
        "specialPayrollItemTypeId",
        "detailTypeId",
        "agencyNumber"
})
public class QBPayrollItem {

    @XmlElement(name = "ID", required = true, nillable = false)
    protected String id;
    @XmlElement(name = "OFXPayrollID", required = false)
    protected String ofxPayrollId;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "PayrollItemCategory", required = true)
    protected QBPayrollItemCategory payrollItemCategory;
    @XmlElement(name = "TaxTrackingTypeId", required = true)
    protected String taxTrackingTypeId;
    @XmlElement(name = "PayrollItemTypeId", required = true)
    protected String payrollItemTypeId;
    @XmlElement(name = "SpecialPayrollItemTypeId", required = true)
    protected String specialPayrollItemTypeId;
    @XmlElement(name = "DetailTypeId", required = true)
    protected String detailTypeId;
    @XmlElement(name = "AgencyNumber")
    protected String agencyNumber;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    public String getOfxPayrollId() {
        return ofxPayrollId;
    }

    public void setOfxPayrollId(String ofxPayrollId) {
        this.ofxPayrollId = ofxPayrollId;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the payrollItemCategory property.
     * 
     * @return
     *     possible object is
     *     {@link QBPayrollItemCategory }
     *     
     */
    public QBPayrollItemCategory getPayrollItemCategory() {
        return payrollItemCategory;
    }

    /**
     * Sets the value of the payrollItemCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link QBPayrollItemCategory }
     *     
     */
    public void setPayrollItemCategory(QBPayrollItemCategory value) {
        this.payrollItemCategory = value;
    }

    /**
     * Gets the value of the taxTrackingTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxTrackingTypeId() {
        return taxTrackingTypeId;
    }

    /**
     * Sets the value of the taxTrackingTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxTrackingTypeId(String value) {
        this.taxTrackingTypeId = value;
    }

    /**
     * Gets the value of the payrollItemTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayrollItemTypeId() {
        return payrollItemTypeId;
    }

    /**
     * Sets the value of the payrollItemTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayrollItemTypeId(String value) {
        this.payrollItemTypeId = value;
    }

    /**
     * Gets the value of the specialPayrollItemTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialPayrollItemTypeId() {
        return specialPayrollItemTypeId;
    }

    /**
     * Sets the value of the specialPayrollItemTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialPayrollItemTypeId(String value) {
        this.specialPayrollItemTypeId = value;
    }

    /**
     * Gets the value of the detailTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDetailTypeId() {
        return detailTypeId;
    }

    /**
     * Sets the value of the detailTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDetailTypeId(String value) {
        this.detailTypeId = value;
    }

    public String getAgencyNumber() {
        return agencyNumber;
    }

    public void setAgencyNumber(String agencyNumber) {
        this.agencyNumber = agencyNumber;
    }

    /**
     * Return the OFX employee identifier if it exists, otherwise
     * return the internal, native QBDT identifier for an employee.
     * Customers who are not on Assisted will only have the native identifier
     * available.
     *
     * @return ofxEmployeeId if not null, otherwise sourceEmployeeId
     */
    @XmlTransient
    public String getPspPayrollItemId() {
        if (isOFXPayrollItem())
            return getOfxPayrollId();
        return getID();
    }

    @XmlTransient
    public boolean isOFXPayrollItem() {
        return getOfxPayrollId() != null && !getOfxPayrollId().equals("0");
    }

    public PayrollItemCode getPayrollItemCode(PayrollItemCode pDefaultCode) {
        PayrollItemCode code = getPayrollItemCode();
        if (code == null) {
            code = pDefaultCode;
        }
        return code;
    }

    @XmlTransient
    public PayrollItemCode getPayrollItemCode() {
        if (getPayrollItemTypeId() == null) {
            return null;
        }

        // PI_SALARY
        if (getPayrollItemTypeId().equals("0")) {
            return PayrollItemCode.Salary;
        // PI_HOURLY
        } else if (getPayrollItemTypeId().equals("1")) {
            return PayrollItemCode.Hourly;
        // PI_COMMISSION
        } else if (getPayrollItemTypeId().equals("2")) {
            return PayrollItemCode.Commission;
        // PI_ADD
        } else if (getPayrollItemTypeId().equals("3")) {
            if (getTaxTrackingTypeId().equals("0")) {
                return PayrollItemCode.OtherAdditionPostTax;
            } else {
                return PayrollItemCode.OtherAdditionPreTax;
            }
        // PI_DEDUCT
        } else if (getPayrollItemTypeId().equals("4")) {
            if (getTaxTrackingTypeId().equals("0")) {
                return PayrollItemCode.OtherPostTaxDeduction;
            } else {
                return PayrollItemCode.OtherPreTaxDeduction;
            }
        // PI_COMPANY
        } else if (getPayrollItemTypeId().equals("5")) {
            if (getTaxTrackingTypeId().equals("0")) {
                return PayrollItemCode.OtherNonTaxableEmployerContribution;
            } else {
                return PayrollItemCode.OtherTaxableEmployerContribution;
            }
        // PI_DIRDEP
        } else if (getPayrollItemTypeId().equals("11")) {
            return PayrollItemCode.DirectDeposit;
        // PI_BONUS
        } else if (getPayrollItemTypeId().equals("12")) {
            return PayrollItemCode.Bonus;
        } else {
            return null;
        } 
    }

    @Override
    public String toString() {
        return "QBPayrollItem{" +
                "id='" + id + '\'' +
                ", name='" + name + '\'' +
                ", payrollItemCategory=" + payrollItemCategory +
                ", taxTrackingTypeId='" + taxTrackingTypeId + '\'' +
                ", payrollItemTypeId='" + payrollItemTypeId + '\'' +
                ", specialPayrollItemTypeId='" + specialPayrollItemTypeId + '\'' +
                ", detailTypeId='" + detailTypeId + '\'' +
                ", agencyNumber='" + agencyNumber + '\'' +
                '}';
    }
}
