//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.27 at 09:25:31 PM PST 
//


package com.intuit.sbd.payroll.psp.adapters.qbdtws.payroll.dtos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QBPayrollItemCategory.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="QBPayrollItemCategory">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="EarningItem"/>
 *     &lt;enumeration value="PreTaxItem"/>
 *     &lt;enumeration value="AdjNetPayItem"/>
 *     &lt;enumeration value="TaxItem"/>
 *     &lt;enumeration value="NonTaxCompanyItem"/>
 *     &lt;enumeration value="TaxCompanyItem"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "QBPayrollItemCategory")
@XmlEnum
public enum QBPayrollItemCategory {

    @XmlEnumValue("EarningItem")
    EARNING_ITEM("EarningItem"),
    @XmlEnumValue("PreTaxItem")
    PRE_TAX_ITEM("PreTaxItem"),
    @XmlEnumValue("AdjNetPayItem")
    ADJ_NET_PAY_ITEM("AdjNetPayItem"),
    @XmlEnumValue("TaxItem")
    TAX_ITEM("TaxItem"),
    @XmlEnumValue("NonTaxCompanyItem")
    NON_TAX_COMPANY_ITEM("NonTaxCompanyItem"),
    @XmlEnumValue("TaxCompanyItem")
    TAX_COMPANY_ITEM("TaxCompanyItem"),
    @XmlEnumValue("DirectDepositItem")
    DIRECT_DEPOSIT_ITEM("DirectDepositItem");
    private final String value;

    QBPayrollItemCategory(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static QBPayrollItemCategory fromValue(String v) {
        for (QBPayrollItemCategory c: QBPayrollItemCategory.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
