//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.27 at 09:25:31 PM PST 
//


package com.intuit.sbd.payroll.psp.adapters.qbdtws.payroll.dtos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QBPaycheckOperationEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="QBPaycheckOperationEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Add"/>
 *     &lt;enumeration value="Edit"/>
 *     &lt;enumeration value="Delete"/>
 *     &lt;enumeration value="Void"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "QBPaycheckOperationEnum")
@XmlEnum
public enum QBPaycheckOperationEnum {

    @XmlEnumValue("Add")
    ADD("Add"),
    @XmlEnumValue("Edit")
    EDIT("Edit"),
    @XmlEnumValue("Delete")
    DELETE("Delete"),
    @XmlEnumValue("Void")
    VOID("Void");
    private final String value;

    QBPaycheckOperationEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static QBPaycheckOperationEnum fromValue(String v) {
        for (QBPaycheckOperationEnum c: QBPaycheckOperationEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
