//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.27 at 09:25:31 PM PST 
//


package com.intuit.sbd.payroll.psp.adapters.qbdtws.payroll.dtos;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Collection of special payroll item type definitions
 * 
 * <p>Java class for QBSpecialPayrollItemTypes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QBSpecialPayrollItemTypes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SpecialPayrollItemType" type="{http://dtos.payroll.qbdtws.adapters.psp.payroll.sbd.intuit.com}QBBaseItemType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QBSpecialPayrollItemTypes", propOrder = {
    "specialPayrollItemType"
})
public class QBSpecialPayrollItemTypes {

    @XmlElement(name = "SpecialPayrollItemType", required = true)
    protected List<QBBaseItemType> specialPayrollItemType;

    /**
     * Gets the value of the specialPayrollItemType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the specialPayrollItemType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecialPayrollItemType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QBBaseItemType }
     * 
     * 
     */
    public List<QBBaseItemType> getSpecialPayrollItemType() {
        if (specialPayrollItemType == null) {
            specialPayrollItemType = new ArrayList<QBBaseItemType>();
        }
        return this.specialPayrollItemType;
    }

}
