//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.27 at 09:25:31 PM PST 
//


package com.intuit.sbd.payroll.psp.adapters.qbdtws.payroll.dtos;

import com.intuit.sbd.payroll.psp.adapters.qbdtws.common.dtos.Request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubmitPayrollRequest", propOrder = {
        "currentToken",
        "updateCompanyRequest",
        "submitEmployeesRequest",
        "paycheckList",
        "payrollItemList",
        "taxTrackingtypeList",
        "payrollItemTypeList",
        "specialPayrollItemTypeList",
        "detailTypeList"
})
public class SubmitPayrollRequest extends Request {
    @XmlElement(name = "CurrentToken")
    protected String currentToken;

    @XmlElement(name = "UpdateCompanyRequest", required = false)
    protected UpdateCompanyRequest updateCompanyRequest;

    @XmlElement(name = "SubmitEmployeesRequest", required = false)
    protected SubmitEmployeesRequest submitEmployeesRequest;

    @XmlElement(name = "PaycheckList")
    protected QBPaychecks paycheckList;
    @XmlElement(name = "PayrollItemList")
    protected QBPayrollItems payrollItemList;
    @XmlElement(name = "TaxTrackingtypeList")
    protected QBTaxTrackingTypes taxTrackingtypeList;
    @XmlElement(name = "PayrollItemTypeList")
    protected QBPayrollItemTypes payrollItemTypeList;
    @XmlElement(name = "SpecialPayrollItemTypeList")
    protected QBSpecialPayrollItemTypes specialPayrollItemTypeList;
    @XmlElement(name = "DetailTypeList")
    protected QBDetailTypes detailTypeList;


    public String getCurrentToken() {
        return currentToken;
    }

    public void setCurrentToken(String currentToken) {
        this.currentToken = currentToken;
    }

    public UpdateCompanyRequest getUpdateCompanyRequest() {
        return updateCompanyRequest;
    }

    public void setUpdateCompanyRequest(UpdateCompanyRequest updateCompanyRequest) {
        this.updateCompanyRequest = updateCompanyRequest;
    }

    public SubmitEmployeesRequest getSubmitEmployeesRequest() {
        return submitEmployeesRequest;
    }

    public void setSubmitEmployeesRequest(SubmitEmployeesRequest submitEmployeesRequest) {
        this.submitEmployeesRequest = submitEmployeesRequest;
    }

    /**
     * Gets the value of the paycheckList property.
     * 
     * @return
     *     possible object is
     *     {@link QBPaychecks }
     *     
     */
    public QBPaychecks getPaycheckList() {
        return paycheckList;
    }

    /**
     * Sets the value of the paycheckList property.
     * 
     * @param value
     *     allowed object is
     *     {@link QBPaychecks }
     *     
     */
    public void setPaycheckList(QBPaychecks value) {
        this.paycheckList = value;
    }

    /**
     * Gets the value of the payrollItemList property.
     * 
     * @return
     *     possible object is
     *     {@link QBPayrollItems }
     *     
     */
    public QBPayrollItems getPayrollItemList() {
        return payrollItemList;
    }

    /**
     * Sets the value of the payrollItemList property.
     * 
     * @param value
     *     allowed object is
     *     {@link QBPayrollItems }
     *     
     */
    public void setPayrollItemList(QBPayrollItems value) {
        this.payrollItemList = value;
    }

    /**
     * Gets the value of the taxTrackingtypeList property.
     * 
     * @return
     *     possible object is
     *     {@link QBTaxTrackingTypes }
     *     
     */
    public QBTaxTrackingTypes getTaxTrackingtypeList() {
        return taxTrackingtypeList;
    }

    /**
     * Sets the value of the taxTrackingtypeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link QBTaxTrackingTypes }
     *     
     */
    public void setTaxTrackingtypeList(QBTaxTrackingTypes value) {
        this.taxTrackingtypeList = value;
    }

    /**
     * Gets the value of the payrollItemTypeList property.
     * 
     * @return
     *     possible object is
     *     {@link QBPayrollItemTypes }
     *     
     */
    public QBPayrollItemTypes getPayrollItemTypeList() {
        return payrollItemTypeList;
    }

    /**
     * Sets the value of the payrollItemTypeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link QBPayrollItemTypes }
     *     
     */
    public void setPayrollItemTypeList(QBPayrollItemTypes value) {
        this.payrollItemTypeList = value;
    }

    /**
     * Gets the value of the specialPayrollItemTypeList property.
     * 
     * @return
     *     possible object is
     *     {@link QBSpecialPayrollItemTypes }
     *     
     */
    public QBSpecialPayrollItemTypes getSpecialPayrollItemTypeList() {
        return specialPayrollItemTypeList;
    }

    /**
     * Sets the value of the specialPayrollItemTypeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link QBSpecialPayrollItemTypes }
     *     
     */
    public void setSpecialPayrollItemTypeList(QBSpecialPayrollItemTypes value) {
        this.specialPayrollItemTypeList = value;
    }

    /**
     * Gets the value of the detailTypeList property.
     * 
     * @return
     *     possible object is
     *     {@link QBDetailTypes }
     *     
     */
    public QBDetailTypes getDetailTypeList() {
        return detailTypeList;
    }

    /**
     * Sets the value of the detailTypeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link QBDetailTypes }
     *     
     */
    public void setDetailTypeList(QBDetailTypes value) {
        this.detailTypeList = value;
    }

}
