//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.15 at 04:47:04 PM PST 
//


package com.intuit.sbd.payroll.psp.adapters.qbdtws.payroll.dtos;

import com.intuit.sbd.payroll.psp.adapters.qbdtws.common.dtos.Request;

import javax.xml.bind.annotation.*;


@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpdateCompanyRequest",        
        propOrder = { "company" })
public class UpdateCompanyRequest {

    @XmlElement(name = "Company", required = true)
    protected QBCompany company;

    public QBCompany getCompany() {
        return company;
    }

    public void setCompany(QBCompany value) {
        this.company = value;
    }

}
