--
-- This script will be executed AFTER the automatically generated
-- C:\dev\PSP\main\PSE\Domain\src\main\model\DBUpgrade_002.000.000.032.sql
--
-- Developers can hand code logic here for data migration purposes
--
