--
-- This script will be executed BEFORE the automatically generated
-- C:\Dev\PSP\main\PSE\Domain\src\main\model\DBUpgrade_002.000.000.034.sql
--
-- Developers can hand code logic here for data migration purposes
--
