--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--                                                                      --
-- Please review the script before using it to make sure it won't       --
-- cause any unacceptable data loss.                                    --
--                                                                      --
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL
-- PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL
Prompt Column AGENCY_SUPPORTED;
ALTER TABLE PSP_AGENCY
 ADD (AGENCY_SUPPORTED  NUMBER(1));

Prompt Table PSP_ATFDATA_EXTRACT_BATCH;
--
-- PSP_ATFDATA_EXTRACT_BATCH  (Table)
--
CREATE TABLE PSP_ATFDATA_EXTRACT_BATCH
(
  ATFDATA_EXTRACT_BATCH_SEQ  VARCHAR2(255 CHAR),
  VERSION                    NUMBER(19),
  CREATOR_ID                 VARCHAR2(30 CHAR),
  CREATED_DATE               TIMESTAMP(6),
  MODIFIER_ID                VARCHAR2(30 CHAR),
  MODIFIED_DATE              TIMESTAMP(6),
  REALM_ID                   NUMBER(19)         DEFAULT -1,
  RUN_TYPE                   VARCHAR2(255 CHAR),
  BATCH_ID                   NUMBER(19),
  START_DATE                 TIMESTAMP(6),
  STATUS_EFFECTIVE_DATE      TIMESTAMP(6),
  BATCH_STATUS               VARCHAR2(255 CHAR),
  YEAR                       NUMBER(10),
  QUARTER                    NUMBER(10)
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE PSP_ATFDATA_EXTRACT_BATCH
 ADD PRIMARY KEY
 (ATFDATA_EXTRACT_BATCH_SEQ, REALM_ID);

Prompt Column DEFAULT_DEPOSIT_FREQUENCY;
ALTER TABLE PSP_PAYMENT_TEMPLATE
 ADD (DEFAULT_DEPOSIT_FREQUENCY  VARCHAR2(50 CHAR));

Prompt Column NON_MODIFIABLE_FREQUENCY;
ALTER TABLE PSP_PAYMENT_TEMPLATE
 ADD (NON_MODIFIABLE_FREQUENCY  NUMBER(1));

Prompt Column FIRST_FILINGS_QUARTER;
ALTER TABLE PSP_COMPANY_AGENCY
 ADD (FIRST_FILINGS_QUARTER  VARCHAR2(5 CHAR));

Prompt Column LAST_FILINGS_QUARTER;
ALTER TABLE PSP_COMPANY_AGENCY
 ADD (LAST_FILINGS_QUARTER  VARCHAR2(5 CHAR));

Prompt Column IS_FINAL_RETURN;
ALTER TABLE PSP_COMPANY_AGENCY
 ADD (IS_FINAL_RETURN  NUMBER(1));

Prompt Column GENERATE_ANNUAL_FORM;
ALTER TABLE PSP_COMPANY_AGENCY
 ADD (GENERATE_ANNUAL_FORM  NUMBER(1));

Prompt Column FINAL_PAYROLL_DATE;
ALTER TABLE PSP_COMPANY_AGENCY
 ADD (FINAL_PAYROLL_DATE  TIMESTAMP(6));

Prompt Table PSP_ATFDATA_EXTRACT_FILE;
--
-- PSP_ATFDATA_EXTRACT_FILE  (Table)
--
CREATE TABLE PSP_ATFDATA_EXTRACT_FILE
(
  ATFDATA_EXTRACT_FILE_SEQ     VARCHAR2(255 CHAR),
  VERSION                      NUMBER(19),
  CREATOR_ID                   VARCHAR2(30 CHAR),
  CREATED_DATE                 TIMESTAMP(6),
  MODIFIER_ID                  VARCHAR2(30 CHAR),
  MODIFIED_DATE                TIMESTAMP(6),
  REALM_ID                     NUMBER(19)       DEFAULT -1,
  FILE_TYPE                    VARCHAR2(255 CHAR),
  FILE_STATUS                  VARCHAR2(255 CHAR),
  FILE_NAME                    VARCHAR2(100 CHAR),
  STATUS_EFFECTIVE_DATE        TIMESTAMP(6),
  START_DATE                   TIMESTAMP(6),
  A_T_F_DATA_EXTRACT_BATCH_FK  VARCHAR2(255 CHAR)
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

Prompt Index PSP_ATFDATA_EXTRACT_FILE_FK1;
--
-- PSP_ATFDATA_EXTRACT_FILE_FK1  (Index)
--
CREATE INDEX PSP_ATFDATA_EXTRACT_FILE_FK1 ON PSP_ATFDATA_EXTRACT_FILE
(A_T_F_DATA_EXTRACT_BATCH_FK, REALM_ID)
LOGGING
NOPARALLEL;

ALTER TABLE PSP_ATFDATA_EXTRACT_FILE
 ADD PRIMARY KEY
 (ATFDATA_EXTRACT_FILE_SEQ, REALM_ID);

Prompt Column HIRE_DATE;
ALTER TABLE PSP_EMPLOYEE
 ADD (HIRE_DATE  TIMESTAMP(6));

Prompt Column RE_HIRE_DATE;
ALTER TABLE PSP_EMPLOYEE
 ADD (RE_HIRE_DATE  TIMESTAMP(6));

Prompt Column FED_FILING_STATUS;
ALTER TABLE PSP_EMPLOYEE
 ADD (FED_FILING_STATUS  VARCHAR2(50 CHAR));

Prompt Column WORK_STATE;
ALTER TABLE PSP_EMPLOYEE
 ADD (WORK_STATE  VARCHAR2(21 CHAR));

Prompt Column TERMINATION_DATE;
ALTER TABLE PSP_EMPLOYEE
 ADD (TERMINATION_DATE  TIMESTAMP(6));

Prompt Column FED_ALLOWANCES;
ALTER TABLE PSP_EMPLOYEE
 ADD (FED_ALLOWANCES  NUMBER(10));

Prompt Column STATE_FILING_STATUS;
ALTER TABLE PSP_EMPLOYEE
 ADD (STATE_FILING_STATUS  VARCHAR2(50 CHAR));

Prompt Column STATE_ALLOWANCES;
ALTER TABLE PSP_EMPLOYEE
 ADD (STATE_ALLOWANCES  NUMBER(10));

Prompt Column IS_STATUTORY;
ALTER TABLE PSP_EMPLOYEE
 ADD (IS_STATUTORY  NUMBER(1));

Prompt Column HAS_RETIREMENT_PLAN;
ALTER TABLE PSP_EMPLOYEE
 ADD (HAS_RETIREMENT_PLAN  NUMBER(1));

Prompt Column HAS_THIRD_PARTY_SICK_PAY;
ALTER TABLE PSP_EMPLOYEE
 ADD (HAS_THIRD_PARTY_SICK_PAY  NUMBER(1));

Prompt Table PSP_TAX_PENALTY_INTEREST;
--
-- PSP_TAX_PENALTY_INTEREST  (Table)
--
CREATE TABLE PSP_TAX_PENALTY_INTEREST
(
  TAX_PENALTY_INTEREST_SEQ  VARCHAR2(255 CHAR),
  VERSION                   NUMBER(19),
  CREATOR_ID                VARCHAR2(30 CHAR),
  CREATED_DATE              TIMESTAMP(6),
  MODIFIER_ID               VARCHAR2(30 CHAR),
  MODIFIED_DATE             TIMESTAMP(6),
  REALM_ID                  NUMBER(19)          DEFAULT -1,
  TYPE                      VARCHAR2(255 CHAR),
  TRANSACTION_ID            VARCHAR2(100 CHAR),
  PENALTY_INTEREST_DATE     TIMESTAMP(6),
  AMOUNT                    NUMBER(19,4),
  NOTE                      VARCHAR2(4000 CHAR),
  COMPANY_AGENCY_FK         VARCHAR2(255 CHAR)
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

Prompt Index PSP_TAX_PENALTY_INTEREST_FK1;
--
-- PSP_TAX_PENALTY_INTEREST_FK1  (Index)
--
CREATE INDEX PSP_TAX_PENALTY_INTEREST_FK1 ON PSP_TAX_PENALTY_INTEREST
(COMPANY_AGENCY_FK, REALM_ID)
LOGGING
NOPARALLEL;

ALTER TABLE PSP_TAX_PENALTY_INTEREST
 ADD PRIMARY KEY
 (TAX_PENALTY_INTEREST_SEQ, REALM_ID);

Prompt Column AGENCY_TAXPAYER_ID;
ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 ADD (AGENCY_TAXPAYER_ID  VARCHAR2(80 CHAR));

Prompt Column TAX_PENALTY_INTEREST_FK;
ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 ADD (TAX_PENALTY_INTEREST_FK  VARCHAR2(255 CHAR));

--Prompt Index PSP_MONEY_MOVEMENT_TRANSAC_FK7;
--
-- PSP_MONEY_MOVEMENT_TRANSAC_FK7  (Index)
--
--CREATE INDEX PSP_MONEY_MOVEMENT_TRANSAC_FK7 ON PSP_MONEY_MOVEMENT_TRANSACTION
--(OFFLOAD_BATCH_FK, REALM_ID)
--LOGGING
--NOPARALLEL;

--Prompt Index PSP_MONEY_MOVEMENT_TRANSAC_FK6;
--Prompt drop Index PSP_MONEY_MOVEMENT_TRANSAC_FK6;
--DROP INDEX PSP_MONEY_MOVEMENT_TRANSAC_FK6;
--Prompt Index PSP_MONEY_MOVEMENT_TRANSAC_FK6;
--
-- PSP_MONEY_MOVEMENT_TRANSAC_FK6  (Index)
--
--CREATE INDEX PSP_MONEY_MOVEMENT_TRANSAC_FK6 ON PSP_MONEY_MOVEMENT_TRANSACTION
--(COMPANY_FK, REALM_ID)
--LOGGING
--NOPARALLEL;

--Prompt Index PSP_MONEY_MOVEMENT_TRANSAC_FK5;
--Prompt drop Index PSP_MONEY_MOVEMENT_TRANSAC_FK5;
--DROP INDEX PSP_MONEY_MOVEMENT_TRANSAC_FK5;
--Prompt Index PSP_MONEY_MOVEMENT_TRANSAC_FK5;
--
-- PSP_MONEY_MOVEMENT_TRANSAC_FK5  (Index)
--
--CREATE INDEX PSP_MONEY_MOVEMENT_TRANSAC_FK5 ON PSP_MONEY_MOVEMENT_TRANSACTION
--(AUTH_USER_FK, REALM_ID)
--LOGGING
--NOPARALLEL;

Prompt Index PSP_MONEY_MOVEMENT_TRANSAC_FK4;
Prompt drop Index PSP_MONEY_MOVEMENT_TRANSAC_FK4;
DROP INDEX PSP_MONEY_MOVEMENT_TRANSAC_FK4;
Prompt Index PSP_MONEY_MOVEMENT_TRANSAC_FK4;
--
-- PSP_MONEY_MOVEMENT_TRANSAC_FK4  (Index)
--
CREATE INDEX PSP_MONEY_MOVEMENT_TRANSAC_FK4 ON PSP_MONEY_MOVEMENT_TRANSACTION
(TAX_PENALTY_INTEREST_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt Constraint PSP_MONEY_MOVEMENT_TRANSAC_FK4;
ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 DROP CONSTRAINT PSP_MONEY_MOVEMENT_TRANSAC_FK4;
ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 ADD CONSTRAINT PSP_MONEY_MOVEMENT_TRANSAC_FK4
 FOREIGN KEY (TAX_PENALTY_INTEREST_FK, REALM_ID)
 REFERENCES PSP_TAX_PENALTY_INTEREST (TAX_PENALTY_INTEREST_SEQ,REALM_ID);

Prompt Constraint PSP_MONEY_MOVEMENT_TRANSAC_FK5;
ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 DROP CONSTRAINT PSP_MONEY_MOVEMENT_TRANSAC_FK5;
ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 ADD CONSTRAINT PSP_MONEY_MOVEMENT_TRANSAC_FK5
 FOREIGN KEY (AUTH_USER_FK, REALM_ID)
 REFERENCES PSP_AUTH_USER (AUTH_USER_SEQ,REALM_ID);

Prompt Constraint PSP_MONEY_MOVEMENT_TRANSAC_FK6;
ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 DROP CONSTRAINT PSP_MONEY_MOVEMENT_TRANSAC_FK6;
ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 ADD CONSTRAINT PSP_MONEY_MOVEMENT_TRANSAC_FK6
 FOREIGN KEY (COMPANY_FK, REALM_ID)
 REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

ALTER TABLE PSP_ATFDATA_EXTRACT_FILE
 ADD CONSTRAINT PSP_ATFDATA_EXTRACT_FILE_FK1
 FOREIGN KEY (A_T_F_DATA_EXTRACT_BATCH_FK, REALM_ID)
 REFERENCES PSP_ATFDATA_EXTRACT_BATCH (ATFDATA_EXTRACT_BATCH_SEQ,REALM_ID);

ALTER TABLE PSP_TAX_PENALTY_INTEREST
 ADD CONSTRAINT PSP_TAX_PENALTY_INTEREST_FK1
 FOREIGN KEY (COMPANY_AGENCY_FK, REALM_ID)
 REFERENCES PSP_COMPANY_AGENCY (COMPANY_AGENCY_SEQ,REALM_ID);

ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 ADD CONSTRAINT PSP_MONEY_MOVEMENT_TRANSAC_FK7
 FOREIGN KEY (OFFLOAD_BATCH_FK, REALM_ID)
 REFERENCES PSP_OFFLOAD_BATCH (OFFLOAD_BATCH_SEQ,REALM_ID);

 
PROMPT finishedDBUpgrade_002.000.000.032.sql