--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--                                                                      --
-- Please review the script before using it to make sure it won't       --
-- cause any unacceptable data loss.                                    --
--                                                                      --
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL
-- PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL
Prompt Column S_K_U;
ALTER TABLE PSP_OFFERING
MODIFY(S_K_U VARCHAR2(40 CHAR));


Prompt Column NAME;
ALTER TABLE PSP_OFFERING
MODIFY(NAME VARCHAR2(100 CHAR));


Prompt Column DESCRIPTION;
ALTER TABLE PSP_OFFERING
MODIFY(DESCRIPTION VARCHAR2(256 CHAR));


Prompt Column OFFER_CD;
ALTER TABLE PSP_OFFER
MODIFY(OFFER_CD VARCHAR2(40 CHAR));


Prompt Column NAME;
ALTER TABLE PSP_OFFER
MODIFY(NAME VARCHAR2(100 CHAR));


Prompt Column DESCRIPTION;
ALTER TABLE PSP_OFFER
MODIFY(DESCRIPTION VARCHAR2(256 CHAR));


Prompt Column CONFIRMATION_CODE;
ALTER TABLE PSP_NACHAFILE
MODIFY(CONFIRMATION_CODE VARCHAR2(100 CHAR));


Prompt Column FILE_NAME;
ALTER TABLE PSP_NACHAFILE
MODIFY(FILE_NAME VARCHAR2(1000 CHAR));


Prompt Column FILE_I_D_MODIFIER;
ALTER TABLE PSP_NACHAFILE
MODIFY(FILE_I_D_MODIFIER VARCHAR2(50 CHAR));


Prompt Column FILE_NAME;
ALTER TABLE PSP_GEMS_UPLOAD_BATCH
MODIFY(FILE_NAME VARCHAR2(1000 CHAR));


Prompt Column FILE_NAME;
ALTER TABLE PSP_DICRFILE
MODIFY(FILE_NAME VARCHAR2(1000 CHAR));


Prompt Column MESSAGE;
ALTER TABLE PSP_BATCH_JOB_AUDIT_LOG
MODIFY(MESSAGE VARCHAR2(100 CHAR));


Prompt Column MESSAGE_DETAIL;
ALTER TABLE PSP_BATCH_JOB_AUDIT_LOG
MODIFY(MESSAGE_DETAIL VARCHAR2(256 CHAR));


Prompt Column BANK_HOLIDAY_NAME;
ALTER TABLE PSP_BANK_HOLIDAY
MODIFY(BANK_HOLIDAY_NAME VARCHAR2(100 CHAR));


Prompt Column DESCRIPTION;
ALTER TABLE PSP_SYSTEM_CAPABILITY
MODIFY(DESCRIPTION VARCHAR2(256 CHAR));


Prompt Column DESCRIPTION;
ALTER TABLE PSP_SERVICE_STATUS
MODIFY(DESCRIPTION VARCHAR2(256 CHAR));


Prompt Column DESCRIPTION;
ALTER TABLE PSP_RETURN_REASON_DESC
MODIFY(DESCRIPTION VARCHAR2(256 CHAR));


Prompt Column VALUE_CLASS_NAME;
ALTER TABLE PSP_EVENT_DETAIL_TYPE
MODIFY(VALUE_CLASS_NAME VARCHAR2(150 CHAR));


Prompt Column DESCRIPTION;
ALTER TABLE PSP_COLLECTION_STAGE
MODIFY(DESCRIPTION VARCHAR2(100 CHAR));


Prompt Column DESCRIPTION;
ALTER TABLE PSP_AUTH_OPERATION
MODIFY(DESCRIPTION VARCHAR2(256 CHAR));


Prompt Column NAME;
ALTER TABLE PSP_AUTH_OPERATION
MODIFY(NAME VARCHAR2(100 CHAR));


Prompt Column DESCRIPTION;
ALTER TABLE PSP_AUTH_DOMAIN
MODIFY(DESCRIPTION VARCHAR2(256 CHAR));


Prompt Column NAME;
ALTER TABLE PSP_AUTH_DOMAIN
MODIFY(NAME VARCHAR2(100 CHAR));


Prompt Column A_C_H_RETURN_FILE_NAME;
ALTER TABLE PSP_TRANSACTION_RETURN_BATCH
MODIFY(A_C_H_RETURN_FILE_NAME VARCHAR2(1000 CHAR));


Prompt Column BANK_NAME;
ALTER TABLE PSP_BANK_ACCOUNT
MODIFY(BANK_NAME VARCHAR2(256 CHAR));


Prompt Column CITY;
ALTER TABLE PSP_ADDRESS
MODIFY(CITY VARCHAR2(256 CHAR));


Prompt Column COUNTRY;
ALTER TABLE PSP_ADDRESS
MODIFY(COUNTRY VARCHAR2(256 CHAR));


Prompt Column SYSTEM_PARAMETER_CD;
ALTER TABLE PSP_SYSTEM_PARAMETER
MODIFY(SYSTEM_PARAMETER_CD VARCHAR2(256 CHAR));


Prompt Column OVERRIDE_CUTOFF_TIME;
ALTER TABLE PSP_SECOND_OFFLOAD
MODIFY(OVERRIDE_CUTOFF_TIME VARCHAR2(16 CHAR));


Prompt Column NAME;
ALTER TABLE PSP_OFFERING_SVCCHG_GRP
MODIFY(NAME VARCHAR2(100 CHAR));


Prompt Column DESCRIPTION;
ALTER TABLE PSP_OFFERING_SVCCHG_GRP
MODIFY(DESCRIPTION VARCHAR2(256 CHAR));


Prompt Column S_K_U;
ALTER TABLE PSP_OFFERING_SVCCHG
MODIFY(S_K_U VARCHAR2(40 CHAR));


Prompt Column ACCOUNT;
ALTER TABLE PSP_GEMS_LEDGER_POSTING_RULE
MODIFY(ACCOUNT VARCHAR2(80 CHAR));


Prompt Column COMPANY;
ALTER TABLE PSP_GEMS_LEDGER_POSTING_RULE
MODIFY(COMPANY VARCHAR2(16 CHAR));


Prompt Column DEPARTMENT;
ALTER TABLE PSP_GEMS_LEDGER_POSTING_RULE
MODIFY(DEPARTMENT VARCHAR2(16 CHAR));


Prompt Column GROUP_CODE;
ALTER TABLE PSP_GEMS_LEDGER_POSTING_RULE
MODIFY(GROUP_CODE VARCHAR2(16 CHAR));


Prompt Column INTER_COMPANY;
ALTER TABLE PSP_GEMS_LEDGER_POSTING_RULE
MODIFY(INTER_COMPANY VARCHAR2(16 CHAR));


Prompt Column ROLE_ID;
ALTER TABLE PSP_AUTH_ROLE
MODIFY(ROLE_ID VARCHAR2(40 CHAR));


Prompt Column NAME;
ALTER TABLE PSP_AUTH_ROLE
MODIFY(NAME VARCHAR2(100 CHAR));


Prompt Column DESCRIPTION;
ALTER TABLE PSP_AUTH_ROLE
MODIFY(DESCRIPTION VARCHAR2(256 CHAR));


Prompt Column DESCRIPTION;
ALTER TABLE PSP_SERVICE_SUB_STATUS
MODIFY(DESCRIPTION VARCHAR2(500 CHAR));


Prompt Column QB_INFO_APP_VERSION;
ALTER TABLE PSP_COMPANY
MODIFY(QB_INFO_APP_VERSION VARCHAR2(100 CHAR));


Prompt Column QUICKBOOKS_INFO_APPLICATION_ID;
ALTER TABLE PSP_COMPANY
MODIFY(QUICKBOOKS_INFO_APPLICATION_ID VARCHAR2(100 CHAR));


Prompt Column QUICKBOOKS_INFO_LICENSE_NUMBER;
ALTER TABLE PSP_COMPANY
MODIFY(QUICKBOOKS_INFO_LICENSE_NUMBER VARCHAR2(100 CHAR));


Prompt Column QB_INFO_COA_FEE_ACC_NAME;
ALTER TABLE PSP_COMPANY
MODIFY(QB_INFO_COA_FEE_ACC_NAME VARCHAR2(100 CHAR));


Prompt Column QB_INFO_COA_SALES_TAX_ACC_NAME;
ALTER TABLE PSP_COMPANY
MODIFY(QB_INFO_COA_SALES_TAX_ACC_NAME VARCHAR2(100 CHAR));


Prompt Column QUICKBOOKS_INFO_TAX_TABLE_ID;
ALTER TABLE PSP_COMPANY
MODIFY(QUICKBOOKS_INFO_TAX_TABLE_ID VARCHAR2(100 CHAR));


Prompt Column AGREEMENT_INFO_NAME;
ALTER TABLE PSP_COMPANY
MODIFY(AGREEMENT_INFO_NAME VARCHAR2(100 CHAR));


Prompt Column AGREEMENT_INFO_SERVICE_TYPE;
ALTER TABLE PSP_COMPANY
MODIFY(AGREEMENT_INFO_SERVICE_TYPE VARCHAR2(100 CHAR));


Prompt Column AGREE_INFO_SUB_NBR;
ALTER TABLE PSP_COMPANY
MODIFY(AGREE_INFO_SUB_NBR VARCHAR2(100 CHAR));


Prompt Column AGREE_INFO_SOURCE_ID;
ALTER TABLE PSP_COMPANY
MODIFY(AGREE_INFO_SOURCE_ID VARCHAR2(100 CHAR));


Prompt Column AGREEMENT_INFO_SERVICE_KEY;
ALTER TABLE PSP_COMPANY
MODIFY(AGREEMENT_INFO_SERVICE_KEY VARCHAR2(100 CHAR));


Prompt Column AGREE_INFO_AGREE_SUB_TYPE;
ALTER TABLE PSP_COMPANY
MODIFY(AGREE_INFO_AGREE_SUB_TYPE VARCHAR2(40 CHAR));


Prompt Column DESCRIPTION;
ALTER TABLE PSP_SOURCE_SYSTEM_TRANSMISSION
MODIFY(DESCRIPTION VARCHAR2(256 CHAR));


Prompt Column TRANSMISSION_IDENTIFIER;
ALTER TABLE PSP_SOURCE_SYSTEM_TRANSMISSION
MODIFY(TRANSMISSION_IDENTIFIER VARCHAR2(40 CHAR));


Prompt Column CLASS_NAME;
ALTER TABLE PSP_PROPERTY_AUDIT
MODIFY(CLASS_NAME VARCHAR2(100 CHAR));


Prompt Column PROPERTY_NAME;
ALTER TABLE PSP_PROPERTY_AUDIT
MODIFY(PROPERTY_NAME VARCHAR2(100 CHAR));


Prompt Column OBJECT_IDENTIFIER;
ALTER TABLE PSP_PROPERTY_AUDIT
MODIFY(OBJECT_IDENTIFIER VARCHAR2(40 CHAR));


Prompt Column USER_ID;
ALTER TABLE PSP_PROPERTY_AUDIT
MODIFY(USER_ID VARCHAR2(100 CHAR));


Prompt Column REPORTING_PERIOD;
ALTER TABLE PSP_GEMS_MONTHLY_BALANCE
MODIFY(REPORTING_PERIOD VARCHAR2(40 CHAR));


Prompt Column SOURCE_ID;
ALTER TABLE PSP_COMPANY_EVENT
MODIFY(SOURCE_ID VARCHAR2(100 CHAR));


Prompt Column NOTES;
ALTER TABLE PSP_ASSIGNED_DEPOSIT_FREQUENCY
MODIFY(NOTES VARCHAR2(256 CHAR));


Prompt Column SOURCE_CONTACT_ID;
ALTER TABLE PSP_CONTACT
MODIFY(SOURCE_CONTACT_ID VARCHAR2(300 CHAR));


Prompt Column TITLE;
ALTER TABLE PSP_CONTACT
MODIFY(TITLE VARCHAR2(20 CHAR));


Prompt Column TITLE_SUFFIX;
ALTER TABLE PSP_CONTACT
MODIFY(TITLE_SUFFIX VARCHAR2(20 CHAR));


Prompt Column JOB_TITLE;
ALTER TABLE PSP_CONTACT
MODIFY(JOB_TITLE VARCHAR2(80 CHAR));


Prompt Column FAX;
ALTER TABLE PSP_CONTACT
MODIFY(FAX VARCHAR2(20 CHAR));


Prompt Column SECOND_PHONE;
ALTER TABLE PSP_CONTACT
MODIFY(SECOND_PHONE VARCHAR2(20 CHAR));


Prompt Column SOURCE_BANK_ACCOUNT_NAME;
ALTER TABLE PSP_COMPANY_BANK_ACCOUNT
MODIFY(SOURCE_BANK_ACCOUNT_NAME VARCHAR2(100 CHAR));


Prompt Column TRACE_NUMBER;
ALTER TABLE PSP_ENTRY_DETAIL_RECORD
MODIFY(TRACE_NUMBER VARCHAR2(20 CHAR));


Prompt Column RECORD_DATA;
ALTER TABLE PSP_ENTRY_DETAIL_RECORD
MODIFY(RECORD_DATA VARCHAR2(250 CHAR));


Prompt Column VALUE;
ALTER TABLE PSP_COMPANY_EVENT_DETAIL
MODIFY(VALUE VARCHAR2(256 CHAR));


Prompt Column ITEM_NAME;
ALTER TABLE PSP_BILLING_DETAIL
MODIFY(ITEM_NAME VARCHAR2(100 CHAR));


Prompt Column ITEM_SKU;
ALTER TABLE PSP_BILLING_DETAIL
MODIFY(ITEM_SKU VARCHAR2(40 CHAR));


Prompt Column OFFER_CD;
ALTER TABLE PSP_BILLING_DETAIL
MODIFY(OFFER_CD VARCHAR2(40 CHAR));


Prompt Column OFFER_NAME;
ALTER TABLE PSP_BILLING_DETAIL
MODIFY(OFFER_NAME VARCHAR2(100 CHAR));


Prompt Column TAX_JURISDICTION;
ALTER TABLE PSP_BILLING_DETAIL
MODIFY(TAX_JURISDICTION VARCHAR2(16 CHAR));


Prompt Column SKU;
ALTER TABLE PSP_FINANCIAL_TRANSACTION
MODIFY(SKU VARCHAR2(40 CHAR));


 PROMPT finishedDBUpgradeFrom_1.9.9.17_To_1.9.9.18.sql