--
-- This script will be executed AFTER the automatically generated
-- C:\dev\psp\main\pse\domain\src\main\model\DBUpgradeFrom_1.9.9.2_To_1.9.9.3.sql
--
-- Developers can hand code logic here for data migration purposes
--
