--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--                                                                      --
-- Please review the script before using it to make sure it won't       --
-- cause any unacceptable data loss.                                    --
--                                                                      --
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL
-- PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL
ALTER TABLE PSP_PAYROLL_RUN
 DROP CONSTRAINT PSP_PAYROLL_RUN_FK3;

Prompt drop Index PSP_PAYROLL_RUN_FK3;
DROP INDEX PSP_PAYROLL_RUN_FK3;

Prompt Column QB_INFO_AS400_PAYROLL_COUNT;
ALTER TABLE PSP_COMPANY
 ADD (QB_INFO_AS400_PAYROLL_COUNT  NUMBER(19));

Prompt Trigger PSP_COMPANY_AT;
Prompt Trigger PSP_COMPANY_AT;
--
-- PSP_COMPANY_AT  (Trigger)
--
CREATE OR REPLACE TRIGGER PSP_COMPANY_AT
AFTER INSERT OR UPDATE ON PSP_COMPANY
FOR EACH ROW
DECLARE
  v_company_fk VARCHAR2(255);
  v_creator_id VARCHAR2(30);
  v_modifier_id VARCHAR2(30);
BEGIN

SELECT :NEW.CREATOR_ID INTO v_creator_id FROM DUAL;
SELECT :NEW.MODIFIER_ID INTO v_modifier_id FROM DUAL;

  IF (UPDATING) THEN
     IF ((:NEW.FUNDING_MODEL_FK <> :OLD.FUNDING_MODEL_FK) OR
         (:NEW.FUNDING_MODEL_FK IS NULL AND :OLD.FUNDING_MODEL_FK IS NOT NULL) OR
         (:NEW.FUNDING_MODEL_FK IS NOT NULL AND :OLD.FUNDING_MODEL_FK IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYSTIMESTAMP, SYSTIMESTAMP, 'Company', 'FundingModel', TO_CHAR(:OLD.FUNDING_MODEL_FK ), TO_CHAR(:NEW.FUNDING_MODEL_FK ), :NEW.COMPANY_SEQ, v_modifier_id, SYSTIMESTAMP, v_company_fk);
         END IF;
     END IF;

     IF ((:NEW.NOTIFICATION_EMAIL <> :OLD.NOTIFICATION_EMAIL) OR
         (:NEW.NOTIFICATION_EMAIL IS NULL AND :OLD.NOTIFICATION_EMAIL IS NOT NULL) OR
         (:NEW.NOTIFICATION_EMAIL IS NOT NULL AND :OLD.NOTIFICATION_EMAIL IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYSTIMESTAMP, SYSTIMESTAMP, 'Company', 'NotificationEmail', TO_CHAR(:OLD.NOTIFICATION_EMAIL ), TO_CHAR(:NEW.NOTIFICATION_EMAIL ), :NEW.COMPANY_SEQ, v_modifier_id, SYSTIMESTAMP, v_company_fk);
         END IF;
     END IF;

     IF ((:NEW.FED_TAX_ID <> :OLD.FED_TAX_ID) OR
         (:NEW.FED_TAX_ID IS NULL AND :OLD.FED_TAX_ID IS NOT NULL) OR
         (:NEW.FED_TAX_ID IS NOT NULL AND :OLD.FED_TAX_ID IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYSTIMESTAMP, SYSTIMESTAMP, 'Company', 'FedTaxId', TO_CHAR(:OLD.FED_TAX_ID ), TO_CHAR(:NEW.FED_TAX_ID ), :NEW.COMPANY_SEQ, v_modifier_id, SYSTIMESTAMP, v_company_fk);
         END IF;
     END IF;

     IF ((:NEW.LEGAL_NAME <> :OLD.LEGAL_NAME) OR
         (:NEW.LEGAL_NAME IS NULL AND :OLD.LEGAL_NAME IS NOT NULL) OR
         (:NEW.LEGAL_NAME IS NOT NULL AND :OLD.LEGAL_NAME IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYSTIMESTAMP, SYSTIMESTAMP, 'Company', 'LegalName', TO_CHAR(:OLD.LEGAL_NAME ), TO_CHAR(:NEW.LEGAL_NAME ), :NEW.COMPANY_SEQ, v_modifier_id, SYSTIMESTAMP, v_company_fk);
         END IF;
     END IF;

     IF ((:NEW.QB_INFO_APP_VERSION <> :OLD.QB_INFO_APP_VERSION) OR
         (:NEW.QB_INFO_APP_VERSION IS NULL AND :OLD.QB_INFO_APP_VERSION IS NOT NULL) OR
         (:NEW.QB_INFO_APP_VERSION IS NOT NULL AND :OLD.QB_INFO_APP_VERSION IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYSTIMESTAMP, SYSTIMESTAMP, 'Company', 'QuickbooksInfo.ApplicationVersion', TO_CHAR(:OLD.QB_INFO_APP_VERSION ), TO_CHAR(:NEW.QB_INFO_APP_VERSION ), :NEW.COMPANY_SEQ, v_modifier_id, SYSTIMESTAMP, v_company_fk);
         END IF;
     END IF;

     IF ((:NEW.QUICKBOOKS_INFO_APPLICATION_ID <> :OLD.QUICKBOOKS_INFO_APPLICATION_ID) OR
         (:NEW.QUICKBOOKS_INFO_APPLICATION_ID IS NULL AND :OLD.QUICKBOOKS_INFO_APPLICATION_ID IS NOT NULL) OR
         (:NEW.QUICKBOOKS_INFO_APPLICATION_ID IS NOT NULL AND :OLD.QUICKBOOKS_INFO_APPLICATION_ID IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYSTIMESTAMP, SYSTIMESTAMP, 'Company', 'QuickbooksInfo.ApplicationId', TO_CHAR(:OLD.QUICKBOOKS_INFO_APPLICATION_ID ), TO_CHAR(:NEW.QUICKBOOKS_INFO_APPLICATION_ID ), :NEW.COMPANY_SEQ, v_modifier_id, SYSTIMESTAMP, v_company_fk);
         END IF;
     END IF;

     IF ((:NEW.QUICKBOOKS_INFO_LICENSE_NUMBER <> :OLD.QUICKBOOKS_INFO_LICENSE_NUMBER) OR
         (:NEW.QUICKBOOKS_INFO_LICENSE_NUMBER IS NULL AND :OLD.QUICKBOOKS_INFO_LICENSE_NUMBER IS NOT NULL) OR
         (:NEW.QUICKBOOKS_INFO_LICENSE_NUMBER IS NOT NULL AND :OLD.QUICKBOOKS_INFO_LICENSE_NUMBER IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYSTIMESTAMP, SYSTIMESTAMP, 'Company', 'QuickbooksInfo.LicenseNumber', TO_CHAR(:OLD.QUICKBOOKS_INFO_LICENSE_NUMBER ), TO_CHAR(:NEW.QUICKBOOKS_INFO_LICENSE_NUMBER ), :NEW.COMPANY_SEQ, v_modifier_id, SYSTIMESTAMP, v_company_fk);
         END IF;
     END IF;

     IF ((:NEW.QB_INFO_COA_FEE_ACC_NAME <> :OLD.QB_INFO_COA_FEE_ACC_NAME) OR
         (:NEW.QB_INFO_COA_FEE_ACC_NAME IS NULL AND :OLD.QB_INFO_COA_FEE_ACC_NAME IS NOT NULL) OR
         (:NEW.QB_INFO_COA_FEE_ACC_NAME IS NOT NULL AND :OLD.QB_INFO_COA_FEE_ACC_NAME IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYSTIMESTAMP, SYSTIMESTAMP, 'Company', 'QuickbooksInfo.CoaFeeAccountName', TO_CHAR(:OLD.QB_INFO_COA_FEE_ACC_NAME ), TO_CHAR(:NEW.QB_INFO_COA_FEE_ACC_NAME ), :NEW.COMPANY_SEQ, v_modifier_id, SYSTIMESTAMP, v_company_fk);
         END IF;
     END IF;

     IF ((:NEW.QB_INFO_COA_SALES_TAX_ACC_NAME <> :OLD.QB_INFO_COA_SALES_TAX_ACC_NAME) OR
         (:NEW.QB_INFO_COA_SALES_TAX_ACC_NAME IS NULL AND :OLD.QB_INFO_COA_SALES_TAX_ACC_NAME IS NOT NULL) OR
         (:NEW.QB_INFO_COA_SALES_TAX_ACC_NAME IS NOT NULL AND :OLD.QB_INFO_COA_SALES_TAX_ACC_NAME IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYSTIMESTAMP, SYSTIMESTAMP, 'Company', 'QuickbooksInfo.CoaSalesTaxAccountName', TO_CHAR(:OLD.QB_INFO_COA_SALES_TAX_ACC_NAME ), TO_CHAR(:NEW.QB_INFO_COA_SALES_TAX_ACC_NAME ), :NEW.COMPANY_SEQ, v_modifier_id, SYSTIMESTAMP, v_company_fk);
         END IF;
     END IF;

     IF ((:NEW.QUICKBOOKS_INFO_TAX_TABLE_ID <> :OLD.QUICKBOOKS_INFO_TAX_TABLE_ID) OR
         (:NEW.QUICKBOOKS_INFO_TAX_TABLE_ID IS NULL AND :OLD.QUICKBOOKS_INFO_TAX_TABLE_ID IS NOT NULL) OR
         (:NEW.QUICKBOOKS_INFO_TAX_TABLE_ID IS NOT NULL AND :OLD.QUICKBOOKS_INFO_TAX_TABLE_ID IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYSTIMESTAMP, SYSTIMESTAMP, 'Company', 'QuickbooksInfo.TaxTableId', TO_CHAR(:OLD.QUICKBOOKS_INFO_TAX_TABLE_ID ), TO_CHAR(:NEW.QUICKBOOKS_INFO_TAX_TABLE_ID ), :NEW.COMPANY_SEQ, v_modifier_id, SYSTIMESTAMP, v_company_fk);
         END IF;
     END IF;

     IF ((:NEW.QB_INFO_AS400_PAYROLL_COUNT <> :OLD.QB_INFO_AS400_PAYROLL_COUNT) OR
         (:NEW.QB_INFO_AS400_PAYROLL_COUNT IS NULL AND :OLD.QB_INFO_AS400_PAYROLL_COUNT IS NOT NULL) OR
         (:NEW.QB_INFO_AS400_PAYROLL_COUNT IS NOT NULL AND :OLD.QB_INFO_AS400_PAYROLL_COUNT IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYSTIMESTAMP, SYSTIMESTAMP, 'Company', 'QuickbooksInfo.AS400PayrollCount', TO_CHAR(:OLD.QB_INFO_AS400_PAYROLL_COUNT ), TO_CHAR(:NEW.QB_INFO_AS400_PAYROLL_COUNT ), :NEW.COMPANY_SEQ, v_modifier_id, SYSTIMESTAMP, v_company_fk);
         END IF;
     END IF;

     IF ((:NEW.AGREE_INFO_AGREE_CREATE_DATE <> :OLD.AGREE_INFO_AGREE_CREATE_DATE) OR
         (:NEW.AGREE_INFO_AGREE_CREATE_DATE IS NULL AND :OLD.AGREE_INFO_AGREE_CREATE_DATE IS NOT NULL) OR
         (:NEW.AGREE_INFO_AGREE_CREATE_DATE IS NOT NULL AND :OLD.AGREE_INFO_AGREE_CREATE_DATE IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYSTIMESTAMP, SYSTIMESTAMP, 'Company', 'AgreementInfo.AgreementCreateDate', TO_CHAR(:OLD.AGREE_INFO_AGREE_CREATE_DATE ), TO_CHAR(:NEW.AGREE_INFO_AGREE_CREATE_DATE ), :NEW.COMPANY_SEQ, v_modifier_id, SYSTIMESTAMP, v_company_fk);
         END IF;
     END IF;

     IF ((:NEW.AGREEMENT_INFO_NAME <> :OLD.AGREEMENT_INFO_NAME) OR
         (:NEW.AGREEMENT_INFO_NAME IS NULL AND :OLD.AGREEMENT_INFO_NAME IS NOT NULL) OR
         (:NEW.AGREEMENT_INFO_NAME IS NOT NULL AND :OLD.AGREEMENT_INFO_NAME IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYSTIMESTAMP, SYSTIMESTAMP, 'Company', 'AgreementInfo.Name', TO_CHAR(:OLD.AGREEMENT_INFO_NAME ), TO_CHAR(:NEW.AGREEMENT_INFO_NAME ), :NEW.COMPANY_SEQ, v_modifier_id, SYSTIMESTAMP, v_company_fk);
         END IF;
     END IF;

     IF ((:NEW.AGREEMENT_INFO_SERVICE_TYPE <> :OLD.AGREEMENT_INFO_SERVICE_TYPE) OR
         (:NEW.AGREEMENT_INFO_SERVICE_TYPE IS NULL AND :OLD.AGREEMENT_INFO_SERVICE_TYPE IS NOT NULL) OR
         (:NEW.AGREEMENT_INFO_SERVICE_TYPE IS NOT NULL AND :OLD.AGREEMENT_INFO_SERVICE_TYPE IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYSTIMESTAMP, SYSTIMESTAMP, 'Company', 'AgreementInfo.ServiceType', TO_CHAR(:OLD.AGREEMENT_INFO_SERVICE_TYPE ), TO_CHAR(:NEW.AGREEMENT_INFO_SERVICE_TYPE ), :NEW.COMPANY_SEQ, v_modifier_id, SYSTIMESTAMP, v_company_fk);
         END IF;
     END IF;

     IF ((:NEW.AGREE_INFO_SUB_NBR <> :OLD.AGREE_INFO_SUB_NBR) OR
         (:NEW.AGREE_INFO_SUB_NBR IS NULL AND :OLD.AGREE_INFO_SUB_NBR IS NOT NULL) OR
         (:NEW.AGREE_INFO_SUB_NBR IS NOT NULL AND :OLD.AGREE_INFO_SUB_NBR IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYSTIMESTAMP, SYSTIMESTAMP, 'Company', 'AgreementInfo.SubscriptionNumber', TO_CHAR(:OLD.AGREE_INFO_SUB_NBR ), TO_CHAR(:NEW.AGREE_INFO_SUB_NBR ), :NEW.COMPANY_SEQ, v_modifier_id, SYSTIMESTAMP, v_company_fk);
         END IF;
     END IF;

     IF ((:NEW.AGREE_INFO_SOURCE_ID <> :OLD.AGREE_INFO_SOURCE_ID) OR
         (:NEW.AGREE_INFO_SOURCE_ID IS NULL AND :OLD.AGREE_INFO_SOURCE_ID IS NOT NULL) OR
         (:NEW.AGREE_INFO_SOURCE_ID IS NOT NULL AND :OLD.AGREE_INFO_SOURCE_ID IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYSTIMESTAMP, SYSTIMESTAMP, 'Company', 'AgreementInfo.SourceAgreementId', TO_CHAR(:OLD.AGREE_INFO_SOURCE_ID ), TO_CHAR(:NEW.AGREE_INFO_SOURCE_ID ), :NEW.COMPANY_SEQ, v_modifier_id, SYSTIMESTAMP, v_company_fk);
         END IF;
     END IF;

     IF ((:NEW.AGREEMENT_INFO_SERVICE_KEY <> :OLD.AGREEMENT_INFO_SERVICE_KEY) OR
         (:NEW.AGREEMENT_INFO_SERVICE_KEY IS NULL AND :OLD.AGREEMENT_INFO_SERVICE_KEY IS NOT NULL) OR
         (:NEW.AGREEMENT_INFO_SERVICE_KEY IS NOT NULL AND :OLD.AGREEMENT_INFO_SERVICE_KEY IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYSTIMESTAMP, SYSTIMESTAMP, 'Company', 'AgreementInfo.ServiceKey', TO_CHAR(:OLD.AGREEMENT_INFO_SERVICE_KEY ), TO_CHAR(:NEW.AGREEMENT_INFO_SERVICE_KEY ), :NEW.COMPANY_SEQ, v_modifier_id, SYSTIMESTAMP, v_company_fk);
         END IF;
     END IF;

     IF ((:NEW.AGREE_INFO_AGREE_SUB_TYPE <> :OLD.AGREE_INFO_AGREE_SUB_TYPE) OR
         (:NEW.AGREE_INFO_AGREE_SUB_TYPE IS NULL AND :OLD.AGREE_INFO_AGREE_SUB_TYPE IS NOT NULL) OR
         (:NEW.AGREE_INFO_AGREE_SUB_TYPE IS NOT NULL AND :OLD.AGREE_INFO_AGREE_SUB_TYPE IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYSTIMESTAMP, SYSTIMESTAMP, 'Company', 'AgreementInfo.AgreementSubType', TO_CHAR(:OLD.AGREE_INFO_AGREE_SUB_TYPE ), TO_CHAR(:NEW.AGREE_INFO_AGREE_SUB_TYPE ), :NEW.COMPANY_SEQ, v_modifier_id, SYSTIMESTAMP, v_company_fk);
         END IF;
     END IF;

  END IF;
  IF (INSERTING) THEN
     BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYSTIMESTAMP, SYSTIMESTAMP, 'Company', 'FundingModel', null, TO_CHAR(:NEW.FUNDING_MODEL_FK ), :NEW.COMPANY_SEQ, v_creator_id, SYSTIMESTAMP, v_company_fk);
         END IF;

     BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYSTIMESTAMP, SYSTIMESTAMP, 'Company', 'NotificationEmail', null, TO_CHAR(:NEW.NOTIFICATION_EMAIL ), :NEW.COMPANY_SEQ, v_creator_id, SYSTIMESTAMP, v_company_fk);
         END IF;

     BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYSTIMESTAMP, SYSTIMESTAMP, 'Company', 'FedTaxId', null, TO_CHAR(:NEW.FED_TAX_ID ), :NEW.COMPANY_SEQ, v_creator_id, SYSTIMESTAMP, v_company_fk);
         END IF;

     BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYSTIMESTAMP, SYSTIMESTAMP, 'Company', 'LegalName', null, TO_CHAR(:NEW.LEGAL_NAME ), :NEW.COMPANY_SEQ, v_creator_id, SYSTIMESTAMP, v_company_fk);
         END IF;

     BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYSTIMESTAMP, SYSTIMESTAMP, 'Company', 'QuickbooksInfo.ApplicationVersion', null, TO_CHAR(:NEW.QB_INFO_APP_VERSION ), :NEW.COMPANY_SEQ, v_creator_id, SYSTIMESTAMP, v_company_fk);
         END IF;

     BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYSTIMESTAMP, SYSTIMESTAMP, 'Company', 'QuickbooksInfo.ApplicationId', null, TO_CHAR(:NEW.QUICKBOOKS_INFO_APPLICATION_ID ), :NEW.COMPANY_SEQ, v_creator_id, SYSTIMESTAMP, v_company_fk);
         END IF;

     BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYSTIMESTAMP, SYSTIMESTAMP, 'Company', 'QuickbooksInfo.LicenseNumber', null, TO_CHAR(:NEW.QUICKBOOKS_INFO_LICENSE_NUMBER ), :NEW.COMPANY_SEQ, v_creator_id, SYSTIMESTAMP, v_company_fk);
         END IF;

     BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYSTIMESTAMP, SYSTIMESTAMP, 'Company', 'QuickbooksInfo.CoaFeeAccountName', null, TO_CHAR(:NEW.QB_INFO_COA_FEE_ACC_NAME ), :NEW.COMPANY_SEQ, v_creator_id, SYSTIMESTAMP, v_company_fk);
         END IF;

     BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYSTIMESTAMP, SYSTIMESTAMP, 'Company', 'QuickbooksInfo.CoaSalesTaxAccountName', null, TO_CHAR(:NEW.QB_INFO_COA_SALES_TAX_ACC_NAME ), :NEW.COMPANY_SEQ, v_creator_id, SYSTIMESTAMP, v_company_fk);
         END IF;

     BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYSTIMESTAMP, SYSTIMESTAMP, 'Company', 'QuickbooksInfo.TaxTableId', null, TO_CHAR(:NEW.QUICKBOOKS_INFO_TAX_TABLE_ID ), :NEW.COMPANY_SEQ, v_creator_id, SYSTIMESTAMP, v_company_fk);
         END IF;

     BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYSTIMESTAMP, SYSTIMESTAMP, 'Company', 'QuickbooksInfo.AS400PayrollCount', null, TO_CHAR(:NEW.QB_INFO_AS400_PAYROLL_COUNT ), :NEW.COMPANY_SEQ, v_creator_id, SYSTIMESTAMP, v_company_fk);
         END IF;

     BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYSTIMESTAMP, SYSTIMESTAMP, 'Company', 'AgreementInfo.AgreementCreateDate', null, TO_CHAR(:NEW.AGREE_INFO_AGREE_CREATE_DATE ), :NEW.COMPANY_SEQ, v_creator_id, SYSTIMESTAMP, v_company_fk);
         END IF;

     BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYSTIMESTAMP, SYSTIMESTAMP, 'Company', 'AgreementInfo.Name', null, TO_CHAR(:NEW.AGREEMENT_INFO_NAME ), :NEW.COMPANY_SEQ, v_creator_id, SYSTIMESTAMP, v_company_fk);
         END IF;

     BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYSTIMESTAMP, SYSTIMESTAMP, 'Company', 'AgreementInfo.ServiceType', null, TO_CHAR(:NEW.AGREEMENT_INFO_SERVICE_TYPE ), :NEW.COMPANY_SEQ, v_creator_id, SYSTIMESTAMP, v_company_fk);
         END IF;

     BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYSTIMESTAMP, SYSTIMESTAMP, 'Company', 'AgreementInfo.SubscriptionNumber', null, TO_CHAR(:NEW.AGREE_INFO_SUB_NBR ), :NEW.COMPANY_SEQ, v_creator_id, SYSTIMESTAMP, v_company_fk);
         END IF;

     BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYSTIMESTAMP, SYSTIMESTAMP, 'Company', 'AgreementInfo.SourceAgreementId', null, TO_CHAR(:NEW.AGREE_INFO_SOURCE_ID ), :NEW.COMPANY_SEQ, v_creator_id, SYSTIMESTAMP, v_company_fk);
         END IF;

     BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYSTIMESTAMP, SYSTIMESTAMP, 'Company', 'AgreementInfo.ServiceKey', null, TO_CHAR(:NEW.AGREEMENT_INFO_SERVICE_KEY ), :NEW.COMPANY_SEQ, v_creator_id, SYSTIMESTAMP, v_company_fk);
         END IF;

     BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYSTIMESTAMP, SYSTIMESTAMP, 'Company', 'AgreementInfo.AgreementSubType', null, TO_CHAR(:NEW.AGREE_INFO_AGREE_SUB_TYPE ), :NEW.COMPANY_SEQ, v_creator_id, SYSTIMESTAMP, v_company_fk);
         END IF;

  END IF;
END;
/
SHOW ERRORS;

Prompt Column SOURCE_SYSTEM_TRANSMISSION_FK;
-- Column to be dropped is part of a multi-column constraint.
-- Oracle requires that the constraint be dropped first.
-- There may be another statement later in the script that tries to drop
-- the constraint again.  Errors produced by it can be ignored.
ALTER TABLE PSP_PAYROLL_RUN DROP CONSTRAINT PSP_PAYROLL_RUN_FK2;
ALTER TABLE PSP_PAYROLL_RUN DROP COLUMN SOURCE_SYSTEM_TRANSMISSION_FK;

Prompt Table PSP_TRANSMISSION_PAYROLL_RUN;
--
-- PSP_TRANSMISSION_PAYROLL_RUN  (Table)
--
CREATE TABLE PSP_TRANSMISSION_PAYROLL_RUN
(
  TRANSMISSION_PAYROLL_RUN_SEQ   VARCHAR2(255 CHAR) NOT NULL,
  VERSION                        NUMBER(19)     NOT NULL,
  CREATOR_ID                     VARCHAR2(30 CHAR),
  CREATED_DATE                   TIMESTAMP(6)   NOT NULL,
  MODIFIER_ID                    VARCHAR2(30 CHAR),
  MODIFIED_DATE                  TIMESTAMP(6)   NOT NULL,
  REALM_ID                       NUMBER(19)     DEFAULT -1                    NOT NULL,
  PAYROLL_PROCESS                VARCHAR2(255 CHAR),
  SOURCE_SYSTEM_TRANSMISSION_FK  VARCHAR2(255 CHAR) NOT NULL,
  PAYROLL_RUN_FK                 VARCHAR2(255 CHAR) NOT NULL
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

Prompt Index PSP_TRANSMISSIONPAYROLLRUN_FK2;
--
-- PSP_TRANSMISSIONPAYROLLRUN_FK2  (Index)
--
CREATE INDEX PSP_TRANSMISSIONPAYROLLRUN_FK2 ON PSP_TRANSMISSION_PAYROLL_RUN
(PAYROLL_RUN_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt Index PSP_TRANSMISSIONPAYROLLRUN_FK1;
--
-- PSP_TRANSMISSIONPAYROLLRUN_FK1  (Index)
--
CREATE INDEX PSP_TRANSMISSIONPAYROLLRUN_FK1 ON PSP_TRANSMISSION_PAYROLL_RUN
(SOURCE_SYSTEM_TRANSMISSION_FK, REALM_ID)
LOGGING
NOPARALLEL;

ALTER TABLE PSP_TRANSMISSION_PAYROLL_RUN
 ADD CONSTRAINT C_PSP_TRANSMISSION_PAYROLL0
 CHECK (PAYROLL_PROCESS IN('SubmitPayroll', 'ReverseTransaction', 'RecallTransaction', 'UpdateTransactionVoidFlag', 'CancelTransaction'));

ALTER TABLE PSP_TRANSMISSION_PAYROLL_RUN
 ADD PRIMARY KEY
 (TRANSMISSION_PAYROLL_RUN_SEQ, REALM_ID);

Prompt Index PSP_PAYROLL_RUN_FK2;
Prompt drop Index PSP_PAYROLL_RUN_FK2;
DROP INDEX PSP_PAYROLL_RUN_FK2;
Prompt Index PSP_PAYROLL_RUN_FK2;
--
-- PSP_PAYROLL_RUN_FK2  (Index)
--
CREATE INDEX PSP_PAYROLL_RUN_FK2 ON PSP_PAYROLL_RUN
(COMPANY_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt Constraint PSP_PAYROLL_RUN_FK2;
ALTER TABLE PSP_PAYROLL_RUN
 DROP CONSTRAINT PSP_PAYROLL_RUN_FK2;
ALTER TABLE PSP_PAYROLL_RUN
 ADD CONSTRAINT PSP_PAYROLL_RUN_FK2
 FOREIGN KEY (COMPANY_FK, REALM_ID)
 REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

ALTER TABLE PSP_TRANSMISSION_PAYROLL_RUN
 ADD CONSTRAINT PSP_TRANSMISSIONPAYROLLRUN_FK1
 FOREIGN KEY (SOURCE_SYSTEM_TRANSMISSION_FK, REALM_ID)
 REFERENCES PSP_SOURCE_SYSTEM_TRANSMISSION (SOURCE_SYSTEM_TRANSMISSION_SEQ,REALM_ID);

ALTER TABLE PSP_TRANSMISSION_PAYROLL_RUN
 ADD CONSTRAINT PSP_TRANSMISSIONPAYROLLRUN_FK2
 FOREIGN KEY (PAYROLL_RUN_FK, REALM_ID)
 REFERENCES PSP_PAYROLL_RUN (PAYROLL_RUN_SEQ,REALM_ID);

 PROMPT finishedDBUpgradeFrom_1.9.9.1_To_1.9.9.2.sql