--
-- This script will be executed BEFORE the automatically generated
-- C:\dev\PSP\main\PSE\Domain\src\main\model\DBUpgradeFrom_2.0.0.17_To_2.0.0.18.sql
--
-- Developers can hand code logic here for data migration purposes
--
