--
-- This script will be executed BEFORE the automatically generated
-- C:\dev\psp\main\PSE\Domain\src\main\model\DBUpgradeFrom_1.0.0.0_To_1.1.0.0.sql
--
-- Developers can hand code logic here for data migration purposes
--
