--
-- This script will be executed BEFORE the automatically generated
-- C:\dev\PSP\rel-1.3\PSE\Domain\src\main\model\DBUpgrade_001.009.009.053.sql
--
-- Developers can hand code logic here for data migration purposes
--
