--
-- This script will be executed BEFORE the automatically generated
-- C:\dev\PSP\main\PSE\Domain\src\main\model\DBUpgradeFrom_1.9.9.44_To_2.0.0.0.sql
--
-- Developers can hand code logic here for data migration purposes
--
