--
-- This script will be executed AFTER the automatically generated
-- C:\dev\PSP\main\PSE\Domain\src\main\model\DBUpgradeFrom_1.9.9.39_To_1.9.9.40.sql
--
-- Developers can hand code logic here for data migration purposes
--
