--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--                                                                      --
-- Please review the script before using it to make sure it won't       --
-- cause any unacceptable data loss.                                    --
--                                                                      --
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
Prompt Trigger PSP_COMPANY_OFFER_AT;
Prompt Trigger PSP_COMPANY_OFFER_AT;
--
-- PSP_COMPANY_OFFER_AT  (Trigger) 
--
CREATE OR REPLACE TRIGGER PSP_COMPANY_OFFER_AT
AFTER INSERT OR UPDATE ON PSP_COMPANY_OFFER
FOR EACH ROW
DECLARE
  v_company_fk VARCHAR2(255);
  v_creator_id VARCHAR2(30);
  v_modifier_id VARCHAR2(30);
BEGIN

SELECT :NEW.CREATOR_ID INTO v_creator_id FROM DUAL;
SELECT :NEW.MODIFIER_ID INTO v_modifier_id FROM DUAL;

  IF (UPDATING) THEN
     IF (((:NEW.OFFER_FK <> :OLD.OFFER_FK) AND :NEW.OFFER_FK IS NOT NULL AND :OLD.OFFER_FK IS NOT NULL) OR
         (:NEW.OFFER_FK IS NULL AND :OLD.OFFER_FK IS NOT NULL) OR
         (:NEW.OFFER_FK IS NOT NULL AND :OLD.OFFER_FK IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'CompanyOffer', 'Offer', TO_CHAR(:OLD.OFFER_FK ), TO_CHAR(:NEW.OFFER_FK ), :NEW.COMPANY_OFFER_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

  END IF;
END;
/
SHOW ERRORS;


Prompt Trigger PSP_COMPANY_AT;
Prompt Trigger PSP_COMPANY_AT;
--
-- PSP_COMPANY_AT  (Trigger) 
--
CREATE OR REPLACE TRIGGER PSP_COMPANY_AT
AFTER INSERT OR UPDATE ON PSP_COMPANY
FOR EACH ROW
DECLARE
  v_company_fk VARCHAR2(255);
  v_creator_id VARCHAR2(30);
  v_modifier_id VARCHAR2(30);
BEGIN

SELECT :NEW.CREATOR_ID INTO v_creator_id FROM DUAL;
SELECT :NEW.MODIFIER_ID INTO v_modifier_id FROM DUAL;

  IF (UPDATING) THEN
     IF (((:NEW.FUNDING_MODEL_FK <> :OLD.FUNDING_MODEL_FK) AND :NEW.FUNDING_MODEL_FK IS NOT NULL AND :OLD.FUNDING_MODEL_FK IS NOT NULL) OR
         (:NEW.FUNDING_MODEL_FK IS NULL AND :OLD.FUNDING_MODEL_FK IS NOT NULL) OR
         (:NEW.FUNDING_MODEL_FK IS NOT NULL AND :OLD.FUNDING_MODEL_FK IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'Company', 'FundingModel', TO_CHAR(:OLD.FUNDING_MODEL_FK ), TO_CHAR(:NEW.FUNDING_MODEL_FK ), :NEW.COMPANY_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

     IF (((:NEW.NOTIFICATION_EMAIL <> :OLD.NOTIFICATION_EMAIL) AND :NEW.NOTIFICATION_EMAIL IS NOT NULL AND :OLD.NOTIFICATION_EMAIL IS NOT NULL) OR
         (:NEW.NOTIFICATION_EMAIL IS NULL AND :OLD.NOTIFICATION_EMAIL IS NOT NULL) OR
         (:NEW.NOTIFICATION_EMAIL IS NOT NULL AND :OLD.NOTIFICATION_EMAIL IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'Company', 'NotificationEmail', TO_CHAR(:OLD.NOTIFICATION_EMAIL ), TO_CHAR(:NEW.NOTIFICATION_EMAIL ), :NEW.COMPANY_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

     IF (((:NEW.FED_TAX_ID <> :OLD.FED_TAX_ID) AND :NEW.FED_TAX_ID IS NOT NULL AND :OLD.FED_TAX_ID IS NOT NULL) OR
         (:NEW.FED_TAX_ID IS NULL AND :OLD.FED_TAX_ID IS NOT NULL) OR
         (:NEW.FED_TAX_ID IS NOT NULL AND :OLD.FED_TAX_ID IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'Company', 'FedTaxId', TO_CHAR(:OLD.FED_TAX_ID ), TO_CHAR(:NEW.FED_TAX_ID ), :NEW.COMPANY_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

     IF (((:NEW.LEGAL_NAME <> :OLD.LEGAL_NAME) AND :NEW.LEGAL_NAME IS NOT NULL AND :OLD.LEGAL_NAME IS NOT NULL) OR
         (:NEW.LEGAL_NAME IS NULL AND :OLD.LEGAL_NAME IS NOT NULL) OR
         (:NEW.LEGAL_NAME IS NOT NULL AND :OLD.LEGAL_NAME IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'Company', 'LegalName', TO_CHAR(:OLD.LEGAL_NAME ), TO_CHAR(:NEW.LEGAL_NAME ), :NEW.COMPANY_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

     IF (((:NEW.QB_INFO_APP_VERSION <> :OLD.QB_INFO_APP_VERSION) AND :NEW.QB_INFO_APP_VERSION IS NOT NULL AND :OLD.QB_INFO_APP_VERSION IS NOT NULL) OR
         (:NEW.QB_INFO_APP_VERSION IS NULL AND :OLD.QB_INFO_APP_VERSION IS NOT NULL) OR
         (:NEW.QB_INFO_APP_VERSION IS NOT NULL AND :OLD.QB_INFO_APP_VERSION IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'Company', 'QuickbooksInfo.ApplicationVersion', TO_CHAR(:OLD.QB_INFO_APP_VERSION ), TO_CHAR(:NEW.QB_INFO_APP_VERSION ), :NEW.COMPANY_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

     IF (((:NEW.QUICKBOOKS_INFO_APPLICATION_ID <> :OLD.QUICKBOOKS_INFO_APPLICATION_ID) AND :NEW.QUICKBOOKS_INFO_APPLICATION_ID IS NOT NULL AND :OLD.QUICKBOOKS_INFO_APPLICATION_ID IS NOT NULL) OR
         (:NEW.QUICKBOOKS_INFO_APPLICATION_ID IS NULL AND :OLD.QUICKBOOKS_INFO_APPLICATION_ID IS NOT NULL) OR
         (:NEW.QUICKBOOKS_INFO_APPLICATION_ID IS NOT NULL AND :OLD.QUICKBOOKS_INFO_APPLICATION_ID IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'Company', 'QuickbooksInfo.ApplicationId', TO_CHAR(:OLD.QUICKBOOKS_INFO_APPLICATION_ID ), TO_CHAR(:NEW.QUICKBOOKS_INFO_APPLICATION_ID ), :NEW.COMPANY_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

     IF (((:NEW.QUICKBOOKS_INFO_LICENSE_NUMBER <> :OLD.QUICKBOOKS_INFO_LICENSE_NUMBER) AND :NEW.QUICKBOOKS_INFO_LICENSE_NUMBER IS NOT NULL AND :OLD.QUICKBOOKS_INFO_LICENSE_NUMBER IS NOT NULL) OR
         (:NEW.QUICKBOOKS_INFO_LICENSE_NUMBER IS NULL AND :OLD.QUICKBOOKS_INFO_LICENSE_NUMBER IS NOT NULL) OR
         (:NEW.QUICKBOOKS_INFO_LICENSE_NUMBER IS NOT NULL AND :OLD.QUICKBOOKS_INFO_LICENSE_NUMBER IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'Company', 'QuickbooksInfo.LicenseNumber', TO_CHAR(:OLD.QUICKBOOKS_INFO_LICENSE_NUMBER ), TO_CHAR(:NEW.QUICKBOOKS_INFO_LICENSE_NUMBER ), :NEW.COMPANY_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

     IF (((:NEW.QB_INFO_COA_FEE_ACC_NAME <> :OLD.QB_INFO_COA_FEE_ACC_NAME) AND :NEW.QB_INFO_COA_FEE_ACC_NAME IS NOT NULL AND :OLD.QB_INFO_COA_FEE_ACC_NAME IS NOT NULL) OR
         (:NEW.QB_INFO_COA_FEE_ACC_NAME IS NULL AND :OLD.QB_INFO_COA_FEE_ACC_NAME IS NOT NULL) OR
         (:NEW.QB_INFO_COA_FEE_ACC_NAME IS NOT NULL AND :OLD.QB_INFO_COA_FEE_ACC_NAME IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'Company', 'QuickbooksInfo.CoaFeeAccountName', TO_CHAR(:OLD.QB_INFO_COA_FEE_ACC_NAME ), TO_CHAR(:NEW.QB_INFO_COA_FEE_ACC_NAME ), :NEW.COMPANY_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

     IF (((:NEW.QB_INFO_COA_SALES_TAX_ACC_NAME <> :OLD.QB_INFO_COA_SALES_TAX_ACC_NAME) AND :NEW.QB_INFO_COA_SALES_TAX_ACC_NAME IS NOT NULL AND :OLD.QB_INFO_COA_SALES_TAX_ACC_NAME IS NOT NULL) OR
         (:NEW.QB_INFO_COA_SALES_TAX_ACC_NAME IS NULL AND :OLD.QB_INFO_COA_SALES_TAX_ACC_NAME IS NOT NULL) OR
         (:NEW.QB_INFO_COA_SALES_TAX_ACC_NAME IS NOT NULL AND :OLD.QB_INFO_COA_SALES_TAX_ACC_NAME IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'Company', 'QuickbooksInfo.CoaSalesTaxAccountName', TO_CHAR(:OLD.QB_INFO_COA_SALES_TAX_ACC_NAME ), TO_CHAR(:NEW.QB_INFO_COA_SALES_TAX_ACC_NAME ), :NEW.COMPANY_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

     IF (((:NEW.QUICKBOOKS_INFO_TAX_TABLE_ID <> :OLD.QUICKBOOKS_INFO_TAX_TABLE_ID) AND :NEW.QUICKBOOKS_INFO_TAX_TABLE_ID IS NOT NULL AND :OLD.QUICKBOOKS_INFO_TAX_TABLE_ID IS NOT NULL) OR
         (:NEW.QUICKBOOKS_INFO_TAX_TABLE_ID IS NULL AND :OLD.QUICKBOOKS_INFO_TAX_TABLE_ID IS NOT NULL) OR
         (:NEW.QUICKBOOKS_INFO_TAX_TABLE_ID IS NOT NULL AND :OLD.QUICKBOOKS_INFO_TAX_TABLE_ID IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'Company', 'QuickbooksInfo.TaxTableId', TO_CHAR(:OLD.QUICKBOOKS_INFO_TAX_TABLE_ID ), TO_CHAR(:NEW.QUICKBOOKS_INFO_TAX_TABLE_ID ), :NEW.COMPANY_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

     IF (((:NEW.QB_INFO_AS400_PAYROLL_COUNT <> :OLD.QB_INFO_AS400_PAYROLL_COUNT) AND :NEW.QB_INFO_AS400_PAYROLL_COUNT IS NOT NULL AND :OLD.QB_INFO_AS400_PAYROLL_COUNT IS NOT NULL) OR
         (:NEW.QB_INFO_AS400_PAYROLL_COUNT IS NULL AND :OLD.QB_INFO_AS400_PAYROLL_COUNT IS NOT NULL) OR
         (:NEW.QB_INFO_AS400_PAYROLL_COUNT IS NOT NULL AND :OLD.QB_INFO_AS400_PAYROLL_COUNT IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'Company', 'QuickbooksInfo.AS400PayrollCount', TO_CHAR(:OLD.QB_INFO_AS400_PAYROLL_COUNT ), TO_CHAR(:NEW.QB_INFO_AS400_PAYROLL_COUNT ), :NEW.COMPANY_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

     IF (((:NEW.AGREE_INFO_AGREE_CREATE_DATE <> :OLD.AGREE_INFO_AGREE_CREATE_DATE) AND :NEW.AGREE_INFO_AGREE_CREATE_DATE IS NOT NULL AND :OLD.AGREE_INFO_AGREE_CREATE_DATE IS NOT NULL) OR
         (:NEW.AGREE_INFO_AGREE_CREATE_DATE IS NULL AND :OLD.AGREE_INFO_AGREE_CREATE_DATE IS NOT NULL) OR
         (:NEW.AGREE_INFO_AGREE_CREATE_DATE IS NOT NULL AND :OLD.AGREE_INFO_AGREE_CREATE_DATE IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'Company', 'AgreementInfo.AgreementCreateDate', TO_CHAR(:OLD.AGREE_INFO_AGREE_CREATE_DATE ), TO_CHAR(:NEW.AGREE_INFO_AGREE_CREATE_DATE ), :NEW.COMPANY_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

     IF (((:NEW.AGREEMENT_INFO_NAME <> :OLD.AGREEMENT_INFO_NAME) AND :NEW.AGREEMENT_INFO_NAME IS NOT NULL AND :OLD.AGREEMENT_INFO_NAME IS NOT NULL) OR
         (:NEW.AGREEMENT_INFO_NAME IS NULL AND :OLD.AGREEMENT_INFO_NAME IS NOT NULL) OR
         (:NEW.AGREEMENT_INFO_NAME IS NOT NULL AND :OLD.AGREEMENT_INFO_NAME IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'Company', 'AgreementInfo.Name', TO_CHAR(:OLD.AGREEMENT_INFO_NAME ), TO_CHAR(:NEW.AGREEMENT_INFO_NAME ), :NEW.COMPANY_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

     IF (((:NEW.AGREEMENT_INFO_SERVICE_TYPE <> :OLD.AGREEMENT_INFO_SERVICE_TYPE) AND :NEW.AGREEMENT_INFO_SERVICE_TYPE IS NOT NULL AND :OLD.AGREEMENT_INFO_SERVICE_TYPE IS NOT NULL) OR
         (:NEW.AGREEMENT_INFO_SERVICE_TYPE IS NULL AND :OLD.AGREEMENT_INFO_SERVICE_TYPE IS NOT NULL) OR
         (:NEW.AGREEMENT_INFO_SERVICE_TYPE IS NOT NULL AND :OLD.AGREEMENT_INFO_SERVICE_TYPE IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'Company', 'AgreementInfo.ServiceType', TO_CHAR(:OLD.AGREEMENT_INFO_SERVICE_TYPE ), TO_CHAR(:NEW.AGREEMENT_INFO_SERVICE_TYPE ), :NEW.COMPANY_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

     IF (((:NEW.AGREE_INFO_SUB_NBR <> :OLD.AGREE_INFO_SUB_NBR) AND :NEW.AGREE_INFO_SUB_NBR IS NOT NULL AND :OLD.AGREE_INFO_SUB_NBR IS NOT NULL) OR
         (:NEW.AGREE_INFO_SUB_NBR IS NULL AND :OLD.AGREE_INFO_SUB_NBR IS NOT NULL) OR
         (:NEW.AGREE_INFO_SUB_NBR IS NOT NULL AND :OLD.AGREE_INFO_SUB_NBR IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'Company', 'AgreementInfo.SubscriptionNumber', TO_CHAR(:OLD.AGREE_INFO_SUB_NBR ), TO_CHAR(:NEW.AGREE_INFO_SUB_NBR ), :NEW.COMPANY_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

     IF (((:NEW.AGREE_INFO_SOURCE_ID <> :OLD.AGREE_INFO_SOURCE_ID) AND :NEW.AGREE_INFO_SOURCE_ID IS NOT NULL AND :OLD.AGREE_INFO_SOURCE_ID IS NOT NULL) OR
         (:NEW.AGREE_INFO_SOURCE_ID IS NULL AND :OLD.AGREE_INFO_SOURCE_ID IS NOT NULL) OR
         (:NEW.AGREE_INFO_SOURCE_ID IS NOT NULL AND :OLD.AGREE_INFO_SOURCE_ID IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'Company', 'AgreementInfo.SourceAgreementId', TO_CHAR(:OLD.AGREE_INFO_SOURCE_ID ), TO_CHAR(:NEW.AGREE_INFO_SOURCE_ID ), :NEW.COMPANY_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

     IF (((:NEW.AGREEMENT_INFO_SERVICE_KEY <> :OLD.AGREEMENT_INFO_SERVICE_KEY) AND :NEW.AGREEMENT_INFO_SERVICE_KEY IS NOT NULL AND :OLD.AGREEMENT_INFO_SERVICE_KEY IS NOT NULL) OR
         (:NEW.AGREEMENT_INFO_SERVICE_KEY IS NULL AND :OLD.AGREEMENT_INFO_SERVICE_KEY IS NOT NULL) OR
         (:NEW.AGREEMENT_INFO_SERVICE_KEY IS NOT NULL AND :OLD.AGREEMENT_INFO_SERVICE_KEY IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'Company', 'AgreementInfo.ServiceKey', TO_CHAR(:OLD.AGREEMENT_INFO_SERVICE_KEY ), TO_CHAR(:NEW.AGREEMENT_INFO_SERVICE_KEY ), :NEW.COMPANY_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

     IF (((:NEW.AGREE_INFO_AGREE_SUB_TYPE <> :OLD.AGREE_INFO_AGREE_SUB_TYPE) AND :NEW.AGREE_INFO_AGREE_SUB_TYPE IS NOT NULL AND :OLD.AGREE_INFO_AGREE_SUB_TYPE IS NOT NULL) OR
         (:NEW.AGREE_INFO_AGREE_SUB_TYPE IS NULL AND :OLD.AGREE_INFO_AGREE_SUB_TYPE IS NOT NULL) OR
         (:NEW.AGREE_INFO_AGREE_SUB_TYPE IS NOT NULL AND :OLD.AGREE_INFO_AGREE_SUB_TYPE IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_SEQ INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'Company', 'AgreementInfo.AgreementSubType', TO_CHAR(:OLD.AGREE_INFO_AGREE_SUB_TYPE ), TO_CHAR(:NEW.AGREE_INFO_AGREE_SUB_TYPE ), :NEW.COMPANY_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

  END IF;
END;
/
SHOW ERRORS;


Prompt Trigger PSP_ADDRESS_AT;
Prompt Trigger PSP_ADDRESS_AT;
--
-- PSP_ADDRESS_AT  (Trigger) 
--
CREATE OR REPLACE TRIGGER PSP_ADDRESS_AT
AFTER INSERT OR UPDATE ON PSP_ADDRESS
FOR EACH ROW
DECLARE
  v_company_fk VARCHAR2(255);
  v_creator_id VARCHAR2(30);
  v_modifier_id VARCHAR2(30);
BEGIN

SELECT :NEW.CREATOR_ID INTO v_creator_id FROM DUAL;
SELECT :NEW.MODIFIER_ID INTO v_modifier_id FROM DUAL;

  IF (UPDATING) THEN
     IF (((:NEW.ADDRESS_LINE1 <> :OLD.ADDRESS_LINE1) AND :NEW.ADDRESS_LINE1 IS NOT NULL AND :OLD.ADDRESS_LINE1 IS NOT NULL) OR
         (:NEW.ADDRESS_LINE1 IS NULL AND :OLD.ADDRESS_LINE1 IS NOT NULL) OR
         (:NEW.ADDRESS_LINE1 IS NOT NULL AND :OLD.ADDRESS_LINE1 IS NULL) ) THEN
         BEGIN
            SELECT t1.COMPANY_SEQ INTO v_company_fk from PSP_COMPANY t1 WHERE t1.MAILING_ADDRESS_FK = :NEW.ADDRESS_SEQ or t1.LEGAL_ADDRESS_FK = :NEW.ADDRESS_SEQ;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'Address', 'AddressLine1', TO_CHAR(:OLD.ADDRESS_LINE1 ), TO_CHAR(:NEW.ADDRESS_LINE1 ), :NEW.ADDRESS_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

     IF (((:NEW.ADDRESS_LINE2 <> :OLD.ADDRESS_LINE2) AND :NEW.ADDRESS_LINE2 IS NOT NULL AND :OLD.ADDRESS_LINE2 IS NOT NULL) OR
         (:NEW.ADDRESS_LINE2 IS NULL AND :OLD.ADDRESS_LINE2 IS NOT NULL) OR
         (:NEW.ADDRESS_LINE2 IS NOT NULL AND :OLD.ADDRESS_LINE2 IS NULL) ) THEN
         BEGIN
            SELECT t1.COMPANY_SEQ INTO v_company_fk from PSP_COMPANY t1 WHERE t1.MAILING_ADDRESS_FK = :NEW.ADDRESS_SEQ or t1.LEGAL_ADDRESS_FK = :NEW.ADDRESS_SEQ;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'Address', 'AddressLine2', TO_CHAR(:OLD.ADDRESS_LINE2 ), TO_CHAR(:NEW.ADDRESS_LINE2 ), :NEW.ADDRESS_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

     IF (((:NEW.ADDRESS_LINE3 <> :OLD.ADDRESS_LINE3) AND :NEW.ADDRESS_LINE3 IS NOT NULL AND :OLD.ADDRESS_LINE3 IS NOT NULL) OR
         (:NEW.ADDRESS_LINE3 IS NULL AND :OLD.ADDRESS_LINE3 IS NOT NULL) OR
         (:NEW.ADDRESS_LINE3 IS NOT NULL AND :OLD.ADDRESS_LINE3 IS NULL) ) THEN
         BEGIN
            SELECT t1.COMPANY_SEQ INTO v_company_fk from PSP_COMPANY t1 WHERE t1.MAILING_ADDRESS_FK = :NEW.ADDRESS_SEQ or t1.LEGAL_ADDRESS_FK = :NEW.ADDRESS_SEQ;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'Address', 'AddressLine3', TO_CHAR(:OLD.ADDRESS_LINE3 ), TO_CHAR(:NEW.ADDRESS_LINE3 ), :NEW.ADDRESS_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

     IF (((:NEW.CITY <> :OLD.CITY) AND :NEW.CITY IS NOT NULL AND :OLD.CITY IS NOT NULL) OR
         (:NEW.CITY IS NULL AND :OLD.CITY IS NOT NULL) OR
         (:NEW.CITY IS NOT NULL AND :OLD.CITY IS NULL) ) THEN
         BEGIN
            SELECT t1.COMPANY_SEQ INTO v_company_fk from PSP_COMPANY t1 WHERE t1.MAILING_ADDRESS_FK = :NEW.ADDRESS_SEQ or t1.LEGAL_ADDRESS_FK = :NEW.ADDRESS_SEQ;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'Address', 'City', TO_CHAR(:OLD.CITY ), TO_CHAR(:NEW.CITY ), :NEW.ADDRESS_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

     IF (((:NEW.COUNTRY <> :OLD.COUNTRY) AND :NEW.COUNTRY IS NOT NULL AND :OLD.COUNTRY IS NOT NULL) OR
         (:NEW.COUNTRY IS NULL AND :OLD.COUNTRY IS NOT NULL) OR
         (:NEW.COUNTRY IS NOT NULL AND :OLD.COUNTRY IS NULL) ) THEN
         BEGIN
            SELECT t1.COMPANY_SEQ INTO v_company_fk from PSP_COMPANY t1 WHERE t1.MAILING_ADDRESS_FK = :NEW.ADDRESS_SEQ or t1.LEGAL_ADDRESS_FK = :NEW.ADDRESS_SEQ;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'Address', 'Country', TO_CHAR(:OLD.COUNTRY ), TO_CHAR(:NEW.COUNTRY ), :NEW.ADDRESS_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

     IF (((:NEW.STATE <> :OLD.STATE) AND :NEW.STATE IS NOT NULL AND :OLD.STATE IS NOT NULL) OR
         (:NEW.STATE IS NULL AND :OLD.STATE IS NOT NULL) OR
         (:NEW.STATE IS NOT NULL AND :OLD.STATE IS NULL) ) THEN
         BEGIN
            SELECT t1.COMPANY_SEQ INTO v_company_fk from PSP_COMPANY t1 WHERE t1.MAILING_ADDRESS_FK = :NEW.ADDRESS_SEQ or t1.LEGAL_ADDRESS_FK = :NEW.ADDRESS_SEQ;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'Address', 'State', TO_CHAR(:OLD.STATE ), TO_CHAR(:NEW.STATE ), :NEW.ADDRESS_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

     IF (((:NEW.ZIP_CODE <> :OLD.ZIP_CODE) AND :NEW.ZIP_CODE IS NOT NULL AND :OLD.ZIP_CODE IS NOT NULL) OR
         (:NEW.ZIP_CODE IS NULL AND :OLD.ZIP_CODE IS NOT NULL) OR
         (:NEW.ZIP_CODE IS NOT NULL AND :OLD.ZIP_CODE IS NULL) ) THEN
         BEGIN
            SELECT t1.COMPANY_SEQ INTO v_company_fk from PSP_COMPANY t1 WHERE t1.MAILING_ADDRESS_FK = :NEW.ADDRESS_SEQ or t1.LEGAL_ADDRESS_FK = :NEW.ADDRESS_SEQ;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'Address', 'ZipCode', TO_CHAR(:OLD.ZIP_CODE ), TO_CHAR(:NEW.ZIP_CODE ), :NEW.ADDRESS_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

     IF (((:NEW.ZIP_CODE_EXTENSION <> :OLD.ZIP_CODE_EXTENSION) AND :NEW.ZIP_CODE_EXTENSION IS NOT NULL AND :OLD.ZIP_CODE_EXTENSION IS NOT NULL) OR
         (:NEW.ZIP_CODE_EXTENSION IS NULL AND :OLD.ZIP_CODE_EXTENSION IS NOT NULL) OR
         (:NEW.ZIP_CODE_EXTENSION IS NOT NULL AND :OLD.ZIP_CODE_EXTENSION IS NULL) ) THEN
         BEGIN
            SELECT t1.COMPANY_SEQ INTO v_company_fk from PSP_COMPANY t1 WHERE t1.MAILING_ADDRESS_FK = :NEW.ADDRESS_SEQ or t1.LEGAL_ADDRESS_FK = :NEW.ADDRESS_SEQ;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'Address', 'ZipCodeExtension', TO_CHAR(:OLD.ZIP_CODE_EXTENSION ), TO_CHAR(:NEW.ZIP_CODE_EXTENSION ), :NEW.ADDRESS_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

  END IF;
END;
/
SHOW ERRORS;


Prompt Trigger PSP_COMPANY_BANK_ACCOUNT_AT;
Prompt Trigger PSP_COMPANY_BANK_ACCOUNT_AT;
--
-- PSP_COMPANY_BANK_ACCOUNT_AT  (Trigger) 
--
CREATE OR REPLACE TRIGGER PSP_COMPANY_BANK_ACCOUNT_AT
AFTER INSERT OR UPDATE ON PSP_COMPANY_BANK_ACCOUNT
FOR EACH ROW
DECLARE
  v_company_fk VARCHAR2(255);
  v_creator_id VARCHAR2(30);
  v_modifier_id VARCHAR2(30);
BEGIN

SELECT :NEW.CREATOR_ID INTO v_creator_id FROM DUAL;
SELECT :NEW.MODIFIER_ID INTO v_modifier_id FROM DUAL;

  IF (UPDATING) THEN
     IF (((:NEW.STATUS_CD <> :OLD.STATUS_CD) AND :NEW.STATUS_CD IS NOT NULL AND :OLD.STATUS_CD IS NOT NULL) OR
         (:NEW.STATUS_CD IS NULL AND :OLD.STATUS_CD IS NOT NULL) OR
         (:NEW.STATUS_CD IS NOT NULL AND :OLD.STATUS_CD IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'CompanyBankAccount', 'StatusCd', TO_CHAR(:OLD.STATUS_CD ), TO_CHAR(:NEW.STATUS_CD ), :NEW.COMPANY_BANK_ACCOUNT_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

     IF (((:NEW.STATUS_EFFECTIVE_DATE <> :OLD.STATUS_EFFECTIVE_DATE) AND :NEW.STATUS_EFFECTIVE_DATE IS NOT NULL AND :OLD.STATUS_EFFECTIVE_DATE IS NOT NULL) OR
         (:NEW.STATUS_EFFECTIVE_DATE IS NULL AND :OLD.STATUS_EFFECTIVE_DATE IS NOT NULL) OR
         (:NEW.STATUS_EFFECTIVE_DATE IS NOT NULL AND :OLD.STATUS_EFFECTIVE_DATE IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'CompanyBankAccount', 'StatusEffectiveDate', TO_CHAR(:OLD.STATUS_EFFECTIVE_DATE ), TO_CHAR(:NEW.STATUS_EFFECTIVE_DATE ), :NEW.COMPANY_BANK_ACCOUNT_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

     IF (((:NEW.SOURCE_BANK_ACCOUNT_NAME <> :OLD.SOURCE_BANK_ACCOUNT_NAME) AND :NEW.SOURCE_BANK_ACCOUNT_NAME IS NOT NULL AND :OLD.SOURCE_BANK_ACCOUNT_NAME IS NOT NULL) OR
         (:NEW.SOURCE_BANK_ACCOUNT_NAME IS NULL AND :OLD.SOURCE_BANK_ACCOUNT_NAME IS NOT NULL) OR
         (:NEW.SOURCE_BANK_ACCOUNT_NAME IS NOT NULL AND :OLD.SOURCE_BANK_ACCOUNT_NAME IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'CompanyBankAccount', 'SourceBankAccountName', TO_CHAR(:OLD.SOURCE_BANK_ACCOUNT_NAME ), TO_CHAR(:NEW.SOURCE_BANK_ACCOUNT_NAME ), :NEW.COMPANY_BANK_ACCOUNT_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

  END IF;
END;
/
SHOW ERRORS;


Prompt Trigger PSP_COMPANY_SERVICE_AT;
Prompt Trigger PSP_COMPANY_SERVICE_AT;
--
-- PSP_COMPANY_SERVICE_AT  (Trigger) 
--
CREATE OR REPLACE TRIGGER PSP_COMPANY_SERVICE_AT
AFTER INSERT OR UPDATE ON PSP_COMPANY_SERVICE
FOR EACH ROW
DECLARE
  v_company_fk VARCHAR2(255);
  v_creator_id VARCHAR2(30);
  v_modifier_id VARCHAR2(30);
BEGIN

SELECT :NEW.CREATOR_ID INTO v_creator_id FROM DUAL;
SELECT :NEW.MODIFIER_ID INTO v_modifier_id FROM DUAL;

  IF (UPDATING) THEN
     IF (((:NEW.STATUS_CD <> :OLD.STATUS_CD) AND :NEW.STATUS_CD IS NOT NULL AND :OLD.STATUS_CD IS NOT NULL) OR
         (:NEW.STATUS_CD IS NULL AND :OLD.STATUS_CD IS NOT NULL) OR
         (:NEW.STATUS_CD IS NOT NULL AND :OLD.STATUS_CD IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'CompanyService', 'StatusCd', TO_CHAR(:OLD.STATUS_CD ), TO_CHAR(:NEW.STATUS_CD ), :NEW.COMPANY_SERVICE_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

     IF (((:NEW.STATUS_EFFECTIVE_DATE <> :OLD.STATUS_EFFECTIVE_DATE) AND :NEW.STATUS_EFFECTIVE_DATE IS NOT NULL AND :OLD.STATUS_EFFECTIVE_DATE IS NOT NULL) OR
         (:NEW.STATUS_EFFECTIVE_DATE IS NULL AND :OLD.STATUS_EFFECTIVE_DATE IS NOT NULL) OR
         (:NEW.STATUS_EFFECTIVE_DATE IS NOT NULL AND :OLD.STATUS_EFFECTIVE_DATE IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'CompanyService', 'StatusEffectiveDate', TO_CHAR(:OLD.STATUS_EFFECTIVE_DATE ), TO_CHAR(:NEW.STATUS_EFFECTIVE_DATE ), :NEW.COMPANY_SERVICE_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

  END IF;
END;
/
SHOW ERRORS;


Prompt Trigger PSP_CONTACT_AT;
Prompt Trigger PSP_CONTACT_AT;
--
-- PSP_CONTACT_AT  (Trigger) 
--
CREATE OR REPLACE TRIGGER PSP_CONTACT_AT
AFTER INSERT OR UPDATE ON PSP_CONTACT
FOR EACH ROW
DECLARE
  v_company_fk VARCHAR2(255);
  v_creator_id VARCHAR2(30);
  v_modifier_id VARCHAR2(30);
BEGIN

SELECT CREATOR_ID INTO v_creator_id FROM PSP_INDIVIDUAL WHERE INDIVIDUAL_SEQ = :NEW.CONTACT_SEQ;
SELECT MODIFIER_ID INTO v_modifier_id FROM PSP_INDIVIDUAL WHERE INDIVIDUAL_SEQ = :NEW.CONTACT_SEQ;

  IF (UPDATING) THEN
     IF (((:NEW.AUTH_SIGNER_YN_IND <> :OLD.AUTH_SIGNER_YN_IND) AND :NEW.AUTH_SIGNER_YN_IND IS NOT NULL AND :OLD.AUTH_SIGNER_YN_IND IS NOT NULL) OR
         (:NEW.AUTH_SIGNER_YN_IND IS NULL AND :OLD.AUTH_SIGNER_YN_IND IS NOT NULL) OR
         (:NEW.AUTH_SIGNER_YN_IND IS NOT NULL AND :OLD.AUTH_SIGNER_YN_IND IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'Contact', 'AuthSignerYnInd', TO_CHAR(:OLD.AUTH_SIGNER_YN_IND ), TO_CHAR(:NEW.AUTH_SIGNER_YN_IND ), :NEW.CONTACT_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

     IF (((:NEW.CONTACT_ROLE_CD <> :OLD.CONTACT_ROLE_CD) AND :NEW.CONTACT_ROLE_CD IS NOT NULL AND :OLD.CONTACT_ROLE_CD IS NOT NULL) OR
         (:NEW.CONTACT_ROLE_CD IS NULL AND :OLD.CONTACT_ROLE_CD IS NOT NULL) OR
         (:NEW.CONTACT_ROLE_CD IS NOT NULL AND :OLD.CONTACT_ROLE_CD IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'Contact', 'ContactRoleCd', TO_CHAR(:OLD.CONTACT_ROLE_CD ), TO_CHAR(:NEW.CONTACT_ROLE_CD ), :NEW.CONTACT_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

     IF (((:NEW.FAX <> :OLD.FAX) AND :NEW.FAX IS NOT NULL AND :OLD.FAX IS NOT NULL) OR
         (:NEW.FAX IS NULL AND :OLD.FAX IS NOT NULL) OR
         (:NEW.FAX IS NOT NULL AND :OLD.FAX IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'Contact', 'Fax', TO_CHAR(:OLD.FAX ), TO_CHAR(:NEW.FAX ), :NEW.CONTACT_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

     IF (((:NEW.JOB_TITLE <> :OLD.JOB_TITLE) AND :NEW.JOB_TITLE IS NOT NULL AND :OLD.JOB_TITLE IS NOT NULL) OR
         (:NEW.JOB_TITLE IS NULL AND :OLD.JOB_TITLE IS NOT NULL) OR
         (:NEW.JOB_TITLE IS NOT NULL AND :OLD.JOB_TITLE IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'Contact', 'JobTitle', TO_CHAR(:OLD.JOB_TITLE ), TO_CHAR(:NEW.JOB_TITLE ), :NEW.CONTACT_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

     IF (((:NEW.SOURCE_CONTACT_ID <> :OLD.SOURCE_CONTACT_ID) AND :NEW.SOURCE_CONTACT_ID IS NOT NULL AND :OLD.SOURCE_CONTACT_ID IS NOT NULL) OR
         (:NEW.SOURCE_CONTACT_ID IS NULL AND :OLD.SOURCE_CONTACT_ID IS NOT NULL) OR
         (:NEW.SOURCE_CONTACT_ID IS NOT NULL AND :OLD.SOURCE_CONTACT_ID IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'Contact', 'SourceContactId', TO_CHAR(:OLD.SOURCE_CONTACT_ID ), TO_CHAR(:NEW.SOURCE_CONTACT_ID ), :NEW.CONTACT_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

     IF (((:NEW.TITLE <> :OLD.TITLE) AND :NEW.TITLE IS NOT NULL AND :OLD.TITLE IS NOT NULL) OR
         (:NEW.TITLE IS NULL AND :OLD.TITLE IS NOT NULL) OR
         (:NEW.TITLE IS NOT NULL AND :OLD.TITLE IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'Contact', 'Title', TO_CHAR(:OLD.TITLE ), TO_CHAR(:NEW.TITLE ), :NEW.CONTACT_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

     IF (((:NEW.TITLE_SUFFIX <> :OLD.TITLE_SUFFIX) AND :NEW.TITLE_SUFFIX IS NOT NULL AND :OLD.TITLE_SUFFIX IS NOT NULL) OR
         (:NEW.TITLE_SUFFIX IS NULL AND :OLD.TITLE_SUFFIX IS NOT NULL) OR
         (:NEW.TITLE_SUFFIX IS NOT NULL AND :OLD.TITLE_SUFFIX IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'Contact', 'TitleSuffix', TO_CHAR(:OLD.TITLE_SUFFIX ), TO_CHAR(:NEW.TITLE_SUFFIX ), :NEW.CONTACT_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

  END IF;
END;
/
SHOW ERRORS;


Prompt Trigger PSP_DDCOMPANY_SERVICE_INFO_AT;
Prompt Trigger PSP_DDCOMPANY_SERVICE_INFO_AT;
--
-- PSP_DDCOMPANY_SERVICE_INFO_AT  (Trigger) 
--
CREATE OR REPLACE TRIGGER PSP_DDCOMPANY_SERVICE_INFO_AT
AFTER INSERT OR UPDATE ON PSP_DDCOMPANY_SERVICE_INFO
FOR EACH ROW
DECLARE
  v_company_fk VARCHAR2(255);
  v_creator_id VARCHAR2(30);
  v_modifier_id VARCHAR2(30);
BEGIN

SELECT CREATOR_ID INTO v_creator_id FROM PSP_COMPANY_SERVICE WHERE COMPANY_SERVICE_SEQ = :NEW.DDCOMPANY_SERVICE_INFO_SEQ;
SELECT MODIFIER_ID INTO v_modifier_id FROM PSP_COMPANY_SERVICE WHERE COMPANY_SERVICE_SEQ = :NEW.DDCOMPANY_SERVICE_INFO_SEQ;

  IF (UPDATING) THEN
     IF (((:NEW.OVERRIDE_COMPANY_LIMIT_AMOUNT <> :OLD.OVERRIDE_COMPANY_LIMIT_AMOUNT) AND :NEW.OVERRIDE_COMPANY_LIMIT_AMOUNT IS NOT NULL AND :OLD.OVERRIDE_COMPANY_LIMIT_AMOUNT IS NOT NULL) OR
         (:NEW.OVERRIDE_COMPANY_LIMIT_AMOUNT IS NULL AND :OLD.OVERRIDE_COMPANY_LIMIT_AMOUNT IS NOT NULL) OR
         (:NEW.OVERRIDE_COMPANY_LIMIT_AMOUNT IS NOT NULL AND :OLD.OVERRIDE_COMPANY_LIMIT_AMOUNT IS NULL) ) THEN
         BEGIN
            SELECT t1.COMPANY_FK INTO v_company_fk from PSP_COMPANY_SERVICE t1 WHERE t1.COMPANY_SERVICE_SEQ = :NEW.DDCOMPANY_SERVICE_INFO_SEQ;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'DDCompanyServiceInfo', 'OverrideCompanyLimitAmount', TO_CHAR(:OLD.OVERRIDE_COMPANY_LIMIT_AMOUNT ), TO_CHAR(:NEW.OVERRIDE_COMPANY_LIMIT_AMOUNT ), :NEW.DDCOMPANY_SERVICE_INFO_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

     IF (((:NEW.OVERRIDE_EMPLOYEE_LIMIT_AMOUNT <> :OLD.OVERRIDE_EMPLOYEE_LIMIT_AMOUNT) AND :NEW.OVERRIDE_EMPLOYEE_LIMIT_AMOUNT IS NOT NULL AND :OLD.OVERRIDE_EMPLOYEE_LIMIT_AMOUNT IS NOT NULL) OR
         (:NEW.OVERRIDE_EMPLOYEE_LIMIT_AMOUNT IS NULL AND :OLD.OVERRIDE_EMPLOYEE_LIMIT_AMOUNT IS NOT NULL) OR
         (:NEW.OVERRIDE_EMPLOYEE_LIMIT_AMOUNT IS NOT NULL AND :OLD.OVERRIDE_EMPLOYEE_LIMIT_AMOUNT IS NULL) ) THEN
         BEGIN
            SELECT t1.COMPANY_FK INTO v_company_fk from PSP_COMPANY_SERVICE t1 WHERE t1.COMPANY_SERVICE_SEQ = :NEW.DDCOMPANY_SERVICE_INFO_SEQ;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'DDCompanyServiceInfo', 'OverrideEmployeeLimitAmount', TO_CHAR(:OLD.OVERRIDE_EMPLOYEE_LIMIT_AMOUNT ), TO_CHAR(:NEW.OVERRIDE_EMPLOYEE_LIMIT_AMOUNT ), :NEW.DDCOMPANY_SERVICE_INFO_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

  END IF;
END;
/
SHOW ERRORS;


Prompt Trigger PSP_FINANCIAL_TRANSACTION_AT;
Prompt Trigger PSP_FINANCIAL_TRANSACTION_AT;
--
-- PSP_FINANCIAL_TRANSACTION_AT  (Trigger) 
--
CREATE OR REPLACE TRIGGER PSP_FINANCIAL_TRANSACTION_AT
AFTER INSERT OR UPDATE ON PSP_FINANCIAL_TRANSACTION
FOR EACH ROW
DECLARE
  v_company_fk VARCHAR2(255);
  v_creator_id VARCHAR2(30);
  v_modifier_id VARCHAR2(30);
BEGIN

SELECT :NEW.CREATOR_ID INTO v_creator_id FROM DUAL;
SELECT :NEW.MODIFIER_ID INTO v_modifier_id FROM DUAL;

  IF (UPDATING) THEN
     IF (((:NEW.CURRENT_TRANSACTION_STATE_FK <> :OLD.CURRENT_TRANSACTION_STATE_FK) AND :NEW.CURRENT_TRANSACTION_STATE_FK IS NOT NULL AND :OLD.CURRENT_TRANSACTION_STATE_FK IS NOT NULL) OR
         (:NEW.CURRENT_TRANSACTION_STATE_FK IS NULL AND :OLD.CURRENT_TRANSACTION_STATE_FK IS NOT NULL) OR
         (:NEW.CURRENT_TRANSACTION_STATE_FK IS NOT NULL AND :OLD.CURRENT_TRANSACTION_STATE_FK IS NULL) ) THEN
         BEGIN
            SELECT :NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (SYS_GUID(), 0, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP), 'FinancialTransaction', 'CurrentTransactionState', TO_CHAR(:OLD.CURRENT_TRANSACTION_STATE_FK ), TO_CHAR(:NEW.CURRENT_TRANSACTION_STATE_FK ), :NEW.FINANCIAL_TRANSACTION_SEQ, v_modifier_id, SYS_EXTRACT_UTC(SYSTIMESTAMP), v_company_fk);
         END IF;
     END IF;

  END IF;
END;
/
SHOW ERRORS;


PROMPT finishedDBUpgradeFrom_1.9.9.27_To_1.9.9.28.sql