--
-- This script will be executed BEFORE the automatically generated
-- C:\dev\PSP\v1-maint\PSE\Domain\src\main\model\DBUpgrade_001.009.011.004.sql
--
-- Developers can hand code logic here for data migration purposes
--
