--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--                                                                      --
-- Please review the script before using it to make sure it won't       --
-- cause any unacceptable data loss.                                    --
--                                                                      --
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL
-- PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL

ALTER TABLE PSP_AGENCY_CHECK_LIST_ITEM 
DROP CONSTRAINT C_PSP_AGENCY_CHECK_LIST_IT2; 

ALTER TABLE PSP_AGENCY_CHECK_LIST_ITEM 
ADD CONSTRAINT C_PSP_AGENCY_CHECK_LIST_IT2 
CHECK(CHECK_LIST_ITEM_GROUP IN('RAAForms', 'CaliforniaInfo'));


ALTER TABLE PSP_EVENT_TYPE
 DROP CONSTRAINT C_PSP_EVENT_TYPE0;

ALTER TABLE PSP_COMPANY_EVENT
 DROP CONSTRAINT C_PSP_COMPANY_EVENT1;

ALTER TABLE PSP_FINANCIAL_TRANSACTION
 DROP CONSTRAINT PSP_FINANCIAL_TRANSACTION_FK2;

Prompt drop Index PSP_FINANCIAL_TRANSACTION_FK2;
DROP INDEX PSP_FINANCIAL_TRANSACTION_FK2;

Prompt drop TABLE PSP_DEPOSIT_FREQUENCY;
ALTER TABLE PSP_DEPOSIT_FREQUENCY
 DROP PRIMARY KEY CASCADE;
DROP TABLE PSP_DEPOSIT_FREQUENCY CASCADE CONSTRAINTS;

Prompt Table PSP_AGENCY_STATUS;
--
-- PSP_AGENCY_STATUS  (Table)
--
CREATE TABLE PSP_AGENCY_STATUS
(
  AGENCY_STATUS_CD     VARCHAR2(255 CHAR)       NOT NULL,
  VERSION              NUMBER(19)               NOT NULL,
  REALM_ID             NUMBER(19)               DEFAULT -1                    NOT NULL,
  DESCRIPTION          VARCHAR2(4000 CHAR),
  NAME                 VARCHAR2(4000 CHAR),
  IS_SET_MANUALLY      NUMBER(1),
  IS_REMOVED_MANUALLY  NUMBER(1),
  IS_HOLD_STATUS       NUMBER(1)
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE PSP_AGENCY_STATUS
 ADD CONSTRAINT C_PSP_AGENCY_STATUS0
 CHECK (AGENCY_STATUS_CD IN('Active', 'AgencyRejection', 'Inactive', 'ManualHold'));

ALTER TABLE PSP_AGENCY_STATUS
 ADD PRIMARY KEY
 (AGENCY_STATUS_CD, REALM_ID);

Prompt Column RFNDS_INTUIT_FOR_RETURNED_PMT;
ALTER TABLE PSP_AGENCY
 ADD (RFNDS_INTUIT_FOR_RETURNED_PMT  NUMBER(1));

Prompt Table PSP_EFE_PMT_BATCH;
--
-- PSP_EFE_PMT_BATCH  (Table)
--
CREATE TABLE PSP_EFE_PMT_BATCH
(
  EFE_PMT_BATCH_SEQ      VARCHAR2(255 CHAR)     NOT NULL,
  VERSION                NUMBER(19)             NOT NULL,
  CREATOR_ID             VARCHAR2(30 CHAR),
  CREATED_DATE           TIMESTAMP(6)           NOT NULL,
  MODIFIER_ID            VARCHAR2(30 CHAR),
  MODIFIED_DATE          TIMESTAMP(6)           NOT NULL,
  REALM_ID               NUMBER(19)             DEFAULT -1                    NOT NULL,
  END_TIME               TIMESTAMP(6),
  INITIATION_DATE        TIMESTAMP(6),
  START_TIME             TIMESTAMP(6),
  STATUS_EFFECTIVE_DATE  TIMESTAMP(6),
  STATUS                 VARCHAR2(255 CHAR)
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE PSP_EFE_PMT_BATCH
 ADD CONSTRAINT C_PSP_EFE_PMT_BATCH0
 CHECK (STATUS IN('Created', 'FatalEFEError', 'FatalPSPError', 'Success', 'SuccessWithErrors'));

ALTER TABLE PSP_EFE_PMT_BATCH
 ADD PRIMARY KEY
 (EFE_PMT_BATCH_SEQ, REALM_ID);

Prompt Table PSP_AGENCY_STAT_TXN_TYPE;
--
-- PSP_AGENCY_STAT_TXN_TYPE  (Table)
--
CREATE TABLE PSP_AGENCY_STAT_TXN_TYPE
(
  AGENCY_STAT_TXN_TYPE_SEQ  VARCHAR2(255 CHAR)  NOT NULL,
  VERSION                   NUMBER(19)          NOT NULL,
  CREATOR_ID                VARCHAR2(30 CHAR),
  CREATED_DATE              TIMESTAMP(6)        NOT NULL,
  MODIFIER_ID               VARCHAR2(30 CHAR),
  MODIFIED_DATE             TIMESTAMP(6)        NOT NULL,
  REALM_ID                  NUMBER(19)          DEFAULT -1                    NOT NULL,
  AGENCY_STATUS_FK          VARCHAR2(255 CHAR)  NOT NULL,
  TRANSACTION_TYPE_FK       VARCHAR2(255 CHAR)  NOT NULL
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

Prompt Index PSP_AGENCY_STATUS_TRANSACT_FK2;
--
-- PSP_AGENCY_STATUS_TRANSACT_FK2  (Index)
--
CREATE INDEX PSP_AGENCY_STATUS_TRANSACT_FK2 ON PSP_AGENCY_STAT_TXN_TYPE
(TRANSACTION_TYPE_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt Index PSP_AGENCY_STATUS_TRANSACT_FK1;
--
-- PSP_AGENCY_STATUS_TRANSACT_FK1  (Index)
--
CREATE INDEX PSP_AGENCY_STATUS_TRANSACT_FK1 ON PSP_AGENCY_STAT_TXN_TYPE
(AGENCY_STATUS_FK, REALM_ID)
LOGGING
NOPARALLEL;

ALTER TABLE PSP_AGENCY_STAT_TXN_TYPE
 ADD PRIMARY KEY
 (AGENCY_STAT_TXN_TYPE_SEQ, REALM_ID);

Prompt Column AGENCY_FK;
ALTER TABLE PSP_PAYMENT_TEMPLATE
 ADD (AGENCY_FK  VARCHAR2(255 CHAR));

Prompt Column COMPANY_AGENCY_STATUS_CODE;
ALTER TABLE PSP_COMPANY_AGENCY
 ADD (COMPANY_AGENCY_STATUS_CODE  VARCHAR2(255 CHAR));

Prompt Index PSP_PAYMENT_TEMPLATE_FK1;
--
-- PSP_PAYMENT_TEMPLATE_FK1  (Index)
--
CREATE INDEX PSP_PAYMENT_TEMPLATE_FK1 ON PSP_PAYMENT_TEMPLATE
(AGENCY_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt Table PSP_PAYROLL_TAX;
--
-- PSP_PAYROLL_TAX  (Table)
--
CREATE TABLE PSP_PAYROLL_TAX
(
  PAYROLL_TAX_SEQ  VARCHAR2(255 CHAR)           NOT NULL,
  VERSION          NUMBER(19)                   NOT NULL,
  CREATOR_ID       VARCHAR2(30 CHAR),
  CREATED_DATE     TIMESTAMP(6)                 NOT NULL,
  MODIFIER_ID      VARCHAR2(30 CHAR),
  MODIFIED_DATE    TIMESTAMP(6)                 NOT NULL,
  REALM_ID         NUMBER(19)                   DEFAULT -1                    NOT NULL,
  AMOUNT           NUMBER(19,4),
  EFFECTIVE_DATE   TIMESTAMP(6),
  LAW_FK           VARCHAR2(255 CHAR)           NOT NULL,
  PAYROLL_RUN_FK   VARCHAR2(255 CHAR)           NOT NULL
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

Prompt Index PSP_PAYROLL_TAX_FK2;
--
-- PSP_PAYROLL_TAX_FK2  (Index)
--
CREATE INDEX PSP_PAYROLL_TAX_FK2 ON PSP_PAYROLL_TAX
(PAYROLL_RUN_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt Index PSP_PAYROLL_TAX_FK1;
--
-- PSP_PAYROLL_TAX_FK1  (Index)
--
CREATE INDEX PSP_PAYROLL_TAX_FK1 ON PSP_PAYROLL_TAX
(LAW_FK, REALM_ID)
LOGGING
NOPARALLEL;

ALTER TABLE PSP_PAYROLL_TAX
 ADD PRIMARY KEY
 (PAYROLL_TAX_SEQ, REALM_ID);

Prompt Table PSP_PMT_TEMPLATE_FREQUENCY;
--
-- PSP_PMT_TEMPLATE_FREQUENCY  (Table)
--
CREATE TABLE PSP_PMT_TEMPLATE_FREQUENCY
(
  PAYMENT_TEMPLATE_FREQUENCY_ID  VARCHAR2(255 CHAR) NOT NULL,
  VERSION                        NUMBER(19)     NOT NULL,
  REALM_ID                       NUMBER(19)     DEFAULT -1                    NOT NULL,
  PAYMENT_FREQUENCY_ID           VARCHAR2(50 CHAR),
  PAYMENT_TEMPLATE_FK            VARCHAR2(255 CHAR) NOT NULL
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

Prompt Index PSP_PAYMENT_TEMPLATE_FREQU_FK1;
--
-- PSP_PAYMENT_TEMPLATE_FREQU_FK1  (Index)
--
CREATE INDEX PSP_PAYMENT_TEMPLATE_FREQU_FK1 ON PSP_PMT_TEMPLATE_FREQUENCY
(PAYMENT_TEMPLATE_FK, REALM_ID)
LOGGING
NOPARALLEL;

ALTER TABLE PSP_PMT_TEMPLATE_FREQUENCY
 ADD PRIMARY KEY
 (PAYMENT_TEMPLATE_FREQUENCY_ID, REALM_ID);

Prompt Column E_F_E_PAYMENT_STATUS;
ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 ADD (E_F_E_PAYMENT_STATUS  VARCHAR2(255 CHAR));

Prompt Column EFE_PMT_STATUS_EFF_DATE;
ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 ADD (EFE_PMT_STATUS_EFF_DATE  TIMESTAMP(6));

Prompt Column REFERENCE_NUMBER;
ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 ADD (REFERENCE_NUMBER  VARCHAR2(4000 CHAR));

Prompt Column MANUAL_PAYMENT_STATUS;
ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 ADD (MANUAL_PAYMENT_STATUS  VARCHAR2(255 CHAR));

Prompt Column EFE_PYMT_BATCH_FK;
ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 ADD (EFE_PYMT_BATCH_FK  VARCHAR2(255 CHAR));

Prompt Column PAYMENT_FREQUENCY_FK;
ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 ADD (PAYMENT_FREQUENCY_FK  VARCHAR2(255 CHAR));

Prompt Column AUTH_USER_FK;
ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 ADD (AUTH_USER_FK  VARCHAR2(255 CHAR));

Prompt Column ORIGINAL_TRANSACTION_FK;
ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 ADD (ORIGINAL_TRANSACTION_FK  VARCHAR2(255 CHAR));

Prompt Column DEPOSIT_FREQUENCY_FK;
-- Column to be dropped is part of a multi-column constraint.
-- Oracle requires that the constraint be dropped first.
-- There may be another statement later in the script that tries to drop
-- the constraint again.  Errors produced by it can be ignored.
--ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION DROP CONSTRAINT PSP_MONEY_MOVEMENT_TRANSAC_FK1;
ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION DROP COLUMN DEPOSIT_FREQUENCY_FK;

Prompt Table PSP_EFERETURN;
--
-- PSP_EFERETURN  (Table)
--
CREATE TABLE PSP_EFERETURN
(
  EFERETURN_SEQ                  VARCHAR2(255 CHAR) NOT NULL,
  VERSION                        NUMBER(19)     NOT NULL,
  CREATOR_ID                     VARCHAR2(30 CHAR),
  CREATED_DATE                   TIMESTAMP(6)   NOT NULL,
  MODIFIER_ID                    VARCHAR2(30 CHAR),
  MODIFIED_DATE                  TIMESTAMP(6)   NOT NULL,
  REALM_ID                       NUMBER(19)     DEFAULT -1                    NOT NULL,
  E_F_E_RETURN_CD                VARCHAR2(4000 CHAR),
  E_F_E_RETURN_DESCRIPTION       VARCHAR2(4000 CHAR),
  E_F_E_RETURN_STATUS            VARCHAR2(255 CHAR),
  EFE_RETURN_STATUS_EFF_DATE     TIMESTAMP(6),
  MONEY_MOVEMENT_TRANSACTION_FK  VARCHAR2(255 CHAR)
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

Prompt Index PSP_EFERETURN_FK1;
--
-- PSP_EFERETURN_FK1  (Index)
--
CREATE INDEX PSP_EFERETURN_FK1 ON PSP_EFERETURN
(MONEY_MOVEMENT_TRANSACTION_FK, REALM_ID)
LOGGING
NOPARALLEL;

ALTER TABLE PSP_EFERETURN
 ADD CONSTRAINT C_PSP_EFERETURN0
 CHECK (E_F_E_RETURN_STATUS IN('Created', 'Resolved'));

ALTER TABLE PSP_EFERETURN
 ADD PRIMARY KEY
 (EFERETURN_SEQ, REALM_ID);

Prompt Table PSP_COMPANY_LAW;
--
-- PSP_COMPANY_LAW  (Table)
--
CREATE TABLE PSP_COMPANY_LAW
(
  COMPANY_LAW_SEQ    VARCHAR2(255 CHAR)         NOT NULL,
  VERSION            NUMBER(19)                 NOT NULL,
  CREATOR_ID         VARCHAR2(30 CHAR),
  CREATED_DATE       TIMESTAMP(6)               NOT NULL,
  MODIFIER_ID        VARCHAR2(30 CHAR),
  MODIFIED_DATE      TIMESTAMP(6)               NOT NULL,
  REALM_ID           NUMBER(19)                 DEFAULT -1                    NOT NULL,
  STATUS             VARCHAR2(255 CHAR),
  COMPANY_AGENCY_FK  VARCHAR2(255 CHAR)         NOT NULL,
  LAW_FK             VARCHAR2(255 CHAR)         NOT NULL
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

Prompt Index PSP_COMPANY_LAW_FK2;
--
-- PSP_COMPANY_LAW_FK2  (Index)
--
CREATE INDEX PSP_COMPANY_LAW_FK2 ON PSP_COMPANY_LAW
(LAW_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt Index PSP_COMPANY_LAW_FK1;
--
-- PSP_COMPANY_LAW_FK1  (Index)
--
CREATE INDEX PSP_COMPANY_LAW_FK1 ON PSP_COMPANY_LAW
(COMPANY_AGENCY_FK, REALM_ID)
LOGGING
NOPARALLEL;

ALTER TABLE PSP_COMPANY_LAW
 ADD CONSTRAINT C_PSP_COMPANY_LAW0
 CHECK (STATUS IN('Exempt', 'NonExempt'));

ALTER TABLE PSP_COMPANY_LAW
 ADD PRIMARY KEY
 (COMPANY_LAW_SEQ, REALM_ID);

Prompt Table PSP_COMPANYAGENCY_PMTTEMPLATE;
--
-- PSP_COMPANYAGENCY_PMTTEMPLATE  (Table)
--
CREATE TABLE PSP_COMPANYAGENCY_PMTTEMPLATE
(
  COMPANYAGENCY_PMTTEMPLATE_SEQ  VARCHAR2(255 CHAR) NOT NULL,
  VERSION                        NUMBER(19)     NOT NULL,
  CREATOR_ID                     VARCHAR2(30 CHAR),
  CREATED_DATE                   TIMESTAMP(6)   NOT NULL,
  MODIFIER_ID                    VARCHAR2(30 CHAR),
  MODIFIED_DATE                  TIMESTAMP(6)   NOT NULL,
  REALM_ID                       NUMBER(19)     DEFAULT -1                    NOT NULL,
  COMPANY_AGENCY_FK              VARCHAR2(255 CHAR) NOT NULL,
  PAYMENT_TEMPLATE_FK            VARCHAR2(255 CHAR) NOT NULL
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

Prompt Index PSP_COMPANY_AGENCY_PAYMENT_FK2;
--
-- PSP_COMPANY_AGENCY_PAYMENT_FK2  (Index)
--
CREATE INDEX PSP_COMPANY_AGENCY_PAYMENT_FK2 ON PSP_COMPANYAGENCY_PMTTEMPLATE
(PAYMENT_TEMPLATE_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt Index PSP_COMPANY_AGENCY_PAYMENT_FK1;
--
-- PSP_COMPANY_AGENCY_PAYMENT_FK1  (Index)
--
CREATE INDEX PSP_COMPANY_AGENCY_PAYMENT_FK1 ON PSP_COMPANYAGENCY_PMTTEMPLATE
(COMPANY_AGENCY_FK, REALM_ID)
LOGGING
NOPARALLEL;

ALTER TABLE PSP_COMPANYAGENCY_PMTTEMPLATE
 ADD PRIMARY KEY
 (COMPANYAGENCY_PMTTEMPLATE_SEQ, REALM_ID);

Prompt Table PSP_COMP_AGENCY_ON_HOLD_REASON;
--
-- PSP_COMP_AGENCY_ON_HOLD_REASON  (Table)
--
CREATE TABLE PSP_COMP_AGENCY_ON_HOLD_REASON
(
  COMP_AGENCY_ON_HOLD_REASON_SEQ  VARCHAR2(255 CHAR) NOT NULL,
  VERSION                         NUMBER(19)    NOT NULL,
  CREATOR_ID                      VARCHAR2(30 CHAR),
  CREATED_DATE                    TIMESTAMP(6)  NOT NULL,
  MODIFIER_ID                     VARCHAR2(30 CHAR),
  MODIFIED_DATE                   TIMESTAMP(6)  NOT NULL,
  REALM_ID                        NUMBER(19)    DEFAULT -1                    NOT NULL,
  EFFECTIVE_DATE                  TIMESTAMP(6),
  EXPIRATION_DATE                 TIMESTAMP(6),
  ON_HOLD_REASON_CD               VARCHAR2(255 CHAR),
  COMPANY_AGENCY_FK               VARCHAR2(255 CHAR) NOT NULL
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

Prompt Index PSP_COMPANY_AGENCY_ON_HOLD_FK1;
--
-- PSP_COMPANY_AGENCY_ON_HOLD_FK1  (Index)
--
CREATE INDEX PSP_COMPANY_AGENCY_ON_HOLD_FK1 ON PSP_COMP_AGENCY_ON_HOLD_REASON
(COMPANY_AGENCY_FK, REALM_ID)
LOGGING
NOPARALLEL;

ALTER TABLE PSP_COMP_AGENCY_ON_HOLD_REASON
 ADD CONSTRAINT C_PSP_COMP_AGENCY_ON_HOLD_0
 CHECK (ON_HOLD_REASON_CD IN('Active', 'AgencyRejection', 'Inactive', 'ManualHold'));

ALTER TABLE PSP_COMP_AGENCY_ON_HOLD_REASON
 ADD PRIMARY KEY
 (COMP_AGENCY_ON_HOLD_REASON_SEQ, REALM_ID);

Prompt Index PSP_MONEY_MOVEMENT_TRANSAC_FK6;
--
-- PSP_MONEY_MOVEMENT_TRANSAC_FK6  (Index)
--
--CREATE INDEX PSP_MONEY_MOVEMENT_TRANSAC_FK6 ON PSP_MONEY_MOVEMENT_TRANSACTION
--(OFFLOAD_BATCH_FK, REALM_ID)
--LOGGING
--NOPARALLEL;

Prompt Index PSP_MONEYMOVEMENTTRANSACTI_FK1;
--
-- PSP_MONEYMOVEMENTTRANSACTI_FK1  (Index)
--
CREATE INDEX PSP_MONEYMOVEMENTTRANSACTI_FK1 ON PSP_MONEY_MOVEMENT_TRANSACTION
(ORIGINAL_TRANSACTION_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt Index PSP_MONEY_MOVEMENT_TRANSAC_FK5;
--
-- PSP_MONEY_MOVEMENT_TRANSAC_FK5  (Index)
--
--CREATE INDEX PSP_MONEY_MOVEMENT_TRANSAC_FK5 ON PSP_MONEY_MOVEMENT_TRANSACTION
--(COMPANY_FK, REALM_ID)
--LOGGING
--NOPARALLEL;

Prompt Index PSP_MONEY_MOVEMENT_TRANSAC_FK4;
Prompt drop Index PSP_MONEY_MOVEMENT_TRANSAC_FK4;
DROP INDEX PSP_MONEY_MOVEMENT_TRANSAC_FK4;
Prompt Index PSP_MONEY_MOVEMENT_TRANSAC_FK4;
--
-- PSP_MONEY_MOVEMENT_TRANSAC_FK4  (Index)
--
CREATE INDEX PSP_MONEY_MOVEMENT_TRANSAC_FK4 ON PSP_MONEY_MOVEMENT_TRANSACTION
(AUTH_USER_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt Index PSP_MONEY_MOVEMENT_TRANSAC_FK3;
Prompt drop Index PSP_MONEY_MOVEMENT_TRANSAC_FK3;
DROP INDEX PSP_MONEY_MOVEMENT_TRANSAC_FK3;
Prompt Index PSP_MONEY_MOVEMENT_TRANSAC_FK3;
--
-- PSP_MONEY_MOVEMENT_TRANSAC_FK3  (Index)
--
CREATE INDEX PSP_MONEY_MOVEMENT_TRANSAC_FK3 ON PSP_MONEY_MOVEMENT_TRANSACTION
(PAYMENT_FREQUENCY_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt Index PSP_MONEY_MOVEMENT_TRANSAC_FK1;
Prompt drop Index PSP_MONEY_MOVEMENT_TRANSAC_FK1;
--DROP INDEX PSP_MONEY_MOVEMENT_TRANSAC_FK1;
--Prompt Index PSP_MONEY_MOVEMENT_TRANSAC_FK1;
--
-- PSP_MONEY_MOVEMENT_TRANSAC_FK1  (Index)
--
CREATE INDEX PSP_MONEY_MOVEMENT_TRANSAC_FK1 ON PSP_MONEY_MOVEMENT_TRANSACTION
(EFE_PYMT_BATCH_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt Column COMPANY_AGENCY_PMT_TEMPLATE_FK;
ALTER TABLE PSP_EFFECTIVE_DEPOSIT_FREQ
 ADD (COMPANY_AGENCY_PMT_TEMPLATE_FK  VARCHAR2(255 CHAR) NOT NULL);

Prompt Column PAYMENT_TEMPLATE_FREQUENCY_FK;
ALTER TABLE PSP_EFFECTIVE_DEPOSIT_FREQ
 ADD (PAYMENT_TEMPLATE_FREQUENCY_FK  VARCHAR2(255 CHAR) NOT NULL);

Prompt Column COMPANY_AGENCY_FK;
-- Column to be dropped is part of a multi-column constraint.
-- Oracle requires that the constraint be dropped first.
-- There may be another statement later in the script that tries to drop
-- the constraint again.  Errors produced by it can be ignored.
ALTER TABLE PSP_EFFECTIVE_DEPOSIT_FREQ DROP CONSTRAINT PSP_EFFECTIVE_DEPOSIT_FREQ_FK1;
ALTER TABLE PSP_EFFECTIVE_DEPOSIT_FREQ DROP COLUMN COMPANY_AGENCY_FK;

Prompt Column DEPOSIT_FREQUENCY_FK;
-- Column to be dropped is part of a multi-column constraint.
-- Oracle requires that the constraint be dropped first.
-- There may be another statement later in the script that tries to drop
-- the constraint again.  Errors produced by it can be ignored.
--ALTER TABLE PSP_EFFECTIVE_DEPOSIT_FREQ DROP CONSTRAINT PSP_EFFECTIVE_DEPOSIT_FREQ_FK2;
ALTER TABLE PSP_EFFECTIVE_DEPOSIT_FREQ DROP COLUMN DEPOSIT_FREQUENCY_FK;

Prompt Index PSP_EFFECTIVE_DEPOSIT_FREQ_FK2;
Prompt drop Index PSP_EFFECTIVE_DEPOSIT_FREQ_FK2;
--DROP INDEX PSP_EFFECTIVE_DEPOSIT_FREQ_FK2;
Prompt Index PSP_EFFECTIVE_DEPOSIT_FREQ_FK2;
--
-- PSP_EFFECTIVE_DEPOSIT_FREQ_FK2  (Index)
--
CREATE INDEX PSP_EFFECTIVE_DEPOSIT_FREQ_FK2 ON PSP_EFFECTIVE_DEPOSIT_FREQ
(PAYMENT_TEMPLATE_FREQUENCY_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt Index PSP_EFFECTIVE_DEPOSIT_FREQ_FK1;
Prompt drop Index PSP_EFFECTIVE_DEPOSIT_FREQ_FK1;
--DROP INDEX PSP_EFFECTIVE_DEPOSIT_FREQ_FK1;
Prompt Index PSP_EFFECTIVE_DEPOSIT_FREQ_FK1;
--
-- PSP_EFFECTIVE_DEPOSIT_FREQ_FK1  (Index)
--
CREATE INDEX PSP_EFFECTIVE_DEPOSIT_FREQ_FK1 ON PSP_EFFECTIVE_DEPOSIT_FREQ
(COMPANY_AGENCY_PMT_TEMPLATE_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt Table PSP_FINTXN_AGENCY_HOLD_ASSOC;
--
-- PSP_FINTXN_AGENCY_HOLD_ASSOC  (Table)
--
CREATE TABLE PSP_FINTXN_AGENCY_HOLD_ASSOC
(
  FINANCIAL_TRANSACTION_FK    VARCHAR2(255 CHAR) NOT NULL,
  COMP_AGENCY_ON_HOLD_REASON  VARCHAR2(255 CHAR) NOT NULL,
  REALM_ID                    NUMBER(19)        DEFAULT -1                    NOT NULL
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

Prompt Index PSP_FINTXN_COMP_AGENCY_HOLD;
--
-- PSP_FINTXN_COMP_AGENCY_HOLD  (Index)
--
CREATE INDEX PSP_FINTXN_COMP_AGENCY_HOLD ON PSP_FINTXN_AGENCY_HOLD_ASSOC
(COMP_AGENCY_ON_HOLD_REASON, REALM_ID)
LOGGING
NOPARALLEL;

Prompt Index PSP_FINTXN_HOLD_COMP_AGENCY;
--
-- PSP_FINTXN_HOLD_COMP_AGENCY  (Index)
--
CREATE INDEX PSP_FINTXN_HOLD_COMP_AGENCY ON PSP_FINTXN_AGENCY_HOLD_ASSOC
(FINANCIAL_TRANSACTION_FK, REALM_ID)
LOGGING
NOPARALLEL;

ALTER TABLE PSP_FINTXN_AGENCY_HOLD_ASSOC
 ADD PRIMARY KEY
 (FINANCIAL_TRANSACTION_FK, COMP_AGENCY_ON_HOLD_REASON, REALM_ID);

Prompt Index PSP_FINANCIAL_TRANSACTION_FK10;
--
-- PSP_FINANCIAL_TRANSACTION_FK10  (Index)
--
--CREATE INDEX PSP_FINANCIAL_TRANSACTION_FK10 ON PSP_FINANCIAL_TRANSACTION
--(MONEY_MOVEMENT_TRANSACTION_FK, REALM_ID)
--LOGGING
--NOPARALLEL;

Prompt Index PSP_FINANCIAL_TRANSACTION_FK9;
Prompt drop Index PSP_FINANCIAL_TRANSACTION_FK9;
DROP INDEX PSP_FINANCIAL_TRANSACTION_FK9;
Prompt Index PSP_FINANCIAL_TRANSACTION_FK9;
--
-- PSP_FINANCIAL_TRANSACTION_FK9  (Index)
--
--CREATE INDEX PSP_FINANCIAL_TRANSACTION_FK9 ON PSP_FINANCIAL_TRANSACTION
--(CURRENT_TRANSACTION_STATE_FK, REALM_ID)
--LOGGING
--NOPARALLEL;

Prompt Index PSP_FINANCIAL_TRANSACTION_FK8;
Prompt drop Index PSP_FINANCIAL_TRANSACTION_FK8;
DROP INDEX PSP_FINANCIAL_TRANSACTION_FK8;
Prompt Index PSP_FINANCIAL_TRANSACTION_FK8;
--
-- PSP_FINANCIAL_TRANSACTION_FK8  (Index)
--
--CREATE INDEX PSP_FINANCIAL_TRANSACTION_FK8 ON PSP_FINANCIAL_TRANSACTION
--(TRANSACTION_TYPE_FK, REALM_ID)
--LOGGING
--NOPARALLEL;

Prompt Index PSP_FINANCIAL_TRANSACTION_FK7;
Prompt drop Index PSP_FINANCIAL_TRANSACTION_FK7;
DROP INDEX PSP_FINANCIAL_TRANSACTION_FK7;
Prompt Index PSP_FINANCIAL_TRANSACTION_FK7;
--
-- PSP_FINANCIAL_TRANSACTION_FK7  (Index)
--
--CREATE INDEX PSP_FINANCIAL_TRANSACTION_FK7 ON PSP_FINANCIAL_TRANSACTION
--(PAYCHECK_SPLIT_FK, REALM_ID)
--LOGGING
--NOPARALLEL;

Prompt Index PSP_FINANCIAL_TRANSACTION_FK6;
Prompt drop Index PSP_FINANCIAL_TRANSACTION_FK6;
DROP INDEX PSP_FINANCIAL_TRANSACTION_FK6;
Prompt Index PSP_FINANCIAL_TRANSACTION_FK6;
--
-- PSP_FINANCIAL_TRANSACTION_FK6  (Index)
--
--CREATE INDEX PSP_FINANCIAL_TRANSACTION_FK6 ON PSP_FINANCIAL_TRANSACTION
--(PAYROLL_RUN_FK, REALM_ID)
--LOGGING
--NOPARALLEL;

Prompt Index PSP_FINANCIAL_TRANSACTION_FK5;
Prompt drop Index PSP_FINANCIAL_TRANSACTION_FK5;
DROP INDEX PSP_FINANCIAL_TRANSACTION_FK5;
Prompt Index PSP_FINANCIAL_TRANSACTION_FK5;
--
-- PSP_FINANCIAL_TRANSACTION_FK5  (Index)
--
--CREATE INDEX PSP_FINANCIAL_TRANSACTION_FK5 ON PSP_FINANCIAL_TRANSACTION
--(COMPANY_FK, REALM_ID)
--LOGGING
--NOPARALLEL;

Prompt Index PSP_FINANCIAL_TRANSACTION_FK4;
Prompt drop Index PSP_FINANCIAL_TRANSACTION_FK4;
DROP INDEX PSP_FINANCIAL_TRANSACTION_FK4;
Prompt Index PSP_FINANCIAL_TRANSACTION_FK4;
--
-- PSP_FINANCIAL_TRANSACTION_FK4  (Index)
--
--CREATE INDEX PSP_FINANCIAL_TRANSACTION_FK4 ON PSP_FINANCIAL_TRANSACTION
--(DEBIT_BANK_ACCOUNT_FK, REALM_ID)
--LOGGING
--NOPARALLEL;

Prompt Index PSP_FINANCIAL_TRANSACTION_FK3;
Prompt drop Index PSP_FINANCIAL_TRANSACTION_FK3;
DROP INDEX PSP_FINANCIAL_TRANSACTION_FK3;
Prompt Index PSP_FINANCIAL_TRANSACTION_FK3;
--
-- PSP_FINANCIAL_TRANSACTION_FK3  (Index)
--
CREATE INDEX PSP_FINANCIAL_TRANSACTION_FK3 ON PSP_FINANCIAL_TRANSACTION
(CREDIT_BANK_ACCOUNT_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt Constraint C_PSP_TRANSACTION_TYPE0;
ALTER TABLE PSP_TRANSACTION_TYPE
 DROP CONSTRAINT C_PSP_TRANSACTION_TYPE0;
ALTER TABLE PSP_TRANSACTION_TYPE
 ADD CONSTRAINT C_PSP_TRANSACTION_TYPE0
 CHECK (TRANSACTION_TYPE_CD IN('BadDebtRecovery', 'EmployeeDdCredit', 'EmployeeDdReversalDebit', 'EmployeeEscalationCredit', 'EmployerDdDebit', 'EmployerDdRedebit', 'EmployerDdRefundCredit', 'EmployerDdRejectRefundCredit', 'EmployerDdReturnedRefundCredit', 'EmployerDdReversalRefundCredit', 'EmployerDoublePaymentRefundCredit', 'EmployerEscalationCredit', 'EmployerFeeDebit', 'EmployerFeeRedebit', 'EmployerFeeRefundCredit', 'DdFraud', 'EmployerWriteOff', 'Intuit5DayReturnTransfer', 'IntuitEmployeeReturnTransfer', 'IntuitFeeTransfer', 'EmployerFeeReturnedRefundCredit', 'IntuitEmployerVerificationReturnTransfer', 'EmployerVerificationDebit', 'EmployerTaxRefundCredit', 'ServiceSalesAndUseTax', 'ServiceSalesAndUseTaxRefundCredit', 'UntimelyReturnPostWriteOff', 'UntimelyReturnPreWriteOff', 'ServiceSalesAndUseTaxRedebit', 'ServiceSalesAndUseTaxReturnedRefundCredit', 'BadDebtRecoveryFee', 'BadDebtRecoverySalesAndUseTax', 'EmployerWriteOffFee', 'EmployerWriteOffSalesAndUseTax', 'EmployerFraudOrEscalationRefundCredit', 'EmployerTaxRedebit', 'EmployerTaxCredit', 'EmployerTaxReturnedCredit', 'AgencyTaxDebit', 'AgencyTaxCredit', 'EmployerTaxDebit', 'EmployerTaxReturnedRefundCredit', 'AgencyTaxRecredit', 'AgencyTaxRedebit'));

Prompt Constraint C_PSP_EVENT_DETAIL_TYPE0;
ALTER TABLE PSP_EVENT_DETAIL_TYPE
 DROP CONSTRAINT C_PSP_EVENT_DETAIL_TYPE0;
ALTER TABLE PSP_EVENT_DETAIL_TYPE
 ADD CONSTRAINT C_PSP_EVENT_DETAIL_TYPE0
 CHECK (EVENT_DETAIL_TYPE_CD IN('ACHEventCd', 'BankAccountNumber', 'BankAccountRoutingNumber', 'EmployeeName', 'SourcePayrollRunId', 'PayrollCancellationReason', 'CallerApplication', 'CompanyBankAccountId', 'ACHReturnReasonCode', 'BankAccountType', 'CancellationDateTime', 'BankAccountName', 'AdjustedERSettlementDate', 'AdjustedEESettlementDate', 'PayrollRunId', 'PayrollCancellationScope', 'EmployeeId', 'LimitAmount', 'LimitType', 'ViolationAmount', 'OldCoaName', 'NewCoaName', 'CoaNameChangeByAgent', 'OldServiceStatus', 'NewServiceStatus', 'OldLimitAmount', 'NewLimitAmount', 'OldBAStatus', 'NewBAStatus', 'ManualStrikeReasonDescription', 'FeeType', 'RefundStatus', 'RefundStatusReason', 'ReturnType', 'CompanyServiceId', 'FinancialTransactionId', 'TransmissionId', 'ErrorCode', 'ErrorMessage', 'ErrorType', 'OldStringValue', 'NewStringValue', 'PaycheckDate', 'TransmissionDateTime', 'OffloadDate', 'PaycheckId', 'PaycheckAmount', 'PendingAutoRedebit', 'FeeAmount', 'OriginalTransactionDateTime', 'RefundedFeeBillingDetailId', 'ReversalAmount', 'StrikeReason', 'ReasonDescription', 'NoteText', 'NumberOfBackdatedDays', 'StrikeRemovalReason', 'FailureReason', 'TerminationDateTime', 'QBToken', 'PSPToken', 'UnsupportedVersionNumber', 'UnsupportedReleaseNumber', 'NSFSubType', 'PayrollStatus', 'OldAccountNumber', 'NewAccountNumber', 'OldRoutingNumber', 'NewRoutingNumber', 'OldAccountType', 'NewAccountType', 'EmployeeBankAccountId', 'VerificationStatus', 'PayrollRejectedReason', 'CompanyEventId', 'ServiceStatus', 'OldOnHoldReason', 'NewOnHoldReason', 'CollectionStage', 'AS400EventName', 'AS400EventToken', 'AS400EventOFX', 'WireExpectedDate', 'IntuitInitiated', 'Details', 'FraudEventCategory', 'ContactId', 'NewAmount', 'OldAmount', 'OldDate', 'NewDate', 'OldPayrollStatus', 'NewPayrollStatus', 'SourceBankAccountId', 'BankAccountId', 'SourcePaycheckId', 'FeeBillingDetailId', 'RefundAmount', 'ExpectedToken', 'ReceivedToken', 'Timestamp', 'UniqueIdentifier', 'UserId', 'ServiceCode', 'AgencyId', 'EnrollmentType', 'CheckListItemType', 'OldAgencyStatus', 'NewAgencyStatus', 'OldPaymentMethod', 'NewPaymentMethod', 'OriginalMMT', 'NewMMT', 'ReferenceNumber', 'PaymentStatus', 'EFERejectionReason', 'PaymentInitiationDate', 'PaymentDueDate', 'PaymentMethod'));

Prompt Constraint C_PSP_ACTION_EVENT0;
ALTER TABLE PSP_ACTION_EVENT
 DROP CONSTRAINT C_PSP_ACTION_EVENT0;
ALTER TABLE PSP_ACTION_EVENT
 ADD CONSTRAINT C_PSP_ACTION_EVENT0
 CHECK (CODE IN('FinancialTransactionVoidTx', 'FinancialTransactionCancel', 'IssueReissueRefundEr', 'TxStateHistory', 'DDTransactionCancel', 'DDTransactionReverse', 'DDRedebitAdd', 'DDRedebitRecord', 'ERFeeAdd', 'BadDebtWriteOff', 'BadDebtRecover', 'EEReturnTransfer', 'FeeTransfer', 'Intuit5DayReturnTransfer', 'DDRefund', 'ERReturnRefund', 'EEReturnRefund', 'ERWireExpected', 'RefundRebillFee', 'DDRedebitEdit', 'ERFraudOrEscalationRefund'));

ALTER TABLE PSP_COMPANY_AGENCY
 ADD CONSTRAINT C_PSP_COMPANY_AGENCY0
 CHECK (COMPANY_AGENCY_STATUS_CODE IN('Active', 'AgencyRejection', 'Inactive', 'ManualHold'));

Prompt Constraint C_PSP_MONEY_MOVEMENT_TRANS0;
ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 DROP CONSTRAINT C_PSP_MONEY_MOVEMENT_TRANS0;
ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 ADD CONSTRAINT C_PSP_MONEY_MOVEMENT_TRANS0
 CHECK (STATUS IN('Canceled', 'Created', 'Executed', 'InProcess'));

Prompt Constraint C_PSP_MONEY_MOVEMENT_TRANS1;
ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 DROP CONSTRAINT C_PSP_MONEY_MOVEMENT_TRANS1;
ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 ADD CONSTRAINT C_PSP_MONEY_MOVEMENT_TRANS1
 CHECK (MONEY_MOVEMENT_PAYMENT_METHOD IN('ACHDebit', 'ACHCredit', 'CheckPayment', 'ACHDirectDeposit', 'WirePayment', 'EFE'));

ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 ADD CONSTRAINT C_PSP_MONEY_MOVEMENT_TRANS2
 CHECK (E_F_E_PAYMENT_STATUS IN('AcknowledgedByAgency', 'DuplicatedEFEPayment', 'FailedEFEValidation', 'RejectedByAgency', 'SentToEFE'));

ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 ADD CONSTRAINT C_PSP_MONEY_MOVEMENT_TRANS3
 CHECK (MANUAL_PAYMENT_STATUS IN('Issued', 'Cleared', 'Recalled', 'Voided'));

Prompt Constraint PSP_MONEY_MOVEMENT_TRANSAC_FK1;
--ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
-- DROP CONSTRAINT PSP_MONEY_MOVEMENT_TRANSAC_FK1;
ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 ADD CONSTRAINT PSP_MONEY_MOVEMENT_TRANSAC_FK1
 FOREIGN KEY (EFE_PYMT_BATCH_FK, REALM_ID)
 REFERENCES PSP_EFE_PMT_BATCH (EFE_PMT_BATCH_SEQ,REALM_ID);

Prompt Constraint PSP_MONEY_MOVEMENT_TRANSAC_FK3;
ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 DROP CONSTRAINT PSP_MONEY_MOVEMENT_TRANSAC_FK3;
ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 ADD CONSTRAINT PSP_MONEY_MOVEMENT_TRANSAC_FK3
 FOREIGN KEY (PAYMENT_FREQUENCY_FK, REALM_ID)
 REFERENCES PSP_PMT_TEMPLATE_FREQUENCY (PAYMENT_TEMPLATE_FREQUENCY_ID,REALM_ID);

Prompt Constraint PSP_MONEY_MOVEMENT_TRANSAC_FK4;
ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 DROP CONSTRAINT PSP_MONEY_MOVEMENT_TRANSAC_FK4;
ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 ADD CONSTRAINT PSP_MONEY_MOVEMENT_TRANSAC_FK4
 FOREIGN KEY (AUTH_USER_FK, REALM_ID)
 REFERENCES PSP_AUTH_USER (AUTH_USER_SEQ,REALM_ID);

Prompt Constraint C_PSP_COMPANY_EVENT_DETAIL0;
ALTER TABLE PSP_COMPANY_EVENT_DETAIL
 DROP CONSTRAINT C_PSP_COMPANY_EVENT_DETAIL0;
ALTER TABLE PSP_COMPANY_EVENT_DETAIL
 ADD CONSTRAINT C_PSP_COMPANY_EVENT_DETAIL0
 CHECK (EVENT_DETAIL_TYPE_CD IN('ACHEventCd', 'BankAccountNumber', 'BankAccountRoutingNumber', 'EmployeeName', 'SourcePayrollRunId', 'PayrollCancellationReason', 'CallerApplication', 'CompanyBankAccountId', 'ACHReturnReasonCode', 'BankAccountType', 'CancellationDateTime', 'BankAccountName', 'AdjustedERSettlementDate', 'AdjustedEESettlementDate', 'PayrollRunId', 'PayrollCancellationScope', 'EmployeeId', 'LimitAmount', 'LimitType', 'ViolationAmount', 'OldCoaName', 'NewCoaName', 'CoaNameChangeByAgent', 'OldServiceStatus', 'NewServiceStatus', 'OldLimitAmount', 'NewLimitAmount', 'OldBAStatus', 'NewBAStatus', 'ManualStrikeReasonDescription', 'FeeType', 'RefundStatus', 'RefundStatusReason', 'ReturnType', 'CompanyServiceId', 'FinancialTransactionId', 'TransmissionId', 'ErrorCode', 'ErrorMessage', 'ErrorType', 'OldStringValue', 'NewStringValue', 'PaycheckDate', 'TransmissionDateTime', 'OffloadDate', 'PaycheckId', 'PaycheckAmount', 'PendingAutoRedebit', 'FeeAmount', 'OriginalTransactionDateTime', 'RefundedFeeBillingDetailId', 'ReversalAmount', 'StrikeReason', 'ReasonDescription', 'NoteText', 'NumberOfBackdatedDays', 'StrikeRemovalReason', 'FailureReason', 'TerminationDateTime', 'QBToken', 'PSPToken', 'UnsupportedVersionNumber', 'UnsupportedReleaseNumber', 'NSFSubType', 'PayrollStatus', 'OldAccountNumber', 'NewAccountNumber', 'OldRoutingNumber', 'NewRoutingNumber', 'OldAccountType', 'NewAccountType', 'EmployeeBankAccountId', 'VerificationStatus', 'PayrollRejectedReason', 'CompanyEventId', 'ServiceStatus', 'OldOnHoldReason', 'NewOnHoldReason', 'CollectionStage', 'AS400EventName', 'AS400EventToken', 'AS400EventOFX', 'WireExpectedDate', 'IntuitInitiated', 'Details', 'FraudEventCategory', 'ContactId', 'NewAmount', 'OldAmount', 'OldDate', 'NewDate', 'OldPayrollStatus', 'NewPayrollStatus', 'SourceBankAccountId', 'BankAccountId', 'SourcePaycheckId', 'FeeBillingDetailId', 'RefundAmount', 'ExpectedToken', 'ReceivedToken', 'Timestamp', 'UniqueIdentifier', 'UserId', 'ServiceCode', 'AgencyId', 'EnrollmentType', 'CheckListItemType', 'OldAgencyStatus', 'NewAgencyStatus', 'OldPaymentMethod', 'NewPaymentMethod', 'OriginalMMT', 'NewMMT', 'ReferenceNumber', 'PaymentStatus', 'EFERejectionReason', 'PaymentInitiationDate', 'PaymentDueDate', 'PaymentMethod'));

Prompt Constraint PSP_EFFECTIVE_DEPOSIT_FREQ_FK1;
--ALTER TABLE PSP_EFFECTIVE_DEPOSIT_FREQ
-- DROP CONSTRAINT PSP_EFFECTIVE_DEPOSIT_FREQ_FK1;
ALTER TABLE PSP_EFFECTIVE_DEPOSIT_FREQ
 ADD CONSTRAINT PSP_EFFECTIVE_DEPOSIT_FREQ_FK1
 FOREIGN KEY (COMPANY_AGENCY_PMT_TEMPLATE_FK, REALM_ID)
 REFERENCES PSP_COMPANYAGENCY_PMTTEMPLATE (COMPANYAGENCY_PMTTEMPLATE_SEQ,REALM_ID);

Prompt Constraint PSP_EFFECTIVE_DEPOSIT_FREQ_FK2;
--ALTER TABLE PSP_EFFECTIVE_DEPOSIT_FREQ
-- DROP CONSTRAINT PSP_EFFECTIVE_DEPOSIT_FREQ_FK2;
ALTER TABLE PSP_EFFECTIVE_DEPOSIT_FREQ
 ADD CONSTRAINT PSP_EFFECTIVE_DEPOSIT_FREQ_FK2
 FOREIGN KEY (PAYMENT_TEMPLATE_FREQUENCY_FK, REALM_ID)
 REFERENCES PSP_PMT_TEMPLATE_FREQUENCY (PAYMENT_TEMPLATE_FREQUENCY_ID,REALM_ID);

Prompt Constraint PSP_FINANCIAL_TRANSACTION_FK3;
ALTER TABLE PSP_FINANCIAL_TRANSACTION
 DROP CONSTRAINT PSP_FINANCIAL_TRANSACTION_FK3;
ALTER TABLE PSP_FINANCIAL_TRANSACTION
 ADD CONSTRAINT PSP_FINANCIAL_TRANSACTION_FK3
 FOREIGN KEY (CREDIT_BANK_ACCOUNT_FK, REALM_ID)
 REFERENCES PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ,REALM_ID);

Prompt Constraint PSP_FINANCIAL_TRANSACTION_FK4;
ALTER TABLE PSP_FINANCIAL_TRANSACTION
 DROP CONSTRAINT PSP_FINANCIAL_TRANSACTION_FK4;
ALTER TABLE PSP_FINANCIAL_TRANSACTION
 ADD CONSTRAINT PSP_FINANCIAL_TRANSACTION_FK4
 FOREIGN KEY (DEBIT_BANK_ACCOUNT_FK, REALM_ID)
 REFERENCES PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ,REALM_ID);

Prompt Constraint PSP_FINANCIAL_TRANSACTION_FK5;
ALTER TABLE PSP_FINANCIAL_TRANSACTION
 DROP CONSTRAINT PSP_FINANCIAL_TRANSACTION_FK5;
ALTER TABLE PSP_FINANCIAL_TRANSACTION
 ADD CONSTRAINT PSP_FINANCIAL_TRANSACTION_FK5
 FOREIGN KEY (COMPANY_FK, REALM_ID)
 REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

Prompt Constraint PSP_FINANCIAL_TRANSACTION_FK6;
ALTER TABLE PSP_FINANCIAL_TRANSACTION
 DROP CONSTRAINT PSP_FINANCIAL_TRANSACTION_FK6;
ALTER TABLE PSP_FINANCIAL_TRANSACTION
 ADD CONSTRAINT PSP_FINANCIAL_TRANSACTION_FK6
 FOREIGN KEY (PAYROLL_RUN_FK, REALM_ID)
 REFERENCES PSP_PAYROLL_RUN (PAYROLL_RUN_SEQ,REALM_ID);

Prompt Constraint PSP_FINANCIAL_TRANSACTION_FK7;
ALTER TABLE PSP_FINANCIAL_TRANSACTION
 DROP CONSTRAINT PSP_FINANCIAL_TRANSACTION_FK7;
ALTER TABLE PSP_FINANCIAL_TRANSACTION
 ADD CONSTRAINT PSP_FINANCIAL_TRANSACTION_FK7
 FOREIGN KEY (PAYCHECK_SPLIT_FK, REALM_ID)
 REFERENCES PSP_PAYCHECK_SPLIT (PAYCHECK_SPLIT_SEQ,REALM_ID);

Prompt Constraint PSP_FINANCIAL_TRANSACTION_FK8;
ALTER TABLE PSP_FINANCIAL_TRANSACTION
 DROP CONSTRAINT PSP_FINANCIAL_TRANSACTION_FK8;
ALTER TABLE PSP_FINANCIAL_TRANSACTION
 ADD CONSTRAINT PSP_FINANCIAL_TRANSACTION_FK8
 FOREIGN KEY (TRANSACTION_TYPE_FK, REALM_ID)
 REFERENCES PSP_TRANSACTION_TYPE (TRANSACTION_TYPE_CD,REALM_ID);

Prompt Constraint PSP_FINANCIAL_TRANSACTION_FK9;
ALTER TABLE PSP_FINANCIAL_TRANSACTION
 DROP CONSTRAINT PSP_FINANCIAL_TRANSACTION_FK9;
ALTER TABLE PSP_FINANCIAL_TRANSACTION
 ADD CONSTRAINT PSP_FINANCIAL_TRANSACTION_FK9
 FOREIGN KEY (CURRENT_TRANSACTION_STATE_FK, REALM_ID)
 REFERENCES PSP_TRANSACTION_STATE (TRANSACTION_STATE_CD,REALM_ID);

ALTER TABLE PSP_AGENCY_STAT_TXN_TYPE
 ADD CONSTRAINT PSP_AGENCY_STATUS_TRANSACT_FK1
 FOREIGN KEY (AGENCY_STATUS_FK, REALM_ID)
 REFERENCES PSP_AGENCY_STATUS (AGENCY_STATUS_CD,REALM_ID);

ALTER TABLE PSP_AGENCY_STAT_TXN_TYPE
 ADD CONSTRAINT PSP_AGENCY_STATUS_TRANSACT_FK2
 FOREIGN KEY (TRANSACTION_TYPE_FK, REALM_ID)
 REFERENCES PSP_TRANSACTION_TYPE (TRANSACTION_TYPE_CD,REALM_ID);

ALTER TABLE PSP_PAYROLL_TAX
 ADD CONSTRAINT PSP_PAYROLL_TAX_FK1
 FOREIGN KEY (LAW_FK, REALM_ID)
 REFERENCES PSP_LAW (LAW_ID,REALM_ID);

ALTER TABLE PSP_PAYROLL_TAX
 ADD CONSTRAINT PSP_PAYROLL_TAX_FK2
 FOREIGN KEY (PAYROLL_RUN_FK, REALM_ID)
 REFERENCES PSP_PAYROLL_RUN (PAYROLL_RUN_SEQ,REALM_ID);

ALTER TABLE PSP_PMT_TEMPLATE_FREQUENCY
 ADD CONSTRAINT PSP_PAYMENT_TEMPLATE_FREQU_FK1
 FOREIGN KEY (PAYMENT_TEMPLATE_FK, REALM_ID)
 REFERENCES PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD,REALM_ID);

ALTER TABLE PSP_EFERETURN
 ADD CONSTRAINT PSP_EFERETURN_FK1
 FOREIGN KEY (MONEY_MOVEMENT_TRANSACTION_FK, REALM_ID)
 REFERENCES PSP_MONEY_MOVEMENT_TRANSACTION (MONEY_MOVEMENT_TRANSACTION_SEQ,REALM_ID);

ALTER TABLE PSP_COMPANY_LAW
 ADD CONSTRAINT PSP_COMPANY_LAW_FK1
 FOREIGN KEY (COMPANY_AGENCY_FK, REALM_ID)
 REFERENCES PSP_COMPANY_AGENCY (COMPANY_AGENCY_SEQ,REALM_ID);

ALTER TABLE PSP_COMPANY_LAW
 ADD CONSTRAINT PSP_COMPANY_LAW_FK2
 FOREIGN KEY (LAW_FK, REALM_ID)
 REFERENCES PSP_LAW (LAW_ID,REALM_ID);

ALTER TABLE PSP_COMPANYAGENCY_PMTTEMPLATE
 ADD CONSTRAINT PSP_COMPANY_AGENCY_PAYMENT_FK1
 FOREIGN KEY (COMPANY_AGENCY_FK, REALM_ID)
 REFERENCES PSP_COMPANY_AGENCY (COMPANY_AGENCY_SEQ,REALM_ID);

ALTER TABLE PSP_COMPANYAGENCY_PMTTEMPLATE
 ADD CONSTRAINT PSP_COMPANY_AGENCY_PAYMENT_FK2
 FOREIGN KEY (PAYMENT_TEMPLATE_FK, REALM_ID)
 REFERENCES PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD,REALM_ID);

ALTER TABLE PSP_COMP_AGENCY_ON_HOLD_REASON
 ADD CONSTRAINT PSP_COMPANY_AGENCY_ON_HOLD_FK1
 FOREIGN KEY (COMPANY_AGENCY_FK, REALM_ID)
 REFERENCES PSP_COMPANY_AGENCY (COMPANY_AGENCY_SEQ,REALM_ID);

ALTER TABLE PSP_FINTXN_AGENCY_HOLD_ASSOC
 ADD CONSTRAINT PSP_FINTXN_HOLD_COMP_AGENCY
 FOREIGN KEY (FINANCIAL_TRANSACTION_FK, REALM_ID)
 REFERENCES PSP_FINANCIAL_TRANSACTION (FINANCIAL_TRANSACTION_SEQ,REALM_ID);

ALTER TABLE PSP_FINTXN_AGENCY_HOLD_ASSOC
 ADD CONSTRAINT PSP_FINTXN_COMP_AGENCY_HOLD
 FOREIGN KEY (COMP_AGENCY_ON_HOLD_REASON, REALM_ID)
 REFERENCES PSP_COMP_AGENCY_ON_HOLD_REASON (COMP_AGENCY_ON_HOLD_REASON_SEQ,REALM_ID);

ALTER TABLE PSP_PAYMENT_TEMPLATE
 ADD CONSTRAINT PSP_PAYMENT_TEMPLATE_FK1
 FOREIGN KEY (AGENCY_FK, REALM_ID)
 REFERENCES PSP_AGENCY (AGENCY_ID,REALM_ID);

ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 ADD CONSTRAINT PSP_MONEY_MOVEMENT_TRANSAC_FK5
 FOREIGN KEY (COMPANY_FK, REALM_ID)
 REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 ADD CONSTRAINT PSP_MONEYMOVEMENTTRANSACTI_FK1
 FOREIGN KEY (ORIGINAL_TRANSACTION_FK, REALM_ID)
 REFERENCES PSP_MONEY_MOVEMENT_TRANSACTION (MONEY_MOVEMENT_TRANSACTION_SEQ,REALM_ID);

ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 ADD CONSTRAINT PSP_MONEY_MOVEMENT_TRANSAC_FK6
 FOREIGN KEY (OFFLOAD_BATCH_FK, REALM_ID)
 REFERENCES PSP_OFFLOAD_BATCH (OFFLOAD_BATCH_SEQ,REALM_ID);

ALTER TABLE PSP_FINANCIAL_TRANSACTION
 ADD CONSTRAINT PSP_FINANCIAL_TRANSACTION_FK10
 FOREIGN KEY (MONEY_MOVEMENT_TRANSACTION_FK, REALM_ID)
 REFERENCES PSP_MONEY_MOVEMENT_TRANSACTION (MONEY_MOVEMENT_TRANSACTION_SEQ,REALM_ID);

 
PROMPT finishedDBUpgrade_002.000.000.031.sql