--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--                                                                      --
-- Please review the script before using it to make sure it won't       --
-- cause any unacceptable data loss.                                    --
--                                                                      --
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
ALTER TABLE PSP_BANK_ACCOUNT
 DROP CONSTRAINT BANKACCOUNTTYPE195;

ALTER TABLE PSP_OFFER
 DROP CONSTRAINT DISCOUNTTYPE119;

ALTER TABLE PSP_OFFER
 DROP CONSTRAINT OFFERBEGINEVENT122;

ALTER TABLE PSP_OFFER
 DROP CONSTRAINT OFFERENDEVENT123;

ALTER TABLE PSP_NACHAFILE
 DROP CONSTRAINT NACHAFILESTATUS105;

ALTER TABLE PSP_NACHAFILE
 DROP CONSTRAINT NACHAFILETYPE106;

ALTER TABLE PSP_GEMS_UPLOAD_BATCH
 DROP CONSTRAINT GEMSUPLOADBATCHSTATUS85;

ALTER TABLE PSP_GEMS_UPLOAD_BATCH
 DROP CONSTRAINT REPORTINGFREQUENCY82;

ALTER TABLE PSP_DICRFILE
 DROP CONSTRAINT DICRFILESTATUS64;

ALTER TABLE PSP_TRANSACTION_TYPE
 DROP CONSTRAINT NACHABATCHTYPE423;

ALTER TABLE PSP_TRANSACTION_TYPE
 DROP CONSTRAINT TRANSACTIONASSOCIATIONTYPE421;

ALTER TABLE PSP_TRANSACTION_TYPE
 DROP CONSTRAINT TRANSACTIONCATEGORY420;

ALTER TABLE PSP_TRANSACTION_TYPE
 DROP CONSTRAINT TRANSACTIONTYPECODE419;

ALTER TABLE PSP_TRANSACTION_TYPE
 DROP CONSTRAINT TRANSACTIONTYPEGROUPCODE424;

ALTER TABLE PSP_TRANSACTION_STATE
 DROP CONSTRAINT TRANSACTIONSTATECODE416;

ALTER TABLE PSP_SOURCE_SYSTEM
 DROP CONSTRAINT SOURCESYSTEMCODE413;

ALTER TABLE PSP_SERVICE
 DROP CONSTRAINT SERVICECODE410;

ALTER TABLE PSP_LEDGER_ACCOUNT
 DROP CONSTRAINT LEDGERACCOUNTCODE399;

ALTER TABLE PSP_LEDGER_ACCOUNT
 DROP CONSTRAINT LEDGERACCOUNTTYPE402;

ALTER TABLE PSP_LEDGER_ACCOUNT
 DROP CONSTRAINT LEDGERBALANCECALCULATIONR401;

ALTER TABLE PSP_LEDGER_ACCOUNT
 DROP CONSTRAINT REPORTINGFREQUENCY403;

ALTER TABLE PSP_EVENT_TYPE
 DROP CONSTRAINT EVENTTYPECODE392;

ALTER TABLE PSP_SYSTEM_CAPABILITY
 DROP CONSTRAINT SYSTEMCAPABILITYCODE388;

ALTER TABLE PSP_SERVICE_STATUS
 DROP CONSTRAINT SERVICESTATUSCODE379;

ALTER TABLE PSP_EVENT_DETAIL_TYPE
 DROP CONSTRAINT EVENTDETAILTYPECODE368;

ALTER TABLE PSP_COLLECTION_STAGE
 DROP CONSTRAINT COLLECTIONSTAGECODE362;

ALTER TABLE PSP_AUTH_OPERATION
 DROP CONSTRAINT OPERATIONID359;

ALTER TABLE PSP_ACTION_EVENT
 DROP CONSTRAINT ACTIONEVENTCODE353;

ALTER TABLE PSP_ACTION_EVENT
 DROP CONSTRAINT ACTIONTYPE355;

ALTER TABLE PSP_TRANSACTION_RETURN_BATCH
 DROP CONSTRAINT TRANSACTIONRETURNBATCHSTA351;

ALTER TABLE PSP_SOURCE_PAYROLL_PARAMETER
 DROP CONSTRAINT SOURCEPAYROLLPARAMETERCODE333;

ALTER TABLE PSP_SOURCE_PAYROLL_PARAMETER
 DROP CONSTRAINT SOURCESYSTEMCODE337;

ALTER TABLE PSP_OFFLOAD_BATCH
 DROP CONSTRAINT OFFLOADBATCHSTATUS308;

ALTER TABLE PSP_INDIVIDUAL
 DROP CONSTRAINT COMMUNICATIONTYPE295;

ALTER TABLE PSP_INDIVIDUAL
 DROP CONSTRAINT GENDER292;

ALTER TABLE PSP_FEE
 DROP CONSTRAINT FEETYPECODE279;

ALTER TABLE PSP_COMPANY
 DROP CONSTRAINT SOURCESYSTEMCODE216;

ALTER TABLE PSP_SOURCE_SYSTEM_TRANSMISSION
 DROP CONSTRAINT SOURCESYSTEMCODE163;

ALTER TABLE PSP_SOURCE_SYSTEM_TRANSMISSION
 DROP CONSTRAINT SOURCESYSTEMCODE172;

ALTER TABLE PSP_SOURCE_SYSTEM_TRANSMISSION
 DROP CONSTRAINT TRANSMISSIONTYPE168;

ALTER TABLE PSP_PAYROLL_SUBTYPE
 DROP CONSTRAINT PAYROLLSUBTYPECODE147;

ALTER TABLE PSP_PAYROLL_RUN_ACTION
 DROP CONSTRAINT PAYROLLSTATUS146;

ALTER TABLE PSP_ON_HOLD_REASON
 DROP CONSTRAINT SERVICESUBSTATUSCODE143;

ALTER TABLE PSP_OFFERING_SVCCHG_GRP
 DROP CONSTRAINT OFFERINGSERVICECHARGETYPE138;

ALTER TABLE PSP_LEDGER_ACCOUNT_ACTION
 DROP CONSTRAINT CREDITDEBITCODE90;

ALTER TABLE PSP_INTUIT_BA_BT_FT
 DROP CONSTRAINT NACHABATCHTYPE89;

ALTER TABLE PSP_INTUIT_BA_BT_FT
 DROP CONSTRAINT NACHAFILETYPE88;

ALTER TABLE PSP_COMPANY_EVENT
 DROP CONSTRAINT COMPANYEVENTSTATUS44;

ALTER TABLE PSP_COMPANY_EVENT
 DROP CONSTRAINT EVENTTYPECODE45;

ALTER TABLE PSP_ASSIGNED_DEPOSIT_FREQUENCY
 DROP CONSTRAINT DEPOSITFREQUENCYSOURCE17;

ALTER TABLE PSP_SERVICE_SUB_STATUS
 DROP CONSTRAINT SERVICESUBSTATUSCODE384;

ALTER TABLE PSP_PAYROLL_RUN
 DROP CONSTRAINT PAYROLLSTATUS328;

ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 DROP CONSTRAINT PAYMENTMETHOD306;

ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 DROP CONSTRAINT PAYMENTSTATUS305;

ALTER TABLE PSP_INTUIT_BANK_ACC_TXN_TYPE
 DROP CONSTRAINT CREDITDEBITCODE301;

ALTER TABLE PSP_EMPLOYEE
 DROP CONSTRAINT EMPLOYEESTATUS269;

ALTER TABLE PSP_CONTACT
 DROP CONSTRAINT CONTACTROLE235;

ALTER TABLE PSP_COMPANY_SERVICE
 DROP CONSTRAINT SERVICESUBSTATUSCODE231;

ALTER TABLE PSP_COMPANY_BANK_ACCOUNT
 DROP CONSTRAINT BANKACCOUNTSTATUS223;

ALTER TABLE PSP_ROLE_SUB_STATUS
 DROP CONSTRAINT SUBSTATUSCHANGETYPE158;

ALTER TABLE PSP_ENTRY_DETAIL_RECORD
 DROP CONSTRAINT CREDITDEBITCODE67;

ALTER TABLE PSP_COMPANY_EVENT_DETAIL
 DROP CONSTRAINT EVENTDETAILTYPECODE48;

ALTER TABLE PSP_TRANSACTION_RETURN
 DROP CONSTRAINT TRANSACTIONRETURNSTATUSCO347;

ALTER TABLE PSP_EMPLOYEE_BANK_ACCOUNT
 DROP CONSTRAINT BANKACCOUNTSTATUS275;

ALTER TABLE PSP_FINANCIAL_TRANSACTION
 DROP CONSTRAINT BANKACCOUNTOWNERTYPE284;

ALTER TABLE PSP_FINANCIAL_TRANSACTION
 DROP CONSTRAINT BANKACCOUNTOWNERTYPE285;

ALTER TABLE PSP_FINANCIAL_TRANSACTION
 DROP CONSTRAINT SETTLEMENTTYPE283;

ALTER TABLE PSP_FINANCIAL_TRANSACTION
 DROP CONSTRAINT PSP_FINANCIALTRANSACTION_FK2;

ALTER TABLE PSP_BILLING_DETAIL
 DROP CONSTRAINT OFFERINGSERVICECHARGETYPE36;

ALTER TABLE PSP_BILLING_DETAIL
 DROP CONSTRAINT SERVICECODE23;

REVOKE DELETE, INSERT, SELECT, UPDATE ON  PSP_TRANSMISSION_ERROR_EVENT FROM PSPAPP_ROLE;

REVOKE DELETE, INSERT, SELECT, UPDATE ON  PSP_STRIKE_EVENT FROM PSPAPP_ROLE;

REVOKE DELETE, INSERT, SELECT, UPDATE ON  PSP_SERV_STATUS_CHANGE_EVENT FROM PSPAPP_ROLE;

REVOKE DELETE, INSERT, SELECT, UPDATE ON  PSP_REVERSAL_RETURN_EVENT FROM PSPAPP_ROLE;

REVOKE DELETE, INSERT, SELECT, UPDATE ON  PSP_REVERSAL_REQUESTED_EVENT FROM PSPAPP_ROLE;

REVOKE DELETE, INSERT, SELECT, UPDATE ON  PSP_REVERSAL_OK_EVENT FROM PSPAPP_ROLE;

REVOKE DELETE, INSERT, SELECT, UPDATE ON  PSP_NSF_EVENT FROM PSPAPP_ROLE;

REVOKE DELETE, INSERT, SELECT, UPDATE ON  PSP_NOC_EVENT FROM PSPAPP_ROLE;

REVOKE DELETE, INSERT, SELECT, UPDATE ON  PSP_LIMIT_INCREASE_EVENT FROM PSPAPP_ROLE;

REVOKE DELETE, INSERT, SELECT, UPDATE ON  PSP_INCORRECT_PINEVENT FROM PSPAPP_ROLE;

REVOKE DELETE, INSERT, SELECT, UPDATE ON  PSP_FEE_RETURN_EVENT FROM PSPAPP_ROLE;

REVOKE DELETE, INSERT, SELECT, UPDATE ON  PSP_FEE_CREATED_EVENT FROM PSPAPP_ROLE;

REVOKE DELETE, INSERT, SELECT, UPDATE ON  PSP_ER_REFUND_RETURN_EVENT FROM PSPAPP_ROLE;

REVOKE DELETE, INSERT, SELECT, UPDATE ON  PSP_ERROR_INFO_EVENT FROM PSPAPP_ROLE;

REVOKE DELETE, INSERT, SELECT, UPDATE ON  PSP_DD_REJECT_EVENT FROM PSPAPP_ROLE;

REVOKE DELETE, INSERT, SELECT, UPDATE ON  PSP_DD_DEBIT_RETURN_EVENT FROM PSPAPP_ROLE;

REVOKE DELETE, INSERT, SELECT, UPDATE ON  PSP_CBA_VERIFY_RETURN_EVENT FROM PSPAPP_ROLE;

REVOKE DELETE, INSERT, SELECT, UPDATE ON  PSP_CBASTATUS_CHANGE_EVENT FROM PSPAPP_ROLE;

REVOKE DELETE, INSERT, SELECT, UPDATE ON  PSP_CBACHANGE_EVENT FROM PSPAPP_ROLE;

REVOKE DELETE, INSERT, SELECT, UPDATE ON  PSP_BA_VERIFIED_EVENT FROM PSPAPP_ROLE;

REVOKE DELETE, INSERT, SELECT, UPDATE ON  PSP_ACH_RETURN_EVENT FROM PSPAPP_ROLE;

REVOKE DELETE, INSERT, SELECT, UPDATE ON  PSP_ACCOUNT_LOCKED_EVENT FROM PSPAPP_ROLE;

Prompt drop Index PSP_ACH_RETURN_EVENT_FK2;
DROP INDEX PSP_ACH_RETURN_EVENT_FK2;

Prompt drop Index PSP_BANK_ACCOUNT_VERIFIED__FK2;
DROP INDEX PSP_BANK_ACCOUNT_VERIFIED__FK2;

Prompt drop Index PSP_CBACHANGE_EVENT_FK2;
DROP INDEX PSP_CBACHANGE_EVENT_FK2;

Prompt drop Index PSP_CBASTATUS_CHANGE_EVENT_FK2;
DROP INDEX PSP_CBASTATUS_CHANGE_EVENT_FK2;

Prompt drop Index PSP_FEE_CREATED_EVENT_FK2;
DROP INDEX PSP_FEE_CREATED_EVENT_FK2;

Prompt drop Index PSP_LIMIT_INCREASE_EVENT_FK2;
DROP INDEX PSP_LIMIT_INCREASE_EVENT_FK2;

Prompt drop Index PSP_NOC_EVENT_FK2;
DROP INDEX PSP_NOC_EVENT_FK2;

Prompt drop Index PSP_NOC_EVENT_FK3;
DROP INDEX PSP_NOC_EVENT_FK3;

Prompt drop Index PSP_REVERSAL_OK_EVENT_FK2;
DROP INDEX PSP_REVERSAL_OK_EVENT_FK2;

Prompt drop Index PSP_REVERSAL_REQUESTED_EVE_FK2;
DROP INDEX PSP_REVERSAL_REQUESTED_EVE_FK2;

Prompt drop Index PSP_SERVICE_STATUS_CHANGE__FK2;
DROP INDEX PSP_SERVICE_STATUS_CHANGE__FK2;

Prompt drop Index PSP_STRIKE_EVENT_FK2;
DROP INDEX PSP_STRIKE_EVENT_FK2;

Prompt drop Index PSP_TRANSMISSION_ERROR_EVE_FK2;
DROP INDEX PSP_TRANSMISSION_ERROR_EVE_FK2;

Prompt drop Index PSP_FINANCIALTRANSACTION_FK2;
DROP INDEX PSP_FINANCIALTRANSACTION_FK2;

Prompt drop TABLE PSP_SERV_STATUS_CHANGE_EVENT;
ALTER TABLE PSP_SERV_STATUS_CHANGE_EVENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE PSP_SERV_STATUS_CHANGE_EVENT CASCADE CONSTRAINTS;

Prompt drop TABLE PSP_REVERSAL_RETURN_EVENT;
ALTER TABLE PSP_REVERSAL_RETURN_EVENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE PSP_REVERSAL_RETURN_EVENT CASCADE CONSTRAINTS;

Prompt drop TABLE PSP_REVERSAL_REQUESTED_EVENT;
ALTER TABLE PSP_REVERSAL_REQUESTED_EVENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE PSP_REVERSAL_REQUESTED_EVENT CASCADE CONSTRAINTS;

Prompt drop TABLE PSP_REVERSAL_OK_EVENT;
ALTER TABLE PSP_REVERSAL_OK_EVENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE PSP_REVERSAL_OK_EVENT CASCADE CONSTRAINTS;

Prompt drop TABLE PSP_NSF_EVENT;
ALTER TABLE PSP_NSF_EVENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE PSP_NSF_EVENT CASCADE CONSTRAINTS;

Prompt drop TABLE PSP_NOC_EVENT;
ALTER TABLE PSP_NOC_EVENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE PSP_NOC_EVENT CASCADE CONSTRAINTS;

Prompt drop TABLE PSP_LIMIT_INCREASE_EVENT;
ALTER TABLE PSP_LIMIT_INCREASE_EVENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE PSP_LIMIT_INCREASE_EVENT CASCADE CONSTRAINTS;

Prompt drop TABLE PSP_INCORRECT_PINEVENT;
ALTER TABLE PSP_INCORRECT_PINEVENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE PSP_INCORRECT_PINEVENT CASCADE CONSTRAINTS;

Prompt drop TABLE PSP_FEE_RETURN_EVENT;
ALTER TABLE PSP_FEE_RETURN_EVENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE PSP_FEE_RETURN_EVENT CASCADE CONSTRAINTS;

Prompt drop TABLE PSP_FEE_CREATED_EVENT;
ALTER TABLE PSP_FEE_CREATED_EVENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE PSP_FEE_CREATED_EVENT CASCADE CONSTRAINTS;

Prompt drop TABLE PSP_ERROR_INFO_EVENT;
ALTER TABLE PSP_ERROR_INFO_EVENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE PSP_ERROR_INFO_EVENT CASCADE CONSTRAINTS;

Prompt drop TABLE PSP_ER_REFUND_RETURN_EVENT;
ALTER TABLE PSP_ER_REFUND_RETURN_EVENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE PSP_ER_REFUND_RETURN_EVENT CASCADE CONSTRAINTS;

Prompt drop TABLE PSP_TRANSMISSION_ERROR_EVENT;
ALTER TABLE PSP_TRANSMISSION_ERROR_EVENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE PSP_TRANSMISSION_ERROR_EVENT CASCADE CONSTRAINTS;

Prompt drop TABLE PSP_STRIKE_EVENT;
ALTER TABLE PSP_STRIKE_EVENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE PSP_STRIKE_EVENT CASCADE CONSTRAINTS;

Prompt drop TABLE PSP_DD_REJECT_EVENT;
ALTER TABLE PSP_DD_REJECT_EVENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE PSP_DD_REJECT_EVENT CASCADE CONSTRAINTS;

Prompt drop TABLE PSP_DD_DEBIT_RETURN_EVENT;
ALTER TABLE PSP_DD_DEBIT_RETURN_EVENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE PSP_DD_DEBIT_RETURN_EVENT CASCADE CONSTRAINTS;

Prompt drop TABLE PSP_CBA_VERIFY_RETURN_EVENT;
ALTER TABLE PSP_CBA_VERIFY_RETURN_EVENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE PSP_CBA_VERIFY_RETURN_EVENT CASCADE CONSTRAINTS;

Prompt drop TABLE PSP_CBASTATUS_CHANGE_EVENT;
ALTER TABLE PSP_CBASTATUS_CHANGE_EVENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE PSP_CBASTATUS_CHANGE_EVENT CASCADE CONSTRAINTS;

Prompt drop TABLE PSP_CBACHANGE_EVENT;
ALTER TABLE PSP_CBACHANGE_EVENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE PSP_CBACHANGE_EVENT CASCADE CONSTRAINTS;

Prompt drop TABLE PSP_BA_VERIFIED_EVENT;
ALTER TABLE PSP_BA_VERIFIED_EVENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE PSP_BA_VERIFIED_EVENT CASCADE CONSTRAINTS;

Prompt drop TABLE PSP_ACH_RETURN_EVENT;
ALTER TABLE PSP_ACH_RETURN_EVENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE PSP_ACH_RETURN_EVENT CASCADE CONSTRAINTS;

Prompt drop TABLE PSP_ACCOUNT_LOCKED_EVENT;
ALTER TABLE PSP_ACCOUNT_LOCKED_EVENT
 DROP PRIMARY KEY CASCADE;
DROP TABLE PSP_ACCOUNT_LOCKED_EVENT CASCADE CONSTRAINTS;

Prompt Index PSP_FINANCIALTRANSACTION_FK1;
--
-- PSP_FINANCIALTRANSACTION_FK1  (Index) 
--
CREATE INDEX PSP_FINANCIALTRANSACTION_FK1 ON PSP_FINANCIAL_TRANSACTION
(ORIGINAL_TRANSACTION_FK, REALM_ID)
LOGGING
NOPARALLEL;

ALTER TABLE PSP_BANK_ACCOUNT
 ADD CONSTRAINT BANKACCOUNTTYPE162
 CHECK (ACCOUNT_TYPE_CD IN('Checking', 'Savings'));

ALTER TABLE PSP_OFFER
 ADD CONSTRAINT DISCOUNTTYPE95
 CHECK (DISCOUNT_TYPE IN('AmountOff', 'PercentOff'));

ALTER TABLE PSP_OFFER
 ADD CONSTRAINT OFFERBEGINEVENT98
 CHECK (BEGIN_EVENT IN('SignupEvent', 'ActivationEvent', 'FirstUseEvent', 'RedemptionEvent'));

ALTER TABLE PSP_OFFER
 ADD CONSTRAINT OFFERENDEVENT99
 CHECK (END_EVENT IN('DateEvent', 'DurationEvent', 'PayrollUsageEvent'));

ALTER TABLE PSP_NACHAFILE
 ADD CONSTRAINT NACHAFILESTATUS88
 CHECK (STATUS IN('Finalized', 'InProcess', 'Transmitted', 'Archived', 'Acknowledged', 'PendingAcknowledgement', 'PendingTransmission'));

ALTER TABLE PSP_NACHAFILE
 ADD CONSTRAINT NACHAFILETYPE89
 CHECK (FILE_TYPE IN('CCD', 'PPD'));

ALTER TABLE PSP_GEMS_UPLOAD_BATCH
 ADD CONSTRAINT GEMSUPLOADBATCHSTATUS73
 CHECK (UPLOAD_STATUS IN('InProcess', 'Empty', 'Finalized', 'PendingTransmission', 'Transmitted', 'Archived', 'Superceded'));

ALTER TABLE PSP_GEMS_UPLOAD_BATCH
 ADD CONSTRAINT REPORTINGFREQUENCY70
 CHECK (BATCH_TYPE IN('Daily', 'Monthly'));

ALTER TABLE PSP_DICRFILE
 ADD CONSTRAINT DICRFILESTATUS55
 CHECK (STATUS IN('Processed', 'Archived'));

ALTER TABLE PSP_TRANSACTION_TYPE
 ADD CONSTRAINT NACHABATCHTYPE390
 CHECK (N_A_C_H_A_BATCH_TYPE IN('BookTransfer', 'Payroll', 'Reversal'));

ALTER TABLE PSP_TRANSACTION_TYPE
 ADD CONSTRAINT TRANSACTIONASSOCIATIONTYPE388
 CHECK (ASSOCIATION_TYPE IN('Reversal', 'Refund', 'Reissue', 'Redebit', 'None'));

ALTER TABLE PSP_TRANSACTION_TYPE
 ADD CONSTRAINT TRANSACTIONCATEGORY387
 CHECK (TRANSACTION_CATEGORY IN('Intuit', 'Employer', 'Employee'));

ALTER TABLE PSP_TRANSACTION_TYPE
 ADD CONSTRAINT TRANSACTIONTYPECODE386
 CHECK (TRANSACTION_TYPE_CD IN('BadDebtRecovery', 'EmployeeDdCredit', 'EmployeeDdReversalDebit', 'EmployeeEscalationCredit', 'EmployerDdDebit', 'EmployerDdRedebit', 'EmployerDdRefundCredit', 'EmployerDdRejectRefundCredit', 'EmployerDdReturnedRefundCredit', 'EmployerDdReversalRefundCredit', 'EmployerDoublePaymentRefundCredit', 'EmployerEscalationCredit', 'EmployerFeeDebit', 'EmployerFeeRedebit', 'EmployerFeeRefundCredit', 'DdFraud', 'EmployerWriteOff', 'Intuit5DayReturnTransfer', 'IntuitEmployeeReturnTransfer', 'IntuitFeeTransfer', 'EmployerFeeReturnedRefundCredit', 'IntuitEmployerVerificationReturnTransfer', 'EmployerVerificationDebit', 'ServiceSalesAndUseTax', 'ServiceSalesAndUseTaxRefundCredit', 'UntimelyReturnPostWriteOff', 'UntimelyReturnPreWriteOff', 'ServiceSalesAndUseTaxRedebit', 'ServiceSalesAndUseTaxReturnedRefundCredit', 'BadDebtRecoveryFee', 'BadDebtRecoverySalesAndUseTax', 'EmployerWriteOffFee', 'EmployerWriteOffSalesAndUseTax'));

ALTER TABLE PSP_TRANSACTION_TYPE
 ADD CONSTRAINT TRANSACTIONTYPEGROUPCODE391
 CHECK (TRANSACTION_TYPE_GROUP_CD IN('Debit', 'Redebit', 'Credit', 'Recredit', 'Writeoff', 'Recovery', 'EscalationOrFraud', 'Other'));

ALTER TABLE PSP_TRANSACTION_STATE
 ADD CONSTRAINT TRANSACTIONSTATECODE383
 CHECK (TRANSACTION_STATE_CD IN('Created', 'Executed', 'Cancelled', 'Returned', 'Completed', 'Voided'));

ALTER TABLE PSP_SOURCE_SYSTEM
 ADD CONSTRAINT SOURCESYSTEMCODE380
 CHECK (SOURCE_SYSTEM_CD IN('CRIS', 'PSP', 'EWS', 'QBOE', 'QBDT', 'AS400'));

ALTER TABLE PSP_SERVICE
 ADD CONSTRAINT SERVICECODE377
 CHECK (SERVICE_CD IN('DirectDeposit', 'Tax'));

ALTER TABLE PSP_LEDGER_ACCOUNT
 ADD CONSTRAINT LEDGERACCOUNTCODE366
 CHECK (LEDGER_ACCOUNT_CD IN('DDFutureReceivable', 'DDFutureLiability', 'DDCurrentCash', 'DDCurrentLiability', 'ERReturnReceivable', 'ERReturnCash', 'SalesAndUseTax', 'EEReturnCash', 'EEReturnLiablility', 'FeeCashRevenue', 'FeeCashBalanceSheet', 'FeeIncome', 'BadDebt'));

ALTER TABLE PSP_LEDGER_ACCOUNT
 ADD CONSTRAINT LEDGERACCOUNTTYPE369
 CHECK (LEDGER_ACCOUNT_TYPE IN('SUTax', 'Income'));

ALTER TABLE PSP_LEDGER_ACCOUNT
 ADD CONSTRAINT LEDGERBALANCECALCULATIONR368
 CHECK (BALANCE_CALCULATION_RULE IN('CreditAddsToBalance', 'DebitAddsToBalance'));

ALTER TABLE PSP_LEDGER_ACCOUNT
 ADD CONSTRAINT REPORTINGFREQUENCY370
 CHECK (REPORTING_FREQUENCY IN('Daily', 'Monthly'));

ALTER TABLE PSP_EVENT_TYPE
 ADD CONSTRAINT EVENTTYPECODE359
 CHECK (EVENT_TYPE_CD IN('AccountLocked', 'AgentNote', 'ACHReturnStatusChanged', 'EINChanged', 'BackdatedPayrollReceived', 'ACHReturn', 'ServiceStatusChange', 'CompanyBankAccountStatusChange', 'LimitViolation', 'ReversalOK', 'DDIncreasePayrollLimit', 'PayrollCancelled', 'Strike', 'ReversalRequested', 'TransmissionError', 'PINCreated', 'PINUpdated', 'BankAccountVerified', 'LegalNameChanged', 'LegalAddressChanged', 'CompanyBankAccountChange', 'FeeCreated', 'IncorrectPIN', 'CoaFeeAccountChange', 'CoaSalesTaxAccountChange', 'NOC', 'ReversalReturn', 'FeeReturn', 'ERRefundReturn', 'CBAVerifyReturn', 'DDDebitReturn', 'NSF', 'DDReject', 'StrikeRemoved', 'PayrollReceived', 'FirstPayrollReceived', 'ZeroPayrollReceived', 'PayrollSubmissionFailed', 'PayrollRejected', 'PSPSentEmail', 'PayrollOffloaded', 'FraudDetected', 'TaxExemptStatusChanged', 'OffloadReportPrinted', 'CustomerSignedUp', 'CompanyInformationChanged', 'PayrollCancelPending', 'RefundIssued', 'CBAVerifyExpired', 'EmailAddressChanged', 'ManualRedebitCreated', 'LastChanceNotify', 'WireReceived', 'ErrorInfo'));

ALTER TABLE PSP_SYSTEM_CAPABILITY
 ADD CONSTRAINT SYSTEMCAPABILITYCODE355
 CHECK (SYSTEM_CAPABILITY_CD IN('ChangeEmployerBankAccount', 'DebitMonthlySubscriptionFee', 'FileCompanyTaxes', 'OffloadPendingPayrolls', 'PayCompanyTaxes', 'RefundOrCredit', 'SubmitPayroll', 'SynchronizeAccount', 'AddService', 'CancelService', 'ChangeCompanyInfo', 'ChangeEmployeeBankAccount', 'TransmitBalanceFile', 'VerifyCompanyBankAccount', 'UpgradeFundingModel'));

ALTER TABLE PSP_SERVICE_STATUS
 ADD CONSTRAINT SERVICESTATUSCODE346
 CHECK (SERVICE_STATUS_CD IN('Active', 'Cancelled', 'OnHold', 'PendingActivation', 'Terminated'));

ALTER TABLE PSP_EVENT_DETAIL_TYPE
 ADD CONSTRAINT EVENTDETAILTYPECODE335
 CHECK (EVENT_DETAIL_TYPE_CD IN('ACHEventCd', 'BankAccountNumber', 'BankAccountRoutingNumber', 'EmployeeName', 'SourcePayrollRunId', 'PayrollCancellationReason', 'CallerApplication', 'CompanyBankAccountId', 'ACHReturnReasonCode', 'BankAccountType', 'CancellationDateTime', 'BankAccountName', 'AdjustedERSettlementDate', 'AdjustedEESettlementDate', 'PayrollRunId', 'PayrollCancellationScope', 'EmployeeId', 'LimitAmount', 'LimitType', 'ViolationAmount', 'OldCoaName', 'NewCoaName', 'CoaNameChangeByAgent', 'OldServiceStatus', 'NewServiceStatus', 'OldLimitAmount', 'NewLimitAmount', 'OldBAStatus', 'NewBAStatus', 'ManualStrikeReasonDescription', 'FeeType', 'RefundStatus', 'RefundStatusReason', 'ReturnType', 'CompanyServiceId', 'FinancialTransactionId', 'TransmissionId', 'ErrorCode', 'ErrorMessage', 'ErrorType', 'OldStringValue', 'NewStringValue', 'PaycheckDate', 'TransmissionDateTime', 'OffloadDate', 'PaycheckId', 'PaycheckAmount', 'PendingAutoRedebit', 'RefundIssued', 'FeeAmount', 'OriginalTransactionDateTime', 'ReversalAmount', 'StrikeReason', 'ReasonDescription', 'NoteText', 'NumberOfBackdatedDays', 'StrikeNumberOfTotal', 'StrikeRemovalReason', 'FailureReason', 'TerminationDateTime', 'QBToken', 'PSPToken', 'UnsupportedVersionNumber', 'UnsupportedReleaseNumber', 'NSFSubType', 'PayrollStatus', 'OldAccountNumber', 'NewAccountNumber', 'OldRoutingNumber', 'NewRoutingNumber', 'OldAccountType', 'NewAccountType', 'EmployeeBankAccountId', 'VerificationStatus', 'PayrollRejectedReason', 'CompanyEventId', 'ServiceStatus'));

ALTER TABLE PSP_COLLECTION_STAGE
 ADD CONSTRAINT COLLECTIONSTAGECODE329
 CHECK (COLLECTION_STAGE_CODE IN('FirstCollectionAttempt', 'SecondCollectionAttempt', 'TerminationExpected'));

ALTER TABLE PSP_AUTH_OPERATION
 ADD CONSTRAINT OPERATIONID326
 CHECK (OPERATION_ID IN('BankReturnUpdate', 'AccessApplication', 'DDLimitUpdate', 'FundingModelUpdate', 'DDStatusUpdate', 'StrikeAdd', 'StrikeCancel', 'DDStatusPendingActivation', 'DDStatusActive', 'DDStatusPendingTermination', 'DDStatusTerminated', 'DDStatusOnHold', 'DDStatusSuspended', 'DDStatusCancelled', 'SettingUpdate', 'ViewFullBankAccountNumbers', 'BankReturnView', 'RecordNonACHRedebitTransaction', 'CreateFeeTransaction', 'CreateReversalTransaction', 'DDTransactionCancel', 'TransactionCancel', 'LedgerView', 'SelectNonStandardSettlementType', 'CreateRefundTransaction', 'VoidTransaction', 'BookTransferTransaction', 'ActivateBankAccount', 'DeActivateBankAccount', 'WriteoffBadDebtTransaction', 'RecoverBadDebtTransaction', 'EscalationCreditTransaction', 'IssueRedebitTransaction', 'AuthAccessApplication', 'AuthAddUpdateUsers', 'AuthRemoveUsers', 'AuthManageRoles', 'AuthAddUpdateHelpDesk', 'AuthAddRemoveHelpDesk', 'AuthAddUpdateDataCustodian', 'AuthRemoveDataCustodian', 'EditCompanyLegalInformation', 'EditCompanyContactInformation', 'ViewTransactionHistory', 'ViewVerificationDebits', 'ResetVerificationAmounts', 'GenerateRandomDebits', 'EditPayrollContact', 'EditPrincipalContacts', 'GeneratePin', 'AddBankAccountRandomDebits', 'AddOffering', 'AddOffer', 'EditChartOfAccounts', 'AddBankAccountByPassRandomDebits', 'RemoveOffer'));

ALTER TABLE PSP_ACTION_EVENT
 ADD CONSTRAINT ACTIONEVENTCODE320
 CHECK (CODE IN('FinancialTransactionVoidTx', 'FinancialTransactionCancel', 'IssueReissueRefundEr', 'ReissueFee', 'TxStateHistory', 'DDTransactionCancel', 'DDTransactionReverse', 'DDRedebitAdd', 'DDRedebitRecord', 'ERFeeAdd', 'BadDebtWriteOff', 'BadDebtRecover', 'EEReturnTransfer', 'FeeTransfer', 'Intuit5DayReturnTransfer', 'DDRefund', 'ERReturnRefund', 'EEReturnRefund', 'ERWireExpected', 'ERChangeRedebitToWireExpected'));

ALTER TABLE PSP_ACTION_EVENT
 ADD CONSTRAINT ACTIONTYPE322
 CHECK (TYPE IN('FinancialTransaction', 'PayrollRun', 'LedgerAccount'));

ALTER TABLE PSP_TRANSACTION_RETURN_BATCH
 ADD CONSTRAINT TRANSACTIONRETURNBATCHSTA318
 CHECK (STATUS_CD IN('Pending', 'Completed', 'Error'));

ALTER TABLE PSP_SOURCE_PAYROLL_PARAMETER
 ADD CONSTRAINT SOURCEPAYROLLPARAMETERCODE300
 CHECK (PARAMETER_CD IN('ACHWaitPeriod', 'CompanyBankAccountDurationLimitForVerification', 'CompanyBankAccountVerificationAttemptLimit', 'ConsecutiveLimitViolationLimit', 'DDCompanyLimitDuration', 'DDEmployeeLimitDuration', 'DefaultDDCompanyLimit', 'DefaultDDEmployeeLimit', 'MaxDDCompanyLimitDefault', 'MinimumNonSuspectPayrollAmount', 'PayrollEntryDescription', 'MinPayrollRunsForLimitAutoIncrease', 'MinQBVersionSupported', 'BookTransferEntryDescription', 'ReversalEntryDescription', 'MaxNumberOfFailedLoginAttempts', 'AllowMultipleFundingModels', 'MaxWarehouseTransactionDays', 'DefaultFundingModel', 'LockAccountDuration', 'ShouldAddCompanyToPSP', 'AllowReverifyBankAccount', 'MinimumEarliestPayrollRunDays', 'DeactiveBankAccountOnReturnedVerificationDebit', 'UnsupportedQBVersionList'));

ALTER TABLE PSP_SOURCE_PAYROLL_PARAMETER
 ADD CONSTRAINT SOURCESYSTEMCODE304
 CHECK (SOURCE_SYSTEM_CD IN('CRIS', 'PSP', 'EWS', 'QBOE', 'QBDT', 'AS400'));

ALTER TABLE PSP_OFFLOAD_BATCH
 ADD CONSTRAINT OFFLOADBATCHSTATUS275
 CHECK (STATUS_CD IN('InProcess', 'Completed'));

ALTER TABLE PSP_INDIVIDUAL
 ADD CONSTRAINT COMMUNICATIONTYPE262
 CHECK (COMMUNICATION_TYPE_PREFERENCE IN('Phone', 'Email'));

ALTER TABLE PSP_INDIVIDUAL
 ADD CONSTRAINT GENDER259
 CHECK (GENDER_CD IN('Male', 'Female'));

ALTER TABLE PSP_FEE
 ADD CONSTRAINT FEETYPECODE246
 CHECK (FEE_CD IN('ReverseFee', 'NSFFee', 'CopyFee'));

ALTER TABLE PSP_COMPANY
 ADD CONSTRAINT SOURCESYSTEMCODE183
 CHECK (SOURCE_SYSTEM_CD IN('CRIS', 'PSP', 'EWS', 'QBOE', 'QBDT', 'AS400'));

ALTER TABLE PSP_SOURCE_SYSTEM_TRANSMISSION
 ADD CONSTRAINT SOURCESYSTEMCODE135
 CHECK (FROM_SOURCE_SYSTEM IN('CRIS', 'PSP', 'EWS', 'QBOE', 'QBDT', 'AS400'));

ALTER TABLE PSP_SOURCE_SYSTEM_TRANSMISSION
 ADD CONSTRAINT SOURCESYSTEMCODE144
 CHECK (TO_SOURCE_SYSTEM IN('CRIS', 'PSP', 'EWS', 'QBOE', 'QBDT', 'AS400'));

ALTER TABLE PSP_SOURCE_SYSTEM_TRANSMISSION
 ADD CONSTRAINT TRANSMISSIONTYPE140
 CHECK (TYPE IN('Sync', 'PayrollSubmission', 'ZeroPayroll', 'CreateAccount', 'UpdateAccount', 'MigrateAccount', 'ValidateBankAccount', 'CreatePIN', 'ChangePIN', 'UpdateBankAccount', 'EntitlementExtensionUpdate', 'AgreementUpdate', 'AccountUpdate', 'ContactUpdate', 'Unknown', 'CUEVENT', 'CUINFOMOD', 'EntitlementExtensionNew'));

ALTER TABLE PSP_PAYROLL_SUBTYPE
 ADD CONSTRAINT PAYROLLSUBTYPECODE123
 CHECK (PAYROLL_SUBTYPE_CD IN('BasicLimited', 'BasicUnlimited', 'Enhanced', 'EnhancedAccountant', 'EnhancedUnlimited', 'NewBasicUnlimited', 'Standard', 'Basic0to3Emp', 'Enhanced0to3Emp', 'PAPEnhAcct'));

ALTER TABLE PSP_PAYROLL_RUN_ACTION
 ADD CONSTRAINT PAYROLLSTATUS122
 CHECK (STATUS IN('Complete', 'Canceled', 'DebitReturnedCanceled', 'DebitReturned', 'NSFCanceled', 'OffloadedAll', 'OffloadedDebit', 'Pending', 'WrittenOff', 'PendingReversals', 'PendingAutoRedebit', 'AutoRedebitOffloaded', 'PendingRedebit', 'RedebitOffloaded', 'PendingWire', 'ReversalsOffloaded', 'ReversalsFinished', 'ReturnedTwice'));

ALTER TABLE PSP_ON_HOLD_REASON
 ADD CONSTRAINT SERVICESUBSTATUSCODE119
 CHECK (ON_HOLD_REASON_CD IN('AchRejectOther', 'AchRejectR1R9', 'ActiveCurrent', 'ActiveSeasonal', 'AuditCorrections', 'Cancelled', 'DirectDepositLimit', 'Fraud', 'FraudReview', 'IntuitCollections', 'MissingPaperwork', 'NoticeOfChange', 'PendingBalanceFile', 'PendingBankVerification', 'PendingFirstPayroll', 'PendingPinCreation', 'PendingTermination', 'RiskAssessment', 'RiskCollections', 'SuspendedDirectDeposit', 'Terminated'));

ALTER TABLE PSP_OFFERING_SVCCHG_GRP
 ADD CONSTRAINT OFFERINGSERVICECHARGETYPE114
 CHECK (APPLIES_TO IN('PerPayroll', 'PerPaycheck', 'PerTransmission', 'ReversalFee', 'DebitReturnFee', 'ManualServicingFee', 'ChaseReportFeeUpTo3Payrolls', 'ChaseReportFeeUpTo6Payrolls', 'ChaseReportFeeUpTo15Payrolls', 'ChaseReportFeeUpTo20Payrolls', 'ChaseReportFeeOver20Payrolls', 'BankVerificationDebit', 'PaymentArrangementFee'));

ALTER TABLE PSP_LEDGER_ACCOUNT_ACTION
 ADD CONSTRAINT CREDITDEBITCODE77
 CHECK (CREDIT_DEBIT_INDICATOR IN('Credit', 'Debit'));

ALTER TABLE PSP_INTUIT_BA_BT_FT
 ADD CONSTRAINT NACHABATCHTYPE76
 CHECK (N_A_C_H_A_BATCH_TYPE IN('BookTransfer', 'Payroll', 'Reversal'));

ALTER TABLE PSP_INTUIT_BA_BT_FT
 ADD CONSTRAINT NACHAFILETYPE75
 CHECK (FILE_TYPE IN('CCD', 'PPD'));

ALTER TABLE PSP_COMPANY_EVENT
 ADD CONSTRAINT COMPANYEVENTSTATUS38
 CHECK (STATUS_CD IN('Active', 'Inactive'));

ALTER TABLE PSP_COMPANY_EVENT
 ADD CONSTRAINT EVENTTYPECODE39
 CHECK (EVENT_TYPE_CD IN('AccountLocked', 'AgentNote', 'ACHReturnStatusChanged', 'EINChanged', 'BackdatedPayrollReceived', 'ACHReturn', 'ServiceStatusChange', 'CompanyBankAccountStatusChange', 'LimitViolation', 'ReversalOK', 'DDIncreasePayrollLimit', 'PayrollCancelled', 'Strike', 'ReversalRequested', 'TransmissionError', 'PINCreated', 'PINUpdated', 'BankAccountVerified', 'LegalNameChanged', 'LegalAddressChanged', 'CompanyBankAccountChange', 'FeeCreated', 'IncorrectPIN', 'CoaFeeAccountChange', 'CoaSalesTaxAccountChange', 'NOC', 'ReversalReturn', 'FeeReturn', 'ERRefundReturn', 'CBAVerifyReturn', 'DDDebitReturn', 'NSF', 'DDReject', 'StrikeRemoved', 'PayrollReceived', 'FirstPayrollReceived', 'ZeroPayrollReceived', 'PayrollSubmissionFailed', 'PayrollRejected', 'PSPSentEmail', 'PayrollOffloaded', 'FraudDetected', 'TaxExemptStatusChanged', 'OffloadReportPrinted', 'CustomerSignedUp', 'CompanyInformationChanged', 'PayrollCancelPending', 'RefundIssued', 'CBAVerifyExpired', 'EmailAddressChanged', 'ManualRedebitCreated', 'LastChanceNotify', 'WireReceived', 'ErrorInfo'));

ALTER TABLE PSP_ASSIGNED_DEPOSIT_FREQUENCY
 ADD CONSTRAINT DEPOSITFREQUENCYSOURCE14
 CHECK (FREQUENCY_SOURCE IN('Agency', 'Company'));

ALTER TABLE PSP_SERVICE_SUB_STATUS
 ADD CONSTRAINT SERVICESUBSTATUSCODE351
 CHECK (SERVICE_SUB_STATUS_CD IN('AchRejectOther', 'AchRejectR1R9', 'ActiveCurrent', 'ActiveSeasonal', 'AuditCorrections', 'Cancelled', 'DirectDepositLimit', 'Fraud', 'FraudReview', 'IntuitCollections', 'MissingPaperwork', 'NoticeOfChange', 'PendingBalanceFile', 'PendingBankVerification', 'PendingFirstPayroll', 'PendingPinCreation', 'PendingTermination', 'RiskAssessment', 'RiskCollections', 'SuspendedDirectDeposit', 'Terminated'));

ALTER TABLE PSP_PAYROLL_RUN
 ADD CONSTRAINT PAYROLLSTATUS295
 CHECK (PAYROLL_RUN_STATUS IN('Complete', 'Canceled', 'DebitReturnedCanceled', 'DebitReturned', 'NSFCanceled', 'OffloadedAll', 'OffloadedDebit', 'Pending', 'WrittenOff', 'PendingReversals', 'PendingAutoRedebit', 'AutoRedebitOffloaded', 'PendingRedebit', 'RedebitOffloaded', 'PendingWire', 'ReversalsOffloaded', 'ReversalsFinished', 'ReturnedTwice'));

ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 ADD CONSTRAINT PAYMENTMETHOD273
 CHECK (MONEY_MOVEMENT_PAYMENT_METHOD IN('ACHDebit', 'ACHCredit', 'CheckPayment', 'ACHDirectDeposit'));

ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 ADD CONSTRAINT PAYMENTSTATUS272
 CHECK (STATUS IN('Canceled', 'Created', 'Executed'));

ALTER TABLE PSP_INTUIT_BANK_ACC_TXN_TYPE
 ADD CONSTRAINT CREDITDEBITCODE268
 CHECK (CREDIT_DEBIT_IND IN('Credit', 'Debit'));

ALTER TABLE PSP_EMPLOYEE
 ADD CONSTRAINT EMPLOYEESTATUS236
 CHECK (STATUS_CD IN('Active', 'Inactive'));

ALTER TABLE PSP_CONTACT
 ADD CONSTRAINT CONTACTROLE202
 CHECK (CONTACT_ROLE_CD IN('PayrollAdmin', 'Other', 'PrimaryPrincipal', 'SecondaryPrincipal'));

ALTER TABLE PSP_COMPANY_SERVICE
 ADD CONSTRAINT SERVICESUBSTATUSCODE198
 CHECK (STATUS_CD IN('AchRejectOther', 'AchRejectR1R9', 'ActiveCurrent', 'ActiveSeasonal', 'AuditCorrections', 'Cancelled', 'DirectDepositLimit', 'Fraud', 'FraudReview', 'IntuitCollections', 'MissingPaperwork', 'NoticeOfChange', 'PendingBalanceFile', 'PendingBankVerification', 'PendingFirstPayroll', 'PendingPinCreation', 'PendingTermination', 'RiskAssessment', 'RiskCollections', 'SuspendedDirectDeposit', 'Terminated'));

ALTER TABLE PSP_COMPANY_BANK_ACCOUNT
 ADD CONSTRAINT BANKACCOUNTSTATUS190
 CHECK (STATUS_CD IN('PendingVerification', 'Active', 'Inactive'));

ALTER TABLE PSP_ROLE_SUB_STATUS
 ADD CONSTRAINT SUBSTATUSCHANGETYPE132
 CHECK (ALLOWED_CHANGE_TYPE IN('CanMoveFromSubStatus', 'CanMoveToSubStatus'));

ALTER TABLE PSP_ENTRY_DETAIL_RECORD
 ADD CONSTRAINT CREDITDEBITCODE58
 CHECK (CREDIT_DEBIT_INDICATOR IN('Credit', 'Debit'));

ALTER TABLE PSP_COMPANY_EVENT_DETAIL
 ADD CONSTRAINT EVENTDETAILTYPECODE42
 CHECK (EVENT_DETAIL_TYPE_CD IN('ACHEventCd', 'BankAccountNumber', 'BankAccountRoutingNumber', 'EmployeeName', 'SourcePayrollRunId', 'PayrollCancellationReason', 'CallerApplication', 'CompanyBankAccountId', 'ACHReturnReasonCode', 'BankAccountType', 'CancellationDateTime', 'BankAccountName', 'AdjustedERSettlementDate', 'AdjustedEESettlementDate', 'PayrollRunId', 'PayrollCancellationScope', 'EmployeeId', 'LimitAmount', 'LimitType', 'ViolationAmount', 'OldCoaName', 'NewCoaName', 'CoaNameChangeByAgent', 'OldServiceStatus', 'NewServiceStatus', 'OldLimitAmount', 'NewLimitAmount', 'OldBAStatus', 'NewBAStatus', 'ManualStrikeReasonDescription', 'FeeType', 'RefundStatus', 'RefundStatusReason', 'ReturnType', 'CompanyServiceId', 'FinancialTransactionId', 'TransmissionId', 'ErrorCode', 'ErrorMessage', 'ErrorType', 'OldStringValue', 'NewStringValue', 'PaycheckDate', 'TransmissionDateTime', 'OffloadDate', 'PaycheckId', 'PaycheckAmount', 'PendingAutoRedebit', 'RefundIssued', 'FeeAmount', 'OriginalTransactionDateTime', 'ReversalAmount', 'StrikeReason', 'ReasonDescription', 'NoteText', 'NumberOfBackdatedDays', 'StrikeNumberOfTotal', 'StrikeRemovalReason', 'FailureReason', 'TerminationDateTime', 'QBToken', 'PSPToken', 'UnsupportedVersionNumber', 'UnsupportedReleaseNumber', 'NSFSubType', 'PayrollStatus', 'OldAccountNumber', 'NewAccountNumber', 'OldRoutingNumber', 'NewRoutingNumber', 'OldAccountType', 'NewAccountType', 'EmployeeBankAccountId', 'VerificationStatus', 'PayrollRejectedReason', 'CompanyEventId', 'ServiceStatus'));

ALTER TABLE PSP_TRANSACTION_RETURN
 ADD CONSTRAINT TRANSACTIONRETURNSTATUSCO314
 CHECK (RETURN_STATUS_CD IN('Created', 'Error', 'Open', 'Resolved'));

ALTER TABLE PSP_EMPLOYEE_BANK_ACCOUNT
 ADD CONSTRAINT BANKACCOUNTSTATUS242
 CHECK (STATUS_CD IN('PendingVerification', 'Active', 'Inactive'));

ALTER TABLE PSP_FINANCIAL_TRANSACTION
 ADD CONSTRAINT BANKACCOUNTOWNERTYPE251
 CHECK (CREDIT_BANK_ACCOUNT_TYPE IN('Company', 'Employee', 'Intuit', 'TaxAgency'));

ALTER TABLE PSP_FINANCIAL_TRANSACTION
 ADD CONSTRAINT BANKACCOUNTOWNERTYPE252
 CHECK (DEBIT_BANK_ACCOUNT_TYPE IN('Company', 'Employee', 'Intuit', 'TaxAgency'));

ALTER TABLE PSP_FINANCIAL_TRANSACTION
 ADD CONSTRAINT SETTLEMENTTYPE250
 CHECK (SETTLEMENT_TYPE_CD IN('ACH', 'Wire', 'Cash', 'CheckType', 'Other'));

ALTER TABLE PSP_FINANCIAL_TRANSACTION
 ADD CONSTRAINT PSP_FINANCIALTRANSACTION_FK1 
 FOREIGN KEY (ORIGINAL_TRANSACTION_FK, REALM_ID) 
 REFERENCES PSP_FINANCIAL_TRANSACTION (FINANCIAL_TRANSACTION_SEQ,REALM_ID);

ALTER TABLE PSP_BILLING_DETAIL
 ADD CONSTRAINT OFFERINGSERVICECHARGETYPE33
 CHECK (OFFERING_SERVICE_CHARGE_TYPE IN('PerPayroll', 'PerPaycheck', 'PerTransmission', 'ReversalFee', 'DebitReturnFee', 'ManualServicingFee', 'ChaseReportFeeUpTo3Payrolls', 'ChaseReportFeeUpTo6Payrolls', 'ChaseReportFeeUpTo15Payrolls', 'ChaseReportFeeUpTo20Payrolls', 'ChaseReportFeeOver20Payrolls', 'BankVerificationDebit', 'PaymentArrangementFee'));

ALTER TABLE PSP_BILLING_DETAIL
 ADD CONSTRAINT SERVICECODE20
 CHECK (SERVICE_CD IN('DirectDeposit', 'Tax'));

select 'finished DBUpgradeFrom_1.0.0.0_To_1.1.0.0.sql ' || to_char(sysdate, 'MM/DD/YYYY HH24:MI:SS') from dual