--
-- This script will be executed BEFORE the automatically generated
-- C:\dev\psp\main\pse\domain\src\main\model\DBUpgradeFrom_1.7.0.0_To_1.8.0.0.sql
--
-- Developers can hand code logic here for data migration purposes
--
