--
-- This script will be executed BEFORE the automatically generated
-- C:\dev\PSP\main\PSE\Domain\src\main\model\DBUpgradeFrom_1.9.9.23_To_1.9.9.24.sql
--
-- Developers can hand code logic here for data migration purposes
--
