--
-- This script will be executed AFTER the automatically generated
-- C:\dev\PSP\main\PSE\Domain\src\main\model\DBUpgradeFrom_1.6.0.0_To_1.7.0.0.sql
--
-- Developers can hand code logic here for data migration purposes
--
