// Generated by DB Solo ${version} on ${date} at ${time}
package ${generator.getPackage()};

import org.hibernate.usertype.UserType;
import org.hibernate.HibernateException;
import org.dom4j.io.DOMReader;
import org.dom4j.Element;
import oracle.jdbc.driver.OracleResultSet;
import oracle.jdbc.driver.OraclePreparedStatement;
import oracle.sql.OPAQUE;

import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.Types;
import java.io.Serializable;


public class HibernateOracleXML2Dom4jElement implements UserType
{
  private static final int[] SQL_TYPES = {Types.CLOB};

  public int[] sqlTypes()
  {
    return SQL_TYPES;
  }

  public Class returnedClass()
  {
    return Element.class;
  }

  public boolean equals(Object x, Object y) throws HibernateException
  {
    if(x == y)
      return true;

    if(x == null || y == null)
      return false;

    return x.equals(y);
  }

  public int hashCode(Object x) throws HibernateException
  {
    return x.hashCode();
  }

  public Object deepCopy(Object value) throws HibernateException
  {
    if(null == value)
      return null;

    return value;
  }

  public boolean isMutable()
  {
    return false;
  }

  public Object nullSafeGet(ResultSet resultSet, String [] names, Object arg2) throws HibernateException, SQLException
  {
    if(resultSet instanceof OracleResultSet)
    {
      OracleResultSet oracleResultSet = (OracleResultSet) resultSet;
      OPAQUE op = oracleResultSet.getOPAQUE(names[0]);

      if(null != op)
      {
        oracle.xdb.XMLType xt = oracle.xdb.XMLType.createXML(op);
        DOMReader reader = new DOMReader();
        org.dom4j.Document document = reader.read(xt.getDOM());

        return document.getRootElement();
      }
      else
      {
        return null;
      }
    }
    else
    {
      throw new UnsupportedOperationException("Result set is not OracleResultSet");
    }
  }

  public void nullSafeSet(PreparedStatement statement, Object value, int index) throws HibernateException, SQLException
  {
    try
    {
      if(statement instanceof OraclePreparedStatement)
      {
        OraclePreparedStatement ost = (OraclePreparedStatement) statement;
        Connection conn = statement.getConnection();

        if(null != value)
          ost.setOPAQUE(index, oracle.xdb.XMLType.createXML(conn, ((Element) value).asXML()));
        else
          ost.setNull(index, Types.NULL);
      }
      else
      {
        throw new HibernateException("statement is not OraclePreparedStatement");
      }
    }
    catch(Exception e)
    {
      throw new HibernateException("Unexpected error", e);
    }
  }

  public Object assemble(Serializable arg0, Object arg1) throws HibernateException
  {
    return deepCopy(arg0);
  }

  public Serializable disassemble(Object value)
  {
    return (Serializable) deepCopy(value);
  }

  public Object replace(Object original, Object target, Object owner) throws HibernateException
  {
    return original;
  }
}
