// Generated by DB Solo ${version} on ${date} at ${time}
package ${generator.getPackage()};

<#assign bottom>
  <#if annotations>
  
     <#if klass.isComponent()>
        @${klass.addImport("javax.persistence.Embeddable")}
     <#else>
        @${klass.addImport("javax.persistence.Entity")}
        <#if klass.isSuperClass()>
            @${klass.addImport("javax.persistence.Inheritance")} (strategy = ${klass.addImport("javax.persistence.InheritanceType")}.${klass.getInheritanceType()})
            @${klass.addImport("javax.persistence.DiscriminatorColumn")} (name="${klass.getDiscriminatorColumn().getName()}")
            <#if klass.isAbstract() == false>
               @${klass.addImport("javax.persistence.DiscriminatorValue")} ("${klass.getDiscriminatorValue()}")
            </#if>
        <#elseif klass.isSubClass()>
            @${klass.addImport("javax.persistence.DiscriminatorValue")} ("${klass.getDiscriminatorValue()}")
        </#if>
        <#if klass.isSingleTableInheritanceSubClass() == false>
            @${klass.addImport("javax.persistence.Table")}(name="${klass.getTableName()}"
            <#if klass.supportsSchema()> ,schema="${klass.getSchemaName()}" </#if>
            <#if klass.supportsDatabase()> ,catalog="${klass.getDatabaseName()}" </#if>
            )
        </#if>
        <#if klass.isJoinedInheritanceSubClass()>
            <#if klass.getPrimaryKeyField().getColumns().size() == 1>
                @${klass.addImport("javax.persistence.PrimaryKeyJoinColumn")}(name="${klass.getPrimaryKeyField().getColumn().getName()}")
            <#else>
                 @${klass.addImport("javax.persistence.PrimaryKeyJoinColumns")} ({
                 <#list klass.getPrimaryKeyField().getColumns() as pkCol>
                 <#if pkCol_index != 0>,</#if>
                  @${klass.addImport("javax.persistence.PrimaryKeyJoinColumn")}(name="${pkCol.getName()}")
                 </#list>
                 })
            </#if>
        </#if>
     </#if>
  </#if>
public <#if klass.isAbstract()>abstract </#if>class ${klass.getName()}<#if klass.hasExtendsClass()> extends ${klass.getExtendsClass()}</#if><#if klass.hasImplements()> implements ${klass.getImplementsList()}</#if>
{
<#foreach field in klass.getFields()>
    <#if field.isPrimaryKey() == false || klass.isSubClass() == false>
        ${field.getFieldScope()} ${field.getJavaType()} ${field.getName()};
    </#if>
</#foreach>

    //
    // constructors
    //
    public ${klass.getName()}() {
    }

<#if klass.hasPrimaryKey()>
 public ${klass.getName()}
 (
<#foreach field in klass.getPrimaryKeyConstructorFields()>
    <#if field_index != 0>,</#if> ${field.getJavaType()} ${field.getName()}
</#foreach>
 )
 {
<#if klass.isSubClass()>
  super(
  <#foreach field in klass.getPrimaryKeyConstructorFields()>
     <#if field.getContainer() != klass >
        <#if field_index != 0>,</#if> ${field.getName()}
     </#if>
  </#foreach>
  );

</#if>
<#foreach field in klass.getPrimaryKeyConstructorFields()>
   <#if klass.isSubClass() == false>
      this.${field.getName()} = ${field.getName()};
   </#if>
</#foreach>
 }
</#if>

 public ${klass.getName()} (
<#foreach field in klass.getConstructorFields()>
    <#if field_index != 0>,</#if> ${field.getJavaType()} ${field.getName()}
</#foreach>
 )
 {
<#if klass.isSubClass()>
  super(
  <#foreach field in klass.getConstructorFields()>
     <#if field.getContainer() != klass >
        <#if field_index != 0>,</#if> ${field.getName()}
     </#if>
  </#foreach>
  );

</#if>
<#foreach field in klass.getFields()>
  <#if field.isPrimaryKey() == false || klass.isSubClass() == false>
     this.${field.getName()} = ${field.getName()};
  </#if>
</#foreach>
 }

    //
    // getters/setters
    //
<#foreach field in klass.getFields()>
<#if field.isPrimaryKey() == false || klass.isSubClass() == false>
<#if annotations>
  <#if field.isVersion()>
      @${klass.addImport("javax.persistence.Version")}
  </#if>
  <#if field.isEnumerated()>
      @${klass.addImport("javax.persistence.Enumerated")}
  </#if>
  <#if field.isPrimaryKey()>
    <#if field.isComponent()>
        @${klass.addImport("javax.persistence.EmbeddedId")}
    <#else>
        @${klass.addImport("javax.persistence.Id")}
    </#if>

    <#if klass.isIdentityPrimaryKey()>
        @${klass.addImport("javax.persistence.GeneratedValue")}(strategy = ${klass.addStaticImport("javax.persistence.GenerationType.IDENTITY")})
    <#elseif klass.isSequencePrimaryKey()>
        @${klass.addImport("javax.persistence.GeneratedValue")}(strategy = ${klass.addStaticImport("javax.persistence.GenerationType.SEQUENCE")}, generator="${klass.getSequenceName()}__")
        @${klass.addImport("javax.persistence.SequenceGenerator")}(name = "${klass.getSequenceName()}__", sequenceName="${klass.getSequenceName()}")
    </#if>
  </#if>

  <#if field.isMany2One()>
     @${klass.addImport("javax.persistence.ManyToOne")}(
      <#if field.getRelation().isLazy()>
        fetch = ${klass.addImport("javax.persistence.FetchType")}.LAZY
      <#else>
        fetch = ${klass.addImport("javax.persistence.FetchType")}.EAGER
      </#if>
     )
     <#if field.getRelation().getColumnCount() == 1>
         @${klass.addImport("javax.persistence.JoinColumn")}(name="${field.getRelation().getColumn().getName()}")
     <#else>
         @${klass.addImport("javax.persistence.JoinColumns")} ({
         <#list field.getRelation().getColumns() as joinCol>
             <#if joinCol_index != 0>,</#if>
             @${klass.addImport("javax.persistence.JoinColumn")}(name="${joinCol.getName()}")
         </#list>  })
     </#if>
  <#elseif field.isOne2One()>
    <#if field.isOne2OneSharedPK()>
        @${klass.addImport("javax.persistence.OneToOne")}
        <#if field.getRelation().getColumnCount() == 1>
           @${klass.addImport("javax.persistence.PrimaryKeyJoinColumn")}
        <#else>
          @${klass.addImport("javax.persistence.PrimaryKeyJoinColumns")} ({
          <#list field.getRelation().getColumns() as joinCol>
              <#if joinCol_index != 0>,</#if>
              @${klass.addImport("javax.persistence.PrimaryKeyJoinColumn")}(name="${joinCol.getName()}", referencedColumnName="${joinCol.getOtherColumnName()}")
          </#list>
          })
        </#if>
    <#else>
      <#if field.isOne2OneOwnerSide()>
        @${klass.addImport("javax.persistence.OneToOne")}
        <#if field.getRelation().getColumnCount() == 1>
            @${klass.addImport("javax.persistence.JoinColumn")}(name="${field.getRelation().getColumn().getName()}")
        <#else>
          @${klass.addImport("javax.persistence.JoinColumns")} ({
          <#list field.getRelation().getColumns() as joinCol>
              <#if joinCol_index != 0>,</#if>
              @${klass.addImport("javax.persistence.JoinColumn")}(name="${joinCol.getName()}")
          </#list>  })
        </#if>
      <#else>
         @${klass.addImport("javax.persistence.OneToOne")}(mappedBy="${field.getReferencedField().getName()}")
         </#if>
     </#if>
  <#elseif field.isMany2Many()>
      <#if field.getRelation().isOwnerSide()>
        @${klass.addImport("javax.persistence.ManyToMany")} @${klass.addImport("javax.persistence.JoinTable")}(name="${field.getRelation().getJoinTable()}",
          joinColumns={
            <#list field.getRelation().getColumns() as joinCol>
              <#if joinCol_index != 0>,</#if>
              @${klass.addImport("javax.persistence.JoinColumn")}(name="${joinCol.getName()}", referencedColumnName="${joinCol.getOtherColumnName()}")
            </#list>
          },
          inverseJoinColumns={
            <#list field.getRelation().getInverseColumns() as joinCol>
              <#if joinCol_index != 0>,</#if>
              @${klass.addImport("javax.persistence.JoinColumn")}(name="${joinCol.getName()}", referencedColumnName="${joinCol.getOtherColumnName()}")
            </#list>
          }
          )
      <#else>
        @${klass.addImport("javax.persistence.ManyToMany")}(mappedBy="${field.getRelation().getOtherField().getName()}")
      </#if>
  <#elseif field.isOne2Many()>
      @${klass.addImport("javax.persistence.OneToMany")}(cascade = ${klass.addImport("javax.persistence.CascadeType")}.ALL,
      <#if field.getRelation().isLazy()>
        fetch = ${klass.addImport("javax.persistence.FetchType")}.LAZY,
      <#else>
        fetch = ${klass.addImport("javax.persistence.FetchType")}.EAGER,
      </#if>
      mappedBy="${field.getReferencedField().getName()}")
  <#elseif field.isComponent()>
      @${klass.addImport("javax.persistence.AttributeOverrides")} ({
      <#list field.getComponent().getFields() as compField>
          <#if compField_index != 0>,</#if>
          @${klass.addImport("javax.persistence.AttributeOverride")}(name="${compField.getName()}", column=@Column(name="${compField.getColumnName()}"))
      </#list>  })
  <#else>
       @${klass.addImport("javax.persistence.Column")}(name="${field.getColumnName()}", updatable=${field.getUpdatable()}, nullable=${field.getNullable()}, insertable=${field.getInsertable()})
      <#if field.getJavaType() == "Element" && field.getColumn().isOracleXMLType()>
        @${klass.addImport("org.hibernate.annotations.Type")}(type="${generator.getPackage()}.HibernateOracleXML2Dom4jElement")
      </#if>
      <#if field.getJavaType() == "String" && field.getColumn().isOracleXMLType()>
        @${klass.addImport("org.hibernate.annotations.Type")}(type="${generator.getPackage()}.HibernateOracleXML2String")
      </#if>
  </#if>
</#if>
    ${field.getGetScope()} ${field.getJavaType()} ${field.getterMethod()}() {
        return this.${field.getName()};
    }
    ${field.getSetScope()} void ${field.setterMethod()}(${field.getJavaType()} ${field.getName()}) {
        this.${field.getName()} = ${field.getName()};
    }
</#if>
</#foreach>
  <#if klass.wantEquals()>    public boolean equals(Object obj) {
	      if(this == obj)
	          return true;
	      if(null == obj)
	          return false;
	      if(obj instanceof ${klass.getName()} == false)
	          return false;

   <#if klass.isSubClass()>
        if(super.equals((${klass.getSuperClass().getName()}) obj) == false)
           return false;
   </#if>

	      ${klass.getName()} other = ( ${klass.getName()} ) obj;

    <#foreach temp in klass.getEqualsFields()>
         ${temp.generateEquals("other")}
    </#foreach>

	      return true;
   }

   public int hashCode() {
   <#if klass.isSubClass()>
         int result = super.hashCode();
   <#else>
         int result = 29;
   </#if>

   <#list klass.getEqualsFields() as temp>
         ${temp.generateHashCode("result")}
    </#list>

         return result;
   }
  </#if>
  <#if klass.wantToString()> public String toString() {
	      StringBuffer buffer = new StringBuffer("${generator.getPackage()}").append(".").append("${klass.getName()}").append("(");

    <#list klass.getToStringFields() as temp>
        buffer.append("[").append("${temp.name}").append("=").append(${temp.name}).append("]");
    </#list>

	      return buffer.append(")").toString();
    }
  </#if>

}
</#assign>

<#list klass.getImports() as import>
  import ${import};
</#list>
<#list klass.getStaticImports() as import>
  import static ${import};
</#list>

${bottom}
