CREATE USER PSP_PRL_APP IDENTIFIED by "&1"
      DEFAULT TABLESPACE "PSP_DATA01"
      TEMPORARY TABLESPACE "TEMP"
      PROFILE "APPLICATION_HIGH_RISK_PROFILE";
 ALTER USER PSP_PRL_APP LOCAL TEMPORARY TABLESPACE "SYSTEM";


   GRANT "CONNECT" TO PSP_PRL_APP;
   GRANT "PSPAPP_ROLE" TO PSP_PRL_APP;


  GRANT CREATE ANY CONTEXT TO PSP_PRL_APP;


  GRANT SELECT ON "SYS"."DBA_USERS" TO PSP_PRL_APP;
  GRANT SELECT ON "SYS"."DBA_ROLE_PRIVS" TO PSP_PRL_APP;
  GRANT SELECT ON "SYS"."DBA_SYS_PRIVS" TO PSP_PRL_APP;
  GRANT SELECT ON "SYS"."DBA_TAB_PRIVS" TO PSP_PRL_APP;
  GRANT SELECT ON "SYS"."V_$DATABASE" TO PSP_PRL_APP;
  GRANT DELETE ON "PSPADM"."PSP_PERF_SST" TO PSP_PRL_APP;
  GRANT DELETE ON "PSPADM"."PSP_ADE_LAW_MAP" TO PSP_PRL_APP;
  GRANT DELETE ON "PSPADM"."PSP_EMPLOYER_PREFERENCE" TO PSP_PRL_APP;
  GRANT DELETE ON "PSPADM"."PSP_TAX_CREDITS_APPLICATION" TO PSP_PRL_APP;
  GRANT DELETE ON "PSPADM"."PSP_FRAUD_CONTACT" TO PSP_PRL_APP;
  GRANT DELETE ON "PSPADM"."PSP_FRAUD_COMPANY" TO PSP_PRL_APP;
  GRANT DELETE ON "PSPADM"."PSP_FRAUD_ADDRESS" TO PSP_PRL_APP;
  GRANT DELETE ON "PSPADM"."PSP_SQL_EXECUTION_LOG_ENTRY" TO PSP_PRL_APP;
  GRANT DELETE ON "PSPADM"."PSP_PAY_ITEM" TO PSP_PRL_APP;
  GRANT INSERT ON "PSPADM"."PSP_PERF_SST" TO PSP_PRL_APP;
  GRANT INSERT ON "PSPADM"."PSP_ADE_LAW_MAP" TO PSP_PRL_APP;
  GRANT INSERT ON "PSPADM"."PSP_EMPLOYER_PREFERENCE" TO PSP_PRL_APP;
  GRANT INSERT ON "PSPADM"."PSP_TAX_CREDITS_APPLICATION" TO PSP_PRL_APP;
  GRANT INSERT ON "PSPADM"."PSP_FRAUD_CONTACT" TO PSP_PRL_APP;
  GRANT INSERT ON "PSPADM"."PSP_FRAUD_COMPANY" TO PSP_PRL_APP;
  GRANT INSERT ON "PSPADM"."PSP_FRAUD_ADDRESS" TO PSP_PRL_APP;
  GRANT INSERT ON "PSPADM"."PSP_SQL_EXECUTION_LOG_ENTRY" TO PSP_PRL_APP;
  GRANT INSERT ON "PSPADM"."PSP_PAY_ITEM" TO PSP_PRL_APP;
  GRANT SELECT ON "PSPADM"."SEQ_ATF_BATCH_ID_NBR" TO PSP_PRL_APP;
  GRANT SELECT ON "PSPADM"."PSP_PERF_SST" TO PSP_PRL_APP;
  GRANT SELECT ON "PSPADM"."PSP_ADE_LAW_MAP" TO PSP_PRL_APP;
  GRANT SELECT ON "PSPADM"."PSP_EMPLOYER_PREFERENCE" TO PSP_PRL_APP;
  GRANT SELECT ON "PSPADM"."PSP_TAX_CREDITS_APPLICATION" TO PSP_PRL_APP;
  GRANT SELECT ON "PSPADM"."PSP_FRAUD_CONTACT" TO PSP_PRL_APP;
  GRANT SELECT ON "PSPADM"."PSP_FRAUD_COMPANY" TO PSP_PRL_APP;
  GRANT SELECT ON "PSPADM"."PSP_FRAUD_ADDRESS" TO PSP_PRL_APP;
  GRANT SELECT ON "PSPADM"."PSP_SQL_EXECUTION_LOG_ENTRY" TO PSP_PRL_APP;
  GRANT SELECT ON "PSPADM"."PSP_PAY_ITEM" TO PSP_PRL_APP;
  GRANT UPDATE ON "PSPADM"."PSP_PERF_SST" TO PSP_PRL_APP;
  GRANT UPDATE ON "PSPADM"."PSP_ADE_LAW_MAP" TO PSP_PRL_APP;
  GRANT UPDATE ON "PSPADM"."PSP_EMPLOYER_PREFERENCE" TO PSP_PRL_APP;
  GRANT UPDATE ON "PSPADM"."PSP_TAX_CREDITS_APPLICATION" TO PSP_PRL_APP;
  GRANT UPDATE ON "PSPADM"."PSP_FRAUD_CONTACT" TO PSP_PRL_APP;
  GRANT UPDATE ON "PSPADM"."PSP_FRAUD_COMPANY" TO PSP_PRL_APP;
  GRANT UPDATE ON "PSPADM"."PSP_FRAUD_ADDRESS" TO PSP_PRL_APP;
  GRANT UPDATE ON "PSPADM"."PSP_SQL_EXECUTION_LOG_ENTRY" TO PSP_PRL_APP;
  GRANT UPDATE ON "PSPADM"."PSP_PAY_ITEM" TO PSP_PRL_APP;
  GRANT EXECUTE ON "PSPADM"."PK_GEMS_ACCOUNTS_RECEIVABLE" TO PSP_PRL_APP;
  GRANT EXECUTE ON "PSPADM"."FN_GET_EDR_AMOUNT" TO PSP_PRL_APP;
  GRANT EXECUTE ON "PSPADM"."FN_GET_LEDGER_BALANCE" TO PSP_PRL_APP;
  GRANT ALTER ON "APPBUGFIX"."TMP_ZP_FT" TO PSP_PRL_APP;
  GRANT ALTER ON "APPBUGFIX"."TMP_ZP_MMT" TO PSP_PRL_APP;
  GRANT DELETE ON "APPBUGFIX"."TMP_ZP_FT" TO PSP_PRL_APP;
  GRANT DELETE ON "APPBUGFIX"."TMP_ZP_MMT" TO PSP_PRL_APP;
  GRANT INDEX ON "APPBUGFIX"."TMP_ZP_FT" TO PSP_PRL_APP;
  GRANT INDEX ON "APPBUGFIX"."TMP_ZP_MMT" TO PSP_PRL_APP;
  GRANT INSERT ON "APPBUGFIX"."TMP_ZP_FT" TO PSP_PRL_APP;
  GRANT INSERT ON "APPBUGFIX"."TMP_ZP_MMT" TO PSP_PRL_APP;
  GRANT SELECT ON "APPBUGFIX"."TMP_ZP_FT" TO PSP_PRL_APP;
  GRANT SELECT ON "APPBUGFIX"."TMP_DUP_FTS" TO PSP_PRL_APP;
  GRANT SELECT ON "APPBUGFIX"."TMP_PPD_RECORD_DATA" TO PSP_PRL_APP;
  GRANT SELECT ON "APPBUGFIX"."TMP_ZP_MMT" TO PSP_PRL_APP;
  GRANT UPDATE ON "APPBUGFIX"."TMP_ZP_FT" TO PSP_PRL_APP;
  GRANT UPDATE ON "APPBUGFIX"."TMP_ZP_MMT" TO PSP_PRL_APP;
  GRANT REFERENCES ON "APPBUGFIX"."TMP_ZP_FT" TO PSP_PRL_APP;
  GRANT REFERENCES ON "APPBUGFIX"."TMP_ZP_MMT" TO PSP_PRL_APP;
  GRANT ON COMMIT REFRESH ON "APPBUGFIX"."TMP_ZP_FT" TO PSP_PRL_APP;
  GRANT ON COMMIT REFRESH ON "APPBUGFIX"."TMP_ZP_MMT" TO PSP_PRL_APP;
  GRANT QUERY REWRITE ON "APPBUGFIX"."TMP_ZP_FT" TO PSP_PRL_APP;
  GRANT QUERY REWRITE ON "APPBUGFIX"."TMP_ZP_MMT" TO PSP_PRL_APP;
  GRANT DEBUG ON "APPBUGFIX"."TMP_ZP_FT" TO PSP_PRL_APP;
  GRANT DEBUG ON "APPBUGFIX"."TMP_ZP_MMT" TO PSP_PRL_APP;
  GRANT FLASHBACK ON "APPBUGFIX"."TMP_ZP_FT" TO PSP_PRL_APP;
  GRANT FLASHBACK ON "APPBUGFIX"."TMP_ZP_MMT" TO PSP_PRL_APP;


   ALTER USER PSP_PRL_APP DEFAULT ROLE ALL;

