set search_path to pspadm;
create index concurrently idx_ent_msg_mod_date_2012 on pspadm.psp_entitlement_message_2012  USING BTREE (modified_date);
create index concurrently idx_ent_msg_mod_date_2013 on pspadm.psp_entitlement_message_2013  USING BTREE (modified_date);
create index concurrently idx_ent_msg_mod_date_2014 on pspadm.psp_entitlement_message_2014  USING BTREE (modified_date);
create index concurrently idx_ent_msg_mod_date_2015 on pspadm.psp_entitlement_message_2015  USING BTREE (modified_date);
create index concurrently idx_ent_msg_mod_date_2016 on pspadm.psp_entitlement_message_2016  USING BTREE (modified_date);
create index concurrently idx_ent_msg_mod_date_2017 on pspadm.psp_entitlement_message_2017  USING BTREE (modified_date);
create index concurrently idx_ent_msg_mod_date_2018 on pspadm.psp_entitlement_message_2018  USING BTREE (modified_date);
create index concurrently idx_ent_msg_mod_date_2019 on pspadm.psp_entitlement_message_2019  USING BTREE (modified_date);
create index concurrently idx_ent_msg_mod_date_2020 on pspadm.psp_entitlement_message_2020  USING BTREE (modified_date);
create index concurrently idx_ent_msg_mod_date_2021 on pspadm.psp_entitlement_message_2021  USING BTREE (modified_date);
create index concurrently idx_ent_msg_mod_date_2022 on pspadm.psp_entitlement_message_2022  USING BTREE (modified_date);
create index concurrently idx_ent_msg_mod_date_2023 on pspadm.psp_entitlement_message_2023  USING BTREE (modified_date);
create index concurrently idx_ent_msg_mod_date_2024 on pspadm.psp_entitlement_message_2024  USING BTREE (modified_date);
create index concurrently idx_ent_msg_mod_date_2025 on pspadm.psp_entitlement_message_2025  USING BTREE (modified_date);
create index concurrently idx_ent_msg_mod_date_2026 on pspadm.psp_entitlement_message_2026  USING BTREE (modified_date);

create index idx_ent_msg_mod_date ON ONLY pspadm.psp_entitlement_message USING BTREE (modified_date);
alter index idx_ent_msg_mod_date attach partition  pspadm.idx_ent_msg_mod_date_2012 ;
alter index idx_ent_msg_mod_date attach partition  pspadm.idx_ent_msg_mod_date_2013 ;
alter index idx_ent_msg_mod_date attach partition  pspadm.idx_ent_msg_mod_date_2014 ;
alter index idx_ent_msg_mod_date attach partition  pspadm.idx_ent_msg_mod_date_2015 ;
alter index idx_ent_msg_mod_date attach partition  pspadm.idx_ent_msg_mod_date_2016 ;
alter index idx_ent_msg_mod_date attach partition  pspadm.idx_ent_msg_mod_date_2017 ;
alter index idx_ent_msg_mod_date attach partition  pspadm.idx_ent_msg_mod_date_2018 ;
alter index idx_ent_msg_mod_date attach partition  pspadm.idx_ent_msg_mod_date_2019 ;
alter index idx_ent_msg_mod_date attach partition  pspadm.idx_ent_msg_mod_date_2020 ;
alter index idx_ent_msg_mod_date attach partition  pspadm.idx_ent_msg_mod_date_2021 ;
alter index idx_ent_msg_mod_date attach partition  pspadm.idx_ent_msg_mod_date_2022 ;
alter index idx_ent_msg_mod_date attach partition  pspadm.idx_ent_msg_mod_date_2023 ;
alter index idx_ent_msg_mod_date attach partition  pspadm.idx_ent_msg_mod_date_2024 ;
alter index idx_ent_msg_mod_date attach partition  pspadm.idx_ent_msg_mod_date_2025 ;
alter index idx_ent_msg_mod_date attach partition  pspadm.idx_ent_msg_mod_date_2026 ;

create index concurrently idx_pchk_usg_mod_date_2012 on pspadm.psp_paycheck_usage_2012  USING BTREE (modified_date);
create index concurrently idx_pchk_usg_mod_date_2013 on pspadm.psp_paycheck_usage_2013  USING BTREE (modified_date);
create index concurrently idx_pchk_usg_mod_date_2014 on pspadm.psp_paycheck_usage_2014  USING BTREE (modified_date);
create index concurrently idx_pchk_usg_mod_date_2015 on pspadm.psp_paycheck_usage_2015  USING BTREE (modified_date);
create index concurrently idx_pchk_usg_mod_date_2016 on pspadm.psp_paycheck_usage_2016  USING BTREE (modified_date);
create index concurrently idx_pchk_usg_mod_date_2017 on pspadm.psp_paycheck_usage_2017  USING BTREE (modified_date);
create index concurrently idx_pchk_usg_mod_date_2018 on pspadm.psp_paycheck_usage_2018  USING BTREE (modified_date);
create index concurrently idx_pchk_usg_mod_date_2019 on pspadm.psp_paycheck_usage_2019  USING BTREE (modified_date);
create index concurrently idx_pchk_usg_mod_date_2020 on pspadm.psp_paycheck_usage_2020  USING BTREE (modified_date);
create index concurrently idx_pchk_usg_mod_date_2021 on pspadm.psp_paycheck_usage_2021  USING BTREE (modified_date);
create index concurrently idx_pchk_usg_mod_date_2022 on pspadm.psp_paycheck_usage_2022  USING BTREE (modified_date);
create index concurrently idx_pchk_usg_mod_date_2023 on pspadm.psp_paycheck_usage_2023  USING BTREE (modified_date);
create index concurrently idx_pchk_usg_mod_date_2024 on pspadm.psp_paycheck_usage_2024  USING BTREE (modified_date);
create index concurrently idx_pchk_usg_mod_date_2025 on pspadm.psp_paycheck_usage_2025  USING BTREE (modified_date);
create index concurrently idx_pchk_usg_mod_date_2026 on pspadm.psp_paycheck_usage_2026  USING BTREE (modified_date);

create index idx_pchk_usg_mod_date ON ONLY pspadm.psp_paycheck_usage USING BTREE (modified_date);
alter index idx_pchk_usg_mod_date attach partition  pspadm.idx_pchk_usg_mod_date_2012 ;
alter index idx_pchk_usg_mod_date attach partition  pspadm.idx_pchk_usg_mod_date_2013 ;
alter index idx_pchk_usg_mod_date attach partition  pspadm.idx_pchk_usg_mod_date_2014 ;
alter index idx_pchk_usg_mod_date attach partition  pspadm.idx_pchk_usg_mod_date_2015 ;
alter index idx_pchk_usg_mod_date attach partition  pspadm.idx_pchk_usg_mod_date_2016 ;
alter index idx_pchk_usg_mod_date attach partition  pspadm.idx_pchk_usg_mod_date_2017 ;
alter index idx_pchk_usg_mod_date attach partition  pspadm.idx_pchk_usg_mod_date_2018 ;
alter index idx_pchk_usg_mod_date attach partition  pspadm.idx_pchk_usg_mod_date_2019 ;
alter index idx_pchk_usg_mod_date attach partition  pspadm.idx_pchk_usg_mod_date_2020 ;
alter index idx_pchk_usg_mod_date attach partition  pspadm.idx_pchk_usg_mod_date_2021 ;
alter index idx_pchk_usg_mod_date attach partition  pspadm.idx_pchk_usg_mod_date_2022 ;
alter index idx_pchk_usg_mod_date attach partition  pspadm.idx_pchk_usg_mod_date_2023 ;
alter index idx_pchk_usg_mod_date attach partition  pspadm.idx_pchk_usg_mod_date_2024 ;
alter index idx_pchk_usg_mod_date attach partition  pspadm.idx_pchk_usg_mod_date_2025 ;
alter index idx_pchk_usg_mod_date attach partition  pspadm.idx_pchk_usg_mod_date_2026 ;

create index concurrently psp_paycheck_usage_fk1_2012 on pspadm.psp_paycheck_usage_2012  USING BTREE (company_fk ASC);
create index concurrently psp_paycheck_usage_fk1_2013 on pspadm.psp_paycheck_usage_2013  USING BTREE (company_fk ASC);
create index concurrently psp_paycheck_usage_fk1_2014 on pspadm.psp_paycheck_usage_2014  USING BTREE (company_fk ASC);
create index concurrently psp_paycheck_usage_fk1_2015 on pspadm.psp_paycheck_usage_2015  USING BTREE (company_fk ASC);
create index concurrently psp_paycheck_usage_fk1_2016 on pspadm.psp_paycheck_usage_2016  USING BTREE (company_fk ASC);
create index concurrently psp_paycheck_usage_fk1_2017 on pspadm.psp_paycheck_usage_2017  USING BTREE (company_fk ASC);
create index concurrently psp_paycheck_usage_fk1_2018 on pspadm.psp_paycheck_usage_2018  USING BTREE (company_fk ASC);
create index concurrently psp_paycheck_usage_fk1_2019 on pspadm.psp_paycheck_usage_2019  USING BTREE (company_fk ASC);
create index concurrently psp_paycheck_usage_fk1_2020 on pspadm.psp_paycheck_usage_2020  USING BTREE (company_fk ASC);
create index concurrently psp_paycheck_usage_fk1_2021 on pspadm.psp_paycheck_usage_2021  USING BTREE (company_fk ASC);
create index concurrently psp_paycheck_usage_fk1_2022 on pspadm.psp_paycheck_usage_2022  USING BTREE (company_fk ASC);
create index concurrently psp_paycheck_usage_fk1_2023 on pspadm.psp_paycheck_usage_2023  USING BTREE (company_fk ASC);
create index concurrently psp_paycheck_usage_fk1_2024 on pspadm.psp_paycheck_usage_2024  USING BTREE (company_fk ASC);
create index concurrently psp_paycheck_usage_fk1_2025 on pspadm.psp_paycheck_usage_2025  USING BTREE (company_fk ASC);
create index concurrently psp_paycheck_usage_fk1_2026 on pspadm.psp_paycheck_usage_2026  USING BTREE (company_fk ASC);
create index psp_paycheck_usage_nu1_2012 on pspadm.psp_paycheck_usage_2012  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_nu1_2013 on pspadm.psp_paycheck_usage_2013  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_nu1_2014 on pspadm.psp_paycheck_usage_2014  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_nu1_2015 on pspadm.psp_paycheck_usage_2015  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_nu1_2016 on pspadm.psp_paycheck_usage_2016  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_nu1_2017 on pspadm.psp_paycheck_usage_2017  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_nu1_2018 on pspadm.psp_paycheck_usage_2018  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_nu1_2019 on pspadm.psp_paycheck_usage_2019  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_nu1_2020 on pspadm.psp_paycheck_usage_2020  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_nu1_2021 on pspadm.psp_paycheck_usage_2021  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_nu1_2022 on pspadm.psp_paycheck_usage_2022  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_nu1_2023 on pspadm.psp_paycheck_usage_2023  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_nu1_2024 on pspadm.psp_paycheck_usage_2024  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_nu1_2025 on pspadm.psp_paycheck_usage_2025  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_nu1_2026 on pspadm.psp_paycheck_usage_2026  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2012 on pspadm.psp_paycheck_usage_2012  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2013 on pspadm.psp_paycheck_usage_2013  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2014 on pspadm.psp_paycheck_usage_2014  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2015 on pspadm.psp_paycheck_usage_2015  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2016 on pspadm.psp_paycheck_usage_2016  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2017 on pspadm.psp_paycheck_usage_2017  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2018 on pspadm.psp_paycheck_usage_2018  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2019 on pspadm.psp_paycheck_usage_2019  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2020 on pspadm.psp_paycheck_usage_2020  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2021 on pspadm.psp_paycheck_usage_2021  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2022 on pspadm.psp_paycheck_usage_2022  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2023 on pspadm.psp_paycheck_usage_2023  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2024 on pspadm.psp_paycheck_usage_2024  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2025 on pspadm.psp_paycheck_usage_2025  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2026 on pspadm.psp_paycheck_usage_2026  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index concurrently psp_paycheckusage_fk1_2012 on pspadm.psp_paycheck_usage_2012  USING BTREE (bill_fk ASC);
create index concurrently psp_paycheckusage_fk1_2013 on pspadm.psp_paycheck_usage_2013  USING BTREE (bill_fk ASC);
create index concurrently psp_paycheckusage_fk1_2014 on pspadm.psp_paycheck_usage_2014  USING BTREE (bill_fk ASC);
create index concurrently psp_paycheckusage_fk1_2015 on pspadm.psp_paycheck_usage_2015  USING BTREE (bill_fk ASC);
create index concurrently psp_paycheckusage_fk1_2016 on pspadm.psp_paycheck_usage_2016  USING BTREE (bill_fk ASC);
create index concurrently psp_paycheckusage_fk1_2017 on pspadm.psp_paycheck_usage_2017  USING BTREE (bill_fk ASC);
create index concurrently psp_paycheckusage_fk1_2018 on pspadm.psp_paycheck_usage_2018  USING BTREE (bill_fk ASC);
create index concurrently psp_paycheckusage_fk1_2019 on pspadm.psp_paycheck_usage_2019  USING BTREE (bill_fk ASC);
create index concurrently psp_paycheckusage_fk1_2020 on pspadm.psp_paycheck_usage_2020  USING BTREE (bill_fk ASC);
create index concurrently psp_paycheckusage_fk1_2021 on pspadm.psp_paycheck_usage_2021  USING BTREE (bill_fk ASC);
create index concurrently psp_paycheckusage_fk1_2022 on pspadm.psp_paycheck_usage_2022  USING BTREE (bill_fk ASC);
create index concurrently psp_paycheckusage_fk1_2023 on pspadm.psp_paycheck_usage_2023  USING BTREE (bill_fk ASC);
create index concurrently psp_paycheckusage_fk1_2024 on pspadm.psp_paycheck_usage_2024  USING BTREE (bill_fk ASC);
create index concurrently psp_paycheckusage_fk1_2025 on pspadm.psp_paycheck_usage_2025  USING BTREE (bill_fk ASC);
create index concurrently psp_paycheckusage_fk1_2026 on pspadm.psp_paycheck_usage_2026  USING BTREE (bill_fk ASC);
create index concurrently psp_paycheckusage_fk2_2012 on pspadm.psp_paycheck_usage_2012  USING BTREE (employee_usage_fk ASC);
create index concurrently psp_paycheckusage_fk2_2013 on pspadm.psp_paycheck_usage_2013  USING BTREE (employee_usage_fk ASC);
create index concurrently psp_paycheckusage_fk2_2014 on pspadm.psp_paycheck_usage_2014  USING BTREE (employee_usage_fk ASC);
create index concurrently psp_paycheckusage_fk2_2015 on pspadm.psp_paycheck_usage_2015  USING BTREE (employee_usage_fk ASC);
create index concurrently psp_paycheckusage_fk2_2016 on pspadm.psp_paycheck_usage_2016  USING BTREE (employee_usage_fk ASC);
create index concurrently psp_paycheckusage_fk2_2017 on pspadm.psp_paycheck_usage_2017  USING BTREE (employee_usage_fk ASC);
create index concurrently psp_paycheckusage_fk2_2018 on pspadm.psp_paycheck_usage_2018  USING BTREE (employee_usage_fk ASC);
create index concurrently psp_paycheckusage_fk2_2019 on pspadm.psp_paycheck_usage_2019  USING BTREE (employee_usage_fk ASC);
create index concurrently psp_paycheckusage_fk2_2020 on pspadm.psp_paycheck_usage_2020  USING BTREE (employee_usage_fk ASC);
create index concurrently psp_paycheckusage_fk2_2021 on pspadm.psp_paycheck_usage_2021  USING BTREE (employee_usage_fk ASC);
create index concurrently psp_paycheckusage_fk2_2022 on pspadm.psp_paycheck_usage_2022  USING BTREE (employee_usage_fk ASC);
create index concurrently psp_paycheckusage_fk2_2023 on pspadm.psp_paycheck_usage_2023  USING BTREE (employee_usage_fk ASC);
create index concurrently psp_paycheckusage_fk2_2024 on pspadm.psp_paycheck_usage_2024  USING BTREE (employee_usage_fk ASC);
create index concurrently psp_paycheckusage_fk2_2025 on pspadm.psp_paycheck_usage_2025  USING BTREE (employee_usage_fk ASC);
create index concurrently psp_paycheckusage_fk2_2026 on pspadm.psp_paycheck_usage_2026  USING BTREE (employee_usage_fk ASC);

create index psp_paycheckusage_fk1 ON ONLY  pspadm.psp_paycheck_usage USING BTREE (bill_fk ASC);
create index psp_paycheckusage_fk2 ON ONLY  pspadm.psp_paycheck_usage USING BTREE (employee_usage_fk ASC);
create index psp_paycheck_usage_fk1 ON ONLY  pspadm.psp_paycheck_usage USING BTREE (company_fk ASC);
create index psp_paycheck_usage_nu1 ON ONLY  pspadm.psp_paycheck_usage USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_u1 ON ONLY  pspadm.psp_paycheck_usage USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);

alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2012 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2013 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2014 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2015 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2016 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2017 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2018 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2019 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2020 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2021 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2022 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2023 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2024 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2025 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2026 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2012 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2013 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2014 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2015 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2016 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2017 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2018 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2019 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2020 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2021 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2022 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2023 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2024 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2025 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2026 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2012 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2013 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2014 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2015 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2016 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2017 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2018 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2019 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2020 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2021 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2022 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2023 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2024 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2025 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2026 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2012 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2013 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2014 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2015 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2016 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2017 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2018 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2019 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2020 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2021 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2022 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2023 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2024 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2025 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2026 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2012 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2013 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2014 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2015 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2016 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2017 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2018 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2019 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2020 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2021 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2022 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2023 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2024 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2025 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2026 ;

create index concurrently psp_entitlement_message_u1_2012 on pspadm.psp_entitlement_message_2012  USING BTREE (token ASC);
create index concurrently psp_entitlement_message_u1_2013 on pspadm.psp_entitlement_message_2013  USING BTREE (token ASC);
create index concurrently psp_entitlement_message_u1_2014 on pspadm.psp_entitlement_message_2014  USING BTREE (token ASC);
create index concurrently psp_entitlement_message_u1_2015 on pspadm.psp_entitlement_message_2015  USING BTREE (token ASC);
create index concurrently psp_entitlement_message_u1_2016 on pspadm.psp_entitlement_message_2016  USING BTREE (token ASC);
create index concurrently psp_entitlement_message_u1_2017 on pspadm.psp_entitlement_message_2017  USING BTREE (token ASC);
create index concurrently psp_entitlement_message_u1_2018 on pspadm.psp_entitlement_message_2018  USING BTREE (token ASC);
create index concurrently psp_entitlement_message_u1_2019 on pspadm.psp_entitlement_message_2019  USING BTREE (token ASC);
create index concurrently psp_entitlement_message_u1_2020 on pspadm.psp_entitlement_message_2020  USING BTREE (token ASC);
create index concurrently psp_entitlement_message_u1_2021 on pspadm.psp_entitlement_message_2021  USING BTREE (token ASC);
create index concurrently psp_entitlement_message_u1_2022 on pspadm.psp_entitlement_message_2022  USING BTREE (token ASC);
create index concurrently psp_entitlement_message_u1_2023 on pspadm.psp_entitlement_message_2023  USING BTREE (token ASC);
create index concurrently psp_entitlement_message_u1_2024 on pspadm.psp_entitlement_message_2024  USING BTREE (token ASC);
create index concurrently psp_entitlement_message_u1_2025 on pspadm.psp_entitlement_message_2025  USING BTREE (token ASC);
create index concurrently psp_entitlement_message_u1_2026 on pspadm.psp_entitlement_message_2026  USING BTREE (token ASC);
create index concurrently psp_entitlement_msg_lcno_eofcd_2012 on pspadm.psp_entitlement_message_2012  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index concurrently psp_entitlement_msg_lcno_eofcd_2013 on pspadm.psp_entitlement_message_2013  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index concurrently psp_entitlement_msg_lcno_eofcd_2014 on pspadm.psp_entitlement_message_2014  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index concurrently psp_entitlement_msg_lcno_eofcd_2015 on pspadm.psp_entitlement_message_2015  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index concurrently psp_entitlement_msg_lcno_eofcd_2016 on pspadm.psp_entitlement_message_2016  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index concurrently psp_entitlement_msg_lcno_eofcd_2017 on pspadm.psp_entitlement_message_2017  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index concurrently psp_entitlement_msg_lcno_eofcd_2018 on pspadm.psp_entitlement_message_2018  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index concurrently psp_entitlement_msg_lcno_eofcd_2019 on pspadm.psp_entitlement_message_2019  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index concurrently psp_entitlement_msg_lcno_eofcd_2020 on pspadm.psp_entitlement_message_2020  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index concurrently psp_entitlement_msg_lcno_eofcd_2021 on pspadm.psp_entitlement_message_2021  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index concurrently psp_entitlement_msg_lcno_eofcd_2022 on pspadm.psp_entitlement_message_2022  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index concurrently psp_entitlement_msg_lcno_eofcd_2023 on pspadm.psp_entitlement_message_2023  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index concurrently psp_entitlement_msg_lcno_eofcd_2024 on pspadm.psp_entitlement_message_2024  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index concurrently psp_entitlement_msg_lcno_eofcd_2025 on pspadm.psp_entitlement_message_2025  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index concurrently psp_entitlement_msg_lcno_eofcd_2026 on pspadm.psp_entitlement_message_2026  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index concurrently psp_entitlement_msg_msgts_er_2012 on pspadm.psp_entitlement_message_2012  USING BTREE (message_timestamp ASC,event_reason ASC);
create index concurrently psp_entitlement_msg_msgts_er_2013 on pspadm.psp_entitlement_message_2013  USING BTREE (message_timestamp ASC,event_reason ASC);
create index concurrently psp_entitlement_msg_msgts_er_2014 on pspadm.psp_entitlement_message_2014  USING BTREE (message_timestamp ASC,event_reason ASC);
create index concurrently psp_entitlement_msg_msgts_er_2015 on pspadm.psp_entitlement_message_2015  USING BTREE (message_timestamp ASC,event_reason ASC);
create index concurrently psp_entitlement_msg_msgts_er_2016 on pspadm.psp_entitlement_message_2016  USING BTREE (message_timestamp ASC,event_reason ASC);
create index concurrently psp_entitlement_msg_msgts_er_2017 on pspadm.psp_entitlement_message_2017  USING BTREE (message_timestamp ASC,event_reason ASC);
create index concurrently psp_entitlement_msg_msgts_er_2018 on pspadm.psp_entitlement_message_2018  USING BTREE (message_timestamp ASC,event_reason ASC);
create index concurrently psp_entitlement_msg_msgts_er_2019 on pspadm.psp_entitlement_message_2019  USING BTREE (message_timestamp ASC,event_reason ASC);
create index concurrently psp_entitlement_msg_msgts_er_2020 on pspadm.psp_entitlement_message_2020  USING BTREE (message_timestamp ASC,event_reason ASC);
create index concurrently psp_entitlement_msg_msgts_er_2021 on pspadm.psp_entitlement_message_2021  USING BTREE (message_timestamp ASC,event_reason ASC);
create index concurrently psp_entitlement_msg_msgts_er_2022 on pspadm.psp_entitlement_message_2022  USING BTREE (message_timestamp ASC,event_reason ASC);
create index concurrently psp_entitlement_msg_msgts_er_2023 on pspadm.psp_entitlement_message_2023  USING BTREE (message_timestamp ASC,event_reason ASC);
create index concurrently psp_entitlement_msg_msgts_er_2024 on pspadm.psp_entitlement_message_2024  USING BTREE (message_timestamp ASC,event_reason ASC);
create index concurrently psp_entitlement_msg_msgts_er_2025 on pspadm.psp_entitlement_message_2025  USING BTREE (message_timestamp ASC,event_reason ASC);
create index concurrently psp_entitlement_msg_msgts_er_2026 on pspadm.psp_entitlement_message_2026  USING BTREE (message_timestamp ASC,event_reason ASC);
create index concurrently psp_entitlement_msg_orno_lcno_2012 on pspadm.psp_entitlement_message_2012  USING BTREE (order_number ASC,license_number ASC);
create index concurrently psp_entitlement_msg_orno_lcno_2013 on pspadm.psp_entitlement_message_2013  USING BTREE (order_number ASC,license_number ASC);
create index concurrently psp_entitlement_msg_orno_lcno_2014 on pspadm.psp_entitlement_message_2014  USING BTREE (order_number ASC,license_number ASC);
create index concurrently psp_entitlement_msg_orno_lcno_2015 on pspadm.psp_entitlement_message_2015  USING BTREE (order_number ASC,license_number ASC);
create index concurrently psp_entitlement_msg_orno_lcno_2016 on pspadm.psp_entitlement_message_2016  USING BTREE (order_number ASC,license_number ASC);
create index concurrently psp_entitlement_msg_orno_lcno_2017 on pspadm.psp_entitlement_message_2017  USING BTREE (order_number ASC,license_number ASC);
create index concurrently psp_entitlement_msg_orno_lcno_2018 on pspadm.psp_entitlement_message_2018  USING BTREE (order_number ASC,license_number ASC);
create index concurrently psp_entitlement_msg_orno_lcno_2019 on pspadm.psp_entitlement_message_2019  USING BTREE (order_number ASC,license_number ASC);
create index concurrently psp_entitlement_msg_orno_lcno_2020 on pspadm.psp_entitlement_message_2020  USING BTREE (order_number ASC,license_number ASC);
create index concurrently psp_entitlement_msg_orno_lcno_2021 on pspadm.psp_entitlement_message_2021  USING BTREE (order_number ASC,license_number ASC);
create index concurrently psp_entitlement_msg_orno_lcno_2022 on pspadm.psp_entitlement_message_2022  USING BTREE (order_number ASC,license_number ASC);
create index concurrently psp_entitlement_msg_orno_lcno_2023 on pspadm.psp_entitlement_message_2023  USING BTREE (order_number ASC,license_number ASC);
create index concurrently psp_entitlement_msg_orno_lcno_2024 on pspadm.psp_entitlement_message_2024  USING BTREE (order_number ASC,license_number ASC);
create index concurrently psp_entitlement_msg_orno_lcno_2025 on pspadm.psp_entitlement_message_2025  USING BTREE (order_number ASC,license_number ASC);
create index concurrently psp_entitlement_msg_orno_lcno_2026 on pspadm.psp_entitlement_message_2026  USING BTREE (order_number ASC,license_number ASC);

create index psp_entitlement_message_u1 ON ONLY  pspadm.psp_entitlement_message USING BTREE (token ASC);
create index psp_entitlement_msg_lcno_eofcd ON ONLY  pspadm.psp_entitlement_message USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index psp_entitlement_msg_msgts_er ON ONLY  pspadm.psp_entitlement_message USING BTREE (message_timestamp ASC,event_reason  ASC);
create index psp_entitlement_msg_orno_lcno ON ONLY  pspadm.psp_entitlement_message USING BTREE (order_number ASC,license_number ASC);
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2012 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2013 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2014 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2015 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2016 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2017 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2018 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2019 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2020 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2021 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2022 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2023 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2024 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2025 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2026 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2012 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2013 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2014 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2015 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2016 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2017 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2018 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2019 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2020 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2021 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2022 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2023 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2024 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2025 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2026 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2012 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2013 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2014 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2015 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2016 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2017 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2018 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2019 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2020 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2021 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2022 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2023 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2024 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2025 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2026 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2012 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2013 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2014 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2015 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2016 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2017 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2018 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2019 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2020 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2021 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2022 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2023 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2024 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2025 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2026 ;

create index idx_entityupdate_crdate_m112022 on pspadm.psp_entity_update_m112022 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m122022 on pspadm.psp_entity_update_m122022 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m012023 on pspadm.psp_entity_update_m012023 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m022023 on pspadm.psp_entity_update_m022023 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m032023 on pspadm.psp_entity_update_m032023 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m042023 on pspadm.psp_entity_update_m042023 USING BTREE (created_date ASC);

create index idx_entityupdate_crdate_m052023 on pspadm.psp_entity_update_m052023 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m062023 on pspadm.psp_entity_update_m062023 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m072023 on pspadm.psp_entity_update_m072023 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m082023 on pspadm.psp_entity_update_m082023 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m092023 on pspadm.psp_entity_update_m092023 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m102023 on pspadm.psp_entity_update_m102023 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m112023 on pspadm.psp_entity_update_m112023 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m122023 on pspadm.psp_entity_update_m122023 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m012024 on pspadm.psp_entity_update_m012024 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m022024 on pspadm.psp_entity_update_m022024 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m032024 on pspadm.psp_entity_update_m032024 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m042024 on pspadm.psp_entity_update_m042024 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m052024 on pspadm.psp_entity_update_m052024 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m062024 on pspadm.psp_entity_update_m052024 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m072024 on pspadm.psp_entity_update_m072024 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m082024 on pspadm.psp_entity_update_m082024 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m092024 on pspadm.psp_entity_update_m092024 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m102024 on pspadm.psp_entity_update_m102024 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m112024 on pspadm.psp_entity_update_m112024 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m122024 on pspadm.psp_entity_update_m122024 USING BTREE (created_date ASC);

create index idx_entityupdate_crdate_m012025 on pspadm.psp_entity_update_m012025 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m022025 on pspadm.psp_entity_update_m022025 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m032025 on pspadm.psp_entity_update_m032025 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m042025 on pspadm.psp_entity_update_m042025 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m052025 on pspadm.psp_entity_update_m052025 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m062025 on pspadm.psp_entity_update_m052025 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m072025 on pspadm.psp_entity_update_m072025 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m082025 on pspadm.psp_entity_update_m082025 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m092025 on pspadm.psp_entity_update_m092025 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m102025 on pspadm.psp_entity_update_m102025 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m112025 on pspadm.psp_entity_update_m112025 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m122025 on pspadm.psp_entity_update_m122025 USING BTREE (created_date ASC);

create index idx_entityupdate_crdate_m012026 on pspadm.psp_entity_update_m012026 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m022026 on pspadm.psp_entity_update_m022026 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m032026 on pspadm.psp_entity_update_m032026 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m042026 on pspadm.psp_entity_update_m042026 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m052026 on pspadm.psp_entity_update_m052026 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m062026 on pspadm.psp_entity_update_m052026 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m072026 on pspadm.psp_entity_update_m072026 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m082026 on pspadm.psp_entity_update_m082026 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m092026 on pspadm.psp_entity_update_m092026 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m102026 on pspadm.psp_entity_update_m102026 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m112026 on pspadm.psp_entity_update_m112026 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m122026 on pspadm.psp_entity_update_m122026 USING BTREE (created_date ASC);

create index idx_entityupdate_crdate ON ONLY  pspadm.psp_entity_update USING BTREE (created_date ASC);
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m112022 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m122022 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m012023 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m022023 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m032023 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m042023 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m052023 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m062023 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m072023 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m082023 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m092023 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m102023 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m112023 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m122023 ;

alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m012024 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m022024 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m032024 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m042024 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m052024 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m062024 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m072024 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m082024 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m092024 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m102024 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m112024 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m122024 ;

alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m012025 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m022025 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m032025 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m042025 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m052025 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m062025 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m072025 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m082025 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m092025 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m102025 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m112025 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m122025 ;

alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m012026 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m022026 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m032026 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m042026 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m052026 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m062026 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m072026 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m082026 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m092026 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m102026 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m112026 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m122026 ;

create index psp_paycheck_split_i1_p0 on pspadm.psp_paycheck_split_p0 USING BTREE (created_date);
create index psp_paycheck_split_i1_p1 on pspadm.psp_paycheck_split_p1 USING BTREE (created_date);
create index psp_paycheck_split_i1_p2 on pspadm.psp_paycheck_split_p2 USING BTREE (created_date);
create index psp_paycheck_split_i1_p3 on pspadm.psp_paycheck_split_p3 USING BTREE (created_date);
create index psp_paycheck_split_i1_p4 on pspadm.psp_paycheck_split_p4 USING BTREE (created_date);
create index psp_paycheck_split_i1_p5 on pspadm.psp_paycheck_split_p5 USING BTREE (created_date);
create index psp_paycheck_split_i1_p6 on pspadm.psp_paycheck_split_p6 USING BTREE (created_date);
create index psp_paycheck_split_i1_p7 on pspadm.psp_paycheck_split_p7 USING BTREE (created_date);
create index psp_paycheck_split_i1_p8 on pspadm.psp_paycheck_split_p8 USING BTREE (created_date);
create index psp_paycheck_split_i1_p9 on pspadm.psp_paycheck_split_p9 USING BTREE (created_date);
create index psp_paycheck_split_i1_p10 on pspadm.psp_paycheck_split_p10 USING BTREE (created_date);
create index psp_paycheck_split_i1_p11 on pspadm.psp_paycheck_split_p11 USING BTREE (created_date);
create index psp_paycheck_split_i1_p12 on pspadm.psp_paycheck_split_p12 USING BTREE (created_date);
create index psp_paycheck_split_i1_p13 on pspadm.psp_paycheck_split_p13 USING BTREE (created_date);
create index psp_paycheck_split_i1_p14 on pspadm.psp_paycheck_split_p14 USING BTREE (created_date);
create index psp_paycheck_split_i1_p15 on pspadm.psp_paycheck_split_p15 USING BTREE (created_date);

create index psp_paycheck_split_i1 ON ONLY pspadm.psp_paycheck_split USING BTREE (created_date);
alter index psp_paycheck_split_i1 attach partition pspadm.psp_paycheck_split_i1_p0;
alter index psp_paycheck_split_i1 attach partition pspadm.psp_paycheck_split_i1_p1;
alter index psp_paycheck_split_i1 attach partition pspadm.psp_paycheck_split_i1_p2;
alter index psp_paycheck_split_i1 attach partition pspadm.psp_paycheck_split_i1_p3;
alter index psp_paycheck_split_i1 attach partition pspadm.psp_paycheck_split_i1_p4;
alter index psp_paycheck_split_i1 attach partition pspadm.psp_paycheck_split_i1_p5;
alter index psp_paycheck_split_i1 attach partition pspadm.psp_paycheck_split_i1_p6;
alter index psp_paycheck_split_i1 attach partition pspadm.psp_paycheck_split_i1_p7;
alter index psp_paycheck_split_i1 attach partition pspadm.psp_paycheck_split_i1_p8;
alter index psp_paycheck_split_i1 attach partition pspadm.psp_paycheck_split_i1_p9;
alter index psp_paycheck_split_i1 attach partition pspadm.psp_paycheck_split_i1_p10;
alter index psp_paycheck_split_i1 attach partition pspadm.psp_paycheck_split_i1_p11;
alter index psp_paycheck_split_i1 attach partition pspadm.psp_paycheck_split_i1_p12;
alter index psp_paycheck_split_i1 attach partition pspadm.psp_paycheck_split_i1_p13;
alter index psp_paycheck_split_i1 attach partition pspadm.psp_paycheck_split_i1_p14;
alter index psp_paycheck_split_i1 attach partition pspadm.psp_paycheck_split_i1_p15;

