//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.14 at 10:29:12 AM PDT 
//


package com.intuit.ias.notification.pub.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BasicContentDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BasicContentDataType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.intuit.com/ias/notification/pub/xsd}ContentDataType">
 *       &lt;all>
 *         &lt;element name="ContentProviderId" type="{http://www.intuit.com/ias/common/xsd}IDDataType" minOccurs="0"/>
 *         &lt;element name="ContentId" type="{http://www.intuit.com/ias/common/xsd}IDDataType"/>
 *         &lt;element name="Subject" type="{http://www.intuit.com/ias/common/xsd}DescriptionDataType" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BasicContentDataType", propOrder = {
    "contentProviderId",
    "contentId",
    "subject"
})
public class BasicContentDataType
    extends ContentDataType
{

    @XmlElement(name = "ContentProviderId")
    protected String contentProviderId;
    @XmlElement(name = "ContentId", required = true)
    protected String contentId;
    @XmlElement(name = "Subject")
    protected String subject;

    /**
     * Gets the value of the contentProviderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentProviderId() {
        return contentProviderId;
    }

    /**
     * Sets the value of the contentProviderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentProviderId(String value) {
        this.contentProviderId = value;
    }

    /**
     * Gets the value of the contentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentId() {
        return contentId;
    }

    /**
     * Sets the value of the contentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentId(String value) {
        this.contentId = value;
    }

    /**
     * Gets the value of the subject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubject(String value) {
        this.subject = value;
    }

}
