//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.14 at 10:29:12 AM PDT 
//


package com.intuit.ias.notification.pub.xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for NotificationDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NotificationDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="NotificationType" type="{http://www.intuit.com/ias/notification/pub/xsd}NotificationTypeDataType"/>
 *         &lt;element name="DeliveryType">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="Immediate">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Scheduled" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="Delayed" type="{http://www.intuit.com/ias/notification/pub/xsd}TimeIntervalDataType"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SenderProfile">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="SenderId" type="{http://www.intuit.com/ias/common/xsd}IDDataType"/>
 *                   &lt;element name="Sender" type="{http://www.intuit.com/ias/notification/pub/xsd}SenderDataType" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ContentProfile">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="Content" type="{http://www.intuit.com/ias/notification/pub/xsd}ContentDataType"/>
 *                   &lt;element name="TemplateProperties" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Attribute" type="{http://www.intuit.com/ias/notification/pub/xsd}AttributeDataType" maxOccurs="100"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Destinations">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Destination" maxOccurs="1000">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="RecipientId" type="{http://www.intuit.com/ias/common/xsd}IDDataType" minOccurs="0"/>
 *                             &lt;element name="Recipient" type="{http://www.intuit.com/ias/notification/pub/xsd}RecipientDataType"/>
 *                             &lt;element name="Format" type="{http://www.intuit.com/ias/notification/pub/xsd}ContentFormatDataType"/>
 *                             &lt;element name="TemplateProperties" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Attribute" type="{http://www.intuit.com/ias/notification/pub/xsd}AttributeDataType" maxOccurs="100"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NotificationDataType", propOrder = {

})
public class NotificationDataType {

    @XmlElement(name = "NotificationType", required = true)
    protected NotificationTypeDataType notificationType;
    @XmlElement(name = "DeliveryType", required = true)
    protected NotificationDataType.DeliveryType deliveryType;
    @XmlElement(name = "SenderProfile", required = true)
    protected NotificationDataType.SenderProfile senderProfile;
    @XmlElement(name = "ContentProfile", required = true)
    protected NotificationDataType.ContentProfile contentProfile;
    @XmlElement(name = "Destinations", required = true)
    protected NotificationDataType.Destinations destinations;

    /**
     * Gets the value of the notificationType property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationTypeDataType }
     *     
     */
    public NotificationTypeDataType getNotificationType() {
        return notificationType;
    }

    /**
     * Sets the value of the notificationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationTypeDataType }
     *     
     */
    public void setNotificationType(NotificationTypeDataType value) {
        this.notificationType = value;
    }

    /**
     * Gets the value of the deliveryType property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationDataType.DeliveryType }
     *     
     */
    public NotificationDataType.DeliveryType getDeliveryType() {
        return deliveryType;
    }

    /**
     * Sets the value of the deliveryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationDataType.DeliveryType }
     *     
     */
    public void setDeliveryType(NotificationDataType.DeliveryType value) {
        this.deliveryType = value;
    }

    /**
     * Gets the value of the senderProfile property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationDataType.SenderProfile }
     *     
     */
    public NotificationDataType.SenderProfile getSenderProfile() {
        return senderProfile;
    }

    /**
     * Sets the value of the senderProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationDataType.SenderProfile }
     *     
     */
    public void setSenderProfile(NotificationDataType.SenderProfile value) {
        this.senderProfile = value;
    }

    /**
     * Gets the value of the contentProfile property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationDataType.ContentProfile }
     *     
     */
    public NotificationDataType.ContentProfile getContentProfile() {
        return contentProfile;
    }

    /**
     * Sets the value of the contentProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationDataType.ContentProfile }
     *     
     */
    public void setContentProfile(NotificationDataType.ContentProfile value) {
        this.contentProfile = value;
    }

    /**
     * Gets the value of the destinations property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationDataType.Destinations }
     *     
     */
    public NotificationDataType.Destinations getDestinations() {
        return destinations;
    }

    /**
     * Sets the value of the destinations property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationDataType.Destinations }
     *     
     */
    public void setDestinations(NotificationDataType.Destinations value) {
        this.destinations = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="Content" type="{http://www.intuit.com/ias/notification/pub/xsd}ContentDataType"/>
     *         &lt;element name="TemplateProperties" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Attribute" type="{http://www.intuit.com/ias/notification/pub/xsd}AttributeDataType" maxOccurs="100"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class ContentProfile {

        @XmlElement(name = "Content", required = true)
        protected ContentDataType content;
        @XmlElement(name = "TemplateProperties")
        protected NotificationDataType.ContentProfile.TemplateProperties templateProperties;

        /**
         * Gets the value of the content property.
         * 
         * @return
         *     possible object is
         *     {@link ContentDataType }
         *     
         */
        public ContentDataType getContent() {
            return content;
        }

        /**
         * Sets the value of the content property.
         * 
         * @param value
         *     allowed object is
         *     {@link ContentDataType }
         *     
         */
        public void setContent(ContentDataType value) {
            this.content = value;
        }

        /**
         * Gets the value of the templateProperties property.
         * 
         * @return
         *     possible object is
         *     {@link NotificationDataType.ContentProfile.TemplateProperties }
         *     
         */
        public NotificationDataType.ContentProfile.TemplateProperties getTemplateProperties() {
            return templateProperties;
        }

        /**
         * Sets the value of the templateProperties property.
         * 
         * @param value
         *     allowed object is
         *     {@link NotificationDataType.ContentProfile.TemplateProperties }
         *     
         */
        public void setTemplateProperties(NotificationDataType.ContentProfile.TemplateProperties value) {
            this.templateProperties = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Attribute" type="{http://www.intuit.com/ias/notification/pub/xsd}AttributeDataType" maxOccurs="100"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "attribute"
        })
        public static class TemplateProperties {

            @XmlElement(name = "Attribute", required = true)
            protected List<AttributeDataType> attribute;

            /**
             * Gets the value of the attribute property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the attribute property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAttribute().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link AttributeDataType }
             * 
             * 
             */
            public List<AttributeDataType> getAttribute() {
                if (attribute == null) {
                    attribute = new ArrayList<AttributeDataType>();
                }
                return this.attribute;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="Immediate">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Scheduled" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="Delayed" type="{http://www.intuit.com/ias/notification/pub/xsd}TimeIntervalDataType"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "immediate",
        "scheduled",
        "delayed"
    })
    public static class DeliveryType {

        @XmlElement(name = "Immediate")
        protected NotificationDataType.DeliveryType.Immediate immediate;
        @XmlElement(name = "Scheduled")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar scheduled;
        @XmlElement(name = "Delayed")
        protected TimeIntervalDataType delayed;

        /**
         * Gets the value of the immediate property.
         * 
         * @return
         *     possible object is
         *     {@link NotificationDataType.DeliveryType.Immediate }
         *     
         */
        public NotificationDataType.DeliveryType.Immediate getImmediate() {
            return immediate;
        }

        /**
         * Sets the value of the immediate property.
         * 
         * @param value
         *     allowed object is
         *     {@link NotificationDataType.DeliveryType.Immediate }
         *     
         */
        public void setImmediate(NotificationDataType.DeliveryType.Immediate value) {
            this.immediate = value;
        }

        /**
         * Gets the value of the scheduled property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getScheduled() {
            return scheduled;
        }

        /**
         * Sets the value of the scheduled property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setScheduled(XMLGregorianCalendar value) {
            this.scheduled = value;
        }

        /**
         * Gets the value of the delayed property.
         * 
         * @return
         *     possible object is
         *     {@link TimeIntervalDataType }
         *     
         */
        public TimeIntervalDataType getDelayed() {
            return delayed;
        }

        /**
         * Sets the value of the delayed property.
         * 
         * @param value
         *     allowed object is
         *     {@link TimeIntervalDataType }
         *     
         */
        public void setDelayed(TimeIntervalDataType value) {
            this.delayed = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Immediate {


        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Destination" maxOccurs="1000">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="RecipientId" type="{http://www.intuit.com/ias/common/xsd}IDDataType" minOccurs="0"/>
     *                   &lt;element name="Recipient" type="{http://www.intuit.com/ias/notification/pub/xsd}RecipientDataType"/>
     *                   &lt;element name="Format" type="{http://www.intuit.com/ias/notification/pub/xsd}ContentFormatDataType"/>
     *                   &lt;element name="TemplateProperties" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Attribute" type="{http://www.intuit.com/ias/notification/pub/xsd}AttributeDataType" maxOccurs="100"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "destination"
    })
    public static class Destinations {

        @XmlElement(name = "Destination", required = true)
        protected List<NotificationDataType.Destinations.Destination> destination;

        /**
         * Gets the value of the destination property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the destination property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDestination().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link NotificationDataType.Destinations.Destination }
         * 
         * 
         */
        public List<NotificationDataType.Destinations.Destination> getDestination() {
            if (destination == null) {
                destination = new ArrayList<NotificationDataType.Destinations.Destination>();
            }
            return this.destination;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="RecipientId" type="{http://www.intuit.com/ias/common/xsd}IDDataType" minOccurs="0"/>
         *         &lt;element name="Recipient" type="{http://www.intuit.com/ias/notification/pub/xsd}RecipientDataType"/>
         *         &lt;element name="Format" type="{http://www.intuit.com/ias/notification/pub/xsd}ContentFormatDataType"/>
         *         &lt;element name="TemplateProperties" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Attribute" type="{http://www.intuit.com/ias/notification/pub/xsd}AttributeDataType" maxOccurs="100"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class Destination {

            @XmlElement(name = "RecipientId")
            protected String recipientId;
            @XmlElement(name = "Recipient", required = true)
            protected RecipientDataType recipient;
            @XmlElement(name = "Format", required = true)
            protected ContentFormatDataType format;
            @XmlElement(name = "TemplateProperties")
            protected NotificationDataType.Destinations.Destination.TemplateProperties templateProperties;

            /**
             * Gets the value of the recipientId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRecipientId() {
                return recipientId;
            }

            /**
             * Sets the value of the recipientId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRecipientId(String value) {
                this.recipientId = value;
            }

            /**
             * Gets the value of the recipient property.
             * 
             * @return
             *     possible object is
             *     {@link RecipientDataType }
             *     
             */
            public RecipientDataType getRecipient() {
                return recipient;
            }

            /**
             * Sets the value of the recipient property.
             * 
             * @param value
             *     allowed object is
             *     {@link RecipientDataType }
             *     
             */
            public void setRecipient(RecipientDataType value) {
                this.recipient = value;
            }

            /**
             * Gets the value of the format property.
             * 
             * @return
             *     possible object is
             *     {@link ContentFormatDataType }
             *     
             */
            public ContentFormatDataType getFormat() {
                return format;
            }

            /**
             * Sets the value of the format property.
             * 
             * @param value
             *     allowed object is
             *     {@link ContentFormatDataType }
             *     
             */
            public void setFormat(ContentFormatDataType value) {
                this.format = value;
            }

            /**
             * Gets the value of the templateProperties property.
             * 
             * @return
             *     possible object is
             *     {@link NotificationDataType.Destinations.Destination.TemplateProperties }
             *     
             */
            public NotificationDataType.Destinations.Destination.TemplateProperties getTemplateProperties() {
                return templateProperties;
            }

            /**
             * Sets the value of the templateProperties property.
             * 
             * @param value
             *     allowed object is
             *     {@link NotificationDataType.Destinations.Destination.TemplateProperties }
             *     
             */
            public void setTemplateProperties(NotificationDataType.Destinations.Destination.TemplateProperties value) {
                this.templateProperties = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Attribute" type="{http://www.intuit.com/ias/notification/pub/xsd}AttributeDataType" maxOccurs="100"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "attribute"
            })
            public static class TemplateProperties {

                @XmlElement(name = "Attribute", required = true)
                protected List<AttributeDataType> attribute;

                /**
                 * Gets the value of the attribute property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the attribute property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getAttribute().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link AttributeDataType }
                 * 
                 * 
                 */
                public List<AttributeDataType> getAttribute() {
                    if (attribute == null) {
                        attribute = new ArrayList<AttributeDataType>();
                    }
                    return this.attribute;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="SenderId" type="{http://www.intuit.com/ias/common/xsd}IDDataType"/>
     *         &lt;element name="Sender" type="{http://www.intuit.com/ias/notification/pub/xsd}SenderDataType" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class SenderProfile {

        @XmlElement(name = "SenderId", required = true)
        protected String senderId;
        @XmlElement(name = "Sender")
        protected SenderDataType sender;

        /**
         * Gets the value of the senderId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSenderId() {
            return senderId;
        }

        /**
         * Sets the value of the senderId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSenderId(String value) {
            this.senderId = value;
        }

        /**
         * Gets the value of the sender property.
         * 
         * @return
         *     possible object is
         *     {@link SenderDataType }
         *     
         */
        public SenderDataType getSender() {
            return sender;
        }

        /**
         * Sets the value of the sender property.
         * 
         * @param value
         *     allowed object is
         *     {@link SenderDataType }
         *     
         */
        public void setSender(SenderDataType value) {
            this.sender = value;
        }

    }

}
