//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.14 at 10:29:12 AM PDT 
//


package com.intuit.ias.notification.pub.xsd;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.intuit.ias.notification.pub.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.intuit.ias.notification.pub.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NotificationDataType.ContentProfile }
     * 
     */
    public NotificationDataType.ContentProfile createNotificationDataTypeContentProfile() {
        return new NotificationDataType.ContentProfile();
    }

    /**
     * Create an instance of {@link SendResponse.Result }
     * 
     */
    public SendResponse.Result createSendResponseResult() {
        return new SendResponse.Result();
    }

    /**
     * Create an instance of {@link RecipientDataType }
     * 
     */
    public RecipientDataType createRecipientDataType() {
        return new RecipientDataType();
    }

    /**
     * Create an instance of {@link BasicSenderDataType }
     * 
     */
    public BasicSenderDataType createBasicSenderDataType() {
        return new BasicSenderDataType();
    }

    /**
     * Create an instance of {@link SendResponse }
     * 
     */
    public SendResponse createSendResponse() {
        return new SendResponse();
    }

    /**
     * Create an instance of {@link NotificationDataType }
     * 
     */
    public NotificationDataType createNotificationDataType() {
        return new NotificationDataType();
    }

    /**
     * Create an instance of {@link NotificationDataType.Destinations.Destination.TemplateProperties }
     * 
     */
    public NotificationDataType.Destinations.Destination.TemplateProperties createNotificationDataTypeDestinationsDestinationTemplateProperties() {
        return new NotificationDataType.Destinations.Destination.TemplateProperties();
    }

    /**
     * Create an instance of {@link BasicRecipientDataType }
     * 
     */
    public BasicRecipientDataType createBasicRecipientDataType() {
        return new BasicRecipientDataType();
    }

    /**
     * Create an instance of {@link SendRequest }
     * 
     */
    public SendRequest createSendRequest() {
        return new SendRequest();
    }

    /**
     * Create an instance of {@link NotificationDataType.DeliveryType }
     * 
     */
    public NotificationDataType.DeliveryType createNotificationDataTypeDeliveryType() {
        return new NotificationDataType.DeliveryType();
    }

    /**
     * Create an instance of {@link ContentDataType }
     * 
     */
    public ContentDataType createContentDataType() {
        return new ContentDataType();
    }

    /**
     * Create an instance of {@link AttributeDataType }
     * 
     */
    public AttributeDataType createAttributeDataType() {
        return new AttributeDataType();
    }

    /**
     * Create an instance of {@link NotificationDataType.SenderProfile }
     * 
     */
    public NotificationDataType.SenderProfile createNotificationDataTypeSenderProfile() {
        return new NotificationDataType.SenderProfile();
    }

    /**
     * Create an instance of {@link NotificationDataType.Destinations }
     * 
     */
    public NotificationDataType.Destinations createNotificationDataTypeDestinations() {
        return new NotificationDataType.Destinations();
    }

    /**
     * Create an instance of {@link NotificationDataType.ContentProfile.TemplateProperties }
     * 
     */
    public NotificationDataType.ContentProfile.TemplateProperties createNotificationDataTypeContentProfileTemplateProperties() {
        return new NotificationDataType.ContentProfile.TemplateProperties();
    }

    /**
     * Create an instance of {@link BasicContentDataType }
     * 
     */
    public BasicContentDataType createBasicContentDataType() {
        return new BasicContentDataType();
    }

    /**
     * Create an instance of {@link SenderDataType }
     * 
     */
    public SenderDataType createSenderDataType() {
        return new SenderDataType();
    }

    /**
     * Create an instance of {@link TimeIntervalDataType }
     * 
     */
    public TimeIntervalDataType createTimeIntervalDataType() {
        return new TimeIntervalDataType();
    }

    /**
     * Create an instance of {@link NotificationDataType.Destinations.Destination }
     * 
     */
    public NotificationDataType.Destinations.Destination createNotificationDataTypeDestinationsDestination() {
        return new NotificationDataType.Destinations.Destination();
    }

    /**
     * Create an instance of {@link NotificationDataType.DeliveryType.Immediate }
     * 
     */
    public NotificationDataType.DeliveryType.Immediate createNotificationDataTypeDeliveryTypeImmediate() {
        return new NotificationDataType.DeliveryType.Immediate();
    }

    /**
     * Create an instance of {@link SuccessDataType }
     * 
     */
    public SuccessDataType createSuccessDataType() {
        return new SuccessDataType();
    }

}
