//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.14 at 10:29:12 AM PDT 
//


package com.intuit.ias.notification.pub.xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.intuit.ias.common.xsd.ErrorDataType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Error" type="{http://www.intuit.com/ias/common/xsd}ErrorDataType" minOccurs="0"/>
 *         &lt;element name="Result" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="RecipientId" type="{http://www.intuit.com/ias/common/xsd}IDDataType" minOccurs="0"/>
 *                   &lt;choice>
 *                     &lt;element name="Success" type="{http://www.intuit.com/ias/notification/pub/xsd}SuccessDataType"/>
 *                     &lt;element name="Error" type="{http://www.intuit.com/ias/common/xsd}ErrorDataType"/>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.intuit.com/ias/notification/pub/xsd}ResponseAttributeGroup"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "error",
    "result"
})
@XmlRootElement(name = "SendResponse")
public class SendResponse {

    @XmlElement(name = "Error")
    protected ErrorDataType error;
    @XmlElement(name = "Result")
    protected List<SendResponse.Result> result;
    @XmlAttribute(name = "Version")
    protected String version;

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorDataType }
     *     
     */
    public ErrorDataType getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorDataType }
     *     
     */
    public void setError(ErrorDataType value) {
        this.error = value;
    }

    /**
     * Gets the value of the result property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the result property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResult().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SendResponse.Result }
     * 
     * 
     */
    public List<SendResponse.Result> getResult() {
        if (result == null) {
            result = new ArrayList<SendResponse.Result>();
        }
        return this.result;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="RecipientId" type="{http://www.intuit.com/ias/common/xsd}IDDataType" minOccurs="0"/>
     *         &lt;choice>
     *           &lt;element name="Success" type="{http://www.intuit.com/ias/notification/pub/xsd}SuccessDataType"/>
     *           &lt;element name="Error" type="{http://www.intuit.com/ias/common/xsd}ErrorDataType"/>
     *         &lt;/choice>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "recipientId",
        "success",
        "error"
    })
    public static class Result {

        @XmlElement(name = "RecipientId")
        protected String recipientId;
        @XmlElement(name = "Success")
        protected SuccessDataType success;
        @XmlElement(name = "Error")
        protected ErrorDataType error;

        /**
         * Gets the value of the recipientId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecipientId() {
            return recipientId;
        }

        /**
         * Sets the value of the recipientId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecipientId(String value) {
            this.recipientId = value;
        }

        /**
         * Gets the value of the success property.
         * 
         * @return
         *     possible object is
         *     {@link SuccessDataType }
         *     
         */
        public SuccessDataType getSuccess() {
            return success;
        }

        /**
         * Sets the value of the success property.
         * 
         * @param value
         *     allowed object is
         *     {@link SuccessDataType }
         *     
         */
        public void setSuccess(SuccessDataType value) {
            this.success = value;
        }

        /**
         * Gets the value of the error property.
         * 
         * @return
         *     possible object is
         *     {@link ErrorDataType }
         *     
         */
        public ErrorDataType getError() {
            return error;
        }

        /**
         * Sets the value of the error property.
         * 
         * @param value
         *     allowed object is
         *     {@link ErrorDataType }
         *     
         */
        public void setError(ErrorDataType value) {
            this.error = value;
        }

    }

}
