//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.14 at 10:29:12 AM PDT 
//


package com.intuit.ias.notification.pub.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Represents an interval of time interval."
 * 						
 * 
 * <p>Java class for TimeIntervalDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TimeIntervalDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="TimeUnit" type="{http://www.intuit.com/ias/notification/pub/xsd}TimeUnitDataType"/>
 *         &lt;element name="TimeAmount" type="{http://www.intuit.com/ias/notification/pub/xsd}TimeAmountDataType"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TimeIntervalDataType", propOrder = {

})
public class TimeIntervalDataType {

    @XmlElement(name = "TimeUnit", required = true)
    protected TimeUnitDataType timeUnit;
    @XmlElement(name = "TimeAmount")
    protected int timeAmount;

    /**
     * Gets the value of the timeUnit property.
     * 
     * @return
     *     possible object is
     *     {@link TimeUnitDataType }
     *     
     */
    public TimeUnitDataType getTimeUnit() {
        return timeUnit;
    }

    /**
     * Sets the value of the timeUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeUnitDataType }
     *     
     */
    public void setTimeUnit(TimeUnitDataType value) {
        this.timeUnit = value;
    }

    /**
     * Gets the value of the timeAmount property.
     * 
     */
    public int getTimeAmount() {
        return timeAmount;
    }

    /**
     * Sets the value of the timeAmount property.
     * 
     */
    public void setTimeAmount(int value) {
        this.timeAmount = value;
    }

}
