   CREATE USER "TESTGEN" IDENTIFIED BY "BxOZlq#if74uyr"
      DEFAULT TABLESPACE "PSP_DATA01"
      TEMPORARY TABLESPACE "TEMP"
      PROFILE "APPLICATION_HIGH_RISK_PROFILE";
 ALTER USER "TESTGEN" LOCAL TEMPORARY TABLESPACE "TEMP";
   GRANT "CONNECT" TO "TESTGEN";
   GRANT "RESOURCE" TO "TESTGEN";
   GRANT "PSPAPP_ROLE" TO "TESTGEN" WITH ADMIN OPTION;
   GRANT "PSPREAD_ROLE" TO "TESTGEN" WITH ADMIN OPTION;
  GRANT CREATE ANY OUTLINE TO "TESTGEN";
  GRANT CREATE ANY CONTEXT TO "TESTGEN";
  GRANT CREATE ROLE TO "TESTGEN";
  GRANT CREATE DATABASE LINK TO "TESTGEN";
  GRANT DROP ANY SYNONYM TO "TESTGEN";
  GRANT CREATE ANY SYNONYM TO "TESTGEN";
  GRANT UNLIMITED TABLESPACE TO "TESTGEN";
  GRANT SELECT ON "SYS"."DBA_USERS" TO "TESTGEN";
  GRANT EXECUTE ON "SYS"."DBMS_LOCK" TO "TESTGEN";
  GRANT SELECT ON "PSPLOG"."PSE_EVENT_LOG" TO "TESTGEN";
  GRANT EXECUTE ON "PSPLOG"."PK_LOGGING_MONITORING" TO "TESTGEN";
  GRANT SELECT ON "APPBUGFIX"."TEMP_SRC_EMP_ID_8_13" TO "TESTGEN";
  GRANT SELECT ON "APPBUGFIX"."TEMP_TOR_2_28" TO "TESTGEN";
  GRANT SELECT ON "APPBUGFIX"."TEMP_SRC_EMP_ID" TO "TESTGEN";
  GRANT EXECUTE ON "APPBUGFIX"."FN_GMT_LOCAL_MIDNIGHT" TO "TESTGEN";
   ALTER USER "TESTGEN" DEFAULT ROLE ALL;

