\timing
set search_path=pspadm;
SELECT CURRENT_TIMESTAMP;
--psp_entitlement_message
create index psp_entitlement_message_u1 ON ONLY  pspadm.psp_entitlement_message USING BTREE (token );
create index psp_entitlement_msg_lcno_eofcd ON ONLY  pspadm.psp_entitlement_message USING BTREE (license_number ,entitlement_offering_code );
create index psp_entitlement_msg_msgts_er ON ONLY  pspadm.psp_entitlement_message USING BTREE (message_timestamp ,event_reason  );
create index psp_entitlement_msg_orno_lcno ON ONLY  pspadm.psp_entitlement_message USING BTREE (order_number ,license_number );
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2012 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2013 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2014 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2015 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2016 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2017 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2018 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2019 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2020 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2021 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2022 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2023 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2024 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2012 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2013 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2014 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2015 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2016 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2017 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2018 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2019 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2020 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2021 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2022 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2023 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2024 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2012 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2013 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2014 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2015 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2016 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2017 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2018 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2019 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2020 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2021 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2022 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2023 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2024 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2012 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2013 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2014 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2015 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2016 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2017 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2018 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2019 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2020 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2021 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2022 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2023 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2024 ;
--psp_paycheck_usage
create index psp_paycheckusage_fk1 ON ONLY  pspadm.psp_paycheck_usage USING BTREE (bill_fk );
create index psp_paycheckusage_fk2 ON ONLY  pspadm.psp_paycheck_usage USING BTREE (employee_usage_fk );
create index psp_paycheck_usage_fk1 ON ONLY  pspadm.psp_paycheck_usage USING BTREE (company_fk );
create index psp_paycheck_usage_nu1 ON ONLY  pspadm.psp_paycheck_usage USING BTREE (source_paycheck_id );
create index psp_paycheck_usage_u1 ON ONLY  pspadm.psp_paycheck_usage USING BTREE (employee_usage_fk ,source_paycheck_id );

alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2012 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2013 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2014 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2015 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2016 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2017 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2018 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2019 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2020 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2021 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2022 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2023 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2024 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2012 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2013 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2014 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2015 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2016 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2017 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2018 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2019 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2020 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2021 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2022 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2023 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2024 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2012 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2013 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2014 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2015 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2016 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2017 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2018 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2019 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2020 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2021 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2022 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2023 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2024 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2012 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2013 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2014 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2015 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2016 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2017 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2018 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2019 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2020 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2021 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2022 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2023 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2024 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2012 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2013 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2014 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2015 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2016 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2017 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2018 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2019 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2020 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2021 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2022 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2023 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2024 ;

--psp_entity_update
create index idx_entityupdate_crdate ON ONLY  pspadm.psp_entity_update USING BTREE (created_date );
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m112022 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m122022 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m012023 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m022023 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m032023 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m042023 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m052023 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m062023 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m072023 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m082023 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m092023 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m102023 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m112023 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m122023 ;

SELECT CURRENT_TIMESTAMP;