\timing
set search_path=pspadm;
SELECT CURRENT_TIMESTAMP;
select 'creating index on psp_entitlement_message' as status ;

create index psp_entitlement_message_u1_p0 on pspadm.psp_entitlement_message_p0  USING BTREE (token );
create index psp_entitlement_message_u1_p1 on pspadm.psp_entitlement_message_p1  USING BTREE (token );
create index psp_entitlement_message_u1_p2 on pspadm.psp_entitlement_message_p2  USING BTREE (token );
create index psp_entitlement_message_u1_p3 on pspadm.psp_entitlement_message_p3  USING BTREE (token );
create index psp_entitlement_message_u1_p4 on pspadm.psp_entitlement_message_p4  USING BTREE (token );
create index psp_entitlement_message_u1_p5 on pspadm.psp_entitlement_message_p5  USING BTREE (token );
create index psp_entitlement_message_u1_p6 on pspadm.psp_entitlement_message_p6  USING BTREE (token );
create index psp_entitlement_message_u1_p7 on pspadm.psp_entitlement_message_p7  USING BTREE (token );
create index psp_entitlement_msg_lcno_eofcd_p0 on pspadm.psp_entitlement_message_p0  USING BTREE (license_number ,entitlement_offering_code );
create index psp_entitlement_msg_lcno_eofcd_p1 on pspadm.psp_entitlement_message_p1  USING BTREE (license_number ,entitlement_offering_code );
create index psp_entitlement_msg_lcno_eofcd_p2 on pspadm.psp_entitlement_message_p2  USING BTREE (license_number ,entitlement_offering_code );
create index psp_entitlement_msg_lcno_eofcd_p3 on pspadm.psp_entitlement_message_p3  USING BTREE (license_number ,entitlement_offering_code );
create index psp_entitlement_msg_lcno_eofcd_p4 on pspadm.psp_entitlement_message_p4  USING BTREE (license_number ,entitlement_offering_code );
create index psp_entitlement_msg_lcno_eofcd_p5 on pspadm.psp_entitlement_message_p5  USING BTREE (license_number ,entitlement_offering_code );
create index psp_entitlement_msg_lcno_eofcd_p6 on pspadm.psp_entitlement_message_p6  USING BTREE (license_number ,entitlement_offering_code );
create index psp_entitlement_msg_lcno_eofcd_p7 on pspadm.psp_entitlement_message_p7  USING BTREE (license_number ,entitlement_offering_code );
create index psp_entitlement_msg_msgts_er_p0 on pspadm.psp_entitlement_message_p0  USING BTREE (message_timestamp ,event_reason );
create index psp_entitlement_msg_msgts_er_p1 on pspadm.psp_entitlement_message_p1  USING BTREE (message_timestamp ,event_reason );
create index psp_entitlement_msg_msgts_er_p2 on pspadm.psp_entitlement_message_p2  USING BTREE (message_timestamp ,event_reason );
create index psp_entitlement_msg_msgts_er_p3 on pspadm.psp_entitlement_message_p3  USING BTREE (message_timestamp ,event_reason );
create index psp_entitlement_msg_msgts_er_p4 on pspadm.psp_entitlement_message_p4  USING BTREE (message_timestamp ,event_reason );
create index psp_entitlement_msg_msgts_er_p5 on pspadm.psp_entitlement_message_p5  USING BTREE (message_timestamp ,event_reason );
create index psp_entitlement_msg_msgts_er_p6 on pspadm.psp_entitlement_message_p6  USING BTREE (message_timestamp ,event_reason );
create index psp_entitlement_msg_msgts_er_p7 on pspadm.psp_entitlement_message_p7  USING BTREE (message_timestamp ,event_reason );
create index psp_entitlement_msg_orno_lcno_p0 on pspadm.psp_entitlement_message_p0  USING BTREE (order_number ,license_number );
create index psp_entitlement_msg_orno_lcno_p1 on pspadm.psp_entitlement_message_p1  USING BTREE (order_number ,license_number );
create index psp_entitlement_msg_orno_lcno_p2 on pspadm.psp_entitlement_message_p2  USING BTREE (order_number ,license_number );
create index psp_entitlement_msg_orno_lcno_p3 on pspadm.psp_entitlement_message_p3  USING BTREE (order_number ,license_number );
create index psp_entitlement_msg_orno_lcno_p4 on pspadm.psp_entitlement_message_p4  USING BTREE (order_number ,license_number );
create index psp_entitlement_msg_orno_lcno_p5 on pspadm.psp_entitlement_message_p5  USING BTREE (order_number ,license_number );
create index psp_entitlement_msg_orno_lcno_p6 on pspadm.psp_entitlement_message_p6  USING BTREE (order_number ,license_number );
create index psp_entitlement_msg_orno_lcno_p7 on pspadm.psp_entitlement_message_p7  USING BTREE (order_number ,license_number );

--psp_entitlement_message
create index psp_entitlement_message_u1 ON ONLY  pspadm.psp_entitlement_message USING BTREE (token );
create index psp_entitlement_msg_lcno_eofcd ON ONLY  pspadm.psp_entitlement_message USING BTREE (license_number ,entitlement_offering_code );
create index psp_entitlement_msg_msgts_er ON ONLY  pspadm.psp_entitlement_message USING BTREE (message_timestamp ,event_reason  );
create index psp_entitlement_msg_orno_lcno ON ONLY  pspadm.psp_entitlement_message USING BTREE (order_number ,license_number );
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_p0 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_p1 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_p2 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_p3 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_p4 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_p5 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_p6 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_p7 ;

alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_p0 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_p1 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_p2 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_p3 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_p4 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_p5 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_p6 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_p7 ;

alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_p0 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_p1 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_p2 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_p3 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_p4 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_p5 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_p6 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_p7 ;

alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_p0 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_p1 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_p2 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_p3 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_p4 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_p5 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_p6 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_p7 ;



select 'creating index on psp_paycheck_usage' as status;
create index psp_paycheck_usage_fk1_2012 on pspadm.psp_paycheck_usage_2012  USING BTREE (company_fk );
create index psp_paycheck_usage_fk1_2013 on pspadm.psp_paycheck_usage_2013  USING BTREE (company_fk );
create index psp_paycheck_usage_fk1_2014 on pspadm.psp_paycheck_usage_2014  USING BTREE (company_fk );
create index psp_paycheck_usage_fk1_2015 on pspadm.psp_paycheck_usage_2015  USING BTREE (company_fk );
create index psp_paycheck_usage_fk1_2016 on pspadm.psp_paycheck_usage_2016  USING BTREE (company_fk );
create index psp_paycheck_usage_fk1_2017 on pspadm.psp_paycheck_usage_2017  USING BTREE (company_fk );
create index psp_paycheck_usage_fk1_2018 on pspadm.psp_paycheck_usage_2018  USING BTREE (company_fk );
create index psp_paycheck_usage_fk1_2019 on pspadm.psp_paycheck_usage_2019  USING BTREE (company_fk );
create index psp_paycheck_usage_fk1_2020 on pspadm.psp_paycheck_usage_2020  USING BTREE (company_fk );
create index psp_paycheck_usage_fk1_2021 on pspadm.psp_paycheck_usage_2021  USING BTREE (company_fk );
create index psp_paycheck_usage_fk1_2022 on pspadm.psp_paycheck_usage_2022  USING BTREE (company_fk );
create index psp_paycheck_usage_fk1_2023 on pspadm.psp_paycheck_usage_2023  USING BTREE (company_fk );
create index psp_paycheck_usage_fk1_2024 on pspadm.psp_paycheck_usage_2024  USING BTREE (company_fk );
create index psp_paycheck_usage_fk1_2025 on pspadm.psp_paycheck_usage_2025  USING BTREE (company_fk );
create index psp_paycheck_usage_fk1_2026 on pspadm.psp_paycheck_usage_2026  USING BTREE (company_fk );
create index psp_paycheck_usage_nu1_2012 on pspadm.psp_paycheck_usage_2012  USING BTREE (source_paycheck_id );
create index psp_paycheck_usage_nu1_2013 on pspadm.psp_paycheck_usage_2013  USING BTREE (source_paycheck_id );
create index psp_paycheck_usage_nu1_2014 on pspadm.psp_paycheck_usage_2014  USING BTREE (source_paycheck_id );
create index psp_paycheck_usage_nu1_2015 on pspadm.psp_paycheck_usage_2015  USING BTREE (source_paycheck_id );
create index psp_paycheck_usage_nu1_2016 on pspadm.psp_paycheck_usage_2016  USING BTREE (source_paycheck_id );
create index psp_paycheck_usage_nu1_2017 on pspadm.psp_paycheck_usage_2017  USING BTREE (source_paycheck_id );
create index psp_paycheck_usage_nu1_2018 on pspadm.psp_paycheck_usage_2018  USING BTREE (source_paycheck_id );
create index psp_paycheck_usage_nu1_2019 on pspadm.psp_paycheck_usage_2019  USING BTREE (source_paycheck_id );
create index psp_paycheck_usage_nu1_2020 on pspadm.psp_paycheck_usage_2020  USING BTREE (source_paycheck_id );
create index psp_paycheck_usage_nu1_2021 on pspadm.psp_paycheck_usage_2021  USING BTREE (source_paycheck_id );
create index psp_paycheck_usage_nu1_2022 on pspadm.psp_paycheck_usage_2022  USING BTREE (source_paycheck_id );
create index psp_paycheck_usage_nu1_2023 on pspadm.psp_paycheck_usage_2023  USING BTREE (source_paycheck_id );
create index psp_paycheck_usage_nu1_2024 on pspadm.psp_paycheck_usage_2024  USING BTREE (source_paycheck_id );
create index psp_paycheck_usage_nu1_2025 on pspadm.psp_paycheck_usage_2025  USING BTREE (source_paycheck_id );
create index psp_paycheck_usage_nu1_2026 on pspadm.psp_paycheck_usage_2026  USING BTREE (source_paycheck_id );
create index psp_paycheck_usage_u1_2012 on pspadm.psp_paycheck_usage_2012  USING BTREE (employee_usage_fk ,source_paycheck_id );
create index psp_paycheck_usage_u1_2013 on pspadm.psp_paycheck_usage_2013  USING BTREE (employee_usage_fk ,source_paycheck_id );
create index psp_paycheck_usage_u1_2014 on pspadm.psp_paycheck_usage_2014  USING BTREE (employee_usage_fk ,source_paycheck_id );
create index psp_paycheck_usage_u1_2015 on pspadm.psp_paycheck_usage_2015  USING BTREE (employee_usage_fk ,source_paycheck_id );
create index psp_paycheck_usage_u1_2016 on pspadm.psp_paycheck_usage_2016  USING BTREE (employee_usage_fk ,source_paycheck_id );
create index psp_paycheck_usage_u1_2017 on pspadm.psp_paycheck_usage_2017  USING BTREE (employee_usage_fk ,source_paycheck_id );
create index psp_paycheck_usage_u1_2018 on pspadm.psp_paycheck_usage_2018  USING BTREE (employee_usage_fk ,source_paycheck_id );
create index psp_paycheck_usage_u1_2019 on pspadm.psp_paycheck_usage_2019  USING BTREE (employee_usage_fk ,source_paycheck_id );
create index psp_paycheck_usage_u1_2020 on pspadm.psp_paycheck_usage_2020  USING BTREE (employee_usage_fk ,source_paycheck_id );
create index psp_paycheck_usage_u1_2021 on pspadm.psp_paycheck_usage_2021  USING BTREE (employee_usage_fk ,source_paycheck_id );
create index psp_paycheck_usage_u1_2022 on pspadm.psp_paycheck_usage_2022  USING BTREE (employee_usage_fk ,source_paycheck_id );
create index psp_paycheck_usage_u1_2023 on pspadm.psp_paycheck_usage_2023  USING BTREE (employee_usage_fk ,source_paycheck_id );
create index psp_paycheck_usage_u1_2024 on pspadm.psp_paycheck_usage_2024  USING BTREE (employee_usage_fk ,source_paycheck_id );
create index psp_paycheck_usage_u1_2025 on pspadm.psp_paycheck_usage_2023  USING BTREE (employee_usage_fk ,source_paycheck_id );
create index psp_paycheck_usage_u1_2026 on pspadm.psp_paycheck_usage_2024  USING BTREE (employee_usage_fk ,source_paycheck_id );
create index psp_paycheckusage_fk1_2012 on pspadm.psp_paycheck_usage_2012  USING BTREE (bill_fk );
create index psp_paycheckusage_fk1_2013 on pspadm.psp_paycheck_usage_2013  USING BTREE (bill_fk );
create index psp_paycheckusage_fk1_2014 on pspadm.psp_paycheck_usage_2014  USING BTREE (bill_fk );
create index psp_paycheckusage_fk1_2015 on pspadm.psp_paycheck_usage_2015  USING BTREE (bill_fk );
create index psp_paycheckusage_fk1_2016 on pspadm.psp_paycheck_usage_2016  USING BTREE (bill_fk );
create index psp_paycheckusage_fk1_2017 on pspadm.psp_paycheck_usage_2017  USING BTREE (bill_fk );
create index psp_paycheckusage_fk1_2018 on pspadm.psp_paycheck_usage_2018  USING BTREE (bill_fk );
create index psp_paycheckusage_fk1_2019 on pspadm.psp_paycheck_usage_2019  USING BTREE (bill_fk );
create index psp_paycheckusage_fk1_2020 on pspadm.psp_paycheck_usage_2020  USING BTREE (bill_fk );
create index psp_paycheckusage_fk1_2021 on pspadm.psp_paycheck_usage_2021  USING BTREE (bill_fk );
create index psp_paycheckusage_fk1_2022 on pspadm.psp_paycheck_usage_2022  USING BTREE (bill_fk );
create index psp_paycheckusage_fk1_2023 on pspadm.psp_paycheck_usage_2023  USING BTREE (bill_fk );
create index psp_paycheckusage_fk1_2024 on pspadm.psp_paycheck_usage_2024  USING BTREE (bill_fk );
create index psp_paycheckusage_fk1_2025 on pspadm.psp_paycheck_usage_2025  USING BTREE (bill_fk );
create index psp_paycheckusage_fk1_2026 on pspadm.psp_paycheck_usage_2026  USING BTREE (bill_fk );
create index psp_paycheckusage_fk2_2012 on pspadm.psp_paycheck_usage_2012  USING BTREE (employee_usage_fk );
create index psp_paycheckusage_fk2_2013 on pspadm.psp_paycheck_usage_2013  USING BTREE (employee_usage_fk );
create index psp_paycheckusage_fk2_2014 on pspadm.psp_paycheck_usage_2014  USING BTREE (employee_usage_fk );
create index psp_paycheckusage_fk2_2015 on pspadm.psp_paycheck_usage_2015  USING BTREE (employee_usage_fk );
create index psp_paycheckusage_fk2_2016 on pspadm.psp_paycheck_usage_2016  USING BTREE (employee_usage_fk );
create index psp_paycheckusage_fk2_2017 on pspadm.psp_paycheck_usage_2017  USING BTREE (employee_usage_fk );
create index psp_paycheckusage_fk2_2018 on pspadm.psp_paycheck_usage_2018  USING BTREE (employee_usage_fk );
create index psp_paycheckusage_fk2_2019 on pspadm.psp_paycheck_usage_2019  USING BTREE (employee_usage_fk );
create index psp_paycheckusage_fk2_2020 on pspadm.psp_paycheck_usage_2020  USING BTREE (employee_usage_fk );
create index psp_paycheckusage_fk2_2021 on pspadm.psp_paycheck_usage_2021  USING BTREE (employee_usage_fk );
create index psp_paycheckusage_fk2_2022 on pspadm.psp_paycheck_usage_2022  USING BTREE (employee_usage_fk );
create index psp_paycheckusage_fk2_2023 on pspadm.psp_paycheck_usage_2023  USING BTREE (employee_usage_fk );
create index psp_paycheckusage_fk2_2024 on pspadm.psp_paycheck_usage_2024  USING BTREE (employee_usage_fk );
create index psp_paycheckusage_fk2_2025 on pspadm.psp_paycheck_usage_2025  USING BTREE (employee_usage_fk );
create index psp_paycheckusage_fk2_2026 on pspadm.psp_paycheck_usage_2026  USING BTREE (employee_usage_fk );
select  'psp_paycheck_usage completed'  as status;


--psp_paycheck_usage
create index psp_paycheckusage_fk1 ON ONLY  pspadm.psp_paycheck_usage USING BTREE (bill_fk );
create index psp_paycheckusage_fk2 ON ONLY  pspadm.psp_paycheck_usage USING BTREE (employee_usage_fk );
create index psp_paycheck_usage_fk1 ON ONLY  pspadm.psp_paycheck_usage USING BTREE (company_fk );
create index psp_paycheck_usage_nu1 ON ONLY  pspadm.psp_paycheck_usage USING BTREE (source_paycheck_id );
create index psp_paycheck_usage_u1 ON ONLY  pspadm.psp_paycheck_usage USING BTREE (employee_usage_fk ,source_paycheck_id );

alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2012 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2013 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2014 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2015 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2016 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2017 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2018 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2019 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2020 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2021 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2022 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2023 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2024 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2025 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2026 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2012 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2013 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2014 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2015 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2016 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2017 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2018 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2019 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2020 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2021 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2022 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2023 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2024 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2025 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2026 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2012 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2013 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2014 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2015 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2016 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2017 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2018 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2019 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2020 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2021 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2022 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2023 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2024 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2025 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2026 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2012 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2013 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2014 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2015 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2016 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2017 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2018 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2019 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2020 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2021 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2022 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2023 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2024 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2025 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2026 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2012 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2013 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2014 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2015 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2016 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2017 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2018 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2019 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2020 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2021 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2022 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2023 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2024 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2025 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2026 ;


select 'creating index on psp_entity_update' as status ;
create index idx_entityupdate_crdate_m012024 on pspadm.psp_entity_update_m012024 USING BTREE (created_date );
create index idx_entityupdate_crdate_m022024 on pspadm.psp_entity_update_m022024 USING BTREE (created_date );
create index idx_entityupdate_crdate_m032024 on pspadm.psp_entity_update_m032024 USING BTREE (created_date );
create index idx_entityupdate_crdate_m042024 on pspadm.psp_entity_update_m042024 USING BTREE (created_date );
create index idx_entityupdate_crdate_m052024 on pspadm.psp_entity_update_m052024 USING BTREE (created_date );
create index idx_entityupdate_crdate_m062024 on pspadm.psp_entity_update_m062024 USING BTREE (created_date );
create index idx_entityupdate_crdate_m072024 on pspadm.psp_entity_update_m072024 USING BTREE (created_date );
create index idx_entityupdate_crdate_m082024 on pspadm.psp_entity_update_m082024 USING BTREE (created_date );
create index idx_entityupdate_crdate_m092024 on pspadm.psp_entity_update_m092024 USING BTREE (created_date );
create index idx_entityupdate_crdate_m102024 on pspadm.psp_entity_update_m102024 USING BTREE (created_date );
create index idx_entityupdate_crdate_m112024 on pspadm.psp_entity_update_m112024 USING BTREE (created_date );
create index idx_entityupdate_crdate_m122024 on pspadm.psp_entity_update_m122024 USING BTREE (created_date );

create index idx_entityupdate_crdate_m012025 on pspadm.psp_entity_update_m012025 USING BTREE (created_date );
create index idx_entityupdate_crdate_m022025 on pspadm.psp_entity_update_m022025 USING BTREE (created_date );
create index idx_entityupdate_crdate_m032025 on pspadm.psp_entity_update_m032025 USING BTREE (created_date );
create index idx_entityupdate_crdate_m042025 on pspadm.psp_entity_update_m042025 USING BTREE (created_date );
create index idx_entityupdate_crdate_m052025 on pspadm.psp_entity_update_m052025 USING BTREE (created_date );
create index idx_entityupdate_crdate_m062025 on pspadm.psp_entity_update_m062025 USING BTREE (created_date );
create index idx_entityupdate_crdate_m072025 on pspadm.psp_entity_update_m072025 USING BTREE (created_date );
create index idx_entityupdate_crdate_m082025 on pspadm.psp_entity_update_m082025 USING BTREE (created_date );
create index idx_entityupdate_crdate_m092025 on pspadm.psp_entity_update_m092025 USING BTREE (created_date );
create index idx_entityupdate_crdate_m102025 on pspadm.psp_entity_update_m102025 USING BTREE (created_date );
create index idx_entityupdate_crdate_m112025 on pspadm.psp_entity_update_m112025 USING BTREE (created_date );
create index idx_entityupdate_crdate_m122025 on pspadm.psp_entity_update_m122025 USING BTREE (created_date );

create index idx_entityupdate_crdate_m012026 on pspadm.psp_entity_update_m012026 USING BTREE (created_date );
create index idx_entityupdate_crdate_m022026 on pspadm.psp_entity_update_m022026 USING BTREE (created_date );
create index idx_entityupdate_crdate_m032026 on pspadm.psp_entity_update_m032026 USING BTREE (created_date );
create index idx_entityupdate_crdate_m042026 on pspadm.psp_entity_update_m042026 USING BTREE (created_date );
create index idx_entityupdate_crdate_m052026 on pspadm.psp_entity_update_m052026 USING BTREE (created_date );
create index idx_entityupdate_crdate_m062026 on pspadm.psp_entity_update_m062026 USING BTREE (created_date );
create index idx_entityupdate_crdate_m072026 on pspadm.psp_entity_update_m072026 USING BTREE (created_date );
create index idx_entityupdate_crdate_m082026 on pspadm.psp_entity_update_m082026 USING BTREE (created_date );
create index idx_entityupdate_crdate_m092026 on pspadm.psp_entity_update_m092026 USING BTREE (created_date );
create index idx_entityupdate_crdate_m102026 on pspadm.psp_entity_update_m102026 USING BTREE (created_date );
create index idx_entityupdate_crdate_m112026 on pspadm.psp_entity_update_m112026 USING BTREE (created_date );
create index idx_entityupdate_crdate_m122026 on pspadm.psp_entity_update_m122026 USING BTREE (created_date );



--psp_entity_update
create index idx_entityupdate_crdate ON ONLY  pspadm.psp_entity_update USING BTREE (created_date );
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m012024 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m022024 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m032024 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m042024 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m052024 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m062024 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m072024 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m082024 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m092024 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m102024 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m112024 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m122024 ;

alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m012025 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m022025 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m032025 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m042025 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m052025 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m062025 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m072025 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m082025 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m092025 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m102025 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m112025 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m122025 ;

alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m012026 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m022026 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m032026 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m042026 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m052026 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m062026 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m072026 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m082026 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m092026 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m102026 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m112026 ;
alter index idx_entityupdate_crdate attach partition  pspadm.idx_entityupdate_crdate_m122026 ;

SELECT CURRENT_TIMESTAMP;