DROP TABLE IF EXISTS TEMP_PSP_HOURS_WORKED CASCADE

;

--------------------------------------------------------
-- Create temp table                                  --
--------------------------------------------------------
CREATE TABLE TEMP_PSP_HOURS_WORKED (LIKE PSP_HOURS_WORKED_EXCEPTION INCLUDING ALL)
;

--------------------------------------------------------
-- Insert into temp table                             --
--------------------------------------------------------

INSERT INTO TEMP_PSP_HOURS_WORKED (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION) VALUES (
  '102001', 'REG', 'Hourly', '102', 0)
;
INSERT INTO TEMP_PSP_HOURS_WORKED (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION) VALUES (
  '102002', 'VAC', 'Hourly', '102', 0)
;
INSERT INTO TEMP_PSP_HOURS_WORKED (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION) VALUES (
  '102003', 'REG', 'Salary', '102', 0)
;
INSERT INTO TEMP_PSP_HOURS_WORKED (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION) VALUES (
  '102004', 'VAC', 'Salary', '102', 0)
;

INSERT INTO TEMP_PSP_HOURS_WORKED (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION) VALUES (
  '106001', 'REG', 'Hourly', '106', 0)
;
INSERT INTO TEMP_PSP_HOURS_WORKED (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION) VALUES (
  '106002', 'VAC', 'Hourly', '106', 0)
;
INSERT INTO TEMP_PSP_HOURS_WORKED (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION) VALUES (
  '106003', 'REG', 'Salary', '106', 0)
;
INSERT INTO TEMP_PSP_HOURS_WORKED (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION) VALUES (
  '106004', 'VAC', 'Salary', '106', 0)
;

INSERT INTO TEMP_PSP_HOURS_WORKED (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION) VALUES (
  '123001', 'REG', 'Hourly', '123', 0)
;
INSERT INTO TEMP_PSP_HOURS_WORKED (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION) VALUES (
'123002', 'VAC', 'Hourly', '123', 0)
;
INSERT INTO TEMP_PSP_HOURS_WORKED (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION) VALUES (
'123003', 'REG', 'Salary', '123', 0)
;
INSERT INTO TEMP_PSP_HOURS_WORKED (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION) VALUES (
'123004', 'VAC', 'Salary', '123', 0)
;
INSERT INTO TEMP_PSP_HOURS_WORKED (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION) VALUES (
'120001', 'REG', 'Hourly', '120', 0)
;
INSERT INTO TEMP_PSP_HOURS_WORKED (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION) VALUES (
'120002', 'REG', 'Salary', '120', 0)
;
INSERT INTO TEMP_PSP_HOURS_WORKED (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION) VALUES (
'131001', 'REG', 'Hourly', '131', 0)
;
INSERT INTO TEMP_PSP_HOURS_WORKED (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION) VALUES (
'131002', 'VAC', 'Hourly', '131', 0)
;
INSERT INTO TEMP_PSP_HOURS_WORKED (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION) VALUES (
'131003', 'VAC', 'Salary', '131', 0)
;
INSERT INTO TEMP_PSP_HOURS_WORKED (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION) VALUES (
'131004', 'REG', 'Salary', '131', 0)
;
INSERT INTO TEMP_PSP_HOURS_WORKED (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION) VALUES (
  '90001', 'REG', 'Hourly', '90', 0)
;
INSERT INTO TEMP_PSP_HOURS_WORKED (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION) VALUES (
  '90002', 'VAC', 'Hourly', '90', 0)
;
INSERT INTO TEMP_PSP_HOURS_WORKED (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION) VALUES (
  '90003', 'VAC', 'Salary', '90', 0)
;
INSERT INTO TEMP_PSP_HOURS_WORKED (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION) VALUES (
  '90004', 'REG', 'Salary', '90', 0)
;
INSERT INTO TEMP_PSP_HOURS_WORKED (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION) VALUES (
  '134001', 'REG', 'Hourly', '134', 0)
;
INSERT INTO TEMP_PSP_HOURS_WORKED (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION) VALUES (
  '134002', 'VAC', 'Hourly', '134', 0)
;
INSERT INTO TEMP_PSP_HOURS_WORKED (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION) VALUES (
  '134003', 'VAC', 'Salary', '134', 0)
;
INSERT INTO TEMP_PSP_HOURS_WORKED (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION) VALUES (
  '134004', 'REG', 'Salary', '134', 0)
;

INSERT INTO TEMP_PSP_HOURS_WORKED (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION) VALUES (
  '134005', 'REG', 'Hourly', '130', 0)
;
INSERT INTO TEMP_PSP_HOURS_WORKED (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION) VALUES (
  '134006', 'REG', 'Salary', '130', 0)
;

INSERT INTO TEMP_PSP_HOURS_WORKED (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION) VALUES (
 '206001', 'REG', 'Salary', '207', 0)
;
INSERT INTO TEMP_PSP_HOURS_WORKED (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION) VALUES (
 '206002', 'VAC', 'Salary', '207', 0)
;
INSERT INTO TEMP_PSP_HOURS_WORKED (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION) VALUES (
 '206003', 'REG', 'Hourly', '207', 0)
;
INSERT INTO TEMP_PSP_HOURS_WORKED (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION) VALUES (
 '206004', 'VAC', 'Hourly', '207', 0)
;

INSERT INTO TEMP_PSP_HOURS_WORKED (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION) VALUES (
 '206887', 'VAC', 'Hourly', '16', 0)
;
INSERT INTO TEMP_PSP_HOURS_WORKED (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION) VALUES (
 '206888', 'REG', 'Hourly', '16', 0)
;
INSERT INTO TEMP_PSP_HOURS_WORKED (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION) VALUES (
 '206889', 'VAC', 'Salary', '16', 0)
;
INSERT INTO TEMP_PSP_HOURS_WORKED (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION) VALUES (
 '206890', 'REG', 'Salary', '16', 0)
;

--------------------------------------------------------
-- Sychronize temp table and real table by            --
-- inserting, deleting, and updating as necessary     --
--------------------------------------------------------

INSERT INTO PSP_HOURS_WORKED_EXCEPTION
   (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION)
SELECT
    HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK, VERSION
FROM
   TEMP_PSP_HOURS_WORKED tt
WHERE
   tt.HOURS_WORKED_EXCEPTION_ID NOT IN (SELECT HOURS_WORKED_EXCEPTION_ID FROM PSP_HOURS_WORKED_EXCEPTION)

;

UPDATE PSP_HOURS_WORKED_EXCEPTION rt
SET (HOURS_WORKED_EXCEPTION_ID, PAY_TYPE, PAYROLL_ITEM_CD, LAW_FK) =
(SELECT  tt.HOURS_WORKED_EXCEPTION_ID, tt.PAY_TYPE, rt.PAYROLL_ITEM_CD, tt.LAW_FK
 FROM TEMP_PSP_HOURS_WORKED tt WHERE tt.HOURS_WORKED_EXCEPTION_ID = rt.HOURS_WORKED_EXCEPTION_ID)
 WHERE rt.HOURS_WORKED_EXCEPTION_ID IN (SELECT HOURS_WORKED_EXCEPTION_ID FROM TEMP_PSP_HOURS_WORKED)
;



--------------------------------------------------------
-- Drop temp table                                  --
--------------------------------------------------------
DROP TABLE TEMP_PSP_HOURS_WORKED

;
COMMIT