DROP TABLE IF EXISTS TEMP_PSP_ACH_TRANSACTION_CODE CASCADE;

--------------------------------------------------------
-- Create temp table                                  --
--------------------------------------------------------
CREATE TABLE TEMP_PSP_ACH_TRANSACTION_CODE (LIKE PSP_ACH_TRANSACTION_CODE INCLUDING ALL) ;
--------------------------------------------------------
-- Insert into temp table                             --
--------------------------------------------------------


INSERT INTO TEMP_PSP_ACH_TRANSACTION_CODE ( TRANSACTION_CODE, DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION, REALM_ID)  VALUES (
'21', 'Automated Return or Notification of Change for orginal transaction code 22, 23, or 24', 'Checking', 'Credit', 1, 0, -1)
;
INSERT INTO TEMP_PSP_ACH_TRANSACTION_CODE ( TRANSACTION_CODE, DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION, REALM_ID)  VALUES (
'22', 'Automated Deposit', 'Checking', 'Credit', 0, 0, -1)
;
INSERT INTO TEMP_PSP_ACH_TRANSACTION_CODE ( TRANSACTION_CODE, DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION, REALM_ID)  VALUES (
'26', 'Automated Return or Notification of Change for orginal transaction code 27, 28, or 29', 'Checking', 'Debit', 1, 0, -1)
;
INSERT INTO TEMP_PSP_ACH_TRANSACTION_CODE ( TRANSACTION_CODE, DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION, REALM_ID)  VALUES (
'27', 'Automated Payment', 'Checking', 'Debit', 0, 0, -1)
;
INSERT INTO TEMP_PSP_ACH_TRANSACTION_CODE ( TRANSACTION_CODE, DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION, REALM_ID)  VALUES (
'31', 'Automated Return or Notification of Change for orginal transaction code 32, 33, or 34', 'Savings', 'Credit', 1, 0, -1)
;
INSERT INTO TEMP_PSP_ACH_TRANSACTION_CODE ( TRANSACTION_CODE, DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION, REALM_ID)  VALUES (
'32', 'Automated Deposit', 'Savings', 'Credit', 0, 0, -1)
;
INSERT INTO TEMP_PSP_ACH_TRANSACTION_CODE ( TRANSACTION_CODE, DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION, REALM_ID)  VALUES (
'36', 'Automated Return or Notification of Change for orginal transaction code 37, 38, or 39', 'Savings', 'Debit', 1, 0, -1)
;
INSERT INTO TEMP_PSP_ACH_TRANSACTION_CODE ( TRANSACTION_CODE, DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION, REALM_ID)  VALUES (
'37', 'Automated Payment', 'Savings', 'Debit', 0, 0, -1)
;
INSERT INTO TEMP_PSP_ACH_TRANSACTION_CODE ( TRANSACTION_CODE, DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION, REALM_ID)  VALUES (
'41', 'Automated Return or Notification of Change for orginal transaction code 42, 43, or 44', 'Ledger', 'Credit', 1, 0, -1)
;
INSERT INTO TEMP_PSP_ACH_TRANSACTION_CODE ( TRANSACTION_CODE, DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION, REALM_ID)  VALUES (
'42', 'Automated Deposit', 'Ledger', 'Credit', 0, 0, -1)
;
INSERT INTO TEMP_PSP_ACH_TRANSACTION_CODE ( TRANSACTION_CODE, DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION, REALM_ID)  VALUES (
'46', 'Automated Return or Notification of Change for orginal transaction code 47, 48, or 49', 'Ledger', 'Debit', 1, 0, -1)
;
INSERT INTO TEMP_PSP_ACH_TRANSACTION_CODE ( TRANSACTION_CODE, DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION, REALM_ID)  VALUES (
'47', 'Automated Payment', 'Ledger', 'Debit', 0, 0, -1)
;
INSERT INTO TEMP_PSP_ACH_TRANSACTION_CODE ( TRANSACTION_CODE, DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION, REALM_ID)  VALUES (
'51', 'Automated Return or Notification of Change for orginal transaction code 52, 53, or 54', 'Loan', 'Credit', 1, 0, -1)
;
INSERT INTO TEMP_PSP_ACH_TRANSACTION_CODE ( TRANSACTION_CODE, DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION, REALM_ID)  VALUES (
'52', 'Automated Deposit', 'Loan', 'Credit', 0, 0, -1)
;
INSERT INTO TEMP_PSP_ACH_TRANSACTION_CODE ( TRANSACTION_CODE, DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION, REALM_ID)  VALUES (
'55', 'Automated Payment (Reversals Only)', 'Loan', 'Debit', 0, 0, -1)
;
INSERT INTO TEMP_PSP_ACH_TRANSACTION_CODE ( TRANSACTION_CODE, DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION, REALM_ID)  VALUES (
'56', 'Automated Return or Notification of Change for orginal transaction code 55', 'Loan', 'Debit', 1, 0, -1)
;
--------------------------------------------------------
-- Sychronize temp table and real table by            --
-- inserting, deleting, and updating as necessary     --
--------------------------------------------------------

INSERT INTO PSP_ACH_TRANSACTION_CODE
   (TRANSACTION_CODE, DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION, REALM_ID)
SELECT
    TRANSACTION_CODE, DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION, REALM_ID
FROM
   TEMP_PSP_ACH_TRANSACTION_CODE tt
WHERE
   tt.TRANSACTION_CODE NOT IN (SELECT TRANSACTION_CODE FROM PSP_ACH_TRANSACTION_CODE)

;
DELETE FROM PSP_ACH_TRANSACTION_CODE
WHERE TRANSACTION_CODE NOT IN (SELECT TRANSACTION_CODE FROM TEMP_PSP_ACH_TRANSACTION_CODE)

;
UPDATE PSP_ACH_TRANSACTION_CODE rt
SET ( DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION) =
(SELECT   tt.DESCRIPTION, tt.ACH_ACCOUNT_TYPE_CD, tt.CREDIT_DEBIT_INDICATOR, tt.IS_RETURN_CODE, tt.VERSION
 FROM TEMP_PSP_ACH_TRANSACTION_CODE tt WHERE tt.TRANSACTION_CODE = rt.TRANSACTION_CODE)

;

--------------------------------------------------------
-- Drop temp table                                  --
--------------------------------------------------------
DROP TABLE TEMP_PSP_ACH_TRANSACTION_CODE

;
COMMIT