DROP TABLE IF EXISTS TMP_PAYMENT_TEMPLATE_AGENCY_ID CASCADE

;

--------------------------------------------------------
-- Create temp table                                  --
--------------------------------------------------------

CREATE TABLE TMP_PAYMENT_TEMPLATE_AGENCY_ID (LIKE PSP_PAYMENT_TEMPLATE_AGENCY_ID INCLUDING ALL)

;

--------------------------------------------------------
-- Insert into temp table                             --
--------------------------------------------------------

INSERT INTO TMP_PAYMENT_TEMPLATE_AGENCY_ID (PAYMENT_TEMPLATE_AGENCY_ID_SEQ, VERSION, CREATOR_ID, CREATED_DATE, MODIFIER_ID, MODIFIED_DATE, REALM_ID, NAME, PAYMENT_TEMPLATE_FK) VALUES (
'd79226a2-0000-0000-0000-a00000000001', 0, 'System', CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, -1, 'BEN Number', 'IA-44105-PAYMENT')
;
INSERT INTO TMP_PAYMENT_TEMPLATE_AGENCY_ID (PAYMENT_TEMPLATE_AGENCY_ID_SEQ, VERSION, CREATOR_ID, CREATED_DATE, MODIFIER_ID, MODIFIED_DATE, REALM_ID, NAME, PAYMENT_TEMPLATE_FK) VALUES (
'd79226a2-0000-0000-0000-a00000000002', 0, 'System', CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, -1, 'Client Bank Acct', 'IA-600103-PAYMENT')
;
INSERT INTO TMP_PAYMENT_TEMPLATE_AGENCY_ID (PAYMENT_TEMPLATE_AGENCY_ID_SEQ, VERSION, CREATOR_ID, CREATED_DATE, MODIFIER_ID, MODIFIED_DATE, REALM_ID, NAME, PAYMENT_TEMPLATE_FK) VALUES (
'd79226a2-0000-0000-0000-a00000000003', 0, 'System', CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, -1, 'State Access Code', 'NY-1MN-PAYMENT')
;
INSERT INTO TMP_PAYMENT_TEMPLATE_AGENCY_ID (PAYMENT_TEMPLATE_AGENCY_ID_SEQ, VERSION, CREATOR_ID, CREATED_DATE, MODIFIER_ID, MODIFIED_DATE, REALM_ID, NAME, PAYMENT_TEMPLATE_FK) VALUES (
'd79226a2-0000-0000-0000-b00000000003', 0, 'System', CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, -1, 'State Access Code', 'NY-MTA305-PAYMENT')
;
INSERT INTO TMP_PAYMENT_TEMPLATE_AGENCY_ID (PAYMENT_TEMPLATE_AGENCY_ID_SEQ, VERSION, CREATOR_ID, CREATED_DATE, MODIFIER_ID, MODIFIED_DATE, REALM_ID, NAME, PAYMENT_TEMPLATE_FK) VALUES (
'd79226a2-0000-0000-0000-a00000000004', 0, 'System', CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, -1, 'State EFT Number', 'CO-DR1094-PAYMENT')
;

INSERT INTO TMP_PAYMENT_TEMPLATE_AGENCY_ID (PAYMENT_TEMPLATE_AGENCY_ID_SEQ, VERSION, CREATOR_ID, CREATED_DATE, MODIFIER_ID, MODIFIED_DATE, REALM_ID, NAME, PAYMENT_TEMPLATE_FK) VALUES (
'529e951d-e2be-4189-94a3-3810893fec0c', 0, 'System', CURRENT_TIMESTAMP, 'System', CURRENT_TIMESTAMP, -1, 'WA UBI', 'WA-F5208-PAYMENT')
;
--------------------------------------------------------
-- Synchronize temp table and real table by            --
-- inserting, deleting, and updating as necessary     --
--------------------------------------------------------

INSERT INTO PSP_PAYMENT_TEMPLATE_AGENCY_ID
   (PAYMENT_TEMPLATE_AGENCY_ID_SEQ, VERSION, CREATOR_ID, CREATED_DATE, MODIFIER_ID, MODIFIED_DATE, REALM_ID, NAME, PAYMENT_TEMPLATE_FK)
SELECT
    PAYMENT_TEMPLATE_AGENCY_ID_SEQ, VERSION, CREATOR_ID, CREATED_DATE, MODIFIER_ID, MODIFIED_DATE, REALM_ID, NAME, PAYMENT_TEMPLATE_FK
FROM
   TMP_PAYMENT_TEMPLATE_AGENCY_ID tt
WHERE
   tt.PAYMENT_TEMPLATE_AGENCY_ID_SEQ NOT IN (SELECT PAYMENT_TEMPLATE_AGENCY_ID_SEQ FROM PSP_PAYMENT_TEMPLATE_AGENCY_ID)
;

UPDATE PSP_PAYMENT_TEMPLATE_AGENCY_ID rt
SET (VERSION, CREATOR_ID, CREATED_DATE, MODIFIER_ID, MODIFIED_DATE, REALM_ID, NAME, PAYMENT_TEMPLATE_FK) =
(SELECT  tt.VERSION, tt.CREATOR_ID, tt.CREATED_DATE, tt.MODIFIER_ID, tt.MODIFIED_DATE, tt.REALM_ID, tt.NAME, tt.PAYMENT_TEMPLATE_FK
 FROM TMP_PAYMENT_TEMPLATE_AGENCY_ID tt WHERE tt.PAYMENT_TEMPLATE_AGENCY_ID_SEQ = rt.PAYMENT_TEMPLATE_AGENCY_ID_SEQ)
 WHERE rt.PAYMENT_TEMPLATE_AGENCY_ID_SEQ IN (SELECT PAYMENT_TEMPLATE_AGENCY_ID_SEQ FROM TMP_PAYMENT_TEMPLATE_AGENCY_ID)
;

DELETE FROM PSP_PAYMENT_TEMPLATE_AGENCY_ID
WHERE PAYMENT_TEMPLATE_AGENCY_ID_SEQ NOT IN (SELECT PAYMENT_TEMPLATE_AGENCY_ID_SEQ FROM TMP_PAYMENT_TEMPLATE_AGENCY_ID)
;

--------------------------------------------------------
-- Drop temp table                                  --
--------------------------------------------------------
DROP TABLE TMP_PAYMENT_TEMPLATE_AGENCY_ID

;
COMMIT;
