set echo on feedback on
spool CREATE_LOCAL_PK_ON_PARTITIONED_TABLES_2
ALTER TABLE PSPADM.PSP_FINANCIAL_TRANSACTION ADD CONSTRAINT PSP_FINANCIAL_TRANSACTION_PK PRIMARY KEY (COMPANY_FK,FINANCIAL_TRANSACTION_SEQ) USING INDEX LOCAL TABLESPACE PSP_IDX01 ENABLE;
ALTER TABLE PSPADM.PSP_PAYCHECK ADD CONSTRAINT PSP_PAYCHECK_PK PRIMARY KEY (COMPANY_FK,PAYCHECK_SEQ) USING INDEX LOCAL TABLESPACE PSP_IDX02 ENABLE;
ALTER TABLE PSPADM.PSP_PAYCHECK_SPLIT ADD CONSTRAINT PSP_PAYCHECK_SPLIT_PK PRIMARY KEY (COMPANY_FK,PAYCHECK_SPLIT_SEQ) USING INDEX LOCAL TABLESPACE PSP_IDX03 ENABLE;
ALTER TABLE PSPADM.PSP_PROPERTY_AUDIT ADD CONSTRAINT PSP_PROPERTY_AUDIT_PK PRIMARY KEY (COMPANY_FK,PROPERTY_AUDIT_SEQ) USING INDEX LOCAL TABLESPACE PSP_IDX04 ENABLE;
ALTER TABLE PSPADM.PSP_QBDT_PAYCHECK_INFO ADD CONSTRAINT PSP_QBDT_PAYCHECK_INFO_PK PRIMARY KEY (COMPANY_FK,QBDT_PAYCHECK_INFO_SEQ) USING INDEX LOCAL TABLESPACE PSP_IDX01 ENABLE;

spool off
