set echo on feedback on timing on
spool CREATE_FAILED_INDEXES
CREATE INDEX PSPADM.PSP_PSTUB_PAY_ITEM_FK1 ON PSPADM.PSP_PSTUB_PAY_ITEM (COMPANY_FK,PAYSTUB_FK) local online parallel (degree 4) TABLESPACE PSP_IDX01;

CREATE INDEX PSPADM.PSP_AGENCY_AGENCYIDENC_I1 ON PSPADM.PSP_AGENCY (AGENCY_ID_ENC) parallel (degree 4) TABLESPACE PSP_IDX02;
CREATE INDEX PSPADM.PSP_BANK_ACCOUNT_ENC_I1 ON PSPADM.PSP_BANK_ACCOUNT (ACCOUNT_NUMBER_ENC) parallel (degree 4) TABLESPACE PSP_IDX01;
CREATE INDEX PSPADM.PSP_COMPANY_FEDTAXIDENC_I1 ON PSPADM.PSP_COMPANY (FED_TAX_ID_ENC) parallel (degree 4) TABLESPACE PSP_IDX02;

CREATE INDEX PSPADM.PSP_EFTPS_PAYMENT_DETAIL_I3 ON PSPADM.PSP_EFTPS_PAYMENT_DETAIL (EFT_TRANSACTION_ID)  parallel (degree 4) TABLESPACE PSP_IDX02;
CREATE INDEX PSPADM.PSP_EFTPS_PAYMENT_DETAIL_I4 ON PSPADM.PSP_EFTPS_PAYMENT_DETAIL (TRANSACTION_ID,AGENCY_PAYMENT_ID)  parallel (degree 4) TABLESPACE PSP_IDX02;
CREATE INDEX PSPADM.PSP_EMPLOYEE_TAXIDENC_I1 ON PSPADM.PSP_EMPLOYEE (TAX_ID_ENC)  parallel (degree 4) TABLESPACE PSP_IDX01;
CREATE INDEX PSPADM.PSP_ENMT_FEDTAXIDENC_I1 ON PSPADM.PSP_ENTITLEMENT_UNIT (FED_TAX_ID_ENC)  parallel (degree 4) TABLESPACE PSP_IDX01;

CREATE INDEX PSPADM.PSP_FRAUD_ACCOUNT_ENC_I1 ON PSPADM.PSP_FRAUD_BANK_ACCOUNT (ACCOUNT_NUMBER_ENC)  parallel (degree 4) TABLESPACE PSP_IDX01;

spool off
