set echo on feedback on
spool DROP_GLOBAL_PK
ALTER TABLE PSPADM.PSP_COMPANY_EVENT DROP PRIMARY KEY;
ALTER TABLE PSPADM.PSP_COMPANY_EVENT_DETAIL DROP PRIMARY KEY;
ALTER TABLE PSPADM.PSP_COMPANY_EVENT_EMAIL_PARAM DROP PRIMARY KEY;
ALTER TABLE PSPADM.PSP_COMPENSATION DROP PRIMARY KEY;
ALTER TABLE PSPADM.PSP_DEDUCTION DROP PRIMARY KEY;
ALTER TABLE PSPADM.PSP_DISBURSE_ADVICE_TAX_LIAB DROP PRIMARY KEY;
ALTER TABLE PSPADM.PSP_ENTRY_DETAIL_RECORD DROP PRIMARY KEY;
ALTER TABLE PSPADM.PSP_FINANCIAL_TRANSACTION DROP PRIMARY KEY;
ALTER TABLE PSPADM.PSP_FINANCIAL_TRANS_STATE DROP PRIMARY KEY;
ALTER TABLE PSPADM.PSP_LEDGER_BALANCE DROP PRIMARY KEY;
ALTER TABLE PSPADM.PSP_MONEY_MOVEMENT_TRANSACTION DROP PRIMARY KEY;
ALTER TABLE PSPADM.PSP_PAYCHECK DROP PRIMARY KEY;
ALTER TABLE PSPADM.PSP_PAYCHECK_SPLIT DROP PRIMARY KEY;
ALTER TABLE PSPADM.PSP_PAYSTUB DROP PRIMARY KEY;
ALTER TABLE PSPADM.PSP_PROPERTY_AUDIT DROP PRIMARY KEY;
ALTER TABLE PSPADM.PSP_PSTUB_EMPLOYEE_INFO DROP PRIMARY KEY;
ALTER TABLE PSPADM.PSP_PSTUB_PAID_TIMEOFF_ITEM DROP PRIMARY KEY;
ALTER TABLE PSPADM.PSP_PSTUB_PAY_ITEM DROP PRIMARY KEY;
ALTER TABLE PSPADM.PSP_QBDT_PAYCHECK_INFO DROP PRIMARY KEY;
ALTER TABLE PSPADM.PSP_QBDT_PAYLINE_INFO DROP PRIMARY KEY;
ALTER TABLE PSPADM.PSP_QBDT_TRANSACTION_INFO DROP PRIMARY KEY;
ALTER TABLE PSPADM.PSP_TAX DROP PRIMARY KEY;

spool off
