set echo on feedback on
spool M
ALTER TABLE PSPADM.PSP_PSTUB_EMPLOYEE_INFO ADD CONSTRAINT PSP_PSTUB_EMPLOYEE_INFO_PK PRIMARY KEY (COMPANY_FK,PSTUB_EMPLOYEE_INFO_SEQ) USING INDEX LOCAL TABLESPACE PSP_IDX02 ENABLE;
spool off

