CREATE OR REPLACE FUNCTION FN_PSP_COMPANY_BANK_ACCOUNT_AT()
RETURNS TRIGGER
AS $$
DECLARE
  v_company_fk VARCHAR(255);
  v_creator_id VARCHAR(30);
  v_modifier_id VARCHAR(30);
  v_psp_utc_systimestamp TIMESTAMP;
BEGIN
SELECT NEW.CREATOR_ID INTO v_creator_id FROM DUAL;
SELECT NEW.MODIFIER_ID INTO v_modifier_id FROM DUAL;

  IF (TG_OP='UPDATE') THEN
     IF (((NEW.STATUS_CD <> OLD.STATUS_CD) AND NEW.STATUS_CD IS NOT NULL AND OLD.STATUS_CD IS NOT NULL) OR
         (NEW.STATUS_CD IS NULL AND OLD.STATUS_CD IS NOT NULL) OR
         (NEW.STATUS_CD IS NOT NULL AND OLD.STATUS_CD IS NULL) ) THEN
         BEGIN
            SELECT NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            SELECT CURRENT_TIMESTAMP AT TIME ZONE 'UTC' +(SELECT INTERVAL '1 second'*(SELECT (SYSTEM_PARAMETER_VALUE)::DOUBLE PRECISION/1000 FROM PSP_SYSTEM_PARAMETER WHERE SYSTEM_PARAMETER_CD = 'PSP_DATE_OFFSET')) INTO v_psp_utc_systimestamp FROM DUAL;
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (gen_random_uuid(), 0, v_psp_utc_systimestamp, v_psp_utc_systimestamp, 'CompanyBankAccount', 'StatusCd', (OLD.STATUS_CD )::VARCHAR, (NEW.STATUS_CD )::VARCHAR, NEW.COMPANY_BANK_ACCOUNT_SEQ, v_modifier_id, v_psp_utc_systimestamp, v_company_fk);
         END IF;
     END IF;

     IF (((NEW.STATUS_EFFECTIVE_DATE <> OLD.STATUS_EFFECTIVE_DATE) AND NEW.STATUS_EFFECTIVE_DATE IS NOT NULL AND OLD.STATUS_EFFECTIVE_DATE IS NOT NULL) OR
         (NEW.STATUS_EFFECTIVE_DATE IS NULL AND OLD.STATUS_EFFECTIVE_DATE IS NOT NULL) OR
         (NEW.STATUS_EFFECTIVE_DATE IS NOT NULL AND OLD.STATUS_EFFECTIVE_DATE IS NULL) ) THEN
         BEGIN
            SELECT NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            SELECT CURRENT_TIMESTAMP AT TIME ZONE 'UTC' +(SELECT INTERVAL '1 second'*(SELECT (SYSTEM_PARAMETER_VALUE)::DOUBLE PRECISION/1000 FROM PSP_SYSTEM_PARAMETER WHERE SYSTEM_PARAMETER_CD = 'PSP_DATE_OFFSET')) INTO v_psp_utc_systimestamp FROM DUAL;
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (gen_random_uuid(), 0, v_psp_utc_systimestamp, v_psp_utc_systimestamp, 'CompanyBankAccount', 'StatusEffectiveDate', (to_char(OLD.STATUS_EFFECTIVE_DATE, 'dd-MON-yy HH.MI.SS.US AM') )::VARCHAR, (to_char(NEW.STATUS_EFFECTIVE_DATE, 'dd-MON-yy HH.MI.SS.US AM') )::VARCHAR, NEW.COMPANY_BANK_ACCOUNT_SEQ, v_modifier_id, v_psp_utc_systimestamp, v_company_fk);
         END IF;
     END IF;

     IF (((NEW.SOURCE_BANK_ACCOUNT_NAME <> OLD.SOURCE_BANK_ACCOUNT_NAME) AND NEW.SOURCE_BANK_ACCOUNT_NAME IS NOT NULL AND OLD.SOURCE_BANK_ACCOUNT_NAME IS NOT NULL) OR
         (NEW.SOURCE_BANK_ACCOUNT_NAME IS NULL AND OLD.SOURCE_BANK_ACCOUNT_NAME IS NOT NULL) OR
         (NEW.SOURCE_BANK_ACCOUNT_NAME IS NOT NULL AND OLD.SOURCE_BANK_ACCOUNT_NAME IS NULL) ) THEN
         BEGIN
            SELECT NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            SELECT CURRENT_TIMESTAMP AT TIME ZONE 'UTC' +(SELECT INTERVAL '1 second'*(SELECT (SYSTEM_PARAMETER_VALUE)::DOUBLE PRECISION/1000 FROM PSP_SYSTEM_PARAMETER WHERE SYSTEM_PARAMETER_CD = 'PSP_DATE_OFFSET')) INTO v_psp_utc_systimestamp FROM DUAL;
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (gen_random_uuid(), 0, v_psp_utc_systimestamp, v_psp_utc_systimestamp, 'CompanyBankAccount', 'SourceBankAccountName', (OLD.SOURCE_BANK_ACCOUNT_NAME )::VARCHAR, (NEW.SOURCE_BANK_ACCOUNT_NAME )::VARCHAR, NEW.COMPANY_BANK_ACCOUNT_SEQ, v_modifier_id, v_psp_utc_systimestamp, v_company_fk);
         END IF;
     END IF;

  END IF;
  RETURN NEW;
END;
$$
LANGUAGE PLPGSQL;
