CREATE OR REPLACE FUNCTION FN_PSP_ENTITY_CHANGE_AT()
RETURNS TRIGGER
AS $$
DECLARE
  v_company_fk VARCHAR(255);
  v_creator_id VARCHAR(30);
  v_modifier_id VARCHAR(30);
  v_psp_utc_systimestamp TIMESTAMP;
BEGIN
SELECT NEW.CREATOR_ID INTO v_creator_id FROM DUAL;
SELECT NEW.MODIFIER_ID INTO v_modifier_id FROM DUAL;

  IF (TG_OP='UPDATE') THEN
     IF (((NEW.AGENT_ID <> OLD.AGENT_ID) AND NEW.AGENT_ID IS NOT NULL AND OLD.AGENT_ID IS NOT NULL) OR
         (NEW.AGENT_ID IS NULL AND OLD.AGENT_ID IS NOT NULL) OR
         (NEW.AGENT_ID IS NOT NULL AND OLD.AGENT_ID IS NULL) ) THEN
         BEGIN
            SELECT NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            SELECT CURRENT_TIMESTAMP AT TIME ZONE 'UTC' +(SELECT INTERVAL '1 second'*(SELECT (SYSTEM_PARAMETER_VALUE)::DOUBLE PRECISION/1000 FROM PSP_SYSTEM_PARAMETER WHERE SYSTEM_PARAMETER_CD = 'PSP_DATE_OFFSET')) INTO v_psp_utc_systimestamp FROM DUAL;
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (gen_random_uuid(), 0, v_psp_utc_systimestamp, v_psp_utc_systimestamp, 'EntityChange', 'AgentId', (OLD.AGENT_ID )::VARCHAR, (NEW.AGENT_ID )::VARCHAR, NEW.ENTITY_CHANGE_SEQ, v_modifier_id, v_psp_utc_systimestamp, v_company_fk);
         END IF;
     END IF;

     IF (((NEW.EFFECTIVE_DATE <> OLD.EFFECTIVE_DATE) AND NEW.EFFECTIVE_DATE IS NOT NULL AND OLD.EFFECTIVE_DATE IS NOT NULL) OR
         (NEW.EFFECTIVE_DATE IS NULL AND OLD.EFFECTIVE_DATE IS NOT NULL) OR
         (NEW.EFFECTIVE_DATE IS NOT NULL AND OLD.EFFECTIVE_DATE IS NULL) ) THEN
         BEGIN
            SELECT NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            SELECT CURRENT_TIMESTAMP AT TIME ZONE 'UTC' +(SELECT INTERVAL '1 second'*(SELECT (SYSTEM_PARAMETER_VALUE)::DOUBLE PRECISION/1000 FROM PSP_SYSTEM_PARAMETER WHERE SYSTEM_PARAMETER_CD = 'PSP_DATE_OFFSET')) INTO v_psp_utc_systimestamp FROM DUAL;
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (gen_random_uuid(), 0, v_psp_utc_systimestamp, v_psp_utc_systimestamp, 'EntityChange', 'EffectiveDate', (to_char(OLD.EFFECTIVE_DATE, 'dd-MON-yy HH.MI.SS.US AM') )::VARCHAR, (to_char(NEW.EFFECTIVE_DATE, 'dd-MON-yy HH.MI.SS.US AM') )::VARCHAR, NEW.ENTITY_CHANGE_SEQ, v_modifier_id, v_psp_utc_systimestamp, v_company_fk);
         END IF;
     END IF;

     IF (((NEW.NEW_EIN_ENC <> OLD.NEW_EIN_ENC) AND NEW.NEW_EIN_ENC IS NOT NULL AND OLD.NEW_EIN_ENC IS NOT NULL) OR
         (NEW.NEW_EIN_ENC IS NULL AND OLD.NEW_EIN_ENC IS NOT NULL) OR
         (NEW.NEW_EIN_ENC IS NOT NULL AND OLD.NEW_EIN_ENC IS NULL) ) THEN
         BEGIN
            SELECT NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            SELECT CURRENT_TIMESTAMP AT TIME ZONE 'UTC' +(SELECT INTERVAL '1 second'*(SELECT (SYSTEM_PARAMETER_VALUE)::DOUBLE PRECISION/1000 FROM PSP_SYSTEM_PARAMETER WHERE SYSTEM_PARAMETER_CD = 'PSP_DATE_OFFSET')) INTO v_psp_utc_systimestamp FROM DUAL;
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (gen_random_uuid(), 0, v_psp_utc_systimestamp, v_psp_utc_systimestamp, 'EntityChange', 'NewEinEnc', (OLD.NEW_EIN_ENC )::VARCHAR, (NEW.NEW_EIN_ENC )::VARCHAR, NEW.ENTITY_CHANGE_SEQ, v_modifier_id, v_psp_utc_systimestamp, v_company_fk);
         END IF;
     END IF;

     IF (((NEW.OLD_EIN_ENC <> OLD.OLD_EIN_ENC) AND NEW.OLD_EIN_ENC IS NOT NULL AND OLD.OLD_EIN_ENC IS NOT NULL) OR
         (NEW.OLD_EIN_ENC IS NULL AND OLD.OLD_EIN_ENC IS NOT NULL) OR
         (NEW.OLD_EIN_ENC IS NOT NULL AND OLD.OLD_EIN_ENC IS NULL) ) THEN
         BEGIN
            SELECT NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            SELECT CURRENT_TIMESTAMP AT TIME ZONE 'UTC' +(SELECT INTERVAL '1 second'*(SELECT (SYSTEM_PARAMETER_VALUE)::DOUBLE PRECISION/1000 FROM PSP_SYSTEM_PARAMETER WHERE SYSTEM_PARAMETER_CD = 'PSP_DATE_OFFSET')) INTO v_psp_utc_systimestamp FROM DUAL;
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (gen_random_uuid(), 0, v_psp_utc_systimestamp, v_psp_utc_systimestamp, 'EntityChange', 'OldEinEnc', (OLD.OLD_EIN_ENC )::VARCHAR, (NEW.OLD_EIN_ENC )::VARCHAR, NEW.ENTITY_CHANGE_SEQ, v_modifier_id, v_psp_utc_systimestamp, v_company_fk);
         END IF;
     END IF;

  END IF;
  RETURN NEW;
END;
$$
LANGUAGE PLPGSQL;
