CREATE OR REPLACE FUNCTION FN_PSP_EMPLOYEE_AT()
RETURNS TRIGGER
AS $$
DECLARE
  v_company_fk VARCHAR(255);
  v_creator_id VARCHAR(30);
  v_modifier_id VARCHAR(30);
  v_psp_utc_systimestamp TIMESTAMP;
BEGIN
SELECT CREATOR_ID INTO v_creator_id FROM PSP_INDIVIDUAL WHERE INDIVIDUAL_SEQ = NEW.EMPLOYEE_SEQ;
SELECT MODIFIER_ID INTO v_modifier_id FROM PSP_INDIVIDUAL WHERE INDIVIDUAL_SEQ = NEW.EMPLOYEE_SEQ;

  IF (TG_OP='UPDATE') THEN
     IF (((NEW.BIRTH_DATE_ENC <> OLD.BIRTH_DATE_ENC) AND NEW.BIRTH_DATE_ENC IS NOT NULL AND OLD.BIRTH_DATE_ENC IS NOT NULL) OR
         (NEW.BIRTH_DATE_ENC IS NULL AND OLD.BIRTH_DATE_ENC IS NOT NULL) OR
         (NEW.BIRTH_DATE_ENC IS NOT NULL AND OLD.BIRTH_DATE_ENC IS NULL) ) THEN
         BEGIN
            SELECT NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            SELECT CURRENT_TIMESTAMP AT TIME ZONE 'UTC' +(SELECT INTERVAL '1 second'*(SELECT (SYSTEM_PARAMETER_VALUE)::DOUBLE PRECISION/1000 FROM PSP_SYSTEM_PARAMETER WHERE SYSTEM_PARAMETER_CD = 'PSP_DATE_OFFSET')) INTO v_psp_utc_systimestamp FROM DUAL;
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (gen_random_uuid(), 0, v_psp_utc_systimestamp, v_psp_utc_systimestamp, 'Employee', 'BirthDateEnc', (OLD.BIRTH_DATE_ENC )::VARCHAR, (NEW.BIRTH_DATE_ENC )::VARCHAR, NEW.EMPLOYEE_SEQ, v_modifier_id, v_psp_utc_systimestamp, v_company_fk);
         END IF;
     END IF;

     IF (((NEW.FED_ALLOWANCES <> OLD.FED_ALLOWANCES) AND NEW.FED_ALLOWANCES IS NOT NULL AND OLD.FED_ALLOWANCES IS NOT NULL) OR
         (NEW.FED_ALLOWANCES IS NULL AND OLD.FED_ALLOWANCES IS NOT NULL) OR
         (NEW.FED_ALLOWANCES IS NOT NULL AND OLD.FED_ALLOWANCES IS NULL) ) THEN
         BEGIN
            SELECT NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            SELECT CURRENT_TIMESTAMP AT TIME ZONE 'UTC' +(SELECT INTERVAL '1 second'*(SELECT (SYSTEM_PARAMETER_VALUE)::DOUBLE PRECISION/1000 FROM PSP_SYSTEM_PARAMETER WHERE SYSTEM_PARAMETER_CD = 'PSP_DATE_OFFSET')) INTO v_psp_utc_systimestamp FROM DUAL;
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (gen_random_uuid(), 0, v_psp_utc_systimestamp, v_psp_utc_systimestamp, 'Employee', 'FedAllowances', (OLD.FED_ALLOWANCES )::VARCHAR, (NEW.FED_ALLOWANCES )::VARCHAR, NEW.EMPLOYEE_SEQ, v_modifier_id, v_psp_utc_systimestamp, v_company_fk);
         END IF;
     END IF;

     IF (((NEW.FED_FILING_STATUS <> OLD.FED_FILING_STATUS) AND NEW.FED_FILING_STATUS IS NOT NULL AND OLD.FED_FILING_STATUS IS NOT NULL) OR
         (NEW.FED_FILING_STATUS IS NULL AND OLD.FED_FILING_STATUS IS NOT NULL) OR
         (NEW.FED_FILING_STATUS IS NOT NULL AND OLD.FED_FILING_STATUS IS NULL) ) THEN
         BEGIN
            SELECT NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            SELECT CURRENT_TIMESTAMP AT TIME ZONE 'UTC' +(SELECT INTERVAL '1 second'*(SELECT (SYSTEM_PARAMETER_VALUE)::DOUBLE PRECISION/1000 FROM PSP_SYSTEM_PARAMETER WHERE SYSTEM_PARAMETER_CD = 'PSP_DATE_OFFSET')) INTO v_psp_utc_systimestamp FROM DUAL;
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (gen_random_uuid(), 0, v_psp_utc_systimestamp, v_psp_utc_systimestamp, 'Employee', 'FedFilingStatus', (OLD.FED_FILING_STATUS )::VARCHAR, (NEW.FED_FILING_STATUS )::VARCHAR, NEW.EMPLOYEE_SEQ, v_modifier_id, v_psp_utc_systimestamp, v_company_fk);
         END IF;
     END IF;

     IF (((NEW.HIRE_DATE <> OLD.HIRE_DATE) AND NEW.HIRE_DATE IS NOT NULL AND OLD.HIRE_DATE IS NOT NULL) OR
         (NEW.HIRE_DATE IS NULL AND OLD.HIRE_DATE IS NOT NULL) OR
         (NEW.HIRE_DATE IS NOT NULL AND OLD.HIRE_DATE IS NULL) ) THEN
         BEGIN
            SELECT NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            SELECT CURRENT_TIMESTAMP AT TIME ZONE 'UTC' +(SELECT INTERVAL '1 second'*(SELECT (SYSTEM_PARAMETER_VALUE)::DOUBLE PRECISION/1000 FROM PSP_SYSTEM_PARAMETER WHERE SYSTEM_PARAMETER_CD = 'PSP_DATE_OFFSET')) INTO v_psp_utc_systimestamp FROM DUAL;
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (gen_random_uuid(), 0, v_psp_utc_systimestamp, v_psp_utc_systimestamp, 'Employee', 'HireDate', (to_char(OLD.HIRE_DATE, 'dd-MON-yy HH.MI.SS.US AM') )::VARCHAR, (to_char(NEW.HIRE_DATE, 'dd-MON-yy HH.MI.SS.US AM') )::VARCHAR, NEW.EMPLOYEE_SEQ, v_modifier_id, v_psp_utc_systimestamp, v_company_fk);
         END IF;
     END IF;

     IF (((NEW.RE_HIRE_DATE <> OLD.RE_HIRE_DATE) AND NEW.RE_HIRE_DATE IS NOT NULL AND OLD.RE_HIRE_DATE IS NOT NULL) OR
         (NEW.RE_HIRE_DATE IS NULL AND OLD.RE_HIRE_DATE IS NOT NULL) OR
         (NEW.RE_HIRE_DATE IS NOT NULL AND OLD.RE_HIRE_DATE IS NULL) ) THEN
         BEGIN
            SELECT NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            SELECT CURRENT_TIMESTAMP AT TIME ZONE 'UTC' +(SELECT INTERVAL '1 second'*(SELECT (SYSTEM_PARAMETER_VALUE)::DOUBLE PRECISION/1000 FROM PSP_SYSTEM_PARAMETER WHERE SYSTEM_PARAMETER_CD = 'PSP_DATE_OFFSET')) INTO v_psp_utc_systimestamp FROM DUAL;
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (gen_random_uuid(), 0, v_psp_utc_systimestamp, v_psp_utc_systimestamp, 'Employee', 'ReHireDate', (to_char(OLD.RE_HIRE_DATE, 'dd-MON-yy HH.MI.SS.US AM') )::VARCHAR, (to_char(NEW.RE_HIRE_DATE, 'dd-MON-yy HH.MI.SS.US AM') )::VARCHAR, NEW.EMPLOYEE_SEQ, v_modifier_id, v_psp_utc_systimestamp, v_company_fk);
         END IF;
     END IF;

     IF (((NEW.TERMINATION_DATE <> OLD.TERMINATION_DATE) AND NEW.TERMINATION_DATE IS NOT NULL AND OLD.TERMINATION_DATE IS NOT NULL) OR
         (NEW.TERMINATION_DATE IS NULL AND OLD.TERMINATION_DATE IS NOT NULL) OR
         (NEW.TERMINATION_DATE IS NOT NULL AND OLD.TERMINATION_DATE IS NULL) ) THEN
         BEGIN
            SELECT NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            SELECT CURRENT_TIMESTAMP AT TIME ZONE 'UTC' +(SELECT INTERVAL '1 second'*(SELECT (SYSTEM_PARAMETER_VALUE)::DOUBLE PRECISION/1000 FROM PSP_SYSTEM_PARAMETER WHERE SYSTEM_PARAMETER_CD = 'PSP_DATE_OFFSET')) INTO v_psp_utc_systimestamp FROM DUAL;
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (gen_random_uuid(), 0, v_psp_utc_systimestamp, v_psp_utc_systimestamp, 'Employee', 'TerminationDate', (to_char(OLD.TERMINATION_DATE, 'dd-MON-yy HH.MI.SS.US AM') )::VARCHAR, (to_char(NEW.TERMINATION_DATE, 'dd-MON-yy HH.MI.SS.US AM') )::VARCHAR, NEW.EMPLOYEE_SEQ, v_modifier_id, v_psp_utc_systimestamp, v_company_fk);
         END IF;
     END IF;

     IF (((NEW.WORK_STATE <> OLD.WORK_STATE) AND NEW.WORK_STATE IS NOT NULL AND OLD.WORK_STATE IS NOT NULL) OR
         (NEW.WORK_STATE IS NULL AND OLD.WORK_STATE IS NOT NULL) OR
         (NEW.WORK_STATE IS NOT NULL AND OLD.WORK_STATE IS NULL) ) THEN
         BEGIN
            SELECT NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            SELECT CURRENT_TIMESTAMP AT TIME ZONE 'UTC' +(SELECT INTERVAL '1 second'*(SELECT (SYSTEM_PARAMETER_VALUE)::DOUBLE PRECISION/1000 FROM PSP_SYSTEM_PARAMETER WHERE SYSTEM_PARAMETER_CD = 'PSP_DATE_OFFSET')) INTO v_psp_utc_systimestamp FROM DUAL;
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (gen_random_uuid(), 0, v_psp_utc_systimestamp, v_psp_utc_systimestamp, 'Employee', 'WorkState', (OLD.WORK_STATE )::VARCHAR, (NEW.WORK_STATE )::VARCHAR, NEW.EMPLOYEE_SEQ, v_modifier_id, v_psp_utc_systimestamp, v_company_fk);
         END IF;
     END IF;

     IF (((NEW.LIVE_STATE <> OLD.LIVE_STATE) AND NEW.LIVE_STATE IS NOT NULL AND OLD.LIVE_STATE IS NOT NULL) OR
         (NEW.LIVE_STATE IS NULL AND OLD.LIVE_STATE IS NOT NULL) OR
         (NEW.LIVE_STATE IS NOT NULL AND OLD.LIVE_STATE IS NULL) ) THEN
         BEGIN
            SELECT NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            SELECT CURRENT_TIMESTAMP AT TIME ZONE 'UTC' +(SELECT INTERVAL '1 second'*(SELECT (SYSTEM_PARAMETER_VALUE)::DOUBLE PRECISION/1000 FROM PSP_SYSTEM_PARAMETER WHERE SYSTEM_PARAMETER_CD = 'PSP_DATE_OFFSET')) INTO v_psp_utc_systimestamp FROM DUAL;
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (gen_random_uuid(), 0, v_psp_utc_systimestamp, v_psp_utc_systimestamp, 'Employee', 'LiveState', (OLD.LIVE_STATE )::VARCHAR, (NEW.LIVE_STATE )::VARCHAR, NEW.EMPLOYEE_SEQ, v_modifier_id, v_psp_utc_systimestamp, v_company_fk);
         END IF;
     END IF;

     IF (((NEW.SOURCE_EMPLOYEE_ID <> OLD.SOURCE_EMPLOYEE_ID) AND NEW.SOURCE_EMPLOYEE_ID IS NOT NULL AND OLD.SOURCE_EMPLOYEE_ID IS NOT NULL) OR
         (NEW.SOURCE_EMPLOYEE_ID IS NULL AND OLD.SOURCE_EMPLOYEE_ID IS NOT NULL) OR
         (NEW.SOURCE_EMPLOYEE_ID IS NOT NULL AND OLD.SOURCE_EMPLOYEE_ID IS NULL) ) THEN
         BEGIN
            SELECT NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            SELECT CURRENT_TIMESTAMP AT TIME ZONE 'UTC' +(SELECT INTERVAL '1 second'*(SELECT (SYSTEM_PARAMETER_VALUE)::DOUBLE PRECISION/1000 FROM PSP_SYSTEM_PARAMETER WHERE SYSTEM_PARAMETER_CD = 'PSP_DATE_OFFSET')) INTO v_psp_utc_systimestamp FROM DUAL;
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (gen_random_uuid(), 0, v_psp_utc_systimestamp, v_psp_utc_systimestamp, 'Employee', 'SourceEmployeeId', (OLD.SOURCE_EMPLOYEE_ID )::VARCHAR, (NEW.SOURCE_EMPLOYEE_ID )::VARCHAR, NEW.EMPLOYEE_SEQ, v_modifier_id, v_psp_utc_systimestamp, v_company_fk);
         END IF;
     END IF;

     IF (((NEW.STATUS_CD <> OLD.STATUS_CD) AND NEW.STATUS_CD IS NOT NULL AND OLD.STATUS_CD IS NOT NULL) OR
         (NEW.STATUS_CD IS NULL AND OLD.STATUS_CD IS NOT NULL) OR
         (NEW.STATUS_CD IS NOT NULL AND OLD.STATUS_CD IS NULL) ) THEN
         BEGIN
            SELECT NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            SELECT CURRENT_TIMESTAMP AT TIME ZONE 'UTC' +(SELECT INTERVAL '1 second'*(SELECT (SYSTEM_PARAMETER_VALUE)::DOUBLE PRECISION/1000 FROM PSP_SYSTEM_PARAMETER WHERE SYSTEM_PARAMETER_CD = 'PSP_DATE_OFFSET')) INTO v_psp_utc_systimestamp FROM DUAL;
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (gen_random_uuid(), 0, v_psp_utc_systimestamp, v_psp_utc_systimestamp, 'Employee', 'StatusCd', (OLD.STATUS_CD )::VARCHAR, (NEW.STATUS_CD )::VARCHAR, NEW.EMPLOYEE_SEQ, v_modifier_id, v_psp_utc_systimestamp, v_company_fk);
         END IF;
     END IF;

     IF (((NEW.TAX_ID_ENC <> OLD.TAX_ID_ENC) AND NEW.TAX_ID_ENC IS NOT NULL AND OLD.TAX_ID_ENC IS NOT NULL) OR
         (NEW.TAX_ID_ENC IS NULL AND OLD.TAX_ID_ENC IS NOT NULL) OR
         (NEW.TAX_ID_ENC IS NOT NULL AND OLD.TAX_ID_ENC IS NULL) ) THEN
         BEGIN
            SELECT NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            SELECT CURRENT_TIMESTAMP AT TIME ZONE 'UTC' +(SELECT INTERVAL '1 second'*(SELECT (SYSTEM_PARAMETER_VALUE)::DOUBLE PRECISION/1000 FROM PSP_SYSTEM_PARAMETER WHERE SYSTEM_PARAMETER_CD = 'PSP_DATE_OFFSET')) INTO v_psp_utc_systimestamp FROM DUAL;
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (gen_random_uuid(), 0, v_psp_utc_systimestamp, v_psp_utc_systimestamp, 'Employee', 'TaxIdEnc', (OLD.TAX_ID_ENC )::VARCHAR, (NEW.TAX_ID_ENC )::VARCHAR, NEW.EMPLOYEE_SEQ, v_modifier_id, v_psp_utc_systimestamp, v_company_fk);
         END IF;
     END IF;

     IF (((NEW.TP_401K_INFO_IS_HCE <> OLD.TP_401K_INFO_IS_HCE) AND NEW.TP_401K_INFO_IS_HCE IS NOT NULL AND OLD.TP_401K_INFO_IS_HCE IS NOT NULL) OR
         (NEW.TP_401K_INFO_IS_HCE IS NULL AND OLD.TP_401K_INFO_IS_HCE IS NOT NULL) OR
         (NEW.TP_401K_INFO_IS_HCE IS NOT NULL AND OLD.TP_401K_INFO_IS_HCE IS NULL) ) THEN
         BEGIN
            SELECT NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            SELECT CURRENT_TIMESTAMP AT TIME ZONE 'UTC' +(SELECT INTERVAL '1 second'*(SELECT (SYSTEM_PARAMETER_VALUE)::DOUBLE PRECISION/1000 FROM PSP_SYSTEM_PARAMETER WHERE SYSTEM_PARAMETER_CD = 'PSP_DATE_OFFSET')) INTO v_psp_utc_systimestamp FROM DUAL;
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (gen_random_uuid(), 0, v_psp_utc_systimestamp, v_psp_utc_systimestamp, 'Employee', 'ThirdParty401kInfo.IsHighlyCompensated', (OLD.TP_401K_INFO_IS_HCE )::VARCHAR, (NEW.TP_401K_INFO_IS_HCE )::VARCHAR, NEW.EMPLOYEE_SEQ, v_modifier_id, v_psp_utc_systimestamp, v_company_fk);
         END IF;
     END IF;

     IF (((NEW.TP_401K_INFO_OWNER_PERCENT <> OLD.TP_401K_INFO_OWNER_PERCENT) AND NEW.TP_401K_INFO_OWNER_PERCENT IS NOT NULL AND OLD.TP_401K_INFO_OWNER_PERCENT IS NOT NULL) OR
         (NEW.TP_401K_INFO_OWNER_PERCENT IS NULL AND OLD.TP_401K_INFO_OWNER_PERCENT IS NOT NULL) OR
         (NEW.TP_401K_INFO_OWNER_PERCENT IS NOT NULL AND OLD.TP_401K_INFO_OWNER_PERCENT IS NULL) ) THEN
         BEGIN
            SELECT NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            SELECT CURRENT_TIMESTAMP AT TIME ZONE 'UTC' +(SELECT INTERVAL '1 second'*(SELECT (SYSTEM_PARAMETER_VALUE)::DOUBLE PRECISION/1000 FROM PSP_SYSTEM_PARAMETER WHERE SYSTEM_PARAMETER_CD = 'PSP_DATE_OFFSET')) INTO v_psp_utc_systimestamp FROM DUAL;
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (gen_random_uuid(), 0, v_psp_utc_systimestamp, v_psp_utc_systimestamp, 'Employee', 'ThirdParty401kInfo.OwnershipPercentage', (OLD.TP_401K_INFO_OWNER_PERCENT )::VARCHAR, (NEW.TP_401K_INFO_OWNER_PERCENT )::VARCHAR, NEW.EMPLOYEE_SEQ, v_modifier_id, v_psp_utc_systimestamp, v_company_fk);
         END IF;
     END IF;

     IF (((NEW.TP_401K_INFO_IS_FAMILY_MEMBER <> OLD.TP_401K_INFO_IS_FAMILY_MEMBER) AND NEW.TP_401K_INFO_IS_FAMILY_MEMBER IS NOT NULL AND OLD.TP_401K_INFO_IS_FAMILY_MEMBER IS NOT NULL) OR
         (NEW.TP_401K_INFO_IS_FAMILY_MEMBER IS NULL AND OLD.TP_401K_INFO_IS_FAMILY_MEMBER IS NOT NULL) OR
         (NEW.TP_401K_INFO_IS_FAMILY_MEMBER IS NOT NULL AND OLD.TP_401K_INFO_IS_FAMILY_MEMBER IS NULL) ) THEN
         BEGIN
            SELECT NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            SELECT CURRENT_TIMESTAMP AT TIME ZONE 'UTC' +(SELECT INTERVAL '1 second'*(SELECT (SYSTEM_PARAMETER_VALUE)::DOUBLE PRECISION/1000 FROM PSP_SYSTEM_PARAMETER WHERE SYSTEM_PARAMETER_CD = 'PSP_DATE_OFFSET')) INTO v_psp_utc_systimestamp FROM DUAL;
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (gen_random_uuid(), 0, v_psp_utc_systimestamp, v_psp_utc_systimestamp, 'Employee', 'ThirdParty401kInfo.IsFamilyMember', (OLD.TP_401K_INFO_IS_FAMILY_MEMBER )::VARCHAR, (NEW.TP_401K_INFO_IS_FAMILY_MEMBER )::VARCHAR, NEW.EMPLOYEE_SEQ, v_modifier_id, v_psp_utc_systimestamp, v_company_fk);
         END IF;
     END IF;

     IF (((NEW.TP_401K_INFO_LAST_UPLOAD_DATE <> OLD.TP_401K_INFO_LAST_UPLOAD_DATE) AND NEW.TP_401K_INFO_LAST_UPLOAD_DATE IS NOT NULL AND OLD.TP_401K_INFO_LAST_UPLOAD_DATE IS NOT NULL) OR
         (NEW.TP_401K_INFO_LAST_UPLOAD_DATE IS NULL AND OLD.TP_401K_INFO_LAST_UPLOAD_DATE IS NOT NULL) OR
         (NEW.TP_401K_INFO_LAST_UPLOAD_DATE IS NOT NULL AND OLD.TP_401K_INFO_LAST_UPLOAD_DATE IS NULL) ) THEN
         BEGIN
            SELECT NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            SELECT CURRENT_TIMESTAMP AT TIME ZONE 'UTC' +(SELECT INTERVAL '1 second'*(SELECT (SYSTEM_PARAMETER_VALUE)::DOUBLE PRECISION/1000 FROM PSP_SYSTEM_PARAMETER WHERE SYSTEM_PARAMETER_CD = 'PSP_DATE_OFFSET')) INTO v_psp_utc_systimestamp FROM DUAL;
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (gen_random_uuid(), 0, v_psp_utc_systimestamp, v_psp_utc_systimestamp, 'Employee', 'ThirdParty401kInfo.Last401kUploadDate', (to_char(OLD.TP_401K_INFO_LAST_UPLOAD_DATE, 'dd-MON-yy HH.MI.SS.US AM') )::VARCHAR, (to_char(NEW.TP_401K_INFO_LAST_UPLOAD_DATE, 'dd-MON-yy HH.MI.SS.US AM') )::VARCHAR, NEW.EMPLOYEE_SEQ, v_modifier_id, v_psp_utc_systimestamp, v_company_fk);
         END IF;
     END IF;

  END IF;
  RETURN NEW;
END;
$$
LANGUAGE PLPGSQL;
