CREATE OR REPLACE FUNCTION FN_PSP_MONEY_MVMT_TRANS_AT()
RETURNS TRIGGER
AS $$
DECLARE
  v_company_fk VARCHAR(255);
  v_creator_id VARCHAR(30);
  v_modifier_id VARCHAR(30);
  v_psp_utc_systimestamp TIMESTAMP;
BEGIN
SELECT NEW.CREATOR_ID INTO v_creator_id FROM DUAL;
SELECT NEW.MODIFIER_ID INTO v_modifier_id FROM DUAL;

  IF (TG_OP='UPDATE') THEN
     IF (((NEW.AGENCY_TAXPAYER_ID_ENC <> OLD.AGENCY_TAXPAYER_ID_ENC) AND NEW.AGENCY_TAXPAYER_ID_ENC IS NOT NULL AND OLD.AGENCY_TAXPAYER_ID_ENC IS NOT NULL) OR
         (NEW.AGENCY_TAXPAYER_ID_ENC IS NULL AND OLD.AGENCY_TAXPAYER_ID_ENC IS NOT NULL) OR
         (NEW.AGENCY_TAXPAYER_ID_ENC IS NOT NULL AND OLD.AGENCY_TAXPAYER_ID_ENC IS NULL) ) THEN
         BEGIN
            SELECT NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            SELECT CURRENT_TIMESTAMP AT TIME ZONE 'UTC' +(SELECT INTERVAL '1 second'*(SELECT (SYSTEM_PARAMETER_VALUE)::DOUBLE PRECISION/1000 FROM PSP_SYSTEM_PARAMETER WHERE SYSTEM_PARAMETER_CD = 'PSP_DATE_OFFSET')) INTO v_psp_utc_systimestamp FROM DUAL;
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (gen_random_uuid(), 0, v_psp_utc_systimestamp, v_psp_utc_systimestamp, 'MoneyMovementTransaction', 'AgencyTaxpayerIdEnc', (OLD.AGENCY_TAXPAYER_ID_ENC )::VARCHAR, (NEW.AGENCY_TAXPAYER_ID_ENC )::VARCHAR, NEW.MONEY_MOVEMENT_TRANSACTION_SEQ, v_modifier_id, v_psp_utc_systimestamp, v_company_fk);
         END IF;
     END IF;

     IF (((NEW.INITIATION_DATE <> OLD.INITIATION_DATE) AND NEW.INITIATION_DATE IS NOT NULL AND OLD.INITIATION_DATE IS NOT NULL) OR
         (NEW.INITIATION_DATE IS NULL AND OLD.INITIATION_DATE IS NOT NULL) OR
         (NEW.INITIATION_DATE IS NOT NULL AND OLD.INITIATION_DATE IS NULL) ) THEN
         BEGIN
            SELECT NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            SELECT CURRENT_TIMESTAMP AT TIME ZONE 'UTC' +(SELECT INTERVAL '1 second'*(SELECT (SYSTEM_PARAMETER_VALUE)::DOUBLE PRECISION/1000 FROM PSP_SYSTEM_PARAMETER WHERE SYSTEM_PARAMETER_CD = 'PSP_DATE_OFFSET')) INTO v_psp_utc_systimestamp FROM DUAL;
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (gen_random_uuid(), 0, v_psp_utc_systimestamp, v_psp_utc_systimestamp, 'MoneyMovementTransaction', 'InitiationDate', to_char(OLD.INITIATION_DATE,'dd-MON-yy HH.MI.SS.US AM')::VARCHAR, to_char(NEW.INITIATION_DATE,'dd-MON-yy HH.MI.SS.US AM')::VARCHAR, NEW.MONEY_MOVEMENT_TRANSACTION_SEQ, v_modifier_id, v_psp_utc_systimestamp, v_company_fk);
         END IF;
     END IF;

     IF (((NEW.MANUAL_PAYMENT_STATUS <> OLD.MANUAL_PAYMENT_STATUS) AND NEW.MANUAL_PAYMENT_STATUS IS NOT NULL AND OLD.MANUAL_PAYMENT_STATUS IS NOT NULL) OR
         (NEW.MANUAL_PAYMENT_STATUS IS NULL AND OLD.MANUAL_PAYMENT_STATUS IS NOT NULL) OR
         (NEW.MANUAL_PAYMENT_STATUS IS NOT NULL AND OLD.MANUAL_PAYMENT_STATUS IS NULL) ) THEN
         BEGIN
            SELECT NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            SELECT CURRENT_TIMESTAMP AT TIME ZONE 'UTC' +(SELECT INTERVAL '1 second'*(SELECT (SYSTEM_PARAMETER_VALUE)::DOUBLE PRECISION/1000 FROM PSP_SYSTEM_PARAMETER WHERE SYSTEM_PARAMETER_CD = 'PSP_DATE_OFFSET')) INTO v_psp_utc_systimestamp FROM DUAL;
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (gen_random_uuid(), 0, v_psp_utc_systimestamp, v_psp_utc_systimestamp, 'MoneyMovementTransaction', 'ManualPaymentStatus', (OLD.MANUAL_PAYMENT_STATUS )::VARCHAR, (NEW.MANUAL_PAYMENT_STATUS )::VARCHAR, NEW.MONEY_MOVEMENT_TRANSACTION_SEQ, v_modifier_id, v_psp_utc_systimestamp, v_company_fk);
         END IF;
     END IF;

     IF (((NEW.MONEY_MOVEMENT_PAYMENT_METHOD <> OLD.MONEY_MOVEMENT_PAYMENT_METHOD) AND NEW.MONEY_MOVEMENT_PAYMENT_METHOD IS NOT NULL AND OLD.MONEY_MOVEMENT_PAYMENT_METHOD IS NOT NULL) OR
         (NEW.MONEY_MOVEMENT_PAYMENT_METHOD IS NULL AND OLD.MONEY_MOVEMENT_PAYMENT_METHOD IS NOT NULL) OR
         (NEW.MONEY_MOVEMENT_PAYMENT_METHOD IS NOT NULL AND OLD.MONEY_MOVEMENT_PAYMENT_METHOD IS NULL) ) THEN
         BEGIN
            SELECT NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            SELECT CURRENT_TIMESTAMP AT TIME ZONE 'UTC' +(SELECT INTERVAL '1 second'*(SELECT (SYSTEM_PARAMETER_VALUE)::DOUBLE PRECISION/1000 FROM PSP_SYSTEM_PARAMETER WHERE SYSTEM_PARAMETER_CD = 'PSP_DATE_OFFSET')) INTO v_psp_utc_systimestamp FROM DUAL;
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (gen_random_uuid(), 0, v_psp_utc_systimestamp, v_psp_utc_systimestamp, 'MoneyMovementTransaction', 'MoneyMovementPaymentMethod', (OLD.MONEY_MOVEMENT_PAYMENT_METHOD )::VARCHAR, (NEW.MONEY_MOVEMENT_PAYMENT_METHOD )::VARCHAR, NEW.MONEY_MOVEMENT_TRANSACTION_SEQ, v_modifier_id, v_psp_utc_systimestamp, v_company_fk);
         END IF;
     END IF;

     IF (((NEW.TAX_PAYMENT_STATUS <> OLD.TAX_PAYMENT_STATUS) AND NEW.TAX_PAYMENT_STATUS IS NOT NULL AND OLD.TAX_PAYMENT_STATUS IS NOT NULL) OR
         (NEW.TAX_PAYMENT_STATUS IS NULL AND OLD.TAX_PAYMENT_STATUS IS NOT NULL) OR
         (NEW.TAX_PAYMENT_STATUS IS NOT NULL AND OLD.TAX_PAYMENT_STATUS IS NULL) ) THEN
         BEGIN
            SELECT NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            SELECT CURRENT_TIMESTAMP AT TIME ZONE 'UTC' +(SELECT INTERVAL '1 second'*(SELECT (SYSTEM_PARAMETER_VALUE)::DOUBLE PRECISION/1000 FROM PSP_SYSTEM_PARAMETER WHERE SYSTEM_PARAMETER_CD = 'PSP_DATE_OFFSET')) INTO v_psp_utc_systimestamp FROM DUAL;
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (gen_random_uuid(), 0, v_psp_utc_systimestamp, v_psp_utc_systimestamp, 'MoneyMovementTransaction', 'TaxPaymentStatus', (OLD.TAX_PAYMENT_STATUS )::VARCHAR, (NEW.TAX_PAYMENT_STATUS )::VARCHAR, NEW.MONEY_MOVEMENT_TRANSACTION_SEQ, v_modifier_id, v_psp_utc_systimestamp, v_company_fk);
         END IF;
     END IF;

     IF (((NEW.REFERENCE_NUMBER <> OLD.REFERENCE_NUMBER) AND NEW.REFERENCE_NUMBER IS NOT NULL AND OLD.REFERENCE_NUMBER IS NOT NULL) OR
         (NEW.REFERENCE_NUMBER IS NULL AND OLD.REFERENCE_NUMBER IS NOT NULL) OR
         (NEW.REFERENCE_NUMBER IS NOT NULL AND OLD.REFERENCE_NUMBER IS NULL) ) THEN
         BEGIN
            SELECT NEW.COMPANY_FK INTO v_company_fk from DUAL;
         EXCEPTION
            WHEN NO_DATA_FOUND THEN v_company_fk := NULL;
            WHEN OTHERS THEN RAISE;
         END;

         IF v_company_fk IS NOT NULL THEN
            SELECT CURRENT_TIMESTAMP AT TIME ZONE 'UTC' +(SELECT INTERVAL '1 second'*(SELECT (SYSTEM_PARAMETER_VALUE)::DOUBLE PRECISION/1000 FROM PSP_SYSTEM_PARAMETER WHERE SYSTEM_PARAMETER_CD = 'PSP_DATE_OFFSET')) INTO v_psp_utc_systimestamp FROM DUAL;
            INSERT INTO PSP_PROPERTY_AUDIT
              (PROPERTY_AUDIT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, CLASS_NAME, PROPERTY_NAME, OLD_PROPERTY_VALUE, NEW_PROPERTY_VALUE, OBJECT_IDENTIFIER, USER_ID, AUDIT_DATE, COMPANY_FK)
            VALUES
              (gen_random_uuid(), 0, v_psp_utc_systimestamp, v_psp_utc_systimestamp, 'MoneyMovementTransaction', 'ReferenceNumber', (OLD.REFERENCE_NUMBER )::VARCHAR, (NEW.REFERENCE_NUMBER )::VARCHAR, NEW.MONEY_MOVEMENT_TRANSACTION_SEQ, v_modifier_id, v_psp_utc_systimestamp, v_company_fk);
         END IF;
     END IF;

  END IF;
  RETURN NEW;
END;
$$
LANGUAGE PLPGSQL;

