<?xml version="1.0" encoding="UTF-8"?>
<!--edited with XMLSpy v2010 rel. 2 (http://www.altova.com) by Anna (Intuit)--><!--** Intuit Inc.  **
** This is a ABS **
** We always include the wsdl,xsd, soap, our documentation, and Core Common namespaces. Always the same prefixes. **
** Need to define namespaces for EBO and ABCS, and always use these same prefixes - abo and abcs. **
** Need to define the target namespace equal to the ABCS namespace. Also define a name, in the form of - name+ABCS. **
 
Copyright (c) 2009, Intuit, Inc. All rights reserved 
 
   WSDL File Name 
   Name: //integration/AIA/AIAComponents/builddev/AIAComponents/EnterpriseBusinessServiceLibrary/Industry/Intuit/EBO/CustomerAsset/V1/IntuitCustomerAsset.wsdl--><definitions name="IntuitCustomerAsset" targetNamespace="http://www.intuit.com/iep/IntuitCustomerAsset/V1" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:svcdoc="http://xmlns.oracle.com/Services/Documentation/V1" xmlns:intuit="http://www.intuit.com/iep/CustomerAsset/IntuitCustomerAssetABO/V1" xmlns:ebs="http://www.intuit.com/iep/IntuitCustomerAsset/V1">
  <!--<documentation><svcdoc:Service>
	<svcdoc:Description>Intuit Customer Asset Application Business Service</svcdoc:Description>
	<svcdoc:ServiceType>Enterprise Business Service</svcdoc:ServiceType>
	<svcdoc:DisplayName>IntuitCustomerAssetEBSV1</svcdoc:DisplayName>
	<svcdoc:Version>1.00</svcdoc:Version>
	<svcdoc:EBOName>IntuitCustomerAssetABO</svcdoc:EBOName>
	<svcdoc:LifecycleStatus>Active</svcdoc:LifecycleStatus>
	<svcdoc:ImplementationTechnology>ESB</svcdoc:ImplementationTechnology>
	<svcdoc:Industry>Intuit</svcdoc:Industry>
</svcdoc:Service></documentation>-->
  <types>
    <xsd:schema targetNamespace="http://www.intuit.com/iep/IntuitCustomerAsset/V1" elementFormDefault="qualified">
      <xsd:import namespace="http://www.intuit.com/iep/CustomerAsset/IntuitCustomerAssetABO/V1" schemaLocation="IntuitCustomerAssetABM.xsd"/>
    </xsd:schema>
  </types>
  <message name="GetCustomerAssetFaultMsg">
    <!--<documentation><svcdoc:Message>
	<svcdoc:Description>This message is used for propagating Error Context and Error Message</svcdoc:Description>
</svcdoc:Message></documentation>-->
    <part name="CustomerAssetFault" element="intuit:Error"/>
  </message>
  <message name="GetCustomerAssetReqMsg">
    <!--<documentation><svcdoc:Message>
	<svcdoc:Description>This message is used as the request payload to the GetCustomerAsset operation</svcdoc:Description>
</svcdoc:Message></documentation>-->
    <part name="GetCustomerAssetABM" element="intuit:GetCustomerAssetABM"/>
  </message>
  <message name="GetCustomerAssetRespMsg">
    <!--<documentation><svcdoc:Message>
	<svcdoc:Description>This message is used as the response payload to the GetCustomerAsset operation</svcdoc:Description>
</svcdoc:Message></documentation>-->
    <part name="GetCustomerAssetResponseABM" element="intuit:GetCustomerAssetResponseABM"/>
  </message>
  <portType name="CustomerAssetPort">
    <!--<documentation><svcdoc:Interface>
	<svcdoc:Description>This interface contains operations for the Request-Response and Request-Only patterns</svcdoc:Description>
	<svcdoc:DisplayName>RequestCustomerAsset EBS Interface</svcdoc:DisplayName>
	<svcdoc:LifecycleStatus>Active</svcdoc:LifecycleStatus>
</svcdoc:Interface></documentation>-->
    <!--operation support for GetCustomerAsset-->
    <operation name="GetCustomerAsset">
      <!--<documentation><svcdoc:Operation>
	<svcdoc:Description>This operation is used to Get CustomerAsset ABO.</svcdoc:Description>
	<svcdoc:MEP>SYNC_REQ_RESPONSE</svcdoc:MEP>
	<svcdoc:DisplayName>GetCustomerAsset</svcdoc:DisplayName>
	<svcdoc:LifecycleStatus>Active</svcdoc:LifecycleStatus>
	<svcdoc:Scope>Public</svcdoc:Scope>
</svcdoc:Operation></documentation>-->
      <input message="ebs:GetCustomerAssetReqMsg"/>
      <output message="ebs:GetCustomerAssetRespMsg"/>
      <fault name="fault" message="ebs:GetCustomerAssetFaultMsg"/>
    </operation>
  </portType>
</definitions>