\timing
set search_path=pspadm;
SELECT CURRENT_TIMESTAMP;
select 'creating index on psp_entitlement_message' as status ;
create index concurrently   psp_entitlement_message_u1_2012 on pspadm.psp_entitlement_message_2012  USING BTREE (token );
create index concurrently   psp_entitlement_message_u1_2013 on pspadm.psp_entitlement_message_2013  USING BTREE (token );
create index concurrently   psp_entitlement_message_u1_2014 on pspadm.psp_entitlement_message_2014  USING BTREE (token );
create index concurrently   psp_entitlement_message_u1_2015 on pspadm.psp_entitlement_message_2015  USING BTREE (token );
create index concurrently   psp_entitlement_message_u1_2016 on pspadm.psp_entitlement_message_2016  USING BTREE (token );
create index concurrently   psp_entitlement_message_u1_2017 on pspadm.psp_entitlement_message_2017  USING BTREE (token );
create index concurrently   psp_entitlement_message_u1_2018 on pspadm.psp_entitlement_message_2018  USING BTREE (token );
create index concurrently   psp_entitlement_message_u1_2019 on pspadm.psp_entitlement_message_2019  USING BTREE (token );
create index concurrently   psp_entitlement_message_u1_2020 on pspadm.psp_entitlement_message_2020  USING BTREE (token );
create index concurrently   psp_entitlement_message_u1_2021 on pspadm.psp_entitlement_message_2021  USING BTREE (token );
create index concurrently   psp_entitlement_message_u1_2022 on pspadm.psp_entitlement_message_2022  USING BTREE (token );
create index concurrently   psp_entitlement_message_u1_2023 on pspadm.psp_entitlement_message_2023  USING BTREE (token );
create index concurrently   psp_entitlement_message_u1_2024 on pspadm.psp_entitlement_message_2024  USING BTREE (token );
create index concurrently   psp_entitlement_message_u1_2025 on pspadm.psp_entitlement_message_2025  USING BTREE (token );
create index concurrently   psp_entitlement_message_u1_2026 on pspadm.psp_entitlement_message_2026  USING BTREE (token );
create index concurrently   psp_entitlement_msg_lcno_eofcd_2012 on pspadm.psp_entitlement_message_2012  USING BTREE (license_number ,entitlement_offering_code );
create index concurrently   psp_entitlement_msg_lcno_eofcd_2013 on pspadm.psp_entitlement_message_2013  USING BTREE (license_number ,entitlement_offering_code );
create index concurrently   psp_entitlement_msg_lcno_eofcd_2014 on pspadm.psp_entitlement_message_2014  USING BTREE (license_number ,entitlement_offering_code );
create index concurrently   psp_entitlement_msg_lcno_eofcd_2015 on pspadm.psp_entitlement_message_2015  USING BTREE (license_number ,entitlement_offering_code );
create index concurrently   psp_entitlement_msg_lcno_eofcd_2016 on pspadm.psp_entitlement_message_2016  USING BTREE (license_number ,entitlement_offering_code );
create index concurrently   psp_entitlement_msg_lcno_eofcd_2017 on pspadm.psp_entitlement_message_2017  USING BTREE (license_number ,entitlement_offering_code );
create index concurrently   psp_entitlement_msg_lcno_eofcd_2018 on pspadm.psp_entitlement_message_2018  USING BTREE (license_number ,entitlement_offering_code );
create index concurrently   psp_entitlement_msg_lcno_eofcd_2019 on pspadm.psp_entitlement_message_2019  USING BTREE (license_number ,entitlement_offering_code );
create index concurrently   psp_entitlement_msg_lcno_eofcd_2020 on pspadm.psp_entitlement_message_2020  USING BTREE (license_number ,entitlement_offering_code );
create index concurrently   psp_entitlement_msg_lcno_eofcd_2021 on pspadm.psp_entitlement_message_2021  USING BTREE (license_number ,entitlement_offering_code );
create index concurrently   psp_entitlement_msg_lcno_eofcd_2022 on pspadm.psp_entitlement_message_2022  USING BTREE (license_number ,entitlement_offering_code );
create index concurrently   psp_entitlement_msg_lcno_eofcd_2023 on pspadm.psp_entitlement_message_2023  USING BTREE (license_number ,entitlement_offering_code );
create index concurrently   psp_entitlement_msg_lcno_eofcd_2024 on pspadm.psp_entitlement_message_2024  USING BTREE (license_number ,entitlement_offering_code );
create index concurrently   psp_entitlement_msg_lcno_eofcd_2025 on pspadm.psp_entitlement_message_2025  USING BTREE (license_number ,entitlement_offering_code );
create index concurrently   psp_entitlement_msg_lcno_eofcd_2026 on pspadm.psp_entitlement_message_2026  USING BTREE (license_number ,entitlement_offering_code );
create index concurrently   psp_entitlement_msg_msgts_er_2012 on pspadm.psp_entitlement_message_2012  USING BTREE (message_timestamp ,event_reason );
create index concurrently   psp_entitlement_msg_msgts_er_2013 on pspadm.psp_entitlement_message_2013  USING BTREE (message_timestamp ,event_reason );
create index concurrently   psp_entitlement_msg_msgts_er_2014 on pspadm.psp_entitlement_message_2014  USING BTREE (message_timestamp ,event_reason );
create index concurrently   psp_entitlement_msg_msgts_er_2015 on pspadm.psp_entitlement_message_2015  USING BTREE (message_timestamp ,event_reason );
create index concurrently   psp_entitlement_msg_msgts_er_2016 on pspadm.psp_entitlement_message_2016  USING BTREE (message_timestamp ,event_reason );
create index concurrently   psp_entitlement_msg_msgts_er_2017 on pspadm.psp_entitlement_message_2017  USING BTREE (message_timestamp ,event_reason );
create index concurrently   psp_entitlement_msg_msgts_er_2018 on pspadm.psp_entitlement_message_2018  USING BTREE (message_timestamp ,event_reason );
create index concurrently   psp_entitlement_msg_msgts_er_2019 on pspadm.psp_entitlement_message_2019  USING BTREE (message_timestamp ,event_reason );
create index concurrently   psp_entitlement_msg_msgts_er_2020 on pspadm.psp_entitlement_message_2020  USING BTREE (message_timestamp ,event_reason );
create index concurrently   psp_entitlement_msg_msgts_er_2021 on pspadm.psp_entitlement_message_2021  USING BTREE (message_timestamp ,event_reason );
create index concurrently   psp_entitlement_msg_msgts_er_2022 on pspadm.psp_entitlement_message_2022  USING BTREE (message_timestamp ,event_reason );
create index concurrently   psp_entitlement_msg_msgts_er_2023 on pspadm.psp_entitlement_message_2023  USING BTREE (message_timestamp ,event_reason );
create index concurrently   psp_entitlement_msg_msgts_er_2024 on pspadm.psp_entitlement_message_2024  USING BTREE (message_timestamp ,event_reason );
create index concurrently   psp_entitlement_msg_msgts_er_2025 on pspadm.psp_entitlement_message_2025  USING BTREE (message_timestamp ,event_reason );
create index concurrently   psp_entitlement_msg_msgts_er_2026 on pspadm.psp_entitlement_message_2026  USING BTREE (message_timestamp ,event_reason );
create index concurrently   psp_entitlement_msg_orno_lcno_2012 on pspadm.psp_entitlement_message_2012  USING BTREE (order_number ,license_number );
create index concurrently   psp_entitlement_msg_orno_lcno_2013 on pspadm.psp_entitlement_message_2013  USING BTREE (order_number ,license_number );
create index concurrently   psp_entitlement_msg_orno_lcno_2014 on pspadm.psp_entitlement_message_2014  USING BTREE (order_number ,license_number );
create index concurrently   psp_entitlement_msg_orno_lcno_2015 on pspadm.psp_entitlement_message_2015  USING BTREE (order_number ,license_number );
create index concurrently   psp_entitlement_msg_orno_lcno_2016 on pspadm.psp_entitlement_message_2016  USING BTREE (order_number ,license_number );
create index concurrently   psp_entitlement_msg_orno_lcno_2017 on pspadm.psp_entitlement_message_2017  USING BTREE (order_number ,license_number );
create index concurrently   psp_entitlement_msg_orno_lcno_2018 on pspadm.psp_entitlement_message_2018  USING BTREE (order_number ,license_number );
create index concurrently   psp_entitlement_msg_orno_lcno_2019 on pspadm.psp_entitlement_message_2019  USING BTREE (order_number ,license_number );
create index concurrently   psp_entitlement_msg_orno_lcno_2020 on pspadm.psp_entitlement_message_2020  USING BTREE (order_number ,license_number );
create index concurrently   psp_entitlement_msg_orno_lcno_2021 on pspadm.psp_entitlement_message_2021  USING BTREE (order_number ,license_number );
create index concurrently   psp_entitlement_msg_orno_lcno_2022 on pspadm.psp_entitlement_message_2022  USING BTREE (order_number ,license_number );
create index concurrently   psp_entitlement_msg_orno_lcno_2023 on pspadm.psp_entitlement_message_2023  USING BTREE (order_number ,license_number );
create index concurrently   psp_entitlement_msg_orno_lcno_2024 on pspadm.psp_entitlement_message_2024  USING BTREE (order_number ,license_number );
create index concurrently   psp_entitlement_msg_orno_lcno_2025 on pspadm.psp_entitlement_message_2025  USING BTREE (order_number ,license_number );
create index concurrently   psp_entitlement_msg_orno_lcno_2026 on pspadm.psp_entitlement_message_2026  USING BTREE (order_number ,license_number );

select  'psp_entitlement_message completed' as status;
SELECT CURRENT_TIMESTAMP;


create index    psp_entitlement_message_u1 ON ONLY  pspadm.psp_entitlement_message USING BTREE (token );
create index    psp_entitlement_msg_lcno_eofcd ON ONLY  pspadm.psp_entitlement_message USING BTREE (license_number ,entitlement_offering_code );
create index    psp_entitlement_msg_msgts_er ON ONLY  pspadm.psp_entitlement_message USING BTREE (message_timestamp ,event_reason  );
create index    psp_entitlement_msg_orno_lcno ON ONLY  pspadm.psp_entitlement_message USING BTREE (order_number ,license_number );
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2012 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2013 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2014 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2015 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2016 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2017 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2018 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2019 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2020 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2021 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2022 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2023 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2024 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2025 ;
alter index psp_entitlement_message_u1 attach partition  pspadm.psp_entitlement_message_u1_2026 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2012 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2013 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2014 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2015 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2016 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2017 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2018 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2019 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2020 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2021 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2022 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2023 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2024 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2025 ;
alter index psp_entitlement_msg_lcno_eofcd attach partition  pspadm.psp_entitlement_msg_lcno_eofcd_2026 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2012 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2013 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2014 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2015 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2016 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2017 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2018 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2019 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2020 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2021 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2022 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2023 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2024 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2025 ;
alter index psp_entitlement_msg_msgts_er attach partition  pspadm.psp_entitlement_msg_msgts_er_2026 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2012 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2013 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2014 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2015 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2016 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2017 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2018 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2019 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2020 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2021 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2022 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2023 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2024 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2025 ;
alter index psp_entitlement_msg_orno_lcno attach partition  pspadm.psp_entitlement_msg_orno_lcno_2026 ;

SELECT CURRENT_TIMESTAMP;