col spoolname new_value spoolname
select 'CHG0664951_drop_index'||SYS_CONTEXT('USERENV', 'DB_NAME')||'_'||to_char(sysdate,'YYMONDD_HH24.MI.SS') spoolname from dual;
spool '&spoolname'

alter session set ddl_lock_timeout=300;

drop index IDX_TxDetails_CreateUser;
drop index IDX_TxDetails_ModifyUser;
drop index IDX_TxHeaders_CreateUser;
drop index IDX_TxHeaders_ModifyUser;
alter table TxHeaders_1 drop constraint TxHeaders_CreateUser;
alter table TxHeaders_1 drop constraint TxHeaders_ModifyUser;
alter table TxDetails_1 drop constraint TxDetails_CreateUser;
alter table TxDetails_1 drop constraint TxDetails_ModifyUser;
drop index IDX_TimeActivities_CreateUser;
drop index IDX_TimeActivities_ModifyUser;
drop index IDX_TxMemorizedDetails_Creatsr;
drop index IDX_TxMemorizedDetails_Modfysr;
drop index IDX_TxMemorizedHeaders_Creatsr;
drop index IDX_TxMemorizedHeaders_Modfysr;
drop index IDX_RecurInfo_CreateUser;
drop index IDX_RecurInfo_ModifyUser;
drop index IDX_Terms_CreateUser;
drop index IDX_Terms_ModifyUser;
drop index IDX_Statements_CreateUser;
drop index IDX_Statements_ModifyUser;
drop index IDX_Items_CreateUser;
drop index IDX_Items_ModifyUser;
drop index IDX_Depts_CreateUser;
drop index IDX_Depts_ModifyUser;
drop index IDX_Klasses_CreateUser;
drop index IDX_Klasses_ModifyUser;
drop index IDX_PaymentMethods_CreateUser;
drop index IDX_PaymentMethods_ModifyUser;
drop index IDX_Employees_CreateUser;
drop index IDX_Employees_ModifyUser;
drop index IDX_Vendors_CreateUser;
drop index IDX_Vendors_ModifyUser;
drop index IDX_Customers_CreateUser;
drop index IDX_Customers_ModifyUser;
drop index IDX_Contacts_CreateUser;
drop index IDX_Contacts_ModifyUser;
drop index IDX_Accounts_CreateUser;
drop index IDX_Accounts_ModifyUser;
drop index IDX_BookkeepingActivity_Cretsr;
drop index IDX_BookkeepingActivity_Mdfysr;
alter table BookkeepingActivity_1 drop constraint BookkeepingActivity_CreateUser;
alter table BookkeepingActivity_1 drop constraint BookkeepingActivity_ModifyUser;
alter table Accounts_1 drop constraint Accounts_CreateUser;
alter table Accounts_1 drop constraint Accounts_ModifyUser;
alter table Contacts_1 drop constraint Contacts_CreateUser;
alter table Contacts_1 drop constraint Contacts_ModifyUser;
alter table Customers_1 drop constraint Customers_CreateUser;
alter table Customers_1 drop constraint Customers_ModifyUser;
alter table Vendors_1 drop constraint Vendors_CreateUser;
alter table Vendors_1 drop constraint Vendors_ModifyUser;
alter table Employees_1 drop constraint Employees_CreateUser;
alter table Employees_1 drop constraint Employees_ModifyUser;
alter table PaymentMethods_1 drop constraint PaymentMethods_CreateUser;
alter table PaymentMethods_1 drop constraint PaymentMethods_ModifyUser;
alter table Klasses_1 drop constraint Klasses_CreateUser;
alter table Klasses_1 drop constraint Klasses_ModifyUser;
alter table Depts_1 drop constraint Depts_CreateUser;
alter table Depts_1 drop constraint Depts_ModifyUser;
alter table Items_1 drop constraint Items_CreateUser;
alter table Items_1 drop constraint Items_ModifyUser;
alter table Statements_1 drop constraint Statements_CreateUser;
alter table Statements_1 drop constraint Statements_ModifyUser;
alter table Terms_1 drop constraint Terms_CreateUser;
alter table Terms_1 drop constraint Terms_ModifyUser;
alter table RecurData_1 drop constraint RecurInfo_CreateUser;
alter table RecurData_1 drop constraint RecurInfo_ModifyUser;
alter table TxMemorizedHeaders_1 drop constraint TxMemorizedHeaders_CreateUser;
alter table TxMemorizedHeaders_1 drop constraint TxMemorizedHeaders_ModifyUser;
alter table TxMemorizedDetails_1 drop constraint TxMemorizedDetails_CreateUser;
alter table TxMemorizedDetails_1 drop constraint TxMemorizedDetails_ModifyUser;
alter table TimeActivities_1 drop constraint TimeActivities_CreateUser;
alter table TimeActivities_1 drop constraint TimeActivities_ModifyUser;
drop index IDX_TxHeaders_Account;

spool off
