# $Id: Makefile,v 1.1 2007/05/05 00:22:47 jspencer Exp $
#
include $(QBNBASE)/build/rules/base.mak
include $(QBNBASE)/build/rules/salsa.mak

all:: $(DIRS) pre

pre::

JAVA_PACKAGE = com/intuit/payroll/agency/util


JAVA_SRC = \
		DateRollingPolicy.java \
		DueDateRollingPolicy.java \
		IAgencyHoliday.java \
		RulesCalendar.java

include $(QBNBASE)/build/rules/java.mak






