# $Id: Makefile,v 1.1 2007/05/05 00:22:47 jspencer Exp $
#
include $(QBNBASE)/build/rules/base.mak
include $(QBNBASE)/build/rules/salsa.mak

all:: $(DIRS) pre

pre::

JAVA_PACKAGE = com/intuit/payroll/agency/impl

JAVA_SRC = \
		Agency.java \
		AgencyHoliday.java \
		CredentialData.java \
		CredentialFormFooter.java \
		CredentialFormHeader.java \
		CredentialFormInputField.java \
		CredentialFormLogin.java \
		EfeRules.java \
		EnrollmentGroup.java \
		FormFilingFrequency.java \
		FormInfo.java \
		FormRulesInfo.java \
		FormSubmitMethod.java \
		FormTemplate.java \
		FormTemplateGroup.java \
		Frequency.java \
		IEfeRules.java \
		Jurisdiction.java \
		PaymentPeriod.java \
		PaymentPeriodRequest.java \
		PaymentReason.java \
		PaymentTemplate.java \
		RulesInfo.java \
		RulesList.java \
		RulesListFactory.java \
		SettlementDatePolicy.java \
		SettlementDateRequest.java \
		SubmitMethod.java

include $(QBNBASE)/build/rules/java.mak

