
truncate table IBOBADM_APG.GG_HEARTBEAT;                                                                                                                                                                                                                                                                    
truncate table IBOBADM_APG.GG_HEARTBEAT_SMC;                                                                                                                                                                                                                                                                
truncate table IBOBADM_APG.GG_HEARTBEAT_SST;                                                                                                                                                                                                                                                                
truncate table IBOBADM_APG.PSP_HCM401K_COMPANY_POLICY;                                                                                                                                                                                                                                                      
truncate table IBOBADM_APG.PSP_HCM401K_COMPANY_QBDT_PITEM;                                                                                                                                                                                                                                                  
truncate table IBOBADM_APG.PSP_HCM401K_EMPLOYEE_DEDUCTION;                                                                                                                                                                                                                                                  
truncate table IBOBADM_APG.PSP_HCM401K_POLICY;                                                                                                                                                                                                                                                              
truncate table IBOBADM_APG.PSP_QBDT_REQUEST_INFO;                                                                                                                                                                                                                                                           
truncate table IBOBADM_APG.PSP_SAP_METHOD_CALL;                                                                                                                                                                                                                                                             
truncate table IBOBADM_APG.PSP_SOURCE_SYSTEM_TRANSMISSION;                                                                                                                                                                                                                                                  
truncate table IBOBADM_APG.REF_TEST;                                                                                                                                                                                                                                                                        
truncate table IBOBADM_APG.TEST1;                                                                                                                                                                                                                                                                           
truncate table IBOBADM_APG.TEST2;                                                                                                                                                                                                                                                                           
Elapsed: 00:00:00.09
