DECLARE
	
	table_exists PLS_INTEGER;

BEGIN


	SELECT COUNT(*) INTO table_exists
	FROM "USER_TABLES"
	WHERE TABLE_NAME = 'TEMP_PSP_ACH_TRANSACTION_CODE';

	IF table_exists = 1 THEN
		EXECUTE IMMEDIATE 'DROP TABLE "TEMP_PSP_ACH_TRANSACTION_CODE" CASCADE CONSTRAINTS';
	END IF;

END;

/

--------------------------------------------------------
-- Create temp table                                  --
--------------------------------------------------------
CREATE TABLE TEMP_PSP_ACH_TRANSACTION_CODE
(
      "TRANSACTION_CODE" VARCHAR2(2 CHAR) NOT NULL, 
	  "VERSION"  NUMBER(19,0) NOT NULL,
	  "REALM_ID"  NUMBER(19,0) NOT NULL,  
	  "ACH_ACCOUNT_TYPE_CD" VARCHAR2(255 CHAR),  
	  "CREDIT_DEBIT_INDICATOR" VARCHAR2(255 CHAR),
	  "DESCRIPTION" VARCHAR2(150 CHAR),
	  "IS_RETURN_CODE" NUMBER(1,0) 
)

/

--------------------------------------------------------
-- Insert into temp table                             --
--------------------------------------------------------


INSERT INTO TEMP_PSP_ACH_TRANSACTION_CODE ( TRANSACTION_CODE, DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION, REALM_ID)  VALUES ( 
'21', 'Automated Return or Notification of Change for orginal transaction code 22, 23, or 24', 'Checking', 'Credit', 1, 0, -1) 
/

INSERT INTO TEMP_PSP_ACH_TRANSACTION_CODE ( TRANSACTION_CODE, DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION, REALM_ID)  VALUES ( 
'22', 'Automated Deposit', 'Checking', 'Credit', 0, 0, -1) 
/

INSERT INTO TEMP_PSP_ACH_TRANSACTION_CODE ( TRANSACTION_CODE, DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION, REALM_ID)  VALUES ( 
'26', 'Automated Return or Notification of Change for orginal transaction code 27, 28, or 29', 'Checking', 'Debit', 1, 0, -1) 
/

INSERT INTO TEMP_PSP_ACH_TRANSACTION_CODE ( TRANSACTION_CODE, DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION, REALM_ID)  VALUES ( 
'27', 'Automated Payment', 'Checking', 'Debit', 0, 0, -1) 
/

INSERT INTO TEMP_PSP_ACH_TRANSACTION_CODE ( TRANSACTION_CODE, DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION, REALM_ID)  VALUES ( 
'31', 'Automated Return or Notification of Change for orginal transaction code 32, 33, or 34', 'Savings', 'Credit', 1, 0, -1) 
/

INSERT INTO TEMP_PSP_ACH_TRANSACTION_CODE ( TRANSACTION_CODE, DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION, REALM_ID)  VALUES ( 
'32', 'Automated Deposit', 'Savings', 'Credit', 0, 0, -1) 
/

INSERT INTO TEMP_PSP_ACH_TRANSACTION_CODE ( TRANSACTION_CODE, DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION, REALM_ID)  VALUES ( 
'36', 'Automated Return or Notification of Change for orginal transaction code 37, 38, or 39', 'Savings', 'Debit', 1, 0, -1) 
/

INSERT INTO TEMP_PSP_ACH_TRANSACTION_CODE ( TRANSACTION_CODE, DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION, REALM_ID)  VALUES ( 
'37', 'Automated Payment', 'Savings', 'Debit', 0, 0, -1) 
/

INSERT INTO TEMP_PSP_ACH_TRANSACTION_CODE ( TRANSACTION_CODE, DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION, REALM_ID)  VALUES ( 
'41', 'Automated Return or Notification of Change for orginal transaction code 42, 43, or 44', 'Ledger', 'Credit', 1, 0, -1) 
/

INSERT INTO TEMP_PSP_ACH_TRANSACTION_CODE ( TRANSACTION_CODE, DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION, REALM_ID)  VALUES ( 
'42', 'Automated Deposit', 'Ledger', 'Credit', 0, 0, -1) 
/

INSERT INTO TEMP_PSP_ACH_TRANSACTION_CODE ( TRANSACTION_CODE, DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION, REALM_ID)  VALUES ( 
'46', 'Automated Return or Notification of Change for orginal transaction code 47, 48, or 49', 'Ledger', 'Debit', 1, 0, -1) 
/

INSERT INTO TEMP_PSP_ACH_TRANSACTION_CODE ( TRANSACTION_CODE, DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION, REALM_ID)  VALUES ( 
'47', 'Automated Payment', 'Ledger', 'Debit', 0, 0, -1) 
/

INSERT INTO TEMP_PSP_ACH_TRANSACTION_CODE ( TRANSACTION_CODE, DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION, REALM_ID)  VALUES ( 
'51', 'Automated Return or Notification of Change for orginal transaction code 52, 53, or 54', 'Loan', 'Credit', 1, 0, -1) 
/

INSERT INTO TEMP_PSP_ACH_TRANSACTION_CODE ( TRANSACTION_CODE, DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION, REALM_ID)  VALUES ( 
'52', 'Automated Deposit', 'Loan', 'Credit', 0, 0, -1) 
/

INSERT INTO TEMP_PSP_ACH_TRANSACTION_CODE ( TRANSACTION_CODE, DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION, REALM_ID)  VALUES ( 
'55', 'Automated Payment (Reversals Only)', 'Loan', 'Debit', 0, 0, -1) 
/

INSERT INTO TEMP_PSP_ACH_TRANSACTION_CODE ( TRANSACTION_CODE, DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION, REALM_ID)  VALUES ( 
'56', 'Automated Return or Notification of Change for orginal transaction code 55', 'Loan', 'Debit', 1, 0, -1) 
/

--------------------------------------------------------
-- Sychronize temp table and real table by            --
-- inserting, deleting, and updating as necessary     --
--------------------------------------------------------

INSERT INTO PSP_ACH_TRANSACTION_CODE
   (TRANSACTION_CODE, DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION, REALM_ID)
SELECT 
    TRANSACTION_CODE, DESCRIPTION, ACH_ACCOUNT_TYPE_CD, CREDIT_DEBIT_INDICATOR, IS_RETURN_CODE, VERSION, REALM_ID
FROM 
   TEMP_PSP_ACH_TRANSACTION_CODE tt 
WHERE 
   tt.TRANSACTION_CODE NOT IN (SELECT TRANSACTION_CODE FROM PSP_ACH_TRANSACTION_CODE)

/

DELETE FROM PSP_ACH_TRANSACTION_CODE
WHERE TRANSACTION_CODE NOT IN (SELECT TRANSACTION_CODE FROM TEMP_PSP_ACH_TRANSACTION_CODE) 

/

UPDATE PSP_ACH_TRANSACTION_CODE rt
SET ( rt.DESCRIPTION, rt.ACH_ACCOUNT_TYPE_CD, rt.CREDIT_DEBIT_INDICATOR, rt.IS_RETURN_CODE, rt.VERSION) =
(SELECT   tt.DESCRIPTION, tt.ACH_ACCOUNT_TYPE_CD, tt.CREDIT_DEBIT_INDICATOR, tt.IS_RETURN_CODE, tt.VERSION
 FROM TEMP_PSP_ACH_TRANSACTION_CODE tt WHERE tt.TRANSACTION_CODE = rt.TRANSACTION_CODE)

/


--------------------------------------------------------
-- Drop temp table                                  --
--------------------------------------------------------
DROP TABLE TEMP_PSP_ACH_TRANSACTION_CODE

/
COMMIT
