DECLARE

	table_exists PLS_INTEGER;

BEGIN


	SELECT COUNT(*) INTO table_exists
	FROM "USER_TABLES"
	WHERE TABLE_NAME = 'TEMP_PSP_SVCSTAT_SVC_ASSOC';

	IF table_exists = 1 THEN
		EXECUTE IMMEDIATE 'DROP TABLE "TEMP_PSP_SVCSTAT_SVC_ASSOC" CASCADE CONSTRAINTS';
	END IF;

END;

/

--------------------------------------------------------
-- Create temp table                                  --
--------------------------------------------------------

CREATE TABLE TEMP_PSP_SVCSTAT_SVC_ASSOC
(
  SERVICE_SUB_STATUS_FK  VARCHAR2(255 CHAR)         NOT NULL,
  SERVICE_FK         VARCHAR2(255 CHAR)         NOT NULL
)

/

--------------------------------------------------------
-- Insert into temp table                             --
--------------------------------------------------------
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('AchRejectOther', 'DirectDeposit')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('AchRejectOther', 'BillPayment')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('AchRejectOther', 'Tax')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('AchRejectR1R9', 'DirectDeposit')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('AchRejectR1R9', 'BillPayment')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('AchRejectR1R9', 'Tax')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('ActiveCurrent', 'DirectDeposit')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('ActiveCurrent', 'ThirdParty401k')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('ActiveCurrent', 'BillPayment')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('ActiveCurrent', 'Tax')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('ActiveCurrent', 'Cloud')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('ActiveSeasonal', 'Tax')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('AuditCorrections', 'Tax')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('AS400Hold', 'Tax')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('AS400DirectDepositLimitHold', 'Tax')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('Cancelled', 'DirectDeposit')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('Cancelled', 'ThirdParty401k')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('Cancelled', 'BillPayment')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('Cancelled', 'Tax')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('BillPaymentLimit', 'BillPayment')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('DirectDepositLimit', 'DirectDeposit')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('DirectDepositLimit', 'BillPayment')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('Fraud', 'DirectDeposit')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('Fraud', 'BillPayment')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('Fraud', 'Tax')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('AMLHold', 'DirectDeposit')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('AMLHold', 'BillPayment')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('AMLHold', 'Tax')
/
-- INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('Fraud', 'Cloud')
-- /
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('FraudReview', 'DirectDeposit')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('FraudReview', 'BillPayment')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('FraudReview', 'Tax')
/
--  FraudReview does not apply to Cloud services.
--INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('FraudReview', 'Cloud')
--/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('IntuitCollections', 'DirectDeposit')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('IntuitCollections', 'BillPayment')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('IntuitCollections', 'Tax')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('MissingPaperwork', 'Tax')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('PendingBalanceFile', 'Tax')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('PendingSetup', 'Tax')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('PendingEnrollment', 'Tax')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('PendingTaxAcceptance', 'Tax')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('PendingBankVerification', 'DirectDeposit')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('PendingBankVerification', 'Tax')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('PendingFirstPayroll', 'DirectDeposit')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('PendingFirstPayroll', 'ThirdParty401k')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('PendingFirstPayroll', 'Tax')
/
--INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('PendingFirstPayroll', 'Cloud')
--/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('PendingPinCreation', 'DirectDeposit')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('PendingPinCreation', 'Tax')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('PendingPinCreation', 'ThirdParty401k')
/
--INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('PendingPinCreation', 'Cloud')
--/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('PendingPrefundingWire', 'DirectDeposit')
/
--PrefundingWire for Assisted is not implemented, once we implement we can add this back
-- INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('PendingPrefundingWire', 'Tax')
-- /
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('PendingTermination', 'DirectDeposit')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('PendingTermination', 'Tax')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('RiskAssessment', 'DirectDeposit')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('RiskAssessment', 'Tax')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('RiskCollections', 'DirectDeposit')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('RiskCollections', 'BillPayment')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('RiskCollections', 'Tax')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('SuspendedDirectDeposit', 'DirectDeposit')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('Terminated', 'DirectDeposit')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('Terminated', 'Tax')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('Terminated', 'BillPayment')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('Terminated', 'Cloud')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('Cancelled', 'Cloud')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('MTLHold', 'DirectDeposit')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('Cancelled', 'CloudV3')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('ActiveCurrent', 'CloudV3')
/
INSERT INTO TEMP_PSP_SVCSTAT_SVC_ASSOC ( SERVICE_SUB_STATUS_FK, SERVICE_FK)  VALUES ('Terminated', 'CloudV3')
/

--------------------------------------------------------
-- Sychronize temp table and real table by            --
-- inserting, deleting, and updating as necessary     --
--------------------------------------------------------

INSERT INTO PSP_SVCSTAT_SVC_ASSOC
   (SERVICE_SUB_STATUS_FK, SERVICE_FK)
SELECT
    SERVICE_SUB_STATUS_FK, SERVICE_FK
FROM
   TEMP_PSP_SVCSTAT_SVC_ASSOC sc
WHERE
   (sc.SERVICE_SUB_STATUS_FK, sc.SERVICE_FK) NOT IN (SELECT SERVICE_SUB_STATUS_FK, SERVICE_FK FROM PSP_SVCSTAT_SVC_ASSOC)

/
DELETE FROM PSP_SVCSTAT_SVC_ASSOC
WHERE (SERVICE_SUB_STATUS_FK, SERVICE_FK) NOT IN (SELECT SERVICE_SUB_STATUS_FK, SERVICE_FK FROM TEMP_PSP_SVCSTAT_SVC_ASSOC)

/

--------------------------------------------------------
-- Drop temp table                                  --
--------------------------------------------------------
DROP TABLE TEMP_PSP_SVCSTAT_SVC_ASSOC

/
COMMIT



