DECLARE

	table_exists PLS_INTEGER;

BEGIN


	SELECT COUNT(*) INTO table_exists
	FROM "USER_TABLES"
	WHERE TABLE_NAME = 'TEMP_PSP_BANK_ACCOUNT';

	IF table_exists = 1 THEN
		EXECUTE IMMEDIATE 'DROP TABLE "TEMP_PSP_BANK_ACCOUNT" CASCADE CONSTRAINTS';
	END IF;

END;

/

--------------------------------------------------------
-- Create temp table                                  --
--------------------------------------------------------

CREATE TABLE TEMP_PSP_BANK_ACCOUNT
(
	"BANK_ACCOUNT_SEQ" VARCHAR2(255 CHAR) NOT NULL,
	"VERSION" NUMBER(19,0) NOT NULL,
	"CREATED_DATE" TIMESTAMP NOT NULL,
	"MODIFIED_DATE" TIMESTAMP NOT NULL,
	"ACCOUNT_NUMBER_ENC" VARCHAR2(4000 CHAR),
	"ACCOUNT_TYPE_CD" VARCHAR2(4000 CHAR),
	"A_C_H_ACCOUNT_TYPE_CD" VARCHAR2(4000 CHAR),
	"BANK_NAME" VARCHAR2(4000 CHAR),
	"EFFECTIVE_DATE" TIMESTAMP,
	"EXPIRATION_DATE" TIMESTAMP,
	"ROUTING_NUMBER" VARCHAR2(4000 CHAR),
    "CREATOR_ID"       VARCHAR2(255 CHAR)
)

/

--------------------------------------------------------
-- Adding new account_number_enc values               --
--------------------------------------------------------
-- DECODE(FN_GET_ENV(),'PROD',<account_number encrypted with prod key>,<account_number encrypted with preprod key>)
-- EXAMPLE :
-- DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACGNpcGt6Tzc3R4poiFDNR0O5TO6txAnbZJ/P2waC+ynBDw==','2gIAAAASAQAEAAAAAgIACHVGWHhPQldQ/T59B2ceS5Ys8QleT2aXlnW7/p0Y3OKPgg==')

--------------------------------------------------------
-- Insert into temp table                             --
--------------------------------------------------------

INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID ) VALUES (
'a5263743-7cf0-42fc-b164-25ea68315756',0, SYSDATE, SYSDATE, 'Checking', 'Checking', 'JP MORGAN CHASE', '111000614', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACGNpcGt6Tzc3R4poiFDNR0O5TO6txAnbZJ/P2waC+ynBDw==','2gIAAAASAQAEAAAAAgIACHVGWHhPQldQ/T59B2ceS5Ys8QleT2aXlnW7/p0Y3OKPgg=='), NULL, NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID ) VALUES (
'a62f39f9-3aab-48ac-ace7-3ab8f700abb9',0, SYSDATE, SYSDATE, 'Checking', 'Checking', 'JP MORGAN CHASE', '111000614', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACDRWdXlrSlNp5X831lieXNtaHeCnLlqGmdX8Lx2dkBxnmw==','2gIAAAASAQAEAAAAAgIACHFSdC92VHE34xJAzEH/lJ4GsLv+iGLSkSuEC0wEYQKknQ=='), NULL, NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID ) VALUES (
'89057491-baf0-49dd-bbda-a5c5eff5a7d9',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '111000614', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACFJHUUZCcm1WO80E63rpH7WVlmquGddIlGiJM7e5fF0HBA==','2gIAAAASAQAEAAAAAgIACC9EdVN5N0gxipZ+YW3sLiyhou1nKg4S7fs2CFOWSD1bOw=='), NULL, NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID ) VALUES (
'3b76af25-eb67-4409-a559-225a85eee4b9',0, SYSDATE, SYSDATE, 'Checking', 'Checking', 'JP MORGAN CHASE', '111000614', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACCtsREJVL2Rs291ek1Yh8RZrPknAJsYFmpjahmAKhFF/qg==','2gIAAAASAQAEAAAAAgIACFZFbUFtdHhtgwaZ9heigTh9ltV4g8O79zp8yALSrwRg8w=='), NULL, NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID ) VALUES (
'3b76af25-eb68-4409-a559-225a85eee4b9',0, SYSDATE, SYSDATE, 'Checking', 'Checking', 'JP MORGAN CHASE', '021000021', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACGdUU0ZFaGtmB3w2i31OVeVf/TsRDF8XOGrX1j/hoNB54w==','2gIAAAASAQAEAAAAAgIACEpKVVVYVlowy6hdJa/y/aMKpGGNB9Cp2yyJSofi083vGg=='), NULL, NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID ) VALUES (
'3b76af25-eb69-4409-a559-225a85eee4b9',0, SYSDATE, SYSDATE, 'Checking', 'Checking', 'JP MORGAN CHASE', '021309379', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACDdXWkcxeUlFbLBELNmRp4LpIsF9/8qkwxTVWufj6RtM0g==','2gIAAAASAQAEAAAAAgIACDNPeEZlcW5H2rLthBswWGyTmbIvJAhBiIPVH+d8kxLFOg=='), NULL, NULL,'System')
/

-----------------------------------------------------------------------------------------------------------------
-- Inserting bank accounts for ACH Payments
-- *** DO NOT MAKE CHANGES TO BANK ACCOUNTS!  Create new bank accounts and new PaymentTemplateBankAccounts ***
-----------------------------------------------------------------------------------------------------------------

INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157567',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '091000022', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACHdtUTZKRXB28AjtAPL2RAU+ZTARATZEFYtYX2i/Q9mBvO9UUA==','2gIAAAASAQAEAAAAAgIACDBJM3F0bUZUgn3C1UEdk82w7Li73QIm4f4reTAIOFsakpT19g=='), NULL, NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157568',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '091000022', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACDZEQXd1L3Yyh6aSGqj50JWfLqDNpKWgKJMgeuGxAxJuj9MSCA==','2gIAAAASAQAEAAAAAgIACE00REZubXVn/6GCoIFoEy65bbWw5dE+P0uiuQqwQ/kL7jic/w=='), NULL, NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157569',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '052001633', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACGoyVHg5NnlGBSlW3cTkCz5TOxhy1bGPhvQ78vmQtb6W1C4=','2gIAAAASAQAEAAAAAgIACGRHZjhDc2JNP3+el76TEPrEoQtSdzXUIHBOts2JsXanrdY='), NULL, NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315756a',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'Citi Bank', '021000089', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACCtIdlVCZGZRVkw1kNA/LcKQuzsLhTvKKS2BZXFBudQl','2gIAAAASAQAEAAAAAgIACG10RFFVdFVrR2MsheNyqm56VhkqqM39OtTNpeu2gx91'), NULL, NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315756b',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '031100209', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACEtaSXZNNnNsJ3SX0Js4gd2Y2ZKXPJMCWsf/tEFKTH8v','2gIAAAASAQAEAAAAAgIACEhLeENMTG1Iv0UDkdNSCPs7PFm4FPZd9wNjk8XiMXVf'), NULL, NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315756e',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '021052053', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACElwWnk4ejM0Y8PDzXoFkMtBUCdY7fSAfZ3IH5BQr8Lx','2gIAAAASAQAEAAAAAgIACHpNRHBNemdW61e04sqd27vSlWjTePv7vHavvbS6aD5/'), NULL, NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315756f',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '021052053', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACHJ2dXBHVUd2KEbrcGXR2HtEriPYOQqihFsA4Q2GWOoG','2gIAAAASAQAEAAAAAgIACEI5aUprRzJKw4i3BbWMxrmo6KaB9FceSneUMlwSNdnf'), NULL, NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'33e4fff0-3595-4d66-9150-06ddb79c2f60',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'US BANK', '021052053', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACGdGYUkzMEorSjWxnvsi1i92VeIhaVEBXxNC+n68o1fm','2gIAAAASAQAEAAAAAgIACHFzdEhSa0pp5FLkSqwtQvj5x4I01jEOuAZx2U+9U5yj'), NULL, NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157571',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '065400137', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACFFGRzFtMnBTD4X/DY+DmvN+1GsVsNIWwJ5cSiwTgvlVGn8=','2gIAAAASAQAEAAAAAgIACHFndmMxRW1Oikvc4opm1ti/rnFMmr0EsRrpoaSxNgNz5gU='), NULL, NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157573',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '082000073', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACEM0aHQ1Y0hVMSKNm10FQbyIxQ197nxB446ALg+eXOt5M8g=','2gIAAAASAQAEAAAAAgIACE41MXVYNGtmYEvVyPvmnzNl/oDuMOkEi7oQY5tlEor5Vjg='), NULL, NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157575',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '102001017', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACDZFZDRkYytaBYbr60WKNRDP6EtqDIQAknajJD+7GJPQwAQ=','2gIAAAASAQAEAAAAAgIACFFDRlpKdjBoBnNaq9TiRIuHKcTXXC6+3LEx0R9sJ5Btz8Y='), NULL, NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ,VERSION,CREATED_DATE,MODIFIED_DATE,ACCOUNT_TYPE_CD,A_C_H_ACCOUNT_TYPE_CD,BANK_NAME,ROUTING_NUMBER,ACCOUNT_NUMBER_ENC,EFFECTIVE_DATE,EXPIRATION_DATE,CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157577',0, SYSDATE, SYSDATE,'Checking','Checking','JP MORGAN CHASE','121000248', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACEtFZ29wcmIzspKWJqoSW1iRQ8sxvSJglKXDorL4ErUAnPw=','2gIAAAASAQAEAAAAAgIACDM5Z2o3YndP6UNLn49Qdl3he1WsGcWMylZa/LnE9GEcq9g='),NULL,NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157578',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '071109338', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACEJEeCtxMUU0oQ/d8utq5Nx2ot5z5TxGilRMV8Dlfg==','2gIAAAASAQAEAAAAAgIACHJ0MWE5RG11Sn7OVYEdadQPKlKs5emYccLVBU/S9Q=='), NULL, NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157579',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '123206707', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACFJVUjYzdmU4957CEgD+u22vIKCHCntOsvJRuDLqE2QliIQ=','2gIAAAASAQAEAAAAAgIACHZaQ1pOajRO7lZ3VzBILBAlKL5D4CcsJ+nJKZoZ3Ec94To='), NULL, NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315757a',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '043000096', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACCtaSm1iQ1F0Z32W0okENbu0XXjbOp+yd8DoyBn9o0btCQY=','2gIAAAASAQAEAAAAAgIACG1HRG1XaENmJPFbmASqTWYbUPxtvk3JO3T/GVSGaT2m4m0='), NULL, NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315757b',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '021000021', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACFBRVWlTLzVPgSXN5uAAgb5rLlHh3xkQYMHK/YGSxOAlnQ==','2gIAAAASAQAEAAAAAgIACHFqWTZWQUpmabCsNMpnT8ZWvkxhosMQLbuCBh/SMGOKKA=='), NULL, NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315757c',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '021000021', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACHl2Tm9KUjJN8uD9zCpB9CNP4Pa2WNff8tFt4B3JdlSTTw==','2gIAAAASAQAEAAAAAgIACE0rZmFqQ3Jy8twjUFmI7LL1JXmGTCKcLT7STpxUx2tdBQ=='), NULL, NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'e0a70827-e95d-4684-b857-11ea7d0d6dd2',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '121000248', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACFlVZ0E2V3VD2mcdVzXkxtLFfyjUJPtDyWJsLegSc+hM/Es=','2gIAAAASAQAEAAAAAgIACDFGT25CeWxnfiWo4WUdvh0QrpW/qAO4VLUzxs64d54VCew='), NULL, NULL,'System')
/
Insert into TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ,VERSION,CREATED_DATE,MODIFIED_DATE,ACCOUNT_TYPE_CD,A_C_H_ACCOUNT_TYPE_CD,BANK_NAME,ROUTING_NUMBER,ACCOUNT_NUMBER_ENC,EFFECTIVE_DATE,EXPIRATION_DATE,CREATOR_ID) values (
'e0a70827-e95d-4684-b857-11ea7d0d6dd3',0, SYSDATE, SYSDATE,'Checking','Checking','JP MORGAN CHASE','121000248', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACC9FSGxPemRzIQgePoX+B8bznQz8h4UnLThWML3b0iQdSPU=','2gIAAAASAQAEAAAAAgIACEs1OTZYdlZmTRubUDvR8vrcDjNNQoTHJIM4pJOTZFS53ZA='),NULL,NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315757d',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '061000227', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACHgrWmFicWZBkM7CqLGS9gC7HIEbAi89H7nEP4rwjf4jsuX1iaA=','2gIAAAASAQAEAAAAAgIACHgxNHVxd2N33enwaBQ268+yEp/BLwOdHFwiIziHKn1ffj8IsR0='), NULL, NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315757e',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '121000248', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACHdHOW1PRWxxxALDfh2366rgbWlgSkr6CArZcCrbZiMLdAs=','2gIAAAASAQAEAAAAAgIACFBiajlENFQ2jbZM1a3/ODm6CeXuflL5zwPCpG1tlJWRm20='), NULL, NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315757f',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '011000206', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACFpHUGVjN1J5zYaJsQXYo/jBsWkor7Xku6gzvIa2z+Rauw==','2gIAAAASAQAEAAAAAgIACGlWMVpIZ2t3GXT6PFMP4+vNAcZXy6qzaRZsd4ul/vD6Ig=='), NULL, NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157580',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '011000138', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACHRJZTJwNGEzoWEDcWRDw/fYT+1JVrEEUjQ4VHi5oSjNjDaLOg==','2gIAAAASAQAEAAAAAgIACFduZzJ3dThKhKUK2xq89JZYaTVTZUn36YCppX23nODWJMO+Yw=='), NULL, NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157581',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '086507174', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACDNVeGIzWUdXhXs8a8BJ4/JtYgspUleOUZKrJ+xPBco=','2gIAAAASAQAEAAAAAgIACDI1VjBGUlJRk45GDw8rvTa4d+9cdUSHPDb2e2ZkAiI='), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157582',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '072000326', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACEZlTW1TMTFGoB5o7PiPF4Z0R+qjVEDxnW+trG6NREs=','2gIAAAASAQAEAAAAAgIACFArc0xycVBM+uvwtmWzTq/boz8E+TG0toa3qxdGzjQ='), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'e0a70827-e95d-4684-b857-11ea7d0d6dd1',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '072000326', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACFhaRGxlbVVKgcFFEmI2jxDp/8N7auqJvKwRiXlJggNoyw==','2gIAAAASAQAEAAAAAgIACGtkdWxvWThFMlfn88RtPEFFqq4LWFKWZv+VW/ERd8Bs8Q=='), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157583',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '075000022', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACEU3SytabkRhgfdqsI3NxaRhKC429DTL1OA9leWZgsXI3g==','2gIAAAASAQAEAAAAAgIACDdVbHUzUUUvKVR41aixdS56Lya7u+7i35PvwHskM8I7ng=='), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157584',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '075000022', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACFg2UWVmMFBMKIpZhSulI5AbUUfTqtw8G1gtBEohb+ialw==','2gIAAAASAQAEAAAAAgIACGdTaExibFhoMYNo2RouvtIMA7LKb1xbntl0FGKKwS0atQ=='), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157585',1, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '121000248', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACDVFQlEzYWFjdvrf1uZ1bdGLH9eV8Evu3kEBgEyrejEjgUEtZ28=','2gIAAAASAQAEAAAAAgIACFhuNEFaSjVQt6cwyNRb4TVk9wuukpLM/lwEtosmv5CLA2ZYD50='), NULL, SYSDATE, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157586',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '053000196', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACHhZcUhqRURzgNP9gl5fPTQycG6d/AQniTo+0Vh/yI007EtZpQ==','2gIAAAASAQAEAAAAAgIACE5PUmF5SWNIcEJ9MgLDRJswhOdbSQ/CHRaGBngVjKZQYo91JA=='), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157587',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '053207766', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACDhyNTA1dGxxrkO0AwxEeJ5R1GBgXYH5uebrqVEQ3Y1pHVmdzkw=','2gIAAAASAQAEAAAAAgIACEtlWU5jZXVk1VHydcvW1TfXzU0e8paxrusbr6tfPPY6Zbky7Gg='), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157588',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '051000020', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACEF4YjE4RlY0WglV2bhWIaByUAHvOfwFEagDH83zfy2amg==','2gIAAAASAQAEAAAAAgIACFdaem9IcDdnB8JkC+VMkCR2afkpD6+1Tsbk2u45Vk197A=='), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157589',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '041001039', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACFQvLzNrc2g3fomaD7T6yVRGSe749jcEiVsL4uQJb+J9gN9/mg==','2gIAAAASAQAEAAAAAgIACDJGOUtEZW5l+rVDKs49AWN5iCZyrOVKTVJ6ae5REpGfhzcH4w=='), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315758a',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '122101706', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACFNwWlJZT2FOfwWaG6Nw9W68vizD0mXsRrqD9O0bZbDkkg==','2gIAAAASAQAEAAAAAgIACExIbFRZTTIzNgfJN1eW12pxHQvCY1G7JplEdGv0eGbWzQ=='), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315758b',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '122101706', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACEI4N0kyU0ZRYUeOUDuCCMbLd/I+VTD2x/g8JzDIS6Nm6pTDxA==','2gIAAAASAQAEAAAAAgIACHdWQ3pyMkYz0xSDOPcRJOeBe7PGpL3ejXdax8KOblAcMAo68g=='), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315758c',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '113000609', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACEM2QTZwMldZHABSC1EfrizQ2uWNXe1IlHI5274yNVnglFcv','2gIAAAASAQAEAAAAAgIACHIySGdTVitYv6kXnpRgRdcWoTP8Apxt9+mey6XDxwjVOeIZ'), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315758d',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '103000648', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACFZOTU1ta3VrHPHHPm3cKCwdlFoXDGV4tZBgluQYFAON9Q==','2gIAAAASAQAEAAAAAgIACG9Zbzh2TGdpo/4RqmqPA0m3EYa+Nxh+H+Q7DQAFhaTCIw=='), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315758e',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '062001186', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACGFMMktLUm9iSxh/00cPhUkxefSGby5dihoHnlts+Jv0','2gIAAAASAQAEAAAAAgIACEhkNmhQelhjFB2d8bbanjsGbrwhzmeoWa0yvTbYXeoQ'), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315758f',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '062000019', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACEgwcDI3b3ZmUiiY2eOQ8Q1lZ7TxhfH4zUlmBTvnD8XZ','2gIAAAASAQAEAAAAAgIACGpTM2htdG5zOshmRfb3j2VcTHPG1BJ5hNdBRxov+6VB'), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157590',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '083000137', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACEJkQnQ5K0NK+ubXrkmpeg3q3Q5a9B7kL0jFPNdEFwbgYQ==','2gIAAAASAQAEAAAAAgIACElSTytRQXh2NQjPFF9VTveYdKX0Z4EDbu0bKzaKIlzxXg=='), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157591',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '011900445', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACFFqL1NpSXNmsTh+zAmnpN8N0+jdkrKQ9nX2TQdIcHFC','2gIAAAASAQAEAAAAAgIACEdFRGJ1bjdyZaZ7BsuaLqLQpqfoB+BrZQUejDwfJ+QT'), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157592',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '121000248', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACHVIbWVwV1R1zB//8N79d4fV0mX8hV3NXslDtLndwJANhCE=','2gIAAAASAQAEAAAAAgIACHlJbmNkd1V3Gje/fLZYGhNGc8/j/c3naCXx5ks//128YqI='), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157593',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '121000248', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACHVIbWVwV1R1zB//8N79d4fV0mX8hV3NXslDtLndwJANhCE=','2gIAAAASAQAEAAAAAgIACHlJbmNkd1V3Gje/fLZYGhNGc8/j/c3naCXx5ks//128YqI='), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157594',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '021052053', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACG9mTjFNZ1B2qknAFmKaNC3xD5OQhjXBSYOhUFVPQRiw','2gIAAAASAQAEAAAAAgIACHQxUTNXbXUwyXlSBh1ZgQcvh2BkVLjP1mFvv5jXGPJL'), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157595',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '021052053', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACHQyZDVyaXdjpuw0Ceng3MnCyXv/oIPS2/QDEjBzsRrF','2gIAAAASAQAEAAAAAgIACHVVUW5hK3Vy5bTwD3Ao/P3dQGnSWjEV5AKYfb0LYIgH'), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157596',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '121301015', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACGRJbkplNHdy5VOMxLYyFdu8DEVRa5Dc1Db9CXUOySEv','2gIAAAASAQAEAAAAAgIACDVOb1NiMHN5ghp7kP3mPz7lpReWmS0Aj/JvM50rKjv6'), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157597',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '073000228', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACFdHalFwZThMSexPVw/v1WRBXPymsumhBhNpQHisWCq7Mfk=','2gIAAAASAQAEAAAAAgIACDRuQ3VjRmQvcTbkJ6OX1GpIQhaUENyqqZarBCxkiPPBSTQ='), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157598',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '121000248', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACEs4NGRITWhWrdTAenYhAwKcYop2WcbgYEohxkCwgnedjxE=','2gIAAAASAQAEAAAAAgIACFdwVi9oaHBnJbmuEZj/Pj89NwNm0kYlxqjphartdSUF9S4='), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157599',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '011600033', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACGZ3SEN2VmY3gFWqnlWAyaQjK2m/Sh5I+lIQVvX4aZKJ1zQ=','2gIAAAASAQAEAAAAAgIACDcwSnNRR252bd6THn2s2awtqFdw+qsWSlR+mg3vF+/YZR4='), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315759a',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '121000248', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACFY2b0FJWktaMyv/ALxwBWsnL7rViU+9dftzWCjnE+OhTCY=','2gIAAAASAQAEAAAAAgIACDF5SXM4QnJZ3aOscekFhX3HKNV1YaWJctjIsUWoQY4VtsU='), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315759b',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '121000248', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACDhPaWNrK3BjtwIeKTnZXSHKYB23NM1O8anj6Yn4LjFKZ0I=','2gIAAAASAQAEAAAAAgIACEJ2UjZOTWtDvIx6359Q8lPTVGLJfm6JiJLB0t2meojxyiA='), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315759c',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '101101154', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACEtoVkZEcDZIdfqQ/kgpKz0uIhNwMH121b5/2Pnw5Weah/E=','2gIAAAASAQAEAAAAAgIACCt4bEM3QTRXmWHFsX+2s6HR5imIZd97l6vtO9kAsolN/a0='), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315759d',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '101000695', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACGZrTHZEU0gwQOulzoBEK7jsh2EmnqWV5y2GLkV0eZhsBv0=','2gIAAAASAQAEAAAAAgIACFJibU9HblhOqR3dJsPvyzHUjJh1Ste8ie3L9CF72fFLJKQ='), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315759e',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '211170101', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACEZxR3VkM3Rn6PFeIPkbyOB/RHeCn79ku55yfkkxsJrJGQs=','2gIAAAASAQAEAAAAAgIACDI4ZGtNeVlSbJ1AdncIxAyGpPyzU/rw5MDWUaGTCUD6ia8='), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea8315759f',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '092900383', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACFc2WUYxV0ZvQuXBTxXAuD6Qzf/HpxcAu18z8y7gE5jNdWdmqyPTQw==','2gIAAAASAQAEAAAAAgIACDVGTFZ6V25v4mAKdc/7zvBNB6bjtIiR6dEaIxZjHdTQJBMPDmEfSg=='), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea831575a0',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'WELLS FARGO', '121000248', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACDd0dlpBRjZY1VEcOWkvG6Qf8bN1A2CE/XtE58sp4nqtGn//FWicqLB/','2gIAAAASAQAEAAAAAgIACHlNVk5yVDB6awa6PxY1Q6xImYlRPSsuHBuoOO5zcMieT9si80gOqSRO'), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea831575a1',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '091300285', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACFhhSWxNQkVGXN2JcQGMW/19VqIq5tn+61+ZQScKZ0s=','2gIAAAASAQAEAAAAAgIACDBBeWw0ZXN2LeASv9XTWSyERSsnZQkwiU2fN0upvLc='), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea831575a2',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '091300285', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACE9xR2d6RXovrl735KJm39AogE4YkyaxjoWu4Ly7Mg==','2gIAAAASAQAEAAAAAgIACHJmcThFRGtBEH4CA9RUn1HmNa22LaV3hRvgwUdD8Q=='), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea831575a3',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '031000037', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACC84SmNjVG01Fnn/+OsuIWf/l9dTnknpTY0Rp3t/bUI=','2gIAAAASAQAEAAAAAgIACDFNS3RwRWk0JWLJ+OP5WaQTiE9BSmbzrdfSqZ/aW5o='), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea831575a4',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '063100277', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACCs3Umd1OGFBa+m6zUtUPpbN4z64Etc0ygGITApBNEBoV/k=','2gIAAAASAQAEAAAAAgIACC9nM3FBNFNvgh/56+V+ipD4xqLaC8oRT0x8J1Y7cNFKR/M='), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea831575a5',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '121000248', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACEQraW16enBCUevbWBgfEQ2+b4lLIT5dsFc6Rvw3ygHet038rTI=','2gIAAAASAQAEAAAAAgIACERkMmcyQXEyD7nwVaeYQBqeUlQlfj7XRlMrT18S0TQhJTUx1mU='), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea831575a6',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '051904634', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACE5oenFERVNz/i6e7YhehESZnzDYteMNYq6wKgleOKlm','2gIAAAASAQAEAAAAAgIACEwxUWRUUE5XuZsAOuViIfEKwLuVe3zenF2nF3kbBinA'), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea831575a7',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '064000020', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACEtKNjljNkF4D3hewJwErekGnanpYDh7PWuy9fbE7iIulVZTDw==','2gIAAAASAQAEAAAAAgIACDIySUVsNDhDuHpxHwwa+SI/IifBrfcJ/q/TaOFEsWxOoSp5BA=='), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea831575a8',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'BANK ONE', '065400137', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACDFoVFRNbUprAFHgc5+XJn1WR1Jqb7LyDAFBN4kYV325eg==','2gIAAAASAQAEAAAAAgIACHRxdmg1ckd2nvGiBKOcBc3PJqGkJHcDfulnS8WIThEJ0w=='), NULL, NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea831575a9',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'Regions', '065305436', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACFZCVk14RkY2158jcL4KZ/Naeb3Ndz8DCeh+1kkd9/gO6wI=','2gIAAAASAQAEAAAAAgIACFRodmx6TEw0wwqKir2ZwE2EwnX15SCOpJP6T7Hxx005VgI='), NULL, NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'e0a70827-e95d-4684-b857-11ea7d0d6dc8',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'PNC Bank', '043000096', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACHViTS9Mcjhk3PiwEptr/JxD/Ytdym8zdB3ENYN8yEgjcmA=','2gIAAAASAQAEAAAAAgIACEpQMTRXNUZ1jKquGq0e1S72vXpU5qQWdMPh2bPSpX9ELDI='), NULL, NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'e0a70827-e95d-4684-b857-11ea7d0d6dc9',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'Bank of America', '021052053', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACEMzcnVsQnVsRtoFXk4Tlpnmh2u/DpmRIDJ/4VsbZEpe','2gIAAAASAQAEAAAAAgIACFB0WkJIRjZ1ClayMoNSFz70VqOPulBHXSgEGRGVsggN'), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'e0a70827-e95d-4684-b857-11ea7d0d6dd0',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'Bank of America', '121000248', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACEFncmp3eklPDs/03Y9qIvQtrk7lYaci9gNMSlV2zWXGjvt3bR2NPMWK','2gIAAAASAQAEAAAAAgIACHJjMHBBL0owkwsjIBovsmkUxFocdoN1iga7B42gGlrHTXILWo8+g1Z1'), NULL, NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea831575ff',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'US BANK', '123103729', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACDJLZUpMT2N0p31/zLod8NTna8ej0dsvYg9iDrYqJZeu6cpcsg==','2gIAAAASAQAEAAAAAgIACEg4Z2tYaDIrweYTnC2/n7N0cJ9xDuA52se6QdM/QHNHHhQowQ=='), NULL, NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157600',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'UNION BANK', '122000496', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACFJTc2dqd2h3zOuG7LxIG3GK8jQxiPiNq0Tf0PLpcT0UaSI=','2gIAAAASAQAEAAAAAgIACGt6V2hXbG95KijfhczI3xvnd5B/6M5Gfa8KBa/bslPmJnI='), NULL, NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b164-25ea83157601',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'WELLS FARGO BANK', '121000248', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACFlPZlZ3R1ErVgz9rgdEBaJ7Z/HFEsdDHXtgVqB5YbhfJtg=','2gIAAAASAQAEAAAAAgIACExhSTVHR1hxJkp5nqbKZu0wQti0WiqxXEPY4ziXrB4yXbY='), NULL, NULL,'System')
/
Insert into TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ,VERSION,CREATED_DATE,MODIFIED_DATE,ACCOUNT_TYPE_CD,A_C_H_ACCOUNT_TYPE_CD,BANK_NAME,ROUTING_NUMBER,ACCOUNT_NUMBER_ENC,EFFECTIVE_DATE,EXPIRATION_DATE,CREATOR_ID) values (
'33b17266-6d6d-4dfb-83cd-93511f52c1f1',0,SYSDATE, SYSDATE,'Checking','Checking','JP MORGAN CHASE','111000614', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACExsTy9kZ25ZO5iOY7UpVAM5uvCD4lG7v+EBbXARDqMdnzfV','2gIAAAASAQAEAAAAAgIACDFrS09hTHBPBwQwGzef53WAciJw0qjJiJpvDDt/7RHNhUyp'),null,null,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'347cccb9-8d41-4bd4-9a1e-a20401b20909',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'CHITTENDEN', '011600062', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACGhpMDdSTithV4Zx8QS3F9W/Pp2I+Q2pecLuBHnczhwC','2gIAAAASAQAEAAAAAgIACEw5UG5uWmZT6Q7gmiPrkmA6yD8a9T3WH1h8ZcgUsUDS'), NULL, NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852d71d0303',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'BB&T', '061113415', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACExML05HdjNN5YZW+grz6cng//4hacSy4tJ+cO3SlLmm2VnHGms=','2gIAAAASAQAEAAAAAgIACG04OE45MUQxQ5Ia4bIAaMS75+SKgXaO34YAerAzjayHWuH8Vgc='), NULL, NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-c164-25ea8315756a',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'Wells Fargo', '121000248', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACGNBWndJckhUOEUZr9djeaGFcJZX7fz8rTv9lVVZKlH47X0=','2gIAAAASAQAEAAAAAgIACGMvcTJtWGpG9im09Gqf6i5OoijuWB6/95YlHfG/VFbmTms='), NULL, NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-c164-25ea83157592',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'CITIBANK NA', '031100209', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACGE4V2c2V3RMgGDxlsV0AN/XlOrYmw5CIAItvC9shoC8','2gIAAAASAQAEAAAAAgIACGtONmYrVzN3OA7FaBOSvO9G/IsNuNPvomDqOwqyGm6r'), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-c164-25ea83157593',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'CITIBANK NA', '031100209', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACGE4V2c2V3RMgGDxlsV0AN/XlOrYmw5CIAItvC9shoC8','2gIAAAASAQAEAAAAAgIACGtONmYrVzN3OA7FaBOSvO9G/IsNuNPvomDqOwqyGm6r'), NULL, NULL, 'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852e71d0303',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'People''s United Bank', '221172186', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAQIACEFlNUxYZWMwZmovJI6YHQQlp8eR3rhEH6d0GBauG1uqeWg=','2gIAAAASAQAEAAAAAgIACDB4MXJYMS84ah5ePed00bXUWeWaY8oIsbLCWulvXOSx35o='), NULL, NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852e71d0313',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'US Bank NA', '123000848', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAgIACFJjL2dIL0xYeTXIRc7yj1oTeVBXXXIuaTq1gy8xL0ThWykjkw==','2gIAAAASAQAEAAAAAgIACFQ2RWlrN1J2NbVIrb6bXytpe04k84wwP6qbM8ykjL0yyNSryw=='), NULL, NULL,'System')
/
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'a5263743-7cf0-42fc-b264-25ea8325759d',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'US BANK', '101000187', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAgIACDIzRGFoR3NnZBoBsQs+N73YYquvybosRhnY5b6fOd6Yuv50qA==','2gIAAAASAQAEAAAAAgIACEVuMTJRcDZCsCyOq5+3IcZ2lDcxqpwAIWwTBAfAxlhsL3jY7Q=='), NULL, NULL, 'System')
/
--PSP-17711
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852e71d0319',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'US Bank', '092900383', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAgIACFVYU3RUUVdnoMhYZXXJun90I1mHwripyhpndT02hascHJ4HOw==','2gIAAAASAQAEAAAAAgIACG5JK0RwYWNBhki5h8saxvBmyG4uYubpwDbTVsyCs2ZNzPWAhg=='), NULL, NULL,'System')
/
--PSP-18543
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852e71d0320',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'Bank of America', '011000206', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAwIACHhGSjlWYjVCcczknaR9D0FMbKZn/wA9rinrdUiPFcpZeQ==','2gIAAAASAQAEAAAAAwIACDl4RVFJdy9yETJdN3r69h8yTimB44kVlXWmCSmVwNuavw=='), NULL, NULL,'System')
/
--PSP-19068
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852e71d0323',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'US Bank National Association OR', '123206707', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAwIACEpKWmZXYWdRAkqXehl6xg0+TyAmJ9EDpqxLy6hV6ldPWm0','2gIAAAASAQAEAAAAAwIACFU2RVQvVWpJxpWTsBMx+5ALqokKZdaHFLbkTieUdDlawTU'), NULL, NULL,'System')
/
--PSP-18895
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852e71d0321',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'Synovus', '061100606', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAAAwIACHVYelVjVmVU5FQBgtTSA6POWP3uYmgrAP0JydmbGxyj4YA=','2gIAAAASAQAEAAAAAwIACHI2d3VtRFBh/yvOCtT5L2VGy0bsZBBILXHOUHRPOs6FZLs='), NULL, NULL,'System')
/
--PSP-19894
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852e71d0324',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '021409169', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAABAIACGFUODM2OUxhiI0rVS5qwQGOu9wwy6RpmZ9+GipwvQ==','2gIAAAASAQAEAAAABAIACGdMclF6K2cwzVJKm37sJFl099sqB2ESl/RM+43pRw=='), NULL, NULL, 'System')
/
--PSP-19946
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852e71d0326',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'MO Employment Security', '086500634', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAABAIACDhPLzNVOWZpZxIr6gUaIdULA3/oqA6hySnslxmYPCk=','2gIAAAASAQAEAAAABAIACGkyMVhEWXN1IKW4Sl04t9g4tX1H35Jk9YVjG4lwpIM='), NULL, NULL, 'System')
/
--PSP-20226
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852e71d0327',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'Bank of America', '011900254', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAABAIACGQrZW02ZXpXCOqK4ULEKJTt6OI8m9zqngRwo1bWBkBBx38FyhgOnZ+H','2gIAAAASAQAEAAAABAIACG0xQTcyVjUySF4W4mDxOG4Fcon9tfqbxnx0pdAn+VNuR9etpYxY+1dl'), NULL, NULL, 'System')
/
---PSP-20860
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852e71d0328',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'Wells Fargo', '121000248', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAABAIACGVWK0ZzNGFmCMzZ8mJOCYdG9357+62KegwttBH9vKxLbtSAjvWto/Oj','2gIAAAASAQAEAAAABAIACDZNdnM2L0pjc0FGubiv/gzgrolqPb4zZD7Ga9B+yBJzHm8MDD1wyWrm'), NULL, NULL, 'System')
/
---PSP-20938
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852e71d0329',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'JP MORGAN CHASE', '121000248', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAABAIACFY0NlVmTjd5XmD5GHqh0Zo+jxO+Y19/t9Bv8Vejrp6TsK4=','2gIAAAASAQAEAAAABAIACGhudlc2NDZYSCt9nJjwmx6l2uUyo6XrBdUbA3U7WG/cnlM='), NULL, NULL, 'System')
/
---PSP-22429
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852e71d0330',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'PNC', '083000108', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAABgUACDl2SDQ1NVZKBSIWaorJgesn9eom2W7gGioR8IxHangeOF8=','2gIAAAASAQAEAAAABgUACEFOTjZGVjg0DQJGq5ihsdkvRBLq/sySHQR1L5a2JUYWV7g='), NULL, NULL, 'System')
/
-- PSP-23405
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852e71d0332',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'Bank of America N.A.', '011900254', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAABwUACGdwVitqeFQrINX3Q3jDXy4X+hIx/TQFyfrTjaZVDb23Crz23w==','2gIAAAASAQAEAAAABwUACEdSVEt3Qmpv3Rhtp1+0ehGR5XdmeTWa1eNBxbAHNuVdcNrAjA=='), NULL, NULL, 'System')
/
--PSP-24126
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852e71d0331',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'WELLS FARGO', '121000248', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAABwUACDNRMW9QV1VZnrdnCbVd2iyhKpfolaiGSGGn88KD0ndfjpk=','2gIAAAASAQAEAAAABwUACDNKVnoxdmdwH3HeoLoyWCKmHr2t610MPpMAmgzDjKHT4aU='), NULL, NULL,'System')
/
--PSP-24938
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852e71d0333',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'Key Bank', '021052053', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAACAUACC9VUkJFemFpocmKvUm9YzBRVeF9TK+eGhZ1Ui/Svuxb','2gIAAAASAQAEAAAABwUACHZ2ME1oUXFW27h8w3CahfJ6JoYMgy5uw+4+FJhLnJ53'), NULL, NULL,'System')
/
--PSP-25221
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852e71d0338',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'US BANK', '021052053', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAACAUACDcrUXpod3FBviLv50f9gsyCYealInpPgQXNGM39H3Gn','2gIAAAASAQAEAAAACAUACENCQzhOdlRNSn4ahTGtx52MXc+NGp7s+ZW/O+a5hPWW'), NULL, NULL,'System')
/
--PSP-25540
INSERT INTO TEMP_PSP_BANK_ACCOUNT (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE, CREATOR_ID) VALUES (
'4063bac7-4c8f-4811-8188-1852e71d0456',0, SYSDATE, SYSDATE,'Checking', 'Checking', 'US Bank', '122235821', DECODE(FN_GET_ENV(),'PROD','2gIAAAASAQAEAAAACQUACFpvUURSSTU1k49yCh52RW7UgBBUMAHp5ydVRXY/SLEF5bTvaw==','2gIAAAASAQAEAAAACAUACGhXN3ZWOWhIuMb0IXGGubz+o2huen/WcdXFMeMp9rfEf/nWEw=='), NULL, NULL,'System')
/


--------------------------------------------------------
-- Sychronize temp table and real table by            --
-- inserting, deleting, and updating as necessary     --
--------------------------------------------------------

INSERT INTO PSP_BANK_ACCOUNT
   (BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE,CREATOR_ID )
SELECT
    BANK_ACCOUNT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ACCOUNT_TYPE_CD, A_C_H_ACCOUNT_TYPE_CD, BANK_NAME, ROUTING_NUMBER, ACCOUNT_NUMBER_ENC, EFFECTIVE_DATE,EXPIRATION_DATE,CREATOR_ID
FROM
   TEMP_PSP_BANK_ACCOUNT tt
WHERE
   tt.BANK_ACCOUNT_SEQ NOT IN (SELECT BANK_ACCOUNT_SEQ FROM PSP_BANK_ACCOUNT)

/

UPDATE PSP_BANK_ACCOUNT rt
SET ( rt.VERSION, rt.CREATED_DATE, rt.MODIFIED_DATE, rt.ACCOUNT_TYPE_CD, rt.A_C_H_ACCOUNT_TYPE_CD, rt.BANK_NAME, rt.ROUTING_NUMBER, rt.ACCOUNT_NUMBER_ENC, rt.EFFECTIVE_DATE, rt.EXPIRATION_DATE,rt.CREATOR_ID) =
(SELECT  tt.VERSION, tt.CREATED_DATE, tt.MODIFIED_DATE, tt.ACCOUNT_TYPE_CD, tt.A_C_H_ACCOUNT_TYPE_CD, tt.BANK_NAME, tt.ROUTING_NUMBER, tt.ACCOUNT_NUMBER_ENC, tt.EFFECTIVE_DATE, tt.EXPIRATION_DATE,tt.CREATOR_ID
FROM TEMP_PSP_BANK_ACCOUNT tt WHERE tt.BANK_ACCOUNT_SEQ = rt.BANK_ACCOUNT_SEQ)
WHERE rt.BANK_ACCOUNT_SEQ IN (SELECT BANK_ACCOUNT_SEQ FROM TEMP_PSP_BANK_ACCOUNT)
/



--------------------------------------------------------
-- Drop temp table                                  --
--------------------------------------------------------
DROP TABLE TEMP_PSP_BANK_ACCOUNT

/
COMMIT;


