DECLARE

	table_exists PLS_INTEGER;

BEGIN

	SELECT COUNT(*) INTO table_exists
	FROM "USER_TABLES"
	WHERE TABLE_NAME = 'TEMP_RETURN_REASON_DESC';

	IF table_exists = 1 THEN
		EXECUTE IMMEDIATE 'DROP TABLE "TEMP_RETURN_REASON_DESC" CASCADE CONSTRAINTS';
	END IF;

END;
/


--------------------------------------------------------
-- Create temp table                                  --
--------------------------------------------------------
CREATE TABLE TEMP_RETURN_REASON_DESC
(
    VERSION         NUMBER(19)          DEFAULT 0   NOT NULL,
	REASON_CD       VARCHAR2(255 CHAR)              NOT NULL,
	DESCRIPTION     VARCHAR2(4000 CHAR)
)
/


--------------------------------------------------------
-- TEMP_RETURN_REASON_DESC                            --
--------------------------------------------------------
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R01', 'Insufficient Funds')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R02', 'Account Closed')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R03', 'Unable to Locate Account')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R04', 'Invalid Account Number')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R05', 'Unauthorized Debit to Consumer Account')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R06', 'Returned per Bank Request')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R07', 'Authorization Revoked by Customer')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R08', 'Payment Stopped')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R09', 'Funds Not Available to Cover Transaction(s)')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R10', 'Not Authorized Per Customer')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R11', 'Check Truncation Entry Return')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R12', 'Branch Sold to Another Bank')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R13', 'Receiving Bank Not Qualified')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R14', 'Customer Deceased')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R15', 'Beneficiary Deceased')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R16', 'Account Frozen')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R17', 'Tape Record Edit Criteria')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R18', 'Improper Effective Entry Date')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R19', 'Amount Field Error')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R20', 'Non-Transaction Account')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R21', 'Invalid Company Identification')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R22', 'Invalid Individual ID Number')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R23', 'Payment Refused by Biller')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R24', 'Duplicate Entry')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R25', 'Addenda Error')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R26', 'Mandatory Field Error')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R27', 'Trace Number Error')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R28', 'Routing Number Digit Error')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R29', 'Corporate Customer Advises not Authorized')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R30', 'Bank Not Participant in Check Truncation Program')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R31', 'Permissible Return Entry')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R32', 'Bank Non-Settlement')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R33', 'Return of XCK Entry')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R34', 'Limited Participation Bank')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R35', 'Return of Improper Debit Entry')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R36', 'Return of Improper Credit Entry')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R37', 'Source Document Presented for Payment')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R38', 'Stop Payment on ARC document')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R39', 'Improper ARC/POP Source Document')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R40', 'Return of ENR Entry by Federal Government Agency')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R41', 'Invalid Transaction Code')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R42', 'Routing Number/Check Digit Error')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R43', 'Invalid DFI Account Number')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R44', 'Invalid Individual ID Number/Identification Number')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R45', 'Invalid Individual Name/Company Name')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R46', 'Invalid Representative Payee Indicator')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R47', 'Duplicate Enrollment')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R48', '')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R49', '')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R50', 'State Law Affecting RCK Acceptance')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R51', 'Item Ineligible, Signature Not Genuine')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R52', 'Stop Payment on Item')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R53', 'Duplicate ACH entry presented for payment.')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R61', 'Misrouted Return')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R62', 'Incorrect Trace Number')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R63', 'Incorrect Dollar Amount')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R64', 'Incorrect Individual Identification')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R65', 'Incorrect Transaction Code')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R66', 'Incorrect Company Identification')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R67', 'Duplicate Return')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R68', 'Untimely Return')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R69', 'Multiple Errors')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R70', 'Permissible Return Entry Not Accepted')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R71', 'Misrouted Dishonored Return')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R72', 'Untimely Dishonored Return')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R73', 'Timely Original Return')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R74', 'Corrected Return')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R75', 'Original Return Not a Duplicate')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R76', 'No Errors Found')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R80', 'Cross-Border Payment Coding Error')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R81', 'Non-Participant in Cross-Border Program')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R82', 'Invalid Foreign Receiving Bank Identification')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R83', 'Foreign Receiving Bank Unable to Settle')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R84', 'Entry Not Processed by OGO')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'R99', '')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'C01', 'Incorrect Bank Account Number')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'C02', 'Incorrect Routing Number')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'C03', 'Incorrect Routing Number and Incorrect Bank Account Number')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'C04', 'Incorrect Account Holder Name')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'C05', 'Incorrect Transaction Code')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'C06', 'Incorrect Bank Account Number and Incorrect Transaction Code')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'C07', 'Incorrect Routing Number, Bank Account Number & Transaction Code')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'C08', 'Incorrect Foreign Receiving Identification')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'C09', 'Incorrect Individual ID Number')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'C10', '')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'C11', '')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'C12', '')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'C13', 'Addenda Format Error')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'C61', 'Misrouted Notification of Change')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'C62', 'Incorrect Trace Number')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'C63', 'Incorrect Company Identification Number')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'C64', 'Incorrect Individual Identification Number')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'C65', 'Incorrectly Formatted Corrected Data')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'C66', 'Incorrect Discretionary Data')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'C67', 'Routing Number Not From Original Entry Detail Record')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'C68', 'DFI Account Number Not From Original Entry Detail Record')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'C69', 'Incorrect Transaction Code')
/
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION ) VALUES (
'C99', '')
/


--------------------------------------------------------
-- Sychronize temp table and real table by            --
-- inserting, deleting, and updating as necessary     --
--------------------------------------------------------

INSERT INTO PSP_RETURN_REASON_DESC
   ( REASON_CD, VERSION, DESCRIPTION )
SELECT
    REASON_CD, VERSION, DESCRIPTION
FROM
   TEMP_RETURN_REASON_DESC tt
WHERE
   tt.REASON_CD NOT IN ( SELECT REASON_CD FROM PSP_RETURN_REASON_DESC )
/

DELETE FROM PSP_RETURN_REASON_DESC
WHERE REASON_CD NOT IN (SELECT REASON_CD FROM TEMP_RETURN_REASON_DESC)
/

UPDATE PSP_RETURN_REASON_DESC rt
SET ( rt.DESCRIPTION ) =
( SELECT tt.DESCRIPTION
  FROM TEMP_RETURN_REASON_DESC tt
  WHERE tt.REASON_CD = rt.REASON_CD )
/


--------------------------------------------------------
-- Drop temp table                                  --
--------------------------------------------------------
DROP TABLE TEMP_RETURN_REASON_DESC
/

COMMIT
