DECLARE

    table_exists PLS_INTEGER;

BEGIN


    SELECT COUNT(*) INTO table_exists
    FROM "USER_TABLES"
    WHERE TABLE_NAME = 'TEMP_PSP_OFFLOAD_GROUP';

    IF table_exists = 1 THEN
        EXECUTE IMMEDIATE 'DROP TABLE "TEMP_PSP_OFFLOAD_GROUP" CASCADE CONSTRAINTS';
    END IF;

END;

/

--------------------------------------------------------
-- Create temp table                                  --
--------------------------------------------------------
CREATE TABLE TEMP_PSP_OFFLOAD_GROUP
(
    "OFFLOAD_GROUP_SEQ" VARCHAR2(255 CHAR)  NOT NULL
    , "OFFLOAD_GROUP_CD" VARCHAR2(10 CHAR)
    , "NAME" VARCHAR2(80 CHAR)
    , "DESCRIPTION" VARCHAR2(160 CHAR)
    , "CUTOFF_TIME" VARCHAR2(20 CHAR)
    , "VERSION" NUMBER(19,0)  NOT NULL
    , "CREATOR_ID" VARCHAR2(30 CHAR)
    , "CREATED_DATE" TIMESTAMP  NOT NULL
    , "MODIFIER_ID" VARCHAR2(30 CHAR)
    , "MODIFIED_DATE" TIMESTAMP  NOT NULL
)


/

--------------------------------------------------------
-- Insert into temp table                             --
--------------------------------------------------------

INSERT INTO TEMP_PSP_OFFLOAD_GROUP (OFFLOAD_GROUP_SEQ, OFFLOAD_GROUP_CD, NAME, DESCRIPTION, CUTOFF_TIME, VERSION, CREATOR_ID, CREATED_DATE, MODIFIER_ID, MODIFIED_DATE) VALUES (
'3b67b658-dc4e-012a-fc4f-005056c02727', 'STD', 'STANDARD', 'STANDARD 5:10 PM PACIFIC OFFLOAD GROUP',  '17:10:00', 0, 'SYSTEM', SYS_EXTRACT_UTC(SYSTIMESTAMP), 'SYSTEM', SYS_EXTRACT_UTC(SYSTIMESTAMP))
/

INSERT INTO TEMP_PSP_OFFLOAD_GROUP (OFFLOAD_GROUP_SEQ, OFFLOAD_GROUP_CD, NAME, DESCRIPTION, CUTOFF_TIME, VERSION, CREATOR_ID, CREATED_DATE, MODIFIER_ID, MODIFIED_DATE) VALUES (
'3b672727-dc4e-012a-fc4f-005056c02727', 'TXP', 'TAXPAYMENT', 'TAX PAYMENT OFFLOAD GROUP',  '13:25:00', 0, 'SYSTEM', SYS_EXTRACT_UTC(SYSTIMESTAMP), 'SYSTEM', SYS_EXTRACT_UTC(SYSTIMESTAMP))
/
INSERT INTO TEMP_PSP_OFFLOAD_GROUP (OFFLOAD_GROUP_SEQ, OFFLOAD_GROUP_CD, NAME, DESCRIPTION, CUTOFF_TIME, VERSION, CREATOR_ID, CREATED_DATE, MODIFIER_ID, MODIFIED_DATE) VALUES (
'3b672729-dc4e-012a-fc4f-005056c02727', 'PSPO', 'DDMIGRATION', 'DD MIGRATION OFFLOAD GROUP - PSP OFFLOADS',  '17:10:00', 0, 'SYSTEM', SYS_EXTRACT_UTC(SYSTIMESTAMP), 'SYSTEM', SYS_EXTRACT_UTC(SYSTIMESTAMP))
/
INSERT INTO TEMP_PSP_OFFLOAD_GROUP (OFFLOAD_GROUP_SEQ, OFFLOAD_GROUP_CD, NAME, DESCRIPTION, CUTOFF_TIME, VERSION, CREATOR_ID, CREATED_DATE, MODIFIER_ID, MODIFIED_DATE) VALUES (
'3b672730-dc4e-012a-fc4f-005056c02727', 'STD_DDS', 'DDMIGRATION', 'DD MIGRATION OFFLOAD GROUP - DD OFFLOADS',  '17:10:00', 0, 'SYSTEM', SYS_EXTRACT_UTC(SYSTIMESTAMP), 'SYSTEM', SYS_EXTRACT_UTC(SYSTIMESTAMP))
/
--------------------------------------------------------
-- Sychronize temp table and real table by            --
-- inserting, deleting, and updating as necessary     --
--------------------------------------------------------

INSERT INTO PSP_OFFLOAD_GROUP
   (OFFLOAD_GROUP_SEQ, OFFLOAD_GROUP_CD, NAME, DESCRIPTION, CUTOFF_TIME, VERSION, CREATOR_ID, CREATED_DATE, MODIFIER_ID, MODIFIED_DATE )
SELECT
    OFFLOAD_GROUP_SEQ, OFFLOAD_GROUP_CD, NAME, DESCRIPTION, CUTOFF_TIME, VERSION, CREATOR_ID, CREATED_DATE, MODIFIER_ID, MODIFIED_DATE
FROM
   TEMP_PSP_OFFLOAD_GROUP tt
WHERE
   tt.OFFLOAD_GROUP_CD NOT IN (SELECT OFFLOAD_GROUP_CD FROM PSP_OFFLOAD_GROUP)

/

UPDATE PSP_OFFLOAD_GROUP rt
SET (rt.OFFLOAD_GROUP_CD, rt.NAME, rt.DESCRIPTION, rt.CUTOFF_TIME, rt.VERSION, rt.CREATOR_ID, rt.CREATED_DATE, rt.MODIFIER_ID, rt.MODIFIED_DATE) =
(SELECT  tt.OFFLOAD_GROUP_CD, tt.NAME, tt.DESCRIPTION, tt.CUTOFF_TIME, tt.VERSION, tt.CREATOR_ID, rt.CREATED_DATE, rt.MODIFIER_ID, tt.MODIFIED_DATE
 FROM TEMP_PSP_OFFLOAD_GROUP tt WHERE tt.OFFLOAD_GROUP_CD = rt.OFFLOAD_GROUP_CD)
 WHERE
    rt.OFFLOAD_GROUP_CD IN (SELECT OFFLOAD_GROUP_CD FROM TEMP_PSP_OFFLOAD_GROUP)

/



--------------------------------------------------------
-- Drop temp table                                  --
--------------------------------------------------------
DROP TABLE TEMP_PSP_OFFLOAD_GROUP

/
COMMIT



