DECLARE

	table_exists PLS_INTEGER;

BEGIN


	SELECT COUNT(*) INTO table_exists
	FROM "USER_TABLES"
	WHERE TABLE_NAME = 'TMP_PAYMENT_TEMPLATE_AGENCY_ID';

	IF table_exists = 1 THEN
		EXECUTE IMMEDIATE 'DROP TABLE "TMP_PAYMENT_TEMPLATE_AGENCY_ID" CASCADE CONSTRAINTS';
	END IF;

END;

/

--------------------------------------------------------
-- Create temp table                                  --
--------------------------------------------------------

CREATE TABLE TMP_PAYMENT_TEMPLATE_AGENCY_ID
(
  PAYMENT_TEMPLATE_AGENCY_ID_SEQ  VARCHAR2(255 CHAR) NOT NULL,
  VERSION                         NUMBER(19)    NOT NULL,
  CREATOR_ID                      VARCHAR2(30 CHAR),
  CREATED_DATE                    TIMESTAMP(6)  NOT NULL,
  MODIFIER_ID                     VARCHAR2(30 CHAR),
  MODIFIED_DATE                   TIMESTAMP(6)  NOT NULL,
  REALM_ID                        NUMBER(19)    DEFAULT -1                    NOT NULL,
  NAME                            VARCHAR2(50 CHAR),
  PAYMENT_TEMPLATE_FK             VARCHAR2(255 CHAR) NOT NULL
)

/

--------------------------------------------------------
-- Insert into temp table                             --
--------------------------------------------------------

INSERT INTO TMP_PAYMENT_TEMPLATE_AGENCY_ID (PAYMENT_TEMPLATE_AGENCY_ID_SEQ, VERSION, CREATOR_ID, CREATED_DATE, MODIFIER_ID, MODIFIED_DATE, REALM_ID, NAME, PAYMENT_TEMPLATE_FK) VALUES (
'd79226a2-0000-0000-0000-a00000000001', 0, 'System', SYSDATE, 'System', SYSDATE, -1, 'BEN Number', 'IA-44105-PAYMENT')
/
INSERT INTO TMP_PAYMENT_TEMPLATE_AGENCY_ID (PAYMENT_TEMPLATE_AGENCY_ID_SEQ, VERSION, CREATOR_ID, CREATED_DATE, MODIFIER_ID, MODIFIED_DATE, REALM_ID, NAME, PAYMENT_TEMPLATE_FK) VALUES (
'd79226a2-0000-0000-0000-a00000000002', 0, 'System', SYSDATE, 'System', SYSDATE, -1, 'Client Bank Acct', 'IA-600103-PAYMENT')
/
INSERT INTO TMP_PAYMENT_TEMPLATE_AGENCY_ID (PAYMENT_TEMPLATE_AGENCY_ID_SEQ, VERSION, CREATOR_ID, CREATED_DATE, MODIFIER_ID, MODIFIED_DATE, REALM_ID, NAME, PAYMENT_TEMPLATE_FK) VALUES (
'd79226a2-0000-0000-0000-a00000000003', 0, 'System', SYSDATE, 'System', SYSDATE, -1, 'State Access Code', 'NY-1MN-PAYMENT')
/
INSERT INTO TMP_PAYMENT_TEMPLATE_AGENCY_ID (PAYMENT_TEMPLATE_AGENCY_ID_SEQ, VERSION, CREATOR_ID, CREATED_DATE, MODIFIER_ID, MODIFIED_DATE, REALM_ID, NAME, PAYMENT_TEMPLATE_FK) VALUES (
'd79226a2-0000-0000-0000-b00000000003', 0, 'System', SYSDATE, 'System', SYSDATE, -1, 'State Access Code', 'NY-MTA305-PAYMENT')
/
INSERT INTO TMP_PAYMENT_TEMPLATE_AGENCY_ID (PAYMENT_TEMPLATE_AGENCY_ID_SEQ, VERSION, CREATOR_ID, CREATED_DATE, MODIFIER_ID, MODIFIED_DATE, REALM_ID, NAME, PAYMENT_TEMPLATE_FK) VALUES (
'd79226a2-0000-0000-0000-a00000000004', 0, 'System', SYSDATE, 'System', SYSDATE, -1, 'State EFT Number', 'CO-DR1094-PAYMENT')
/

INSERT INTO TMP_PAYMENT_TEMPLATE_AGENCY_ID (PAYMENT_TEMPLATE_AGENCY_ID_SEQ, VERSION, CREATOR_ID, CREATED_DATE, MODIFIER_ID, MODIFIED_DATE, REALM_ID, NAME, PAYMENT_TEMPLATE_FK) VALUES (
'529e951d-e2be-4189-94a3-3810893fec0c', 0, 'System', SYSDATE, 'System', SYSDATE, -1, 'WA UBI', 'WA-F5208-PAYMENT')
/
--------------------------------------------------------
-- Synchronize temp table and real table by            --
-- inserting, deleting, and updating as necessary     --
--------------------------------------------------------

INSERT INTO PSP_PAYMENT_TEMPLATE_AGENCY_ID
   (PAYMENT_TEMPLATE_AGENCY_ID_SEQ, VERSION, CREATOR_ID, CREATED_DATE, MODIFIER_ID, MODIFIED_DATE, REALM_ID, NAME, PAYMENT_TEMPLATE_FK)
SELECT
    PAYMENT_TEMPLATE_AGENCY_ID_SEQ, VERSION, CREATOR_ID, CREATED_DATE, MODIFIER_ID, MODIFIED_DATE, REALM_ID, NAME, PAYMENT_TEMPLATE_FK
FROM
   TMP_PAYMENT_TEMPLATE_AGENCY_ID tt
WHERE
   tt.PAYMENT_TEMPLATE_AGENCY_ID_SEQ NOT IN (SELECT PAYMENT_TEMPLATE_AGENCY_ID_SEQ FROM PSP_PAYMENT_TEMPLATE_AGENCY_ID)
/

UPDATE PSP_PAYMENT_TEMPLATE_AGENCY_ID rt
SET (rt.VERSION, rt.CREATOR_ID, rt.CREATED_DATE, rt.MODIFIER_ID, rt.MODIFIED_DATE, rt.REALM_ID, rt.NAME, rt.PAYMENT_TEMPLATE_FK) =
(SELECT  tt.VERSION, tt.CREATOR_ID, tt.CREATED_DATE, tt.MODIFIER_ID, tt.MODIFIED_DATE, tt.REALM_ID, tt.NAME, tt.PAYMENT_TEMPLATE_FK
 FROM TMP_PAYMENT_TEMPLATE_AGENCY_ID tt WHERE tt.PAYMENT_TEMPLATE_AGENCY_ID_SEQ = rt.PAYMENT_TEMPLATE_AGENCY_ID_SEQ)
 WHERE rt.PAYMENT_TEMPLATE_AGENCY_ID_SEQ IN (SELECT PAYMENT_TEMPLATE_AGENCY_ID_SEQ FROM TMP_PAYMENT_TEMPLATE_AGENCY_ID)
/

DELETE FROM PSP_PAYMENT_TEMPLATE_AGENCY_ID
WHERE PAYMENT_TEMPLATE_AGENCY_ID_SEQ NOT IN (SELECT PAYMENT_TEMPLATE_AGENCY_ID_SEQ FROM TMP_PAYMENT_TEMPLATE_AGENCY_ID)
/

--------------------------------------------------------
-- Drop temp table                                  --
--------------------------------------------------------
DROP TABLE TMP_PAYMENT_TEMPLATE_AGENCY_ID

/
COMMIT;
