DECLARE
	
	table_exists PLS_INTEGER;

BEGIN


	SELECT COUNT(*) INTO table_exists
	FROM "USER_TABLES"
	WHERE TABLE_NAME = 'TEMP_INTUIT_BA_BT_FT';

	IF table_exists = 1 THEN
		EXECUTE IMMEDIATE 'DROP TABLE "TEMP_INTUIT_BA_BT_FT" CASCADE CONSTRAINTS';
	END IF;

END;

/

--------------------------------------------------------
-- Create temp table                                  --
--------------------------------------------------------
CREATE TABLE TEMP_INTUIT_BA_BT_FT
(
	"INTUIT_BA_BT_FT_SEQ" VARCHAR2(255 CHAR) NOT NULL,  
	"VERSION" NUMBER(19,0) NOT NULL,
	"CREATED_DATE" TIMESTAMP NOT NULL, 
	"MODIFIED_DATE" TIMESTAMP NOT NULL, 
	"FILE_TYPE" VARCHAR2(4000 CHAR),  
	"N_A_C_H_A_BATCH_TYPE" VARCHAR2(255 CHAR),
	"INTUIT_BANK_ACCOUNT_FK" VARCHAR2(255 CHAR)  
)

/

--------------------------------------------------------
-- Insert into temp table                             --
--------------------------------------------------------
INSERT INTO TEMP_INTUIT_BA_BT_FT ( INTUIT_BA_BT_FT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE,
FILE_TYPE, N_A_C_H_A_BATCH_TYPE, INTUIT_BANK_ACCOUNT_FK ) VALUES ( 
'a5c6268b-017a-111c-bf88-5870e9b19d98', 0, SYSDATE, SYSDATE, 'PPD', 'Reversal', 'a62f39f9-3aab-48ac-ace7-3ab8f700abb9')
/

INSERT INTO TEMP_INTUIT_BA_BT_FT ( INTUIT_BA_BT_FT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE,
FILE_TYPE, N_A_C_H_A_BATCH_TYPE, INTUIT_BANK_ACCOUNT_FK ) VALUES ( 
'a5c6268b-017a-211c-bf88-5870e9b19d98', 0, SYSDATE, SYSDATE, 'PPD', 'Payroll', '3b76af25-eb67-4409-a559-225a85eee4b9')
/

INSERT INTO TEMP_INTUIT_BA_BT_FT ( INTUIT_BA_BT_FT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE,
FILE_TYPE, N_A_C_H_A_BATCH_TYPE, INTUIT_BANK_ACCOUNT_FK ) VALUES ( 
'a5c6268b-017a-311c-bf88-5870e9b19d98', 0, SYSDATE, SYSDATE, 'CCD', 'Payroll', '3b76af25-eb67-4409-a559-225a85eee4b9')
/
INSERT INTO TEMP_INTUIT_BA_BT_FT ( INTUIT_BA_BT_FT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE,
FILE_TYPE, N_A_C_H_A_BATCH_TYPE, INTUIT_BANK_ACCOUNT_FK ) VALUES ( 
'a5c6268b-017a-411c-bf88-5870e9b19d98', 0, SYSDATE, SYSDATE, 'CCD', 'Payroll', 'a5263743-7cf0-42fc-b164-25ea68315756')
/
INSERT INTO TEMP_INTUIT_BA_BT_FT ( INTUIT_BA_BT_FT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE,
FILE_TYPE, N_A_C_H_A_BATCH_TYPE, INTUIT_BANK_ACCOUNT_FK ) VALUES ( 
'a5c6268b-017a-511c-bf88-5870e9b19d98', 0, SYSDATE, SYSDATE, 'CCD', 'Payroll', 'a62f39f9-3aab-48ac-ace7-3ab8f700abb9')
/
INSERT INTO TEMP_INTUIT_BA_BT_FT ( INTUIT_BA_BT_FT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE,
FILE_TYPE, N_A_C_H_A_BATCH_TYPE, INTUIT_BANK_ACCOUNT_FK ) VALUES ( 
'a5c6268b-017a-611c-bf88-5870e9b19d98', 0, SYSDATE, SYSDATE, 'CCD', 'Payroll', '89057491-baf0-49dd-bbda-a5c5eff5a7d9')
/
INSERT INTO TEMP_INTUIT_BA_BT_FT ( INTUIT_BA_BT_FT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE,
FILE_TYPE, N_A_C_H_A_BATCH_TYPE, INTUIT_BANK_ACCOUNT_FK ) VALUES ( 
'a5c6268b-017a-711c-bf88-5870e9b19d98', 0, SYSDATE, SYSDATE, 'CCD', 'BookTransfer', 'a5263743-7cf0-42fc-b164-25ea68315756')
/
INSERT INTO TEMP_INTUIT_BA_BT_FT ( INTUIT_BA_BT_FT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE,
FILE_TYPE, N_A_C_H_A_BATCH_TYPE, INTUIT_BANK_ACCOUNT_FK ) VALUES ( 
'a5c6268b-017a-811c-bf88-5870e9b19d98', 0, SYSDATE, SYSDATE, 'CCD', 'BookTransfer', 'a62f39f9-3aab-48ac-ace7-3ab8f700abb9')
/
INSERT INTO TEMP_INTUIT_BA_BT_FT ( INTUIT_BA_BT_FT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE,
FILE_TYPE, N_A_C_H_A_BATCH_TYPE, INTUIT_BANK_ACCOUNT_FK ) VALUES ( 
'a5c6268b-017a-911c-bf88-5870e9b19d98', 0, SYSDATE, SYSDATE, 'CCD', 'BookTransfer', '89057491-baf0-49dd-bbda-a5c5eff5a7d9')
/
INSERT INTO TEMP_INTUIT_BA_BT_FT ( INTUIT_BA_BT_FT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE,
FILE_TYPE, N_A_C_H_A_BATCH_TYPE, INTUIT_BANK_ACCOUNT_FK ) VALUES ( 
'a5c6268b-017a-011c-bf88-5870e9b19d98', 0, SYSDATE, SYSDATE, 'CCD', 'BookTransfer', '3b76af25-eb67-4409-a559-225a85eee4b9')
/

--------------------------------------------------------
-- Sychronize temp table and real table by            --
-- inserting, deleting, and updating as necessary     --
--------------------------------------------------------
INSERT INTO PSP_INTUIT_BA_BT_FT
   (INTUIT_BA_BT_FT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE,  FILE_TYPE, N_A_C_H_A_BATCH_TYPE, INTUIT_BANK_ACCOUNT_FK)
SELECT 
    INTUIT_BA_BT_FT_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE,  FILE_TYPE, N_A_C_H_A_BATCH_TYPE, INTUIT_BANK_ACCOUNT_FK 
FROM 
   TEMP_INTUIT_BA_BT_FT tt 
WHERE 
   tt.INTUIT_BA_BT_FT_SEQ NOT IN (SELECT INTUIT_BA_BT_FT_SEQ FROM PSP_INTUIT_BA_BT_FT)

/

DELETE FROM PSP_INTUIT_BA_BT_FT
WHERE INTUIT_BA_BT_FT_SEQ NOT IN (SELECT INTUIT_BA_BT_FT_SEQ FROM TEMP_INTUIT_BA_BT_FT) 

/

UPDATE PSP_INTUIT_BA_BT_FT rt
SET ( rt.VERSION, rt.CREATED_DATE, rt.MODIFIED_DATE,  rt.FILE_TYPE, rt.N_A_C_H_A_BATCH_TYPE, rt.INTUIT_BANK_ACCOUNT_FK) =
(SELECT tt.VERSION,  tt.CREATED_DATE,  tt.MODIFIED_DATE,  tt.FILE_TYPE, tt.N_A_C_H_A_BATCH_TYPE, tt.INTUIT_BANK_ACCOUNT_FK
 FROM TEMP_INTUIT_BA_BT_FT tt WHERE tt.INTUIT_BA_BT_FT_SEQ = rt.INTUIT_BA_BT_FT_SEQ)
/

--------------------------------------------------------
-- Drop temp table                                  --
--------------------------------------------------------
DROP TABLE TEMP_INTUIT_BA_BT_FT

/
COMMIT
 

 
