DECLARE
	
	table_exists PLS_INTEGER;

BEGIN


	SELECT COUNT(*) INTO table_exists
	FROM "USER_TABLES"
	WHERE TABLE_NAME = 'TEMP_PAYROLL_RUN_ACTION';

	IF table_exists = 1 THEN
		EXECUTE IMMEDIATE 'DROP TABLE "TEMP_PAYROLL_RUN_ACTION" CASCADE CONSTRAINTS';
	END IF;

END;
                                 
/
--------------------------------------------------------
-- Create temp table                                  --
--------------------------------------------------------
CREATE TABLE TEMP_PAYROLL_RUN_ACTION
(
  PAYROLL_RUN_ACTION_SEQ        VARCHAR2(255 CHAR)           NOT NULL,
  VERSION          NUMBER(19)                   NOT NULL,
  CREATED_DATE     TIMESTAMP(6)                 NOT NULL,
  MODIFIED_DATE    TIMESTAMP(6)                 NOT NULL,
  STATUS           VARCHAR2(255 CHAR),
  ACTION_EVENT_FK  VARCHAR2(255 CHAR)           NOT NULL
)
/

--------------------------------------------------------
-- Insert into temp table                             --
--------------------------------------------------------


INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS, ACTION_EVENT_FK)
VALUES ('35aa8b0f-a89d-46d9-a474-60e3bb5e4481', 0, SYSDATE, SYSDATE, 'OffloadedAll','DDTransactionReverse')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('aac2f372-c6ad-47a7-a67c-3a492405f04c', 0, SYSDATE, SYSDATE,  'PendingAutoRedebit','DDTransactionReverse')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('0055072f-ba32-4fbc-868f-54b7370162ef', 0,SYSDATE, SYSDATE,  'AutoRedebitOffloaded','DDTransactionReverse')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('93e25d84-5e6a-403a-9760-197ed324613e', 0, SYSDATE, SYSDATE,  'ReturnedTwice','DDTransactionReverse')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('cfff81fb-e7ca-4443-a00d-713ef880bc9e', 0, SYSDATE, SYSDATE,  'DebitReturned','DDTransactionReverse')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS, ACTION_EVENT_FK)
VALUES ('50812626-78b4-43f8-99fa-00016ae800ec', 0, SYSDATE, SYSDATE,  'PendingRedebit','DDTransactionReverse')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('3db69376-7c6a-4dc0-bf52-e02aae664a67', 0, SYSDATE, SYSDATE,  'RedebitOffloaded','DDTransactionReverse')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('e74402e9-1afc-46f7-8b7e-aedc41f583ab', 0, SYSDATE, SYSDATE,  'Complete','DDTransactionReverse')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS, ACTION_EVENT_FK)
VALUES ('985d0ef7-937a-45c4-a561-275f4fe6f1f5', 0, SYSDATE, SYSDATE,  'PendingWire','DDTransactionReverse')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('23232d7d-0467-4f93-849f-b2e93500c250', 0, SYSDATE, SYSDATE,  'Pending','DDTransactionCancel')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('9d3572b5-1157-4f40-a523-fe8604f65e08', 0, SYSDATE, SYSDATE,  'OffloadedDebit','DDTransactionCancel')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('ee7d84a6-5cca-4ab6-bf4e-c4e9a8195263', 0, SYSDATE, SYSDATE,  'ReturnedTwice','DDRedebitAdd')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('7e1adb35-8e8d-4eab-8fd1-10fc42e45323', 0, SYSDATE, SYSDATE,  'DebitReturned','DDRedebitAdd')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('934ab4bd-d05a-4af6-9fd0-f25872d82c11', 0, SYSDATE, SYSDATE,  'PendingReversals','DDRedebitAdd')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('ee7d84a6-5cca-4ab6-bf4e-c4e9a8197263', 0, SYSDATE, SYSDATE,  'PendingWire','DDRedebitAdd')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('ee7d84a6-5cca-4ab6-bf4e-c4e9a8198263', 0, SYSDATE, SYSDATE,  'ReversalsFinished','DDRedebitAdd')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('4394baef-b65e-a4e6-f0d9-852f8d72112c', 0, SYSDATE, SYSDATE,  'PendingAutoRedebit','DDRedebitEdit')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('ab4546ac-41ab-2ac3-4ad6-f85227c112d8', 0, SYSDATE, SYSDATE,  'PendingRedebit','DDRedebitEdit')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('484e8a46-a5d8-45f7-8044-5342e81e9caf', 0, SYSDATE, SYSDATE,  'Canceled','DDRedebitRecord')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('9baaf874-7d1a-4702-baf6-f5197fdfbb22', 0, SYSDATE, SYSDATE,  'Complete','DDRedebitRecord')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('deef465d-ff0f-481b-ae42-bfb2ac95e6db', 0, SYSDATE, SYSDATE, 'DebitReturnedCanceled','DDRedebitRecord')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS, ACTION_EVENT_FK)
VALUES ('e1b69e37-2bef-47ab-a60a-420913325325', 0, SYSDATE, SYSDATE,  'RedebitOffloaded','DDRedebitRecord')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('4956be82-4faa-4150-8243-ab34ee45f0c8', 0, SYSDATE, SYSDATE,  'PendingRedebit','DDRedebitRecord')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('caaf980c-3812-4eb8-9c38-946fe51076c0', 0, SYSDATE, SYSDATE,  'NSFCanceled','DDRedebitRecord')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('1d84561f-6f13-4cfe-b337-08fcbb1abc02', 0, SYSDATE, SYSDATE,  'AutoRedebitOffloaded','DDRedebitRecord')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('b99a2184-5cc2-4be3-a98c-1fc93d9b427c', 0, SYSDATE, SYSDATE,  'PendingAutoRedebit','DDRedebitRecord')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('4584d8db-55d2-467f-9aa6-c77652bf109c', 0, SYSDATE, SYSDATE, 'OffloadedAll','DDRedebitRecord')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('4534d8db-55d2-467f-9aa6-c77652bf109c', 0, SYSDATE, SYSDATE, 'OffloadedDebit','DDRedebitRecord')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('4594d8db-55d2-467f-9aa6-c77652bf109c', 0, SYSDATE, SYSDATE, 'Pending','DDRedebitRecord')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('1d84561f-6f13-4cfe-b337-08fcbb2abc02', 0, SYSDATE, SYSDATE,  'ReversalsOffloaded','DDRedebitRecord')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS, ACTION_EVENT_FK)
VALUES ('d8bd56ca-5315-4ac4-bf25-a58a8a5a97a7', 0, SYSDATE, SYSDATE, 'Canceled','ERFeeAdd')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS, ACTION_EVENT_FK)
VALUES ('353a3b93-5f98-4276-b7c5-470ac5dba1e2', 0, SYSDATE, SYSDATE,  'Complete','ERFeeAdd')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS, ACTION_EVENT_FK)
VALUES ('4c9d246b-2341-47a5-8de3-127a86d88a10', 0, SYSDATE, SYSDATE,  'DebitReturned','ERFeeAdd')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('8187a784-be7b-4fc6-90ca-75ad7815f687', 0, SYSDATE, SYSDATE,  'DebitReturnedCanceled','ERFeeAdd')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('e141fe60-4b26-41d4-ae85-a45b99fdf267', 0, SYSDATE, SYSDATE,  'RedebitOffloaded','ERFeeAdd')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('ce4e9a8c-6110-4e62-8866-ca919c98dff5', 0, SYSDATE, SYSDATE,  'PendingRedebit','ERFeeAdd')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('5f748cc5-87e4-4c44-a591-13bbf6127ba1', 0, SYSDATE, SYSDATE,  'NSFCanceled','ERFeeAdd')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('157da69f-f5f8-48ae-9016-3154dfe2dfb4', 0, SYSDATE, SYSDATE,  'PendingAutoRedebit','ERFeeAdd')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('e141fe60-4b26-51d4-ae85-a45b99fdf267', 0, SYSDATE, SYSDATE,  'AutoRedebitOffloaded','ERFeeAdd')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('90ea8c51-3f13-4e70-8514-887bb705a3d3', 0, SYSDATE, SYSDATE,  'ReturnedTwice','ERFeeAdd')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('999ec685-6c30-4004-87dd-48ec75ead9b3', 0, SYSDATE, SYSDATE,  'OffloadedAll','ERFeeAdd')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('8e056780-b121-4dc3-8045-f85bfc80338e', 0, SYSDATE, SYSDATE,  'PendingReversals','ERFeeAdd')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('804b5891-4fa2-4e88-a697-bb21fd11b09c', 0,SYSDATE, SYSDATE,  'PendingWire','ERFeeAdd')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('e141fe60-4b26-61d4-ae85-a45b99fdf267', 0, SYSDATE, SYSDATE,  'ReversalsOffloaded','ERFeeAdd')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('e141fe60-4b26-71d4-ae85-a45b99fdf267', 0, SYSDATE, SYSDATE,  'ReversalsFinished','ERFeeAdd')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('e141fe60-4b26-71d4-ae85-a45b99fdf367', 0, SYSDATE, SYSDATE,  'Pending','ERFeeAdd')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('409ce586-630b-0054-8d7d-84ce75daeb96', 0, SYSDATE, SYSDATE,  'PendingReversals','ERWireExpected')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('5685e080-f341-d43c-5408-b58ffc83380b', 0, SYSDATE, SYSDATE,  'PendingWire','ERWireExpected')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('4fa21895-804b-9788-4ea6-d1b211b09bcf', 0,SYSDATE, SYSDATE,  'DebitReturned','ERWireExpected')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('61d4fe60-ae85-e141-4b26-bd99fa45762f', 0, SYSDATE, SYSDATE,  'ReturnedTwice','ERWireExpected')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('4b26fe60-e141-7ae8-51d4-f267a45b99fd', 0, SYSDATE, SYSDATE,  'ReversalsFinished','ERWireExpected')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('d1802594-5072-4474-83e1-8b891343de0f', 0, SYSDATE, SYSDATE,  'WrittenOff','ERFeeAdd')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('bcc2108e-de26-45b5-b282-33280a2a80a6', 0, SYSDATE, SYSDATE,  'WrittenOff','DDRedebitRecord')
/


INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('fcc2108e-de26-45b5-b282-33280a2a8001', 0, SYSDATE, SYSDATE,  'Pending','RecordPrefundingWire')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('fcc2108e-de26-45b5-b282-33280a2a8002', 0, SYSDATE, SYSDATE,  'Complete','RecordPrefundingWire')
/
INSERT INTO TEMP_PAYROLL_RUN_ACTION ( PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
VALUES ('fcc2108e-de26-45b5-b282-33280a2a8003', 0, SYSDATE, SYSDATE,  'Pending','CancelAdjustment')
/


--------------------------------------------------------
-- Sychronize temp table and real table by            --
-- inserting, deleting, and updating as necessary     --
--------------------------------------------------------

INSERT INTO PSP_PAYROLL_RUN_ACTION
   (PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK)
SELECT 
   PAYROLL_RUN_ACTION_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, STATUS,ACTION_EVENT_FK
FROM 
   TEMP_PAYROLL_RUN_ACTION tpra
WHERE 
    (tpra.STATUS, tpra.ACTION_EVENT_FK)  NOT IN (SELECT STATUS, ACTION_EVENT_FK FROM PSP_PAYROLL_RUN_ACTION)

/

DELETE FROM PSP_PAYROLL_RUN_ACTION
WHERE  (STATUS, ACTION_EVENT_FK)  NOT IN (SELECT STATUS,ACTION_EVENT_FK FROM TEMP_PAYROLL_RUN_ACTION)


/

UPDATE PSP_PAYROLL_RUN_ACTION pra
SET (pra. VERSION, pra.CREATED_DATE, pra.MODIFIED_DATE, pra.ACTION_EVENT_FK, pra.STATUS) =
(SELECT  tpra. VERSION, tpra.CREATED_DATE, tpra.MODIFIED_DATE, tpra.ACTION_EVENT_FK, tpra.STATUS
 FROM TEMP_PAYROLL_RUN_ACTION tpra WHERE 
                                   tpra.STATUS = pra.STATUS AND 
                                   tpra.ACTION_EVENT_FK = pra.ACTION_EVENT_FK )
/



--------------------------------------------------------
-- Drop temp table                                  --
--------------------------------------------------------
DROP TABLE TEMP_PAYROLL_RUN_ACTION

/
COMMIT
 

