DECLARE

	table_exists PLS_INTEGER;

BEGIN


	SELECT COUNT(*) INTO table_exists
	FROM "USER_TABLES"
	WHERE TABLE_NAME = 'TEMP_PSP_SVCSTAT_SPS_ASSOC';

	IF table_exists = 1 THEN
		EXECUTE IMMEDIATE 'DROP TABLE "TEMP_PSP_SVCSTAT_SPS_ASSOC" CASCADE CONSTRAINTS';
	END IF;

END;

/

--------------------------------------------------------
-- Create temp table                                  --
--------------------------------------------------------

CREATE TABLE TEMP_PSP_SVCSTAT_SPS_ASSOC
(
  SERVICE_SUB_STATUS_FK  VARCHAR2(255 CHAR)         NOT NULL,
  SOURCE_SYSTEM_FK   VARCHAR2(255 CHAR)         NOT NULL
)

/

--------------------------------------------------------
-- Insert into temp table                             --
--------------------------------------------------------
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('AchRejectOther', 'QBOE')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('AchRejectOther', 'QBDT')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('AchRejectR1R9', 'QBOE')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('AchRejectR1R9', 'QBDT')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('ActiveCurrent', 'QBOE')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('ActiveCurrent', 'QBDT')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('ActiveSeasonal', 'QBOE')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('ActiveSeasonal', 'QBDT')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('AS400Hold', 'QBDT')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('AS400DirectDepositLimitHold', 'QBDT')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('AuditCorrections', 'QBOE')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('AuditCorrections', 'QBDT')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('Cancelled', 'QBOE')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('Cancelled', 'QBDT')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('BillPaymentLimit', 'QBOE')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('BillPaymentLimit', 'QBDT')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('DirectDepositLimit', 'QBOE')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('DirectDepositLimit', 'QBDT')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('Fraud', 'QBOE')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('Fraud', 'QBDT')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('AMLHold', 'QBOE')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('AMLHold', 'QBDT')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('FraudReview', 'QBOE')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('FraudReview', 'QBDT')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('IntuitCollections', 'QBOE')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('IntuitCollections', 'QBDT')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('MissingPaperwork', 'QBOE')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('MissingPaperwork', 'QBDT')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('PendingBalanceFile', 'QBOE')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('PendingBalanceFile', 'QBDT')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('PendingSetup', 'QBDT')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('PendingBankVerification', 'QBOE')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('PendingBankVerification', 'QBDT')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('PendingFirstPayroll', 'QBOE')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('PendingFirstPayroll', 'QBDT')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('PendingPinCreation', 'QBDT')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('PendingPrefundingWire', 'QBDT')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('PendingPrefundingWire', 'QBOE')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('PendingTermination', 'QBOE')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('PendingTermination', 'QBDT')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('RiskAssessment', 'QBOE')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('RiskAssessment', 'QBDT')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('RiskCollections', 'QBOE')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('RiskCollections', 'QBDT')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('SuspendedDirectDeposit', 'QBOE')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('SuspendedDirectDeposit', 'QBDT')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('Terminated', 'QBOE')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('Terminated', 'QBDT')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('MTLHold', 'QBOE')
/
INSERT INTO TEMP_PSP_SVCSTAT_SPS_ASSOC ( SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)  VALUES ('MTLHold', 'QBDT')
/

--------------------------------------------------------
-- Sychronize temp table and real table by            --
-- inserting, deleting, and updating as necessary     --
--------------------------------------------------------

INSERT INTO PSP_SVCSTAT_SRCSYS_ASSOC
   (SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK)
SELECT
    SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK
FROM
   TEMP_PSP_SVCSTAT_SPS_ASSOC sc
WHERE
   (sc.SERVICE_SUB_STATUS_FK, sc.SOURCE_SYSTEM_FK) NOT IN (SELECT SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK FROM PSP_SVCSTAT_SRCSYS_ASSOC)

/
DELETE FROM PSP_SVCSTAT_SRCSYS_ASSOC
WHERE (SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK) NOT IN (SELECT SERVICE_SUB_STATUS_FK, SOURCE_SYSTEM_FK FROM TEMP_PSP_SVCSTAT_SPS_ASSOC)

/

--------------------------------------------------------
-- Drop temp table                                  --
--------------------------------------------------------
DROP TABLE TEMP_PSP_SVCSTAT_SPS_ASSOC

/
COMMIT



