DECLARE

	table_exists PLS_INTEGER;

BEGIN


	SELECT COUNT(*) INTO table_exists
	FROM "USER_TABLES"
	WHERE TABLE_NAME = 'TEMP_PSP_SYSTEM_CAPABILITY';

	IF table_exists = 1 THEN
		EXECUTE IMMEDIATE 'DROP TABLE "TEMP_PSP_SYSTEM_CAPABILITY" CASCADE CONSTRAINTS';
	END IF;

END;

/

--------------------------------------------------------
-- Create temp table                                  --
--------------------------------------------------------
CREATE TABLE TEMP_PSP_SYSTEM_CAPABILITY
(
  SYSTEM_CAPABILITY_CD  VARCHAR2(255)      NOT NULL,
  VERSION               NUMBER(19)         NOT NULL,
  DESCRIPTION           VARCHAR2(2000)
)

/

--------------------------------------------------------
-- Insert into temp table                             --
--------------------------------------------------------
INSERT INTO TEMP_PSP_SYSTEM_CAPABILITY ( SYSTEM_CAPABILITY_CD, DESCRIPTION, VERSION)  VALUES (
'AddService', '', 0)
/
INSERT INTO TEMP_PSP_SYSTEM_CAPABILITY ( SYSTEM_CAPABILITY_CD, DESCRIPTION, VERSION)  VALUES (
'CancelService', '', 0)
/
INSERT INTO TEMP_PSP_SYSTEM_CAPABILITY ( SYSTEM_CAPABILITY_CD, DESCRIPTION, VERSION)  VALUES (
'ChangeCompanyInfo', '', 0)
/
INSERT INTO TEMP_PSP_SYSTEM_CAPABILITY ( SYSTEM_CAPABILITY_CD, DESCRIPTION, VERSION)  VALUES (
'ChangeEmployeeBankAccount', '', 0)
/
INSERT INTO TEMP_PSP_SYSTEM_CAPABILITY ( SYSTEM_CAPABILITY_CD, DESCRIPTION, VERSION)  VALUES (
'ChangeEmployerBankAccount', '', 0)
/
INSERT INTO TEMP_PSP_SYSTEM_CAPABILITY ( SYSTEM_CAPABILITY_CD, DESCRIPTION, VERSION)  VALUES (
'AddEmployerBankAccount', '', 0)
/
INSERT INTO TEMP_PSP_SYSTEM_CAPABILITY ( SYSTEM_CAPABILITY_CD, DESCRIPTION, VERSION)  VALUES (
'VerifyCompanyBankAccount', '', 0)
/
INSERT INTO TEMP_PSP_SYSTEM_CAPABILITY ( SYSTEM_CAPABILITY_CD, DESCRIPTION, VERSION)  VALUES (
'RefundOrCredit', '', 0)
/
INSERT INTO TEMP_PSP_SYSTEM_CAPABILITY ( SYSTEM_CAPABILITY_CD, DESCRIPTION, VERSION)  VALUES (
'SubmitPayroll', '', 0)
/
INSERT INTO TEMP_PSP_SYSTEM_CAPABILITY ( SYSTEM_CAPABILITY_CD, DESCRIPTION, VERSION)  VALUES (
'SynchronizeAccount', '', 0)
/
INSERT INTO TEMP_PSP_SYSTEM_CAPABILITY ( SYSTEM_CAPABILITY_CD, DESCRIPTION, VERSION)  VALUES (
'UpgradeFundingModel', '', 0)
/
INSERT INTO TEMP_PSP_SYSTEM_CAPABILITY ( SYSTEM_CAPABILITY_CD, DESCRIPTION, VERSION)  VALUES (
'RecallPayroll', '', 0)
/
INSERT INTO TEMP_PSP_SYSTEM_CAPABILITY ( SYSTEM_CAPABILITY_CD, DESCRIPTION, VERSION)  VALUES (
'UpdatePIN', '', 0)
/
INSERT INTO TEMP_PSP_SYSTEM_CAPABILITY ( SYSTEM_CAPABILITY_CD, DESCRIPTION, VERSION)  VALUES (
'VoidPayroll', '', 0)
/
INSERT INTO TEMP_PSP_SYSTEM_CAPABILITY ( SYSTEM_CAPABILITY_CD, DESCRIPTION, VERSION)  VALUES (
'SubmitPayment', '', 0)
/
INSERT INTO TEMP_PSP_SYSTEM_CAPABILITY ( SYSTEM_CAPABILITY_CD, DESCRIPTION, VERSION)  VALUES (
'RecallPayment', '', 0)
/
--------------------------------------------------------
-- Sychronize temp table and real table by            --
-- inserting, deleting, and updating as necessary     --
--------------------------------------------------------

INSERT INTO PSP_SYSTEM_CAPABILITY
   (SYSTEM_CAPABILITY_CD, DESCRIPTION, VERSION)
SELECT
    SYSTEM_CAPABILITY_CD, DESCRIPTION, VERSION
FROM
   TEMP_PSP_SYSTEM_CAPABILITY sc
WHERE
   sc.SYSTEM_CAPABILITY_CD NOT IN (SELECT SYSTEM_CAPABILITY_CD FROM PSP_SYSTEM_CAPABILITY)

/

-- delete children first
DELETE FROM PSP_SVCSTAT_SYSCAP_ASSOC
WHERE SYSTEM_CAPABILITY_FK NOT IN (SELECT SYSTEM_CAPABILITY_CD FROM TEMP_PSP_SYSTEM_CAPABILITY)

/

DELETE FROM PSP_SYSTEM_CAPABILITY
WHERE SYSTEM_CAPABILITY_CD NOT IN (SELECT SYSTEM_CAPABILITY_CD FROM TEMP_PSP_SYSTEM_CAPABILITY)

/

UPDATE PSP_SYSTEM_CAPABILITY rt
SET ( rt.DESCRIPTION, rt.VERSION) =
(SELECT sc.DESCRIPTION, sc.VERSION
 FROM TEMP_PSP_SYSTEM_CAPABILITY sc WHERE sc.SYSTEM_CAPABILITY_CD = rt.SYSTEM_CAPABILITY_CD)
/



--------------------------------------------------------
-- Drop temp table                                  --
--------------------------------------------------------
DROP TABLE TEMP_PSP_SYSTEM_CAPABILITY

/
COMMIT



