DECLARE
	
	table_exists PLS_INTEGER;

BEGIN


	SELECT COUNT(*) INTO table_exists
	FROM "USER_TABLES"
	WHERE TABLE_NAME = 'TEMP_PSP_SERVICE';

	IF table_exists = 1 THEN
		EXECUTE IMMEDIATE 'DROP TABLE "TEMP_PSP_SERVICE" CASCADE CONSTRAINTS';
	END IF;

END;

/

--------------------------------------------------------
-- Create temp table                                  --
--------------------------------------------------------
CREATE TABLE TEMP_PSP_SERVICE
(
	"SERVICE_CD" VARCHAR2(255 CHAR) NOT NULL,
	"VERSION" NUMBER(19,0) NOT NULL, 
	"DESCRIPTION" VARCHAR2(4000 CHAR),  
	"NAME" VARCHAR2(4000 CHAR),
	"CAN_BE_MANUALLY_CANCELLED" NUMBER(1,0),
	"PSP_PROVIDES_CUSTOMER_SERVICE" NUMBER(1,0)
)

/

-- delete service codes that do not exist any more from PSP_SVCSTAT_SVC_ASSOC
DELETE FROM PSP_SVCSTAT_SVC_ASSOC WHERE SERVICE_FK NOT IN (SELECT DISTINCT SERVICE_CD FROM TEMP_PSP_SERVICE)
/

--------------------------------------------------------
-- Insert into temp table                             --
--------------------------------------------------------

INSERT INTO TEMP_PSP_SERVICE (SERVICE_CD, NAME, CAN_BE_MANUALLY_CANCELLED, DESCRIPTION, VERSION, PSP_PROVIDES_CUSTOMER_SERVICE) VALUES ( 
'DirectDeposit', 'Direct Deposit Service', 1, 'A METHOD TO TRANSFER MONEY ELECTRONICALLY FROM ONE PARTY TO ANOTHER, TYPICALLY FROM A COMPANY TO AN EMPLOYEE', 0, 1)
/

INSERT INTO TEMP_PSP_SERVICE (SERVICE_CD, NAME, CAN_BE_MANUALLY_CANCELLED, DESCRIPTION, VERSION, PSP_PROVIDES_CUSTOMER_SERVICE) VALUES ( 
'Tax', 'Assisted Service', 1, '', 0, 1)
/

INSERT INTO TEMP_PSP_SERVICE (SERVICE_CD, NAME, CAN_BE_MANUALLY_CANCELLED, DESCRIPTION, VERSION, PSP_PROVIDES_CUSTOMER_SERVICE) VALUES ( 
'BillPayment', 'Bill Payment Service', 1, 'A METHOD TO TRANSFER MONEY ELECTRONICALLY FROM ONE PARTY TO ANOTHER, TYPICALLY FROM A COMPANY TO A THIRD PARTY', 0, 1)
/

INSERT INTO TEMP_PSP_SERVICE (SERVICE_CD, NAME, CAN_BE_MANUALLY_CANCELLED, DESCRIPTION, VERSION, PSP_PROVIDES_CUSTOMER_SERVICE) VALUES ( 
'ThirdParty401k', 'Third Party 401k Service', 0, 'A METHOD TO TRANSFER 401K DATA TO A THIRD PARTY PROVIDER', 0, 1)
/

INSERT INTO TEMP_PSP_SERVICE (SERVICE_CD, NAME, CAN_BE_MANUALLY_CANCELLED, DESCRIPTION, VERSION, PSP_PROVIDES_CUSTOMER_SERVICE) VALUES (
'CheckDistribution', 'Check Distribution Service', 1, 'A METHOD TO PRINT PAYCHECKS FOR CUSTOMERS', 0, 1)
/

INSERT INTO TEMP_PSP_SERVICE (SERVICE_CD, NAME, CAN_BE_MANUALLY_CANCELLED, DESCRIPTION, VERSION, PSP_PROVIDES_CUSTOMER_SERVICE) VALUES (
'Cloud', 'Intuit Services', 1, 'A METHOD TO COLLECT ADDITIONAL COMPANY AND PAYROLL DATA FOR NEW SERVICES', 0, 0)
/

INSERT INTO TEMP_PSP_SERVICE (SERVICE_CD, NAME, CAN_BE_MANUALLY_CANCELLED, DESCRIPTION, VERSION, PSP_PROVIDES_CUSTOMER_SERVICE) VALUES (
'RiskAssessment', 'Risk Assessment Service', 0, '', 0, 0)
/

INSERT INTO TEMP_PSP_SERVICE (SERVICE_CD, NAME, CAN_BE_MANUALLY_CANCELLED, DESCRIPTION, VERSION, PSP_PROVIDES_CUSTOMER_SERVICE) VALUES ( 
'WorkersComp', 'Workers Compensation Service', 0, 'A METHOD TO TRANSFER WORKERS COMPENSATION DATA', 0, 1)
/

INSERT INTO TEMP_PSP_SERVICE (SERVICE_CD, NAME, CAN_BE_MANUALLY_CANCELLED, DESCRIPTION, VERSION, PSP_PROVIDES_CUSTOMER_SERVICE) VALUES (
'ViewMyPaycheck', 'View My Paycheck Service', 1, 'A METHOD TO TRANSFER AND VIEW PAYCHECKS', 0, 1)
/

INSERT INTO TEMP_PSP_SERVICE (SERVICE_CD, NAME, CAN_BE_MANUALLY_CANCELLED, DESCRIPTION, VERSION, PSP_PROVIDES_CUSTOMER_SERVICE) VALUES (
  'CloudV2', 'New Cloud V2 Service', 1, 'A METHOD TO COLLECT ADDITIONAL COMPANY AND PAYROLL DATA FOR NEW SERVICES', 0, 1)
/
INSERT INTO TEMP_PSP_SERVICE (SERVICE_CD, NAME, CAN_BE_MANUALLY_CANCELLED, DESCRIPTION, VERSION, PSP_PROVIDES_CUSTOMER_SERVICE) VALUES (
  'Guideline401k', 'Guideline 401k Service', 0, 'A METHOD TO TRANSFER 401K DATA TO GUIDELINE', 0, 0)
/
INSERT INTO TEMP_PSP_SERVICE (SERVICE_CD, NAME, CAN_BE_MANUALLY_CANCELLED, DESCRIPTION, VERSION, PSP_PROVIDES_CUSTOMER_SERVICE) VALUES (
    'CloudV3', 'Cloud V3 Service', 0, 'A METHOD TO TELL PSP CONTAIN FULL CUSTOMER DATA', 0, 0)
/

--------------------------------------------------------
-- Sychronize temp table and real table by            --
-- inserting, deleting, and updating as necessary     --
--------------------------------------------------------

INSERT INTO PSP_SERVICE
   (SERVICE_CD, NAME, DESCRIPTION, VERSION, CAN_BE_MANUALLY_CANCELLED, PSP_PROVIDES_CUSTOMER_SERVICE)
SELECT 
    SERVICE_CD, NAME, DESCRIPTION, VERSION, CAN_BE_MANUALLY_CANCELLED, PSP_PROVIDES_CUSTOMER_SERVICE
FROM 
   TEMP_PSP_SERVICE tt 
WHERE 
   tt.SERVICE_CD NOT IN (SELECT SERVICE_CD FROM PSP_SERVICE)

/

DELETE FROM PSP_SERVICE
WHERE SERVICE_CD NOT IN (SELECT SERVICE_CD FROM TEMP_PSP_SERVICE) 

/

UPDATE PSP_SERVICE rt
SET ( rt.NAME, rt.DESCRIPTION, rt.VERSION, rt.CAN_BE_MANUALLY_CANCELLED, rt.PSP_PROVIDES_CUSTOMER_SERVICE) =
(SELECT tt.NAME, tt.DESCRIPTION, tt.VERSION, tt.CAN_BE_MANUALLY_CANCELLED, tt.PSP_PROVIDES_CUSTOMER_SERVICE
 FROM TEMP_PSP_SERVICE tt WHERE tt.SERVICE_CD = rt.SERVICE_CD)
/



--------------------------------------------------------
-- Drop temp table                                  --
--------------------------------------------------------
DROP TABLE TEMP_PSP_SERVICE

/
COMMIT
 

 
