package com.intuit.spc.foundations.primary.config;

import com.intuit.spc.foundations.primary.config.util.SpcfConfigErrorEnum;

/**
 * @author yzhang
 */
public class SpcfConfigFileTooBigException extends SpcfConfigModuleException
{
    /**
     * Auto generated by Eclipse
     */
    private static final long serialVersionUID = 1981534212028934684L;

    /**
     * @param fileName the name of the file
     */
    public SpcfConfigFileTooBigException(String fileName)
    {
        super("The file is over the allowed size limit (" + SpcfConfigurationManager.OVERALL_FILE_SIZE_LIMIT
                        + " bytes): " + fileName);
    }

    @Override
    SpcfConfigErrorEnum getSpcfConfigError()
    {
        return SpcfConfigErrorEnum.FileTooBigError;
    }
}
