UPDATE PSP_LAW
SET IS_EMPLOYER_TAX = '1'
;

UPDATE PSP_LAW law
SET IS_EMPLOYER_TAX = '0'
WHERE cast(law.LAW_ID as int) between 1 and 61
;

UPDATE PSP_LAW law
SET IS_EMPLOYER_TAX = '0'
WHERE law.LAW_ID in ('63', '67', '69', '70', '72', '75', '135', '136', '137', '168', '170', '172', '173', '191', '194', '200', '207')
;


DROP TABLE IF EXISTS TEMP_PSP_LAW CASCADE

;

--------------------------------------------------------
-- Create temp table                                  --
--------------------------------------------------------

CREATE TABLE TEMP_PSP_LAW (LIKE PSP_LAW INCLUDING ALL)

;

--------------------------------------------------------
-- Insert into temp table                             --
--------------------------------------------------------
 
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('2', 'AK-SIT', 'AK-SIT', 'AK-NOCALC' , 0, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('11', 'FL-SIT', 'FL-SIT', 'FL-NOCALC' , 0, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('32', 'NH-SIT', 'NH-SIT', 'NH-NOCALC' , 0, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('35', 'NV-SIT', 'NV-SIT', 'NV-NOCALC' , 0, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('41', 'PR-SIT', 'PR-SIT', 'PR-NOCALC' , 0, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('44', 'SD-SIT', 'SD-SIT', 'SD-NOCALC' , 0, 0) 
   ;   
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('45', 'TN-SIT', 'TN-SIT', 'TN-NOCALC' , 0, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('46', 'TX-SIT', 'TX-SIT', 'TX-NOCALC' , 0, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('50', 'WA-SIT', 'WA-SIT', 'WA-NOCALC' , 0, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('53', 'WY-SIT', 'WY-SIT', 'WY-NOCALC' , 0, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('55', 'LWT-NYCNR', 'LWT-NYCNR', 'NY-NOCALC' , 0, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('58', 'LWT-MC', 'LWT-MC', 'MI-NOCALC' , 0, 0) 
   ;   
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('68', 'HI-SDI-EE', 'HI-SDI-EE', 'HI-NOCALC' , 0, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('71', 'PR-SDI-EE', 'PR-SDI-EE', 'PR-NOCALC' , 0, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('74', 'PR-SDI-ER', 'PR-SDI-ER', 'PR-NOCALC' , 0, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('122', 'PR-SUI-ER', 'PR-SUI-ER', 'PR-NOCALC' , 0, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('149', 'SUP-KY-SCUF', 'SUP-KY-SCUF', 'KY-NOCALC' , 0, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('165', 'SUP-MT-OLFR', 'SUP-MT-OLFR', 'MT-NOCALC' , 0, 0)
   ;   
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('166', 'SUP-MT-OFLE', 'SUP-MT-OFLE', 'MT-NOCALC' , 0, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('177', 'LAW-177', 'LAW-177', '177-NOCALC' , 0, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('178', 'SUP-NC-TRT', 'SUP-NC-TRT', 'NC-NOCALC' , 0, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('180', 'LWT-RI-ESRT', 'LWT-RI-ESRT', 'RI-NOCALC' , 0, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('181', 'LWT-CRT', 'LWT-CRT', 'MI-NOCALC' , 0, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('182', 'SUP-PR-SAT', 'SUP-PR-SAT', 'PR-NOCALC' , 0, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('193', 'UHI', 'UHI', 'MA-NOCALC' , 0, 0) 
   ;   
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('195', 'UIAS', 'UIAS', 'MO-NOCALC' , 0, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('0', 'Other', 'Other Tax', 'MN_UI' , 0, 0)
   ; 
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('900', 'AL_SUI_EE', 'AL_SUI_EE', 'AL-NOCALC' , 0, 0)
   ;  
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('901', 'AZ_SUI_EE', 'AZ_SUI_EE', 'AZ-NOCALC' ,  0, 0)
   ; 
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('902', 'CA_SDI_ER', 'CA_SDI_ER', 'CA-NOCALC' , 0, 0)
   ; 
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('903', 'CA_SUI_EE', 'CA_SUI_EE', 'CA-NOCALC' ,  0, 0)
   ; 
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('904', 'CO_SUI_EE', 'CO_SUI_EE', 'CO-NOCALC' ,  0, 0)
   ; 
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('905', 'DC_SUI_EE', 'DC_SUI_EE', 'DC-NOCALC' ,  0, 0)
   ; 
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('906', 'FL_SUI_EE', 'FL_SUI_EE', 'FL-NOCALC' ,  0, 0)
   ; 
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('907', 'GA_SUI_EE', 'GA_SUI_EE', 'GA-NOCALC' ,  0, 0)
   ; 
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('908', 'IL_SUI_EE', 'IL_SUI_EE', 'IL-NOCALC' ,  0, 0)
   ; 
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('909', 'LA_SUI_EE', 'LA_SUI_EE', 'LA-NOCALC' ,  0, 0)
   ; 
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('910', 'MA_SUI_EE', 'MA_SUI_EE', 'MA-NOCALC' ,  0, 0)
   ; 
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('911', 'MD_SDI_EE', 'MD_SDI_EE', 'MD-NOCALC' , 0, 0)
   ; 
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('912', 'MD_SUI_EE', 'MD_SUI_EE', 'MD-NOCALC' ,  0, 0)
   ; 
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('913', 'ME_SUI_EE', 'ME_SUI_EE', 'ME-NOCALC' ,  0, 0)
   ; 
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('914', 'MI_SUI_EE', 'MI_SUI_EE', 'MI-NOCALC' ,  0, 0)
   ; 
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('915', 'NC_SUI_EE', 'NC_SUI_EE', 'NC-NOCALC' ,  0, 0)
   ; 
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('916', 'NM_SUI_EE', 'NM_SUI_EE', 'NM-NOCALC' ,  0, 0)
   ; 
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('917', 'NY_SUI_EE', 'NY_SUI_EE', 'NY-NOCALC' ,  0, 0)
   ; 
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('918', 'OK_SUI_EE', 'OK_SUI_EE', 'OK-NOCALC' ,  0, 0)
   ; 
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('919', 'OR_SDI_EE', 'OR_SDI_EE', 'OR-NOCALC' , 0, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('920', 'OR_SDI_ER', 'OR_SDI_ER', 'OR-NOCALC' , 0, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('921', 'OR_SUI_EE', 'OR_SUI_EE', 'OR-NOCALC' ,  0, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('922', 'VA_SUI_EE', 'VA_SUI_EE', 'VA-NOCALC' ,  0, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('923', 'VT_SDI_ER', 'VT_SDI_ER', 'VT-NOCALC' , 0, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('924', 'VT_SUI_EE', 'VT_SUI_EE', 'VT-NOCALC' ,  0, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('925', 'WA_SUI_EE', 'WA_SUI_EE', 'WA-NOCALC' ,  0, 0)
   ;  
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('926', '9-NOCALC', '9-NOCALC', '9-NOCALC' , 0, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('203', 'NY_FL', 'New York-Family Leave', 'NY-NOCALC' , 0, 0)
   ;

   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('208', 'PFL', 'DC Paid Family Leave', 'DC-PFL-PAYMENT' , 1, 0)
   ;
    --PSP-17930 START
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('209', 'PaidMedicalLeaveER', 'MA Paid Family and Medical Leave', 'MA-PFML-PAYMENT' , 1, 0)
   ;

   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('210', 'PaidMedicalLeaveEE', 'MA Paid Family and Medical Leave', 'MA-PFML-PAYMENT' , 1, 0)
   ;

   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('211', 'PaidFamilyLeaveER', 'MA Paid Family and Medical Leave', 'MA-PFML-PAYMENT' , 1, 0)
   ;

   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('212', 'PaidFamilyLeaveEE', 'MA Paid Family and Medical Leave', 'MA-PFML-PAYMENT' , 1, 0)
   ;
   -- NE Law_id
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('213', 'UI Wage Base Increase', 'NE UI Wage Base Increase', 'NE-UI11T-PAYMENT' , 1, 0)
   ;
  --PSP-17930-END
  INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('214', 'FFCRA Credit', 'National Paid Leave Credit', 'IRS-941-PAYMENT' , 1, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('215', 'CARES Credit', 'CARES Retention Credit', 'IRS-941-PAYMENT' , 1, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('216', 'CARES FICA-ER Deferral', 'CARES FICA-ER Deferral', 'IRS-941-PAYMENT' , 1, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('9178', 'Covid Advance', 'Covid Advance', 'IRS-941-PAYMENT' , 1, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('217', 'FICA-EE Deferral', 'FICA-EE Deferral', 'IRS-941-PAYMENT' , 0, 0)
   ;

   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('218', 'PaidMedicalLeaveEE', 'CT Paid Leave', 'CT-PFML-PAYMENT' , 1, 0)
   ;

   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('219', 'UPAF', 'UI Program Admin. Fund', 'ME-941C1ME-PAYMENT' , 1, 0)
   ;

   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('220', 'MA Covid Recovery Assmnt', 'Covid-19 Recovery Assessment', 'MA-1700HI-PAYMENT' , 1, 0)
   ;

   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('221', 'CaresEE', 'WA Cares Fund', 'WA-CARES-PAYMENT' , 0, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('222', 'FAMLI ER', 'CO FAMLI ER', 'CO-FAMLI-PAYMENT' , 1, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('223', 'FAMLI EE', 'CO FAMLI EE', 'CO-FAMLI-PAYMENT' , 0, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('224', 'PaidLeaveER', 'OR Paid Leave ER', 'OR-PFMSL-PAYMENT' , 1, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('225', 'PaidLeaveEE', 'OR Paid Leave EE', 'OR-PFMSL-PAYMENT' , 0, 0)
   ;
   INSERT INTO TEMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX, VERSION )
   VALUES ('226', 'Metro Zone 2', 'MCTMT (Zone 2 Transit Tax)', 'NY-MTA305-PAYMENT' , 0, 0)
   ;
---------------------------------------------
-- Sychronize temp table and real table by            --
-- inserting, deleting, and updating as necessary     --
--------------------------------------------------------

INSERT INTO PSP_LAW
   (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, VERSION, IS_EMPLOYER_TAX)
SELECT
    LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, 0 , IS_EMPLOYER_TAX
FROM
   TEMP_PSP_LAW tt
WHERE
   tt.LAW_ID NOT IN (SELECT LAW_ID FROM PSP_LAW)

;

UPDATE PSP_LAW rt
SET (LAW_ID,LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, IS_EMPLOYER_TAX) =
(SELECT  tt.LAW_ID, tt.LAW_ABBREV, tt.DESCRIPTION, tt.PAYMENT_TEMPLATE_FK, tt.IS_EMPLOYER_TAX
 FROM TEMP_PSP_LAW tt WHERE tt.LAW_ID = rt.LAW_ID)
 WHERE rt.LAW_ID IN (SELECT LAW_ID FROM TEMP_PSP_LAW)
;


--------------------------------------------------------
-- Update law tax type codes with ATF data

-- query to recreate script
/*
SELECT 'UPDATE PSP_LAW SET LAW_TYPE_CD = ''' ||
DECODE(tax_type_cd, 'SDI-EE', REGION_CD || ' ' || TAX_TYPE_CD,
               'SDI-ER', REGION_CD || ' ' || TAX_TYPE_CD,
               'SUI-EE', REGION_CD || ' ' || TAX_TYPE_CD,
               'SUI-ER', REGION_CD || ' ' || TAX_TYPE_CD,
               'SWT', REGION_CD || ' ' || TAX_TYPE_CD,
               TAX_TYPE_CD) ||
''' WHERE LAW_ID = ''' || source_tax_cd || '''' || CHR(13) || CHR(10) || ';'
FROM REGIONTAX_PAYROLL_ASSOC
WHERE payroll_system_cd = 'QB'
AND tax_type_cd NOT IN ('MEDI-TIPS', 'FICA-TIPS')
ORDER BY TO_NUMBER(source_tax_cd)
*/
--------------------------------------------------------

UPDATE PSP_LAW SET LAW_TYPE_CD = 'FWT' WHERE LAW_ID = '1'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'AK SWT' WHERE LAW_ID = '2'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'AL SWT' WHERE LAW_ID = '3'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'AR SWT' WHERE LAW_ID = '4'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'AZ SWT' WHERE LAW_ID = '5'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'CA SWT' WHERE LAW_ID = '6'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'CO SWT' WHERE LAW_ID = '7'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'CT SWT' WHERE LAW_ID = '8'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'DC SWT' WHERE LAW_ID = '9'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'DE SWT' WHERE LAW_ID = '10'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'FL SWT' WHERE LAW_ID = '11'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'GA SWT' WHERE LAW_ID = '12'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'HI SWT' WHERE LAW_ID = '13'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'IA SWT' WHERE LAW_ID = '14'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'ID SWT' WHERE LAW_ID = '15'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'IL SWT' WHERE LAW_ID = '16'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'IN SWT' WHERE LAW_ID = '17'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'KS SWT' WHERE LAW_ID = '18'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'KY SWT' WHERE LAW_ID = '19'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'LA SWT' WHERE LAW_ID = '20'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'MA SWT' WHERE LAW_ID = '21'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'MD SWT' WHERE LAW_ID = '22'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'ME SWT' WHERE LAW_ID = '23'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'MI SWT' WHERE LAW_ID = '24'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'MN SWT' WHERE LAW_ID = '25'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'MO SWT' WHERE LAW_ID = '26'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'MS SWT' WHERE LAW_ID = '27'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'MT SWT' WHERE LAW_ID = '28'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'NC SWT' WHERE LAW_ID = '29'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'ND SWT' WHERE LAW_ID = '30'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'NE SWT' WHERE LAW_ID = '31'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'NH SWT' WHERE LAW_ID = '32'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'NJ SWT' WHERE LAW_ID = '33'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'NM SWT' WHERE LAW_ID = '34'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'NV SWT' WHERE LAW_ID = '35'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'NY SWT' WHERE LAW_ID = '36'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'OH SWT' WHERE LAW_ID = '37'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'OK SWT' WHERE LAW_ID = '38'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'OR SWT' WHERE LAW_ID = '39'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'PA SWT' WHERE LAW_ID = '40'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'PR SWT' WHERE LAW_ID = '41'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'RI SWT' WHERE LAW_ID = '42'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SC SWT' WHERE LAW_ID = '43'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SD SWT' WHERE LAW_ID = '44'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'TN SWT' WHERE LAW_ID = '45'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'TX SWT' WHERE LAW_ID = '46'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'UT SWT' WHERE LAW_ID = '47'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'VA SWT' WHERE LAW_ID = '48'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'VT SWT' WHERE LAW_ID = '49'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'WA SWT' WHERE LAW_ID = '50'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'WI SWT' WHERE LAW_ID = '51'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'WV SWT' WHERE LAW_ID = '52'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'WY SWT' WHERE LAW_ID = '53'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'LWT-NYCR' WHERE LAW_ID = '54'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'LWT-NYCNR' WHERE LAW_ID = '55'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'LWT-YR' WHERE LAW_ID = '56'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'LWT-YNR' WHERE LAW_ID = '57'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'LWT-MC' WHERE LAW_ID = '58'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'LWT-IC' WHERE LAW_ID = '59'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'LWT-OSD' WHERE LAW_ID = '60'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'FICA-EE' WHERE LAW_ID = '61'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'FICA-ER' WHERE LAW_ID = '62'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'FMED-EE' WHERE LAW_ID = '63'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'FMED-ER' WHERE LAW_ID = '64'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'FUTA' WHERE LAW_ID = '66'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'ADDMED-EE' WHERE LAW_ID = '200'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'CA SDI-EE' WHERE LAW_ID = '67'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'HI SDI-EE' WHERE LAW_ID = '68'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'NJ SDI-EE' WHERE LAW_ID = '69'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'NY SDI-EE' WHERE LAW_ID = '70'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'PR SDI-EE' WHERE LAW_ID = '71'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'RI SDI-EE' WHERE LAW_ID = '72'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'NJ SDI-ER' WHERE LAW_ID = '73'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'PR SDI-ER' WHERE LAW_ID = '74'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'NY SDI-ER' WHERE LAW_ID = '75'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'AK SUI-ER' WHERE LAW_ID = '83'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'AL SUI-ER' WHERE LAW_ID = '84'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'AR SUI-ER' WHERE LAW_ID = '85'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'AZ SUI-ER' WHERE LAW_ID = '86'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'CA SUI-ER' WHERE LAW_ID = '87'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'CO SUI-ER' WHERE LAW_ID = '88'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'CT SUI-ER' WHERE LAW_ID = '89'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'DC SUI-ER' WHERE LAW_ID = '90'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'DE SUI-ER' WHERE LAW_ID = '91'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'FL SUI-ER' WHERE LAW_ID = '92'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'GA SUI-ER' WHERE LAW_ID = '93'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'HI SUI-ER' WHERE LAW_ID = '94'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'IA SUI-ER' WHERE LAW_ID = '95'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'ID SUI-ER' WHERE LAW_ID = '96'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'IL SUI-ER' WHERE LAW_ID = '97'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'IN SUI-ER' WHERE LAW_ID = '98'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'KS SUI-ER' WHERE LAW_ID = '99'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'KY SUI-ER' WHERE LAW_ID = '100'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'LA SUI-ER' WHERE LAW_ID = '101'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'MA SUI-ER' WHERE LAW_ID = '102'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'MD SUI-ER' WHERE LAW_ID = '103'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'ME SUI-ER' WHERE LAW_ID = '104'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'MI SUI-ER' WHERE LAW_ID = '105'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'MN SUI-ER' WHERE LAW_ID = '106'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'MO SUI-ER' WHERE LAW_ID = '107'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'MS SUI-ER' WHERE LAW_ID = '108'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'MT SUI-ER' WHERE LAW_ID = '109'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'NC SUI-ER' WHERE LAW_ID = '110'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'ND SUI-ER' WHERE LAW_ID = '111'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'NE SUI-ER' WHERE LAW_ID = '112'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'NH SUI-ER' WHERE LAW_ID = '113'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'NJ SUI-ER' WHERE LAW_ID = '114'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'NM SUI-ER' WHERE LAW_ID = '115'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'NV SUI-ER' WHERE LAW_ID = '116'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'NY SUI-ER' WHERE LAW_ID = '117'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'OH SUI-ER' WHERE LAW_ID = '118'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'OK SUI-ER' WHERE LAW_ID = '119'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'OR SUI-ER' WHERE LAW_ID = '120'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'PA SUI-ER' WHERE LAW_ID = '121'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'PR SUI-ER' WHERE LAW_ID = '122'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'RI SUI-ER' WHERE LAW_ID = '123'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SC SUI-ER' WHERE LAW_ID = '124'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SD SUI-ER' WHERE LAW_ID = '125'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'TN SUI-ER' WHERE LAW_ID = '126'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'TX SUI-ER' WHERE LAW_ID = '127'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'UT SUI-ER' WHERE LAW_ID = '128'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'VA SUI-ER' WHERE LAW_ID = '129'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'VT SUI-ER' WHERE LAW_ID = '130'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'WA SUI-ER' WHERE LAW_ID = '131'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'WI SUI-ER' WHERE LAW_ID = '132'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'WV SUI-ER' WHERE LAW_ID = '133'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'WY SUI-ER' WHERE LAW_ID = '134'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'AK SUI-EE' WHERE LAW_ID = '135'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'NJ SUI-EE' WHERE LAW_ID = '136'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'PA SUI-EE' WHERE LAW_ID = '137'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'ETT' WHERE LAW_ID = '142'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'FEIC' WHERE LAW_ID = '143'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-AL ESC' WHERE LAW_ID = '144'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-AR ST' WHERE LAW_ID = '145'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-ID WDF' WHERE LAW_ID = '146'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-MT AFT' WHERE LAW_ID = '147'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-NE UIT' WHERE LAW_ID = '148'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-NE WBI' WHERE LAW_ID = '213'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-KY SCUF' WHERE LAW_ID = '149'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-MA WTF' WHERE LAW_ID = '150'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-TN JSF' WHERE LAW_ID = '151'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-NY RSF' WHERE LAW_ID = '152'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-CO ST' WHERE LAW_ID = '153'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-GA AA' WHERE LAW_ID = '154'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP HI ETA' WHERE LAW_ID = '155'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-IA AST' WHERE LAW_ID = '156'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-ME ST' WHERE LAW_ID = '157'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-MN DWA' WHERE LAW_ID = '158'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-NV CEP' WHERE LAW_ID = '159'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-RI JDF' WHERE LAW_ID = '160'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-SC CAT' WHERE LAW_ID = '161'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-SD IF' WHERE LAW_ID = '162'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-TX SJA' WHERE LAW_ID = '163'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-WA WTF' WHERE LAW_ID = '164'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-MT OFLR' WHERE LAW_ID = '165'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-MT OFLE' WHERE LAW_ID = '166'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-NJ WDF' WHERE LAW_ID = '167'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-NJ WDF_EE' WHERE LAW_ID = '168'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-NJ HSF' WHERE LAW_ID = '169'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-NJ HSF_EE' WHERE LAW_ID = '170'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-NJ SHC' WHERE LAW_ID = '171'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-OR TM' WHERE LAW_ID = '172'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-OR LTD' WHERE LAW_ID = '173'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-OR WA' WHERE LAW_ID = '174'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-OR SPT' WHERE LAW_ID = '175'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-OR WAT' WHERE LAW_ID = '176'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-NC TRT' WHERE LAW_ID = '178'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-AZ TT' WHERE LAW_ID = '179'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'LWT-RI ESRT' WHERE LAW_ID = '180'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'LWT-CRT' WHERE LAW_ID = '181'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-PR SAT' WHERE LAW_ID = '182'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-LA SCT' WHERE LAW_ID = '183'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-WY ESF' WHERE LAW_ID = '184'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-NH AC' WHERE LAW_ID = '185'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-IA RF' WHERE LAW_ID = '186'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-MS WTEF' WHERE LAW_ID = '187'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-DC AFA' WHERE LAW_ID = '188'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-ME CSSF' WHERE LAW_ID = '189'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-NM TF' WHERE LAW_ID = '190'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-NMWCF-EE' WHERE LAW_ID = '191'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-NMWCF-ER' WHERE LAW_ID = '192'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'UHI' WHERE LAW_ID = '193'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-NJ FLI' WHERE LAW_ID = '194'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'UIAS' WHERE LAW_ID = '195'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'COBRA' WHERE LAW_ID = '196'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-NY MCTMT' WHERE LAW_ID = '197'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-SD TF' WHERE LAW_ID = '198'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-RI WBI' WHERE LAW_ID = '199'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-MI OA' WHERE LAW_ID = '201'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-KY SC' WHERE LAW_ID = '202'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-SD AF' WHERE LAW_ID = '204'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUICREDIT' WHERE LAW_ID = '9000'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'UHICREDIT' WHERE LAW_ID = '9001'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUICREDIT' WHERE LAW_ID = '9003'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'WHCREDIT' WHERE LAW_ID = '9004'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUICREDIT' WHERE LAW_ID = '9005'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUICREDIT' WHERE LAW_ID = '9006'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUICREDIT' WHERE LAW_ID = '9008'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = '203' WHERE LAW_ID = '203'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'OR STT' WHERE LAW_ID = '205'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'WA PFL-ER' WHERE LAW_ID = '206'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'WA PFL-EE' WHERE LAW_ID = '207'
;

UPDATE PSP_LAW SET LAW_TYPE_CD = 'DC PFL-ER' WHERE LAW_ID = '208'
;

--PSP-17930--START
UPDATE PSP_LAW SET LAW_TYPE_CD = 'MA PML-ER' WHERE LAW_ID = '209'
;

UPDATE PSP_LAW SET LAW_TYPE_CD = 'MA PML-EE' WHERE LAW_ID = '210'
;

UPDATE PSP_LAW SET LAW_TYPE_CD = 'MA PFL-ER' WHERE LAW_ID = '211'
;

UPDATE PSP_LAW SET LAW_TYPE_CD = 'MA PFL-EE' WHERE LAW_ID = '212'
;
--PSP-17930--END

UPDATE PSP_LAW SET LAW_TYPE_CD = 'NPL CREDIT' WHERE LAW_ID = '214'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'CARES Credit' WHERE LAW_ID = '215'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'CARES Deferral' WHERE LAW_ID = '216'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'Deferral' WHERE LAW_ID = '217'
;

UPDATE PSP_LAW SET LAW_TYPE_CD = 'CT PFML-EE' WHERE LAW_ID = '218'
;

UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-ME UPAF' WHERE LAW_ID = '219'
;

UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP' WHERE LAW_ID = '220'
;

UPDATE PSP_LAW SET LAW_TYPE_CD = 'WA CF-EE' WHERE LAW_ID = '221'
;
-- PSP-24451
UPDATE PSP_LAW SET LAW_TYPE_CD = 'CO FAMLI-ER' WHERE LAW_ID = '222'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'CO FAMLI-EE' WHERE LAW_ID = '223'
;
-- PSP-24451
UPDATE PSP_LAW SET LAW_TYPE_CD = 'OR-PFMSL-ER' WHERE LAW_ID = '224'
;
UPDATE PSP_LAW SET LAW_TYPE_CD = 'OR-PFMSL-EE' WHERE LAW_ID = '225'
;
-- PSP-27326
UPDATE PSP_LAW SET LAW_TYPE_CD = 'SUP-NY Metro' WHERE LAW_ID = '226'
;
-- Update ALL LAW_CATEGORY_CODE based on Law ID
UPDATE PSP_LAW rt 
SET LAW_CATEGORY_CODE ='DisabilityEmployee'
WHERE rt.LAW_ID in ('67','68','69','75','71','72')
;
UPDATE PSP_LAW rt 
SET LAW_CATEGORY_CODE ='DisabilityEmployer'
WHERE rt.LAW_ID in ('73','74','70')
;
UPDATE PSP_LAW rt 
SET LAW_CATEGORY_CODE ='Local'
WHERE rt.LAW_ID in ('181','59','58','55','54','60','180','57','56','173','172','177','197')
;
UPDATE PSP_LAW rt 
SET LAW_CATEGORY_CODE ='MedicareEmployee'
WHERE rt.LAW_ID = '63'
;
UPDATE PSP_LAW rt 
SET LAW_CATEGORY_CODE ='MedicareEmployer'
WHERE rt.LAW_ID = '64'
;
UPDATE PSP_LAW rt 
SET LAW_CATEGORY_CODE ='SocialSecurityEmployee'
WHERE rt.LAW_ID = '61'
;
UPDATE PSP_LAW rt 
SET LAW_CATEGORY_CODE ='SocialSecurityEmployer'
WHERE rt.LAW_ID = '62'
;
UPDATE PSP_LAW rt 
SET LAW_CATEGORY_CODE ='Supplemental'
WHERE rt.LAW_ID in ('159','152','175','174','176','182','195','142','155','144','145','179','153','188','154','156','186','146','149','183','150','189','157','158','187','147','166','165','178','148','185','194','169','170','171','167','168','190','160','199','161','162','198','151','163','164','184','201','202', '204','213','219','220')
;
UPDATE PSP_LAW rt 
SET LAW_CATEGORY_CODE ='UnemploymentEmployee'
WHERE rt.LAW_ID in ('135','137','136')
;
UPDATE PSP_LAW rt 
SET LAW_CATEGORY_CODE ='UnemploymentEmployer'
WHERE rt.LAW_ID in ('98','122','65','66','83','84','85','86','87','88','89','90','91','92','93','94','95','96','97','99','100','101','102','103','104','105','106','107','108','109','110','111','112','113','114','115','116','117','118','119','120','121','123','124','125','126','127','128','129','130','131','132','133','134')
;
UPDATE PSP_LAW rt 
SET LAW_CATEGORY_CODE ='UnemploymentHealthInsurance'
WHERE rt.LAW_ID = '193'
;
UPDATE PSP_LAW rt 
SET LAW_CATEGORY_CODE ='Unused'
WHERE rt.LAW_ID in ('0','2','196','143','11','32','35','44','45','46','50','53','908','914','911','917','910','925','920','918','902','904','922','906','913','919','912','900','923','901','921','915','903','924','909','916','905','907','926','203','205','206','207','208','209','210','211','212','214','215','216','9178','217','218','221')
;
UPDATE PSP_LAW rt 
SET LAW_CATEGORY_CODE ='Withholding'
WHERE rt.LAW_ID in ('41','3','4','5','6','7','8','9','10','1','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31','33','34','36','37','38','39','40','42','43','47','48','49','51','52')
;
UPDATE PSP_LAW rt 
SET LAW_CATEGORY_CODE ='WorkersCompensationEmployee'
WHERE rt.LAW_ID in ('191','192')
;
UPDATE PSP_LAW rt
SET REQUIRES_MONTH_COUNTS ='0'
WHERE rt.LAW_CATEGORY_CODE <> 'UnemploymentEmployer' and rt.LAW_ID not in ('38','25')
;
UPDATE PSP_LAW rt
SET REQUIRES_MONTH_COUNTS ='1'
WHERE rt.LAW_CATEGORY_CODE ='UnemploymentEmployer' or rt.LAW_ID in ('38','25','206','207', '62', '64', '223','225')
;
UPDATE PSP_LAW rt
SET LAW_CATEGORY_CODE ='TransitTax'
WHERE rt.LAW_ID in ('205','226')
;
UPDATE PSP_LAW rt
SET REQUIRES_MONTH_COUNTS ='0'
WHERE rt.LAW_CATEGORY_CODE = 'TransitTax' and rt.LAW_ID in ('226')
;
UPDATE PSP_LAW rt
SET LAW_CATEGORY_CODE ='PaidLeave'
WHERE LAW_ID in ('222','223','224','225')
;
UPDATE PSP_LAW law
SET IS_EMPLOYER_TAX = '0'
WHERE law.LAW_ID in ('176','205','210','212','218','226')
;
--------------------------------------------------------
-- Drop temp table                                  --
--------------------------------------------------------
DROP TABLE TEMP_PSP_LAW

;
COMMIT
