UPDATE PSP_MONEY_MOVEMENT_TRANSACTION mmt
SET OFFLOAD_BATCH_FK = (SELECT OFFLOAD_BATCH_SEQ FROM PSP_OFFLOAD_BATCH ob INNER JOIN PSP_OFFLOAD_GROUP og ON OB.OFFLOAD_GROUP_FK = OG.OFFLOAD_GROUP_SEQ WHERE ob.OFFLOAD_DATE = mmt.INITIATION_DATE and og.OFFLOAD_GROUP_CD = 'STD' and ob.status_cd = 'InProcess'),
       MODIFIER_ID = 'UpdateOffloadBatchFk',
       MODIFIED_DATE = SYSTIMESTAMP
WHERE INITIATION_DATE > SYSTIMESTAMP - 90
            AND MONEY_MOVEMENT_PAYMENT_METHOD = 'ACHDirectDeposit'
            AND STATUS = 'Created'
            AND OFFLOAD_BATCH_FK IS NULL;
commit;            

UPDATE PSP_ENTRY_DETAIL_RECORD
SET N_A_C_H_A_FILE_FK = (SELECT NACHAFILE_SEQ FROM PSP_NACHAFILE nf INNER JOIN PSP_OFFLOAD_BATCH ob ON OB.OFFLOAD_BATCH_SEQ = NF.OFFLOAD_BATCH_FK  WHERE OB.OFFLOAD_DATE = INITIATION_DATE AND FILE_TYPE = 'PPD' ),
       MODIFIER_ID = 'UpdateOffloadBatchFk',
       MODIFIED_DATE = SYSTIMESTAMP
WHERE INITIATION_DATE > SYSTIMESTAMP - 90
            AND N_A_C_H_A_FILE_FK IS NULL
           AND N_A_C_H_A_FILE_TYPE = 'PPD'
           AND EXISTS (SELECT 'T' FROM PSP_MONEY_MOVEMENT_TRANSACTION WHERE MONEY_MOVEMENT_TRANSACTION_SEQ = MONEY_MOVEMENT_TRANSACTION_FK AND OFFLOAD_BATCH_FK IS NOT NULL AND STATUS = 'Created');
commit;

UPDATE PSP_ENTRY_DETAIL_RECORD
SET N_A_C_H_A_FILE_FK = (SELECT NACHAFILE_SEQ FROM PSP_NACHAFILE nf INNER JOIN PSP_OFFLOAD_BATCH ob ON OB.OFFLOAD_BATCH_SEQ = NF.OFFLOAD_BATCH_FK  WHERE OB.OFFLOAD_DATE = INITIATION_DATE AND FILE_TYPE = 'CCD' ),
       MODIFIER_ID = 'UpdateOffloadBatchFk',
       MODIFIED_DATE = SYSTIMESTAMP
WHERE INITIATION_DATE > SYSTIMESTAMP - 90
           AND N_A_C_H_A_FILE_FK IS NULL
           AND N_A_C_H_A_FILE_TYPE = 'CCD'
           AND EXISTS (SELECT 'T' FROM PSP_MONEY_MOVEMENT_TRANSACTION WHERE MONEY_MOVEMENT_TRANSACTION_SEQ = MONEY_MOVEMENT_TRANSACTION_FK AND OFFLOAD_BATCH_FK IS NOT NULL AND STATUS = 'Created');
commit;           
