UPDATE PSP_PAYMENT_TEMPLATE pt
SET pt.SUPPORT_START_DATE = null,
    pt.NO_CALCULATION = 0 
/
-- Create a similar update statement with new supported payment templates
--UPDATE PSP_PAYMENT_TEMPLATE pt
--SET pt.SUPPORT_START_DATE = TO_DATE( '04-01-2011 12:00:00 am', 'mm-dd-yyyy hh:mi:ss am')
--WHERE pt.PAYMENT_TEMPLATE_CD  IN ('IRS-940-PAYMENT', 'IRS-941-PAYMENT')

-- IRS SUPPORT START DATE = 04/01/2011
UPDATE PSP_PAYMENT_TEMPLATE pt
SET pt.SUPPORT_START_DATE = TO_DATE( '04-01-2011 12:00:00 am', 'mm-dd-yyyy hh:mi:ss am')
WHERE pt.PAYMENT_TEMPLATE_CD  IN ('IRS-940-PAYMENT', 'IRS-941-PAYMENT')
/
COMMIT
/


update psp_payment_template
set support_start_date = timestamp '2011-10-01 00:00:00'
where payment_template_cd in
('AL-CR4WH-PAYMENT',
'AR-941M-PAYMENT',
'AZ-A1-PAYMENT',
'CA-PITSDI-PAYMENT',
'CO-DR1094-PAYMENT',
'CT-CTWH-PAYMENT',
'DE-DES-PAYMENT',
'DC-FR900-PAYMENT',
'GA-GAV-PAYMENT',
'HI-VP1-PAYMENT',
'ID-910-PAYMENT',
'IL-501-PAYMENT',
'IA-44105-PAYMENT',
'KS-KW5-PAYMENT',
'KY-K1-PAYMENT',
'LA-L1-PAYMENT',
'MA-M941-PAYMENT',
'MD-MW506-PAYMENT',
'ME-900ME-PAYMENT',
'MI-MW106-PAYMENT',
'MN-MW1-PAYMENT',
'MO-941-PAYMENT',
'MT-MW1-PAYMENT',
'NE-941N-PAYMENT',
'NJ-NJ927PWH-PAYMENT',
'NM-CRS1-PAYMENT',
'NY-1MN-PAYMENT',
'NY-MTA305-PAYMENT',
'NC-NC5P-PAYMENT',
'ND-306-PAYMENT',
'OH-IT501-PAYMENT',
'OK-OW9A-PAYMENT',
'OR-OTCWH-PAYMENT',
'PA-501-PAYMENT',
'RI-941-PAYMENT',
'SC-WH1601-PAYMENT',
'UT-TC96-PAYMENT',
'VT-WH433-PAYMENT',
'VA-VA15-PAYMENT',
'WV-IT101-PAYMENT',
'WI-WT6-PAYMENT');

-- CREATE NO CALC PAYMENT TEMPLATES - USED FOR LAWS THAT ARE NOT BEING PAID AND THEREFORE HAVE NO 
-- RULES ASSOCIATED WITH THEM.
DECLARE

	table_exists PLS_INTEGER;

BEGIN


	SELECT COUNT(*) INTO table_exists
	FROM "USER_TABLES"
	WHERE TABLE_NAME = 'TMP_PSP_PAYMENT_TEMPLATE';

	IF table_exists = 1 THEN
		EXECUTE IMMEDIATE 'DROP TABLE TMP_PSP_PAYMENT_TEMPLATE CASCADE CONSTRAINTS';
	END IF;

END;

/

--------------------------------------------------------
-- Create temp table                                  --
--------------------------------------------------------

CREATE TABLE TMP_PSP_PAYMENT_TEMPLATE
(
	 PAYMENT_TEMPLATE_CD VARCHAR(30) NOT NULL,
	 AGENCY_FK VARCHAR(30) ,
	 PAYMENT_TEMPLATE_ABBREV VARCHAR(30) ,
	 NO_CALCULATION NUMBER(1) NULL,
	 VERSION NUMBER(1) NULL,
	 PRIMARY KEY(PAYMENT_TEMPLATE_CD)
)

/

--------------------------------------------------------
-- Insert into temp table                             --
--------------------------------------------------------

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV,VERSION, NO_CALCULATION)
VALUES ('AK-NOCALC','NOCALC', 'AK-NOCALC', 0, 1)
/
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV,VERSION, NO_CALCULATION)
VALUES ('AL-NOCALC','NOCALC', 'AL-NOCALC', 0, 1)
/
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV,VERSION, NO_CALCULATION)
VALUES ('AZ-NOCALC','NOCALC', 'AZ-NOCALC', 0, 1)
/
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV,VERSION, NO_CALCULATION)
VALUES ('CA-NOCALC','NOCALC', 'CA-NOCALC', 0, 1)
/
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV,VERSION, NO_CALCULATION)
VALUES ('CO-NOCALC','NOCALC', 'CO-NOCALC', 0, 1)
/
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV,VERSION, NO_CALCULATION)
VALUES ('DC-NOCALC','NOCALC', 'DC-NOCALC', 0, 1)
/
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV,VERSION, NO_CALCULATION)
VALUES ('FL-NOCALC','NOCALC', 'FL-NOCALC', 0, 1)
/
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV,VERSION, NO_CALCULATION)
VALUES ('GA-NOCALC','NOCALC', 'GA-NOCALC', 0, 1)
/
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV,VERSION, NO_CALCULATION)
VALUES ('HI-NOCALC', 'NOCALC',  'HI-NOCALC', 0, 1)
/
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV,VERSION, NO_CALCULATION)
VALUES ('IL-NOCALC','NOCALC', 'IL-NOCALC', 0, 1)
/
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV,VERSION, NO_CALCULATION)
VALUES ('KY-NOCALC', 'NOCALC',  'KY-NOCALC', 0, 1)
/
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV,VERSION, NO_CALCULATION)
VALUES ('LA-NOCALC','NOCALC', 'LA-NOCALC', 0, 1)
/
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV,VERSION, NO_CALCULATION)
VALUES ('MA-NOCALC', 'NOCALC',  'MA-NOCALC', 0, 1)
/
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV,VERSION, NO_CALCULATION)
VALUES ('MD-NOCALC', 'NOCALC',  'MD-NOCALC', 0, 1)
/
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV,VERSION, NO_CALCULATION)
VALUES ('ME-NOCALC', 'NOCALC',  'ME-NOCALC', 0, 1)
/
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV,VERSION, NO_CALCULATION)
VALUES ('MI-NOCALC', 'NOCALC',  'MI-NOCALC', 0, 1)
/
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV,VERSION, NO_CALCULATION)
VALUES ('MO-NOCALC', 'NOCALC',  'MO-NOCALC', 0, 1)
/
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV,VERSION, NO_CALCULATION)
VALUES ('MT-NOCALC', 'NOCALC',  'MT-NOCALC', 0, 1)
/
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV,VERSION, NO_CALCULATION)
VALUES ('NC-NOCALC', 'NOCALC',  'NC-NOCALC', 0, 1)
/
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV,VERSION, NO_CALCULATION)
VALUES ('NH-NOCALC', 'NOCALC',  'NH-NOCALC', 0, 1)
/
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV,VERSION, NO_CALCULATION)
VALUES ('NM-NOCALC', 'NOCALC',  'NM-NOCALC', 0, 1)
/
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV,VERSION, NO_CALCULATION)
VALUES ('NV-NOCALC', 'NOCALC',  'NV-NOCALC', 0, 1)
/
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV,VERSION, NO_CALCULATION)
VALUES ('NY-NOCALC', 'NOCALC',  'NY-NOCALC', 0, 1)
/
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV,VERSION, NO_CALCULATION)
VALUES ('OK-NOCALC', 'NOCALC',  'OK-NOCALC', 0, 1)
/
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV,VERSION, NO_CALCULATION)
VALUES ('OR-NOCALC', 'NOCALC',  'OR-NOCALC', 0, 1)
/
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV,VERSION, NO_CALCULATION)
VALUES ('PR-NOCALC', 'NOCALC',  'PR-NOCALC', 0, 1)
/
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV,VERSION, NO_CALCULATION)
VALUES ('RI-NOCALC', 'NOCALC',  'RI-NOCALC', 0, 1)
/
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV,VERSION, NO_CALCULATION)
VALUES ('SD-NOCALC', 'NOCALC',  'SD-NOCALC', 0, 1)
/
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV,VERSION, NO_CALCULATION)
VALUES ('TN-NOCALC', 'NOCALC',  'TN-NOCALC', 0, 1)
/
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV,VERSION, NO_CALCULATION)
VALUES ('TX-NOCALC', 'NOCALC',  'TX-NOCALC', 0, 1)
/
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV,VERSION, NO_CALCULATION)
VALUES ('VA-NOCALC', 'NOCALC',  'VA-NOCALC', 0, 1)
/
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV,VERSION, NO_CALCULATION)
VALUES ('VT-NOCALC', 'NOCALC',  'VT-NOCALC', 0, 1)
/
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV,VERSION, NO_CALCULATION)
VALUES ('WA-NOCALC', 'NOCALC',  'WA-NOCALC', 0, 1)
/
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV,VERSION, NO_CALCULATION)
VALUES ('WY-NOCALC', 'NOCALC',  'WY-NOCALC', 0, 1)
/
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV,VERSION, NO_CALCULATION)
VALUES ('177-NOCALC', 'NOCALC',  '177-NOCALC', 0, 1)
/
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV,VERSION, NO_CALCULATION)
VALUES ('9-NOCALC', 'NOCALC',  '9-NOCALC', 0, 1)
/
--------------------------------------------------------
-- Sychronize temp table and real table by            --
-- inserting, deleting, and updating as necessary     --
--------------------------------------------------------

INSERT INTO PSP_PAYMENT_TEMPLATE
   (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION)
SELECT
    PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, 0 
FROM
   TMP_PSP_PAYMENT_TEMPLATE tt
WHERE
   tt.PAYMENT_TEMPLATE_CD NOT IN (SELECT PAYMENT_TEMPLATE_CD FROM PSP_PAYMENT_TEMPLATE)

/

UPDATE PSP_PAYMENT_TEMPLATE rt
SET (rt.PAYMENT_TEMPLATE_CD, rt.AGENCY_FK, rt.PAYMENT_TEMPLATE_ABBREV, rt.NO_CALCULATION) =
(SELECT  tt.PAYMENT_TEMPLATE_CD, tt.AGENCY_FK, tt.PAYMENT_TEMPLATE_ABBREV, tt.NO_CALCULATION
 FROM TMP_PSP_PAYMENT_TEMPLATE tt WHERE tt.PAYMENT_TEMPLATE_CD = rt.PAYMENT_TEMPLATE_CD)
 WHERE rt.PAYMENT_TEMPLATE_CD IN (SELECT PAYMENT_TEMPLATE_CD FROM TMP_PSP_PAYMENT_TEMPLATE)
/



--------------------------------------------------------
-- Drop temp table                                  --
--------------------------------------------------------
DROP TABLE TMP_PSP_PAYMENT_TEMPLATE

/
COMMIT

-- DEFAULT_DEPOSIT_FREQUENCY

---  Weekly
UPDATE PSP_PAYMENT_TEMPLATE rt 
SET rt.DEFAULT_DEPOSIT_FREQUENCY ='WEEKLY'
WHERE PAYMENT_TEMPLATE_CD IN 
('CT-CTWH-PAYMENT',
 'NJ-NJ500-PAYMENT',
 'NJ-NJ500UI-PAYMENT',
 'NJ-NJ927PWH-PAYMENT')
/
--- Semiweekly
UPDATE PSP_PAYMENT_TEMPLATE rt 
SET rt.DEFAULT_DEPOSIT_FREQUENCY ='SEMIWEEKLY'
WHERE PAYMENT_TEMPLATE_CD IN 
('IRS-941-PAYMENT', 
 'AZ-A1-PAYMENT',
 'CA-PITSDI-PAYMENT',
 'MN-MW1-PAYMENT',
 'MN_UI',
 'MN_WH',
 'OR-OTCWH-PAYMENT',
 'SC-WH1601-PAYMENT',
 'VA-VA15-PAYMENT')
/

--- Monthly
UPDATE PSP_PAYMENT_TEMPLATE rt 
SET rt.DEFAULT_DEPOSIT_FREQUENCY ='MONTHLY'
WHERE PAYMENT_TEMPLATE_CD IN 
('AL-CR4WH-PAYMENT',
 'AR-941M-PAYMENT',
 'CO-DR1094-PAYMENT',
 'DC-FR900-PAYMENT',
 'DE-DES-PAYMENT',
 'GA-GAV-PAYMENT',
 'HI-VP1-PAYMENT',
 'IA-44105-PAYMENT',
 'ID-910-PAYMENT',
 'IL-501-PAYMENT',
 'IN-WH1-PAYMENT',
 'MA-M941-PAYMENT',
 'MI-MW106-PAYMENT',
 'MO-941-PAYMENT',
 'MS-M89-PAYMENT',
 'MT-MW1-PAYMENT',
 'NC-NC5P-PAYMENT',
 'NE-941N-PAYMENT',
 'NM-CRS1-PAYMENT',
 'OH-IT501-PAYMENT',
 'OH-SD101-PAYMENT',
 'OK-OW9A-PAYMENT',
 'RI-941-PAYMENT',
 'UT-TC96-PAYMENT',
 'VT-WH433-PAYMENT',
 'WV-IT101-PAYMENT')
/

--- Semimonthly
UPDATE PSP_PAYMENT_TEMPLATE rt 
SET rt.DEFAULT_DEPOSIT_FREQUENCY ='SEMIMONTHLY'
WHERE PAYMENT_TEMPLATE_CD IN 
('KS-CNS100-PAYMENT',
 'KS-KW5-PAYMENT',
 'LA-L1-PAYMENT',
 'PA-501-PAYMENT',
 'WI-WT6-PAYMENT')
/

--- TwiceMonthly
UPDATE PSP_PAYMENT_TEMPLATE rt 
SET rt.DEFAULT_DEPOSIT_FREQUENCY ='TWICEMONTHLY'
WHERE PAYMENT_TEMPLATE_CD IN 
('KY-K1-PAYMENT')
/

--- Quarterly
UPDATE PSP_PAYMENT_TEMPLATE rt 
SET rt.DEFAULT_DEPOSIT_FREQUENCY ='QUARTERLY'
WHERE PAYMENT_TEMPLATE_CD IN 
('ME-900ME-PAYMENT',
 'ME-941C1ME-PAYMENT',
 'ND-306-PAYMENT',
 'ND-SFN41263-PAYMENT',
 'NV-NUCS4072-PAYMENT',
 'NY-1MN-PAYMENT',
 'NY-45MN-PAYMENT',
 'NY-SDI-PAYMENT',
 'AK-AKNS-PAYMENT',
 'FL-UCT6-PAYMENT',
 'IRS-940-PAYMENT',
 'NH-DES200-PAYMENT',
 'SD-UID21-PAYMENT',
 'TN-LB0456-PAYMENT',
 'TX-C3V-PAYMENT',
 'WA-F5208-PAYMENT',
 'WY-WYO056-PAYMENT',
 'AL-CR4UI-PAYMENT',
 'AR-209B-PAYMENT',
 'AZ-UC018-PAYMENT',
 'CA-UIETT-PAYMENT',
 'CO-UITR1-PAYMENT',
 'CT-2MAG-PAYMENT',
 'DC-UC30-PAYMENT',
 'DE-UC8-PAYMENT',
 'GA-DOL4-PAYMENT',
 'HI-UCB6-PAYMENT',
 'IA-600103-PAYMENT',
 'ID-020-PAYMENT',
 'IL-UI340-PAYMENT',
 'IN-UC1-PAYMENT',
 'KS-KCNS100-PAYMENT',
 'KY-UI3-PAYMENT',
 'LA-ES61-PAYMENT',
 'MA-1700HI-PAYMENT',
 'MD-DLLR-PAYMENT',
 'MI-UIA1020-PAYMENT',
 'MN-DEED1-PAYMENT',
 'MO-MODES-PAYMENT',
 'MS-UI23-PAYMENT',
 'MT-UI5-PAYMENT',
 'NC-101-PAYMENT',
 'NE-UI11T-PAYMENT',
 'NJ-NJ927PUI-PAYMENT',
 'NM-ES903A-PAYMENT',
 'NM-WC1-PAYMENT',
 'OH-JFS66111-PAYMENT',
 'OK-OES3-PAYMENT',
 'OR-OTCUI-PAYMENT',
 'PA-UC2-PAYMENT',
 'RI-TX17-PAYMENT',
 'SC-UCE120-PAYMENT',
 'UT-F3-PAYMENT',
 'VA-FC20-PAYMENT',
 'VT-C101-PAYMENT',
 'WI-UCT101-PAYMENT',
 'WV-A154-PAYMENT'
 )
 /

 --- 3D (ACCELERATED)
UPDATE PSP_PAYMENT_TEMPLATE rt 
SET rt.DEFAULT_DEPOSIT_FREQUENCY ='ACCELERATED'
WHERE PAYMENT_TEMPLATE_CD IN 
('MD-MW506-PAYMENT')
 /
 
-- NON_MODIFIABLE_FREQUENCY
UPDATE PSP_PAYMENT_TEMPLATE rt
SET rt.NON_MODIFIABLE_FREQUENCY = '0'
/
UPDATE PSP_PAYMENT_TEMPLATE rt
SET rt.NON_MODIFIABLE_FREQUENCY = '1'
WHERE PAYMENT_TEMPLATE_CD IN ('CA-UIETT-PAYMENT', 'IRS-940-PAYMENT')
/

-- PRIOR_QTR_ADJ_REQ_AMENDMENT
UPDATE PSP_PAYMENT_TEMPLATE rt
SET rt.PRIOR_QTR_ADJ_REQ_AMENDMENT = '0'
/
UPDATE PSP_PAYMENT_TEMPLATE rt
SET rt.PRIOR_QTR_ADJ_REQ_AMENDMENT = '1'
WHERE PAYMENT_TEMPLATE_CD IN ('IRS-941-PAYMENT', 'CA-PITSDI-PAYMENT')
/

--AGENCY_REFUNDS_QUARTERLY
UPDATE PSP_PAYMENT_TEMPLATE rt
SET rt.AGENCY_REFUNDS_QUARTERLY = '0'
/
UPDATE PSP_PAYMENT_TEMPLATE rt
SET rt.AGENCY_REFUNDS_QUARTERLY = '1'
WHERE PAYMENT_TEMPLATE_CD IN ('IRS-941-PAYMENT')
/

-- TXP_RECORD_CLASS

UPDATE PSP_PAYMENT_TEMPLATE SET TXP_RECORD_CLASS='com.intuit.sbd.payroll.psp.agency.ach.txp.Txp_'|| substr(PAYMENT_TEMPLATE_CD, 0, 2)||'_WH' WHERE PAYMENT_TEMPLATE_CD in (
'KS-KW5-PAYMENT',
'OK-OW9A-PAYMENT',
'GA-GAV-PAYMENT',
'WV-IT101-PAYMENT',
'LA-L1-PAYMENT',
'SC-WH1601-PAYMENT',
'PA-501-PAYMENT',
'NC-NC5P-PAYMENT',
'NY-1MN-PAYMENT',
'ND-306-PAYMENT',
'ID-910-PAYMENT',
'MD-MW506-PAYMENT',
'MA-M941-PAYMENT',
'WI-WT6-PAYMENT',
'IL-501-PAYMENT',
'NE-941N-PAYMENT',
'NJ-NJ927PWH-PAYMENT',
'MO-941-PAYMENT',
'IA-44105-PAYMENT',
'UT-TC96-PAYMENT',
'AL-CR4WH-PAYMENT',
'CT-CTWH-PAYMENT',
'KY-K1-PAYMENT',
'HI-VP1-PAYMENT',
'ME-900ME-PAYMENT',
'CO-DR1094-PAYMENT',
'AZ-A1-PAYMENT',
'VA-VA15-PAYMENT',
'VT-WH433-PAYMENT',
'DE-DES-PAYMENT',
'DC-FR900-PAYMENT',
'OH-IT501-PAYMENT',
'RI-941-PAYMENT',
'CA-PITSDI-PAYMENT',
'OR-OTCWH-PAYMENT',
'MN-MW1-PAYMENT',
'MI-MW106-PAYMENT',
'MT-MW1-PAYMENT',
'AR-941M-PAYMENT',
'NM-CRS1-PAYMENT')
/

UPDATE PSP_PAYMENT_TEMPLATE SET TXP_RECORD_CLASS='com.intuit.sbd.payroll.psp.agency.ach.txp.Txp_NY_MCT' WHERE PAYMENT_TEMPLATE_CD='NY-MTA305-PAYMENT'
/

COMMIT;
/


UPDATE PSP_AGENCY ag set AG.AGENCY_SUPPORTED = 1 where AG.AGENCY_ID in (
select distinct agency_id from PSP_AGENCY Agency join PSP_PAYMENT_TEMPLATE pt on PT.AGENCY_FK = AGENCY.AGENCY_ID where PT.SUPPORT_START_DATE is not null)
/
commit;
/