CREATE INDEX PSPADM.PSP_FINANCIALTRANSACTIONST_FK1 ON PSP_FINANCIAL_TRANS_STATE
(COMPANY_FK, TRANSACTION_TYPE_FK, transaction_state_eff_date)
TABLESPACE PSP_IDX01
ONLINE
LOCAL
PARALLEL 16;

ALTER INDEX PSPADM.PSP_FINANCIALTRANSACTIONST_FK1 NOPARALLEL;

CREATE INDEX PSPADM.PSP_FINANCIALTRANSACTIONST_FK2 ON PSP_FINANCIAL_TRANS_STATE
(TRANSACTION_TYPE_FK, transaction_state_eff_date)
TABLESPACE PSP_IDX01
ONLINE
LOCAL
PARALLEL 16;

ALTER INDEX PSPADM.PSP_FINANCIALTRANSACTIONST_FK2 NOPARALLEL;

ALTER TABLE PSPADM.PSP_FINANCIAL_TRANS_STATE
 ADD CONSTRAINT PSP_FINANCIALTRANSACTIONST_FK1 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

ALTER TABLE PSPADM.PSP_FINANCIAL_TRANS_STATE
 ADD CONSTRAINT PSP_FINANCIALTRANSACTIONST_FK2 
  FOREIGN KEY (TRANSACTION_TYPE_FK, REALM_ID) 
  REFERENCES PSP_TRANSACTION_TYPE (TRANSACTION_TYPE_CD,REALM_ID);
