-- FILE NAME    : dbupgrade_PSRV001197_SST_a1.sql
-- CREATED  DATE: 3.20.2009
-- MODIFIED DATE: 3.25.2009  02:00 PM
--                - 
-- AUTHOR       : EMR
--
-- PURPOSE: 
--   This script will change the PSP SOURCE SYSTEM TRANSMISSION table from no partitions  
--   to monthly, or twelve times a year.  The partition key will be on CREATED_DATE.
--   Applicable indexes will also be modified.
--                    file-a1 = create int table
--                    file-a2 = run can_redef_table
--                    file-a3 = run start_redef_table
--                    file-a4 = run copy_dependents
--                    file-a5 = run finish_redef_table
--                    file-b1 = drop int table, and add additional objects
--
-- LOGON AS : PSPADM

-- grant using SYS

-- GRANT execute ON DBMS_REDEFINITION TO PSPADM;
-- GRANT create materialized view     TO PSPADM;
-- GRANT alter  any table             TO PSPADM;
-- GRANT create any table             TO PSPADM;
-- GRANT drop   any table             TO PSPADM;
-- GRANT lock   any table             TO PSPADM;
-- GRANT select any table             TO PSPADM;
-- GRANT create any trigger           TO PSPADM; -- used for COPY_TABLE_DEPENDENTS
-- GRANT create any index             TO PSPADM; -- used for COPY_TABLE_DEPENDENTS


SET SERVEROUTPUT ON
SET LINESIZE     1000
SET PAGESIZE     1000
SET DEFINE       OFF

SPOOL dbupgrade_PSRV001197_SST_a1.log

SELECT USER FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'MM.DD.YYYY HH24:MI') AS TIME_MARK FROM DUAL;


PROMPT .
PROMPT Get initial table count for PSP_SOURCE_SYSTEM_TRANSMISSION ...

SELECT COUNT(*) FROM PSP_SOURCE_SYSTEM_TRANSMISSION;

SELECT SUBSTR(FROM_SOURCE_SYSTEM,1,30) AS FROM_SOURCE_SYS,
       COUNT(*)
  FROM PSP_SOURCE_SYSTEM_TRANSMISSION
 GROUP
    BY FROM_SOURCE_SYSTEM
 ORDER
    BY 1;
    

PROMPT .
PROMPT Create an interim table ...

-- design note: the partition format is M<01-12>YYYY, where 
--                M    = month, Jan to Dec
--                YYYY = year

-- this is simply to compare to at the end
CREATE TABLE Z_REDEF_SRC_SYS_TRANSMISSION AS
SELECT * FROM PSP_SOURCE_SYSTEM_TRANSMISSION WHERE 1=0;

-- this is the real deal for DBMS_REDEFINITION
CREATE TABLE INT_PSP_SRC_SYS_TRANSMISSION
(
  SOURCE_SYSTEM_TRANSMISSION_SEQ  VARCHAR2(255 CHAR),
  VERSION                         NUMBER(19),
  CREATOR_ID                      VARCHAR2(30 CHAR),
  CREATED_DATE                    TIMESTAMP(6),
  MODIFIER_ID                     VARCHAR2(30 CHAR),
  MODIFIED_DATE                   TIMESTAMP(6),
  REALM_ID                        NUMBER(19) DEFAULT -1,
  FROM_SOURCE_SYSTEM              VARCHAR2(255 CHAR),
  REQUEST_TOKEN                   NUMBER(19),
  RESPONSE_TOKEN                  NUMBER(19),
  REQUEST_DOCUMENT                CLOB,
  RESPONSE_DOCUMENT               CLOB,
  TYPE                            VARCHAR2(255 CHAR),
  INITIALIZE_DATE_TIME            TIMESTAMP(6),
  FINALIZE_DATE_TIME              TIMESTAMP(6),
  DESCRIPTION                     VARCHAR2(256 CHAR),
  TO_SOURCE_SYSTEM                VARCHAR2(255 CHAR),
  TRANSMISSION_IDENTIFIER         VARCHAR2(40 CHAR),
  I_P_ADDRESS                     VARCHAR2(20 CHAR),
  COMPANY_FK                      VARCHAR2(255 CHAR)
)
LOB (REQUEST_DOCUMENT, RESPONSE_DOCUMENT) STORE AS (TABLESPACE PSP_LOB01)
PARTITION BY RANGE (CREATED_DATE)
SUBPARTITION BY LIST (FROM_SOURCE_SYSTEM)
SUBPARTITION TEMPLATE 
(
 SUBPARTITION FROM_AS400   VALUES ('AS400'),
 SUBPARTITION FROM_CRIS    VALUES ('CRIS'),  
 SUBPARTITION FROM_EWS     VALUES ('EWS'),
 SUBPARTITION FROM_PSP     VALUES ('PSP'),
 SUBPARTITION FROM_QBDT    VALUES ('QBDT'),  
 SUBPARTITION FROM_NULL    VALUES (NULL), 
 SUBPARTITION FROM_DFLT    VALUES (DEFAULT)  
)
(
 PARTITION SRCSYSTRNS_2008    VALUES LESS THAN (TO_DATE('01/01/2009', 'MM/DD/YYYY')),
 PARTITION SRCSYSTRNS_M012009 VALUES LESS THAN (TO_DATE('02/01/2009', 'MM/DD/YYYY')),
 PARTITION SRCSYSTRNS_M022009 VALUES LESS THAN (TO_DATE('03/01/2009', 'MM/DD/YYYY')),
 PARTITION SRCSYSTRNS_M032009 VALUES LESS THAN (TO_DATE('04/01/2009', 'MM/DD/YYYY')),
 PARTITION SRCSYSTRNS_M042009 VALUES LESS THAN (TO_DATE('05/01/2009', 'MM/DD/YYYY')),
 PARTITION SRCSYSTRNS_M052009 VALUES LESS THAN (TO_DATE('06/01/2009', 'MM/DD/YYYY')),   
 PARTITION SRCSYSTRNS_M062009 VALUES LESS THAN (TO_DATE('07/01/2009', 'MM/DD/YYYY')), 
 PARTITION SRCSYSTRNS_M072009 VALUES LESS THAN (TO_DATE('08/01/2009', 'MM/DD/YYYY')), 
 PARTITION SRCSYSTRNS_M082009 VALUES LESS THAN (TO_DATE('09/01/2009', 'MM/DD/YYYY')), 
 PARTITION SRCSYSTRNS_M092009 VALUES LESS THAN (TO_DATE('10/01/2009', 'MM/DD/YYYY')),  
 PARTITION SRCSYSTRNS_M102009 VALUES LESS THAN (TO_DATE('11/01/2009', 'MM/DD/YYYY')), 
 PARTITION SRCSYSTRNS_M112009 VALUES LESS THAN (TO_DATE('12/01/2009', 'MM/DD/YYYY')), 
 PARTITION SRCSYSTRNS_M122009 VALUES LESS THAN (TO_DATE('01/01/2010', 'MM/DD/YYYY')),  
 PARTITION SRCSYSTRNS_M012010 VALUES LESS THAN (TO_DATE('02/01/2010', 'MM/DD/YYYY')),
 PARTITION SRCSYSTRNS_M022010 VALUES LESS THAN (TO_DATE('03/01/2010', 'MM/DD/YYYY')),
 PARTITION SRCSYSTRNS_M032010 VALUES LESS THAN (TO_DATE('04/01/2010', 'MM/DD/YYYY')),
 PARTITION SRCSYSTRNS_M042010 VALUES LESS THAN (TO_DATE('05/01/2010', 'MM/DD/YYYY')),
 PARTITION SRCSYSTRNS_M052010 VALUES LESS THAN (TO_DATE('06/01/2010', 'MM/DD/YYYY')),   
 PARTITION SRCSYSTRNS_M062010 VALUES LESS THAN (TO_DATE('07/01/2010', 'MM/DD/YYYY')), 
 PARTITION SRCSYSTRNS_M072010 VALUES LESS THAN (TO_DATE('08/01/2010', 'MM/DD/YYYY')), 
 PARTITION SRCSYSTRNS_M082010 VALUES LESS THAN (TO_DATE('09/01/2010', 'MM/DD/YYYY')), 
 PARTITION SRCSYSTRNS_M092010 VALUES LESS THAN (TO_DATE('10/01/2010', 'MM/DD/YYYY')),  
 PARTITION SRCSYSTRNS_M102010 VALUES LESS THAN (TO_DATE('11/01/2010', 'MM/DD/YYYY')), 
 PARTITION SRCSYSTRNS_M112010 VALUES LESS THAN (TO_DATE('12/01/2010', 'MM/DD/YYYY')), 
 PARTITION SRCSYSTRNS_M122010 VALUES LESS THAN (TO_DATE('01/01/2011', 'MM/DD/YYYY')),  
 PARTITION SRCSYSTRNS_9999    VALUES LESS THAN (MAXVALUE)
);

CREATE UNIQUE INDEX INT_XPKSRC_SYS_TRANSMISSION
  ON INT_PSP_SRC_SYS_TRANSMISSION (SOURCE_SYSTEM_TRANSMISSION_SEQ, REALM_ID);

ALTER TABLE INT_PSP_SRC_SYS_TRANSMISSION ADD (
  CONSTRAINT INT_XPKSRC_SYS_TRANSMISSION
  PRIMARY KEY (SOURCE_SYSTEM_TRANSMISSION_SEQ, REALM_ID));

-- 03.20.2009 EMR  to avoid resource busy ora error do prior to redef
-- ALTER TABLE PSP_SOURCE_SYSTEM_TRANSMISSION       ENABLE ROW MOVEMENT;
ALTER TABLE INT_PSP_SRC_SYS_TRANSMISSION         ENABLE ROW MOVEMENT;

-- 03.25.2009 EMR  put clobs in their own tablespace


PROMPT . 
PROMPT Part a1 complete, please run part a2 if successful ...

SELECT TO_CHAR(SYSDATE, 'MM.DD.YYYY HH24:MI') AS TIME_MARK FROM DUAL;

SPOOL OFF