-- TEAMTRACK NUM: PSRV002065
-- CREATED  DATE: 01.14.2011
-- AUTHOR       : AELLURU
-- MODIFIER     : 
--PURPOSE       :EXTEND THE OFFER END DATE FOR OFFER CODE P62255 TILL 07/31/2011

-- LOGON AS : PSPADM


SET SERVEROUTPUT ON
SET HEADING      ON
SET LINESIZE     1000
SET PAGESIZE     0
SET DEFINE       OFF


SPOOL dbupgrade_PSRV002065.log

SELECT 'User = ' || USER
  FROM DUAL;
  
SELECT 'Start Time = ' || TO_CHAR (SYSDATE, 'MM.DD.YYYY HH24:MI')
  FROM DUAL;



UPDATE PSPADM.PSP_OFFER 
SET END_DATE=to_timestamp('8/01/2011 12:01:00.000000 AM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'),MODIFIED_DATE=SYSTIMESTAMP where OFFER_CD='P62255';

commit;


 
 SELECT 'END Time = ' || TO_CHAR (SYSDATE, 'MM.DD.YYYY HH24:MI')
   FROM DUAL;
   
spool off;




