
PROMPT RUN THIS AS PSPAPP USER

DROP synonym PSP_ASSIGNED_DEPOSIT_FREQUENCY;
DROP synonym PSP_COMPANY_JURISD_TAX_TYPE;
DROP synonym PSP_COMPANY_PAYMENT_TEMPLATE;
DROP synonym PSP_DEPOSIT_FREQUENCY;
DROP synonym PSP_EVTDTLTP_EVTTP_ASSOC;
DROP synonym PSP_ODFCHANGE_REASON;
DROP synonym PSP_ONGOING_DEPOSIT_FREQUENCY;
DROP synonym PSP_PAYLINE;
DROP synonym PSP_PAYMENT_TEMPLATE_FREQUENCY;
