CREATE INDEX PSPADM.PSP_PAYCHECK_I2 ON PSPADM.PSP_PAYCHECK
(COMPANY_FK, SOURCE_PAYCHECK_ID)
TABLESPACE PSP_IDX01
online
parallel 16;

alter index PSPADM.PSP_PAYCHECK_I2 noparallel;


drop index PSPADM.PSP_PAYCHECK_FK5;



