SPOOL PostDeploy1.log

Accept p_idx_tbl_space CHAR def 'PSP_IDX01' Prompt 'Enter PSP Index tablespace (default PSP_IDX01) : '


PROMPT INDEX TABLESPACE &&p_idx_tbl_space



ALTER TABLE PSP_OFFERING_SVCCHG_GRP
 DROP CONSTRAINT PSP_OFFERING_SERVICE_CHARG_FK1;

ALTER TABLE PSP_OFFERING_SVCCHG
 DROP CONSTRAINT PSP_OFFERING_SERVICE_CHARG_FK2;

ALTER TABLE PSP_BILLING_DETAIL
 DROP CONSTRAINT C_PSP_BILLING_DETAIL1;

Prompt Constraint C_PSP_COMPANY_EVENT_EMAIL1;
/*
ALTER TABLE PSP_COMPANY_EVENT_EMAIL
 DROP CONSTRAINT C_PSP_COMPANY_EVENT_EMAIL1;
*/ 
ALTER TABLE PSP_COMPANY_EVENT_EMAIL
 ADD CONSTRAINT C_PSP_COMPANY_EVENT_EMAIL1
 CHECK (EMAIL_TEMPLATE_TYPE_CD IN('AllPaycheckReversalsFailed', 'AllPaycheckReversalsSuccessful', 'AutoRedebit', 'AutoRedebitFourStrikes', 'BankVerificationFailed', 'BilledNonPayrollRelatedFee', 'CustomerInitiatedDDReversal', 'DDBankVerificationReminder', 'DDBankVerificationSuccessful', 'DDERBankAccountChange', 'DDPINChangeConfirmation', 'DDServiceCancelledConfirmation', 'DDSignupConfirmation', 'ERandEENOC2', 'LastChanceEmail', 'ManualRedebit', 'NonACHPaymentReceivedInFull', 'NonACHPaymentReceivedInFullActionRequired', 'NonACHPaymentReceivedLiabilityOutstanding', 'PartialPaycheckReversal', 'PayrollCancellationNotification', 'DebitReturned', 'DebitReturnedFourStrikes', 'EEDDREJECT', 'EmailChangeNotification', 'EmployeeNOC', 'EmployeeNOC2', 'EmployerNOC', 'ERandEENOC', 'PayrollCancelledNotification', 'QBDTPayrollConfirmation', 'RedebitFailed', 'RefundedFeeAmount', 'RefundWithRebillFeeAmount', 'WireExpectedNotification', 'EFTPSEnrollmentRejectedEIN', 'EFTPSEnrollmentRejectedName', 'BankVerifyAttemptFailed'))  NOVALIDATE;


Prompt Constraint C_PSP_COMPANY_EVENT_EMAIL_0;
/*
ALTER TABLE PSP_COMPANY_EVENT_EMAIL_PARAM
 DROP CONSTRAINT C_PSP_COMPANY_EVENT_EMAIL_0;
*/
ALTER TABLE PSP_COMPANY_EVENT_EMAIL_PARAM
 ADD CONSTRAINT C_PSP_COMPANY_EVENT_EMAIL_0
 CHECK (PARAM_TYPE_CD IN('AdjustedPayrollDebitAmount', 'BilledFeeList', 'CompanyBalanceDue', 'CompanyBankAccountLastFour', 'CompanyID', 'CompanyLegalName', 'CurrentEmail', 'EffectiveCreditPostingDate', 'EmailFirstName', 'EmailLastName', 'EmployeeFirstName', 'EmployeeLastNameFirstInitial', 'EmployeeList', 'FailureReason', 'IntuitHandlingFee', 'NextBusinessDate', 'NonPayrollFeeAmount', 'NonPayrollFeeSettlementDate', 'NonPayrollFeeType', 'NumberOfStrikes', 'PayrollRunTime', 'PrimaryPrincipalEmail', 'PrimaryPrincipalFirstName', 'PrimaryPrincipalLastName', 'PriorEmail', 'RedebitCompletedDate', 'RedebitSettlementDate', 'RefundedFeeList', 'ReversalFailedList', 'ReversalPendingList', 'ReversalSuccessfulList', 'SourcePayrollSystem', 'TodaysDate', 'TodaysDatePlus14CalendarDays', 'WireExpectedDate', 'PaycheckSettlementDate', 'PayrollAdminEmail', 'PayrollAdminFirstName', 'PayrollAdminLastName', 'PayrollCancelDate', 'PayrollDebitAmount', 'PayrollDebitSettlementDate', 'PayrollRunDate', 'CompanyDBAName'))  NOVALIDATE;


Prompt Constraint PSP_COMPANY_FK5;
ALTER TABLE PSP_COMPANY
 DROP CONSTRAINT PSP_COMPANY_FK5;
ALTER TABLE PSP_COMPANY
 ADD CONSTRAINT PSP_COMPANY_FK5 
 FOREIGN KEY (OFFLOAD_GROUP_FK, REALM_ID) 
 REFERENCES PSP_OFFLOAD_GROUP (OFFLOAD_GROUP_SEQ,REALM_ID) NOVALIDATE;
 
ALTER TABLE PSP_COMPANY ENABLE VALIDATE CONSTRAINT PSP_COMPANY_FK5 ;

Prompt Constraint PSP_FINANCIALTRANSACTION_FK2;
ALTER TABLE PSP_FINANCIAL_TRANSACTION
 DROP CONSTRAINT PSP_FINANCIALTRANSACTION_FK2;

ALTER TABLE PSP_FINANCIAL_TRANSACTION
 ADD CONSTRAINT PSP_FINANCIALTRANSACTION_FK2 
 FOREIGN KEY (RELATABLE_TRANSACTION_FK, REALM_ID) 
 REFERENCES PSP_FINANCIAL_TRANSACTION (FINANCIAL_TRANSACTION_SEQ,REALM_ID) NOVALIDATE;
ALTER TABLE PSP_FINANCIAL_TRANSACTION ENABLE VALIDATE CONSTRAINT PSP_FINANCIALTRANSACTION_FK2 ;
 

ALTER TABLE PSP_OFFERING_SVCCHG_GRP
 ADD CONSTRAINT PSP_OFFERING_SVCCHG_GRP_FK 
 FOREIGN KEY (OFFERING_FK, REALM_ID) 
 REFERENCES PSP_OFFERING (OFFERING_SEQ,REALM_ID);

ALTER TABLE PSP_OFFERING_SVCCHG
 ADD CONSTRAINT PSP_OFFERING_SVCCHG_FK 
 FOREIGN KEY (OFFERING_SVCCHG_GRP_FK, REALM_ID) 
 REFERENCES PSP_OFFERING_SVCCHG_GRP (OFFERING_SVCCHG_GRP_SEQ,REALM_ID);

ALTER TABLE PSP_COMPANY
 ADD CONSTRAINT PSP_COMPANY_FK6 
 FOREIGN KEY (FUNDING_MODEL_FK, REALM_ID) 
 REFERENCES PSP_FUNDING_MODEL (FUNDING_MODEL_CD,REALM_ID) NOVALIDATE;
ALTER TABLE PSP_COMPANY ENABLE VALIDATE CONSTRAINT PSP_COMPANY_FK6 ;

ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 ADD CONSTRAINT PSP_MONEY_MOVEMENT_TRANSAC_FK4 
 FOREIGN KEY (EFE_PYMT_BATCH_FK, REALM_ID) 
 REFERENCES PSP_EFE_PMT_BATCH (EFE_PMT_BATCH_SEQ,REALM_ID) NOVALIDATE;
ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION ENABLE VALIDATE CONSTRAINT PSP_MONEY_MOVEMENT_TRANSAC_FK4 ;

ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 ADD CONSTRAINT PSP_MONEY_MOVEMENT_TRANSAC_FK5 
 FOREIGN KEY (PAYMENT_TEMPLATE_FK, REALM_ID) 
 REFERENCES PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD,REALM_ID) NOVALIDATE;
ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION ENABLE VALIDATE CONSTRAINT PSP_MONEY_MOVEMENT_TRANSAC_FK5 ;

ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 ADD CONSTRAINT PSP_MONEY_MOVEMENT_TRANSAC_FK6 
 FOREIGN KEY (PAYMENT_FREQUENCY_FK, REALM_ID) 
 REFERENCES PSP_PMT_TEMPLATE_FREQUENCY (PAYMENT_TEMPLATE_FREQUENCY_ID,REALM_ID) NOVALIDATE;
 ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION ENABLE VALIDATE CONSTRAINT PSP_MONEY_MOVEMENT_TRANSAC_FK6 ;

ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 ADD CONSTRAINT PSP_MONEY_MOVEMENT_TRANSAC_FK7 
 FOREIGN KEY (AUTH_USER_FK, REALM_ID) 
 REFERENCES PSP_AUTH_USER (AUTH_USER_SEQ,REALM_ID) NOVALIDATE;
 ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION ENABLE VALIDATE CONSTRAINT PSP_MONEY_MOVEMENT_TRANSAC_FK7 ;

ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 ADD CONSTRAINT PSP_MONEYMOVEMENTTRANSACTI_FK1 
 FOREIGN KEY (ORIGINAL_TRANSACTION_FK, REALM_ID) 
 REFERENCES PSP_MONEY_MOVEMENT_TRANSACTION (MONEY_MOVEMENT_TRANSACTION_SEQ,REALM_ID) NOVALIDATE;
 ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION ENABLE VALIDATE CONSTRAINT PSP_MONEYMOVEMENTTRANSACTI_FK1 ;

ALTER TABLE PSP_PAYCHECK
 ADD CONSTRAINT PSP_PAYCHECK_FK3 
 FOREIGN KEY (COMP_ADJUST_SUBMISSION_FK, REALM_ID) 
 REFERENCES PSP_COMP_ADJUST_SUBMISSION (COMP_ADJUST_SUBMISSION_SEQ,REALM_ID) NOVALIDATE;
ALTER TABLE PSP_PAYCHECK ENABLE VALIDATE CONSTRAINT PSP_PAYCHECK_FK3 ;

ALTER TABLE PSP_FINANCIAL_TRANSACTION
 ADD CONSTRAINT PSP_FINANCIAL_TRANSACTION_FK11 
 FOREIGN KEY (COMP_ADJUST_SUBMISSION_FK, REALM_ID) 
 REFERENCES PSP_COMP_ADJUST_SUBMISSION (COMP_ADJUST_SUBMISSION_SEQ,REALM_ID) NOVALIDATE;
ALTER TABLE PSP_FINANCIAL_TRANSACTION ENABLE VALIDATE CONSTRAINT PSP_FINANCIAL_TRANSACTION_FK11 ;

ALTER TABLE PSP_FINANCIAL_TRANSACTION
 ADD CONSTRAINT PSP_FINANCIAL_TRANSACTION_FK8 
 FOREIGN KEY (LAW_FK, REALM_ID) 
 REFERENCES PSP_LAW (LAW_ID,REALM_ID) NOVALIDATE;
ALTER TABLE PSP_FINANCIAL_TRANSACTION ENABLE VALIDATE CONSTRAINT PSP_FINANCIAL_TRANSACTION_FK8 ; 

ALTER TABLE PSP_FINANCIAL_TRANSACTION
 ADD CONSTRAINT PSP_FINANCIAL_TRANSACTION_FK14 
 FOREIGN KEY (TAX_PENALTY_INTEREST_FK, REALM_ID) 
 REFERENCES PSP_TAX_PENALTY_INTEREST (TAX_PENALTY_INTEREST_SEQ,REALM_ID) NOVALIDATE;
ALTER TABLE PSP_FINANCIAL_TRANSACTION ENABLE VALIDATE CONSTRAINT PSP_FINANCIAL_TRANSACTION_FK14 ;


ALTER TABLE PSP_FINANCIAL_TRANSACTION
 ADD CONSTRAINT PSP_FINANCIALTRANSACTION_FK3 
 FOREIGN KEY (ORIGINAL_TRANSACTION_FK, REALM_ID) 
 REFERENCES PSP_FINANCIAL_TRANSACTION (FINANCIAL_TRANSACTION_SEQ,REALM_ID) NOVALIDATE;
ALTER TABLE PSP_FINANCIAL_TRANSACTION ENABLE VALIDATE CONSTRAINT PSP_FINANCIALTRANSACTION_FK3 ;


PROMPT  DROPPING INDEXES
 
 
 Prompt drop Index PSP_OFFERING_SERVICE_CHARG_FK2;
 DROP INDEX PSP_OFFERING_SERVICE_CHARG_FK2;
 
 Prompt drop Index PSP_OFFERING_SERVICE_CHARG_FK1;
 DROP INDEX PSP_OFFERING_SERVICE_CHARG_FK1;
Prompt Index PSP_PAYMENT_TEMPLATE_FREQU_FK1;
--
-- PSP_PAYMENT_TEMPLATE_FREQU_FK1  (Index) 
--
CREATE INDEX PSP_PAYMENT_TEMPLATE_FREQU_FK1 ON PSP_PMT_TEMPLATE_FREQUENCY
(PAYMENT_TEMPLATE_FK, REALM_ID)
LOGGING
NOPARALLEL ONLINE TABLESPACE &&p_idx_tbl_space;

Prompt Index PSP_OFFERING_SVCCHG_GRP_FK;
--
-- PSP_OFFERING_SVCCHG_GRP_FK  (Index) 
--
CREATE INDEX PSP_OFFERING_SVCCHG_GRP_FK ON PSP_OFFERING_SVCCHG_GRP
(OFFERING_FK, REALM_ID)
LOGGING
NOPARALLEL ONLINE TABLESPACE &&p_idx_tbl_space;


Prompt Index PSP_COMPANY_FK5;
Prompt drop Index PSP_COMPANY_FK5;
DROP INDEX PSP_COMPANY_FK5;
Prompt Index PSP_COMPANY_FK5;
--
-- PSP_COMPANY_FK5  (Index) 
--
CREATE INDEX PSP_COMPANY_FK5 ON PSP_COMPANY
(OFFLOAD_GROUP_FK, REALM_ID)
LOGGING
NOPARALLEL ONLINE TABLESPACE &&p_idx_tbl_space;

Prompt Index PSP_OFFERING_SVCCHG_FK;
--
-- PSP_OFFERING_SVCCHG_FK  (Index) 
--
CREATE INDEX PSP_OFFERING_SVCCHG_FK ON PSP_OFFERING_SVCCHG
(OFFERING_SVCCHG_GRP_FK, REALM_ID)
LOGGING
NOPARALLEL ONLINE TABLESPACE &&p_idx_tbl_space;

Prompt Index PSP_ACTIVATION_CHECK_LIST__FK3;
Prompt drop Index PSP_ACTIVATION_CHECK_LIST__FK3;
DROP INDEX PSP_ACTIVATION_CHECK_LIST__FK3;


Prompt Index PSP_ACTIVATION_CHECK_LIST__FK2;
Prompt drop Index PSP_ACTIVATION_CHECK_LIST__FK2;
DROP INDEX PSP_ACTIVATION_CHECK_LIST__FK2;
Prompt Index PSP_ACTIVATION_CHECK_LIST__FK2;
--
-- PSP_ACTIVATION_CHECK_LIST__FK2  (Index) 
--
CREATE INDEX PSP_ACTIVATION_CHECK_LIST__FK2 ON PSP_ACTIVATION_CHECK_LIST_ITEM
(SERVICE_CHECK_LIST_ITEM_FK, REALM_ID)
LOGGING
NOPARALLEL ONLINE TABLESPACE &&p_idx_tbl_space;

Prompt Index PSP_PAYCHECK_FK3;
--
-- PSP_PAYCHECK_FK3  (Index) 
--
CREATE INDEX PSP_PAYCHECK_FK3 ON PSP_PAYCHECK
(COMP_ADJUST_SUBMISSION_FK, REALM_ID)
LOGGING
NOPARALLEL ONLINE TABLESPACE &&p_idx_tbl_space;

Prompt Index PSP_MONEYMOVEMENTTRANSACTI_FK1;
--
-- PSP_MONEYMOVEMENTTRANSACTI_FK1  (Index) 
--
CREATE INDEX PSP_MONEYMOVEMENTTRANSACTI_FK1 ON PSP_MONEY_MOVEMENT_TRANSACTION
(ORIGINAL_TRANSACTION_FK, REALM_ID)
LOGGING
NOPARALLEL ONLINE TABLESPACE &&p_idx_tbl_space;

Prompt Index PSP_MONEY_MOVEMENT_TRANSAC_FK7;
--
-- PSP_MONEY_MOVEMENT_TRANSAC_FK7  (Index) 
--
CREATE INDEX PSP_MONEY_MOVEMENT_TRANSAC_FK7 ON PSP_MONEY_MOVEMENT_TRANSACTION
(AUTH_USER_FK, REALM_ID)
LOGGING
NOPARALLEL ONLINE TABLESPACE &&p_idx_tbl_space;

Prompt Index PSP_MONEY_MOVEMENT_TRANSAC_FK6;
--
-- PSP_MONEY_MOVEMENT_TRANSAC_FK6  (Index) 
--
CREATE INDEX PSP_MONEY_MOVEMENT_TRANSAC_FK6 ON PSP_MONEY_MOVEMENT_TRANSACTION
(PAYMENT_FREQUENCY_FK, REALM_ID)
LOGGING
NOPARALLEL ONLINE TABLESPACE &&p_idx_tbl_space;

Prompt Index PSP_MONEY_MOVEMENT_TRANSAC_FK5;
--
-- PSP_MONEY_MOVEMENT_TRANSAC_FK5  (Index) 
--
CREATE INDEX PSP_MONEY_MOVEMENT_TRANSAC_FK5 ON PSP_MONEY_MOVEMENT_TRANSACTION
(PAYMENT_TEMPLATE_FK, REALM_ID)
LOGGING
NOPARALLEL ONLINE TABLESPACE &&p_idx_tbl_space;

Prompt Index PSP_MONEY_MOVEMENT_TRANSAC_FK4;
--
-- PSP_MONEY_MOVEMENT_TRANSAC_FK4  (Index) 
--
CREATE INDEX PSP_MONEY_MOVEMENT_TRANSAC_FK4 ON PSP_MONEY_MOVEMENT_TRANSACTION
(EFE_PYMT_BATCH_FK, REALM_ID)
LOGGING
NOPARALLEL ONLINE TABLESPACE &&p_idx_tbl_space;



Prompt Index PSP_FINANCIALTRANSACTION_FK2;
Prompt drop Index PSP_FINANCIALTRANSACTION_FK2;
DROP INDEX PSP_FINANCIALTRANSACTION_FK2;
Prompt Index PSP_FINANCIALTRANSACTION_FK2;
--
-- PSP_FINANCIALTRANSACTION_FK2  (Index) 
--
CREATE INDEX PSP_FINANCIALTRANSACTION_FK2 ON PSP_FINANCIAL_TRANSACTION
(RELATABLE_TRANSACTION_FK, REALM_ID)
LOGGING
NOPARALLEL ONLINE TABLESPACE &&p_idx_tbl_space;

Prompt Index PSP_FINANCIAL_TRANSACTION_FK14;
--
-- PSP_FINANCIAL_TRANSACTION_FK14  (Index) 
--
CREATE INDEX PSP_FINANCIAL_TRANSACTION_FK14 ON PSP_FINANCIAL_TRANSACTION
(TAX_PENALTY_INTEREST_FK, REALM_ID)
LOGGING
NOPARALLEL ONLINE TABLESPACE &&p_idx_tbl_space;

Prompt Index PSP_FINANCIAL_TRANSACTION_FK11;
--
-- PSP_FINANCIAL_TRANSACTION_FK11  (Index) 
--
CREATE INDEX PSP_FINANCIAL_TRANSACTION_FK11 ON PSP_FINANCIAL_TRANSACTION
(COMP_ADJUST_SUBMISSION_FK, REALM_ID)
LOGGING
NOPARALLEL ONLINE TABLESPACE &&p_idx_tbl_space;

Prompt Index PSP_ACTIVATION_CHECK_LIST__FK3;
--
-- PSP_ACTIVATION_CHECK_LIST__FK3  (Index) 
--


CREATE INDEX PSP_ACTIVATION_CHECK_LIST__FK3 ON PSP_ACTIVATION_CHECK_LIST_ITEM
(AGENCY_CHECK_LIST_ITEM_FK, REALM_ID)
LOGGING
NOPARALLEL ONLINE TABLESPACE &&p_idx_tbl_space;

Prompt here Index PSP_FINANCIALTRANSACTION_FK3;
--
-- PSP_FINANCIALTRANSACTION_FK3  (Index) 
--
CREATE INDEX PSP_FINANCIALTRANSACTION_FK3 ON PSP_FINANCIAL_TRANSACTION
(ORIGINAL_TRANSACTION_FK, REALM_ID)
LOGGING
NOPARALLEL ONLINE TABLESPACE &&p_idx_tbl_space;

Prompt  PSP_COMPANY_FK6;
--
-- PSP_COMPANY_FK6  (Index) 
--

CREATE INDEX PSP_COMPANY_FK6 ON PSP_COMPANY
(FUNDING_MODEL_FK, REALM_ID)
LOGGING
NOPARALLEL ONLINE TABLESPACE &&p_idx_tbl_space;


Prompt Column VERSION;
 ALTER TABLE PSP_EVENT_LOG
 MODIFY(VERSION  NOT NULL);
 
 
 Prompt Column CREATED_DATE;
 ALTER TABLE PSP_EVENT_LOG
 MODIFY(CREATED_DATE  NOT NULL);
 
 
 Prompt Column MODIFIED_DATE;
 ALTER TABLE PSP_EVENT_LOG
 MODIFY(MODIFIED_DATE  NOT NULL);
 
 
 ALTER TABLE PSP_FORECAST
  ADD CONSTRAINT C_PSP_FORECAST0
  CHECK (STATUS IN('Open', 'Closed', 'Error'));

 Prompt Column VERSION;
 ALTER TABLE PSP_FORECAST
 MODIFY(VERSION  NOT NULL);
 
 
 Prompt Column CREATED_DATE;
 ALTER TABLE PSP_FORECAST
 MODIFY(CREATED_DATE  NOT NULL);
 
 
 Prompt Column MODIFIED_DATE;
 ALTER TABLE PSP_FORECAST
 MODIFY(MODIFIED_DATE  NOT NULL);
 
 
 Prompt Column VERSION;
 ALTER TABLE PSP_FORECAST_DETAIL
 MODIFY(VERSION  NOT NULL);
 
 
 Prompt Column CREATED_DATE;
 ALTER TABLE PSP_FORECAST_DETAIL
 MODIFY(CREATED_DATE  NOT NULL);
 
 
 Prompt Column MODIFIED_DATE;
 ALTER TABLE PSP_FORECAST_DETAIL
 MODIFY(MODIFIED_DATE  NOT NULL);
 
 
 Prompt Column FORECAST_FK;
 ALTER TABLE PSP_FORECAST_DETAIL
 MODIFY(FORECAST_FK  NOT NULL);


spool off