/
DECLARE
   sequence_exists PLS_INTEGER;
BEGIN
   SELECT COUNT(*) INTO sequence_exists
   FROM "USER_SEQUENCES"
   WHERE SEQUENCE_NAME = 'SEQ_EE_CALCULATION_TOKEN';
   IF sequence_exists = 0 THEN
    EXECUTE IMMEDIATE 'create sequence SEQ_EE_CALCULATION_TOKEN INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999 CYCLE';
   END IF;
   SELECT COUNT(*) INTO sequence_exists
   FROM "USER_SEQUENCES"
   WHERE SEQUENCE_NAME = 'SEQ_EE_PITEM_CALC_TOKEN';
   IF sequence_exists = 0 THEN
    EXECUTE IMMEDIATE 'create sequence SEQ_EE_PITEM_CALC_TOKEN INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999 CYCLE';
   END IF;
end;
/
