/
DECLARE
   sequence_exists PLS_INTEGER;
BEGIN
   SELECT COUNT(*) INTO sequence_exists
   FROM "USER_SEQUENCES"
   WHERE SEQUENCE_NAME = 'SEQ_EFTPS_SEGMENT_SEQUENCE';
   IF sequence_exists = 0 THEN
    EXECUTE IMMEDIATE 'create sequence SEQ_EFTPS_SEGMENT_SEQUENCE INCREMENT BY 1 MINVALUE 1000 NOCYCLE';
   END IF;
end;
/