/
DECLARE
   sequence_exists PLS_INTEGER;
BEGIN
   SELECT COUNT(*) INTO sequence_exists
   FROM "USER_SEQUENCES"
   WHERE SEQUENCE_NAME = 'SEQ_GEMS_UPLOAD_BATCH_ID';
   IF sequence_exists = 0 THEN
    EXECUTE IMMEDIATE 'create sequence SEQ_GEMS_UPLOAD_BATCH_ID INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999 NOCACHE CYCLE';
   END IF;
end;
/
