/
DECLARE
   sequence_exists PLS_INTEGER;
BEGIN
   SELECT COUNT(*) INTO sequence_exists
   FROM "USER_SEQUENCES"
   WHERE SEQUENCE_NAME = 'SEQ_QBDT_SOURCE_COMPANY_ID';
   IF sequence_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_QBDT_SOURCE_COMPANY_ID INCREMENT BY 1 MINVALUE 100000000 MAXVALUE 308999999';
   END IF;
end;
/
