/
DECLARE
   sequence_exists PLS_INTEGER;
BEGIN
   SELECT COUNT(*) INTO sequence_exists
   FROM "USER_SEQUENCES"
   WHERE SEQUENCE_NAME = 'SEQ_SUBSCRIPTION_NUMBER';
   IF sequence_exists = 0 THEN
    EXECUTE IMMEDIATE 'create sequence SEQ_SUBSCRIPTION_NUMBER INCREMENT BY 1 MINVALUE 8000000 MAXVALUE 999999999 CYCLE';
       END IF;
end;
/
