/
DECLARE
   sequence_exists PLS_INTEGER;
BEGIN
   SELECT COUNT(*) INTO sequence_exists
   FROM "USER_SEQUENCES"
   WHERE SEQUENCE_NAME = 'SEQ_TRACE_NUMBER';
   IF sequence_exists = 0 THEN
    EXECUTE IMMEDIATE 'create sequence  SEQ_TRACE_NUMBER  INCREMENT BY 1 MINVALUE 100000 MAXVALUE 9999999999999999 NOCYCLE CACHE 10000 ORDER';
   END IF;
end;
/