set echo on feedback on
spool CREATE_LOCAL_PK_ON_PARTITIONED_TABLES_1
ALTER TABLE PSPADM.PSP_COMPENSATION ADD CONSTRAINT PSP_COMPENSATION_PK PRIMARY KEY (COMPANY_FK,COMPENSATION_SEQ) USING INDEX LOCAL TABLESPACE PSP_IDX01 ENABLE;
ALTER TABLE PSPADM.PSP_LEDGER_BALANCE ADD CONSTRAINT PSP_LEDGER_BALANCE_PK PRIMARY KEY (COMPANY_FK,LEDGER_BALANCE_SEQ) USING INDEX LOCAL TABLESPACE PSP_IDX04 ENABLE;
ALTER TABLE PSPADM.PSP_MONEY_MOVEMENT_TRANSACTION ADD CONSTRAINT PSP_MONEY_MOVEMENT_TRANSACTION_PK PRIMARY KEY (COMPANY_FK,MONEY_MOVEMENT_TRANSACTION_SEQ) USING INDEX LOCAL TABLESPACE PSP_IDX01 ENABLE;
ALTER TABLE PSPADM.PSP_COMPANY_EVENT ADD CONSTRAINT PSP_COMPANY_EVENT_PK PRIMARY KEY (COMPANY_FK,COMPANY_EVENT_SEQ) USING INDEX LOCAL TABLESPACE PSP_IDX02 ENABLE;
ALTER TABLE PSPADM.PSP_COMPANY_EVENT_DETAIL ADD CONSTRAINT PSP_COMPANY_EVENT_DETAIL_PK PRIMARY KEY (COMPANY_FK,COMPANY_EVENT_DETAIL_SEQ) USING INDEX LOCAL TABLESPACE PSP_IDX03 ENABLE;
ALTER TABLE PSPADM.PSP_COMPANY_EVENT_EMAIL_PARAM ADD CONSTRAINT PSP_COMPANY_EVENT_EMAIL_PARAM_PK PRIMARY KEY (COMPANY_FK,COMPANY_EVENT_EMAIL_PARAM_SEQ) USING INDEX LOCAL TABLESPACE PSP_IDX04 ENABLE;

spool off
