apiVersion: v1
kind: Pod
metadata:
  name: payroll-dtpayroll-dt-payroll-svc-service-template-v2
spec:
  containers:
  - name: jnlp
    image: docker.intuit.com/dev/build/ibp/jnlp-slave-with-docker:3.36-2_master_85
    tty: true
    args: ["$(JENKINS_SECRET)", "$(JENKINS_AGENT_NAME)", "-url", "$(JENKINS_URL)"]
# Docker Images Details : https://wiki.intuit.com/display/ems/PSP+Build+and+Release+Image+Details
  - name: dbbuild
    image: docker.intuit.com/payroll/dtpayroll/dt-payroll-svc/service/dt-payroll-svc/psp-oracle21c-db-image:0.0.2
  - name: pspmavensql
    image: docker.intuit.com/payroll/dtpayroll/dt-payroll-svc/service/dt-payroll-svc/pspmavensql:latest
    tty: true
    command: ["cat"]
  - name: cdtools
    image: docker.intuit.com/dev/deploy/cd/argocd-utils:stable
    tty: true
    command: ["cat"]
    alwaysPullImage: true
  - name: servicenow
    image: docker.intuit.com/coe/servicenow-cr-agent/service/servicenow-cr-agent:latest
    tty: true
    command: ["cat"]
    alwaysPullImage: true
  - name: test
    image: docker.intuit.com/oicp/standard/external/maven:3.5.3-jdk-8
    tty: true
    command: [ "cat" ]
    alwaysPullImage: true
  - name: maven
    image: docker.intuit.com/oicp/standard/external/maven:3.5.3-jdk-8
    tty: true
    command: ["cat"]
    alwaysPullImage: true
  - name: podman
    image: docker.intuit.com/oicp/standard/podman:latest
    tty: true
    command: [ "cat" ]
    imagePullPolicy: Always
    volumeMounts:
      - name: container-storage
        mountPath: /var/lib/containers
    resources:
      limits:
        github.com/fuse: 1
    securityContext:
      capabilities:
        add: [ "SYS_ADMIN", "SYS_RESOURCE" ]
  - name: cpd2
    image: docker.intuit.com/oicp/standard/cpd2:1
    tty: true
    command: ["cat"]
    imagePullPolicy: Always
  volumes:
    - name: container-storage
      emptyDir: {}

