CREATE USER QBO_BUILD_USER IDENTIFIED BY "Y0Csp!LPu2"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
PROFILE DEFAULT
/
GRANT EXECUTE ON SYS.DBMS_LOCK  TO "QBO_BUILD_USER"  WITH GRANT OPTION ;

   GRANT "CONNECT" TO "QBO_BUILD_USER"  WITH ADMIN OPTION ;
   GRANT "RESOURCE" TO "QBO_BUILD_USER"  WITH ADMIN OPTION ;
   GRANT "SELECT_CATALOG_ROLE" TO "QBO_BUILD_USER"  WITH ADMIN OPTION ;
   GRANT "EXP_FULL_DATABASE" TO "QBO_BUILD_USER";
   GRANT "IMP_FULL_DATABASE" TO "QBO_BUILD_USER";
   GRANT "OEM_ADVISOR" TO "QBO_BUILD_USER";


  GRANT CREATE ANY SQL PROFILE TO "QBO_BUILD_USER";
  GRANT ADMINISTER SQL TUNING SET TO "QBO_BUILD_USER";
  GRANT ALTER ANY SQL PROFILE TO "QBO_BUILD_USER";
  GRANT DROP ANY SQL PROFILE TO "QBO_BUILD_USER";
  GRANT SELECT ANY DICTIONARY TO "QBO_BUILD_USER";
  GRANT EXEMPT ACCESS POLICY TO "QBO_BUILD_USER"  WITH ADMIN OPTION ;
  GRANT ADMINISTER DATABASE TRIGGER TO "QBO_BUILD_USER";
  GRANT DROP ANY OUTLINE TO "QBO_BUILD_USER";
  GRANT ALTER ANY OUTLINE TO "QBO_BUILD_USER";
  GRANT CREATE ANY OUTLINE TO "QBO_BUILD_USER";
  GRANT CREATE ANY CONTEXT TO "QBO_BUILD_USER";
  GRANT EXECUTE ANY INDEXTYPE TO "QBO_BUILD_USER"  WITH ADMIN OPTION ;
  GRANT DROP ANY INDEXTYPE TO "QBO_BUILD_USER";
  GRANT ALTER ANY INDEXTYPE TO "QBO_BUILD_USER";
  GRANT CREATE ANY INDEXTYPE TO "QBO_BUILD_USER";
  GRANT EXECUTE ANY TYPE TO "QBO_BUILD_USER"  WITH ADMIN OPTION ;
  GRANT DROP ANY TYPE TO "QBO_BUILD_USER";
  GRANT ALTER ANY TYPE TO "QBO_BUILD_USER";
  GRANT CREATE ANY TYPE TO "QBO_BUILD_USER";
  GRANT DROP ANY DIRECTORY TO "QBO_BUILD_USER";
  GRANT CREATE ANY DIRECTORY TO "QBO_BUILD_USER";
  GRANT DROP ANY MATERIALIZED VIEW TO "QBO_BUILD_USER";
  GRANT ALTER ANY MATERIALIZED VIEW TO "QBO_BUILD_USER";
  GRANT CREATE ANY MATERIALIZED VIEW TO "QBO_BUILD_USER";
  GRANT ANALYZE ANY TO "QBO_BUILD_USER";
  GRANT DROP ANY TRIGGER TO "QBO_BUILD_USER";
  GRANT ALTER ANY TRIGGER TO "QBO_BUILD_USER";
  GRANT CREATE ANY TRIGGER TO "QBO_BUILD_USER";
  GRANT EXECUTE ANY PROCEDURE TO "QBO_BUILD_USER"  WITH ADMIN OPTION ;
  GRANT DROP ANY PROCEDURE TO "QBO_BUILD_USER";
  GRANT ALTER ANY PROCEDURE TO "QBO_BUILD_USER";
  GRANT CREATE ANY PROCEDURE TO "QBO_BUILD_USER";
  GRANT DROP PUBLIC DATABASE LINK TO "QBO_BUILD_USER"  WITH ADMIN OPTION ;
  GRANT CREATE PUBLIC DATABASE LINK TO "QBO_BUILD_USER"  WITH ADMIN OPTION ;
  GRANT SELECT ANY SEQUENCE TO "QBO_BUILD_USER"  WITH ADMIN OPTION ;
  GRANT DROP ANY SEQUENCE TO "QBO_BUILD_USER";
  GRANT ALTER ANY SEQUENCE TO "QBO_BUILD_USER";
  GRANT CREATE ANY SEQUENCE TO "QBO_BUILD_USER";
  GRANT DROP ANY VIEW TO "QBO_BUILD_USER";
  GRANT CREATE ANY VIEW TO "QBO_BUILD_USER";
  GRANT DROP PUBLIC SYNONYM TO "QBO_BUILD_USER";
  GRANT CREATE PUBLIC SYNONYM TO "QBO_BUILD_USER"  WITH ADMIN OPTION ;
  GRANT DROP ANY SYNONYM TO "QBO_BUILD_USER";
  GRANT CREATE ANY SYNONYM TO "QBO_BUILD_USER";
  GRANT DROP ANY INDEX TO "QBO_BUILD_USER";
  GRANT ALTER ANY INDEX TO "QBO_BUILD_USER";
  GRANT CREATE ANY INDEX TO "QBO_BUILD_USER";
  GRANT DROP ANY CLUSTER TO "QBO_BUILD_USER";
  GRANT ALTER ANY CLUSTER TO "QBO_BUILD_USER";
  GRANT CREATE ANY CLUSTER TO "QBO_BUILD_USER";
  GRANT DELETE ANY TABLE TO "QBO_BUILD_USER"  WITH ADMIN OPTION ;
  GRANT UPDATE ANY TABLE TO "QBO_BUILD_USER"  WITH ADMIN OPTION ;
  GRANT INSERT ANY TABLE TO "QBO_BUILD_USER"  WITH ADMIN OPTION ;
  GRANT SELECT ANY TABLE TO "QBO_BUILD_USER"  WITH ADMIN OPTION ;
  GRANT LOCK ANY TABLE TO "QBO_BUILD_USER";
  GRANT DROP ANY TABLE TO "QBO_BUILD_USER";
  GRANT ALTER ANY TABLE TO "QBO_BUILD_USER";
  GRANT CREATE ANY TABLE TO "QBO_BUILD_USER";
  GRANT DROP USER TO "QBO_BUILD_USER";
  GRANT ALTER USER TO "QBO_BUILD_USER";
  GRANT CREATE USER TO "QBO_BUILD_USER";
  GRANT UNLIMITED TABLESPACE TO "QBO_BUILD_USER"  WITH ADMIN OPTION ;
  GRANT ALTER SESSION TO "QBO_BUILD_USER"  WITH ADMIN OPTION ;

  GRANT EXECUTE ON "SYS"."DBMS_SESSION" TO "QBO_BUILD_USER"  WITH GRANT OPTION ;
  GRANT EXECUTE ON "SYS"."DBMS_RLS" TO "QBO_BUILD_USER"  WITH GRANT OPTION ;
  GRANT EXECUTE ON "SYS"."DBMS_REDEFINITION" TO "QBO_BUILD_USER";
  GRANT EXECUTE ON "SYS"."DBMS_WORKLOAD_REPOSITORY" TO "QBO_BUILD_USER";

