ALTER TABLE PSPADM.PSP_BATCH_JOB_SETUP DISABLE  CONSTRAINT C_PSP_BATCH_JOB_SETUP0;

ALTER TABLE PSPADM.PSP_BATCH_JOB_SETUP CONSTRAINT  C_PSP_BATCH_JOB_SETUP0 ENABLE  NOVALIDATE;

Prompt Constraint C_PSP_EVENT_DETAIL_TYPE0;
ALTER TABLE PSPADM.PSP_EVENT_DETAIL_TYPE DISABLE  CONSTRAINT C_PSP_EVENT_DETAIL_TYPE0;

ALTER TABLE PSPADM.PSP_EVENT_DETAIL_TYPE CONSTRAINT  C_PSP_EVENT_DETAIL_TYPE0 ENABLE  NOVALIDATE;

Prompt Constraint C_PSP_BATCH_JOB_STATUS0;
ALTER TABLE PSPADM.PSP_BATCH_JOB_STATUS DISABLE  CONSTRAINT C_PSP_BATCH_JOB_STATUS0;

ALTER TABLE PSPADM.PSP_BATCH_JOB_STATUS CONSTRAINT  C_PSP_BATCH_JOB_STATUS0 ENABLE  NOVALIDATE;

Prompt Constraint C_PSP_EVENT_TYPE0;
ALTER TABLE PSPADM.PSP_EVENT_TYPE DISABLE  CONSTRAINT C_PSP_EVENT_TYPE0;

ALTER TABLE PSPADM.PSP_EVENT_TYPE CONSTRAINT  C_PSP_EVENT_TYPE0 ENABLE  NOVALIDATE;

Prompt Constraint C_PSP_COMPANY_EVENT1;
ALTER TABLE PSPADM.PSP_COMPANY_EVENT DISABLE  CONSTRAINT C_PSP_COMPANY_EVENT1;

ALTER TABLE PSPADM.PSP_COMPANY_EVENT CONSTRAINT  C_PSP_COMPANY_EVENT1 ENABLE  NOVALIDATE;

Prompt Constraint C_PSP_COMPANY_EVENT_DETAIL0;
ALTER TABLE PSPADM.PSP_COMPANY_EVENT_DETAIL DISABLE  CONSTRAINT C_PSP_COMPANY_EVENT_DETAIL0;

ALTER TABLE PSPADM.PSP_COMPANY_EVENT_DETAIL CONSTRAINT  C_PSP_COMPANY_EVENT_DETAIL0 ENABLE  NOVALIDATE;

Prompt Constraint C_PSP_COMPANY_EVENT_EMAIL1;
ALTER TABLE PSPADM.PSP_COMPANY_EVENT_EMAIL DISABLE  CONSTRAINT C_PSP_COMPANY_EVENT_EMAIL1;

ALTER TABLE PSPADM.PSP_COMPANY_EVENT_EMAIL CONSTRAINT  C_PSP_COMPANY_EVENT_EMAIL1 ENABLE  NOVALIDATE;

Prompt Constraint C_PSP_COMPANY_EVENT_EMAIL_0;
ALTER TABLE PSPADM.PSP_COMPANY_EVENT_EMAIL_PARAM DISABLE  CONSTRAINT C_PSP_COMPANY_EVENT_EMAIL_0;

ALTER TABLE PSPADM.PSP_COMPANY_EVENT_EMAIL_PARAM CONSTRAINT  C_PSP_COMPANY_EVENT_EMAIL_0 ENABLE  NOVALIDATE;

Prompt Constraint C_PSP_FRAUD_EVENT1;
ALTER TABLE PSPADM.PSP_FRAUD_EVENT DISABLE  CONSTRAINT C_PSP_FRAUD_EVENT1;

ALTER TABLE PSPADM.PSP_FRAUD_EVENT CONSTRAINT  C_PSP_FRAUD_EVENT1 ENABLE  NOVALIDATE;

ALTER TABLE "PSPADM"."PSP_NACHAFILE" MODIFY ("OFFLOAD_BATCH_FK" NULL);
ALTER TABLE "PSPADM"."PSP_NACHAFILE" MODIFY ("OFFLOAD_BATCH_FK" NOT NULL ENABLE NOVALIDATE);

ALTER TABLE "PSPADM"."PSP_TRANSACTION_RETURN_BATCH" DISABLE CONSTRAINT "C_PSP_TRANSACTION_RETURN_B0" ;
ALTER TABLE "PSPADM"."PSP_TRANSACTION_RETURN_BATCH" CONSTRAINT "C_PSP_TRANSACTION_RETURN_B0" ENABLE NOVALIDATE;

ALTER TABLE "PSPADM"."PSP_EVENT_LOG" DISABLE CONSTRAINT "C_PSP_EVENT_LOG0";
ALTER TABLE "PSPADM"."PSP_EVENT_LOG" CONSTRAINT "C_PSP_EVENT_LOG0" ENABLE NOVALIDATE;

ALTER TABLE "PSPADM"."PSP_LEDGER_BALANCE" MODIFY ("REPORTING_TYPE" NULL);
ALTER TABLE "PSPADM"."PSP_LEDGER_BALANCE" MODIFY ("REPORTING_TYPE" NOT NULL ENABLE NOVALIDATE);

ALTER TABLE "PSPADM"."PSP_TP401K_BATCH_EMPLOYEE" Disable CONSTRAINT "PSP_TP401K_BATCH_EE_FK2 ";
ALTER TABLE "PSPADM"."PSP_TP401K_BATCH_EMPLOYEE" CONSTRAINT "PSP_TP401K_BATCH_EE_FK2 " enable novalidate;
