# Properties file for EFTPS Bulk Acknowledgment Splitter

inputDir    = /qsys.lib/dhaddan.lib/dtest3.file
errorDir    = /dawnifs/error
renoDir     = /qsys.lib/dhaddan.lib/dtest2.file
sandiegoDir = /dawnifs/sd
log4jPropertiesFilePath=/app/eftps/config/log4j.properties
