\timing
set search_path=pspadm;
SELECT CURRENT_TIMESTAMP;

select 'creating index on psp_paycheck_usage' as status;
create index concurrently psp_paycheck_usage_fk1_2012 on pspadm.psp_paycheck_usage_2012  USING BTREE (company_fk );
create index concurrently psp_paycheck_usage_fk1_2013 on pspadm.psp_paycheck_usage_2013  USING BTREE (company_fk );
create index concurrently psp_paycheck_usage_fk1_2014 on pspadm.psp_paycheck_usage_2014  USING BTREE (company_fk );
create index concurrently psp_paycheck_usage_fk1_2015 on pspadm.psp_paycheck_usage_2015  USING BTREE (company_fk );
create index concurrently psp_paycheck_usage_fk1_2016 on pspadm.psp_paycheck_usage_2016  USING BTREE (company_fk );
create index concurrently psp_paycheck_usage_fk1_2017 on pspadm.psp_paycheck_usage_2017  USING BTREE (company_fk );
create index concurrently psp_paycheck_usage_fk1_2018 on pspadm.psp_paycheck_usage_2018  USING BTREE (company_fk );
create index concurrently psp_paycheck_usage_fk1_2019 on pspadm.psp_paycheck_usage_2019  USING BTREE (company_fk );
create index concurrently psp_paycheck_usage_fk1_2020 on pspadm.psp_paycheck_usage_2020  USING BTREE (company_fk );
create index concurrently psp_paycheck_usage_fk1_2021 on pspadm.psp_paycheck_usage_2021  USING BTREE (company_fk );
create index concurrently psp_paycheck_usage_fk1_2022 on pspadm.psp_paycheck_usage_2022  USING BTREE (company_fk );
create index concurrently psp_paycheck_usage_fk1_2023 on pspadm.psp_paycheck_usage_2023  USING BTREE (company_fk );
create index concurrently psp_paycheck_usage_fk1_2024 on pspadm.psp_paycheck_usage_2024  USING BTREE (company_fk );
create index concurrently psp_paycheck_usage_fk1_2025 on pspadm.psp_paycheck_usage_2025  USING BTREE (company_fk );
create index concurrently psp_paycheck_usage_fk1_2026 on pspadm.psp_paycheck_usage_2026  USING BTREE (company_fk );

create index concurrently psp_paycheck_usage_nu1_2012 on pspadm.psp_paycheck_usage_2012  USING BTREE (source_paycheck_id );
create index concurrently psp_paycheck_usage_nu1_2013 on pspadm.psp_paycheck_usage_2013  USING BTREE (source_paycheck_id );
create index concurrently psp_paycheck_usage_nu1_2014 on pspadm.psp_paycheck_usage_2014  USING BTREE (source_paycheck_id );
create index concurrently psp_paycheck_usage_nu1_2015 on pspadm.psp_paycheck_usage_2015  USING BTREE (source_paycheck_id );
create index concurrently psp_paycheck_usage_nu1_2016 on pspadm.psp_paycheck_usage_2016  USING BTREE (source_paycheck_id );
create index concurrently psp_paycheck_usage_nu1_2017 on pspadm.psp_paycheck_usage_2017  USING BTREE (source_paycheck_id );
create index concurrently psp_paycheck_usage_nu1_2018 on pspadm.psp_paycheck_usage_2018  USING BTREE (source_paycheck_id );
create index concurrently psp_paycheck_usage_nu1_2019 on pspadm.psp_paycheck_usage_2019  USING BTREE (source_paycheck_id );
create index concurrently psp_paycheck_usage_nu1_2020 on pspadm.psp_paycheck_usage_2020  USING BTREE (source_paycheck_id );
create index concurrently psp_paycheck_usage_nu1_2021 on pspadm.psp_paycheck_usage_2021  USING BTREE (source_paycheck_id );
create index concurrently psp_paycheck_usage_nu1_2022 on pspadm.psp_paycheck_usage_2022  USING BTREE (source_paycheck_id );
create index concurrently psp_paycheck_usage_nu1_2023 on pspadm.psp_paycheck_usage_2023  USING BTREE (source_paycheck_id );
create index concurrently psp_paycheck_usage_nu1_2024 on pspadm.psp_paycheck_usage_2024  USING BTREE (source_paycheck_id );
create index concurrently psp_paycheck_usage_nu1_2025 on pspadm.psp_paycheck_usage_2025  USING BTREE (source_paycheck_id );
create index concurrently psp_paycheck_usage_nu1_2026 on pspadm.psp_paycheck_usage_2026  USING BTREE (source_paycheck_id );

create index concurrently psp_paycheck_usage_u1_2012 on pspadm.psp_paycheck_usage_2012  USING BTREE (employee_usage_fk ,source_paycheck_id );
create index concurrently psp_paycheck_usage_u1_2013 on pspadm.psp_paycheck_usage_2013  USING BTREE (employee_usage_fk ,source_paycheck_id );
create index concurrently psp_paycheck_usage_u1_2014 on pspadm.psp_paycheck_usage_2014  USING BTREE (employee_usage_fk ,source_paycheck_id );
create index concurrently psp_paycheck_usage_u1_2015 on pspadm.psp_paycheck_usage_2015  USING BTREE (employee_usage_fk ,source_paycheck_id );
create index concurrently psp_paycheck_usage_u1_2016 on pspadm.psp_paycheck_usage_2016  USING BTREE (employee_usage_fk ,source_paycheck_id );
create index concurrently psp_paycheck_usage_u1_2017 on pspadm.psp_paycheck_usage_2017  USING BTREE (employee_usage_fk ,source_paycheck_id );
create index concurrently psp_paycheck_usage_u1_2018 on pspadm.psp_paycheck_usage_2018  USING BTREE (employee_usage_fk ,source_paycheck_id );
create index concurrently psp_paycheck_usage_u1_2019 on pspadm.psp_paycheck_usage_2019  USING BTREE (employee_usage_fk ,source_paycheck_id );
create index concurrently psp_paycheck_usage_u1_2020 on pspadm.psp_paycheck_usage_2020  USING BTREE (employee_usage_fk ,source_paycheck_id );
create index concurrently psp_paycheck_usage_u1_2021 on pspadm.psp_paycheck_usage_2021  USING BTREE (employee_usage_fk ,source_paycheck_id );
create index concurrently psp_paycheck_usage_u1_2022 on pspadm.psp_paycheck_usage_2022  USING BTREE (employee_usage_fk ,source_paycheck_id );
create index concurrently psp_paycheck_usage_u1_2023 on pspadm.psp_paycheck_usage_2023  USING BTREE (employee_usage_fk ,source_paycheck_id );
create index concurrently psp_paycheck_usage_u1_2024 on pspadm.psp_paycheck_usage_2024  USING BTREE (employee_usage_fk ,source_paycheck_id );
create index concurrently psp_paycheck_usage_u1_2025 on pspadm.psp_paycheck_usage_2025  USING BTREE (employee_usage_fk ,source_paycheck_id );
create index concurrently psp_paycheck_usage_u1_2026 on pspadm.psp_paycheck_usage_2026  USING BTREE (employee_usage_fk ,source_paycheck_id );

create index concurrently psp_paycheckusage_fk1_2012 on pspadm.psp_paycheck_usage_2012  USING BTREE (bill_fk );
create index concurrently psp_paycheckusage_fk1_2013 on pspadm.psp_paycheck_usage_2013  USING BTREE (bill_fk );
create index concurrently psp_paycheckusage_fk1_2014 on pspadm.psp_paycheck_usage_2014  USING BTREE (bill_fk );
create index concurrently psp_paycheckusage_fk1_2015 on pspadm.psp_paycheck_usage_2015  USING BTREE (bill_fk );
create index concurrently psp_paycheckusage_fk1_2016 on pspadm.psp_paycheck_usage_2016  USING BTREE (bill_fk );
create index concurrently psp_paycheckusage_fk1_2017 on pspadm.psp_paycheck_usage_2017  USING BTREE (bill_fk );
create index concurrently psp_paycheckusage_fk1_2018 on pspadm.psp_paycheck_usage_2018  USING BTREE (bill_fk );
create index concurrently psp_paycheckusage_fk1_2019 on pspadm.psp_paycheck_usage_2019  USING BTREE (bill_fk );
create index concurrently psp_paycheckusage_fk1_2020 on pspadm.psp_paycheck_usage_2020  USING BTREE (bill_fk );
create index concurrently psp_paycheckusage_fk1_2021 on pspadm.psp_paycheck_usage_2021  USING BTREE (bill_fk );
create index concurrently psp_paycheckusage_fk1_2022 on pspadm.psp_paycheck_usage_2022  USING BTREE (bill_fk );
create index concurrently psp_paycheckusage_fk1_2023 on pspadm.psp_paycheck_usage_2023  USING BTREE (bill_fk );
create index concurrently psp_paycheckusage_fk1_2024 on pspadm.psp_paycheck_usage_2024  USING BTREE (bill_fk );
create index concurrently psp_paycheckusage_fk1_2025 on pspadm.psp_paycheck_usage_2025  USING BTREE (bill_fk );
create index concurrently psp_paycheckusage_fk1_2026 on pspadm.psp_paycheck_usage_2026  USING BTREE (bill_fk );

create index concurrently psp_paycheckusage_fk2_2012 on pspadm.psp_paycheck_usage_2012  USING BTREE (employee_usage_fk );
create index concurrently psp_paycheckusage_fk2_2013 on pspadm.psp_paycheck_usage_2013  USING BTREE (employee_usage_fk );
create index concurrently psp_paycheckusage_fk2_2014 on pspadm.psp_paycheck_usage_2014  USING BTREE (employee_usage_fk );
create index concurrently psp_paycheckusage_fk2_2015 on pspadm.psp_paycheck_usage_2015  USING BTREE (employee_usage_fk );
create index concurrently psp_paycheckusage_fk2_2016 on pspadm.psp_paycheck_usage_2016  USING BTREE (employee_usage_fk );
create index concurrently psp_paycheckusage_fk2_2017 on pspadm.psp_paycheck_usage_2017  USING BTREE (employee_usage_fk );
create index concurrently psp_paycheckusage_fk2_2018 on pspadm.psp_paycheck_usage_2018  USING BTREE (employee_usage_fk );
create index concurrently psp_paycheckusage_fk2_2019 on pspadm.psp_paycheck_usage_2019  USING BTREE (employee_usage_fk );
create index concurrently psp_paycheckusage_fk2_2020 on pspadm.psp_paycheck_usage_2020  USING BTREE (employee_usage_fk );
create index concurrently psp_paycheckusage_fk2_2021 on pspadm.psp_paycheck_usage_2021  USING BTREE (employee_usage_fk );
create index concurrently psp_paycheckusage_fk2_2022 on pspadm.psp_paycheck_usage_2022  USING BTREE (employee_usage_fk );
create index concurrently psp_paycheckusage_fk2_2023 on pspadm.psp_paycheck_usage_2023  USING BTREE (employee_usage_fk );
create index concurrently psp_paycheckusage_fk2_2024 on pspadm.psp_paycheck_usage_2024  USING BTREE (employee_usage_fk );
create index concurrently psp_paycheckusage_fk2_2025 on pspadm.psp_paycheck_usage_2025  USING BTREE (employee_usage_fk );
create index concurrently psp_paycheckusage_fk2_2026 on pspadm.psp_paycheck_usage_2026  USING BTREE (employee_usage_fk );

create index concurrently  idx_pchk_usg_mod_date_2012 on pspadm.psp_paycheck_usage_2012  USING BTREE (modified_date);
create index concurrently  idx_pchk_usg_mod_date_2013 on pspadm.psp_paycheck_usage_2013  USING BTREE (modified_date);
create index concurrently  idx_pchk_usg_mod_date_2014 on pspadm.psp_paycheck_usage_2014  USING BTREE (modified_date);
create index concurrently  idx_pchk_usg_mod_date_2015 on pspadm.psp_paycheck_usage_2015  USING BTREE (modified_date);
create index concurrently  idx_pchk_usg_mod_date_2016 on pspadm.psp_paycheck_usage_2016  USING BTREE (modified_date);
create index concurrently  idx_pchk_usg_mod_date_2017 on pspadm.psp_paycheck_usage_2017  USING BTREE (modified_date);
create index concurrently  idx_pchk_usg_mod_date_2018 on pspadm.psp_paycheck_usage_2018  USING BTREE (modified_date);
create index concurrently  idx_pchk_usg_mod_date_2019 on pspadm.psp_paycheck_usage_2019  USING BTREE (modified_date);
create index concurrently  idx_pchk_usg_mod_date_2020 on pspadm.psp_paycheck_usage_2020  USING BTREE (modified_date);
create index concurrently  idx_pchk_usg_mod_date_2021 on pspadm.psp_paycheck_usage_2021  USING BTREE (modified_date);
create index concurrently  idx_pchk_usg_mod_date_2022 on pspadm.psp_paycheck_usage_2022  USING BTREE (modified_date);
create index concurrently  idx_pchk_usg_mod_date_2023 on pspadm.psp_paycheck_usage_2023  USING BTREE (modified_date);
create index concurrently  idx_pchk_usg_mod_date_2024 on pspadm.psp_paycheck_usage_2024  USING BTREE (modified_date);
create index concurrently  idx_pchk_usg_mod_date_2025 on pspadm.psp_paycheck_usage_2025  USING BTREE (modified_date);
create index concurrently  idx_pchk_usg_mod_date_2026 on pspadm.psp_paycheck_usage_2026  USING BTREE (modified_date);


select  'psp_paycheck_usage completed'  as status;


--psp_paycheck_usage
create index  psp_paycheckusage_fk1 ON ONLY  pspadm.psp_paycheck_usage USING BTREE (bill_fk );
create index  psp_paycheckusage_fk2 ON ONLY  pspadm.psp_paycheck_usage USING BTREE (employee_usage_fk );
create index  psp_paycheck_usage_fk1 ON ONLY  pspadm.psp_paycheck_usage USING BTREE (company_fk );
create index  psp_paycheck_usage_nu1 ON ONLY  pspadm.psp_paycheck_usage USING BTREE (source_paycheck_id );
create index  psp_paycheck_usage_u1 ON ONLY  pspadm.psp_paycheck_usage USING BTREE (employee_usage_fk ,source_paycheck_id );
create index  idx_pchk_usg_mod_date ON ONLY  pspadm.psp_paycheck_usage USING BTREE (modified_date);

alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2012 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2013 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2014 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2015 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2016 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2017 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2018 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2019 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2020 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2021 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2022 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2023 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2024 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2025 ;
alter index psp_paycheck_usage_fk1 attach partition  pspadm.psp_paycheck_usage_fk1_2026 ;

alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2012 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2013 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2014 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2015 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2016 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2017 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2018 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2019 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2020 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2021 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2022 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2023 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2024 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2025 ;
alter index psp_paycheck_usage_nu1 attach partition  pspadm.psp_paycheck_usage_nu1_2026 ;

alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2012 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2013 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2014 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2015 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2016 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2017 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2018 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2019 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2020 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2021 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2022 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2023 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2024 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2025 ;
alter index psp_paycheck_usage_u1 attach partition  pspadm.psp_paycheck_usage_u1_2026 ;

alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2012 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2013 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2014 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2015 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2016 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2017 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2018 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2019 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2020 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2021 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2022 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2023 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2024 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2025 ;
alter index psp_paycheckusage_fk1 attach partition  pspadm.psp_paycheckusage_fk1_2026 ;

alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2012 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2013 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2014 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2015 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2016 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2017 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2018 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2019 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2020 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2021 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2022 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2023 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2024 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2025 ;
alter index psp_paycheckusage_fk2 attach partition  pspadm.psp_paycheckusage_fk2_2026 ;

alter index idx_pchk_usg_mod_date attach partition  pspadm.idx_pchk_usg_mod_date_2012 ;
alter index idx_pchk_usg_mod_date attach partition  pspadm.idx_pchk_usg_mod_date_2013 ;
alter index idx_pchk_usg_mod_date attach partition  pspadm.idx_pchk_usg_mod_date_2014 ;
alter index idx_pchk_usg_mod_date attach partition  pspadm.idx_pchk_usg_mod_date_2015 ;
alter index idx_pchk_usg_mod_date attach partition  pspadm.idx_pchk_usg_mod_date_2016 ;
alter index idx_pchk_usg_mod_date attach partition  pspadm.idx_pchk_usg_mod_date_2017 ;
alter index idx_pchk_usg_mod_date attach partition  pspadm.idx_pchk_usg_mod_date_2018 ;
alter index idx_pchk_usg_mod_date attach partition  pspadm.idx_pchk_usg_mod_date_2019 ;
alter index idx_pchk_usg_mod_date attach partition  pspadm.idx_pchk_usg_mod_date_2020 ;
alter index idx_pchk_usg_mod_date attach partition  pspadm.idx_pchk_usg_mod_date_2021 ;
alter index idx_pchk_usg_mod_date attach partition  pspadm.idx_pchk_usg_mod_date_2022 ;
alter index idx_pchk_usg_mod_date attach partition  pspadm.idx_pchk_usg_mod_date_2023 ;
alter index idx_pchk_usg_mod_date attach partition  pspadm.idx_pchk_usg_mod_date_2024 ;
alter index idx_pchk_usg_mod_date attach partition  pspadm.idx_pchk_usg_mod_date_2025 ;
alter index idx_pchk_usg_mod_date attach partition  pspadm.idx_pchk_usg_mod_date_2026 ;

SELECT CURRENT_TIMESTAMP;

