DROP TABLE IF EXISTS TEMP_RETURN_REASON_DESC CASCADE;

--------------------------------------------------------
-- Create temp table                                  --
--------------------------------------------------------
CREATE TABLE TEMP_RETURN_REASON_DESC (LIKE PSP_RETURN_REASON_DESC INCLUDING ALL) ;


--------------------------------------------------------
-- TEMP_RETURN_REASON_DESC                            --
--------------------------------------------------------
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R01', 'Insufficient Funds', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R02', 'Account Closed', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R03', 'Unable to Locate Account', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R04', 'Invalid Account Number', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R05', 'Unauthorized Debit to Consumer Account', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R06', 'Returned per Bank Request', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R07', 'Authorization Revoked by Customer', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R08', 'Payment Stopped', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R09', 'Funds Not Available to Cover Transaction(s)', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R10', 'Not Authorized Per Customer', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R11', 'Check Truncation Entry Return', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R12', 'Branch Sold to Another Bank', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R13', 'Receiving Bank Not Qualified', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R14', 'Customer Deceased', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R15', 'Beneficiary Deceased', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R16', 'Account Frozen', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R17', 'Tape Record Edit Criteria', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R18', 'Improper Effective Entry Date', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R19', 'Amount Field Error', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R20', 'Non-Transaction Account', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R21', 'Invalid Company Identification', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R22', 'Invalid Individual ID Number', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R23', 'Payment Refused by Biller', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R24', 'Duplicate Entry', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R25', 'Addenda Error', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R26', 'Mandatory Field Error', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R27', 'Trace Number Error', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R28', 'Routing Number Digit Error', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R29', 'Corporate Customer Advises not Authorized', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R30', 'Bank Not Participant in Check Truncation Program', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R31', 'Permissible Return Entry', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R32', 'Bank Non-Settlement', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R33', 'Return of XCK Entry', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R34', 'Limited Participation Bank', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R35', 'Return of Improper Debit Entry', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R36', 'Return of Improper Credit Entry', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R37', 'Source Document Presented for Payment', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R38', 'Stop Payment on ARC document', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R39', 'Improper ARC/POP Source Document', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R40', 'Return of ENR Entry by Federal Government Agency', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R41', 'Invalid Transaction Code', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R42', 'Routing Number/Check Digit Error', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R43', 'Invalid DFI Account Number', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R44', 'Invalid Individual ID Number/Identification Number', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R45', 'Invalid Individual Name/Company Name', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R46', 'Invalid Representative Payee Indicator', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R47', 'Duplicate Enrollment', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R48', NULL, '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R49', NULL, '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R50', 'State Law Affecting RCK Acceptance', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R51', 'Item Ineligible, Signature Not Genuine', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R52', 'Stop Payment on Item', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R53', 'Duplicate ACH entry presented for payment.', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R61', 'Misrouted Return', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R62', 'Incorrect Trace Number', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R63', 'Incorrect Dollar Amount', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R64', 'Incorrect Individual Identification', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R65', 'Incorrect Transaction Code', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R66', 'Incorrect Company Identification', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R67', 'Duplicate Return', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R68', 'Untimely Return', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R69', 'Multiple Errors', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R70', 'Permissible Return Entry Not Accepted', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R71', 'Misrouted Dishonored Return', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R72', 'Untimely Dishonored Return', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R73', 'Timely Original Return', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R74', 'Corrected Return', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R75', 'Original Return Not a Duplicate', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R76', 'No Errors Found', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R80', 'Cross-Border Payment Coding Error', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R81', 'Non-Participant in Cross-Border Program', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R82', 'Invalid Foreign Receiving Bank Identification', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R83', 'Foreign Receiving Bank Unable to Settle', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R84', 'Entry Not Processed by OGO', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'R99', NULL, '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'C01', 'Incorrect Bank Account Number', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'C02', 'Incorrect Routing Number', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'C03', 'Incorrect Routing Number and Incorrect Bank Account Number', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'C04', 'Incorrect Account Holder Name', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'C05', 'Incorrect Transaction Code', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'C06', 'Incorrect Bank Account Number and Incorrect Transaction Code', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'C07', 'Incorrect Routing Number, Bank Account Number & Transaction Code', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'C08', 'Incorrect Foreign Receiving Identification', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'C09', 'Incorrect Individual ID Number', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'C10', NULL, '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'C11', NULL, '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'C12', NULL, '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'C13', 'Addenda Format Error', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'C61', 'Misrouted Notification of Change', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'C62', 'Incorrect Trace Number', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'C63', 'Incorrect Company Identification Number', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'C64', 'Incorrect Individual Identification Number', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'C65', 'Incorrectly Formatted Corrected Data', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'C66', 'Incorrect Discretionary Data', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'C67', 'Routing Number Not From Original Entry Detail Record', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'C68', 'DFI Account Number Not From Original Entry Detail Record', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'C69', 'Incorrect Transaction Code', '0')
;
INSERT INTO TEMP_RETURN_REASON_DESC ( REASON_CD, DESCRIPTION, VERSION ) VALUES (
'C99', NULL, '0')
;


--------------------------------------------------------
-- Sychronize temp table and real table by            --
-- inserting, deleting, and updating as necessary     --
--------------------------------------------------------

INSERT INTO PSP_RETURN_REASON_DESC
   ( REASON_CD, VERSION, DESCRIPTION )
SELECT
    REASON_CD, VERSION, DESCRIPTION
FROM
   TEMP_RETURN_REASON_DESC tt
WHERE
   tt.REASON_CD NOT IN ( SELECT REASON_CD FROM PSP_RETURN_REASON_DESC )
;

DELETE FROM PSP_RETURN_REASON_DESC
WHERE REASON_CD NOT IN (SELECT REASON_CD FROM TEMP_RETURN_REASON_DESC)
;

UPDATE PSP_RETURN_REASON_DESC rt
SET ( DESCRIPTION ) =
( SELECT tt.DESCRIPTION
  FROM TEMP_RETURN_REASON_DESC tt
  WHERE tt.REASON_CD = rt.REASON_CD )
;


--------------------------------------------------------
-- Drop temp table                                  --
--------------------------------------------------------
DROP TABLE TEMP_RETURN_REASON_DESC
;

COMMIT
