DROP TABLE IF EXISTS TEMP_DEPOSIT_FREQUENCY CASCADE;

--------------------------------------------------------
-- Create temp table                                  --
--------------------------------------------------------

CREATE TABLE TEMP_DEPOSIT_FREQUENCY (LIKE PSP_DEPOSIT_FREQUENCY INCLUDING ALL) ;

--------------------------------------------------------
-- Insert into temp table                             --
--------------------------------------------------------

INSERT INTO TEMP_DEPOSIT_FREQUENCY (DEPOSIT_FREQUENCY_CODE, VERSION, A_T_F_DEPOSIT_FREQ_CODE, DESCRIPTION) VALUES (
'ACCELERATED', 0, NULL, 'Accelerated')
;
INSERT INTO TEMP_DEPOSIT_FREQUENCY (DEPOSIT_FREQUENCY_CODE, VERSION, A_T_F_DEPOSIT_FREQ_CODE, DESCRIPTION) VALUES (
'ANNUAL', 0, 'A', 'Annually')
;
INSERT INTO TEMP_DEPOSIT_FREQUENCY (DEPOSIT_FREQUENCY_CODE, VERSION, A_T_F_DEPOSIT_FREQ_CODE, DESCRIPTION) VALUES (
'EARLYFILER', 0, NULL, 'Early Filer')
;
INSERT INTO TEMP_DEPOSIT_FREQUENCY (DEPOSIT_FREQUENCY_CODE, VERSION, A_T_F_DEPOSIT_FREQ_CODE, DESCRIPTION) VALUES (
'EIGHTHMONTHLY', 0, 'EM', 'Eighth Monthly')
;
INSERT INTO TEMP_DEPOSIT_FREQUENCY (DEPOSIT_FREQUENCY_CODE, VERSION, A_T_F_DEPOSIT_FREQ_CODE, DESCRIPTION) VALUES (
'FIVEBANKINGDAY', 0, NULL, 'Five Banking Day')
;
INSERT INTO TEMP_DEPOSIT_FREQUENCY (DEPOSIT_FREQUENCY_CODE, VERSION, A_T_F_DEPOSIT_FREQ_CODE, DESCRIPTION) VALUES (
'MONTHLY', 0, 'M', 'Monthly')
;
INSERT INTO TEMP_DEPOSIT_FREQUENCY (DEPOSIT_FREQUENCY_CODE, VERSION, A_T_F_DEPOSIT_FREQ_CODE, DESCRIPTION) VALUES (
'MONTHLYACCELERATED', 0, NULL, 'Monthly Accelerated')
;
INSERT INTO TEMP_DEPOSIT_FREQUENCY (DEPOSIT_FREQUENCY_CODE, VERSION, A_T_F_DEPOSIT_FREQ_CODE, DESCRIPTION) VALUES (
'NEXTBANKINGDAY', 0, NULL, 'Next Banking Day')
;
INSERT INTO TEMP_DEPOSIT_FREQUENCY (DEPOSIT_FREQUENCY_CODE, VERSION, A_T_F_DEPOSIT_FREQ_CODE, DESCRIPTION) VALUES (
'NOCALC', 0, NULL, 'No Calculation')
;
INSERT INTO TEMP_DEPOSIT_FREQUENCY (DEPOSIT_FREQUENCY_CODE, VERSION, A_T_F_DEPOSIT_FREQ_CODE, DESCRIPTION) VALUES (
'QUADMONTHLY', 0, NULL, 'Quad Monthly')
;
INSERT INTO TEMP_DEPOSIT_FREQUENCY (DEPOSIT_FREQUENCY_CODE, VERSION, A_T_F_DEPOSIT_FREQ_CODE, DESCRIPTION) VALUES (
'QUARTERLY', 0, 'Q', 'Quarterly')
;
INSERT INTO TEMP_DEPOSIT_FREQUENCY (DEPOSIT_FREQUENCY_CODE, VERSION, A_T_F_DEPOSIT_FREQ_CODE, DESCRIPTION) VALUES (
'QUARTERMONTHLY', 0, 'QM', 'Quarter-Monthly')
;
INSERT INTO TEMP_DEPOSIT_FREQUENCY (DEPOSIT_FREQUENCY_CODE, VERSION, A_T_F_DEPOSIT_FREQ_CODE, DESCRIPTION) VALUES (
'SEMIANNUAL', 0, 'SA', 'Semi-Annually')
;
INSERT INTO TEMP_DEPOSIT_FREQUENCY (DEPOSIT_FREQUENCY_CODE, VERSION, A_T_F_DEPOSIT_FREQ_CODE, DESCRIPTION) VALUES (
'SEMIMONTHLY', 0, 'SM', 'Semi-Monthly')
;
INSERT INTO TEMP_DEPOSIT_FREQUENCY (DEPOSIT_FREQUENCY_CODE, VERSION, A_T_F_DEPOSIT_FREQ_CODE, DESCRIPTION) VALUES (
'SEMIWEEKLY', 0, 'SW', 'Semi-Weekly')
;
INSERT INTO TEMP_DEPOSIT_FREQUENCY (DEPOSIT_FREQUENCY_CODE, VERSION, A_T_F_DEPOSIT_FREQ_CODE, DESCRIPTION) VALUES (
'SPLITMONTHLY', 0, 'SM', 'Split-Monthly')
;
INSERT INTO TEMP_DEPOSIT_FREQUENCY (DEPOSIT_FREQUENCY_CODE, VERSION, A_T_F_DEPOSIT_FREQ_CODE, DESCRIPTION) VALUES (
'THREEBANKINGDAY', 0, '3D', 'Third Day')
;
INSERT INTO TEMP_DEPOSIT_FREQUENCY (DEPOSIT_FREQUENCY_CODE, VERSION, A_T_F_DEPOSIT_FREQ_CODE, DESCRIPTION) VALUES (
'TWICEMONTHLY', 0, 'TM', 'Twice Monthly')
;
INSERT INTO TEMP_DEPOSIT_FREQUENCY (DEPOSIT_FREQUENCY_CODE, VERSION, A_T_F_DEPOSIT_FREQ_CODE, DESCRIPTION) VALUES (
'WEEKLY', 0, 'W', 'Weekly')
;
--------------------------------------------------------
-- Sychronize temp table and real table by            --
-- inserting, deleting, and updating as necessary     --
--------------------------------------------------------

INSERT INTO PSP_DEPOSIT_FREQUENCY
   (DEPOSIT_FREQUENCY_CODE, VERSION, A_T_F_DEPOSIT_FREQ_CODE,DESCRIPTION)
SELECT 
    DEPOSIT_FREQUENCY_CODE, VERSION, A_T_F_DEPOSIT_FREQ_CODE,DESCRIPTION
FROM 
   TEMP_DEPOSIT_FREQUENCY f
WHERE 
   f.DEPOSIT_FREQUENCY_CODE NOT IN (SELECT DEPOSIT_FREQUENCY_CODE FROM PSP_DEPOSIT_FREQUENCY)

;

DELETE FROM PSP_DEPOSIT_FREQUENCY
WHERE DEPOSIT_FREQUENCY_CODE NOT IN (SELECT DEPOSIT_FREQUENCY_CODE FROM TEMP_DEPOSIT_FREQUENCY)

;

UPDATE PSP_DEPOSIT_FREQUENCY rf
SET  (VERSION, DEPOSIT_FREQUENCY_CODE, A_T_F_DEPOSIT_FREQ_CODE,DESCRIPTION) =
(SELECT  tf.VERSION, tf.DEPOSIT_FREQUENCY_CODE, tf.A_T_F_DEPOSIT_FREQ_CODE,tf.DESCRIPTION
 FROM TEMP_DEPOSIT_FREQUENCY tf WHERE tf.DEPOSIT_FREQUENCY_CODE = rf.DEPOSIT_FREQUENCY_CODE)
;



--------------------------------------------------------
-- Drop temp table                                  --
--------------------------------------------------------
DROP TABLE TEMP_DEPOSIT_FREQUENCY

;
COMMIT
 

 
