\timing
set search_path=pspadm;
SELECT CURRENT_TIMESTAMP;

select 'creating index on psp_entry_detail_record' as status;
create index psp_entry_detail_record_fk1_p0 on pspadm.psp_entry_detail_record_p0 USING BTREE (intuit_bank_account_fk ASC);
create index psp_entry_detail_record_fk1_p1 on pspadm.psp_entry_detail_record_p1 USING BTREE (intuit_bank_account_fk ASC);
create index psp_entry_detail_record_fk1_p10 on pspadm.psp_entry_detail_record_p10 USING BTREE (intuit_bank_account_fk ASC);
create index psp_entry_detail_record_fk1_p11 on pspadm.psp_entry_detail_record_p11 USING BTREE (intuit_bank_account_fk ASC);
create index psp_entry_detail_record_fk1_p12 on pspadm.psp_entry_detail_record_p12 USING BTREE (intuit_bank_account_fk ASC);
create index psp_entry_detail_record_fk1_p13 on pspadm.psp_entry_detail_record_p13 USING BTREE (intuit_bank_account_fk ASC);
create index psp_entry_detail_record_fk1_p14 on pspadm.psp_entry_detail_record_p14 USING BTREE (intuit_bank_account_fk ASC);
create index psp_entry_detail_record_fk1_p15 on pspadm.psp_entry_detail_record_p15 USING BTREE (intuit_bank_account_fk ASC);
create index psp_entry_detail_record_fk1_p2 on pspadm.psp_entry_detail_record_p2 USING BTREE (intuit_bank_account_fk ASC);
create index psp_entry_detail_record_fk1_p3 on pspadm.psp_entry_detail_record_p3 USING BTREE (intuit_bank_account_fk ASC);
create index psp_entry_detail_record_fk1_p4 on pspadm.psp_entry_detail_record_p4 USING BTREE (intuit_bank_account_fk ASC);
create index psp_entry_detail_record_fk1_p5 on pspadm.psp_entry_detail_record_p5 USING BTREE (intuit_bank_account_fk ASC);
create index psp_entry_detail_record_fk1_p6 on pspadm.psp_entry_detail_record_p6 USING BTREE (intuit_bank_account_fk ASC);
create index psp_entry_detail_record_fk1_p7 on pspadm.psp_entry_detail_record_p7 USING BTREE (intuit_bank_account_fk ASC);
create index psp_entry_detail_record_fk1_p8 on pspadm.psp_entry_detail_record_p8 USING BTREE (intuit_bank_account_fk ASC);
create index psp_entry_detail_record_fk1_p9 on pspadm.psp_entry_detail_record_p9 USING BTREE (intuit_bank_account_fk ASC);
create index psp_entry_detail_record_fk2_p0 on pspadm.psp_entry_detail_record_p0 USING BTREE (n_a_c_h_a_file_fk ASC,intuit_bank_account_fk ASC);
create index psp_entry_detail_record_fk2_p1 on pspadm.psp_entry_detail_record_p1 USING BTREE (n_a_c_h_a_file_fk ASC,intuit_bank_account_fk ASC);
create index psp_entry_detail_record_fk2_p10 on pspadm.psp_entry_detail_record_p10 USING BTREE (n_a_c_h_a_file_fk ASC,intuit_bank_account_fk ASC);
create index psp_entry_detail_record_fk2_p11 on pspadm.psp_entry_detail_record_p11 USING BTREE (n_a_c_h_a_file_fk ASC,intuit_bank_account_fk ASC);
create index psp_entry_detail_record_fk2_p12 on pspadm.psp_entry_detail_record_p12 USING BTREE (n_a_c_h_a_file_fk ASC,intuit_bank_account_fk ASC);
create index psp_entry_detail_record_fk2_p13 on pspadm.psp_entry_detail_record_p13 USING BTREE (n_a_c_h_a_file_fk ASC,intuit_bank_account_fk ASC);
create index psp_entry_detail_record_fk2_p14 on pspadm.psp_entry_detail_record_p14 USING BTREE (n_a_c_h_a_file_fk ASC,intuit_bank_account_fk ASC);
create index psp_entry_detail_record_fk2_p15 on pspadm.psp_entry_detail_record_p15 USING BTREE (n_a_c_h_a_file_fk ASC,intuit_bank_account_fk ASC);
create index psp_entry_detail_record_fk2_p2 on pspadm.psp_entry_detail_record_p2 USING BTREE (n_a_c_h_a_file_fk ASC,intuit_bank_account_fk ASC);
create index psp_entry_detail_record_fk2_p3 on pspadm.psp_entry_detail_record_p3 USING BTREE (n_a_c_h_a_file_fk ASC,intuit_bank_account_fk ASC);
create index psp_entry_detail_record_fk2_p4 on pspadm.psp_entry_detail_record_p4 USING BTREE (n_a_c_h_a_file_fk ASC,intuit_bank_account_fk ASC);
create index psp_entry_detail_record_fk2_p5 on pspadm.psp_entry_detail_record_p5 USING BTREE (n_a_c_h_a_file_fk ASC,intuit_bank_account_fk ASC);
create index psp_entry_detail_record_fk2_p6 on pspadm.psp_entry_detail_record_p6 USING BTREE (n_a_c_h_a_file_fk ASC,intuit_bank_account_fk ASC);
create index psp_entry_detail_record_fk2_p7 on pspadm.psp_entry_detail_record_p7 USING BTREE (n_a_c_h_a_file_fk ASC,intuit_bank_account_fk ASC);
create index psp_entry_detail_record_fk2_p8 on pspadm.psp_entry_detail_record_p8 USING BTREE (n_a_c_h_a_file_fk ASC,intuit_bank_account_fk ASC);
create index psp_entry_detail_record_fk2_p9 on pspadm.psp_entry_detail_record_p9 USING BTREE (n_a_c_h_a_file_fk ASC,intuit_bank_account_fk ASC);
create index psp_entry_detail_record_fk3_p0 on pspadm.psp_entry_detail_record_p0 USING BTREE (company_fk ASC,money_movement_transaction_fk ASC);
create index psp_entry_detail_record_fk3_p1 on pspadm.psp_entry_detail_record_p1 USING BTREE (company_fk ASC,money_movement_transaction_fk ASC);
create index psp_entry_detail_record_fk3_p10 on pspadm.psp_entry_detail_record_p10 USING BTREE (company_fk ASC,money_movement_transaction_fk ASC);
create index psp_entry_detail_record_fk3_p11 on pspadm.psp_entry_detail_record_p11 USING BTREE (company_fk ASC,money_movement_transaction_fk ASC);
create index psp_entry_detail_record_fk3_p12 on pspadm.psp_entry_detail_record_p12 USING BTREE (company_fk ASC,money_movement_transaction_fk ASC);
create index psp_entry_detail_record_fk3_p13 on pspadm.psp_entry_detail_record_p13 USING BTREE (company_fk ASC,money_movement_transaction_fk ASC);
create index psp_entry_detail_record_fk3_p14 on pspadm.psp_entry_detail_record_p14 USING BTREE (company_fk ASC,money_movement_transaction_fk ASC);
create index psp_entry_detail_record_fk3_p15 on pspadm.psp_entry_detail_record_p15 USING BTREE (company_fk ASC,money_movement_transaction_fk ASC);
create index psp_entry_detail_record_fk3_p2 on pspadm.psp_entry_detail_record_p2 USING BTREE (company_fk ASC,money_movement_transaction_fk ASC);
create index psp_entry_detail_record_fk3_p3 on pspadm.psp_entry_detail_record_p3 USING BTREE (company_fk ASC,money_movement_transaction_fk ASC);
create index psp_entry_detail_record_fk3_p4 on pspadm.psp_entry_detail_record_p4 USING BTREE (company_fk ASC,money_movement_transaction_fk ASC);
create index psp_entry_detail_record_fk3_p5 on pspadm.psp_entry_detail_record_p5 USING BTREE (company_fk ASC,money_movement_transaction_fk ASC);
create index psp_entry_detail_record_fk3_p6 on pspadm.psp_entry_detail_record_p6 USING BTREE (company_fk ASC,money_movement_transaction_fk ASC);
create index psp_entry_detail_record_fk3_p7 on pspadm.psp_entry_detail_record_p7 USING BTREE (company_fk ASC,money_movement_transaction_fk ASC);
create index psp_entry_detail_record_fk3_p8 on pspadm.psp_entry_detail_record_p8 USING BTREE (company_fk ASC,money_movement_transaction_fk ASC);
create index psp_entry_detail_record_fk3_p9 on pspadm.psp_entry_detail_record_p9 USING BTREE (company_fk ASC,money_movement_transaction_fk ASC);
create index psp_entry_detail_record_fk4_p0 on pspadm.psp_entry_detail_record_p0 USING BTREE (company_fk ASC);
create index psp_entry_detail_record_fk4_p1 on pspadm.psp_entry_detail_record_p1 USING BTREE (company_fk ASC);
create index psp_entry_detail_record_fk4_p10 on pspadm.psp_entry_detail_record_p10 USING BTREE (company_fk ASC);
create index psp_entry_detail_record_fk4_p11 on pspadm.psp_entry_detail_record_p11 USING BTREE (company_fk ASC);
create index psp_entry_detail_record_fk4_p12 on pspadm.psp_entry_detail_record_p12 USING BTREE (company_fk ASC);
create index psp_entry_detail_record_fk4_p13 on pspadm.psp_entry_detail_record_p13 USING BTREE (company_fk ASC);
create index psp_entry_detail_record_fk4_p14 on pspadm.psp_entry_detail_record_p14 USING BTREE (company_fk ASC);
create index psp_entry_detail_record_fk4_p15 on pspadm.psp_entry_detail_record_p15 USING BTREE (company_fk ASC);
create index psp_entry_detail_record_fk4_p2 on pspadm.psp_entry_detail_record_p2 USING BTREE (company_fk ASC);
create index psp_entry_detail_record_fk4_p3 on pspadm.psp_entry_detail_record_p3 USING BTREE (company_fk ASC);
create index psp_entry_detail_record_fk4_p4 on pspadm.psp_entry_detail_record_p4 USING BTREE (company_fk ASC);
create index psp_entry_detail_record_fk4_p5 on pspadm.psp_entry_detail_record_p5 USING BTREE (company_fk ASC);
create index psp_entry_detail_record_fk4_p6 on pspadm.psp_entry_detail_record_p6 USING BTREE (company_fk ASC);
create index psp_entry_detail_record_fk4_p7 on pspadm.psp_entry_detail_record_p7 USING BTREE (company_fk ASC);
create index psp_entry_detail_record_fk4_p8 on pspadm.psp_entry_detail_record_p8 USING BTREE (company_fk ASC);
create index psp_entry_detail_record_fk4_p9 on pspadm.psp_entry_detail_record_p9 USING BTREE (company_fk ASC);
create index psp_entry_detail_record_i1_p0 on pspadm.psp_entry_detail_record_p0 USING BTREE (trace_number ASC);
create index psp_entry_detail_record_i1_p1 on pspadm.psp_entry_detail_record_p1 USING BTREE (trace_number ASC);
create index psp_entry_detail_record_i1_p10 on pspadm.psp_entry_detail_record_p10 USING BTREE (trace_number ASC);
create index psp_entry_detail_record_i1_p11 on pspadm.psp_entry_detail_record_p11 USING BTREE (trace_number ASC);
create index psp_entry_detail_record_i1_p12 on pspadm.psp_entry_detail_record_p12 USING BTREE (trace_number ASC);
create index psp_entry_detail_record_i1_p13 on pspadm.psp_entry_detail_record_p13 USING BTREE (trace_number ASC);
create index psp_entry_detail_record_i1_p14 on pspadm.psp_entry_detail_record_p14 USING BTREE (trace_number ASC);
create index psp_entry_detail_record_i1_p15 on pspadm.psp_entry_detail_record_p15 USING BTREE (trace_number ASC);
create index psp_entry_detail_record_i1_p2 on pspadm.psp_entry_detail_record_p2 USING BTREE (trace_number ASC);
create index psp_entry_detail_record_i1_p3 on pspadm.psp_entry_detail_record_p3 USING BTREE (trace_number ASC);
create index psp_entry_detail_record_i1_p4 on pspadm.psp_entry_detail_record_p4 USING BTREE (trace_number ASC);
create index psp_entry_detail_record_i1_p5 on pspadm.psp_entry_detail_record_p5 USING BTREE (trace_number ASC);
create index psp_entry_detail_record_i1_p6 on pspadm.psp_entry_detail_record_p6 USING BTREE (trace_number ASC);
create index psp_entry_detail_record_i1_p7 on pspadm.psp_entry_detail_record_p7 USING BTREE (trace_number ASC);
create index psp_entry_detail_record_i1_p8 on pspadm.psp_entry_detail_record_p8 USING BTREE (trace_number ASC);
create index psp_entry_detail_record_i1_p9 on pspadm.psp_entry_detail_record_p9 USING BTREE (trace_number ASC);
create index psp_entry_detail_record_i2_p0 on pspadm.psp_entry_detail_record_p0 USING BTREE (initiation_date ASC,n_a_c_h_a_file_type ASC);
create index psp_entry_detail_record_i2_p1 on pspadm.psp_entry_detail_record_p1 USING BTREE (initiation_date ASC,n_a_c_h_a_file_type ASC);
create index psp_entry_detail_record_i2_p10 on pspadm.psp_entry_detail_record_p10 USING BTREE (initiation_date ASC,n_a_c_h_a_file_type ASC);
create index psp_entry_detail_record_i2_p11 on pspadm.psp_entry_detail_record_p11 USING BTREE (initiation_date ASC,n_a_c_h_a_file_type ASC);
create index psp_entry_detail_record_i2_p12 on pspadm.psp_entry_detail_record_p12 USING BTREE (initiation_date ASC,n_a_c_h_a_file_type ASC);
create index psp_entry_detail_record_i2_p13 on pspadm.psp_entry_detail_record_p13 USING BTREE (initiation_date ASC,n_a_c_h_a_file_type ASC);
create index psp_entry_detail_record_i2_p14 on pspadm.psp_entry_detail_record_p14 USING BTREE (initiation_date ASC,n_a_c_h_a_file_type ASC);
create index psp_entry_detail_record_i2_p15 on pspadm.psp_entry_detail_record_p15 USING BTREE (initiation_date ASC,n_a_c_h_a_file_type ASC);
create index psp_entry_detail_record_i2_p2 on pspadm.psp_entry_detail_record_p2 USING BTREE (initiation_date ASC,n_a_c_h_a_file_type ASC);
create index psp_entry_detail_record_i2_p3 on pspadm.psp_entry_detail_record_p3 USING BTREE (initiation_date ASC,n_a_c_h_a_file_type ASC);
create index psp_entry_detail_record_i2_p4 on pspadm.psp_entry_detail_record_p4 USING BTREE (initiation_date ASC,n_a_c_h_a_file_type ASC);
create index psp_entry_detail_record_i2_p5 on pspadm.psp_entry_detail_record_p5 USING BTREE (initiation_date ASC,n_a_c_h_a_file_type ASC);
create index psp_entry_detail_record_i2_p6 on pspadm.psp_entry_detail_record_p6 USING BTREE (initiation_date ASC,n_a_c_h_a_file_type ASC);
create index psp_entry_detail_record_i2_p7 on pspadm.psp_entry_detail_record_p7 USING BTREE (initiation_date ASC,n_a_c_h_a_file_type ASC);
create index psp_entry_detail_record_i2_p8 on pspadm.psp_entry_detail_record_p8 USING BTREE (initiation_date ASC,n_a_c_h_a_file_type ASC);
create index psp_entry_detail_record_i2_p9 on pspadm.psp_entry_detail_record_p9 USING BTREE (initiation_date ASC,n_a_c_h_a_file_type ASC);
select  'psp_entry_detail_record completed' as status;
SELECT CURRENT_TIMESTAMP;

