\timing
set search_path=pspadm;
SELECT CURRENT_TIMESTAMP;
select 'creating index on on psp_tax' as status;
create index psp_tax_fk1_p0 on pspadm.psp_tax_p0 USING BTREE (law_fk ASC);
create index psp_tax_fk1_p1 on pspadm.psp_tax_p1 USING BTREE (law_fk ASC);
create index psp_tax_fk1_p10 on pspadm.psp_tax_p10 USING BTREE (law_fk ASC);
create index psp_tax_fk1_p11 on pspadm.psp_tax_p11 USING BTREE (law_fk ASC);
create index psp_tax_fk1_p12 on pspadm.psp_tax_p12 USING BTREE (law_fk ASC);
create index psp_tax_fk1_p13 on pspadm.psp_tax_p13 USING BTREE (law_fk ASC);
create index psp_tax_fk1_p14 on pspadm.psp_tax_p14 USING BTREE (law_fk ASC);
create index psp_tax_fk1_p15 on pspadm.psp_tax_p15 USING BTREE (law_fk ASC);
create index psp_tax_fk1_p2 on pspadm.psp_tax_p2 USING BTREE (law_fk ASC);
create index psp_tax_fk1_p3 on pspadm.psp_tax_p3 USING BTREE (law_fk ASC);
create index psp_tax_fk1_p4 on pspadm.psp_tax_p4 USING BTREE (law_fk ASC);
create index psp_tax_fk1_p5 on pspadm.psp_tax_p5 USING BTREE (law_fk ASC);
create index psp_tax_fk1_p6 on pspadm.psp_tax_p6 USING BTREE (law_fk ASC);
create index psp_tax_fk1_p7 on pspadm.psp_tax_p7 USING BTREE (law_fk ASC);
create index psp_tax_fk1_p8 on pspadm.psp_tax_p8 USING BTREE (law_fk ASC);
create index psp_tax_fk1_p9 on pspadm.psp_tax_p9 USING BTREE (law_fk ASC);
create index psp_tax_fk2_p0 on pspadm.psp_tax_p0 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_tax_fk2_p1 on pspadm.psp_tax_p1 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_tax_fk2_p10 on pspadm.psp_tax_p10 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_tax_fk2_p11 on pspadm.psp_tax_p11 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_tax_fk2_p12 on pspadm.psp_tax_p12 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_tax_fk2_p13 on pspadm.psp_tax_p13 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_tax_fk2_p14 on pspadm.psp_tax_p14 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_tax_fk2_p15 on pspadm.psp_tax_p15 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_tax_fk2_p2 on pspadm.psp_tax_p2 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_tax_fk2_p3 on pspadm.psp_tax_p3 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_tax_fk2_p4 on pspadm.psp_tax_p4 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_tax_fk2_p5 on pspadm.psp_tax_p5 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_tax_fk2_p6 on pspadm.psp_tax_p6 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_tax_fk2_p7 on pspadm.psp_tax_p7 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_tax_fk2_p8 on pspadm.psp_tax_p8 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_tax_fk2_p9 on pspadm.psp_tax_p9 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_tax_fk3_p0 on pspadm.psp_tax_p0 USING BTREE (company_law_fk ASC);
create index psp_tax_fk3_p1 on pspadm.psp_tax_p1 USING BTREE (company_law_fk ASC);
create index psp_tax_fk3_p10 on pspadm.psp_tax_p10 USING BTREE (company_law_fk ASC);
create index psp_tax_fk3_p11 on pspadm.psp_tax_p11 USING BTREE (company_law_fk ASC);
create index psp_tax_fk3_p12 on pspadm.psp_tax_p12 USING BTREE (company_law_fk ASC);
create index psp_tax_fk3_p13 on pspadm.psp_tax_p13 USING BTREE (company_law_fk ASC);
create index psp_tax_fk3_p14 on pspadm.psp_tax_p14 USING BTREE (company_law_fk ASC);
create index psp_tax_fk3_p15 on pspadm.psp_tax_p15 USING BTREE (company_law_fk ASC);
create index psp_tax_fk3_p2 on pspadm.psp_tax_p2 USING BTREE (company_law_fk ASC);
create index psp_tax_fk3_p3 on pspadm.psp_tax_p3 USING BTREE (company_law_fk ASC);
create index psp_tax_fk3_p4 on pspadm.psp_tax_p4 USING BTREE (company_law_fk ASC);
create index psp_tax_fk3_p5 on pspadm.psp_tax_p5 USING BTREE (company_law_fk ASC);
create index psp_tax_fk3_p6 on pspadm.psp_tax_p6 USING BTREE (company_law_fk ASC);
create index psp_tax_fk3_p7 on pspadm.psp_tax_p7 USING BTREE (company_law_fk ASC);
create index psp_tax_fk3_p8 on pspadm.psp_tax_p8 USING BTREE (company_law_fk ASC);
create index psp_tax_fk3_p9 on pspadm.psp_tax_p9 USING BTREE (company_law_fk ASC);
create index psp_tax_fk5_p0 on pspadm.psp_tax_p0 USING BTREE (company_fk ASC);
create index psp_tax_fk5_p1 on pspadm.psp_tax_p1 USING BTREE (company_fk ASC);
create index psp_tax_fk5_p10 on pspadm.psp_tax_p10 USING BTREE (company_fk ASC);
create index psp_tax_fk5_p11 on pspadm.psp_tax_p11 USING BTREE (company_fk ASC);
create index psp_tax_fk5_p12 on pspadm.psp_tax_p12 USING BTREE (company_fk ASC);
create index psp_tax_fk5_p13 on pspadm.psp_tax_p13 USING BTREE (company_fk ASC);
create index psp_tax_fk5_p14 on pspadm.psp_tax_p14 USING BTREE (company_fk ASC);
create index psp_tax_fk5_p15 on pspadm.psp_tax_p15 USING BTREE (company_fk ASC);
create index psp_tax_fk5_p2 on pspadm.psp_tax_p2 USING BTREE (company_fk ASC);
create index psp_tax_fk5_p3 on pspadm.psp_tax_p3 USING BTREE (company_fk ASC);
create index psp_tax_fk5_p4 on pspadm.psp_tax_p4 USING BTREE (company_fk ASC);
create index psp_tax_fk5_p5 on pspadm.psp_tax_p5 USING BTREE (company_fk ASC);
create index psp_tax_fk5_p6 on pspadm.psp_tax_p6 USING BTREE (company_fk ASC);
create index psp_tax_fk5_p7 on pspadm.psp_tax_p7 USING BTREE (company_fk ASC);
create index psp_tax_fk5_p8 on pspadm.psp_tax_p8 USING BTREE (company_fk ASC);
create index psp_tax_fk5_p9 on pspadm.psp_tax_p9 USING BTREE (company_fk ASC)	;
select  'psp_tax completed' as status;
SELECT CURRENT_TIMESTAMP;
