\timing
set search_path=pspadm;
SELECT CURRENT_TIMESTAMP;


select 'creating index on psp_qbdt_transaction_info' as status;
create index psp_qbdt_transaction_info_fk1_p0 on pspadm.psp_qbdt_transaction_info_p0 USING BTREE (liability_check_fk ASC);
create index psp_qbdt_transaction_info_fk1_p1 on pspadm.psp_qbdt_transaction_info_p1 USING BTREE (liability_check_fk ASC);
create index psp_qbdt_transaction_info_fk1_p2 on pspadm.psp_qbdt_transaction_info_p2 USING BTREE (liability_check_fk ASC);
create index psp_qbdt_transaction_info_fk1_p3 on pspadm.psp_qbdt_transaction_info_p3 USING BTREE (liability_check_fk ASC);
create index psp_qbdt_transaction_info_fk2_p0 on pspadm.psp_qbdt_transaction_info_p0 USING BTREE (liability_check_line_fk ASC);
create index psp_qbdt_transaction_info_fk2_p1 on pspadm.psp_qbdt_transaction_info_p1 USING BTREE (liability_check_line_fk ASC);
create index psp_qbdt_transaction_info_fk2_p2 on pspadm.psp_qbdt_transaction_info_p2 USING BTREE (liability_check_line_fk ASC);
create index psp_qbdt_transaction_info_fk2_p3 on pspadm.psp_qbdt_transaction_info_p3 USING BTREE (liability_check_line_fk ASC);
create index psp_qbdt_transaction_info_fk3_p0 on pspadm.psp_qbdt_transaction_info_p0 USING BTREE (company_fk ASC,money_movement_transaction_fk ASC);
create index psp_qbdt_transaction_info_fk3_p1 on pspadm.psp_qbdt_transaction_info_p1 USING BTREE (company_fk ASC,money_movement_transaction_fk ASC);
create index psp_qbdt_transaction_info_fk3_p2 on pspadm.psp_qbdt_transaction_info_p2 USING BTREE (company_fk ASC,money_movement_transaction_fk ASC);
create index psp_qbdt_transaction_info_fk3_p3 on pspadm.psp_qbdt_transaction_info_p3 USING BTREE (company_fk ASC,money_movement_transaction_fk ASC);
create index psp_qbdt_transaction_info_fk4_p0 on pspadm.psp_qbdt_transaction_info_p0 USING BTREE (company_fk ASC,financial_transaction_fk ASC);
create index psp_qbdt_transaction_info_fk4_p1 on pspadm.psp_qbdt_transaction_info_p1 USING BTREE (company_fk ASC,financial_transaction_fk ASC);
create index psp_qbdt_transaction_info_fk4_p2 on pspadm.psp_qbdt_transaction_info_p2 USING BTREE (company_fk ASC,financial_transaction_fk ASC);
create index psp_qbdt_transaction_info_fk4_p3 on pspadm.psp_qbdt_transaction_info_p3 USING BTREE (company_fk ASC,financial_transaction_fk ASC);
create index psp_qbdt_transaction_info_fk5_p0 on pspadm.psp_qbdt_transaction_info_p0 USING BTREE (comp_adjust_submission_fk ASC);
create index psp_qbdt_transaction_info_fk5_p1 on pspadm.psp_qbdt_transaction_info_p1 USING BTREE (comp_adjust_submission_fk ASC);
create index psp_qbdt_transaction_info_fk5_p2 on pspadm.psp_qbdt_transaction_info_p2 USING BTREE (comp_adjust_submission_fk ASC);
create index psp_qbdt_transaction_info_fk5_p3 on pspadm.psp_qbdt_transaction_info_p3 USING BTREE (comp_adjust_submission_fk ASC);
create index psp_qbdt_transaction_info_fk6_p0 on pspadm.psp_qbdt_transaction_info_p0 USING BTREE (liability_adjustment_fk ASC);
create index psp_qbdt_transaction_info_fk6_p1 on pspadm.psp_qbdt_transaction_info_p1 USING BTREE (liability_adjustment_fk ASC);
create index psp_qbdt_transaction_info_fk6_p2 on pspadm.psp_qbdt_transaction_info_p2 USING BTREE (liability_adjustment_fk ASC);
create index psp_qbdt_transaction_info_fk6_p3 on pspadm.psp_qbdt_transaction_info_p3 USING BTREE (liability_adjustment_fk ASC);
create index psp_qbdt_transaction_info_fk7_p0 on pspadm.psp_qbdt_transaction_info_p0 USING BTREE (company_fk ASC);
create index psp_qbdt_transaction_info_fk7_p1 on pspadm.psp_qbdt_transaction_info_p1 USING BTREE (company_fk ASC);
create index psp_qbdt_transaction_info_fk7_p2 on pspadm.psp_qbdt_transaction_info_p2 USING BTREE (company_fk ASC);
create index psp_qbdt_transaction_info_fk7_p3 on pspadm.psp_qbdt_transaction_info_p3 USING BTREE (company_fk ASC);
create index psp_qbdt_transaction_info_fk8_p0 on pspadm.psp_qbdt_transaction_info_p0 USING BTREE (qbdt_payroll_transaction_fk ASC);
create index psp_qbdt_transaction_info_fk8_p1 on pspadm.psp_qbdt_transaction_info_p1 USING BTREE (qbdt_payroll_transaction_fk ASC);
create index psp_qbdt_transaction_info_fk8_p2 on pspadm.psp_qbdt_transaction_info_p2 USING BTREE (qbdt_payroll_transaction_fk ASC);
create index psp_qbdt_transaction_info_fk8_p3 on pspadm.psp_qbdt_transaction_info_p3 USING BTREE (qbdt_payroll_transaction_fk ASC);
create index psp_qbdt_transaction_info_fk9_p0 on pspadm.psp_qbdt_transaction_info_p0 USING BTREE (qbdt_payroll_trans_line_fk ASC);
create index psp_qbdt_transaction_info_fk9_p1 on pspadm.psp_qbdt_transaction_info_p1 USING BTREE (qbdt_payroll_trans_line_fk ASC);
create index psp_qbdt_transaction_info_fk9_p2 on pspadm.psp_qbdt_transaction_info_p2 USING BTREE (qbdt_payroll_trans_line_fk ASC);
create index psp_qbdt_transaction_info_fk9_p3 on pspadm.psp_qbdt_transaction_info_p3 USING BTREE (qbdt_payroll_trans_line_fk ASC);
create index psp_qbdttransactioninfo_fk1_p0 on pspadm.psp_qbdt_transaction_info_p0 USING BTREE (prior_payment_submission_fk ASC);
create index psp_qbdttransactioninfo_fk1_p1 on pspadm.psp_qbdt_transaction_info_p1 USING BTREE (prior_payment_submission_fk ASC);
create index psp_qbdttransactioninfo_fk1_p2 on pspadm.psp_qbdt_transaction_info_p2 USING BTREE (prior_payment_submission_fk ASC);
create index psp_qbdttransactioninfo_fk1_p3 on pspadm.psp_qbdt_transaction_info_p3 USING BTREE (prior_payment_submission_fk ASC);
select  'psp_qbdt_transaction_info completed' as status;
SELECT CURRENT_TIMESTAMP;

select 'creating index on psp_paystub' as status;
create index psp_paystub_fk1_p0 on pspadm.psp_paystub_p0 USING BTREE (pstub_employer_info_fk ASC);
create index psp_paystub_fk1_p1 on pspadm.psp_paystub_p1 USING BTREE (pstub_employer_info_fk ASC);
create index psp_paystub_fk1_p2 on pspadm.psp_paystub_p2 USING BTREE (pstub_employer_info_fk ASC);
create index psp_paystub_fk1_p3 on pspadm.psp_paystub_p3 USING BTREE (pstub_employer_info_fk ASC);
create index psp_paystub_fk2_p0 on pspadm.psp_paystub_p0 USING BTREE (company_fk ASC,pstub_employee_info_fk ASC);
create index psp_paystub_fk2_p1 on pspadm.psp_paystub_p1 USING BTREE (company_fk ASC,pstub_employee_info_fk ASC);
create index psp_paystub_fk2_p2 on pspadm.psp_paystub_p2 USING BTREE (company_fk ASC,pstub_employee_info_fk ASC);
create index psp_paystub_fk2_p3 on pspadm.psp_paystub_p3 USING BTREE (company_fk ASC,pstub_employee_info_fk ASC);
create index psp_paystub_fk3_p0 on pspadm.psp_paystub_p0 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_paystub_fk3_p1 on pspadm.psp_paystub_p1 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_paystub_fk3_p2 on pspadm.psp_paystub_p2 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_paystub_fk3_p3 on pspadm.psp_paystub_p3 USING BTREE (company_fk ASC,paycheck_fk ASC);
select  'psp_paystub completed' as status;
SELECT CURRENT_TIMESTAMP;

select 'creating index on psp_deduction' as status;
create index psp_deduction_fk1_p0 on pspadm.psp_deduction_p0 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_deduction_fk1_p1 on pspadm.psp_deduction_p1 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_deduction_fk1_p2 on pspadm.psp_deduction_p2 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_deduction_fk1_p3 on pspadm.psp_deduction_p3 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_deduction_fk2_p0 on pspadm.psp_deduction_p0 USING BTREE (company_payroll_item_fk ASC);
create index psp_deduction_fk2_p1 on pspadm.psp_deduction_p1 USING BTREE (company_payroll_item_fk ASC);
create index psp_deduction_fk2_p2 on pspadm.psp_deduction_p2 USING BTREE (company_payroll_item_fk ASC);
create index psp_deduction_fk2_p3 on pspadm.psp_deduction_p3 USING BTREE (company_payroll_item_fk ASC);
create index psp_deduction_fk4_p0 on pspadm.psp_deduction_p0 USING BTREE (company_fk ASC);
create index psp_deduction_fk4_p1 on pspadm.psp_deduction_p1 USING BTREE (company_fk ASC);
create index psp_deduction_fk4_p2 on pspadm.psp_deduction_p2 USING BTREE (company_fk ASC);
create index psp_deduction_fk4_p3 on pspadm.psp_deduction_p3 USING BTREE (company_fk ASC);
select  'psp_deduction completed' as status;
SELECT CURRENT_TIMESTAMP;

select 'creating index on psp_pstub_paid_timeoff_item';
create index psp_pstub_paid_timeoff_ite_fk1_p0 on pspadm.psp_pstub_paid_timeoff_item_p0 USING BTREE (company_fk ASC,paystub_fk ASC);
create index psp_pstub_paid_timeoff_ite_fk1_p1 on pspadm.psp_pstub_paid_timeoff_item_p1 USING BTREE (company_fk ASC,paystub_fk ASC);
create index psp_pstub_paid_timeoff_ite_fk1_p2 on pspadm.psp_pstub_paid_timeoff_item_p2 USING BTREE (company_fk ASC,paystub_fk ASC);
create index psp_pstub_paid_timeoff_ite_fk1_p3 on pspadm.psp_pstub_paid_timeoff_item_p3 USING BTREE (company_fk ASC,paystub_fk ASC);
select  'sp_pstub_paid_timeoff_item completed' as status;
SELECT CURRENT_TIMESTAMP;

select 'creating index on psp_pstub_employee_info' as status;
create index psp_pstub_employee_info_fk1_p0 on pspadm.psp_pstub_employee_info_p0 USING BTREE (employee_fk ASC);
create index psp_pstub_employee_info_fk1_p1 on pspadm.psp_pstub_employee_info_p1 USING BTREE (employee_fk ASC);
create index psp_pstub_employee_info_fk1_p2 on pspadm.psp_pstub_employee_info_p2 USING BTREE (employee_fk ASC);
create index psp_pstub_employee_info_fk1_p3 on pspadm.psp_pstub_employee_info_p3 USING BTREE (employee_fk ASC);
create index psp_pstub_employee_info_fk2_p0 on pspadm.psp_pstub_employee_info_p0 USING BTREE (pstub_address_fk ASC);
create index psp_pstub_employee_info_fk2_p1 on pspadm.psp_pstub_employee_info_p1 USING BTREE (pstub_address_fk ASC);
create index psp_pstub_employee_info_fk2_p2 on pspadm.psp_pstub_employee_info_p2 USING BTREE (pstub_address_fk ASC);
create index psp_pstub_employee_info_fk2_p3 on pspadm.psp_pstub_employee_info_p3 USING BTREE (pstub_address_fk ASC);
select  'psp_pstub_employee_info completed' as status;
SELECT CURRENT_TIMESTAMP;

