\timing
set search_path=pspadm;
SELECT CURRENT_TIMESTAMP;

select 'creating index on psp_compensation' as status;
create index psp_compensation_fk1_p0 on pspadm.psp_compensation_p0 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_compensation_fk1_p1 on pspadm.psp_compensation_p1 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_compensation_fk1_p2 on pspadm.psp_compensation_p2 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_compensation_fk1_p3 on pspadm.psp_compensation_p3 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_compensation_fk1_p4 on pspadm.psp_compensation_p4 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_compensation_fk1_p5 on pspadm.psp_compensation_p5 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_compensation_fk1_p6 on pspadm.psp_compensation_p6 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_compensation_fk1_p7 on pspadm.psp_compensation_p7 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_compensation_fk2_p0 on pspadm.psp_compensation_p0 USING BTREE (company_payroll_item_fk ASC);
create index psp_compensation_fk2_p1 on pspadm.psp_compensation_p1 USING BTREE (company_payroll_item_fk ASC);
create index psp_compensation_fk2_p2 on pspadm.psp_compensation_p2 USING BTREE (company_payroll_item_fk ASC);
create index psp_compensation_fk2_p3 on pspadm.psp_compensation_p3 USING BTREE (company_payroll_item_fk ASC);
create index psp_compensation_fk2_p4 on pspadm.psp_compensation_p4 USING BTREE (company_payroll_item_fk ASC);
create index psp_compensation_fk2_p5 on pspadm.psp_compensation_p5 USING BTREE (company_payroll_item_fk ASC);
create index psp_compensation_fk2_p6 on pspadm.psp_compensation_p6 USING BTREE (company_payroll_item_fk ASC);
create index psp_compensation_fk2_p7 on pspadm.psp_compensation_p7 USING BTREE (company_payroll_item_fk ASC);
create index psp_compensation_fk4_p0 on pspadm.psp_compensation_p0 USING BTREE (company_fk ASC);
create index psp_compensation_fk4_p1 on pspadm.psp_compensation_p1 USING BTREE (company_fk ASC);
create index psp_compensation_fk4_p2 on pspadm.psp_compensation_p2 USING BTREE (company_fk ASC);
create index psp_compensation_fk4_p3 on pspadm.psp_compensation_p3 USING BTREE (company_fk ASC);
create index psp_compensation_fk4_p4 on pspadm.psp_compensation_p4 USING BTREE (company_fk ASC);
create index psp_compensation_fk4_p5 on pspadm.psp_compensation_p5 USING BTREE (company_fk ASC);
create index psp_compensation_fk4_p6 on pspadm.psp_compensation_p6 USING BTREE (company_fk ASC);
create index psp_compensation_fk4_p7 on pspadm.psp_compensation_p7 USING BTREE (company_fk ASC);
select  'psp_compensation completed' as status;
SELECT CURRENT_TIMESTAMP;

select 'creating index on psp_ledger_balance' as status;
create index psp_ledger_balance_i1_p0 on pspadm.psp_ledger_balance_p0 USING BTREE (balance_date ASC) ;
create index psp_ledger_balance_i1_p1 on pspadm.psp_ledger_balance_p1 USING BTREE (balance_date ASC) ;
create index psp_ledger_balance_i1_p2 on pspadm.psp_ledger_balance_p2 USING BTREE (balance_date ASC) ;
create index psp_ledger_balance_i1_p3 on pspadm.psp_ledger_balance_p3 USING BTREE (balance_date ASC) ;
create index psp_ledger_balance_i1_p4 on pspadm.psp_ledger_balance_p4 USING BTREE (balance_date ASC) ;
create index psp_ledger_balance_i1_p5 on pspadm.psp_ledger_balance_p5 USING BTREE (balance_date ASC) ;
create index psp_ledger_balance_i1_p6 on pspadm.psp_ledger_balance_p6 USING BTREE (balance_date ASC) ;
create index psp_ledger_balance_i1_p7 on pspadm.psp_ledger_balance_p7 USING BTREE (balance_date ASC) ;
create index psp_ledger_balance_u1_p0 on pspadm.psp_ledger_balance_p0 USING BTREE (date(balance_date) ASC) ;
create index psp_ledger_balance_u1_p1 on pspadm.psp_ledger_balance_p1 USING BTREE (date(balance_date) ASC) ;
create index psp_ledger_balance_u1_p2 on pspadm.psp_ledger_balance_p2 USING BTREE (date(balance_date) ASC) ;
create index psp_ledger_balance_u1_p3 on pspadm.psp_ledger_balance_p3 USING BTREE (date(balance_date) ASC) ;
create index psp_ledger_balance_u1_p4 on pspadm.psp_ledger_balance_p4 USING BTREE (date(balance_date) ASC) ;
create index psp_ledger_balance_u1_p5 on pspadm.psp_ledger_balance_p5 USING BTREE (date(balance_date) ASC) ;
create index psp_ledger_balance_u1_p6 on pspadm.psp_ledger_balance_p6 USING BTREE (date(balance_date) ASC) ;
create index psp_ledger_balance_u1_p7 on pspadm.psp_ledger_balance_p7 USING BTREE (date(balance_date) ASC) ;
create index psp_ledger_balance_u2_p0 on pspadm.psp_ledger_balance_p0 USING BTREE (company_fk ASC, ledger_account_fk ASC, date(balance_date) ASC) ;
create index psp_ledger_balance_u2_p1 on pspadm.psp_ledger_balance_p1 USING BTREE (company_fk ASC, ledger_account_fk ASC, date(balance_date) ASC) ;
create index psp_ledger_balance_u2_p2 on pspadm.psp_ledger_balance_p2 USING BTREE (company_fk ASC, ledger_account_fk ASC, date(balance_date) ASC) ;
create index psp_ledger_balance_u2_p3 on pspadm.psp_ledger_balance_p3 USING BTREE (company_fk ASC, ledger_account_fk ASC, date(balance_date) ASC) ;
create index psp_ledger_balance_u2_p4 on pspadm.psp_ledger_balance_p4 USING BTREE (company_fk ASC, ledger_account_fk ASC, date(balance_date) ASC) ;
create index psp_ledger_balance_u2_p5 on pspadm.psp_ledger_balance_p5 USING BTREE (company_fk ASC, ledger_account_fk ASC, date(balance_date) ASC) ;
create index psp_ledger_balance_u2_p6 on pspadm.psp_ledger_balance_p6 USING BTREE (company_fk ASC, ledger_account_fk ASC, date(balance_date) ASC) ;
create index psp_ledger_balance_u2_p7 on pspadm.psp_ledger_balance_p7 USING BTREE (company_fk ASC, ledger_account_fk ASC, date(balance_date) ASC) ;
create index psp_ledgerbalance_fk1_p0 on pspadm.psp_ledger_balance_p0 USING BTREE (ledger_account_fk) ;
create index psp_ledgerbalance_fk1_p1 on pspadm.psp_ledger_balance_p1 USING BTREE (ledger_account_fk) ;
create index psp_ledgerbalance_fk1_p2 on pspadm.psp_ledger_balance_p2 USING BTREE (ledger_account_fk) ;
create index psp_ledgerbalance_fk1_p3 on pspadm.psp_ledger_balance_p3 USING BTREE (ledger_account_fk) ;
create index psp_ledgerbalance_fk1_p4 on pspadm.psp_ledger_balance_p4 USING BTREE (ledger_account_fk) ;
create index psp_ledgerbalance_fk1_p5 on pspadm.psp_ledger_balance_p5 USING BTREE (ledger_account_fk) ;
create index psp_ledgerbalance_fk1_p6 on pspadm.psp_ledger_balance_p6 USING BTREE (ledger_account_fk) ;
create index psp_ledgerbalance_fk1_p7 on pspadm.psp_ledger_balance_p7 USING BTREE (ledger_account_fk) ;
create index psp_ledgerbalance_fk2_p0 on pspadm.psp_ledger_balance_p0 USING BTREE (company_fk ASC) ;
create index psp_ledgerbalance_fk2_p1 on pspadm.psp_ledger_balance_p1 USING BTREE (company_fk ASC) ;
create index psp_ledgerbalance_fk2_p2 on pspadm.psp_ledger_balance_p2 USING BTREE (company_fk ASC) ;
create index psp_ledgerbalance_fk2_p3 on pspadm.psp_ledger_balance_p3 USING BTREE (company_fk ASC) ;
create index psp_ledgerbalance_fk2_p4 on pspadm.psp_ledger_balance_p4 USING BTREE (company_fk ASC) ;
create index psp_ledgerbalance_fk2_p5 on pspadm.psp_ledger_balance_p5 USING BTREE (company_fk ASC) ;
create index psp_ledgerbalance_fk2_p6 on pspadm.psp_ledger_balance_p6 USING BTREE (company_fk ASC) ;
create index psp_ledgerbalance_fk2_p7 on pspadm.psp_ledger_balance_p7 USING BTREE (company_fk ASC) ;
select  'psp_ledger_balance completed' as status;
SELECT CURRENT_TIMESTAMP;
