\timing
set search_path=pspadm;
SELECT CURRENT_TIMESTAMP;

select 'creating index on psp_money_movement_transaction' as status;
create index psp_mm_transaction_i10_p0 on pspadm.psp_money_movement_transaction_p0 USING BTREE (payment_template_fk ASC,tax_payment_status ASC,payment_period_end ASC) ;
create index psp_mm_transaction_i10_p1 on pspadm.psp_money_movement_transaction_p1 USING BTREE (payment_template_fk ASC,tax_payment_status ASC,payment_period_end ASC) ;
create index psp_mm_transaction_i10_p2 on pspadm.psp_money_movement_transaction_p2 USING BTREE (payment_template_fk ASC,tax_payment_status ASC,payment_period_end ASC) ;
create index psp_mm_transaction_i10_p3 on pspadm.psp_money_movement_transaction_p3 USING BTREE (payment_template_fk ASC,tax_payment_status ASC,payment_period_end ASC) ;
create index psp_mm_transaction_i10_p4 on pspadm.psp_money_movement_transaction_p4 USING BTREE (payment_template_fk ASC,tax_payment_status ASC,payment_period_end ASC) ;
create index psp_mm_transaction_i10_p5 on pspadm.psp_money_movement_transaction_p5 USING BTREE (payment_template_fk ASC,tax_payment_status ASC,payment_period_end ASC) ;
create index psp_mm_transaction_i10_p6 on pspadm.psp_money_movement_transaction_p6 USING BTREE (payment_template_fk ASC,tax_payment_status ASC,payment_period_end ASC) ;
create index psp_mm_transaction_i10_p7 on pspadm.psp_money_movement_transaction_p7 USING BTREE (payment_template_fk ASC,tax_payment_status ASC,payment_period_end ASC) ;
create index psp_mm_transaction_i1_p0 on pspadm.psp_money_movement_transaction_p0 USING BTREE (company_fk ASC,status ASC,initiation_date ASC,due_date ASC,money_movement_payment_method ASC) ;
create index psp_mm_transaction_i1_p1 on pspadm.psp_money_movement_transaction_p1 USING BTREE (company_fk ASC,status ASC,initiation_date ASC,due_date ASC,money_movement_payment_method ASC) ;
create index psp_mm_transaction_i1_p2 on pspadm.psp_money_movement_transaction_p2 USING BTREE (company_fk ASC,status ASC,initiation_date ASC,due_date ASC,money_movement_payment_method ASC) ;
create index psp_mm_transaction_i1_p3 on pspadm.psp_money_movement_transaction_p3 USING BTREE (company_fk ASC,status ASC,initiation_date ASC,due_date ASC,money_movement_payment_method ASC) ;
create index psp_mm_transaction_i1_p4 on pspadm.psp_money_movement_transaction_p4 USING BTREE (company_fk ASC,status ASC,initiation_date ASC,due_date ASC,money_movement_payment_method ASC) ;
create index psp_mm_transaction_i1_p5 on pspadm.psp_money_movement_transaction_p5 USING BTREE (company_fk ASC,status ASC,initiation_date ASC,due_date ASC,money_movement_payment_method ASC) ;
create index psp_mm_transaction_i1_p6 on pspadm.psp_money_movement_transaction_p6 USING BTREE (company_fk ASC,status ASC,initiation_date ASC,due_date ASC,money_movement_payment_method ASC) ;
create index psp_mm_transaction_i1_p7 on pspadm.psp_money_movement_transaction_p7 USING BTREE (company_fk ASC,status ASC,initiation_date ASC,due_date ASC,money_movement_payment_method ASC) ;
create index psp_mm_transaction_i2_p0 on pspadm.psp_money_movement_transaction_p0 USING BTREE (initiation_date ASC,money_movement_payment_method ASC) ;
create index psp_mm_transaction_i2_p1 on pspadm.psp_money_movement_transaction_p1 USING BTREE (initiation_date ASC,money_movement_payment_method ASC) ;
create index psp_mm_transaction_i2_p2 on pspadm.psp_money_movement_transaction_p2 USING BTREE (initiation_date ASC,money_movement_payment_method ASC) ;
create index psp_mm_transaction_i2_p3 on pspadm.psp_money_movement_transaction_p3 USING BTREE (initiation_date ASC,money_movement_payment_method ASC) ;
create index psp_mm_transaction_i2_p4 on pspadm.psp_money_movement_transaction_p4 USING BTREE (initiation_date ASC,money_movement_payment_method ASC) ;
create index psp_mm_transaction_i2_p5 on pspadm.psp_money_movement_transaction_p5 USING BTREE (initiation_date ASC,money_movement_payment_method ASC) ;
create index psp_mm_transaction_i2_p6 on pspadm.psp_money_movement_transaction_p6 USING BTREE (initiation_date ASC,money_movement_payment_method ASC) ;
create index psp_mm_transaction_i2_p7 on pspadm.psp_money_movement_transaction_p7 USING BTREE (initiation_date ASC,money_movement_payment_method ASC) ;
create index psp_mm_transaction_i3_p0 on pspadm.psp_money_movement_transaction_p0 USING BTREE (tax_payment_status ASC,company_fk ASC) ;
create index psp_mm_transaction_i3_p1 on pspadm.psp_money_movement_transaction_p1 USING BTREE (tax_payment_status ASC,company_fk ASC) ;
create index psp_mm_transaction_i3_p2 on pspadm.psp_money_movement_transaction_p2 USING BTREE (tax_payment_status ASC,company_fk ASC) ;
create index psp_mm_transaction_i3_p3 on pspadm.psp_money_movement_transaction_p3 USING BTREE (tax_payment_status ASC,company_fk ASC) ;
create index psp_mm_transaction_i3_p4 on pspadm.psp_money_movement_transaction_p4 USING BTREE (tax_payment_status ASC,company_fk ASC) ;
create index psp_mm_transaction_i3_p5 on pspadm.psp_money_movement_transaction_p5 USING BTREE (tax_payment_status ASC,company_fk ASC) ;
create index psp_mm_transaction_i3_p6 on pspadm.psp_money_movement_transaction_p6 USING BTREE (tax_payment_status ASC,company_fk ASC) ;
create index psp_mm_transaction_i3_p7 on pspadm.psp_money_movement_transaction_p7 USING BTREE (tax_payment_status ASC,company_fk ASC) ;
create index psp_mm_transaction_i4_p0 on pspadm.psp_money_movement_transaction_p0 USING BTREE (payment_template_fk ASC,company_fk ASC,status ASC) ;
create index psp_mm_transaction_i4_p1 on pspadm.psp_money_movement_transaction_p1 USING BTREE (payment_template_fk ASC,company_fk ASC,status ASC) ;
create index psp_mm_transaction_i4_p2 on pspadm.psp_money_movement_transaction_p2 USING BTREE (payment_template_fk ASC,company_fk ASC,status ASC) ;
create index psp_mm_transaction_i4_p3 on pspadm.psp_money_movement_transaction_p3 USING BTREE (payment_template_fk ASC,company_fk ASC,status ASC) ;
create index psp_mm_transaction_i4_p4 on pspadm.psp_money_movement_transaction_p4 USING BTREE (payment_template_fk ASC,company_fk ASC,status ASC) ;
create index psp_mm_transaction_i4_p5 on pspadm.psp_money_movement_transaction_p5 USING BTREE (payment_template_fk ASC,company_fk ASC,status ASC) ;
create index psp_mm_transaction_i4_p6 on pspadm.psp_money_movement_transaction_p6 USING BTREE (payment_template_fk ASC,company_fk ASC,status ASC) ;
create index psp_mm_transaction_i4_p7 on pspadm.psp_money_movement_transaction_p7 USING BTREE (payment_template_fk ASC,company_fk ASC,status ASC) ;
create index psp_mm_transaction_i5_p0 on pspadm.psp_money_movement_transaction_p0 USING BTREE (tax_payment_status ASC,money_movement_payment_method ASC,payment_period_end ASC) ;
create index psp_mm_transaction_i5_p1 on pspadm.psp_money_movement_transaction_p1 USING BTREE (tax_payment_status ASC,money_movement_payment_method ASC,payment_period_end ASC) ;
create index psp_mm_transaction_i5_p2 on pspadm.psp_money_movement_transaction_p2 USING BTREE (tax_payment_status ASC,money_movement_payment_method ASC,payment_period_end ASC) ;
create index psp_mm_transaction_i5_p3 on pspadm.psp_money_movement_transaction_p3 USING BTREE (tax_payment_status ASC,money_movement_payment_method ASC,payment_period_end ASC) ;
create index psp_mm_transaction_i5_p4 on pspadm.psp_money_movement_transaction_p4 USING BTREE (tax_payment_status ASC,money_movement_payment_method ASC,payment_period_end ASC) ;
create index psp_mm_transaction_i5_p5 on pspadm.psp_money_movement_transaction_p5 USING BTREE (tax_payment_status ASC,money_movement_payment_method ASC,payment_period_end ASC) ;
create index psp_mm_transaction_i5_p6 on pspadm.psp_money_movement_transaction_p6 USING BTREE (tax_payment_status ASC,money_movement_payment_method ASC,payment_period_end ASC) ;
create index psp_mm_transaction_i5_p7 on pspadm.psp_money_movement_transaction_p7 USING BTREE (tax_payment_status ASC,money_movement_payment_method ASC,payment_period_end ASC) ;
create index psp_mm_transaction_i9_p0 on pspadm.psp_money_movement_transaction_p0 USING BTREE (tax_payment_status ASC,status ASC,payment_template_fk) ;
create index psp_mm_transaction_i9_p1 on pspadm.psp_money_movement_transaction_p1 USING BTREE (tax_payment_status ASC,status ASC,payment_template_fk) ;
create index psp_mm_transaction_i9_p2 on pspadm.psp_money_movement_transaction_p2 USING BTREE (tax_payment_status ASC,status ASC,payment_template_fk) ;
create index psp_mm_transaction_i9_p3 on pspadm.psp_money_movement_transaction_p3 USING BTREE (tax_payment_status ASC,status ASC,payment_template_fk) ;
create index psp_mm_transaction_i9_p4 on pspadm.psp_money_movement_transaction_p4 USING BTREE (tax_payment_status ASC,status ASC,payment_template_fk) ;
create index psp_mm_transaction_i9_p5 on pspadm.psp_money_movement_transaction_p5 USING BTREE (tax_payment_status ASC,status ASC,payment_template_fk) ;
create index psp_mm_transaction_i9_p6 on pspadm.psp_money_movement_transaction_p6 USING BTREE (tax_payment_status ASC,status ASC,payment_template_fk) ;
create index psp_mm_transaction_i9_p7 on pspadm.psp_money_movement_transaction_p7 USING BTREE (tax_payment_status ASC,status ASC,payment_template_fk) ;
create index psp_money_movement_transac_fk2_p0 on pspadm.psp_money_movement_transaction_p0 USING BTREE (company_fk ASC) ;
create index psp_money_movement_transac_fk2_p1 on pspadm.psp_money_movement_transaction_p1 USING BTREE (company_fk ASC) ;
create index psp_money_movement_transac_fk2_p2 on pspadm.psp_money_movement_transaction_p2 USING BTREE (company_fk ASC) ;
create index psp_money_movement_transac_fk2_p3 on pspadm.psp_money_movement_transaction_p3 USING BTREE (company_fk ASC) ;
create index psp_money_movement_transac_fk2_p4 on pspadm.psp_money_movement_transaction_p4 USING BTREE (company_fk ASC) ;
create index psp_money_movement_transac_fk2_p5 on pspadm.psp_money_movement_transaction_p5 USING BTREE (company_fk ASC) ;
create index psp_money_movement_transac_fk2_p6 on pspadm.psp_money_movement_transaction_p6 USING BTREE (company_fk ASC) ;
create index psp_money_movement_transac_fk2_p7 on pspadm.psp_money_movement_transaction_p7 USING BTREE (company_fk ASC) ;
create index psp_money_movement_transac_fk3_p0 on pspadm.psp_money_movement_transaction_p0 USING BTREE (offload_batch_fk ASC) ;
create index psp_money_movement_transac_fk3_p1 on pspadm.psp_money_movement_transaction_p1 USING BTREE (offload_batch_fk ASC) ;
create index psp_money_movement_transac_fk3_p2 on pspadm.psp_money_movement_transaction_p2 USING BTREE (offload_batch_fk ASC) ;
create index psp_money_movement_transac_fk3_p3 on pspadm.psp_money_movement_transaction_p3 USING BTREE (offload_batch_fk ASC) ;
create index psp_money_movement_transac_fk3_p4 on pspadm.psp_money_movement_transaction_p4 USING BTREE (offload_batch_fk ASC) ;
create index psp_money_movement_transac_fk3_p5 on pspadm.psp_money_movement_transaction_p5 USING BTREE (offload_batch_fk ASC) ;
create index psp_money_movement_transac_fk3_p6 on pspadm.psp_money_movement_transaction_p6 USING BTREE (offload_batch_fk ASC) ;
create index psp_money_movement_transac_fk3_p7 on pspadm.psp_money_movement_transaction_p7 USING BTREE (offload_batch_fk ASC) ;
create index psp_money_movement_transac_fk6_p0 on pspadm.psp_money_movement_transaction_p0 USING BTREE (payment_frequency_fk ASC) ;
create index psp_money_movement_transac_fk6_p1 on pspadm.psp_money_movement_transaction_p1 USING BTREE (payment_frequency_fk ASC) ;
create index psp_money_movement_transac_fk6_p2 on pspadm.psp_money_movement_transaction_p2 USING BTREE (payment_frequency_fk ASC) ;
create index psp_money_movement_transac_fk6_p3 on pspadm.psp_money_movement_transaction_p3 USING BTREE (payment_frequency_fk ASC) ;
create index psp_money_movement_transac_fk6_p4 on pspadm.psp_money_movement_transaction_p4 USING BTREE (payment_frequency_fk ASC) ;
create index psp_money_movement_transac_fk6_p5 on pspadm.psp_money_movement_transaction_p5 USING BTREE (payment_frequency_fk ASC) ;
create index psp_money_movement_transac_fk6_p6 on pspadm.psp_money_movement_transaction_p6 USING BTREE (payment_frequency_fk ASC) ;
create index psp_money_movement_transac_fk6_p7 on pspadm.psp_money_movement_transaction_p7 USING BTREE (payment_frequency_fk ASC) ;
create index psp_moneymovementtransacti_fk1_p0 on pspadm.psp_money_movement_transaction_p0 USING BTREE (company_fk ASC,original_transaction_fk ASC) ;
create index psp_moneymovementtransacti_fk1_p1 on pspadm.psp_money_movement_transaction_p1 USING BTREE (company_fk ASC,original_transaction_fk ASC) ;
create index psp_moneymovementtransacti_fk1_p2 on pspadm.psp_money_movement_transaction_p2 USING BTREE (company_fk ASC,original_transaction_fk ASC) ;
create index psp_moneymovementtransacti_fk1_p3 on pspadm.psp_money_movement_transaction_p3 USING BTREE (company_fk ASC,original_transaction_fk ASC) ;
create index psp_moneymovementtransacti_fk1_p4 on pspadm.psp_money_movement_transaction_p4 USING BTREE (company_fk ASC,original_transaction_fk ASC) ;
create index psp_moneymovementtransacti_fk1_p5 on pspadm.psp_money_movement_transaction_p5 USING BTREE (company_fk ASC,original_transaction_fk ASC) ;
create index psp_moneymovementtransacti_fk1_p6 on pspadm.psp_money_movement_transaction_p6 USING BTREE (company_fk ASC,original_transaction_fk ASC) ;
create index psp_moneymovementtransacti_fk1_p7 on pspadm.psp_money_movement_transaction_p7 USING BTREE (company_fk ASC,original_transaction_fk ASC) ;
select  'psp_money_movement_transaction completed' as status;
SELECT CURRENT_TIMESTAMP;
