\timing
set search_path=pspadm;
SELECT CURRENT_TIMESTAMP;

select 'creating index on psp_company_event' as status;
create index psp_company_event_fk1_p0 on pspadm.psp_company_event_p0 USING BTREE (company_fk ASC);
create index psp_company_event_fk1_p1 on pspadm.psp_company_event_p1 USING BTREE (company_fk ASC);
create index psp_company_event_fk1_p2 on pspadm.psp_company_event_p2 USING BTREE (company_fk ASC);
create index psp_company_event_fk1_p3 on pspadm.psp_company_event_p3 USING BTREE (company_fk ASC);
create index psp_company_event_fk1_p4 on pspadm.psp_company_event_p4 USING BTREE (company_fk ASC);
create index psp_company_event_fk1_p5 on pspadm.psp_company_event_p5 USING BTREE (company_fk ASC);
create index psp_company_event_fk1_p6 on pspadm.psp_company_event_p6 USING BTREE (company_fk ASC);
create index psp_company_event_fk1_p7 on pspadm.psp_company_event_p7 USING BTREE (company_fk ASC);
create index psp_company_event_i1_p0 on pspadm.psp_company_event_p0 USING BTREE (company_fk ASC,event_type_cd ASC);
create index psp_company_event_i1_p1 on pspadm.psp_company_event_p1 USING BTREE (company_fk ASC,event_type_cd ASC);
create index psp_company_event_i1_p2 on pspadm.psp_company_event_p2 USING BTREE (company_fk ASC,event_type_cd ASC);
create index psp_company_event_i1_p3 on pspadm.psp_company_event_p3 USING BTREE (company_fk ASC,event_type_cd ASC);
create index psp_company_event_i1_p4 on pspadm.psp_company_event_p4 USING BTREE (company_fk ASC,event_type_cd ASC);
create index psp_company_event_i1_p5 on pspadm.psp_company_event_p5 USING BTREE (company_fk ASC,event_type_cd ASC);
create index psp_company_event_i1_p6 on pspadm.psp_company_event_p6 USING BTREE (company_fk ASC,event_type_cd ASC);
create index psp_company_event_i1_p7 on pspadm.psp_company_event_p7 USING BTREE (company_fk ASC,event_type_cd ASC);
create index psp_company_event_i2_p0 on pspadm.psp_company_event_p0 USING BTREE (event_time_stamp ASC);
create index psp_company_event_i2_p1 on pspadm.psp_company_event_p1 USING BTREE (event_time_stamp ASC);
create index psp_company_event_i2_p2 on pspadm.psp_company_event_p2 USING BTREE (event_time_stamp ASC);
create index psp_company_event_i2_p3 on pspadm.psp_company_event_p3 USING BTREE (event_time_stamp ASC);
create index psp_company_event_i2_p4 on pspadm.psp_company_event_p4 USING BTREE (event_time_stamp ASC);
create index psp_company_event_i2_p5 on pspadm.psp_company_event_p5 USING BTREE (event_time_stamp ASC);
create index psp_company_event_i2_p6 on pspadm.psp_company_event_p6 USING BTREE (event_time_stamp ASC);
create index psp_company_event_i2_p7 on pspadm.psp_company_event_p7 USING BTREE (event_time_stamp ASC);
create index psp_company_event_i3_p0 on pspadm.psp_company_event_p0 USING BTREE (company_fk ASC,event_time_stamp ASC);
create index psp_company_event_i3_p1 on pspadm.psp_company_event_p1 USING BTREE (company_fk ASC,event_time_stamp ASC);
create index psp_company_event_i3_p2 on pspadm.psp_company_event_p2 USING BTREE (company_fk ASC,event_time_stamp ASC);
create index psp_company_event_i3_p3 on pspadm.psp_company_event_p3 USING BTREE (company_fk ASC,event_time_stamp ASC);
create index psp_company_event_i3_p4 on pspadm.psp_company_event_p4 USING BTREE (company_fk ASC,event_time_stamp ASC);
create index psp_company_event_i3_p5 on pspadm.psp_company_event_p5 USING BTREE (company_fk ASC,event_time_stamp ASC);
create index psp_company_event_i3_p6 on pspadm.psp_company_event_p6 USING BTREE (company_fk ASC,event_time_stamp ASC);
create index psp_company_event_i3_p7 on pspadm.psp_company_event_p7 USING BTREE (company_fk ASC,event_time_stamp ASC);
select  'psp_company_event completed' as status;
SELECT CURRENT_TIMESTAMP;

select 'creating index on psp_company_event_detail' as status;
create index psp_company_event_detail_fk1_p0 on pspadm.psp_company_event_detail_p0 USING BTREE (company_fk ASC,company_event_fk ASC);
create index psp_company_event_detail_fk1_p1 on pspadm.psp_company_event_detail_p1 USING BTREE (company_fk ASC,company_event_fk ASC);
create index psp_company_event_detail_fk1_p2 on pspadm.psp_company_event_detail_p2 USING BTREE (company_fk ASC,company_event_fk ASC);
create index psp_company_event_detail_fk1_p3 on pspadm.psp_company_event_detail_p3 USING BTREE (company_fk ASC,company_event_fk ASC);
create index psp_company_event_detail_fk1_p4 on pspadm.psp_company_event_detail_p4 USING BTREE (company_fk ASC,company_event_fk ASC);
create index psp_company_event_detail_fk1_p5 on pspadm.psp_company_event_detail_p5 USING BTREE (company_fk ASC,company_event_fk ASC);
create index psp_company_event_detail_fk1_p6 on pspadm.psp_company_event_detail_p6 USING BTREE (company_fk ASC,company_event_fk ASC);
create index psp_company_event_detail_fk1_p7 on pspadm.psp_company_event_detail_p7 USING BTREE (company_fk ASC,company_event_fk ASC);
create index psp_company_event_detail_fk2_p0 on pspadm.psp_company_event_detail_p0 USING BTREE (company_fk ASC);
create index psp_company_event_detail_fk2_p1 on pspadm.psp_company_event_detail_p1 USING BTREE (company_fk ASC);
create index psp_company_event_detail_fk2_p2 on pspadm.psp_company_event_detail_p2 USING BTREE (company_fk ASC);
create index psp_company_event_detail_fk2_p3 on pspadm.psp_company_event_detail_p3 USING BTREE (company_fk ASC);
create index psp_company_event_detail_fk2_p4 on pspadm.psp_company_event_detail_p4 USING BTREE (company_fk ASC);
create index psp_company_event_detail_fk2_p5 on pspadm.psp_company_event_detail_p5 USING BTREE (company_fk ASC);
create index psp_company_event_detail_fk2_p6 on pspadm.psp_company_event_detail_p6 USING BTREE (company_fk ASC);
create index psp_company_event_detail_fk2_p7 on pspadm.psp_company_event_detail_p7 USING BTREE (company_fk ASC);
create index psp_company_event_detail_i2_p0 on pspadm.psp_company_event_detail_p0 USING BTREE (event_detail_type_cd ASC,company_fk ASC);
create index psp_company_event_detail_i2_p1 on pspadm.psp_company_event_detail_p1 USING BTREE (event_detail_type_cd ASC,company_fk ASC);
create index psp_company_event_detail_i2_p2 on pspadm.psp_company_event_detail_p2 USING BTREE (event_detail_type_cd ASC,company_fk ASC);
create index psp_company_event_detail_i2_p3 on pspadm.psp_company_event_detail_p3 USING BTREE (event_detail_type_cd ASC,company_fk ASC);
create index psp_company_event_detail_i2_p4 on pspadm.psp_company_event_detail_p4 USING BTREE (event_detail_type_cd ASC,company_fk ASC);
create index psp_company_event_detail_i2_p5 on pspadm.psp_company_event_detail_p5 USING BTREE (event_detail_type_cd ASC,company_fk ASC);
create index psp_company_event_detail_i2_p6 on pspadm.psp_company_event_detail_p6 USING BTREE (event_detail_type_cd ASC,company_fk ASC);
create index psp_company_event_detail_i2_p7 on pspadm.psp_company_event_detail_p7 USING BTREE (event_detail_type_cd ASC,company_fk ASC);
select  'psp_company_event_detail completed' as status;
SELECT CURRENT_TIMESTAMP;

select 'creating index on psp_company_event_email_param' as status;
create index psp_company_event_email_pa_fk1_p0 on pspadm.psp_company_event_email_param_p0 USING BTREE (company_event_email_fk ASC);
create index psp_company_event_email_pa_fk1_p1 on pspadm.psp_company_event_email_param_p1 USING BTREE (company_event_email_fk ASC);
create index psp_company_event_email_pa_fk1_p2 on pspadm.psp_company_event_email_param_p2 USING BTREE (company_event_email_fk ASC);
create index psp_company_event_email_pa_fk1_p3 on pspadm.psp_company_event_email_param_p3 USING BTREE (company_event_email_fk ASC);
create index psp_company_event_email_pa_fk1_p4 on pspadm.psp_company_event_email_param_p4 USING BTREE (company_event_email_fk ASC);
create index psp_company_event_email_pa_fk1_p5 on pspadm.psp_company_event_email_param_p5 USING BTREE (company_event_email_fk ASC);
create index psp_company_event_email_pa_fk1_p6 on pspadm.psp_company_event_email_param_p6 USING BTREE (company_event_email_fk ASC);
create index psp_company_event_email_pa_fk1_p7 on pspadm.psp_company_event_email_param_p7 USING BTREE (company_event_email_fk ASC);
create index psp_company_event_email_pa_fk2_p0 on pspadm.psp_company_event_email_param_p0 USING BTREE (company_fk ASC);
create index psp_company_event_email_pa_fk2_p1 on pspadm.psp_company_event_email_param_p1 USING BTREE (company_fk ASC);
create index psp_company_event_email_pa_fk2_p2 on pspadm.psp_company_event_email_param_p2 USING BTREE (company_fk ASC);
create index psp_company_event_email_pa_fk2_p3 on pspadm.psp_company_event_email_param_p3 USING BTREE (company_fk ASC);
create index psp_company_event_email_pa_fk2_p4 on pspadm.psp_company_event_email_param_p4 USING BTREE (company_fk ASC);
create index psp_company_event_email_pa_fk2_p5 on pspadm.psp_company_event_email_param_p5 USING BTREE (company_fk ASC);
create index psp_company_event_email_pa_fk2_p6 on pspadm.psp_company_event_email_param_p6 USING BTREE (company_fk ASC);
create index psp_company_event_email_pa_fk2_p7 on pspadm.psp_company_event_email_param_p7 USING BTREE (company_fk ASC);
select  'psp_company_event_email_param completed' as status;
SELECT CURRENT_TIMESTAMP;

select 'creating index on psp_property_audit' as status;
create index psp_propertyaudit_fk1_p0 on pspadm.psp_property_audit_p0 USING BTREE (company_fk ASC);
create index psp_propertyaudit_fk1_p1 on pspadm.psp_property_audit_p1 USING BTREE (company_fk ASC);
create index psp_propertyaudit_fk1_p2 on pspadm.psp_property_audit_p2 USING BTREE (company_fk ASC);
create index psp_propertyaudit_fk1_p3 on pspadm.psp_property_audit_p3 USING BTREE (company_fk ASC);
create index psp_propertyaudit_fk1_p4 on pspadm.psp_property_audit_p4 USING BTREE (company_fk ASC);
create index psp_propertyaudit_fk1_p5 on pspadm.psp_property_audit_p5 USING BTREE (company_fk ASC);
create index psp_propertyaudit_fk1_p6 on pspadm.psp_property_audit_p6 USING BTREE (company_fk ASC);
create index psp_propertyaudit_fk1_p7 on pspadm.psp_property_audit_p7 USING BTREE (company_fk ASC);
select  'psp_property_audit completed' as status;
SELECT CURRENT_TIMESTAMP;

select 'creating index on psp_disburse_advice_tax_liab' as status;
create index psp_disburse_advice_tax_li_fk1_p0 on pspadm.psp_disburse_advice_tax_liab_p0 USING BTREE (disburse_advice_fk ASC);
create index psp_disburse_advice_tax_li_fk1_p1 on pspadm.psp_disburse_advice_tax_liab_p1 USING BTREE (disburse_advice_fk ASC);
create index psp_disburse_advice_tax_li_fk1_p2 on pspadm.psp_disburse_advice_tax_liab_p2 USING BTREE (disburse_advice_fk ASC);
create index psp_disburse_advice_tax_li_fk1_p3 on pspadm.psp_disburse_advice_tax_liab_p3 USING BTREE (disburse_advice_fk ASC);
create index psp_disburse_advice_tax_li_fk2_p0 on pspadm.psp_disburse_advice_tax_liab_p0 USING BTREE (company_fk ASC,tips_liability_fk ASC);
create index psp_disburse_advice_tax_li_fk2_p1 on pspadm.psp_disburse_advice_tax_liab_p1 USING BTREE (company_fk ASC,tips_liability_fk ASC);
create index psp_disburse_advice_tax_li_fk2_p2 on pspadm.psp_disburse_advice_tax_liab_p2 USING BTREE (company_fk ASC,tips_liability_fk ASC);
create index psp_disburse_advice_tax_li_fk2_p3 on pspadm.psp_disburse_advice_tax_liab_p3 USING BTREE (company_fk ASC,tips_liability_fk ASC);
create index psp_disburse_advice_tax_li_fk3_p0 on pspadm.psp_disburse_advice_tax_liab_p0 USING BTREE (company_fk ASC);
create index psp_disburse_advice_tax_li_fk3_p1 on pspadm.psp_disburse_advice_tax_liab_p1 USING BTREE (company_fk ASC);
create index psp_disburse_advice_tax_li_fk3_p2 on pspadm.psp_disburse_advice_tax_liab_p2 USING BTREE (company_fk ASC);
create index psp_disburse_advice_tax_li_fk3_p3 on pspadm.psp_disburse_advice_tax_liab_p3 USING BTREE (company_fk ASC);
select  'psp_disburse_advice_tax_liab completed' as status;
SELECT CURRENT_TIMESTAMP;
