--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--
-- Please review the script before using it to make sure it won't
-- cause any unacceptable data loss.
--
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PSP_LOCAL 

Prompt Column ACCOUNT_NUMBER_ENC;
ALTER TABLE PSP_BANK_ACCOUNT
 ADD (ACCOUNT_NUMBER_ENC  VARCHAR2(4000 CHAR));

Prompt Index PSP_BANK_ACCOUNT_Enc_I1;
CREATE INDEX PSP_BANK_ACCOUNT_Enc_I1 ON PSP_BANK_ACCOUNT
(ACCOUNT_NUMBER_ENC )
NOPARALLEL;

Prompt Column AGENCY_ID_ENC;
ALTER TABLE PSP_PSTUB_STATE_TAX_INFO
 ADD (AGENCY_ID_ENC  VARCHAR2(4000 CHAR));

Prompt Column FED_TAX_ID_ENC;
ALTER TABLE PSP_REPORTING_AGENT
 ADD (FED_TAX_ID_ENC  VARCHAR2(4000 CHAR));

Prompt Column FED_ID_ENC;
ALTER TABLE PSP_REPORTING_AGENT
 ADD (FED_ID_ENC  VARCHAR2(4000 CHAR));

Prompt Column FED_TAX_ID_ENC;
ALTER TABLE PSP_TP401K_SIGNUP_QUEUE
 ADD (FED_TAX_ID_ENC  VARCHAR2(4000 CHAR));

Prompt Column FILE_CONTENT_ENC;
ALTER TABLE PSP_ACHENROLLMENT_FILE
 ADD (FILE_CONTENT_ENC  CLOB);

Prompt Column AGENCY_ID_ENC;
ALTER TABLE PSP_AGENCY
 ADD (AGENCY_ID_ENC  VARCHAR2(4000 CHAR));

Prompt Index PSP_AGENCY_AgencyIdEnc_I1;
CREATE INDEX PSP_AGENCY_AgencyIdEnc_I1 ON PSP_AGENCY
(AGENCY_ID_ENC )
NOPARALLEL;

Prompt Column MESSAGE_ENC;
ALTER TABLE PSP_ENTITLEMENT_MESSAGE
 ADD (MESSAGE_ENC  CLOB);

Prompt Column DATE_OF_BIRTH_ENC;
ALTER TABLE PSP_CONTACT
 ADD (DATE_OF_BIRTH_ENC  TIMESTAMP(6));

Prompt Column SOCIAL_SECURITY_NUMBER_ENC;
ALTER TABLE PSP_CONTACT
 ADD (SOCIAL_SECURITY_NUMBER_ENC  VARCHAR2(4000 CHAR));

Prompt Column BIRTH_DATE_ENC;
ALTER TABLE PSP_EMPLOYEE
 ADD (BIRTH_DATE_ENC  TIMESTAMP(6));

Prompt Column TAX_ID_ENC;
ALTER TABLE PSP_EMPLOYEE
 ADD (TAX_ID_ENC  VARCHAR2(4000 CHAR));


Prompt Index PSP_EMPLOYEE_TaxIdEnc_I1;
CREATE INDEX PSP_EMPLOYEE_TaxIdEnc_I1 ON PSP_EMPLOYEE
(TAX_ID_ENC )
NOPARALLEL;

Prompt Column FED_TAX_ID_ENC;
ALTER TABLE PSP_TAX_CREDITS9061
 ADD (FED_TAX_ID_ENC  VARCHAR2(4000 CHAR));

Prompt Column ACCOUNT_NUMBER_ENC;
ALTER TABLE PSP_PAYEE
 ADD (ACCOUNT_NUMBER_ENC  VARCHAR2(4000 CHAR));

Prompt Column FED_TAX_ID_ENC;
ALTER TABLE PSP_ENTITLEMENT_UNIT
 ADD (FED_TAX_ID_ENC  VARCHAR2(4000 CHAR));

Prompt Index PSP_ENMT_FedTaxidEnc_I1;
CREATE INDEX PSP_ENMT_FedTaxidEnc_I1 ON PSP_ENTITLEMENT_UNIT
(FED_TAX_ID_ENC)
NOPARALLEL;

Prompt Column OLD_EIN_ENC;
ALTER TABLE PSP_ENTITY_CHANGE
 ADD (OLD_EIN_ENC  VARCHAR2(4000 CHAR));

Prompt Column NEW_EIN_ENC;
ALTER TABLE PSP_ENTITY_CHANGE
 ADD (NEW_EIN_ENC  VARCHAR2(4000 CHAR));

Prompt Column ACCOUNT_NUMBER_ENC;
ALTER TABLE PSP_FRAUD_BANK_ACCOUNT
 ADD (ACCOUNT_NUMBER_ENC  VARCHAR2(4000 CHAR));

Prompt Index PSP_FRAUD_ACCOUNT_Enc_I1;
CREATE INDEX PSP_FRAUD_ACCOUNT_Enc_I1 ON PSP_FRAUD_BANK_ACCOUNT
(ACCOUNT_NUMBER_ENC )
NOPARALLEL;

Prompt Column FED_TAX_ID_ENC;
ALTER TABLE PSP_FRAUD_COMPANY
 ADD (FED_TAX_ID_ENC  VARCHAR2(4000 CHAR));

Prompt Column AGENCY_TAXPAYER_ID_ENC;
ALTER TABLE PSP_COMPANYAGENCY_PMTTEMPLATE
 ADD (AGENCY_TAXPAYER_ID_ENC  VARCHAR2(4000 CHAR));

Prompt Column AGENCY_TAXPAYER_ID_ENC;
ALTER TABLE PSP_COMP_PMT_TEMPLATE_AGENCYID
 ADD (AGENCY_TAXPAYER_ID_ENC  VARCHAR2(4000 CHAR));

Prompt Column EIN_ENC;
ALTER TABLE PSP_DEPOSIT_FREQUENCY_FILE_REC
 ADD (EIN_ENC  VARCHAR2(4000 CHAR));

Prompt Column AGENCY_TAXPAYER_ID_ENC;
ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 ADD (AGENCY_TAXPAYER_ID_ENC  VARCHAR2(4000 CHAR));

Prompt Column AGENCY_ID_ENC;
ALTER TABLE PSP_QBDT_PAYROLL_ITEM_INFO
 ADD (AGENCY_ID_ENC  VARCHAR2(4000 CHAR));

Prompt Column AGENCY_ID_ENC;
ALTER TABLE PSP_ACHENROLLMENT_DETAIL
 ADD (AGENCY_ID_ENC  VARCHAR2(4000 CHAR));

Prompt Column FEIN_ENC;
ALTER TABLE PSP_ACHENROLLMENT_DETAIL
 ADD (FEIN_ENC  VARCHAR2(4000 CHAR));

Prompt Column FED_TAX_ID_ENC;
ALTER TABLE PSP_EDI_PAYMENT_DETAIL
 ADD (FED_TAX_ID_ENC  VARCHAR2(4000 CHAR));

Prompt Column FED_TAX_ID_ENC;
ALTER TABLE PSP_EFTPS_ENROLLMENT_DETAIL
 ADD (FED_TAX_ID_ENC  VARCHAR2(4000 CHAR));

Prompt Column FED_TAX_ID_ENC;
ALTER TABLE PSP_EFTPS_PAYMENT_DETAIL
 ADD (FED_TAX_ID_ENC  VARCHAR2(4000 CHAR));

Prompt Column TXP_RECORD_DATA_ENC;
ALTER TABLE PSP_ENTRY_DETAIL_RECORD
 ADD (TXP_RECORD_DATA_ENC  VARCHAR2(4000 CHAR));

Prompt Column RECORD_DATA_ENC;
ALTER TABLE PSP_ENTRY_DETAIL_RECORD
 ADD (RECORD_DATA_ENC  VARCHAR2(4000 CHAR));

Prompt Column COMPANY_EIN_ENC;
ALTER TABLE PSP_FRAUD_EVENT
 ADD (COMPANY_EIN_ENC  VARCHAR2(4000 CHAR));

Prompt Column FRAUD_TRIGGER_DETAIL_ENC;
ALTER TABLE PSP_FRAUD_EVENT
 ADD (FRAUD_TRIGGER_DETAIL_ENC  VARCHAR2(4000 CHAR));

Prompt Column FED_TAX_ID_ENC;
ALTER TABLE PSP_FSET_FILING_DETAIL
 ADD (FED_TAX_ID_ENC  VARCHAR2(4000 CHAR));

Prompt Column AGENCY_ID_ENC;
ALTER TABLE PSP_FSET_FILING_DETAIL
 ADD (AGENCY_ID_ENC  VARCHAR2(4000 CHAR));

PROMPT finished DBUpgrade_002.018.004.001.sql