--
-- This script will be executed BEFORE the automatically generated
-- D:\dev\PSP\main\PSE\Domain\src\main\model\DBUpgrade_002.001.000.004.sql
--
-- Developers can hand code logic here for data migration purposes
--
