--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--
-- Please review the script before using it to make sure it won't
-- cause any unacceptable data loss.
--
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PSP_LOCAL 

-- moved to pre deploy script
/*Prompt Column E_E_CALCULATION_TOKEN;
ALTER TABLE PSP_PAYROLL_RUN
 ADD (E_E_CALCULATION_TOKEN  NUMBER(19));*/

Prompt Table PSP_EMPLOYEE_LAW_QTR_TOTALS;
CREATE TABLE PSP_EMPLOYEE_LAW_QTR_TOTALS
(
  EMPLOYEE_LAW_QTR_TOTALS_SEQ   VARCHAR2(255 CHAR),
  VERSION                       NUMBER(19),
  CREATOR_ID                    VARCHAR2(30 CHAR),
  CREATED_DATE                  TIMESTAMP(6),
  MODIFIER_ID                   VARCHAR2(30 CHAR),
  MODIFIED_DATE                 TIMESTAMP(6),
  REALM_ID                      NUMBER(19)      DEFAULT -1,
  HOURS_WORKED                  NUMBER(19,7),
  MONTH_ONE_WORKED_INDICATOR    NUMBER(1),
  MONTH_TWO_WORKED_INDICATOR    NUMBER(1),
  MONTH_THREE_WORKED_INDICATOR  NUMBER(1),
  QUARTER                       NUMBER(10),
  TAXABLE_WAGES                 NUMBER(19,4),
  TAX_AMOUNT                    NUMBER(19,4),
  TIPS_TAXABLE_WAGES_AMOUNT     NUMBER(19,4),
  TOTAL_WAGES                   NUMBER(19,4),
  WEEKS_WORKED                  NUMBER(10),
  YEAR                          NUMBER(10),
  LAW_FK                        VARCHAR2(255 CHAR),
  EMPLOYEE_FK                   VARCHAR2(255 CHAR),
  COMPANY_FK                    VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_EMPLOYEE_LAW_QTR_TOTAL_FK1;
CREATE INDEX PSP_EMPLOYEE_LAW_QTR_TOTAL_FK1 ON PSP_EMPLOYEE_LAW_QTR_TOTALS
(LAW_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_EMPLOYEE_LAW_QTR_TOTAL_FK2;
CREATE INDEX PSP_EMPLOYEE_LAW_QTR_TOTAL_FK2 ON PSP_EMPLOYEE_LAW_QTR_TOTALS
(EMPLOYEE_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_EMPLOYEE_LAW_QTR_TOTAL_FK3;
CREATE INDEX PSP_EMPLOYEE_LAW_QTR_TOTAL_FK3 ON PSP_EMPLOYEE_LAW_QTR_TOTALS
(COMPANY_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_EMPLOYEE_LAW_QTR_TOTALS
 ADD PRIMARY KEY
  (EMPLOYEE_LAW_QTR_TOTALS_SEQ, REALM_ID);

Prompt Table PSP_EE_PAYROLLITEM_QTRTOTALS;
CREATE TABLE PSP_EE_PAYROLLITEM_QTRTOTALS
(
  EE_PAYROLLITEM_QTRTOTALS_SEQ  VARCHAR2(255 CHAR),
  VERSION                       NUMBER(19),
  CREATOR_ID                    VARCHAR2(30 CHAR),
  CREATED_DATE                  TIMESTAMP(6),
  MODIFIER_ID                   VARCHAR2(30 CHAR),
  MODIFIED_DATE                 TIMESTAMP(6),
  REALM_ID                      NUMBER(19)      DEFAULT -1,
  QUARTER                       NUMBER(10),
  YEAR                          NUMBER(10),
  TAXABLE_WAGES                 NUMBER(19,4),
  AMOUNT                        NUMBER(19,4),
  TOTAL_WAGES                   NUMBER(19,4),
  TIPS_TAXABLE_WAGES_AMOUNT     NUMBER(19,4),
  COMPANY_PAYROLL_ITEM_FK       VARCHAR2(255 CHAR),
  EMPLOYEE_FK                   VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_EMPLOYEE_PAYROLL_ITEM__FK2;
CREATE INDEX PSP_EMPLOYEE_PAYROLL_ITEM__FK2 ON PSP_EE_PAYROLLITEM_QTRTOTALS
(EMPLOYEE_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_EMPLOYEE_PAYROLL_ITEM__FK1;
CREATE INDEX PSP_EMPLOYEE_PAYROLL_ITEM__FK1 ON PSP_EE_PAYROLLITEM_QTRTOTALS
(COMPANY_PAYROLL_ITEM_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_EE_PAYROLLITEM_QTRTOTALS
 ADD PRIMARY KEY
  (EE_PAYROLLITEM_QTRTOTALS_SEQ, REALM_ID);

Prompt Table PSP_EMPLOYEE_W2_TOTALS;
CREATE TABLE PSP_EMPLOYEE_W2_TOTALS
(
  EMPLOYEE_W2_TOTALS_SEQ     VARCHAR2(255 CHAR),
  VERSION                    NUMBER(19),
  CREATOR_ID                 VARCHAR2(30 CHAR),
  CREATED_DATE               TIMESTAMP(6),
  MODIFIER_ID                VARCHAR2(30 CHAR),
  MODIFIED_DATE              TIMESTAMP(6),
  REALM_ID                   NUMBER(19)         DEFAULT -1,
  YEAR                       NUMBER(10),
  TAXABLE_WAGES              NUMBER(19,4),
  AMOUNT                     NUMBER(19,4),
  TIPS_TAXABLE_WAGES_AMOUNT  NUMBER(19,4),
  TOTAL_WAGES                NUMBER(19,4),
  COMPANY_PAYROLL_ITEM_FK    VARCHAR2(255 CHAR),
  EMPLOYEE_FK                VARCHAR2(255 CHAR),
  LAW_FK                     VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_EMPLOYEE_W2_TOTALS_FK1;
CREATE INDEX PSP_EMPLOYEE_W2_TOTALS_FK1 ON PSP_EMPLOYEE_W2_TOTALS
(COMPANY_PAYROLL_ITEM_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_EMPLOYEE_W2_TOTALS_FK2;
CREATE INDEX PSP_EMPLOYEE_W2_TOTALS_FK2 ON PSP_EMPLOYEE_W2_TOTALS
(EMPLOYEE_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_EMPLOYEE_W2_TOTALS_FK3;
CREATE INDEX PSP_EMPLOYEE_W2_TOTALS_FK3 ON PSP_EMPLOYEE_W2_TOTALS
(LAW_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_EMPLOYEE_W2_TOTALS
 ADD PRIMARY KEY
  (EMPLOYEE_W2_TOTALS_SEQ, REALM_ID);

ALTER TABLE PSP_EMPLOYEE_LAW_QTR_TOTALS
 ADD CONSTRAINT PSP_EMPLOYEE_LAW_QTR_TOTAL_FK1 
  FOREIGN KEY (LAW_FK, REALM_ID) 
  REFERENCES PSP_LAW (LAW_ID,REALM_ID);

ALTER TABLE PSP_EMPLOYEE_LAW_QTR_TOTALS
 ADD CONSTRAINT PSP_EMPLOYEE_LAW_QTR_TOTAL_FK2 
  FOREIGN KEY (EMPLOYEE_FK, REALM_ID) 
  REFERENCES PSP_EMPLOYEE (EMPLOYEE_SEQ,REALM_ID);

ALTER TABLE PSP_EMPLOYEE_LAW_QTR_TOTALS
 ADD CONSTRAINT PSP_EMPLOYEE_LAW_QTR_TOTAL_FK3 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

ALTER TABLE PSP_EE_PAYROLLITEM_QTRTOTALS
 ADD CONSTRAINT PSP_EMPLOYEE_PAYROLL_ITEM__FK1 
  FOREIGN KEY (COMPANY_PAYROLL_ITEM_FK, REALM_ID) 
  REFERENCES PSP_COMPANY_PAYROLL_ITEM (COMPANY_PAYROLL_ITEM_SEQ,REALM_ID);

ALTER TABLE PSP_EE_PAYROLLITEM_QTRTOTALS
 ADD CONSTRAINT PSP_EMPLOYEE_PAYROLL_ITEM__FK2 
  FOREIGN KEY (EMPLOYEE_FK, REALM_ID) 
  REFERENCES PSP_EMPLOYEE (EMPLOYEE_SEQ,REALM_ID);

ALTER TABLE PSP_EMPLOYEE_W2_TOTALS
 ADD CONSTRAINT PSP_EMPLOYEE_W2_TOTALS_FK1 
  FOREIGN KEY (COMPANY_PAYROLL_ITEM_FK, REALM_ID) 
  REFERENCES PSP_COMPANY_PAYROLL_ITEM (COMPANY_PAYROLL_ITEM_SEQ,REALM_ID);

ALTER TABLE PSP_EMPLOYEE_W2_TOTALS
 ADD CONSTRAINT PSP_EMPLOYEE_W2_TOTALS_FK2 
  FOREIGN KEY (EMPLOYEE_FK, REALM_ID) 
  REFERENCES PSP_EMPLOYEE (EMPLOYEE_SEQ,REALM_ID);

ALTER TABLE PSP_EMPLOYEE_W2_TOTALS
 ADD CONSTRAINT PSP_EMPLOYEE_W2_TOTALS_FK3 
  FOREIGN KEY (LAW_FK, REALM_ID) 
  REFERENCES PSP_LAW (LAW_ID,REALM_ID);

PROMPT finishedDBUpgrade_002.001.001.010.sql