--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--                                                                      --
-- Please review the script before using it to make sure it won't       --
-- cause any unacceptable data loss.                                    --
--                                                                      --
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 

/* 
Prompt COLUMN TOKEN;
ALTER TABLE PSP_ENTITLEMENT_MESSAGE
 ADD (TOKEN  NUMBER(19));

Prompt COLUMN CREDIT_CARD_TYPE;
ALTER TABLE PSP_ENTITLEMENT
MODIFY(CREDIT_CARD_TYPE VARCHAR2(20 CHAR));


Prompt COLUMN VERSION;
ALTER TABLE PSP_COMPANY
MODIFY(VERSION  DEFAULT 0);

Prompt COLUMN VERSION;
ALTER TABLE PSP_AUTH_USER
MODIFY(VERSION  DEFAULT 0);

Prompt COLUMN F_E_I_N;
ALTER TABLE PSP_ENTITLEMENT_UNIT
 ADD (F_E_I_N  VARCHAR2(9 CHAR));

ALTER TABLE PSP_COMPANY_EVENT DROP CONSTRAINT PSP_COMPANY_EVENT_FK2;

DROP INDEX PSP_COMPANY_EVENT_FK2;

Prompt COLUMN EVENT_AS400_SYNC_FK;
ALTER TABLE PSP_COMPANY_EVENT DROP COLUMN EVENT_AS400_SYNC_FK;

Prompt COLUMN COMPANY_EVENT_FK;
ALTER TABLE PSP_EVENT_AS400_SYNC
 ADD (COMPANY_EVENT_FK  VARCHAR2(255 CHAR)          NOT NULL);

Prompt INDEX PSP_EVENT_AS400_SYNC_FK1;
--
-- PSP_EVENT_AS400_SYNC_FK1  (Index) 
--
CREATE INDEX PSP_EVENT_AS400_SYNC_FK1 ON PSP_EVENT_AS400_SYNC
(COMPANY_EVENT_FK, REALM_ID)
LOGGING
NOPARALLEL;

ALTER TABLE PSP_EVENT_AS400_SYNC
 ADD CONSTRAINT PSP_EVENT_AS400_SYNC_FK1 
 FOREIGN KEY (COMPANY_EVENT_FK, REALM_ID) 
 REFERENCES PSP_COMPANY_EVENT (COMPANY_EVENT_SEQ,REALM_ID); */ 


PROMPT finishedDBUpgrade_002.001.000.002.sql