--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--
-- Please review the script before using it to make sure it won't
-- cause any unacceptable data loss.
--
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PSP_LOCAL 

Prompt Table PSP_ANNUAL_BILLING_BATCH;
CREATE TABLE PSP_ANNUAL_BILLING_BATCH
(
  ANNUAL_BILLING_BATCH_SEQ        VARCHAR2(255 CHAR),
  VERSION                         NUMBER(19),
  CREATOR_ID                      VARCHAR2(30 CHAR),
  CREATED_DATE                    TIMESTAMP(6),
  MODIFIER_ID                     VARCHAR2(30 CHAR),
  MODIFIED_DATE                   TIMESTAMP(6),
  REALM_ID                        NUMBER(19)    DEFAULT -1,
  FORM_TYPE_CD                    VARCHAR2(255 CHAR),
  FORM_YEAR                       NUMBER(10),
  ANNUAL_BILLING_BATCH_STATUS_CD  VARCHAR2(255 CHAR)
)
NOPARALLEL;

ALTER TABLE PSP_ANNUAL_BILLING_BATCH
 ADD PRIMARY KEY
  (ANNUAL_BILLING_BATCH_SEQ, REALM_ID)
  USING INDEX;

Prompt Column ANNUAL_BILLING_BATCH_FK;
ALTER TABLE PSP_COMPANY
 ADD (ANNUAL_BILLING_BATCH_FK  VARCHAR2(255 CHAR));

Prompt Index PSP_COMPANY_FK7;
CREATE INDEX PSP_COMPANY_FK7 ON PSP_COMPANY
(ANNUAL_BILLING_BATCH_FK, REALM_ID)
NOPARALLEL;

Prompt Table PSP_ANNUAL_BILLING_ITEM;
CREATE TABLE PSP_ANNUAL_BILLING_ITEM
(
  ANNUAL_BILLING_ITEM_SEQ        VARCHAR2(255 CHAR),
  VERSION                        NUMBER(19),
  CREATOR_ID                     VARCHAR2(30 CHAR),
  CREATED_DATE                   TIMESTAMP(6),
  MODIFIER_ID                    VARCHAR2(30 CHAR),
  MODIFIED_DATE                  TIMESTAMP(6),
  REALM_ID                       NUMBER(19)     DEFAULT -1,
  FORM_COUNT                     NUMBER(10),
  ERROR_MESSAGE                  VARCHAR2(4000 CHAR),
  ANNUAL_BILLING_ITEM_STATUS_CD  VARCHAR2(255 CHAR),
  ANNUAL_BILLING_BATCH_FK        VARCHAR2(255 CHAR),
  COMPANY_FK                     VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_ANNUALBILLINGITEM_FK1;
CREATE INDEX PSP_ANNUALBILLINGITEM_FK1 ON PSP_ANNUAL_BILLING_ITEM
(ANNUAL_BILLING_BATCH_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_ANNUALBILLINGITEM_FK2;
CREATE INDEX PSP_ANNUALBILLINGITEM_FK2 ON PSP_ANNUAL_BILLING_ITEM
(COMPANY_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_ANNUAL_BILLING_ITEM
 ADD PRIMARY KEY
  (ANNUAL_BILLING_ITEM_SEQ, REALM_ID)
  USING INDEX;

ALTER TABLE PSP_ANNUAL_BILLING_ITEM
 ADD CONSTRAINT PSP_ANNUALBILLINGITEM_FK1 
  FOREIGN KEY (ANNUAL_BILLING_BATCH_FK, REALM_ID) 
  REFERENCES PSP_ANNUAL_BILLING_BATCH (ANNUAL_BILLING_BATCH_SEQ,REALM_ID);

ALTER TABLE PSP_ANNUAL_BILLING_ITEM
 ADD CONSTRAINT PSP_ANNUALBILLINGITEM_FK2 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

ALTER TABLE PSP_COMPANY
 ADD CONSTRAINT PSP_COMPANY_FK7 
  FOREIGN KEY (ANNUAL_BILLING_BATCH_FK, REALM_ID) 
  REFERENCES PSP_ANNUAL_BILLING_BATCH (ANNUAL_BILLING_BATCH_SEQ,REALM_ID);

PROMPT finishedDBUpgrade_002.012.012.001.sql