UPDATE PSP_EMPLOYEE SET IS_CLOUD_EMPLOYEE=0;

UPDATE PSP_EMPLOYEE SET IS_CLOUD_EMPLOYEE=1 WHERE 
    TP_401K_INFO_BIRTH_DATE IS NOT NULL OR
    TP_401K_INFO_IS_HCE IS NOT NULL OR
    TP_401K_INFO_OWNER_PERCENT IS NOT NULL OR
    TP_401K_INFO_IS_FAMILY_MEMBER IS NOT NULL OR
    TP_401K_INFO_LAST_UPLOAD_DATE IS NOT NULL;
	