
PROMPT started DBUpgrade_002.016.006.003.sql
  
Prompt COLUMN START_TIME;
ALTER TABLE PSP_IOPSYNC_COMPANY
 ADD (START_TIME  TIMESTAMP);
 
 Prompt COLUMN END_TIME;
ALTER TABLE PSP_IOPSYNC_COMPANY
 ADD (END_TIME  TIMESTAMP);
 
PROMPT finished DBUpgrade_002.016.006.003.sql