--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--
-- Please review the script before using it to make sure it won't
-- cause any unacceptable data loss.
--
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PSP_LOCAL 

Prompt Column ASSET_TYPE_CD;
ALTER TABLE PSP_ENTITLEMENT_CODE
 ADD (ASSET_TYPE_CD  VARCHAR2(255 CHAR));

Prompt Constraint C_PSP_ENTITLEMENT_CODE0;
ALTER TABLE PSP_ENTITLEMENT_CODE
 DROP CONSTRAINT C_PSP_ENTITLEMENT_CODE0;

ALTER TABLE PSP_ENTITLEMENT_CODE
 ADD CONSTRAINT C_PSP_ENTITLEMENT_CODE0
  CHECK (ASSET_TYPE_CD IN('Payroll', 'Usage'));

Prompt Constraint C_PSP_ENTITLEMENT_CODE1;
ALTER TABLE PSP_ENTITLEMENT_CODE
 DROP CONSTRAINT C_PSP_ENTITLEMENT_CODE1;

ALTER TABLE PSP_ENTITLEMENT_CODE
 ADD CONSTRAINT C_PSP_ENTITLEMENT_CODE1
  CHECK (ASSET_ITEM_CD IN('Assisted', 'AssistedAdvantage', 'DIY', 'DIYDiskDelivery', 'EmployeeOrganizer', 'EmploymentRegulation'));

Prompt Constraint C_PSP_ENTITLEMENT_CODE2;
ALTER TABLE PSP_ENTITLEMENT_CODE
 DROP CONSTRAINT C_PSP_ENTITLEMENT_CODE2;

ALTER TABLE PSP_ENTITLEMENT_CODE
 ADD CONSTRAINT C_PSP_ENTITLEMENT_CODE2
  CHECK (EDITION_TYPE IN('EnhancedAccountantProAdvisor', 'Basic', 'Enhanced', 'EnhancedAccountant', 'Standard'));

Prompt Constraint C_PSP_ENTITLEMENT_CODE3;
ALTER TABLE PSP_ENTITLEMENT_CODE
 DROP CONSTRAINT C_PSP_ENTITLEMENT_CODE3;

ALTER TABLE PSP_ENTITLEMENT_CODE
 ADD CONSTRAINT C_PSP_ENTITLEMENT_CODE3
  CHECK (NUMBER_OF_EMPLOYEES_TYPE IN('ONE', 'UPTO3', 'UNLIMITED'));

ALTER TABLE PSP_ENTITLEMENT_CODE
 ADD CONSTRAINT C_PSP_ENTITLEMENT_CODE4
  CHECK (BILLING_FREQUENCY_TYPE IN('Monthly', 'Annually'));

PROMPT finished DBUpgrade_002.013.009.001.sql