--
-- This script will be executed AFTER the automatically generated
-- D:\dev\psp\dev\PSE\Domain\src\main\model\DBUpgrade_002.013.006.005.sql
--
-- Developers can hand code logic here for data migration purposes
--
