--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--
-- Please review the script before using it to make sure it won't
-- cause any unacceptable data loss.
--
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PSP_LOCAL 

Prompt Constraint C_PSP_TRANSACTION_TYPE0;
ALTER TABLE PSP_TRANSACTION_TYPE
 DROP CONSTRAINT C_PSP_TRANSACTION_TYPE0;

ALTER TABLE PSP_TRANSACTION_TYPE
 ADD CONSTRAINT C_PSP_TRANSACTION_TYPE0
  CHECK (TRANSACTION_TYPE_CD IN('FLAdERLOcERPAY', 'FLAdERLOcTXCC', 'FLAdERPAYcERLO', 'BadDebtRecovery', 'EmployeeDdCredit', 'FLAdERPAYcTXCL', 'FLAdFCRcFI', 'EmployeeDdReversalDebit', 'EmployeeEscalationCredit', 'EmployerDdDebit', 'EmployerDdRedebit', 'EmployerTaxRefundCredit', 'EmployerDdRefundCredit', 'EmployerDdRejectRefundCredit', 'EmployerDdReturnedRefundCredit', 'EmployerDdReversalRefundCredit', 'EmployerDoublePaymentRefundCredit', 'EmployerEscalationCredit', 'EmployerFeeDebit', 'EmployerFeeRedebit', 'EmployerFeeRefundCredit', 'DdFraud', 'EmployerWriteOff', 'Intuit5DayReturnTransfer', 'IntuitEmployeeReturnTransfer', 'IntuitFeeTransfer', 'EmployerFeeReturnedRefundCredit', 'IntuitEmployerVerificationReturnTransfer', 'EmployerVerificationDebit', 'AgencyHPDEWarehousedTaxPayment', 'BadDebtCustomerRecoverySalesAndUseTax', 'IntuitTaxVoidTransfer', 'ThirdPartyCollectionExpense', 'ServiceSalesAndUseTax', 'ServiceSalesAndUseTaxRefundCredit', 'UntimelyReturnPostWriteOff', 'UntimelyReturnPreWriteOff', 'ServiceSalesAndUseTaxRedebit', 'ServiceSalesAndUseTaxReturnedRefundCredit', 'BadDebtRecoveryFee', 'BadDebtRecoverySalesAndUseTax', 'EmployerWriteOffFee', 'EmployerWriteOffSalesAndUseTax', 'EmployerFraudOrEscalationRefundCredit', 'EmployerTaxRedebit', 'EmployerTaxCredit', 'EmployerTaxReturnedCredit', 'AgencyTaxDebit', 'AgencyTaxCredit', 'EmployerTaxDebit', 'EmployerTaxReturnedRefundCredit', 'BadDebtCustomerRecovery', 'EmployerTaxDirectOverpaymentApplied', 'AgencyHPDETaxRefund', 'AgencyTaxRecredit', 'AgencyTaxRedebit', 'FLAdERRCcERRR', 'FLAdEERCcERRR', 'EmployerCobraPaymentAdjustmentDebit', 'AgencyCobraPaymentAdjustmentCredit', 'BadDebtCustomerRecoveryFee', 'EmployerPenaltiesRefundCredit', 'EmployerInterestRefundCredit', 'AgencyInterestCredit', 'FLAdERPAYcTXCC', 'FLAdATRcTXCL', 'FLAdFCBcCOGSINT', 'FLAdTXCCcERSUI', 'FLAdERSUIcTXCC', 'AgencyHPDETaxPayment', 'EmployerCreditBalanceCarryForwardCredit', 'AgencyCreditBalanceCarryForwardDebit', 'FLAdERSUIcTXCL', 'FLAdERSUIcATR', 'FLAdERSUIcERLO', 'FLAdERSUIcERPAY', 'ReissueAgencyTaxDebitOffset', 'FLAdTXCLcERSUI', 'AgencyRefundTOR', 'ReissueTaxLiabilityTransfer', 'FLAdATRcERSUI', 'FLAdERPAYcERSUI', 'FLAdBDcERRR', 'EmployeeReversalFailedWriteOff', 'ERPayableAppliedBalanceDue'
, 'Intuit5DayFeeReturnTransfer', 'Intuit5DaySalesTaxReturnTransfer', 'FLAdBDcERRC', 'FLAdBDcEERL', 'EmployerTaxDirectDebit', 'AgencyDirectCredit', 'EmployerTaxCreditApplied', 'EmployerTaxOverpaymentApplied', 'AgencyTaxOverpayment', 'AgencyTaxOverpaymentApplied', 'FLAdBDcTXCC', 'FLAdTXCLcTXCC', 'AgencyHPDEPriorPaymentApplied', 'AgencyDirectOverpayment', 'AgencyPostBALFHPDETaxRefund', 'AgencyDirectDebit', 'AgencyPostBALFHPDETaxPayment', 'FLAdTXCLcERLO', 'FLAdERRRcERRC', 'FLAdTXCCcTXCL', 'FLAdATRcERPAY', 'FLAdDDCLcDDCC', 'FLAdDDCCcDDCL', 'FLATemp1', 'FLATemp2', 'FLATemp3', 'FLATemp4', 'FLATemp5', 'EmployerSUITaxReceivable', 'EmployerSUITaxCollection', 'EmployerSUITaxRefund', 'EmployerSUITaxPayable', 'GlobalBookTransfer', 'EmployerVerificationCredit', 'BadDebtCustomerRecoveryTax', 'EmployerTaxDoublePaymentRefundCredit', 'EmployerTaxFraudOrEscalationRefundCredit', 'EmployerWriteOffTax', 'BadDebtRecoveryTax', 'FLAdTXCLcATR', 'FLAdEERLcEERC', 'FLAdTXCLcERPAY', 'FLAdBDcTXCL', 'FLAdTXCCcERPAY', 'FLAdERLOcTXCL', 'EmployerTaxCreditReturnedTransfer', 'EmployerInterestRefundDebit', 'EmployerPenaltiesRefundDebit', 'ERCourtesyRefundCredit', 'FLAdBDcERPAY', 'FLAdERLOcERSUI', 'FLAdTXCCcERLO', 'FLAdBDcATR', 'EmployerVerificationCreditReturnTransfer', 'FLAdBDcERLO', 'FLAdBDcERSUI', 'FLAdERRRcBD', 'FLAdERRCcBD', 'FLAdEERLcBD', 'FLAdTXCCcBD', 'FLAdTXCLcBD', 'FLAdERPAYcBD', 'FLAdATRcBD', 'FLAdERLOcBD', 'FLAdERSUIcBD', 'FLAdATRcTXCC', 'FLAdTXCCcATR', 'FLAdEERCcEERL'));

PROMPT finished DBUpgrade_002.017.003.001.sql