--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--
-- Please review the script before using it to make sure it won't
-- cause any unacceptable data loss.
--
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PSP_LOCAL 

Prompt Column VERSION;
ALTER TABLE PSP_AUTH_USER
MODIFY(VERSION  DEFAULT 0);

Prompt Column VERSION;
ALTER TABLE PSP_COMPANY
MODIFY(VERSION  DEFAULT 0);

Prompt Column VERSION;
ALTER TABLE PSP_ENTITLEMENT_UNIT
MODIFY(VERSION  DEFAULT 0);

Prompt Column OLD_RATE;
ALTER TABLE PSP_COMPANY_RATE_REQUEST
 ADD (OLD_RATE  NUMBER(19,7));

Prompt Column NEW_RATE;
ALTER TABLE PSP_COMPANY_RATE_REQUEST
 ADD (NEW_RATE  NUMBER(19,7));

Prompt Column VERSION;
ALTER TABLE PSP_QUICKBOOKS_INFO
MODIFY(VERSION  DEFAULT 0);

Prompt Table PSP_ADE_LAW_MAP;
CREATE TABLE PSP_ADE_LAW_MAP
(
  ADE_LAW_MAP_ID  VARCHAR2(50 CHAR),
  VERSION         NUMBER(19),
  REALM_ID        NUMBER(19)                    DEFAULT -1,
  ADE_NAME        VARCHAR2(50 CHAR),
  LAW_FK          VARCHAR2(255 CHAR),
  ADE_LAW_MAP_FK  VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_ADE_LAW_MAP_FK1;
CREATE INDEX PSP_ADE_LAW_MAP_FK1 ON PSP_ADE_LAW_MAP
(LAW_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_ADE_LAW_MAP_FK2;
CREATE INDEX PSP_ADE_LAW_MAP_FK2 ON PSP_ADE_LAW_MAP
(ADE_LAW_MAP_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_ADE_LAW_MAP
 ADD PRIMARY KEY
  (ADE_LAW_MAP_ID, REALM_ID)
  USING INDEX;

ALTER TABLE PSP_ADE_LAW_MAP
 ADD CONSTRAINT PSP_ADE_LAW_MAP_FK1 
  FOREIGN KEY (LAW_FK, REALM_ID) 
  REFERENCES PSP_LAW (LAW_ID,REALM_ID);

ALTER TABLE PSP_ADE_LAW_MAP
 ADD CONSTRAINT PSP_ADE_LAW_MAP_FK2 
  FOREIGN KEY (ADE_LAW_MAP_FK, REALM_ID) 
  REFERENCES PSP_ADE_LAW_MAP (ADE_LAW_MAP_ID,REALM_ID);

PROMPT finishedDBUpgrade_002.013.004.005.sql