--
-- This script will be executed BEFORE the automatically generated
-- C:\Dev\PSP\rel-1.9\PSE\Domain\src\main\model\DBUpgrade_002.000.000.063.sql
--
-- Developers can hand code logic here for data migration purposes
--
