--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--
-- Please review the script before using it to make sure it won't
-- cause any unacceptable data loss.
--
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PSP_LOCAL 

Prompt Column SYSTEM_MODIFIED_TOKEN;
ALTER TABLE PSP_LIABILITY_CHECK
 ADD (SYSTEM_MODIFIED_TOKEN  NUMBER(19));

Prompt Column IS_REFUND;
ALTER TABLE PSP_LIABILITY_CHECK DROP COLUMN IS_REFUND;

Prompt Column COMPANY_FK;
ALTER TABLE PSP_QBDT_PAYROLL_TRANSACTION
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));

Prompt Index PSP_QBDT_PAYROLL_TRANSACTI_FK3;
CREATE INDEX PSP_QBDT_PAYROLL_TRANSACTI_FK3 ON PSP_QBDT_PAYROLL_TRANSACTION
(COMPANY_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_QBDT_PAYROLL_TRANSACTION
 ADD CONSTRAINT PSP_QBDT_PAYROLL_TRANSACTI_FK3 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

PROMPT finishedDBUpgrade_002.000.012.006.sql