--
-- This script will be executed AFTER the automatically generated
-- C:\Dev\PSP\rel-1.9\PSE\Domain\src\main\model\DBUpgrade_002.000.000.067.sql
--
-- Developers can hand code logic here for data migration purposes
--
INSERT INTO PSP_FRAUD_COMPANY
            (FRAUD_COMPANY_SEQ, COMPANY_FK, FED_TAX_ID, LEGAL_NAME, DBA_NAME, NOTIFICATION_EMAIL, LICENSE_NUMBER, SOURCE_AGREEMENT_ID, VERSION, CREATED_DATE, MODIFIED_DATE, CREATOR_ID, MODIFIER_ID)
     SELECT FN_FORMAT_SYSGUID(SYS_GUID()), C.COMPANY_SEQ, C.FED_TAX_ID, C.LEGAL_NAME, C.DBA_NAME, C.NOTIFICATION_EMAIL, C.QUICKBOOKS_INFO_LICENSE_NUMBER, C.AGREE_INFO_SOURCE_ID, 0, sysdate, sysdate, 'BatchJob', 'BatchJob' 
       FROM PSP_COMPANY_SERVICE cs 
 INNER JOIN PSP_COMPANY c ON C.COMPANY_SEQ  = CS.COMPANY_FK
      WHERE CS.STATUS_CD = 'Terminated'
        AND CS.SERVICE_FK = 'DirectDeposit';
              
INSERT INTO PSP_FRAUD_ADDRESS
            (FRAUD_ADDRESS_SEQ, COMPANY_FK, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, CITY, STATE, ZIP_CODE, VERSION, CREATED_DATE, MODIFIED_DATE, CREATOR_ID, MODIFIER_ID)  
     SELECT FN_FORMAT_SYSGUID(SYS_GUID()), COMPANY_SEQ, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, CITY, STATE, ZIP_CODE, 0, sysdate, sysdate, 'BatchJob', 'BatchJob'
       FROM (
         SELECT C.COMPANY_SEQ, CA.ADDRESS_LINE1, CA.ADDRESS_LINE2, CA.ADDRESS_LINE3, CA.CITY, CA.STATE, CA.ZIP_CODE
           FROM PSP_COMPANY c
     INNER JOIN PSP_COMPANY_SERVICE cs ON CS.COMPANY_FK = C.COMPANY_SEQ AND CS.SERVICE_FK = 'DirectDeposit'
     INNER JOIN PSP_ADDRESS ca ON C.LEGAL_ADDRESS_FK = CA.ADDRESS_SEQ 
          WHERE CS.STATUS_CD = 'Terminated'
            AND CS.SERVICE_FK = 'DirectDeposit'
     UNION
         SELECT C.COMPANY_SEQ, CA.ADDRESS_LINE1, CA.ADDRESS_LINE2, CA.ADDRESS_LINE3, CA.CITY, CA.STATE, CA.ZIP_CODE
           FROM PSP_COMPANY c
     INNER JOIN PSP_COMPANY_SERVICE cs ON CS.COMPANY_FK = C.COMPANY_SEQ AND CS.SERVICE_FK = 'DirectDeposit'
     INNER JOIN PSP_ADDRESS ca ON C.MAILING_ADDRESS_FK = CA.ADDRESS_SEQ 
          WHERE CS.STATUS_CD = 'Terminated' 
            AND CS.SERVICE_FK = 'DirectDeposit'          
            );

INSERT INTO PSP_FRAUD_CONTACT
            (FRAUD_CONTACT_SEQ, COMPANY_FK, FIRST_NAME, LAST_NAME, PHONE, EMAIL, VERSION, CREATED_DATE, MODIFIED_DATE, CREATOR_ID, MODIFIER_ID)
     SELECT FN_FORMAT_SYSGUID(SYS_GUID()), C.COMPANY_SEQ, I.FIRST_NAME, I.LAST_NAME, I.PHONE, I.EMAIL, 0, sysdate, sysdate, 'BatchJob', 'BatchJob'
       FROM PSP_COMPANY c
INNER JOIN PSP_COMPANY_SERVICE cs ON CS.COMPANY_FK = C.COMPANY_SEQ AND CS.SERVICE_FK = 'DirectDeposit'
INNER JOIN PSP_CONTACT cc ON C.COMPANY_SEQ = CC.COMPANY_FK
INNER JOIN PSP_INDIVIDUAL i ON CC.CONTACT_SEQ = I.INDIVIDUAL_SEQ 
      WHERE CS.STATUS_CD = 'Terminated'
        AND CS.SERVICE_FK = 'DirectDeposit'                
   GROUP BY C.COMPANY_SEQ, I.FIRST_NAME, I.LAST_NAME, I.PHONE, I.EMAIL;

INSERT INTO PSP_FRAUD_COMPANY
            (FRAUD_COMPANY_SEQ, COMPANY_FK, FED_TAX_ID, LEGAL_NAME, DBA_NAME, NOTIFICATION_EMAIL, LICENSE_NUMBER, SOURCE_AGREEMENT_ID, VERSION, CREATED_DATE, MODIFIED_DATE, CREATOR_ID, MODIFIER_ID)
     SELECT FN_FORMAT_SYSGUID(SYS_GUID()), COMPANY_SEQ, FED_TAX_ID, LEGAL_NAME, DBA_NAME, NOTIFICATION_EMAIL, LICENSE_NUMBER, SOURCE_AGREEMENT_ID, 0, sysdate, sysdate, 'BatchJob', 'BatchJob' 
       FROM (
              SELECT C.COMPANY_SEQ, C.FED_TAX_ID, C.LEGAL_NAME, C.DBA_NAME, C.NOTIFICATION_EMAIL, C.QUICKBOOKS_INFO_LICENSE_NUMBER as LICENSE_NUMBER, C.AGREE_INFO_SOURCE_ID as SOURCE_AGREEMENT_ID
                   FROM PSP_COMPANY c
                   JOIN PSP_COMPANY_SERVICE cs ON CS.COMPANY_FK = c.COMPANY_SEQ AND cs.SERVICE_FK = 'DirectDeposit'                   
                   JOIN PSP_ON_HOLD_REASON oh ON oh.COMPANY_FK = c.COMPANY_SEQ AND oh.EXPIRATION_DATE is null
              MINUS
              SELECT COMPANY_FK as COMPANY_SEQ, FED_TAX_ID, LEGAL_NAME, DBA_NAME, NOTIFICATION_EMAIL, LICENSE_NUMBER, SOURCE_AGREEMENT_ID
              FROM PSP_FRAUD_COMPANY
             );

INSERT INTO PSP_FRAUD_ADDRESS
            (FRAUD_ADDRESS_SEQ, COMPANY_FK, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, CITY, STATE, ZIP_CODE, VERSION, CREATED_DATE, MODIFIED_DATE, CREATOR_ID, MODIFIER_ID)  
     SELECT FN_FORMAT_SYSGUID(SYS_GUID()), COMPANY_SEQ, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, CITY, STATE, ZIP_CODE, 0, sysdate, sysdate, 'BatchJob', 'BatchJob'
       FROM (
       (
         SELECT COMPANY_SEQ, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, CITY, STATE, ZIP_CODE
           FROM PSP_COMPANY c
     INNER JOIN PSP_COMPANY_SERVICE cs ON CS.COMPANY_FK = c.COMPANY_SEQ AND cs.SERVICE_FK = 'DirectDeposit'
     INNER JOIN PSP_ADDRESS ca ON C.LEGAL_ADDRESS_FK = CA.ADDRESS_SEQ
     INNER JOIN PSP_ON_HOLD_REASON oh ON oh.COMPANY_FK = c.COMPANY_SEQ AND oh.EXPIRATION_DATE is null  
     UNION
         SELECT COMPANY_SEQ, ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, CITY, STATE, ZIP_CODE
           FROM PSP_COMPANY c
     INNER JOIN PSP_COMPANY_SERVICE cs ON CS.COMPANY_FK = c.COMPANY_SEQ AND cs.SERVICE_FK = 'DirectDeposit'           
     INNER JOIN PSP_ADDRESS ca ON C.MAILING_ADDRESS_FK = CA.ADDRESS_SEQ
     INNER JOIN PSP_ON_HOLD_REASON oh ON oh.COMPANY_FK = c.COMPANY_SEQ AND oh.EXPIRATION_DATE is null
      )
    MINUS
        SELECT COMPANY_FK,ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, CITY, STATE, ZIP_CODE
          FROM PSP_FRAUD_ADDRESS                          
    );
    
INSERT INTO PSP_FRAUD_CONTACT
            (FRAUD_CONTACT_SEQ, COMPANY_FK, FIRST_NAME, LAST_NAME, PHONE, EMAIL, VERSION, CREATED_DATE, MODIFIED_DATE, CREATOR_ID, MODIFIER_ID)
     SELECT FN_FORMAT_SYSGUID(SYS_GUID()), COMPANY_SEQ, FIRST_NAME, LAST_NAME, PHONE, EMAIL, 0, sysdate, sysdate, 'BatchJob', 'BatchJob'
       FROM (       
     SELECT DISTINCT C.COMPANY_SEQ, I.FIRST_NAME, I.LAST_NAME, I.PHONE, I.EMAIL
       FROM PSP_COMPANY c
 INNER JOIN PSP_COMPANY_SERVICE cs ON CS.COMPANY_FK = c.COMPANY_SEQ AND cs.SERVICE_FK = 'DirectDeposit'       
 INNER JOIN PSP_CONTACT cc ON C.COMPANY_SEQ = CC.COMPANY_FK
 INNER JOIN PSP_INDIVIDUAL i ON CC.CONTACT_SEQ = I.INDIVIDUAL_SEQ
 INNER JOIN PSP_ON_HOLD_REASON oh ON oh.COMPANY_FK = C.COMPANY_SEQ AND oh.EXPIRATION_DATE is null 
      MINUS
     SELECT COMPANY_FK as COMPANY_SEQ, FIRST_NAME, LAST_NAME, PHONE, EMAIL
       FROM PSP_FRAUD_CONTACT
       );

COMMIT;
