--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--
-- Please review the script before using it to make sure it won't
-- cause any unacceptable data loss.
--
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PSP_LOCAL 

Prompt Table PSP_FSET_FILE;
CREATE TABLE PSP_FSET_FILE
(
  FSET_FILE_SEQ          VARCHAR2(255 CHAR),
  VERSION                NUMBER(19),
  CREATOR_ID             VARCHAR2(30 CHAR),
  CREATED_DATE           TIMESTAMP(6),
  MODIFIER_ID            VARCHAR2(30 CHAR),
  MODIFIED_DATE          TIMESTAMP(6),
  REALM_ID               NUMBER(19)             DEFAULT -1,
  FILE_NAME              VARCHAR2(100 CHAR),
  FILE_TYPE              VARCHAR2(255 CHAR),
  STATUS_CD              VARCHAR2(255 CHAR),
  STATUS_EFFECTIVE_DATE  TIMESTAMP(6),
  TRANSMISSION_ID        VARCHAR2(50 CHAR),
  SUBMIT_DATE            TIMESTAMP(6)
)
NOPARALLEL;

ALTER TABLE PSP_FSET_FILE
 ADD PRIMARY KEY
  (FSET_FILE_SEQ, REALM_ID)
  USING INDEX;

Prompt Table PSP_FSET_FILING_DETAIL;
CREATE TABLE PSP_FSET_FILING_DETAIL
(
  FSET_FILING_DETAIL_SEQ         VARCHAR2(255 CHAR),
  VERSION                        NUMBER(19),
  CREATOR_ID                     VARCHAR2(30 CHAR),
  CREATED_DATE                   TIMESTAMP(6),
  MODIFIER_ID                    VARCHAR2(30 CHAR),
  MODIFIED_DATE                  TIMESTAMP(6),
  REALM_ID                       NUMBER(19)     DEFAULT -1,
  FED_TAX_ID                     VARCHAR2(80 CHAR),
  AGENCY_ID                      VARCHAR2(80 CHAR),
  FILING_DUE_DATE                TIMESTAMP(6),
  STATUS                         VARCHAR2(255 CHAR),
  BUSINESS_NAME                  VARCHAR2(100 CHAR),
  ADDRESS_LINE1                  VARCHAR2(80 CHAR),
  CITY                           VARCHAR2(256 CHAR),
  STATE                          VARCHAR2(21 CHAR),
  ZIP                            VARCHAR2(13 CHAR),
  FILING_AMOUNT                  NUMBER(19,4),
  SUBMISSION_ID                  VARCHAR2(50 CHAR),
  PERIOD_END_DATE                TIMESTAMP(6),
  ADDRESS_LINE2                  VARCHAR2(80 CHAR),
  FILING_STATUS_DATE             TIMESTAMP(6),
  ERROR_MESSAGE                  VARCHAR2(4000 CHAR),
  RESPONSE_FILE_FK               VARCHAR2(255 CHAR),
  PARENT_FILE_FK                 VARCHAR2(255 CHAR),
  MONEY_MOVEMENT_TRANSACTION_FK  VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_FSET_FILING_DETAIL_FK1;
CREATE INDEX PSP_FSET_FILING_DETAIL_FK1 ON PSP_FSET_FILING_DETAIL
(RESPONSE_FILE_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_FSET_FILING_DETAIL_FK2;
CREATE INDEX PSP_FSET_FILING_DETAIL_FK2 ON PSP_FSET_FILING_DETAIL
(PARENT_FILE_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_FSET_FILING_DETAIL_FK3;
CREATE INDEX PSP_FSET_FILING_DETAIL_FK3 ON PSP_FSET_FILING_DETAIL
(MONEY_MOVEMENT_TRANSACTION_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_FSET_FILING_DETAIL
 ADD PRIMARY KEY
  (FSET_FILING_DETAIL_SEQ, REALM_ID)
  USING INDEX;

ALTER TABLE PSP_FSET_FILING_DETAIL
 ADD CONSTRAINT PSP_FSET_FILING_DETAIL_FK1 
  FOREIGN KEY (RESPONSE_FILE_FK, REALM_ID) 
  REFERENCES PSP_FSET_FILE (FSET_FILE_SEQ,REALM_ID);

ALTER TABLE PSP_FSET_FILING_DETAIL
 ADD CONSTRAINT PSP_FSET_FILING_DETAIL_FK2 
  FOREIGN KEY (PARENT_FILE_FK, REALM_ID) 
  REFERENCES PSP_FSET_FILE (FSET_FILE_SEQ,REALM_ID);

ALTER TABLE PSP_FSET_FILING_DETAIL
 ADD CONSTRAINT PSP_FSET_FILING_DETAIL_FK3 
  FOREIGN KEY (MONEY_MOVEMENT_TRANSACTION_FK, REALM_ID) 
  REFERENCES PSP_MONEY_MOVEMENT_TRANSACTION (MONEY_MOVEMENT_TRANSACTION_SEQ,REALM_ID);

PROMPT finishedDBUpgrade_002.001.001.020.sql