--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--
-- Please review the script before using it to make sure it won't
-- cause any unacceptable data loss.
--
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PSP_LOCAL 

Prompt Column SUPER_CHECK;
ALTER TABLE PSP_AGENCY_CHECK_BATCH
 ADD (SUPER_CHECK  NUMBER(1));

Prompt Column AGENCY_CHECK_BATCH_FK;
ALTER TABLE PSP_VOIDED_CHECK
 ADD (AGENCY_CHECK_BATCH_FK  VARCHAR2(255 CHAR));

Prompt Index PSP_VOIDED_CHECK_FK3;
CREATE INDEX PSP_VOIDED_CHECK_FK3 ON PSP_VOIDED_CHECK
(AGENCY_CHECK_BATCH_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_VOIDED_CHECK
 ADD CONSTRAINT PSP_VOIDED_CHECK_FK3 
  FOREIGN KEY (AGENCY_CHECK_BATCH_FK, REALM_ID) 
  REFERENCES PSP_AGENCY_CHECK_BATCH (AGENCY_CHECK_BATCH_SEQ,REALM_ID);

ALTER TABLE PSP_VOIDED_CHECK
 MODIFY (MONEY_MOVEMENT_TRANSACTION_FK NULL);

PROMPT finishedDBUpgrade_002.000.013.004.sql