--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--
-- Please review the script before using it to make sure it won't
-- cause any unacceptable data loss.
--
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PSP_LOCAL 

Prompt Column FEIN_ENC;
ALTER TABLE PSP_COMPANY_CONSENT
 ADD (FEIN_ENC  VARCHAR2(4000 CHAR));

Prompt Column PERSONA_ID;
ALTER TABLE PSP_EMPLOYEE
 ADD (PERSONA_ID  VARCHAR2(4000 CHAR));

Prompt Table PSP_VMP_EMPLOYEE_INFO;
CREATE TABLE PSP_VMP_EMPLOYEE_INFO
(
  VMP_EMPLOYEE_INFO_SEQ  VARCHAR2(255 CHAR)     NOT NULL,
  VERSION                NUMBER(19)             NOT NULL,
  CREATOR_ID             VARCHAR2(30 CHAR),
  CREATED_DATE           TIMESTAMP(6)           NOT NULL,
  MODIFIER_ID            VARCHAR2(30 CHAR),
  MODIFIED_DATE          TIMESTAMP(6)           NOT NULL,
  REALM_ID               NUMBER(19)             DEFAULT -1                    NOT NULL,
  CONSUMER_REALM_ID      VARCHAR2(4000 CHAR),
  EMPLOYEE_RECNUM        VARCHAR2(4000 CHAR),
  EMAIL                  VARCHAR2(4000 CHAR),
  PERSONA_ID             VARCHAR2(4000 CHAR),
  COMPANY_FK             VARCHAR2(255 CHAR)     NOT NULL
)
NOPARALLEL;

Prompt Index PSP_VMP_EMPLOYEE_INFO_FK1;
CREATE INDEX PSP_VMP_EMPLOYEE_INFO_FK1 ON PSP_VMP_EMPLOYEE_INFO
(COMPANY_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_VMP_EMPLOYEE_INFO
 ADD PRIMARY KEY
  (VMP_EMPLOYEE_INFO_SEQ, REALM_ID)
  USING INDEX;

ALTER TABLE PSP_VMP_EMPLOYEE_INFO
 ADD CONSTRAINT PSP_VMP_EMPLOYEE_INFO_FK1 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);
