--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--                                                                      --
-- Please review the script before using it to make sure it won't       --
-- cause any unacceptable data loss.                                    --
--                                                                      --
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
Prompt DROP TABLE PSP_DEPOSIT_FREQUENCY_CODE;
ALTER TABLE PSP_DEPOSIT_FREQUENCY_CODE
 DROP PRIMARY KEY CASCADE;
DROP TABLE PSP_DEPOSIT_FREQUENCY_CODE CASCADE CONSTRAINTS;

Prompt TABLE PSP_QBDT_TRANSACTION_INFO;
--
-- PSP_QBDT_TRANSACTION_INFO  (Table) 
--
CREATE TABLE PSP_QBDT_TRANSACTION_INFO
(
  QBDT_TRANSACTION_INFO_SEQ  VARCHAR2(255 CHAR) NOT NULL,
  VERSION                    NUMBER(19)         NOT NULL,
  CREATOR_ID                 VARCHAR2(30 CHAR),
  CREATED_DATE               TIMESTAMP(6)       NOT NULL,
  MODIFIER_ID                VARCHAR2(30 CHAR),
  MODIFIED_DATE              TIMESTAMP(6)       NOT NULL,
  REALM_ID                   NUMBER(19)         DEFAULT -1                    NOT NULL,
  AGENCY_NAME                VARCHAR2(128 CHAR),
  REFERENCE_NUMBER           VARCHAR2(11 CHAR),
  ACCOUNT_NAME               VARCHAR2(128 CHAR),
  MEMO                       VARCHAR2(4000 CHAR),
  ON_SERVICE                 NUMBER(1),
  CLEARED                    VARCHAR2(1 CHAR),
  TRACKING_CLASS             VARCHAR2(128 CHAR),
  IS_DELETED                 NUMBER(1)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

Prompt TABLE PSP_QBDT_PAYROLL_ITEM_INFO;
--
-- PSP_QBDT_PAYROLL_ITEM_INFO  (Table) 
--
CREATE TABLE PSP_QBDT_PAYROLL_ITEM_INFO
(
  QBDT_PAYROLL_ITEM_INFO_SEQ  VARCHAR2(255 CHAR) NOT NULL,
  VERSION                     NUMBER(19)        NOT NULL,
  CREATOR_ID                  VARCHAR2(30 CHAR),
  CREATED_DATE                TIMESTAMP(6)      NOT NULL,
  MODIFIER_ID                 VARCHAR2(30 CHAR),
  MODIFIED_DATE               TIMESTAMP(6)      NOT NULL,
  REALM_ID                    NUMBER(19)        DEFAULT -1                    NOT NULL,
  EARNINGS_TABLE              NUMBER(1),
  IS_EMPLOYEE_PAID            NUMBER(1),
  LIABILITY_ACCOUNT           VARCHAR2(255 CHAR),
  LIABILITY_AGENCY            VARCHAR2(255 CHAR),
  AGENCY_ID                   VARCHAR2(24 CHAR),
  ADJUSTS_GROSS               NUMBER(1),
  BASED_ON_QUANTITY           NUMBER(1),
  EXPENSE_ACCOUNT             VARCHAR2(255 CHAR),
  DEFAULT_RATE                NUMBER(19,7),
  DEFAULT_LIMIT               NUMBER(19,4),
  EXPENSE_BY_JOB              NUMBER(1),
  PAY_TYPE                    VARCHAR2(255 CHAR),
  SPECIAL_TYPE                VARCHAR2(255 CHAR),
  IS_DELETED                  NUMBER(1),
  ON_SERVICE                  NUMBER(1),
  DEFAULT_RATE_TYPE           VARCHAR2(255 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

Prompt TABLE PSP_QBDT_PAYLINE_INFO;
--
-- PSP_QBDT_PAYLINE_INFO  (Table) 
--
CREATE TABLE PSP_QBDT_PAYLINE_INFO
(
  QBDT_PAYLINE_INFO_SEQ  VARCHAR2(255 CHAR)     NOT NULL,
  VERSION                NUMBER(19)             NOT NULL,
  CREATOR_ID             VARCHAR2(30 CHAR),
  CREATED_DATE           TIMESTAMP(6)           NOT NULL,
  MODIFIER_ID            VARCHAR2(30 CHAR),
  MODIFIED_DATE          TIMESTAMP(6)           NOT NULL,
  REALM_ID               NUMBER(19)             DEFAULT -1                    NOT NULL,
  RATE                   NUMBER(19,7),
  TRACKING_CLASS         VARCHAR2(128 CHAR),
  JOB                    VARCHAR2(128 CHAR),
  ITEM                   VARCHAR2(128 CHAR),
  WC_CODE                VARCHAR2(20 CHAR),
  QUANTITY               NUMBER(19,7),
  EXPENSE_BY_JOB         NUMBER(1),
  RATE_TYPE              VARCHAR2(255 CHAR),
  QUANTITY_TYPE          VARCHAR2(255 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

Prompt TABLE PSP_QBDT_PAYCHECK_INFO;
--
-- PSP_QBDT_PAYCHECK_INFO  (Table) 
--
CREATE TABLE PSP_QBDT_PAYCHECK_INFO
(
  QBDT_PAYCHECK_INFO_SEQ  VARCHAR2(255 CHAR)    NOT NULL,
  VERSION                 NUMBER(19)            NOT NULL,
  CREATOR_ID              VARCHAR2(30 CHAR),
  CREATED_DATE            TIMESTAMP(6)          NOT NULL,
  MODIFIER_ID             VARCHAR2(30 CHAR),
  MODIFIED_DATE           TIMESTAMP(6)          NOT NULL,
  REALM_ID                NUMBER(19)            DEFAULT -1                    NOT NULL,
  PRORATE                 NUMBER(1),
  CHECK_NUMBER            VARCHAR2(11 CHAR),
  MEMO                    VARCHAR2(4000 CHAR),
  CLEARED                 VARCHAR2(1 CHAR),
  ON_SERVICE              NUMBER(1),
  TRACKING_CLASS          VARCHAR2(128 CHAR),
  ACCOUNT_NAME            VARCHAR2(128 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

Prompt TABLE PSP_QBDT_EMPLOYEE_INFO;
--
-- PSP_QBDT_EMPLOYEE_INFO  (Table) 
--
CREATE TABLE PSP_QBDT_EMPLOYEE_INFO
(
  QBDT_EMPLOYEE_INFO_SEQ  VARCHAR2(255 CHAR)    NOT NULL,
  VERSION                 NUMBER(19)            NOT NULL,
  CREATOR_ID              VARCHAR2(30 CHAR),
  CREATED_DATE            TIMESTAMP(6)          NOT NULL,
  MODIFIER_ID             VARCHAR2(30 CHAR),
  MODIFIED_DATE           TIMESTAMP(6)          NOT NULL,
  REALM_ID                NUMBER(19)            DEFAULT -1                    NOT NULL,
  BILL_PAY_ACCOUNT        VARCHAR2(64 CHAR),
  INITIALS                VARCHAR2(12 CHAR),
  TRACKING_CLASS          VARCHAR2(128 CHAR),
  USE_TIME                NUMBER(1),
  ENFORCE_SUBJECT_TO      NUMBER(1),
  EMPLOYEE_TYPE           VARCHAR2(255 CHAR),
  IS_DELETED              NUMBER(1),
  TITLE                   VARCHAR2(20 CHAR),
  ALT_PHONE               VARCHAR2(21 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

Prompt TABLE PSP_SOURCE_SYSTEM_LAW_ASSOC;
--
-- PSP_SOURCE_SYSTEM_LAW_ASSOC  (Table) 
--
CREATE TABLE PSP_SOURCE_SYSTEM_LAW_ASSOC
(
  SOURCE_SYSTEM_LAW_ASSOC_SEQ  VARCHAR2(255 CHAR) NOT NULL,
  VERSION                      NUMBER(19)       NOT NULL,
  CREATOR_ID                   VARCHAR2(30 CHAR),
  CREATED_DATE                 TIMESTAMP(6)     NOT NULL,
  MODIFIER_ID                  VARCHAR2(30 CHAR),
  MODIFIED_DATE                TIMESTAMP(6)     NOT NULL,
  REALM_ID                     NUMBER(19)       DEFAULT -1                    NOT NULL,
  SOURCE_LAW_CODE              VARCHAR2(80 CHAR),
  LAW_FK                       VARCHAR2(255 CHAR) NOT NULL,
  SOURCE_SYSTEM_FK             VARCHAR2(255 CHAR) NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


Prompt TABLE PSP_DEPOSIT_FREQUENCY;
--
-- PSP_DEPOSIT_FREQUENCY  (Table) 
--
CREATE TABLE PSP_DEPOSIT_FREQUENCY
(
  DEPOSIT_FREQUENCY_CODE   VARCHAR2(255 CHAR)   NOT NULL,
  VERSION                  NUMBER(19)           NOT NULL,
  REALM_ID                 NUMBER(19)           DEFAULT -1                    NOT NULL,
  A_T_F_DEPOSIT_FREQ_CODE  VARCHAR2(50 CHAR),
  DESCRIPTION              VARCHAR2(100 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

Prompt COLUMN AGENCY_SUPPORT_START_DATE;
ALTER TABLE PSP_AGENCY
 ADD (AGENCY_SUPPORT_START_DATE  TIMESTAMP(6));

Prompt COLUMN NO_CALCULATION;
ALTER TABLE PSP_AGENCY
 ADD (NO_CALCULATION  NUMBER(1));

Prompt COLUMN NO_CALCULATION;
ALTER TABLE PSP_PAYMENT_TEMPLATE
 ADD (NO_CALCULATION  NUMBER(1));


Prompt COLUMN STATUS;
ALTER TABLE PSP_COMPANY_PAYROLL_ITEM
 ADD (STATUS  VARCHAR2(255 CHAR));

Prompt COLUMN TAX_FORM_LINE;
ALTER TABLE PSP_COMPANY_PAYROLL_ITEM
 ADD (TAX_FORM_LINE  VARCHAR2(255 CHAR));

Prompt COLUMN QBDT_PAYROLL_ITEM_INFO_FK;
ALTER TABLE PSP_COMPANY_PAYROLL_ITEM
 ADD (QBDT_PAYROLL_ITEM_INFO_FK  VARCHAR2(255 CHAR));

Prompt COLUMN SOURCE_ID;
ALTER TABLE PSP_COMP_ADJUST_SUBMISSION
 ADD (SOURCE_ID  VARCHAR2(9 CHAR));

Prompt COLUMN AMOUNT;
ALTER TABLE PSP_COMP_ADJUST_SUBMISSION
 ADD (AMOUNT  NUMBER(19,4));

Prompt COLUMN IS_VOID;
ALTER TABLE PSP_COMP_ADJUST_SUBMISSION
 ADD (IS_VOID  NUMBER(1));

Prompt COLUMN QBDT_TRANSACTION_INFO_FK;
ALTER TABLE PSP_COMP_ADJUST_SUBMISSION
 ADD (QBDT_TRANSACTION_INFO_FK  VARCHAR2(255 CHAR));




Prompt TABLE PSP_QBDT_UNPROCESSED_REQUEST;
--
-- PSP_QBDT_UNPROCESSED_REQUEST  (Table) 
--
CREATE TABLE PSP_QBDT_UNPROCESSED_REQUEST
(
  QBDT_UNPROCESSED_REQUEST_SEQ   VARCHAR2(255 CHAR) NOT NULL,
  VERSION                        NUMBER(19)     NOT NULL,
  CREATOR_ID                     VARCHAR2(30 CHAR),
  CREATED_DATE                   TIMESTAMP(6)   NOT NULL,
  MODIFIER_ID                    VARCHAR2(30 CHAR),
  MODIFIED_DATE                  TIMESTAMP(6)   NOT NULL,
  REALM_ID                       NUMBER(19)     DEFAULT -1                    NOT NULL,
  STATUS                         VARCHAR2(255 CHAR),
  ERROR_MESSAGE                  VARCHAR2(4000 CHAR),
  SOURCE_SYSTEM_TRANSMISSION_FK  VARCHAR2(255 CHAR) NOT NULL,
  COMPANY_FK                     VARCHAR2(255 CHAR) NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

Prompt TABLE PSP_LIABILITY_CHECK;
--
-- PSP_LIABILITY_CHECK  (Table) 
--
CREATE TABLE PSP_LIABILITY_CHECK
(
  LIABILITY_CHECK_SEQ       VARCHAR2(255 CHAR)  NOT NULL,
  VERSION                   NUMBER(19)          NOT NULL,
  CREATOR_ID                VARCHAR2(30 CHAR),
  CREATED_DATE              TIMESTAMP(6)        NOT NULL,
  MODIFIER_ID               VARCHAR2(30 CHAR),
  MODIFIED_DATE             TIMESTAMP(6)        NOT NULL,
  REALM_ID                  NUMBER(19)          DEFAULT -1                    NOT NULL,
  AMOUNT                    NUMBER(19,4),
  PERIOD_END_DATE           TIMESTAMP(6),
  IS_VOID                   NUMBER(1),
  IS_REFUND                 NUMBER(1),
  SOURCE_ID                 VARCHAR2(9 CHAR),
  TRANSACTION_DATE          TIMESTAMP(6),
  COMPANY_FK                VARCHAR2(255 CHAR)  NOT NULL,
  QBDT_TRANSACTION_INFO_FK  VARCHAR2(255 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

Prompt COLUMN PAYMENT_FREQUENCY_ID;
ALTER TABLE PSP_PMT_TEMPLATE_FREQUENCY
MODIFY(PAYMENT_FREQUENCY_ID VARCHAR2(255 CHAR));


Prompt COLUMN SOURCE_ID;
ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 ADD (SOURCE_ID  VARCHAR2(9 CHAR));

Prompt COLUMN QBDT_TRANSACTION_INFO_FK;
ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 ADD (QBDT_TRANSACTION_INFO_FK  VARCHAR2(255 CHAR));

Prompt COLUMN IS_DECEASED;
ALTER TABLE PSP_EMPLOYEE
 ADD (IS_DECEASED  NUMBER(1));

Prompt COLUMN QUALIFIES_FOR_AEIC;
ALTER TABLE PSP_EMPLOYEE
 ADD (QUALIFIES_FOR_AEIC  NUMBER(1));

Prompt COLUMN FED_EXTRA_WITHHOLDING;
ALTER TABLE PSP_EMPLOYEE
 ADD (FED_EXTRA_WITHHOLDING  NUMBER(19,4));

Prompt COLUMN LIVE_STATE;
ALTER TABLE PSP_EMPLOYEE
 ADD (LIVE_STATE  VARCHAR2(21 CHAR));

Prompt COLUMN PAY_PERIOD;
ALTER TABLE PSP_EMPLOYEE
 ADD (PAY_PERIOD  VARCHAR2(255 CHAR));

Prompt COLUMN QBDT_EMPLOYEE_INFO_FK;
ALTER TABLE PSP_EMPLOYEE
 ADD (QBDT_EMPLOYEE_INFO_FK  VARCHAR2(255 CHAR));

Prompt COLUMN DESCRIPTION;
ALTER TABLE PSP_EMPLOYEE_WAGE_PLAN
 ADD (DESCRIPTION  VARCHAR2(100 CHAR));

Prompt COLUMN RULES_VERSION;
ALTER TABLE PSP_EMPLOYEE_WAGE_PLAN
 ADD (RULES_VERSION  VARCHAR2(10 CHAR));

Prompt TABLE PSP_EMPLOYEE_PAYROLL_ITEM;
--
-- PSP_EMPLOYEE_PAYROLL_ITEM  (Table) 
--
CREATE TABLE PSP_EMPLOYEE_PAYROLL_ITEM
(
  EMPLOYEE_PAYROLL_ITEM_SEQ  VARCHAR2(255 CHAR) NOT NULL,
  VERSION                    NUMBER(19)         NOT NULL,
  CREATOR_ID                 VARCHAR2(30 CHAR),
  CREATED_DATE               TIMESTAMP(6)       NOT NULL,
  MODIFIER_ID                VARCHAR2(30 CHAR),
  MODIFIED_DATE              TIMESTAMP(6)       NOT NULL,
  REALM_ID                   NUMBER(19)         DEFAULT -1                    NOT NULL,
  AMOUNT                     NUMBER(19,7),
  LIMIT                      NUMBER(19,7),
  TYPE                       VARCHAR2(255 CHAR),
  AMOUNT_TYPE                VARCHAR2(255 CHAR),
  LIMIT_TYPE                 VARCHAR2(255 CHAR),
  COMPANY_PAYROLL_ITEM_FK    VARCHAR2(255 CHAR) NOT NULL,
  EMPLOYEE_FK                VARCHAR2(255 CHAR) NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

Prompt TABLE PSP_EMPLOYEE_CUSTOM_FIELD;
--
-- PSP_EMPLOYEE_CUSTOM_FIELD  (Table) 
--
CREATE TABLE PSP_EMPLOYEE_CUSTOM_FIELD
(
  EMPLOYEE_CUSTOM_FIELD_SEQ  VARCHAR2(255 CHAR) NOT NULL,
  VERSION                    NUMBER(19)         NOT NULL,
  CREATOR_ID                 VARCHAR2(30 CHAR),
  CREATED_DATE               TIMESTAMP(6)       NOT NULL,
  MODIFIER_ID                VARCHAR2(30 CHAR),
  MODIFIED_DATE              TIMESTAMP(6)       NOT NULL,
  REALM_ID                   NUMBER(19)         DEFAULT -1                    NOT NULL,
  NAME                       VARCHAR2(128 CHAR),
  VALUE                      VARCHAR2(128 CHAR),
  EMPLOYEE_FK                VARCHAR2(255 CHAR) NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

Prompt TABLE PSP_EMPLOYEE_ACCRUAL;
--
-- PSP_EMPLOYEE_ACCRUAL  (Table) 
--
CREATE TABLE PSP_EMPLOYEE_ACCRUAL
(
  EMPLOYEE_ACCRUAL_SEQ  VARCHAR2(255 CHAR)      NOT NULL,
  VERSION               NUMBER(19)              NOT NULL,
  CREATOR_ID            VARCHAR2(30 CHAR),
  CREATED_DATE          TIMESTAMP(6)            NOT NULL,
  MODIFIER_ID           VARCHAR2(30 CHAR),
  MODIFIED_DATE         TIMESTAMP(6)            NOT NULL,
  REALM_ID              NUMBER(19)              DEFAULT -1                    NOT NULL,
  ACCRUAL_PERIOD        VARCHAR2(255 CHAR),
  HOURS_PER_PERIOD      NUMBER(19,7),
  HOURS                 NUMBER(19,7),
  MAX_HOURS             NUMBER(19,7),
  NEW_YEAR_RESET        NUMBER(1),
  ACCRUAL_TYPE          VARCHAR2(255 CHAR),
  EMPLOYEE_FK           VARCHAR2(255 CHAR)      NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

Prompt COLUMN EXEMPTION_STATUS;
ALTER TABLE PSP_COMPANY_LAW
 ADD (EXEMPTION_STATUS  VARCHAR2(255 CHAR));

Prompt COLUMN TAX_FORM_LINE;
ALTER TABLE PSP_COMPANY_LAW
 ADD (TAX_FORM_LINE  VARCHAR2(255 CHAR));

Prompt COLUMN SOURCE_DESCRIPTION;
ALTER TABLE PSP_COMPANY_LAW
 ADD (SOURCE_DESCRIPTION  VARCHAR2(50 CHAR));

Prompt COLUMN SOURCE_ID;
ALTER TABLE PSP_COMPANY_LAW
 ADD (SOURCE_ID  VARCHAR2(5 CHAR));

Prompt COLUMN QBDT_PAYROLL_ITEM_INFO_FK;
ALTER TABLE PSP_COMPANY_LAW
 ADD (QBDT_PAYROLL_ITEM_INFO_FK  VARCHAR2(255 CHAR));





Prompt TABLE PSP_QBDT_PROCESSED_PAYROLL;
--
-- PSP_QBDT_PROCESSED_PAYROLL  (Table) 
--
CREATE TABLE PSP_QBDT_PROCESSED_PAYROLL
(
  QBDT_PROCESSED_PAYROLL_SEQ  VARCHAR2(255 CHAR) NOT NULL,
  VERSION                     NUMBER(19)        NOT NULL,
  CREATOR_ID                  VARCHAR2(30 CHAR),
  CREATED_DATE                TIMESTAMP(6)      NOT NULL,
  MODIFIER_ID                 VARCHAR2(30 CHAR),
  MODIFIED_DATE               TIMESTAMP(6)      NOT NULL,
  REALM_ID                    NUMBER(19)        DEFAULT -1                    NOT NULL,
  IS_PROCESSED                NUMBER(1),
  PAYROLL_RUN_FK              VARCHAR2(255 CHAR) NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

Prompt TABLE PSP_PAYROLL_ITEM_TAXABLE_TO;
--
-- PSP_PAYROLL_ITEM_TAXABLE_TO  (Table) 
--
CREATE TABLE PSP_PAYROLL_ITEM_TAXABLE_TO
(
  PAYROLL_ITEM_TAXABLE_TO_SEQ  VARCHAR2(255 CHAR) NOT NULL,
  VERSION                      NUMBER(19)       NOT NULL,
  CREATOR_ID                   VARCHAR2(30 CHAR),
  CREATED_DATE                 TIMESTAMP(6)     NOT NULL,
  MODIFIER_ID                  VARCHAR2(30 CHAR),
  MODIFIED_DATE                TIMESTAMP(6)     NOT NULL,
  REALM_ID                     NUMBER(19)       DEFAULT -1                    NOT NULL,
  COMPANY_LAW_FK               VARCHAR2(255 CHAR) NOT NULL,
  COMPANY_PAYROLL_ITEM_FK      VARCHAR2(255 CHAR) NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

Prompt TABLE PSP_LIABILITY_CHECK_LINE;
--
-- PSP_LIABILITY_CHECK_LINE  (Table) 
--
CREATE TABLE PSP_LIABILITY_CHECK_LINE
(
  LIABILITY_CHECK_LINE_SEQ  VARCHAR2(255 CHAR)  NOT NULL,
  VERSION                   NUMBER(19)          NOT NULL,
  CREATOR_ID                VARCHAR2(30 CHAR),
  CREATED_DATE              TIMESTAMP(6)        NOT NULL,
  MODIFIER_ID               VARCHAR2(30 CHAR),
  MODIFIED_DATE             TIMESTAMP(6)        NOT NULL,
  REALM_ID                  NUMBER(19)          DEFAULT -1                    NOT NULL,
  AMOUNT                    NUMBER(19,4),
  COMPANY_PAYROLL_ITEM_FK   VARCHAR2(255 CHAR)  NOT NULL,
  LIABILITY_CHECK_FK        VARCHAR2(255 CHAR)  NOT NULL,
  QBDT_TRANSACTION_INFO_FK  VARCHAR2(255 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

Prompt COLUMN TAXABLE_WAGES;
ALTER TABLE PSP_LIABILITY_ADJUSTMENT
 ADD (TAXABLE_WAGES  NUMBER(19,4));

Prompt COLUMN TOTAL_WAGES;
ALTER TABLE PSP_LIABILITY_ADJUSTMENT
 ADD (TOTAL_WAGES  NUMBER(19,4));

Prompt COLUMN QBDT_TRANSACTION_INFO_FK;
ALTER TABLE PSP_LIABILITY_ADJUSTMENT
 ADD (QBDT_TRANSACTION_INFO_FK  VARCHAR2(255 CHAR));

Prompt COLUMN IS_Y_T_D_ADJUSTMENT;
ALTER TABLE PSP_PAYCHECK
 ADD (IS_Y_T_D_ADJUSTMENT  NUMBER(1));

Prompt COLUMN QBDT_PAYCHECK_INFO_FK;
ALTER TABLE PSP_PAYCHECK
 ADD (QBDT_PAYCHECK_INFO_FK  VARCHAR2(255 CHAR));

Prompt COLUMN AMOUNT;
ALTER TABLE PSP_EMPLOYEE_BANK_ACCOUNT
 ADD (AMOUNT  NUMBER(19,7));

Prompt COLUMN AMOUNT_TYPE;
ALTER TABLE PSP_EMPLOYEE_BANK_ACCOUNT
 ADD (AMOUNT_TYPE  VARCHAR2(255 CHAR));

Prompt COLUMN QBDT_PAYLINE_INFO_FK;
ALTER TABLE PSP_DEDUCTION
 ADD (QBDT_PAYLINE_INFO_FK  VARCHAR2(255 CHAR));

Prompt COLUMN QBDT_PAYLINE_INFO_FK;
ALTER TABLE PSP_COMPENSATION
 ADD (QBDT_PAYLINE_INFO_FK  VARCHAR2(255 CHAR));

Prompt COLUMN QBDT_PAYLINE_INFO_FK;
ALTER TABLE PSP_EMPLOYER_CONTRIBUTION
 ADD (QBDT_PAYLINE_INFO_FK  VARCHAR2(255 CHAR));

Prompt TABLE PSP_EMPLOYEE_TAX;
--
-- PSP_EMPLOYEE_TAX  (Table) 
--
CREATE TABLE PSP_EMPLOYEE_TAX
(
  EMPLOYEE_TAX_SEQ   VARCHAR2(255 CHAR)         NOT NULL,
  VERSION            NUMBER(19)                 NOT NULL,
  CREATOR_ID         VARCHAR2(30 CHAR),
  CREATED_DATE       TIMESTAMP(6)               NOT NULL,
  MODIFIER_ID        VARCHAR2(30 CHAR),
  MODIFIED_DATE      TIMESTAMP(6)               NOT NULL,
  REALM_ID           NUMBER(19)                 DEFAULT -1                    NOT NULL,
  TAX_LAW_VERSION    VARCHAR2(20 CHAR),
  W2_NAME            VARCHAR2(41 CHAR),
  STATE              VARCHAR2(2 CHAR),
  SUBJECT_TO         NUMBER(1),
  TAX_TYPE           VARCHAR2(255 CHAR),
  FILING_STATUS      VARCHAR2(50 CHAR),
  ALLOWANCES         NUMBER(10),
  EXTRA_WITHHOLDING  NUMBER(19,4),
  COMPANY_LAW_FK     VARCHAR2(255 CHAR),
  EMPLOYEE_FK        VARCHAR2(255 CHAR)         NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

Prompt TABLE PSP_COMPANY_LAW_RATE;
--
-- PSP_COMPANY_LAW_RATE  (Table) 
--
CREATE TABLE PSP_COMPANY_LAW_RATE
(
  COMPANY_LAW_RATE_SEQ  VARCHAR2(255 CHAR)      NOT NULL,
  VERSION               NUMBER(19)              NOT NULL,
  CREATOR_ID            VARCHAR2(30 CHAR),
  CREATED_DATE          TIMESTAMP(6)            NOT NULL,
  MODIFIER_ID           VARCHAR2(30 CHAR),
  MODIFIED_DATE         TIMESTAMP(6)            NOT NULL,
  REALM_ID              NUMBER(19)              DEFAULT -1                    NOT NULL,
  EFFECTIVE_DATE        TIMESTAMP(6),
  EXPIRATION_DATE       TIMESTAMP(6),
  RATE                  NUMBER(19,7),
  COMPANY_LAW_FK        VARCHAR2(255 CHAR)      NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


Prompt TABLE PSP_PAYCHECK_ACCRUAL;
--
-- PSP_PAYCHECK_ACCRUAL  (Table) 
--
CREATE TABLE PSP_PAYCHECK_ACCRUAL
(
  PAYCHECK_ACCRUAL_SEQ  VARCHAR2(255 CHAR)      NOT NULL,
  VERSION               NUMBER(19)              NOT NULL,
  CREATOR_ID            VARCHAR2(30 CHAR),
  CREATED_DATE          TIMESTAMP(6)            NOT NULL,
  MODIFIER_ID           VARCHAR2(30 CHAR),
  MODIFIED_DATE         TIMESTAMP(6)            NOT NULL,
  REALM_ID              NUMBER(19)              DEFAULT -1                    NOT NULL,
  HOURS_ACCRUED         NUMBER(19,7),
  EMPLOYEE_ACCRUAL_FK   VARCHAR2(255 CHAR)      NOT NULL,
  PAYCHECK_FK           VARCHAR2(255 CHAR)      NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

Prompt COLUMN TIPS_TAXABLE_WAGE_AMOUNT;
ALTER TABLE PSP_TAX
 ADD (TIPS_TAXABLE_WAGE_AMOUNT  NUMBER(19,4));

Prompt COLUMN COMPANY_LAW_FK;
ALTER TABLE PSP_TAX
 ADD (COMPANY_LAW_FK  VARCHAR2(255 CHAR));

Prompt COLUMN QBDT_TRANSACTION_INFO_FK;
ALTER TABLE PSP_FINANCIAL_TRANSACTION
 ADD (QBDT_TRANSACTION_INFO_FK  VARCHAR2(255 CHAR));

Prompt TABLE PSP_TAX_TABLE_MISC_DATA;
--
-- PSP_TAX_TABLE_MISC_DATA  (Table) 
--
CREATE TABLE PSP_TAX_TABLE_MISC_DATA
(
  TAX_TABLE_MISC_DATA_SEQ  VARCHAR2(255 CHAR)   NOT NULL,
  VERSION                  NUMBER(19)           NOT NULL,
  CREATOR_ID               VARCHAR2(30 CHAR),
  CREATED_DATE             TIMESTAMP(6)         NOT NULL,
  MODIFIER_ID              VARCHAR2(30 CHAR),
  MODIFIED_DATE            TIMESTAMP(6)         NOT NULL,
  REALM_ID                 NUMBER(19)           DEFAULT -1                    NOT NULL,
  VALUE                    VARCHAR2(56 CHAR),
  EMPLOYEE_TAX_FK          VARCHAR2(255 CHAR)   NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;



ALTER TABLE PSP_QBDT_TRANSACTION_INFO
 ADD PRIMARY KEY
 (QBDT_TRANSACTION_INFO_SEQ, REALM_ID);

ALTER TABLE PSP_QBDT_PAYROLL_ITEM_INFO
 ADD PRIMARY KEY
 (QBDT_PAYROLL_ITEM_INFO_SEQ, REALM_ID);

ALTER TABLE PSP_QBDT_PAYLINE_INFO
 ADD PRIMARY KEY
 (QBDT_PAYLINE_INFO_SEQ, REALM_ID);

ALTER TABLE PSP_QBDT_PAYCHECK_INFO
 ADD PRIMARY KEY
 (QBDT_PAYCHECK_INFO_SEQ, REALM_ID);

ALTER TABLE PSP_QBDT_EMPLOYEE_INFO
 ADD PRIMARY KEY
 (QBDT_EMPLOYEE_INFO_SEQ, REALM_ID);

ALTER TABLE PSP_DEPOSIT_FREQUENCY
 ADD PRIMARY KEY
 (DEPOSIT_FREQUENCY_CODE, REALM_ID);

ALTER TABLE PSP_SOURCE_SYSTEM_LAW_ASSOC
 ADD PRIMARY KEY
 (SOURCE_SYSTEM_LAW_ASSOC_SEQ, REALM_ID);

ALTER TABLE PSP_QBDT_UNPROCESSED_REQUEST
 ADD PRIMARY KEY
 (QBDT_UNPROCESSED_REQUEST_SEQ, REALM_ID);
 
ALTER TABLE PSP_LIABILITY_CHECK
 ADD PRIMARY KEY
 (LIABILITY_CHECK_SEQ, REALM_ID);

ALTER TABLE PSP_EMPLOYEE_PAYROLL_ITEM
 ADD PRIMARY KEY
 (EMPLOYEE_PAYROLL_ITEM_SEQ, REALM_ID);
 
ALTER TABLE PSP_EMPLOYEE_CUSTOM_FIELD
 ADD PRIMARY KEY
 (EMPLOYEE_CUSTOM_FIELD_SEQ, REALM_ID);

ALTER TABLE PSP_EMPLOYEE_ACCRUAL
 ADD PRIMARY KEY
 (EMPLOYEE_ACCRUAL_SEQ, REALM_ID);

ALTER TABLE PSP_QBDT_PROCESSED_PAYROLL
 ADD PRIMARY KEY
 (QBDT_PROCESSED_PAYROLL_SEQ, REALM_ID);

ALTER TABLE PSP_PAYROLL_ITEM_TAXABLE_TO
 ADD PRIMARY KEY
 (PAYROLL_ITEM_TAXABLE_TO_SEQ, REALM_ID);

ALTER TABLE PSP_LIABILITY_CHECK_LINE
 ADD PRIMARY KEY
 (LIABILITY_CHECK_LINE_SEQ, REALM_ID);

ALTER TABLE PSP_EMPLOYEE_TAX
 ADD PRIMARY KEY
 (EMPLOYEE_TAX_SEQ, REALM_ID);

ALTER TABLE PSP_COMPANY_LAW_RATE
 ADD PRIMARY KEY
 (COMPANY_LAW_RATE_SEQ, REALM_ID);

ALTER TABLE PSP_PAYCHECK_ACCRUAL
 ADD PRIMARY KEY
 (PAYCHECK_ACCRUAL_SEQ, REALM_ID);

ALTER TABLE PSP_TAX_TABLE_MISC_DATA
 ADD PRIMARY KEY
 (TAX_TABLE_MISC_DATA_SEQ, REALM_ID);













 

PROMPT finishedDBUpgrade_002.000.000.062.sql