--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--                                                                      --
-- Please review the script before using it to make sure it won't       --
-- cause any unacceptable data loss.                                    --
--                                                                      --
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
/* 
Prompt TABLE PSP_EVENT_AS400_SYNC;
--
-- PSP_EVENT_AS400_SYNC  (Table) 
--
CREATE TABLE PSP_EVENT_AS400_SYNC
(
  EVENT_AS400_SYNC_SEQ  VARCHAR2(255 CHAR)      NOT NULL,
  VERSION               NUMBER(19)              NOT NULL,
  CREATOR_ID            VARCHAR2(30 CHAR),
  CREATED_DATE          TIMESTAMP(6)            NOT NULL,
  MODIFIER_ID           VARCHAR2(30 CHAR),
  MODIFIED_DATE         TIMESTAMP(6)            NOT NULL,
  REALM_ID              NUMBER(19)              DEFAULT -1                    NOT NULL,
  STATUS_CD             VARCHAR2(255 CHAR),
  RETRY_COUNT           NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE PSP_EVENT_AS400_SYNC
 ADD PRIMARY KEY
 (EVENT_AS400_SYNC_SEQ, REALM_ID);

Prompt COLUMN CONTACT_NAME;
ALTER TABLE PSP_ENTITLEMENT
MODIFY(CONTACT_NAME VARCHAR2(200 CHAR));

Prompt COLUMN BILLING_ZIP_CODE;
ALTER TABLE PSP_ENTITLEMENT
 ADD (BILLING_ZIP_CODE  VARCHAR2(10 CHAR));

Prompt COLUMN CANCELLATION_REASON;
ALTER TABLE PSP_ENTITLEMENT
 ADD (CANCELLATION_REASON  VARCHAR2(200 CHAR));

Prompt COLUMN REQUIRES_UNIQUE_E_I_N;
ALTER TABLE PSP_SERVICE
 ADD (REQUIRES_UNIQUE_E_I_N  NUMBER(1));

Prompt COLUMN VERSION;
ALTER TABLE PSP_COMPANY
MODIFY(VERSION  DEFAULT 0);

Prompt COLUMN SERVICE_KEY;
ALTER TABLE PSP_ENTITLEMENT_UNIT
MODIFY(SERVICE_KEY VARCHAR2(19 CHAR));

Prompt COLUMN EXTENSION_KEY;
ALTER TABLE PSP_ENTITLEMENT_UNIT
 ADD (EXTENSION_KEY  VARCHAR2(14 CHAR));

Prompt COLUMN EVENT_AS400_SYNC_FK;
ALTER TABLE PSP_COMPANY_EVENT
 ADD (EVENT_AS400_SYNC_FK  VARCHAR2(255 CHAR));

Prompt INDEX PSP_COMPANY_EVENT_FK2;
--
-- PSP_COMPANY_EVENT_FK2  (Index) 
--
CREATE INDEX PSP_COMPANY_EVENT_FK2 ON PSP_COMPANY_EVENT
(EVENT_AS400_SYNC_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt COLUMN VERSION;
ALTER TABLE PSP_AUTH_USER
MODIFY(VERSION  DEFAULT 0);

ALTER TABLE PSP_COMPANY_EVENT
 ADD CONSTRAINT PSP_COMPANY_EVENT_FK2 
 FOREIGN KEY (EVENT_AS400_SYNC_FK, REALM_ID) 
 REFERENCES PSP_EVENT_AS400_SYNC (EVENT_AS400_SYNC_SEQ,REALM_ID); */ 

PROMPT finishedDBUpgrade_002.001.000.001.sql