--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--
-- Please review the script before using it to make sure it won't
-- cause any unacceptable data loss.
--
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PSP_LOCAL 

Prompt Column VERSION;
ALTER TABLE PSP_AUTH_USER
MODIFY(VERSION  DEFAULT 0);

Prompt Column VERSION;
ALTER TABLE PSP_COMPANY
MODIFY(VERSION  DEFAULT 0);

Prompt Column VERSION;
ALTER TABLE PSP_ENTITLEMENT_UNIT
MODIFY(VERSION  DEFAULT 0);

Prompt Table PSP_WC_PAYCHECK;
CREATE TABLE PSP_WC_PAYCHECK
(
  WC_PAYCHECK_SEQ   VARCHAR2(255 CHAR),
  VERSION           NUMBER(19),
  CREATOR_ID        VARCHAR2(30 CHAR),
  CREATED_DATE      TIMESTAMP(6),
  MODIFIER_ID       VARCHAR2(30 CHAR),
  MODIFIED_DATE     TIMESTAMP(6),
  REALM_ID          NUMBER(19)                  DEFAULT -1,
  INITIATION_DATE   TIMESTAMP(6),
  CURRENT_STATE_CD  VARCHAR2(255 CHAR),
  PAYCHECK_FK       VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_WC_PCHK_PCHK_FK;
CREATE INDEX PSP_WC_PCHK_PCHK_FK ON PSP_WC_PAYCHECK
(PAYCHECK_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_WC_PAYCHECK
 ADD PRIMARY KEY
  (WC_PAYCHECK_SEQ, REALM_ID)
  USING INDEX;

Prompt Table PSP_WC_PAYCHECK_STATE;
CREATE TABLE PSP_WC_PAYCHECK_STATE
(
  WC_PAYCHECK_STATE_SEQ     VARCHAR2(255 CHAR),
  VERSION                   NUMBER(19),
  CREATOR_ID                VARCHAR2(30 CHAR),
  CREATED_DATE              TIMESTAMP(6),
  MODIFIER_ID               VARCHAR2(30 CHAR),
  MODIFIED_DATE             TIMESTAMP(6),
  REALM_ID                  NUMBER(19)          DEFAULT -1,
  STATE_CD                  VARCHAR2(255 CHAR),
  STATE_EFFECTIVE_DATE      TIMESTAMP(6),
  WORKERS_COMP_PAYCHECK_FK  VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_WC_PCHK_STATE_PCHK_FK;
CREATE INDEX PSP_WC_PCHK_STATE_PCHK_FK ON PSP_WC_PAYCHECK_STATE
(WORKERS_COMP_PAYCHECK_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_WC_PAYCHECK_STATE
 ADD PRIMARY KEY
  (WC_PAYCHECK_STATE_SEQ, REALM_ID)
  USING INDEX;

Prompt Table PSP_WC_PAYCHECK_PENDING;
CREATE TABLE PSP_WC_PAYCHECK_PENDING
(
  WC_PAYCHECK_PENDING_SEQ   VARCHAR2(255 CHAR),
  VERSION                   NUMBER(19),
  CREATOR_ID                VARCHAR2(30 CHAR),
  CREATED_DATE              TIMESTAMP(6),
  MODIFIER_ID               VARCHAR2(30 CHAR),
  MODIFIED_DATE             TIMESTAMP(6),
  REALM_ID                  NUMBER(19)          DEFAULT -1,
  INITIATION_DATE           TIMESTAMP(6),
  STATE_CD                  VARCHAR2(255 CHAR),
  WORKERS_COMP_PAYCHECK_FK  VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_WC_PEND_STATE_PCHK_FK;
CREATE INDEX PSP_WC_PEND_STATE_PCHK_FK ON PSP_WC_PAYCHECK_PENDING
(WORKERS_COMP_PAYCHECK_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_WC_PAYCHECK_PENDING
 ADD PRIMARY KEY
  (WC_PAYCHECK_PENDING_SEQ, REALM_ID)
  USING INDEX;

ALTER TABLE PSP_WC_PAYCHECK
 ADD CONSTRAINT PSP_WC_PCHK_PCHK_FK 
  FOREIGN KEY (PAYCHECK_FK, REALM_ID) 
  REFERENCES PSP_PAYCHECK (PAYCHECK_SEQ,REALM_ID);

ALTER TABLE PSP_WC_PAYCHECK_STATE
 ADD CONSTRAINT PSP_WC_PCHK_STATE_PCHK_FK 
  FOREIGN KEY (WORKERS_COMP_PAYCHECK_FK, REALM_ID) 
  REFERENCES PSP_WC_PAYCHECK (WC_PAYCHECK_SEQ,REALM_ID);

ALTER TABLE PSP_WC_PAYCHECK_PENDING
 ADD CONSTRAINT PSP_WC_PEND_STATE_PCHK_FK 
  FOREIGN KEY (WORKERS_COMP_PAYCHECK_FK, REALM_ID) 
  REFERENCES PSP_WC_PAYCHECK (WC_PAYCHECK_SEQ,REALM_ID);

PROMPT finishedDBUpgrade_002.012.011.002.sql