--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--
-- Please review the script before using it to make sure it won't
-- cause any unacceptable data loss.
--
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PSP_LOCAL 

Prompt Column COMPANY_FK;
ALTER TABLE PSP_QBDT_EMPLOYEE_INFO
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));

Prompt Column COMPANY_FK;
ALTER TABLE PSP_QBDT_PAYROLL_ITEM_INFO
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));

Prompt Column COMPANY_FK;
ALTER TABLE PSP_TAX_TABLE_MISC_DATA
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));

Prompt Index PSP_QBDT_PAYROLL_ITEM_INFO_FK3;
CREATE INDEX PSP_QBDT_PAYROLL_ITEM_INFO_FK3 ON PSP_QBDT_PAYROLL_ITEM_INFO
(COMPANY_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_QBDT_EMPLOYEE_INFO_FK2;
CREATE INDEX PSP_QBDT_EMPLOYEE_INFO_FK2 ON PSP_QBDT_EMPLOYEE_INFO
(COMPANY_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_TAX_TABLE_MISC_DATA_FK2;
CREATE INDEX PSP_TAX_TABLE_MISC_DATA_FK2 ON PSP_TAX_TABLE_MISC_DATA
(COMPANY_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_QBDT_EMPLOYEE_INFO
 ADD CONSTRAINT PSP_QBDT_EMPLOYEE_INFO_FK2 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

ALTER TABLE PSP_QBDT_PAYROLL_ITEM_INFO
 ADD CONSTRAINT PSP_QBDT_PAYROLL_ITEM_INFO_FK3 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

ALTER TABLE PSP_TAX_TABLE_MISC_DATA
 ADD CONSTRAINT PSP_TAX_TABLE_MISC_DATA_FK2 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

PROMPT finishedDBUpgrade_002.000.011.010.sql
