--
-- This script will be executed BEFORE the automatically generated
-- D:\Dev\psp\dev\PSE\Domain\src\main\model\DBUpgrade_002.013.002.003.sql
--
-- Developers can hand code logic here for data migration purposes
--
