--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--
-- Please review the script before using it to make sure it won't
-- cause any unacceptable data loss.
--
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PSP_LOCAL 


Prompt Table PSP_DISBURSE_ADVICE;
CREATE TABLE PSP_DISBURSE_ADVICE
(
  DISBURSE_ADVICE_SEQ   VARCHAR2(255 CHAR),
  VERSION               NUMBER(19),
  CREATOR_ID            VARCHAR2(30 CHAR),
  CREATED_DATE          TIMESTAMP(6),
  MODIFIER_ID           VARCHAR2(30 CHAR),
  MODIFIED_DATE         TIMESTAMP(6),
  REALM_ID              NUMBER(19)              DEFAULT -1,
  TAX_LIABILITY_AMOUNT  NUMBER(19,4),
  TAX_QUARTER           NUMBER(10),
  PAYCHECK_DATE         TIMESTAMP(6),
  COMPANY_FK            VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_DISBURSE_ADVICE_FK1;
CREATE INDEX PSP_DISBURSE_ADVICE_FK1 ON PSP_DISBURSE_ADVICE
(COMPANY_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_DISBURSE_ADVICE
 ADD PRIMARY KEY
  (DISBURSE_ADVICE_SEQ, REALM_ID)
  USING INDEX;

Prompt Table PSP_DISBURSE_ADVICE_TAX_LIAB;
CREATE TABLE PSP_DISBURSE_ADVICE_TAX_LIAB
(
  DISBURSE_ADVICE_TAX_LIAB_SEQ  VARCHAR2(255 CHAR),
  VERSION                       NUMBER(19),
  CREATOR_ID                    VARCHAR2(30 CHAR),
  CREATED_DATE                  TIMESTAMP(6),
  MODIFIER_ID                   VARCHAR2(30 CHAR),
  MODIFIED_DATE                 TIMESTAMP(6),
  REALM_ID                      NUMBER(19)      DEFAULT -1,
  PAYROLL_ITEM_ID               VARCHAR2(4000 CHAR),
  CURRENT_AMOUNT                NUMBER(19,4),
  QUARTER_AMOUNT                NUMBER(19,4),
  Y_T_D_AMOUNT                  NUMBER(19,4),
  CURRENT_TAXABLE_AMOUNT        NUMBER(19,4),
  QUARTER_TAXABLE_AMOUNT        NUMBER(19,4),
  Y_T_D_TAXABLE_AMOUNT          NUMBER(19,4),
  STATE                         VARCHAR2(4000 CHAR),
  STATE_TAX_DESC                VARCHAR2(4000 CHAR),
  FED_TAX_DESC                  VARCHAR2(4000 CHAR),
  OTHER_TAX_DESC                VARCHAR2(4000 CHAR),
  DISBURSE_ADVICE_FK            VARCHAR2(255 CHAR),
  TIPS_LIABILITY_FK             VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_DISBURSE_ADVICE_TAX_LI_FK1;
CREATE INDEX PSP_DISBURSE_ADVICE_TAX_LI_FK1 ON PSP_DISBURSE_ADVICE_TAX_LIAB
(DISBURSE_ADVICE_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_DISBURSE_ADVICE_TAX_LI_FK2;
CREATE INDEX PSP_DISBURSE_ADVICE_TAX_LI_FK2 ON PSP_DISBURSE_ADVICE_TAX_LIAB
(TIPS_LIABILITY_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_DISBURSE_ADVICE_TAX_LIAB
 ADD PRIMARY KEY
  (DISBURSE_ADVICE_TAX_LIAB_SEQ, REALM_ID)
  USING INDEX;

ALTER TABLE PSP_DISBURSE_ADVICE
 ADD CONSTRAINT PSP_DISBURSE_ADVICE_FK1 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

ALTER TABLE PSP_DISBURSE_ADVICE_TAX_LIAB
 ADD CONSTRAINT PSP_DISBURSE_ADVICE_TAX_LI_FK1 
  FOREIGN KEY (DISBURSE_ADVICE_FK, REALM_ID) 
  REFERENCES PSP_DISBURSE_ADVICE (DISBURSE_ADVICE_SEQ,REALM_ID);

ALTER TABLE PSP_DISBURSE_ADVICE_TAX_LIAB
 ADD CONSTRAINT PSP_DISBURSE_ADVICE_TAX_LI_FK2 
  FOREIGN KEY (TIPS_LIABILITY_FK, REALM_ID) 
  REFERENCES PSP_DISBURSE_ADVICE_TAX_LIAB (DISBURSE_ADVICE_TAX_LIAB_SEQ,REALM_ID);

PROMPT finishedDBUpgrade_002.012.011.003.sql