--
-- This script will be executed BEFORE the automatically generated
-- C:\dev\PSP\rel-1.10\PSE\Domain\src\main\model\DBUpgrade_002.000.000.068.sql
--
-- Developers can hand code logic here for data migration purposes
--
