--
-- This script will be executed AFTER the automatically generated
-- C:\Dev\PSP\rel-1.13\PSE\Domain\src\main\model\DBUpgrade_002.000.013.002.sql
--
-- Developers can hand code logic here for data migration purposes
--

CREATE TABLE TEMP_POPULATE_AGENCY_ID
(
    "COMPANY_FK" VARCHAR2(255 CHAR) NOT NULL,
    "AGENCY_TAXPAYER_ID" VARCHAR2(24), 
    "COMPANY_AGENCY_FK" VARCHAR2(255 CHAR) NOT NULL,  
    "PAYMENT_TEMPLATE_FK" VARCHAR2(255 CHAR) NOT NULL,
    "PMTTMP_CATEGORY" VARCHAR2(255 CHAR),
    "QBDT_PAYROLL_ITEM_INFO_FK" VARCHAR2(255 CHAR) NOT NULL,
    "COMPANYAGENY_PMTTEMPLATE_FK" VARCHAR2(255 CHAR) NOT NULL,
    "SOURCE_ID" VARCHAR2(5 CHAR)
)
/

CREATE INDEX TEMP_POPULATE_AGENCY_ID_I1 ON TEMP_POPULATE_AGENCY_ID (COMPANYAGENY_PMTTEMPLATE_FK)
/

CREATE INDEX TEMP_POPULATE_AGENCY_ID_I2 ON TEMP_POPULATE_AGENCY_ID (COMPANY_AGENCY_FK)
/

INSERT INTO TEMP_POPULATE_AGENCY_ID 
(COMPANY_FK, AGENCY_TAXPAYER_ID, COMPANY_AGENCY_FK, PAYMENT_TEMPLATE_FK, PMTTMP_CATEGORY, QBDT_PAYROLL_ITEM_INFO_FK, COMPANYAGENY_PMTTEMPLATE_FK, SOURCE_ID)
select qbpi.company_fk, trim(qbpi.agency_id), CL.COMPANY_AGENCY_FK, L.PAYMENT_TEMPLATE_FK, PT.CATEGORY, QBPI.QBDT_PAYROLL_ITEM_INFO_SEQ, capt.companyagency_pmttemplate_seq, cl.source_id
from psp_company_law cl
  join psp_law l on CL.LAW_FK = L.LAW_ID  
  join PSP_QBDT_PAYROLL_ITEM_INFO qbpi on CL.COMPANY_LAW_SEQ = QBPI.COMPANY_LAW_FK
  join psp_Payment_template pt on L.PAYMENT_TEMPLATE_FK = PT.PAYMENT_TEMPLATE_CD 
  join psp_company_agency ca on ca.company_agency_seq = CL.COMPANY_AGENCY_FK
  join PSP_COMPANYAGENCY_PMTTEMPLATE capt on capt.company_agency_fk = CL.COMPANY_AGENCY_FK and capt.payment_template_fk = PT.PAYMENT_TEMPLATE_CD 
  join PSP_SOURCE_SYSTEM_LAW_ASSOC ssla on SSLA.LAW_FK = L.LAW_ID
Where SSLA.SOURCE_LAW_CODE like '% SIT' or SSLA.SOURCE_LAW_CODE like '% SUI_ER'
AND CA.AGENCY_FK = PT.AGENCY_FK;
/
