--
-- This script will be executed BEFORE the automatically generated
-- C:\Users\aagarwal14\Perforce\aagarwal14_INTUIT-RLNLLOH1_759\psp\dev-maven\PSE\domain\src\main\model\DBUpgrade_002.017.006.001.sql
--
-- Developers can hand code logic here for data migration purposes
--
