--
-- This script will be executed BEFORE the automatically generated
-- D:\dev\PSP\rel-2012R5\PSE\Domain\src\main\model\DBUpgrade_002.001.000.013.sql
--
-- Developers can hand code logic here for data migration purposes
--
