--
-- This script will be executed BEFORE the automatically generated
-- C:\dev\psp\dev-maven2\PSE\domain\src\main\model\DBUpgrade_002.016.012.001.sql
--
-- Developers can hand code logic here for data migration purposes
--
