--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--
-- Please review the script before using it to make sure it won't
-- cause any unacceptable data loss.
--
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PSP_LOCAL 

Prompt Column COMPANY_FK;
ALTER TABLE PSP_PSTUB_EMPLOYEE_INFO
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));

Prompt Column COMPANY_FK;
ALTER TABLE PSP_COMPANY_EVENT_EMAIL
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));

Prompt Column COMPANY_FK;
ALTER TABLE PSP_PAYCHECK_USAGE_HIST
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));

Prompt Index PSP_COMPANY_EVENT_EMAIL_FK2;
CREATE INDEX PSP_COMPANY_EVENT_EMAIL_FK2 ON PSP_COMPANY_EVENT_EMAIL
(COMPANY_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_PSTUB_EMPLOYEE_INFO_FK3;
CREATE INDEX PSP_PSTUB_EMPLOYEE_INFO_FK3 ON PSP_PSTUB_EMPLOYEE_INFO
(COMPANY_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_PAYCHECK_USAGE_HIST_FK3;
CREATE INDEX PSP_PAYCHECK_USAGE_HIST_FK3 ON PSP_PAYCHECK_USAGE_HIST
(COMPANY_FK, REALM_ID)
NOPARALLEL;

Prompt Column COMPANY_FK;
ALTER TABLE PSP_TAX_PAYMENT_ON_HOLD_REASON
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));

Prompt Column COMPANY_FK;
ALTER TABLE PSP_TP401K_BATCH_PAYCHECK
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));

Prompt Column COMPANY_FK;
ALTER TABLE PSP_TP401K_PAYCHECK
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));

Prompt Column COMPANY_FK;
ALTER TABLE PSP_EVENT_AS400_SYNC
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));

Prompt Column COMPANY_FK;
ALTER TABLE PSP_FSET_FILING_DETAIL
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));

Prompt Column COMPANY_FK;
ALTER TABLE PSP_EDI_PAYMENT_DETAIL
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));

Prompt Column COMPANY_FK;
ALTER TABLE PSP_EFTPS_PAYMENT_DETAIL
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));

Prompt Column COMPANY_FK;
ALTER TABLE PSP_PAYMENT_BATCH_ASSOC
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));

Prompt Column COMPANY_FK;
ALTER TABLE PSP_PAYSTUB
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));

Prompt Index PSP_EFTPS_PAYMENT_DETAIL_FK5;
CREATE INDEX PSP_EFTPS_PAYMENT_DETAIL_FK5 ON PSP_EFTPS_PAYMENT_DETAIL
(COMPANY_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_EDI_PAYMENT_DETAIL_FK4;
CREATE INDEX PSP_EDI_PAYMENT_DETAIL_FK4 ON PSP_EDI_PAYMENT_DETAIL
(COMPANY_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_PAYSTUB_FK4;
CREATE INDEX PSP_PAYSTUB_FK4 ON PSP_PAYSTUB
(COMPANY_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_FSET_FILING_DETAIL_FK4;
CREATE INDEX PSP_FSET_FILING_DETAIL_FK4 ON PSP_FSET_FILING_DETAIL
(COMPANY_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_EVENT_AS400_SYNC_FK2;
CREATE INDEX PSP_EVENT_AS400_SYNC_FK2 ON PSP_EVENT_AS400_SYNC
(COMPANY_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_THIRD_PARTY401K_PAYCHE_FK2;
CREATE INDEX PSP_THIRD_PARTY401K_PAYCHE_FK2 ON PSP_TP401K_PAYCHECK
(COMPANY_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_THIRD_PARTY401K_BATCH__FK3;
CREATE INDEX PSP_THIRD_PARTY401K_BATCH__FK3 ON PSP_TP401K_BATCH_PAYCHECK
(COMPANY_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_TAX_PAYMENT_ON_HOLD_RE_FK2;
CREATE INDEX PSP_TAX_PAYMENT_ON_HOLD_RE_FK2 ON PSP_TAX_PAYMENT_ON_HOLD_REASON
(COMPANY_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_PAYMENT_BATCH_ASSOC_FK3;
CREATE INDEX PSP_PAYMENT_BATCH_ASSOC_FK3 ON PSP_PAYMENT_BATCH_ASSOC
(COMPANY_FK, REALM_ID)
NOPARALLEL;

Prompt Column COMPANY_FK;
ALTER TABLE PSP_VOIDED_CHECK
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));

Prompt Column COMPANY_FK;
ALTER TABLE PSP_WC_PAYCHECK
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));

Prompt Column COMPANY_FK;
ALTER TABLE PSP_TRANSACTION_OFFLOAD_BATCH
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));

Prompt Column COMPANY_FK;
ALTER TABLE PSP_PSTUB_DDITEM
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));

Prompt Column COMPANY_FK;
ALTER TABLE PSP_PSTUB_MSG
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));

Prompt Column COMPANY_FK;
ALTER TABLE PSP_PSTUB_PAID_TIMEOFF_ITEM
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));

Prompt Index PSP_PSTUB_PAID_TIMEOFF_ITE_FK2;
CREATE INDEX PSP_PSTUB_PAID_TIMEOFF_ITE_FK2 ON PSP_PSTUB_PAID_TIMEOFF_ITEM
(COMPANY_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_PSTUB_MSG_FK2;
CREATE INDEX PSP_PSTUB_MSG_FK2 ON PSP_PSTUB_MSG
(COMPANY_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_PSTUB_DDITEM_FK2;
CREATE INDEX PSP_PSTUB_DDITEM_FK2 ON PSP_PSTUB_DDITEM
(COMPANY_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_WORKERS_COMP_PAYCHECK_FK2;
CREATE INDEX PSP_WORKERS_COMP_PAYCHECK_FK2 ON PSP_WC_PAYCHECK
(COMPANY_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_VOIDED_CHECK_FK4;
CREATE INDEX PSP_VOIDED_CHECK_FK4 ON PSP_VOIDED_CHECK
(COMPANY_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_TRANSACTION_OFFLOAD_BA_FK3;
CREATE INDEX PSP_TRANSACTION_OFFLOAD_BA_FK3 ON PSP_TRANSACTION_OFFLOAD_BATCH
(COMPANY_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_PSTUB_EMPLOYEE_INFO
 ADD CONSTRAINT PSP_PSTUB_EMPLOYEE_INFO_FK3 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

ALTER TABLE PSP_COMPANY_EVENT_EMAIL
 ADD CONSTRAINT PSP_COMPANY_EVENT_EMAIL_FK2 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

ALTER TABLE PSP_PAYCHECK_USAGE_HIST
 ADD CONSTRAINT PSP_PAYCHECK_USAGE_HIST_FK3 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

ALTER TABLE PSP_TAX_PAYMENT_ON_HOLD_REASON
 ADD CONSTRAINT PSP_TAX_PAYMENT_ON_HOLD_RE_FK2 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

ALTER TABLE PSP_TP401K_BATCH_PAYCHECK
 ADD CONSTRAINT PSP_THIRD_PARTY401K_BATCH__FK3 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

ALTER TABLE PSP_TP401K_PAYCHECK
 ADD CONSTRAINT PSP_THIRD_PARTY401K_PAYCHE_FK2 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

ALTER TABLE PSP_EVENT_AS400_SYNC
 ADD CONSTRAINT PSP_EVENT_AS400_SYNC_FK2 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

ALTER TABLE PSP_FSET_FILING_DETAIL
 ADD CONSTRAINT PSP_FSET_FILING_DETAIL_FK4 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

ALTER TABLE PSP_EDI_PAYMENT_DETAIL
 ADD CONSTRAINT PSP_EDI_PAYMENT_DETAIL_FK4 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

ALTER TABLE PSP_EFTPS_PAYMENT_DETAIL
 ADD CONSTRAINT PSP_EFTPS_PAYMENT_DETAIL_FK5 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

ALTER TABLE PSP_PAYMENT_BATCH_ASSOC
 ADD CONSTRAINT PSP_PAYMENT_BATCH_ASSOC_FK3 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

ALTER TABLE PSP_PAYSTUB
 ADD CONSTRAINT PSP_PAYSTUB_FK4 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

ALTER TABLE PSP_VOIDED_CHECK
 ADD CONSTRAINT PSP_VOIDED_CHECK_FK4 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

ALTER TABLE PSP_WC_PAYCHECK
 ADD CONSTRAINT PSP_WORKERS_COMP_PAYCHECK_FK2 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

ALTER TABLE PSP_TRANSACTION_OFFLOAD_BATCH
 ADD CONSTRAINT PSP_TRANSACTION_OFFLOAD_BA_FK3 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

ALTER TABLE PSP_PSTUB_DDITEM
 ADD CONSTRAINT PSP_PSTUB_DDITEM_FK2 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

ALTER TABLE PSP_PSTUB_MSG
 ADD CONSTRAINT PSP_PSTUB_MSG_FK2 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

ALTER TABLE PSP_PSTUB_PAID_TIMEOFF_ITEM
 ADD CONSTRAINT PSP_PSTUB_PAID_TIMEOFF_ITE_FK2 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

PROMPT finished DBUpgrade_002.023.002.001.sql