--------------------------------------------------------------------------
-- Run this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE.
--
-- Please review the script before using it to make sure it won't cause any unacceptable data loss.
--
-- PREVIOUS_PSP_LOCAL@XE schema extracted by user PREVIOUS_PSP_LOCAL
-- PSP_LOCAL@XE schema extracted by user PSP_LOCAL

Prompt Column COMPANY_FK;
ALTER TABLE PSP_COMPANY_EVENT_EMAIL_PARAM
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));

Prompt Column COMPANY_FK;
ALTER TABLE PSP_DISBURSE_ADVICE_TAX_LIAB
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));

Prompt Column COMPANY_FK;
ALTER TABLE PSP_PAYCHECK_USAGE
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));

Prompt Column COMPANY_FK;
ALTER TABLE PSP_PSTUB_PAY_ITEM
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));

/*
To be executed after deployment

Prompt Index PSP_COMPANY_EVENT_EMAIL_PA_FK2;
CREATE INDEX PSP_COMPANY_EVENT_EMAIL_PA_FK2 ON PSP_COMPANY_EVENT_EMAIL_PARAM
(COMPANY_FK, REALM_ID)
ONLINE
PARALLEL 8;

Prompt Index PSP_DISBURSE_ADVICE_TAX_LI_FK3;
CREATE INDEX PSP_DISBURSE_ADVICE_TAX_LI_FK3 ON PSP_DISBURSE_ADVICE_TAX_LIAB
(COMPANY_FK, REALM_ID)
ONLINE
PARALLEL 8;

Prompt Index PSP_PAYCHECK_USAGE_FK1;
CREATE INDEX PSP_PAYCHECK_USAGE_FK1 ON PSP_PAYCHECK_USAGE
(COMPANY_FK, REALM_ID)
ONLINE
PARALLEL 8;

Prompt Index PSP_PSTUB_PAY_ITEM_FK2;
CREATE INDEX PSP_PSTUB_PAY_ITEM_FK2 ON PSP_PSTUB_PAY_ITEM
(COMPANY_FK, REALM_ID)
ONLINE
PARALLEL 8;

ALTER TABLE PSP_COMPANY_EVENT_EMAIL_PARAM
 ADD CONSTRAINT PSP_COMPANY_EVENT_EMAIL_PA_FK2 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

ALTER TABLE PSP_DISBURSE_ADVICE_TAX_LIAB
 ADD CONSTRAINT PSP_DISBURSE_ADVICE_TAX_LI_FK3 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

ALTER TABLE PSP_PAYCHECK_USAGE
 ADD CONSTRAINT PSP_PAYCHECK_USAGE_FK1 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

ALTER TABLE PSP_PSTUB_PAY_ITEM
 ADD CONSTRAINT PSP_PSTUB_PAY_ITEM_FK2 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);
*/

PROMPT finished DBUpgrade_002.018.008.002.sql