--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--
-- Please review the script before using it to make sure it won't
-- cause any unacceptable data loss.
--
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PSP_LOCAL 

Prompt Table PSP_COMPANY_USAGE;
CREATE TABLE PSP_COMPANY_USAGE
(
  COMPANY_USAGE_SEQ         VARCHAR2(255 CHAR),
  VERSION                   NUMBER(19),
  CREATOR_ID                VARCHAR2(30 CHAR),
  CREATED_DATE              TIMESTAMP(6),
  MODIFIER_ID               VARCHAR2(30 CHAR),
  MODIFIED_DATE             TIMESTAMP(6),
  REALM_ID                  NUMBER(19)          DEFAULT -1,
  SOURCE_COMPANY_ID         VARCHAR2(255 CHAR),
  SOURCE_SYSTEM_CD          VARCHAR2(255 CHAR),
  ENTITLEMENT_ID            VARCHAR2(255 CHAR),
  LICENSE_ID                VARCHAR2(255 CHAR),
  BILLING_DAY_OF_MONTH      NUMBER(10),
  START_DAY_OF_USAGE_MONTH  NUMBER(10)
)
NOPARALLEL;

Prompt Index PSP_COMPANY_USAGE_U1;
CREATE UNIQUE INDEX PSP_COMPANY_USAGE_U1 ON PSP_COMPANY_USAGE
(SOURCE_COMPANY_ID, SOURCE_SYSTEM_CD)
NOPARALLEL;

ALTER TABLE PSP_COMPANY_USAGE
 ADD PRIMARY KEY
  (COMPANY_USAGE_SEQ, REALM_ID)
  USING INDEX;

Prompt Table PSP_USAGE_PERIOD;
CREATE TABLE PSP_USAGE_PERIOD
(
  USAGE_PERIOD_SEQ  VARCHAR2(255 CHAR),
  VERSION           NUMBER(19),
  CREATOR_ID        VARCHAR2(30 CHAR),
  CREATED_DATE      TIMESTAMP(6),
  MODIFIER_ID       VARCHAR2(30 CHAR),
  MODIFIED_DATE     TIMESTAMP(6),
  REALM_ID          NUMBER(19)                  DEFAULT -1,
  START_DATE        TIMESTAMP(6),
  END_DATE          TIMESTAMP(6),
  COMPANY_USAGE_FK  VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_USAGEPERIOD_FK1;
CREATE INDEX PSP_USAGEPERIOD_FK1 ON PSP_USAGE_PERIOD
(COMPANY_USAGE_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_USAGE_PERIOD_U1;
CREATE UNIQUE INDEX PSP_USAGE_PERIOD_U1 ON PSP_USAGE_PERIOD
(COMPANY_USAGE_FK, START_DATE, END_DATE)
NOPARALLEL;

ALTER TABLE PSP_USAGE_PERIOD
 ADD PRIMARY KEY
  (USAGE_PERIOD_SEQ, REALM_ID)
  USING INDEX;

 -- added in predeploy script
/* Prompt Column USAGE_BILLING_TOKEN;
ALTER TABLE PSP_PAYROLL_RUN
 ADD (USAGE_BILLING_TOKEN  NUMBER(19)); */

Prompt Table PSP_BILL;
CREATE TABLE PSP_BILL
(
  BILL_SEQ          VARCHAR2(255 CHAR),
  VERSION           NUMBER(19),
  CREATOR_ID        VARCHAR2(30 CHAR),
  CREATED_DATE      TIMESTAMP(6),
  MODIFIER_ID       VARCHAR2(30 CHAR),
  MODIFIED_DATE     TIMESTAMP(6),
  REALM_ID          NUMBER(19)                  DEFAULT -1,
  BILL_DATE         TIMESTAMP(6),
  USAGE_COUNT       NUMBER(10),
  SYNCHED_COUNT     NUMBER(10),
  COMPANY_USAGE_FK  VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_BILL_FK1;
CREATE INDEX PSP_BILL_FK1 ON PSP_BILL
(COMPANY_USAGE_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_BILL_U1;
CREATE UNIQUE INDEX PSP_BILL_U1 ON PSP_BILL
(COMPANY_USAGE_FK, BILL_DATE)
NOPARALLEL;

ALTER TABLE PSP_BILL
 ADD PRIMARY KEY
  (BILL_SEQ, REALM_ID)
  USING INDEX;

Prompt Table PSP_EMPLOYEE_USAGE;
CREATE TABLE PSP_EMPLOYEE_USAGE
(
  EMPLOYEE_USAGE_SEQ      VARCHAR2(255 CHAR),
  VERSION                 NUMBER(19),
  CREATOR_ID              VARCHAR2(30 CHAR),
  CREATED_DATE            TIMESTAMP(6),
  MODIFIER_ID             VARCHAR2(30 CHAR),
  MODIFIED_DATE           TIMESTAMP(6),
  REALM_ID                NUMBER(19)            DEFAULT -1,
  EMPLOYEE_NAME           VARCHAR2(300 CHAR),
  EMPLOYEE_RECORD_NUMBER  VARCHAR2(255 CHAR),
  SOURCE_EMPLOYEE_ID      VARCHAR2(255 CHAR),
  USAGE_COUNT             NUMBER(10),
  USAGE_PERIOD_FK         VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_EMPLOYEEUSAGE_FK1;
CREATE INDEX PSP_EMPLOYEEUSAGE_FK1 ON PSP_EMPLOYEE_USAGE
(USAGE_PERIOD_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_EMPLOYEE_USAGE_U1;
CREATE UNIQUE INDEX PSP_EMPLOYEE_USAGE_U1 ON PSP_EMPLOYEE_USAGE
(USAGE_PERIOD_FK, SOURCE_EMPLOYEE_ID)
NOPARALLEL;

ALTER TABLE PSP_EMPLOYEE_USAGE
 ADD PRIMARY KEY
  (EMPLOYEE_USAGE_SEQ, REALM_ID)
  USING INDEX;

Prompt Table PSP_FAILED_PAYROLL_RUN;
CREATE TABLE PSP_FAILED_PAYROLL_RUN
(
  FAILED_PAYROLL_RUN_SEQ  VARCHAR2(255 CHAR),
  VERSION                 NUMBER(19),
  CREATOR_ID              VARCHAR2(30 CHAR),
  CREATED_DATE            TIMESTAMP(6),
  MODIFIER_ID             VARCHAR2(30 CHAR),
  MODIFIED_DATE           TIMESTAMP(6),
  REALM_ID                NUMBER(19)            DEFAULT -1,
  STATUS_TOKEN            VARCHAR2(255 CHAR),
  PAYROLL_RUN_FK          VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_FAILED_PAYROLL_RUN_FK1;
CREATE INDEX PSP_FAILED_PAYROLL_RUN_FK1 ON PSP_FAILED_PAYROLL_RUN
(PAYROLL_RUN_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_FAILED_PAYROLL_RUN
 ADD PRIMARY KEY
  (FAILED_PAYROLL_RUN_SEQ, REALM_ID)
  USING INDEX;

Prompt Table PSP_PAYCHECK_USAGE;
CREATE TABLE PSP_PAYCHECK_USAGE
(
  PAYCHECK_USAGE_SEQ    VARCHAR2(255 CHAR),
  VERSION               NUMBER(19),
  CREATOR_ID            VARCHAR2(30 CHAR),
  CREATED_DATE          TIMESTAMP(6),
  MODIFIER_ID           VARCHAR2(30 CHAR),
  MODIFIED_DATE         TIMESTAMP(6),
  REALM_ID              NUMBER(19)              DEFAULT -1,
  PAYCHECK_DATE         TIMESTAMP(6),
  CHECK_NUMBER          VARCHAR2(100 CHAR),
  SOURCE_PAYCHECK_ID    VARCHAR2(100 CHAR),
  TRANSACTION_ID        VARCHAR2(255 CHAR),
  PAYCHECK_STATUS_CODE  VARCHAR2(255 CHAR),
  BILL_FK               VARCHAR2(255 CHAR),
  EMPLOYEE_USAGE_FK     VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_PAYCHECKUSAGE_FK1;
CREATE INDEX PSP_PAYCHECKUSAGE_FK1 ON PSP_PAYCHECK_USAGE
(BILL_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_PAYCHECKUSAGE_FK2;
CREATE INDEX PSP_PAYCHECKUSAGE_FK2 ON PSP_PAYCHECK_USAGE
(EMPLOYEE_USAGE_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_PAYCHECK_USAGE_U1;
CREATE UNIQUE INDEX PSP_PAYCHECK_USAGE_U1 ON PSP_PAYCHECK_USAGE
(EMPLOYEE_USAGE_FK, SOURCE_PAYCHECK_ID)
NOPARALLEL;

ALTER TABLE PSP_PAYCHECK_USAGE
 ADD PRIMARY KEY
  (PAYCHECK_USAGE_SEQ, REALM_ID)
  USING INDEX;

Prompt Index PSP_PAYROLL_RUN_I2;
CREATE INDEX PSP_PAYROLL_RUN_I2 ON PSP_PAYROLL_RUN
(USAGE_BILLING_TOKEN)
NOPARALLEL;

ALTER TABLE PSP_USAGE_PERIOD
 ADD CONSTRAINT PSP_USAGEPERIOD_FK1 
  FOREIGN KEY (COMPANY_USAGE_FK, REALM_ID) 
  REFERENCES PSP_COMPANY_USAGE (COMPANY_USAGE_SEQ,REALM_ID);

ALTER TABLE PSP_BILL
 ADD CONSTRAINT PSP_BILL_FK1 
  FOREIGN KEY (COMPANY_USAGE_FK, REALM_ID) 
  REFERENCES PSP_COMPANY_USAGE (COMPANY_USAGE_SEQ,REALM_ID);

ALTER TABLE PSP_EMPLOYEE_USAGE
 ADD CONSTRAINT PSP_EMPLOYEEUSAGE_FK1 
  FOREIGN KEY (USAGE_PERIOD_FK, REALM_ID) 
  REFERENCES PSP_USAGE_PERIOD (USAGE_PERIOD_SEQ,REALM_ID);

ALTER TABLE PSP_FAILED_PAYROLL_RUN
 ADD CONSTRAINT PSP_FAILED_PAYROLL_RUN_FK1 
  FOREIGN KEY (PAYROLL_RUN_FK, REALM_ID) 
  REFERENCES PSP_PAYROLL_RUN (PAYROLL_RUN_SEQ,REALM_ID);

ALTER TABLE PSP_PAYCHECK_USAGE
 ADD CONSTRAINT PSP_PAYCHECKUSAGE_FK1 
  FOREIGN KEY (BILL_FK, REALM_ID) 
  REFERENCES PSP_BILL (BILL_SEQ,REALM_ID);

ALTER TABLE PSP_PAYCHECK_USAGE
 ADD CONSTRAINT PSP_PAYCHECKUSAGE_FK2 
  FOREIGN KEY (EMPLOYEE_USAGE_FK, REALM_ID) 
  REFERENCES PSP_EMPLOYEE_USAGE (EMPLOYEE_USAGE_SEQ,REALM_ID);

PROMPT finishedDBUpgrade_002.001.001.006.sql