--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--                                                                      --
-- Please review the script before using it to make sure it won't       --
-- cause any unacceptable data loss.                                    --
--                                                                      --
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL
-- PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL

Prompt Table PSP_FRAUD_CONTACT;
--
-- PSP_FRAUD_CONTACT  (Table)
--
CREATE TABLE PSP_FRAUD_CONTACT
(
  FRAUD_CONTACT_SEQ  VARCHAR2(255 CHAR),
  VERSION            NUMBER(19),
  CREATOR_ID         VARCHAR2(30 CHAR),
  CREATED_DATE       TIMESTAMP(6),
  MODIFIER_ID        VARCHAR2(30 CHAR),
  MODIFIED_DATE      TIMESTAMP(6),
  REALM_ID           NUMBER(19)                 DEFAULT -1,
  EMAIL              VARCHAR2(100 CHAR),
  FIRST_NAME         VARCHAR2(80 CHAR),
  LAST_NAME          VARCHAR2(80 CHAR),
  PHONE              VARCHAR2(100 CHAR),
  COMPANY_FK         VARCHAR2(255 CHAR)
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

Prompt Index PSP_FRAUDCONTACT_FK1;
--
-- PSP_FRAUDCONTACT_FK1  (Index)
--
CREATE INDEX PSP_FRAUDCONTACT_FK1 ON PSP_FRAUD_CONTACT
(COMPANY_FK, REALM_ID)
LOGGING
NOPARALLEL;

ALTER TABLE PSP_FRAUD_CONTACT
 ADD PRIMARY KEY
 (FRAUD_CONTACT_SEQ, REALM_ID);

Prompt Table PSP_FRAUD_COMPANY;
--
-- PSP_FRAUD_COMPANY  (Table)
--
CREATE TABLE PSP_FRAUD_COMPANY
(
  FRAUD_COMPANY_SEQ    VARCHAR2(255 CHAR),
  VERSION              NUMBER(19),
  CREATOR_ID           VARCHAR2(30 CHAR),
  CREATED_DATE         TIMESTAMP(6),
  MODIFIER_ID          VARCHAR2(30 CHAR),
  MODIFIED_DATE        TIMESTAMP(6),
  REALM_ID             NUMBER(19)               DEFAULT -1,
  DBA_NAME             VARCHAR2(100 CHAR),
  FED_TAX_ID           VARCHAR2(80 CHAR),
  LEGAL_NAME           VARCHAR2(100 CHAR),
  LICENSE_NUMBER       VARCHAR2(100 CHAR),
  NOTIFICATION_EMAIL   VARCHAR2(100 CHAR),
  SOURCE_AGREEMENT_ID  VARCHAR2(100 CHAR),
  COMPANY_FK           VARCHAR2(255 CHAR)
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

Prompt Index PSP_FRAUDCOMPANY_FK1;
--
-- PSP_FRAUDCOMPANY_FK1  (Index)
--
CREATE INDEX PSP_FRAUDCOMPANY_FK1 ON PSP_FRAUD_COMPANY
(COMPANY_FK, REALM_ID)
LOGGING
NOPARALLEL;

ALTER TABLE PSP_FRAUD_COMPANY
 ADD PRIMARY KEY
 (FRAUD_COMPANY_SEQ, REALM_ID);

Prompt Table PSP_FRAUD_ADDRESS;
--
-- PSP_FRAUD_ADDRESS  (Table)
--
CREATE TABLE PSP_FRAUD_ADDRESS
(
  FRAUD_ADDRESS_SEQ  VARCHAR2(255 CHAR),
  VERSION            NUMBER(19),
  CREATOR_ID         VARCHAR2(30 CHAR),
  CREATED_DATE       TIMESTAMP(6),
  MODIFIER_ID        VARCHAR2(30 CHAR),
  MODIFIED_DATE      TIMESTAMP(6),
  REALM_ID           NUMBER(19)                 DEFAULT -1,
  ADDRESS_LINE1      VARCHAR2(80 CHAR),
  ADDRESS_LINE2      VARCHAR2(80 CHAR),
  ADDRESS_LINE3      VARCHAR2(80 CHAR),
  CITY               VARCHAR2(256 CHAR),
  STATE              VARCHAR2(21 CHAR),
  ZIP_CODE           VARCHAR2(13 CHAR),
  COMPANY_FK         VARCHAR2(255 CHAR)
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

Prompt Index PSP_FRAUDADDRESS_FK1;
--
-- PSP_FRAUDADDRESS_FK1  (Index)
--
CREATE INDEX PSP_FRAUDADDRESS_FK1 ON PSP_FRAUD_ADDRESS
(COMPANY_FK, REALM_ID)
LOGGING
NOPARALLEL;

ALTER TABLE PSP_FRAUD_ADDRESS
 ADD PRIMARY KEY
 (FRAUD_ADDRESS_SEQ, REALM_ID);

ALTER TABLE PSP_FRAUD_CONTACT
 ADD CONSTRAINT PSP_FRAUDCONTACT_FK1
 FOREIGN KEY (COMPANY_FK, REALM_ID)
 REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

ALTER TABLE PSP_FRAUD_COMPANY
 ADD CONSTRAINT PSP_FRAUDCOMPANY_FK1
 FOREIGN KEY (COMPANY_FK, REALM_ID)
 REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

ALTER TABLE PSP_FRAUD_ADDRESS
 ADD CONSTRAINT PSP_FRAUDADDRESS_FK1
 FOREIGN KEY (COMPANY_FK, REALM_ID)
 REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

