--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--
-- Please review the script before using it to make sure it won't
-- cause any unacceptable data loss.
--
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PSP_LOCAL 

Prompt Table PSP_EMPLOYER_PREFERENCE;
CREATE TABLE PSP_EMPLOYER_PREFERENCE
(
  EMPLOYER_PREFERENCE_SEQ  VARCHAR2(255 CHAR),
  VERSION                  NUMBER(19),
  CREATOR_ID               VARCHAR2(30 CHAR),
  CREATED_DATE             TIMESTAMP(6),
  MODIFIER_ID              VARCHAR2(30 CHAR),
  MODIFIED_DATE            TIMESTAMP(6),
  REALM_ID                 NUMBER(19)           DEFAULT -1,
  APP_NAME                 VARCHAR2(30 CHAR),
  PREFERENCE_NAME          VARCHAR2(30 CHAR),
  PREFERENCE_VALUE         VARCHAR2(100 CHAR),
  COMPANY_FK               VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_EMPLOYER_PREFERENCE_FK1;
CREATE INDEX PSP_EMPLOYER_PREFERENCE_FK1 ON PSP_EMPLOYER_PREFERENCE
(COMPANY_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_EMPLOYER_PREFERENCE
 ADD PRIMARY KEY
  (EMPLOYER_PREFERENCE_SEQ, REALM_ID)
  USING INDEX;

ALTER TABLE PSP_EMPLOYER_PREFERENCE
 ADD CONSTRAINT PSP_EMPLOYER_PREFERENCE_FK1 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

PROMPT finishedDBUpgrade_002.013.004.001.sql