--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--
-- Please review the script before using it to make sure it won't
-- cause any unacceptable data loss.
--
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PSP_LOCAL 

Prompt Column SOURCE_COMPANY_ID;
ALTER TABLE PSP_COMPANY_USAGE
MODIFY(SOURCE_COMPANY_ID VARCHAR2(50 CHAR));


Prompt Column ENTITLEMENT_ID;
ALTER TABLE PSP_COMPANY_USAGE
MODIFY(ENTITLEMENT_ID VARCHAR2(20 CHAR));


Prompt Column LICENSE_ID;
ALTER TABLE PSP_COMPANY_USAGE
MODIFY(LICENSE_ID VARCHAR2(20 CHAR));


Prompt Index PSP_COMPANY_USAGE_U1;
CREATE UNIQUE INDEX PSP_COMPANY_USAGE_U1 ON PSP_COMPANY_USAGE
(SOURCE_COMPANY_ID, SOURCE_SYSTEM_CD, LICENSE_ID, ENTITLEMENT_ID)
NOPARALLEL;

Prompt Column EMPLOYEE_NAME;
ALTER TABLE PSP_EMPLOYEE_USAGE
MODIFY(EMPLOYEE_NAME VARCHAR2(240 CHAR));


Prompt Column EMPLOYEE_RECORD_NUMBER;
ALTER TABLE PSP_EMPLOYEE_USAGE
MODIFY(EMPLOYEE_RECORD_NUMBER VARCHAR2(50 CHAR));


Prompt Column SOURCE_EMPLOYEE_ID;
ALTER TABLE PSP_EMPLOYEE_USAGE
MODIFY(SOURCE_EMPLOYEE_ID VARCHAR2(50 CHAR));


Prompt Column CHECK_NUMBER;
ALTER TABLE PSP_PAYCHECK_USAGE
MODIFY(CHECK_NUMBER VARCHAR2(11 CHAR));


Prompt Column SOURCE_PAYCHECK_ID;
ALTER TABLE PSP_PAYCHECK_USAGE
MODIFY(SOURCE_PAYCHECK_ID VARCHAR2(50 CHAR));


Prompt Column TRANSACTION_ID;
ALTER TABLE PSP_PAYCHECK_USAGE
MODIFY(TRANSACTION_ID VARCHAR2(50 CHAR));

PROMPT finishedDBUpgrade_002.001.001.016.sql