--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--
-- Please review the script before using it to make sure it won't
-- cause any unacceptable data loss.
--
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PSP_LOCAL 

Prompt Table PSP_FRAUD_RULE;
CREATE TABLE PSP_FRAUD_RULE
(
  FRAUD_RULE_SEQ    VARCHAR2(255 CHAR),
  VERSION           NUMBER(19),
  CREATOR_ID        VARCHAR2(30 CHAR),
  CREATED_DATE      TIMESTAMP(6),
  MODIFIER_ID       VARCHAR2(30 CHAR),
  MODIFIED_DATE     TIMESTAMP(6),
  REALM_ID          NUMBER(19)                  DEFAULT -1,
  DESCRIPTION       VARCHAR2(255 CHAR),
  SOURCE_SYSTEM_CD  VARCHAR2(255 CHAR)
)
NOPARALLEL;

ALTER TABLE PSP_FRAUD_RULE
 ADD PRIMARY KEY
  (FRAUD_RULE_SEQ, REALM_ID)
  USING INDEX;

Prompt Column REPORTING_TYPE;
ALTER TABLE PSP_OFFERING
 ADD (REPORTING_TYPE  VARCHAR2(255 CHAR));

Prompt Column FRAUD_RULE_FK;
ALTER TABLE PSP_OFFERING
 ADD (FRAUD_RULE_FK  VARCHAR2(255 CHAR));

Prompt Table PSP_FRAUD_VALUE;
CREATE TABLE PSP_FRAUD_VALUE
(
  FRAUD_VALUE_SEQ  VARCHAR2(255 CHAR),
  VERSION          NUMBER(19),
  CREATOR_ID       VARCHAR2(30 CHAR),
  CREATED_DATE     TIMESTAMP(6),
  MODIFIER_ID      VARCHAR2(30 CHAR),
  MODIFIED_DATE    TIMESTAMP(6),
  REALM_ID         NUMBER(19)                   DEFAULT -1,
  NAME             VARCHAR2(255 CHAR),
  VALUE            VARCHAR2(255 CHAR),
  FRAUD_RULE_FK    VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_FRAUDVALUE_FK1;
CREATE INDEX PSP_FRAUDVALUE_FK1 ON PSP_FRAUD_VALUE
(FRAUD_RULE_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_FRAUD_VALUE
 ADD PRIMARY KEY
  (FRAUD_VALUE_SEQ, REALM_ID)
  USING INDEX;

Prompt Column REPORTING_TYPE;
ALTER TABLE PSP_GEMS_LEDGER_POSTING_RULE
 ADD (REPORTING_TYPE  VARCHAR2(255 CHAR));

Prompt Column SERVICE;
ALTER TABLE PSP_GEMS_LEDGER_POSTING_RULE DROP COLUMN SERVICE;

Prompt Index PSP_OFFERING_FK2;
CREATE INDEX PSP_OFFERING_FK2 ON PSP_OFFERING
(FRAUD_RULE_FK, REALM_ID)
NOPARALLEL;

Prompt Column PRICE_TYPE;
ALTER TABLE PSP_ENTITLEMENT_CODE_OFFERING
 ADD (PRICE_TYPE  VARCHAR2(150 CHAR));

Prompt Column IS_DEFAULT;
ALTER TABLE PSP_ENTITLEMENT_CODE_OFFERING
 ADD (IS_DEFAULT  NUMBER(1));

Prompt Table PSP_SVCCHGPRICE;
-- Difference : Column Order (No action taken) 

ALTER TABLE PSP_FRAUD_VALUE
 ADD CONSTRAINT PSP_FRAUDVALUE_FK1 
  FOREIGN KEY (FRAUD_RULE_FK, REALM_ID) 
  REFERENCES PSP_FRAUD_RULE (FRAUD_RULE_SEQ,REALM_ID);

ALTER TABLE PSP_OFFERING
 ADD CONSTRAINT PSP_OFFERING_FK2 
  FOREIGN KEY (FRAUD_RULE_FK, REALM_ID) 
  REFERENCES PSP_FRAUD_RULE (FRAUD_RULE_SEQ,REALM_ID);

PROMPT finishedDBUpgrade_002.001.001.009.sql