--
-- This script will be executed BEFORE the automatically generated
-- Z:\dev\psp\dev\PSE\Domain\src\main\model\DBUpgrade_002.013.008.004.sql
--
-- Developers can hand code logic here for data migration purposes
--
