--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--
-- Please review the script before using it to make sure it won't
-- cause any unacceptable data loss.
--
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PSP_LOCAL 

Prompt Table PSP_RATE_LEDGER_OPERATION;
CREATE TABLE PSP_RATE_LEDGER_OPERATION
(
  RATE_LEDGER_OPERATION_SEQ      VARCHAR2(255 CHAR),
  REALM_ID                       NUMBER(19)     DEFAULT -1,
  ADDITIONAL_FILING_AMOUNT_NAME  VARCHAR2(4000 CHAR),
  PUSH_TO_QUICK_BOOKS            NUMBER(1),
  RATE                           NUMBER(19,7)
)
NOPARALLEL;

ALTER TABLE PSP_RATE_LEDGER_OPERATION
 ADD PRIMARY KEY
  (RATE_LEDGER_OPERATION_SEQ, REALM_ID);

ALTER TABLE PSP_RATE_LEDGER_OPERATION
 ADD CONSTRAINT PSP_RATE_LEDGER_OPERATION_FK1 
  FOREIGN KEY (RATE_LEDGER_OPERATION_SEQ, REALM_ID) 
  REFERENCES PSP_LEDGER_OPERATION (LEDGER_OPERATION_SEQ,REALM_ID);

PROMPT finishedDBUpgrade_002.013.003.008.sql