--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--                                                                      --
-- Please review the script before using it to make sure it won't       --
-- cause any unacceptable data loss.                                    --
--                                                                      --
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 

Prompt TABLE PSP_ACCOUNTING_REPORT_FILE;
--
-- PSP_ACCOUNTING_REPORT_FILE  (Table) 
--
CREATE TABLE PSP_ACCOUNTING_REPORT_FILE
(
  ACCOUNTING_REPORT_FILE_SEQ  VARCHAR2(255 CHAR) NOT NULL,
  VERSION                     NUMBER(19)        NOT NULL,
  CREATOR_ID                  VARCHAR2(30 CHAR),
  CREATED_DATE                TIMESTAMP(6)      NOT NULL,
  MODIFIER_ID                 VARCHAR2(30 CHAR),
  MODIFIED_DATE               TIMESTAMP(6)      NOT NULL,
  REALM_ID                    NUMBER(19)        DEFAULT -1                    NOT NULL,
  FILE_NAME                   VARCHAR2(4000 CHAR),
  STATUS                      VARCHAR2(255 CHAR),
  TYPE                        VARCHAR2(255 CHAR),
  TRANSMISSION_DATE           TIMESTAMP(6)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

Prompt COLUMN CUSTOM_REQUIREMENT;
ALTER TABLE PSP_AGENCY_ID_REQUIREMENT
 ADD (CUSTOM_REQUIREMENT  VARCHAR2(255 CHAR));

Prompt COLUMN FOLLOWS_FED_TAX_ID;
ALTER TABLE PSP_AGENCY_ID_REQUIREMENT DROP COLUMN FOLLOWS_FED_TAX_ID;

Prompt TABLE PSP_PAYMENT_REQUIREMENT;
--
-- PSP_PAYMENT_REQUIREMENT  (Table) 
--
CREATE TABLE PSP_PAYMENT_REQUIREMENT
(
  PAYMENT_REQUIREMENT_SEQ  VARCHAR2(255 CHAR)   NOT NULL,
  REALM_ID                 NUMBER(19)           DEFAULT -1                    NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

Prompt COLUMN ACCOUNTING_REPORT_FILE_FK;
ALTER TABLE PSP_VOIDED_CHECK
 ADD (ACCOUNTING_REPORT_FILE_FK  VARCHAR2(255 CHAR));

Prompt COLUMN PRINTED_CHECK_FILE_FK;
ALTER TABLE PSP_VOIDED_CHECK DROP CONSTRAINT PSP_VOIDED_CHECK_FK1;  
DROP INDEX PSP_VOIDED_CHECK_FK1;
ALTER TABLE PSP_VOIDED_CHECK DROP COLUMN PRINTED_CHECK_FILE_FK;

Prompt TABLE PSP_THRESHOLD_REQUIREMENT;
--
-- PSP_THRESHOLD_REQUIREMENT  (Table) 
--
CREATE TABLE PSP_THRESHOLD_REQUIREMENT
(
  THRESHOLD_REQUIREMENT_SEQ  VARCHAR2(255 CHAR) NOT NULL,
  REALM_ID                   NUMBER(19)         DEFAULT -1                    NOT NULL,
  MAXIMUM_PAYMENT_AMOUNT     NUMBER(19,4)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

Prompt TABLE PSP_DEPOSIT_FREQUENCY_REQ;
--
-- PSP_DEPOSIT_FREQUENCY_REQ  (Table) 
--
CREATE TABLE PSP_DEPOSIT_FREQUENCY_REQ
(
  DEPOSIT_FREQUENCY_REQ_SEQ     VARCHAR2(255 CHAR) NOT NULL,
  REALM_ID                      NUMBER(19)      DEFAULT -1                    NOT NULL,
  PROHIBITED_DEPOSIT_FREQUENCY  VARCHAR2(255 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE PSP_ACCOUNTING_REPORT_FILE
 ADD PRIMARY KEY
 (ACCOUNTING_REPORT_FILE_SEQ, REALM_ID);

Prompt INDEX PSP_VOIDED_CHECK_FK1;
--
-- PSP_VOIDED_CHECK_FK1  (Index) 
--
CREATE INDEX PSP_VOIDED_CHECK_FK1 ON PSP_VOIDED_CHECK
(ACCOUNTING_REPORT_FILE_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt CONSTRAINT PSP_CHECK_PRINT_BATCH_FK1;
ALTER TABLE PSP_CHECK_PRINT_BATCH
 ADD CONSTRAINT PSP_CHECK_PRINT_BATCH_FK1 
 FOREIGN KEY (RECON_PLUS_FILE_FK, REALM_ID) 
 REFERENCES PSP_ACCOUNTING_REPORT_FILE (ACCOUNTING_REPORT_FILE_SEQ,REALM_ID);

Prompt CONSTRAINT PSP_CHECK_PRINT_BATCH_FK2;
ALTER TABLE PSP_CHECK_PRINT_BATCH
 ADD CONSTRAINT PSP_CHECK_PRINT_BATCH_FK2 
 FOREIGN KEY (POSITIVE_PAY_FILE_FK, REALM_ID) 
 REFERENCES PSP_ACCOUNTING_REPORT_FILE (ACCOUNTING_REPORT_FILE_SEQ,REALM_ID);

ALTER TABLE PSP_VOIDED_CHECK
 ADD CONSTRAINT PSP_VOIDED_CHECK_FK1 
 FOREIGN KEY (ACCOUNTING_REPORT_FILE_FK, REALM_ID) 
 REFERENCES PSP_ACCOUNTING_REPORT_FILE (ACCOUNTING_REPORT_FILE_SEQ,REALM_ID);

ALTER TABLE PSP_PAYMENT_REQUIREMENT
 ADD PRIMARY KEY
 (PAYMENT_REQUIREMENT_SEQ, REALM_ID);

ALTER TABLE PSP_PAYMENT_REQUIREMENT
 ADD CONSTRAINT PSP_PAYMENT_REQUIREMENT_FK1 
 FOREIGN KEY (PAYMENT_REQUIREMENT_SEQ, REALM_ID) 
 REFERENCES PSP_PAYMENT_METHOD_REQUIREMENT (PAYMENT_METHOD_REQUIREMENT_SEQ,REALM_ID);

ALTER TABLE PSP_THRESHOLD_REQUIREMENT
 ADD PRIMARY KEY
 (THRESHOLD_REQUIREMENT_SEQ, REALM_ID);

ALTER TABLE PSP_THRESHOLD_REQUIREMENT
 ADD CONSTRAINT PSP_THRESHOLD_REQUIREMENT_FK1 
 FOREIGN KEY (THRESHOLD_REQUIREMENT_SEQ, REALM_ID) 
 REFERENCES PSP_PAYMENT_REQUIREMENT (PAYMENT_REQUIREMENT_SEQ,REALM_ID);

ALTER TABLE PSP_DEPOSIT_FREQUENCY_REQ
 ADD PRIMARY KEY
 (DEPOSIT_FREQUENCY_REQ_SEQ, REALM_ID);

ALTER TABLE PSP_DEPOSIT_FREQUENCY_REQ
 ADD CONSTRAINT PSP_DEPOSIT_FREQUENCY_REQU_FK1 
 FOREIGN KEY (DEPOSIT_FREQUENCY_REQ_SEQ, REALM_ID) 
 REFERENCES PSP_PAYMENT_REQUIREMENT (PAYMENT_REQUIREMENT_SEQ,REALM_ID);


PROMPT finishedDBUpgrade_002.000.011.004.sql
