--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--
-- Please review the script before using it to make sure it won't
-- cause any unacceptable data loss.
--
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PSP_LOCAL 

Prompt drop TABLE PSP_ACHENROLLMENT_BATCH_ASSOC;
ALTER TABLE PSP_ACHENROLLMENT_BATCH_ASSOC
 DROP PRIMARY KEY CASCADE;

DROP TABLE PSP_ACHENROLLMENT_BATCH_ASSOC CASCADE CONSTRAINTS;

Prompt drop TABLE PSP_ACHENROLLMENT_BATCH;
ALTER TABLE PSP_ACHENROLLMENT_BATCH
 DROP PRIMARY KEY CASCADE;

DROP TABLE PSP_ACHENROLLMENT_BATCH CASCADE CONSTRAINTS;

Prompt Table PSP_ACHENROLLMENT_FILE;
CREATE TABLE PSP_ACHENROLLMENT_FILE
(
  ACHENROLLMENT_FILE_SEQ  VARCHAR2(255 CHAR),
  VERSION                 NUMBER(19),
  CREATOR_ID              VARCHAR2(30 CHAR),
  CREATED_DATE            TIMESTAMP(6),
  MODIFIER_ID             VARCHAR2(30 CHAR),
  MODIFIED_DATE           TIMESTAMP(6),
  REALM_ID                NUMBER(19)            DEFAULT -1,
  FILE_NAME               VARCHAR2(4000 CHAR),
  STATUS                  VARCHAR2(255 CHAR),
  STATUS_EFFECTIVE_DATE   TIMESTAMP(6),
  TYPE                    VARCHAR2(255 CHAR),
  FILE_CONTENT            CLOB
)
NOPARALLEL;

ALTER TABLE PSP_ACHENROLLMENT_FILE
 ADD PRIMARY KEY
  (ACHENROLLMENT_FILE_SEQ, REALM_ID)
  USING INDEX;

Prompt Column STATUS;
ALTER TABLE PSP_ACHENROLLMENT
 ADD (STATUS  VARCHAR2(255 CHAR));

Prompt Column CONFIRMATION_NUMBER;
ALTER TABLE PSP_ACHENROLLMENT
 ADD (CONFIRMATION_NUMBER  VARCHAR2(4000 CHAR));

Prompt Column STATUS_CD;
ALTER TABLE PSP_ACHENROLLMENT DROP COLUMN STATUS_CD;

Prompt Table PSP_ACHENROLLMENT_DETAIL;
CREATE TABLE PSP_ACHENROLLMENT_DETAIL
(
  ACHENROLLMENT_DETAIL_SEQ  VARCHAR2(255 CHAR),
  VERSION                   NUMBER(19),
  CREATOR_ID                VARCHAR2(30 CHAR),
  CREATED_DATE              TIMESTAMP(6),
  MODIFIER_ID               VARCHAR2(30 CHAR),
  MODIFIED_DATE             TIMESTAMP(6),
  REALM_ID                  NUMBER(19)          DEFAULT -1,
  AGENCY_ID                 VARCHAR2(4000 CHAR),
  F_E_I_N                   VARCHAR2(4000 CHAR),
  LEGAL_NAME                VARCHAR2(4000 CHAR),
  A_C_H_ENROLLMENT_FK       VARCHAR2(255 CHAR),
  RESPONSE_FILE_FK          VARCHAR2(255 CHAR),
  REQUEST_FILE_FK           VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_ACHENROLLMENT_DETAIL_FK1;
CREATE INDEX PSP_ACHENROLLMENT_DETAIL_FK1 ON PSP_ACHENROLLMENT_DETAIL
(A_C_H_ENROLLMENT_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_ACHENROLLMENT_DETAIL_FK2;
CREATE INDEX PSP_ACHENROLLMENT_DETAIL_FK2 ON PSP_ACHENROLLMENT_DETAIL
(RESPONSE_FILE_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_ACHENROLLMENT_DETAIL_FK3;
CREATE INDEX PSP_ACHENROLLMENT_DETAIL_FK3 ON PSP_ACHENROLLMENT_DETAIL
(REQUEST_FILE_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_ACHENROLLMENT_DETAIL
 ADD PRIMARY KEY
  (ACHENROLLMENT_DETAIL_SEQ, REALM_ID)
  USING INDEX;

ALTER TABLE PSP_ACHENROLLMENT_DETAIL
 ADD CONSTRAINT PSP_ACHENROLLMENT_DETAIL_FK1 
  FOREIGN KEY (A_C_H_ENROLLMENT_FK, REALM_ID) 
  REFERENCES PSP_ACHENROLLMENT (ACHENROLLMENT_SEQ,REALM_ID);

ALTER TABLE PSP_ACHENROLLMENT_DETAIL
 ADD CONSTRAINT PSP_ACHENROLLMENT_DETAIL_FK2 
  FOREIGN KEY (RESPONSE_FILE_FK, REALM_ID) 
  REFERENCES PSP_ACHENROLLMENT_FILE (ACHENROLLMENT_FILE_SEQ,REALM_ID);

ALTER TABLE PSP_ACHENROLLMENT_DETAIL
 ADD CONSTRAINT PSP_ACHENROLLMENT_DETAIL_FK3 
  FOREIGN KEY (REQUEST_FILE_FK, REALM_ID) 
  REFERENCES PSP_ACHENROLLMENT_FILE (ACHENROLLMENT_FILE_SEQ,REALM_ID);

PROMPT finishedDBUpgrade_002.013.002.003.sql