--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--
-- Please review the script before using it to make sure it won't
-- cause any unacceptable data loss.
--
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PSP_LOCAL 

Prompt Table PSP_COMPANY_TFSSUBMISSION;
CREATE TABLE PSP_COMPANY_TFSSUBMISSION
(
  COMPANY_TFSSUBMISSION_SEQ  VARCHAR2(255 CHAR),
  VERSION                    NUMBER(19),
  CREATOR_ID                 VARCHAR2(30 CHAR),
  CREATED_DATE               TIMESTAMP(6),
  MODIFIER_ID                VARCHAR2(30 CHAR),
  MODIFIED_DATE              TIMESTAMP(6),
  REALM_ID                   NUMBER(19)         DEFAULT -1,
  SUBMISSION_STATUS          VARCHAR2(255 CHAR),
  STATUS_EFFECTIVE_DATE      TIMESTAMP(6),
  COMPANY_FK                 VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_COMPANY_TFSSUBMISSION_FK1;
CREATE INDEX PSP_COMPANY_TFSSUBMISSION_FK1 ON PSP_COMPANY_TFSSUBMISSION
(COMPANY_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_COMPANY_TFSSUBMISSION
 ADD PRIMARY KEY
  (COMPANY_TFSSUBMISSION_SEQ, REALM_ID);

ALTER TABLE PSP_COMPANY_TFSSUBMISSION
 ADD CONSTRAINT PSP_COMPANY_TFSSUBMISSION_FK1 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

PROMPT finishedDBUpgrade_002.001.001.018.sql