--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--
-- Please review the script before using it to make sure it won't
-- cause any unacceptable data loss.
--
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PSP_LOCAL 

ALTER TABLE PSPADM.PSP_SAP_METHOD_CALL RENAME TO PSP_SAP_METHOD_CALL_BKP;


Prompt Table PSP_SAP_METHOD_CALL;
CREATE TABLE PSP_SAP_METHOD_CALL
(
  SAP_METHOD_CALL_SEQ  VARCHAR2(255 CHAR),
  VERSION              NUMBER(19),
  CREATOR_ID           VARCHAR2(30 CHAR),
  CREATED_DATE         TIMESTAMP(6),
  MODIFIER_ID          VARCHAR2(30 CHAR),
  MODIFIED_DATE        TIMESTAMP(6),
  REALM_ID             NUMBER(19)               DEFAULT -1,
  SCREEN_PATH          VARCHAR2(400 CHAR),
  SERVICE_NAME         VARCHAR2(255 CHAR),
  METHOD_NAME          VARCHAR2(255 CHAR),
  PARAMETERS           VARCHAR2(4000 CHAR),
  RESULT_SIZE          NUMBER(19)				DEFAULT -1,
  ELAPSED_MILLIS       NUMBER(19)				DEFAULT -1,
  EXCEPTION_TRACE      VARCHAR2(4000 CHAR),
  SECURITY_PRINCIPAL   VARCHAR2(255 CHAR),
  SESSION_ID           VARCHAR2(255 CHAR),
  HOST                 VARCHAR2(200 CHAR)
)
NOPARALLEL;

ALTER TABLE PSP_SAP_METHOD_CALL
 ADD PRIMARY KEY
  (SAP_METHOD_CALL_SEQ, REALM_ID);

Prompt Column HOST;
ALTER TABLE PSP_SOURCE_SYSTEM_TRANSMISSION
 ADD (HOST  VARCHAR2(200 CHAR));

CREATE INDEX PSPADM.PSP_SAP_METH_CALL_IDX1 ON PSPADM.PSP_SAP_METHOD_CALL
(CREATED_DATE, SERVICE_NAME, METHOD_NAME)
LOGGING
TABLESPACE PSP_IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
ONLINE;

PROMPT finishedDBUpgrade_002.012.010.001.sql