--
-- This script will be executed AFTER the automatically generated
-- D:\Dev\psp\dev\PSE\Domain\src\main\model\DBUpgrade_002.013.003.001.sql
--
-- Developers can hand code logic here for data migration purposes
--
