--
-- This script will be executed AFTER the automatically generated
-- C:\Dev\PSP\rel-1.10\PSE\Domain\src\main\model\DBUpgrade_002.000.010.084.sql
--
-- Developers can hand code logic here for data migration purposes
--
