--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--                                                                      --
-- Please review the script before using it to make sure it won't       --
-- cause any unacceptable data loss.                                    --
--                                                                      --
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 

select to_char(sysdate, 'MM/DD/YYYY HH24:MI:SS') AS "START TIME" from dual;

Prompt COLUMN ACK_FILE_FK;
ALTER TABLE PSP_EFTPS_FILE
 ADD (ACK_FILE_FK  VARCHAR2(255 CHAR));

Prompt drop index PSP_EFTPS_FILE_FK1
DROP INDEX PSP_EFTPS_FILE_FK1;
 
Prompt COLUMN PARENT_FILE_FK;
-- Column to be dropped is part of a multi-column constraint.
-- Oracle requires that the constraint be dropped first.
-- There may be another statement later in the script that tries to drop
-- the constraint again.  Errors produced by it can be ignored.
ALTER TABLE PSP_EFTPS_FILE DROP CONSTRAINT PSP_EFTPS_FILE_FK1;
ALTER TABLE PSP_EFTPS_FILE DROP COLUMN PARENT_FILE_FK;

Prompt COLUMN TOKEN;
ALTER TABLE PSP_QBDT_TRANSACTION_INFO
 ADD (TOKEN  NUMBER(19));

Prompt INDEX PSP_EFTPS_FILE_FK1;
--
-- PSP_EFTPS_FILE_FK1  (Index) 
--
CREATE INDEX PSP_EFTPS_FILE_FK1 ON PSP_EFTPS_FILE
(ACK_FILE_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt COLUMN TAX_PAYMENT_STATUS;
ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION  RENAME COLUMN E_F_E_PAYMENT_STATUS TO TAX_PAYMENT_STATUS;

Prompt COLUMN TAX_PMTSTATUS_EFFECTIVEDATE;
ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION RENAME COLUMN EFE_PMT_STATUS_EFF_DATE TO TAX_PMTSTATUS_EFFECTIVEDATE;

Prompt TABLE PSP_EFTPS_PAYMENT_DETAIL;
--
-- PSP_EFTPS_PAYMENT_DETAIL  (Table) 
--
CREATE TABLE PSP_EFTPS_PAYMENT_DETAIL
(
  EFTPS_PAYMENT_DETAIL_SEQ       VARCHAR2(255 CHAR) NOT NULL,
  VERSION                        NUMBER(19)     NOT NULL,
  CREATOR_ID                     VARCHAR2(30 CHAR),
  CREATED_DATE                   TIMESTAMP(6)   NOT NULL,
  MODIFIER_ID                    VARCHAR2(30 CHAR),
  MODIFIED_DATE                  TIMESTAMP(6)   NOT NULL,
  REALM_ID                       NUMBER(19)     DEFAULT -1                    NOT NULL,
  TRANSACTION_SET_ID             NUMBER(10),
  TRANSACTION_ID                 NUMBER(10),
  RETURN_CD                      VARCHAR2(255 CHAR),
  PAYMENT_INITIATION_DATE        TIMESTAMP(6),
  TAX_TYPE_CODE                  VARCHAR2(4000 CHAR),
  EFT_TRANSACTION_ID             VARCHAR2(4000 CHAR),
  AGENCY_PAYMENT_ID              VARCHAR2(4000 CHAR),
  FED_TAX_ID                     VARCHAR2(4000 CHAR),
  PAYMENT_DUE_DATE               TIMESTAMP(6),
  PERIOD_END_DATE                TIMESTAMP(6),
  PAYMENT_AMOUNT                 NUMBER(19,4),
  PAYMENT_DETAILS                VARCHAR2(4000 CHAR),
  STATUS_CD                      VARCHAR2(255 CHAR),
  STATUS_EFFECTIVE_DATE          TIMESTAMP(6),
  GROUP_ID                       NUMBER(10),
  REJECT_CD                      VARCHAR2(4000 CHAR),
  REASON                         VARCHAR2(4000 CHAR),
  RESPONSE_DATE                  TIMESTAMP(6),
  PARENT_FILE_FK                 VARCHAR2(255 CHAR) NOT NULL,
  RETURN_FILE_FK                 VARCHAR2(255 CHAR),
  RESPONSE_FILE_FK               VARCHAR2(255 CHAR),
  MONEY_MOVEMENT_TRANSACTION_FK  VARCHAR2(255 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

Prompt INDEX PSP_EFTPS_PAYMENT_DETAIL_FK4;
--
-- PSP_EFTPS_PAYMENT_DETAIL_FK4  (Index) 
--
CREATE INDEX PSP_EFTPS_PAYMENT_DETAIL_FK4 ON PSP_EFTPS_PAYMENT_DETAIL
(MONEY_MOVEMENT_TRANSACTION_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt INDEX PSP_EFTPS_PAYMENT_DETAIL_FK3;
--
-- PSP_EFTPS_PAYMENT_DETAIL_FK3  (Index) 
--
CREATE INDEX PSP_EFTPS_PAYMENT_DETAIL_FK3 ON PSP_EFTPS_PAYMENT_DETAIL
(RESPONSE_FILE_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt INDEX PSP_EFTPS_PAYMENT_DETAIL_FK2;
--
-- PSP_EFTPS_PAYMENT_DETAIL_FK2  (Index) 
--
CREATE INDEX PSP_EFTPS_PAYMENT_DETAIL_FK2 ON PSP_EFTPS_PAYMENT_DETAIL
(RETURN_FILE_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt INDEX PSP_EFTPS_PAYMENT_DETAIL_FK1;
--
-- PSP_EFTPS_PAYMENT_DETAIL_FK1  (Index) 
--
CREATE INDEX PSP_EFTPS_PAYMENT_DETAIL_FK1 ON PSP_EFTPS_PAYMENT_DETAIL
(PARENT_FILE_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt COLUMN PARENT_FILE_FK;
ALTER TABLE PSP_EFTPS_ENROLLMENT_DETAIL
 ADD (PARENT_FILE_FK  VARCHAR2(255 CHAR)            NOT NULL);

Prompt COLUMN RESPONSE_FILE_FK;
ALTER TABLE PSP_EFTPS_ENROLLMENT_DETAIL
 ADD (RESPONSE_FILE_FK  VARCHAR2(255 CHAR));

Prompt COLUMN ACKNOWLEDGE_DATE;
ALTER TABLE PSP_EFTPS_ENROLLMENT_DETAIL DROP COLUMN ACKNOWLEDGE_DATE;

Prompt drop index PSP_EFTPS_ENROLLMENT_DETAI_FK2;
DROP INDEX PSP_EFTPS_ENROLLMENT_DETAI_FK2;

Prompt COLUMN EFTPS_FILE_FK;
ALTER TABLE PSP_EFTPS_ENROLLMENT_DETAIL DROP CONSTRAINT PSP_EFTPS_ENROLLMENT_DETAI_FK2;
ALTER TABLE PSP_EFTPS_ENROLLMENT_DETAIL DROP COLUMN EFTPS_FILE_FK;

Prompt INDEX PSP_EFTPS_ENROLLMENT_DETAI_FK3;
--
-- PSP_EFTPS_ENROLLMENT_DETAI_FK3  (Index) 
--
CREATE INDEX PSP_EFTPS_ENROLLMENT_DETAI_FK3 ON PSP_EFTPS_ENROLLMENT_DETAIL
(RESPONSE_FILE_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt INDEX PSP_EFTPS_ENROLLMENT_DETAI_FK2;
--
-- PSP_EFTPS_ENROLLMENT_DETAI_FK2  (Index) 
--
CREATE INDEX PSP_EFTPS_ENROLLMENT_DETAI_FK2 ON PSP_EFTPS_ENROLLMENT_DETAIL
(PARENT_FILE_FK, REALM_ID)
LOGGING
NOPARALLEL;

ALTER TABLE PSP_EFTPS_FILE
 ADD CONSTRAINT PSP_EFTPS_FILE_FK1 
 FOREIGN KEY (ACK_FILE_FK, REALM_ID) 
 REFERENCES PSP_EFTPS_FILE (EFTPS_FILE_SEQ,REALM_ID);

ALTER TABLE PSP_EFTPS_ENROLLMENT_DETAIL
 ADD CONSTRAINT PSP_EFTPS_ENROLLMENT_DETAI_FK2 
 FOREIGN KEY (PARENT_FILE_FK, REALM_ID) 
 REFERENCES PSP_EFTPS_FILE (EFTPS_FILE_SEQ,REALM_ID);

ALTER TABLE PSP_EFTPS_ENROLLMENT_DETAIL
 ADD CONSTRAINT PSP_EFTPS_ENROLLMENT_DETAI_FK3 
 FOREIGN KEY (RESPONSE_FILE_FK, REALM_ID) 
 REFERENCES PSP_EFTPS_FILE (EFTPS_FILE_SEQ,REALM_ID);

ALTER TABLE PSP_EFTPS_PAYMENT_DETAIL
 ADD PRIMARY KEY
 (EFTPS_PAYMENT_DETAIL_SEQ, REALM_ID);

ALTER TABLE PSP_EFTPS_PAYMENT_DETAIL
 ADD CONSTRAINT PSP_EFTPS_PAYMENT_DETAIL_FK1 
 FOREIGN KEY (PARENT_FILE_FK, REALM_ID) 
 REFERENCES PSP_EFTPS_FILE (EFTPS_FILE_SEQ,REALM_ID);

ALTER TABLE PSP_EFTPS_PAYMENT_DETAIL
 ADD CONSTRAINT PSP_EFTPS_PAYMENT_DETAIL_FK2 
 FOREIGN KEY (RETURN_FILE_FK, REALM_ID) 
 REFERENCES PSP_EFTPS_FILE (EFTPS_FILE_SEQ,REALM_ID);

ALTER TABLE PSP_EFTPS_PAYMENT_DETAIL
 ADD CONSTRAINT PSP_EFTPS_PAYMENT_DETAIL_FK3 
 FOREIGN KEY (RESPONSE_FILE_FK, REALM_ID) 
 REFERENCES PSP_EFTPS_FILE (EFTPS_FILE_SEQ,REALM_ID);

ALTER TABLE PSP_EFTPS_PAYMENT_DETAIL
 ADD CONSTRAINT PSP_EFTPS_PAYMENT_DETAIL_FK4 
 FOREIGN KEY (MONEY_MOVEMENT_TRANSACTION_FK, REALM_ID) 
 REFERENCES PSP_MONEY_MOVEMENT_TRANSACTION (MONEY_MOVEMENT_TRANSACTION_SEQ,REALM_ID);

select to_char(sysdate, 'MM/DD/YYYY HH24:MI:SS') AS "END TIME" from dual;


PROMPT finishedDBUpgrade_002.000.000.070.sql