--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--                                                                      --
-- Please review the script before using it to make sure it won't       --
-- cause any unacceptable data loss.                                    --
--                                                                      --
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL
-- PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL
select to_char(sysdate, 'MM/DD/YYYY HH24:MI:SS') AS "START TIME" from dual;

Prompt COLUMN QBDT_EMPLOYEE_INFO_FK;
--ALTER TABLE PSP_EMPLOYEE DROP COLUMN QBDT_EMPLOYEE_INFO_FK;

Prompt TABLE PSP_ENTITY_CHANGE;
--
-- PSP_ENTITY_CHANGE  (Table)


--
CREATE TABLE PSP_ENTITY_CHANGE
(
  ENTITY_CHANGE_SEQ  VARCHAR2(255 CHAR)         NOT NULL,
  VERSION            NUMBER(19)                 NOT NULL,
  CREATOR_ID         VARCHAR2(30 CHAR),
  CREATED_DATE       TIMESTAMP(6)               NOT NULL,
  MODIFIER_ID        VARCHAR2(30 CHAR),
  MODIFIED_DATE      TIMESTAMP(6)               NOT NULL,
  REALM_ID           NUMBER(19)                 DEFAULT -1                    NOT NULL,
  SOURCE_COMPANY_ID  VARCHAR2(4000 CHAR),
  E_I_N              VARCHAR2(4000 CHAR),
  EFFECTIVE_DATE     TIMESTAMP(6),
  COMPANY_FK         VARCHAR2(255 CHAR)         NOT NULL
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

Prompt COLUMN QBDT_PAYROLL_ITEM_INFO_FK;
--ALTER TABLE PSP_COMPANY_PAYROLL_ITEM DROP COLUMN QBDT_PAYROLL_ITEM_INFO_FK;

Prompt COLUMN VOID_SUBMISSION_FK;
ALTER TABLE PSP_COMP_ADJUST_SUBMISSION
 ADD (VOID_SUBMISSION_FK  VARCHAR2(255 CHAR));

Prompt COLUMN ORIGINAL_SUBMISSION_FK;
ALTER TABLE PSP_COMP_ADJUST_SUBMISSION
 ADD (ORIGINAL_SUBMISSION_FK  VARCHAR2(255 CHAR));

Prompt COLUMN IS_VOID;
ALTER TABLE PSP_COMP_ADJUST_SUBMISSION DROP COLUMN IS_VOID;

Prompt COLUMN QBDT_TRANSACTION_INFO_FK;
--ALTER TABLE PSP_COMP_ADJUST_SUBMISSION DROP COLUMN QBDT_TRANSACTION_INFO_FK;

Prompt COLUMN EMPLOYEE_FK;
ALTER TABLE PSP_QBDT_EMPLOYEE_INFO
 ADD (EMPLOYEE_FK  VARCHAR2(255 CHAR)               NULL);

Prompt INDEX PSP_ENTITYCHANGE_FK1;
--
-- PSP_ENTITYCHANGE_FK1  (Index)
--
CREATE INDEX PSP_ENTITYCHANGE_FK1 ON PSP_ENTITY_CHANGE
(COMPANY_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt INDEX PSP_COMPANY_ADJUSTMENT_SUB_FK4;
--
-- PSP_COMPANY_ADJUSTMENT_SUB_FK4  (Index)
--
CREATE INDEX PSP_COMPANY_ADJUSTMENT_SUB_FK4 ON PSP_COMP_ADJUST_SUBMISSION
(ORIGINAL_SUBMISSION_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt INDEX PSP_COMPANY_ADJUSTMENT_SUB_FK3;
--
-- PSP_COMPANY_ADJUSTMENT_SUB_FK3  (Index)
--
CREATE INDEX PSP_COMPANY_ADJUSTMENT_SUB_FK3 ON PSP_COMP_ADJUST_SUBMISSION
(VOID_SUBMISSION_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt INDEX PSP_QBDT_EMPLOYEE_INFO_FK1;
--
-- PSP_QBDT_EMPLOYEE_INFO_FK1  (Index)
--
CREATE INDEX PSP_QBDT_EMPLOYEE_INFO_FK1 ON PSP_QBDT_EMPLOYEE_INFO
(EMPLOYEE_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt COLUMN QBDT_PAYCHECK_INFO_FK;
--ALTER TABLE PSP_PAYCHECK DROP COLUMN QBDT_PAYCHECK_INFO_FK;

Prompt COLUMN QBDT_PAYLINE_INFO_FK;
--ALTER TABLE PSP_DEDUCTION DROP COLUMN QBDT_PAYLINE_INFO_FK;

Prompt COLUMN QBDT_PAYLINE_INFO_FK;
--ALTER TABLE PSP_EMPLOYER_CONTRIBUTION DROP COLUMN QBDT_PAYLINE_INFO_FK;

Prompt COLUMN QBDT_PAYROLL_ITEM_INFO_FK;
--ALTER TABLE PSP_COMPANY_LAW DROP COLUMN QBDT_PAYROLL_ITEM_INFO_FK;

Prompt COLUMN QBDT_PAYLINE_INFO_FK;
--ALTER TABLE PSP_COMPENSATION DROP COLUMN QBDT_PAYLINE_INFO_FK;

Prompt COLUMN COMPANY_LAW_FK;
ALTER TABLE PSP_QBDT_PAYROLL_ITEM_INFO
 ADD (COMPANY_LAW_FK  VARCHAR2(255 CHAR)            NULL);

Prompt COLUMN COMPANY_PAYROLL_ITEM_FK;
ALTER TABLE PSP_QBDT_PAYROLL_ITEM_INFO
 ADD (COMPANY_PAYROLL_ITEM_FK  VARCHAR2(255 CHAR)   NULL);

Prompt COLUMN EMPLOYER_CONTRIBUTION_FK;
ALTER TABLE PSP_QBDT_PAYLINE_INFO
 ADD (EMPLOYER_CONTRIBUTION_FK  VARCHAR2(255 CHAR)  NULL);

Prompt COLUMN COMPENSATION_FK;
ALTER TABLE PSP_QBDT_PAYLINE_INFO
 ADD (COMPENSATION_FK  VARCHAR2(255 CHAR)           NULL);

Prompt COLUMN DEDUCTION_FK;
ALTER TABLE PSP_QBDT_PAYLINE_INFO
 ADD (DEDUCTION_FK  VARCHAR2(255 CHAR)              NULL);

Prompt COLUMN PAYCHECK_FK;
ALTER TABLE PSP_QBDT_PAYCHECK_INFO
 ADD (PAYCHECK_FK  VARCHAR2(255 CHAR)               NULL);

Prompt INDEX PSP_QBDT_PAYROLL_ITEM_INFO_FK2;
--
-- PSP_QBDT_PAYROLL_ITEM_INFO_FK2  (Index)
--
CREATE INDEX PSP_QBDT_PAYROLL_ITEM_INFO_FK2 ON PSP_QBDT_PAYROLL_ITEM_INFO
(COMPANY_PAYROLL_ITEM_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt INDEX PSP_QBDT_PAYROLL_ITEM_INFO_FK1;
--
-- PSP_QBDT_PAYROLL_ITEM_INFO_FK1  (Index)
--
CREATE INDEX PSP_QBDT_PAYROLL_ITEM_INFO_FK1 ON PSP_QBDT_PAYROLL_ITEM_INFO
(COMPANY_LAW_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt INDEX PSP_QBDT_PAYLINE_INFO_FK3;
--
-- PSP_QBDT_PAYLINE_INFO_FK3  (Index)
--
CREATE INDEX PSP_QBDT_PAYLINE_INFO_FK3 ON PSP_QBDT_PAYLINE_INFO
(DEDUCTION_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt INDEX PSP_QBDT_PAYLINE_INFO_FK2;
--
-- PSP_QBDT_PAYLINE_INFO_FK2  (Index)
--
CREATE INDEX PSP_QBDT_PAYLINE_INFO_FK2 ON PSP_QBDT_PAYLINE_INFO
(COMPENSATION_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt INDEX PSP_QBDT_PAYLINE_INFO_FK1;
--
-- PSP_QBDT_PAYLINE_INFO_FK1  (Index)
--
CREATE INDEX PSP_QBDT_PAYLINE_INFO_FK1 ON PSP_QBDT_PAYLINE_INFO
(EMPLOYER_CONTRIBUTION_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt INDEX PSP_QBDT_PAYCHECK_INFO_FK1;
--
-- PSP_QBDT_PAYCHECK_INFO_FK1  (Index)
--
CREATE INDEX PSP_QBDT_PAYCHECK_INFO_FK1 ON PSP_QBDT_PAYCHECK_INFO
(PAYCHECK_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt COLUMN QBDT_TRANSACTION_INFO_FK;
--ALTER TABLE PSP_FINANCIAL_TRANSACTION DROP COLUMN QBDT_TRANSACTION_INFO_FK;

Prompt COLUMN IS_RECONCILING_ADJUSTMENT;
ALTER TABLE PSP_LIABILITY_ADJUSTMENT
 ADD (IS_RECONCILING_ADJUSTMENT  NUMBER(1));

Prompt COLUMN QBDT_TRANSACTION_INFO_FK;
--ALTER TABLE PSP_LIABILITY_ADJUSTMENT DROP COLUMN QBDT_TRANSACTION_INFO_FK;

Prompt COLUMN IS_DIRECT_DEPOSIT;
ALTER TABLE PSP_QBDT_TRANSACTION_INFO
 ADD (IS_DIRECT_DEPOSIT  NUMBER(1) DEFAULT 0);

Prompt COLUMN SYSTEM_GENERATED;
ALTER TABLE PSP_QBDT_TRANSACTION_INFO
 ADD (SYSTEM_GENERATED  NUMBER(1) DEFAULT 0);

Prompt COLUMN COMP_ADJUST_SUBMISSION_FK;
ALTER TABLE PSP_QBDT_TRANSACTION_INFO
 ADD (COMP_ADJUST_SUBMISSION_FK  VARCHAR2(255 CHAR) NULL);

Prompt COLUMN LIABILITY_ADJUSTMENT_FK;
ALTER TABLE PSP_QBDT_TRANSACTION_INFO
 ADD (LIABILITY_ADJUSTMENT_FK  VARCHAR2(255 CHAR)   NULL);

Prompt COLUMN FINANCIAL_TRANSACTION_FK;
ALTER TABLE PSP_QBDT_TRANSACTION_INFO
 ADD (FINANCIAL_TRANSACTION_FK  VARCHAR2(255 CHAR)  NULL);

Prompt INDEX PSP_QBDT_TRANSACTION_INFO_FK4;
--
-- PSP_QBDT_TRANSACTION_INFO_FK4  (Index)
--
CREATE INDEX PSP_QBDT_TRANSACTION_INFO_FK4 ON PSP_QBDT_TRANSACTION_INFO
(FINANCIAL_TRANSACTION_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt INDEX PSP_QBDT_TRANSACTION_INFO_FK6;
--
-- PSP_QBDT_TRANSACTION_INFO_FK6  (Index)
--
CREATE INDEX PSP_QBDT_TRANSACTION_INFO_FK6 ON PSP_QBDT_TRANSACTION_INFO
(LIABILITY_ADJUSTMENT_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt INDEX PSP_QBDT_TRANSACTION_INFO_FK5;
--
-- PSP_QBDT_TRANSACTION_INFO_FK5  (Index)
--
CREATE INDEX PSP_QBDT_TRANSACTION_INFO_FK5 ON PSP_QBDT_TRANSACTION_INFO
(COMP_ADJUST_SUBMISSION_FK, REALM_ID)
LOGGING
NOPARALLEL;

ALTER TABLE PSP_COMP_ADJUST_SUBMISSION
 ADD CONSTRAINT PSP_COMPANY_ADJUSTMENT_SUB_FK3
 FOREIGN KEY (VOID_SUBMISSION_FK, REALM_ID)
 REFERENCES PSP_COMP_ADJUST_SUBMISSION (COMP_ADJUST_SUBMISSION_SEQ,REALM_ID);

ALTER TABLE PSP_COMP_ADJUST_SUBMISSION
 ADD CONSTRAINT PSP_COMPANY_ADJUSTMENT_SUB_FK4
 FOREIGN KEY (ORIGINAL_SUBMISSION_FK, REALM_ID)
 REFERENCES PSP_COMP_ADJUST_SUBMISSION (COMP_ADJUST_SUBMISSION_SEQ,REALM_ID);

ALTER TABLE PSP_QBDT_EMPLOYEE_INFO
 ADD CONSTRAINT PSP_QBDT_EMPLOYEE_INFO_FK1
 FOREIGN KEY (EMPLOYEE_FK, REALM_ID)
 REFERENCES PSP_EMPLOYEE (EMPLOYEE_SEQ,REALM_ID);

ALTER TABLE PSP_QBDT_PAYROLL_ITEM_INFO
 ADD CONSTRAINT PSP_QBDT_PAYROLL_ITEM_INFO_FK1
 FOREIGN KEY (COMPANY_LAW_FK, REALM_ID)
 REFERENCES PSP_COMPANY_LAW (COMPANY_LAW_SEQ,REALM_ID);

ALTER TABLE PSP_QBDT_PAYROLL_ITEM_INFO
 ADD CONSTRAINT PSP_QBDT_PAYROLL_ITEM_INFO_FK2
 FOREIGN KEY (COMPANY_PAYROLL_ITEM_FK, REALM_ID)
 REFERENCES PSP_COMPANY_PAYROLL_ITEM (COMPANY_PAYROLL_ITEM_SEQ,REALM_ID);

ALTER TABLE PSP_QBDT_PAYLINE_INFO
 ADD CONSTRAINT PSP_QBDT_PAYLINE_INFO_FK1
 FOREIGN KEY (EMPLOYER_CONTRIBUTION_FK, REALM_ID)
 REFERENCES PSP_EMPLOYER_CONTRIBUTION (EMPLOYER_CONTRIBUTION_SEQ,REALM_ID);

ALTER TABLE PSP_QBDT_PAYLINE_INFO
 ADD CONSTRAINT PSP_QBDT_PAYLINE_INFO_FK2
 FOREIGN KEY (COMPENSATION_FK, REALM_ID)
 REFERENCES PSP_COMPENSATION (COMPENSATION_SEQ,REALM_ID);

ALTER TABLE PSP_QBDT_PAYLINE_INFO
 ADD CONSTRAINT PSP_QBDT_PAYLINE_INFO_FK3
 FOREIGN KEY (DEDUCTION_FK, REALM_ID)
 REFERENCES PSP_DEDUCTION (DEDUCTION_SEQ,REALM_ID);

ALTER TABLE PSP_QBDT_PAYCHECK_INFO
 ADD CONSTRAINT PSP_QBDT_PAYCHECK_INFO_FK1
 FOREIGN KEY (PAYCHECK_FK, REALM_ID)
 REFERENCES PSP_PAYCHECK (PAYCHECK_SEQ,REALM_ID);

ALTER TABLE PSP_QBDT_TRANSACTION_INFO
 ADD CONSTRAINT PSP_QBDT_TRANSACTION_INFO_FK5
 FOREIGN KEY (COMP_ADJUST_SUBMISSION_FK, REALM_ID)
 REFERENCES PSP_COMP_ADJUST_SUBMISSION (COMP_ADJUST_SUBMISSION_SEQ,REALM_ID);

ALTER TABLE PSP_QBDT_TRANSACTION_INFO
 ADD CONSTRAINT PSP_QBDT_TRANSACTION_INFO_FK6
 FOREIGN KEY (LIABILITY_ADJUSTMENT_FK, REALM_ID)
 REFERENCES PSP_LIABILITY_ADJUSTMENT (LIABILITY_ADJUSTMENT_SEQ,REALM_ID);

ALTER TABLE PSP_QBDT_TRANSACTION_INFO
 ADD CONSTRAINT PSP_QBDT_TRANSACTION_INFO_FK4
 FOREIGN KEY (FINANCIAL_TRANSACTION_FK, REALM_ID)
 REFERENCES PSP_FINANCIAL_TRANSACTION (FINANCIAL_TRANSACTION_SEQ,REALM_ID);

ALTER TABLE PSP_ENTITY_CHANGE
 ADD PRIMARY KEY
 (ENTITY_CHANGE_SEQ, REALM_ID);

ALTER TABLE PSP_ENTITY_CHANGE
 ADD CONSTRAINT PSP_ENTITYCHANGE_FK1
 FOREIGN KEY (COMPANY_FK, REALM_ID)
 REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

select to_char(sysdate, 'MM/DD/YYYY HH24:MI:SS') AS "END TIME" from dual;


PROMPT finishedDBUpgrade_002.000.010.077.sql