--
-- This script will be executed BEFORE the automatically generated
-- D:\dev\PSP\rel-1.11\PSE\Domain\src\main\model\DBUpgrade_002.000.011.001.sql
--
-- Developers can hand code logic here for data migration purposes
--
ALTER TABLE PSP_CHECK_PRINT_SIGNATURE
 DROP CONSTRAINT PSP_CHECK_PRINT_SIGNATURE_FK1;

DROP INDEX PSP_CHECK_PRINT_SIGNATURE_FK1; 
 
ALTER TABLE PSP_CHECK_PRINT_BATCH
 DROP CONSTRAINT PSP_CHECKPRINTBATCH_FK1; 
 
DROP INDEX PSP_CHECKPRINTBATCH_FK1;

ALTER TABLE PSP_CHECK_PRINT_PAYCHECK 
	DROP CONSTRAINT PSP_CHECKPRINTPAYCHECK_FK1;
	
DROP INDEX PSP_CHECKPRINTPAYCHECK_FK1;	
 
