--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--                                                                      --
-- Please review the script before using it to make sure it won't       --
-- cause any unacceptable data loss.                                    --
--                                                                      --
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 

Prompt COLUMN I_A_M_AUTHENTICATION_ID;
ALTER TABLE PSP_COMPANY
 ADD (I_A_M_AUTHENTICATION_ID  VARCHAR2(50 CHAR));

Prompt COLUMN I_A_M_REALM_ID;
ALTER TABLE PSP_COMPANY
 ADD (I_A_M_REALM_ID  VARCHAR2(50 CHAR));


Prompt COLUMN I_A_M_AUTHENTICATION_ID;
ALTER TABLE PSP_CONTACT
 ADD (I_A_M_AUTHENTICATION_ID  VARCHAR2(50 CHAR));


Prompt COLUMN COMPANY_LAW_FK;
ALTER TABLE PSP_LIABILITY_CHECK_LINE
 ADD (COMPANY_LAW_FK  VARCHAR2(255 CHAR));

Prompt COLUMN COMPANY_LAW_FK;
ALTER TABLE PSP_LIABILITY_ADJUSTMENT
 ADD (COMPANY_LAW_FK  VARCHAR2(255 CHAR));

Prompt COLUMN COMPANY_LAW_FK;
ALTER TABLE PSP_FINANCIAL_TRANSACTION
 ADD (COMPANY_LAW_FK  VARCHAR2(255 CHAR));

ALTER TABLE PSP_LIABILITY_CHECK_LINE
 ADD CONSTRAINT PSP_LIABILITY_CHECK_LINE_FK4 
 FOREIGN KEY (COMPANY_LAW_FK, REALM_ID) 
 REFERENCES PSP_COMPANY_LAW (COMPANY_LAW_SEQ,REALM_ID);

ALTER TABLE PSP_LIABILITY_ADJUSTMENT
 ADD CONSTRAINT PSP_LIABILITY_ADJUSTMENT_FK6 
 FOREIGN KEY (COMPANY_LAW_FK, REALM_ID) 
 REFERENCES PSP_COMPANY_LAW (COMPANY_LAW_SEQ,REALM_ID);

ALTER TABLE PSP_FINANCIAL_TRANSACTION
 ADD CONSTRAINT PSP_FINANCIAL_TRANSACTION_FK16 
 FOREIGN KEY (COMPANY_LAW_FK, REALM_ID) 
 REFERENCES PSP_COMPANY_LAW (COMPANY_LAW_SEQ,REALM_ID);

DECLARE
  l_nullable varchar2(1);
BEGIN
  SELECT nullable into l_nullable
  FROM user_tab_columns
  WHERE table_name = 'PSP_COMPANY_AGENCY'
  AND   column_name = 'FORM_TEMPLATE_FK';

  IF l_nullable = 'N' THEN
    execute immediate 'ALTER TABLE PSP_COMPANY_AGENCY MODIFY (FORM_TEMPLATE_FK varchar2(255) null)';
  END IF;
END;
/

PROMPT finishedDBUpgrade_002.000.000.064.sql