--
-- This script will be executed AFTER the automatically generated
-- D:\dev\PSP\rel-1.8.2\PSE\Domain\src\main\model\DBUpgrade_002.000.000.061.sql
--
-- Developers can hand code logic here for data migration purposes
--
