--
-- This script will be executed BEFORE the automatically generated
-- D:\dev\PSP\dev\PSE\Domain\src\main\model\DBUpgrade_002.000.013.007.sql
--
-- Developers can hand code logic here for data migration purposes
--
