--
-- This script will be executed AFTER the automatically generated
-- D:\Dev\PSP\dev\PSE\Domain\src\main\model\DBUpgrade_002.012.011.001.sql
--
-- Developers can hand code logic here for data migration purposes
--
