--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--
-- Please review the script before using it to make sure it won't
-- cause any unacceptable data loss.
--
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PSP_LOCAL 

Prompt drop TABLE PSP_QBDT_PROCESSED_PAYROLL;
ALTER TABLE PSP_QBDT_PROCESSED_PAYROLL
 DROP PRIMARY KEY CASCADE;

DROP TABLE PSP_QBDT_PROCESSED_PAYROLL CASCADE CONSTRAINTS;

Prompt drop TABLE PSP_PAYCHECK_ACCRUAL;
ALTER TABLE PSP_PAYCHECK_ACCRUAL
 DROP PRIMARY KEY CASCADE;

DROP TABLE PSP_PAYCHECK_ACCRUAL CASCADE CONSTRAINTS;

Prompt Column PAY_STUB_ORDER;
ALTER TABLE PSP_PAYCHECK_SPLIT
 ADD (PAY_STUB_ORDER  NUMBER(19));

Prompt Column VACATION_HOURS_ACCRUED;
ALTER TABLE PSP_QBDT_PAYCHECK_INFO
 ADD (VACATION_HOURS_ACCRUED  NUMBER(19,7));

Prompt Column SICK_HOURS_ACCRUED;
ALTER TABLE PSP_QBDT_PAYCHECK_INFO
 ADD (SICK_HOURS_ACCRUED  NUMBER(19,7));

Prompt Column VOID_TOKEN;
ALTER TABLE PSP_QBDT_PAYCHECK_INFO
 ADD (VOID_TOKEN  NUMBER(19));

PROMPT finishedDBUpgrade_002.000.012.005.sql