--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--
-- Please review the script before using it to make sure it won't
-- cause any unacceptable data loss.
--
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PSP_LOCAL 

Prompt drop TABLE PSP_LAW_FILING_AMOUNT;
ALTER TABLE PSP_LAW_FILING_AMOUNT
 DROP PRIMARY KEY CASCADE;

DROP TABLE PSP_LAW_FILING_AMOUNT CASCADE CONSTRAINTS;

Prompt drop TABLE PSP_COMPANY_LAW_FILING_AMOUNT;
ALTER TABLE PSP_COMPANY_LAW_FILING_AMOUNT
 DROP PRIMARY KEY CASCADE;

DROP TABLE PSP_COMPANY_LAW_FILING_AMOUNT CASCADE CONSTRAINTS;

Prompt Table PSP_ADDITIONAL_FILING_AMOUNT;
CREATE TABLE PSP_ADDITIONAL_FILING_AMOUNT
(
  NAME                 VARCHAR2(255 CHAR),
  VERSION              NUMBER(19),
  REALM_ID             NUMBER(19)               DEFAULT -1,
  A_T_F_LAW_ID         VARCHAR2(4000 CHAR),
  DESCRIPTION          VARCHAR2(4000 CHAR),
  RATE                 NUMBER(1),
  PAYMENT_TEMPLATE_FK  VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_ADDITIONAL_FILING_AMOU_FK1;
CREATE INDEX PSP_ADDITIONAL_FILING_AMOU_FK1 ON PSP_ADDITIONAL_FILING_AMOUNT
(PAYMENT_TEMPLATE_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_ADDITIONAL_FILING_AMOUNT
 ADD PRIMARY KEY
  (NAME, REALM_ID)
  USING INDEX;

Prompt Table PSP_COMPANY_FILING_AMOUNT;
CREATE TABLE PSP_COMPANY_FILING_AMOUNT
(
  COMPANY_FILING_AMOUNT_SEQ       VARCHAR2(255 CHAR),
  VERSION                         NUMBER(19),
  CREATOR_ID                      VARCHAR2(30 CHAR),
  CREATED_DATE                    TIMESTAMP(6),
  MODIFIER_ID                     VARCHAR2(30 CHAR),
  MODIFIED_DATE                   TIMESTAMP(6),
  REALM_ID                        NUMBER(19)    DEFAULT -1,
  AMOUNT                          NUMBER(19,7),
  EFFECTIVE_DATE                  TIMESTAMP(6),
  INVALID_DATE                    TIMESTAMP(6),
  NAME                            VARCHAR2(4000 CHAR),
  COMPANY_AGENCY_PMT_TEMPLATE_FK  VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_COMPANYFILINGAMOUNT_FK1;
CREATE INDEX PSP_COMPANYFILINGAMOUNT_FK1 ON PSP_COMPANY_FILING_AMOUNT
(COMPANY_AGENCY_PMT_TEMPLATE_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_COMPANY_FILING_AMOUNT
 ADD PRIMARY KEY
  (COMPANY_FILING_AMOUNT_SEQ, REALM_ID)
  USING INDEX;

ALTER TABLE PSP_ADDITIONAL_FILING_AMOUNT
 ADD CONSTRAINT PSP_ADDITIONAL_FILING_AMOU_FK1 
  FOREIGN KEY (PAYMENT_TEMPLATE_FK, REALM_ID) 
  REFERENCES PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD,REALM_ID);

ALTER TABLE PSP_COMPANY_FILING_AMOUNT
 ADD CONSTRAINT PSP_COMPANYFILINGAMOUNT_FK1 
  FOREIGN KEY (COMPANY_AGENCY_PMT_TEMPLATE_FK, REALM_ID) 
  REFERENCES PSP_COMPANYAGENCY_PMTTEMPLATE (COMPANYAGENCY_PMTTEMPLATE_SEQ,REALM_ID);

PROMPT finishedDBUpgrade_002.001.001.012.sql