--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--
-- Please review the script before using it to make sure it won't
-- cause any unacceptable data loss.
--
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PSP_LOCAL 

Prompt Table PSP_QBDT_REQUEST_INFO;
CREATE TABLE PSP_QBDT_REQUEST_INFO
(
  QBDT_REQUEST_INFO_SEQ          VARCHAR2(255 CHAR),
  VERSION                        NUMBER(19),
  CREATOR_ID                     VARCHAR2(30 CHAR),
  CREATED_DATE                   TIMESTAMP(6),
  MODIFIER_ID                    VARCHAR2(30 CHAR),
  MODIFIED_DATE                  TIMESTAMP(6),
  REALM_ID                       NUMBER(19)     DEFAULT -1,
  EMPLOYEE_ADD_COUNT             NUMBER(10),
  EMPLOYEE_ADD_START             TIMESTAMP(6),
  EMPLOYEE_ADD_END               TIMESTAMP(6),
  EMPLOYEE_UPDATE_COUNT          NUMBER(10),
  EMPLOYEE_UPDATE_START          TIMESTAMP(6),
  EMPLOYEE_UPDATE_END            TIMESTAMP(6),
  PAYCHECK_ADD_COUNT             NUMBER(10),
  PAYCHECK_UPDATE_COUNT          NUMBER(10),
  PAYROLL_PROCESSING_START       TIMESTAMP(6),
  PAYROLL_PROCESSING_END         TIMESTAMP(6),
  PAYROLL_ITEM_ADD_COUNT         NUMBER(10),
  PAYROLL_ITEM_ADD_START         TIMESTAMP(6),
  PAYROLL_ITEM_ADD_END           TIMESTAMP(6),
  PAYROLL_ITEM_UPDATE_COUNT      NUMBER(10),
  PAYROLL_ITEM_UPDATE_START      TIMESTAMP(6),
  PAYROLL_ITEM_UPDATE_END        TIMESTAMP(6),
  PAYROLL_TRANSACTION_ADD_COUNT  NUMBER(10),
  PAYROLL_TRANSACTION_ADD_START  TIMESTAMP(6),
  PAYROLL_TRANSACTION_ADD_END    TIMESTAMP(6),
  PAYROLL_TRANS_UPDATE_COUNT     NUMBER(10),
  PAYROLL_TRANS_UPDATE_START     TIMESTAMP(6),
  PAYROLL_TRANS_UPDATE_END       TIMESTAMP(6),
  EMPLOYEE_DELETE_COUNT          NUMBER(10),
  PAYROLL_ITEM_DELETE_COUNT      NUMBER(10),
  PAYROLL_TRANS_DELETE_COUNT     NUMBER(10),
  DELETE_PROCESSING_START        TIMESTAMP(6),
  DELETE_PROCESSING_END          TIMESTAMP(6),
  SOURCE_SYSTEM_TRANSMISSION_FK  VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_QBDT_REQUEST_INFO_FK1;
CREATE INDEX PSP_QBDT_REQUEST_INFO_FK1 ON PSP_QBDT_REQUEST_INFO
(SOURCE_SYSTEM_TRANSMISSION_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_QBDT_REQUEST_INFO
 ADD PRIMARY KEY
  (QBDT_REQUEST_INFO_SEQ, REALM_ID);

ALTER TABLE PSP_QBDT_REQUEST_INFO
 ADD CONSTRAINT PSP_QBDT_REQUEST_INFO_FK1 
  FOREIGN KEY (SOURCE_SYSTEM_TRANSMISSION_FK, REALM_ID) 
  REFERENCES PSP_SOURCE_SYSTEM_TRANSMISSION (SOURCE_SYSTEM_TRANSMISSION_SEQ,REALM_ID);

PROMPT finishedDBUpgrade_002.000.013.007.sql