--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--
-- Please review the script before using it to make sure it won't
-- cause any unacceptable data loss.
--
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PSP_LOCAL 

Prompt Table PSP_ARCHIVE_RECORD;
CREATE TABLE PSP_ARCHIVE_RECORD
(
  ARCHIVE_RECORD_SEQ  VARCHAR2(255 CHAR)        NOT NULL,
  VERSION             NUMBER(19)                NOT NULL,
  CREATOR_ID          VARCHAR2(30 CHAR),
  CREATED_DATE        TIMESTAMP(6)              NOT NULL,
  MODIFIER_ID         VARCHAR2(30 CHAR),
  MODIFIED_DATE       TIMESTAMP(6)              NOT NULL,
  REALM_ID            NUMBER(19)                DEFAULT -1                    NOT NULL,
  RECORD_IDENTIFIER   VARCHAR2(4000 CHAR),
  TABLE_NAME          VARCHAR2(4000 CHAR),
  STATUS              VARCHAR2(20 CHAR)
)
NOPARALLEL;

ALTER TABLE PSP_ARCHIVE_RECORD
 ADD PRIMARY KEY
  (ARCHIVE_RECORD_SEQ, REALM_ID)
  USING INDEX;

Prompt Constraint C_PSP_EVENT_TYPE0;
ALTER TABLE PSP_EVENT_TYPE
 DROP CONSTRAINT C_PSP_EVENT_TYPE0;

ALTER TABLE PSP_EVENT_TYPE
 ADD CONSTRAINT C_PSP_EVENT_TYPE0
  CHECK (EVENT_TYPE_CD IN('FileIdChanged', 'SendEmailFailed', 'PaycheckRecalledAfterOffload', 'SendEmailSkipped', 'InvalidVendorEmail', 'ERLoanNOC', 'NewPSIDCreatedForExistingCustomer', 'PrimaryPrincipalNameChanged', 'PayeeBankAccountChange', 'BackdatePriorToProcessingStart', 'SubscriptionEndDateChanged', 'SUICreditsApplied', 'TrialAssetDetected', 'WelcomeEmail', 'AccountLocked', 'ACHReturnStatusChanged', 'EINChanged', 'ServiceStatusChange', 'CompanyBankAccountStatusChange', 'LimitViolation', 'ReversalOK', 'DDIncreasePayrollLimit', 'PayrollCancelled', 'Strike', 'ReversalRequested', 'TransmissionError', 'PINCreated', 'PINUpdated', 'PayrollSubmittedWithPendingNOC', 'BackdatedPayrollReceived', 'ACHReturn', 'FeeCreated', 'IncorrectPIN', 'BankAccountVerified', 'LegalNameChanged', 'LegalAddressChanged', 'CompanyBankAccountChange', 'NOC', 'ReversalReturn', 'FeeReturn', 'ERRefundReturn', 'CBAVerifyReturn', 'DDDebitReturn', 'NSF', 'DDReject', 'PayrollReceived', 'FirstPayrollReceived', 'ZeroPayrollReceived', 'PayrollRejected', 'CompanyContactEmailChanged', 'TaxExemptStatusChanged', 'CustomerSignedUp', 'PayrollCancelPending', 'FeeRefunded', 'CoaFeeAccountChange', 'CoaSalesTaxAccountChange', 'EmailAddressChanged', 'ManualRedebitCreated', 'LastChanceNotify', 'NonAchPaymentReceived', 'DBANameChanged', 'CompanyContactRoleChanged', 'CompanyContactPhoneChanged', 'CompanyContactAddressChanged', 'CompanyFundingModelChanged', 'PayrollAdminChanged', 'QuickBooksInfoChanged', 'WireExpected', 'EmployeePaidEvenDollarAmount', 'NumberOfPayrollsPerDayExceeded', 'EmployeePaidGreaterThanMax', 'TotalPayrollExceedsLimit', 'CurrentPayrollPercentageIncrease', 'SingleEmployeePercentageIncrease', 'PayrollProcessedTooSoon', 'CompanyMatchesFraudulentCompany', 'FraudFlagRemovedEvent', 'SalesTaxReturn', 'FeeOffloaded', 'RedebitAmountUpdated', 'RedebitDateUpdated', 'AS400Event', 'PayrollRecalled', 'PaycheckRecalled', 'ChangeRedebitToWireExpected', 'FeeRebilled', 'ManualNoteEvent', 'PINReset', 'KeyPairGenerated', 'HigherTokenSynced', 'AuthenticationFailed', 'NOCWithOutChanges', 'CompanyIndustryTypeChanged', 'PrimaryPrincipalSSNChanged', 'PrimaryPrincipalDOBChanged', 'EnrollmentStatusChanged', 'StateIdModified', 'TaxPaymentStatusChanged', 'PaymentMethodChanged'
, 'DepositFrequencyChanged', 'ThresholdExceeded', 'AssistedEmployeeMigrationComplete', 'OfferingUpdated', 'OfferClaimed', 'OfferRemoved', 'EmployeeInTermedCompany', 'EmployeeBankAccountInTermedCompany', 'PrefundingReceived', 'EmployeePaidTooManyTimes', 'EmployeePaidPercentageGreaterThanOthers', 'EmployeesPaidToSameBank', 'EmployeeBankAccountChangedSpikeInPay', 'EmployeesPaidToSameBankAccount', 'InvalidEmployeeInformation', 'PINUnlocked', 'Employee401kDataUploaded', 'EmployeeBankAccountChange', 'TotalBillPaymentExceedsLimit', 'PayeePaidGreaterThanMax', 'PayeePaidTooManyTimes', 'BillPaymentReceived', 'InvalidPaycheckInformation', 'VoidedPaycheckAlreadyOffloadedToTOK', 'DeletedPaycheckAlreadyOffloadedToTOK', 'TOKNotifiedOfCompanyFraud', 'BillPaymentOffloaded', 'PreOffload401kValidationAlert', 'BillPaymentRecalled', 'NonPrintChecks', 'PayrollReceivedCloud', 'PostOffload401kValidationAlert', 'InvalidSourceSystemTransmissionInformation', 'CloudResponse', 'InactivityDDPayrollAmountExceeded', 'InactivityBPPayrollAmountExceeded', 'AssistedPayrollItemMigrationComplete', 'ERPayableRefundCreated', 'MultipleCompanyLawsCreated', 'BalanceFileReceived', 'CompanyLawUpdated', 'PayrollReceivedPayCard', 'LiabilityAdjustmentCreated', 'PSPToAS400HoldSync', 'PSPToAS400HoldRemoveSync', 'OFXServiceActivated', 'PositiveCobraReceived', 'ManualLedgerEntry', 'PayrollTaxPaymentVoided', 'PayrollTaxPaymentReissued', 'ERPayableAppliedToBalanceDue', 'AIDUpdated', 'AssistedFailedEnrollment', 'AssistedPayrollConfirmation', 'EntitlementStateChanged', 'EntitlementUnitStatusChanged', 'SourceCompanyIdChanged', 'ServiceKeyUpdated', 'EntitlementCodeChanged', 'PriceTypeChanged', 'EntitlementCommunication', 'ManualDataSync', 'AccountingFinancialLedgerAdjustmentCreated', 'SUIEoqDebitCreated', 'SUIEoqCreditCreated', 'SUIImmediateDebitCreated', 'SUIImmediateCreditCreated', 'CompanyContactAdded', 'CompanyContactJobTitleChanged', 'PayrollSubmissionIncludedAllNewEmployees', 'PSIDMismatch', 'CompanyContactDeleted', 'CompanyContactNameChanged', 'CompanyContactFaxChanged', 'ERPenaltiesAndInterestRefundCreated', 'ERPenaltiesAndInterestRefundDebitCreated', 'EntitlementUnitAdded', 'UsageBilling25DaysIntoSubscription', 'UsageBilling15DaysIntoSubscription', 'CreditReduction', 'RequestProcessingFlagChanged'
, 'PayrollSubmittedWithEmployeeWithPendingReturn', 'DuplicatePayrollItemReceived', 'VmpSignUpEmployeeEmail', 'VmpSignUpEmployerEmail', 'ACHEnrollmentStatusChanged', 'PaystubCreated', 'AdditionalFilingAmount', 'BPIncreasePayrollLimit', 'AllowTransmissionsFlagChanged', 'MonthlyFeeCreated', 'EmployeeAdded', 'EmployeeDeleted', 'EmployeeUpdated', 'PayeeAdded', 'PayeeUpdated', 'DDMigration', 'SplitMMTReturn', 'RealmIdAdded', 'RealmIdUpdated', 'BillingRealmCreated', 'BillingRealmAttached', 'DataRealmAttached', 'GrantAttached', 'DGDeleteRequest', 'SMSToPSPSyncFailure', 'SMSToPSPSyncSuccess', 'CompanyBankAccountVBDStatusChange', 'ComplianceAddressChanged', 'DGAccessRequest', 'AutoEnabledVMP', 'ConsentChange', 'EmployeeInvited', 'EmployeeSignedUp', 'EmployeeBankAccountWalletSuccess', 'EmployeeBankAccountWalletFailure', 'CloneEmployeeWalletOnRealmChangeSuccess', 'CloneEmployeeWalletOnRealmChangeFailure', 'AddUserToRealmSuccess', 'AddUserToRealmFailure', 'AddUserToRealmOnRealmChangeSuccess', 'AddUserToRealmOnRealmChangeFailure', 'RiskProfileMigrated', 'RiskProfileUnMigrated', 'PSPToSMSMigration', 'PSPToSMSMigrationRevert', 'SMSRealmIdUpdated', 'UpdateConsumerRealmId', 'VendorBankAccountWalletFailure', 'VendorBankAccountWalletSuccess', 'CloneVendorWalletOnRealmChangeFailure', 'CloneVendorWalletOnRealmChangeSuccess')) ENABLE NOVALIDATE;

Prompt Constraint C_PSP_EVENT_DETAIL_TYPE0;
ALTER TABLE PSP_EVENT_DETAIL_TYPE
 DROP CONSTRAINT C_PSP_EVENT_DETAIL_TYPE0;

ALTER TABLE PSP_EVENT_DETAIL_TYPE
 ADD CONSTRAINT C_PSP_EVENT_DETAIL_TYPE0
  CHECK (EVENT_DETAIL_TYPE_CD IN('EmailTemplateType', 'VendorInvalidEmail', 'OldAchAccountType', 'NewAchAccountType', 'OldCompanyBankAccountId', 'OldPayeeBankAccountNumber', 'ACHEventCd', 'BankAccountNumber', 'BankAccountRoutingNumber', 'EmployeeName', 'SourcePayrollRunId', 'PayrollCancellationReason', 'CompanyBankAccountId', 'ACHReturnReasonCode', 'CancellationDateTime', 'OffloadDate', 'PaycheckId', 'PaycheckAmount', 'FeeAmount', 'RefundedFeeBillingDetailId', 'StrikeReason', 'ReasonDescription', 'NoteText', 'FailureReason', 'PayrollRunId', 'PayrollCancellationScope', 'EmployeeId', 'LimitAmount', 'LimitType', 'ViolationAmount', 'OldCoaName', 'NewCoaName', 'CoaNameChangeByAgent', 'OldServiceStatus', 'NewServiceStatus', 'OldLimitAmount', 'NewLimitAmount', 'OldBAStatus', 'NewBAStatus', 'ManualStrikeReasonDescription', 'FeeType', 'RefundStatus', 'RefundStatusReason', 'ReturnType', 'CompanyServiceId', 'FinancialTransactionId', 'TransmissionId', 'ErrorCode', 'ErrorMessage', 'OldStringValue', 'NewStringValue', 'PaycheckDate', 'NSFSubType', 'PayrollStatus', 'OldAccountNumber', 'NewAccountNumber', 'OldRoutingNumber', 'NewRoutingNumber', 'OldAccountType', 'NewAccountType', 'EmployeeBankAccountId', 'VerificationStatus', 'PayrollRejectedReason', 'CompanyEventId', 'ServiceStatus', 'OldOnHoldReason', 'NewOnHoldReason', 'CollectionStage', 'AS400EventName', 'AS400EventToken', 'AS400EventOFX', 'WireExpectedDate', 'IntuitInitiated', 'Details', 'FraudEventCategory', 'ContactId', 'NewAmount', 'OldAmount', 'OldDate', 'NewDate', 'OldPayrollStatus', 'NewPayrollStatus', 'SourceBankAccountId', 'SourcePaycheckId', 'FeeBillingDetailId', 'RefundAmount', 'ExpectedToken', 'ReceivedToken', 'Timestamp', 'UniqueIdentifier', 'UserId', 'ServiceCode', 'ThresholdPeriodStartDate', 'AgencyId', 'EnrollmentType', 'PaymentEFTNumber', 'PaymentAcknowledgeNumber', 'MoneyMovementTransactionId', 'CompanyTIN', 'PaymentPeriodEndDate', 'NewPayeeBankAccountNumber', 'PaymentInitiationDate', 'PaymentDueDate', 'PaymentMethod', 'OldPayeeBankRoutingNumber', 'NewPayeeBankRoutingNumber', 'GenericEventDetail', 'NewEffectiveDate', 'NewDepositFrequency', 'OldEffectiveDate', 'OldDepositFrequency', 'PaymentTemplate', 'Percentage', 'EmployeeInvalidReason', 'SourceEmployeeId', 'MessageLevel', 'OldEmployeeBankAccountId'
, 'NewEmployeeBankAccountId', 'BillPaymentId', 'PayeeId', 'PayeeName', 'PayeeBankAccountId', 'PaycheckInvalidReason', 'OverrideRecipientEmailAddress', 'SourceSystemTransmissionInvalidReason', 'CompanyAgency', 'Law', 'NextPaycheckId', 'SourceCompanyId', 'OFXToken', 'NextEmployeeId', 'NextPaylineTransactionId', 'NextPayrollTransactionId', 'Amount', 'Description', 'EntitlementId', 'EntitlementUnitId', 'InvalidatedDepositFrequencyId', 'TransactionType', 'PermanentPaymentFrequencyId', 'ThresholdPeriodEndDate', 'ThresholdReversed', 'PenaltiesRefundAmount', 'InterestRefundAmount', 'TotalRefundAmount', 'RefundDebitAmount', 'ACHEnrollmentId', 'RecipientEmailAddress', 'CaseId', 'FirstPayrollRunDate', 'PayrollCount', 'GrantType', 'WorkflowId', 'AuthId', 'BillingRealmId', 'DataRealmId', 'WorkOrderId', 'EmployeeSequence', 'WorkOrderCreatedTime', 'ServiceKey', 'CompanySequence', 'CompanyName', 'AppName', 'ConsentValue', 'EmailTemplate', 'InvitationSource', 'IUSInvitationId', 'PersonaId', 'NewWalletId', 'OldWalletId', 'CompanyRealmId', 'OldCompanyRealmId', 'ConsumerRealmId', 'OwnerOldLimit', 'OwnerNewLimit', 'PayeeOldLimit', 'PayeeNewLimit', 'VendorId')) ENABLE NOVALIDATE;

Prompt Constraint C_PSP_SMSMIGRATION0;
ALTER TABLE PSP_SMSMIGRATION
 DROP CONSTRAINT C_PSP_SMSMIGRATION0;

ALTER TABLE PSP_SMSMIGRATION
 ADD CONSTRAINT C_PSP_SMSMIGRATION0
  CHECK (MIGRATION_STATUS IN('ValidationInProgress', 'NeedsValidation', 'ValidationSuccess', 'ValidationError', 'ValidationInternalError', 'MigrationError', 'MigrationInProgress', 'MigrationComplete', 'DataCollectionComplete', 'MigrationReverted', 'MigrationOnHold', 'LimitsMigrationError', 'LimitsMigrationRetryableError', 'LimitsMigrationOnHold', 'LimitsMigrationComplete', 'LimitsMigrationIrresolvableError')) ENABLE NOVALIDATE;

Prompt Constraint C_PSP_COMPANY_EVENT1;
ALTER TABLE PSP_COMPANY_EVENT
 DROP CONSTRAINT C_PSP_COMPANY_EVENT1;

ALTER TABLE PSP_COMPANY_EVENT
 ADD CONSTRAINT C_PSP_COMPANY_EVENT1
  CHECK (EVENT_TYPE_CD IN('FileIdChanged', 'SendEmailFailed', 'PaycheckRecalledAfterOffload', 'SendEmailSkipped', 'InvalidVendorEmail', 'ERLoanNOC', 'NewPSIDCreatedForExistingCustomer', 'PrimaryPrincipalNameChanged', 'PayeeBankAccountChange', 'BackdatePriorToProcessingStart', 'SubscriptionEndDateChanged', 'SUICreditsApplied', 'TrialAssetDetected', 'WelcomeEmail', 'AccountLocked', 'ACHReturnStatusChanged', 'EINChanged', 'ServiceStatusChange', 'CompanyBankAccountStatusChange', 'LimitViolation', 'ReversalOK', 'DDIncreasePayrollLimit', 'PayrollCancelled', 'Strike', 'ReversalRequested', 'TransmissionError', 'PINCreated', 'PINUpdated', 'PayrollSubmittedWithPendingNOC', 'BackdatedPayrollReceived', 'ACHReturn', 'FeeCreated', 'IncorrectPIN', 'BankAccountVerified', 'LegalNameChanged', 'LegalAddressChanged', 'CompanyBankAccountChange', 'NOC', 'ReversalReturn', 'FeeReturn', 'ERRefundReturn', 'CBAVerifyReturn', 'DDDebitReturn', 'NSF', 'DDReject', 'PayrollReceived', 'FirstPayrollReceived', 'ZeroPayrollReceived', 'PayrollRejected', 'CompanyContactEmailChanged', 'TaxExemptStatusChanged', 'CustomerSignedUp', 'PayrollCancelPending', 'FeeRefunded', 'CoaFeeAccountChange', 'CoaSalesTaxAccountChange', 'EmailAddressChanged', 'ManualRedebitCreated', 'LastChanceNotify', 'NonAchPaymentReceived', 'DBANameChanged', 'CompanyContactRoleChanged', 'CompanyContactPhoneChanged', 'CompanyContactAddressChanged', 'CompanyFundingModelChanged', 'PayrollAdminChanged', 'QuickBooksInfoChanged', 'WireExpected', 'EmployeePaidEvenDollarAmount', 'NumberOfPayrollsPerDayExceeded', 'EmployeePaidGreaterThanMax', 'TotalPayrollExceedsLimit', 'CurrentPayrollPercentageIncrease', 'SingleEmployeePercentageIncrease', 'PayrollProcessedTooSoon', 'CompanyMatchesFraudulentCompany', 'FraudFlagRemovedEvent', 'SalesTaxReturn', 'FeeOffloaded', 'RedebitAmountUpdated', 'RedebitDateUpdated', 'AS400Event', 'PayrollRecalled', 'PaycheckRecalled', 'ChangeRedebitToWireExpected', 'FeeRebilled', 'ManualNoteEvent', 'PINReset', 'KeyPairGenerated', 'HigherTokenSynced', 'AuthenticationFailed', 'NOCWithOutChanges', 'CompanyIndustryTypeChanged', 'PrimaryPrincipalSSNChanged', 'PrimaryPrincipalDOBChanged', 'EnrollmentStatusChanged', 'StateIdModified', 'TaxPaymentStatusChanged', 'PaymentMethodChanged'
, 'DepositFrequencyChanged', 'ThresholdExceeded', 'AssistedEmployeeMigrationComplete', 'OfferingUpdated', 'OfferClaimed', 'OfferRemoved', 'EmployeeInTermedCompany', 'EmployeeBankAccountInTermedCompany', 'PrefundingReceived', 'EmployeePaidTooManyTimes', 'EmployeePaidPercentageGreaterThanOthers', 'EmployeesPaidToSameBank', 'EmployeeBankAccountChangedSpikeInPay', 'EmployeesPaidToSameBankAccount', 'InvalidEmployeeInformation', 'PINUnlocked', 'Employee401kDataUploaded', 'EmployeeBankAccountChange', 'TotalBillPaymentExceedsLimit', 'PayeePaidGreaterThanMax', 'PayeePaidTooManyTimes', 'BillPaymentReceived', 'InvalidPaycheckInformation', 'VoidedPaycheckAlreadyOffloadedToTOK', 'DeletedPaycheckAlreadyOffloadedToTOK', 'TOKNotifiedOfCompanyFraud', 'BillPaymentOffloaded', 'PreOffload401kValidationAlert', 'BillPaymentRecalled', 'NonPrintChecks', 'PayrollReceivedCloud', 'PostOffload401kValidationAlert', 'InvalidSourceSystemTransmissionInformation', 'CloudResponse', 'InactivityDDPayrollAmountExceeded', 'InactivityBPPayrollAmountExceeded', 'AssistedPayrollItemMigrationComplete', 'ERPayableRefundCreated', 'MultipleCompanyLawsCreated', 'BalanceFileReceived', 'CompanyLawUpdated', 'PayrollReceivedPayCard', 'LiabilityAdjustmentCreated', 'PSPToAS400HoldSync', 'PSPToAS400HoldRemoveSync', 'OFXServiceActivated', 'PositiveCobraReceived', 'ManualLedgerEntry', 'PayrollTaxPaymentVoided', 'PayrollTaxPaymentReissued', 'ERPayableAppliedToBalanceDue', 'AIDUpdated', 'AssistedFailedEnrollment', 'AssistedPayrollConfirmation', 'EntitlementStateChanged', 'EntitlementUnitStatusChanged', 'SourceCompanyIdChanged', 'ServiceKeyUpdated', 'EntitlementCodeChanged', 'PriceTypeChanged', 'EntitlementCommunication', 'ManualDataSync', 'AccountingFinancialLedgerAdjustmentCreated', 'SUIEoqDebitCreated', 'SUIEoqCreditCreated', 'SUIImmediateDebitCreated', 'SUIImmediateCreditCreated', 'CompanyContactAdded', 'CompanyContactJobTitleChanged', 'PayrollSubmissionIncludedAllNewEmployees', 'PSIDMismatch', 'CompanyContactDeleted', 'CompanyContactNameChanged', 'CompanyContactFaxChanged', 'ERPenaltiesAndInterestRefundCreated', 'ERPenaltiesAndInterestRefundDebitCreated', 'EntitlementUnitAdded', 'UsageBilling25DaysIntoSubscription', 'UsageBilling15DaysIntoSubscription', 'CreditReduction', 'RequestProcessingFlagChanged'
, 'PayrollSubmittedWithEmployeeWithPendingReturn', 'DuplicatePayrollItemReceived', 'VmpSignUpEmployeeEmail', 'VmpSignUpEmployerEmail', 'ACHEnrollmentStatusChanged', 'PaystubCreated', 'AdditionalFilingAmount', 'BPIncreasePayrollLimit', 'AllowTransmissionsFlagChanged', 'MonthlyFeeCreated', 'EmployeeAdded', 'EmployeeDeleted', 'EmployeeUpdated', 'PayeeAdded', 'PayeeUpdated', 'DDMigration', 'SplitMMTReturn', 'RealmIdAdded', 'RealmIdUpdated', 'BillingRealmCreated', 'BillingRealmAttached', 'DataRealmAttached', 'GrantAttached', 'DGDeleteRequest', 'SMSToPSPSyncFailure', 'SMSToPSPSyncSuccess', 'CompanyBankAccountVBDStatusChange', 'ComplianceAddressChanged', 'DGAccessRequest', 'AutoEnabledVMP', 'ConsentChange', 'EmployeeInvited', 'EmployeeSignedUp', 'EmployeeBankAccountWalletSuccess', 'EmployeeBankAccountWalletFailure', 'CloneEmployeeWalletOnRealmChangeSuccess', 'CloneEmployeeWalletOnRealmChangeFailure', 'AddUserToRealmSuccess', 'AddUserToRealmFailure', 'AddUserToRealmOnRealmChangeSuccess', 'AddUserToRealmOnRealmChangeFailure', 'RiskProfileMigrated', 'RiskProfileUnMigrated', 'PSPToSMSMigration', 'PSPToSMSMigrationRevert', 'SMSRealmIdUpdated', 'UpdateConsumerRealmId', 'VendorBankAccountWalletFailure', 'VendorBankAccountWalletSuccess', 'CloneVendorWalletOnRealmChangeFailure', 'CloneVendorWalletOnRealmChangeSuccess')) ENABLE NOVALIDATE;

Prompt Constraint C_PSP_COMPANY_EVENT_DETAIL0;
ALTER TABLE PSP_COMPANY_EVENT_DETAIL
 DROP CONSTRAINT C_PSP_COMPANY_EVENT_DETAIL0;

ALTER TABLE PSP_COMPANY_EVENT_DETAIL
 ADD CONSTRAINT C_PSP_COMPANY_EVENT_DETAIL0
  CHECK (EVENT_DETAIL_TYPE_CD IN('EmailTemplateType', 'VendorInvalidEmail', 'OldAchAccountType', 'NewAchAccountType', 'OldCompanyBankAccountId', 'OldPayeeBankAccountNumber', 'ACHEventCd', 'BankAccountNumber', 'BankAccountRoutingNumber', 'EmployeeName', 'SourcePayrollRunId', 'PayrollCancellationReason', 'CompanyBankAccountId', 'ACHReturnReasonCode', 'CancellationDateTime', 'OffloadDate', 'PaycheckId', 'PaycheckAmount', 'FeeAmount', 'RefundedFeeBillingDetailId', 'StrikeReason', 'ReasonDescription', 'NoteText', 'FailureReason', 'PayrollRunId', 'PayrollCancellationScope', 'EmployeeId', 'LimitAmount', 'LimitType', 'ViolationAmount', 'OldCoaName', 'NewCoaName', 'CoaNameChangeByAgent', 'OldServiceStatus', 'NewServiceStatus', 'OldLimitAmount', 'NewLimitAmount', 'OldBAStatus', 'NewBAStatus', 'ManualStrikeReasonDescription', 'FeeType', 'RefundStatus', 'RefundStatusReason', 'ReturnType', 'CompanyServiceId', 'FinancialTransactionId', 'TransmissionId', 'ErrorCode', 'ErrorMessage', 'OldStringValue', 'NewStringValue', 'PaycheckDate', 'NSFSubType', 'PayrollStatus', 'OldAccountNumber', 'NewAccountNumber', 'OldRoutingNumber', 'NewRoutingNumber', 'OldAccountType', 'NewAccountType', 'EmployeeBankAccountId', 'VerificationStatus', 'PayrollRejectedReason', 'CompanyEventId', 'ServiceStatus', 'OldOnHoldReason', 'NewOnHoldReason', 'CollectionStage', 'AS400EventName', 'AS400EventToken', 'AS400EventOFX', 'WireExpectedDate', 'IntuitInitiated', 'Details', 'FraudEventCategory', 'ContactId', 'NewAmount', 'OldAmount', 'OldDate', 'NewDate', 'OldPayrollStatus', 'NewPayrollStatus', 'SourceBankAccountId', 'SourcePaycheckId', 'FeeBillingDetailId', 'RefundAmount', 'ExpectedToken', 'ReceivedToken', 'Timestamp', 'UniqueIdentifier', 'UserId', 'ServiceCode', 'ThresholdPeriodStartDate', 'AgencyId', 'EnrollmentType', 'PaymentEFTNumber', 'PaymentAcknowledgeNumber', 'MoneyMovementTransactionId', 'CompanyTIN', 'PaymentPeriodEndDate', 'NewPayeeBankAccountNumber', 'PaymentInitiationDate', 'PaymentDueDate', 'PaymentMethod', 'OldPayeeBankRoutingNumber', 'NewPayeeBankRoutingNumber', 'GenericEventDetail', 'NewEffectiveDate', 'NewDepositFrequency', 'OldEffectiveDate', 'OldDepositFrequency', 'PaymentTemplate', 'Percentage', 'EmployeeInvalidReason', 'SourceEmployeeId', 'MessageLevel', 'OldEmployeeBankAccountId'
, 'NewEmployeeBankAccountId', 'BillPaymentId', 'PayeeId', 'PayeeName', 'PayeeBankAccountId', 'PaycheckInvalidReason', 'OverrideRecipientEmailAddress', 'SourceSystemTransmissionInvalidReason', 'CompanyAgency', 'Law', 'NextPaycheckId', 'SourceCompanyId', 'OFXToken', 'NextEmployeeId', 'NextPaylineTransactionId', 'NextPayrollTransactionId', 'Amount', 'Description', 'EntitlementId', 'EntitlementUnitId', 'InvalidatedDepositFrequencyId', 'TransactionType', 'PermanentPaymentFrequencyId', 'ThresholdPeriodEndDate', 'ThresholdReversed', 'PenaltiesRefundAmount', 'InterestRefundAmount', 'TotalRefundAmount', 'RefundDebitAmount', 'ACHEnrollmentId', 'RecipientEmailAddress', 'CaseId', 'FirstPayrollRunDate', 'PayrollCount', 'GrantType', 'WorkflowId', 'AuthId', 'BillingRealmId', 'DataRealmId', 'WorkOrderId', 'EmployeeSequence', 'WorkOrderCreatedTime', 'ServiceKey', 'CompanySequence', 'CompanyName', 'AppName', 'ConsentValue', 'EmailTemplate', 'InvitationSource', 'IUSInvitationId', 'PersonaId', 'NewWalletId', 'OldWalletId', 'CompanyRealmId', 'OldCompanyRealmId', 'ConsumerRealmId', 'OwnerOldLimit', 'OwnerNewLimit', 'PayeeOldLimit', 'PayeeNewLimit', 'VendorId')) ENABLE NOVALIDATE;

Prompt Constraint C_PSP_INDUSTRY_TYPE1;
ALTER TABLE PSP_INDUSTRY_TYPE
 ADD CONSTRAINT C_PSP_INDUSTRY_TYPE1
  CHECK (LENGTH(STANDARD_INDUSTRY_CODE) > 3) ENABLE NOVALIDATE;

Prompt Constraint C_PSP_FRAUD_EVENT1;
ALTER TABLE PSP_FRAUD_EVENT
 DROP CONSTRAINT C_PSP_FRAUD_EVENT1;

ALTER TABLE PSP_FRAUD_EVENT
 ADD CONSTRAINT C_PSP_FRAUD_EVENT1
  CHECK (EVENT_TYPE_CD IN('FileIdChanged', 'SendEmailFailed', 'PaycheckRecalledAfterOffload', 'SendEmailSkipped', 'InvalidVendorEmail', 'ERLoanNOC', 'NewPSIDCreatedForExistingCustomer', 'PrimaryPrincipalNameChanged', 'PayeeBankAccountChange', 'BackdatePriorToProcessingStart', 'SubscriptionEndDateChanged', 'SUICreditsApplied', 'TrialAssetDetected', 'WelcomeEmail', 'AccountLocked', 'ACHReturnStatusChanged', 'EINChanged', 'ServiceStatusChange', 'CompanyBankAccountStatusChange', 'LimitViolation', 'ReversalOK', 'DDIncreasePayrollLimit', 'PayrollCancelled', 'Strike', 'ReversalRequested', 'TransmissionError', 'PINCreated', 'PINUpdated', 'PayrollSubmittedWithPendingNOC', 'BackdatedPayrollReceived', 'ACHReturn', 'FeeCreated', 'IncorrectPIN', 'BankAccountVerified', 'LegalNameChanged', 'LegalAddressChanged', 'CompanyBankAccountChange', 'NOC', 'ReversalReturn', 'FeeReturn', 'ERRefundReturn', 'CBAVerifyReturn', 'DDDebitReturn', 'NSF', 'DDReject', 'PayrollReceived', 'FirstPayrollReceived', 'ZeroPayrollReceived', 'PayrollRejected', 'CompanyContactEmailChanged', 'TaxExemptStatusChanged', 'CustomerSignedUp', 'PayrollCancelPending', 'FeeRefunded', 'CoaFeeAccountChange', 'CoaSalesTaxAccountChange', 'EmailAddressChanged', 'ManualRedebitCreated', 'LastChanceNotify', 'NonAchPaymentReceived', 'DBANameChanged', 'CompanyContactRoleChanged', 'CompanyContactPhoneChanged', 'CompanyContactAddressChanged', 'CompanyFundingModelChanged', 'PayrollAdminChanged', 'QuickBooksInfoChanged', 'WireExpected', 'EmployeePaidEvenDollarAmount', 'NumberOfPayrollsPerDayExceeded', 'EmployeePaidGreaterThanMax', 'TotalPayrollExceedsLimit', 'CurrentPayrollPercentageIncrease', 'SingleEmployeePercentageIncrease', 'PayrollProcessedTooSoon', 'CompanyMatchesFraudulentCompany', 'FraudFlagRemovedEvent', 'SalesTaxReturn', 'FeeOffloaded', 'RedebitAmountUpdated', 'RedebitDateUpdated', 'AS400Event', 'PayrollRecalled', 'PaycheckRecalled', 'ChangeRedebitToWireExpected', 'FeeRebilled', 'ManualNoteEvent', 'PINReset', 'KeyPairGenerated', 'HigherTokenSynced', 'AuthenticationFailed', 'NOCWithOutChanges', 'CompanyIndustryTypeChanged', 'PrimaryPrincipalSSNChanged', 'PrimaryPrincipalDOBChanged', 'EnrollmentStatusChanged', 'StateIdModified', 'TaxPaymentStatusChanged', 'PaymentMethodChanged'
, 'DepositFrequencyChanged', 'ThresholdExceeded', 'AssistedEmployeeMigrationComplete', 'OfferingUpdated', 'OfferClaimed', 'OfferRemoved', 'EmployeeInTermedCompany', 'EmployeeBankAccountInTermedCompany', 'PrefundingReceived', 'EmployeePaidTooManyTimes', 'EmployeePaidPercentageGreaterThanOthers', 'EmployeesPaidToSameBank', 'EmployeeBankAccountChangedSpikeInPay', 'EmployeesPaidToSameBankAccount', 'InvalidEmployeeInformation', 'PINUnlocked', 'Employee401kDataUploaded', 'EmployeeBankAccountChange', 'TotalBillPaymentExceedsLimit', 'PayeePaidGreaterThanMax', 'PayeePaidTooManyTimes', 'BillPaymentReceived', 'InvalidPaycheckInformation', 'VoidedPaycheckAlreadyOffloadedToTOK', 'DeletedPaycheckAlreadyOffloadedToTOK', 'TOKNotifiedOfCompanyFraud', 'BillPaymentOffloaded', 'PreOffload401kValidationAlert', 'BillPaymentRecalled', 'NonPrintChecks', 'PayrollReceivedCloud', 'PostOffload401kValidationAlert', 'InvalidSourceSystemTransmissionInformation', 'CloudResponse', 'InactivityDDPayrollAmountExceeded', 'InactivityBPPayrollAmountExceeded', 'AssistedPayrollItemMigrationComplete', 'ERPayableRefundCreated', 'MultipleCompanyLawsCreated', 'BalanceFileReceived', 'CompanyLawUpdated', 'PayrollReceivedPayCard', 'LiabilityAdjustmentCreated', 'PSPToAS400HoldSync', 'PSPToAS400HoldRemoveSync', 'OFXServiceActivated', 'PositiveCobraReceived', 'ManualLedgerEntry', 'PayrollTaxPaymentVoided', 'PayrollTaxPaymentReissued', 'ERPayableAppliedToBalanceDue', 'AIDUpdated', 'AssistedFailedEnrollment', 'AssistedPayrollConfirmation', 'EntitlementStateChanged', 'EntitlementUnitStatusChanged', 'SourceCompanyIdChanged', 'ServiceKeyUpdated', 'EntitlementCodeChanged', 'PriceTypeChanged', 'EntitlementCommunication', 'ManualDataSync', 'AccountingFinancialLedgerAdjustmentCreated', 'SUIEoqDebitCreated', 'SUIEoqCreditCreated', 'SUIImmediateDebitCreated', 'SUIImmediateCreditCreated', 'CompanyContactAdded', 'CompanyContactJobTitleChanged', 'PayrollSubmissionIncludedAllNewEmployees', 'PSIDMismatch', 'CompanyContactDeleted', 'CompanyContactNameChanged', 'CompanyContactFaxChanged', 'ERPenaltiesAndInterestRefundCreated', 'ERPenaltiesAndInterestRefundDebitCreated', 'EntitlementUnitAdded', 'UsageBilling25DaysIntoSubscription', 'UsageBilling15DaysIntoSubscription', 'CreditReduction', 'RequestProcessingFlagChanged'
, 'PayrollSubmittedWithEmployeeWithPendingReturn', 'DuplicatePayrollItemReceived', 'VmpSignUpEmployeeEmail', 'VmpSignUpEmployerEmail', 'ACHEnrollmentStatusChanged', 'PaystubCreated', 'AdditionalFilingAmount', 'BPIncreasePayrollLimit', 'AllowTransmissionsFlagChanged', 'MonthlyFeeCreated', 'EmployeeAdded', 'EmployeeDeleted', 'EmployeeUpdated', 'PayeeAdded', 'PayeeUpdated', 'DDMigration', 'SplitMMTReturn', 'RealmIdAdded', 'RealmIdUpdated', 'BillingRealmCreated', 'BillingRealmAttached', 'DataRealmAttached', 'GrantAttached', 'DGDeleteRequest', 'SMSToPSPSyncFailure', 'SMSToPSPSyncSuccess', 'CompanyBankAccountVBDStatusChange', 'ComplianceAddressChanged', 'DGAccessRequest', 'AutoEnabledVMP', 'ConsentChange', 'EmployeeInvited', 'EmployeeSignedUp', 'EmployeeBankAccountWalletSuccess', 'EmployeeBankAccountWalletFailure', 'CloneEmployeeWalletOnRealmChangeSuccess', 'CloneEmployeeWalletOnRealmChangeFailure', 'AddUserToRealmSuccess', 'AddUserToRealmFailure', 'AddUserToRealmOnRealmChangeSuccess', 'AddUserToRealmOnRealmChangeFailure', 'RiskProfileMigrated', 'RiskProfileUnMigrated', 'PSPToSMSMigration', 'PSPToSMSMigrationRevert', 'SMSRealmIdUpdated', 'UpdateConsumerRealmId', 'VendorBankAccountWalletFailure', 'VendorBankAccountWalletSuccess', 'CloneVendorWalletOnRealmChangeFailure', 'CloneVendorWalletOnRealmChangeSuccess')) ENABLE NOVALIDATE;

PROMPT finished DBUpgrade_002.022.008.006.sql