--
-- This script will be executed AFTER the automatically generated
-- C:\dev\PSP\rel-1.12\PSE\Domain\src\main\model\DBUpgrade_002.000.012.001.sql
--
-- Developers can hand code logic here for data migration purposes
--
INSERT INTO PSP_EDI_TAX_FILE
            (EDI_TAX_FILE_SEQ, VERSION, CREATOR_ID, CREATED_DATE, MODIFIER_ID, MODIFIED_DATE, REALM_ID, FILE_CODE, FILE_ID, FILE_NAME, FILE_TYPE, STATUS_CD, STATUS_EFFECTIVE_DATE, SUBMIT_DATE, SYSTEM_OWNER)
     SELECT EFTPS_FILE_SEQ, VERSION, CREATOR_ID, CREATED_DATE, MODIFIER_ID, MODIFIED_DATE, REALM_ID, FILE_CODE, FILE_ID, FILE_NAME, FILE_TYPE, STATUS_CD, STATUS_EFFECTIVE_DATE, SUBMIT_DATE, SYSTEM_OWNER
       FROM PSP_EFTPS_FILE;

Prompt COLUMN VERSION;
ALTER TABLE PSP_EFTPS_FILE DROP COLUMN VERSION;

Prompt COLUMN CREATOR_ID;
ALTER TABLE PSP_EFTPS_FILE DROP COLUMN CREATOR_ID;

Prompt COLUMN CREATED_DATE;
ALTER TABLE PSP_EFTPS_FILE DROP COLUMN CREATED_DATE;

Prompt COLUMN MODIFIER_ID;
ALTER TABLE PSP_EFTPS_FILE DROP COLUMN MODIFIER_ID;

Prompt COLUMN MODIFIED_DATE;
ALTER TABLE PSP_EFTPS_FILE DROP COLUMN MODIFIED_DATE;

Prompt COLUMN FILE_TYPE;
ALTER TABLE PSP_EFTPS_FILE DROP COLUMN FILE_TYPE;

Prompt COLUMN FILE_CODE;
ALTER TABLE PSP_EFTPS_FILE DROP COLUMN FILE_CODE;

Prompt COLUMN FILE_ID;
ALTER TABLE PSP_EFTPS_FILE DROP COLUMN FILE_ID;

Prompt COLUMN SYSTEM_OWNER;
ALTER TABLE PSP_EFTPS_FILE DROP COLUMN SYSTEM_OWNER;

Prompt COLUMN STATUS_CD;
ALTER TABLE PSP_EFTPS_FILE DROP COLUMN STATUS_CD;

Prompt COLUMN FILE_NAME;
ALTER TABLE PSP_EFTPS_FILE DROP COLUMN FILE_NAME;

Prompt COLUMN STATUS_EFFECTIVE_DATE;
ALTER TABLE PSP_EFTPS_FILE DROP COLUMN STATUS_EFFECTIVE_DATE;

Prompt COLUMN SUBMIT_DATE;
ALTER TABLE PSP_EFTPS_FILE DROP COLUMN SUBMIT_DATE;

ALTER TABLE PSP_EFTPS_FILE
 ADD CONSTRAINT PSP_EFTPS_FILE_FK2
 FOREIGN KEY (EFTPS_FILE_SEQ, REALM_ID)
 REFERENCES PSP_EDI_TAX_FILE (EDI_TAX_FILE_SEQ,REALM_ID);
 
COMMIT;