--
-- This script will be executed BEFORE the automatically generated
-- C:\Dev\PSP\dev\PSE\Domain\src\main\model\DBUpgrade_002.001.001.024.sql
--
-- Developers can hand code logic here for data migration purposes
--
