--
-- This script will be executed BEFORE the automatically generated
-- C:\Users\snasim\Documents\GitHub\Payroll-Services\PSE\domain\src\main\model\DBUpgrade_002.018.005.003.sql
--
-- Developers can hand code logic here for data migration purposes
--
