--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--
-- Please review the script before using it to make sure it won't
-- cause any unacceptable data loss.
--
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PSP_LOCAL 

Prompt Column VERSION;
ALTER TABLE PSP_AUTH_USER
MODIFY(VERSION  DEFAULT 0);

Prompt Column VERSION;
ALTER TABLE PSP_COMPANY
MODIFY(VERSION  DEFAULT 0);

Prompt Table PSP_AGENCY_RATE_REQUEST;
CREATE TABLE PSP_AGENCY_RATE_REQUEST
(
  AGENCY_RATE_REQUEST_SEQ  VARCHAR2(255 CHAR),
  VERSION                  NUMBER(19),
  CREATOR_ID               VARCHAR2(30 CHAR),
  CREATED_DATE             TIMESTAMP(6),
  MODIFIER_ID              VARCHAR2(30 CHAR),
  MODIFIED_DATE            TIMESTAMP(6),
  REALM_ID                 NUMBER(19)           DEFAULT -1,
  RECORD_COUNT             NUMBER(10),
  STATUS                   VARCHAR2(255 CHAR),
  YEAR_QUARTER             VARCHAR2(30 CHAR),
  AGENCY_FK                VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_AGENCY_RATE_REQUEST_FK1;
CREATE INDEX PSP_AGENCY_RATE_REQUEST_FK1 ON PSP_AGENCY_RATE_REQUEST
(AGENCY_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_AGENCY_RATE_REQUEST
 ADD PRIMARY KEY
  (AGENCY_RATE_REQUEST_SEQ, REALM_ID)
  USING INDEX;

Prompt Table PSP_COMPANY_RATE_REQUEST;
CREATE TABLE PSP_COMPANY_RATE_REQUEST
(
  COMPANY_RATE_REQUEST_SEQ  VARCHAR2(255 CHAR),
  VERSION                   NUMBER(19),
  CREATOR_ID                VARCHAR2(30 CHAR),
  CREATED_DATE              TIMESTAMP(6),
  MODIFIER_ID               VARCHAR2(30 CHAR),
  MODIFIED_DATE             TIMESTAMP(6),
  REALM_ID                  NUMBER(19)          DEFAULT -1,
  STATUS_MESSAGE            VARCHAR2(256 CHAR),
  STATUS                    VARCHAR2(255 CHAR),
  AGENCY_RATE_REQUEST_FK    VARCHAR2(255 CHAR),
  COMPANY_AGENCY_FK         VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_COMPANY_RATE_REQUEST_FK1;
CREATE INDEX PSP_COMPANY_RATE_REQUEST_FK1 ON PSP_COMPANY_RATE_REQUEST
(AGENCY_RATE_REQUEST_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_COMPANY_RATE_REQUEST_FK2;
CREATE INDEX PSP_COMPANY_RATE_REQUEST_FK2 ON PSP_COMPANY_RATE_REQUEST
(COMPANY_AGENCY_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_COMPANY_RATE_REQUEST
 ADD PRIMARY KEY
  (COMPANY_RATE_REQUEST_SEQ, REALM_ID)
  USING INDEX;

Prompt Column VERSION;
ALTER TABLE PSP_ENTITLEMENT_UNIT
MODIFY(VERSION  DEFAULT 0);

ALTER TABLE PSP_AGENCY_RATE_REQUEST
 ADD CONSTRAINT PSP_AGENCY_RATE_REQUEST_FK1 
  FOREIGN KEY (AGENCY_FK, REALM_ID) 
  REFERENCES PSP_AGENCY (AGENCY_ID,REALM_ID);

ALTER TABLE PSP_COMPANY_RATE_REQUEST
 ADD CONSTRAINT PSP_COMPANY_RATE_REQUEST_FK1 
  FOREIGN KEY (AGENCY_RATE_REQUEST_FK, REALM_ID) 
  REFERENCES PSP_AGENCY_RATE_REQUEST (AGENCY_RATE_REQUEST_SEQ,REALM_ID);

ALTER TABLE PSP_COMPANY_RATE_REQUEST
 ADD CONSTRAINT PSP_COMPANY_RATE_REQUEST_FK2 
  FOREIGN KEY (COMPANY_AGENCY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY_AGENCY (COMPANY_AGENCY_SEQ,REALM_ID);

PROMPT finishedDBUpgrade_002.013.002.001.sql