--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--
-- Please review the script before using it to make sure it won't
-- cause any unacceptable data loss.
--
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PSP_LOCAL 

Prompt Column VERSION;
ALTER TABLE PSP_AUTH_USER
MODIFY(VERSION  DEFAULT 0);

Prompt Column VERSION;
ALTER TABLE PSP_COMPANY
MODIFY(VERSION  DEFAULT 0);

Prompt Column VERSION;
ALTER TABLE PSP_ENTITLEMENT_UNIT
MODIFY(VERSION  DEFAULT 0);

Prompt Table PSP_LAW_RATE_RANGE;
CREATE TABLE PSP_LAW_RATE_RANGE
(
  LAW_RATE_RANGE_ID  VARCHAR2(50 CHAR),
  VERSION            NUMBER(19),
  REALM_ID           NUMBER(19)                 DEFAULT -1,
  MIN_RATE           NUMBER(19,7),
  MAX_RATE           NUMBER(19,7),
  PRECISION          NUMBER(10),
  LAW_FK             VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_LAW_RATE_RANGE_FK1;
CREATE INDEX PSP_LAW_RATE_RANGE_FK1 ON PSP_LAW_RATE_RANGE
(LAW_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_LAW_RATE_RANGE
 ADD PRIMARY KEY
  (LAW_RATE_RANGE_ID, REALM_ID)
  USING INDEX;

Prompt Table PSP_LAW_RATE_VALUE;
CREATE TABLE PSP_LAW_RATE_VALUE
(
  LAW_RATE_VALUE_ID  VARCHAR2(50 CHAR),
  VERSION            NUMBER(19),
  REALM_ID           NUMBER(19)                 DEFAULT -1,
  RATE               NUMBER(19,7),
  LAW_FK             VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_LAW_RATE_VALUE_FK1;
CREATE INDEX PSP_LAW_RATE_VALUE_FK1 ON PSP_LAW_RATE_VALUE
(LAW_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_LAW_RATE_VALUE
 ADD PRIMARY KEY
  (LAW_RATE_VALUE_ID, REALM_ID)
  USING INDEX;

Prompt Column VERSION;
ALTER TABLE PSP_QUICKBOOKS_INFO
MODIFY(VERSION  DEFAULT 0);

ALTER TABLE PSP_LAW_RATE_RANGE
 ADD CONSTRAINT PSP_LAW_RATE_RANGE_FK1 
  FOREIGN KEY (LAW_FK, REALM_ID) 
  REFERENCES PSP_LAW (LAW_ID,REALM_ID);

ALTER TABLE PSP_LAW_RATE_VALUE
 ADD CONSTRAINT PSP_LAW_RATE_VALUE_FK1 
  FOREIGN KEY (LAW_FK, REALM_ID) 
  REFERENCES PSP_LAW (LAW_ID,REALM_ID);

PROMPT finishedDBUpgrade_002.013.003.005.sql