--
-- This script will be executed AFTER the automatically generated
-- C:\Dev\psp\Payroll-Services\PSE\domain\src\main\model\DBUpgrade_002.018.011.001.sql
--
-- Developers can hand code logic here for data migration purposes
--
