--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--
-- Please review the script before using it to make sure it won't
-- cause any unacceptable data loss.
--
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PSP_LOCAL 

Prompt Column COMPANY_LAW_FK;
ALTER TABLE PSP_EMPLOYEE_LAW_QTR_TOTALS
 ADD (COMPANY_LAW_FK  VARCHAR2(255 CHAR));

Prompt Column COMPANY_LAW_FK;
ALTER TABLE PSP_EMPLOYEE_W2_TOTALS
 ADD (COMPANY_LAW_FK  VARCHAR2(255 CHAR));

Prompt Index PSP_EMPLOYEE_W2_TOTALS_FK6;
CREATE INDEX PSP_EMPLOYEE_W2_TOTALS_FK6 ON PSP_EMPLOYEE_W2_TOTALS
(COMPANY_LAW_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_EMPLOYEE_LAW_QTR_TOTAL_FK6;
CREATE INDEX PSP_EMPLOYEE_LAW_QTR_TOTAL_FK6 ON PSP_EMPLOYEE_LAW_QTR_TOTALS
(COMPANY_LAW_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_EMPLOYEE_LAW_QTR_TOTALS
 ADD CONSTRAINT PSP_EMPLOYEE_LAW_QTR_TOTAL_FK6 
  FOREIGN KEY (COMPANY_LAW_FK, REALM_ID) 
  REFERENCES PSP_COMPANY_LAW (COMPANY_LAW_SEQ,REALM_ID);

ALTER TABLE PSP_EMPLOYEE_W2_TOTALS
 ADD CONSTRAINT PSP_EMPLOYEE_W2_TOTALS_FK6 
  FOREIGN KEY (COMPANY_LAW_FK, REALM_ID) 
  REFERENCES PSP_COMPANY_LAW (COMPANY_LAW_SEQ,REALM_ID);

PROMPT finishedDBUpgrade_002.012.011.001.sql