--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--
-- Please review the script before using it to make sure it won't
-- cause any unacceptable data loss.
--
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PSP_LOCAL 

Prompt Table PSP_PAYCHECK_USAGE_HIST;
CREATE TABLE PSP_PAYCHECK_USAGE_HIST
(
  PAYCHECK_USAGE_HIST_SEQ  VARCHAR2(255 CHAR)   NOT NULL,
  VERSION                  NUMBER(19)           NOT NULL,
  CREATOR_ID               VARCHAR2(30 CHAR),
  CREATED_DATE             TIMESTAMP(6)         NOT NULL,
  MODIFIER_ID              VARCHAR2(30 CHAR),
  MODIFIED_DATE            TIMESTAMP(6)         NOT NULL,
  REALM_ID                 NUMBER(19)           DEFAULT -1                    NOT NULL,
  NOTES                    VARCHAR2(4000 CHAR),
  EMPLOYEE_USAGE_FK        VARCHAR2(255 CHAR)   NOT NULL,
  PAYCHECK_USAGE_FK        VARCHAR2(255 CHAR)   NOT NULL
)
NOPARALLEL;

Prompt Index PSP_PAYCHECK_USAGE_HIST_FK1;
CREATE INDEX PSP_PAYCHECK_USAGE_HIST_FK1 ON PSP_PAYCHECK_USAGE_HIST
(EMPLOYEE_USAGE_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_PAYCHECK_USAGE_HIST_FK2;
CREATE INDEX PSP_PAYCHECK_USAGE_HIST_FK2 ON PSP_PAYCHECK_USAGE_HIST
(PAYCHECK_USAGE_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_PAYCHECK_USAGE_HIST
 ADD PRIMARY KEY
  (PAYCHECK_USAGE_HIST_SEQ, REALM_ID)
  USING INDEX;

Prompt Constraint C_PSP_PAYCHECK_USAGE1;
ALTER TABLE PSP_PAYCHECK_USAGE
 DROP CONSTRAINT C_PSP_PAYCHECK_USAGE1;

ALTER TABLE PSP_PAYCHECK_USAGE
 ADD CONSTRAINT C_PSP_PAYCHECK_USAGE1
  CHECK (REASON_FOR_FREE_CHARGE IN('AlreadyBilled', 'UsageTransfer', 'TrialUpgrade', 'None', 'Trial', 'Upgrade'));

ALTER TABLE PSP_PAYCHECK_USAGE_HIST
 ADD CONSTRAINT PSP_PAYCHECK_USAGE_HIST_FK1 
  FOREIGN KEY (EMPLOYEE_USAGE_FK, REALM_ID) 
  REFERENCES PSP_EMPLOYEE_USAGE (EMPLOYEE_USAGE_SEQ,REALM_ID);

ALTER TABLE PSP_PAYCHECK_USAGE_HIST
 ADD CONSTRAINT PSP_PAYCHECK_USAGE_HIST_FK2 
  FOREIGN KEY (PAYCHECK_USAGE_FK, REALM_ID) 
  REFERENCES PSP_PAYCHECK_USAGE (PAYCHECK_USAGE_SEQ,REALM_ID);

PROMPT finished DBUpgrade_002.019.003.001.sql