--
-- This script will be executed AFTER the automatically generated
-- C:\dev\PSP\rel-1.11\PSE\Domain\src\main\model\DBUpgrade_002.000.011.002.sql
--
-- Developers can hand code logic here for data migration purposes
--
