--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--                                                                      --
-- Please review the script before using it to make sure it won't       --
-- cause any unacceptable data loss.                                    --
--                                                                      --
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
Prompt TABLE PSP_EDI_TAX_FILE;
--
-- PSP_EDI_TAX_FILE  (Table) 
--
CREATE TABLE PSP_EDI_TAX_FILE
(
  EDI_TAX_FILE_SEQ       VARCHAR2(255 CHAR)     NOT NULL,
  VERSION                NUMBER(19)             NOT NULL,
  CREATOR_ID             VARCHAR2(30 CHAR),
  CREATED_DATE           TIMESTAMP(6)           NOT NULL,
  MODIFIER_ID            VARCHAR2(30 CHAR),
  MODIFIED_DATE          TIMESTAMP(6)           NOT NULL,
  REALM_ID               NUMBER(19)             DEFAULT -1                    NOT NULL,
  FILE_CODE              NUMBER(10),
  FILE_ID                NUMBER(10),
  FILE_NAME              VARCHAR2(4000 CHAR),
  FILE_TYPE              VARCHAR2(255 CHAR),
  STATUS_CD              VARCHAR2(255 CHAR),
  STATUS_EFFECTIVE_DATE  TIMESTAMP(6),
  SUBMIT_DATE            TIMESTAMP(6),
  SYSTEM_OWNER           VARCHAR2(255 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE PSP_EDI_TAX_FILE
 ADD PRIMARY KEY
 (EDI_TAX_FILE_SEQ, REALM_ID);

Prompt TABLE PSP_STATE_EDI_TAX_FILE;
--
-- PSP_STATE_EDI_TAX_FILE  (Table) 
--
CREATE TABLE PSP_STATE_EDI_TAX_FILE
(
  STATE_EDI_TAX_FILE_SEQ  VARCHAR2(255 CHAR)    NOT NULL,
  REALM_ID                NUMBER(19)            DEFAULT -1                    NOT NULL,
  ACK_FILE_FK             VARCHAR2(255 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE PSP_STATE_EDI_TAX_FILE
 ADD PRIMARY KEY
 (STATE_EDI_TAX_FILE_SEQ, REALM_ID);


Prompt INDEX PSP_STATE_EDI_TAX_FILE_FK2;
--
-- PSP_STATE_EDI_TAX_FILE_FK2  (Index) 
--
CREATE INDEX PSP_STATE_EDI_TAX_FILE_FK2 ON PSP_STATE_EDI_TAX_FILE
(ACK_FILE_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt TABLE PSP_EDI_PAYMENT_DETAIL;
--
-- PSP_EDI_PAYMENT_DETAIL  (Table) 
--
CREATE TABLE PSP_EDI_PAYMENT_DETAIL
(
  EDI_PAYMENT_DETAIL_SEQ         VARCHAR2(255 CHAR) NOT NULL,
  VERSION                        NUMBER(19)     NOT NULL,
  CREATOR_ID                     VARCHAR2(30 CHAR),
  CREATED_DATE                   TIMESTAMP(6)   NOT NULL,
  MODIFIER_ID                    VARCHAR2(30 CHAR),
  MODIFIED_DATE                  TIMESTAMP(6)   NOT NULL,
  REALM_ID                       NUMBER(19)     DEFAULT -1                    NOT NULL,
  PAYMENT_DETAILS                VARCHAR2(4000 CHAR),
  PAYMENT_DUE_DATE               TIMESTAMP(6),
  PAYMENT_INITIATION_DATE        TIMESTAMP(6),
  PAYMENT_SETTLEMENT_DATE        TIMESTAMP(6),
  PERIOD_BEGIN_DATE              TIMESTAMP(6),
  PERIOD_END_DATE                TIMESTAMP(6),
  RESPONSE_DATE                  TIMESTAMP(6),
  STATUS_EFFECTIVE_DATE          TIMESTAMP(6),
  TAX_TYPE_CODE                  VARCHAR2(4000 CHAR),
  CONFIRMATION_NUMBER            VARCHAR2(4000 CHAR),
  TRANSACTION_SET_ID             NUMBER(10),
  STATUS_CD                      VARCHAR2(255 CHAR),
  TRANSACTION_ID                 VARCHAR2(4000 CHAR),
  ERROR_CD                       VARCHAR2(4000 CHAR),
  ERROR_MESSAGE                  VARCHAR2(4000 CHAR),
  FED_TAX_ID                     VARCHAR2(4000 CHAR),
  GROUP_ID                       NUMBER(10),
  GROUP_TRANSACTION_TIME         VARCHAR2(4000 CHAR),
  PAYMENT_AMOUNT                 NUMBER(19,4),
  PARENT_FILE_FK                 VARCHAR2(255 CHAR) NOT NULL,
  RESPONSE_FILE_FK               VARCHAR2(255 CHAR),
  MONEY_MOVEMENT_TRANSACTION_FK  VARCHAR2(255 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE PSP_EDI_PAYMENT_DETAIL
 ADD PRIMARY KEY
 (EDI_PAYMENT_DETAIL_SEQ, REALM_ID);

Prompt INDEX PSP_EDI_PAYMENT_DETAIL_FK3;
--
-- PSP_EDI_PAYMENT_DETAIL_FK3  (Index) 
--
CREATE INDEX PSP_EDI_PAYMENT_DETAIL_FK3 ON PSP_EDI_PAYMENT_DETAIL
(MONEY_MOVEMENT_TRANSACTION_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt INDEX PSP_EDI_PAYMENT_DETAIL_FK2;
--
-- PSP_EDI_PAYMENT_DETAIL_FK2  (Index) 
--
CREATE INDEX PSP_EDI_PAYMENT_DETAIL_FK2 ON PSP_EDI_PAYMENT_DETAIL
(RESPONSE_FILE_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt INDEX PSP_EDI_PAYMENT_DETAIL_FK1;
--
-- PSP_EDI_PAYMENT_DETAIL_FK1  (Index) 
--
CREATE INDEX PSP_EDI_PAYMENT_DETAIL_FK1 ON PSP_EDI_PAYMENT_DETAIL
(PARENT_FILE_FK, REALM_ID)
LOGGING
NOPARALLEL;

ALTER TABLE PSP_STATE_EDI_TAX_FILE
 ADD CONSTRAINT PSP_STATE_EDI_TAX_FILE_FK2 
 FOREIGN KEY (ACK_FILE_FK, REALM_ID) 
 REFERENCES PSP_STATE_EDI_TAX_FILE (STATE_EDI_TAX_FILE_SEQ,REALM_ID);

ALTER TABLE PSP_STATE_EDI_TAX_FILE
 ADD CONSTRAINT PSP_STATE_EDI_TAX_FILE_FK1 
 FOREIGN KEY (STATE_EDI_TAX_FILE_SEQ, REALM_ID) 
 REFERENCES PSP_EDI_TAX_FILE (EDI_TAX_FILE_SEQ,REALM_ID);

ALTER TABLE PSP_EDI_PAYMENT_DETAIL
 ADD CONSTRAINT PSP_EDI_PAYMENT_DETAIL_FK1 
 FOREIGN KEY (PARENT_FILE_FK, REALM_ID) 
 REFERENCES PSP_STATE_EDI_TAX_FILE (STATE_EDI_TAX_FILE_SEQ,REALM_ID);

ALTER TABLE PSP_EDI_PAYMENT_DETAIL
 ADD CONSTRAINT PSP_EDI_PAYMENT_DETAIL_FK2 
 FOREIGN KEY (RESPONSE_FILE_FK, REALM_ID) 
 REFERENCES PSP_STATE_EDI_TAX_FILE (STATE_EDI_TAX_FILE_SEQ,REALM_ID);

ALTER TABLE PSP_EDI_PAYMENT_DETAIL
 ADD CONSTRAINT PSP_EDI_PAYMENT_DETAIL_FK3 
 FOREIGN KEY (MONEY_MOVEMENT_TRANSACTION_FK, REALM_ID) 
 REFERENCES PSP_MONEY_MOVEMENT_TRANSACTION (MONEY_MOVEMENT_TRANSACTION_SEQ,REALM_ID);


PROMPT finishedDBUpgrade_002.000.012.001.sql