--
-- This script will be executed BEFORE the automatically generated
-- C:\Users\rtbteam\Payroll-Services\PSE\domain\src\main\model\DBUpgrade_002.019.011.001.sql
--
-- Developers can hand code logic here for data migration purposes
--
