--
-- This script will be executed BEFORE the automatically generated
-- C:\Users\rtbteam\dt-payroll-svc\app\PSE\domain\src\main\model\DBUpgrade_002.021.011.001.sql
--
-- Developers can hand code logic here for data migration purposes
--
