--
-- This script will be executed BEFORE the automatically generated
-- D:\Dev\PSP\dev-2012R7\PSE\Domain\src\main\model\DBUpgrade_002.001.001.006.sql
--
-- Developers can hand code logic here for data migration purposes
--
