--
-- This script will be executed BEFORE the automatically generated
-- C:\dev\depot\psp\dev-maven\PSE\domain\src\main\model\DBUpgrade_002.016.011.001.sql
--
-- Developers can hand code logic here for data migration purposes
--
