--
-- This script will be executed BEFORE the automatically generated
-- D:\dev\PSP\rel-1.11\PSE\Domain\src\main\model\DBUpgrade_002.000.011.007.sql
--
-- Developers can hand code logic here for data migration purposes
--
