--
-- This script will be executed AFTER the automatically generated
-- D:\dev\PSP\rel-1.6\PSE\Domain\src\main\model\DBUpgrade_002.000.000.036.sql
--
-- Developers can hand code logic here for data migration purposes
--
