--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--                                                                      --
-- Please review the script before using it to make sure it won't       --
-- cause any unacceptable data loss.                                    --
--                                                                      --
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 

select to_char(sysdate, 'MM/DD/YYYY HH24:MI:SS') AS "START TIME" from dual;

Prompt DROP INDEX PSP_RAFENROLLMENT_BATCH_FK1;
DROP INDEX PSP_RAFENROLLMENT_BATCH_FK1;

Prompt DROP INDEX PSP_RAFENROLLMENT_BATCH_FK2;
DROP INDEX PSP_RAFENROLLMENT_BATCH_FK2;

Prompt DROP TABLE PSP_RAFENROLLMENT_BATCH_ASSOC;
ALTER TABLE PSP_RAFENROLLMENT_BATCH_ASSOC
 DROP PRIMARY KEY CASCADE;
DROP TABLE PSP_RAFENROLLMENT_BATCH_ASSOC CASCADE CONSTRAINTS;

Prompt DROP TABLE PSP_RAFENROLLMENT_BATCH;
ALTER TABLE PSP_RAFENROLLMENT_BATCH
 DROP PRIMARY KEY CASCADE;
DROP TABLE PSP_RAFENROLLMENT_BATCH CASCADE CONSTRAINTS;

Prompt TABLE PSP_RAFENROLLMENT_FILE;
--
-- PSP_RAFENROLLMENT_FILE  (Table) 
--
CREATE TABLE PSP_RAFENROLLMENT_FILE
(
  RAFENROLLMENT_FILE_SEQ  VARCHAR2(255 CHAR)    NOT NULL,
  VERSION                 NUMBER(19)            NOT NULL,
  CREATOR_ID              VARCHAR2(30 CHAR),
  CREATED_DATE            TIMESTAMP(6)          NOT NULL,
  MODIFIER_ID             VARCHAR2(30 CHAR),
  MODIFIED_DATE           TIMESTAMP(6)          NOT NULL,
  REALM_ID                NUMBER(19)            DEFAULT -1                    NOT NULL,
  STATUS                  VARCHAR2(255 CHAR),
  R_A_F_ACTION_CODE       VARCHAR2(255 CHAR),
  FILE_NAME               VARCHAR2(4000 CHAR),
  STATUS_EFFECTIVE_DATE   TIMESTAMP(6),
  EMAIL_FILE_NAME         VARCHAR2(4000 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

Prompt COLUMN PAYMENT_TEMPLATE_FK;
ALTER TABLE PSP_FORM_TEMPLATE
 ADD (PAYMENT_TEMPLATE_FK  VARCHAR2(255 CHAR));

Prompt INDEX PSP_FORM_TEMPLATE_FK2;
--
-- PSP_FORM_TEMPLATE_FK2  (Index) 
--
CREATE INDEX PSP_FORM_TEMPLATE_FK2 ON PSP_FORM_TEMPLATE
(PAYMENT_TEMPLATE_FK, REALM_ID)
LOGGING
NOPARALLEL;

ALTER TABLE PSP_MONEY_MOVEMENT_TRANSACTION
 DROP CONSTRAINT PSP_MONEY_MOVEMENT_TRANSAC_FK8;
 


ALTER TABLE PSP_COMPANY_AGENCY
 DROP CONSTRAINT PSP_COMPANY_AGENCY_FK3;
 
Prompt COLUMN FORM_TEMPLATE_FK;
ALTER TABLE PSP_COMPANY_AGENCY DROP COLUMN FORM_TEMPLATE_FK;

Prompt COLUMN SOURCE_BANK_ACCOUNT_NAME;
ALTER TABLE PSP_COMPANY_BANK_ACCOUNT
MODIFY(SOURCE_BANK_ACCOUNT_NAME VARCHAR2(128 CHAR));


Prompt COLUMN TYPE;
ALTER TABLE PSP_LIABILITY_CHECK
 ADD (TYPE  VARCHAR2(255 CHAR));

Prompt COLUMN PAYROLL_RUN_FK;
ALTER TABLE PSP_LIABILITY_CHECK
 ADD (PAYROLL_RUN_FK  VARCHAR2(255 CHAR));

ALTER TABLE PSP_LIABILITY_CHECK
 DROP CONSTRAINT PSP_LIABILITY_CHECK_FK2;
 
Prompt COLUMN QBDT_TRANSACTION_INFO_FK;
ALTER TABLE PSP_LIABILITY_CHECK DROP COLUMN QBDT_TRANSACTION_INFO_FK;

Prompt INDEX PSP_LIABILITY_CHECK_FK2;
--
-- PSP_LIABILITY_CHECK_FK2  (Index) 
--
CREATE INDEX PSP_LIABILITY_CHECK_FK2 ON PSP_LIABILITY_CHECK
(PAYROLL_RUN_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt TABLE PSP_COMPANYAGENCY_FRMTEMPLATE;
--
-- PSP_COMPANYAGENCY_FRMTEMPLATE  (Table) 
--
CREATE TABLE PSP_COMPANYAGENCY_FRMTEMPLATE
(
  COMPANYAGENCY_FRMTEMPLATE_SEQ  VARCHAR2(255 CHAR) NOT NULL,
  VERSION                        NUMBER(19)     NOT NULL,
  CREATOR_ID                     VARCHAR2(30 CHAR),
  CREATED_DATE                   TIMESTAMP(6)   NOT NULL,
  MODIFIER_ID                    VARCHAR2(30 CHAR),
  MODIFIED_DATE                  TIMESTAMP(6)   NOT NULL,
  REALM_ID                       NUMBER(19)     DEFAULT -1                    NOT NULL,
  EFFECTIVE_DATE                 TIMESTAMP(6),
  INVALID_DATE                   TIMESTAMP(6),
  COMPANY_AGENCY_FK              VARCHAR2(255 CHAR),
  FORM_TEMPLATE_FK               VARCHAR2(255 CHAR) NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

Prompt TABLE PSP_RAFENROLLMENT_DETAIL;
--
-- PSP_RAFENROLLMENT_DETAIL  (Table) 
--
CREATE TABLE PSP_RAFENROLLMENT_DETAIL
(
  RAFENROLLMENT_DETAIL_SEQ  VARCHAR2(255 CHAR)  NOT NULL,
  VERSION                   NUMBER(19)          NOT NULL,
  CREATOR_ID                VARCHAR2(30 CHAR),
  CREATED_DATE              TIMESTAMP(6)        NOT NULL,
  MODIFIER_ID               VARCHAR2(30 CHAR),
  MODIFIED_DATE             TIMESTAMP(6)        NOT NULL,
  REALM_ID                  NUMBER(19)          DEFAULT -1                    NOT NULL,
  FED_TAXID                 VARCHAR2(4000 CHAR),
  LEGAL_NAME                VARCHAR2(4000 CHAR),
  LEGAL_STREET_ADDRESS      VARCHAR2(4000 CHAR),
  LEGAL_CITY                VARCHAR2(4000 CHAR),
  LEGAL_STATE               VARCHAR2(4000 CHAR),
  LEGAL_ZIP_CODE            VARCHAR2(4000 CHAR),
  YEAR                      VARCHAR2(4000 CHAR),
  QUARTER                   VARCHAR2(4000 CHAR),
  R_A_F_ENROLLMENT_FK       VARCHAR2(255 CHAR)  NOT NULL,
  ENROLLMENT_FILE_FK        VARCHAR2(255 CHAR)  NOT NULL,
  DELETE_FILE_FK            VARCHAR2(255 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE PSP_LIABILITY_CHECK_LINE
 DROP CONSTRAINT PSP_LIABILITY_CHECK_LINE_FK3;
 
Prompt COLUMN QBDT_TRANSACTION_INFO_FK;
ALTER TABLE PSP_LIABILITY_CHECK_LINE DROP COLUMN QBDT_TRANSACTION_INFO_FK;

Prompt INDEX PSP_COMPANY_AGENCY_FORM_TE_FK2;
--
-- PSP_COMPANY_AGENCY_FORM_TE_FK2  (Index) 
--
CREATE INDEX PSP_COMPANY_AGENCY_FORM_TE_FK2 ON PSP_COMPANYAGENCY_FRMTEMPLATE
(FORM_TEMPLATE_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt INDEX PSP_COMPANY_AGENCY_FORM_TE_FK1;
--
-- PSP_COMPANY_AGENCY_FORM_TE_FK1  (Index) 
--
CREATE INDEX PSP_COMPANY_AGENCY_FORM_TE_FK1 ON PSP_COMPANYAGENCY_FRMTEMPLATE
(COMPANY_AGENCY_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt INDEX PSP_RAFENROLLMENT_DETAIL_FK3;
--
-- PSP_RAFENROLLMENT_DETAIL_FK3  (Index) 
--
CREATE INDEX PSP_RAFENROLLMENT_DETAIL_FK3 ON PSP_RAFENROLLMENT_DETAIL
(DELETE_FILE_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt INDEX PSP_RAFENROLLMENT_DETAIL_FK2;
--
-- PSP_RAFENROLLMENT_DETAIL_FK2  (Index) 
--
CREATE INDEX PSP_RAFENROLLMENT_DETAIL_FK2 ON PSP_RAFENROLLMENT_DETAIL
(ENROLLMENT_FILE_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt INDEX PSP_RAFENROLLMENT_DETAIL_FK1;
--
-- PSP_RAFENROLLMENT_DETAIL_FK1  (Index) 
--
CREATE INDEX PSP_RAFENROLLMENT_DETAIL_FK1 ON PSP_RAFENROLLMENT_DETAIL
(R_A_F_ENROLLMENT_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt COLUMN INVALID_DATE;
ALTER TABLE PSP_COMPANY_LAW_RATE
 ADD (INVALID_DATE  TIMESTAMP(6));

Prompt COLUMN LIABILITY_CHECK_FK;
ALTER TABLE PSP_QBDT_TRANSACTION_INFO
 ADD (LIABILITY_CHECK_FK  VARCHAR2(255 CHAR));

Prompt COLUMN LIABILITY_CHECK_LINE_FK;
ALTER TABLE PSP_QBDT_TRANSACTION_INFO
 ADD (LIABILITY_CHECK_LINE_FK  VARCHAR2(255 CHAR));

Prompt COLUMN MONEY_MOVEMENT_TRANSACTION_FK;
ALTER TABLE PSP_QBDT_TRANSACTION_INFO
 ADD (MONEY_MOVEMENT_TRANSACTION_FK  VARCHAR2(255 CHAR));

Prompt INDEX PSP_QBDT_TRANSACTION_INFO_FK3;
--
-- PSP_QBDT_TRANSACTION_INFO_FK3  (Index) 
--
CREATE INDEX PSP_QBDT_TRANSACTION_INFO_FK3 ON PSP_QBDT_TRANSACTION_INFO
(MONEY_MOVEMENT_TRANSACTION_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt INDEX PSP_QBDT_TRANSACTION_INFO_FK2;
--
-- PSP_QBDT_TRANSACTION_INFO_FK2  (Index) 
--
CREATE INDEX PSP_QBDT_TRANSACTION_INFO_FK2 ON PSP_QBDT_TRANSACTION_INFO
(LIABILITY_CHECK_LINE_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt INDEX PSP_QBDT_TRANSACTION_INFO_FK1;
--
-- PSP_QBDT_TRANSACTION_INFO_FK1  (Index) 
--
CREATE INDEX PSP_QBDT_TRANSACTION_INFO_FK1 ON PSP_QBDT_TRANSACTION_INFO
(LIABILITY_CHECK_FK, REALM_ID)
LOGGING
NOPARALLEL;

ALTER TABLE PSP_FORM_TEMPLATE
 ADD CONSTRAINT PSP_FORM_TEMPLATE_FK2 
 FOREIGN KEY (PAYMENT_TEMPLATE_FK, REALM_ID) 
 REFERENCES PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD,REALM_ID);

ALTER TABLE PSP_LIABILITY_CHECK
 ADD CONSTRAINT PSP_LIABILITY_CHECK_FK2 
 FOREIGN KEY (PAYROLL_RUN_FK, REALM_ID) 
 REFERENCES PSP_PAYROLL_RUN (PAYROLL_RUN_SEQ,REALM_ID);

ALTER TABLE PSP_QBDT_TRANSACTION_INFO
 ADD CONSTRAINT PSP_QBDT_TRANSACTION_INFO_FK1 
 FOREIGN KEY (LIABILITY_CHECK_FK, REALM_ID) 
 REFERENCES PSP_LIABILITY_CHECK (LIABILITY_CHECK_SEQ,REALM_ID);

ALTER TABLE PSP_QBDT_TRANSACTION_INFO
 ADD CONSTRAINT PSP_QBDT_TRANSACTION_INFO_FK2 
 FOREIGN KEY (LIABILITY_CHECK_LINE_FK, REALM_ID) 
 REFERENCES PSP_LIABILITY_CHECK_LINE (LIABILITY_CHECK_LINE_SEQ,REALM_ID);

ALTER TABLE PSP_QBDT_TRANSACTION_INFO
 ADD CONSTRAINT PSP_QBDT_TRANSACTION_INFO_FK3 
 FOREIGN KEY (MONEY_MOVEMENT_TRANSACTION_FK, REALM_ID) 
 REFERENCES PSP_MONEY_MOVEMENT_TRANSACTION (MONEY_MOVEMENT_TRANSACTION_SEQ,REALM_ID);

ALTER TABLE PSP_RAFENROLLMENT_FILE
 ADD PRIMARY KEY
 (RAFENROLLMENT_FILE_SEQ, REALM_ID);

ALTER TABLE PSP_COMPANYAGENCY_FRMTEMPLATE
 ADD PRIMARY KEY
 (COMPANYAGENCY_FRMTEMPLATE_SEQ, REALM_ID);

ALTER TABLE PSP_COMPANYAGENCY_FRMTEMPLATE
 ADD CONSTRAINT PSP_COMPANY_AGENCY_FORM_TE_FK1 
 FOREIGN KEY (COMPANY_AGENCY_FK, REALM_ID) 
 REFERENCES PSP_COMPANY_AGENCY (COMPANY_AGENCY_SEQ,REALM_ID);

ALTER TABLE PSP_COMPANYAGENCY_FRMTEMPLATE
 ADD CONSTRAINT PSP_COMPANY_AGENCY_FORM_TE_FK2 
 FOREIGN KEY (FORM_TEMPLATE_FK, REALM_ID) 
 REFERENCES PSP_FORM_TEMPLATE (FORM_TEMPLATE_CD,REALM_ID);

ALTER TABLE PSP_RAFENROLLMENT_DETAIL
 ADD PRIMARY KEY
 (RAFENROLLMENT_DETAIL_SEQ, REALM_ID);

ALTER TABLE PSP_RAFENROLLMENT_DETAIL
 ADD CONSTRAINT PSP_RAFENROLLMENT_DETAIL_FK1 
 FOREIGN KEY (R_A_F_ENROLLMENT_FK, REALM_ID) 
 REFERENCES PSP_RAFENROLLMENT (RAFENROLLMENT_SEQ,REALM_ID);

ALTER TABLE PSP_RAFENROLLMENT_DETAIL
 ADD CONSTRAINT PSP_RAFENROLLMENT_DETAIL_FK2 
 FOREIGN KEY (ENROLLMENT_FILE_FK, REALM_ID) 
 REFERENCES PSP_RAFENROLLMENT_FILE (RAFENROLLMENT_FILE_SEQ,REALM_ID);

ALTER TABLE PSP_RAFENROLLMENT_DETAIL
 ADD CONSTRAINT PSP_RAFENROLLMENT_DETAIL_FK3 
 FOREIGN KEY (DELETE_FILE_FK, REALM_ID) 
 REFERENCES PSP_RAFENROLLMENT_FILE (RAFENROLLMENT_FILE_SEQ,REALM_ID);

select to_char(sysdate, 'MM/DD/YYYY HH24:MI:SS') AS "END TIME" from dual;


PROMPT finishedDBUpgrade_002.000.010.074.sql