--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--                                                                      --
-- Please review the script before using it to make sure it won't       --
-- cause any unacceptable data loss.                                    --
--                                                                      --
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 

Prompt TABLE PSP_QUICKBOOKS_INFO;
--
-- PSP_QUICKBOOKS_INFO  (Table) 
--
CREATE TABLE PSP_QUICKBOOKS_INFO
(
  QUICKBOOKS_INFO_SEQ         VARCHAR2(255 CHAR) NOT NULL,
  VERSION                     NUMBER(19)        NOT NULL,
  CREATOR_ID                  VARCHAR2(30 CHAR),
  CREATED_DATE                TIMESTAMP(6)      NOT NULL,
  MODIFIER_ID                 VARCHAR2(30 CHAR),
  MODIFIED_DATE               TIMESTAMP(6)      NOT NULL,
  REALM_ID                    NUMBER(19)        DEFAULT -1                    NOT NULL,
  AGREEMENT_CREATE_DATE       TIMESTAMP(6),
  APPLICATION_VERSION         VARCHAR2(100 CHAR),
  APPLICATION_ID              VARCHAR2(100 CHAR),
  LICENSE_NUMBER              VARCHAR2(100 CHAR),
  COA_FEE_ACCOUNT_NAME        VARCHAR2(100 CHAR),
  COA_SALES_TAX_ACCOUNT_NAME  VARCHAR2(100 CHAR),
  TAX_TABLE_ID                VARCHAR2(100 CHAR),
  A_S400_PAYROLL_COUNT        NUMBER(19),
  SERVICE_TYPE                VARCHAR2(100 CHAR),
  SUBSCRIPTION_NUMBER         VARCHAR2(100 CHAR),
  TOKEN                       NUMBER(19),
  AGREEMENT_SUB_TYPE          VARCHAR2(40 CHAR),
  NAME                        VARCHAR2(100 CHAR),
  SERVICE_KEY                 VARCHAR2(100 CHAR),
  SOURCE_AGREEMENT_ID         VARCHAR2(100 CHAR),
  COMPANY_FK                  VARCHAR2(255 CHAR) NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

Prompt INDEX PSP_QUICKBOOKS_INFO_FK1;
--
-- PSP_QUICKBOOKS_INFO_FK1  (Index) 
--
CREATE INDEX PSP_QUICKBOOKS_INFO_FK1 ON PSP_QUICKBOOKS_INFO
(COMPANY_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt TABLE PSP_QBDT_PAYROLL_TRANSACTION;
--
-- PSP_QBDT_PAYROLL_TRANSACTION  (Table) 
--
CREATE TABLE PSP_QBDT_PAYROLL_TRANSACTION
(
  QBDT_PAYROLL_TRANSACTION_SEQ  VARCHAR2(255 CHAR) NOT NULL,
  VERSION                       NUMBER(19)      NOT NULL,
  CREATOR_ID                    VARCHAR2(30 CHAR),
  CREATED_DATE                  TIMESTAMP(6)    NOT NULL,
  MODIFIER_ID                   VARCHAR2(30 CHAR),
  MODIFIED_DATE                 TIMESTAMP(6)    NOT NULL,
  REALM_ID                      NUMBER(19)      DEFAULT -1                    NOT NULL,
  TRANSACTION_TYPE              VARCHAR2(255 CHAR),
  AMOUNT                        NUMBER(19,4),
  PERIOD_END_DATE               TIMESTAMP(6),
  IS_VOIDED                     NUMBER(1),
  SOURCE_ID                     VARCHAR2(9 CHAR),
  TRANSACTION_DATE              TIMESTAMP(6),
  COMP_ADJUST_SUBMISSION_FK     VARCHAR2(255 CHAR),
  PRIOR_PAYMENT_SUBMISSION_FK   VARCHAR2(255 CHAR),
  EMPLOYEE_FK                   VARCHAR2(255 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE PSP_QBDT_PAYROLL_TRANSACTION
 ADD PRIMARY KEY
 (QBDT_PAYROLL_TRANSACTION_SEQ, REALM_ID);

Prompt COLUMN TOKEN;
ALTER TABLE PSP_QBDT_PAYROLL_ITEM_INFO
 ADD (TOKEN  NUMBER(19));

-- added in 1.11.3
--Prompt COLUMN COMPANY_FK;
--ALTER TABLE PSP_QBDT_PAYROLL_ITEM_INFO
-- ADD (COMPANY_FK  VARCHAR2(255 CHAR));

Prompt COLUMN TOKEN;
ALTER TABLE PSP_QBDT_EMPLOYEE_INFO
 ADD (TOKEN  NUMBER(19));
 
Prompt COLUMN TOKEN;
ALTER TABLE PSP_QBDT_PAYCHECK_INFO
 ADD (TOKEN  NUMBER(19));

-- added in 1.11.3
--Prompt COLUMN COMPANY_FK;
--ALTER TABLE PSP_QBDT_EMPLOYEE_INFO
-- ADD (COMPANY_FK  VARCHAR2(255 CHAR));

Prompt INDEX PSP_QBDT_PAYROLL_TRANS_FK1;
--
-- PSP_QBDT_PAYROLL_TRANS_FK1  (Index) 
--
CREATE INDEX PSP_QBDT_PAYROLL_TRANS_FK1 ON PSP_QBDT_PAYROLL_TRANSACTION
(EMPLOYEE_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt INDEX PSP_QBDT_PAYROLL_TRANS_FK2;
--
-- PSP_QBDT_PAYROLL_TRANS_FK2  (Index) 
--
CREATE INDEX PSP_QBDT_PAYROLL_TRANS_FK2 ON PSP_QBDT_PAYROLL_TRANSACTION
(PRIOR_PAYMENT_SUBMISSION_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt INDEX PSP_QBDT_PAYROLL_TRANSACTI_FK1;
--
-- PSP_QBDT_PAYROLL_TRANSACTI_FK1  (Index) 
--
CREATE INDEX PSP_QBDT_PAYROLL_TRANSACTI_FK1 ON PSP_QBDT_PAYROLL_TRANSACTION
(COMP_ADJUST_SUBMISSION_FK, REALM_ID)
LOGGING
NOPARALLEL;

-- added in 1.11.3
--Prompt INDEX PSP_QBDT_PAYROLL_ITEM_INFO_FK3;
--
-- PSP_QBDT_PAYROLL_ITEM_INFO_FK3  (Index) 
--
--CREATE INDEX PSP_QBDT_PAYROLL_ITEM_INFO_FK3 ON PSP_QBDT_PAYROLL_ITEM_INFO
--(COMPANY_FK, REALM_ID)
--LOGGING
--NOPARALLEL;

-- added in 1.11.3
--Prompt INDEX PSP_QBDT_EMPLOYEE_INFO_FK2;
--
-- PSP_QBDT_EMPLOYEE_INFO_FK2  (Index) 
--
--CREATE INDEX PSP_QBDT_EMPLOYEE_INFO_FK2 ON PSP_QBDT_EMPLOYEE_INFO
--(COMPANY_FK, REALM_ID)
--LOGGING
--NOPARALLEL;

Prompt TABLE PSP_QBDT_PAYROLL_TRANS_LINE;
--
-- PSP_QBDT_PAYROLL_TRANS_LINE  (Table) 
--
CREATE TABLE PSP_QBDT_PAYROLL_TRANS_LINE
(
  QBDT_PAYROLL_TRANS_LINE_SEQ  VARCHAR2(255 CHAR) NOT NULL,
  VERSION                      NUMBER(19)       NOT NULL,
  CREATOR_ID                   VARCHAR2(30 CHAR),
  CREATED_DATE                 TIMESTAMP(6)     NOT NULL,
  MODIFIER_ID                  VARCHAR2(30 CHAR),
  MODIFIED_DATE                TIMESTAMP(6)     NOT NULL,
  REALM_ID                     NUMBER(19)       DEFAULT -1                    NOT NULL,
  AMOUNT                       NUMBER(19,4),
  WAGE_BASE_AMOUNT             NUMBER(19,4),
  TAXABLE_WAGE_AMOUNT          NUMBER(19,4),
  COMPANY_PAYROLL_ITEM_FK      VARCHAR2(255 CHAR),
  QBDT_PAYROLL_TRANSACTION_FK  VARCHAR2(255 CHAR) NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE PSP_QBDT_PAYROLL_TRANS_LINE
 ADD PRIMARY KEY
 (QBDT_PAYROLL_TRANS_LINE_SEQ, REALM_ID);

Prompt INDEX PSP_QBDT_PAYROLL_TRANSACTI_FK2;
--
-- PSP_QBDT_PAYROLL_TRANSACTI_FK2  (Index) 
--
CREATE INDEX PSP_QBDT_PAYROLL_TRANSACTI_FK2 ON PSP_QBDT_PAYROLL_TRANS_LINE
(QBDT_PAYROLL_TRANSACTION_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt INDEX PSP_QBDT_PAYROLL_TRANSLINE_FK1;
--
-- PSP_QBDT_PAYROLL_TRANSLINE_FK1  (Index) 
--
CREATE INDEX PSP_QBDT_PAYROLL_TRANSLINE_FK1 ON PSP_QBDT_PAYROLL_TRANS_LINE
(COMPANY_PAYROLL_ITEM_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt COLUMN QBDT_PAYROLL_TRANSACTION_FK;
ALTER TABLE PSP_QBDT_TRANSACTION_INFO
 ADD (QBDT_PAYROLL_TRANSACTION_FK  VARCHAR2(255 CHAR));

Prompt COLUMN QBDT_PAYROLL_TRANS_LINE_FK;
ALTER TABLE PSP_QBDT_TRANSACTION_INFO
 ADD (QBDT_PAYROLL_TRANS_LINE_FK  VARCHAR2(255 CHAR));

Prompt INDEX PSP_QBDT_TRANSACTION_INFO_FK9;
--
-- PSP_QBDT_TRANSACTION_INFO_FK9  (Index) 
--
CREATE INDEX PSP_QBDT_TRANSACTION_INFO_FK9 ON PSP_QBDT_TRANSACTION_INFO
(QBDT_PAYROLL_TRANS_LINE_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt INDEX PSP_QBDT_TRANSACTION_INFO_FK8;
--
-- PSP_QBDT_TRANSACTION_INFO_FK8  (Index) 
--
CREATE INDEX PSP_QBDT_TRANSACTION_INFO_FK8 ON PSP_QBDT_TRANSACTION_INFO
(QBDT_PAYROLL_TRANSACTION_FK, REALM_ID)
LOGGING
NOPARALLEL;

-- added in 1.11.3
--ALTER TABLE PSP_QBDT_PAYROLL_ITEM_INFO
-- ADD CONSTRAINT PSP_QBDT_PAYROLL_ITEM_INFO_FK3 
-- FOREIGN KEY (COMPANY_FK, REALM_ID) 
-- REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

-- added in 1.11.3
--ALTER TABLE PSP_QBDT_EMPLOYEE_INFO
-- ADD CONSTRAINT PSP_QBDT_EMPLOYEE_INFO_FK2 
-- FOREIGN KEY (COMPANY_FK, REALM_ID) 
-- REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

ALTER TABLE PSP_QBDT_TRANSACTION_INFO
 ADD CONSTRAINT PSP_QBDT_TRANSACTION_INFO_FK8 
 FOREIGN KEY (QBDT_PAYROLL_TRANSACTION_FK, REALM_ID) 
 REFERENCES PSP_QBDT_PAYROLL_TRANSACTION (QBDT_PAYROLL_TRANSACTION_SEQ,REALM_ID);

ALTER TABLE PSP_QBDT_TRANSACTION_INFO
 ADD CONSTRAINT PSP_QBDT_TRANSACTION_INFO_FK9 
 FOREIGN KEY (QBDT_PAYROLL_TRANS_LINE_FK, REALM_ID) 
 REFERENCES PSP_QBDT_PAYROLL_TRANS_LINE (QBDT_PAYROLL_TRANS_LINE_SEQ,REALM_ID);

ALTER TABLE PSP_QUICKBOOKS_INFO
 ADD PRIMARY KEY
 (QUICKBOOKS_INFO_SEQ, REALM_ID);

 
ALTER TABLE PSP_QUICKBOOKS_INFO
 ADD CONSTRAINT PSP_QUICKBOOKS_INFO_FK1 
 FOREIGN KEY (COMPANY_FK, REALM_ID) 
 REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID);

ALTER TABLE PSP_QBDT_PAYROLL_TRANSACTION
 ADD CONSTRAINT PSP_QBDT_PAYROLL_TRANSACTI_FK1 
 FOREIGN KEY (COMP_ADJUST_SUBMISSION_FK, REALM_ID) 
 REFERENCES PSP_COMP_ADJUST_SUBMISSION (COMP_ADJUST_SUBMISSION_SEQ,REALM_ID);

ALTER TABLE PSP_QBDT_PAYROLL_TRANSACTION
 ADD CONSTRAINT PSP_QBDT_PAYROLL_TRANS_FK2 
 FOREIGN KEY (PRIOR_PAYMENT_SUBMISSION_FK, REALM_ID) 
 REFERENCES PSP_PRIOR_PAYMENT_SUBMISSION (PRIOR_PAYMENT_SUBMISSION_SEQ,REALM_ID);

ALTER TABLE PSP_QBDT_PAYROLL_TRANSACTION
 ADD CONSTRAINT PSP_QBDT_PAYROLL_TRANS_FK1 
 FOREIGN KEY (EMPLOYEE_FK, REALM_ID) 
 REFERENCES PSP_EMPLOYEE (EMPLOYEE_SEQ,REALM_ID);

ALTER TABLE PSP_QBDT_PAYROLL_TRANS_LINE
 ADD CONSTRAINT PSP_QBDT_PAYROLL_TRANSLINE_FK1 
 FOREIGN KEY (COMPANY_PAYROLL_ITEM_FK, REALM_ID) 
 REFERENCES PSP_COMPANY_PAYROLL_ITEM (COMPANY_PAYROLL_ITEM_SEQ,REALM_ID);

ALTER TABLE PSP_QBDT_PAYROLL_TRANS_LINE
 ADD CONSTRAINT PSP_QBDT_PAYROLL_TRANSACTI_FK2 
 FOREIGN KEY (QBDT_PAYROLL_TRANSACTION_FK, REALM_ID) 
 REFERENCES PSP_QBDT_PAYROLL_TRANSACTION (QBDT_PAYROLL_TRANSACTION_SEQ,REALM_ID);


PROMPT finishedDBUpgrade_002.000.012.000.sql