--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--
-- Please review the script before using it to make sure it won't
-- cause any unacceptable data loss.
--
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PSP_LOCAL 

Prompt Table PSP_PSTUB_EMPLOYER_INFO;
CREATE TABLE PSP_PSTUB_EMPLOYER_INFO
(
  PSTUB_EMPLOYER_INFO_SEQ  VARCHAR2(255 CHAR),
  VERSION                  NUMBER(19),
  CREATOR_ID               VARCHAR2(30 CHAR),
  CREATED_DATE             TIMESTAMP(6),
  MODIFIER_ID              VARCHAR2(30 CHAR),
  MODIFIED_DATE            TIMESTAMP(6),
  REALM_ID                 NUMBER(19)           DEFAULT -1,
  NAME                     VARCHAR2(60 CHAR),
  NAME_ADDR_FED_ID         VARCHAR2(200 CHAR)
)
NOPARALLEL;

ALTER TABLE PSP_PSTUB_EMPLOYER_INFO
 ADD PRIMARY KEY
  (PSTUB_EMPLOYER_INFO_SEQ, REALM_ID)
  USING INDEX;

Prompt Column VERSION;
ALTER TABLE PSP_AUTH_USER
MODIFY(VERSION  DEFAULT 0);

Prompt Column VERSION;
ALTER TABLE PSP_COMPANY
MODIFY(VERSION  DEFAULT 0);

Prompt Column VERSION;
ALTER TABLE PSP_ENTITLEMENT_UNIT
MODIFY(VERSION  DEFAULT 0);

Prompt Table PSP_PSTUB_EMPLOYEE_INFO;
CREATE TABLE PSP_PSTUB_EMPLOYEE_INFO
(
  PSTUB_EMPLOYEE_INFO_SEQ       VARCHAR2(255 CHAR),
  VERSION                       NUMBER(19),
  CREATOR_ID                    VARCHAR2(30 CHAR),
  CREATED_DATE                  TIMESTAMP(6),
  MODIFIER_ID                   VARCHAR2(30 CHAR),
  MODIFIED_DATE                 TIMESTAMP(6),
  REALM_ID                      NUMBER(19)      DEFAULT -1,
  FED_ALLOWANCES                NUMBER(10),
  FED_EXTRA                     NUMBER(10),
  FED_TAX_FILING_STATUS         VARCHAR2(30 CHAR),
  FED_TAX_FILING_STATUS_CODE    NUMBER(10),
  FIRST_NAME                    VARCHAR2(30 CHAR),
  LAST_NAME                     VARCHAR2(30 CHAR),
  S_S_N                         VARCHAR2(15 CHAR),
  STATE_ALLOWANCES              NUMBER(10),
  STATE_EXTRA                   NUMBER(10),
  STATE_TAX_FILING_STATUS       VARCHAR2(30 CHAR),
  STATE_TAX_FILING_STATUS_CODE  NUMBER(10),
  TAX_FILING_STATE              VARCHAR2(2 CHAR),
  EMPLOYEE_FK                   VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_PSTUB_EMPLOYEE_INFO_FK1;
CREATE INDEX PSP_PSTUB_EMPLOYEE_INFO_FK1 ON PSP_PSTUB_EMPLOYEE_INFO
(EMPLOYEE_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_PSTUB_EMPLOYEE_INFO
 ADD PRIMARY KEY
  (PSTUB_EMPLOYEE_INFO_SEQ, REALM_ID)
  USING INDEX;

Prompt Table PSP_PSTUB_EMPLOYEE_PREFERENCE;
CREATE TABLE PSP_PSTUB_EMPLOYEE_PREFERENCE
(
  PSTUB_EMPLOYEE_PREFERENCE_SEQ  VARCHAR2(255 CHAR),
  VERSION                        NUMBER(19),
  CREATOR_ID                     VARCHAR2(30 CHAR),
  CREATED_DATE                   TIMESTAMP(6),
  MODIFIER_ID                    VARCHAR2(30 CHAR),
  MODIFIED_DATE                  TIMESTAMP(6),
  REALM_ID                       NUMBER(19)     DEFAULT -1,
  EMPLOYEE_FK                    VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_PSTUB_EMPLOYEE_PREFERE_FK1;
CREATE INDEX PSP_PSTUB_EMPLOYEE_PREFERE_FK1 ON PSP_PSTUB_EMPLOYEE_PREFERENCE
(EMPLOYEE_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_PSTUB_EMPLOYEE_PREFERENCE
 ADD PRIMARY KEY
  (PSTUB_EMPLOYEE_PREFERENCE_SEQ, REALM_ID)
  USING INDEX;

Prompt Table PSP_PSTUB_ADDRESS;
CREATE TABLE PSP_PSTUB_ADDRESS
(
  PSTUB_ADDRESS_SEQ       VARCHAR2(255 CHAR),
  VERSION                 NUMBER(19),
  CREATOR_ID              VARCHAR2(30 CHAR),
  CREATED_DATE            TIMESTAMP(6),
  MODIFIER_ID             VARCHAR2(30 CHAR),
  MODIFIED_DATE           TIMESTAMP(6),
  REALM_ID                NUMBER(19)            DEFAULT -1,
  LINE1                   VARCHAR2(51 CHAR),
  LINE2                   VARCHAR2(51 CHAR),
  LINE3                   VARCHAR2(51 CHAR),
  LINE4                   VARCHAR2(51 CHAR),
  LINE5                   VARCHAR2(51 CHAR),
  PSTUB_EMPLOYER_INFO_FK  VARCHAR2(255 CHAR),
  PSTUB_EMPLOYEE_INFO_FK  VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_PSTUB_ADDRESS_FK1;
CREATE INDEX PSP_PSTUB_ADDRESS_FK1 ON PSP_PSTUB_ADDRESS
(PSTUB_EMPLOYER_INFO_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_PSTUB_ADDRESS_FK2;
CREATE INDEX PSP_PSTUB_ADDRESS_FK2 ON PSP_PSTUB_ADDRESS
(PSTUB_EMPLOYEE_INFO_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_PSTUB_ADDRESS
 ADD PRIMARY KEY
  (PSTUB_ADDRESS_SEQ, REALM_ID)
  USING INDEX;

Prompt Table PSP_PAYSTUB;
CREATE TABLE PSP_PAYSTUB
(
  PAYSTUB_SEQ               VARCHAR2(255 CHAR),
  VERSION                   NUMBER(19),
  CREATOR_ID                VARCHAR2(30 CHAR),
  CREATED_DATE              TIMESTAMP(6),
  MODIFIER_ID               VARCHAR2(30 CHAR),
  MODIFIED_DATE             TIMESTAMP(6),
  REALM_ID                  NUMBER(19)          DEFAULT -1,
  ADJ_NET_PAY               NUMBER(19,4),
  GROSS_PAY                 NUMBER(19,4),
  NET_PAY                   NUMBER(19,4),
  PAY_BEGIN_DATE            TIMESTAMP(6),
  PAYCHECK_DATE             TIMESTAMP(6),
  PAY_END_DATE              TIMESTAMP(6),
  PRE_TAX_DEDUCTIONS        NUMBER(19,4),
  TAXES                     NUMBER(19,4),
  Y_T_D_ADJ_NET_PAY         NUMBER(19,4),
  Y_T_D_GROSS_PAY           NUMBER(19,4),
  Y_T_D_NET_PAY             NUMBER(19,4),
  Y_T_D_PRE_TAX_DEDUCTIONS  NUMBER(19,4),
  Y_T_D_TAXES               NUMBER(19,4),
  PSTUB_EMPLOYER_INFO_FK    VARCHAR2(255 CHAR),
  PSTUB_EMPLOYEE_INFO_FK    VARCHAR2(255 CHAR),
  PAYCHECK_FK               VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_PAYSTUB_FK2;
CREATE INDEX PSP_PAYSTUB_FK2 ON PSP_PAYSTUB
(PSTUB_EMPLOYEE_INFO_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_PAYSTUB_FK3;
CREATE INDEX PSP_PAYSTUB_FK3 ON PSP_PAYSTUB
(PAYCHECK_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_PAYSTUB_FK1;
CREATE INDEX PSP_PAYSTUB_FK1 ON PSP_PAYSTUB
(PSTUB_EMPLOYER_INFO_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_PAYSTUB
 ADD PRIMARY KEY
  (PAYSTUB_SEQ, REALM_ID)
  USING INDEX;

Prompt Table PSP_PSTUB_DDITEM;
CREATE TABLE PSP_PSTUB_DDITEM
(
  PSTUB_DDITEM_SEQ      VARCHAR2(255 CHAR),
  VERSION               NUMBER(19),
  CREATOR_ID            VARCHAR2(30 CHAR),
  CREATED_DATE          TIMESTAMP(6),
  MODIFIER_ID           VARCHAR2(30 CHAR),
  MODIFIED_DATE         TIMESTAMP(6),
  REALM_ID              NUMBER(19)              DEFAULT -1,
  ACCT_NAME             VARCHAR2(51 CHAR),
  ACCT_NUMBER           VARCHAR2(30 CHAR),
  ACCT_TYPE             VARCHAR2(10 CHAR),
  BANK_NAME             VARCHAR2(51 CHAR),
  "CURRENT"             NUMBER(19,4),
  NAME                  VARCHAR2(31 CHAR),
  PAYROLL_ITEM_LIST_ID  VARCHAR2(51 CHAR),
  ROUTING_NUMBER        VARCHAR2(20 CHAR),
  PAYSTUB_FK            VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_PSTUB_DDITEM_FK1;
CREATE INDEX PSP_PSTUB_DDITEM_FK1 ON PSP_PSTUB_DDITEM
(PAYSTUB_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_PSTUB_DDITEM
 ADD PRIMARY KEY
  (PSTUB_DDITEM_SEQ, REALM_ID)
  USING INDEX;

Prompt Table PSP_PSTUB_MSG;
CREATE TABLE PSP_PSTUB_MSG
(
  PSTUB_MSG_SEQ  VARCHAR2(255 CHAR),
  VERSION        NUMBER(19),
  CREATOR_ID     VARCHAR2(30 CHAR),
  CREATED_DATE   TIMESTAMP(6),
  MODIFIER_ID    VARCHAR2(30 CHAR),
  MODIFIED_DATE  TIMESTAMP(6),
  REALM_ID       NUMBER(19)                     DEFAULT -1,
  SEQUENCE       NUMBER(10),
  TYPE           VARCHAR2(255 CHAR),
  TEXT           VARCHAR2(200 CHAR),
  PAYSTUB_FK     VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_PSTUB_MSG_FK1;
CREATE INDEX PSP_PSTUB_MSG_FK1 ON PSP_PSTUB_MSG
(PAYSTUB_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_PSTUB_MSG
 ADD PRIMARY KEY
  (PSTUB_MSG_SEQ, REALM_ID)
  USING INDEX;

Prompt Table PSP_PSTUB_PAID_TIMEOFF_ITEM;
CREATE TABLE PSP_PSTUB_PAID_TIMEOFF_ITEM
(
  PSTUB_PAID_TIMEOFF_ITEM_SEQ  VARCHAR2(255 CHAR),
  VERSION                      NUMBER(19),
  CREATOR_ID                   VARCHAR2(30 CHAR),
  CREATED_DATE                 TIMESTAMP(6),
  MODIFIER_ID                  VARCHAR2(30 CHAR),
  MODIFIED_DATE                TIMESTAMP(6),
  REALM_ID                     NUMBER(19)       DEFAULT -1,
  ACCT_NAME                    VARCHAR2(51 CHAR),
  AVAILABLE                    NUMBER(19,7),
  NAME                         VARCHAR2(31 CHAR),
  PAYROLL_ITEM_LIST_ID         VARCHAR2(51 CHAR),
  Y_T_D_USED                   NUMBER(19,7),
  PAYSTUB_FK                   VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_PSTUB_PAID_TIMEOFF_ITE_FK1;
CREATE INDEX PSP_PSTUB_PAID_TIMEOFF_ITE_FK1 ON PSP_PSTUB_PAID_TIMEOFF_ITEM
(PAYSTUB_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_PSTUB_PAID_TIMEOFF_ITEM
 ADD PRIMARY KEY
  (PSTUB_PAID_TIMEOFF_ITEM_SEQ, REALM_ID)
  USING INDEX;

Prompt Table PSP_PSTUB_PAY_ITEM;
CREATE TABLE PSP_PSTUB_PAY_ITEM
(
  PSTUB_PAY_ITEM_SEQ     VARCHAR2(255 CHAR),
  VERSION                NUMBER(19),
  CREATOR_ID             VARCHAR2(30 CHAR),
  CREATED_DATE           TIMESTAMP(6),
  MODIFIER_ID            VARCHAR2(30 CHAR),
  MODIFIED_DATE          TIMESTAMP(6),
  REALM_ID               NUMBER(19)             DEFAULT -1,
  ACCT_NAME              VARCHAR2(51 CHAR),
  "CURRENT"              NUMBER(19,4),
  EMPLOYEE_PAID          NUMBER(1),
  INCOME_SUBJECT_TO_TAX  NUMBER(19,4),
  NAME                   VARCHAR2(31 CHAR),
  PAYROLL_ITEM_LIST_ID   VARCHAR2(51 CHAR),
  QTY                    NUMBER(10),
  RATE                   NUMBER(19,4),
  TYPE                   VARCHAR2(255 CHAR),
  WAGE_BASE              NUMBER(19,4),
  Y_T_D                  NUMBER(19,4),
  PAYSTUB_FK             VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_PSTUB_PAY_ITEM_FK1;
CREATE INDEX PSP_PSTUB_PAY_ITEM_FK1 ON PSP_PSTUB_PAY_ITEM
(PAYSTUB_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_PSTUB_PAY_ITEM
 ADD PRIMARY KEY
  (PSTUB_PAY_ITEM_SEQ, REALM_ID)
  USING INDEX;

ALTER TABLE PSP_PSTUB_EMPLOYEE_INFO
 ADD CONSTRAINT PSP_PSTUB_EMPLOYEE_INFO_FK1 
  FOREIGN KEY (EMPLOYEE_FK, REALM_ID) 
  REFERENCES PSP_EMPLOYEE (EMPLOYEE_SEQ,REALM_ID);

ALTER TABLE PSP_PSTUB_EMPLOYEE_PREFERENCE
 ADD CONSTRAINT PSP_PSTUB_EMPLOYEE_PREFERE_FK1 
  FOREIGN KEY (EMPLOYEE_FK, REALM_ID) 
  REFERENCES PSP_EMPLOYEE (EMPLOYEE_SEQ,REALM_ID);

ALTER TABLE PSP_PSTUB_ADDRESS
 ADD CONSTRAINT PSP_PSTUB_ADDRESS_FK1 
  FOREIGN KEY (PSTUB_EMPLOYER_INFO_FK, REALM_ID) 
  REFERENCES PSP_PSTUB_EMPLOYER_INFO (PSTUB_EMPLOYER_INFO_SEQ,REALM_ID);

ALTER TABLE PSP_PSTUB_ADDRESS
 ADD CONSTRAINT PSP_PSTUB_ADDRESS_FK2 
  FOREIGN KEY (PSTUB_EMPLOYEE_INFO_FK, REALM_ID) 
  REFERENCES PSP_PSTUB_EMPLOYEE_INFO (PSTUB_EMPLOYEE_INFO_SEQ,REALM_ID);

ALTER TABLE PSP_PAYSTUB
 ADD CONSTRAINT PSP_PAYSTUB_FK1 
  FOREIGN KEY (PSTUB_EMPLOYER_INFO_FK, REALM_ID) 
  REFERENCES PSP_PSTUB_EMPLOYER_INFO (PSTUB_EMPLOYER_INFO_SEQ,REALM_ID);

ALTER TABLE PSP_PAYSTUB
 ADD CONSTRAINT PSP_PAYSTUB_FK2 
  FOREIGN KEY (PSTUB_EMPLOYEE_INFO_FK, REALM_ID) 
  REFERENCES PSP_PSTUB_EMPLOYEE_INFO (PSTUB_EMPLOYEE_INFO_SEQ,REALM_ID);

ALTER TABLE PSP_PAYSTUB
 ADD CONSTRAINT PSP_PAYSTUB_FK3 
  FOREIGN KEY (PAYCHECK_FK, REALM_ID) 
  REFERENCES PSP_PAYCHECK (PAYCHECK_SEQ,REALM_ID);

ALTER TABLE PSP_PSTUB_DDITEM
 ADD CONSTRAINT PSP_PSTUB_DDITEM_FK1 
  FOREIGN KEY (PAYSTUB_FK, REALM_ID) 
  REFERENCES PSP_PAYSTUB (PAYSTUB_SEQ,REALM_ID);

ALTER TABLE PSP_PSTUB_MSG
 ADD CONSTRAINT PSP_PSTUB_MSG_FK1 
  FOREIGN KEY (PAYSTUB_FK, REALM_ID) 
  REFERENCES PSP_PAYSTUB (PAYSTUB_SEQ,REALM_ID);

ALTER TABLE PSP_PSTUB_PAID_TIMEOFF_ITEM
 ADD CONSTRAINT PSP_PSTUB_PAID_TIMEOFF_ITE_FK1 
  FOREIGN KEY (PAYSTUB_FK, REALM_ID) 
  REFERENCES PSP_PAYSTUB (PAYSTUB_SEQ,REALM_ID);

ALTER TABLE PSP_PSTUB_PAY_ITEM
 ADD CONSTRAINT PSP_PSTUB_PAY_ITEM_FK1 
  FOREIGN KEY (PAYSTUB_FK, REALM_ID) 
  REFERENCES PSP_PAYSTUB (PAYSTUB_SEQ,REALM_ID);

PROMPT finishedDBUpgrade_002.013.002.004.sql