--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--                                                                      --
-- Please review the script before using it to make sure it won't       --
-- cause any unacceptable data loss.                                    --
--                                                                      --
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL
-- PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL
Prompt Column TXP_RECORD_CLASS;
ALTER TABLE PSP_PAYMENT_TEMPLATE
 ADD (TXP_RECORD_CLASS  VARCHAR2(4000 CHAR));

Prompt Column VERSION;
ALTER TABLE PSP_COMPANY
MODIFY(VERSION  DEFAULT 0);

Prompt Column VERSION;
ALTER TABLE PSP_AUTH_USER
MODIFY(VERSION  DEFAULT 0);

Prompt Table PSP_FRAUD_EVENT;
--
-- PSP_FRAUD_EVENT  (Table)
--
CREATE TABLE PSP_FRAUD_EVENT
(
  FRAUD_EVENT_SEQ       VARCHAR2(255 CHAR),
  VERSION               NUMBER(19),
  CREATOR_ID            VARCHAR2(30 CHAR),
  CREATED_DATE          TIMESTAMP(6),
  MODIFIER_ID           VARCHAR2(30 CHAR),
  MODIFIED_DATE         TIMESTAMP(6),
  REALM_ID              NUMBER(19)              DEFAULT -1,
  COMPANY_EIN           VARCHAR2(80 CHAR),
  EVENT_TYPE_CD         VARCHAR2(255 CHAR),
  EVENT_STATUS_CD       VARCHAR2(255 CHAR),
  EVENT_TIME_STAMP      TIMESTAMP(6),
  COMPANY_PSID          VARCHAR2(50 CHAR),
  FRAUD_CATEGORY        VARCHAR2(40 CHAR),
  FRAUD_TRIGGER_DETAIL  VARCHAR2(4000 CHAR),
  PAYROLL_NET_AMOUNT    NUMBER(19,4),
  COMPANY_EVENT_FK      VARCHAR2(255 CHAR),
  PAYROLL_RUN_FK        VARCHAR2(255 CHAR),
  COMPANY_FK            VARCHAR2(255 CHAR),
  EMPLOYEE_FK           VARCHAR2(255 CHAR)
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

Prompt Index PSP_FRAUD_EVENT_FK4;
--
-- PSP_FRAUD_EVENT_FK4  (Index)
--
CREATE INDEX PSP_FRAUD_EVENT_FK4 ON PSP_FRAUD_EVENT
(EMPLOYEE_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt Index PSP_FRAUD_EVENT_FK3;
--
-- PSP_FRAUD_EVENT_FK3  (Index)
--
CREATE INDEX PSP_FRAUD_EVENT_FK3 ON PSP_FRAUD_EVENT
(COMPANY_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt Index PSP_FRAUD_EVENT_FK2;
--
-- PSP_FRAUD_EVENT_FK2  (Index)
--
CREATE INDEX PSP_FRAUD_EVENT_FK2 ON PSP_FRAUD_EVENT
(PAYROLL_RUN_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt Index PSP_FRAUD_EVENT_FK1;
--
-- PSP_FRAUD_EVENT_FK1  (Index)
--
CREATE INDEX PSP_FRAUD_EVENT_FK1 ON PSP_FRAUD_EVENT
(COMPANY_EVENT_FK, REALM_ID)
LOGGING
NOPARALLEL;

ALTER TABLE PSP_FRAUD_EVENT
 ADD PRIMARY KEY
 (FRAUD_EVENT_SEQ, REALM_ID);

Prompt Column TXP_RECORD_DATA;
ALTER TABLE PSP_ENTRY_DETAIL_RECORD
 ADD (TXP_RECORD_DATA  VARCHAR2(80 CHAR));

Prompt Column COMPANY_FK;
ALTER TABLE PSP_COMPANY_EVENT_DETAIL
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));


Prompt Column COMPANY_FK;
ALTER TABLE PSP_PAYCHECK
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));

Prompt Column COMPANY_FK;
ALTER TABLE PSP_DEDUCTION
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));

Prompt Column COMPANY_FK;
ALTER TABLE PSP_COMPENSATION
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));

Prompt Column COMPANY_FK;
ALTER TABLE PSP_LIABILITY_ADJUSTMENT
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));
 

Prompt Column COMPANY_FK;
ALTER TABLE PSP_EMPLOYER_CONTRIBUTION
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));

Prompt Column COMPANY_FK;
ALTER TABLE PSP_QBDT_PAYLINE_INFO
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));

ALTER TABLE PSP_QBDT_PAYCHECK_INFO
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));


Prompt Column COMPANY_FK;
ALTER TABLE PSP_TAX
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));

Prompt Column COMPANY_FK;
ALTER TABLE PSP_PAYCHECK_SPLIT
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));

Prompt Column COMPANY_FK;
ALTER TABLE PSP_QBDT_TRANSACTION_INFO
 ADD (COMPANY_FK  VARCHAR2(255 CHAR));
 
PROMPT finishedDBUpgrade_002.000.010.090.sql
