
PROMPT finished DBUpgrade_002.016.006.002.sql

CREATE TABLE "PSP_IOPSYNC_COMPANY"
(
    PRIMARY KEY(IOPSYNC_COMPANY_SEQ,"REALM_ID")
    , "IOPSYNC_COMPANY_SEQ" VARCHAR2(255 CHAR) NOT NULL
    , "VERSION" NUMBER(19,0) NOT NULL
    , "CREATOR_ID" VARCHAR2(30 CHAR) 
    , "CREATED_DATE" TIMESTAMP NOT NULL
    , "MODIFIER_ID" VARCHAR2(30 CHAR) 
    , "MODIFIED_DATE" TIMESTAMP NOT NULL
    , "REALM_ID" NUMBER(19,0) DEFAULT -1 NOT NULL
    , "COMPANY_ID" NUMBER(10,0) 
    , "HAS_EMPLOYEE_PAYROLL" NUMBER(1,0) 
    , "HAS_CONTRACTOR_PAYMENT" NUMBER(1,0) 
    , "NOTES" VARCHAR2(4000 CHAR) 
    , "RETRY_COUNT" NUMBER(10,0) 
    , "STATUS" VARCHAR2(255 CHAR) 
);

ALTER TABLE PSP_IOPSYNC_COMPANY
 ADD CONSTRAINT C_PSP_IOPSYNC_COMPANY1
  CHECK (STATUS IN('Pending', 'InProcess', 'Failed', 'Synced'));
  

PROMPT finished DBUpgrade_002.016.006.002.sql