--
-- This script will be executed BEFORE the automatically generated
-- c:\dev\PSP\dev\PSE\Domain\src\main\model\DBUpgrade_002.013.004.001.sql
--
-- Developers can hand code logic here for data migration purposes
--
