--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--                                                                      --
-- Please review the script before using it to make sure it won't       --
-- cause any unacceptable data loss.                                    --
--                                                                      --
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL
-- PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL


select to_char(sysdate, 'MM/DD/YYYY HH24:MI:SS') AS "START TIME" from dual;


Prompt Column DEFAULT_PAYMENT_METHOD;
ALTER TABLE PSP_PAYMENT_TEMPLATE
 ADD (DEFAULT_PAYMENT_METHOD  VARCHAR2(255 CHAR));

Prompt Table PSP_EFTPS_FILE;
--
-- PSP_EFTPS_FILE  (Table)
--
CREATE TABLE PSP_EFTPS_FILE
(
  EFTPS_FILE_SEQ         VARCHAR2(255 CHAR),
  VERSION                NUMBER(19),
  CREATOR_ID             VARCHAR2(30 CHAR),
  CREATED_DATE           TIMESTAMP(6),
  MODIFIER_ID            VARCHAR2(30 CHAR),
  MODIFIED_DATE          TIMESTAMP(6),
  REALM_ID               NUMBER(19)             DEFAULT -1,
  FILE_TYPE              VARCHAR2(255 CHAR),
  FILE_CODE              NUMBER(10),
  FILE_ID                NUMBER(10),
  SYSTEM_OWNER           VARCHAR2(255 CHAR),
  STATUS_CD              VARCHAR2(255 CHAR),
  FILE_NAME              VARCHAR2(500 CHAR),
  STATUS_EFFECTIVE_DATE  TIMESTAMP(6),
  SUBMIT_DATE            TIMESTAMP(6),
  PARENT_FILE_FK         VARCHAR2(255 CHAR)
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

Prompt Index PSP_EFTPS_FILE_FK1;
--
-- PSP_EFTPS_FILE_FK1  (Index)
--
CREATE INDEX PSP_EFTPS_FILE_FK1 ON PSP_EFTPS_FILE
(PARENT_FILE_FK, REALM_ID)
LOGGING
NOPARALLEL;

ALTER TABLE PSP_EFTPS_FILE
 ADD PRIMARY KEY
 (EFTPS_FILE_SEQ, REALM_ID);

Prompt Column EFTPS_ENROLLMENT_ID;
ALTER TABLE PSP_EFTPS_ENROLLMENT
 ADD (EFTPS_ENROLLMENT_ID  VARCHAR2(100 CHAR));

Prompt Column FED_TAX_ID;
ALTER TABLE PSP_EFTPS_ENROLLMENT DROP COLUMN FED_TAX_ID;

Prompt Column LEGAL_NAME;
ALTER TABLE PSP_EFTPS_ENROLLMENT DROP COLUMN LEGAL_NAME;

Prompt Column CONTACT_FIRST_NAME;
ALTER TABLE PSP_EFTPS_ENROLLMENT DROP COLUMN CONTACT_FIRST_NAME;

Prompt Column CONTACT_LAST_NAME;
ALTER TABLE PSP_EFTPS_ENROLLMENT DROP COLUMN CONTACT_LAST_NAME;

Prompt Column CONTACT_PHONE;
ALTER TABLE PSP_EFTPS_ENROLLMENT DROP COLUMN CONTACT_PHONE;

Prompt Column CONTACT_JOB_TITLE;
ALTER TABLE PSP_EFTPS_ENROLLMENT DROP COLUMN CONTACT_JOB_TITLE;

Prompt Column ADDRESS_LINE1;
ALTER TABLE PSP_EFTPS_ENROLLMENT DROP COLUMN ADDRESS_LINE1;

Prompt Column ADDRESS_LINE2;
ALTER TABLE PSP_EFTPS_ENROLLMENT DROP COLUMN ADDRESS_LINE2;

Prompt Column CITY;
ALTER TABLE PSP_EFTPS_ENROLLMENT DROP COLUMN CITY;

Prompt Column STATE;
ALTER TABLE PSP_EFTPS_ENROLLMENT DROP COLUMN STATE;

Prompt Column ZIP_CODE;
ALTER TABLE PSP_EFTPS_ENROLLMENT DROP COLUMN ZIP_CODE;

Prompt Column STATUS_REASON;
ALTER TABLE PSP_EFTPS_ENROLLMENT DROP COLUMN STATUS_REASON;

Prompt Column SUBMITTED_DATE;
ALTER TABLE PSP_EFTPS_ENROLLMENT DROP COLUMN SUBMITTED_DATE;

Prompt Column EFE_FILING_ID;
ALTER TABLE PSP_EFTPS_ENROLLMENT DROP COLUMN EFE_FILING_ID;

Prompt Column EFE_STATUS;
ALTER TABLE PSP_EFTPS_ENROLLMENT DROP COLUMN EFE_STATUS;

Prompt Column EFE_STATUS_EFFECTIVE_DATE;
ALTER TABLE PSP_EFTPS_ENROLLMENT DROP COLUMN EFE_STATUS_EFFECTIVE_DATE;

Prompt Table PSP_EFTPS_ENROLLMENT_DETAIL;
--
-- PSP_EFTPS_ENROLLMENT_DETAIL  (Table)
--
CREATE TABLE PSP_EFTPS_ENROLLMENT_DETAIL
(
  EFTPS_ENROLLMENT_DETAIL_SEQ  VARCHAR2(255 CHAR),
  VERSION                      NUMBER(19),
  CREATOR_ID                   VARCHAR2(30 CHAR),
  CREATED_DATE                 TIMESTAMP(6),
  MODIFIER_ID                  VARCHAR2(30 CHAR),
  MODIFIED_DATE                TIMESTAMP(6),
  REALM_ID                     NUMBER(19)       DEFAULT -1,
  GROUP_ID                     NUMBER(10),
  TRANSACTION_SET_ID           NUMBER(10),
  TRANSACTION_ID               NUMBER(10),
  FED_TAX_ID                   VARCHAR2(80 CHAR),
  LEGAL_NAME                   VARCHAR2(100 CHAR),
  LEGAL_ZIP                    VARCHAR2(13 CHAR),
  STATUS_CD                    VARCHAR2(255 CHAR),
  STATUS_EFFECTIVE_DATE        TIMESTAMP(6),
  ACKNOWLEDGE_DATE             TIMESTAMP(6),
  RESPONSE_DATE                TIMESTAMP(6),
  REJECT_CD                    VARCHAR2(20 CHAR),
  REJECT_REASON                VARCHAR2(100 CHAR),
  EFTPS_ENROLLMENT_FK          VARCHAR2(255 CHAR),
  EFTPS_FILE_FK                VARCHAR2(255 CHAR)
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

Prompt Index PSP_EFTPS_ENROLLMENT_DETAI_FK2;
--
-- PSP_EFTPS_ENROLLMENT_DETAI_FK2  (Index)
--
CREATE INDEX PSP_EFTPS_ENROLLMENT_DETAI_FK2 ON PSP_EFTPS_ENROLLMENT_DETAIL
(EFTPS_FILE_FK, REALM_ID)
LOGGING
NOPARALLEL;

Prompt Index PSP_EFTPS_ENROLLMENT_DETAI_FK1;
--
-- PSP_EFTPS_ENROLLMENT_DETAI_FK1  (Index)
--
CREATE INDEX PSP_EFTPS_ENROLLMENT_DETAI_FK1 ON PSP_EFTPS_ENROLLMENT_DETAIL
(EFTPS_ENROLLMENT_FK, REALM_ID)
LOGGING
NOPARALLEL;

ALTER TABLE PSP_EFTPS_ENROLLMENT_DETAIL
 ADD PRIMARY KEY
 (EFTPS_ENROLLMENT_DETAIL_SEQ, REALM_ID);

ALTER TABLE PSP_EFTPS_FILE
 ADD CONSTRAINT PSP_EFTPS_FILE_FK1
 FOREIGN KEY (PARENT_FILE_FK, REALM_ID)
 REFERENCES PSP_EFTPS_FILE (EFTPS_FILE_SEQ,REALM_ID);

ALTER TABLE PSP_EFTPS_ENROLLMENT_DETAIL
 ADD CONSTRAINT PSP_EFTPS_ENROLLMENT_DETAI_FK1
 FOREIGN KEY (EFTPS_ENROLLMENT_FK, REALM_ID)
 REFERENCES PSP_EFTPS_ENROLLMENT (EFTPS_ENROLLMENT_SEQ,REALM_ID);

ALTER TABLE PSP_EFTPS_ENROLLMENT_DETAIL
 ADD CONSTRAINT PSP_EFTPS_ENROLLMENT_DETAI_FK2
 FOREIGN KEY (EFTPS_FILE_FK, REALM_ID)
 REFERENCES PSP_EFTPS_FILE (EFTPS_FILE_SEQ,REALM_ID);

select to_char(sysdate, 'MM/DD/YYYY HH24:MI:SS') AS "END TIME" from dual;

 
PROMPT finishedDBUpgrade_002.000.000.068.sql