--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--
-- Please review the script before using it to make sure it won't
-- cause any unacceptable data loss.
--
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PSP_LOCAL 

Prompt Table PSP_LIMIT_RULE;
CREATE TABLE PSP_LIMIT_RULE
(
  LIMIT_RULE_SEQ    VARCHAR2(255 CHAR),
  VERSION           NUMBER(19),
  CREATOR_ID        VARCHAR2(30 CHAR),
  CREATED_DATE      TIMESTAMP(6),
  MODIFIER_ID       VARCHAR2(30 CHAR),
  MODIFIED_DATE     TIMESTAMP(6),
  REALM_ID          NUMBER(19)                  DEFAULT -1,
  SOURCE_SYSTEM_CD  VARCHAR2(255 CHAR),
  DESCRIPTION       VARCHAR2(255 CHAR)
)
NOPARALLEL;

ALTER TABLE PSP_LIMIT_RULE
 ADD PRIMARY KEY
  (LIMIT_RULE_SEQ, REALM_ID);

Prompt Table PSP_LIMIT_VALUE;
CREATE TABLE PSP_LIMIT_VALUE
(
  LIMIT_VALUE_SEQ  VARCHAR2(255 CHAR),
  VERSION          NUMBER(19),
  CREATOR_ID       VARCHAR2(30 CHAR),
  CREATED_DATE     TIMESTAMP(6),
  MODIFIER_ID      VARCHAR2(30 CHAR),
  MODIFIED_DATE    TIMESTAMP(6),
  REALM_ID         NUMBER(19)                   DEFAULT -1,
  NAME             VARCHAR2(255 CHAR),
  VALUE            VARCHAR2(255 CHAR),
  TIER             NUMBER(10),
  LIMIT_RULE_FK    VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_LIMIT_VALUE_FK1;
CREATE INDEX PSP_LIMIT_VALUE_FK1 ON PSP_LIMIT_VALUE
(LIMIT_RULE_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_LIMIT_VALUE
 ADD PRIMARY KEY
  (LIMIT_VALUE_SEQ, REALM_ID);

Prompt Column LIMIT_RULE_FK;
ALTER TABLE PSP_OFFERING
 ADD (LIMIT_RULE_FK  VARCHAR2(255 CHAR));

Prompt Index PSP_OFFERING_FK1;
CREATE INDEX PSP_OFFERING_FK1 ON PSP_OFFERING
(LIMIT_RULE_FK, REALM_ID)
NOPARALLEL;

Prompt Column NEXT_PAYROLL_ITEM_ID;
ALTER TABLE PSP_COMPANY
 RENAME COLUMN NEXT_PAYLINE_TRANSACTION_ID TO NEXT_PAYROLL_ITEM_ID;

Prompt Table PSP_LIAB_CHECK_BILLING_ASSOC;
CREATE TABLE PSP_LIAB_CHECK_BILLING_ASSOC
(
  LIAB_CHECK_BILLING_ASSOC_SEQ  VARCHAR2(255 CHAR),
  VERSION                       NUMBER(19),
  CREATOR_ID                    VARCHAR2(30 CHAR),
  CREATED_DATE                  TIMESTAMP(6),
  MODIFIER_ID                   VARCHAR2(30 CHAR),
  MODIFIED_DATE                 TIMESTAMP(6),
  REALM_ID                      NUMBER(19)      DEFAULT -1,
  BILLING_DETAIL_FK             VARCHAR2(255 CHAR),
  LIABILITY_CHECK_FK            VARCHAR2(255 CHAR)
)
NOPARALLEL;

Prompt Index PSP_LIABILITY_CHECK_BILLIN_FK1;
CREATE INDEX PSP_LIABILITY_CHECK_BILLIN_FK1 ON PSP_LIAB_CHECK_BILLING_ASSOC
(BILLING_DETAIL_FK, REALM_ID)
NOPARALLEL;

Prompt Index PSP_LIABILITY_CHECK_BILLIN_FK2;
CREATE INDEX PSP_LIABILITY_CHECK_BILLIN_FK2 ON PSP_LIAB_CHECK_BILLING_ASSOC
(LIABILITY_CHECK_FK, REALM_ID)
NOPARALLEL;

ALTER TABLE PSP_LIAB_CHECK_BILLING_ASSOC
 ADD PRIMARY KEY
  (LIAB_CHECK_BILLING_ASSOC_SEQ, REALM_ID);

Prompt Column W2_DELIVERY_PREFERENCE_CD;
ALTER TABLE PSP_TAX_COMPANY_SERVICE_INFO
 ADD (W2_DELIVERY_PREFERENCE_CD  VARCHAR2(255 CHAR));

Prompt Column CLIENT_PACKET_DELIVERY_PREF_CD;
ALTER TABLE PSP_TAX_COMPANY_SERVICE_INFO
 ADD (CLIENT_PACKET_DELIVERY_PREF_CD  VARCHAR2(255 CHAR));

Prompt Column LAST_TAX_YEAR;
ALTER TABLE PSP_TAX_COMPANY_SERVICE_INFO
 ADD (LAST_TAX_YEAR  NUMBER(10));

ALTER TABLE PSP_LIMIT_VALUE
 ADD CONSTRAINT PSP_LIMIT_VALUE_FK1 
  FOREIGN KEY (LIMIT_RULE_FK, REALM_ID) 
  REFERENCES PSP_LIMIT_RULE (LIMIT_RULE_SEQ,REALM_ID);

ALTER TABLE PSP_LIAB_CHECK_BILLING_ASSOC
 ADD CONSTRAINT PSP_LIABILITY_CHECK_BILLIN_FK1 
  FOREIGN KEY (BILLING_DETAIL_FK, REALM_ID) 
  REFERENCES PSP_BILLING_DETAIL (BILLING_DETAIL_SEQ,REALM_ID);

ALTER TABLE PSP_LIAB_CHECK_BILLING_ASSOC
 ADD CONSTRAINT PSP_LIABILITY_CHECK_BILLIN_FK2 
  FOREIGN KEY (LIABILITY_CHECK_FK, REALM_ID) 
  REFERENCES PSP_LIABILITY_CHECK (LIABILITY_CHECK_SEQ,REALM_ID);

ALTER TABLE PSP_OFFERING
 ADD CONSTRAINT PSP_OFFERING_FK1 
  FOREIGN KEY (LIMIT_RULE_FK, REALM_ID) 
  REFERENCES PSP_LIMIT_RULE (LIMIT_RULE_SEQ,REALM_ID);

PROMPT finishedDBUpgrade_002.001.001.001.sql