--------------------------------------------------------
-- Create temp table                                  --
--------------------------------------------------------
INSERT INTO PSP_COMPANY_OFFERING(COMPANY_OFFERING_SEQ, COMPANY_FK, OFFERING_FK, VERSION, CREATED_DATE, MODIFIED_DATE, CREATOR_ID, MODIFIER_ID) SELECT FN_FORMAT_SYSGUID(SYS_GUID()), COMPANY_SEQ,OFFERING_FK, 0, sysdate, sysdate, 'BatchJob', 'BatchJob' FROM TEMP_COMPANY_DATAFILE
/
INSERT INTO PSP_COMPANY_OFFERING co
(COMPANY_OFFERING_SEQ, COMPANY_FK, OFFERING_FK, VERSION, CREATED_DATE, MODIFIED_DATE, CREATOR_ID, MODIFIER_ID)
SELECT FN_FORMAT_SYSGUID(SYS_GUID()), CS.COMPANY_FK, O.OFFERING_SEQ, 0, sysdate, sysdate, 'BatchJob', 'BatchJob' FROM PSP_COMPANY_SERVICE cs
 INNER JOIN PSP_SERVICE s ON S.SERVICE_CD = CS.SERVICE_FK
   INNER JOIN PSP_OFFERING o ON o.SERVICE_CODE = s.SERVICE_CD
WHERE CS.SERVICE_FK = 'ThirdParty401k'
/
INSERT INTO PSP_COMPANY_OFFERING co
(COMPANY_OFFERING_SEQ, COMPANY_FK, OFFERING_FK, VERSION, CREATED_DATE, MODIFIED_DATE, CREATOR_ID, MODIFIER_ID)
SELECT FN_FORMAT_SYSGUID(SYS_GUID()), CS.COMPANY_FK, O.OFFERING_SEQ, 0, sysdate, sysdate, 'BatchJob', 'BatchJob' FROM PSP_COMPANY_SERVICE cs
 INNER JOIN PSP_SERVICE s ON S.SERVICE_CD = CS.SERVICE_FK
   INNER JOIN PSP_OFFERING o ON o.SERVICE_CODE = s.SERVICE_CD
WHERE CS.SERVICE_FK = 'BillPayment'
/

COMMIT
/
