#
# Go to psp.database.naming.properties find the generated name paste it in this doc and give it a new name
#
# Tables
INTUITBANKACCOUNTTRANSACTIONTYPE=INTUIT_BANK_ACC_TXN_TYPE
COMPANYJURISDICTIONTAXTYPE=COMPANY_JURISD_TAX_TYPE
COMPANYSERVICEBANKACCOUNT=COMPANY_SERVICE_BANK_ACCT
SERVICESTATUSCHANGEEVENT=SERV_STATUS_CHANGE_EVENT
BANKACCOUNTVERIFIEDEVENT=BA_VERIFIED_EVENT
AUTHDOMAINUSERROLEASSOC=AUTH_DOMAIN_USR_ROLE_ASSOC
AUTHGLOBALUSERROLEASSOC=AUTH_GLOVAL_USR_ROLE_ASSOC
EFFECTIVEDEPOSITFREQUENCY=EFFECTIVE_DEPOSIT_FREQ
FINANCIALTRANSACTIONSTATE=FINANCIAL_TRANS_STATE
PAYMENTTAXGROUPFREQUENCY=PAYMENT_TAX_GROUP_FREQ
FINANCIALTRANSACTIONACTION=FINANCIAL_TXN_ACTION
INTUITBABATCHTYPEFILETYPE=INTUIT_BA_BT_FT
TRANSACTIONTYPESERVICESTATUSOFFLOAD=TXN_TYPE_SRV_STAT_OFLD
OFFERINGSERVICECHARGEGROUP=OFFERING_SVCCHG_GRP
OFFERINGSERVICECHARGE=OFFERING_SVCCHG
FINANCIALTRANSACTIONONHOLDREASON_ASSOC=FINTXN_ONHOLDREASON_ASSOC
SERVICESUBSTATUSSYSTEMCAPABILITY_ASSOC=SVCSTAT_SYSCAP_ASSOC
SERVICESUBSTATUSSOURCESYSTEM_ASSOC=SVCSTAT_SRCSYS_ASSOC
SERVICESUBSTATUSSERVICE_ASSOC=SVCSTAT_SVC_ASSOC
SERVICESUBSTATUSTRANSACTIONTYPE_ASSOC=SVCSTAT_TXNTYPE_ASSOC
AGENCYAPPLICABLECHECKLISTITEM=AGENCY_CHECK_LIST_ITEM
AGENCYCHECKLISTAPPLICABLESTATUS=AGENCY_CHECK_LIST_STATUS
SERVICEAPPLICABLECHECKLISTITEM=SERVICE_CHECK_LIST_ITEM
SERVICECHECKLISTAPPLICABLESTATUS=SERVICE_CHECK_LIST_STATUS
ACHENROLLMENTACHENROLLMENTBATCH_ASSOC=ACHENROLLMENT_BATCH_ASSOC
COMPANYAGENCYPAYMENTTEMPLATE=COMPANYAGENCY_PMTTEMPLATE
PAYMENTTEMPLATEFREQUENCY=PMT_TEMPLATE_FREQUENCY
COMPANYAGENCYONHOLDREASON=COMP_AGENCY_ON_HOLD_REASON
EFEPAYMENTSUBMISSIONBATCH=EFE_PMT_BATCH
FINANCIALTRANSACTIONCOMPANYAGENCYONHOLDREASON_ASSOC=FINTXN_AGENCY_HOLD_ASSOC
AGENCYSTATUSTRANSACTIONTYPE=AGENCY_STAT_TXN_TYPE
APPLIEDLIABILITYADJUSTMENTS=APPLIED_LIABILITY_ADJ
COMPANYADJUSTMENTSUBMISSION=COMP_ADJUST_SUBMISSION
THIRDPARTY401KCOMPANYSERVICEINFO=TP401KCOMPANY_SERVICE_INFO
THIRDPARTY401KSIGNUPQUEUE=TP401K_SIGNUP_QUEUE
THIRDPARTY401KSIGNUPBATCH=TP401K_SIGNUP_BATCH
THIRDPARTY401KBATCHPAYCHECK=TP401K_BATCH_PAYCHECK
THIRDPARTY401KBATCHEMPLOYEE=TP401K_BATCH_EMPLOYEE
COMPANYAGENCYFORMTEMPLATE=COMPANYAGENCY_FRMTEMPLATE
PAYMENTTEMPLATEBANKACCOUNT=PMT_TEMPLATE_BANKACCOUNT
PAYMENTTEMPLATEPAYMENTMETHOD=PMT_TEMPLATE_PAYMENTMETHOD
THIRDPARTY401KPAYCHECKSTATE=TP401K_PAYCHECK_STATE
THIRDPARTY401KPAYCHECKPENDINGSTATE=TP401K_PAYCHECK_PENDING
THIRDPARTY401KPAYCHECK=TP401K_PAYCHECK
COMPANYPAYMENTTEMPLATEAGENCYID=COMP_PMT_TEMPLATE_AGENCYID
COMPANYPAYMENTTEMPLATEPAYMENTMETHOD=COMP_PMTTEMPLATE_PMTMETHOD
STATEREPORTOUTPUTPAYMENTTEMPLATEFREQUENCY_ASSOC=STATERPT_PMNTTEMPFRQ_ASSOC
DEPOSITFREQUENCYREQUIREMENT=DEPOSIT_FREQUENCY_REQ
QBDTPAYROLLTRANSACTIONLINE=QBDT_PAYROLL_TRANS_LINE
QBDTREQUEST_INFO=PSP_QBDT_REQUEST_INFO
LIABILITYCHECKBILLINGDETAILASSOC=LIAB_CHECK_BILLING_ASSOC
EMPLOYEEPAYROLLITEMQTRTOTALS=EE_PAYROLLITEM_QTRTOTALS
SAPMETHODCALL=SAP_METHOD_CALL
WORKERSCOMPPAYCHECK=WC_PAYCHECK
WORKERSCOMPPAYCHECKSTATE=WC_PAYCHECK_STATE
WORKERSCOMPPAYCHECKPENDINGSTATE=WC_PAYCHECK_PENDING
DEPOSITFREQUENCYLEDGEROPERATION=DEP_FREQ_LEDGER_OPERATION

# Columns
CLIENT_PACKET_DELIVERY_PREFERENCE_CD=CLIENT_PACKET_DELIVERY_PREF_CD
MANUAL_STRIKE_REASON_DESCRIPTION=MANUAL_STRIKE_REASON_DESCR
CONSECUTIVE_LIMIT_VIOLATION_COUNT=CONS_LIMIT_VIOLATION_CNT
TRANSACTION_STATE_EFFECTIVE_DATE=TRANSACTION_STATE_EFF_DATE
MONEY_MOVEMENT_TRANSACTION_AMOUNT=MM_TRANSACTION_AMOUNT
MONEY_MOVEMENT_RESPONSE_FILE_ID=MM_RESPONSE_FILE_ID
OFFERING_SERVICE_CHARGE_GROUP_FK=OFFERING_SVCCHG_GRP_FK
OFFERING_SERVICE_CHARGE_PRICE_FK=OFFERING_SVCCHG_PRICE_FK
NUMBER_OF_FAILED_LOGIN_ATTEMPTS=NBR_OF_FAILED_LOGIN_ATTEMPTS
QUICKBOOKS_INFO_APPLICATION_VERSION=QB_INFO_APP_VERSION
QUICKBOOKS_INFO_COA_FEE_ACCOUNT_NAME=QB_INFO_COA_FEE_ACC_NAME
QUICKBOOKS_INFO_COA_SALES_TAX_ACCOUNT_NAME=QB_INFO_COA_SALES_TAX_ACC_NAME
QUICKBOOKS_INFO_A_S400_PAYROLL_COUNT= QB_INFO_AS400_PAYROLL_COUNT
AGREEMENT_INFO_SUBSCRIPTION_NUMBER=AGREE_INFO_SUB_NBR
AGREEMENT_INFO_SOURCE_AGREEMENT_ID=AGREE_INFO_SOURCE_ID
AGREEMENT_INFO_AGREEMENT_CREATE_DATE=AGREE_INFO_AGREE_CREATE_DATE
AGREEMENT_INFO_AGREEMENT_SUB_TYPE=AGREE_INFO_AGREE_SUB_TYPE
NUMBER_OF_FAILED_AUTHENTICATIONS=NBR_FAILED_AUTHENTICATIONS
DELAY_BETWEEN_RETRIES_TIMER_EXPRESSION=DLY_BW_RETRIES_TIMER_EXPR
AGENCY_APPLICABLE_CHECK_LIST_ITEM_FK=AGENCY_CHECK_LIST_ITEM_FK
SERVICE_APPLICABLE_CHECK_LIST_ITEM_FK=SERVICE_CHECK_LIST_ITEM_FK
COMPANY_AGENCY_PAYMENT_TEMPLATE_FK=COMPANY_AGENCY_PMT_TEMPLATE_FK
E_F_E_PAYMENT_STATUS_EFFECTIVE_DATE=EFE_PMT_STATUS_EFF_DATE
E_F_E_PAYMENT_SUBMISSION_BATCH_FK=EFE_PYMT_BATCH_FK
COMPANY_AGENCY_ON_HOLD_REASON_FK=COMP_AGENCY_ON_HOLD_REASON
FINANCIAL_TRANSACTIONCOMPANY_AGENCY_ON_HOLD_REASON_FK_FINANCIAL_TRANSACTION=FINTXN_HOLD_COMP_AGENCY
FINANCIAL_TRANSACTIONCOMPANY_AGENCY_ON_HOLD_REASON_FK_COMPANY_AGENCY_ON_HOLD_REASON=FINTXN_COMP_AGENCY_HOLD
E_F_E_RETURN_STATUS_EFFECTIVE_DATE=EFE_RETURN_STATUS_EFF_DATE
REFUNDS_INTUIT_FOR_RETURNED_PAYMENTS=RFNDS_INTUIT_FOR_RETURNED_PMT
PRIOR_QUARTER_ADJUSTMENT_REQUIRES_AMENDMENT=PRIOR_QTR_ADJ_REQ_AMENDMENT
THIRD_PARTY401K_INFO_BIRTH_DATE=TP_401K_INFO_BIRTH_DATE
THIRD_PARTY401K_INFO_IS_HIGHLY_COMPENSATED=TP_401K_INFO_IS_HCE
THIRD_PARTY401K_INFO_OWNERSHIP_PERCENTAGE=TP_401K_INFO_OWNER_PERCENT
THIRD_PARTY401K_INFO_IS_FAMILY_MEMBER=TP_401K_INFO_IS_FAMILY_MEMBER
THIRD_PARTY401K_INFO_LAST401K_UPLOAD_DATE=TP_401K_INFO_LAST_UPLOAD_DATE
THIRD_PARTY401K_PAYROLL_ITEM_INFO_IS_PROVIDER_ACCEPTED=TP401K_IS_TOK_ACCEPTED
THIRD_PARTY401K_PAYROLL_ITEM_INFO_ALLOWS_NEGATIVE_AMOUNTS=TP401K_ALLOWS_NEGATIVE_AMOUNTS
IS_OFFLOADED_TRANSACTIONS_EVENT_CREATION_COMPLETE=IS_OFFLDTXN_EVT_COMPLETE
P_S_P_PROVIDES_CUSTOMER_SERVICE=PSP_PROVIDES_CUSTOMER_SERVICE
TAX_PAYMENT_STATUS_EFFECTIVE_DATE=TAX_PMTSTATUS_EFFECTIVEDATE
COMPANY_P_S_I_D=COMPANY_PSID
COMPANY_E_I_N=COMPANY_EIN
QBDT_PAYROLL_TRANSACTION_LINE_FK=QBDT_PAYROLL_TRANS_LINE_FK

THIRD_PARTY401K_BATCH_EMPLOYEE_FK_THIRD_PARTY401K_BATCH

QBDT_PAYROLL_TRANSACTION_FK_EMPLOYEE=QBDT_PAYROLL_TRANS_FK1
QBDT_PAYROLL_TRANSACTION_FK_PRIOR_PAYMENT_SUBMISSION=QBDT_PAYROLL_TRANS_FK2
QBDT_PAYROLL_TRANSACTION_FK_COMP_ADJUST_SUBMISSION=QBDT_PAYROLL_TRANS_FK3
QBDT_PAYROLL_TRANSACTION_LINE_FK_COMPANY_PAYROLL_ITEM=QBDT_PAYROLL_TRANSLINE_FK1

PAYROLL_TRANSACTION_DELETE_COUNT=PAYROLL_TRANS_DELETE_COUNT
PAYROLL_TRANSACTION_UPDATE_COUNT=PAYROLL_TRANS_UPDATE_COUNT
PAYROLL_TRANSACTION_UPDATE_START=PAYROLL_TRANS_UPDATE_START
PAYROLL_TRANSACTION_UPDATE_END=PAYROLL_TRANS_UPDATE_END

#Adjustments
COMPANY_ADJUSTMENT_SUBMISSION_FK=COMP_ADJUST_SUBMISSION_FK


#TransactionType
INCLUDE_IN_TRANSACTION_RESPONSE=INCLUDE_IN_TXN_RESPONSE

# Offer * --> * OfferingServiceCharge
OFFEROFFERINGSERVICECHARGE_ASSOC=OFFER_SVCCHG_ASSOC
OFFEROFFERING_SERVICE_CHARGE_FK_OFFER=OFFER_SVCCHG_FK_OFFER
OFFEROFFERING_SERVICE_CHARGE_FK_OFFERING_SERVICE_CHARGE=OFFER_SVCCHG_FK_SVCCHG
OFFEROFFERINGSERVICECHARGE_ASSOC_UT=OFFER_SVCCHG_ASSOC_UT
OFFEROFFERINGSERVICECHARGE_ASSOC_IT=OFFER_SVCCHG_ASSOC_IT


# Offering * --> * Service
OFFERINGSERVICE_ASSOC=OFFERING_SVC_ASSOC
OFFERINGSERVICE_FK_OFFERING=OFFERING_SVC_FK_OFFERING
OFFERINGSERVICE_FK_SERVICE=OFFERING_SVC_FK_SERVICE
OFFERINGSERVICE_ASSOC_UT=OFFERING_SVC_ASSOC_UT
OFFERINGSERVICE_ASSOC_IT=OFFERING_SVC_ASSOC_IT

# TP401kBatchEmployee * --> TP401kBatch
THIRD_PARTY401K_BATCH_EMPLOYEE_FK_THIRD_PARTY401K_BATCH=TP401K_BATCH_EE_FK1
THIRD_PARTY401K_BATCH_EMPLOYEE_FK_EMPLOYEE=TP401K_BATCH_EE_FK2

# TP401k
THIRD_PARTY401K_PAYCHECK_PENDING_STATE_FK_THIRD_PARTY401K_PAYCHECK=TP401K_PEND_STATE_PCHK_FK
THIRD_PARTY401K_PAYCHECK_STATE_FK_THIRD_PARTY401K_PAYCHECK=TP401K_PCHK_STATE_PCHK_FK
THIRD_PARTY401K_PAYCHECK_FK_PAYCHECK=TP401K_PCHK_PCHK_FK

#WorkersComp
WORKERS_COMP_PAYCHECK_PENDING_STATE_FK_WORKERS_COMP_PAYCHECK=WC_PEND_STATE_PCHK_FK
WORKERS_COMP_PAYCHECK_STATE_FK_WORKERS_COMP_PAYCHECK=WC_PCHK_STATE_PCHK_FK
WORKERS_COMP_PAYCHECK_FK_PAYCHECK=WC_PCHK_PCHK_FK


# OfferingServiceCharge 1 <-- * OfferingServiceChargePrice
OFFERINGSERVICECHARGEPRICE=SVCCHGPRICE
OFFERINGSERVICE_FK_OFFERING=SVCCHGPRICE_FK_OFFERING

# OfferingServiceCharge 1 --> * Offering
OFFERING_SERVICE_CHARGE_FK_OFFERING_SERVICE_CHARGE_GROUP=OFFERING_SVCCHG_FK
OFFERING_SERVICE_CHARGE_GROUP_FK_OFFERING=OFFERING_SVCCHG_GRP_FK

STATE_REPORT_OUTPUTPAYMENT_TEMPLATE_FREQUENCY_FK_STATE_REPORT_OUTPUT=STRPT_TMPFREQ_FK_STRPTOUT
STATE_REPORT_OUTPUTPAYMENT_TEMPLATE_FREQUENCY_FK_PAYMENT_TEMPLATE_FREQUENCY=STRPT_TMPFREQ_FK_PMTTMPFRQ



COMPANYON_HOLD_REASON_FK_COMPANY=COMPHOLD_REASON_FK_COMPANY
COMPANYON_HOLD_REASON_FK_ON_HOLD_REASON=COMPANY_FK_ON_HOLD_REASON
COMPANYONHOLDREASON_ASSOC_UT=COMP_ONHOLDREASON_ASSOC_UT
COMPANYONHOLDREASON_ASSOC_IT=COMP_ONHOLDREASON_ASSOC_IT
FINANCIAL_TRANSACTIONON_HOLD_REASON_FK_FINANCIAL_TRANSACTION=FIN_TXN_HOLD_FK_FIN_TXN
FINANCIAL_TRANSACTIONON_HOLD_REASON_FK_ON_HOLD_REASON=FIN_TXN_HOLD_FK_HOLD
FINANCIALTRANSACTIONONHOLDREASON_ASSOCFINANCIALTRANSACTIONONHOLDREASON_ASSOC_UT=FTXN_HOLD_FTXN_ASSOC_UT
FINANCIALTRANSACTIONONHOLDREASON_ASSOC_UT=FINTXN_HOLD_ASSOC_UT
FINANCIALTRANSACTIONONHOLDREASON_ASSOC_IT=FINTXN_HOLD_ASSOC_IT
SERVICE_SUB_STATUSSYSTEM_CAPABILITY_FK_SERVICE_SUB_STATUS=SVCSTAT_CAP_FK_SVCSTAT
SERVICE_SUB_STATUSSYSTEM_CAPABILITY_FK_SYSTEM_CAPABILITY=SVCSTAT_CAP_FK_CAP
SERVICESUBSTATUSSYSTEMCAPABILITY_ASSOC_UT=SVCSTAT_CAP_ASSOC_UT
SERVICESUBSTATUSSYSTEMCAPABILITY_ASSOC_IT=SVCSTAT_CAP_ASSOC_IT
SERVICE_SUB_STATUSSOURCE_SYSTEM_FK_SERVICE_SUB_STATUS=SVCSTAT_SRCSYS_FK_SVCSTAT
SERVICE_SUB_STATUSSOURCE_SYSTEM_FK_SOURCE_SYSTEM=SVCSTAT_SRCSYS_FK_SRCSYS
SERVICESUBSTATUSSOURCESYSTEM_ASSOC_UT=SVCSTAT_SRCSYS_ASSOC_UT
SERVICESUBSTATUSSOURCESYSTEM_ASSOC_IT=SVCSTAT_SRCSYS_ASSOC_IT
SERVICE_SUB_STATUSSERVICE_FK_SERVICE_SUB_STATUS=SVCSTAT_SVC_FK_SVCSTAT
SERVICE_SUB_STATUSSERVICE_FK_SERVICE=SVCSTAT_SVC_FK_SVC
SERVICESUBSTATUSSERVICE_ASSOC_UT=SVCSTAT_SVC_ASSOC_UT
SERVICESUBSTATUSSERVICE_ASSOC_IT=SVCSTAT_SVC_ASSOC_IT
SERVICE_SUB_STATUSTRANSACTION_TYPE_FK_SERVICE_SUB_STATUS=SVCSTAT_TXNTYPE_FK_SVCSTAT
SERVICE_SUB_STATUSTRANSACTION_TYPE_FK_TRANSACTION_TYPE=SVCSTAT_TXNTYPE_FK_TXNTYPE
SERVICESUBSTATUSTRANSACTIONTYPE_ASSOC_UT=SVCSTAT_TXNTYPE_ASSOC_UT
SERVICESUBSTATUSTRANSACTIONTYPE_ASSOC_IT=SVCSTAT_TXNTYPE_ASSOC_IT
PAYMENT_TEMPLATE_FK_PAYMENT_TEMPLATE_FREQUENCY=PMTTEMPL_FK_PMTTEMPL_FREQ

EVENT_DETAIL_TYPEEVENT_TYPE_FK_EVENT_DETAIL_TYPE=EVTDTLTP_EVTTP_FK_EVTDTTP
EVENT_DETAIL_TYPEEVENT_TYPE_FK_EVENT_TYPE=EVTDTLTP_EVTTP_FK_EVTTP
EVENTDETAILTYPEEVENTTYPE_ASSOC=EVTDTLTP_EVTTP_ASSOC
EVENTDETAILTYPEEVENTTYPE_ASSOC_UT=EVTDTLTP_EVTTP_ASSOC_UT
EVENTDETAILTYPEEVENTTYPE_ASSOC_IT=EVTDTLTP_EVTTP_ASSOC_IT
INTERESTING_EVENT_TYPESSOURCE_SYSTEM_FK_INTERESTING_EVENT_TYPES=EVTTP_SRCSYS_FK_EVTTP
INTERESTING_EVENT_TYPESSOURCE_SYSTEM_FK_SOURCE_SYSTEM=EVTTP_SRCSYS_FK_SRCSYS
INTERESTINGEVENTTYPESSOURCESYSTEM_ASSOC=EVTTP_SRCSYS_ASSOC
INTERESTINGEVENTTYPESSOURCESYSTEM_ASSOC_UT=EVTTP_SRCSYS_ASSOC_UT
INTERESTINGEVENTTYPESSOURCESYSTEM_ASSOC_IT=EVTTP_SRCSYS_ASSOC_IT

#AuthRole *-->* AuthOperation
AUTHROLEAUTHOPERATION_ASSOC=AUTHROLE_OPERATION_ASSOC
AUTH_ROLEAUTH_OPERATION_FK_AUTH_ROLE = ROLE_OPERATION_FK_ROLE
AUTH_ROLEAUTH_OPERATION_FK_AUTH_OPERATION=AUTHROLE_OPT_FK_OPT
AUTHROLEAUTHOPERATION_ASSOC_UT=ROLEOPERATION_ASSOC_UT
AUTHROLEAUTHOPERATION_ASSOC_IT=ROLEOPERATION_ASSOC_IT

AUTH_USERAUTH_ROLE_FK_AUTH_USER=USERROLE_FK_USER
AUTH_USERAUTH_ROLE_FK_AUTH_ROLE=USERROLE_FK_ROLE

#BillingDetail -> * FinancialTransaction
BILLING_DETAIL_FK_FINANCIAL_TRANSACTION=BILLING_DETAIL_FK_FIN_TXN

TRANSACTIONTYPESERVICE_ASSOC=TXNTYPE_SERVICE_ASSOC
TRANSACTION_TYPESERVICE_FK_TRANSACTION_TYPE=TXNTYPE_SVC_FK_TXNTYPE
TRANSACTION_TYPESERVICE_FK_SERVICE=TXNTYPE_SVC_FK_SVC
TRANSACTIONTYPESERVICE_ASSOC_UT=TXNTYPE_SVC_ASSOC_UT
TRANSACTIONTYPESERVICE_ASSOC_IT=TXNTYPE_SVC_ASSOC_IT

#CompanyAgency
INTUIT_RESPONSIBILITY_START_DATE=RESP_START_DATE
INTUIT_RESPONSIBILITY_END_DATE=RESP_END_DATE

#ACHEnrollment <-> ACHEnrollmentBatch
ACHENROLLMENTACHENROLLMENTBATCH_ASSOC_IT=ACHENROLBATCH_ASSOC_IT
ACHENROLLMENTACHENROLLMENTBATCH_ASSOC_UT=ACHENROLBATCH_ASSOC_UT
A_C_H_ENROLLMENTA_C_H_ENROLLMENT_BATCH_FK_A_C_H_ENROLLMENT=ACHENROL_FK_ACHENROL
A_C_H_ENROLLMENTA_C_H_ENROLLMENT_BATCH_FK_A_C_H_ENROLLMENT_BATCH=ACHENROL_FK_ACHENROLBATCH

#CompanyEvent
EVENTS_GATEWAY_STATUS_EFFECTIVE_DATE=EVTGTWY_STATUS_EFF_DT

#RAF Batch Job
R_A_F_ENROLLMENTR_A_F_ENROLLMENT_BATCH_FK_R_A_F_ENROLLMENT=RAFENROLLMENT_BATCH_FK1
R_A_F_ENROLLMENTR_A_F_ENROLLMENT_BATCH_FK_R_A_F_ENROLLMENT_BATCH=RAFENROLLMENT_BATCH_FK2
RAFENROLLMENTRAFENROLLMENTBATCH_ASSOC=RAFENROLLMENT_BATCH_ASSOC
RAFENROLLMENTRAFENROLLMENTBATCH_ASSOC_UT=RAF_BATCH_ASSOC_UT
RAFENROLLMENTRAFENROLLMENTBATCH_ASSOC_IT=RAF_BATCH_ASSOC_IT

#Triggers
FINANCIALTRANSACTIONCOMPANYAGENCYONHOLDREASON_ASSOC_UT=FINTXN_AGENCY_HOLD_ASOC_UT
FINANCIALTRANSACTIONCOMPANYAGENCYONHOLDREASON_ASSOC_IT=FINTXN_AGENCY_HOLD_ASOC_IT
PSP_MONEY_MOVEMENT_TRANSACTION_AT=PSP_MONEY_MVMT_TRANS_AT
PSP_COMP_PMTTEMPLATE_PMTMETHOD_AT=PSP_CMPMTMPLT_PMTMTD_AT
PSP_COMPANYAGENCY_PMTTEMPLATE_AT=PSP_CMPNYAGENCY_PMTTPLT_AT
PSP_TAX_COMPANY_SERVICE_INFO_AT=PSP_TAX_CS_INFO_AT


#PayrollTax
PAYROLL_TAXLAW_FK_PAYROLL_TAX=PAYROLL_TAXLAW_FK

#CheckPrintPaycheck
CHECK_PRINT_PAYCHECK_STATUS_CODE=CP_PAYCHECK_STATUS_CODE

#EntityChange
OLD_E_I_N=OLD_EIN
NEW_E_I_N=NEW_EIN

#PaymentTemplate
PAYMENT_TEMPLATE_PAYMENT_METHOD_FK=PMT_TEMPLATE_PMT_METHOD_FK
COMPANY_PAYMENT_TEMPLATE_AGENCY_ID_FK_COMPANY_AGENCY_PAYMENT_TEMPLATE=COMPANYPAYMENTTEMPLATE_FK2

#Check payments
PAYMENTTEMPLATECHECKINFOASSOC=PMTTEMPLATE_CHKINFO_ASSOC
PAYMENTTEMPLATEPRINTEDCHECKINFO=PMTTEMPLATE_PRINTEDCHKINFO
SOURCESYSTEMPRINTEDCHECKINFO=SOURCESYS_PRINTEDCHK_INFO
SOURCE_SYSTEM_PRINTED_CHECK_INFO_FK=SOURCESYS_PRINTEDCHK_INFO_FK
PAYMENT_TEMPLATE_PRINTED_CHECK_INFO_FK=PMTTEMPLATE_PRINTEDCHKINFO_FK

#Disburse Advice Tax Liab
DISBURSE_ADVICE_TAX_LIAB_FK_DISBURSE_ADVICE=DISBURSE_ADVICE_TAX_LI_FK1
DISBURSE_ADVICE_TAX_LIAB_FK_TIPS_LIABILITY=DISBURSE_ADVICE_TAX_LI_FK2
DISBURSE_ADVICE_TAX_LIAB_FK_COMPANY=DISBURSE_ADVICE_TAX_LI_FK3

