drop synonym PSP_ACTIVATION_CHECK_LIST;
drop synonym PSP_ACTIVATION_CHECK_LIST_ITEM;
drop synonym PSP_AGENCY_CHECK_LIST_ITEM;
drop synonym PSP_AGENCY_CHECK_LIST_STATUS;
drop synonym PSP_BASIC_CHECK_LIST_ITEM;
drop synonym PSP_ENROLLMENT_CHECK_LIST_ITEM;
drop synonym PSP_SERVICE_CHECK_LIST_ITEM;
drop synonym PSP_SERVICE_CHECK_LIST_STATUS;
drop synonym PSP_RAFENROLLMENT_BATCH;
drop synonym PSP_RAFENROLLMENT_BATCH_ASSOC;
drop synonym PRC_RAFTAPE;

-- todo if exists
DECLARE

	constraint_exists PLS_INTEGER;

BEGIN


	SELECT COUNT(*) INTO constraint_exists
	FROM USER_CONSTRAINTS 
	WHERE CONSTRAINT_NAME = 'SYS_C00137996' AND TABLE_NAME = 'PSP_LIABILITY_CHECK';

	IF constraint_exists = 1 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE PSP_LIABILITY_CHECK_LINE DROP CONSTRAINT SYS_C00137996';
	END IF;

END;

COMMIT;