-- pre_deploy for 1.8


alter table PSP_OFFERING disable constraint PSP_SVCCHGPRICE_FK_OFFERING
/

DROP SYNONYM pspapp.PSP_OFFERING_SVC_ASSOC
/

CREATE INDEX PSPADM.PSP_COMPANY_I3 ON PSPADM.PSP_COMPANY
( P_S_ID )
LOGGING
TABLESPACE PSP_IDX01
NOPARALLEL
MONITORING
/