--***new table

CREATE TABLE PSP_TAX_CREDITS_APPLICATION
(
  TAX_CREDITS_APPLICATION_SEQ  VARCHAR2(255 CHAR) NOT NULL,
  VERSION                      NUMBER(19)       NOT NULL,
  CREATOR_ID                   VARCHAR2(30 CHAR),
  CREATED_DATE                 TIMESTAMP(6)     NOT NULL,
  MODIFIER_ID                  VARCHAR2(30 CHAR),
  MODIFIED_DATE                TIMESTAMP(6)     NOT NULL,
  REALM_ID                     NUMBER(19)       DEFAULT -1                    NOT NULL,
  UNSIGNED_DOCUMENT            CLOB,
  SIGNED_DOCUMENT              CLOB,
  DOCUMENT_KEY                 VARCHAR2(4000 CHAR),
  SIGNERS_REMAINING            VARCHAR2(4000 CHAR),
  DOCUMENT_PASSWORD            VARCHAR2(4000 CHAR),
  EMPLOYER_EMAIL               VARCHAR2(4000 CHAR),
  EMPLOYEE_EMAIL               VARCHAR2(4000 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

ALTER TABLE PSP_TAX_CREDITS9061
 ADD (TAX_CREDITS_APPLICATION_FK  VARCHAR2(255 CHAR) NOT NULL)
/

--
-- PSP_TAX_CREDITS9061_FK1  (Index) 
--
CREATE INDEX PSP_TAX_CREDITS9061_FK1 ON PSP_TAX_CREDITS9061
(TAX_CREDITS_APPLICATION_FK, REALM_ID)
LOGGING
NOPARALLEL
/


ALTER TABLE PSP_TAX_CREDITS9061
 ADD CONSTRAINT PSP_TAX_CREDITS9061_FK1 
 FOREIGN KEY (TAX_CREDITS_APPLICATION_FK, REALM_ID) 
 REFERENCES PSP_TAX_CREDITS_APPLICATION (TAX_CREDITS_APPLICATION_SEQ,REALM_ID)
/

ALTER TABLE PSP_TAX_CREDITS_APPLICATION
 ADD PRIMARY KEY
 (TAX_CREDITS_APPLICATION_SEQ, REALM_ID)
/


--***update constraints
alter table psp_batch_job_setup drop constraint c_psp_batch_job_setup0
/

alter table psp_batch_job_setup ADD (CONSTRAINT c_psp_batch_job_setup0 CHECK (JOB_TYPE IN('AchReturnsMonitor', 'AchTransactionsMonitor', 'As400ToCris', 'BalanceFileMonitor', 'CrisToSourceSystem', 'EmailGateway', 'EmailGatewayMonitor', 'FeeEvents', 'FeeEventsMonitor', 'FraudPayrolls', 'FraudPayrollsMonitor', 'GemsAccountsReceivable', 'GemsAccountsReceivableMonitor', 'GemsGeneralLedger', 'GemsGeneralLedgerMonitor', 'LedgerBalance', 'LedgerBalanceMonitor', 'MissedPayrollsMonitor', 'MissedTransactionsMonitor', 'NightlyBatchJobs', 'NightlyBatchJobsMonitor', 'PrimaryAchOffloadMonitor', 'PrimaryDailyBatchJobs', 'PrimaryDailyBatchJobsMonitor', 'PspToCris', 'ScheduledAchOffloadMonitor', 'ScheduledDailyBatchJobs', 'ScheduledDailyBatchJobsMonitor', 'As400EventSync', 'GemsGeneralLedgerUpload', 'GemsGeneralLedgerUploadMonitor', 'AchOffloadCompleteMonitor', 'EventsGateway', 'RAFWriter', 'EftpsEnrollments', 'ATFDataExtract', 'TaxPaymentSubmission', 'TaxPaymentSynchronization', 'TriggerAmendments', 'HPDEBatchProcessor', 'PrimaryDailyForecast', 'CheckPrint', 'CheckPrintMonitor', 'TaxCreditsEchoSignMonitor', 'OffloadedTransactionsEvents', 'OffloadedTransactionsEventsMonitor', 'ThirdParty401kOffload', 'ThirdParty401kSignup', 'ThirdParty401kValidation', 'ThirdParty401kOffloadMonitor', 'ThirdParty401kSignupMonitor', 'ThirdParty401kValidationMonitor', 'As400DataSync', 'As400DataSyncMonitor', 'TaxCreditsEchoSign')))
/

--***initial data
INSERT INTO PSP_SYSTEM_PARAMETER (SYSTEM_PARAMETER_SEQ, SYSTEM_PARAMETER_CD, SYSTEM_PARAMETER_VALUE, SYSTEM_PARAMETER_DESCRIPTION, SYSTEM_PARAMETER_ORG, VERSION, CREATED_DATE, MODIFIED_DATE) VALUES ( 
'0455979c-3520-4630-b5ce-b5b3b961b3a7', 'TAX_CREDITS_ECHOSIGN_SYNC_WINDOW', '45', 'Days back to sync documents from Echosign', 'PSP', 0, SYSDATE, SYSDATE)
/
INSERT INTO PSP_SYSTEM_PARAMETER (SYSTEM_PARAMETER_SEQ, SYSTEM_PARAMETER_CD, SYSTEM_PARAMETER_VALUE, SYSTEM_PARAMETER_DESCRIPTION, SYSTEM_PARAMETER_ORG, VERSION, CREATED_DATE, MODIFIED_DATE) VALUES ( 
'0455979c-3520-4630-b5ce-b5b3b961b3a8', 'TAX_CREDITS_ECHOSIGN_ENDPOINT', 'https://secure.echosign.com/services/EchoSignDocumentService9', 'EchoSign endpoint URL', 'PSP', 0, SYSDATE, SYSDATE)
/


INSERT INTO PSP_BATCH_JOB_SETUP ( JOB_TYPE, JOB_TIMER_EXPRESSION, VERSION, REALM_ID, DLY_BW_RETRIES_TIMER_EXPR, IS_AUTOMATICALLY_SCHEDULED, JOB_PROCESSOR_CLASS_NAME, JOB_NAMESPACE, MAX_RETRIES)
    VALUES ('TaxCreditsEchoSign', '+5m', 1, -1, '+5m', 1, 'com.intuit.sbd.payroll.psp.batchjobs.processors.TaxCreditsEchoSignSyncProcessor', '/PSP/NORMAL', 5)
/
INSERT INTO PSP_BATCH_JOB_SETUP ( JOB_TYPE, JOB_TIMER_EXPRESSION, VERSION, REALM_ID, DLY_BW_RETRIES_TIMER_EXPR, IS_AUTOMATICALLY_SCHEDULED, JOB_PROCESSOR_CLASS_NAME, JOB_NAMESPACE, MAX_RETRIES)
    VALUES ('TaxCreditsEchoSignMonitor', '0 0 0-59/15 * * * * * * * *', 1, -1, '', 1, 'com.intuit.sbd.payroll.psp.batchjobs.monitors.TaxCreditsEchoSignSyncMonitor', '/PSP/MONITOR', 0)
/


--PSRV001921
INSERT INTO PSP_ROLE_SUB_STATUS ( ROLE_SUB_STATUS_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ALLOWED_CHANGE_TYPE,
SERVICE_SUB_STATUS_FK, AUTH_ROLE_FK)
VALUES ('8391f43e-f3d3-3de1-4729-772d7341edc2', 0, SYSDATE, SYSDATE, 'CanMoveToSubStatus','ActiveCurrent',
'675e8b0e-43f4-a631-5341-6fd6a5327356')
/

INSERT INTO PSP_ROLE_SUB_STATUS ( ROLE_SUB_STATUS_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ALLOWED_CHANGE_TYPE,
SERVICE_SUB_STATUS_FK, AUTH_ROLE_FK)
VALUES ('dc42941a-e437-35a2-a474-fdd2333ee4ec', 0, SYSDATE, SYSDATE, 'CanMoveToSubStatus','FraudReview',
'675e8b0e-43f4-a631-5341-6fd6a5327356')
/

INSERT INTO PSP_ROLE_SUB_STATUS ( ROLE_SUB_STATUS_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ALLOWED_CHANGE_TYPE,
SERVICE_SUB_STATUS_FK, AUTH_ROLE_FK)
VALUES ('431fa34f-e437-35a1-a924-339778bb58ff', 0, SYSDATE, SYSDATE, 'CanMoveFromSubStatus','RiskAssessment',
'675e8b0e-43f4-a631-5341-6fd6a5327356')
/

INSERT INTO PSP_ROLE_SUB_STATUS ( ROLE_SUB_STATUS_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ALLOWED_CHANGE_TYPE,
SERVICE_SUB_STATUS_FK, AUTH_ROLE_FK)
VALUES ('ffadda3f-e437-3efd-a474-fd9254874434', 0, SYSDATE, SYSDATE, 'CanMoveFromSubStatus','IntuitCollections',
'675e8b0e-43f4-a631-5341-6fd6a5327356')
/

INSERT INTO PSP_ROLE_SUB_STATUS ( ROLE_SUB_STATUS_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ALLOWED_CHANGE_TYPE,
SERVICE_SUB_STATUS_FK, AUTH_ROLE_FK)
VALUES ('ddf9383f-ddf7-ddaa-face-ee3389133433', 0, SYSDATE, SYSDATE, 'CanMoveFromSubStatus','RiskCollections',
'675e8b0e-43f4-a631-5341-6fd6a5327356')
/

INSERT INTO PSP_ROLE_SUB_STATUS ( ROLE_SUB_STATUS_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ALLOWED_CHANGE_TYPE,
SERVICE_SUB_STATUS_FK, AUTH_ROLE_FK)
VALUES ('faa12bad-eff7-1287-a474-4492e833accc', 0, SYSDATE, SYSDATE, 'CanMoveFromSubStatus','Fraud','675e8b0e-43f4-a631-5341-6fd6a5327356')
/

INSERT INTO PSP_ROLE_SUB_STATUS ( ROLE_SUB_STATUS_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ALLOWED_CHANGE_TYPE,
SERVICE_SUB_STATUS_FK, AUTH_ROLE_FK)
VALUES ('dfeed3af-e437-35a1-aaad-248394843ad1', 0, SYSDATE, SYSDATE, 'CanMoveFromSubStatus','FraudReview','675e8b0e-43f4-a631-5341-6fd6a5327356')
/

INSERT INTO PSP_ROLE_SUB_STATUS ( ROLE_SUB_STATUS_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ALLOWED_CHANGE_TYPE,
SERVICE_SUB_STATUS_FK, AUTH_ROLE_FK)
VALUES ('223d61af-dc57-35a1-ffdd-dddf454ddf82', 0, SYSDATE, SYSDATE, 'CanMoveFromSubStatus','SuspendedDirectDeposit','675e8b0e-43f4-a631-5341-6fd6a5327356')
/

INSERT INTO PSP_ROLE_SUB_STATUS ( ROLE_SUB_STATUS_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ALLOWED_CHANGE_TYPE,
SERVICE_SUB_STATUS_FK, AUTH_ROLE_FK)
VALUES ('11f44393-e517-35a1-a474-5592847addfc', 0, SYSDATE, SYSDATE, 'CanMoveFromSubStatus','PendingTermination','675e8b0e-43f4-a631-5341-6fd6a5327356')
/


INSERT INTO PSP_ROLE_SUB_STATUS ( ROLE_SUB_STATUS_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ALLOWED_CHANGE_TYPE,
SERVICE_SUB_STATUS_FK, AUTH_ROLE_FK)
VALUES ('abf43a06-0000-0000-a474-000000000000', 0, SYSDATE, SYSDATE, 'CanMoveFromSubStatus','AchRejectOther','675e8b0e-43f4-a631-5341-6fd6a5327356')
/

INSERT INTO PSP_ROLE_SUB_STATUS ( ROLE_SUB_STATUS_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ALLOWED_CHANGE_TYPE,
SERVICE_SUB_STATUS_FK, AUTH_ROLE_FK)
VALUES ('abf44c66-0000-0000-a474-000000000001', 0, SYSDATE, SYSDATE, 'CanMoveFromSubStatus','AchRejectR1R9','675e8b0e-43f4-a631-5341-6fd6a5327356')
/

INSERT INTO PSP_ROLE_SUB_STATUS ( ROLE_SUB_STATUS_SEQ, VERSION, CREATED_DATE, MODIFIED_DATE, ALLOWED_CHANGE_TYPE,
SERVICE_SUB_STATUS_FK, AUTH_ROLE_FK)
VALUES ('abf44000-0cca-0000-a474-000000000046', 0, SYSDATE, SYSDATE, 'CanMoveFromSubStatus','PendingPrefundingWire','675e8b0e-43f4-a631-5341-6fd6a5327356')
/
