SPO coe_xfr_sql_profile_fam5cqu99ukb6_1989083634.log;
SET ECHO ON TERM ON LIN 2000 TRIMS ON NUMF 99999999999999999999;
REM
REM $Header: 215187.1 coe_xfr_sql_profile_fam5cqu99ukb6_1989083634.sql 11.4.1.4 2018/04/30 csierra $
REM
REM Copyright (c) 2000-2010, Oracle Corporation. All rights reserved.
REM
REM AUTHOR
REM   carlos.sierra@oracle.com
REM
REM SCRIPT
REM   coe_xfr_sql_profile_fam5cqu99ukb6_1989083634.sql
REM
REM DESCRIPTION
REM   This script is generated by coe_xfr_sql_profile.sql
REM   It contains the SQL*Plus commands to create a custom
REM   SQL Profile for SQL_ID fam5cqu99ukb6 based on plan hash
REM   value 1989083634.
REM   The custom SQL Profile to be created by this script
REM   will affect plans for SQL commands with signature
REM   matching the one for SQL Text below.
REM   Review SQL Text and adjust accordingly.
REM
REM PARAMETERS
REM   None.
REM
REM EXAMPLE
REM   SQL> START coe_xfr_sql_profile_fam5cqu99ukb6_1989083634.sql;
REM
REM NOTES
REM   1. Should be run as SYSTEM or SYSDBA.
REM   2. User must have CREATE ANY SQL PROFILE privilege.
REM   3. SOURCE and TARGET systems can be the same or similar.
REM   4. To drop this custom SQL Profile after it has been created:
REM      EXEC DBMS_SQLTUNE.DROP_SQL_PROFILE('coe_fam5cqu99ukb6_1989083634');
REM   5. Be aware that using DBMS_SQLTUNE requires a license
REM      for the Oracle Tuning Pack.
REM
WHENEVER SQLERROR EXIT SQL.SQLCODE;
REM
VAR signature NUMBER;
REM
DECLARE
sql_txt CLOB;
h       SYS.SQLPROF_ATTR;
BEGIN
sql_txt := q'[
/* ReadListTxnNeoDAO.fastReadRcntExpTotalsMoreWhere7fc5774b */  SELECT  SUM( CASE WHEN (TxDetails.is_ap_paid = '1' AND TxDetails.Amount > 0) THEN 0 ELSE  CASE WHEN TxHeaders.Tx_Type_Id = 4       THEN  TxHeaders.amount + NVL((SELECT SUM(TxdSub10.amount) FROM TxDetails_1 TxdSub10 WHERE TxdSub10.tx_id = TxHeaders.tx_id AND TxdSub10.sales_detail_type = 8),0)  WHEN TxHeaders.Tx_type_Id IN (1,3,7,9,11,12,41,46,54)       THEN -TxHeaders.amount  WHEN (TxHeaders.Tx_type_Id = 25 OR TxHeaders.Tx_type_Id = 13) AND TxHeaders.Is_No_Post = 1       THEN TxHeaders.amount + NVL(TxHeaders.tax_amount, 0)  WHEN (TxHeaders.Tx_Type_Id IN (8)  AND TxDetails.IS_AP_PAID in ('1','2'))
THEN NVL(-TxDetails.amount, 0)  WHEN TxHeaders.Tx_Type_Id IN (8,27)       THEN NVL(TxDetails.amount, 0)  ELSE TxHeaders.amount   END  END ),  SUM( CASE WHEN (TxDetails.is_ar_paid = '1' AND TxDetails.Amount > 0) THEN 0 ELSE  CASE WHEN TxHeaders.Tx_Type_Id = 4       THEN  TxHeaders.home_amount + NVL((SELECT SUM(TxdSub10.home_amount) FROM TxDetails_1 TxdSub10 WHERE TxdSub10.tx_id = TxHeaders.tx_id AND TxdSub10.sales_detail_type = 8),0)  WHEN TxHeaders.Tx_type_Id IN (1,3,7,9,11,12,41,46,54)       THEN -TxHeaders.home_amount  WHEN (TxHeaders.Tx_type_Id = 25 OR TxHeaders.Tx_type_Id = 13) AND TxHeaders.Is_No_Post = 1       THEN TxHeaders.home_amount +
(TxHeaders.tax_amount * NVL(TxHeaders.exchange_rate, 10000000) / 10000000)  WHEN (TxHeaders.Tx_Type_Id IN (8)  AND TxDetails.IS_AP_PAID in ('1','2'))       THEN NVL(-TxDetails.home_amount, 0)  WHEN TxHeaders.Tx_Type_Id IN (8,27)       THEN NVL(TxDetails.home_amount, 0)  ELSE TxHeaders.home_amount   END  END ),  SUM(  CASE WHEN TxHeaders.Tx_type_Id IN (1,3,7,9,11,12,41,46,54)       THEN NVL(-TxHeaders.open_balance,0)  WHEN (TxHeaders.Tx_Type_Id IN (8) AND TxDetails.IS_AP_PAID in ('1','2'))       THEN NVL(-TxDetails.open_balance,0)  WHEN TxHeaders.Tx_Type_Id IN (8,27)       THEN NVL(TxDetails.open_balance,0)  ELSE NVL(TxHeaders.open_balance,0)   END  ),  SUM(
CASE WHEN TxHeaders.Tx_type_Id IN (1,3,7,9,11,12,41,46,54)       THEN ROUND((-TxHeaders.open_balance/10000000)*(NVL(TxHeaders.exchange_rate, 10000000)/10000000),2)*10000000  WHEN (TxHeaders.Tx_Type_Id IN (8) AND TxDetails.IS_AP_PAID in ('1','2'))       THEN ROUND(-TxDetails.open_balance/10000000*NVL(TxDetails.exchange_rate, 10000000)/10000000 ,2)*10000000  WHEN TxHeaders.Tx_Type_Id IN (8,27)       THEN ROUND(TxDetails.open_balance/10000000*NVL(TxDetails.exchange_rate, 10000000)/10000000 ,2)*10000000  ELSE ROUND(TxHeaders.open_balance/10000000*NVL(TxHeaders.exchange_rate, 10000000)/10000000,2)*10000000   END  ),  SUM( TxHeaders.tax_amount ),  SUM(
TxHeaders.net_amount ),  SUM( CASE WHEN (TxDetails.is_ap_paid = '1' AND TxDetails.Amount > 0) THEN 0 ELSE 1 END ), SUM( CASE WHEN ABS(trunc(current_date - TxDetails.tx_date)) <= 30           THEN DECODE (TxDetails.tx_type_id,                  1,  CASE WHEN (TxDetails.sequence = 0 AND Accounts.account_type_id in (0,2,6)) THEN  ROUND((-TxDetails.amount/10000000)*(NVL(TxHeaders.exchange_rate, 10000000)/10000000),2)*10000000 ELSE 0 END,                  3,  CASE WHEN (TxDetails.sequence = 0 AND Accounts.account_type_id in (0,2,6)) THEN  ROUND((-TxDetails.amount/10000000)*(NVL(TxHeaders.exchange_rate, 10000000)/10000000),2)*10000000 ELSE 0 END,
11, CASE WHEN (TxDetails.sequence = 0 AND Accounts.account_type_id in (0,2,6)) THEN  ROUND((-TxDetails.amount/10000000)*(NVL(TxHeaders.exchange_rate, 10000000)/10000000),2)*10000000 ELSE 0 END,                  31, CASE WHEN (TxDetails.sequence = 0 AND Accounts.account_type_id in (0,2,6)) THEN  ROUND((-TxDetails.amount/10000000)*(NVL(TxHeaders.exchange_rate, 10000000)/10000000),2)*10000000 ELSE 0 END,                  48, CASE WHEN (TxDetails.sequence = 0 AND Accounts.account_type_id in (0,2,6)) THEN  ROUND((-TxDetails.amount/10000000)*(NVL(TxHeaders.exchange_rate, 10000000)/10000000),2)*10000000 ELSE 0 END,                  50, CASE WHEN (TxDetails.sequence
= 0 AND Accounts.account_type_id in (0,2,6)) THEN  ROUND((-TxDetails.amount/10000000)*(NVL(TxHeaders.exchange_rate, 10000000)/10000000),2)*10000000 ELSE 0 END,                  54, CASE WHEN (TxDetails.sequence = 0 AND Accounts.account_type_id in (0,2,6)) THEN  ROUND((-TxDetails.amount/10000000)*(NVL(TxHeaders.exchange_rate, 10000000)/10000000),2)*10000000 ELSE 0 END,                  63, CASE WHEN (TxDetails.sequence = 0 AND Accounts.account_type_id in (0,2,6)) THEN  ROUND((-TxDetails.amount/10000000)*(NVL(TxHeaders.exchange_rate, 10000000)/10000000),2)*10000000 ELSE 0 END,                  9,  0,                  12, 0,                  CASE WHEN
(TxDetails.is_ap_paid IN ('1','2') AND TxDetails.vendor_id IS NOT NULL AND TxDetails.amount > 0) THEN ROUND((TxDetails.amount/10000000)*(NVL(TxHeaders.exchange_rate, 10000000)/10000000),2)*10000000 ELSE 0 END                  )           END    ) AS RECENTLY_PAID_AMOUNT  FROM  TxHeaders_1 TxHeaders, TxDetails_1 TxDetails, Accounts_1 Accounts, NameTypePairs_1 NameTypePairs, NameTypePairs_1 Hnom, PaymentMethods_1 PaymentMethods  WHERE  TxHeaders.Tx_Id = TxDetails.Tx_Id AND TxHeaders.name_id = Hnom.name_id(+) AND  TxDetails.Vendor_Id = NameTypePairs.Name_Id(+) AND TxDetails.Account_id = Accounts.Account_id AND TxHeaders.payment_method_id =
PaymentMethods.payment_method_id(+) AND ( TxDetails.Tx_Id,TxDetails.Sequence ) IN (         (SELECT TxSub3.Tx_Id,TxSub3.sequence                FROM TxHeaders_1 ThSub3, TxDetails_1 TxSub3                 WHERE ThSub3.last_modify_date >= current_date-45                  AND ThSub3.tx_date >= trunc(current_date)-30 AND ThSub3.tx_date < trunc(current_date)+30                  AND ThSub3.tx_id = TxSub3.tx_id                  AND (                       (ThSub3.tx_type_id IN (1,3,11,31,48,50,54,63) AND TxSub3.sequence = 0)                   OR (ThSub3.tx_type_id != 12 AND TxSub3.is_ap_paid  IN (1,2)  AND TxSub3.amount > 0 )                  )         )   UNION
(SELECT TxSub4.Tx_Id,TxSub4.sequence               FROM TxHeaders_1 ThSub4, TxDetails_1 TxSub4               WHERE ThSub4.last_modify_date >= current_date-45                 AND ThSub4.tx_id = TxSub4.tx_id                 AND TxSub4.is_ap_paid IN (1,2)                 AND TxSub4.amount < 0                 AND ABS(trunc(current_date - TxSub4.paid_date)) <= 30         )  )  AND NameTypePairs.hidden is null AND Hnom.hidden is null AND NameTypePairs.name_type_id = 1
]';
h := SYS.SQLPROF_ATTR(
q'[BEGIN_OUTLINE_DATA]',
q'[IGNORE_OPTIM_EMBEDDED_HINTS]',
q'[OPTIMIZER_FEATURES_ENABLE('12.1.0.2')]',
q'[DB_VERSION('12.1.0.2')]',
q'[OPT_PARAM('_optimizer_use_feedback' 'false')]',
q'[OPT_PARAM('_px_adaptive_dist_method' 'off')]',
q'[OPT_PARAM('_optimizer_dsdir_usage_control' 0)]',
q'[OPT_PARAM('_optimizer_adaptive_plans' 'false')]',
q'[OPT_PARAM('_optimizer_strans_adaptive_pruning' 'false')]',
q'[OPT_PARAM('_optimizer_gather_feedback' 'false')]',
q'[OPT_PARAM('_optimizer_nlj_hj_adaptive_join' 'false')]',
q'[ALL_ROWS]',
q'[OUTLINE_LEAF(@"SEL$335DD26A")]',
q'[MERGE(@"SEL$3")]',
q'[OUTLINE_LEAF(@"SEL$7286615E")]',
q'[MERGE(@"SEL$5")]',
q'[OUTLINE_LEAF(@"SEL$E28402CB")]',
q'[MERGE(@"SEL$13")]',
q'[MERGE(@"SEL$14")]',
q'[OUTLINE_LEAF(@"SEL$EEE90419")]',
q'[MERGE(@"SEL$16")]',
q'[MERGE(@"SEL$17")]',
q'[OUTLINE_LEAF(@"SET$FCA7A018")]',
q'[OUTLINE_LEAF(@"SEL$57CDC764")]',
q'[UNNEST(@"SET$1" UNNEST_INNERJ_DISTINCT_VIEW)]',
q'[OUTLINE(@"SEL$2")]',
q'[OUTLINE(@"SEL$3")]',
q'[OUTLINE(@"SEL$4")]',
q'[OUTLINE(@"SEL$5")]',
q'[OUTLINE(@"SEL$12")]',
q'[OUTLINE(@"SEL$13")]',
q'[OUTLINE(@"SEL$14")]',
q'[OUTLINE(@"SEL$15")]',
q'[OUTLINE(@"SEL$16")]',
q'[OUTLINE(@"SEL$17")]',
q'[OUTLINE(@"SET$1")]',
q'[OUTLINE(@"SEL$55270BE5")]',
q'[MERGE(@"SEL$10")]',
q'[MERGE(@"SEL$11")]',
q'[MERGE(@"SEL$6")]',
q'[MERGE(@"SEL$7")]',
q'[MERGE(@"SEL$8")]',
q'[MERGE(@"SEL$9")]',
q'[OUTLINE(@"SEL$F206DE42")]',
q'[OUTER_JOIN_TO_INNER(@"SEL$1" "NAMETYPEPAIRS"@"SEL$1")]',
q'[OUTLINE(@"SEL$10")]',
q'[OUTLINE(@"SEL$11")]',
q'[OUTLINE(@"SEL$6")]',
q'[OUTLINE(@"SEL$7")]',
q'[OUTLINE(@"SEL$8")]',
q'[OUTLINE(@"SEL$9")]',
q'[OUTLINE(@"SEL$1")]',
q'[NO_ACCESS(@"SEL$57CDC764" "VW_NSO_1"@"SEL$57CDC764")]',
q'[INDEX_RS_ASC(@"SEL$57CDC764" "TXDETAILS_1"@"SEL$7" ("TXDETAILS_1"."COMPANY_ID" "TXDETAILS_1"."TX_ID" "TXDETAILS_1"."SEQUENCE"))]',
q'[INDEX_RS_ASC(@"SEL$57CDC764" "TXHEADERS_1"@"SEL$6" ("TXHEADERS_1"."COMPANY_ID" "TXHEADERS_1"."TX_ID"))]',
q'[INDEX(@"SEL$57CDC764" "PAYMENTMETHODS_1"@"SEL$11" ("PAYMENTMETHODS_1"."COMPANY_ID" "PAYMENTMETHODS_1"."PAYMENT_METHOD_ID"))]',
q'[INDEX_RS_ASC(@"SEL$57CDC764" "ACCOUNTS_1"@"SEL$8" ("ACCOUNTS_1"."COMPANY_ID" "ACCOUNTS_1"."ACCOUNT_ID"))]',
q'[INDEX_RS_ASC(@"SEL$57CDC764" "NAMETYPEPAIRS_1"@"SEL$10" ("NAMETYPEPAIRS_1"."COMPANY_ID" "NAMETYPEPAIRS_1"."NAME_ID"))]',
q'[INDEX(@"SEL$57CDC764" "NAMETYPEPAIRS_1"@"SEL$9" ("NAMETYPEPAIRS_1"."COMPANY_ID" "NAMETYPEPAIRS_1"."NAME_ID"))]',
q'[LEADING(@"SEL$57CDC764" "VW_NSO_1"@"SEL$57CDC764" "TXDETAILS_1"@"SEL$7" "TXHEADERS_1"@"SEL$6" "PAYMENTMETHODS_1"@"SEL$11" "ACCOUNTS_1"@"SEL$8" "NAMETYPEPAIRS_1"@"SEL$10" "NAMETYPEPAIRS_1"@"SEL$9")]',
q'[USE_NL(@"SEL$57CDC764" "TXDETAILS_1"@"SEL$7")]',
q'[USE_NL(@"SEL$57CDC764" "TXHEADERS_1"@"SEL$6")]',
q'[USE_NL(@"SEL$57CDC764" "PAYMENTMETHODS_1"@"SEL$11")]',
q'[USE_NL(@"SEL$57CDC764" "ACCOUNTS_1"@"SEL$8")]',
q'[USE_NL(@"SEL$57CDC764" "NAMETYPEPAIRS_1"@"SEL$10")]',
q'[USE_NL(@"SEL$57CDC764" "NAMETYPEPAIRS_1"@"SEL$9")]',
q'[NLJ_BATCHING(@"SEL$57CDC764" "NAMETYPEPAIRS_1"@"SEL$9")]',
q'[INDEX_RS_ASC(@"SEL$EEE90419" "TXHEADERS_1"@"SEL$16" "TXHEADERS_TXTYPE_LASTMODIFY")]',
q'[BATCH_TABLE_ACCESS_BY_ROWID(@"SEL$EEE90419" "TXHEADERS_1"@"SEL$16")]',
q'[INDEX(@"SEL$EEE90419" "TXDETAILS_1"@"SEL$17" ("TXDETAILS_1"."COMPANY_ID" "TXDETAILS_1"."TX_ID" "TXDETAILS_1"."SEQUENCE"))]',
q'[LEADING(@"SEL$EEE90419" "TXHEADERS_1"@"SEL$16" "TXDETAILS_1"@"SEL$17")]',
q'[USE_NL(@"SEL$EEE90419" "TXDETAILS_1"@"SEL$17")]',
q'[NLJ_BATCHING(@"SEL$EEE90419" "TXDETAILS_1"@"SEL$17")]',
q'[INDEX_RS_ASC(@"SEL$E28402CB" "TXHEADERS_1"@"SEL$13" ("TXHEADERS_1"."COMPANY_ID" "TXHEADERS_1"."TX_DATE" "TXHEADERS_1"."TX_TYPE_ID" "TXHEADERS_1"."IS_INVOICED"))]',
q'[BATCH_TABLE_ACCESS_BY_ROWID(@"SEL$E28402CB" "TXHEADERS_1"@"SEL$13")]',
q'[INDEX(@"SEL$E28402CB" "TXDETAILS_1"@"SEL$14" ("TXDETAILS_1"."COMPANY_ID" "TXDETAILS_1"."TX_ID" "TXDETAILS_1"."SEQUENCE"))]',
q'[LEADING(@"SEL$E28402CB" "TXHEADERS_1"@"SEL$13" "TXDETAILS_1"@"SEL$14")]',
q'[USE_NL(@"SEL$E28402CB" "TXDETAILS_1"@"SEL$14")]',
q'[NLJ_BATCHING(@"SEL$E28402CB" "TXDETAILS_1"@"SEL$14")]',
q'[INDEX_RS_ASC(@"SEL$7286615E" "TXDETAILS_1"@"SEL$5" ("TXDETAILS_1"."COMPANY_ID" "TXDETAILS_1"."TX_ID" "TXDETAILS_1"."SEQUENCE"))]',
q'[BATCH_TABLE_ACCESS_BY_ROWID(@"SEL$7286615E" "TXDETAILS_1"@"SEL$5")]',
q'[INDEX_RS_ASC(@"SEL$335DD26A" "TXDETAILS_1"@"SEL$3" ("TXDETAILS_1"."COMPANY_ID" "TXDETAILS_1"."TX_ID" "TXDETAILS_1"."SEQUENCE"))]',
q'[BATCH_TABLE_ACCESS_BY_ROWID(@"SEL$335DD26A" "TXDETAILS_1"@"SEL$3")]',
q'[END_OUTLINE_DATA]');
:signature := DBMS_SQLTUNE.SQLTEXT_TO_SIGNATURE(sql_txt);
DBMS_SQLTUNE.IMPORT_SQL_PROFILE (
sql_text    => sql_txt,
profile     => h,
name        => 'coe_fam5cqu99ukb6_1989083634',
description => 'coe fam5cqu99ukb6 1989083634 '||:signature||'',
category    => 'DEFAULT',
validate    => TRUE,
replace     => TRUE,
force_match => FALSE /* TRUE:FORCE (match even when different literals in SQL). FALSE:EXACT (similar to CURSOR_SHARING) */ );
END;
/
WHENEVER SQLERROR CONTINUE
SET ECHO OFF;
PRINT signature
PRO
PRO ... manual custom SQL Profile has been created
PRO
SET TERM ON ECHO OFF LIN 80 TRIMS OFF NUMF "";
SPO OFF;
PRO
PRO COE_XFR_SQL_PROFILE_fam5cqu99ukb6_1989083634 completed
