spool t_companyinfo.log
insert into kpopat.all_companyinfo select company_id, 2 from qbo_data.companyinfo_1@SPM_C2_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 3 from qbo_data.companyinfo_1@SPM_C3_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 4 from qbo_data.companyinfo_1@SPM_C4_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 5 from qbo_data.companyinfo_1@SPM_C5_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 6 from qbo_data.companyinfo_1@SPM_C6_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 7 from qbo_data.companyinfo_1@SPM_C7_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 8 from qbo_data.companyinfo_1@SPM_C8_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 9 from qbo_data.companyinfo_1@SPM_C9_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 10 from qbo_data.companyinfo_1@SPM_C10_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 19 from qbo_data.companyinfo_1@SPM_C19_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 11 from qbo_data.companyinfo_1@SPM_C11_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 12 from qbo_data.companyinfo_1@SPM_C12_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 13 from qbo_data.companyinfo_1@SPM_C13_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 14 from qbo_data.companyinfo_1@SPM_C14_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 15 from qbo_data.companyinfo_1@SPM_C15_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 16 from qbo_data.companyinfo_1@SPM_C16_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 17 from qbo_data.companyinfo_1@SPM_C17_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 18 from qbo_data.companyinfo_1@SPM_C18_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 20 from qbo_data.companyinfo_1@SPM_C20_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 21 from qbo_data.companyinfo_1@SPM_C21_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 22 from qbo_data.companyinfo_1@SPM_C22_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 23 from qbo_data.companyinfo_1@SPM_C23_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 24 from qbo_data.companyinfo_1@SPM_C24_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 25 from qbo_data.companyinfo_1@SPM_C25_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 26 from qbo_data.companyinfo_1@SPM_C26_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 27 from qbo_data.companyinfo_1@SPM_C27_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 28 from qbo_data.companyinfo_1@SPM_C28_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 29 from qbo_data.companyinfo_1@SPM_C29_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 30 from qbo_data.companyinfo_1@SPM_C30_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 31 from qbo_data.companyinfo_1@SPM_C31_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 32 from qbo_data.companyinfo_1@SPM_C32_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 33 from qbo_data.companyinfo_1@SPM_C33_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 34 from qbo_data.companyinfo_1@SPM_C34_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 35 from qbo_data.companyinfo_1@SPM_C35_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 36 from qbo_data.companyinfo_1@SPM_C36_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 37 from qbo_data.companyinfo_1@SPM_C37_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 38 from qbo_data.companyinfo_1@SPM_C38_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 39 from qbo_data.companyinfo_1@SPM_C39_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 40 from qbo_data.companyinfo_1@SPM_C40_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 41 from qbo_data.companyinfo_1@SPM_C41_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 42 from qbo_data.companyinfo_1@SPM_C42_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 43 from qbo_data.companyinfo_1@SPM_C43_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 70 from qbo_data.companyinfo_1@SPM_C70_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 71 from qbo_data.companyinfo_1@SPM_C71_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 72 from qbo_data.companyinfo_1@SPM_C72_UW2 ;
commit ;
insert into kpopat.all_companyinfo select company_id, 73 from qbo_data.companyinfo_1@SPM_C73_UW2 ;
commit ;
spool off
