---10.1 DATA MIGRATION SCRIPTS 

PROMPT BACKUP PSP_COMPANY TABLE.

CREATE TABLE BAK_PSP_COMPANY AS SELECT * FROM PSP_COMPANY;

CREATE TABLE PSPADM.TEMP_COMPANY
(
   RECORD_PK                      NUMBER PRIMARY KEY,
     BATCH_ID                       NUMBER (10, 0) NOT NULL,
   FED_TAX_ID                     VARCHAR2 (100 CHAR) NOT NULL,
   AGREE_INFO_SUB_NBR             NUMBER (22, 7) NOT NULL,
   CRIS_ACCT_ROWID                VARCHAR2 (15 CHAR),
   PHONE                          VARCHAR2 (40 CHAR),
   LEGAL_NAME                     VARCHAR2 (100 CHAR),
   PRICE_TYPE                     VARCHAR2 (50 CHAR),
   IAM_REALM_ID                   VARCHAR2 (40 CHAR),
   QB_INFO_APP_VERSION            VARCHAR2 (100 CHAR),
   QB_INFO_APPLICATION_ID         VARCHAR2 (100 CHAR),
   QB_INFO_LICENSE_NUMBER         VARCHAR2 (100 CHAR),
   AGREE_INFO_AGREE_CREATE_DATE   TIMESTAMP (6),
   AGREE_INFO_NAME                VARCHAR2 (100 CHAR),
   AGREE_INFO_SERVICE_TYPE        VARCHAR2 (100 CHAR),
   AGREE_INFO_SOURCE_ID           VARCHAR2 (100 CHAR),
   AGREE_INFO_SERVICE_KEY         VARCHAR2 (100 CHAR),
   AGREE_INFO_AGREE_SUB_TYPE      VARCHAR2 (100 CHAR),
   COMP_ADDRESS_LINE2             VARCHAR2 (800 CHAR),
   COMP_ADDRESS_LINE1             VARCHAR2 (800 CHAR),
   COMP_CITY                      VARCHAR2 (200 CHAR),
   COMP_COUNTRY                   VARCHAR2 (120 CHAR),
   COMP_STATE                     VARCHAR2 (40 CHAR),
   COMP_ZIP_CODE                  VARCHAR2 (120 CHAR),
   COMP_NOTIFICATION_EMAIL        VARCHAR2 (100 CHAR),
   CONTACT_TITLE                  VARCHAR2 (100 CHAR),
   CONTACT_JOB_TITLE              VARCHAR2 (100 CHAR),
   CONTACT_FAX                    VARCHAR2 (40 CHAR),
   CONTACT_SECOND_PHONE           VARCHAR2 (40 CHAR),
   CONTACT_IAM_AUTH_ID            VARCHAR2 (40 CHAR),
   CONTACT_FIRST_NAME             VARCHAR2 (50 CHAR),
   CONTACT_LAST_NAME              VARCHAR2 (50 CHAR),
   CONTACT_MIDDLE_NAME            VARCHAR2 (50 CHAR),
   CONTACT_GENDER_CD              VARCHAR2 (50 CHAR),
   CONTACT_EMAIL                  VARCHAR2 (100 CHAR),
   CONTACT_PHONE                  VARCHAR2 (40 CHAR),
   CONTACT_ADDRESS_LINE2          VARCHAR2 (800 CHAR),
   CONTACT_ADDRESS_LINE1          VARCHAR2 (800 CHAR),
   CONTACT_CITY                   VARCHAR2 (200 CHAR),
   CONTACT_COUNTRY                VARCHAR2 (120 CHAR),
   CONTACT_STATE                  VARCHAR2 (40 CHAR),
   CONTACT_ZIP_CODE               VARCHAR2 (120 CHAR),
   MIGRATION_STATUS               VARCHAR2 (100 CHAR) DEFAULT 'NotMigrated',
   MIGRATION_STATUS_DTTM          TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
   ERROR_MESSAGE                  VARCHAR2 (1000 CHAR),
    CREATED_DTTM                   TIMESTAMP (6) DEFAULT SYSTIMESTAMP
);


CREATE SEQUENCE PSPADM.SEQ_TEMP_COMPANY INCREMENT BY 1 MINVALUE 1 NOMAXVALUE NOCYCLE NOCACHE NOORDER;

CREATE OR REPLACE TRIGGER PSPADM.TR_INS_TEMP_COMPANY
   BEFORE INSERT ON PSPADM.TEMP_COMPANY FOR EACH ROW
BEGIN
   SELECT PSPADM.SEQ_TEMP_COMPANY.NEXTVAL INTO :NEW.RECORD_PK FROM DUAL;
END;
/

PROMPT ENABLE ERROR LOGGING FOR TEMP_COMPANY
EXEC dbms_errlog.create_error_log('TEMP_COMPANY');
