   CREATE USER "PSPADM" IDENTIFIED BY "Fv8Yz#1yi"
      DEFAULT TABLESPACE "PSP_DATA01"
      TEMPORARY TABLESPACE "TEMP"
      PROFILE "APPLICATION_HIGH_RISK_PROFILE";
 ALTER USER "PSPADM" LOCAL TEMPORARY TABLESPACE "SYSTEM";


   GRANT "CONNECT" TO "PSPADM";
   GRANT "RESOURCE" TO "PSPADM";
   GRANT "PSPAPP_ROLE" TO "PSPADM" WITH ADMIN OPTION;
   GRANT "PSPREAD_ROLE" TO "PSPADM" WITH ADMIN OPTION;


  GRANT CREATE ANY OUTLINE TO "PSPADM";
  GRANT CREATE ANY CONTEXT TO "PSPADM";
  GRANT CREATE ROLE TO "PSPADM";
  GRANT CREATE DATABASE LINK TO "PSPADM";
  GRANT DROP ANY SYNONYM TO "PSPADM";
  GRANT CREATE ANY SYNONYM TO "PSPADM";
  GRANT UNLIMITED TABLESPACE TO "PSPADM";


  GRANT SELECT ON "SYS"."DBA_USERS" TO "PSPADM";
  GRANT EXECUTE ON "SYS"."DBMS_LOCK" TO "PSPADM";
  GRANT SELECT ON "PSPLOG"."PSE_EVENT_LOG" TO "PSPADM";
  GRANT EXECUTE ON "PSPLOG"."PK_LOGGING_MONITORING" TO "PSPADM";
  GRANT SELECT ON "APPBUGFIX"."TEMP_SRC_EMP_ID_8_13" TO "PSPADM";
  GRANT SELECT ON "APPBUGFIX"."TEMP_TOR_2_28" TO "PSPADM";
  GRANT SELECT ON "APPBUGFIX"."TEMP_SRC_EMP_ID" TO "PSPADM";
  GRANT EXECUTE ON "APPBUGFIX"."FN_GMT_LOCAL_MIDNIGHT" TO "PSPADM";


   ALTER USER "PSPADM" DEFAULT ROLE ALL;

