spool create_tablespaces
set echo on
set feed on
set time on
set timi on

CREATE TABLESPACE PSP_DATA02 DATAFILE SIZE 100G AUTOEXTEND ON NEXT 10G MAXSIZE UNLIMITED;
ALTER TABLESPACE PSP_DATA02  RESIZE 2T;

CREATE TABLESPACE PSP_IDX02 DATAFILE SIZE 100G AUTOEXTEND ON NEXT 10G MAXSIZE UNLIMITED;
ALTER TABLESPACE PSP_IDX02 RESIZE 2T;

spool off
exit
