# $Id: Makefile,v 1.1 2007/05/05 00:20:47 jspencer Exp $
#
include $(QBNBASE)/build/rules/base.mak
include $(QBNBASE)/build/rules/salsa.mak

all:: $(DIRS) pre

pre::

JAVA_PACKAGE = com/intuit/payroll/agency/dao/mnemonics

JAVA_SRC = \
		AbstractMnemonicExpression.java \
		DueDateMnemonicExpression.java \
		DueDatePolicy.java \
		EndDateMnemonicExpression.java \
		InvalidMnemonicException.java \
		MnemonicContext.java \
		MnemonicData.java \
		MnemonicInterpreter.java \
		MnemonicInterpreterRequest.java \
		MnemonicInterpreterResponse.java \
		MnemonicPeriod.java \
		StartDateMnemonicExpression.java

include $(QBNBASE)/build/rules/java.mak






