//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.14 at 10:29:12 AM PDT 
//


package com.intuit.ias.common.xsd;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.intuit.ias.common.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Error_QNAME = new QName("http://www.intuit.com/ias/common/xsd", "Error");
    private final static QName _Header_QNAME = new QName("http://www.intuit.com/ias/common/xsd", "Header");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.intuit.ias.common.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HeaderDataType }
     * 
     */
    public HeaderDataType createHeaderDataType() {
        return new HeaderDataType();
    }

    /**
     * Create an instance of {@link ErrorDataType }
     * 
     */
    public ErrorDataType createErrorDataType() {
        return new ErrorDataType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ErrorDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.intuit.com/ias/common/xsd", name = "Error")
    public JAXBElement<ErrorDataType> createError(ErrorDataType value) {
        return new JAXBElement<ErrorDataType>(_Error_QNAME, ErrorDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HeaderDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.intuit.com/ias/common/xsd", name = "Header")
    public JAXBElement<HeaderDataType> createHeader(HeaderDataType value) {
        return new JAXBElement<HeaderDataType>(_Header_QNAME, HeaderDataType.class, null, value);
    }

}
