\timing
set search_path=pspadm;
SELECT CURRENT_TIMESTAMP;
select 'creating index on psp_paycheck' as status;
create index psp_paycheck_fk1_p0 on pspadm.psp_paycheck_p0 USING BTREE (d_d_employee_fk ASC);
create index psp_paycheck_fk1_p1 on pspadm.psp_paycheck_p1 USING BTREE (d_d_employee_fk ASC);
create index psp_paycheck_fk1_p10 on pspadm.psp_paycheck_p10 USING BTREE (d_d_employee_fk ASC);
create index psp_paycheck_fk1_p11 on pspadm.psp_paycheck_p11 USING BTREE (d_d_employee_fk ASC);
create index psp_paycheck_fk1_p12 on pspadm.psp_paycheck_p12 USING BTREE (d_d_employee_fk ASC);
create index psp_paycheck_fk1_p13 on pspadm.psp_paycheck_p13 USING BTREE (d_d_employee_fk ASC);
create index psp_paycheck_fk1_p14 on pspadm.psp_paycheck_p14 USING BTREE (d_d_employee_fk ASC);
create index psp_paycheck_fk1_p15 on pspadm.psp_paycheck_p15 USING BTREE (d_d_employee_fk ASC);
create index psp_paycheck_fk1_p2 on pspadm.psp_paycheck_p2 USING BTREE (d_d_employee_fk ASC);
create index psp_paycheck_fk1_p3 on pspadm.psp_paycheck_p3 USING BTREE (d_d_employee_fk ASC);
create index psp_paycheck_fk1_p4 on pspadm.psp_paycheck_p4 USING BTREE (d_d_employee_fk ASC);
create index psp_paycheck_fk1_p5 on pspadm.psp_paycheck_p5 USING BTREE (d_d_employee_fk ASC);
create index psp_paycheck_fk1_p6 on pspadm.psp_paycheck_p6 USING BTREE (d_d_employee_fk ASC);
create index psp_paycheck_fk1_p7 on pspadm.psp_paycheck_p7 USING BTREE (d_d_employee_fk ASC);
create index psp_paycheck_fk1_p8 on pspadm.psp_paycheck_p8 USING BTREE (d_d_employee_fk ASC);
create index psp_paycheck_fk1_p9 on pspadm.psp_paycheck_p9 USING BTREE (d_d_employee_fk ASC);
create index psp_paycheck_fk2_p0 on pspadm.psp_paycheck_p0 USING BTREE (payroll_run_fk ASC);
create index psp_paycheck_fk2_p1 on pspadm.psp_paycheck_p1 USING BTREE (payroll_run_fk ASC);
create index psp_paycheck_fk2_p10 on pspadm.psp_paycheck_p10 USING BTREE (payroll_run_fk ASC);
create index psp_paycheck_fk2_p11 on pspadm.psp_paycheck_p11 USING BTREE (payroll_run_fk ASC);
create index psp_paycheck_fk2_p12 on pspadm.psp_paycheck_p12 USING BTREE (payroll_run_fk ASC);
create index psp_paycheck_fk2_p13 on pspadm.psp_paycheck_p13 USING BTREE (payroll_run_fk ASC);
create index psp_paycheck_fk2_p14 on pspadm.psp_paycheck_p14 USING BTREE (payroll_run_fk ASC);
create index psp_paycheck_fk2_p15 on pspadm.psp_paycheck_p15 USING BTREE (payroll_run_fk ASC);
create index psp_paycheck_fk2_p2 on pspadm.psp_paycheck_p2 USING BTREE (payroll_run_fk ASC);
create index psp_paycheck_fk2_p3 on pspadm.psp_paycheck_p3 USING BTREE (payroll_run_fk ASC);
create index psp_paycheck_fk2_p4 on pspadm.psp_paycheck_p4 USING BTREE (payroll_run_fk ASC);
create index psp_paycheck_fk2_p5 on pspadm.psp_paycheck_p5 USING BTREE (payroll_run_fk ASC);
create index psp_paycheck_fk2_p6 on pspadm.psp_paycheck_p6 USING BTREE (payroll_run_fk ASC);
create index psp_paycheck_fk2_p7 on pspadm.psp_paycheck_p7 USING BTREE (payroll_run_fk ASC);
create index psp_paycheck_fk2_p8 on pspadm.psp_paycheck_p8 USING BTREE (payroll_run_fk ASC);
create index psp_paycheck_fk2_p9 on pspadm.psp_paycheck_p9 USING BTREE (payroll_run_fk ASC);
create index psp_paycheck_fk3_p0 on pspadm.psp_paycheck_p0 USING BTREE (comp_adjust_submission_fk ASC);
create index psp_paycheck_fk3_p1 on pspadm.psp_paycheck_p1 USING BTREE (comp_adjust_submission_fk ASC);
create index psp_paycheck_fk3_p10 on pspadm.psp_paycheck_p10 USING BTREE (comp_adjust_submission_fk ASC);
create index psp_paycheck_fk3_p11 on pspadm.psp_paycheck_p11 USING BTREE (comp_adjust_submission_fk ASC);
create index psp_paycheck_fk3_p12 on pspadm.psp_paycheck_p12 USING BTREE (comp_adjust_submission_fk ASC);
create index psp_paycheck_fk3_p13 on pspadm.psp_paycheck_p13 USING BTREE (comp_adjust_submission_fk ASC);
create index psp_paycheck_fk3_p14 on pspadm.psp_paycheck_p14 USING BTREE (comp_adjust_submission_fk ASC);
create index psp_paycheck_fk3_p15 on pspadm.psp_paycheck_p15 USING BTREE (comp_adjust_submission_fk ASC);
create index psp_paycheck_fk3_p2 on pspadm.psp_paycheck_p2 USING BTREE (comp_adjust_submission_fk ASC);
create index psp_paycheck_fk3_p3 on pspadm.psp_paycheck_p3 USING BTREE (comp_adjust_submission_fk ASC);
create index psp_paycheck_fk3_p4 on pspadm.psp_paycheck_p4 USING BTREE (comp_adjust_submission_fk ASC);
create index psp_paycheck_fk3_p5 on pspadm.psp_paycheck_p5 USING BTREE (comp_adjust_submission_fk ASC);
create index psp_paycheck_fk3_p6 on pspadm.psp_paycheck_p6 USING BTREE (comp_adjust_submission_fk ASC);
create index psp_paycheck_fk3_p7 on pspadm.psp_paycheck_p7 USING BTREE (comp_adjust_submission_fk ASC);
create index psp_paycheck_fk3_p8 on pspadm.psp_paycheck_p8 USING BTREE (comp_adjust_submission_fk ASC);
create index psp_paycheck_fk3_p9 on pspadm.psp_paycheck_p9 USING BTREE (comp_adjust_submission_fk ASC);
create index psp_paycheck_fk4_p0 on pspadm.psp_paycheck_p0 USING BTREE (source_employee_fk ASC);
create index psp_paycheck_fk4_p1 on pspadm.psp_paycheck_p1 USING BTREE (source_employee_fk ASC);
create index psp_paycheck_fk4_p10 on pspadm.psp_paycheck_p10 USING BTREE (source_employee_fk ASC);
create index psp_paycheck_fk4_p11 on pspadm.psp_paycheck_p11 USING BTREE (source_employee_fk ASC);
create index psp_paycheck_fk4_p12 on pspadm.psp_paycheck_p12 USING BTREE (source_employee_fk ASC);
create index psp_paycheck_fk4_p13 on pspadm.psp_paycheck_p13 USING BTREE (source_employee_fk ASC);
create index psp_paycheck_fk4_p14 on pspadm.psp_paycheck_p14 USING BTREE (source_employee_fk ASC);
create index psp_paycheck_fk4_p15 on pspadm.psp_paycheck_p15 USING BTREE (source_employee_fk ASC);
create index psp_paycheck_fk4_p2 on pspadm.psp_paycheck_p2 USING BTREE (source_employee_fk ASC);
create index psp_paycheck_fk4_p3 on pspadm.psp_paycheck_p3 USING BTREE (source_employee_fk ASC);
create index psp_paycheck_fk4_p4 on pspadm.psp_paycheck_p4 USING BTREE (source_employee_fk ASC);
create index psp_paycheck_fk4_p5 on pspadm.psp_paycheck_p5 USING BTREE (source_employee_fk ASC);
create index psp_paycheck_fk4_p6 on pspadm.psp_paycheck_p6 USING BTREE (source_employee_fk ASC);
create index psp_paycheck_fk4_p7 on pspadm.psp_paycheck_p7 USING BTREE (source_employee_fk ASC);
create index psp_paycheck_fk4_p8 on pspadm.psp_paycheck_p8 USING BTREE (source_employee_fk ASC);
create index psp_paycheck_fk4_p9 on pspadm.psp_paycheck_p9 USING BTREE (source_employee_fk ASC);
create index psp_paycheck_i1_p0 on pspadm.psp_paycheck_p0 USING BTREE (created_date ASC);
create index psp_paycheck_i1_p1 on pspadm.psp_paycheck_p1 USING BTREE (created_date ASC);
create index psp_paycheck_i1_p10 on pspadm.psp_paycheck_p10 USING BTREE (created_date ASC);
create index psp_paycheck_i1_p11 on pspadm.psp_paycheck_p11 USING BTREE (created_date ASC);
create index psp_paycheck_i1_p12 on pspadm.psp_paycheck_p12 USING BTREE (created_date ASC);
create index psp_paycheck_i1_p13 on pspadm.psp_paycheck_p13 USING BTREE (created_date ASC);
create index psp_paycheck_i1_p14 on pspadm.psp_paycheck_p14 USING BTREE (created_date ASC);
create index psp_paycheck_i1_p15 on pspadm.psp_paycheck_p15 USING BTREE (created_date ASC);
create index psp_paycheck_i1_p2 on pspadm.psp_paycheck_p2 USING BTREE (created_date ASC);
create index psp_paycheck_i1_p3 on pspadm.psp_paycheck_p3 USING BTREE (created_date ASC);
create index psp_paycheck_i1_p4 on pspadm.psp_paycheck_p4 USING BTREE (created_date ASC);
create index psp_paycheck_i1_p5 on pspadm.psp_paycheck_p5 USING BTREE (created_date ASC);
create index psp_paycheck_i1_p6 on pspadm.psp_paycheck_p6 USING BTREE (created_date ASC);
create index psp_paycheck_i1_p7 on pspadm.psp_paycheck_p7 USING BTREE (created_date ASC);
create index psp_paycheck_i1_p8 on pspadm.psp_paycheck_p8 USING BTREE (created_date ASC);
create index psp_paycheck_i1_p9 on pspadm.psp_paycheck_p9 USING BTREE (created_date ASC);
create index psp_paycheck_i2_p0 on pspadm.psp_paycheck_p0 USING BTREE (company_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_i2_p1 on pspadm.psp_paycheck_p1 USING BTREE (company_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_i2_p10 on pspadm.psp_paycheck_p10 USING BTREE (company_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_i2_p11 on pspadm.psp_paycheck_p11 USING BTREE (company_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_i2_p12 on pspadm.psp_paycheck_p12 USING BTREE (company_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_i2_p13 on pspadm.psp_paycheck_p13 USING BTREE (company_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_i2_p14 on pspadm.psp_paycheck_p14 USING BTREE (company_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_i2_p15 on pspadm.psp_paycheck_p15 USING BTREE (company_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_i2_p2 on pspadm.psp_paycheck_p2 USING BTREE (company_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_i2_p3 on pspadm.psp_paycheck_p3 USING BTREE (company_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_i2_p4 on pspadm.psp_paycheck_p4 USING BTREE (company_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_i2_p5 on pspadm.psp_paycheck_p5 USING BTREE (company_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_i2_p6 on pspadm.psp_paycheck_p6 USING BTREE (company_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_i2_p7 on pspadm.psp_paycheck_p7 USING BTREE (company_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_i2_p8 on pspadm.psp_paycheck_p8 USING BTREE (company_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_i2_p9 on pspadm.psp_paycheck_p9 USING BTREE (company_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_u1_p0 on pspadm.psp_paycheck_p0 USING BTREE (source_paycheck_id ASC,payroll_run_fk ASC);
create index psp_paycheck_u1_p1 on pspadm.psp_paycheck_p1 USING BTREE (source_paycheck_id ASC,payroll_run_fk ASC);
create index psp_paycheck_u1_p10 on pspadm.psp_paycheck_p10 USING BTREE (source_paycheck_id ASC,payroll_run_fk ASC);
create index psp_paycheck_u1_p11 on pspadm.psp_paycheck_p11 USING BTREE (source_paycheck_id ASC,payroll_run_fk ASC);
create index psp_paycheck_u1_p12 on pspadm.psp_paycheck_p12 USING BTREE (source_paycheck_id ASC,payroll_run_fk ASC);
create index psp_paycheck_u1_p13 on pspadm.psp_paycheck_p13 USING BTREE (source_paycheck_id ASC,payroll_run_fk ASC);
create index psp_paycheck_u1_p14 on pspadm.psp_paycheck_p14 USING BTREE (source_paycheck_id ASC,payroll_run_fk ASC);
create index psp_paycheck_u1_p15 on pspadm.psp_paycheck_p15 USING BTREE (source_paycheck_id ASC,payroll_run_fk ASC);
create index psp_paycheck_u1_p2 on pspadm.psp_paycheck_p2 USING BTREE (source_paycheck_id ASC,payroll_run_fk ASC);
create index psp_paycheck_u1_p3 on pspadm.psp_paycheck_p3 USING BTREE (source_paycheck_id ASC,payroll_run_fk ASC);
create index psp_paycheck_u1_p4 on pspadm.psp_paycheck_p4 USING BTREE (source_paycheck_id ASC,payroll_run_fk ASC);
create index psp_paycheck_u1_p5 on pspadm.psp_paycheck_p5 USING BTREE (source_paycheck_id ASC,payroll_run_fk ASC);
create index psp_paycheck_u1_p6 on pspadm.psp_paycheck_p6 USING BTREE (source_paycheck_id ASC,payroll_run_fk ASC);
create index psp_paycheck_u1_p7 on pspadm.psp_paycheck_p7 USING BTREE (source_paycheck_id ASC,payroll_run_fk ASC);
create index psp_paycheck_u1_p8 on pspadm.psp_paycheck_p8 USING BTREE (source_paycheck_id ASC,payroll_run_fk ASC);
create index psp_paycheck_u1_p9 on pspadm.psp_paycheck_p9 USING BTREE (source_paycheck_id ASC,payroll_run_fk ASC);
select  'psp_paycheck completed' as status;
SELECT CURRENT_TIMESTAMP;

select 'creating index on psp_paycheck_split' as status;
create index psp_paycheck_split_fk1_p0 on pspadm.psp_paycheck_split_p0 USING BTREE (employee_bank_account_fk ASC);
create index psp_paycheck_split_fk1_p1 on pspadm.psp_paycheck_split_p1 USING BTREE (employee_bank_account_fk ASC);
create index psp_paycheck_split_fk1_p10 on pspadm.psp_paycheck_split_p10 USING BTREE (employee_bank_account_fk ASC);
create index psp_paycheck_split_fk1_p11 on pspadm.psp_paycheck_split_p11 USING BTREE (employee_bank_account_fk ASC);
create index psp_paycheck_split_fk1_p12 on pspadm.psp_paycheck_split_p12 USING BTREE (employee_bank_account_fk ASC);
create index psp_paycheck_split_fk1_p13 on pspadm.psp_paycheck_split_p13 USING BTREE (employee_bank_account_fk ASC);
create index psp_paycheck_split_fk1_p14 on pspadm.psp_paycheck_split_p14 USING BTREE (employee_bank_account_fk ASC);
create index psp_paycheck_split_fk1_p15 on pspadm.psp_paycheck_split_p15 USING BTREE (employee_bank_account_fk ASC);
create index psp_paycheck_split_fk1_p2 on pspadm.psp_paycheck_split_p2 USING BTREE (employee_bank_account_fk ASC);
create index psp_paycheck_split_fk1_p3 on pspadm.psp_paycheck_split_p3 USING BTREE (employee_bank_account_fk ASC);
create index psp_paycheck_split_fk1_p4 on pspadm.psp_paycheck_split_p4 USING BTREE (employee_bank_account_fk ASC);
create index psp_paycheck_split_fk1_p5 on pspadm.psp_paycheck_split_p5 USING BTREE (employee_bank_account_fk ASC);
create index psp_paycheck_split_fk1_p6 on pspadm.psp_paycheck_split_p6 USING BTREE (employee_bank_account_fk ASC);
create index psp_paycheck_split_fk1_p7 on pspadm.psp_paycheck_split_p7 USING BTREE (employee_bank_account_fk ASC);
create index psp_paycheck_split_fk1_p8 on pspadm.psp_paycheck_split_p8 USING BTREE (employee_bank_account_fk ASC);
create index psp_paycheck_split_fk1_p9 on pspadm.psp_paycheck_split_p9 USING BTREE (employee_bank_account_fk ASC);
create index psp_paycheck_split_fk2_p0 on pspadm.psp_paycheck_split_p0 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_paycheck_split_fk2_p1 on pspadm.psp_paycheck_split_p1 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_paycheck_split_fk2_p10 on pspadm.psp_paycheck_split_p10 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_paycheck_split_fk2_p11 on pspadm.psp_paycheck_split_p11 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_paycheck_split_fk2_p12 on pspadm.psp_paycheck_split_p12 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_paycheck_split_fk2_p13 on pspadm.psp_paycheck_split_p13 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_paycheck_split_fk2_p14 on pspadm.psp_paycheck_split_p14 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_paycheck_split_fk2_p15 on pspadm.psp_paycheck_split_p15 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_paycheck_split_fk2_p2 on pspadm.psp_paycheck_split_p2 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_paycheck_split_fk2_p3 on pspadm.psp_paycheck_split_p3 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_paycheck_split_fk2_p4 on pspadm.psp_paycheck_split_p4 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_paycheck_split_fk2_p5 on pspadm.psp_paycheck_split_p5 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_paycheck_split_fk2_p6 on pspadm.psp_paycheck_split_p6 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_paycheck_split_fk2_p7 on pspadm.psp_paycheck_split_p7 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_paycheck_split_fk2_p8 on pspadm.psp_paycheck_split_p8 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_paycheck_split_fk2_p9 on pspadm.psp_paycheck_split_p9 USING BTREE (company_fk ASC,paycheck_fk ASC);
create index psp_paycheck_split_fk3_p0 on pspadm.psp_paycheck_split_p0 USING BTREE (company_fk ASC);
create index psp_paycheck_split_fk3_p1 on pspadm.psp_paycheck_split_p1 USING BTREE (company_fk ASC);
create index psp_paycheck_split_fk3_p10 on pspadm.psp_paycheck_split_p10 USING BTREE (company_fk ASC);
create index psp_paycheck_split_fk3_p11 on pspadm.psp_paycheck_split_p11 USING BTREE (company_fk ASC);
create index psp_paycheck_split_fk3_p12 on pspadm.psp_paycheck_split_p12 USING BTREE (company_fk ASC);
create index psp_paycheck_split_fk3_p13 on pspadm.psp_paycheck_split_p13 USING BTREE (company_fk ASC);
create index psp_paycheck_split_fk3_p14 on pspadm.psp_paycheck_split_p14 USING BTREE (company_fk ASC);
create index psp_paycheck_split_fk3_p15 on pspadm.psp_paycheck_split_p15 USING BTREE (company_fk ASC);
create index psp_paycheck_split_fk3_p2 on pspadm.psp_paycheck_split_p2 USING BTREE (company_fk ASC);
create index psp_paycheck_split_fk3_p3 on pspadm.psp_paycheck_split_p3 USING BTREE (company_fk ASC);
create index psp_paycheck_split_fk3_p4 on pspadm.psp_paycheck_split_p4 USING BTREE (company_fk ASC);
create index psp_paycheck_split_fk3_p5 on pspadm.psp_paycheck_split_p5 USING BTREE (company_fk ASC);
create index psp_paycheck_split_fk3_p6 on pspadm.psp_paycheck_split_p6 USING BTREE (company_fk ASC);
create index psp_paycheck_split_fk3_p7 on pspadm.psp_paycheck_split_p7 USING BTREE (company_fk ASC);
create index psp_paycheck_split_fk3_p8 on pspadm.psp_paycheck_split_p8 USING BTREE (company_fk ASC);
create index psp_paycheck_split_fk3_p9 on pspadm.psp_paycheck_split_p9 USING BTREE (company_fk ASC);
create index psp_paycheck_split_u1_p0 on pspadm.psp_paycheck_split_p0 USING BTREE (source_dd_txn_id ASC,paycheck_fk ASC);
create index psp_paycheck_split_u1_p1 on pspadm.psp_paycheck_split_p1 USING BTREE (source_dd_txn_id ASC,paycheck_fk ASC);
create index psp_paycheck_split_u1_p10 on pspadm.psp_paycheck_split_p10 USING BTREE (source_dd_txn_id ASC,paycheck_fk ASC);
create index psp_paycheck_split_u1_p11 on pspadm.psp_paycheck_split_p11 USING BTREE (source_dd_txn_id ASC,paycheck_fk ASC);
create index psp_paycheck_split_u1_p12 on pspadm.psp_paycheck_split_p12 USING BTREE (source_dd_txn_id ASC,paycheck_fk ASC);
create index psp_paycheck_split_u1_p13 on pspadm.psp_paycheck_split_p13 USING BTREE (source_dd_txn_id ASC,paycheck_fk ASC);
create index psp_paycheck_split_u1_p14 on pspadm.psp_paycheck_split_p14 USING BTREE (source_dd_txn_id ASC,paycheck_fk ASC);
create index psp_paycheck_split_u1_p15 on pspadm.psp_paycheck_split_p15 USING BTREE (source_dd_txn_id ASC,paycheck_fk ASC);
create index psp_paycheck_split_u1_p2 on pspadm.psp_paycheck_split_p2 USING BTREE (source_dd_txn_id ASC,paycheck_fk ASC);
create index psp_paycheck_split_u1_p3 on pspadm.psp_paycheck_split_p3 USING BTREE (source_dd_txn_id ASC,paycheck_fk ASC);
create index psp_paycheck_split_u1_p4 on pspadm.psp_paycheck_split_p4 USING BTREE (source_dd_txn_id ASC,paycheck_fk ASC);
create index psp_paycheck_split_u1_p5 on pspadm.psp_paycheck_split_p5 USING BTREE (source_dd_txn_id ASC,paycheck_fk ASC);
create index psp_paycheck_split_u1_p6 on pspadm.psp_paycheck_split_p6 USING BTREE (source_dd_txn_id ASC,paycheck_fk ASC);
create index psp_paycheck_split_u1_p7 on pspadm.psp_paycheck_split_p7 USING BTREE (source_dd_txn_id ASC,paycheck_fk ASC);
create index psp_paycheck_split_u1_p8 on pspadm.psp_paycheck_split_p8 USING BTREE (source_dd_txn_id ASC,paycheck_fk ASC);
create index psp_paycheck_split_u1_p9 on pspadm.psp_paycheck_split_p9 USING BTREE (source_dd_txn_id ASC,paycheck_fk ASC);
select  'psp_paycheck_split completed' as status;
SELECT CURRENT_TIMESTAMP;

