\copy (select 'delete from pspadm.' || table_name || ' where (' ||split_part(pk_cols, ',', 1) || ') in (''' || pk_seq || ''') and (' || split_part(pk_cols, ',', 2) ||') in (''' || company_fk || ''');' from backup_oos.oos_metadata where table_name = 'psp_company_event' and op_type = 'update' and status!='inflight') to 'fix_del_for_update_oos_o2p_psp_company_event.sql';
\copy (select 'delete from pspadm.' || table_name || ' where (' ||split_part(pk_cols, ',', 1) || ') in (''' || pk_seq || ''') and (' || split_part(pk_cols, ',', 2) ||') in (''' || company_fk || ''');' from backup_oos.oos_metadata where table_name = 'psp_financial_transaction' and op_type = 'update' and status!='inflight') to 'fix_del_for_update_oos_o2p_psp_financial_transaction.sql';
\copy (select 'delete from pspadm.' || table_name || ' where (' ||split_part(pk_cols, ',', 1) || ') in (''' || pk_seq || ''') and (' || split_part(pk_cols, ',', 2) ||') in (''' || company_fk || ''');' from backup_oos.oos_metadata where table_name = 'psp_money_movement_transaction' and op_type = 'update' and status!='inflight') to 'fix_del_for_update_oos_o2p_psp_money_movement_transaction.sql';
\copy (select 'delete from pspadm.' || table_name || ' where (' ||split_part(pk_cols, ',', 1) || ') in (''' || pk_seq || ''') and (' || split_part(pk_cols, ',', 2) ||') in (''' || company_fk || ''');' from backup_oos.oos_metadata where table_name = 'psp_paycheck' and op_type = 'update' and status!='inflight') to 'fix_del_for_update_oos_o2p_psp_paycheck.sql';
\copy (select 'delete from pspadm.' || table_name || ' where (' ||split_part(pk_cols, ',', 1) || ') in (''' || pk_seq || ''') and (' || split_part(pk_cols, ',', 2) ||') in (''' || company_fk || ''');' from backup_oos.oos_metadata where table_name = 'psp_paystub' and op_type = 'update' and status!='inflight') to 'fix_del_for_update_oos_o2p_psp_paystub.sql';
\copy (select 'delete from pspadm.' || table_name || ' where (' ||split_part(pk_cols, ',', 1) || ') in (''' || pk_seq || ''') and (' || split_part(pk_cols, ',', 2) ||') in (''' || company_fk || ''');' from backup_oos.oos_metadata where table_name = 'psp_pstub_employee_info' and op_type = 'update' and status!='inflight') to 'fix_del_for_update_oos_o2p_psp_pstub_employee_info.sql';
\copy (select 'delete from pspadm.' || table_name || ' where (' ||split_part(pk_cols, ',', 1) || ') in (''' || pk_seq || ''') and (' || split_part(pk_cols, ',', 2) ||') in (''' || company_fk || ''');' from backup_oos.oos_metadata where table_name = 'psp_qbdt_paycheck_info' and op_type = 'update' and status!='inflight') to 'fix_del_for_update_oos_o2p_psp_qbdt_paycheck_info.sql';
\copy (select 'delete from pspadm.' || table_name || ' where (' ||split_part(pk_cols, ',', 1) || ') in (''' || pk_seq || ''') and (' || split_part(pk_cols, ',', 2) ||') in (''' || company_fk || ''');' from backup_oos.oos_metadata where table_name = 'psp_qbdt_payline_info' and op_type = 'update' and status!='inflight') to 'fix_del_for_update_oos_o2p_psp_qbdt_payline_info.sql';
\copy (select 'delete from pspadm.' || table_name || ' where (' ||split_part(pk_cols, ',', 1) || ') in (''' || pk_seq || ''') and (' || split_part(pk_cols, ',', 2) ||') in (''' || company_fk || ''');' from backup_oos.oos_metadata where table_name = 'psp_qbdt_transaction_info' and op_type = 'update' and status!='inflight') to 'fix_del_for_update_oos_o2p_psp_qbdt_transaction_info.sql';

\copy (select 'insert into pspadm.' || table_name || ' select * from imp_psphpp02_pspadm.' || table_name || ' where (' ||split_part(pk_cols, ',', 1)|| ') in ('''||pk_seq||''') and ('||split_part(pk_cols, ',', 2)||') in ('''||company_fk||''');' from backup_oos.oos_metadata where table_name ='psp_company_event' and op_type='update' and status!='inflight') to 'fix_ins_for_update_oos_o2p_psp_company_event.sql';
\copy (select 'insert into pspadm.' || table_name || ' select * from imp_psphpp02_pspadm.' || table_name || ' where (' ||split_part(pk_cols, ',', 1)|| ') in ('''||pk_seq||''') and ('||split_part(pk_cols, ',', 2)||') in ('''||company_fk||''');' from backup_oos.oos_metadata where table_name ='psp_financial_transaction' and op_type='update' and status!='inflight') to 'fix_ins_for_update_oos_o2p_psp_financial_transaction.sql';
\copy (select 'insert into pspadm.' || table_name || ' select * from imp_psphpp02_pspadm.' || table_name || ' where (' ||split_part(pk_cols, ',', 1)|| ') in ('''||pk_seq||''') and ('||split_part(pk_cols, ',', 2)||') in ('''||company_fk||''');' from backup_oos.oos_metadata where table_name ='psp_money_movement_transaction' and op_type='update' and status!='inflight') to 'fix_ins_for_update_oos_o2p_psp_money_movement_transaction.sql';
\copy (select 'insert into pspadm.' || table_name || ' select * from imp_psphpp02_pspadm.' || table_name || ' where (' ||split_part(pk_cols, ',', 1)|| ') in ('''||pk_seq||''') and ('||split_part(pk_cols, ',', 2)||') in ('''||company_fk||''');' from backup_oos.oos_metadata where table_name ='psp_paycheck' and op_type='update' and status!='inflight') to 'fix_ins_for_update_oos_o2p_psp_paycheck.sql';
\copy (select 'insert into pspadm.' || table_name || ' select * from imp_psphpp02_pspadm.' || table_name || ' where (' ||split_part(pk_cols, ',', 1)|| ') in ('''||pk_seq||''') and ('||split_part(pk_cols, ',', 2)||') in ('''||company_fk||''');' from backup_oos.oos_metadata where table_name ='psp_paystub' and op_type='update' and status!='inflight') to 'fix_ins_for_update_oos_o2p_psp_paystub.sql';
\copy (select 'insert into pspadm.' || table_name || ' select * from imp_psphpp02_pspadm.' || table_name || ' where (' ||split_part(pk_cols, ',', 1)|| ') in ('''||pk_seq||''') and ('||split_part(pk_cols, ',', 2)||') in ('''||company_fk||''');' from backup_oos.oos_metadata where table_name ='psp_pstub_employee_info' and op_type='update' and status!='inflight') to 'fix_ins_for_update_oos_o2p_psp_pstub_employee_info.sql';
\copy (select 'insert into pspadm.' || table_name || ' select * from imp_psphpp02_pspadm.' || table_name || ' where (' ||split_part(pk_cols, ',', 1)|| ') in ('''||pk_seq||''') and ('||split_part(pk_cols, ',', 2)||') in ('''||company_fk||''');' from backup_oos.oos_metadata where table_name ='psp_qbdt_paycheck_info' and op_type='update' and status!='inflight') to 'fix_ins_for_update_oos_o2p_psp_qbdt_paycheck_info.sql';
\copy (select 'insert into pspadm.' || table_name || ' select * from imp_psphpp02_pspadm.' || table_name || ' where (' ||split_part(pk_cols, ',', 1)|| ') in ('''||pk_seq||''') and ('||split_part(pk_cols, ',', 2)||') in ('''||company_fk||''');' from backup_oos.oos_metadata where table_name ='psp_qbdt_payline_info' and op_type='update' and status!='inflight') to 'fix_ins_for_update_oos_o2p_psp_qbdt_payline_info.sql';
\copy (select 'insert into pspadm.' || table_name || ' select * from imp_psphpp02_pspadm.' || table_name || ' where (' ||split_part(pk_cols, ',', 1)|| ') in ('''||pk_seq||''') and ('||split_part(pk_cols, ',', 2)||') in ('''||company_fk||''');' from backup_oos.oos_metadata where table_name ='psp_qbdt_transaction_info' and op_type='update' and status!='inflight') to 'fix_ins_for_update_oos_o2p_psp_qbdt_transaction_info.sql';

