
select count(*) from IBOBADM.GG_HEARTBEAT;                                                                                                                                                                                                                                                                  
select count(*) from IBOBADM.PSP_HCM401K_COMPANY_POLICY;                                                                                                                                                                                                                                                    
select count(*) from IBOBADM.PSP_HCM401K_COMPANY_QBDT_PITEM;                                                                                                                                                                                                                                                
select count(*) from IBOBADM.PSP_HCM401K_EMPLOYEE_DEDUCTION;                                                                                                                                                                                                                                                
select count(*) from IBOBADM.PSP_HCM401K_POLICY;                                                                                                                                                                                                                                                            
select count(*) from IBOBADM.PSP_QBDT_REQUEST_INFO;                                                                                                                                                                                                                                                         
select count(*) from IBOBADM.PSP_SAP_METHOD_CALL;                                                                                                                                                                                                                                                           
select count(*) from IBOBADM.PSP_SOURCE_SYSTEM_TRANSMISSION;                                                                                                                                                                                                                                                
select count(*) from IBOBADM.TEST2;                                                                                                                                                                                                                                                                         
select count(*) from IBOBADM.TEST3;                                                                                                                                                                                                                                                                         
