CREATE USER &1 IDENTIFIED BY "&PASSWORD"
      DEFAULT TABLESPACE USERS
      TEMPORARY TABLESPACE TEMP
      PROFILE INDIVIDUAL_PROFILE;

GRANT PSPREAD_ROLE TO &&1;

GRANT CREATE SESSION TO &&1;

ALTER USER &&1 DEFAULT ROLE ALL;
