spool 01_create_tablespaces
set echo on
set feed on
set time on
set timi on

CREATE TABLESPACE PSP_DATA01 DATAFILE SIZE 50G AUTOEXTEND ON NEXT 100G MAXSIZE UNLIMITED;
CREATE TABLESPACE PSP_DATA02 DATAFILE SIZE 50G AUTOEXTEND ON NEXT 100G MAXSIZE UNLIMITED;
CREATE TABLESPACE PSP_DATA03 DATAFILE SIZE 10G AUTOEXTEND ON NEXT 100G MAXSIZE UNLIMITED;
CREATE TABLESPACE PSP_DATA04 DATAFILE SIZE 10G AUTOEXTEND ON NEXT 100G MAXSIZE UNLIMITED;

CREATE TABLESPACE PSP_IDX01 DATAFILE SIZE 50G AUTOEXTEND ON NEXT 100G MAXSIZE UNLIMITED;
CREATE TABLESPACE PSP_IDX02 DATAFILE SIZE 50G AUTOEXTEND ON NEXT 100G MAXSIZE UNLIMITED;
CREATE TABLESPACE PSP_IDX03 DATAFILE SIZE 10G AUTOEXTEND ON NEXT 100G MAXSIZE UNLIMITED;
CREATE TABLESPACE PSP_IDX04 DATAFILE SIZE 10G AUTOEXTEND ON NEXT 100G MAXSIZE UNLIMITED;

CREATE TABLESPACE PSP_LOB01 DATAFILE SIZE 50G AUTOEXTEND ON NEXT 10G MAXSIZE UNLIMITED;

CREATE TABLESPACE APPBUGFIX_DATA DATAFILE SIZE 1G AUTOEXTEND ON NEXT 1G MAXSIZE UNLIMITED;
CREATE TABLESPACE ARC_DATA01 DATAFILE SIZE 1G AUTOEXTEND ON NEXT 1G MAXSIZE UNLIMITED;
CREATE TABLESPACE ARC_IDX01 DATAFILE SIZE 1G AUTOEXTEND ON NEXT 1G MAXSIZE UNLIMITED;
CREATE TABLESPACE PSP_FLUX DATAFILE SIZE 1G AUTOEXTEND ON NEXT 1G MAXSIZE UNLIMITED;
CREATE TABLESPACE PSP_LOG DATAFILE SIZE 1G AUTOEXTEND ON NEXT 1G MAXSIZE UNLIMITED;
CREATE TABLESPACE TOOLS DATAFILE SIZE 1G AUTOEXTEND ON NEXT 1G MAXSIZE UNLIMITED;
CREATE TABLESPACE GGS_DATA DATAFILE SIZE 1G AUTOEXTEND ON NEXT 1G MAXSIZE UNLIMITED;
CREATE TABLESPACE GGT_DATA DATAFILE SIZE 1G AUTOEXTEND ON NEXT 1G MAXSIZE UNLIMITED;

spool off
exit

