// Generated by DB Solo ${version} on ${date} at ${time}
package ${generator.getPackage()};
<#assign temp>
${klass.setOwnPackage("${generator.getPackage()}")}

public class ${klass.getName()} <#if klass.hasExtendsClass()> extends ${klass.getExtendsClass()}</#if><#if klass.hasImplements()> implements ${klass.getImplementsList()}</#if>
{
<#foreach field in klass.getFields()>
  ${field.getFieldScope()} ${field.getJavaType()} ${field.getName()};
</#foreach>

    //
    // getters / setters
    //
<#foreach field in klass.getFields()>

    ${field.getGetScope()} ${field.getJavaType()} ${field.getterMethod()}() {
        return this.${field.getName()};
    }
    ${field.getSetScope()} void ${field.setterMethod()}(${field.getJavaType()} ${field.getName()}) {
        this.${field.getName()} = ${field.getName()};
    }

</#foreach>

  <#if klass.wantEquals()>    public boolean equals(Object obj) {
	      if(this == obj)
	          return true;
	      if(null == obj)
	          return false;
	      if(obj instanceof ${klass.getName()} == false)
	          return false;

   <#if klass.isSubClass()>
        if(super.equals((${klass.getSuperClass().getName()}) obj) == false)
           return false;
   </#if>

	      ${klass.getName()} other = ( ${klass.getName()} ) obj;

    <#foreach temp in klass.getEqualsFields()>
         ${temp.generateEquals("other")}
    </#foreach>

	      return true;
   }

   public int hashCode() {
   <#if klass.isSubClass()>
         int result = super.hashCode();
   <#else>
         int result = 29;
   </#if>

   <#list klass.getEqualsFields() as temp>
         ${temp.generateHashCode("result")}
    </#list>

         return result;
   }
  </#if>
  <#if klass.wantToString()> public String toString() {
	      StringBuffer buffer = new StringBuffer("${generator.getPackage()}").append(".").append("${klass.getName()}").append("(");

    <#list klass.getToStringFields() as temp>
        buffer.append("[").append("${temp.name}").append("=").append(${temp.name}).append("]");
    </#list>

	      return buffer.append(")").toString();
    }
  </#if>
}
</#assign>

<#list klass.getImports() as import>
  import ${import};
</#list>
<#list klass.getStaticImports() as import>
  import static ${import};
</#list>

${temp}
