// Generated by DB Solo ${version} on ${date} at ${time}
package ${generator.getDAOPackage()};
${klass.setOwnPackage("${generator.getDAOPackage()}")}

<#assign temp>
public interface ${klass.addImport("${generator.getDAOPackage()}.${klass.getDaoName()}")} {

   // CRUD methods
   public ${klass.addImport("${generator.getPackage()}.${klass.getName()}")} getByPrimaryKey(
<#list klass.getPrimaryKeyFields() as field>
     <#if field.isComponent() >
        ${klass.addImport("${generator.getPackage()}.${field.getJavaType()}")} ${field.getName()}
     <#else>
        ${field.getJavaType()} ${field.getName()}
     </#if>
</#list>
    ) throws DAOException;
  public ${klass.addImport("java.util.List")} selectAll() throws DAOException;
  public List select(String whereStatement, Object[] bindVariables) throws DAOException;
  public long selectCount() throws DAOException;
  public long selectCount(String whereStatement, Object[] bindVariables) throws DAOException;
  public int update(${klass.getName()} obj) throws DAOException;
  public int insert(${klass.getName()} obj) throws DAOException;
  public int delete(${klass.getName()} obj) throws DAOException;

  // Finders
<#list klass.getFields() as field>
  <#if !field.isPrimaryKey() >
    public List getBy${field.getNameInMethod()}(${field.getJavaType()} ${field.getName()}) throws DAOException;
 <#elseif field.isComponent()>
     <#list field.getComponent().getFields() as compField>
        public List getBy${compField.getNameInMethod()}(${compField.getJavaType(klass)} ${compField.getName()}) throws DAOException;
     </#list>
  </#if>
</#list>

}
</#assign>

<#list klass.getImports() as import>
  import ${import};
</#list>
<#list klass.getStaticImports() as import>
  import static ${import};
</#list>

${temp}
