// Generated by DB Solo ${version} on ${date} at ${time}
package ${generator.getDAOPackage()};

public class DAOException extends Exception
{
  public DAOException(String s, Exception e)
  {
    super(s, e);
  }
  
  public DAOException(String e)
  {
    super(e);
  }
  
  public DAOException(Exception e)
  {
    super(e);
  }
}