// Generated by DB Solo ${version} on ${date} at ${time}
package ${generator.getDAOPackage()};

import java.sql.Connection;

public abstract class DAOFactory {
  private static DAOFactory singleton;

  public static DAOFactory getInstance() throws DAOException
  {
      try {
        if(null == singleton)
          singleton = (DAOFactory) Class.forName("${generator.getDAOImplPackage()}.JDBCDAOFactory").newInstance();
      } catch (Exception e) {
        throw new DAOException("Could not create the DAOFactory singleton", e);
      }
      return singleton;
  }

<#list generator.getClasses() as entity>
  public abstract ${entity.getDaoName()} get${entity.getDaoName()}();
  public abstract ${entity.getDaoName()} get${entity.getDaoName()}(Connection conn);
</#list>

}

