// Generated by DB Solo ${version} on ${date} at ${time}
package ${generator.getDAOImplPackage()};
${klass.setOwnPackage("${generator.getDAOImplPackage()}")}

<#assign temp>
public class ${klass.getDaoImplName()} implements ${klass.addImport("${generator.getDAOPackage()}.${klass.getDaoName()}")} {

  //
  // static data
  //

  protected static ${klass.addImport("java.util.List")} pkColumns = new ${klass.addImport("java.util.ArrayList")}();
  protected static ${klass.addImport("java.util.List")} stdColumns = new ${klass.addImport("java.util.ArrayList")}();
  protected static ${klass.addImport("java.util.List")} allColumns = new ${klass.addImport("java.util.ArrayList")}();
<#if klass.supportsSchema()>
  protected static String tableName = "${klass.getSchemaName()}.${klass.getTableName()}";
<#else>
  protected static String tableName = "${klass.getTableName()}";
</#if>

  static
  {
<#foreach field in klass.getFields()>
    <#if field.isPrimaryKey() >
      <#foreach column in field.getColumns() >
    pkColumns.add("${column.getName()}");
      </#foreach>
    </#if>
</#foreach>
<#foreach field in klass.getFields()>
    <#if !field.isPrimaryKey() >
      <#foreach column in field.getColumns() >
         stdColumns.add("${column.getName()}");
      </#foreach>
    </#if>
</#foreach>
    allColumns.addAll(pkColumns);
    allColumns.addAll(stdColumns);
  }

  //
  // data
  //

  protected ${klass.addImport("java.sql.Connection")} conn = null;

  //
  // construction
  //

  public ${klass.getDaoImplName()}()
  {
    this(null);
  }

  public ${klass.getDaoImplName()}(Connection conn)
  {
    this.conn = conn;
  }



  //
  // CRUD methods
  //

   public ${klass.addImport("${generator.getPackage()}.${klass.getName()}")} getByPrimaryKey(
<#list klass.getFields() as field>
  <#if field.isPrimaryKey() >
     <#if field.isComponent() >
        ${klass.addImport("${generator.getPackage()}.${field.getJavaType()}")} ${field.getName()}
     <#else>
        ${field.getJavaType()} ${field.getName()}
     </#if>
  </#if>
</#list>
    ) throws ${klass.addImport("${generator.getDAOPackage()}.DAOException")}
   {
    ${klass.addImport("java.sql.PreparedStatement")} ps = null;
    ${klass.addImport("java.sql.ResultSet")} rs = null;

    try
    {
      int pos = 1;
      ps = getConn().prepareStatement(DBUtil.select(tableName, allColumns, pkColumns));
<#if klass.getPrimaryKeyField().isComponent() >
  <#foreach field in klass.getFields()>
    <#if field.isPrimaryKey() >
      <#foreach idfield in  klass.getPrimaryKeyField().getComponent().getFields()>
    DBUtil.bind(ps, pos++, ${field.getName()}.${idfield.getterMethod()}());
      </#foreach>
    </#if>
  </#foreach>
<#else>
  <#foreach field in klass.getFields()>
    <#if field.isPrimaryKey() >
      DBUtil.bind(ps, pos++, ${field.getName()});
    </#if>
  </#foreach>
</#if>
      rs = ps.executeQuery();

      if(rs.next())
        return fromResultSet(rs);
    }
    catch(${klass.addImport("java.sql.SQLException")} e)
    {
      throw new DAOException(e);
    }
    finally
    {
      DBUtil.close(ps, rs);
    }

    return null;
   }

  public long selectCount() throws DAOException
  {
    PreparedStatement ps = null;
    ResultSet rs = null;

    try
    {
      ps = getConn().prepareStatement("select count(*) from " + tableName);
      rs = ps.executeQuery();

      if (rs.next())
        return rs.getLong(1);
    }
    catch (SQLException e)
    {
      throw new DAOException(e);
    }
    finally
    {
      DBUtil.close(ps, rs);
    }

    return 0;
  }

  public long selectCount(String whereStatement, Object[] bindVariables) throws DAOException
  {
    PreparedStatement ps = null;
    ResultSet rs = null;

    if(!whereStatement.trim().toUpperCase().startsWith("WHERE"))
       whereStatement = " WHERE " + whereStatement;
    else if(whereStatement.startsWith(" ") == false)
       whereStatement = " " + whereStatement;

  try
    {
      ps = getConn().prepareStatement("select count(*) from " + tableName + whereStatement);

      for(int i = 0; i < bindVariables.length; i++)
           DBUtil.bind(ps, i+1, bindVariables[i]);

      rs = ps.executeQuery();

      if(rs.next())
        return rs.getLong(1);
    }
    catch(${klass.addImport("java.sql.SQLException")} e)
    {
      throw new DAOException(e);
    }
    finally
    {
      DBUtil.close(ps, rs);
    }
    return 0;
  }

  public List selectAll() throws DAOException
  {
    ${klass.addImport("java.util.List")} ret = new ${klass.addImport("java.util.ArrayList")}();
    ${klass.addImport("java.sql.PreparedStatement")} ps = null;
    ${klass.addImport("java.sql.ResultSet")} rs = null;

    try
    {
      ps = getConn().prepareStatement(DBUtil.select(tableName, allColumns));
      rs = ps.executeQuery();

      while(rs.next())
        ret.add(fromResultSet(rs));
    }
    catch(${klass.addImport("java.sql.SQLException")} e)
    {
      throw new DAOException(e);
    }
    finally
    {
      DBUtil.close(ps, rs);
    }

    return ret;
  }

  public List select(String whereStatement, Object[] bindVariables) throws DAOException
  {
      List ret = new ArrayList();
      PreparedStatement ps = null;
      ResultSet rs = null;

      if(!whereStatement.trim().toUpperCase().startsWith("WHERE"))
        whereStatement = " WHERE " + whereStatement;
      else if(whereStatement.startsWith(" ") == false)
        whereStatement = " " + whereStatement;

      try
      {
          ps = getConn().prepareStatement(DBUtil.select(tableName, allColumns) + whereStatement);

          for(int i = 0; i < bindVariables.length; i++)
              DBUtil.bind(ps, i+1, bindVariables[i]);

          rs = ps.executeQuery();
          while (rs.next())
              ret.add(fromResultSet(rs));
      }
      catch (SQLException e)
      {
          throw new DAOException("Error in select(), table = " + tableName, e);
      }
      finally
      {
          DBUtil.close(ps, rs);
      }

      return ret;
   }

   public int update(${klass.getName()} obj) throws DAOException
   {
     PreparedStatement ps = null;
     int pos = 1;

     try
     {
        ps = getConn().prepareStatement(DBUtil.update(tableName, stdColumns, pkColumns));
        pos = bindStdColumns(ps, obj, pos);
        bindPrimaryKey(ps, obj, pos);
        int rowCount = ps.executeUpdate();

       if(rowCount != 1)
         throw new DAOException("Error updating " + obj.getClass() + " in " + tableName + ", affected rows = " + rowCount);

       return rowCount;
     }
     catch (SQLException e)
     {
        throw new DAOException(e);
     }
     finally
     {
        DBUtil.close(ps, null);
     }
   }

   public int insert(${klass.getName()} obj) throws DAOException
   {
     PreparedStatement ps = null;
     int pos = 1;

     try
     {
<#if klass.isSequencePrimaryKey()>
<#foreach field in klass.getFields()>
  <#if field.isPrimaryKey() >
    obj.${field.setterMethod()}(getGeneratedId());
  </#if>
</#foreach>
</#if>

<#if klass.isIdentityPrimaryKey()>
        ps = getConn().prepareStatement(DBUtil.insert(tableName, new ArrayList(), stdColumns));
<#else>
        ps = getConn().prepareStatement(DBUtil.insert(tableName, pkColumns, stdColumns));
        pos = bindPrimaryKey(ps, obj, pos);
</#if>
        bindStdColumns(ps, obj, pos);
        int rowCount = ps.executeUpdate();
<#if klass.isIdentityPrimaryKey()>
<#foreach field in klass.getFields()>
  <#if field.isPrimaryKey() >
    obj.${field.setterMethod()}(getGeneratedId());
  </#if>
</#foreach>
</#if>

       if(rowCount != 1)
         throw new DAOException("Error inserting " + obj.getClass() + " in " + tableName + ", affected rows = " + rowCount);

       return rowCount;
     }
     catch (SQLException e)
     {
        throw new DAOException(e);
     }
     finally
     {
        DBUtil.close(ps, null);
     }
   }

<#if klass.isIdentityPrimaryKey() || klass.isSequencePrimaryKey() >
   protected ${klass.getPrimaryKeyField().getJavaType()} getGeneratedId() throws DAOException
   {
     PreparedStatement ps = null;
     ResultSet rs = null;

     try
     {
<#if klass.isSequencePrimaryKey() >
  <#if generator.isOracle() >
        ps = getConn().prepareStatement("SELECT ${klass.getSequenceName()}.NEXTVAL FROM DUAL");
  <#elseif generator.isDB2() >
        ps = getConn().prepareStatement("VALUES NEXTVAL FOR ${klass.getSequenceName()}");
  <#elseif generator.isPostgres() >
        ps = getConn().prepareStatement("SELECT NEXTVAL('${klass.getSequenceName()}')");
  </#if>
</#if>

<#if klass.isIdentityPrimaryKey() >
  <#if generator.isSQLServer() || generator.isSybase() >
        ps = getConn().prepareStatement("SELECT @@IDENTITY");
  <#elseif generator.isOracle() >
        ps = getConn().prepareStatement("SELECT MAX(" + pkColumns.get(0) + ") FROM " + tableName);
  <#elseif generator.isMySQL() >
        ps = getConn().prepareStatement("SELECT LAST_INSERT_ID()");
  <#elseif generator.isDB2() >
        ps = getConn().prepareStatement("VALUES IDENTITY_VAL_LOCAL()");
  <#elseif generator.isH2() >
        ps = getConn().prepareStatement("SELECT IDENTITY()");
  <#elseif generator.isPostgres() >
        ps = getConn().prepareStatement("SELECT CURRVAL('${klass.getSchemaName()}.${klass.getTableName()}_" + pkColumns.get(0) + "_seq')");
  </#if>
</#if>
        rs = ps.executeQuery();

        if(rs.next())
          return DBUtil.${generator.dbutilGetter(klass.getPrimaryKeyField())}(rs, 1);

<#if klass.getPrimaryKeyField().isPrimitive() >
       return 0;
<#else>
       return null;
</#if>

     }
     catch (SQLException e)
     {
        throw new DAOException(e);
     }
     finally
     {
        DBUtil.close(ps, rs);
     }
   }
</#if>

   public int delete(${klass.getName()} obj) throws DAOException
   {
     PreparedStatement ps = null;

     try
     {
        ps = getConn().prepareStatement(DBUtil.delete(tableName, pkColumns));
        bindPrimaryKey(ps, obj, 1);
        int rowCount = ps.executeUpdate();

       if(rowCount != 1)
         throw new DAOException("Error deleting " + obj.getClass() + " in " + tableName + ", affected rows = " + rowCount);

       return rowCount;           
     }
     catch (SQLException e)
     {
        throw new DAOException(e);
     }
     finally
     {
        DBUtil.close(ps, null);
     }
   }

  //
  // finders
  //
<#list klass.getFields() as field>
  <#if !field.isPrimaryKey() >
  public List getBy${field.getNameInMethod()}(${field.getJavaType()} ${field.getName()}) throws DAOException
  {
    PreparedStatement ps = null;
    ResultSet rs = null;
    List ret = new ArrayList();

    try
    {
      <#if field.isPrimitive() >
        ps = getConn().prepareStatement(DBUtil.select(tableName, allColumns, ${klass.addImport("java.util.Arrays")}.asList(new String[] {"${field.getColumnName()}"})));
        DBUtil.bind(ps, 1, ${field.getName()});
     <#else>
        if(null == ${field.getName()})
        {
          ps = getConn().prepareStatement(DBUtil.selectNull(tableName, allColumns, ${klass.addImport("java.util.Arrays")}.asList(new String[] {"${field.getColumnName()}"})));
        }
        else
        {
          ps = getConn().prepareStatement(DBUtil.select(tableName, allColumns, ${klass.addImport("java.util.Arrays")}.asList(new String[] {"${field.getColumnName()}"})));
          DBUtil.bind(ps, 1, ${field.getName()});
        }
     </#if>
      rs = ps.executeQuery();

      while (rs.next())
        ret.add(fromResultSet(rs));
    }
    catch (SQLException e)
    {
      throw new DAOException(e);
    }
    finally
    {
      DBUtil.close(ps, rs);
    }

    return ret;
  }
  <#elseif field.isComponent()>
     <#list field.getComponent().getFields() as compField>
       public List getBy${compField.getNameInMethod()}(${compField.getJavaType(klass)} ${compField.getName()}) throws DAOException
       {
          PreparedStatement ps = null;
          ResultSet rs = null;
          List ret = new ArrayList();

          try
          {
              ps = getConn().prepareStatement(DBUtil.select(tableName, allColumns, ${klass.addImport("java.util.Arrays")}.asList(new String[] {"${compField.getColumnName()}"})));
              DBUtil.bind(ps, 1, ${compField.getName()});
              rs = ps.executeQuery();

              while (rs.next())
                ret.add(fromResultSet(rs));
          }
          catch (SQLException e)
          {
              throw new DAOException("SQL Error in finder getBy${compField.getNameInMethod()}()", e);
          }
          finally
          {
            DBUtil.close(ps, rs);
          }
          return ret;
      }
     </#list>
  </#if>
</#list>

   //
   // helpers
   //
   protected int bindPrimaryKey(PreparedStatement ps, ${klass.getName()} obj, int pos) throws SQLException
   {
<#if klass.getPrimaryKeyField().isComponent() >
  <#foreach field in klass.getPrimaryKeyFields()>
      <#foreach idfield in  field.getComponent().getFields()>
         DBUtil.bind(ps, pos++, obj.${field.getterMethod()}().${idfield.getterMethod()}());
      </#foreach>
  </#foreach>
<#else>
  <#foreach field in klass.getPrimaryKeyFields()>
    DBUtil.bind(ps, pos++, obj.${field.getterMethod()}());
  </#foreach>
</#if>
     return pos;
   }

   protected int bindStdColumns(PreparedStatement ps, ${klass.getName()} obj, int pos) throws SQLException
   {
   <#foreach field in klass.getFields()>
     <#if !field.isPrimaryKey() >
        <#if field.getJavaType() == "String" && field.getColumn().isOracleXMLType()>
          DBUtil.bindXMLTypeString(ps, pos++, obj.${field.getterMethod()}());
        <#else>
          DBUtil.bind(ps, pos++, obj.${field.getterMethod()}());
        </#if>
     </#if>
   </#foreach>
        return pos;
   }

   protected ${klass.getName()} fromResultSet(ResultSet rs) throws SQLException
   {
     ${klass.getName()} obj = new ${klass.getName()}();

<#foreach field in klass.getFields()>
  <#if field.isComponent() == false>
    <#foreach column in field.getColumns() >
        obj.${field.setterMethod()}(DBUtil.${generator.dbutilGetter(field)}(rs, "${column.getName()}"));
     </#foreach>
  <#else>
     obj.${field.setterMethod()}(${field.getterMethod()}(rs));
  </#if>
</#foreach>

     return obj;
   }

<#foreach field in klass.getFields()>
  <#if field.isComponent() && field.isPrimaryKey()>
   protected ${field.getJavaType()} ${field.getterMethod()}(ResultSet rs) throws SQLException
   {
     ${field.getJavaType()} obj = new ${field.getJavaType()}();

  <#foreach idfield in klass.getPrimaryKeyField().getComponent().getFields() >
    <#foreach column in idfield.getColumns() >
       obj.${idfield.setterMethod()}(DBUtil.${generator.dbutilGetter(idfield)}(rs, "${column.getName()}"));
    </#foreach>
  </#foreach>

     return obj;
   }
  </#if>
</#foreach>


  protected Connection getConn() { return conn == null ? DBUtil.getConnection() : conn; }
}
</#assign>

<#list klass.getImports() as import>
  import ${import};
</#list>
<#list klass.getStaticImports() as import>
  import static ${import};
</#list>

${temp}
