// Generated by DB Solo ${version} on ${date} at ${time}
package ${generator.getDAOImplPackage()};
${klass.setOwnPackage("${generator.getDAOImplPackage()}")}

import java.sql.Connection;
<#if generator.getDAOPackage() != generator.getDAOImplPackage() >
   import ${generator.getDAOPackage()}.DAOFactory;

   <#list generator.getClasses() as entity>
     import ${generator.getDAOPackage()}.${entity.getDaoName()};
   </#list>
</#if>

public class JDBCDAOFactory extends DAOFactory
{
<#list generator.getClasses() as entity>
  public ${entity.getDaoName()} get${entity.getDaoName()}() { return new ${entity.getDaoImplName()}(); }
  public ${entity.getDaoName()} get${entity.getDaoName()}(Connection conn) { return new ${entity.getDaoImplName()}(conn); }
</#list>
}

