// Generated by DB Solo ${version} on ${date} at ${time}
package ${generator.getJUnitPackage()};
${klass.setOwnPackage("${generator.getJUnitPackage()}")}

<#assign temp>

public class ${klass.getDaoImplName()}Test extends TestCase {

  private ${klass.addImport("java.sql.Connection")} conn = null;

  protected void setUp() throws Exception
  {
    conn = TestUtil.getConnection();
  }

  protected void tearDown() throws Exception
  {
    TestUtil.closeConnection(conn);
    conn = null;
  }

  public void testSelect() {
     ${klass.addImport("${generator.getDAOImplPackage()}.${klass.getDaoImplName()}")} obj = new ${klass.getDaoImplName()}(getConn());

    try
    {
      obj.selectAll();
    }
    catch(Exception e)
    {
      e.printStackTrace();
      assertTrue(false);
    }
  }

  public void testDelete() {
    try
    {
      ${klass.getDaoImplName()} dao = new ${klass.getDaoImplName()}(getConn());

      ${klass.addImport("${generator.getPackage()}.${klass.getName()}")} obj = insert(getConn());
      int before = dao.selectAll().size(), after;

      dao.delete(obj);
      after = dao.selectAll().size();
      assertTrue(after == before - 1);
      getConn().commit();
    } catch(Exception e) {
      e.printStackTrace();
      assertFalse(true);
    }
  }

  public void testFinders() {
    try
    {
      ${klass.getDaoImplName()} dao = new ${klass.getDaoImplName()}(getConn());
      ${klass.getName()} obj = insert(getConn());

<#list klass.getFields() as field>
  <#if !field.isPrimaryKey() >
       assertTrue(dao.getBy${field.getNameInMethod()}(obj.${field.getterMethod()}()).size() > 0);
  </#if>
</#list>
      dao.delete(obj);

      getConn().commit();
    } catch(Exception e) {
      e.printStackTrace();
      assertFalse(true);
    }
  }

  public void testInsert() {
    try
    {
      ${klass.getDaoImplName()} dao = new ${klass.getDaoImplName()}(getConn());

      int before = dao.selectAll().size();
      ${klass.getName()} obj = insert(getConn());
      int after = dao.selectAll().size();

      assertNotNull(obj);
      assertTrue(after == before + 1);
      getConn().commit();
    } catch(Exception e) {
      e.printStackTrace();
      assertFalse(true);
    }
  }

  public void testUpdate() {
    try
    {
      // insert
      ${klass.getDaoImplName()} dao = new ${klass.getDaoImplName()}(getConn());
      ${klass.getName()} obj = insert(getConn());

      // update
<#foreach field in klass.getFields()>
    <#if generator.updatableField(field) >
         <#if field.isComponent() == false>
      ${field.getJavaType()} temp${field.getName()} = TestUtil.random_${generator.methodNameForRandom(field)}();
         <#else>
      ${field.getJavaType()} temp${field.getName()} = random_${generator.methodNameForRandom(field)}();
         </#if>
    </#if>
</#foreach>

<#foreach field in klass.getFields()>
    <#if generator.updatableField(field) >
      obj.${field.setterMethod()}(temp${field.getName()});
    </#if>
</#foreach>
      dao.update(obj);

      // verify results
<#foreach field in klass.getFields()>
  <#if field.isPrimaryKey() >
      obj = dao.getByPrimaryKey(
<#foreach field in klass.getFields()>
  <#if field.isPrimaryKey() >
      obj.${field.getterMethod()}()
  </#if>
</#foreach>
      );
  </#if>
</#foreach>

<#foreach field in klass.getFields()>
    <#if generator.updatableField(field) >
      ${generator.getAssertEquals("TestUtil", field)};
    </#if>
</#foreach>
      getConn().commit();

    } catch(Exception e) {
      e.printStackTrace();
      assertFalse(true);
    }
  }


  protected static ${klass.getName()} insert(Connection conn) throws Exception {
    ${klass.getName()} obj = new ${klass.getName()}();
    ${klass.getDaoImplName()} dao = new ${klass.getDaoImplName()}(conn);
<#if generator.insertablePrimaryKey(klass) && klass.getPrimaryKeyField().isComponent() >
    ${klass.addImport("${generator.getPackage()}.${klass.getPrimaryKeyField().getJavaType()}")} id = new ${klass.getPrimaryKeyField().getJavaType()}();
    <#if generator.isForeignKey(klass.getPrimaryKeyField())  >
       ${klass.addImport("${generator.getPackage()}.${generator.getReferencedEntity(klass.getPrimaryKeyField()).getName()}")} ref = ${generator.getReferencedEntity(klass.getPrimaryKeyField()).getName()}DAOImplTest.insert(conn);

        <#list klass.getPrimaryKeyField().getComponent().getFields() as field>
           id. ${field.setterMethod()} (ref. ${generator.getReferencedEntity(klass.getPrimaryKeyField()).getPrimaryKeyField().getterMethod()} (). ${generator.getReferencedComponentField(klass.getPrimaryKeyField(), field).getterMethod()} ());
        </#list>
    <#else>
        <#list klass.getPrimaryKeyField().getComponent().getFields() as field>
           id.${field.setterMethod()}(TestUtil.random_${generator.methodNameForRandom(field)}());
        </#list>
    </#if>

    obj.${klass.getPrimaryKeyField().setterMethod()}(id);
<#else>

</#if>
<#foreach field in klass.getFields()>
    <#if generator.isForeignKey(field) >
        <#if generator.isSharedPK(field) >
           <#if false == field.isComponent() >
              obj. ${field.setterMethod()} ( ${generator.getReferencedEntity(field).getName()}DAOImplTest.insert(conn).${generator.getReferencedField(field).getterMethod()}());
           </#if>
        <#elseif generator.isSelfRef(field)  >
             obj. ${field.setterMethod()} (obj. ${klass.getPrimaryKeyField().getterMethod()} ());
        <#elseif generator.hasReferencedEntity(field)>
             <#if generator.isFirstForeignKeyColumn(field) >
                 <#if generator.multiColumnForeignKey(field) >
                   ${klass.addImport("${generator.getPackage()}.${generator.getReferencedEntity(field).getName()}")} temp${field_index} = ${generator.getReferencedEntity(field).getName()}DAOImplTest.insert(conn);
                      <#list generator.getAllForeignKeyFields(field) as comp>
                         obj. ${comp.setterMethod()} (temp${field_index}. ${generator.getReferencedEntity(field).getPrimaryKeyField().getterMethod()} (). ${generator.getReferencedComponentField(comp).getterMethod()} ());
                      </#list>
                 <#else>
                     obj. ${field.setterMethod()} ( ${generator.getReferencedEntity(field).getName()}DAOImplTest.insert(conn).${generator.getReferencedField(field).getterMethod()}());
                 </#if>
             </#if>
        </#if>
     <#elseif field.isPrimaryKey() == false >
        <#if field.isComponent() == false>
             obj.${field.setterMethod()}(TestUtil.random_${generator.methodNameForRandom(field)}());
         <#else>
             obj.${field.setterMethod()}(random_${generator.methodNameForRandom(field)}());
        </#if>
     <#elseif generator.insertablePrimaryKey(klass)>
        <#if klass.getPrimaryKeyField().isComponent() == false>
              obj.${field.setterMethod()}(TestUtil.random_${generator.methodNameForRandom(field)}());
        </#if>
     </#if>
</#foreach>

    dao.insert(obj);

    return obj;
  }


  private Connection getConn() { return conn; }
}

</#assign>

import junit.framework.TestCase;
<#list klass.getImports() as import>
  import ${import};
</#list>
<#list klass.getStaticImports() as import>
  import static ${import};
</#list>

${temp}

