select to_char(CREATED_DATE,'MON-YY'),count(1) from IBOBADM.PSP_QBDT_REQUEST_INFO where SOURCE_SYSTEM_TRANSMISSION_FK IN
( select SOURCE_SYSTEM_TRANSMISSION_SEQ from IBOBADM.PSP_SOURCE_SYSTEM_TRANSMISSION where COMPANY_ID = '&company_id'
    )
group by to_char(CREATED_DATE,'MON-YY') order by to_char(CREATED_DATE,'MON-YY');

