SELECT /*+PARALLEL(16) */ count(EVENT_AS400_SYNC_SEQ)
FROM PSPADM.PSP_EVENT_AS400_SYNC ceei,
     PSPADM.PSP_COMPANY_EVENT cei
WHERE ceei.COMPANY_EVENT_FK = cei.COMPANY_EVENT_SEQ
  AND ceei.COMPANY_FK is not null
  and ceei.COMPANY_FK = cei.COMPANY_FK
  and ceei.EVENT_AS400_SYNC_SEQ in
      (SELECT EVENT_AS400_SYNC_SEQ FROM SKUMAR71.PSP_EVENT_AS400_SYNC_TEMP);