DROP TABLE IF EXISTS TMP_PSP_PAYMENT_TEMPLATE CASCADE

;

--------------------------------------------------------
-- Create temp table                                  --
--------------------------------------------------------

CREATE TABLE TMP_PSP_PAYMENT_TEMPLATE (LIKE PSP_PAYMENT_TEMPLATE INCLUDING ALL)

;

--------------------------------------------------------
-- Insert into temp table                             --
--------------------------------------------------------

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'GA-DOL4-PAYMENT' , 'GADOL', 'GA-DOL4-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'NY-45MN-PAYMENT' , 'NYDOL', 'NY-45MN-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'CO-UITR1-PAYMENT' , 'CODLE', 'CO-UITR1-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'MN_UI' , 'MNEEUI', 'MN_UI', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'MN-DEED1-PAYMENT' , 'MNEEUI', 'MN-DEED1-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'OK-OES3-PAYMENT' , 'OKESC', 'OK-OES3-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'MN-MW1-PAYMENT' , 'MNDOR', 'MN-MW1-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'MN_WH' , 'MNDOR', 'MN_WH', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'NM-CRS1-PAYMENT' , 'NMTRD', 'NM-CRS1-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'NM-WC1-PAYMENT' , 'NMTRD', 'NM-WC1-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'GA-GAV-PAYMENT' , 'GADOR', 'GA-GAV-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'WY-WYO056-PAYMENT' , 'WYDOE', 'WY-WYO056-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'IL-501-PAYMENT' , 'ILDOR', 'IL-501-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'KY-UI3-PAYMENT' , 'KYDES', 'KY-UI3-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'SD-UID21-PAYMENT' , 'SDUID', 'SD-UID21-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'HI-VP1-PAYMENT' , 'HIDOT', 'HI-VP1-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'PA-501-PAYMENT' , 'PADOR', 'PA-501-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'WI-UCT101-PAYMENT' , 'WIDWD', 'WI-UCT101-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'AR-941M-PAYMENT' , 'ARDFA', 'AR-941M-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'NJ-NJ500-PAYMENT' , 'NJT', 'NJ-NJ500-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'NJ-NJ927PWH-PAYMENT' , 'NJT', 'NJ-NJ927PWH-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'OR-OTCWH-PAYMENT' , 'ORDOR', 'OR-OTCWH-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'OR-STTV-PAYMENT' , 'ORDOR', 'OR-STTV-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION) VALUES (
'OR-PFMSL-PAYMENT' , 'ORDOR', 'OR-PFMSL-PAYMENT', 0, 0)
;
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION) VALUES (
'OR-OTCUI-PAYMENT' , 'ORDOR', 'OR-OTCUI-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'VA-FC20-PAYMENT' , 'VAEC', 'VA-FC20-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'CT-CTWH-PAYMENT' , 'CTDRS', 'CT-CTWH-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'MD-MW506-PAYMENT' , 'MDRAD', 'MD-MW506-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'ID-910-PAYMENT' , 'IDSTC', 'ID-910-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'TN-LB0456-PAYMENT' , 'TNDOL', 'TN-LB0456-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'WA-F5208-PAYMENT' , 'WAESD', 'WA-F5208-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'WA-PFML-PAYMENT' , 'WAESD', 'WA-PFML-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'WA-CARES-PAYMENT' , 'WAESD', 'WA-CARES-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'AZ-UC018-PAYMENT' , 'AZDES', 'AZ-UC018-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'MO-941-PAYMENT' , 'MODOR', 'MO-941-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'NY-MTA305-PAYMENT' , 'NYMCT', 'NY-MTA305-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'CA-PITSDI-PAYMENT' , 'CAEDD', 'CA-PIT/SDI', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'CA-UIETT-PAYMENT' , 'CAEDD', 'CA-UI/ETT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'AL-CR4WH-PAYMENT' , 'ALDOR', 'AL-CR4WH-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'IA-44105-PAYMENT' , 'IADOR', 'IA-44105-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'DE-DES-PAYMENT' , 'DEDFR', 'DE-DES-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION) VALUES (
'CO-FAMLI-PAYMENT' , 'CODFMLI', 'CO-FAMLI-PAYMENT', 0, 0)
;
INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION) VALUES (
'HI-UCB6-PAYMENT' , 'HIDLIR', 'HI-UCB6-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'KY-K1-PAYMENT' , 'KYDOR', 'KY-K1-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'SC-UCE120-PAYMENT' , 'SCESC', 'SC-UCE120-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'PA-UC2-PAYMENT' , 'PADLI', 'PA-UC2-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'WV-IT101-PAYMENT' , 'WVSTD', 'WV-IT101-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'RI-941-PAYMENT' , 'RIDOT', 'RI-941-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'RI-TX17-PAYMENT' , 'RIDOT', 'RI-TX17-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'NC-NC5P-PAYMENT' , 'NCDOR', 'NC-NC5P-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'AR-209B-PAYMENT' , 'ARESD', 'AR-209B-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'VT-C101-PAYMENT' , 'VTDOL', 'VT-C101-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'LA-ES61-PAYMENT' , 'LADOL', 'LA-ES61-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'MT-MW1-PAYMENT' , 'MTDOR', 'MT-MW1-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'VA-VA15-PAYMENT' , 'VADOT', 'VA-VA15-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'ME-941C1ME-PAYMENT' , 'MEUITD', 'ME-941C1ME-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'IL-UI340-PAYMENT' , 'ILDES', 'IL-UI340-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'CT-2MAG-PAYMENT' , 'CTDOL', 'CT-2MAG-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'IA-600103-PAYMENT' , 'IAWD', 'IA-600103-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'MA-M941-PAYMENT' , 'MADOR', 'MA-M941-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'MA-PFML-PAYMENT' , 'MADOR', 'MA-PFML-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'NV-NUCS4072-PAYMENT' , 'NVETR', 'NV-NUCS4072-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'VT-WH433-PAYMENT' , 'VTDOT', 'VT-WH433-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'IRS-941-PAYMENT' , 'IRS', 'IRS-941/944', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'IRS-940-PAYMENT' , 'IRS', 'IRS-940', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'IN-WH1-PAYMENT' , 'INDOR', 'IN-WH1-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'OH-IT501-PAYMENT' , 'OHDOT', 'OH-IT501-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'OH-SD101-PAYMENT' , 'OHDOT', 'OH-SD101-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'NH-DES200-PAYMENT' , 'NHES', 'NH-DES200-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'MT-UI5-PAYMENT' , 'MTUID', 'MT-UI5-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'DC-UC30-PAYMENT' , 'DCDES', 'DC-UC30-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'DC-PFL-PAYMENT' , 'DCDES', 'DC-PFL-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'MI-UIA1020-PAYMENT' , 'MIDLEG', 'MI-UIA1020-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'MI-MW106-PAYMENT' , 'MIDOT', 'MI-MW106-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'AK-AKNS-PAYMENT' , 'AKDLWD', 'AK-AKNS-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'MA-1700HI-PAYMENT' , 'MAWUA', 'MA-1700HI-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'AL-CR4UI-PAYMENT' , 'ALDIR', 'AL-CR4UI-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'ND-SFN41263-PAYMENT' , 'NDJS', 'ND-SFN41263-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'WV-A154-PAYMENT' , 'WVBEP', 'WV-A154-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'NJ-NJ927PUI-PAYMENT' , 'NJDLWD', 'NJ-NJ927PUI-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'NJ-NJ500UI-PAYMENT' , 'NJDLWD', 'NJ-NJ500UI-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'DE-UC8-PAYMENT' , 'DEDOL', 'DE-UC8-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'FL-UCT6-PAYMENT' , 'FLDOR', 'FL-UCT6-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'LA-L1-PAYMENT' , 'LADOR', 'LA-L1-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'NE-UI11T-PAYMENT' , 'NEWD', 'NE-UI11T-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'CT-PFML-PAYMENT' , 'CTPLA', 'CT-PFML-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'IN-UC1-PAYMENT' , 'INDWD', 'IN-UC1-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'OH-JFS20127-PAYMENT' , 'OHJFS', 'OH-JFS20127-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'OH-JFS66111-PAYMENT' , 'OHJFS', 'OH-JFS66111-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'ID-020-PAYMENT' , 'IDCL', 'ID-020-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'SC-WH1601-PAYMENT' , 'SCDOR', 'SC-WH1601-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'ND-306-PAYMENT' , 'NDSTC', 'ND-306-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'UT-TC96-PAYMENT' , 'UTTC', 'UT-TC96-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'NC-101-PAYMENT' , 'NCESC', 'NC-101-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'NM-ES903A-PAYMENT' , 'NMDOL', 'NM-ES903A-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'CO-DR1094-PAYMENT' , 'CODOR', 'CO-DR1094-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'OK-OW9A-PAYMENT' , 'OKTC', 'OK-OW9A-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'MS-UI23-PAYMENT' , 'MSDES', 'MS-UI23-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'MD-DLLR-PAYMENT' , 'MDOUI', 'MD-DLLR-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'NY-SDI-PAYMENT' , 'NYSIF', 'NY-SDI-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'MO-MODES-PAYMENT' , 'MODES', 'MO-MODES-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'AZ-A1-PAYMENT' , 'AZDOR', 'AZ-A1-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'DC-FR900-PAYMENT' , 'DCOTR', 'DC-FR900-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'UT-F3-PAYMENT' , 'UTDWS', 'UT-F3-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'TX-C3V-PAYMENT' , 'TXWC', 'TX-C3V-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'KS-KW5-PAYMENT' , 'KSDOR', 'KS-KW5-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'MS-M89-PAYMENT' , 'MSSTC', 'MS-M89-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'WI-WT6-PAYMENT' , 'WIDOR', 'WI-WT6-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'NE-941N-PAYMENT' , 'NEDOR', 'NE-941N-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'ME-900ME-PAYMENT' , 'MERS', 'ME-900ME-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'KS-KCNS100-PAYMENT' , 'KSDOL', 'KS-KCNS100-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'KS-CNS100-PAYMENT' , 'KSDOL', 'KS-CNS100-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'NY-1MN-PAYMENT' , 'NYDTF', 'NY-1MN-PAYMENT', 0, 0)
;

INSERT INTO TMP_PSP_PAYMENT_TEMPLATE (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION ) VALUES (
'DE-PFML-PAYMENT' , 'DEDOL', 'DE-PFML-PAYMENT', 0, 0)
;



--------------------------------------------------------
-- Sychronize temp table and real table by            --
-- inserting, deleting, and updating as necessary     --
--------------------------------------------------------

INSERT INTO PSP_PAYMENT_TEMPLATE
   (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION)
SELECT
    PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION, VERSION
FROM
   TMP_PSP_PAYMENT_TEMPLATE tt
WHERE
   tt.PAYMENT_TEMPLATE_CD NOT IN (SELECT PAYMENT_TEMPLATE_CD FROM PSP_PAYMENT_TEMPLATE)

;

UPDATE PSP_PAYMENT_TEMPLATE rt
SET (PAYMENT_TEMPLATE_CD, AGENCY_FK, PAYMENT_TEMPLATE_ABBREV, NO_CALCULATION) =
(SELECT  tt.PAYMENT_TEMPLATE_CD, tt.AGENCY_FK, tt.PAYMENT_TEMPLATE_ABBREV, tt.NO_CALCULATION
 FROM TMP_PSP_PAYMENT_TEMPLATE tt WHERE tt.PAYMENT_TEMPLATE_CD = rt.PAYMENT_TEMPLATE_CD)
 WHERE rt.PAYMENT_TEMPLATE_CD IN (SELECT PAYMENT_TEMPLATE_CD FROM TMP_PSP_PAYMENT_TEMPLATE)
;



--------------------------------------------------------
-- Drop temp table                                  --
--------------------------------------------------------
DROP TABLE TMP_PSP_PAYMENT_TEMPLATE

;
COMMIT
