DECLARE
	
	index_exists PLS_INTEGER;

BEGIN
	SELECT COUNT(*) INTO index_exists
	FROM "USER_INDEXES"
	WHERE INDEX_NAME = 'PSP_COMPANY_U1';

	IF index_exists = 1 THEN
		EXECUTE IMMEDIATE 'DROP INDEX "PSP_COMPANY_U1"';
	END IF;

END;

/

CREATE UNIQUE INDEX PSP_COMPANY_U1 ON PSP_COMPANY (SOURCE_COMPANY_ID, SOURCE_SYSTEM_CD)

/

DECLARE

	index_exists PLS_INTEGER;

BEGIN
	SELECT COUNT(*) INTO index_exists
	FROM "USER_INDEXES"
	WHERE INDEX_NAME = 'PSP_COMPANY_USAGE_U1';

	IF index_exists = 1 THEN
		EXECUTE IMMEDIATE 'DROP INDEX "PSP_COMPANY_USAGE_U1"';
	END IF;

END;

/

CREATE UNIQUE INDEX PSP_COMPANY_USAGE_U1 ON PSP_COMPANY_USAGE (SOURCE_COMPANY_ID, SOURCE_SYSTEM_CD, LICENSE_ID, ENTITLEMENT_ID)

/

DECLARE

	index_exists PLS_INTEGER;

BEGIN
	SELECT COUNT(*) INTO index_exists
	FROM "USER_INDEXES"
	WHERE INDEX_NAME = 'PSP_PAYROLL_RUN_I2';

	IF index_exists = 1 THEN
		EXECUTE IMMEDIATE 'DROP INDEX "PSP_PAYROLL_RUN_I2"';
	END IF;

END;

/

CREATE INDEX PSP_PAYROLL_RUN_I2 ON PSP_PAYROLL_RUN (USAGE_BILLING_TOKEN)

/

DECLARE

	index_exists PLS_INTEGER;

BEGIN
	SELECT COUNT(*) INTO index_exists
	FROM "USER_INDEXES"
	WHERE INDEX_NAME = 'PSP_BILL_U1';

	IF index_exists = 1 THEN
		EXECUTE IMMEDIATE 'DROP INDEX "PSP_BILL_U1"';
	END IF;

END;

/

CREATE UNIQUE INDEX PSP_BILL_U1 ON PSP_BILL (COMPANY_USAGE_FK, BILL_DATE)

/


DECLARE

	index_exists PLS_INTEGER;

BEGIN
	SELECT COUNT(*) INTO index_exists
	FROM "USER_INDEXES"
	WHERE INDEX_NAME = 'PSP_USAGE_PERIOD_U1';

	IF index_exists = 1 THEN
		EXECUTE IMMEDIATE 'DROP INDEX "PSP_USAGE_PERIOD_U1"';
	END IF;

END;

/

CREATE UNIQUE INDEX PSP_USAGE_PERIOD_U1 ON PSP_USAGE_PERIOD (COMPANY_USAGE_FK, START_DATE, END_DATE)

/


DECLARE

	index_exists PLS_INTEGER;

BEGIN
	SELECT COUNT(*) INTO index_exists
	FROM "USER_INDEXES"
	WHERE INDEX_NAME = 'PSP_EMPLOYEE_USAGE_U1';

	IF index_exists = 1 THEN
		EXECUTE IMMEDIATE 'DROP INDEX "PSP_EMPLOYEE_USAGE_U1"';
	END IF;

END;

/

CREATE UNIQUE INDEX PSP_EMPLOYEE_USAGE_U1 ON PSP_EMPLOYEE_USAGE (USAGE_PERIOD_FK, SOURCE_EMPLOYEE_ID)

/


DECLARE

	index_exists PLS_INTEGER;

BEGIN
	SELECT COUNT(*) INTO index_exists
	FROM "USER_INDEXES"
	WHERE INDEX_NAME = 'PSP_PAYCHECK_USAGE_U1';

	IF index_exists = 1 THEN
		EXECUTE IMMEDIATE 'DROP INDEX "PSP_PAYCHECK_USAGE_U1"';
	END IF;

END;

/

CREATE UNIQUE INDEX PSP_PAYCHECK_USAGE_U1 ON PSP_PAYCHECK_USAGE (EMPLOYEE_USAGE_FK, SOURCE_PAYCHECK_ID)

/

DECLARE

	index_exists PLS_INTEGER;

BEGIN
	SELECT COUNT(*) INTO index_exists
	FROM "USER_INDEXES"
	WHERE INDEX_NAME = 'PSP_COMPANY_I1';

	IF index_exists = 1 THEN
		EXECUTE IMMEDIATE 'DROP INDEX "PSP_COMPANY_I1"';
	END IF;

END;

/

CREATE INDEX PSP_COMPANY_I1 ON PSP_COMPANY (SOURCE_COMPANY_ID, LOWER(SOURCE_SYSTEM_CD))

/


DECLARE
	
	index_exists PLS_INTEGER;

BEGIN
	SELECT COUNT(*) INTO index_exists
	FROM "USER_INDEXES"
	WHERE INDEX_NAME = 'PSP_COMPANY_BANK_ACCOUNT_U1';

	IF index_exists = 1 THEN
		EXECUTE IMMEDIATE 'DROP INDEX "PSP_COMPANY_BANK_ACCOUNT_U1"';
	END IF;

END;

/
CREATE INDEX PSP_COMPANY_BANK_ACCOUNT_U1 ON PSP_COMPANY_BANK_ACCOUNT (SOURCE_BANK_ACCOUNT_ID, COMPANY_FK)


/
DECLARE
	
	index_exists PLS_INTEGER;

BEGIN
	SELECT COUNT(*) INTO index_exists
	FROM "USER_INDEXES"
	WHERE INDEX_NAME = 'PSP_EMPLOYEE_U1';

	IF index_exists = 1 THEN
		EXECUTE IMMEDIATE 'DROP INDEX "PSP_EMPLOYEE_U1"';
	END IF;

END;

/
CREATE UNIQUE INDEX PSP_EMPLOYEE_U1 ON PSP_EMPLOYEE (COMPANY_FK, SOURCE_EMPLOYEE_ID)


/
DECLARE
	
	index_exists PLS_INTEGER;

BEGIN
	SELECT COUNT(*) INTO index_exists
	FROM "USER_INDEXES"
	WHERE INDEX_NAME = 'PSP_EMPLOYEE_BANK_ACCOUNT_U1';

	IF index_exists = 1 THEN
		EXECUTE IMMEDIATE 'DROP INDEX "PSP_EMPLOYEE_BANK_ACCOUNT_U1"';
	END IF;

END;

/
CREATE INDEX PSP_EMPLOYEE_BANK_ACCOUNT_U1 ON PSP_EMPLOYEE_BANK_ACCOUNT (SOURCE_BANK_ACCOUNT_ID, EMPLOYEE_FK)



/
DECLARE
	
	index_exists PLS_INTEGER;

BEGIN
	SELECT COUNT(*) INTO index_exists
	FROM "USER_INDEXES"
	WHERE INDEX_NAME = 'PSP_PAYROLL_RUN_U1';

	IF index_exists = 1 THEN
		EXECUTE IMMEDIATE 'DROP INDEX "PSP_PAYROLL_RUN_U1"';
	END IF;

END;

/
CREATE UNIQUE INDEX PSP_PAYROLL_RUN_U1 ON PSP_PAYROLL_RUN (COMPANY_FK, SOURCE_PAY_RUN_ID)

/
DECLARE
	
	index_exists PLS_INTEGER;

BEGIN
	SELECT COUNT(*) INTO index_exists
	FROM "USER_INDEXES"
	WHERE INDEX_NAME = 'PSP_PAYROLL_RUN_I1';

	IF index_exists = 1 THEN
		EXECUTE IMMEDIATE 'DROP INDEX "PSP_PAYROLL_RUN_I1"';
	END IF;

END;

/
CREATE INDEX PSP_PAYROLL_RUN_I1 ON PSP_PAYROLL_RUN (COMPANY_FK, PAYCHECK_DATE)


/
DECLARE
	
	index_exists PLS_INTEGER;

BEGIN
	SELECT COUNT(*) INTO index_exists
	FROM "USER_INDEXES"
	WHERE INDEX_NAME = 'PSP_PAYCHECK_U1';

	IF index_exists = 1 THEN
		EXECUTE IMMEDIATE 'DROP INDEX "PSP_PAYCHECK_U1"';
	END IF;

END;

/
CREATE INDEX PSP_PAYCHECK_U1 ON PSP_PAYCHECK (SOURCE_PAYCHECK_ID, PAYROLL_RUN_FK)

/

DECLARE

	index_exists PLS_INTEGER;

BEGIN
	SELECT COUNT(*) INTO index_exists
	FROM "USER_INDEXES"
	WHERE INDEX_NAME = 'PSP_MAX_TOKEN_TEMP';

	IF index_exists = 1 THEN
		EXECUTE IMMEDIATE 'DROP INDEX "PSP_MAX_TOKEN_TEMP"';
	END IF;

END;

/

DECLARE
	
	index_exists PLS_INTEGER;

BEGIN
	SELECT COUNT(*) INTO index_exists
	FROM "USER_INDEXES"
	WHERE INDEX_NAME = 'PSP_PAYCHECK_SPLIT_U1';

	IF index_exists = 1 THEN
		EXECUTE IMMEDIATE 'DROP INDEX "PSP_PAYCHECK_SPLIT_U1"';
	END IF;

END;

/
CREATE UNIQUE INDEX PSP_PAYCHECK_SPLIT_U1 ON PSP_PAYCHECK_SPLIT (SOURCE_DD_TXN_ID, PAYCHECK_FK)

/
DECLARE
	
	index_exists PLS_INTEGER;

BEGIN
	SELECT COUNT(*) INTO index_exists
	FROM "USER_INDEXES"
	WHERE INDEX_NAME = 'PSP_FINANCIAL_TRANSACTION_I1';

	IF index_exists = 1 THEN
		EXECUTE IMMEDIATE 'DROP INDEX PSP_FINANCIAL_TRANSACTION_I1';
	END IF;

END;

/
CREATE INDEX PSP_FINANCIAL_TRANSACTION_I1 ON PSP_FINANCIAL_TRANSACTION (PAYROLL_RUN_FK, TRANSACTION_TYPE_FK, CURRENT_TRANSACTION_STATE_FK)


/
DECLARE

	index_exists PLS_INTEGER;

BEGIN
	SELECT COUNT(*) INTO index_exists
	FROM "USER_INDEXES"
	WHERE INDEX_NAME = 'PSP_BANK_ACCOUNT_I1';

	IF index_exists = 1 THEN
		EXECUTE IMMEDIATE 'DROP INDEX PSP_BANK_ACCOUNT_I1';
	END IF;

END;

/
CREATE INDEX PSP_BANK_ACCOUNT_I1 ON PSP_BANK_ACCOUNT (ROUTING_NUMBER, ACCOUNT_NUMBER_ENC)
/

DECLARE
	
	index_exists PLS_INTEGER;

BEGIN
	SELECT COUNT(*) INTO index_exists
	FROM "USER_INDEXES"
	WHERE INDEX_NAME = 'PSP_MM_TRANSACTION_I1';

	IF index_exists = 1 THEN
		EXECUTE IMMEDIATE 'DROP INDEX PSP_MM_TRANSACTION_I1';
	END IF;

END;

/
CREATE INDEX PSP_MM_TRANSACTION_I1 ON PSP_MONEY_MOVEMENT_TRANSACTION (COMPANY_FK, STATUS, INITIATION_DATE, DUE_DATE, MONEY_MOVEMENT_PAYMENT_METHOD)

/

DECLARE

	index_exists PLS_INTEGER;

BEGIN
	SELECT COUNT(*) INTO index_exists
	FROM "USER_INDEXES"
	WHERE INDEX_NAME = 'PSP_COMPANY_EVENT_I1';

	IF index_exists = 1 THEN
		EXECUTE IMMEDIATE 'DROP INDEX PSP_COMPANY_EVENT_I1';
	END IF;

END;

/
CREATE INDEX PSP_COMPANY_EVENT_I1 ON PSP_COMPANY_EVENT (COMPANY_FK, EVENT_TYPE_CD)
/


DECLARE

	index_exists PLS_INTEGER;

BEGIN
	SELECT COUNT(*) INTO index_exists
	FROM "USER_INDEXES"
	WHERE INDEX_NAME = 'PSP_LEDGER_BALANCE_U1';

	IF index_exists = 1 THEN
		EXECUTE IMMEDIATE 'DROP INDEX PSP_LEDGER_BALANCE_U1';
	END IF;

END;

/
CREATE INDEX PSP_LEDGER_BALANCE_U1 ON PSP_LEDGER_BALANCE (COMPANY_FK, LEDGER_ACCOUNT_FK, TRUNC(BALANCE_DATE))

/


DECLARE

	index_exists PLS_INTEGER;

BEGIN
	SELECT COUNT(*) INTO index_exists
	FROM "USER_INDEXES"
	WHERE INDEX_NAME = 'FN_STATE_EFF_DATE';

	IF index_exists = 1 THEN
		EXECUTE IMMEDIATE 'DROP INDEX FN_STATE_EFF_DATE';
	END IF;

END;

/
CREATE INDEX FN_STATE_EFF_DATE ON PSP_FINANCIAL_TRANS_STATE
(TRUNC(TRANSACTION_STATE_EFF_DATE))


/


DECLARE

	index_exists PLS_INTEGER;

BEGIN
	SELECT COUNT(*) INTO index_exists
	FROM "USER_INDEXES"
	WHERE INDEX_NAME = 'PSP_ENTRY_DETAIL_RECORD_I1 ';

	IF index_exists = 1 THEN
		EXECUTE IMMEDIATE 'DROP INDEX PSP_ENTRY_DETAIL_RECORD_I1 ';
	END IF;

END;

/
CREATE INDEX PSP_ENTRY_DETAIL_RECORD_I1 ON PSP_ENTRY_DETAIL_RECORD (TRACE_NUMBER) 

/


DECLARE

	index_exists PLS_INTEGER;

BEGIN
	SELECT COUNT(*) INTO index_exists
	FROM "USER_INDEXES"
	WHERE INDEX_NAME = 'PROPERTY_AUDIT_I1';

	IF index_exists = 1 THEN
		EXECUTE IMMEDIATE 'DROP INDEX PROPERTY_AUDIT_I1';
	END IF;

END;

/
CREATE INDEX PROPERTY_AUDIT_I1 ON PSP_PROPERTY_AUDIT (OBJECT_IDENTIFIER)
/

CREATE INDEX PSP_COMPANY_I5 ON PSP_COMPANY (LOWER(legal_name))
/

DECLARE
    
    index_exists PLS_INTEGER;

BEGIN
    SELECT COUNT(*) INTO index_exists
    FROM "USER_INDEXES"
	WHERE INDEX_NAME = 'PSP_ENTITLEMENT_U1';

	IF index_exists = 1 THEN
		EXECUTE IMMEDIATE 'DROP INDEX "PSP_ENTITLEMENT_U1"';
	END IF;

END;
/

CREATE UNIQUE INDEX PSP_ENTITLEMENT_U1 ON PSP_ENTITLEMENT (LICENSE_NUMBER, ENTITLEMENT_OFFERING_CODE)
/

DECLARE
    
    index_exists PLS_INTEGER;

BEGIN
    SELECT COUNT(*) INTO index_exists
    FROM "USER_INDEXES"
    WHERE INDEX_NAME = 'PSP_EMPLOYEE_BANK_ACCOUNT_I1';

    IF index_exists = 1 THEN
        EXECUTE IMMEDIATE 'DROP INDEX "PSP_EMPLOYEE_BANK_ACCOUNT_I1"';
    END IF;

END;
/

CREATE INDEX PSP_EMPLOYEE_BANK_ACCOUNT_I1 ON PSP_EMPLOYEE_BANK_ACCOUNT (MODIFIED_DATE)
/

DECLARE
    
    index_exists PLS_INTEGER;

BEGIN
    SELECT COUNT(*) INTO index_exists
    FROM "USER_INDEXES"
    WHERE INDEX_NAME = 'PSP_FRAUD_EVENT_I1';

    IF index_exists = 1 THEN
        EXECUTE IMMEDIATE 'DROP INDEX "PSP_FRAUD_EVENT_I1"';
    END IF;

END;
/

CREATE INDEX PSP_FRAUD_EVENT_I1 ON PSP_FRAUD_EVENT (EVENT_STATUS_CD, EVENT_TIME_STAMP)
/

DECLARE
    
    index_exists PLS_INTEGER;

BEGIN
    SELECT COUNT(*) INTO index_exists
    FROM "USER_INDEXES"
    WHERE INDEX_NAME = 'PSP_BILLING_DETAIL_BP1';

    IF index_exists = 1 THEN
        EXECUTE IMMEDIATE 'DROP INDEX "PSP_BILLING_DETAIL_BP1"';
    END IF;

END;
/

CREATE INDEX PSP_BILLING_DETAIL_BP1 ON PSP_BILLING_DETAIL (BILLING_PERIOD, OFFERING_SERVICE_CHARGE_TYPE)
/
