\i 'Type/record_type.sql'
\i 'Procedure/prc_achtransactionprocessor.sql'
\i 'Procedure/prc_calculate_ledger_balance.sql'
\i 'Procedure/prc_calculate_w2_totals.sql'
\i 'Procedure/prc_cost_co_plsql_jobs_processor.sql'
\i 'Procedure/prc_eftps_payments_events.sql'
\i 'Procedure/prc_eftps_payments_mmt_status.sql'
\i 'Procedure/prc_eftps_payments_response.sql'
\i 'Procedure/prc_eftps_payments_return.sql'
\i 'Procedure/prc_eftps_payments_sent_events.sql'
\i 'Procedure/prc_gems_accounts_receivable_assoc_fin_txn_states.sql'
\i 'Procedure/prc_gems_accounts_receivable_create_upload_batch.sql'
\i 'Procedure/prc_gems_accounts_receivable_supercede_upload_batch.sql'
\i 'Procedure/prc_eftps_payments_sent.sql'
\i 'Procedure/prc_offload_insert_fts.sql'
\i 'Procedure/prc_offload_upd_agency_status.sql'
\i 'Procedure/prc_offload_update_ft.sql'
\i 'Procedure/prc_offload_update_mmt.sql'
\i 'Procedure/prc_offload_update_payroll.sql'
\i 'Procedure/prc_offload.sql'
\i 'Procedure/prc_payroll_fraudBatch_purge_dbUpgrade_plsql_jobs_processor.sql'
\i 'Procedure/prc_payroll_item_totals_comp_qtr_payroll_item_tot.sql'
\i 'Procedure/prc_payroll_item_totals_qtr_payroll_item_tot.sql'
\i 'Procedure/prc_payroll_item_totals_year_payroll_item_tot.sql'
\i 'Procedure/prc_recalc_atf_payments_eftps.sql'
\i 'Procedure/prc_recalculate_atf_payments.sql'
\i 'Procedure/prc_remove_company_fast.sql'
\i 'Procedure/prc_set_psp_event_log.sql'
\i 'Procedure/prc_upd_company_ledger_balance.sql'
\i 'Procedure/prc_update_ledger_balance.sql'
\i 'Procedure/prc_update_nacha_file_trace_number.sql'

-- \i 'Package/pk_gems_accounts_receivable.sql'
-- \i 'Package/pk_payroll_item_totals.sql'