//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.31 at 03:14:25 PM PST 
//


package merlin.bedl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for BasicType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BasicType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Binary"/>
 *     &lt;enumeration value="Boolean"/>
 *     &lt;enumeration value="Date"/>
 *     &lt;enumeration value="Double"/>
 *     &lt;enumeration value="Integer"/>
 *     &lt;enumeration value="LargeText"/>
 *     &lt;enumeration value="Long"/>
 *     &lt;enumeration value="String"/>
 *     &lt;enumeration value="UniqueId"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum BasicType {

    @XmlEnumValue("Binary")
    BINARY("Binary"),
    @XmlEnumValue("Boolean")
    BOOLEAN("Boolean"),
    @XmlEnumValue("Date")
    DATE("Date"),
    @XmlEnumValue("Double")
    DOUBLE("Double"),
    @XmlEnumValue("Integer")
    INTEGER("Integer"),
    @XmlEnumValue("LargeText")
    LARGE_TEXT("LargeText"),
    @XmlEnumValue("Long")
    LONG("Long"),
    @XmlEnumValue("String")
    STRING("String"),
    @XmlEnumValue("UniqueId")
    UNIQUE_ID("UniqueId");
    private final String value;

    BasicType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BasicType fromValue(String v) {
        for (BasicType c: BasicType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
