//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.31 at 03:14:25 PM PST 
//


package merlin.bedl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataEntityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataEntityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Documentation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InternalNotes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Specializes" type="{http://www.intuit.com/IMM-BEDL-Schema}TypeReference" minOccurs="0"/>
 *         &lt;element name="Extends" type="{http://www.intuit.com/IMM-BEDL-Schema}TypeReference" minOccurs="0"/>
 *         &lt;element name="Properties" type="{http://www.intuit.com/IMM-BEDL-Schema}PropertiesList" minOccurs="0"/>
 *         &lt;element name="SortByProperties" type="{http://www.intuit.com/IMM-BEDL-Schema}SortOrderPropertyListType" minOccurs="0"/>
 *         &lt;element name="Methods" type="{http://www.intuit.com/IMM-BEDL-Schema}MethodList" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="AllowCustomization" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="AllowDynamicSpecialization" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="AllowExtension" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="AllowSpecialization" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="IsImmutable" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="IsPersisted" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="IsPublic" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Namespace" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SeedDataFile" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TableName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataEntityType", propOrder = {

})
public class DataEntityType {

    @XmlElement(name = "Documentation")
    protected String documentation;
    @XmlElement(name = "InternalNotes")
    protected String internalNotes;
    @XmlElement(name = "Specializes")
    protected TypeReference specializes;
    @XmlElement(name = "Extends")
    protected TypeReference _extends;
    @XmlElement(name = "Properties")
    protected PropertiesList properties;
    @XmlElement(name = "SortByProperties")
    protected SortOrderPropertyListType sortByProperties;
    @XmlElement(name = "Methods")
    protected MethodList methods;
    @XmlAttribute(name = "AllowCustomization")
    protected Boolean allowCustomization;
    @XmlAttribute(name = "AllowDynamicSpecialization")
    protected Boolean allowDynamicSpecialization;
    @XmlAttribute(name = "AllowExtension")
    protected Boolean allowExtension;
    @XmlAttribute(name = "AllowSpecialization")
    protected Boolean allowSpecialization;
    @XmlAttribute(name = "IsImmutable")
    protected Boolean isImmutable;
    @XmlAttribute(name = "IsPersisted")
    protected Boolean isPersisted;
    @XmlAttribute(name = "IsPublic")
    protected Boolean isPublic;
    @XmlAttribute(name = "Name", required = true)
    protected String name;
    @XmlAttribute(name = "Namespace")
    protected String namespace;
    @XmlAttribute(name = "SeedDataFile")
    protected String seedDataFile;
    @XmlAttribute(name = "TableName")
    protected String tableName;

    /**
     * Gets the value of the documentation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentation() {
        return documentation;
    }

    /**
     * Sets the value of the documentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentation(String value) {
        this.documentation = value;
    }

    /**
     * Gets the value of the internalNotes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternalNotes() {
        return internalNotes;
    }

    /**
     * Sets the value of the internalNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternalNotes(String value) {
        this.internalNotes = value;
    }

    /**
     * Gets the value of the specializes property.
     * 
     * @return
     *     possible object is
     *     {@link TypeReference }
     *     
     */
    public TypeReference getSpecializes() {
        return specializes;
    }

    /**
     * Sets the value of the specializes property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeReference }
     *     
     */
    public void setSpecializes(TypeReference value) {
        this.specializes = value;
    }

    /**
     * Gets the value of the extends property.
     * 
     * @return
     *     possible object is
     *     {@link TypeReference }
     *     
     */
    public TypeReference getExtends() {
        return _extends;
    }

    /**
     * Sets the value of the extends property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeReference }
     *     
     */
    public void setExtends(TypeReference value) {
        this._extends = value;
    }

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link PropertiesList }
     *     
     */
    public PropertiesList getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertiesList }
     *     
     */
    public void setProperties(PropertiesList value) {
        this.properties = value;
    }

    /**
     * Gets the value of the sortByProperties property.
     * 
     * @return
     *     possible object is
     *     {@link SortOrderPropertyListType }
     *     
     */
    public SortOrderPropertyListType getSortByProperties() {
        return sortByProperties;
    }

    /**
     * Sets the value of the sortByProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link SortOrderPropertyListType }
     *     
     */
    public void setSortByProperties(SortOrderPropertyListType value) {
        this.sortByProperties = value;
    }

    /**
     * Gets the value of the methods property.
     * 
     * @return
     *     possible object is
     *     {@link MethodList }
     *     
     */
    public MethodList getMethods() {
        return methods;
    }

    /**
     * Sets the value of the methods property.
     * 
     * @param value
     *     allowed object is
     *     {@link MethodList }
     *     
     */
    public void setMethods(MethodList value) {
        this.methods = value;
    }

    /**
     * Gets the value of the allowCustomization property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAllowCustomization() {
        if (allowCustomization == null) {
            return true;
        } else {
            return allowCustomization;
        }
    }

    /**
     * Sets the value of the allowCustomization property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowCustomization(Boolean value) {
        this.allowCustomization = value;
    }

    /**
     * Gets the value of the allowDynamicSpecialization property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAllowDynamicSpecialization() {
        if (allowDynamicSpecialization == null) {
            return true;
        } else {
            return allowDynamicSpecialization;
        }
    }

    /**
     * Sets the value of the allowDynamicSpecialization property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowDynamicSpecialization(Boolean value) {
        this.allowDynamicSpecialization = value;
    }

    /**
     * Gets the value of the allowExtension property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAllowExtension() {
        if (allowExtension == null) {
            return true;
        } else {
            return allowExtension;
        }
    }

    /**
     * Sets the value of the allowExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowExtension(Boolean value) {
        this.allowExtension = value;
    }

    /**
     * Gets the value of the allowSpecialization property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAllowSpecialization() {
        if (allowSpecialization == null) {
            return true;
        } else {
            return allowSpecialization;
        }
    }

    /**
     * Sets the value of the allowSpecialization property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowSpecialization(Boolean value) {
        this.allowSpecialization = value;
    }

    /**
     * Gets the value of the isImmutable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsImmutable() {
        if (isImmutable == null) {
            return false;
        } else {
            return isImmutable;
        }
    }

    /**
     * Sets the value of the isImmutable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsImmutable(Boolean value) {
        this.isImmutable = value;
    }

    /**
     * Gets the value of the isPersisted property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsPersisted() {
        if (isPersisted == null) {
            return true;
        } else {
            return isPersisted;
        }
    }

    /**
     * Sets the value of the isPersisted property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPersisted(Boolean value) {
        this.isPersisted = value;
    }

    /**
     * Gets the value of the isPublic property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsPublic() {
        if (isPublic == null) {
            return true;
        } else {
            return isPublic;
        }
    }

    /**
     * Sets the value of the isPublic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPublic(Boolean value) {
        this.isPublic = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the namespace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamespace() {
        return namespace;
    }

    /**
     * Sets the value of the namespace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamespace(String value) {
        this.namespace = value;
    }

    /**
     * Gets the value of the seedDataFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeedDataFile() {
        return seedDataFile;
    }

    /**
     * Sets the value of the seedDataFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeedDataFile(String value) {
        this.seedDataFile = value;
    }

    /**
     * Gets the value of the tableName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * Sets the value of the tableName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTableName(String value) {
        this.tableName = value;
    }

}
