//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.31 at 03:14:25 PM PST 
//


package merlin.bedl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Documentation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InternalNotes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="References" type="{http://www.intuit.com/IMM-BEDL-Schema}ModelReferenceList" minOccurs="0"/>
 *         &lt;element name="DataTypes" type="{http://www.intuit.com/IMM-BEDL-Schema}DataTypeList" minOccurs="0"/>
 *         &lt;element name="DataEntities" type="{http://www.intuit.com/IMM-BEDL-Schema}DataEntityList" minOccurs="0"/>
 *         &lt;element name="DataObjects" type="{http://www.intuit.com/IMM-BEDL-Schema}DataObjectList" minOccurs="0"/>
 *         &lt;element name="FunctionalAreas" type="{http://www.intuit.com/IMM-BEDL-Schema}FunctionalAreaList" minOccurs="0"/>
 *         &lt;element name="EntityInterfaces" type="{http://www.intuit.com/IMM-BEDL-Schema}EntityInterfaceList" minOccurs="0"/>
 *         &lt;element name="ServiceInterfaces" type="{http://www.intuit.com/IMM-BEDL-Schema}ServiceInterfaceList" minOccurs="0"/>
 *         &lt;element name="Relations" type="{http://www.intuit.com/IMM-BEDL-Schema}RelationList" minOccurs="0"/>
 *         &lt;element name="Enumerations" type="{http://www.intuit.com/IMM-BEDL-Schema}EnumerationsList" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="AssemblyName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="InheritanceMapping" type="{http://www.intuit.com/IMM-BEDL-Schema}InheritanceMappingType" default="TablePerHierarchy" />
 *       &lt;attribute name="MetaModelVersion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ModelAlias" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Namespace" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "DomainModel")
public class DomainModel {

    @XmlElement(name = "Documentation")
    protected String documentation;
    @XmlElement(name = "InternalNotes")
    protected String internalNotes;
    @XmlElement(name = "References")
    protected ModelReferenceList references;
    @XmlElement(name = "DataTypes")
    protected DataTypeList dataTypes;
    @XmlElement(name = "DataEntities")
    protected DataEntityList dataEntities;
    @XmlElement(name = "DataObjects")
    protected DataObjectList dataObjects;
    @XmlElement(name = "FunctionalAreas")
    protected FunctionalAreaList functionalAreas;
    @XmlElement(name = "EntityInterfaces")
    protected EntityInterfaceList entityInterfaces;
    @XmlElement(name = "ServiceInterfaces")
    protected ServiceInterfaceList serviceInterfaces;
    @XmlElement(name = "Relations")
    protected RelationList relations;
    @XmlElement(name = "Enumerations")
    protected EnumerationsList enumerations;
    @XmlAttribute(name = "AssemblyName")
    protected String assemblyName;
    @XmlAttribute(name = "InheritanceMapping")
    protected InheritanceMappingType inheritanceMapping;
    @XmlAttribute(name = "MetaModelVersion")
    protected String metaModelVersion;
    @XmlAttribute(name = "ModelAlias")
    protected String modelAlias;
    @XmlAttribute(name = "Name", required = true)
    protected String name;
    @XmlAttribute(name = "Namespace")
    protected String namespace;
    @XmlAttribute(name = "Version")
    protected String version;

    /**
     * Gets the value of the documentation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentation() {
        return documentation;
    }

    /**
     * Sets the value of the documentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentation(String value) {
        this.documentation = value;
    }

    /**
     * Gets the value of the internalNotes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternalNotes() {
        return internalNotes;
    }

    /**
     * Sets the value of the internalNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternalNotes(String value) {
        this.internalNotes = value;
    }

    /**
     * Gets the value of the references property.
     * 
     * @return
     *     possible object is
     *     {@link ModelReferenceList }
     *     
     */
    public ModelReferenceList getReferences() {
        return references;
    }

    /**
     * Sets the value of the references property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModelReferenceList }
     *     
     */
    public void setReferences(ModelReferenceList value) {
        this.references = value;
    }

    /**
     * Gets the value of the dataTypes property.
     * 
     * @return
     *     possible object is
     *     {@link DataTypeList }
     *     
     */
    public DataTypeList getDataTypes() {
        return dataTypes;
    }

    /**
     * Sets the value of the dataTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataTypeList }
     *     
     */
    public void setDataTypes(DataTypeList value) {
        this.dataTypes = value;
    }

    /**
     * Gets the value of the dataEntities property.
     * 
     * @return
     *     possible object is
     *     {@link DataEntityList }
     *     
     */
    public DataEntityList getDataEntities() {
        return dataEntities;
    }

    /**
     * Sets the value of the dataEntities property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataEntityList }
     *     
     */
    public void setDataEntities(DataEntityList value) {
        this.dataEntities = value;
    }

    /**
     * Gets the value of the dataObjects property.
     * 
     * @return
     *     possible object is
     *     {@link DataObjectList }
     *     
     */
    public DataObjectList getDataObjects() {
        return dataObjects;
    }

    /**
     * Sets the value of the dataObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataObjectList }
     *     
     */
    public void setDataObjects(DataObjectList value) {
        this.dataObjects = value;
    }

    /**
     * Gets the value of the functionalAreas property.
     * 
     * @return
     *     possible object is
     *     {@link FunctionalAreaList }
     *     
     */
    public FunctionalAreaList getFunctionalAreas() {
        return functionalAreas;
    }

    /**
     * Sets the value of the functionalAreas property.
     * 
     * @param value
     *     allowed object is
     *     {@link FunctionalAreaList }
     *     
     */
    public void setFunctionalAreas(FunctionalAreaList value) {
        this.functionalAreas = value;
    }

    /**
     * Gets the value of the entityInterfaces property.
     * 
     * @return
     *     possible object is
     *     {@link EntityInterfaceList }
     *     
     */
    public EntityInterfaceList getEntityInterfaces() {
        return entityInterfaces;
    }

    /**
     * Sets the value of the entityInterfaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityInterfaceList }
     *     
     */
    public void setEntityInterfaces(EntityInterfaceList value) {
        this.entityInterfaces = value;
    }

    /**
     * Gets the value of the serviceInterfaces property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceInterfaceList }
     *     
     */
    public ServiceInterfaceList getServiceInterfaces() {
        return serviceInterfaces;
    }

    /**
     * Sets the value of the serviceInterfaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceInterfaceList }
     *     
     */
    public void setServiceInterfaces(ServiceInterfaceList value) {
        this.serviceInterfaces = value;
    }

    /**
     * Gets the value of the relations property.
     * 
     * @return
     *     possible object is
     *     {@link RelationList }
     *     
     */
    public RelationList getRelations() {
        return relations;
    }

    /**
     * Sets the value of the relations property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationList }
     *     
     */
    public void setRelations(RelationList value) {
        this.relations = value;
    }

    /**
     * Gets the value of the enumerations property.
     * 
     * @return
     *     possible object is
     *     {@link EnumerationsList }
     *     
     */
    public EnumerationsList getEnumerations() {
        return enumerations;
    }

    /**
     * Sets the value of the enumerations property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnumerationsList }
     *     
     */
    public void setEnumerations(EnumerationsList value) {
        this.enumerations = value;
    }

    /**
     * Gets the value of the assemblyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssemblyName() {
        return assemblyName;
    }

    /**
     * Sets the value of the assemblyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssemblyName(String value) {
        this.assemblyName = value;
    }

    /**
     * Gets the value of the inheritanceMapping property.
     * 
     * @return
     *     possible object is
     *     {@link InheritanceMappingType }
     *     
     */
    public InheritanceMappingType getInheritanceMapping() {
        if (inheritanceMapping == null) {
            return InheritanceMappingType.TABLE_PER_HIERARCHY;
        } else {
            return inheritanceMapping;
        }
    }

    /**
     * Sets the value of the inheritanceMapping property.
     * 
     * @param value
     *     allowed object is
     *     {@link InheritanceMappingType }
     *     
     */
    public void setInheritanceMapping(InheritanceMappingType value) {
        this.inheritanceMapping = value;
    }

    /**
     * Gets the value of the metaModelVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetaModelVersion() {
        return metaModelVersion;
    }

    /**
     * Sets the value of the metaModelVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetaModelVersion(String value) {
        this.metaModelVersion = value;
    }

    /**
     * Gets the value of the modelAlias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelAlias() {
        return modelAlias;
    }

    /**
     * Sets the value of the modelAlias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelAlias(String value) {
        this.modelAlias = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the namespace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamespace() {
        return namespace;
    }

    /**
     * Sets the value of the namespace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamespace(String value) {
        this.namespace = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
