//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.31 at 03:14:25 PM PST 
//


package merlin.bedl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EntityInterfaceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EntityInterfaceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Documentation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InternalNotes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Properties" type="{http://www.intuit.com/IMM-BEDL-Schema}PropertiesList" minOccurs="0"/>
 *         &lt;element name="Methods" type="{http://www.intuit.com/IMM-BEDL-Schema}MethodList" minOccurs="0"/>
 *         &lt;element name="Specializes" type="{http://www.intuit.com/IMM-BEDL-Schema}TypeReference" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="BridgeClassName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="GenerateManagerInterface" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="ImplClassName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ManagerInterfaceName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Namespace" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SupportsCustomFields" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="SupportsDynamicSpecialization" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EntityInterfaceType", propOrder = {

})
public class EntityInterfaceType {

    @XmlElement(name = "Documentation")
    protected String documentation;
    @XmlElement(name = "InternalNotes")
    protected String internalNotes;
    @XmlElement(name = "Properties")
    protected PropertiesList properties;
    @XmlElement(name = "Methods")
    protected MethodList methods;
    @XmlElement(name = "Specializes")
    protected TypeReference specializes;
    @XmlAttribute(name = "BridgeClassName", required = true)
    protected String bridgeClassName;
    @XmlAttribute(name = "GenerateManagerInterface", required = true)
    protected boolean generateManagerInterface;
    @XmlAttribute(name = "ImplClassName", required = true)
    protected String implClassName;
    @XmlAttribute(name = "ManagerInterfaceName", required = true)
    protected String managerInterfaceName;
    @XmlAttribute(name = "Name", required = true)
    protected String name;
    @XmlAttribute(name = "Namespace")
    protected String namespace;
    @XmlAttribute(name = "SupportsCustomFields", required = true)
    protected boolean supportsCustomFields;
    @XmlAttribute(name = "SupportsDynamicSpecialization", required = true)
    protected boolean supportsDynamicSpecialization;

    /**
     * Gets the value of the documentation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentation() {
        return documentation;
    }

    /**
     * Sets the value of the documentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentation(String value) {
        this.documentation = value;
    }

    /**
     * Gets the value of the internalNotes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternalNotes() {
        return internalNotes;
    }

    /**
     * Sets the value of the internalNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternalNotes(String value) {
        this.internalNotes = value;
    }

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link PropertiesList }
     *     
     */
    public PropertiesList getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertiesList }
     *     
     */
    public void setProperties(PropertiesList value) {
        this.properties = value;
    }

    /**
     * Gets the value of the methods property.
     * 
     * @return
     *     possible object is
     *     {@link MethodList }
     *     
     */
    public MethodList getMethods() {
        return methods;
    }

    /**
     * Sets the value of the methods property.
     * 
     * @param value
     *     allowed object is
     *     {@link MethodList }
     *     
     */
    public void setMethods(MethodList value) {
        this.methods = value;
    }

    /**
     * Gets the value of the specializes property.
     * 
     * @return
     *     possible object is
     *     {@link TypeReference }
     *     
     */
    public TypeReference getSpecializes() {
        return specializes;
    }

    /**
     * Sets the value of the specializes property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeReference }
     *     
     */
    public void setSpecializes(TypeReference value) {
        this.specializes = value;
    }

    /**
     * Gets the value of the bridgeClassName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBridgeClassName() {
        return bridgeClassName;
    }

    /**
     * Sets the value of the bridgeClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBridgeClassName(String value) {
        this.bridgeClassName = value;
    }

    /**
     * Gets the value of the generateManagerInterface property.
     * 
     */
    public boolean isGenerateManagerInterface() {
        return generateManagerInterface;
    }

    /**
     * Sets the value of the generateManagerInterface property.
     * 
     */
    public void setGenerateManagerInterface(boolean value) {
        this.generateManagerInterface = value;
    }

    /**
     * Gets the value of the implClassName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImplClassName() {
        return implClassName;
    }

    /**
     * Sets the value of the implClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImplClassName(String value) {
        this.implClassName = value;
    }

    /**
     * Gets the value of the managerInterfaceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManagerInterfaceName() {
        return managerInterfaceName;
    }

    /**
     * Sets the value of the managerInterfaceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManagerInterfaceName(String value) {
        this.managerInterfaceName = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the namespace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamespace() {
        return namespace;
    }

    /**
     * Sets the value of the namespace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamespace(String value) {
        this.namespace = value;
    }

    /**
     * Gets the value of the supportsCustomFields property.
     * 
     */
    public boolean isSupportsCustomFields() {
        return supportsCustomFields;
    }

    /**
     * Sets the value of the supportsCustomFields property.
     * 
     */
    public void setSupportsCustomFields(boolean value) {
        this.supportsCustomFields = value;
    }

    /**
     * Gets the value of the supportsDynamicSpecialization property.
     * 
     */
    public boolean isSupportsDynamicSpecialization() {
        return supportsDynamicSpecialization;
    }

    /**
     * Sets the value of the supportsDynamicSpecialization property.
     * 
     */
    public void setSupportsDynamicSpecialization(boolean value) {
        this.supportsDynamicSpecialization = value;
    }

}
