//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.31 at 03:14:25 PM PST 
//


package merlin.bedl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FunctionalAreaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FunctionalAreaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Documentation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InternalNotes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Atoms" type="{http://www.intuit.com/IMM-BEDL-Schema}AtomList" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="BridgeClassName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ImplClassName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Namespace" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FunctionalAreaType", propOrder = {

})
public class FunctionalAreaType {

    @XmlElement(name = "Documentation")
    protected String documentation;
    @XmlElement(name = "InternalNotes")
    protected String internalNotes;
    @XmlElement(name = "Atoms")
    protected AtomList atoms;
    @XmlAttribute(name = "BridgeClassName")
    protected String bridgeClassName;
    @XmlAttribute(name = "ImplClassName")
    protected String implClassName;
    @XmlAttribute(name = "Name", required = true)
    protected String name;
    @XmlAttribute(name = "Namespace")
    protected String namespace;

    /**
     * Gets the value of the documentation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentation() {
        return documentation;
    }

    /**
     * Sets the value of the documentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentation(String value) {
        this.documentation = value;
    }

    /**
     * Gets the value of the internalNotes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternalNotes() {
        return internalNotes;
    }

    /**
     * Sets the value of the internalNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternalNotes(String value) {
        this.internalNotes = value;
    }

    /**
     * Gets the value of the atoms property.
     * 
     * @return
     *     possible object is
     *     {@link AtomList }
     *     
     */
    public AtomList getAtoms() {
        return atoms;
    }

    /**
     * Sets the value of the atoms property.
     * 
     * @param value
     *     allowed object is
     *     {@link AtomList }
     *     
     */
    public void setAtoms(AtomList value) {
        this.atoms = value;
    }

    /**
     * Gets the value of the bridgeClassName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBridgeClassName() {
        return bridgeClassName;
    }

    /**
     * Sets the value of the bridgeClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBridgeClassName(String value) {
        this.bridgeClassName = value;
    }

    /**
     * Gets the value of the implClassName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImplClassName() {
        return implClassName;
    }

    /**
     * Sets the value of the implClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImplClassName(String value) {
        this.implClassName = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the namespace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamespace() {
        return namespace;
    }

    /**
     * Sets the value of the namespace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamespace(String value) {
        this.namespace = value;
    }

}
