//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.31 at 03:14:25 PM PST 
//


package merlin.bedl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for InheritanceMappingType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="InheritanceMappingType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="TablePerHierarchy"/>
 *     &lt;enumeration value="TablePerSubclass"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum InheritanceMappingType {

    @XmlEnumValue("TablePerHierarchy")
    TABLE_PER_HIERARCHY("TablePerHierarchy"),
    @XmlEnumValue("TablePerSubclass")
    TABLE_PER_SUBCLASS("TablePerSubclass");
    private final String value;

    InheritanceMappingType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static InheritanceMappingType fromValue(String v) {
        for (InheritanceMappingType c: InheritanceMappingType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
