//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.31 at 03:14:25 PM PST 
//


package merlin.bedl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MultiplicityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MultiplicityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SortByProperties" type="{http://www.intuit.com/IMM-BEDL-Schema}SortOrderPropertyListType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="CollectionContainerType" type="{http://www.w3.org/2001/XMLSchema}string" default="list" />
 *       &lt;attribute name="LowerBound" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;attribute name="UpperBound" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MultiplicityType", propOrder = {
    "sortByProperties"
})
public class MultiplicityType {

    @XmlElement(name = "SortByProperties")
    protected SortOrderPropertyListType sortByProperties;
    @XmlAttribute(name = "CollectionContainerType")
    protected String collectionContainerType;
    @XmlAttribute(name = "LowerBound")
    protected Short lowerBound;
    @XmlAttribute(name = "UpperBound", required = true)
    protected String upperBound;

    /**
     * Gets the value of the sortByProperties property.
     * 
     * @return
     *     possible object is
     *     {@link SortOrderPropertyListType }
     *     
     */
    public SortOrderPropertyListType getSortByProperties() {
        return sortByProperties;
    }

    /**
     * Sets the value of the sortByProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link SortOrderPropertyListType }
     *     
     */
    public void setSortByProperties(SortOrderPropertyListType value) {
        this.sortByProperties = value;
    }

    /**
     * Gets the value of the collectionContainerType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCollectionContainerType() {
        if (collectionContainerType == null) {
            return "list";
        } else {
            return collectionContainerType;
        }
    }

    /**
     * Sets the value of the collectionContainerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCollectionContainerType(String value) {
        this.collectionContainerType = value;
    }

    /**
     * Gets the value of the lowerBound property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getLowerBound() {
        return lowerBound;
    }

    /**
     * Sets the value of the lowerBound property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setLowerBound(Short value) {
        this.lowerBound = value;
    }

    /**
     * Gets the value of the upperBound property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpperBound() {
        return upperBound;
    }

    /**
     * Sets the value of the upperBound property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpperBound(String value) {
        this.upperBound = value;
    }

}
