//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.31 at 03:14:25 PM PST 
//


package merlin.bedl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the merlin.bedl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: merlin.bedl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EnumerationFieldType }
     * 
     */
    public EnumerationFieldType createEnumerationFieldType() {
        return new EnumerationFieldType();
    }

    /**
     * Create an instance of {@link MethodList }
     * 
     */
    public MethodList createMethodList() {
        return new MethodList();
    }

    /**
     * Create an instance of {@link DataTypeDefinition }
     * 
     */
    public DataTypeDefinition createDataTypeDefinition() {
        return new DataTypeDefinition();
    }

    /**
     * Create an instance of {@link TypeReference }
     * 
     */
    public TypeReference createTypeReference() {
        return new TypeReference();
    }

    /**
     * Create an instance of {@link EnumerationType }
     * 
     */
    public EnumerationType createEnumerationType() {
        return new EnumerationType();
    }

    /**
     * Create an instance of {@link PropertyDefinition }
     * 
     */
    public PropertyDefinition createPropertyDefinition() {
        return new PropertyDefinition();
    }

    /**
     * Create an instance of {@link EntityInterfaceList }
     * 
     */
    public EntityInterfaceList createEntityInterfaceList() {
        return new EntityInterfaceList();
    }

    /**
     * Create an instance of {@link EnumerationsList }
     * 
     */
    public EnumerationsList createEnumerationsList() {
        return new EnumerationsList();
    }

    /**
     * Create an instance of {@link FunctionalAreaList }
     * 
     */
    public FunctionalAreaList createFunctionalAreaList() {
        return new FunctionalAreaList();
    }

    /**
     * Create an instance of {@link DataEntityList }
     * 
     */
    public DataEntityList createDataEntityList() {
        return new DataEntityList();
    }

    /**
     * Create an instance of {@link ModelReferenceList }
     * 
     */
    public ModelReferenceList createModelReferenceList() {
        return new ModelReferenceList();
    }

    /**
     * Create an instance of {@link DataObjectList }
     * 
     */
    public DataObjectList createDataObjectList() {
        return new DataObjectList();
    }

    /**
     * Create an instance of {@link PropertiesList }
     * 
     */
    public PropertiesList createPropertiesList() {
        return new PropertiesList();
    }

    /**
     * Create an instance of {@link MethodParameter }
     * 
     */
    public MethodParameter createMethodParameter() {
        return new MethodParameter();
    }

    /**
     * Create an instance of {@link EnumerationFieldsList }
     * 
     */
    public EnumerationFieldsList createEnumerationFieldsList() {
        return new EnumerationFieldsList();
    }

    /**
     * Create an instance of {@link AtomList }
     * 
     */
    public AtomList createAtomList() {
        return new AtomList();
    }

    /**
     * Create an instance of {@link MethodDefinition }
     * 
     */
    public MethodDefinition createMethodDefinition() {
        return new MethodDefinition();
    }

    /**
     * Create an instance of {@link ServiceInterfaceList }
     * 
     */
    public ServiceInterfaceList createServiceInterfaceList() {
        return new ServiceInterfaceList();
    }

    /**
     * Create an instance of {@link ModelReference }
     * 
     */
    public ModelReference createModelReference() {
        return new ModelReference();
    }

    /**
     * Create an instance of {@link SortOrderPropertyListType }
     * 
     */
    public SortOrderPropertyListType createSortOrderPropertyListType() {
        return new SortOrderPropertyListType();
    }

    /**
     * Create an instance of {@link FunctionalAreaType }
     * 
     */
    public FunctionalAreaType createFunctionalAreaType() {
        return new FunctionalAreaType();
    }

    /**
     * Create an instance of {@link RelationDefinition }
     * 
     */
    public RelationDefinition createRelationDefinition() {
        return new RelationDefinition();
    }

    /**
     * Create an instance of {@link DataEntityType }
     * 
     */
    public DataEntityType createDataEntityType() {
        return new DataEntityType();
    }

    /**
     * Create an instance of {@link MultiplicityType }
     * 
     */
    public MultiplicityType createMultiplicityType() {
        return new MultiplicityType();
    }

    /**
     * Create an instance of {@link DataTypeList }
     * 
     */
    public DataTypeList createDataTypeList() {
        return new DataTypeList();
    }

    /**
     * Create an instance of {@link EntityInterfaceType }
     * 
     */
    public EntityInterfaceType createEntityInterfaceType() {
        return new EntityInterfaceType();
    }

    /**
     * Create an instance of {@link AtomDefinition }
     * 
     */
    public AtomDefinition createAtomDefinition() {
        return new AtomDefinition();
    }

    /**
     * Create an instance of {@link RelationEndType }
     * 
     */
    public RelationEndType createRelationEndType() {
        return new RelationEndType();
    }

    /**
     * Create an instance of {@link DomainModel }
     * 
     */
    public DomainModel createDomainModel() {
        return new DomainModel();
    }

    /**
     * Create an instance of {@link ParameterList }
     * 
     */
    public ParameterList createParameterList() {
        return new ParameterList();
    }

    /**
     * Create an instance of {@link ServiceInterfaceType }
     * 
     */
    public ServiceInterfaceType createServiceInterfaceType() {
        return new ServiceInterfaceType();
    }

    /**
     * Create an instance of {@link RelationList }
     * 
     */
    public RelationList createRelationList() {
        return new RelationList();
    }

    /**
     * Create an instance of {@link DataObjectType }
     * 
     */
    public DataObjectType createDataObjectType() {
        return new DataObjectType();
    }

}
