//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.31 at 03:14:25 PM PST 
//


package merlin.bedl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for ParameterDirection.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ParameterDirection">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="In"/>
 *     &lt;enumeration value="InOut"/>
 *     &lt;enumeration value="Out"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum ParameterDirection {

    @XmlEnumValue("In")
    IN("In"),
    @XmlEnumValue("InOut")
    IN_OUT("InOut"),
    @XmlEnumValue("Out")
    OUT("Out");
    private final String value;

    ParameterDirection(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ParameterDirection fromValue(String v) {
        for (ParameterDirection c: ParameterDirection.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
