//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.31 at 03:14:25 PM PST 
//


package merlin.bedl;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PropertyDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PropertyDefinition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Documentation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InternalNotes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Multiplicity" type="{http://www.intuit.com/IMM-BEDL-Schema}MultiplicityType" minOccurs="0"/>
 *         &lt;element name="Type" type="{http://www.intuit.com/IMM-BEDL-Schema}TypeReference"/>
 *         &lt;element name="InitialValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MinimumValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MaximumValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RegularExpression" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Calculation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ColumnName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="HandcodedAccessorType" use="required" type="{http://www.intuit.com/IMM-BEDL-Schema}HandcodedAccessorType" />
 *       &lt;attribute name="IsCalculated" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="IsIndexed" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="IsPersisted" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="IsReadOnly" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="IsUnique" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="Length" type="{http://www.w3.org/2001/XMLSchema}integer" default="255" />
 *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Precision" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="Scale" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="SecurityLevel" type="{http://www.intuit.com/IMM-BEDL-Schema}DataClassificationType" default="Unclassified" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PropertyDefinition", propOrder = {
    "documentation",
    "internalNotes",
    "multiplicity",
    "type",
    "initialValue",
    "minimumValue",
    "maximumValue",
    "regularExpression",
    "calculation"
})
public class PropertyDefinition {

    @XmlElement(name = "Documentation")
    protected String documentation;
    @XmlElement(name = "InternalNotes")
    protected String internalNotes;
    @XmlElement(name = "Multiplicity")
    protected MultiplicityType multiplicity;
    @XmlElement(name = "Type", required = true)
    protected TypeReference type;
    @XmlElement(name = "InitialValue")
    protected String initialValue;
    @XmlElement(name = "MinimumValue")
    protected String minimumValue;
    @XmlElement(name = "MaximumValue")
    protected String maximumValue;
    @XmlElement(name = "RegularExpression")
    protected String regularExpression;
    @XmlElement(name = "Calculation")
    protected String calculation;
    @XmlAttribute(name = "ColumnName")
    protected String columnName;
    @XmlAttribute(name = "HandcodedAccessorType", required = true)
    protected HandcodedAccessorType handcodedAccessorType;
    @XmlAttribute(name = "IsCalculated")
    protected Boolean isCalculated;
    @XmlAttribute(name = "IsIndexed")
    protected Boolean isIndexed;
    @XmlAttribute(name = "IsPersisted")
    protected Boolean isPersisted;
    @XmlAttribute(name = "IsReadOnly")
    protected Boolean isReadOnly;
    @XmlAttribute(name = "IsUnique")
    protected Boolean isUnique;
    @XmlAttribute(name = "Length")
    protected BigInteger length;
    @XmlAttribute(name = "Name", required = true)
    protected String name;
    @XmlAttribute(name = "Precision")
    protected BigInteger precision;
    @XmlAttribute(name = "Scale")
    protected BigInteger scale;
    @XmlAttribute(name = "SecurityLevel")
    protected DataClassificationType securityLevel;

    /**
     * Gets the value of the documentation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentation() {
        return documentation;
    }

    /**
     * Sets the value of the documentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentation(String value) {
        this.documentation = value;
    }

    /**
     * Gets the value of the internalNotes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternalNotes() {
        return internalNotes;
    }

    /**
     * Sets the value of the internalNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternalNotes(String value) {
        this.internalNotes = value;
    }

    /**
     * Gets the value of the multiplicity property.
     * 
     * @return
     *     possible object is
     *     {@link MultiplicityType }
     *     
     */
    public MultiplicityType getMultiplicity() {
        return multiplicity;
    }

    /**
     * Sets the value of the multiplicity property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiplicityType }
     *     
     */
    public void setMultiplicity(MultiplicityType value) {
        this.multiplicity = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link TypeReference }
     *     
     */
    public TypeReference getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeReference }
     *     
     */
    public void setType(TypeReference value) {
        this.type = value;
    }

    /**
     * Gets the value of the initialValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitialValue() {
        return initialValue;
    }

    /**
     * Sets the value of the initialValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitialValue(String value) {
        this.initialValue = value;
    }

    /**
     * Gets the value of the minimumValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinimumValue() {
        return minimumValue;
    }

    /**
     * Sets the value of the minimumValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinimumValue(String value) {
        this.minimumValue = value;
    }

    /**
     * Gets the value of the maximumValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaximumValue() {
        return maximumValue;
    }

    /**
     * Sets the value of the maximumValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaximumValue(String value) {
        this.maximumValue = value;
    }

    /**
     * Gets the value of the regularExpression property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegularExpression() {
        return regularExpression;
    }

    /**
     * Sets the value of the regularExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegularExpression(String value) {
        this.regularExpression = value;
    }

    /**
     * Gets the value of the calculation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCalculation() {
        return calculation;
    }

    /**
     * Sets the value of the calculation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCalculation(String value) {
        this.calculation = value;
    }

    /**
     * Gets the value of the columnName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * Sets the value of the columnName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColumnName(String value) {
        this.columnName = value;
    }

    /**
     * Gets the value of the handcodedAccessorType property.
     * 
     * @return
     *     possible object is
     *     {@link HandcodedAccessorType }
     *     
     */
    public HandcodedAccessorType getHandcodedAccessorType() {
        return handcodedAccessorType;
    }

    /**
     * Sets the value of the handcodedAccessorType property.
     * 
     * @param value
     *     allowed object is
     *     {@link HandcodedAccessorType }
     *     
     */
    public void setHandcodedAccessorType(HandcodedAccessorType value) {
        this.handcodedAccessorType = value;
    }

    /**
     * Gets the value of the isCalculated property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsCalculated() {
        if (isCalculated == null) {
            return false;
        } else {
            return isCalculated;
        }
    }

    /**
     * Sets the value of the isCalculated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsCalculated(Boolean value) {
        this.isCalculated = value;
    }

    /**
     * Gets the value of the isIndexed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsIndexed() {
        if (isIndexed == null) {
            return false;
        } else {
            return isIndexed;
        }
    }

    /**
     * Sets the value of the isIndexed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsIndexed(Boolean value) {
        this.isIndexed = value;
    }

    /**
     * Gets the value of the isPersisted property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsPersisted() {
        if (isPersisted == null) {
            return true;
        } else {
            return isPersisted;
        }
    }

    /**
     * Sets the value of the isPersisted property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPersisted(Boolean value) {
        this.isPersisted = value;
    }

    /**
     * Gets the value of the isReadOnly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsReadOnly() {
        if (isReadOnly == null) {
            return false;
        } else {
            return isReadOnly;
        }
    }

    /**
     * Sets the value of the isReadOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsReadOnly(Boolean value) {
        this.isReadOnly = value;
    }

    /**
     * Gets the value of the isUnique property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsUnique() {
        if (isUnique == null) {
            return false;
        } else {
            return isUnique;
        }
    }

    /**
     * Sets the value of the isUnique property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsUnique(Boolean value) {
        this.isUnique = value;
    }

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLength() {
        if (length == null) {
            return new BigInteger("255");
        } else {
            return length;
        }
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLength(BigInteger value) {
        this.length = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the precision property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPrecision() {
        return precision;
    }

    /**
     * Sets the value of the precision property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPrecision(BigInteger value) {
        this.precision = value;
    }

    /**
     * Gets the value of the scale property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getScale() {
        return scale;
    }

    /**
     * Sets the value of the scale property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setScale(BigInteger value) {
        this.scale = value;
    }

    /**
     * Gets the value of the securityLevel property.
     * 
     * @return
     *     possible object is
     *     {@link DataClassificationType }
     *     
     */
    public DataClassificationType getSecurityLevel() {
        if (securityLevel == null) {
            return DataClassificationType.UNCLASSIFIED;
        } else {
            return securityLevel;
        }
    }

    /**
     * Sets the value of the securityLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataClassificationType }
     *     
     */
    public void setSecurityLevel(DataClassificationType value) {
        this.securityLevel = value;
    }

}
