//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.31 at 03:14:25 PM PST 
//


package merlin.bedl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RelationDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RelationDefinition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Source" type="{http://www.intuit.com/IMM-BEDL-Schema}RelationEndType"/>
 *         &lt;element name="Target" type="{http://www.intuit.com/IMM-BEDL-Schema}RelationEndType"/>
 *       &lt;/all>
 *       &lt;attribute name="Direction" use="required" type="{http://www.intuit.com/IMM-BEDL-Schema}RelationDirectionType" />
 *       &lt;attribute name="TableName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Type" use="required" type="{http://www.intuit.com/IMM-BEDL-Schema}RelationType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RelationDefinition", propOrder = {

})
public class RelationDefinition {

    @XmlElement(name = "Source", required = true)
    protected RelationEndType source;
    @XmlElement(name = "Target", required = true)
    protected RelationEndType target;
    @XmlAttribute(name = "Direction", required = true)
    protected RelationDirectionType direction;
    @XmlAttribute(name = "TableName")
    protected String tableName;
    @XmlAttribute(name = "Type", required = true)
    protected RelationType type;

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link RelationEndType }
     *     
     */
    public RelationEndType getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationEndType }
     *     
     */
    public void setSource(RelationEndType value) {
        this.source = value;
    }

    /**
     * Gets the value of the target property.
     * 
     * @return
     *     possible object is
     *     {@link RelationEndType }
     *     
     */
    public RelationEndType getTarget() {
        return target;
    }

    /**
     * Sets the value of the target property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationEndType }
     *     
     */
    public void setTarget(RelationEndType value) {
        this.target = value;
    }

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link RelationDirectionType }
     *     
     */
    public RelationDirectionType getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationDirectionType }
     *     
     */
    public void setDirection(RelationDirectionType value) {
        this.direction = value;
    }

    /**
     * Gets the value of the tableName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * Sets the value of the tableName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTableName(String value) {
        this.tableName = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link RelationType }
     *     
     */
    public RelationType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationType }
     *     
     */
    public void setType(RelationType value) {
        this.type = value;
    }

}
