DROP TABLE IF EXISTS TEMP_PSP_SYSTEM_CAPABILITY CASCADE

;

--------------------------------------------------------
-- Create temp table                                  --
--------------------------------------------------------
CREATE TABLE TEMP_PSP_SYSTEM_CAPABILITY (LIKE PSP_SYSTEM_CAPABILITY INCLUDING ALL)

;

--------------------------------------------------------
-- Insert into temp table                             --
--------------------------------------------------------
INSERT INTO TEMP_PSP_SYSTEM_CAPABILITY ( SYSTEM_CAPABILITY_CD, DESCRIPTION, VERSION)  VALUES (
'AddService', NULL , 0)
;
INSERT INTO TEMP_PSP_SYSTEM_CAPABILITY ( SYSTEM_CAPABILITY_CD, DESCRIPTION, VERSION)  VALUES (
'CancelService', NULL, 0)
;
INSERT INTO TEMP_PSP_SYSTEM_CAPABILITY ( SYSTEM_CAPABILITY_CD, DESCRIPTION, VERSION)  VALUES (
'ChangeCompanyInfo', NULL, 0)
;
INSERT INTO TEMP_PSP_SYSTEM_CAPABILITY ( SYSTEM_CAPABILITY_CD, DESCRIPTION, VERSION)  VALUES (
'ChangeEmployeeBankAccount', NULL, 0)
;
INSERT INTO TEMP_PSP_SYSTEM_CAPABILITY ( SYSTEM_CAPABILITY_CD, DESCRIPTION, VERSION)  VALUES (
'ChangeEmployerBankAccount', NULL, 0)
;
INSERT INTO TEMP_PSP_SYSTEM_CAPABILITY ( SYSTEM_CAPABILITY_CD, DESCRIPTION, VERSION)  VALUES (
'AddEmployerBankAccount', NULL, 0)
;
INSERT INTO TEMP_PSP_SYSTEM_CAPABILITY ( SYSTEM_CAPABILITY_CD, DESCRIPTION, VERSION)  VALUES (
'VerifyCompanyBankAccount', NULL, 0)
;
INSERT INTO TEMP_PSP_SYSTEM_CAPABILITY ( SYSTEM_CAPABILITY_CD, DESCRIPTION, VERSION)  VALUES (
'RefundOrCredit', NULL, 0)
;
INSERT INTO TEMP_PSP_SYSTEM_CAPABILITY ( SYSTEM_CAPABILITY_CD, DESCRIPTION, VERSION)  VALUES (
'SubmitPayroll', NULL, 0)
;
INSERT INTO TEMP_PSP_SYSTEM_CAPABILITY ( SYSTEM_CAPABILITY_CD, DESCRIPTION, VERSION)  VALUES (
'SynchronizeAccount', NULL, 0)
;
INSERT INTO TEMP_PSP_SYSTEM_CAPABILITY ( SYSTEM_CAPABILITY_CD, DESCRIPTION, VERSION)  VALUES (
'UpgradeFundingModel', NULL, 0)
;
INSERT INTO TEMP_PSP_SYSTEM_CAPABILITY ( SYSTEM_CAPABILITY_CD, DESCRIPTION, VERSION)  VALUES (
'RecallPayroll', NULL, 0)
;
INSERT INTO TEMP_PSP_SYSTEM_CAPABILITY ( SYSTEM_CAPABILITY_CD, DESCRIPTION, VERSION)  VALUES (
'UpdatePIN', NULL, 0)
;
INSERT INTO TEMP_PSP_SYSTEM_CAPABILITY ( SYSTEM_CAPABILITY_CD, DESCRIPTION, VERSION)  VALUES (
'VoidPayroll', NULL, 0)
;
INSERT INTO TEMP_PSP_SYSTEM_CAPABILITY ( SYSTEM_CAPABILITY_CD, DESCRIPTION, VERSION)  VALUES (
'SubmitPayment', NULL, 0)
;
INSERT INTO TEMP_PSP_SYSTEM_CAPABILITY ( SYSTEM_CAPABILITY_CD, DESCRIPTION, VERSION)  VALUES (
'RecallPayment', NULL, 0)
;
--------------------------------------------------------
-- Sychronize temp table and real table by            --
-- inserting, deleting, and updating as necessary     --
--------------------------------------------------------

INSERT INTO PSP_SYSTEM_CAPABILITY
   (SYSTEM_CAPABILITY_CD, DESCRIPTION, VERSION)
SELECT
    SYSTEM_CAPABILITY_CD, DESCRIPTION, VERSION
FROM
   TEMP_PSP_SYSTEM_CAPABILITY sc
WHERE
   sc.SYSTEM_CAPABILITY_CD NOT IN (SELECT SYSTEM_CAPABILITY_CD FROM PSP_SYSTEM_CAPABILITY)

;

-- delete children first
DELETE FROM PSP_SVCSTAT_SYSCAP_ASSOC
WHERE SYSTEM_CAPABILITY_FK NOT IN (SELECT SYSTEM_CAPABILITY_CD FROM TEMP_PSP_SYSTEM_CAPABILITY)

;

DELETE FROM PSP_SYSTEM_CAPABILITY
WHERE SYSTEM_CAPABILITY_CD NOT IN (SELECT SYSTEM_CAPABILITY_CD FROM TEMP_PSP_SYSTEM_CAPABILITY)

;

UPDATE PSP_SYSTEM_CAPABILITY rt
SET ( DESCRIPTION, VERSION) =
(SELECT sc.DESCRIPTION, sc.VERSION
 FROM TEMP_PSP_SYSTEM_CAPABILITY sc WHERE sc.SYSTEM_CAPABILITY_CD = rt.SYSTEM_CAPABILITY_CD)
;



--------------------------------------------------------
-- Drop temp table                                  --
--------------------------------------------------------
DROP TABLE TEMP_PSP_SYSTEM_CAPABILITY

;
COMMIT



