\timing
set search_path to ibobadm;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012016_from_dflt  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062010_from_dflt  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072010_from_psp  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032020_from_qbdt  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092013_from_qbdt  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072021_from_null  ;
vacuum (analyze, verbose) ibobadm.psp_qbdt_request_info  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062013_from_dflt  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012012_from_qbdt  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052021_from_dflt  ;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022021_from_qbdt  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022012_from_psp  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012013_from_psp  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012013_from_cris  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012013_from_null  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012013_from_as400  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052021_from_as400  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012013_from_qbdt  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032012_from_null  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012015_from_as400  ;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012017_from_qbdt  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012017_from_null  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012021_from_ews  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082019_from_null  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012019_from_dflt  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082019_from_psp  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052020_from_qbdt  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022020_from_null  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082017_from_as400  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102015_from_dflt  ;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052020_from_cris  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122010_from_dflt  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062019_from_ews  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082009_from_dflt  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102009_from_ews  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062019_from_cris  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122009_from_dflt  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042010_from_ews  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032019_from_psp  ;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042020_from_as400  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042019_from_as400  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092009_from_psp  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122009_from_as400  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122017_from_ews  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052010_from_ews  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102010_from_null  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072009_from_qbdt  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112009_from_null  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052020_from_null  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082010_from_dflt  ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092009_from_qbdt  ;
