\timing
set search_path to ibobadm;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m022014_from_ews;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m022014_from_null;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m082011_from_ews;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m082011_from_psp;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m082011_from_null;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m082011_from_cris;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m082011_from_qbdt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m082011_from_dflt;
SELECT pg_sleep(60);
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m102011_from_psp;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m032014_from_qbdt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m032014_from_null;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m072011_from_qbdt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m102011_from_cris;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m042011_from_as400;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m102011_from_dflt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m012014_from_as400;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m102011_from_ews;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m042011_from_cris;
SELECT pg_sleep(60);
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m032014_from_as400;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m032014_from_ews;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m032014_from_dflt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m102011_from_null;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m032014_from_cris;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m032014_from_psp;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m102011_from_qbdt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m012018_from_as400;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m012018_from_cris;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m012018_from_ews;
SELECT pg_sleep(60);
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m122011_from_psp;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m012018_from_dflt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m122011_from_dflt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m112011_from_as400;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m112011_from_dflt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m112011_from_cris;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m112011_from_psp;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m012018_from_null;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m112011_from_ews;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m112011_from_qbdt;
SELECT pg_sleep(60);
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m112011_from_null;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m012018_from_psp;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m012018_from_qbdt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m122011_from_cris;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m122011_from_as400;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m122011_from_qbdt;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m122011_from_null;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m122011_from_ews;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m052014_from_ews;
vacuum (analyze, verbose)  ibobadm.psp_source_system_transmission_m052014_from_qbdt;
