nohup ./run_on_ppsp--stg-olap.sh pspadm_analyze_1.sql > pspadm_analyze_pstolap_1.log &
nohup ./run_on_ppsp--stg-olap.sh pspadm_analyze_2.sql > pspadm_analyze_pstolap_2.log &
nohup ./run_on_ppsp--stg-olap.sh pspadm_analyze_3.sql > pspadm_analyze_pstolap_3.log &
nohup ./run_on_ppsp--stg-olap.sh pspadm_analyze_4.sql > pspadm_analyze_pstolap_4.log &
nohup ./run_on_ppsp--stg-olap.sh pspadm_analyze_5.sql > pspadm_analyze_pstolap_5.log &
nohup ./run_on_ppsp--stg-olap.sh pspadm_analyze_nonpart_1.sql > pspadm_analyze_nonpart_pstolap_1.log &
nohup ./run_on_ppsp--stg-olap.sh pspadm_analyze_nonpart_2.sql > pspadm_analyze_nonpart_pstolap_2.log &
nohup ./run_on_ppsp--stg-olap.sh pspadm_analyze_nonpart_3.sql > pspadm_analyze_nonpart_pstolap_3.log &
nohup ./run_on_ppsp--stg-olap.sh pspadm_analyze_nonpart_4.sql > pspadm_analyze_nonpart_pstolap_4.log &
