\timing
set search_path to ibobadm;

vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012016_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042012_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122021_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032021_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052021_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102021_from_cris;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092013_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072021_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022013_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072021_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022013_from_dflt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042017_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072016_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042010_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102013_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082010_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082010_from_cris;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082010_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042015_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102021_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092017_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112009_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072009_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042013_from_dflt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092009_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072021_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082009_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052017_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102009_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082009_from_null;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102010_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102010_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112016_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082017_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042016_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042016_from_qbdt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092017_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032017_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102009_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042010_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082019_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042010_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052020_from_dflt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022019_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112010_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042020_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062010_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022012_from_null;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102017_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092016_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072013_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012020_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032021_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082013_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102017_from_dflt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102016_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102013_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012017_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122016_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062021_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022017_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062017_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062015_from_ews;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082012_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092012_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102021_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092012_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072015_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082013_from_psp;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032016_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082016_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122012_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112021_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092022_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_9999_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102022_from_cris;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122012_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_9999_from_psp;
vacuum (analyze, verbose) ibobadm.psp_hcm401k_policy;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022022_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122022_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022022_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012022_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012022_from_as400;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_9999_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_9999_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022022_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102022_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_9999_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012022_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022022_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112022_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032022_from_null;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122022_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012022_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_9999_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122022_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032022_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112022_from_as400;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112022_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092022_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032022_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032022_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102022_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102022_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112022_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122022_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092022_from_as400;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_9999_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092022_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122015_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112015_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052016_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102015_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022022_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032022_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012022_from_qbdt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022022_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012022_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032022_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022022_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012022_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032022_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102022_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092022_from_qbdt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102022_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092022_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102022_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092022_from_psp;
SELECT pg_sleep(60);
vacuum (analyze, verbose) pg_largeobject;
vacuum (analyze, verbose) pg_shdepend;
vacuum (analyze, verbose) gg_heartbeat;
vacuum (analyze, verbose) public.awsdms_ddl_audit;
vacuum (analyze, verbose) ibobadm.psp_hcm401k_employee_deduction;
vacuum (analyze, verbose) awsdms_control_table.awsdms_suspended_tables;
vacuum (analyze, verbose) awsdms_control_table.awsdms_full_load_exceptions;
vacuum (analyze, verbose) awsdms_control_table.awsdms_status;
