\timing
set search_path to ibobadm;

vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102015_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042021_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112013_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112012_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022016_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012020_from_cris;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012020_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042019_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012020_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022020_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022010_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032010_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082012_from_dflt;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032010_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022019_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122016_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102012_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102012_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012016_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112013_from_as400;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052019_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072010_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122019_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052010_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042020_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122010_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032016_from_cris;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102013_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122015_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122012_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122012_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122012_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122021_from_as400;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012012_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032016_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042021_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112015_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072013_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122021_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032019_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042019_from_ews;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072013_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122021_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012012_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032017_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092021_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022012_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112012_from_as400;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122017_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062016_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112013_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012015_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062021_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112021_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012015_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112013_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022013_from_cris;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072013_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052019_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072016_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042019_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032016_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102012_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042020_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082021_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092009_from_null;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052016_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112016_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062012_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122013_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122010_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072016_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042016_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122013_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032012_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102016_from_null;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122013_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072016_from_as400;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072021_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112012_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122013_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022012_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042019_from_psp;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082021_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012020_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072016_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032016_from_dflt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032015_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122017_from_as400;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022016_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092017_from_cris;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092020_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052019_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022020_from_cris;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092021_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042020_from_ews;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052017_from_psp;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092021_from_null;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072015_from_qbdt;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082016_from_dflt;
