\timing
set search_path to ibobadm;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122009_from_psp ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042019_from_null ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102009_from_as400 ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052015_from_qbdt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022017_from_qbdt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082020_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112009_from_psp ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022019_from_psp ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092019_from_as400 ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082013_from_dflt ;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052020_from_as400 ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112017_from_qbdt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012021_from_as400 ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072012_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012016_from_as400 ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012015_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122016_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042021_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042012_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052019_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092017_from_dflt ;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092013_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062015_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032021_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032015_from_qbdt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032012_from_psp ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082021_from_as400 ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052016_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082017_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022021_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012016_from_null ;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082013_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062020_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062020_from_as400 ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062020_from_psp ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062020_from_qbdt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042021_from_null ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102015_from_as400 ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102015_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092015_from_as400 ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102019_from_psp ;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062019_from_as400 ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032020_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102019_from_qbdt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062013_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022013_from_null ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102013_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062013_from_psp ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062013_from_qbdt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112012_from_psp ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052013_from_dflt ;

