\timing
set search_path to ibobadm;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112012_from_qbdt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022012_from_qbdt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m122021_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042012_from_as400 ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012016_from_qbdt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032021_from_as400 ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052021_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102021_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092013_from_psp ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072021_from_ews ;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072021_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042017_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072016_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022013_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022013_from_psp ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102013_from_null ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042010_from_qbdt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082010_from_null ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082010_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082010_from_as400 ;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042015_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102021_from_psp ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072009_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042013_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112009_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092017_from_qbdt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072021_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082009_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092009_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052017_from_dflt ;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102009_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082009_from_null ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102010_from_psp ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102010_from_qbdt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042016_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112016_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082017_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042016_from_qbdt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092017_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032017_from_null ;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102009_from_qbdt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042010_from_as400 ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022012_from_null ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042010_from_psp ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m042020_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m022019_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m112010_from_as400 ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m052020_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m062010_from_cris ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082019_from_ews ;
SELECT pg_sleep(60);
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102017_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m092016_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m072013_from_psp ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012020_from_as400 ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m032021_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m082013_from_qbdt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102017_from_dflt ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102016_from_ews ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m102013_from_psp ;
vacuum (analyze, verbose) ibobadm.psp_source_system_transmission_m012017_from_psp ;

