package com.intuit.sbd.payroll.psp.adapters.ade.mapping;

import java.util.HashMap;
import java.util.Map;

/**
 * Created with IntelliJ IDEA.
 * User: shivanandad069
 * Date: 9/27/13
 * Time: 5:17 AM
 * To change this template use File | Settings | File Templates.
 */
public class AgencyIdMapper {
    //Mapping if agencyids in PSP to agencyids mapped in CEP/AED
    private static final Map<String, String> PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP = new HashMap<String, String>();
    private static final Map<String, String> COMPLIANCE_AGENCY_ID_TO_PSP_AGENCY_ID_MAP = new HashMap<String, String>();


    static {
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("IRS", "US_FEDERAL_IRS");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("AKDLWD", "US_AK_DLWD");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("ALDIR", "US_AL_DIR");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("ALDOR", "US_AL_DOR");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("ARDFA", "US_AR_DFA");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("ARESD", "US_AR_ESD");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("AZDES", "US_AZ_DES");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("AZDOR", "US_AZ_DOR");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("CAEDD", "US_CA_EDD");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("CODFMLI", "US_CO_DFMLI");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("CODLE", "US_CO_DLE");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("CODOR", "US_CO_DOR");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("CTDOL", "US_CT_DOL");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("CTDRS", "US_CT_DRS");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("DCDES", "US_DC_DES");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("DCOTR", "US_DC_OTR");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("DEDFR", "US_DE_DFR");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("DEDOL", "US_DE_DOL");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("FLDOR", "US_FL_DOR");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("GADOL", "US_GA_DOL");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("GADOR", "US_GA_DOR");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("HIDLIR", "US_HI_DLIR");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("HIDOT", "US_HI_DOT");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("IADOR", "US_IA_DOR");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("IAWD", "US_IA_WD");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("IDCL", "US_ID_CL");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("IDSTC", "US_ID_STC");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("ILDES", "US_IL_DES");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("ILDOR", "US_IL_DOR");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("INDOR", "US_IN_DOR");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("INDWD", "US_IN_DWD");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("KSDOL", "US_KS_DOL");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("KSDOR", "US_KS_DOR");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("KYDES", "US_KY_DES");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("KYDOR", "US_KY_DOR");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("LADOL", "US_LA_DOL");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("LADOR", "US_LA_DOR");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("MADOR", "US_MA_DOR");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("MAWUA", "US_MA_WUA");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("MDOUI", "US_MD_OUI");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("MDRAD", "US_MD_RAD");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("MERS", "US_ME_RS");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("MEUITD", "US_ME_UITD");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("MIDLEG", "US_MI_DLEG");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("MIDOT", "US_MI_DOT");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("MNDOR", "US_MN_DOR");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("MNEEUI", "US_MN_EEUI");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("MODES", "US_MO_DES");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("MODOR", "US_MO_DOR");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("MSDES", "US_MS_DES");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("MSSTC", "US_MS_STC");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("MTDOR", "US_MT_DOR");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("MTUID", "US_MT_UID");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("NCDOR", "US_NC_DOR");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("NCESC", "US_NC_ESC");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("NDJS", "US_ND_JS");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("NDSTC", "US_ND_STC");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("NEDOR", "US_NE_DOR");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("NEWD", "US_NE_WD");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("NHES", "US_NH_ES");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("NJDLWD", "US_NJ_DLWD");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("NJT", "US_NJ_T");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("NMDOL", "US_NM_DOL");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("NMTRD", "US_NM_TRD");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("NVETR", "US_NV_ETR");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("NYDOL", "US_NY_DOL");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("NYDTF", "US_NY_DTF");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("NYMCT", "US_NY_MCT");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("NYSIF", "US_NY_SIF");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("OHDOT", "US_OH_DOT");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("OHJFS", "US_OH_JFS");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("OKESC", "US_OK_ESC");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("OKTC", "US_OK_TC");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("ORDOR", "US_OR_DOR");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("PADLI", "US_PA_DLI");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("PADOR", "US_PA_DOR");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("RIDOT", "US_RI_DOT");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("SCDOR", "US_SC_DOR");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("SCESC", "US_SC_ESC");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("SDUID", "US_SD_UID");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("TNDOL", "US_TN_DOL");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("TXWC", "US_TX_WC");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("UTDWS", "US_UT_DWS");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("UTTC", "US_UT_TC");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("VADOT", "US_VA_DOT");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("VAEC", "US_VA_EC");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("VTDOL", "US_VT_DOL");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("VTDOT", "US_VT_DOT");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("WAESD", "US_WA_ESD");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("WIDOR", "US_WI_DOR");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("WIDWD", "US_WI_DWD");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("WVBEP", "US_WV_BEP");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("WVSTD", "US_WV_STD");
        PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.put("WYDOE", "US_WY_DOE");


        // reverse map
        for (String pspAgencyId : PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.keySet()) {
            COMPLIANCE_AGENCY_ID_TO_PSP_AGENCY_ID_MAP.put(PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.get(pspAgencyId), pspAgencyId);
        }
    }

    public static String getPSPAgencyIdByComplianceAgencyId(String complianceAgencyId) {
        return COMPLIANCE_AGENCY_ID_TO_PSP_AGENCY_ID_MAP.get(complianceAgencyId);
    }

    public static String getComplianceAgencyIdByPSPAgencyId(String pspAgencyId) {
        return PSP_AGENCY_ID_TO_COMPLIANCE_AGENCY_ID_MAP.get(pspAgencyId);
    }

}

