package com.intuit.sbd.payroll.psp.adapters.ade.mapping;

import java.util.HashMap;
import java.util.Map;
import java.util.Set;

/**
 * Created with IntelliJ IDEA.
 * User: shivanandad069
 * Date: 10/1/13
 * Time: 4:35 AM
 * To change this template use File | Settings | File Templates.
 */
public class TaxPaymentGroupIdMapper {
    private static final Map<String, String> PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP = new HashMap<String, String>();
    private static final Map<String, String> COMPLIANCE_TAXPAYGROUPID_TO_P1SP_PAYMENTTEMPLATE_CD_MAP = new HashMap<String, String>();


    static {

        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("IRS-940-PAYMENT", "US_IRS_940_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("IRS-941-PAYMENT", "US_IRS_941_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("177-NOCALC", "US_177_NOCALC");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("9-NOCALC", "US_9_NOCALC");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("AK-AKNS-PAYMENT", "US_AK_AKNS_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("AK-NOCALC", "US_AK_NOCALC");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("AL-CR4UI-PAYMENT", "US_AL_CR4UI_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("AL-CR4WH-PAYMENT", "US_AL_CR4WH_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("AL-NOCALC", "US_AL_NOCALC");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("AR-209B-PAYMENT", "US_AR_209B_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("AR-941M-PAYMENT", "US_AR_941M_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("AZ-A1-PAYMENT", "US_AZ_A1_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("AZ-NOCALC", "US_AZ_NOCALC");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("AZ-UC018-PAYMENT", "US_AZ_UC018_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("CA-NOCALC", "US_CA_NOCALC");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("CA-PITSDI-PAYMENT", "US_CA_PITSDI_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("CA-UIETT-PAYMENT", "US_CA_UIETT_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("CO-DR1094-PAYMENT", "US_CO_DR1094_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("CO-NOCALC", "US_CO_NOCALC");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("CO-UITR1-PAYMENT", "US_CO_UITR1_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("CT-2MAG-PAYMENT", "US_CT_2MAG_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("CT-CTWH-PAYMENT", "US_CT_CTWH_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("DC-FR900-PAYMENT", "US_DC_FR900_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("DC-NOCALC", "US_DC_NOCALC");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("DC-UC30-PAYMENT", "US_DC_UC30_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("DE-DES-PAYMENT", "US_DE_DES_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("DE-UC8-PAYMENT", "US_DE_UC8_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("FL-NOCALC", "US_FL_NOCALC");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("FL-UCT6-PAYMENT", "US_FL_UCT6_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("GA-DOL4-PAYMENT", "US_GA_DOL4_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("GA-GAV-PAYMENT", "US_GA_GAV_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("GA-NOCALC", "US_GA_NOCALC");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("HI-NOCALC", "US_HI_NOCALC");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("HI-UCB6-PAYMENT", "US_HI_UCB6_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("HI-VP1-PAYMENT", "US_HI_VP1_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("IA-44105-PAYMENT", "US_IA_44105_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("IA-600103-PAYMENT", "US_IA_600103_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("ID-020-PAYMENT", "US_ID_020_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("ID-910-PAYMENT", "US_ID_910_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("IL-501-PAYMENT", "US_IL_501_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("IL-NOCALC", "US_IL_NOCALC");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("IL-UI340-PAYMENT", "US_IL_UI340_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("IN-UC1-PAYMENT", "US_IN_UC1_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("IN-WH1-PAYMENT", "US_IN_WH1_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("KS-CNS100-PAYMENT", "US_KS_CNS100_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("KS-KCNS100-PAYMENT", "US_KS_KCNS100_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("KS-KW5-PAYMENT", "US_KS_KW5_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("KY-K1-PAYMENT", "US_KY_K1_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("KY-NOCALC", "US_KY_NOCALC");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("KY-UI3-PAYMENT", "US_KY_UI3_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("LA-ES61-PAYMENT", "US_LA_ES61_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("LA-L1-PAYMENT", "US_LA_L1_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("LA-NOCALC", "US_LA_NOCALC");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("MA-1700HI-PAYMENT", "US_MA_1700HI_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("MA-M941-PAYMENT", "US_MA_M941_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("MA-NOCALC", "US_MA_NOCALC");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("MD-DLLR-PAYMENT", "US_MD_DLLR_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("MD-MW506-PAYMENT", "US_MD_MW506_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("MD-NOCALC", "US_MD_NOCALC");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("ME-900ME-PAYMENT", "US_ME_900ME_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("ME-941C1ME-PAYMENT", "US_ME_941C1ME_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("ME-NOCALC", "US_ME_NOCALC");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("MI-MW106-PAYMENT", "US_MI_MW106_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("MI-NOCALC", "US_MI_NOCALC");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("MI-UIA1020-PAYMENT", "US_MI_UIA1020_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("MN-DEED1-PAYMENT", "US_MN_DEED1_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("MN-MW1-PAYMENT", "US_MN_MW1_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("MN_UI", "US_MN_UI");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("MN_WH", "US_MN_WH");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("MO-941-PAYMENT", "US_MO_941_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("MO-MODES-PAYMENT", "US_MO_MODES_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("MO-NOCALC", "US_MO_NOCALC");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("MS-M89-PAYMENT", "US_MS_M89_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("MS-UI23-PAYMENT", "US_MS_UI23_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("MT-MW1-PAYMENT", "US_MT_MW1_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("MT-NOCALC", "US_MT_NOCALC");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("MT-UI5-PAYMENT", "US_MT_UI5_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("NC-101-PAYMENT", "US_NC_101_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("NC-NC5P-PAYMENT", "US_NC_NC5P_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("NC-NOCALC", "US_NC_NOCALC");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("ND-306-PAYMENT", "US_ND_306_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("ND-SFN41263-PAYMENT", "US_ND_SFN41263_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("NE-941N-PAYMENT", "US_NE_941N_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("NE-UI11T-PAYMENT", "US_NE_UI11T_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("NH-DES200-PAYMENT", "US_NH_DES200_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("NH-NOCALC", "US_NH_NOCALC");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("NJ-NJ500-PAYMENT", "US_NJ_NJ500_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("NJ-NJ500UI-PAYMENT", "US_NJ_NJ500UI_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("NJ-NJ927PUI-PAYMENT", "US_NJ_NJ927PUI_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("NJ-NJ927PWH-PAYMENT", "US_NJ_NJ927PWH_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("NM-CRS1-PAYMENT", "US_NM_CRS1_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("NM-ES903A-PAYMENT", "US_NM_ES903A_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("NM-NOCALC", "US_NM_NOCALC");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("NM-WC1-PAYMENT", "US_NM_WC1_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("NV-NOCALC", "US_NV_NOCALC");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("NV-NUCS4072-PAYMENT", "US_NV_NUCS4072_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("NY-1MN-PAYMENT", "US_NY_1MN_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("NY-45MN-PAYMENT", "US_NY_45MN_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("NY-MTA305-PAYMENT", "US_NY_MTA305_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("NY-NOCALC", "US_NY_NOCALC");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("NY-SDI-PAYMENT", "US_NY_SDI_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("OH-IT501-PAYMENT", "US_OH_IT501_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("OH-JFS20127-PAYMENT", "US_OH_JFS20127_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("OH-JFS66111-PAYMENT", "US_OH_JFS66111_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("OH-SD101-PAYMENT", "US_OH_SD101_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("OK-NOCALC", "US_OK_NOCALC");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("OK-OES3-PAYMENT", "US_OK_OES3_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("OK-OW9A-PAYMENT", "US_OK_OW9A_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("OR-NOCALC", "US_OR_NOCALC");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("OR-OTCUI-PAYMENT", "US_OR_OTCUI_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("OR-OTCWH-PAYMENT", "US_OR_OTCWH_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("PA-501-PAYMENT", "US_PA_501_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("PA-UC2-PAYMENT", "US_PA_UC2_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("PR-NOCALC", "US_PR_NOCALC");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("RI-941-PAYMENT", "US_RI_941_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("RI-NOCALC", "US_RI_NOCALC");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("RI-TX17-PAYMENT", "US_RI_TX17_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("SC-UCE120-PAYMENT", "US_SC_UCE120_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("SC-WH1601-PAYMENT", "US_SC_WH1601_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("SD-NOCALC", "US_SD_NOCALC");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("SD-UID21-PAYMENT", "US_SD_UID21_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("TN-LB0456-PAYMENT", "US_TN_LB0456_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("TN-NOCALC", "US_TN_NOCALC");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("TX-C3V-PAYMENT", "US_TX_C3V_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("TX-NOCALC", "US_TX_NOCALC");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("UT-F3-PAYMENT", "US_UT_F3_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("UT-TC96-PAYMENT", "US_UT_TC96_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("VA-FC20-PAYMENT", "US_VA_FC20_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("VA-NOCALC", "US_VA_NOCALC");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("VA-VA15-PAYMENT", "US_VA_VA15_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("VT-C101-PAYMENT", "US_VT_C101_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("VT-NOCALC", "US_VT_NOCALC");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("VT-WH433-PAYMENT", "US_VT_WH433_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("WA-F5208-PAYMENT", "US_WA_F5208_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("WA-NOCALC", "US_WA_NOCALC");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("WI-UCT101-PAYMENT", "US_WI_UCT101_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("WI-WT6-PAYMENT", "US_WI_WT6_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("WV-A154-PAYMENT", "US_WV_A154_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("WV-IT101-PAYMENT", "US_WV_IT101_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("WY-NOCALC", "US_WY_NOCALC");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("WY-WYO056-PAYMENT", "US_WY_WYO056_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("DC-PFL-PAYMENT", "US_DC_PFL_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("MA-PFML-PAYMENT", "US_MA_PFML_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("CT-PFML-PAYMENT", "US_CT-PFML-PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("WA-CARES-PAYMENT", "US_WA_CARES_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("OR-PFMSL-PAYMENT", "US_OR_PFMSL_PAYMENT");
        PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.put("CO-FAMLI-PAYMENT", "US_CO_FAMLI_PAYMENT");

        // reverse map
        for (String complianceTaxItemId : PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.keySet()) {
            COMPLIANCE_TAXPAYGROUPID_TO_P1SP_PAYMENTTEMPLATE_CD_MAP.put(PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.get(complianceTaxItemId), complianceTaxItemId);
        }
    }

    public static String getComplianceTaxPayGroupIdByPSPPaymentTemplateCd(String pspPaymentTemplateCd) {
        return PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.get(pspPaymentTemplateCd);
    }

    public static String getPSPPaymentTemplateCdByComplianceTaxPayGroupIdId(String complianceTaxPayGroupId) {
        return COMPLIANCE_TAXPAYGROUPID_TO_P1SP_PAYMENTTEMPLATE_CD_MAP.get(complianceTaxPayGroupId);
    }


    public static Set<String> getAllComplianceTaxItemIds() {
        return COMPLIANCE_TAXPAYGROUPID_TO_P1SP_PAYMENTTEMPLATE_CD_MAP.keySet();
    }
    public static Set<String> getAllPSPPaymentTemplateCds() {
        return PSP_PAYMENTTEMPLATE_CD_TO_COMPLIANCE_TAXPAYGROUPID_MAP.keySet();
    }
}
