DELETE FROM PSP_AUTH_ROLE_TASK_VAL; 
 
DELETE FROM PSP_AUTH_TASK_OPERATION_VAL; 
 
DELETE FROM PSP_AUTH_GLOBAL_USER_APP_ASSOC; 

DELETE FROM PSP_AUTH_GLOVAL_USR_ROLE_ASSOC; 

DELETE FROM PSP_AUTH_OPERATION_VAL; 
 
DELETE FROM PSP_AUTH_TASK_VAL;

DELETE FROM PSP_AUTH_ROLE; 

DELETE FROM PSP_LDAP_USER; 
 
DELETE FROM PSP_AUTH_GLOBAL_USER; 

DELETE FROM PSP_AUTH_APPLICATION; 
 
DELETE FROM PSP_AUTH_DOMAIN;

commit;
