\timing
set search_path=pspadm;
SELECT CURRENT_TIMESTAMP;


select 'creating index on psp_financial_trans_state' as status;
create index fn_state_eff_date_p0 on pspadm.psp_financial_trans_state_p0 USING BTREE (date(transaction_state_eff_date) ASC);
create index fn_state_eff_date_p1 on pspadm.psp_financial_trans_state_p1 USING BTREE (date(transaction_state_eff_date) ASC);
create index fn_state_eff_date_p10 on pspadm.psp_financial_trans_state_p10 USING BTREE (date(transaction_state_eff_date) ASC);
create index fn_state_eff_date_p11 on pspadm.psp_financial_trans_state_p11 USING BTREE (date(transaction_state_eff_date) ASC);
create index fn_state_eff_date_p12 on pspadm.psp_financial_trans_state_p12 USING BTREE (date(transaction_state_eff_date) ASC);
create index fn_state_eff_date_p13 on pspadm.psp_financial_trans_state_p13 USING BTREE (date(transaction_state_eff_date) ASC);
create index fn_state_eff_date_p14 on pspadm.psp_financial_trans_state_p14 USING BTREE (date(transaction_state_eff_date) ASC);
create index fn_state_eff_date_p15 on pspadm.psp_financial_trans_state_p15 USING BTREE (date(transaction_state_eff_date) ASC);
create index fn_state_eff_date_p2 on pspadm.psp_financial_trans_state_p2 USING BTREE (date(transaction_state_eff_date) ASC);
create index fn_state_eff_date_p3 on pspadm.psp_financial_trans_state_p3 USING BTREE (date(transaction_state_eff_date) ASC);
create index fn_state_eff_date_p4 on pspadm.psp_financial_trans_state_p4 USING BTREE (date(transaction_state_eff_date) ASC);
create index fn_state_eff_date_p5 on pspadm.psp_financial_trans_state_p5 USING BTREE (date(transaction_state_eff_date) ASC);
create index fn_state_eff_date_p6 on pspadm.psp_financial_trans_state_p6 USING BTREE (date(transaction_state_eff_date) ASC);
create index fn_state_eff_date_p7 on pspadm.psp_financial_trans_state_p7 USING BTREE (date(transaction_state_eff_date) ASC);
create index fn_state_eff_date_p8 on pspadm.psp_financial_trans_state_p8 USING BTREE (date(transaction_state_eff_date) ASC);
create index fn_state_eff_date_p9 on pspadm.psp_financial_trans_state_p9 USING BTREE (date(transaction_state_eff_date) ASC);
create index psp_financial_trans_state_fk4_p0 on pspadm.psp_financial_trans_state_p0 USING BTREE (gems_upload_batch_fk ASC);
create index psp_financial_trans_state_fk4_p1 on pspadm.psp_financial_trans_state_p1 USING BTREE (gems_upload_batch_fk ASC);
create index psp_financial_trans_state_fk4_p10 on pspadm.psp_financial_trans_state_p10 USING BTREE (gems_upload_batch_fk ASC);
create index psp_financial_trans_state_fk4_p11 on pspadm.psp_financial_trans_state_p11 USING BTREE (gems_upload_batch_fk ASC);
create index psp_financial_trans_state_fk4_p12 on pspadm.psp_financial_trans_state_p12 USING BTREE (gems_upload_batch_fk ASC);
create index psp_financial_trans_state_fk4_p13 on pspadm.psp_financial_trans_state_p13 USING BTREE (gems_upload_batch_fk ASC);
create index psp_financial_trans_state_fk4_p14 on pspadm.psp_financial_trans_state_p14 USING BTREE (gems_upload_batch_fk ASC);
create index psp_financial_trans_state_fk4_p15 on pspadm.psp_financial_trans_state_p15 USING BTREE (gems_upload_batch_fk ASC);
create index psp_financial_trans_state_fk4_p2 on pspadm.psp_financial_trans_state_p2 USING BTREE (gems_upload_batch_fk ASC);
create index psp_financial_trans_state_fk4_p3 on pspadm.psp_financial_trans_state_p3 USING BTREE (gems_upload_batch_fk ASC);
create index psp_financial_trans_state_fk4_p4 on pspadm.psp_financial_trans_state_p4 USING BTREE (gems_upload_batch_fk ASC);
create index psp_financial_trans_state_fk4_p5 on pspadm.psp_financial_trans_state_p5 USING BTREE (gems_upload_batch_fk ASC);
create index psp_financial_trans_state_fk4_p6 on pspadm.psp_financial_trans_state_p6 USING BTREE (gems_upload_batch_fk ASC);
create index psp_financial_trans_state_fk4_p7 on pspadm.psp_financial_trans_state_p7 USING BTREE (gems_upload_batch_fk ASC);
create index psp_financial_trans_state_fk4_p8 on pspadm.psp_financial_trans_state_p8 USING BTREE (gems_upload_batch_fk ASC);
create index psp_financial_trans_state_fk4_p9 on pspadm.psp_financial_trans_state_p9 USING BTREE (gems_upload_batch_fk ASC);
create index psp_financial_trans_state_fk5_p0 on pspadm.psp_financial_trans_state_p0 USING BTREE (company_fk ASC,financial_transaction_fk ASC);
create index psp_financial_trans_state_fk5_p1 on pspadm.psp_financial_trans_state_p1 USING BTREE (company_fk ASC,financial_transaction_fk ASC);
create index psp_financial_trans_state_fk5_p10 on pspadm.psp_financial_trans_state_p10 USING BTREE (company_fk ASC,financial_transaction_fk ASC);
create index psp_financial_trans_state_fk5_p11 on pspadm.psp_financial_trans_state_p11 USING BTREE (company_fk ASC,financial_transaction_fk ASC);
create index psp_financial_trans_state_fk5_p12 on pspadm.psp_financial_trans_state_p12 USING BTREE (company_fk ASC,financial_transaction_fk ASC);
create index psp_financial_trans_state_fk5_p13 on pspadm.psp_financial_trans_state_p13 USING BTREE (company_fk ASC,financial_transaction_fk ASC);
create index psp_financial_trans_state_fk5_p14 on pspadm.psp_financial_trans_state_p14 USING BTREE (company_fk ASC,financial_transaction_fk ASC);
create index psp_financial_trans_state_fk5_p15 on pspadm.psp_financial_trans_state_p15 USING BTREE (company_fk ASC,financial_transaction_fk ASC);
create index psp_financial_trans_state_fk5_p2 on pspadm.psp_financial_trans_state_p2 USING BTREE (company_fk ASC,financial_transaction_fk ASC);
create index psp_financial_trans_state_fk5_p3 on pspadm.psp_financial_trans_state_p3 USING BTREE (company_fk ASC,financial_transaction_fk ASC);
create index psp_financial_trans_state_fk5_p4 on pspadm.psp_financial_trans_state_p4 USING BTREE (company_fk ASC,financial_transaction_fk ASC);
create index psp_financial_trans_state_fk5_p5 on pspadm.psp_financial_trans_state_p5 USING BTREE (company_fk ASC,financial_transaction_fk ASC);
create index psp_financial_trans_state_fk5_p6 on pspadm.psp_financial_trans_state_p6 USING BTREE (company_fk ASC,financial_transaction_fk ASC);
create index psp_financial_trans_state_fk5_p7 on pspadm.psp_financial_trans_state_p7 USING BTREE (company_fk ASC,financial_transaction_fk ASC);
create index psp_financial_trans_state_fk5_p8 on pspadm.psp_financial_trans_state_p8 USING BTREE (company_fk ASC,financial_transaction_fk ASC);
create index psp_financial_trans_state_fk5_p9 on pspadm.psp_financial_trans_state_p9 USING BTREE (company_fk ASC,financial_transaction_fk ASC);
create index psp_financial_trans_state_fk6_p0 on pspadm.psp_financial_trans_state_p0 USING BTREE (transaction_state_fk ASC);
create index psp_financial_trans_state_fk6_p1 on pspadm.psp_financial_trans_state_p1 USING BTREE (transaction_state_fk ASC);
create index psp_financial_trans_state_fk6_p10 on pspadm.psp_financial_trans_state_p10 USING BTREE (transaction_state_fk ASC);
create index psp_financial_trans_state_fk6_p11 on pspadm.psp_financial_trans_state_p11 USING BTREE (transaction_state_fk ASC);
create index psp_financial_trans_state_fk6_p12 on pspadm.psp_financial_trans_state_p12 USING BTREE (transaction_state_fk ASC);
create index psp_financial_trans_state_fk6_p13 on pspadm.psp_financial_trans_state_p13 USING BTREE (transaction_state_fk ASC);
create index psp_financial_trans_state_fk6_p14 on pspadm.psp_financial_trans_state_p14 USING BTREE (transaction_state_fk ASC);
create index psp_financial_trans_state_fk6_p15 on pspadm.psp_financial_trans_state_p15 USING BTREE (transaction_state_fk ASC);
create index psp_financial_trans_state_fk6_p2 on pspadm.psp_financial_trans_state_p2 USING BTREE (transaction_state_fk ASC);
create index psp_financial_trans_state_fk6_p3 on pspadm.psp_financial_trans_state_p3 USING BTREE (transaction_state_fk ASC);
create index psp_financial_trans_state_fk6_p4 on pspadm.psp_financial_trans_state_p4 USING BTREE (transaction_state_fk ASC);
create index psp_financial_trans_state_fk6_p5 on pspadm.psp_financial_trans_state_p5 USING BTREE (transaction_state_fk ASC);
create index psp_financial_trans_state_fk6_p6 on pspadm.psp_financial_trans_state_p6 USING BTREE (transaction_state_fk ASC);
create index psp_financial_trans_state_fk6_p7 on pspadm.psp_financial_trans_state_p7 USING BTREE (transaction_state_fk ASC);
create index psp_financial_trans_state_fk6_p8 on pspadm.psp_financial_trans_state_p8 USING BTREE (transaction_state_fk ASC);
create index psp_financial_trans_state_fk6_p9 on pspadm.psp_financial_trans_state_p9 USING BTREE (transaction_state_fk ASC);
create index psp_financial_trans_state_fk7_p0 on pspadm.psp_financial_trans_state_p0 USING BTREE (transaction_response_fk ASC);
create index psp_financial_trans_state_fk7_p1 on pspadm.psp_financial_trans_state_p1 USING BTREE (transaction_response_fk ASC);
create index psp_financial_trans_state_fk7_p10 on pspadm.psp_financial_trans_state_p10 USING BTREE (transaction_response_fk ASC);
create index psp_financial_trans_state_fk7_p11 on pspadm.psp_financial_trans_state_p11 USING BTREE (transaction_response_fk ASC);
create index psp_financial_trans_state_fk7_p12 on pspadm.psp_financial_trans_state_p12 USING BTREE (transaction_response_fk ASC);
create index psp_financial_trans_state_fk7_p13 on pspadm.psp_financial_trans_state_p13 USING BTREE (transaction_response_fk ASC);
create index psp_financial_trans_state_fk7_p14 on pspadm.psp_financial_trans_state_p14 USING BTREE (transaction_response_fk ASC);
create index psp_financial_trans_state_fk7_p15 on pspadm.psp_financial_trans_state_p15 USING BTREE (transaction_response_fk ASC);
create index psp_financial_trans_state_fk7_p2 on pspadm.psp_financial_trans_state_p2 USING BTREE (transaction_response_fk ASC);
create index psp_financial_trans_state_fk7_p3 on pspadm.psp_financial_trans_state_p3 USING BTREE (transaction_response_fk ASC);
create index psp_financial_trans_state_fk7_p4 on pspadm.psp_financial_trans_state_p4 USING BTREE (transaction_response_fk ASC);
create index psp_financial_trans_state_fk7_p5 on pspadm.psp_financial_trans_state_p5 USING BTREE (transaction_response_fk ASC);
create index psp_financial_trans_state_fk7_p6 on pspadm.psp_financial_trans_state_p6 USING BTREE (transaction_response_fk ASC);
create index psp_financial_trans_state_fk7_p7 on pspadm.psp_financial_trans_state_p7 USING BTREE (transaction_response_fk ASC);
create index psp_financial_trans_state_fk7_p8 on pspadm.psp_financial_trans_state_p8 USING BTREE (transaction_response_fk ASC);
create index psp_financial_trans_state_fk7_p9 on pspadm.psp_financial_trans_state_p9 USING BTREE (transaction_response_fk ASC);
create index psp_financial_trans_state_fk1_p0 on pspadm.psp_financial_trans_state_p0 USING BTREE (company_fk ASC,transaction_type_fk ASC,transaction_state_eff_date ASC);
create index psp_financial_trans_state_fk1_p1 on pspadm.psp_financial_trans_state_p1 USING BTREE (company_fk ASC,transaction_type_fk ASC,transaction_state_eff_date ASC);
create index psp_financial_trans_state_fk1_p10 on pspadm.psp_financial_trans_state_p10 USING BTREE (company_fk ASC,transaction_type_fk ASC,transaction_state_eff_date ASC);
create index psp_financial_trans_state_fk1_p11 on pspadm.psp_financial_trans_state_p11 USING BTREE (company_fk ASC,transaction_type_fk ASC,transaction_state_eff_date ASC);
create index psp_financial_trans_state_fk1_p12 on pspadm.psp_financial_trans_state_p12 USING BTREE (company_fk ASC,transaction_type_fk ASC,transaction_state_eff_date ASC);
create index psp_financial_trans_state_fk1_p13 on pspadm.psp_financial_trans_state_p13 USING BTREE (company_fk ASC,transaction_type_fk ASC,transaction_state_eff_date ASC);
create index psp_financial_trans_state_fk1_p14 on pspadm.psp_financial_trans_state_p14 USING BTREE (company_fk ASC,transaction_type_fk ASC,transaction_state_eff_date ASC);
create index psp_financial_trans_state_fk1_p15 on pspadm.psp_financial_trans_state_p15 USING BTREE (company_fk ASC,transaction_type_fk ASC,transaction_state_eff_date ASC);
create index psp_financial_trans_state_fk1_p2 on pspadm.psp_financial_trans_state_p2 USING BTREE (company_fk ASC,transaction_type_fk ASC,transaction_state_eff_date ASC);
create index psp_financial_trans_state_fk1_p3 on pspadm.psp_financial_trans_state_p3 USING BTREE (company_fk ASC,transaction_type_fk ASC,transaction_state_eff_date ASC);
create index psp_financial_trans_state_fk1_p4 on pspadm.psp_financial_trans_state_p4 USING BTREE (company_fk ASC,transaction_type_fk ASC,transaction_state_eff_date ASC);
create index psp_financial_trans_state_fk1_p5 on pspadm.psp_financial_trans_state_p5 USING BTREE (company_fk ASC,transaction_type_fk ASC,transaction_state_eff_date ASC);
create index psp_financial_trans_state_fk1_p6 on pspadm.psp_financial_trans_state_p6 USING BTREE (company_fk ASC,transaction_type_fk ASC,transaction_state_eff_date ASC);
create index psp_financial_trans_state_fk1_p7 on pspadm.psp_financial_trans_state_p7 USING BTREE (company_fk ASC,transaction_type_fk ASC,transaction_state_eff_date ASC);
create index psp_financial_trans_state_fk1_p8 on pspadm.psp_financial_trans_state_p8 USING BTREE (company_fk ASC,transaction_type_fk ASC,transaction_state_eff_date ASC);
create index psp_financial_trans_state_fk1_p9 on pspadm.psp_financial_trans_state_p9 USING BTREE (company_fk ASC,transaction_type_fk ASC,transaction_state_eff_date ASC);
create index psp_financial_trans_state_fk2_p0 on pspadm.psp_financial_trans_state_p0 USING BTREE (transaction_type_fk ASC,transaction_state_eff_date ASC);
create index psp_financial_trans_state_fk2_p1 on pspadm.psp_financial_trans_state_p1 USING BTREE (transaction_type_fk ASC,transaction_state_eff_date ASC);
create index psp_financial_trans_state_fk2_p10 on pspadm.psp_financial_trans_state_p10 USING BTREE (transaction_type_fk ASC,transaction_state_eff_date ASC);
create index psp_financial_trans_state_fk2_p11 on pspadm.psp_financial_trans_state_p11 USING BTREE (transaction_type_fk ASC,transaction_state_eff_date ASC);
create index psp_financial_trans_state_fk2_p12 on pspadm.psp_financial_trans_state_p12 USING BTREE (transaction_type_fk ASC,transaction_state_eff_date ASC);
create index psp_financial_trans_state_fk2_p13 on pspadm.psp_financial_trans_state_p13 USING BTREE (transaction_type_fk ASC,transaction_state_eff_date ASC);
create index psp_financial_trans_state_fk2_p14 on pspadm.psp_financial_trans_state_p14 USING BTREE (transaction_type_fk ASC,transaction_state_eff_date ASC);
create index psp_financial_trans_state_fk2_p15 on pspadm.psp_financial_trans_state_p15 USING BTREE (transaction_type_fk ASC,transaction_state_eff_date ASC);
create index psp_financial_trans_state_fk2_p2 on pspadm.psp_financial_trans_state_p2 USING BTREE (transaction_type_fk ASC,transaction_state_eff_date ASC);
create index psp_financial_trans_state_fk2_p3 on pspadm.psp_financial_trans_state_p3 USING BTREE (transaction_type_fk ASC,transaction_state_eff_date ASC);
create index psp_financial_trans_state_fk2_p4 on pspadm.psp_financial_trans_state_p4 USING BTREE (transaction_type_fk ASC,transaction_state_eff_date ASC);
create index psp_financial_trans_state_fk2_p5 on pspadm.psp_financial_trans_state_p5 USING BTREE (transaction_type_fk ASC,transaction_state_eff_date ASC);
create index psp_financial_trans_state_fk2_p6 on pspadm.psp_financial_trans_state_p6 USING BTREE (transaction_type_fk ASC,transaction_state_eff_date ASC);
create index psp_financial_trans_state_fk2_p7 on pspadm.psp_financial_trans_state_p7 USING BTREE (transaction_type_fk ASC,transaction_state_eff_date ASC);
create index psp_financial_trans_state_fk2_p8 on pspadm.psp_financial_trans_state_p8 USING BTREE (transaction_type_fk ASC,transaction_state_eff_date ASC);
create index psp_financial_trans_state_fk2_p9 on pspadm.psp_financial_trans_state_p9 USING BTREE (transaction_type_fk ASC,transaction_state_eff_date ASC);
select  'psp_financial_trans_state completed' as status;
SELECT CURRENT_TIMESTAMP;

