DROP TABLE IF EXISTS TMP_PSP_LAW CASCADE

;

--------------------------------------------------------
-- Create temp table                                  --
--------------------------------------------------------

CREATE TABLE TMP_PSP_LAW (LIKE PSP_LAW INCLUDING ALL)

;

--------------------------------------------------------
-- Insert into temp table                             --
--------------------------------------------------------

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'65', 'FUTA', 'FUTA - In state w. no SUI', 'IRS-940-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'66', 'FUTA', 'SUTA - In state w. SUI', 'IRS-940-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'1', 'FIT', 'Federal income tax withholding', 'IRS-941-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'61', 'FICA EE', 'FICA - Employee', 'IRS-941-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'62', 'FICA ER', 'FICA - Employer', 'IRS-941-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'63', 'Medicare EE', 'Medicare - Employee', 'IRS-941-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'64', 'Medicare ER', 'Medicare - Employer', 'IRS-941-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'143', 'AEIC', 'Advance Earned Income Credit', 'IRS-941-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'196', 'COBRA', 'COBRA Subsidy Credit', 'IRS-941-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'200', 'Medicare EE Addl Tax', 'Medicare Employee Addl Tax', 'IRS-941-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'214', 'NPL Credit', 'National Paid Leave Credit', 'IRS-941-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'215', 'CARES Credit', 'CARES Retention Credit', 'IRS-941-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'216', 'CARES FICA-ER Deferral', 'CARES FICA-Emplyr Deferral', 'IRS-941-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'217', 'FICA-EE Deferral', 'FICA-Employee Deferral', 'IRS-941-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'6', 'SIT', 'CA Personal Income Tax', 'CA-PITSDI-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'67', 'SDI EE', 'CA State Disability Insurance', 'CA-PITSDI-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'87', 'SUI', 'CA Unemployment Insurance', 'CA-UIETT-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'142', 'ETT', 'CA Employment Training Tax', 'CA-UIETT-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'92', 'SUI', 'FL Quarterly Unemployment Insurance Payment', 'FL-UCT6-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'16', 'SIT', 'IL Income Tax Withholding', 'IL-501-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'97', 'SUI', 'IL Unemployment Insurance (UI)', 'IL-UI340-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'40', 'SIT', 'PA Income Tax Withholding', 'PA-501-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'121', 'SUI', 'PA Unemployment Insurance (SUI)', 'PA-UC2-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'137', 'SUI EE', 'PA Unemployment Insurance - E (SUI)', 'PA-UC2-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'206', 'PaidLeaveER', 'WA Paid Family and Medical Leave (Company)', 'WA-PFML-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'207', 'PaidLeaveEE', 'WA Paid Family and Medical Leave (Employee)', 'WA-PFML-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'221', 'CaresEE', 'WA Cares Fund', 'WA-CARES-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'131', 'SUI', 'WA Unemployment Insurance', 'WA-F5208-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'164', 'Workforce Training Fund', 'WA Workforce Training Fund', 'WA-F5208-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'8', 'SIT', 'CT Income Tax Withholding', 'CT-CTWH-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'89', 'SUI', 'CT Unemployment Insurance', 'CT-2MAG-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'218', 'PaidLeaveEE', 'CT Paid Family and Medical Leave (Employee)', 'CT-PFML-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'127', 'SUI', 'TX Unemployment Insurance', 'TX-C3V-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'163', 'Smart Job Assessment', 'TX Smart Job Assessment', 'TX-C3V-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'103', 'SUI', 'MD Unemployment Insurance', 'MD-DLLR-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'22', 'SIT', 'MD Income Tax Withholding', 'MD-MW506-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'33', 'SIT', 'NJ Income Tax Withholding', 'NJ-NJ927PWH-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'69', 'SDI EE', 'NJ SDI - Employee', 'NJ-NJ927PUI-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'73', 'SDI ER', 'NJ SDI - Employer', 'NJ-NJ927PUI-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'114', 'SUI', 'NJ SUI - Employer', 'NJ-NJ927PUI-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'136', 'SUI EE', 'NJ SUI - Employee', 'NJ-NJ927PUI-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'168', 'Workforce Development Fund EE', 'NJ Workforce Development Fund - Employee', 'NJ-NJ927PUI-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'167', 'Workforce Development Fund', 'NJ Workforce Development Fund - Employer', 'NJ-NJ927PUI-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'170', 'Healthcare Subsidy Fund - Employee', 'NJ Healthcare Subsidy Fund - Employee', 'NJ-NJ927PUI-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'169', 'Healthcare Subsidy Fund - Employer', 'NJ Healthcare Subsidy Fund - Employer', 'NJ-NJ927PUI-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'171', 'Special Healthcare Contributions', 'NJ Special Healthcare Contributions', 'NJ-NJ927PUI-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'194', 'FLI', 'NJ Family Leave Insurance', 'NJ-NJ927PUI-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'132', 'SUI', 'WI Unemployment Insurance', 'WI-UCT101-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'51', 'SIT', 'WI Income Tax Withholding', 'WI-WT6-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'105', 'SUI', 'MI Unemployment Insurance', 'MI-UIA1020-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'201', 'Obligation Assessment', 'MI Obligation Assessment', 'MI-UIA1020-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'24', 'SIT', 'MI Income Tax Withholding', 'MI-MW106-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'83', 'SUI', 'AK Unemployment Insurance', 'AK-AKNS-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'135', 'SUI EE', 'AK Unemployment Insurance - Employee', 'AK-AKNS-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'84', 'SUI', 'AL Unemployment Insurance', 'AL-CR4UI-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'144', 'Employment Security Assessment', 'AL Employment Security Assessment', 'AL-CR4UI-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'3', 'SIT', 'AL Income Tax Withholding', 'AL-CR4WH-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'85', 'SUI', 'AR Unemployment Insurance', 'AR-209B-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'145', 'Stabilization Tax', 'AR Stabilization Tax', 'AR-209B-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'4', 'SIT', 'AR Income Tax Withholding', 'AR-941M-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'5', 'SIT', 'AZ Income Tax Withholding', 'AZ-A1-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'86', 'SUI', 'AZ Unemployment Insurance', 'AZ-UC018-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'179', 'JTT', 'AZ Job Training Tax', 'AZ-UC018-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'7', 'SIT', 'CO Personal Income Tax Withholding', 'CO-DR1094-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'88', 'SUI', 'CO Unemployment Insurance', 'CO-UITR1-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'153', 'Solvency Tax', 'CO Solvency Tax Surcharge', 'CO-UITR1-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'222', 'CO FAMLI ER', 'CO Paid Family and Medical Leave (Company)', 'CO-FAMLI-PAYMENT','Unused', 0)
;
INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'223', 'CO FAMLI EE', 'CO Paid Family and Medical Leave (Employee)', 'CO-FAMLI-PAYMENT','Unused', 0)
;
INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'9', 'SIT', 'DC Personal Income Tax Withholding', 'DC-FR900-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'90', 'SUI', 'DC Unemployment Insurance', 'DC-UC30-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'188', 'Administrative Funding Assessment', 'DC Administrative Funding Assessment', 'DC-UC30-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'208', 'PaidLeaveER', 'DC Paid Family Leave (Company)', 'DC-PFL-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'10', 'SIT', 'DE Income Tax Withholding', 'DE-DES-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'91', 'SUI', 'DE Unemployment Insurance', 'DE-UC8-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'12', 'SIT', 'GA Income Tax Withholding', 'GA-GAV-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'93', 'SUI', 'GA Unemployment Insurance', 'GA-DOL4-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'154', 'Administration Access', 'GA Administration Access', 'GA-DOL4-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'13', 'SIT', 'HI Income Tax Withholding', 'HI-VP1-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'94', 'SUI', 'HI Unemployment Insurance', 'HI-UCB6-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'155', 'Employment and Training Assessment', 'HI Employment and Training Assessment', 'HI-UCB6-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'14', 'SIT', 'IA Income Tax Withholding', 'IA-44105-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'95', 'SUI', 'IA Unemployment Insurance', 'IA-600103-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'156', 'Administrative Surcharge', 'IA Administrative Surcharge', 'IA-600103-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'186', 'Reserve Fund', 'IA Reserve Fund', 'IA-600103-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'15', 'SIT', 'ID Income Tax Withholding', 'ID-910-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'96', 'SUI', 'ID Unemployment Insurance (SUI)', 'ID-020-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'146', 'Workforce Development Fund', 'ID Workforce Development Fund', 'ID-020-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'17', 'SIT', 'IN Income Tax Withholding', 'IN-WH1-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'59', 'Counties', 'IN Indiana Counties', 'IN-WH1-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'98', 'SUI', 'IN Unemployment Insurance', 'IN-UC1-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'18', 'SIT', 'KS Income Tax Withholding', 'KS-KW5-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'99', 'SUI', 'KS Unemployment Insurance (SUI)', 'KS-KCNS100-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'19', 'SIT', 'KY Income Tax Withholding', 'KY-K1-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'100', 'SUI', 'KY Unemployment Insurance', 'KY-UI3-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'202', 'Surcharge', 'KY Surcharge', 'KY-UI3-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'20', 'SIT', 'LA Income Tax Withholding', 'LA-L1-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'101', 'SUI', 'LA Unemployment Insurance', 'LA-ES61-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'183', 'Social Charge Tax', 'LA Social Charge Tax', 'LA-ES61-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'21', 'SIT', 'MA Income Tax Withholding', 'MA-M941-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'209', 'MedicalLeaveER', 'MA Paid Medical Leave (Company)', 'MA-PFML-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'210', 'MedicalLeaveEE', 'MA Paid Medical Leave (Employee)', 'MA-PFML-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'211', 'FamilyLeaveER', 'MA Paid Family Leave (Company)', 'MA-PFML-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'212', 'FamilyLeaveEE', 'MA Paid Family Leave (Employee)', 'MA-PFML-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'102', 'SUI', 'MA Unemployment Insurance (SUI)', 'MA-1700HI-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'150', 'Workforce Training Fund', 'MA Workforce Training Fund', 'MA-1700HI-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'220', 'COVID-19 Assessment', 'MA COVID-19 Recovery Assessment', 'MA-1700HI-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'193', 'MA Health Insurance', 'MA Health Insurance', 'MA-1700HI-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'23', 'SIT', 'ME Income Tax Withholding', 'ME-900ME-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'104', 'SUI', 'ME Unemployment Insurance', 'ME-941C1ME-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'157', 'Surtax', 'ME Surtax', 'ME-941C1ME-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'189', 'Comp Skills Schlr Fund', 'ME Comp Skills Schlr Fund', 'ME-941C1ME-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'219', 'Unemp Prog Admin Fund', 'ME Unemp Prog Admin Fund', 'ME-941C1ME-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'25', 'SIT', 'MN Income Tax Withholding', 'MN-MW1-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'106', 'SUI', 'MN Unemployment Insurance', 'MN-DEED1-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'158', 'Dislocated Worker Assessment', 'MN Dislocated Worker Assessment', 'MN-DEED1-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'26', 'SIT', 'MO Income Tax Withholding', 'MO-941-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'107', 'SUI', 'MO Unemployment Insurance (SUI)', 'MO-MODES-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'195', 'MO Unemployment Automation Surcharge', 'MO Unemployment Automation Surcharge', 'MO-MODES-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'27', 'SIT', 'MS Income Tax Withholding', 'MS-M89-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'108', 'SUI', 'MS Unemployment Insurance (SUI)', 'MS-UI23-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'187', 'Training Contribution', 'MS Training Contribution', 'MS-UI23-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'28', 'SIT', 'MT Income Tax Withholding', 'MT-MW1-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'109', 'SUI', 'MT Unemployment Insurance (SUI)', 'MT-UI5-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'147', 'Administration Fund', 'MT Administration Fund', 'MT-UI5-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'29', 'SIT', 'NC Income Tax Withholding', 'NC-NC5P-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'110', 'SUI', 'NC Unemployment Insurance', 'NC-101-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'30', 'SIT', 'ND Income Tax Withholding', 'ND-306-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'111', 'SUI', 'ND Unemployment Insurance (SUI)', 'ND-SFN41263-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'31', 'SIT', 'NE Income Tax Withholding', 'NE-941N-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'112', 'SUI', 'NE Unemployment Insurance', 'NE-UI11T-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'148', 'SUIT Tax', 'NE SUIT Tax', 'NE-UI11T-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'213', 'UI Wage Base Increase', 'NE UI Wage Base Increase', 'NE-UI11T-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'113', 'SUI', 'NH Unemployment Insurance', 'NH-DES200-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'185', 'Administrative Contribution', 'NH Administrative Contribution', 'NH-DES200-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'115', 'SUI', 'NM Unemployment Insurance', 'NM-ES903A-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'190', 'NM Trust Fund', 'NM Trust Fund', 'NM-ES903A-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'34', 'SIT', 'NM Income Tax Withholding', 'NM-CRS1-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'191', 'WC Fee EE', 'NM Workers'' Compensation Fee - Employee', 'NM-WC1-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'192', 'WC Fee ER', 'NM Workers'' Compensation Fee - Employer', 'NM-WC1-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'116', 'SUI', 'NV Unemployment Insurance', 'NV-NUCS4072-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'159', 'CEP', 'NV Career Enhancement Program', 'NV-NUCS4072-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'36', 'SIT', 'NY Income Tax Withholding', 'NY-1MN-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'54', 'NYC Res', 'NYC Resident', 'NY-1MN-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'56', 'Yonkers Res', 'Yonkers Resident', 'NY-1MN-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'57', 'Yonkers NonRes', 'Yonkers Non-Resident', 'NY-1MN-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'197', 'Metro', 'NY - MCTMT (Transit Tax)', 'NY-MTA305-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'117', 'SUI', 'NY Unemployment Insurance', 'NY-45MN-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'152', 'Re-Employment Service Fund', 'NY Re-Employment Service Fund', 'NY-45MN-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'70', 'SDI EE', 'NY State Disability Insurance', 'NY-SDI-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'75', 'SDI ER', 'NY State Disability Insurance - E', 'NY-SDI-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'37', 'SIT', 'OH Income Tax Withholding', 'OH-IT501-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'60', 'School District', 'OH School District Tax', 'OH-SD101-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'118', 'SUI', 'OH Unemployment Insurance', 'OH-JFS20127-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'38', 'SIT', 'OK Income Tax Withholding', 'OK-OW9A-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'119', 'SUI', 'OK Unemployment Insurance', 'OK-OES3-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'39', 'SIT', 'OR Income Tax Withholding', 'OR-OTCWH-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'205', 'STT', 'OR Statewide Transit Tax', 'OR-STTV-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'172', 'TriMet', 'OR Transit District Taxes (Tri-Met)', 'OR-OTCUI-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'173', 'LTD', 'OR Transit District Taxes (LTD)', 'OR-OTCUI-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'174', 'Workers Assessment ER', 'OR Worker''s Assessment', 'OR-OTCUI-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'176', 'Workers Assessment EE', 'OR Worker''s Assessment (Emp)', 'OR-OTCUI-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'120', 'SUI', 'OR Unemployment Insurance', 'OR-OTCUI-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'175', 'Special Payroll Tax', 'OR Special Payroll Tax', 'OR-OTCUI-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'224', 'PaidLeaveER', 'OR Paid Leave (Company)', 'OR-PFMSL-PAYMENT','Unused', 0)
;
INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'225', 'PaidLeaveEE', 'OR Paid Leave (Employee)', 'OR-PFMSL-PAYMENT','Unused', 0)
;
INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'42', 'SIT', 'RI Income Tax Withholding', 'RI-941-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'123', 'SUI', 'RI Unemployment Insurance (SUI)', 'RI-TX17-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'72', 'SDI EE', 'RI State Disability Insurance', 'RI-TX17-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'160', 'JDF', 'RI Job Development Fund', 'RI-TX17-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'199', 'UI;JDF Wage Base Increase', 'RI UI;JDF Wage Base Increase', 'RI-TX17-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'43', 'SIT', 'SC Personal Income Tax Withholdings', 'SC-WH1601-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'124', 'SUI', 'SC Unemployment Insurance', 'SC-UCE120-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'161', 'Contingency Assessment', 'SC Contingency Assessment', 'SC-UCE120-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'125', 'SUI', 'SD Unemployment Insurance', 'SD-UID21-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'162', 'Investment Fee', 'SD Investment Fee', 'SD-UID21-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'198', 'SD Surcharge', 'SD Surcharge', 'SD-UID21-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'204', 'SD Administrative Fee', 'SD Administrative Fee', 'SD-UID21-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'126', 'SUI', 'TN Unemployment Insurance', 'TN-LB0456-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'151', 'Job Skills Fee', 'TN Job Skills Fee', 'TN-LB0456-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'128', 'SUI', 'UT Unemployment Insurance', 'UT-F3-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'47', 'SIT', 'UT Income Tax Withholding', 'UT-TC96-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'48', 'SIT', 'VA Income Tax Withholding', 'VA-VA15-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'129', 'SUI', 'VA Unemployment Insurance', 'VA-FC20-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'49', 'SIT', 'VT Income Tax Withholding', 'VT-WH433-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'130', 'SUI', 'VT Unemployment Insurance', 'VT-C101-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'52', 'SIT', 'WV Income Tax Withholding', 'WV-IT101-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'133', 'SUI', 'WV Unemployment Insurance (SUI)', 'WV-A154-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'134', 'SUI', 'WY Unemployment Insurance', 'WY-WYO056-PAYMENT','Unused', 0)
;

INSERT INTO TMP_PSP_LAW (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION) VALUES (
'184', 'Employment Support Fund', 'WY Employment Support Fund', 'WY-WYO056-PAYMENT','Unused', 0)
;



--------------------------------------------------------
-- Sychronize temp table and real table by            --
-- inserting, deleting, and updating as necessary     --
--------------------------------------------------------

INSERT INTO PSP_LAW
   (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION)
SELECT
    LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE, VERSION 
FROM
   TMP_PSP_LAW tt
WHERE
   tt.LAW_ID NOT IN (SELECT LAW_ID FROM PSP_LAW)

;

UPDATE PSP_LAW rt
SET (LAW_ID, LAW_ABBREV, DESCRIPTION, PAYMENT_TEMPLATE_FK, LAW_CATEGORY_CODE) =
(SELECT  tt.LAW_ID, tt.LAW_ABBREV, tt.DESCRIPTION, tt.PAYMENT_TEMPLATE_FK, tt.LAW_CATEGORY_CODE
 FROM TMP_PSP_LAW tt WHERE tt.LAW_ID = rt.LAW_ID)
 WHERE rt.LAW_ID IN (SELECT LAW_ID FROM TMP_PSP_LAW)
;



--------------------------------------------------------
-- Drop temp table                                  --
--------------------------------------------------------
DROP TABLE TMP_PSP_LAW

;
COMMIT