set echo on feedback on timing on
spool create_indexes_2
--  disable online index rebuild cleanup job
select owner, job_name, enabled, state, next_run_date from DBA_SCHEDULER_JOBS where job_name ='CLEANUP_ONLINE_IND_BUILD';
exec rdsadmin.rdsadmin_dbms_scheduler.disable('SYS.CLEANUP_ONLINE_IND_BUILD');
select owner, job_name, enabled, state, next_run_date from DBA_SCHEDULER_JOBS where job_name ='CLEANUP_ONLINE_IND_BUILD';

Prompt Index PSP_PSTUB_EMPLOYEE_INFO_FK3;
CREATE INDEX PSPADM.PSP_PSTUB_EMPLOYEE_INFO_FK3 ON PSPADM.PSP_PSTUB_EMPLOYEE_INFO (COMPANY_FK, REALM_ID) online parallel 8;
alter index PSPADM.PSP_PSTUB_EMPLOYEE_INFO_FK3 noparallel;

Prompt Index PSP_PAYCHECK_USAGE_HIST_FK3;
CREATE INDEX PSPADM.PSP_PAYCHECK_USAGE_HIST_FK3 ON PSPADM.PSP_PAYCHECK_USAGE_HIST (COMPANY_FK, REALM_ID) online parallel 8;
alter index PSPADM.PSP_PAYCHECK_USAGE_HIST_FK3 noparallel;

Prompt Index PSP_EFTPS_PAYMENT_DETAIL_FK5;
CREATE INDEX PSPADM.PSP_EFTPS_PAYMENT_DETAIL_FK5 ON PSPADM.PSP_EFTPS_PAYMENT_DETAIL (COMPANY_FK, REALM_ID) online parallel 8;
alter index PSPADM.PSP_EFTPS_PAYMENT_DETAIL_FK5 noparallel;

Prompt Index PSP_EDI_PAYMENT_DETAIL_FK4;
CREATE INDEX PSPADM.PSP_EDI_PAYMENT_DETAIL_FK4 ON PSPADM.PSP_EDI_PAYMENT_DETAIL (COMPANY_FK, REALM_ID) online parallel 8;
alter index PSPADM.PSP_EDI_PAYMENT_DETAIL_FK4 noparallel;

Prompt Index PSP_PAYSTUB_FK4;
CREATE INDEX PSPADM.PSP_PAYSTUB_FK4 ON PSPADM.PSP_PAYSTUB (COMPANY_FK, REALM_ID) online parallel 8;
alter index PSPADM.PSP_PAYSTUB_FK4 noparallel;

Prompt Index PSP_FSET_FILING_DETAIL_FK4;
CREATE INDEX PSPADM.PSP_FSET_FILING_DETAIL_FK4 ON PSPADM.PSP_FSET_FILING_DETAIL (COMPANY_FK, REALM_ID) online parallel 8;
alter index PSPADM.PSP_FSET_FILING_DETAIL_FK4 noparallel;

Prompt Index PSP_EVENT_AS400_SYNC_FK2;
CREATE INDEX PSPADM.PSP_EVENT_AS400_SYNC_FK2 ON PSPADM.PSP_EVENT_AS400_SYNC (COMPANY_FK, REALM_ID) online parallel 8;
alter index PSPADM.PSP_EVENT_AS400_SYNC_FK2 noparallel;

Prompt Index PSP_THIRD_PARTY401K_PAYCHE_FK2;
CREATE INDEX PSPADM.PSP_THIRD_PARTY401K_PAYCHE_FK2 ON PSPADM.PSP_TP401K_PAYCHECK (COMPANY_FK, REALM_ID) online parallel 8;
alter index PSPADM.PSP_THIRD_PARTY401K_PAYCHE_FK2 noparallel;

Prompt Index PSP_THIRD_PARTY401K_BATCH__FK3;
CREATE INDEX PSPADM.PSP_THIRD_PARTY401K_BATCH__FK3 ON PSPADM.PSP_TP401K_BATCH_PAYCHECK (COMPANY_FK, REALM_ID) online parallel 8;
alter index PSPADM.PSP_THIRD_PARTY401K_BATCH__FK3 noparallel;

Prompt Index PSP_TAX_PAYMENT_ON_HOLD_RE_FK2;
CREATE INDEX PSPADM.PSP_TAX_PAYMENT_ON_HOLD_RE_FK2 ON PSPADM.PSP_TAX_PAYMENT_ON_HOLD_REASON (COMPANY_FK, REALM_ID) online parallel 8;
alter index PSPADM.PSP_TAX_PAYMENT_ON_HOLD_RE_FK2 noparallel;

Prompt Index PSP_PAYMENT_BATCH_ASSOC_FK3;
CREATE INDEX PSPADM.PSP_PAYMENT_BATCH_ASSOC_FK3 ON PSPADM.PSP_PAYMENT_BATCH_ASSOC (COMPANY_FK, REALM_ID) online parallel 8;
alter index PSPADM.PSP_PAYMENT_BATCH_ASSOC_FK3 noparallel;

Prompt Index PSP_WORKERS_COMP_PAYCHECK_FK2;
CREATE INDEX PSPADM.PSP_WORKERS_COMP_PAYCHECK_FK2 ON PSPADM.PSP_WC_PAYCHECK (COMPANY_FK, REALM_ID) online parallel 8;
alter index PSPADM.PSP_WORKERS_COMP_PAYCHECK_FK2 noparallel;

Prompt Index PSP_VOIDED_CHECK_FK4;
CREATE INDEX PSPADM.PSP_VOIDED_CHECK_FK4 ON PSPADM.PSP_VOIDED_CHECK (COMPANY_FK, REALM_ID) online parallel 8;
alter index PSPADM.PSP_VOIDED_CHECK_FK4 noparallel;

Prompt Index PSP_TRANSACTION_OFFLOAD_BA_FK3;
CREATE INDEX PSPADM.PSP_TRANSACTION_OFFLOAD_BA_FK3 ON PSPADM.PSP_TRANSACTION_OFFLOAD_BATCH (COMPANY_FK, REALM_ID) online parallel 8;
alter index PSPADM.PSP_TRANSACTION_OFFLOAD_BA_FK3 noparallel;

--  enable online index rebuild cleanup job
select owner, job_name, enabled, state, next_run_date from DBA_SCHEDULER_JOBS where job_name ='CLEANUP_ONLINE_IND_BUILD';
exec rdsadmin.rdsadmin_dbms_scheduler.enable('SYS.CLEANUP_ONLINE_IND_BUILD');
select owner, job_name, enabled, state, next_run_date from DBA_SCHEDULER_JOBS where job_name ='CLEANUP_ONLINE_IND_BUILD';

spool off

