--------------------------------------------------------------------------
-- Play this script in PREVIOUS_PSP_LOCAL@XE to make it look like PSP_LOCAL@XE
--
-- Please review the script before using it to make sure it won't
-- cause any unacceptable data loss.
--
-- PREVIOUS_PSP_LOCAL@XE Schema Extracted by User PREVIOUS_PSP_LOCAL 
-- PSP_LOCAL@XE Schema Extracted by User PSP_LOCAL

set echo on feedback on timing on
spool create_fk_constraints

alter session set current_schema=pspadm;

ALTER TABLE PSP_PSTUB_EMPLOYEE_INFO
 ADD CONSTRAINT PSP_PSTUB_EMPLOYEE_INFO_FK3 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID) ENABLE NOVALIDATE;

ALTER TABLE PSP_COMPANY_EVENT_EMAIL
 ADD CONSTRAINT PSP_COMPANY_EVENT_EMAIL_FK2 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID) ENABLE NOVALIDATE;

ALTER TABLE PSP_PAYCHECK_USAGE_HIST
 ADD CONSTRAINT PSP_PAYCHECK_USAGE_HIST_FK3 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID) ENABLE NOVALIDATE;

ALTER TABLE PSP_TAX_PAYMENT_ON_HOLD_REASON
 ADD CONSTRAINT PSP_TAX_PAYMENT_ON_HOLD_RE_FK2 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID) ENABLE NOVALIDATE;

ALTER TABLE PSP_TP401K_BATCH_PAYCHECK
 ADD CONSTRAINT PSP_THIRD_PARTY401K_BATCH__FK3 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID) ENABLE NOVALIDATE;

ALTER TABLE PSP_TP401K_PAYCHECK
 ADD CONSTRAINT PSP_THIRD_PARTY401K_PAYCHE_FK2 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID) ENABLE NOVALIDATE;

ALTER TABLE PSP_EVENT_AS400_SYNC
 ADD CONSTRAINT PSP_EVENT_AS400_SYNC_FK2 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID) ENABLE NOVALIDATE;

ALTER TABLE PSP_FSET_FILING_DETAIL
 ADD CONSTRAINT PSP_FSET_FILING_DETAIL_FK4 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID) ENABLE NOVALIDATE;

ALTER TABLE PSP_EDI_PAYMENT_DETAIL
 ADD CONSTRAINT PSP_EDI_PAYMENT_DETAIL_FK4 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID) ENABLE NOVALIDATE;

ALTER TABLE PSP_EFTPS_PAYMENT_DETAIL
 ADD CONSTRAINT PSP_EFTPS_PAYMENT_DETAIL_FK5 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID) ENABLE NOVALIDATE;

ALTER TABLE PSP_PAYMENT_BATCH_ASSOC
 ADD CONSTRAINT PSP_PAYMENT_BATCH_ASSOC_FK3 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID) ENABLE NOVALIDATE;

ALTER TABLE PSP_PAYSTUB
 ADD CONSTRAINT PSP_PAYSTUB_FK4 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID) ENABLE NOVALIDATE;

ALTER TABLE PSP_VOIDED_CHECK
 ADD CONSTRAINT PSP_VOIDED_CHECK_FK4 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID) ENABLE NOVALIDATE;

ALTER TABLE PSP_WC_PAYCHECK
 ADD CONSTRAINT PSP_WORKERS_COMP_PAYCHECK_FK2 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID) ENABLE NOVALIDATE;

ALTER TABLE PSP_TRANSACTION_OFFLOAD_BATCH
 ADD CONSTRAINT PSP_TRANSACTION_OFFLOAD_BA_FK3 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID) ENABLE NOVALIDATE;

ALTER TABLE PSP_PSTUB_DDITEM
 ADD CONSTRAINT PSP_PSTUB_DDITEM_FK2 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID) ENABLE NOVALIDATE;

ALTER TABLE PSP_PSTUB_MSG
 ADD CONSTRAINT PSP_PSTUB_MSG_FK2 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID) ENABLE NOVALIDATE;

ALTER TABLE PSP_PSTUB_PAID_TIMEOFF_ITEM
 ADD CONSTRAINT PSP_PSTUB_PAID_TIMEOFF_ITE_FK2 
  FOREIGN KEY (COMPANY_FK, REALM_ID) 
  REFERENCES PSP_COMPANY (COMPANY_SEQ,REALM_ID) ENABLE NOVALIDATE;

PROMPT finished DBUpgrade_002.023.002.001.sql

spool off

