set echo on timing on feedback on
spool create_fk_constraints_CHG2103248_13Mar
--add FK constraint
ALTER TABLE PSPADM.PSP_PSTUB_EMPLOYEE_INFO ADD CONSTRAINT PSP_PSTUB_EMPLOYEE_INFO_FK3 FOREIGN KEY (COMPANY_FK, REALM_ID) REFERENCES PSPADM.PSP_COMPANY (COMPANY_SEQ,REALM_ID) ENABLE NOVALIDATE;
ALTER TABLE PSPADM.PSP_PSTUB_PAID_TIMEOFF_ITEM ADD CONSTRAINT PSP_PSTUB_PAID_TIMEOFF_ITE_FK2 FOREIGN KEY (COMPANY_FK, REALM_ID) REFERENCES PSPADM.PSP_COMPANY (COMPANY_SEQ,REALM_ID) ENABLE NOVALIDATE;
ALTER TABLE PSPADM.PSP_PSTUB_DDITEM ADD CONSTRAINT PSP_PSTUB_DDITEM_FK2 FOREIGN KEY (COMPANY_FK, REALM_ID) REFERENCES PSPADM.PSP_COMPANY (COMPANY_SEQ,REALM_ID) ENABLE NOVALIDATE;  
ALTER TABLE PSPADM.PSP_PSTUB_MSG ADD CONSTRAINT PSP_PSTUB_MSG_FK2 FOREIGN KEY (COMPANY_FK, REALM_ID) REFERENCES PSPADM.PSP_COMPANY (COMPANY_SEQ,REALM_ID) ENABLE NOVALIDATE;

spool off
