set echo on timing on feedback on
spool PROD_ENABLE_NOT_NULL_CONS_25MAR
ALTER TABLE PSPADM.PSP_DISBURSE_ADVICE_TAX_LIAB MODIFY company_fk NOT NULL ENABLE NOVALIDATE;
ALTER TABLE PSPADM.PSP_FSET_FILING_DETAIL MODIFY company_fk NOT NULL ENABLE NOVALIDATE;
ALTER TABLE PSPADM.PSP_COMPENSATION MODIFY company_fk NOT NULL ENABLE NOVALIDATE;
ALTER TABLE PSPADM.PSP_DEDUCTION MODIFY company_fk NOT NULL ENABLE NOVALIDATE;
ALTER TABLE PSPADM.PSP_EMPLOYER_CONTRIBUTION MODIFY company_fk NOT NULL ENABLE NOVALIDATE;
ALTER TABLE PSPADM.PSP_ENTRY_DETAIL_RECORD MODIFY company_fk NOT NULL ENABLE NOVALIDATE;
ALTER TABLE PSPADM.PSP_FINANCIAL_TRANS_STATE MODIFY company_fk NOT NULL ENABLE NOVALIDATE;
ALTER TABLE PSPADM.PSP_FINANCIAL_TRANSACTION MODIFY company_fk NOT NULL ENABLE NOVALIDATE;
ALTER TABLE PSPADM.PSP_MONEY_MOVEMENT_TRANSACTION MODIFY company_fk NOT NULL ENABLE NOVALIDATE;
ALTER TABLE PSPADM.PSP_PAYMENT_BATCH_ASSOC MODIFY company_fk NOT NULL ENABLE NOVALIDATE;
ALTER TABLE PSPADM.PSP_PROPERTY_AUDIT MODIFY company_fk NOT NULL ENABLE NOVALIDATE;
ALTER TABLE PSPADM.PSP_QBDT_PAYCHECK_INFO MODIFY company_fk NOT NULL ENABLE NOVALIDATE;
ALTER TABLE PSPADM.PSP_QBDT_PAYLINE_INFO MODIFY company_fk NOT NULL ENABLE NOVALIDATE;
ALTER TABLE PSPADM.PSP_QBDT_TRANSACTION_INFO MODIFY company_fk NOT NULL ENABLE NOVALIDATE;
ALTER TABLE PSPADM.PSP_TRANSACTION_RETURN MODIFY company_fk NOT NULL ENABLE NOVALIDATE;
ALTER TABLE PSPADM.PSP_ATFPAYMENTS_TO_PROCESS MODIFY company_fk NOT NULL ENABLE NOVALIDATE;
ALTER TABLE PSPADM.PSP_EDI_PAYMENT_DETAIL MODIFY company_fk NOT NULL ENABLE NOVALIDATE;
ALTER TABLE PSPADM.PSP_EFTPS_PAYMENT_DETAIL MODIFY company_fk NOT NULL ENABLE NOVALIDATE;
ALTER TABLE PSPADM.PSP_TAX MODIFY company_fk NOT NULL ENABLE NOVALIDATE;
ALTER TABLE PSPADM.PSP_TAX_PAYMENT_ON_HOLD_REASON MODIFY company_fk NOT NULL ENABLE NOVALIDATE;

spool off
