set echo on feedback on
spool PROD_ENABLE_NOT_NULL_CONS_03APR
ALTER TABLE PSPADM.PSP_COMPANY_EVENT_DETAIL MODIFY company_fk NOT NULL ENABLE NOVALIDATE;
ALTER TABLE PSPADM.PSP_COMPANY_EVENT_EMAIL MODIFY company_fk NOT NULL ENABLE NOVALIDATE;
ALTER TABLE PSPADM.PSP_COMPANY_EVENT_EMAIL_PARAM MODIFY company_fk NOT NULL ENABLE NOVALIDATE;
ALTER TABLE PSPADM.PSP_EVENT_AS400_SYNC MODIFY company_fk NOT NULL ENABLE NOVALIDATE;
ALTER TABLE PSPADM.PSP_FRAUD_EVENT MODIFY company_fk NOT NULL ENABLE NOVALIDATE;
spool off
