\timing
SELECT CURRENT_TIMESTAMP;
select 'creating index on psp_entitlement_message' as status ;
create index psp_entitlement_message_u1_2012 on psp_entitlement_message_2012  USING BTREE (token ASC);
create index psp_entitlement_message_u1_2013 on psp_entitlement_message_2013  USING BTREE (token ASC);
create index psp_entitlement_message_u1_2014 on psp_entitlement_message_2014  USING BTREE (token ASC);
create index psp_entitlement_message_u1_2015 on psp_entitlement_message_2015  USING BTREE (token ASC);
create index psp_entitlement_message_u1_2016 on psp_entitlement_message_2016  USING BTREE (token ASC);
create index psp_entitlement_message_u1_2017 on psp_entitlement_message_2017  USING BTREE (token ASC);
create index psp_entitlement_message_u1_2018 on psp_entitlement_message_2018  USING BTREE (token ASC);
create index psp_entitlement_message_u1_2019 on psp_entitlement_message_2019  USING BTREE (token ASC);
create index psp_entitlement_message_u1_2020 on psp_entitlement_message_2020  USING BTREE (token ASC);
create index psp_entitlement_message_u1_2021 on psp_entitlement_message_2021  USING BTREE (token ASC);
create index psp_entitlement_message_u1_2022 on psp_entitlement_message_2022  USING BTREE (token ASC);
create index psp_entitlement_message_u1_2023 on psp_entitlement_message_2023  USING BTREE (token ASC);
create index psp_entitlement_msg_lcno_eofcd_2012 on psp_entitlement_message_2012  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index psp_entitlement_msg_lcno_eofcd_2013 on psp_entitlement_message_2013  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index psp_entitlement_msg_lcno_eofcd_2014 on psp_entitlement_message_2014  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index psp_entitlement_msg_lcno_eofcd_2015 on psp_entitlement_message_2015  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index psp_entitlement_msg_lcno_eofcd_2016 on psp_entitlement_message_2016  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index psp_entitlement_msg_lcno_eofcd_2017 on psp_entitlement_message_2017  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index psp_entitlement_msg_lcno_eofcd_2018 on psp_entitlement_message_2018  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index psp_entitlement_msg_lcno_eofcd_2019 on psp_entitlement_message_2019  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index psp_entitlement_msg_lcno_eofcd_2020 on psp_entitlement_message_2020  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index psp_entitlement_msg_lcno_eofcd_2021 on psp_entitlement_message_2021  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index psp_entitlement_msg_lcno_eofcd_2022 on psp_entitlement_message_2022  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index psp_entitlement_msg_lcno_eofcd_2023 on psp_entitlement_message_2023  USING BTREE (license_number ASC,entitlement_offering_code ASC);
create index psp_entitlement_msg_msgts_er_2012 on psp_entitlement_message_2012  USING BTREE (message_timestamp ASC,event_reason ASC);
create index psp_entitlement_msg_msgts_er_2013 on psp_entitlement_message_2013  USING BTREE (message_timestamp ASC,event_reason ASC);
create index psp_entitlement_msg_msgts_er_2014 on psp_entitlement_message_2014  USING BTREE (message_timestamp ASC,event_reason ASC);
create index psp_entitlement_msg_msgts_er_2015 on psp_entitlement_message_2015  USING BTREE (message_timestamp ASC,event_reason ASC);
create index psp_entitlement_msg_msgts_er_2016 on psp_entitlement_message_2016  USING BTREE (message_timestamp ASC,event_reason ASC);
create index psp_entitlement_msg_msgts_er_2017 on psp_entitlement_message_2017  USING BTREE (message_timestamp ASC,event_reason ASC);
create index psp_entitlement_msg_msgts_er_2018 on psp_entitlement_message_2018  USING BTREE (message_timestamp ASC,event_reason ASC);
create index psp_entitlement_msg_msgts_er_2019 on psp_entitlement_message_2019  USING BTREE (message_timestamp ASC,event_reason ASC);
create index psp_entitlement_msg_msgts_er_2020 on psp_entitlement_message_2020  USING BTREE (message_timestamp ASC,event_reason ASC);
create index psp_entitlement_msg_msgts_er_2021 on psp_entitlement_message_2021  USING BTREE (message_timestamp ASC,event_reason ASC);
create index psp_entitlement_msg_msgts_er_2022 on psp_entitlement_message_2022  USING BTREE (message_timestamp ASC,event_reason ASC);
create index psp_entitlement_msg_msgts_er_2023 on psp_entitlement_message_2023  USING BTREE (message_timestamp ASC,event_reason ASC);
create index psp_entitlement_msg_orno_lcno_2012 on psp_entitlement_message_2012  USING BTREE (order_number ASC,license_number ASC);
create index psp_entitlement_msg_orno_lcno_2013 on psp_entitlement_message_2013  USING BTREE (order_number ASC,license_number ASC);
create index psp_entitlement_msg_orno_lcno_2014 on psp_entitlement_message_2014  USING BTREE (order_number ASC,license_number ASC);
create index psp_entitlement_msg_orno_lcno_2015 on psp_entitlement_message_2015  USING BTREE (order_number ASC,license_number ASC);
create index psp_entitlement_msg_orno_lcno_2016 on psp_entitlement_message_2016  USING BTREE (order_number ASC,license_number ASC);
create index psp_entitlement_msg_orno_lcno_2017 on psp_entitlement_message_2017  USING BTREE (order_number ASC,license_number ASC);
create index psp_entitlement_msg_orno_lcno_2018 on psp_entitlement_message_2018  USING BTREE (order_number ASC,license_number ASC);
create index psp_entitlement_msg_orno_lcno_2019 on psp_entitlement_message_2019  USING BTREE (order_number ASC,license_number ASC);
create index psp_entitlement_msg_orno_lcno_2020 on psp_entitlement_message_2020  USING BTREE (order_number ASC,license_number ASC);
create index psp_entitlement_msg_orno_lcno_2021 on psp_entitlement_message_2021  USING BTREE (order_number ASC,license_number ASC);
create index psp_entitlement_msg_orno_lcno_2022 on psp_entitlement_message_2022  USING BTREE (order_number ASC,license_number ASC);
create index psp_entitlement_msg_orno_lcno_2023 on psp_entitlement_message_2023  USING BTREE (order_number ASC,license_number ASC);
select  'psp_entitlement_message completed' as status;
SELECT CURRENT_TIMESTAMP;

select 'creating index on psp_paycheck_usage' as status;
create index psp_paycheck_usage_fk1_2012 on psp_paycheck_usage_2012  USING BTREE (company_fk ASC);
create index psp_paycheck_usage_fk1_2013 on psp_paycheck_usage_2013  USING BTREE (company_fk ASC);
create index psp_paycheck_usage_fk1_2014 on psp_paycheck_usage_2014  USING BTREE (company_fk ASC);
create index psp_paycheck_usage_fk1_2015 on psp_paycheck_usage_2015  USING BTREE (company_fk ASC);
create index psp_paycheck_usage_fk1_2016 on psp_paycheck_usage_2016  USING BTREE (company_fk ASC);
create index psp_paycheck_usage_fk1_2017 on psp_paycheck_usage_2017  USING BTREE (company_fk ASC);
create index psp_paycheck_usage_fk1_2018 on psp_paycheck_usage_2018  USING BTREE (company_fk ASC);
create index psp_paycheck_usage_fk1_2019 on psp_paycheck_usage_2019  USING BTREE (company_fk ASC);
create index psp_paycheck_usage_fk1_2020 on psp_paycheck_usage_2020  USING BTREE (company_fk ASC);
create index psp_paycheck_usage_fk1_2021 on psp_paycheck_usage_2021  USING BTREE (company_fk ASC);
create index psp_paycheck_usage_fk1_2022 on psp_paycheck_usage_2022  USING BTREE (company_fk ASC);
create index psp_paycheck_usage_fk1_2023 on psp_paycheck_usage_2023  USING BTREE (company_fk ASC);
create index psp_paycheck_usage_nu1_2012 on psp_paycheck_usage_2012  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_nu1_2013 on psp_paycheck_usage_2013  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_nu1_2014 on psp_paycheck_usage_2014  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_nu1_2015 on psp_paycheck_usage_2015  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_nu1_2016 on psp_paycheck_usage_2016  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_nu1_2017 on psp_paycheck_usage_2017  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_nu1_2018 on psp_paycheck_usage_2018  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_nu1_2019 on psp_paycheck_usage_2019  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_nu1_2020 on psp_paycheck_usage_2020  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_nu1_2021 on psp_paycheck_usage_2021  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_nu1_2022 on psp_paycheck_usage_2022  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_nu1_2023 on psp_paycheck_usage_2023  USING BTREE (source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2012 on psp_paycheck_usage_2012  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2013 on psp_paycheck_usage_2013  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2014 on psp_paycheck_usage_2014  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2015 on psp_paycheck_usage_2015  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2016 on psp_paycheck_usage_2016  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2017 on psp_paycheck_usage_2017  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2018 on psp_paycheck_usage_2018  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2019 on psp_paycheck_usage_2019  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2020 on psp_paycheck_usage_2020  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2021 on psp_paycheck_usage_2021  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2022 on psp_paycheck_usage_2022  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheck_usage_u1_2023 on psp_paycheck_usage_2023  USING BTREE (employee_usage_fk ASC,source_paycheck_id ASC);
create index psp_paycheckusage_fk1_2012 on psp_paycheck_usage_2012  USING BTREE (bill_fk ASC);
create index psp_paycheckusage_fk1_2013 on psp_paycheck_usage_2013  USING BTREE (bill_fk ASC);
create index psp_paycheckusage_fk1_2014 on psp_paycheck_usage_2014  USING BTREE (bill_fk ASC);
create index psp_paycheckusage_fk1_2015 on psp_paycheck_usage_2015  USING BTREE (bill_fk ASC);
create index psp_paycheckusage_fk1_2016 on psp_paycheck_usage_2016  USING BTREE (bill_fk ASC);
create index psp_paycheckusage_fk1_2017 on psp_paycheck_usage_2017  USING BTREE (bill_fk ASC);
create index psp_paycheckusage_fk1_2018 on psp_paycheck_usage_2018  USING BTREE (bill_fk ASC);
create index psp_paycheckusage_fk1_2019 on psp_paycheck_usage_2019  USING BTREE (bill_fk ASC);
create index psp_paycheckusage_fk1_2020 on psp_paycheck_usage_2020  USING BTREE (bill_fk ASC);
create index psp_paycheckusage_fk1_2021 on psp_paycheck_usage_2021  USING BTREE (bill_fk ASC);
create index psp_paycheckusage_fk1_2022 on psp_paycheck_usage_2022  USING BTREE (bill_fk ASC);
create index psp_paycheckusage_fk1_2023 on psp_paycheck_usage_2023  USING BTREE (bill_fk ASC);
create index psp_paycheckusage_fk2_2012 on psp_paycheck_usage_2012  USING BTREE (employee_usage_fk ASC);
create index psp_paycheckusage_fk2_2013 on psp_paycheck_usage_2013  USING BTREE (employee_usage_fk ASC);
create index psp_paycheckusage_fk2_2014 on psp_paycheck_usage_2014  USING BTREE (employee_usage_fk ASC);
create index psp_paycheckusage_fk2_2015 on psp_paycheck_usage_2015  USING BTREE (employee_usage_fk ASC);
create index psp_paycheckusage_fk2_2016 on psp_paycheck_usage_2016  USING BTREE (employee_usage_fk ASC);
create index psp_paycheckusage_fk2_2017 on psp_paycheck_usage_2017  USING BTREE (employee_usage_fk ASC);
create index psp_paycheckusage_fk2_2018 on psp_paycheck_usage_2018  USING BTREE (employee_usage_fk ASC);
create index psp_paycheckusage_fk2_2019 on psp_paycheck_usage_2019  USING BTREE (employee_usage_fk ASC);
create index psp_paycheckusage_fk2_2020 on psp_paycheck_usage_2020  USING BTREE (employee_usage_fk ASC);
create index psp_paycheckusage_fk2_2021 on psp_paycheck_usage_2021  USING BTREE (employee_usage_fk ASC);
create index psp_paycheckusage_fk2_2022 on psp_paycheck_usage_2022  USING BTREE (employee_usage_fk ASC);
create index psp_paycheckusage_fk2_2023 on psp_paycheck_usage_2023  USING BTREE (employee_usage_fk ASC);
select  'psp_paycheck_usage completed'  as status;
SELECT CURRENT_TIMESTAMP;

select 'creating index on psp_entity_update' as status;
create index idx_entityupdate_crdate_m011950 on psp_entity_update_m011950 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m112022 on psp_entity_update_m112022 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m122022 on psp_entity_update_m122022 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m012023 on psp_entity_update_m012023 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m022023 on psp_entity_update_m022023 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m032023 on psp_entity_update_m032023 USING BTREE (created_date ASC);
create index idx_entityupdate_crdate_m042023 on psp_entity_update_m042023 USING BTREE (created_date ASC);
select  'psp_entity_update completed' as status;
SELECT CURRENT_TIMESTAMP;