spool create_tablespaces
set echo on
set feed on
set time on
set timi on

CREATE TABLESPACE PSP_DATA02 DATAFILE SIZE 50G AUTOEXTEND ON NEXT 10G MAXSIZE UNLIMITED;

CREATE TABLESPACE PSP_IDX02 DATAFILE SIZE 50G AUTOEXTEND ON NEXT 10G MAXSIZE UNLIMITED;

spool off
exit

